// Profiles for the "Thoughts" section: who each thinker was, their main ideas, principles to live by
// and interesting facts. Written for MindArchive. Ancient sources are often late or legendary, so
// claims that rest on tradition are worded that way ("tradition says", "according to…").
// `slug` matches the thinker's slug in the archive, so profiles link to their quotes.

export type Tradition = 'Presocratic' | 'Classical Greek' | 'Hellenistic' | 'Roman' | 'Eastern'

export interface Idea {
  title: string
  text: string
}

export interface Profile {
  slug: string
  /** Sort key: approximate year of birth (negative = BC) */
  order: number
  dates: string
  place: string
  tradition: Tradition
  tagline: string
  who: string[]
  ideas: Idea[]
  principles: string[]
  facts: string[]
  legacy: string
}

export const TRADITIONS: Tradition[] = ['Presocratic', 'Classical Greek', 'Hellenistic', 'Roman', 'Eastern']

export const ANCIENT: Profile[] = [
  {
    slug: 'thales',
    order: -624,
    dates: 'c. 624 – c. 546 BC',
    place: 'Miletus, Ionia (now western Turkey)',
    tradition: 'Presocratic',
    tagline: 'The first thinker on record to ask what the world is made of, and to answer without turning to the gods.',
    who: [
      'Thales lived in Miletus, a busy trading city on the coast of Ionia. Later Greeks counted him among the Seven Sages, and Aristotle named him the founder of natural philosophy. Nothing he wrote survives, so what we know comes from later writers such as Herodotus, Aristotle and Diogenes Laertius.',
      'What made him new was a habit of mind. Instead of explaining earthquakes, storms and the origin of the world through the moods of gods, he looked for natural causes that anyone could examine and argue about.',
    ],
    ideas: [
      { title: 'Water is the source of everything', text: 'Thales proposed that all things come from water and are in some sense still water. Whether or not he was right, he is the first on record to look for one underlying material behind the variety of the world.' },
      { title: 'Nature explains nature', text: 'Earthquakes, he is said to have argued, happen because the Earth floats on water and is rocked by it. The details are wrong, but the method, a natural explanation that can be criticised, became the seed of science.' },
      { title: 'Geometry as a tool', text: 'Tradition credits him with proving simple facts, such as that a circle is cut in half by its diameter, and with measuring the height of a pyramid from the length of its shadow.' },
      { title: 'A world alive with power', text: 'Aristotle reports that Thales thought magnets and amber have a kind of soul because they move other things. Life and motion, he felt, are everywhere in nature.' },
    ],
    principles: [
      'Ask what something is made of before asking which god is angry.',
      'Test explanations against what you can observe.',
      'Begin with honest self-knowledge. Ancient writers credit the maxim “know thyself” to several of the Seven Sages, Thales among them.',
    ],
    facts: [
      'Herodotus says Thales predicted a solar eclipse. Many historians date it to 585 BC, though how he could have done so is still debated.',
      'Plato tells a story that Thales fell into a well while watching the stars, and a servant girl laughed that he was so eager to know the heavens that he missed what was at his feet.',
      'Aristotle tells the opposite story: Thales used his knowledge of the weather to predict a huge olive harvest, rented all the olive presses cheaply, and made a fortune, to show that philosophers could be rich if they wished.',
      'He is said to have travelled to Egypt, where he learned geometry.',
    ],
    legacy: 'His followers Anaximander and Anaximenes continued the Milesian school. The belief that the world can be understood by reason is the starting point of Western philosophy and science.',
  },
  {
    slug: 'pythagoras',
    order: -570,
    dates: 'c. 570 – c. 495 BC',
    place: 'Samos, then Croton in southern Italy',
    tradition: 'Presocratic',
    tagline: 'A teacher who heard music in numbers and taught that the soul travels from life to life.',
    who: [
      'Pythagoras was born on the island of Samos and, according to tradition, travelled widely before settling in Croton, a Greek city in southern Italy, around 530 BC. There he founded a community that was part school and part religious brotherhood, with strict rules of life.',
      'He wrote nothing, and his followers kept their teachings secret and credited later discoveries to him, so it is hard to separate the man from the legend. What is clear is the lasting force of the idea that mathematics holds the key to the order of the world.',
    ],
    ideas: [
      { title: 'Number is the order behind nature', text: 'The Pythagoreans held that the world is ordered by number and proportion. They noticed that musical harmonies match simple ratios of string lengths, such as 2:1 for the octave, and concluded that harmony rules the cosmos.' },
      { title: 'The soul is immortal and reborn', text: 'He taught that the soul is immortal and passes from one body to another (metempsychosis). This belief shaped how the Pythagoreans treated animals and each other.' },
      { title: 'Philosophy as a way of life', text: 'Membership meant purification, self-discipline, shared property and, for new students, years of silence. Philosophy was something you practised, not only discussed.' },
      { title: 'An ordered, beautiful universe', text: 'The Greek word kosmos, meaning both order and ornament, is traditionally credited to Pythagoras or his school.' },
    ],
    principles: [
      'Look for the pattern behind things.',
      'Harmony in music, in the soul and in the city comes from the right proportion.',
      'Examine your day each evening, a practice later writers attribute to the Pythagoreans.',
    ],
    facts: [
      'The theorem that bears his name was known to Babylonian mathematicians more than a thousand years earlier. The Pythagoreans may have been among the first Greeks to prove it, but we cannot be sure.',
      'According to tradition he was the first to call himself a “philosopher”, a lover of wisdom, rather than a wise man.',
      'Followers were reportedly forbidden to eat beans. Ancient writers disagree about why.',
      'Women were admitted to the community. Theano, traditionally his wife or pupil, is the best known.',
    ],
    legacy: 'Plato drew deeply on Pythagorean ideas about number and the soul, and the belief that mathematics describes reality runs through Western science to this day.',
  },
  {
    slug: 'heraclitus',
    order: -535,
    dates: 'c. 535 – c. 475 BC',
    place: 'Ephesus, Ionia (now western Turkey)',
    tradition: 'Presocratic',
    tagline: 'The philosopher of change: the river is never the same, and yet it is still the river.',
    who: [
      'Heraclitus lived in Ephesus, a wealthy Greek city in Ionia. He came from a leading family, yet by later accounts he gave up a public role and withdrew from public life. Ancient writers nicknamed him “the Obscure” because his short, riddling sayings are hard to read.',
      'He wrote a single book, now lost except for about 130 fragments quoted by other authors. In them he is proud, blunt and often scornful of how little most people understand.',
    ],
    ideas: [
      { title: 'Everything changes', text: 'The world is in constant flux. The famous river saying, in its closest surviving form, says that different waters flow on those who step into the same river. The river stays “the same” only because it keeps changing.' },
      { title: 'The unity of opposites', text: 'Day and night, war and peace, hot and cold depend on each other. The tension between opposites, he said, holds the world together, like the pull of a bow or a lyre.' },
      { title: 'The Logos', text: 'Beneath all change lies a rational order he called the Logos, a shared principle that governs everything and that most people fail to notice even though it is all around them.' },
      { title: 'Fire as the pattern of change', text: 'For him fire, always consuming and shining, was the image of the world: a measured process of exchange rather than a fixed thing.' },
    ],
    principles: [
      'Expect change and do not cling.',
      'Wake up: pay attention to what is shared and real, not only to your private opinions.',
      'Look for the harmony that holds opposites together.',
    ],
    facts: [
      'The phrase “panta rhei” (“everything flows”) is a later summary, not a quotation from his surviving fragments.',
      'Later writers called him “the weeping philosopher”, as a pair to Democritus the laughing one. This is a late literary invention.',
      'Tradition says he placed his book in the temple of Artemis at Ephesus, one of the Seven Wonders of the ancient world.',
      'Hegel said that there was no sentence of Heraclitus he had not taken into his own Logic.',
    ],
    legacy: 'Plato, the Stoics and Hegel all drew on his ideas of constant change and a hidden rational order.',
  },
  {
    slug: 'parmenides',
    order: -515,
    dates: 'c. 515 – c. 450 BC',
    place: 'Elea, southern Italy',
    tradition: 'Presocratic',
    tagline: 'He argued that reality is one and unchanging, and that change is an illusion.',
    who: [
      'Parmenides lived in Elea, a Greek colony on the coast of southern Italy. He wrote one work, a poem in verse, in which a goddess reveals the truth to a young man carried to her house in a chariot.',
      'The poem has two parts: “The Way of Truth”, a bold argument about what must be, and “The Way of Opinion”, a description of the world as it seems to ordinary mortals. Plato admired him enough to name a dialogue after him and to call him “venerable and awesome”.',
    ],
    ideas: [
      { title: '“What is, is; what is not, is not”', text: 'From this plain-sounding premise Parmenides argued that you cannot think or speak about what does not exist. So there can be no empty space, no coming into being from nothing, and no passing away into nothing.' },
      { title: 'Change and plurality are illusions', text: 'If nothing can come from nothing, real being cannot begin, end, move or divide. The world of many shifting things that our senses show us is, he claimed, mere appearance.' },
      { title: 'Trust reason over the senses', text: 'The senses deceive us, and only reasoning can reach the truth about what really is. This is the first great defence of rationalism.' },
      { title: 'A challenge to everyone after him', text: 'Atomists, Plato and Aristotle each built their systems partly to answer him. They had to explain how change is possible when his argument seems so hard to refute.' },
    ],
    principles: [
      'Follow an argument where it leads, even when it clashes with common sense.',
      'Do not trust appearances alone.',
      'Be careful with words: ask whether the things you talk about can really be.',
    ],
    facts: [
      'His student Zeno of Elea devised famous paradoxes, such as Achilles and the tortoise, to defend the claim that motion is impossible.',
      'Plato’s dialogue Parmenides imagines a young Socrates meeting the old Parmenides. Whether the meeting really happened is doubtful.',
      'Only about 150 lines of his poem survive.',
      'Ancient sources say he wrote laws for his home city of Elea.',
    ],
    legacy: 'Western metaphysics begins as a series of replies to Parmenides. His insistence that logic can overrule appearances shaped Plato, Aristotle and the later rationalists.',
  },
  {
    slug: 'democritus',
    order: -460,
    dates: 'c. 460 – c. 370 BC',
    place: 'Abdera, Thrace (northern Greece)',
    tradition: 'Presocratic',
    tagline: 'The “laughing philosopher” who said the world is made of atoms and empty space.',
    who: [
      'Democritus was born in Abdera, a Greek city on the coast of Thrace. He developed the atomic theory begun by his teacher Leucippus. Ancient writers list dozens of his works on physics, ethics, mathematics and music, but almost all are lost.',
      'According to later writers he travelled widely and lived modestly, spending his inheritance on his studies.',
    ],
    ideas: [
      { title: 'Atoms and void', text: 'Everything is made of tiny, indivisible, eternal particles moving in empty space. The differences between things come from the shape, arrangement and position of their atoms.' },
      { title: 'Qualities are conventions', text: 'He summed it up: by convention there is sweet and bitter, hot and cold, colour; in truth there are only atoms and void. How things taste or feel is how atoms affect us, not a property of the atoms themselves.' },
      { title: 'A world without a designer', text: 'The cosmos arises from the motion and collision of atoms, with no plan and no divine craftsman. Countless other worlds may exist.' },
      { title: 'Cheerfulness as the goal', text: 'The aim of life is euthymia, a calm and cheerful state of mind that comes from moderation, not from excess pleasure or wealth.' },
    ],
    principles: [
      'Seek contentment through moderation.',
      'Do not only refrain from wrongdoing, but do not even desire it.',
      'Respect yourself more than the opinion of others.',
    ],
    facts: [
      'The word “atom” comes from the Greek atomos, “uncuttable”.',
      'Later tradition made him the “laughing philosopher” who found human folly funny, a pair to weeping Heraclitus.',
      'One ancient story says Plato wished to burn all of Democritus’s books. It is an anecdote, not a proven fact.',
      'Modern atomic theory is very different from his, but his idea that matter is made of tiny particles is why he is called a forerunner.',
    ],
    legacy: 'Epicurus adopted his atomism, and Lucretius later turned it into a famous poem. The idea resurfaced in the scientific revolution of the 17th century.',
  },
  {
    slug: 'socrates',
    order: -470,
    dates: 'c. 470 – 399 BC',
    place: 'Athens',
    tradition: 'Classical Greek',
    tagline: 'He wrote nothing, questioned everyone, and died for a life of inquiry.',
    who: [
      'Socrates was born in Athens, the son of a stonemason and a midwife. He served as a soldier in the Peloponnesian War, then spent most of his life in the city’s streets and marketplace, questioning anyone who would talk: politicians, poets, craftsmen and young men.',
      'He never wrote a book. We know him through Plato and Xenophon, who knew him personally, and through the comic playwright Aristophanes, who mocked him. In 399 BC an Athenian jury condemned him to death on charges of impiety and corrupting the young. He refused to flee and drank the hemlock.',
    ],
    ideas: [
      { title: 'The examined life', text: 'In Plato’s Apology he says that the unexamined life is not worth living for a human being. A good life needs constant, honest questioning of how we live and what we believe.' },
      { title: 'Knowing what you do not know', text: 'The oracle at Delphi was said to have called him the wisest of men. He concluded that his wisdom lay only in not thinking he knew what he did not know.' },
      { title: 'Virtue is knowledge', text: 'If people truly knew what is good, Socrates argued, they would do it. Wrongdoing comes from ignorance, so no one does wrong willingly.' },
      { title: 'The Socratic method', text: 'He taught by asking questions, testing definitions until the speaker saw the gaps in their thinking. The aim was to reach better understanding together, not to win.' },
      { title: 'Care of the soul', text: 'What matters most is not wealth, reputation or power but the state of your soul: justice, courage and wisdom.' },
    ],
    principles: [
      'Question your assumptions, especially the comfortable ones.',
      'Be willing to say “I do not know”.',
      'It is better to suffer injustice than to commit it.',
      'Stay true to your convictions, even under pressure.',
    ],
    facts: [
      'The oracle story comes from his friend Chaerephon, who asked at Delphi whether anyone was wiser than Socrates.',
      'He fought as a heavy infantryman at Potidaea, Delium and Amphipolis, and in Plato’s Symposium he is remembered for his endurance, even going barefoot in the winter cold.',
      'He called himself a gadfly sent to the sleepy city of Athens, like a fly that stings a large, lazy horse into action.',
      'His wife Xanthippe has a reputation as bad-tempered, but that comes from later anecdotes.',
      'In Plato’s Crito, his friends offer him an escape from prison, and he refuses, arguing that he owes obedience to the laws of the city that raised him.',
    ],
    legacy: 'Plato, Aristotle, the Cynics and the Stoics all claimed him as their ancestor. Socratic questioning is still used in teaching, law and therapy.',
  },
  {
    slug: 'plato',
    order: -428,
    dates: 'c. 428 – 348 BC',
    place: 'Athens',
    tradition: 'Classical Greek',
    tagline: 'Student of Socrates, founder of the Academy, and author of the dialogues that shaped Western thought.',
    who: [
      'Plato was born into a leading Athenian family. As a young man he followed Socrates, and after Socrates’s execution in 399 BC he travelled, including to Sicily. Around 387 BC he returned to found the Academy, a school in a grove outside Athens that lasted for centuries.',
      'He wrote some thirty dialogues, conversations in which Socrates and others examine justice, love, knowledge and the best form of government. Unlike Socrates, Plato left a large body of writing, almost all of it preserved.',
    ],
    ideas: [
      { title: 'The Theory of Forms', text: 'Beyond the changing things we see exist eternal, perfect Forms, such as Beauty, Justice and the Good, of which the physical world is an imperfect copy. True knowledge is knowledge of the Forms.' },
      { title: 'The Allegory of the Cave', text: 'In the Republic, prisoners in a cave take shadows on a wall for reality. The philosopher escapes, sees the sun and returns to help the others. Education means turning the soul towards the truth.' },
      { title: 'The three parts of the soul', text: 'Reason, spirit and appetite. A just person is one in whom reason rules, and a just city is one ruled by wisdom.' },
      { title: 'Philosopher-rulers', text: 'Plato argued that the ideal city would be ruled by those who love wisdom and understand the good, not by those who merely seek power.' },
      { title: 'Love as a ladder', text: 'In the Symposium, love begins with attraction to a beautiful body and can rise step by step to the love of beauty itself.' },
    ],
    principles: [
      'Look beyond appearances to what is real.',
      'Education is turning the soul towards the truth, not pouring facts into an empty vessel.',
      'Learn to rule yourself with reason before trying to rule others.',
      'A good question is worth more than a quick answer.',
    ],
    facts: [
      'Ancient tradition says his birth name was Aristocles and that “Plato” is a nickname, perhaps from the Greek platus, “broad”.',
      'The Academy, founded about 387 BC, gave us the word “academy”. Aristotle studied there for about twenty years.',
      'The mathematician Alfred North Whitehead wrote that the safest general description of European philosophy is that it consists of a series of footnotes to Plato.',
      'He made trips to Sicily to advise the rulers of Syracuse, with little success. Tradition says that at one point he was even sold into slavery.',
      'Atlantis first appears in two of his dialogues, Timaeus and Critias.',
    ],
    legacy: 'Plato’s ideas shaped Aristotle, the Neoplatonists, early Christian thought, Islamic philosophy and the Renaissance. Almost every later philosopher answers him.',
  },
  {
    slug: 'aristotle',
    order: -384,
    dates: '384 – 322 BC',
    place: 'Stagira, then Athens',
    tradition: 'Classical Greek',
    tagline: 'The great organiser of knowledge: logic, ethics, biology, politics and more.',
    who: [
      'Aristotle was born in Stagira in northern Greece, the son of a court physician. At seventeen he joined Plato’s Academy in Athens and stayed about twenty years. He later tutored the young Alexander the Great, and in 335 BC he opened his own school, the Lyceum.',
      'His surviving works, mostly lecture notes, cover logic, physics, biology, ethics, politics, poetry and rhetoric. For many centuries he was simply called “the Philosopher”.',
    ],
    ideas: [
      { title: 'The first logic', text: 'He created the first formal system of logic, built on the syllogism: all humans are mortal; Socrates is human; so Socrates is mortal. It dominated reasoning for over two thousand years.' },
      { title: 'Happiness as flourishing', text: 'In the Nicomachean Ethics the highest good is eudaimonia, a flourishing life in which we use our distinctive human capacity, reason, well over a whole lifetime.' },
      { title: 'Virtue is a habit and a mean', text: 'Courage, generosity and the other virtues are habits built by practice, and each lies between two extremes: courage between cowardice and recklessness.' },
      { title: 'Humans are political animals', text: 'We reach our full nature only in communities, in cities that aim at the good life.' },
      { title: 'Study nature by observing it', text: 'Where Plato looked to the Forms, Aristotle looked closely at living things. He gathered observations on hundreds of animal species and founded biology as a science.' },
    ],
    principles: [
      'We are what we repeatedly do: build good habits.',
      'Look for the mean between too much and too little.',
      'Start from what can be observed and what is widely accepted.',
      'Friendship and community are part of a good life.',
    ],
    facts: [
      '“Peripatetic”, meaning “walking about”, names his school. It is said to come from his habit of teaching while strolling in the Lyceum’s covered walk.',
      'When anti-Macedonian feeling rose in Athens after Alexander’s death in 323 BC, he left the city, reportedly so that Athens would not “sin twice against philosophy”. He died the next year at Chalcis.',
      'He studied marine life on the island of Lesbos and described how the dogfish shark develops, a detail doubted until it was confirmed in the 19th century.',
      'The Islamic philosopher Averroes wrote commentaries on nearly all his works, which helped bring Aristotle back to medieval Europe.',
    ],
    legacy: 'Medieval Christian, Jewish and Islamic thinkers built on Aristotle, and his logic and biology shaped science until the 17th century.',
  },
  {
    slug: 'diogenes-of-sinope',
    order: -412,
    dates: 'c. 412 – c. 323 BC',
    place: 'Sinope on the Black Sea, then Athens and Corinth',
    tradition: 'Classical Greek',
    tagline: 'The philosopher who lived in a jar and told a king to get out of his sunlight.',
    who: [
      'Diogenes was born in Sinope, a Greek city on the Black Sea. He was banished from it, according to one tradition for defacing the currency, and moved to Athens, where he became the best-known figure of the Cynic school. The Cynics taught that virtue means living simply and in accordance with nature.',
      'He lived in the open, owned almost nothing, and used public behaviour and sharp humour to show how much of social convention is empty. What we know about him comes from anecdotes recorded long after his death.',
    ],
    ideas: [
      { title: 'Live according to nature', text: 'Happiness requires needing little. Nature provides enough for a simple life, while luxury and status only create anxiety.' },
      { title: 'Self-sufficiency', text: 'Freedom comes from not depending on possessions, praise or the opinions of others.' },
      { title: '“Deface the currency”', text: 'He took the story of his exile as a motto: challenge accepted values and conventions, and question what society treats as valuable.' },
      { title: 'A citizen of the world', text: 'Asked where he came from, he is said to have answered that he was a kosmopolites, a citizen of the world, not of any one city.' },
    ],
    principles: [
      'Want less, and you will need less.',
      'Be honest, even when it is uncomfortable.',
      'Practise hardship in advance so that fortune cannot shake you.',
      'Judge by nature and reason, not by custom.',
    ],
    facts: [
      'He is said to have lived in a large storage jar (a pithos) in the Athenian marketplace.',
      'When Alexander the Great found him sunbathing and offered him anything he wished, Diogenes replied, “Stand out of my sun.” Alexander reportedly said that if he were not Alexander, he would wish to be Diogenes.',
      'He is said to have walked in daylight carrying a lamp, saying he was looking for an honest human being.',
      '“Cynic” comes from the Greek kynikos, “dog-like”. Diogenes accepted the nickname “the Dog”.',
      'Tradition says he died in 323 BC, the same year as Alexander the Great.',
    ],
    legacy: 'The Stoics, who began with Zeno, a student of the Cynic Crates, took over much of the Cynic ideal of independence from fortune.',
  },
  {
    slug: 'epicurus',
    order: -341,
    dates: '341 – 270 BC',
    place: 'Samos, then Athens',
    tradition: 'Hellenistic',
    tagline: 'He taught that a good life means simple pleasures, friendship and freedom from fear.',
    who: [
      'Epicurus was born on the island of Samos and taught in several cities before buying a house with a garden in Athens around 306 BC. “The Garden” became a community of friends, open to women and slaves, who lived modestly and studied together.',
      'He is said to have written about 300 scrolls. Only three letters and a few collections of sayings survive in full, along with fragments, and the Roman poet Lucretius later set out his ideas in verse.',
    ],
    ideas: [
      { title: 'Pleasure, but simple', text: 'The highest good is pleasure, which he defined mainly as freedom from bodily pain (aponia) and from mental disturbance (ataraxia). A quiet mind, not a feast, is the goal.' },
      { title: 'Death is nothing to us', text: 'While we exist, death is not here; when death is here, we are not. So there is nothing to fear. He believed fear of death ruins life more than any other fear.' },
      { title: 'The gods do not interfere', text: 'The gods exist but live in perfect peace and take no interest in humans, so we need neither fear their punishment nor beg for favours.' },
      { title: 'Atoms and the swerve', text: 'Like Democritus, he held that everything is made of atoms and void. He added the “swerve”, a small random deviation in the atoms’ paths, to leave room for free will.' },
      { title: 'Friendship above all', text: 'Of all the things that wisdom provides for a happy life, he said, the greatest by far is the possession of friends.' },
    ],
    principles: [
      'Tell natural, necessary desires apart from empty ones.',
      'Live simply: a little is enough.',
      'Do not fear death or the gods.',
      'Invest in friendship.',
    ],
    facts: [
      'Today “epicurean” can mean a lover of fine food, but Epicurus himself lived on bread, water and a little cheese. In one letter he asks a friend to send a small pot of cheese so that he can feast whenever he likes.',
      'On his deathbed he wrote that although he was in great pain, the joy of remembering his friends’ conversations outweighed it.',
      'According to Seneca, an inscription at the Garden’s gate read: “Stranger, you will do well to stay here; here our highest good is pleasure.”',
    ],
    legacy: 'Epicureanism spread across the Greek and Roman world and was revived in the Renaissance. It shaped modern ideas about science, secular ethics and the pursuit of happiness.',
  },
  {
    slug: 'zeno-of-citium',
    order: -334,
    dates: 'c. 334 – c. 262 BC',
    place: 'Citium, Cyprus, then Athens',
    tradition: 'Hellenistic',
    tagline: 'The founder of Stoicism, who began teaching in a painted colonnade.',
    who: [
      'Zeno came from Citium on Cyprus. According to Diogenes Laertius, a shipwreck while he was trading purple dye left him stranded in Athens, where reading about Socrates drew him to philosophy. He studied with the Cynic Crates and others.',
      'Around 300 BC he began teaching in the Stoa Poikile, the “Painted Porch”, at the edge of the Athenian marketplace. His followers were called Stoics, “people of the porch”. His own writings are lost, and we know them through later Stoics.',
    ],
    ideas: [
      { title: 'Live in agreement with nature', text: 'Humans are rational beings in a rational universe, and the good life is one in harmony with reason, which Zeno identified with nature and the divine order.' },
      { title: 'Virtue is the only true good', text: 'Wisdom, justice, courage and self-control are enough for happiness. Health, wealth and reputation are “preferred indifferents”: pleasant to have, but not necessary.' },
      { title: 'Emotions are judgments', text: 'Destructive passions such as anger and fear come from false judgments about what is good or bad. Correct the judgment, and you free yourself.' },
      { title: 'One city for all', text: 'All rational beings share a common reason, which became the root of the Stoic idea of world citizenship and universal justice.' },
    ],
    principles: [
      'Judge carefully; do not be carried away by first impressions.',
      'Value virtue above fortune.',
      'Accept what you cannot change, and do your duty.',
      'Treat every person as a fellow member of one community.',
    ],
    facts: [
      'Diogenes Laertius records a saying of Zeno: we have two ears and one mouth so that we may hear more and speak less.',
      'After losing everything in the shipwreck, he is said to have remarked that he had made a prosperous voyage.',
      'Athens honoured him with a gold crown and a public tomb for the example of his life.',
    ],
    legacy: 'Stoicism became one of the most influential philosophies of the Roman world, through Seneca, Epictetus and Marcus Aurelius, and it is still read today as a guide to resilience.',
  },
  {
    slug: 'epictetus',
    order: 50,
    dates: 'c. 50 – c. 135 AD',
    place: 'Hierapolis in Phrygia, Rome, then Nicopolis in Greece',
    tradition: 'Roman',
    tagline: 'A former slave who taught that we are free as soon as we master our own judgments.',
    who: [
      'Epictetus was born into slavery in Hierapolis, in what is now Turkey, and belonged to a secretary of Emperor Nero. He studied Stoicism with Musonius Rufus, was freed, and taught in Rome until Emperor Domitian banished philosophers around 93 AD. He then settled in Nicopolis in Greece, where he ran a school.',
      'He wrote nothing himself. His student Arrian recorded his lectures as the Discourses and condensed them into a short handbook, the Enchiridion. He was lame, according to one report because of a leg broken while he was a slave.',
    ],
    ideas: [
      { title: 'The dichotomy of control', text: 'Some things are up to us and some are not. Our opinions, choices and desires are ours; our bodies, property, reputation and other people’s actions are not. Peace comes from focusing only on the first group.' },
      { title: 'It is not events but judgments', text: 'People are disturbed not by things but by the views they take of them. Change the judgment, and the disturbance goes.' },
      { title: 'Freedom is inner', text: 'A slave in chains may be freer than a master who is ruled by fear and desire.' },
      { title: 'Play your role well', text: 'Life is like a play in which you have been given a part. You do not choose it, but you can choose to play it well.' },
      { title: 'Practise every day', text: 'Philosophy is training, not talk: watch your impressions, test them, and apply the principles in ordinary situations.' },
    ],
    principles: [
      'Ask first: is this up to me?',
      'Remember that what disturbs you is your judgment about the event.',
      'Rehearse hardship in advance.',
      'Do your duty as a citizen, friend and parent.',
    ],
    facts: [
      '“Epictetus” is Greek for “acquired”, a descriptive name often given to slaves, not his birth name.',
      'Marcus Aurelius thanks his teacher Rusticus for lending him his own copy of Epictetus’s lectures.',
      'Admiral James Stockdale, shot down over Vietnam in 1965 and held prisoner for seven years, credited Epictetus’s teaching with helping him endure.',
    ],
    legacy: 'His ideas about control and judgment are the foundation of modern cognitive therapy, and the Enchiridion remains a widely read handbook of Stoic practice.',
  },
  {
    slug: 'seneca',
    order: -4,
    dates: 'c. 4 BC – 65 AD',
    place: 'Corduba (Córdoba, Spain), then Rome',
    tradition: 'Roman',
    tagline: 'Statesman, playwright and Stoic who wrote about how to spend your time.',
    who: [
      'Lucius Annaeus Seneca was born in Corduba in Spain and raised in Rome. He became a famous orator, writer and senator, was exiled to Corsica by Emperor Claudius in 41 AD, and was later recalled to tutor the young Nero.',
      'When Nero became emperor in 54, Seneca was one of his chief advisers and grew very rich. He withdrew from public life in 62 and devoted himself to the essays and letters for which he is remembered. In 65 he was accused of involvement in a plot, and Nero ordered him to take his own life.',
    ],
    ideas: [
      { title: 'Time is your most precious possession', text: 'In On the Shortness of Life he argues that life is long enough if you use it well. We waste it on trivial pursuits and then complain that it is short.' },
      { title: 'Prepare for misfortune', text: 'Imagine the worst in advance, a practice later called premeditatio malorum, so that setbacks lose their power to shock.' },
      { title: 'Master anger', text: 'In On Anger he calls anger a brief madness. His advice: delay your reaction and examine the facts.' },
      { title: 'Wealth without attachment', text: 'A wise person can enjoy riches without being ruled by them. The test is being able to lose them calmly.' },
      { title: 'Philosophy as daily practice', text: 'His Letters to Lucilius, over a hundred of them, are conversational guides to daily living, written for a friend who is making progress.' },
    ],
    principles: [
      'Guard your time as you would your money.',
      'Practise voluntary discomfort now and then.',
      'Pause before acting in anger.',
      'Balance your books each day: review what you did and what you learned.',
    ],
    facts: [
      'Tacitus describes his death as a model Stoic end: calm, still conversing and dictating as he lost blood.',
      'He was one of the richest men in Rome, which led critics then and now to call him a hypocrite for praising simplicity.',
      'He also wrote tragedies, such as Medea and Thyestes, which influenced Renaissance playwrights, including Shakespeare’s generation.',
    ],
    legacy: 'His elegant letters and essays made Stoicism accessible to Roman readers, and they became favourites of the Renaissance and of modern readers looking for practical wisdom.',
  },
  {
    slug: 'marcus-aurelius',
    order: 121,
    dates: '121 – 180 AD',
    place: 'Rome',
    tradition: 'Roman',
    tagline: 'The Roman emperor who wrote private notes to himself on how to be a good person.',
    who: [
      'Marcus Aurelius became Roman emperor in 161 AD and ruled until his death in 180. He is counted as the last of the “Five Good Emperors”. His reign was troubled: a deadly plague, long wars along the Danube frontier and a revolt in the East.',
      'During the campaigns he kept a private notebook in Greek, now known as the Meditations. It was never meant to be published. It is a record of a man reminding himself, again and again, of the Stoic principles he wanted to live by.',
    ],
    ideas: [
      { title: 'Your judgment is the only thing that can harm you', text: 'He reminds himself that external things cannot touch the mind unless he allows it. What really hurts is his own opinion about what happens.' },
      { title: 'The obstacle becomes the way', text: 'What stands in the way becomes the way: the mind turns every obstacle into material for practising virtue.' },
      { title: 'Remember that life is short', text: 'He reminds himself often that life is brief and fame fleeting, so that he can focus on what matters today.' },
      { title: 'The view from above', text: 'He imagines looking down on the world from a great height, seeing armies, cities and individual troubles as small, to gain perspective.' },
      { title: 'Made for cooperation', text: 'People are made for one another, like hands or feet. To act against each other is against nature, and duty to the common good comes first.' },
    ],
    principles: [
      'Start the day expecting difficult people, and decide to meet them with patience.',
      'Do what is in front of you now, with full attention.',
      'Be strict with yourself and gentle with others.',
      'Accept what the universe brings, and treat it as part of the whole.',
    ],
    facts: [
      'The title “Meditations” was added later. The Greek manuscript is usually described as “To Himself”.',
      'Emperor Hadrian picked him as a future emperor when he was still a boy, and he was later adopted by Antoninus Pius.',
      'Two of the books carry notes saying where they were written near the Danube: one “among the Quadi on the river Gran”, the other “at Carnuntum”.',
      'He is the rare ruler who tried to live as Plato’s philosopher-king, yet his son Commodus is widely seen as a disappointing successor.',
    ],
    legacy: 'The Meditations has been read by leaders, soldiers and ordinary readers for nearly two thousand years as a guide to staying steady under pressure.',
  },
  {
    slug: 'plotinus',
    order: 204,
    dates: 'c. 204 – 270 AD',
    place: 'Roman Egypt, then Rome',
    tradition: 'Roman',
    tagline: 'The mystic philosopher who described all reality as flowing from a single source, the One.',
    who: [
      'Plotinus was born in Roman Egypt. He studied in Alexandria under Ammonius Saccas, then joined the emperor Gordian III’s expedition to Persia in 243–244, hoping to learn Persian and Indian thought. Around 245 he settled in Rome and taught there for the rest of his life.',
      'He began writing only in his fifties. His pupil Porphyry later edited the essays into six groups of nine, the Enneads, and also wrote his biography.',
    ],
    ideas: [
      { title: 'The One', text: 'All things come from a single, indescribable source beyond being and thought, which he called the One or the Good.' },
      { title: 'Three levels of reality', text: 'From the One flows Intellect, the realm of the Forms, and from Intellect flows Soul, which gives life to the physical world. This flow he called emanation, like light from the sun.' },
      { title: 'The return', text: 'Our true self is the soul, and the aim of life is to turn inward and upward, through virtue, contemplation and the love of beauty, until the soul is united with the One.' },
      { title: 'Beauty leads to the divine', text: 'We love beautiful things because they carry a trace of the highest Beauty. Following that trace is the way back.' },
      { title: 'Evil as absence', text: 'Matter, at the bottom, is the absence of form and good. Evil is a lack, not a power of its own.' },
    ],
    principles: [
      'Turn your attention inward.',
      'Never stop sculpting your own statue: remove what is excess until the beauty shows.',
      'Seek beauty, and let it lead you upward.',
      'Practise stillness and contemplation.',
    ],
    facts: [
      'Porphyry reports that Plotinus would not tell anyone his birthday and refused to have his portrait made, asking whether it was not enough to carry the image in which nature had enclosed him.',
      'Porphyry says he seemed almost ashamed of being in a body.',
      'According to Porphyry, Plotinus had a mystical union with the One four times during the years they were together; Porphyry himself had it once.',
      'He is said to have asked the emperor Gallienus for a ruined city in Italy to rebuild as “Platonopolis”, a town run on Plato’s laws. The plan fell through.',
    ],
    legacy: 'Neoplatonism, the school he founded, deeply influenced Christian thinkers such as Augustine, Islamic and Jewish philosophers, and Renaissance Platonists.',
  },
  {
    slug: 'confucius',
    order: -551,
    dates: '551 – 479 BC',
    place: 'Lu (now Shandong, China)',
    tradition: 'Eastern',
    tagline: 'A teacher who made humane character and learning the foundation of a good society.',
    who: [
      'Confucius (Kong Fuzi, “Master Kong”) was born in the state of Lu, in what is now Shandong, China. He came from a modest family, held minor posts and later office in Lu. Disappointed that rulers did not follow his advice, he travelled with his disciples for about fourteen years before returning home to teach.',
      'He saw himself as a transmitter of ancient wisdom, not an inventor. His sayings and conversations were collected by disciples as the Analects, one of the most influential books in history.',
    ],
    ideas: [
      { title: 'Ren, humaneness', text: 'The core virtue: goodwill, empathy and care for others, shown in how we treat everyone.' },
      { title: 'Li, ritual and propriety', text: 'Courtesy, ceremony and good manners are not empty forms. They shape character and keep a society harmonious.' },
      { title: 'The golden rule', text: 'Asked for one word to guide a whole life, he offered reciprocity: what you do not wish for yourself, do not do to others.' },
      { title: 'The exemplary person', text: 'A person of moral character, not noble birth, deserves to lead. Rulers should govern by example and virtue, not by force.' },
      { title: 'Education and self-cultivation', text: 'Everyone can improve through learning and practice. He taught students of every background, a radical idea in his time: in education, he said, there are no classes.' },
      { title: 'Family as the root', text: 'Respect within the family, filial piety, is the root of respect in society.' },
    ],
    principles: [
      'Study, and reflect on what you study.',
      'Treat others as you would like to be treated.',
      'Lead by example.',
      'Know what you know, and admit what you do not know.',
      'Cultivate yourself every day.',
    ],
    facts: [
      '“Confucius” is a Latinised form of “Kong Fuzi”, created by Jesuit missionaries in the 16th century.',
      'He said, “I transmit but do not create”, and called himself a lover of antiquity.',
      'He described his life in stages: at fifteen he set his heart on learning, at thirty he took his stand, at forty he had no doubts, at fifty he knew his calling, and at seventy he could follow his heart without overstepping what was right.',
      'For roughly two thousand years Confucian texts were the core of education in China, and later of the civil-service examinations.',
    ],
    legacy: 'Confucian ideas about family, education, duty and good government shaped China, Korea, Japan and Vietnam, and they are still part of East Asian culture today.',
  },
  {
    slug: 'laozi',
    order: -600,
    dates: 'traditionally 6th c. BC',
    place: 'China (Zhou kingdom)',
    tradition: 'Eastern',
    tagline: 'The “Old Master” of the Tao, who taught the strength of softness and not forcing things.',
    who: [
      'Laozi, “Old Master”, is the traditional author of the Tao Te Ching (Daodejing), a short book of 81 brief chapters. According to legend he was a record-keeper at the Zhou court who, weary of the kingdom’s decline, rode west on an ox. At the border gate a guard asked him to write down his wisdom before he left.',
      'Historians do not agree on whether he was a real person, a legendary figure, or a name for several authors. The text as we have it probably took shape between the 4th and 3rd centuries BC.',
    ],
    ideas: [
      { title: 'The Tao, the Way', text: 'The Tao is the nameless source and pattern of all things. The opening line says that the Tao that can be told is not the eternal Tao: it cannot be captured in words, but it can be followed.' },
      { title: 'Wu wei, effortless action', text: 'Act in harmony with the natural flow instead of forcing things. The best action is like water finding its course.' },
      { title: 'The soft overcomes the hard', text: 'Water is gentle yet wears away rock. What is flexible endures, while what is rigid breaks.' },
      { title: 'Simplicity and humility', text: 'The sage keeps few desires, does not compete and leads by staying in the background. The best ruler is one whom people barely notice.' },
      { title: 'Opposites define each other', text: 'Beautiful and ugly, long and short, giving and receiving: each exists through the other. Understanding this brings balance.' },
    ],
    principles: [
      'Do not force it.',
      'Be like water: yielding, patient and persistent.',
      'Return to simplicity.',
      'Know when enough is enough.',
      'A journey of a thousand miles begins with a single step.',
    ],
    facts: [
      'His name simply means “Old Master”.',
      'The Tao Te Ching is among the most translated works in world literature.',
      'Silk copies of the text were found in 1973 at Mawangdui, dated to about 168 BC, and older copies on bamboo strips at Guodian in 1993, dated to about 300 BC.',
      'In legend, the border guard Yinxi was the first to receive the text, which is why the book exists at all.',
      'In religious Taoism Laozi is worshipped as a divine figure.',
    ],
    legacy: 'Taoism shaped Chinese art, medicine, poetry and politics. Its ideas of balance and non-forcing influenced Buddhism in China and are widely read around the world today.',
  },
  {
    slug: 'the-buddha',
    order: -563,
    dates: 'c. 563 – 483 BC (traditional)',
    place: 'Lumbini (now Nepal) and northern India',
    tradition: 'Eastern',
    tagline: 'A prince who left his palace to find the end of suffering, and taught the Middle Way.',
    who: [
      'Siddhartha Gautama was born into the Shakya clan, in the region of Lumbini in what is now Nepal. Tradition says he grew up in comfort, left home at 29 after seeing old age, sickness and death, and spent years in extreme self-denial.',
      'He gave up that path, meditated beneath a tree at Bodh Gaya and attained awakening (bodhi), becoming “the Buddha”, the Awakened One. He taught for about forty-five years across northern India and died at Kushinagar. Scholars debate his dates, and many place him in the 5th century BC.',
    ],
    ideas: [
      { title: 'The Four Noble Truths', text: 'Life involves suffering (dukkha); suffering has a cause, craving and clinging; it can end; and there is a path to its end.' },
      { title: 'The Eightfold Path', text: 'Right view, intention, speech, action, livelihood, effort, mindfulness and concentration: a practical training in wisdom, ethics and meditation.' },
      { title: 'The Middle Way', text: 'Neither indulgence nor extreme self-denial leads to peace. The sensible path lies between them.' },
      { title: 'Impermanence and non-self', text: 'All things, including what we call “I”, are in constant change. Clinging to a fixed self is a source of suffering, and seeing through it brings freedom.' },
      { title: 'Compassion', text: 'Kindness towards all beings, without exceptions, is a central practice and a mark of wisdom.' },
    ],
    principles: [
      'Observe your own mind.',
      'Let go of craving and clinging.',
      'Act with kindness.',
      'Test teachings for yourself rather than accepting them on authority.',
    ],
    facts: [
      '“Buddha” is a title, not a name. It means “awakened one”.',
      'His teachings were passed on orally for centuries. The Pali Canon was first written down in Sri Lanka around the first century BC.',
      'He is said to have declined to answer metaphysical questions, such as whether the world is eternal, because they do not lead to freedom. His parable of the man shot with a poisoned arrow makes the point: first pull out the arrow.',
      'According to tradition, his last words were: all conditioned things are subject to decay, so strive on with diligence.',
      'Buddhism spread from India to Sri Lanka, Southeast Asia, China, Korea, Japan and Tibet, and is now practised around the world.',
    ],
    legacy: 'One of the world’s major traditions, Buddhism continues to shape the lives of hundreds of millions, and its meditation practices have been adopted in psychology and medicine.',
  },
  {
    slug: 'cicero',
    order: -106,
    dates: '106 – 43 BC',
    place: 'Arpinum, then Rome',
    tradition: 'Roman',
    tagline: 'Roman orator and statesman who carried Greek philosophy into Latin.',
    who: [
      'Marcus Tullius Cicero was born in Arpinum, outside Rome, and rose to the highest office, consul, in 63 BC. He is regarded as Rome’s greatest orator, and he spoke and wrote against civil war and dictatorship during the collapse of the Republic.',
      'Pushed out of politics by Caesar’s dictatorship, he spent 46–44 BC writing a remarkable series of philosophical works in Latin, explaining Greek schools to Roman readers. After Caesar’s murder he attacked Mark Antony in the Philippics and was killed on Antony’s orders in 43 BC.',
    ],
    ideas: [
      { title: 'Natural law', text: 'There is a true law in agreement with nature, valid for all people and all times, and unjust human laws do not bind. This idea echoed through later political thought.' },
      { title: 'The duties of a good citizen', text: 'In On Duties he argues that moral goodness and usefulness never truly conflict, and he sets out obligations to family, friends, country and humanity.' },
      { title: 'Moderate scepticism', text: 'Following the Academy, he held that certainty is rare, so we should follow what is most probable and keep an open mind.' },
      { title: 'Friendship', text: 'In On Friendship he argues that true friendship is possible only between good people and is one of the greatest goods.' },
      { title: 'Old age and death', text: 'In On Old Age he argues that age has pleasures of its own and that death is nothing to fear.' },
    ],
    principles: [
      'Serve the common good.',
      'Be honest, even when it is costly.',
      'Weigh evidence, and hold your views with humility.',
      'Choose friends of good character.',
      'Never stop reading and learning.',
    ],
    facts: [
      'He invented Latin words for many philosophical ideas, including qualitas (quality) and moralis (moral).',
      'More than 900 of his letters survive, giving an unmatched, intimate view of Roman political and private life.',
      'The poet Petrarch’s rediscovery of Cicero’s letters in 1345 is often said to have helped inspire the Renaissance.',
      'After his death on Antony’s orders, his head and hands were displayed in the Forum.',
    ],
    legacy: 'Cicero’s Latin shaped European prose for centuries, and his ideas on natural law, duty and republican government influenced the founders of modern constitutions.',
  },
  {
    slug: 'lucretius',
    order: -99,
    dates: 'c. 99 – c. 55 BC',
    place: 'Rome',
    tradition: 'Roman',
    tagline: 'A Roman poet who explained the world as atoms and freed readers from the fear of death.',
    who: [
      'Titus Lucretius Carus is known almost entirely through one surviving work, On the Nature of Things (De rerum natura), a long philosophical poem in Latin. Little is certain about his life. He lived in the late Roman Republic, and later tradition says Cicero edited the poem after his death.',
      'The poem sets out the philosophy of Epicurus in six books, written to persuade Romans that the world can be explained by natural causes and that there is nothing to fear in the gods or in death.',
    ],
    ideas: [
      { title: 'Atoms and void', text: 'Everything is made of atoms moving in empty space. Nothing comes from nothing, and nothing is destroyed; things only change their arrangement.' },
      { title: 'Freedom from superstition', text: 'Religion, he writes, has been able to persuade people to evil deeds. Understanding nature frees us from superstitious fear.' },
      { title: 'Death is nothing to us', text: 'Before we were born we did not suffer, and after death we shall not. He compares both sides of life to the same peaceful nothing, the “symmetry argument”.' },
      { title: 'A world that makes itself', text: 'He imagines life springing from the earth and creatures that were unfit for survival dying out, an early guess at natural selection.' },
      { title: 'Calm as the goal', text: 'The wise person watches the troubles of the world from a calm shelter, free of fear and unnecessary desire.' },
    ],
    principles: [
      'Understand nature to reduce fear.',
      'Pursue calm, not excess.',
      'Do not be afraid of death.',
      'Stay curious about how the world works.',
    ],
    facts: [
      'He compares his poem to a doctor who smears honey on the rim of a cup of bitter medicine: poetry makes the hard philosophy easier to swallow.',
      'St Jerome claimed Lucretius went mad from a love potion and died by suicide. Modern scholars doubt it.',
      'The poem was rediscovered in 1417 by the Italian humanist Poggio Bracciolini, who found a copy in a monastery in Germany.',
      'Thomas Jefferson owned several copies of Lucretius.',
    ],
    legacy: 'The rediscovery of De rerum natura helped shape Renaissance science and the Enlightenment, bringing atomism and Epicurean ethics back into European thought.',
  },
]
