import type { Profile } from './types'

export const CLASSICAL: Profile[] = [
  {
    slug: 'socrates',
    order: -470,
    dates: 'c. 470 – 399 BC',
    place: 'Athens',
    era: 'Ancient',
    tradition: 'Classical Greek',
    tagline: 'He wrote nothing, questioned everyone, and died rather than give up a life of inquiry.',
    who: [
      'Socrates was born in Athens around 470 BC. According to Plato, his father Sophroniscus was a stoneworker and his mother Phaenarete a midwife. He married Xanthippe and had three sons. Like other Athenian citizens he served as a hoplite, a heavily armed foot soldier, and Plato and others place him at the battles of Potidaea (432 BC), Delium (424 BC) and Amphipolis (422 BC). For the rest of his life he seems to have lived simply, spending his days in the agora, the city’s open marketplace, and in the gymnasia, talking with anyone willing to talk: politicians, poets, craftsmen, visiting teachers and the sons of wealthy families. Unlike the travelling teachers called Sophists, he took no fees.',
      'Socrates wrote nothing, so everything we know about him is second-hand, and the sources disagree. The comic playwright Aristophanes, in his play The Clouds (423 BC), showed him as a ridiculous figure dangling in a basket and studying the sky. Xenophon, a soldier and writer who knew him, presents a practical, down-to-earth adviser. Plato, his most gifted follower, presents a daring and profound questioner, but Plato also made Socrates the main speaker of his own philosophy, so it is hard to say where the real man ends and Plato’s character begins. Scholars call this the Socratic problem, and they have not solved it.',
      'In 399 BC, when Socrates was about seventy, three citizens named Meletus, Anytus and Lycon brought a charge against him. The accusation was that he did not recognise the gods of the city, introduced new divinities, and corrupted the young. A jury of several hundred citizens, traditionally put at 500 or 501, found him guilty by a margin that Plato’s Socrates says was narrower than he expected. When asked to propose his own penalty he was defiant, and the jury voted for death. Because a sacred festival ship was away from Athens, the execution was delayed for about a month. Plato’s Phaedo describes how Socrates spent his last day talking with friends before drinking the cup of hemlock, a poison, and dying calmly.',
    ],
    context: [
      'Socrates lived through the rise and fall of Athenian power. As a young man he saw the city at its height, rich from its empire and decorated with new temples under the statesman Pericles. The Peloponnesian War against Sparta (431–404 BC), a plague and a disastrous expedition to Sicily wore the city down, and in 404 BC Athens surrendered. A brief, brutal oligarchy known as the Thirty Tyrants then ruled until democracy was restored in 403 BC. Two of the Thirty, Critias and Charmides, had been in Socrates’s circle, and so had the brilliant and unreliable general Alcibiades, who changed sides during the war. These links made Socrates look suspicious in the anxious years after the war.',
      'It was also a time of great intellectual excitement. The Sophists taught rhetoric and argued that moral rules are matters of custom, and natural philosophers offered new accounts of the heavens. Many traditional beliefs were being questioned. Socrates turned from questions about the cosmos to questions about how a person ought to live, and he did it in public conversation instead of lectures. To many Athenians that made him an annoying critic, and to others a hero. His trial in 399 BC was shaped by this mood. Scholars still debate how far it was a religious matter, how far a political one, and how far a response to the harm that his followers had done to the city.',
    ],
    ideas: [
      { title: 'The examined life', text: 'In Plato’s Apology, Socrates says that the unexamined life is not worth living for a human being. By this he meant that we should not simply accept the way we live, but ask what we are doing and why. His usual tool was the elenchus, a method of cross-examination in which he asks someone to define a word like courage or justice, tests the answer against other things they believe, and shows that the answer does not hold together. The result is often puzzlement, and puzzlement is where he thought honest thinking begins.' },
      { title: 'Wisdom begins with knowing your limits', text: 'Plato tells how his friend Chaerephon asked the oracle at Delphi whether anyone was wiser than Socrates, and the priestess said no. Puzzled, Socrates went to question people with a reputation for wisdom, and found that they thought they knew what they did not. He concluded that he was wiser only in this: he did not think he knew what he did not know. The saying “I know that I know nothing” is a later simplification of that idea, and Plato’s Socrates does claim to know some things, for example that it is wrong to disobey a good authority.' },
      { title: 'Virtue is a kind of knowledge', text: 'Socrates argued that if people truly understood what is good, they would do it, because nobody wants to harm themselves. On this view wrongdoing comes from ignorance, which is why scholars say he held that no one does wrong willingly. Critics from Aristotle onward have found this too hopeful, because people often know what is right and do otherwise. But it led Socrates to treat moral education and honest self-examination as the most urgent task a person can have.' },
      { title: 'Care of the soul', text: 'Socrates told the Athenians that they cared for money, reputation and power but not for the state of their souls, by which he meant their moral character. In Plato’s Gorgias he goes further and argues that it is worse to do injustice than to suffer it, because doing wrong damages the person who does it. This was a radical view in a society that prized honour and success, and it was the root of his claim that the just person is better off whatever happens to them.' },
      { title: 'Duty, conscience and the law', text: 'Socrates described an inner divine sign, his daimonion, which did not tell him what to do but warned him away from certain actions. He said that the god had given him a mission to question his fellow citizens, and that he would obey it even at the risk of death. Yet in Plato’s Crito he refuses to escape from prison, arguing that he owes the laws of Athens obedience, since they raised him and he chose to live under them. How these two commitments fit together is one of the great debates about him.' },
    ],
    principles: [
      'Examine your assumptions, especially the comfortable ones.',
      'Be willing to say “I do not know”, and to learn from the answer.',
      'Ask what you mean by the big words you use: justice, courage, success.',
      'Care more about the quality of your character than about reputation or wealth.',
      'It is better to suffer wrong than to do wrong.',
    ],
    practice: [
      'When you hold a strong opinion, try to define the key words in it, and see whether your definition survives a few examples.',
      'In a disagreement, ask questions before making statements. Try to understand how the other person reached their view.',
      'Once a week, ask yourself whether something you have been doing for a long time is actually good, or just familiar.',
    ],
    facts: [
      'Plato’s Symposium has the general Alcibiades tell of Socrates’s toughness on campaign at Potidaea: he went barefoot in the icy winter, and once stood thinking in one spot from dawn to the next morning.',
      'Plato’s Socrates calls himself a gadfly sent by the god to sting a large, sleepy horse, which is how he described Athens.',
      'In Plato’s Theaetetus he compares his work to his mother’s: he is a midwife of ideas, who does not give birth to wisdom himself but helps others deliver their own.',
      'Socrates took little part in politics, but he was no stranger to its dangers. In 406 BC, according to Plato and Xenophon, he was serving on the council committee presiding when the generals of the battle of Arginusae were to be tried together, and he opposed the illegal procedure. Under the Thirty he refused, in Plato’s account, an order to help arrest Leon of Salamis.',
      'His last words in Plato’s Phaedo are a request to his friend Crito to offer a rooster to Asclepius, the god of healing. Readers still argue about what he meant.',
      'He is described as short, snub-nosed and bulging-eyed, and he is compared in Plato’s Symposium to a statue of the satyr Silenus that opens to reveal figures of gods inside.',
    ],
    myths: [
      { myth: 'Socrates said “I know that I know nothing.”', reality: 'The line does not appear in this form in Plato. In the Apology he says he is wise only in not thinking he knows what he does not know. He still claims to know certain moral matters, so his ignorance is more specific than the slogan suggests.' },
      { myth: 'Xanthippe was a shrew who made his life miserable.', reality: 'The image comes from later anecdotes. In Xenophon she is difficult but loyal, and in Plato’s Phaedo she grieves for him on his last day. Ancient evidence for her character is thin.' },
      { myth: 'Socrates was killed simply for asking questions.', reality: 'The formal charges were religious. Scholars debate how far the trial was also political, since several of his associates had been involved in the Thirty. Athens had also granted an amnesty in 403 BC for wartime offences, so the prosecution had to rely on religious charges.' },
    ],
    works: [
      { title: 'No writings by Socrates', note: 'Nothing he wrote survives, and ancient writers agree that he published nothing. Everything depends on the accounts of others.' },
      { title: 'Plato, Apology, Crito and Phaedo', note: 'Plato’s account of the trial, the refusal to escape, and the last day. They are among the most powerful portraits of Socrates, though shaped by Plato’s own thinking.' },
      { title: 'Xenophon, Memorabilia, Apology and Symposium', note: 'Memoirs and conversations from a friend who presents a more practical, less mystical Socrates.' },
      { title: 'Aristophanes, The Clouds', note: 'A comedy of 423 BC that caricatures him, and that Plato’s Socrates says helped prejudice the jury.' },
      { title: 'Aristotle, Metaphysics', note: 'Credits Socrates with seeking universal definitions in ethics, an outsider’s view that helps check Plato’s picture.' },
    ],
    legacy: [
      'Almost every school of ancient philosophy claimed Socrates as an ancestor. Plato and Aristotle came from his circle, the Cynics admired his indifference to comfort, the Stoics his steadiness, and the Sceptics his admission of ignorance. Because he wrote nothing, each could find in him what it needed. The term “Presocratic” for earlier thinkers reflects how much later writers saw him as a turning point, when philosophy moved from nature to human life.',
      'His death became one of the great stories of Western culture, a model for those who accept punishment rather than abandon conscience. His method lives on in classrooms, law schools and in the questioning used in modern therapy. Meanwhile the question of who the historical Socrates really was remains open, and part of his pull is that he exists for us only in the minds of those who loved him.',
    ],
  },
  {
    slug: 'plato',
    order: -428,
    dates: 'c. 428 – c. 348 BC',
    place: 'Athens',
    era: 'Ancient',
    tradition: 'Classical Greek',
    tagline: 'Student of Socrates, founder of the Academy, and author of the dialogues that shaped Western thought.',
    who: [
      'Plato was born in Athens around 428 or 427 BC into an aristocratic family. His father was Ariston and his mother Perictione, and his relatives included Critias and Charmides, who would later be among the Thirty Tyrants. His brothers Glaucon and Adeimantus appear as speakers in the Republic. A tradition reported by Diogenes Laertius says his birth name was Aristocles and that “Plato”, from the Greek platus, “broad”, was a nickname, whether for his build, his forehead or his wide-ranging style. Like other young men of his class he expected a career in politics. Instead he met Socrates, and by his own account the violence of the Thirty in 404 BC and the execution of Socrates in 399 BC disillusioned him with public life.',
      'After Socrates’s death, tradition says Plato left Athens and travelled, perhaps to Megara, Egypt and Cyrene. What is better attested is a visit to Italy and Sicily around 388–387 BC, where he met Pythagorean thinkers such as Archytas of Tarentum and visited the court of the tyrant Dionysius I of Syracuse. On his return he founded the Academy, a school in a grove sacred to the hero Academus outside the walls of Athens, around 387 BC. After Dionysius I died, Plato made two more journeys to Syracuse, around 367 and 361 BC, hoping to guide the young ruler Dionysius II. The attempts failed and left Plato in some danger. A later tradition says that on an earlier trip he was sold into slavery on Aegina and ransomed by a friend, but ancient sources for this are late and scholars doubt it.',
      'Plato spent most of his remaining years teaching and writing at the Academy and died around 348 or 347 BC, at about eighty. Roughly thirty works are accepted as genuine, almost all of them dialogues, which are dramatic conversations. Plato never speaks in his own voice in them, and Socrates is the main speaker in most. The order in which they were written is partly guesswork, and scholars usually divide them into early, middle and late groups on stylistic grounds, though they debate how well this division reflects Plato’s development. Unlike nearly every other ancient writer, his works survive in full. Thirteen letters also come down under his name, among them the Seventh Letter, but most scholars doubt that many, or any, are by him.',
    ],
    context: [
      'Plato grew up during the Peloponnesian War and came of age in the confusion after it. Athens had lost its empire, its democracy had been overthrown and restored, and its most famous philosopher had been put to death by a jury. Plato’s mature work can be read as an answer to that crisis: a search for something solid beneath the changing opinions and the shifting politics of the city. He wanted to know what justice really is, and what kind of person and kind of society could be truly just.',
      'He also drew on many sources. From Parmenides and Heraclitus he took the problem of change and permanence, from the Pythagoreans a respect for mathematics and for the soul’s fate after death, and from Socrates the method of question and answer. The Academy was something new: a community that brought together mathematicians, astronomers and philosophers. Gifted mathematicians such as Theaetetus and Eudoxus worked there, and many of the early Academy’s members came to teach and advise in cities around the Greek world.',
    ],
    ideas: [
      { title: 'The Theory of Forms', text: 'The physical world is full of things that change and decay: beautiful things fade, and no drawn circle is perfectly round. Plato proposed that behind them stand Forms, perfect and unchanging patterns such as Beauty, Justice and Equality, which we know through reason, not through the senses. The things we see take their character by sharing in the Forms. The idea is the foundation of his thought, though he did not treat it as settled. In his own dialogue Parmenides, the aged philosopher raises serious objections to the theory, including the “third man” argument, and Plato leaves them hanging.' },
      { title: 'The Cave and the Form of the Good', text: 'In the Republic, Plato imagines prisoners chained in a cave, seeing only shadows on a wall and taking them for reality. A prisoner who is freed and climbs out sees the sun and the real things, and is dazzled. If he goes back to teach the others, they mock him. The story pictures education as a painful turning of the whole soul toward the truth. The sun stands for the Form of the Good, the highest object of knowledge, which makes everything else both intelligible and good.' },
      { title: 'The soul and recollection', text: 'Plato argued that the soul is immortal and that learning is a kind of recollection of what the soul knew before birth. In the Meno, Socrates draws a geometry lesson out of an untaught slave boy by questions alone, to suggest that knowledge is already latent in us. In the Republic the soul has three parts: reason, which seeks truth, spirit, the seat of anger and ambition, and appetite, the desire for food, drink and pleasure. A healthy soul is one in which reason rules with the support of spirit.' },
      { title: 'Justice and the philosopher-rulers', text: 'The Republic asks what justice is by imagining a city. It has three classes, matching the three parts of the soul, and justice means each doing its proper work. Plato argued that such a city should be guided by those who have come to know the Good, the philosopher-rulers, instead of by wealth or popularity. He distrusted democracy, which in his view put power in the hands of people who lacked knowledge. Scholars still debate how literally he meant the blueprint, and in his late work, the Laws, he describes a very different city governed by law.' },
      { title: 'Love as a ladder', text: 'In the Symposium, a group of guests give speeches praising love. Socrates reports the teaching of a wise woman, Diotima, who describes a ladder. Love begins with attraction to one beautiful body, rises to love of all beautiful bodies, then of beautiful souls, laws and kinds of knowledge, and finally to the vision of Beauty itself. Plato presents love as a longing for the good that can lead us toward wisdom.' },
    ],
    principles: [
      'Look beyond appearances to what is real and lasting.',
      'Education is the turning of the soul toward the truth, not the pouring of facts into an empty vessel.',
      'Learn to rule yourself by reason before trying to rule others.',
      'A good question is worth more than a quick answer.',
      'Justice in a person and justice in a city have the same shape: each part doing its own work in harmony.',
    ],
    practice: [
      'When you admire something beautiful or good, ask what makes it so, and whether you can name the quality behind it.',
      'When you feel pulled between what you want, what you feel and what you think, ask which of the three is ruling you at that moment.',
      'Test your opinions in conversation with a friend who is willing to disagree.',
    ],
    facts: [
      'The Academy, founded around 387 BC, lent its name to every “academy” since. It continued in various forms for centuries, and Aristotle studied there for nearly twenty years.',
      'The mathematician Alfred North Whitehead wrote in 1929 that the safest general description of the European philosophical tradition is that it consists of a series of footnotes to Plato.',
      'Atlantis first appears in two of his dialogues, Timaeus and Critias. Scholars generally think it is Plato’s own invention, used to illustrate a point about the ideal state and its enemies.',
      'In the Phaedrus, Socrates warns that writing weakens memory and cannot answer questions, and Plato then went on to write a great deal. Many take this to explain why he chose the dialogue form, which imitates living conversation.',
      'Diogenes Laertius tells a story that when Plato defined a human being as a featherless biped, Diogenes the Cynic plucked a chicken and announced “Here is Plato’s human being.”',
      'Diogenes Laertius reports a tradition that the Laws was left unfinished on wax tablets at Plato’s death and was copied out by his follower Philip of Opus.',
    ],
    myths: [
      { myth: '“Platonic love” means love without sex.', reality: 'The phrase is a Renaissance coinage, associated with Marsilio Ficino’s writing about Plato. In the Symposium, love grows out of erotic desire, and the ascent to the Form of Beauty begins from there.' },
      { myth: 'Plato proved that Atlantis was a real lost civilisation.', reality: 'Plato presents the story as an old tale told to Solon by Egyptian priests. Most scholars think he invented it as a story to make a philosophical point.' },
      { myth: 'Over the Academy’s door were the words “Let no one ignorant of geometry enter.”', reality: 'This is reported only by writers centuries later. It captures the Academy’s respect for mathematics, but nobody knows whether such an inscription existed.' },
    ],
    works: [
      { title: 'Apology and Crito', note: 'Socrates’s speech at his trial and his conversation in prison, the best entry point to Plato.' },
      { title: 'Republic', note: 'Plato’s longest and most famous work apart from the Laws: justice, the soul, the ideal city, the Cave and the Form of the Good.' },
      { title: 'Phaedo and Symposium', note: 'Dialogues on the death of Socrates and the immortality of the soul, and on love and beauty.' },
      { title: 'Timaeus and Critias', note: 'A creation story, in which a divine craftsman shapes the world by looking to the Forms, and the first appearance of Atlantis.' },
      { title: 'Laws and the Letters', note: 'The Laws is Plato’s last and longest dialogue. The Letters, including the Seventh Letter, tell of his Sicilian ventures, but most scholars doubt their authenticity.' },
    ],
    legacy: [
      'Aristotle began his career in the Academy and then built a system that both borrows from Plato and criticises him. Later Platonists, above all Plotinus, built a spiritual philosophy from Plato’s ideas, and this Neoplatonism shaped Augustine, much Islamic and Jewish thought, and the Renaissance. In the fifteenth century Marsilio Ficino translated Plato into Latin, and the translation was printed in 1484, which brought the dialogues to many European readers.',
      'In the modern era Plato’s influence is everywhere, from mathematics, where many mathematicians still hold a “Platonist” view that numbers exist independently of us, to political theory and education. He has also had sharp critics. In the twentieth century Karl Popper accused the Republic of laying the groundwork for authoritarian rule, and others reply that Plato intended it as a thought experiment about justice rather than as a plan. What is not in doubt is how much of Western thought is a conversation with his.',
    ],
  },
  {
    slug: 'aristotle',
    order: -384,
    dates: '384 – 322 BC',
    place: 'Stagira, then Athens',
    era: 'Ancient',
    tradition: 'Classical Greek',
    tagline: 'The great organiser of knowledge: logic, ethics, biology, politics and more.',
    who: [
      'Aristotle was born in 384 BC in Stagira, a small Greek town in the north of the Aegean, in the region of Chalcidice. His father Nicomachus was a physician at the court of the Macedonian king Amyntas III, and the family’s medical tradition may have helped shape the son’s interest in living things. Both his parents died while he was young. At about seventeen he travelled to Athens and joined Plato’s Academy, where he stayed for nearly twenty years, first as a student and then as a researcher and teacher.',
      'When Plato died in 347 BC Aristotle left Athens. He spent several years at Assos on the coast of Asia Minor, where the ruler Hermias of Atarneus was a friend, and he married Pythias, who was connected to Hermias. He then worked on the island of Lesbos, where, together with his colleague Theophrastus, he studied marine animals and plants. Around 343 BC King Philip II of Macedon called him to Pella to teach his teenage son, the future Alexander the Great. The lessons lasted only a few years, and how much influence Aristotle had on Alexander is much debated.',
      'In 335 BC Aristotle returned to Athens and founded his own school in the Lyceum, a gymnasium dedicated to Apollo Lykeios. As a foreigner he could not own property there, so the school depended on rented buildings and gifts. His followers were later called the Peripatetics, a name often connected with the peripatos, the covered walkway where tradition says he taught while walking. When Alexander died in 323 BC, anti-Macedonian feeling surged in Athens and Aristotle left for Chalcis on the island of Euboea, where he died in 322 BC of a stomach illness. A story, told by the later writer Aelian, says he left so that Athens would not “sin twice against philosophy”, a reference to the execution of Socrates.',
    ],
    context: [
      'Aristotle lived during the rise of Macedon. Philip II won control of Greece at the battle of Chaeronea in 338 BC and Alexander then conquered the Persian empire, so the independent city-state that Plato and Aristotle took as the basic political unit was passing into history. Ancient lists say his school collected the constitutions of 158 cities as research for the Politics, even as the world around him was shifting toward kingdoms and empires. Athens remained the intellectual capital, but it was now a city under Macedonian influence, and resentment of that influence was a constant danger to Aristotle.',
      'Intellectually he inherited Plato’s questions and gave different answers. Where Plato looked beyond the visible world to the Forms, Aristotle held that form exists in things themselves and that careful study of the world is the way to knowledge. His school set up a research programme with a library, collections of specimens and many collaborators. It is one reason he is often described as the first great systematic scientist, though by modern standards his methods were often limited to observation and reasoning, without experiment.',
    ],
    ideas: [
      { title: 'The first system of logic', text: 'Aristotle created the first formal study of valid reasoning. Its core is the syllogism, an argument in which two statements lead to a conclusion: all humans are mortal; all Greeks are human; so all Greeks are mortal. He showed that the validity of such arguments depends on their form and not on their subject matter. His logic was taught almost unchanged for over two thousand years, and the philosopher Kant remarked that logic had not had to go a step backwards since Aristotle.' },
      { title: 'Matter, form and four causes', text: 'Aristotle held that every natural thing is a compound of matter and form: a bronze statue is bronze (matter) shaped like a person (form). To understand something, he said, we should ask four questions, which he called causes: what it is made of, what shape or nature it has, what brought it about, and what it is for. This last, its purpose, is a distinctive part of his thinking. He argued that nature is full of such purposes, as when a seed develops into a tree. In his Metaphysics the chain of motion in the universe leads back to an unmoved mover, a being that moves things by being the object of desire and thought.' },
      { title: 'Happiness as flourishing, and virtue as a mean', text: 'In the Nicomachean Ethics, Aristotle says that the highest human good is eudaimonia, often translated happiness, but closer to flourishing: a whole life spent doing well what is characteristically human, which means using our reason. Virtues such as courage and generosity are not rules or feelings but settled habits of character, built by practice. Each lies in a mean between two extremes, courage between cowardice and recklessness, and the mean is relative to the person and the situation. Good judgement, which he calls practical wisdom, tells us where the mean lies.' },
      { title: 'Humans are political animals', text: 'The Politics begins with the claim that a city exists by nature, and that humans are by nature creatures who live in communities. A person who needs no community is, he says, either a beast or a god. He compares constitutions, sorts them into good forms (rule by one, a few or many for the common good) and corrupt forms (tyranny, oligarchy, extreme democracy), and favours a mixed system with a strong middle class. His views have a darker side. He defended slavery as natural for some people and held that women are naturally subordinate, positions that many readers today regard as serious failures of his reasoning.' },
      { title: 'Studying nature by observing it', text: 'Aristotle’s biological works, including the History of Animals, Parts of Animals and Generation of Animals, record the structure, habits and development of hundreds of kinds of animals. He dissected animals, studied the development of chick embryos, and described the way some sharks bear live young, a claim that others doubted until it was confirmed in the nineteenth century. He also made mistakes, such as placing the seat of intelligence in the heart. Still, his insistence on gathering facts first made biology a field of study.' },
    ],
    principles: [
      'We are what we repeatedly do. Excellence is a habit, not an act.',
      'Look for the mean between too much and too little, in the way that fits you and your situation.',
      'Start from what can be observed and from what thoughtful people believe, then reason from there.',
      'A good life is a whole life: it takes time, friends and the use of your abilities.',
      'Different subjects allow different kinds of precision. Do not demand mathematical certainty from ethics.',
    ],
    practice: [
      'Pick a quality you want to build, such as patience, and practise it in small, regular acts, since Aristotle believed character is trained by repetition.',
      'When you face a decision with two extremes, ask what the mean would be for you today, neither too harsh nor too lax.',
      'Invest in friendships of real goodwill, not just usefulness or pleasure. He spends two whole books of the Ethics on friendship.',
    ],
    facts: [
      'Ancient lists credit Aristotle with some two hundred works, of which about thirty survive. Most are lecture notes or working drafts, not polished books. Cicero praised his lost dialogues for a “golden stream” of style.',
      'The marine studies on Lesbos led him to describe the way the dogfish shark develops, and details of the cuttlefish and octopus, that were doubted until confirmed by nineteenth-century zoologists.',
      'A papyrus of his Constitution of the Athenians, a study of the Athenian government, was found in Egypt in the late nineteenth century.',
      'Dante called him “the master of those who know”, and medieval scholars often referred to him simply as “the Philosopher”.',
      'His will, preserved by Diogenes Laertius, provides for his family and arranges for the freeing of several slaves. Scholars debate whether it is authentic, but it is often cited.',
      'Aristotle wrote in his History of Animals that men have more teeth than women, a claim that anyone could have checked and that is false. It shows the limits of his empirical habits.',
    ],
    myths: [
      { myth: 'Aristotle’s writings were buried in a cellar for two centuries and rediscovered by chance.', reality: 'The story is told by Strabo and Plutarch, who say that Aristotle’s library was hidden at Scepsis and later edited by Andronicus of Rhodes in the first century BC. Many scholars think the details are exaggerated, because Aristotle’s works were certainly known in the meantime.' },
      { myth: 'Aristotle taught Alexander the Great how to conquer.', reality: 'The lessons lasted only a few years, when Alexander was in his early teens. Aristotle’s influence on Alexander’s later career is uncertain, and the two seem to have drifted apart.' },
      { myth: 'Aristotle was a rigid authority who blocked science.', reality: 'Later Europeans turned him into an unquestionable authority, which Galileo and others rebelled against. Aristotle himself valued observation, corrected predecessors and said that the truth should be preferred to friends, including his teacher Plato.' },
    ],
    works: [
      { title: 'The logical works (the Organon)', note: 'Categories, On Interpretation, Prior and Posterior Analytics, Topics and Sophistical Refutations. The title Organon, “tool”, was added by later editors.' },
      { title: 'Physics, On the Heavens and Metaphysics', note: 'His accounts of nature, motion and the heavens, and of being as such. The name Metaphysics comes from the editors, and means roughly “after the Physics”.' },
      { title: 'Nicomachean Ethics', note: 'His main work on happiness and virtue, named either after his son Nicomachus or his father.' },
      { title: 'Politics', note: 'The study of the city, of constitutions and of how states can be well governed.' },
      { title: 'Biological works, Poetics and Rhetoric', note: 'History of Animals and related works on biology, together with the first systematic studies of tragedy and of persuasion.' },
    ],
    legacy: [
      'For well over a thousand years Aristotle’s works set the agenda for learning. Islamic philosophers such as Avicenna and Averroes wrote commentaries on them, Jewish thinkers such as Maimonides drew on them, and in the thirteenth century Thomas Aquinas built a Christian philosophy on Aristotelian foundations. Aristotle’s physics and astronomy dominated European universities until the seventeenth century, when thinkers such as Galileo and Newton replaced them.',
      'Many of his ideas are still alive. Modern virtue ethics draws directly on the Nicomachean Ethics, political theorists still discuss the mixed constitution, and biologists still honour his pioneering natural history. His habit of dividing a subject into branches and assigning each its own method is part of how knowledge is organised today.',
    ],
  },
  {
    slug: 'diogenes-of-sinope',
    order: -412,
    dates: 'c. 412 – c. 323 BC',
    place: 'Sinope on the Black Sea, then Athens and Corinth',
    era: 'Ancient',
    tradition: 'Cynicism',
    tagline: 'The philosopher who lived in a jar and told a king to stand out of his sunlight.',
    who: [
      'Diogenes was born in Sinope, a Greek port on the Black Sea in what is now northern Turkey. Ancient sources disagree about his dates, and modern scholars place his birth somewhere between about 413 and 404 BC and his death in the 320s BC. His father is said to have run the city’s mint or been a money-changer. According to Diogenes Laertius, either the father or Diogenes himself was caught debasing the coinage, and Diogenes was banished. Later he was reported to have said that he had “defaced the currency”, a phrase that became a motto for his challenge to accepted values.',
      'Exiled, he came to Athens and became the best-known figure of the Cynics, a movement that held that virtue is enough for happiness and that the way to it is to live simply, according to nature, and to reject social convention. Tradition makes him a student of Antisthenes, a follower of Socrates, but modern scholars doubt the connection because of the dates, and think he may have known Antisthenes’s ideas mainly through his writings. Stories describe him living in a large ceramic storage jar, a pithos, begging, owning a cloak, a staff and a bag, and mocking the philosophers, politicians and wealthy citizens of Athens.',
      'We know Diogenes almost entirely from anecdotes, many written down centuries after his death, above all by Diogenes Laertius in the third century AD, and some may be inventions attached to his name. Later sources say he was captured by pirates, sold as a slave to a Corinthian named Xeniades, and ended his life in Corinth, but scholars regard parts of this as legend. Ancient writers disagree on how he died. Accounts include holding his breath, a bad octopus meal, or a dog bite, and modern scholars think old age is the most likely cause. Tradition says the Corinthians set up a pillar topped with a marble dog in his memory.',
    ],
    context: [
      'Cynicism grew out of the Socratic tradition. Antisthenes had admired Socrates’s endurance and independence, and Diogenes pushed that independence much further. In Athens in the fourth century BC, the city was rich in schools and arguments but also in status and display, and Diogenes saw the contest for reputation as a kind of sickness. The word “Cynic” comes from the Greek kynikos, “dog-like”, probably first used by critics and then adopted as a badge of honour, since a dog lives simply, does things openly and guards those it loves.',
      'Diogenes lived through the period when the independent Greek city-states fell under Macedonian rule. His encounters with Philip and Alexander, whether real or invented, reflect the age of kings and a philosopher’s insistence that no ruler can give or take away what matters most. His idea that a person belongs to the whole world and not to a single city also suited an era in which the old city-state loyalties were weakening.',
    ],
    ideas: [
      { title: 'Live according to nature', text: 'Diogenes argued that nature gives us enough for a good life, and that most of our suffering comes from artificial needs. He is said to have thrown away his cup after seeing a boy drink from his hands, and to have learned from a mouse that a home and comforts are not essential. Training in hardship (askesis) was central: by practising cold, hunger and discomfort, a person grows free from fear of losing them.' },
      { title: 'Self-sufficiency and freedom', text: 'The Cynic aimed to need nothing that fortune can take away. A person who wants little cannot be threatened with its loss, and one who does not care for praise cannot be flattered or bullied. Diogenes treated this as true freedom, and a story, probably legend, has him put up for sale as a slave and telling the crowd that he knows how to govern people, so they should sell him to a man who needs a master.' },
      { title: 'Free speech and shamelessness', text: 'Cynics practised parrhesia, frank, fearless speech, and anaideia, a deliberate disregard for shame. Diogenes did in public what others did in private, such as eating in the marketplace, to show that many things we feel ashamed of are natural, and that many things we treat as respectable are empty. Some of his behaviour was crude and deliberately shocking, and it was meant to start people thinking, not simply to offend.' },
      { title: 'Deface the currency', text: 'The saying about defacing the currency turned a personal disgrace into a philosophy: he proposed to test every inherited custom, law and value, to see which are genuine coin and which are counterfeit. Laws and conventions, he suggested, are human products, and nature is the better guide.' },
      { title: 'Citizen of the world', text: 'Asked where he came from, Diogenes is said to have answered that he was a kosmopolites, a citizen of the cosmos. If so, he was one of the first to say that belonging to humanity matters more than belonging to a particular city, and the idea became important to later Stoics.' },
    ],
    principles: [
      'Want less, and you will need less.',
      'Say what you think, and say it plainly.',
      'Train for hardship in advance, so that fortune cannot shake you.',
      'Judge by nature and reason, not by custom or reputation.',
      'Do not be impressed by power or wealth.',
    ],
    practice: [
      'Try a day or a week without something you think you cannot do without, such as a comfort or a habit, and notice what you really need.',
      'When you are about to do something to impress others, ask whether you would still do it if no one would ever know.',
      'Look at a convention you take for granted, such as how much to spend or how to look, and ask who decided it and why.',
    ],
    facts: [
      'He is said to have lived in a pithos, a large clay storage jar, in Athens. The popular picture of a wooden barrel is a later one.',
      'According to Plutarch and Diogenes Laertius, when Alexander the Great found him sunbathing and asked if he wanted anything, Diogenes asked him to stand out of his sun, and Alexander is said to have remarked that if he were not Alexander, he would wish to be Diogenes.',
      'He is said to have walked the marketplace in daylight with a lit lamp, saying he was looking for a human being.',
      'Diogenes Laertius tells how he once begged from a statue to practise being refused, and how, hearing an argument that motion is impossible, he simply stood up and walked.',
      'Plato is said to have called him “a Socrates gone mad”, though the line comes from late sources.',
      'Raphael’s fresco The School of Athens (c. 1509–11) shows a figure sprawled on the steps that is usually identified as Diogenes.',
    ],
    myths: [
      { myth: 'Diogenes lived in a barrel.', reality: 'The ancient accounts describe a pithos, a large clay storage jar. The “barrel” appears in later retellings, probably because wooden barrels were more familiar to later readers.' },
      { myth: 'Diogenes died on the very day Alexander did, in 323 BC.', reality: 'Some ancient sources link the two deaths, which makes a neat story, but other ancient writers give different ages and dates. Modern scholars prefer a date in the 320s BC.' },
      { myth: 'A Cynic is someone who sneers at everything.', reality: 'The modern meaning of “cynic” describes distrust of human motives. The Greek Cynics were not pessimists. They were optimistic about what a person can achieve by simple living and honest effort, and were harsh mainly on pretension and hypocrisy.' },
    ],
    works: [
      { title: 'Writings attributed to Diogenes (lost)', note: 'Ancient lists credit him with dialogues, tragedies and a Republic, but none survives, and it is unclear how many he actually wrote. Letters under his name are later forgeries.' },
      { title: 'Diogenes Laertius, Lives of the Eminent Philosophers, Book VI', note: 'The main collection of anecdotes about Diogenes and the early Cynics, written in the third century AD.' },
      { title: 'Plutarch, Life of Alexander and other essays', note: 'Preserves the best-known version of the meeting with Alexander.' },
      { title: 'Dio Chrysostom, Discourses', note: 'A Greek orator of the first century AD who wrote speeches featuring Diogenes and Alexander.' },
      { title: 'Epictetus, Discourses', note: 'The Stoic teacher’s admiring portrait of the ideal Cynic, an important later view of the tradition.' },
    ],
    legacy: [
      'Diogenes’s follower Crates of Thebes, together with Crates’s wife Hipparchia, kept Cynicism alive, and Crates taught Zeno of Citium, who founded Stoicism. The Stoics adopted much of the Cynic emphasis on virtue, simplicity and independence from fortune, while softening its public shock tactics. Cynic-style street preachers remained a visible presence in the Roman world for centuries.',
      'In later centuries the Cynic became a symbol of the outsider who tells the truth to power. Diogenes appears in countless paintings and stories, from the Renaissance to modern philosophy. His life poses a question that remains uncomfortable: how much of what we chase do we need, and how much do we simply imitate?',
    ],
  },
  {
    slug: 'epicurus',
    order: -341,
    dates: '341 – 270 BC',
    place: 'Samos, then Athens',
    era: 'Ancient',
    tradition: 'Epicureanism',
    tagline: 'He taught that a good life means simple pleasures, good friends and freedom from fear.',
    who: [
      'Epicurus was born on the island of Samos in 341 BC, to Athenian parents, Neocles and Chaerestrate, who lived there as colonists. He is said to have turned to philosophy at about fourteen, and studied under the Platonist Pamphilus and then the Democritean Nausiphanes. After serving his term as a young man in Athens, he taught in Mytilene on Lesbos and in Lampsacus on the Asian coast, where he won his first followers. Around 307 or 306 BC he bought a house with a garden in Athens and settled there. “The Garden” became the name of both the property and the school.',
      'The Garden was unusual. Its members, who included Metrodorus, Hermarchus and a woman named Leontion, lived modestly together and studied, and women and slaves were admitted. Hostile ancient writers spread stories that the community was immoral, but these rumours are not supported by reliable evidence. Epicurus seems to have been loved by his friends, and the school kept a strong loyalty to his teachings for centuries, celebrating his birthday each month.',
      'Diogenes Laertius says he wrote about three hundred scrolls, among them a huge work On Nature in thirty-seven books. Only a little survives: three letters (to Herodotus, to Pythocles and to Menoeceus), two collections of sayings called the Principal Doctrines and the Vatican Sayings, and fragments recovered from papyri at Herculaneum. He died in 270 BC. Diogenes Laertius quotes a letter to his friend Idomeneus, whose authenticity is debated, in which he says that on his last day, though he is tormented by kidney trouble, his soul rejoices in the memory of their conversations.',
    ],
    context: [
      'Epicurus lived in the generation after Alexander the Great. The old world of independent city-states had given way to large kingdoms ruled by Alexander’s successors, and ordinary people felt less control over their lives. Philosophy was increasingly asked not just to explain the world but to give peace of mind in an uncertain one. Epicureanism, Stoicism and Scepticism all grew in this setting, and each offered a way to find tranquillity.',
      'Epicurus built on the atomism of Democritus, which he learned through Nausiphanes, but he put it to a practical purpose. If the world is made of atoms moving in void, he argued, then natural events need no divine explanation, the gods do not threaten us, and the soul does not outlast the body, so there is nothing to fear after death. Knowledge of nature was valuable to him because it frees us from fear.',
    ],
    ideas: [
      { title: 'Pleasure, understood simply', text: 'Epicurus held that pleasure is the highest good, but he defined it mainly as the absence of pain in the body (aponia) and of disturbance in the mind (ataraxia). The pleasures he valued most were quiet ones, such as a satisfied stomach, good company and an untroubled mind. He argued that once pain and want are removed, more luxury only varies the pleasure and does not increase it, and that a wise person can feel happy even on simple food.' },
      { title: 'Sorting desires', text: 'He divided desires into those that are natural and necessary, such as food, shelter and friendship, those that are natural but not necessary, such as fine dishes, and those that are empty, such as the desire for fame or unlimited wealth, which have no natural limit and so can never be satisfied. A good life, he said, is organised around the first kind and cautious about the others.' },
      { title: 'Death is nothing to us', text: 'In his Letter to Menoeceus, Epicurus argues that death is the end of sensation, and that what lacks sensation is nothing to us. While we exist death is not present, and when death is present we do not exist. Fear of death, he thought, spoils life more than any other fear, and understanding this removes it. Later Epicureans summed up their medicine for the soul in four lines: do not fear the gods, do not worry about death, what is good is easy to get, and what is terrible is easy to endure.' },
      { title: 'Atoms, the gods and the swerve', text: 'Like Democritus, he held that everything is made of atoms and void. The gods exist, he said, but they are blessed and undisturbed beings who take no part in human affairs, so there is no reason to fear punishment or to bargain for favours. To make room for free will, later sources say, Epicurus added the swerve, a tiny random deviation in the paths of atoms. Our main evidence for the swerve is Lucretius and Cicero, not Epicurus’s own surviving writings, and scholars debate its exact role.' },
      { title: 'Friendship and justice', text: 'Of everything wisdom provides for a happy life, Epicurus says in the Principal Doctrines, by far the most important is the possession of friends. He also taught that justice is not a cosmic order but an agreement among people not to harm one another, useful because it brings security. He advised many followers to keep away from politics, which brings anxiety, though this is sometimes summed up as “live unnoticed”, a slogan that later critics attacked.' },
    ],
    principles: [
      'Tell natural, necessary desires apart from empty ones.',
      'A little is enough, and what is enough is easy to get.',
      'Do not fear death or the gods.',
      'Invest in friendship, since it is the greatest source of security and joy.',
      'Study nature to free your mind from needless fear.',
    ],
    practice: [
      'Before buying or chasing something, ask which kind of desire it comes from: natural and necessary, natural but optional, or empty.',
      'When you are afraid of something, ask what would actually be painful about it, and when, and whether the worry is worse than the thing.',
      'Make time for a few close friends, with simple meals and good conversation, as Epicurus’s Garden did.',
    ],
    facts: [
      'Today “epicurean” can mean a lover of fine food, but Epicurus himself reportedly lived on bread, water and a little cheese. In a letter quoted by Diogenes Laertius, he asks a friend to send a small pot of cheese so he can feast whenever he wishes.',
      'On his last day, Diogenes Laertius says, he took a warm bath, drank some unmixed wine, and told his friends to remember his teachings.',
      'According to the Roman writer Seneca, the Garden’s keeper welcomed visitors with a simple barley cake and water, and a sign promised that pleasure is the highest good there.',
      'In the early second century AD, a wealthy follower named Diogenes of Oenoanda had a huge summary of Epicurean teaching carved on a wall in his town in what is now Turkey.',
      'The Vatican Sayings were identified in a manuscript in the Vatican Library in the nineteenth century, and the Herculaneum papyri, carbonised by the eruption of Vesuvius in AD 79, are still being read with modern imaging.',
      'Dante places Epicurus and his followers in a burning tomb in the Inferno, among the heretics, because they denied that the soul survives death.',
    ],
    myths: [
      { myth: 'Epicurus taught a life of feasting and indulgence.', reality: 'His own writings praise simple food, moderation and calm. The charge came from rival schools, especially the Stoics, and later from Christian writers, and it stuck. The Roman poet Horace jokingly called himself a pig from Epicurus’s herd.' },
      { myth: 'Epicurus said that the gods do not exist.', reality: 'He held that the gods exist but are blessed beings who do not care about human affairs. Critics in antiquity suspected that this was a polite cover for atheism, and the question is still debated.' },
      { myth: 'The Epicureans wanted people to withdraw from the world altogether.', reality: 'Epicurus was cautious about public life, but he valued friendship and community highly and ran an active school. His withdrawal was from ambition and anxiety, not from other people.' },
    ],
    works: [
      { title: 'On Nature (fragments)', note: 'His large main work in thirty-seven books, known only from fragments of papyrus found at Herculaneum.' },
      { title: 'Letter to Menoeceus', note: 'His short summary of ethics: how to live, why not to fear death, and how to deal with desires.' },
      { title: 'Letters to Herodotus and Pythocles', note: 'Summaries of his physics and of how to explain the heavens. The authenticity of the Pythocles letter has been questioned.' },
      { title: 'Principal Doctrines and Vatican Sayings', note: 'Two collections of short sayings, made for memorisation.' },
      { title: 'Lucretius, On the Nature of Things', note: 'A Roman poem in six books that sets out Epicurean thought in verse, and the best long account we have.' },
    ],
    legacy: [
      'Epicureanism spread across the Greek and Roman world and lasted for around six centuries. In Rome it won followers such as Lucretius, Philodemus and Horace and drew criticism from Cicero, and in the Middle Ages it was largely condemned. In the seventeenth century Pierre Gassendi worked to revive and Christianise it, and it fed into early modern science and the new atomic philosophy of Robert Boyle.',
      'Later thinkers took from it many things: the idea that a good life rests on modest means, the view that pleasure and pain matter for ethics, and the belief that society is a contract. Thomas Jefferson called himself an Epicurean, and Karl Marx wrote his doctoral dissertation on Democritus and Epicurus. Today Epicurus is read as one of the first philosophers of tranquillity and secular happiness.',
    ],
  },
  {
    slug: 'zeno-of-citium',
    order: -334,
    dates: 'c. 334 – c. 262 BC',
    place: 'Citium, Cyprus, then Athens',
    era: 'Ancient',
    tradition: 'Stoicism',
    tagline: 'The founder of Stoicism, who taught in a painted colonnade and made virtue the only true good.',
    who: [
      'Zeno was born around 334 BC in Citium, a city on the south coast of Cyprus with a mixed Greek and Phoenician population. Ancient writers sometimes called him a Phoenician, and modern scholars debate how Greek or Phoenician his background was. His father, Mnaseas, is said to have been a merchant. According to Diogenes Laertius, Zeno was shipwrecked while carrying a cargo of purple dye and arrived in Athens, where he lost his fortune. Tradition says he afterwards declared that he had made a prosperous voyage.',
      'The story of how he came to philosophy is also told by Diogenes Laertius. Sitting in a bookseller’s shop he read the second book of Xenophon’s Memorabilia, about Socrates, and asked where such men could be found. The Cynic Crates happened to be passing, and the bookseller told him to follow him. Zeno became Crates’s pupil, and he also studied with Stilpo of Megara and with members of Plato’s Academy, including Xenocrates and Polemo. The details may be embellished, but it is clear that Zeno drew on Cynic, Socratic and Platonic ideas.',
      'Around 301 BC Zeno began teaching in the Stoa Poikile, the “Painted Porch”, a colonnade decorated with paintings on the north side of the Athenian agora. His followers were first called Zenonians and then Stoics, “people of the porch”. He taught there for nearly forty years. Diogenes Laertius says the Athenians held him in such honour that they voted him a gold crown and a public tomb, and that King Antigonus Gonatas of Macedon admired him. Tradition says he died around 262 BC after a fall, and Laertius reports that he took his own life. His successor was Cleanthes, followed by Chrysippus, who developed the system in great detail.',
    ],
    context: [
      'Zeno taught in the age of the Hellenistic kingdoms, after Alexander’s conquests had linked Greece to Egypt and the East. Athens was no longer a great power but remained the centre of philosophy, and he competed there with Plato’s Academy, Aristotle’s Lyceum and Epicurus’s Garden. In a world where individuals had less say in how kingdoms were ruled, Stoicism offered a form of freedom that no ruler could remove: the freedom to judge and choose well.',
      'Zeno’s own writings are lost, apart from fragments, and our knowledge of early Stoicism comes from quotations in later authors such as Cicero, Diogenes Laertius and Plutarch. This means that it is often hard to tell which ideas belong to Zeno and which to his successors, especially Chrysippus. Scholars generally credit Zeno with the basic framework: philosophy as logic, physics and ethics, and ethics built on the claim that virtue alone is good.',
    ],
    ideas: [
      { title: 'Philosophy in three parts', text: 'Zeno divided philosophy into logic, physics and ethics, and later Stoics compared this to an egg, a garden or an animal, in which each part supports the rest. Logic, which includes the study of knowledge, trains the mind to judge truly. Physics studies the nature of the cosmos, and ethics studies how to live. The Stoics believed that to live well one must understand the world one lives in.' },
      { title: 'A rational, living universe', text: 'The Stoics held that the cosmos is a single, living, rational whole, shaped throughout by a divine reason or Logos, a word taken over from Heraclitus. Everything that happens belongs to a connected order. The wise person accepts this order and does not fight it. This is the source of the Stoic phrase about living in agreement with nature, and Zeno’s successor Cleanthes made explicit that this means in agreement with nature as a whole and with our own nature as rational beings.' },
      { title: 'Virtue is the only true good', text: 'For Zeno, wisdom, justice, courage and self-control are the only things that are truly good, and vice the only thing truly bad. Health, wealth, reputation and even life itself are “indifferents”: not what makes a life good or bad. He allowed that some of them are “preferred”, since it is natural to choose health over sickness, but he held that they cannot make us happy or unhappy. Because virtue is within our control, happiness is too.' },
      { title: 'Emotions are judgments', text: 'The Stoics taught that destructive emotions, or passions, such as rage, panic and greed, arise from mistaken judgments about what is good or bad. If you think that losing money is a real evil, you will fear it. Zeno is reported to have defined a passion as an excessive impulse against reason, and later Stoics refined the idea. The aim was not to feel nothing: later Stoics described good feelings such as joy and goodwill, which belong to the wise.' },
      { title: 'One community of reason', text: 'Because all humans share reason, Stoics held, we belong to a single community. Zeno’s lost Republic, written under the influence of the Cynics, described an ideal society without temples, law courts or money, and, according to later ancient sources, aimed at all humanity in one city of wise people. Details are uncertain, and later Stoics were sometimes embarrassed by its radical claims. But the idea of a shared humanity became a basis for the Stoic ideals of cosmopolitanism and duty.' },
    ],
    principles: [
      'Do not be carried away by first impressions. Examine them before you agree.',
      'Value virtue above fortune.',
      'Accept what you cannot change, and do your duty in what you can.',
      'Treat every person as a fellow member of one community of reason.',
      'Listen more than you speak.',
    ],
    practice: [
      'When something upsets you, pause and ask what judgment you are making about it, and whether it is true.',
      'Sort a worry into what is up to you and what is not, and spend your energy on the first.',
      'At the end of a hard day, ask whether you acted with justice, courage and self-control, which in the Stoic view are the only measures that count.',
    ],
    facts: [
      'Diogenes Laertius records Zeno as saying that we have two ears and one mouth so that we may hear more and say less.',
      'He is said to have called a friend “another I”.',
      'The shipwreck story ends with Zeno saying that he made a prosperous voyage when he suffered shipwreck, because it brought him to philosophy.',
      'The Athenians reportedly honoured him with a gold crown, a public tomb and a decree praising his example of virtue, which Diogenes Laertius quotes.',
      'King Antigonus Gonatas of Macedon invited him to his court. Zeno declined because of his age, and sent two followers instead.',
      'A later story says that Zeno tripped as he left the school, broke a toe, struck the ground and said “I am coming of my own accord; why do you call me?”, and then ended his own life. The story is told by a late source and may be a legend.',
    ],
    myths: [
      { myth: 'Zeno of Citium is the Zeno of the paradoxes about Achilles and the tortoise.', reality: 'That was Zeno of Elea, a pupil of Parmenides who lived more than a century earlier. The two are often confused.' },
      { myth: 'Stoics are people who feel no emotion.', reality: 'The Stoics sought to be free of harmful passions arising from false judgments, but they valued love of family and friends, goodwill and joy. The modern meaning of “stoic” as unfeeling is a simplification.' },
      { myth: 'We can read Zeno’s own writings to learn Stoicism.', reality: 'His books are lost and survive only in fragments quoted by others. Most of what we call Stoicism comes from later Roman writers such as Seneca, Epictetus and Marcus Aurelius, who lived centuries after Zeno.' },
    ],
    works: [
      { title: 'Republic (lost)', note: 'His best-known work, in which he outlined an ideal community in the Cynic spirit. Known only from reports.' },
      { title: 'Other lost works', note: 'Diogenes Laertius lists titles such as On Life in Accordance with Nature, On Impulse, On Passions, On Duty and On Law.' },
      { title: 'Diogenes Laertius, Lives, Book VII', note: 'Our fullest ancient biography of Zeno, with quotations from his decree of honour and summaries of Stoic teaching, written about five hundred years later.' },
      { title: 'Cicero, On Ends and Academica', note: 'Roman accounts of Stoic teaching, including Zeno’s famous comparison of knowledge to the hand closing into a fist.' },
      { title: 'Collected fragments of the early Stoics', note: 'Modern scholars gather the surviving quotations in editions such as Hans von Arnim’s Stoicorum Veterum Fragmenta, published in the early twentieth century.' },
    ],
    legacy: [
      'Stoicism became one of the most influential philosophies of the ancient world. Cleanthes and Chrysippus developed it in the Hellenistic period, and in Rome it shaped statesmen and writers, among them Seneca, Epictetus and Marcus Aurelius, whose works survive and are still widely read. The Stoic ideas of natural law and of a community of all human beings influenced Roman law and later thinking about human rights.',
      'In modern times Stoicism has found a new audience. Cognitive behavioural therapy, developed in the twentieth century by Albert Ellis and Aaron Beck, draws on the Stoic claim that emotions follow from our judgments, and Ellis acknowledged Epictetus as an inspiration. Whatever Zeno himself said in detail, the philosophy he began in a painted porch in Athens remains a practical guide to steadiness.',
    ],
  },
]
