import type { Profile } from './types'

export const EASTERN_ANCIENT: Profile[] = [
  {
    slug: 'laozi',
    order: -600,
    dates: 'traditionally 6th century BC',
    place: 'Chu and the Zhou court, China (traditional)',
    era: 'Ancient',
    tradition: 'Taoism',
    tagline: 'The “Old Master” credited with the Tao Te Ching, a short book on the strength of softness and the wisdom of not forcing things.',
    who: [
      'Laozi, “Old Master”, is the name attached to the Tao Te Ching (Daodejing), a book of 81 very short chapters. The oldest biography is in the Records of the Grand Historian by Sima Qian, written around 100 BC, centuries after the events it describes. It says Laozi’s family name was Li and his personal name Er, that he came from Chu in the south, and that he served as a keeper of archives at the royal court of Zhou. In one famous episode Confucius visits him to ask about ritual, and afterwards compares him to a dragon, a creature he cannot grasp. Sima Qian adds that some people said Laozi lived more than a hundred and sixty years, a sign of how much legend had already gathered around him.',
      'According to the same account, Laozi grew tired of the decline of Zhou and rode west on an ox. At a mountain pass the keeper, Yinxi, asked him to write down his teaching before he vanished from the world. Laozi wrote a book in two parts of about five thousand characters, then left, and nobody knew where he died. It is a wonderful story, and it is almost certainly a story: Sima Qian himself admits that he is unsure who Laozi really was, and he lists other candidates, including a man called Lao Laizi and a court historian named Dan.',
      'Modern scholars therefore disagree sharply. Some think there may have been a historical teacher behind the name, perhaps an older contemporary of Confucius. Others think “Laozi” is a legendary figure, and that the Tao Te Ching is a collection of sayings that grew over time and reached its familiar form in the fourth to third centuries BC. Everything said about his life below the level of “the book exists, and the name attached to it is Laozi” should be read as tradition, not as established fact.',
    ],
    context: [
      'The traditional Laozi belongs to the Spring and Autumn period, when the Zhou kings had lost real power and regional states fought for land. The book, whoever wrote it, belongs more probably to the Warring States period, a time of larger armies, harsher punishments and ambitious rulers. Many thinkers of the “Hundred Schools” offered cures for the disorder: Confucius proposed moral education and ritual, Mozi proposed impartial care, and the Legalists proposed strict laws and rewards.',
      'The Tao Te Ching answers in a different voice. Instead of telling people to build better institutions, it suggests that much of the trouble comes from too much striving, too much interference and too much display. Its answer is to return to the natural pattern, the Tao, that governs the world before human schemes are laid over it. The later writer Zhuangzi, who lived in the fourth century BC, developed this outlook in stories and humour, and Han historians later grouped both under the name of Taoism.',
    ],
    ideas: [
      { title: 'The Tao, the Way', text: 'The book opens by saying that the Way that can be spoken of is not the constant Way. The Tao is the nameless source and pattern of all things, deeper than any description. It is not a god who gives orders but something closer to the way the world works when it is left to work, and the text suggests we do best when we follow it.' },
      { title: 'Wu wei, acting without forcing', text: 'Wu wei, often translated “non-action”, does not mean doing nothing. It means acting in harmony with the situation instead of pushing against it, the way a skilled boatman uses the current. The text claims that much of what we achieve by force is undone by the resistance it creates, while patient, well-timed action succeeds almost unnoticed.' },
      { title: 'The strength of the soft', text: 'Water is the favourite image: it is gentle, it takes the lowest place, and yet nothing wears away stone as well. The book also notes that living things are soft and flexible while the dead are stiff, and it draws the conclusion that rigidity is a sign of decay. The lesson is to be yielding, patient and persistent.' },
      { title: 'The use of emptiness', text: 'Chapter 11 observes that a wheel is useful because of the empty hole at its hub, a pot because of the space inside, a room because of its doors and windows. What we see gives advantage, the passage says, but what is not there gives use. The same thought underlies the praise of the “uncarved block”, a simple, unspoiled state that has not yet been shaped by ambition and fashion.' },
      { title: 'Opposites, humility and the quiet ruler', text: 'Beautiful and ugly, long and short, high and low arise together and define each other, so grasping at one side creates the other. The wise person therefore keeps to the humble position, does not compete and does not boast. In politics this becomes the ideal of the ruler whom the people hardly notice, so that when the work is done they say that they did it themselves.' },
    ],
    principles: [
      'Do not force it: look for the way things already want to move.',
      'Be like water: yielding, patient and persistent.',
      'Know when enough is enough, and do not chase more than you need.',
      'Lead by stepping back, and let others take the credit.',
      'Return to simplicity: a journey of a thousand miles begins with a single step.',
    ],
    practice: [
      'Before pushing hard on a stubborn problem, stop and ask where the resistance is coming from, and whether a gentler approach would work.',
      'Spend a few minutes each day doing nothing in particular, and notice what the empty space does for the rest of the day.',
      'When you are in charge of a task, try to organise it so well that others feel they achieved the result themselves.',
    ],
    facts: [
      'The name “Laozi” simply means “Old Master”, and may be an honorific and not a personal name.',
      'The oldest known copies of the text are bamboo strips found at Guodian in 1993, from a tomb dated to around 300 BC. They contain only about a third of the later book, which suggests that the text grew over time.',
      'Two silk copies from a tomb sealed in 168 BC were found at Mawangdui in 1973. They put the second half of the book (the De) before the first (the Dao), the reverse of the standard order.',
      'The Tao Te Ching has been translated into English hundreds of times, beginning with an early version published in 1868.',
      'A later Taoist text claims that Laozi went on to India and taught the Buddha. Buddhists naturally disputed it, and historians treat it as a legend.',
      'During the Tang dynasty (618–907 AD) the imperial family, whose surname was Li, claimed descent from Laozi.',
    ],
    myths: [
      { myth: 'Laozi was a historical figure who wrote the Tao Te Ching in one sitting at a mountain pass.', reality: 'The pass story is a legend recorded centuries later. The text shows signs of gradual growth, and scholars debate whether Laozi lived at all.' },
      { myth: 'Wu wei means laziness or doing nothing.', reality: 'The text praises effective action that goes with the grain of a situation. It warns against forcing and meddling, not against effort as such.' },
      { myth: 'The Tao Te Ching is simply a book of relaxed self-help.', reality: 'It is also a book about government, and it includes remarks on war and on rulers. Its “small country with few people” image is a political ideal, not just a lifestyle tip.' },
    ],
    works: [
      { title: 'Tao Te Ching (Daodejing)', note: 'The book attributed to Laozi: 81 short chapters, roughly five thousand Chinese characters, in verse-like prose.' },
      { title: 'Guodian and Mawangdui manuscripts', note: 'The earliest surviving copies, from about 300 BC (bamboo) and about 168 BC (silk), which show how the text changed.' },
      { title: 'Sima Qian, Records of the Grand Historian, chapter 63', note: 'The earliest biography, written about 100 BC, with the Confucius meeting and the pass story, and with an honest admission of doubt.' },
      { title: 'Commentaries by Wang Bi and Heshang Gong', note: 'Two early commentaries, the first philosophical and the second more religious and practical, which shaped how the book was read for centuries.' },
      { title: 'Zhuangzi', note: 'A fourth-century BC collection of stories and arguments, the other great early Taoist text, which often mentions Laozi.' },
    ],
    legacy: [
      'The Tao Te Ching shaped Chinese poetry, painting, medicine and political thought. Its images of water and emptiness appear throughout East Asian art, and its ideas of balance and non-forcing mixed with Buddhism as that religion arrived in China, helping to produce Chan, known in Japan as Zen. From the Han period Laozi was also worshipped within religious Taoism as a divine being, Laojun, a development quite separate from the philosophy.',
      'Today it is one of the most translated books in the world, read as philosophy, poetry, management advice and spiritual guidance. Readers disagree about what it teaches, and that variety is part of its appeal: it is short, mysterious and open to many readings. Its steady message, that we often do better by yielding than by forcing, remains a useful counterweight to a culture of constant effort.',
    ],
  },
  {
    slug: 'the-buddha',
    order: -563,
    dates: 'traditionally c. 563 – 483 BC; many scholars place his death c. 400 BC',
    place: 'Lumbini (now Nepal) and the Ganges plain of northern India',
    era: 'Ancient',
    tradition: 'Buddhism',
    tagline: 'A teacher who left a life of comfort to understand suffering, and who taught a path between indulgence and self-denial.',
    who: [
      'Siddhartha Gautama was born into the Shakya clan, in the Lumbini region at the foot of the Himalayas, in what is now Nepal. His father Suddhodana was a leading figure of the clan, and tradition describes a sheltered, comfortable youth, a marriage to Yashodhara and the birth of a son, Rahula. An inscription set up by the emperor Ashoka at Lumbini around 249 BC says that the Buddha was born there, which is one of the few solid pieces of early evidence.',
      'The earliest accounts, written down much later, say that at twenty-nine he left home after seeing an old man, a sick man and a dead man, the “four sights”, and then a wandering ascetic. He studied with two meditation teachers, Alara Kalama and Uddaka Ramaputta, and then practised severe fasting with five companions. When he judged that extreme self-denial was not leading to insight, he began eating again and sat in meditation beneath a tree at Bodh Gaya. There, tradition says, he attained awakening (bodhi) and became “the Buddha”, the Awakened One.',
      'He is said to have given his first teaching to his five former companions at Sarnath, near Varanasi, and to have spent some forty-five years walking and teaching across the kingdoms of the Ganges plain, including Magadha and Kosala. He founded a community of monks and, after some hesitation according to the texts, an order of nuns. He died at about eighty at Kushinagar, after a meal given by a smith named Cunda. The traditional dates of 563–483 BC are now widely doubted: a conference of scholars in the 1980s favoured a death date within about twenty years of 400 BC.',
    ],
    context: [
      'Northern India in the sixth and fifth centuries BC was changing fast. Cities and trade were growing along the Ganges, small tribal republics such as the Shakyas were being swallowed by larger kingdoms such as Magadha and Kosala, and old ways of life were being questioned. A wide movement of wandering teachers, the shramanas, had left home to search for liberation from the cycle of rebirth. Some taught harsh asceticism, some taught that everything is fixed by fate, and some taught that nothing can be known.',
      'The priestly tradition of the Vedas and the early Upanishads, which stressed ritual sacrifice and, increasingly, inner knowledge, was a powerful background. The Jain teacher Mahavira is traditionally a contemporary. The Buddha spoke to this crowded intellectual world, accepting ideas such as karma and rebirth but rejecting the authority of the Vedas, the claims of birth to spiritual rank, and both extremes of luxury and mortification.',
    ],
    ideas: [
      { title: 'The Four Noble Truths', text: 'The first teaching is framed like a medical diagnosis. There is suffering or unsatisfactoriness (dukkha); it has a cause, in craving and clinging; it can come to an end; and there is a path that leads to that end. The point is practical: to understand a problem in order to cure it.' },
      { title: 'The Middle Way and the Eightfold Path', text: 'The path avoids both indulgence in pleasure and extreme self-denial. It is usually listed as right view, intention, speech, action, livelihood, effort, mindfulness and concentration, and it is grouped under three headings: ethical conduct, meditation and wisdom. It treats freedom as something trained in daily life, not a belief to be accepted.' },
      { title: 'Impermanence and non-self', text: 'Everything that arises passes away, including the body, feelings, thoughts and the sense of “I”. The Buddha taught that what we call a self is a changing collection of processes (the five aggregates), not a fixed soul, and that clinging to the idea of a permanent self is a root of suffering. Seeing this clearly was said to bring release.' },
      { title: 'Karma and dependent origination', text: 'In the Buddha’s teaching, karma is intentional action: what matters is the intention behind what we do, which shapes our future states of mind and circumstances. He also described how things arise in dependence on conditions, in a chain of causes that begins with ignorance and ends in suffering, and that can be unwound.' },
      { title: 'Compassion and testing for yourself', text: 'Kindness towards all beings, without exception, is central to the ethics he taught. The texts also record a famous passage to a group called the Kalamas, advising them not to accept a teaching merely because of tradition, a teacher or hearsay, but to test whether it leads to harm or to well-being.' },
    ],
    principles: [
      'Look closely at your own mind: much of our suffering comes from how we react.',
      'Hold things lightly, since everything changes.',
      'Act from good intentions, because intention shapes character.',
      'Avoid extremes: neither indulgence nor harsh self-denial brings peace.',
      'Test a teaching by its fruits, not by its authority.',
    ],
    practice: [
      'Sit quietly for a few minutes and simply watch your breath and your thoughts, noticing that thoughts arise and pass away.',
      'When you feel a strong craving or aversion, name it and notice how it feels in the body before deciding whether to act.',
      'Wish well, silently, to a person you find difficult, as a simple exercise in kindness.',
    ],
    facts: [
      '“Buddha” is a title meaning “awakened one”. “Gautama” is his family name and “Siddhartha” his personal name.',
      'His teachings were handed on by memory for several centuries. The Pali Canon was first written down in Sri Lanka around the first century BC.',
      'In the parable of the poisoned arrow, a wounded man refuses treatment until he knows who shot him; the Buddha says to pull out the arrow first. He used it to explain why he left certain metaphysical questions unanswered.',
      'In another parable he compared his teaching to a raft: useful for crossing a river but not to be carried on your back once you have reached the other side.',
      'The traditional last words in the account of his death say that all conditioned things pass away, and urge his followers to strive on with diligence.',
      'The meal that preceded his death is described in the texts as a dish whose name is unclear; scholars and traditions have disagreed over whether it was pork or a kind of mushroom.',
    ],
    myths: [
      { myth: 'The Buddha was a god, and Buddhists worship him as the creator.', reality: 'The early texts present him as a human teacher who found a way to freedom, not as a creator. Later devotion, ritual and the idea of many Buddhas developed over the centuries and differ across traditions.' },
      { myth: 'The cheerful fat “laughing Buddha” statue shows Siddhartha Gautama.', reality: 'That figure is generally identified as Budai, a folk figure from Chinese tradition, linked to a monk who is said to have lived around the tenth century AD.' },
      { myth: 'Buddhism teaches that life is only suffering.', reality: 'Dukkha is a diagnosis, not the whole story. The Four Noble Truths end with a cure, and the texts speak often of joy, calm and compassion.' },
    ],
    works: [
      { title: 'No writings by the Buddha', note: 'He taught orally, and his sayings were gathered by his followers and memorised, with the first council said to have been held soon after his death.' },
      { title: 'The Pali Canon (Tipitaka)', note: 'The collection of discourses, monastic rules and philosophical analysis preserved by the Theravada tradition, written down in Sri Lanka in the first century BC.' },
      { title: 'Dhammacakkappavattana Sutta', note: 'The “Setting in Motion of the Wheel of Dhamma”, the traditional account of his first sermon at Sarnath.' },
      { title: 'Mahaparinibbana Sutta', note: 'The account of his last journey, death and the cremation of his body.' },
      { title: 'Dhammapada', note: 'A short anthology of verses on mind, conduct and freedom, among the most widely read Buddhist texts.' },
    ],
    legacy: [
      'The emperor Ashoka, who ruled much of India in the third century BC, supported Buddhism and sent envoys abroad, and the teaching spread to Sri Lanka and Southeast Asia and, by way of the Silk Road, to Central Asia, China, Korea and Japan. As it travelled it divided into major traditions, including Theravada, Mahayana and Vajrayana, each with its own texts and practices. Today it is followed by hundreds of millions of people.',
      'Buddhist ideas about the mind have found new audiences in modern times. Meditation techniques have been adapted into secular mindfulness programmes in hospitals and schools, such as the stress-reduction course developed in 1979, and philosophers have compared the doctrine of non-self with modern accounts of the mind. Whether one follows it as a religion, a philosophy or a set of exercises, the Buddha’s central question, how to live well with change and loss, still draws readers.',
    ],
  },
  {
    slug: 'confucius',
    order: -551,
    dates: '551 – 479 BC',
    place: 'Lu (now Shandong, China)',
    era: 'Ancient',
    tradition: 'Confucianism',
    tagline: 'A teacher who made learning, humane character and good example the foundation of a decent society.',
    who: [
      'Confucius is the Latin form of Kong Fuzi, “Master Kong”. His given name was Kong Qiu, and he was born in 551 BC in or near the town of Zou, in the state of Lu, in what is now Shandong province. According to Sima Qian, his father, an older soldier, died when the boy was young, and the family lived in modest circumstances. Confucius later remarked that his poor origins had taught him many practical skills. He is said to have held minor posts, including work with granaries and livestock, before rising to office in Lu.',
      'Around 500 BC he held a high post in Lu, with traditions saying he became a minister of justice, but his attempt to weaken the great noble families who dominated the state failed, and he left Lu about 497 BC. For roughly fourteen years he travelled with a group of disciples among neighbouring states, looking for a ruler who would put his ideas into practice. He was sometimes honoured and sometimes in danger, and no ruler gave him real power. He returned to Lu around 484 BC and spent his last years teaching and, according to tradition, working on the old classics. He died in 479 BC.',
      'He regarded himself as a transmitter of the wisdom of earlier sages and not as an inventor of a new doctrine. His conversations with disciples, among them Yan Hui, Zilu, Zigong and Zengzi, were collected after his death in the Analects. Scholars note that the book was assembled over a long period and that some parts are later than others, so the “historical Confucius” is partly reconstructed from layers of tradition.',
    ],
    context: [
      'Confucius lived in the later part of the Spring and Autumn period. The Zhou kings, once rulers of a unified realm, had lost most of their power, and regional states, such as Lu, Qi, Jin and Chu, competed and warred. Within the states, power often passed from the rulers to powerful noble families, and rank and ritual no longer matched reality. Many educated men were employed as advisers, scribes and officials, and Confucius belonged to that class of people who lived by learning.',
      'He admired the early Zhou rulers as a golden age and believed order could be restored by moral example and proper ritual, not by fear or by force. This was a hopeful but also conservative vision. After his death the school he founded became one of the main currents in the Hundred Schools of Thought that flourished in the Warring States period, alongside Mohism, Taoism and Legalism.',
    ],
    ideas: [
      { title: 'Ren, humaneness', text: 'Ren is the central virtue: goodwill, empathy and care for other people, expressed in everyday conduct. It cannot be learned from rules alone, and it is built through practice in the family, in friendship and in public life. Asked what it meant, he answered, according to the Analects, that it is to love people.' },
      { title: 'Reciprocity', text: 'Asked whether there was one word that could guide a whole life, Confucius gave the answer “shu”, often translated as reciprocity: what you do not wish for yourself, do not do to others. It is one of the earliest versions of the golden rule, in a negative form, and it makes a practical test for how to treat anyone.' },
      { title: 'Li, ritual and propriety', text: 'Li covers ceremony, courtesy and the many small forms of respect that shape social life. Confucius insisted that ritual without sincerity is empty, but he also believed that good forms shape character: by practising respect we grow into respectful people. Good manners, in this view, are a school of the heart.' },
      { title: 'The exemplary person and government by virtue', text: 'The ideal is the junzi, a person of moral character, who deserves authority because of character and not birth alone. A ruler who leads by example, he argued, will be followed freely, while one who relies on punishments will only make people avoid wrongdoing without shame. He also stressed that governing begins with putting names and roles in order: a ruler should act as a ruler, a parent as a parent.' },
      { title: 'Learning and self-cultivation', text: 'Almost anyone, in his view, can become better through lifelong learning, reflection and practice. He taught students from many backgrounds, and the Analects records his remark that in education there are no classes. He also warned that learning without thinking is useless, and thinking without learning is dangerous.' },
    ],
    principles: [
      'Treat others as you would like to be treated.',
      'Study, and reflect on what you study.',
      'Lead by example, since people copy what you do.',
      'Admit what you do not know: that is what knowing really is.',
      'Cultivate yourself a little each day, starting with your closest relationships.',
    ],
    practice: [
      'Each evening, ask yourself three questions in the spirit of his disciple Zengzi: have I been faithful to others, have I been trustworthy with friends, and have I practised what I was taught?',
      'Before judging someone, apply the test of reciprocity: would I want to be treated this way in their place?',
      'Pick one small courtesy, such as listening without interrupting, and practise it for a week until it becomes natural.',
    ],
    facts: [
      '“Confucius” is a Latinised form of “Kong Fuzi”, created by Jesuit missionaries in the late sixteenth century.',
      'He summed up his life in stages: at fifteen he set his heart on learning, at thirty he took his stand, at forty he had no doubts, at fifty he knew the will of Heaven, and at seventy he could follow his heart’s desires without overstepping what was right.',
      'He described himself as one who “transmits but does not create”, and as a lover of the ancient ways.',
      'When asked about serving the spirits, he is reported to have said that one who cannot yet serve people cannot serve spirits, and to have declined to say much about death.',
      'His favourite pupil Yan Hui died young, and the Analects records the master’s deep grief.',
      'The Temple, Cemetery and Family Mansion of Confucius at Qufu are now a World Heritage Site.',
    ],
    myths: [
      { myth: 'Confucius wrote the Analects and a great many of the proverbs credited to him.', reality: 'The Analects was compiled by disciples and later generations. Many sayings that circulate online as “Confucius say” do not appear in it, including popular lines about doing a job you love.' },
      { myth: 'Confucianism is simply a teaching of blind obedience.', reality: 'Confucius stressed duties, but he also expected rulers to be moral, and the Analects advises a minister to oppose a ruler openly if the ruler is wrong, without deceiving him.' },
      { myth: 'Confucius edited and wrote all the Five Classics.', reality: 'Later tradition said so, but modern scholars doubt that he composed or edited them all, and his connection to the Spring and Autumn Annals in particular is debated.' },
    ],
    works: [
      { title: 'The Analects (Lunyu)', note: 'Short conversations and sayings gathered by disciples and later followers. It is the main source for his teaching and one of the most influential books in history.' },
      { title: 'The Five Classics', note: 'The ancient books of poetry, documents, rites, changes and spring and autumn annals that Confucian tradition linked to him as a teacher and editor.' },
      { title: 'Sima Qian, Records of the Grand Historian', note: 'The first full biography, written about four hundred years after his death, with much legend mixed with fact.' },
      { title: 'The Four Books', note: 'A later grouping by the Song scholar Zhu Xi: the Analects, the Mencius, the Great Learning and the Doctrine of the Mean, which shaped education for centuries.' },
    ],
    legacy: [
      'Confucius’s influence grew slowly. In the Han dynasty, under Emperor Wu (r. 141–87 BC), Confucian learning was placed at the centre of state education, and in later dynasties the Confucian classics became the basis of the civil service examinations, which lasted until 1905. In this way the ideas of an unemployed teacher shaped the values of the Chinese state and of Korea, Japan and Vietnam for roughly two thousand years.',
      'His reputation has been debated in modern times. Chinese reformers of the early twentieth century often blamed Confucian tradition for holding the country back, the Cultural Revolution attacked it, and more recently it has been revived as a source of national heritage. Whatever one thinks of that politics, his core ideas, that character is built by learning and practice, that example is more powerful than command, and that society is held together by mutual respect, remain a living part of East Asian culture.',
    ],
  },
  {
    slug: 'sun-tzu',
    order: -544,
    dates: 'traditionally c. 544 – c. 496 BC; the book is probably later',
    place: 'Qi and Wu (traditional); the historical details are uncertain',
    era: 'Ancient',
    tradition: 'Chinese military thought',
    tagline: 'The name on the most famous book of strategy ever written, though we know very little about the man.',
    who: [
      'Sun Tzu, in modern spelling Sunzi, “Master Sun”, is the name attached to The Art of War, a short Chinese treatise on warfare and strategy. The traditional biography is found in the Records of the Grand Historian by Sima Qian, written around 100 BC, which is several centuries after the events it describes. According to it, Sun Wu was a native of the state of Qi who presented his thirteen chapters to King Helü of Wu, and went on to help Wu defeat the powerful state of Chu in the early fifth century BC.',
      'The most famous anecdote is the story of the palace women. To test his theory, King Helü asked Sun Wu to train 180 women of his court as soldiers. When they laughed at his orders, Sun Wu had the two women who had been made commanders, the king’s favourites, executed, and after that the rest drilled perfectly. The story is vivid but may be a teaching tale, since it makes the point that a general’s orders must be obeyed. The much earlier Zuo Zhuan, a detailed chronicle of the period, never mentions Sun Wu, even though it describes the same wars, and this silence leads many historians to doubt the traditional biography.',
      'The honest summary is that we do not know whether a man called Sun Wu existed, and if he did, we cannot tell what he wrote. Scholars generally date the surviving text to the early Warring States period, perhaps from around 500 to 430 BC or even later, and some believe it was compiled by one or more later authors who drew on a growing body of military knowledge. A separate treatise, also called Master Sun’s Art of War, is attributed to Sun Bin, a strategist of the fourth century BC who was perhaps a descendant of the same family. The two were long confused.',
    ],
    context: [
      'In the Spring and Autumn period war was largely a matter of aristocratic charioteers and limited campaigns. By the Warring States period, from the fifth century BC, it had changed: the states were larger, they raised armies of tens of thousands of infantry, campaigns lasted longer, and professional generals appeared. Wars at that scale were very costly. The Art of War itself notes that an army of a hundred thousand costs a thousand pieces of gold a day.',
      'This new kind of war encouraged writing about it. Strategy was no longer only the business of nobles who inherited command. Rulers sought advisers who could win battles with fewer losses, and a new genre of military writing arose, of which The Art of War is the most famous example. The book also reflects the intellectual world of its time: it speaks of “the Way”, of Heaven and Earth, and of flexibility and change, in language that echoes the philosophical schools.',
    ],
    ideas: [
      { title: 'The best victory avoids the fight', text: 'The book says that to subdue the enemy without fighting is the highest skill, and that the best strategy is to attack the enemy’s plans, then alliances, then armies, and to attack walled cities only as a last resort. War damages the state that wins as well as the state that loses, and the text warns that no country has ever benefited from prolonged war. This is a calculation of cost, but it also reflects a hope for restraint.' },
      { title: 'Know yourself and know the enemy', text: 'A commander who knows both himself and his opponent will not be in danger in a hundred battles, while one who knows only himself will win and lose by turns, and one who knows neither will be beaten every time. The book opens by listing the factors to weigh before war: the moral Way that unites ruler and people, the weather and season, the terrain, the quality of the commander and the system of organisation.' },
      { title: 'War is the way of deception', text: 'All warfare is based on deception, the book says: when able, appear unable; when near, appear far. The aim is to mislead the opponent about your strength and intentions so that he commits mistakes. Deception is paired with preparation, and the book insists that you should not rely on the enemy not coming, but on being ready to meet him.' },
      { title: 'Be formless like water, and use momentum', text: 'A good commander adapts to circumstances, as water takes the shape of the ground it flows over. The book stresses shi, a word that can mean momentum or strategic advantage, such as the force of a boulder rolling downhill. Victory comes less from brute strength than from placing yourself in a position where the situation itself favours you.' },
      { title: 'Information and spies', text: 'The last chapter argues that foreknowledge cannot be got from spirits or from reasoning by analogy, but from people who know the enemy’s situation. It describes five kinds of spies, including local agents, inside agents and double agents, and says that rulers should reward them well. The book treats the cost of failing to obtain information as far greater than the cost of paying for it.' },
    ],
    principles: [
      'Prepare thoroughly: victory is usually decided before the battle begins.',
      'Win without fighting whenever you can.',
      'Understand both your own strengths and weaknesses and those of your opponent.',
      'Stay flexible: adapt to the situation, as water adapts to the ground.',
      'Value information, and take care of the people you lead.',
    ],
    practice: [
      'Before entering a negotiation or a dispute, write down what you know about your own position and what you know about the other side, and note what you are guessing.',
      'Ask whether you can reach your goal without a confrontation: a conversation, a compromise or an alliance may cost much less.',
      'Count the costs of a prolonged struggle honestly, including the time, the goodwill and the relationships it will use up.',
    ],
    facts: [
      'In 1972 archaeologists excavating Han dynasty tombs at Yinqueshan in Shandong found bamboo strips, sealed in the second century BC, that include parts of The Art of War and also the long-lost treatise of Sun Bin. This showed that there really were two separate works.',
      'The warlord Cao Cao (155–220 AD) wrote one of the earliest surviving commentaries on the book, and in the eleventh century it was included in the Seven Military Classics, the official collection of military texts.',
      'The book reached Europe in 1772, when the French Jesuit Jean Joseph Marie Amiot published a translation. The first annotated English translation, by Lionel Giles, appeared in 1910.',
      'The Japanese warlord Takeda Shingen (1521–1573) is said to have used a banner with a line from the book’s chapter on manoeuvre: swift as the wind, calm as a forest, fierce as fire and steady as a mountain.',
      'The text consists of thirteen short chapters, from “Laying Plans” on assessment and planning to “The Use of Spies” on intelligence, and it can be read in an hour or two.',
    ],
    myths: [
      { myth: 'Sun Tzu was a single general who wrote the book himself in the sixth century BC.', reality: 'The only biography is late and partly legendary. Scholars think the text was written or assembled at least a century later, and it may have grown over time.' },
      { myth: 'The Art of War teaches ruthless aggression and winning at any cost.', reality: 'The book is cautious about war. It calls it a matter of life and death for the state, prefers victory without battle, and warns about the cost of long campaigns.' },
      { myth: 'Lines such as “Every battle is won before it is ever fought” or “Opportunities multiply as they are seized” are genuine quotations.', reality: 'These popular lines do not appear in the text. The nearest real idea is that victorious armies win first and then go to war.' },
    ],
    works: [
      { title: 'The Art of War (Sunzi bingfa)', note: 'Thirteen short chapters on planning, resources, attack, formation, momentum, weakness and strength, manoeuvre, adaptation, terrain, the nine grounds, fire attack and spies.' },
      { title: 'Sima Qian, Records of the Grand Historian, chapter 65', note: 'The earliest account of Sun Wu’s life, with the story of the palace women, written about four hundred years after his supposed lifetime.' },
      { title: 'The Yinqueshan bamboo manuscripts', note: 'The 1972 discovery that gave early evidence for the text and recovered Sun Bin’s separate treatise.' },
      { title: 'Cao Cao and other commentaries', note: 'A tradition of commentary, beginning with Cao Cao, that shaped how generations of readers understood the book.' },
      { title: 'Translations by Giles (1910) and Griffith (1963)', note: 'Two influential English versions, the second by a US Marine Corps officer, which brought the book to a wide Western audience.' },
    ],
    legacy: [
      'For more than two thousand years The Art of War has been read by Chinese commanders and scholars, and it was studied in Japan, Korea and Vietnam too. Its stress on information, deception and speed has been quoted by military writers around the world, and it is still taught in military academies. Chinese military authors of the twentieth century, among them Mao Zedong, were familiar with it.',
      'In recent decades it has also become a bestseller for business and politics, with managers, lawyers and sports coaches quoting it. Such uses often stretch the book beyond its original setting and can lose its warnings about caution and the costs of conflict. As a work of strategy it offers a few durable ideas: prepare, gather information, avoid needless fights and remain adaptable. As a work of history, it reminds us how much can be attached to a name about which very little is known.',
    ],
  },
  {
    slug: 'mozi',
    order: -470,
    dates: 'c. 470 – c. 391 BC (approximate)',
    place: 'Probably Lu (now Shandong), active in Song, Chu and other states, China',
    era: 'Ancient',
    tradition: 'Mohism',
    tagline: 'A craftsman-philosopher who argued that we should care for everyone alike and that war is organised crime.',
    who: [
      'Mozi, “Master Mo”, whose personal name was Mo Di, is the founder of Mohism, a school that rivalled Confucianism in the Warring States period. We know little about his life. Sima Qian gives him only a brief mention, and the dates, around 470 to 391 BC, are approximate. He seems to have come from Lu or Song and, according to many scholars, from the artisan class, and the book that bears his name shows a strong interest in crafts, defence and engineering. Some have suggested that “Mo” may even refer to the ink line of a carpenter, while others link it to a punishment tattoo, and nobody knows for certain.',
      'Later tradition says that Mozi first studied Confucian teachings and then broke with them, objecting to their elaborate funerals, their love of ritual music and their belief in fate. He gathered a following that was unusually disciplined: its members lived plainly, shared a common set of doctrines, took orders from a leader and travelled to serve as advisers or as defenders of small states under threat. The Mozi records a famous episode in which he walked for ten days to the state of Chu to stop an attack on Song. He is said to have defeated the engineer Gongshu Ban in a mock siege and to have revealed that his disciples were already on Song’s walls with his defensive designs.',
      'The book of the Mozi was not written by Mozi alone. It was compiled by his followers over generations, and of an original seventy-one chapters roughly fifty survive. The core chapters present ten doctrines, many of them in three versions, probably from different Mohist groups. Because of this, the Mozi is as much a record of a movement as of one man, and the detailed stories about his life should be read with care.',
    ],
    context: [
      'Mozi lived in the years after Confucius, when the Zhou kings were weak and the Chinese states fought one another with increasing violence. Larger states were swallowing smaller ones, armies were growing, and ordinary people paid in lives and taxes. Many of the philosophers of the time asked how to restore order, and Mozi’s answer was radical: order comes from caring for everyone’s welfare and from ending the privileges of birth.',
      'He also lived at a time of social change in which skilled people from outside the old aristocracy could rise as advisers and officials. Mohism, with its emphasis on talent, practical benefit and defence, appealed to this world. It was one of the two most prominent schools of the age, Confucianism and Mohism, according to the later writer Han Feizi, and for a while it must have seemed a serious rival for the future of Chinese thought.',
    ],
    ideas: [
      { title: 'Impartial care', text: 'Mozi’s best-known doctrine, jian ai, is often translated “universal love” but is better rendered impartial or inclusive care. He argued that most of the world’s troubles come from partiality, from people favouring themselves, their family or their state at the expense of others. If we cared for others’ welfare as we do our own, the argument goes, there would be much less theft, quarrelling and war. Defenders note that he did not ask people to abandon their families, only to extend real concern outwards.' },
      { title: 'Against offensive war', text: 'Mozi pointed out that people condemn a thief who takes a neighbour’s peaches, and condemn a murderer even more, yet they praise a ruler who invades another country. The logic, he said, is that the greater the harm, the worse the crime, so a war of conquest is crime on a vast scale. He did not oppose all fighting: the Mohists defended weaker states against attack, and they became known for their skill in siege defence.' },
      { title: 'Promote the worthy', text: 'Offices, Mozi argued, should go to people of ability and virtue, whatever their birth, and even farmers and craftsmen should be raised if they deserve it. A ruler who gives posts to relatives and favourites wastes the talent of the state. This was a striking idea in an age when rank was largely inherited, and it is one source of the later idea that government should be run by merit.' },
      { title: 'Benefit as the test', text: 'Mozi judged practices by whether they benefit the people, by increasing wealth, population and order. By this test he attacked costly funerals, long mourning and elaborate music as wasteful, and he urged frugality in clothing, food and building. His opponents found this harsh, and later writers criticised him for ignoring the role of music and ritual in the inner life.' },
      { title: 'Heaven’s will and the three standards', text: 'Mozi believed that Heaven, and also the spirits, cares for all people alike and rewards good and punishes evil, which gave his doctrine of impartial care a religious foundation. He rejected fatalism, the view that outcomes are fixed in advance, because it discourages effort. To test any teaching, he proposed three standards: its basis in the examples of the ancient sage kings, its agreement with what ordinary people have seen, and its practical benefit when used in government.' },
    ],
    principles: [
      'Ask of any rule or custom: who does it actually help?',
      'Extend your concern beyond your own circle.',
      'Judge people by ability and character, not by birth or connections.',
      'Do not call something right for a crowd that you would call wrong for one person.',
      'Do not wait for fate: effort and good conduct change outcomes.',
    ],
    practice: [
      'When you are about to defend a decision, test it with Mozi’s question: would I accept the same reasoning if the roles were reversed?',
      'Look at one of your regular expenses or habits and ask honestly whether it brings real benefit to anyone.',
      'When hiring, choosing a teammate or giving credit, look for ability and effort first and set aside favouritism.',
    ],
    facts: [
      'Mencius attacked Mozi sharply, saying that his impartial care amounted to “having no father”, and that Mozi would have been willing to wear himself out from head to heel if it benefited the world.',
      'The Mohists formed a tightly organised group, led by a chief known as the juzi, who was said to pass the position on to his chosen successor.',
      'The later Mohist writings, the Canons, contain early Chinese work on logic, language, geometry, optics and mechanics, including definitions of a point and an account of how a pinhole forms an inverted image.',
      'The school nearly vanished after the Qin unification in 221 BC and in the early Han period. The Mozi survived in poor condition, and it was only in the nineteenth century, through the scholarship of men such as Sun Yirang, that it was properly edited.',
      'In 2016 China launched the first quantum communication satellite, named Micius after Mozi.',
    ],
    myths: [
      { myth: 'Mozi was a pacifist who opposed all war.', reality: 'He opposed aggressive war but supported defence, and his followers trained as military engineers to protect weaker states.' },
      { myth: 'Impartial care means you should love strangers exactly as you love your family.', reality: 'Scholars debate this, but Mohists were concerned with equal consideration in conduct and policy. They also kept to ideas of filial duty, and the doctrine is more a principle of fair treatment than a demand for identical feelings.' },
    ],
    works: [
      { title: 'The Mozi', note: 'The main text, compiled by followers: roughly fifty of seventy-one chapters survive, including the core doctrines, the Canons and the chapters on defence.' },
      { title: 'The core chapters on the ten doctrines', note: 'Chapters, many in three versions, on impartial care, condemning aggression, promoting the worthy, frugality, Heaven’s intent and more.' },
      { title: 'The Mohist Canons and Explanations', note: 'Later Mohist chapters on logic, argument, mathematics and the natural sciences.' },
      { title: 'The Mencius and Han Feizi', note: 'Sources of criticism and comment that show how Mozi was seen by rivals in the Warring States period.' },
      { title: 'Sima Qian, Records of the Grand Historian', note: 'Gives only a brief mention of Mozi, evidence of how little reliable biography survives.' },
    ],
    legacy: [
      'Mohism has been called one of the first systematic ethics of consequences in world philosophy. It put forward ideas, such as equal concern, promotion by merit, and judging practices by their benefits, that later thinkers admired. In its time it was heavily criticised, in particular by Mencius, who defended the special obligations owed to family, and the school lost out to Confucianism, which offered a more familiar vision of ritual and family and, under Han rulers, state backing.',
      'After more than a thousand years of neglect, Mozi was rediscovered by Chinese scholars in the late Qing period and early twentieth century, and he was read as a forerunner of modern ideas of equality, science and logic. His arguments against war, his insistence that rulers justify policies by their effect on ordinary people, and his demand that leaders be chosen for ability have lost none of their force.',
    ],
  },
  {
    slug: 'mencius',
    order: -372,
    dates: 'traditionally c. 372 – c. 289 BC (other dates are given)',
    place: 'Zou (now Shandong, China); travelled to Liang, Qi and other states',
    era: 'Ancient',
    tradition: 'Confucianism',
    tagline: 'The Confucian who argued that human nature is good and that a ruler who betrays the people loses the right to rule.',
    who: [
      'Mencius, in Chinese Mengzi, “Master Meng”, was born Meng Ke in the small state of Zou, near Confucius’s home state of Lu. The usual dates are about 372 to 289 BC, but sources vary by a few years. A tradition recorded in the Han dynasty says that his father died early and that his mother raised him with great care, moving house three times, from a cemetery to a market and finally to a place near a school, so that he would grow up among good influences. It is a charming story, and probably a moral tale, but it shows how the Chinese tradition came to see his mother as a model parent.',
      'Later accounts say that he studied with followers of Zisi, the grandson of Confucius. Like Confucius, he spent years travelling from court to court trying to persuade rulers to govern with humaneness. He visited King Hui of Liang and spent time in the state of Qi, serving there as an adviser to King Xuan, probably between about 319 and 312 BC. He also visited Teng and other states. He was treated with respect and listened to politely, but the rulers, who were busy with war and expansion, mostly ignored his advice to rule through moral example.',
      'Disappointed, he withdrew from public life, according to Sima Qian, and spent his last years teaching and discussing with disciples. The book that bears his name, the Mencius, records his conversations and debates in seven books, and was probably put together by his disciples. Its style is more lively and argumentative than the Analects: Mencius answers kings, debates rival thinkers and uses stories, analogies and sharp questions.',
    ],
    context: [
      'Mencius lived in the middle of the Warring States period, when seven large states competed for supremacy. Ambitious rulers were hiring advisers who promised wealth and military power, and those who preached moral cultivation were often seen as impractical. The Legalist statesman Shang Yang had already reformed Qin around 350 BC with strict laws and rewards for military service, while the followers of Mozi preached impartial care.',
      'Within this climate Mencius took up the task of defending and developing Confucius’s teaching. He faced the philosophy of Yang Zhu, which stressed looking after oneself, and that of Mozi, who wanted equal care for all, and he argued that both distorted human nature. He also had to answer the question the Analects had left open: if people can become good, what in human nature makes this possible? A later Confucian, Xunzi, answered differently, so that the debate continued for generations.',
    ],
    ideas: [
      { title: 'Human nature is good', text: 'Mencius held that people are born with the beginnings of virtue, which he called four sprouts: the feeling of compassion, which grows into benevolence; of shame, into righteousness; of deference, into propriety; and of approval and disapproval, into wisdom. His famous example is a person who suddenly sees a small child about to fall into a well: anyone would feel alarm and pity, he says, not from calculation but from the heart. The argument is that goodness is natural, though it needs care to grow.' },
      { title: 'Cultivation, not force', text: 'Sprouts can be damaged, as in his image of Ox Mountain, once covered with trees but stripped by cutting and grazing, until people think it was always bare. Good character likewise needs nourishment and protection. He also warned against impatience in a story of a farmer from Song who pulled at his shoots to help them grow, and so killed them. Moral growth takes steady, patient effort.' },
      { title: 'Righteousness before profit', text: 'In the first chapter of the book, King Hui of Liang asks how Mencius can benefit his state. Mencius replies that the king should speak only of benevolence and righteousness, because if everyone from the king to the commoner pursues profit, the state will be in danger. He taught that some things, including righteousness, can matter more than life itself, and he used the image of a fish and a bear’s paw: if you cannot have both, take the one that matters more.' },
      { title: 'Government that cares for the people', text: 'A good ruler provides for the people’s livelihood, with fair taxes and light punishments, so that they can feed their families, and only then educates them. He argued that people cannot be expected to keep to morality if they are starving. He proposed a “well-field” system of land use, in which families farm shared plots, as a way to secure a fair living. He is also known for saying that the people are most important, the altars of the state next, and the ruler least.' },
      { title: 'The Mandate of Heaven and the right to remove a tyrant', text: 'When a king asked whether a subject may kill his ruler, as the founders of the Zhou dynasty had done to the last Shang king, Mencius answered that he had heard of killing a villain named Zhou, but not of killing a ruler. A ruler who destroys benevolence and righteousness has become a mere fellow, and loses the Mandate of Heaven. This was among the boldest statements of the Confucian tradition, and later rulers found it uncomfortable.' },
    ],
    principles: [
      'Trust that the beginnings of goodness are within you, and nurture them.',
      'Do not rush growth: patient effort works better than pulling on the shoots.',
      'Put what is right before what is profitable.',
      'Provide for people’s needs before demanding virtue of them.',
      'A leader who betrays those who depend on him loses his claim to lead.',
    ],
    practice: [
      'When you feel a spontaneous impulse to help, notice it and act on it, since Mencius thought that is how good character is built.',
      'Look at a goal you are impatient about and ask whether you are trying to force results that need steady care.',
      'Before taking a decision for gain, ask whether it is also right, and which of the two you would choose if you could only have one.',
    ],
    facts: [
      'Mencius is often called the “Second Sage” of Confucianism, after Confucius himself.',
      'The Mencius became one of the Four Books, grouped with the Analects, the Great Learning and the Doctrine of the Mean by the Song scholar Zhu Xi, and it was later a basic text for the civil service examinations.',
      'The book is divided into seven sections, each split into two halves, and many of its best-known passages are dialogues with kings.',
      'He described a “flood-like qi”, a vast moral energy that, he said, grows in a person who accumulates righteous deeds and cannot be forced.',
      'The story of the mother who moved house three times and who is also said to have cut up her loom cloth to teach her son perseverance is one of the most familiar in Chinese education.',
    ],
    myths: [
      { myth: 'Mencius thought people are born perfectly good and need no education.', reality: 'He believed that only the sprouts of virtue are innate. They must be cultivated and can be neglected, damaged or lost, which is why he put so much weight on education and good government.' },
      { myth: 'Mencius supported democracy and the right to revolt, in the modern sense.', reality: 'He argued that a tyrant loses Heaven’s mandate and can be removed, but the removal was to be carried out by a virtuous figure acting for Heaven and the people, not by votes or popular assemblies.' },
      { myth: 'Mencius and Xunzi disagreed about whether education matters.', reality: 'They both thought that education and ritual were essential. Where they differed was on human nature itself: Xunzi held that people are born with selfish tendencies that need shaping.' },
    ],
    works: [
      { title: 'The Mencius (Mengzi)', note: 'Seven books of dialogues, debates and sayings, compiled by disciples, with famous passages on human nature, government and the way of the true king.' },
      { title: 'Zhao Qi’s commentary', note: 'A second-century AD commentary, the oldest complete one, which helped keep the text alive.' },
      { title: 'Zhu Xi, Collected Commentaries on the Four Books', note: 'The twelfth-century commentary that made the Mencius a core text of later Confucian education.' },
      { title: 'Sima Qian, Records of the Grand Historian', note: 'Gives a short biography, with the later view that Mencius retired to write with his disciples.' },
    ],
    legacy: [
      'In his own time Mencius did not have much political success, but his reputation grew. Later Confucians, especially in the Song dynasty, made him central, with the Mencius taking its place among the Four Books and his view of human nature becoming the standard Confucian one. His ideas of innate moral sensitivity, and of cultivating it, influenced neo-Confucian thinkers such as Zhu Xi and Wang Yangming and shaped moral education in China, Korea, Japan and Vietnam.',
      'Today he is read by philosophers of ethics and psychology as an early defender of a view that moral feelings are natural and can be developed, and by political thinkers for his claim that rulers exist for the sake of the people. The debate between him and Xunzi, and the question they both asked, how people become good, is still an open and fruitful one.',
    ],
  },
  {
    slug: 'chanakya',
    order: -350,
    dates: 'traditionally 4th – 3rd century BC (dates uncertain)',
    place: 'Taxila and Pataliputra (Magadha), India, according to later tradition',
    era: 'Ancient',
    tradition: 'Indian political thought',
    tagline: 'The legendary minister to the first Maurya emperor, whose name is attached to the Arthashastra, India’s great treatise on statecraft.',
    who: [
      'Chanakya, also called Kautilya or Vishnugupta, is remembered in Indian tradition as the Brahmin adviser who helped Chandragupta Maurya overthrow the Nanda dynasty of Magadha around 321 BC and build the Maurya Empire, and who then served as his chief minister. It is an unusually dramatic story, but the sources for it are late. Buddhist, Jain and Kashmiri retellings and a Sanskrit play, the Mudrarakshasa, were written centuries after the events, in some cases a thousand years or more, and they differ in details. The Greek ambassador Megasthenes, who visited Chandragupta’s court, does not mention him in the fragments that survive.',
      'According to these stories, Chanakya taught at Taxila in the north-west and was insulted at the Nanda court in Pataliputra, so he swore to destroy the dynasty. He found a young man of ability, Chandragupta, trained him and, through diplomacy, intrigue and war, put him on the throne. In one Jain version, he fed Chandragupta tiny amounts of poison so that he would be immune to it, with disastrous consequences for the emperor’s wife. Such tales are better seen as legend than as biography.',
      'The honest position is therefore that we know almost nothing about Chanakya as a person. Chandragupta is a real, well-attested figure, who ruled from about 320 to 297 BC and made a treaty with the Greek ruler Seleucus around 305 BC. Whether a minister called Chanakya stood beside him, and what exactly he did, comes only from later tradition. Even the identification of Chanakya with Kautilya, the name attached to the Arthashastra, was made by later writers.',
    ],
    context: [
      'Northern India in the fourth century BC was dominated by the kingdom of Magadha, in the Ganges basin, ruled by the Nanda dynasty. Alexander of Macedon’s campaign reached the north-west in 326 BC, shaking the political order there. Out of this world of rival kingdoms and rapid change, the Mauryas built the first empire to unite most of the subcontinent, with Pataliputra as capital. Their administration was large, with armies, taxes, roads, mines and officials stretching across wide territories.',
      'India already had a tradition of reflecting on kingship, in the Dharmashastra literature and the epics, and the Arthashastra refers to earlier teachers and schools of politics. It sits in a different tradition from that of the religious law books. Artha, material well-being and power, was recognised as one of the aims of life alongside dharma (duty) and kama (pleasure), and the Arthashastra is the major surviving treatise on artha, a manual of how to rule and keep a state secure and prosperous.',
    ],
    ideas: [
      { title: 'Why there must be government', text: 'The Arthashastra uses the image of the “law of the fishes”: without a ruler to keep order, the strong swallow the weak, as big fish eat small ones. A ruler who wields punishment (danda) fairly and in proportion protects the weak and makes social life possible. The text treats the rod as a necessary tool but warns that excessive severity makes the ruler hated.' },
      { title: 'The seven elements of the state', text: 'The text analyses a kingdom into seven parts: the king, the minister, the territory and people, the fort, the treasury, the army and the ally. A state is strong when all are healthy, and the strength of the whole is limited by its weakest part. This is one of the earliest systematic analyses of what makes a state work, and it goes into detail on how to run each part.' },
      { title: 'The circle of states', text: 'In foreign policy the book imagines a king who aims to expand, the “conqueror”, and sees his immediate neighbour as a natural rival and the neighbour’s neighbour as a natural ally. It lists six measures: peace, war, staying neutral, preparing to march, seeking protection and playing a double game. The advice is to choose whichever suits the balance of strength at the time, and to prefer gains won without costly war.' },
      { title: 'Spies and secrecy', text: 'The treatise gives a great deal of space to spies, informers and secret agents, to the screening of ministers, and to guarding the king from poison and plots. This is the feature that gave the work a reputation for ruthlessness, and the text does describe deceit and assassination as tools of state. Yet it presents them as instruments to protect the realm, often directed at enemies and traitors, and it sets them within a framework that gives rulers duties.' },
      { title: 'The disciplined, servant-minded king', text: 'The king, the Arthashastra says, must first master himself, controlling the six enemies of lust, anger, greed, pride, arrogance and recklessness. He is asked to keep a strict daily routine, to be accessible to petitioners and to act for the benefit of the people. A famous line says that in the happiness of his subjects lies the king’s happiness, and in their welfare his welfare. The state is also responsible for roads, famine relief and care for the helpless.' },
    ],
    principles: [
      'Master yourself before trying to master others.',
      'A leader’s well-being is tied to the well-being of those they lead.',
      'Gather accurate information, and do not rely on appearances.',
      'Weigh the strength of every side before choosing between peace and war.',
      'Be ready: a state or an organisation is only as strong as its weakest part.',
    ],
    practice: [
      'Before taking on a rival or negotiating, list the strengths of each party, including your own weaknesses and those of any allies.',
      'Review your own habits of anger, greed or pride, the “inner enemies”, and note which of them most often affects your decisions.',
      'Organise your day with a clear routine for work and for availability to others, as the text recommends for a ruler.',
    ],
    facts: [
      'The Arthashastra was lost to modern scholars until 1905, when R. Shamasastry, a librarian at the Mysore Oriental Library, identified a palm-leaf manuscript among the library’s holdings. He published the Sanskrit text in 1909 and an English translation in 1915.',
      'It is a large work of fifteen books, 150 chapters and about 180 topics, covering law, taxes, mines, trade, spies, war and the duties of the king.',
      'It has been compared with Machiavelli’s The Prince. The sociologist Max Weber saw it as a classic of unscrupulous statecraft, but unlike Machiavelli it is a full manual of administration, not a short essay.',
      'The Chanakya Niti, a collection of short maxims attributed to Chanakya, is a different work, of uncertain and later date, and many sayings circulating online as “Chanakya quotes” are not found in the Arthashastra.',
      'Chanakyapuri, the diplomatic enclave in New Delhi, is named after him.',
    ],
    myths: [
      { myth: 'Chanakya wrote the Arthashastra for Chandragupta at the Maurya court.', reality: 'Scholars such as Patrick Olivelle argue that the work was put together over several centuries and reached its final form around the second or third century AD. It mentions things such as Chinese silk and coral from Alexandria, and assumes Sanskrit as a language of royal documents, which suggests a later date, though some earlier scholars, such as R. P. Kangle, argued for an older Mauryan core.' },
      { myth: 'The Arthashastra is a handbook of pure amorality, justifying any crime for the king.', reality: 'It does recommend spies and deception, but it also lays down duties for the king, rules on law and justice, relief for the poor and a vision of rule for the welfare of subjects.' },
      { myth: 'We have detailed facts about Chanakya’s life and character.', reality: 'Nearly everything comes from later retellings, which differ from one another, and some parts are plainly fiction.' },
    ],
    works: [
      { title: 'The Arthashastra', note: 'The treatise on statecraft attributed to Kautilya, in fifteen books. It has been dated by many scholars to between about the first century BC and the third century AD.' },
      { title: 'Patrick Olivelle’s translation (2013)', note: 'A modern English edition with an argument about how the text was composed, now regarded as the standard translation.' },
      { title: 'R. P. Kangle’s edition and translation (1960s)', note: 'The scholarly edition on which much later study is based.' },
      { title: 'Mudrarakshasa by Vishakhadatta', note: 'A Sanskrit political drama about Chanakya and the Nanda minister Rakshasa, of uncertain date, from perhaps the fourth to the eighth century AD.' },
      { title: 'Kamandaki’s Nitisara', note: 'A later verse work on politics that summarises and follows the Arthashastra tradition.' },
    ],
    legacy: [
      'The Arthashastra was influential in classical India as a model for later writing on kingship and politics, and it was known to authors in later centuries, but the text itself disappeared from view. When it was found and published in the early twentieth century, it changed how scholars saw ancient India, showing a worldly, detailed tradition of political and economic thought that stood alongside the better-known religious and philosophical writings.',
      'Today Chanakya is a figure of national memory in India, appearing in books, television and political debate, and the Arthashastra is cited in discussions of diplomacy, security and administration. Readers should remember that the legend of the all-knowing adviser and the historical text are not the same thing. The text is best read as a rich, multi-layered work of ancient political science, whose author or authors we cannot identify with certainty.',
    ],
  },
]
