import type { Profile } from './types'

export const ENLIGHTENMENT_B: Profile[] = [
  {
    slug: 'david-hume',
    order: 1711,
    dates: '1711 – 1776',
    place: 'Edinburgh, Scotland',
    era: 'Enlightenment',
    tradition: 'Scottish Enlightenment',
    tagline: 'The Scottish sceptic who asked how much we can really know from experience, and whose questions Kant said woke him from his slumber.',
    who: [
      'David Hume was born in Edinburgh in 1711 and grew up at his family’s modest estate, Ninewells, in the Scottish borders. He entered the University of Edinburgh unusually young, perhaps at ten to twelve years old, and left without a degree. His family expected him to study law, but he later wrote that he felt a strong pull towards philosophy and general learning. In his late teens he suffered a period of mental distress that he linked to this intense reading and thinking.',
      'In the mid-1730s he lived in France, partly at La Flèche in Anjou, where he wrote most of his first and most ambitious book, A Treatise of Human Nature, published in 1739–40 when he was still in his twenties. He later complained that it “fell dead-born from the press”, meaning that it attracted almost no notice. He rewrote its main arguments in shorter, clearer form as the two Enquiries, and he turned to essays and then to history. His six-volume History of England, published between 1754 and 1762, was a bestseller and made him famous as a historian before most readers thought of him as a philosopher.',
      'Hume’s reputation for religious scepticism cost him university posts: he was passed over for chairs at Edinburgh and Glasgow, and opponents accused him of atheism. He took other work instead, as a tutor, a diplomat’s secretary, and from 1752 as librarian of the Faculty of Advocates in Edinburgh, where he had a large library at his command. He spent some time in Paris in the 1760s, where he was warmly received in the salons, and he brought the philosopher Jean-Jacques Rousseau to England in 1766 before the two quarrelled bitterly. He died in Edinburgh in 1776, and James Boswell recorded that he faced death calmly and cheerfully. His friend Adam Smith later published a letter describing his last weeks.',
    ],
    context: [
      'Hume belonged to the Scottish Enlightenment, a remarkable flowering of thought in a small country that had joined England in the Union of 1707. Edinburgh and Glasgow were full of lawyers, ministers, professors and doctors who read widely, argued in clubs, and applied reason to morals, politics, history and economics. Hume’s circle included Adam Smith, the historian William Robertson and the philosopher Thomas Reid, who became his best-known critic.',
      'It was also a time of religious tension. The Church of Scotland still had real power, and in 1697 a young man, Thomas Aikenhead, had been hanged in Edinburgh for blasphemy. Behind Hume’s work stood the success of Newton, whose experimental method inspired him. The subtitle of the Treatise announces an attempt to introduce the experimental method of reasoning into moral subjects, meaning that Hume wanted a science of human nature based on observation instead of speculation.',
    ],
    ideas: [
      { title: 'Knowledge begins in experience', text: 'Hume held that all the materials of thought come from sense experience. Our ideas are fainter copies of the vivid impressions we first receive, and an idea that cannot be traced to any impression should be treated with suspicion. He also separated two kinds of claims: relations of ideas, such as mathematical truths, which can be settled by thinking alone, and matters of fact, which can be learned only from experience. This division is often called Hume’s fork.' },
      { title: 'The problem of induction and the limits of cause', text: 'We say that fire causes heat or that one billiard ball moves another, but Hume pointed out that we never actually observe a necessary connection, only one event regularly following another. Our belief that the future will resemble the past cannot itself be proved by reason without going in a circle, a puzzle now called the problem of induction. In his view we form such expectations through habit, and nature makes us believe them whether or not we can justify them. Scholars still argue over whether he denied that causes exist or only that we can know them.' },
      { title: 'The self as a bundle', text: 'When Hume looked inward, he said, he found only particular perceptions, such as warmth, a thought, a feeling, and never a separate “self” that owns them. He described the mind as a bundle or collection of perceptions linked by memory and resemblance. Later in life he admitted that he was not satisfied with his own explanation of what holds the bundle together, and the question is still debated.' },
      { title: 'Feeling, reason and morality', text: 'Hume wrote that reason is, and ought only to be, the slave of the passions, meaning that reason can show us the means to an end but cannot choose the end itself. Moral judgements, he argued, rest on sentiments of approval and disapproval, shaped by sympathy with others and by what is useful or agreeable. He also noted that writers often slide from statements about what is to statements about what ought to be without explaining the step. This is now known as the is–ought problem.' },
      { title: 'Miracles and religion', text: 'In his essay on miracles he argued that a sensible person should proportion belief to evidence, and that testimony for a miracle must be weighed against the uniform experience that such events do not happen. His Dialogues Concerning Natural Religion examine the argument that the order of the world proves a designer, and he left them unpublished in his lifetime. Readers still disagree about which of the speakers he sides with, so his exact religious views remain a matter of debate.' },
    ],
    principles: [
      'Proportion your belief to the evidence.',
      'Be suspicious of any idea you cannot trace back to experience.',
      'Remember that habit and feeling guide much of life, including your own reasoning.',
      'Hold views with modesty. Hume’s sceptical stance asks us to doubt without becoming paralysed.',
      'Be good company: Hume valued friendship, conversation and good humour as part of a good life.',
    ],
    practice: [
      'When a claim sounds impressive, ask what experience or evidence it rests on, and how often similar claims have turned out true.',
      'Notice when you move from “this is how things are” to “this is how they should be”, and state the value judgement openly.',
      'When you feel certain, ask whether it is argument or habit that gives you the feeling.',
    ],
    facts: [
      'He may have gone to university at ten to twelve, though fourteen was typical at the time.',
      'He called his first book “dead-born from the press”, yet it is now one of the most studied works in the history of philosophy.',
      'In 1761 the Catholic Church placed his works on its Index of Prohibited Books.',
      'Contemporaries sometimes called him “le bon David” in Paris, a nickname that reflects how warmly he was received in the salons, though accounts of it come from later retellings.',
      'He wrote a short autobiography, My Own Life, in 1776, only months before he died.',
      'His Dialogues Concerning Natural Religion were published after his death, in 1779, by his nephew.',
    ],
    myths: [
      { myth: 'Hume was an atheist who denied that anything can be known.', reality: 'He was a sceptic about what reason can prove, not about everyday life, and he insisted that we cannot help believing in the world around us. His religious views are disputed: he attacked arguments for miracles and design, but scholars differ on whether he was an atheist or something closer to an agnostic.' },
      { myth: 'Hume denied that causation exists.', reality: 'He argued that we cannot observe or prove necessary connections, and that our belief in causes comes from habit. Whether he went further and denied that real causes exist is a live scholarly debate.' },
      { myth: 'His remarks about race were only a minor aside that nobody noticed at the time.', reality: 'A footnote added to his essay “Of National Characters” in the early 1750s claimed that non-white peoples were naturally inferior to whites. The Scottish philosopher James Beattie criticised it publicly by 1770, and Hume revised the note in later editions in response, though not in a way that withdrew the claim. Hume also wrote against the harshness of slavery in another essay, and scholars argue about how to weigh these passages.' },
    ],
    works: [
      { title: 'A Treatise of Human Nature (1739–40)', note: 'His first and most ambitious book, on understanding, the passions and morals.' },
      { title: 'An Enquiry Concerning Human Understanding (1748) and An Enquiry Concerning the Principles of Morals (1751)', note: 'Shorter, clearer versions of the Treatise; the first includes the essay on miracles.' },
      { title: 'The History of England (1754–62)', note: 'A six-volume narrative that made him famous and was the standard account for decades.' },
      { title: 'Dialogues Concerning Natural Religion (1779)', note: 'A dialogue about the argument from design, published after his death.' },
      { title: 'My Own Life (1776)', note: 'A brief autobiography written shortly before his death.' },
    ],
    legacy: [
      'Hume shaped almost every major philosopher after him. Immanuel Kant said that Hume interrupted his “dogmatic slumber” and pushed him toward the project of the Critique of Pure Reason. Adam Smith drew on his ideas about sympathy and society. Later, logical positivists in the twentieth century revived his distinction between claims about ideas and claims about facts, and modern philosophy of science still discusses the problem of induction. His thoughts on feeling and morality also influenced later moral theory and psychology.',
      'He remains a philosopher worth reading with open eyes. His sharp, humane style and his habit of testing big claims against experience are admired, and so are his essays, which cover trade, taxes and politics. At the same time, his remarks on race are a serious blot that readers and scholars today discuss openly, and they have led some universities and institutions to rethink how his name is used.',
    ],
  },
  {
    slug: 'adam-smith',
    order: 1723,
    dates: '1723 – 1790',
    place: 'Kirkcaldy, Glasgow and Edinburgh, Scotland',
    era: 'Enlightenment',
    tradition: 'Scottish Enlightenment',
    tagline: 'A moral philosopher who explained how trade, specialisation and self-interest can build a nation’s wealth, and who never thought that was the whole story.',
    who: [
      'Adam Smith was baptised in Kirkcaldy, a small port in Fife, Scotland, on 16 June 1723, and his exact birthday is unknown. His father, a customs official, died before he was born, and he was raised by his mother, to whom he remained close until her death in 1784. A well-known anecdote says that he was briefly carried off by travellers as a small child, though this comes from later retellings. At fourteen he went to the University of Glasgow, where he studied under the moral philosopher Francis Hutcheson, and in 1740 he went to Balliol College, Oxford, on a scholarship. He later criticised the teaching he found there.',
      'After public lectures in Edinburgh in the late 1740s, he became a professor at Glasgow, first of logic and then of moral philosophy. His first book, The Theory of Moral Sentiments (1759), was a success, and he kept revising it until the year of his death. In the mid-1760s he left his chair to tutor the young Duke of Buccleuch on a tour of France, where he met leading French thinkers, and he returned with a pension that gave him time to write.',
      'The Wealth of Nations appeared in March 1776, after about a decade of work, and the first edition sold out in roughly six months. Smith later served as a Commissioner of Customs in Edinburgh, a post that put him in charge of the very kind of tax system he had criticised. He never married and, shortly before he died in 1790, had most of his unpublished papers burned. His friend David Hume was the person closest to him intellectually, and Smith wrote an account of Hume’s last days.',
    ],
    context: [
      'Smith wrote at the start of Britain’s commercial and industrial expansion. Glasgow was prospering on Atlantic trade, and new manufacturing was changing how goods were made. The prevailing economic thinking, which later writers called mercantilism, treated national wealth as a stock of gold and silver and urged governments to promote exports, restrict imports and protect favoured merchants through monopolies.',
      'Smith was also part of a European conversation. He read and met French writers, including the Physiocrats, who argued that wealth came from the land, and he built on the ideas of his friend Hume about trade. In the same year as the Wealth of Nations, the American colonies declared independence, and Smith’s book discusses Britain’s empire and the colonies with a critical eye.',
    ],
    ideas: [
      { title: 'Sympathy and the impartial spectator', text: 'In The Theory of Moral Sentiments, Smith argued that people are naturally interested in the fortunes of others and can imagine themselves in another’s position. We learn right and wrong by picturing how an impartial observer would judge our conduct, and over time we carry an inner version of that observer, which he called the man within the breast. For Smith, conscience is built from social experience.' },
      { title: 'The division of labour', text: 'The Wealth of Nations opens with a small pin factory. Smith reports that ten workers, each doing one or two of about eighteen distinct tasks, could make upwards of forty-eight thousand pins a day, while a single worker doing everything alone could scarcely make twenty. Specialisation, he argued, is the main reason for rising productivity, and it grows as markets widen.' },
      { title: 'Exchange and self-interest', text: 'Smith observed that we expect our dinner not from the benevolence of the butcher, the brewer or the baker, but from their regard to their own interest. Trade lets strangers cooperate without needing to know or like one another. He did not praise selfishness as such. His point was that a system of exchange can turn everyday self-interest into mutual benefit, provided there are fair rules, justice and competition.' },
      { title: 'Against monopoly and mercantilism', text: 'Smith attacked tariffs, trading monopolies and special privileges, arguing that they enrich a few merchants at the expense of consumers and the wider country. He warned that people of the same trade seldom meet without some plot against the public. He preferred what he called a system of natural liberty, in which people are free to pursue their own interest within the rules of justice.' },
      { title: 'A real role for government, and worry about the poor', text: 'Smith assigned the state clear duties: defence, justice, certain public works and, in his view, public education. He feared that a lifetime spent on a few repetitive tasks could dull workers’ minds, and he argued that a society where most people are poor and wretched can hardly be called flourishing. He also thought that employers hold the stronger bargaining position over wages and criticised their combinations.' },
    ],
    principles: [
      'See yourself as an impartial observer would see you.',
      'Cooperation grows when people specialise and trade freely.',
      'Be wary of rules that protect the powerful from competition.',
      'Judge an economy by how well ordinary people live, not by how much gold the state holds.',
      'Combine self-interest with justice, because markets work best within fair rules.',
    ],
    practice: [
      'Before a decision that affects others, picture how a fair, well-informed stranger would judge it.',
      'Notice who benefits from a rule or a price, and whether the benefit comes from real service or from protection against competition.',
      'Ask what you do best and what you rely on others for, and what that dependence is built on.',
    ],
    facts: [
      'The Wealth of Nations was published on the eve of the American Declaration of Independence, in 1776, the same year as the first volume of Gibbon’s Decline and Fall.',
      'Smith used the phrase “invisible hand” only three times in all his writings: once in an essay on the history of astronomy, once in The Theory of Moral Sentiments and once in The Wealth of Nations.',
      'He was a close friend of David Hume, and wrote a moving account of Hume’s death that stirred controversy among religious readers.',
      'He was elected Rector of the University of Glasgow in 1787.',
      'Before he died he had many of his manuscripts destroyed, so we know less about his private thoughts than about his published ones.',
      'He is buried in the Canongate Kirkyard in Edinburgh.',
    ],
    myths: [
      { myth: 'The “invisible hand” is the central idea of Smith’s thought.', reality: 'The phrase appears only three times, and in The Wealth of Nations it occurs once, in a short passage about investors preferring home industry. Its meaning there is limited, and Smith himself never presented it as a general law that markets always serve the public good. The phrase became a slogan largely after his time.' },
      { myth: 'Smith was just an economist who praised greed and wanted government to stay out of everything.', reality: 'He was a professor of moral philosophy and wrote a major book on ethics. He backed the state’s role in justice, defence, public works and education, defended the Navigation Acts for reasons of national defence, and supported legal limits on interest rates. He also used the phrase “system of natural liberty” and never used the word “laissez-faire”, and the word “capitalism” did not exist in his day.' },
      { myth: 'Smith invented economics from nothing.', reality: 'He built on Hume, on French writers such as Quesnay and Turgot, and on earlier thinkers about trade and money. His achievement was to bring many ideas together in a single, readable system, which is why his book became so influential.' },
    ],
    works: [
      { title: 'The Theory of Moral Sentiments (1759)', note: 'His book on ethics, sympathy and the impartial spectator; he revised it through to a sixth edition in 1790.' },
      { title: 'An Inquiry into the Nature and Causes of the Wealth of Nations (1776)', note: 'His great work on production, trade, money, taxes and government, in five books.' },
      { title: 'Essays on Philosophical Subjects (published 1795)', note: 'Posthumous essays, including one on the history of astronomy.' },
      { title: 'Lectures on Jurisprudence', note: 'Student notes of his Glasgow lectures on law and government, discovered and published long after his death.' },
    ],
    legacy: [
      'The Wealth of Nations launched what became classical economics. David Ricardo, John Stuart Mill and later economists built on and argued with it, and Karl Marx treated it as a key text to criticise. Smith’s picture of how specialisation and trade create wealth underlies much of modern economic thinking, and his account of the worth of competition shaped debates about free trade for two centuries.',
      'Since then, both admirers and critics have often cut Smith down to a slogan. Some scholars once spoke of an “Adam Smith problem”, thinking that sympathy in one book contradicted self-interest in the other, but most now see the two as parts of one view of human society. Readers who go back to his own words find a thinker who cared about justice, who distrusted concentrated power in business as well as in government, and who treated economics as part of the study of human beings.',
    ],
  },
  {
    slug: 'immanuel-kant',
    order: 1724,
    dates: '1724 – 1804',
    place: 'Königsberg, Prussia (now Kaliningrad, Russia)',
    era: 'Enlightenment',
    tradition: 'German idealism',
    tagline: 'The philosopher who argued that the mind shapes experience, and that morality rests on duty and respect for persons.',
    who: [
      'Immanuel Kant was born in 1724 in Königsberg, a Baltic port city in East Prussia, and he lived and worked there nearly all his life. His father was a craftsman and his family was devoted to Pietism, a serious, inward form of Lutheran Christianity. He entered the local university at sixteen, in 1740, studied philosophy, mathematics and natural science, and then worked for several years as a private tutor. In 1755 he began lecturing at the university, and he was made professor of logic and metaphysics in 1770, when he was in his mid-forties.',
      'His early writings were on science, including a bold 1755 proposal that the solar system formed from a rotating cloud of matter. After 1770 he published little for about a decade, working on the book that became the Critique of Pure Reason, which appeared in 1781, with a revised second edition in 1787. It met a cool reception at first and then, within a few years, made him the leading philosopher in Germany. A rapid series of works followed, including the Groundwork of the Metaphysics of Morals (1785), the Critique of Practical Reason (1788) and the Critique of the Power of Judgment (1790).',
      'Kant was a popular teacher and a sociable man who reportedly hosted regular dinners, but his daily routine was famously orderly. Stories say neighbours set their clocks by his afternoon walk, though that is probably an exaggeration. In the 1790s he fell foul of Prussian censorship over his writings on religion, and he was reprimanded by the king in 1794. He died in 1804 at the age of 79. Like Hume, he also wrote passages about race that are racist and that most readers now find disturbing, a point discussed below.',
    ],
    context: [
      'Kant lived in the Age of Enlightenment, in a Prussia ruled from 1740 to 1786 by Frederick the Great, who allowed more freedom of discussion than many rulers while expecting obedience in practice. German philosophy was then dominated by a rationalism that tried to prove the great truths of metaphysics, such as God and the soul, by pure reasoning, and Kant was trained in that tradition. In the same years, the British empiricists, above all Hume, argued that all knowledge comes from experience and cast doubt on much of metaphysics.',
      'Kant looked for a way between the two camps. He was impressed by Newton’s physics, which seemed to give certain knowledge of the world, and he asked how such knowledge was possible. He said that reading Hume had interrupted his “dogmatic slumber” and set his thinking in a new direction. His answer, worked out over many years, became known as the critical philosophy.',
    ],
    ideas: [
      { title: 'The mind shapes experience', text: 'Kant compared his approach to the revolution of Copernicus. Instead of assuming that the mind simply receives the world as it is, he proposed that the mind contributes its own structure to experience. Space and time, and basic concepts such as cause and effect, are the ways our minds organise what we perceive. In his words, thoughts without content are empty and perceptions without concepts are blind: we need both.' },
      { title: 'Appearances and things in themselves', text: 'Because the mind shapes experience, Kant distinguished the world as it appears to us (phenomena) from things as they are in themselves, which we cannot know. Science can give us reliable knowledge of appearances, but reason cannot reach beyond them to prove claims about God, the soul or the universe as a whole. He wrote that he had to limit knowledge in order to make room for faith. He did not claim that the world is only in our heads. He held that things exist independently of us, but that we know them only through our own forms of knowing.' },
      { title: 'The categorical imperative', text: 'Kant held that morality is a matter of duty that binds all rational beings, not of personal desire. A hypothetical imperative says “if you want this, do that”, while a categorical imperative commands without conditions. His best-known formulation says to act only on a rule that you could at the same time will to be a universal law. A person who makes a false promise to get out of trouble, for example, relies on others keeping their promises, so the rule undermines itself if everyone follows it.' },
      { title: 'Dignity and autonomy', text: 'A second formulation says to treat humanity, in yourself and in others, always as an end and never merely as a means. For Kant, rational beings have a worth beyond price, because they can set their own goals and give themselves moral laws. This idea of autonomy, meaning self-government by reason, underlies much modern thinking about human dignity and rights. He also held that only a good will, acting from duty, is good without qualification.' },
      { title: 'Enlightenment, republics and perpetual peace', text: 'In a short essay of 1784, Kant defined enlightenment as emerging from self-imposed immaturity, and he urged readers to have the courage to use their own understanding, in the words of the motto he borrowed, “dare to know”. In Perpetual Peace (1795) he argued that peace requires republican governments, a federation of free states and a right of strangers to be treated hospitably. These essays are among the roots of modern ideas about international law and cooperation.' },
    ],
    principles: [
      'Dare to think for yourself.',
      'Act on rules you could want everyone to follow.',
      'Treat people as ends in themselves, never only as tools.',
      'Know the limits of reason as well as its power.',
      'Do the right thing because it is right, not for reward.',
    ],
    practice: [
      'Before acting, state the rule behind your choice and ask whether you would accept everyone following it.',
      'When dealing with others, ask whether you are respecting their ability to choose, or only using them for your goal.',
      'Notice which of your beliefs you hold only because an authority told you to, and test them yourself.',
    ],
    facts: [
      'He wrote that two things filled him with ever-growing wonder: the starry heavens above and the moral law within. The line closes the Critique of Practical Reason and is inscribed on his tomb in Königsberg.',
      'Königsberg was occupied by Russian forces for several years during the Seven Years’ War, from 1758 to 1762, while Kant was a young teacher in the city.',
      'He never married, though he is said to have considered it.',
      'He lectured for decades on physical geography as well as on logic, metaphysics and ethics.',
      'His essay on enlightenment of 1784 borrowed its motto from the Roman poet Horace, in Latin “sapere aude”, meaning dare to know.',
      'His last words are reported, by a later account, to have been “It is good”, though that report should be treated with some caution.',
    ],
    myths: [
      { myth: 'Kant was a dry, solitary recluse who barely noticed the world around him.', reality: 'Königsberg was a busy port with merchants and visitors from many countries, and Kant was reportedly a sociable host and a popular lecturer. His rigid routine is partly legend, and the tale of neighbours setting their watches by him is told as hearsay.' },
      { myth: 'Kant taught that the real world is just an illusion in our heads.', reality: 'He held that things exist independently of us, but that we know them only as they appear through the forms of our own minds. He called this transcendental idealism and explicitly separated it from the claim that the world is nothing but ideas.' },
      { myth: 'Kant’s ethics requires blind obedience to rules, whatever the consequences.', reality: 'The categorical imperative is a test of whether a personal rule could be universal, and one formulation puts respect for persons first. Kant did write a notorious 1797 essay arguing that one may not lie even to a murderer asking where a friend is hiding, and scholars still debate whether that follows from his own theory.' },
    ],
    works: [
      { title: 'Critique of Pure Reason (1781, revised 1787)', note: 'His central work on what reason can and cannot know.' },
      { title: 'Groundwork of the Metaphysics of Morals (1785)', note: 'A short, influential book setting out the categorical imperative.' },
      { title: 'Critique of Practical Reason (1788) and Critique of the Power of Judgment (1790)', note: 'On freedom and morality, and on beauty and purpose in nature.' },
      { title: 'Answer to the Question: What Is Enlightenment? (1784)', note: 'A short essay on thinking for oneself.' },
      { title: 'Toward Perpetual Peace (1795)', note: 'An essay on how lasting peace between states might be achieved.' },
    ],
    legacy: [
      'Kant reshaped Western philosophy. German idealists such as Fichte, Schelling and Hegel began from his ideas, and later neo-Kantians, phenomenologists and many analytic philosophers continued the conversation. His moral philosophy is one of the three or four great frameworks of modern ethics, alongside the traditions that stress consequences and character, and his ideas about dignity and universal law have fed into modern human-rights thinking. His ideas about peace between republics are often cited as ancestors of the League of Nations and the United Nations, though the links are indirect.',
      'His writings on race are an uncomfortable part of that legacy. In the 1770s and 1780s he published essays on human races that ranked groups in a hierarchy with whites at the top. Some scholars, notably Pauline Kleingeld, argue that in the 1790s he dropped this hierarchy and criticised colonialism and slavery, while others think the change was limited. Scholars also argue about whether these views weaken the universal claims of his ethics or only show that Kant failed to live up to them.',
    ],
  },
  {
    slug: 'edmund-burke',
    order: 1729,
    dates: '1729 – 1797',
    place: 'Dublin, Ireland, and England',
    era: 'Enlightenment',
    tradition: 'Conservatism',
    tagline: 'A statesman who defended inherited institutions as the stored wisdom of generations, and warned that revolution can destroy what it cannot rebuild.',
    who: [
      'Edmund Burke was born in Dublin on 1 January 1729, the son of a Protestant lawyer and a Catholic mother. He was educated partly at a Quaker school in Ballitore and at Trinity College, Dublin, and then moved to London to study law, which he gave up for writing. His first books were two published within two years: A Vindication of Natural Society (1756), a satire of the rationalist attacks on established institutions, and A Philosophical Enquiry into the Origin of Our Ideas of the Sublime and Beautiful (1757), an influential work on aesthetics.',
      'He entered Parliament in 1765 as a Whig, one of the party’s reformers, and sat for Wendover, then for Bristol from 1774 and later for Malton. In a famous speech to the Bristol voters in 1774, he argued that a representative owes the people his judgement as well as his industry, and that he betrays them if he sacrifices that judgement to their opinion. His support for Irish trade and for easing restrictions on Catholics cost him votes in Bristol, and he left that seat in 1780. He served briefly as Paymaster of the Forces in 1782 and 1783–84.',
      'Burke spent years campaigning on great causes: he opposed the taxation and coercion of the American colonies, delivering his speech on conciliation in 1775, and he led the impeachment of Warren Hastings, the former governor-general of Bengal, accused of abuse of power in India. The trial began in 1788 and dragged on until Hastings was acquitted in 1795. In 1790 he published Reflections on the Revolution in France, a bestseller that made him the great critic of the Revolution and split his own party. He retired from Parliament in 1794 and died in 1797 at Beaconsfield.',
    ],
    context: [
      'Eighteenth-century Britain was a parliamentary monarchy run largely by aristocratic families, factions and patronage. Burke worked in this system as a Whig, a tradition that defended Parliament’s powers against the Crown, and he argued for party as a way of acting together on shared principles. His native Ireland, under a Protestant Ascendancy, was governed by laws that disadvantaged the Catholic majority, a situation he knew personally and criticised.',
      'Burke’s later career was shaped by upheaval: the quarrel with the American colonies from the 1760s and then, from 1789, the French Revolution. Many British liberals welcomed it at first. Burke was alarmed by it from the start, in part because a sermon by the Dissenting minister Richard Price praised it, and he feared that a break with the past could lead to chaos, terror and military rule. His Reflections were written to warn his readers and also as an answer to Price.',
    ],
    ideas: [
      { title: 'Society is a partnership across generations', text: 'Burke described the state as more than a business deal: it is a partnership in all science, all art and all virtue, a partnership between the living, the dead and those yet to be born. Institutions carry the accumulated experience of many generations, so each generation holds them in trust and should hesitate before tearing them down.' },
      { title: 'Prejudice, prescription and the limits of abstract reason', text: 'Burke distrusted political programmes drawn from abstract theory. He argued that customs and inherited habits, which he called prejudice or prescription, often embody wisdom no single mind could work out in advance. Politics, he said, is a practical art that depends on circumstances, not on geometry-like rules applied to human beings.' },
      { title: 'Reform, not revolution', text: 'Burke is often misread as an enemy of change. He wrote that a state without the means of some change is without the means of its conservation. His ideal was gradual reform that repairs a part while preserving the whole. He supported the American colonists’ case against Britain’s taxes and backed Catholic relief, while condemning the French Revolution’s overthrow of the entire order.' },
      { title: 'The little platoons', text: 'He valued the small groups of ordinary life, such as family, neighbourhood, church and local association, which he called the “little platoons” of society, as the first training in public affection and the basis of love for one’s country. Rapid, abstract reorganisation from above, he feared, would dissolve these bonds.' },
      { title: 'The sublime and the beautiful', text: 'In his youthful Enquiry, Burke argued that the sublime, which he linked to vastness, darkness and the fear of pain, produces a stronger and darker delight than the beautiful, which he linked to smoothness, smallness and gentleness. The book influenced later writers and artists, including Kant, who discussed it, and it helped lay the groundwork for Romantic ideas about awe in nature.' },
    ],
    principles: [
      'Change what you must, preserve what you can.',
      'Be wary of grand schemes built on abstract theory alone.',
      'Respect the wisdom stored in long-standing institutions, while recognising their faults.',
      'Use your own judgement for those you serve, and do not simply follow the crowd.',
      'Value small communities as the school of public spirit.',
    ],
    practice: [
      'Before removing a rule or tradition, find out why it was created and what it still does.',
      'When you want to improve something, try a small change first and see what follows.',
      'If you lead or represent others, tell them honestly what you think instead of only repeating their views.',
    ],
    facts: [
      'He was born in Dublin with a Protestant father and a Catholic mother, which shaped his lifelong interest in Irish Catholic relief.',
      'His A Vindication of Natural Society was a satire, though some early readers took it at face value.',
      'The Hastings impeachment began in 1787 and the trial ran from 1788 to 1795, ending in acquittal.',
      'Reflections on the Revolution in France was a bestseller and drew replies from many writers, the most famous being Thomas Paine’s Rights of Man.',
      'His speech on conciliation with America (1775) urged the government to keep the colonies by wise concessions instead of force.',
      'He is widely called the father of modern conservatism, even though he spent most of his career in the reformist wing of the Whig party.',
    ],
    myths: [
      { myth: 'Burke wrote: “The only thing necessary for the triumph of evil is for good men to do nothing.”', reality: 'This line is widely attributed to him, but no one has found it in his writings, and researchers have not traced it to a reliable source. Treat it as a misattribution.' },
      { myth: 'Burke was against all change and defended the status quo.', reality: 'He fought the Crown’s American policy, called for Catholic relief, attacked the East India Company’s abuses and supported economical reform. His point was that change should grow out of existing institutions and respect their lessons.' },
      { myth: 'Burke’s predictions about France were all vindicated.', reality: 'He feared violence and a military ruler, and the Terror of 1793–94 and the rise of Napoleon seemed to bear him out. Critics point out that he wrote in 1790, before the worst events, and that his picture of the old regime and his sympathetic portrait of the French queen were also disputed in his own time, notably by Paine.' },
    ],
    works: [
      { title: 'A Philosophical Enquiry into the Origin of Our Ideas of the Sublime and Beautiful (1757)', note: 'His early work on aesthetics and emotion.' },
      { title: 'Speech on Conciliation with America (1775)', note: 'A famous parliamentary speech urging peace through compromise.' },
      { title: 'Reflections on the Revolution in France (1790)', note: 'His most influential book, a critique of the early Revolution and a defence of inherited institutions.' },
      { title: 'An Appeal from the New to the Old Whigs (1791)', note: 'Burke’s defence of his consistency after his break with Charles James Fox and other Whigs.' },
      { title: 'Letters on a Regicide Peace (1796–97)', note: 'Late writings warning against peace with revolutionary France.' },
    ],
    legacy: [
      'Burke gave conservatism its first great statement, and writers from the nineteenth century to today have drawn on his ideas about tradition, institutions and prudence. He is also claimed by liberals for his defence of ordered liberty, his fight against abuses in India and his support for the American colonists and for Catholics in Ireland. Few thinkers have been admired by so many different camps.',
      'His reputation is debated. Admirers value his warning that grand projects of social reconstruction can have terrible costs, and that institutions are harder to rebuild than to break. Critics say he under-rated the injustice of the old regime, defended privilege, and that his fear of change could be used to resist needed reforms. Both sides continue to read the Reflections, which Paine and others attacked at once.',
    ],
  },
  {
    slug: 'thomas-paine',
    order: 1737,
    dates: '1737 – 1809',
    place: 'Thetford, England; Philadelphia, Paris and New York',
    era: 'Enlightenment',
    tradition: 'Radical Enlightenment',
    tagline: 'An English corset-maker turned pamphleteer whose plain words helped drive the American and French revolutions and gave democracy a popular voice.',
    who: [
      'Thomas Paine was born on 9 February 1737 in Thetford, Norfolk, England. He left school young and learned his father’s trade of staymaking, which meant making the stiffened undergarments then worn by women. He tried other occupations, and from the early 1760s he worked as an excise officer, collecting taxes on goods. In the early 1770s he wrote a pamphlet arguing for better pay for his fellow officers, and he was dismissed in 1774. That year he met Benjamin Franklin in London, who gave him a letter of recommendation, and he sailed to Philadelphia.',
      'In America, Paine wrote for magazines, and on 10 January 1776 he published Common Sense, an anonymous pamphlet arguing that the colonies should break from Britain and become a republic. It was written in clear language for ordinary people, and by Paine’s own estimate it sold about 100,000 copies within three months, though that figure is an estimate. Later in 1776, as the American cause faltered, he began The American Crisis, a series of pamphlets whose first words, “These are the times that try men’s souls”, became famous.',
      'He returned to Europe and answered Edmund Burke’s attack on the French Revolution with Rights of Man (Part 1 in 1791, Part 2 in 1792). The British government put him on trial in his absence for seditious libel in December 1792, and he was found guilty, but by then he was in France. Elected to the French National Convention, he argued against executing the king and was imprisoned in Paris in December 1793, narrowly escaping the guillotine. He was released in November 1794 after the American minister James Monroe intervened. He returned to the United States in 1802 and died in New York on 8 June 1809, and only a handful of mourners are said to have attended the funeral.',
    ],
    context: [
      'Paine’s career spanned a revolutionary age. In the 1760s and 1770s the American colonists were in conflict with Britain over taxation and representation, and many still hoped to stay inside the empire. Paine’s achievement was to argue plainly for independence at a time when the question was still open. In 1789 revolution broke out in France, and Britain saw an intense debate over whether such change should be welcomed or feared.',
      'The British government under William Pitt grew anxious about radical ideas and the spread of cheap pamphlets. In 1792 a royal proclamation against seditious writings was issued, and Paine’s book was a principal target. Paine’s ideas were part of a wider current that historians call the Radical Enlightenment, which asked not only how to improve existing institutions but whether kings, hereditary rank and established churches were justified at all.',
    ],
    ideas: [
      { title: 'Independence and the republic', text: 'In Common Sense, Paine argued that society is a blessing but government, even at its best, is a necessary evil, to be kept small and close to the people. He criticised monarchy and hereditary rule as unreasonable, and argued that America’s cause was the cause of all humanity. The pamphlet’s strength was its plain, forceful style and the way it moved the debate from complaint to independence.' },
      { title: 'The rights of man, and the living over the dead', text: 'In Rights of Man he argued that people have natural rights and that governments exist to protect them, with authority resting on the consent of the governed. Against Burke’s idea of inherited constitutions, he insisted that each generation is free to act for itself and that no generation may bind those who come after it. Hereditary rule, he said, makes no sense because wisdom cannot be inherited.' },
      { title: 'A foundation for social welfare', text: 'The second part of Rights of Man proposed that a representative government should spend less on war and more on its people, with progressive taxes on large estates, pensions for the old, support for poor families to educate their children and employment for the temporarily distressed. In Agrarian Justice (1797) he proposed a lump sum to every person at the age of twenty-one and a yearly pension from fifty, paid from a tax on inherited land. Many historians see these as early ancestors of the modern welfare state.' },
      { title: 'Deism and reason in religion', text: 'In The Age of Reason, Paine attacked the authority of the Bible and organised churches, arguing that revelation passed second-hand cannot be trusted and that reason and nature point to a creator. He professed his belief in one God and in the equality of man, saying that religious duties consist in doing justice, loving mercy and trying to make other people happy. He was a deist, not an atheist, but the book scandalised many of his contemporaries.' },
      { title: 'Writing for ordinary people', text: 'Paine believed political ideas belong to everyone and wrote in short sentences without Latin or learned allusions. His pamphlets were printed cheaply, read aloud in taverns and passed from hand to hand. He showed that a clear style and low prices could make public opinion a political force, and he gave no great weight to titles or ancestry.' },
    ],
    principles: [
      'Government exists to serve the people, not the other way round.',
      'No one has the right to rule simply by birth.',
      'Each generation should be free to decide for itself.',
      'Society owes something to its poor, old and young, as a matter of justice and not just charity.',
      'Say it plainly, so that everyone can follow.',
    ],
    practice: [
      'Before sharing an idea, try to put it in language a thoughtful teenager would understand.',
      'When someone appeals to “how it has always been done”, ask who benefits and whether anyone chose it.',
      'Ask of a policy or institution what it does for the least powerful person it affects.',
    ],
    facts: [
      'Common Sense was published anonymously in Philadelphia in January 1776.',
      'The American Crisis opened with “These are the times that try men’s souls”, a line that, by tradition, was read to soldiers at a low point in the war.',
      'Paine did not speak French, yet he was elected to the French National Convention in 1792 as a deputy for the Pas-de-Calais.',
      'A story says that his life was saved in prison when a chalk mark meant for the guards was placed on the wrong side of his cell door, though this tale comes from later accounts and its details are uncertain.',
      'In 1775 an anonymous essay against slavery in a Pennsylvania magazine is attributed to him by many scholars.',
      'In 1819 the English journalist William Cobbett dug up Paine’s bones to take them to England for a monument, but the remains were later lost.',
    ],
    myths: [
      { myth: 'Paine was an atheist.', reality: 'He wrote clearly that he believed in one God and hoped for happiness beyond this life. Theodore Roosevelt called him a “filthy little atheist” in 1888, and the label stuck, but Paine was a deist who attacked organised religion and the Bible, not belief in God.' },
      { myth: 'Paine recanted his religious views on his deathbed.', reality: 'Pious stories of a recantation circulated after his death, but they are disputed, and accounts from people close to him deny them. Historians treat the claim as unreliable.' },
      { myth: 'Paine was a bloodthirsty French radical.', reality: 'He spoke against executing Louis XVI, urging that the king be exiled to America, and he was imprisoned in 1793 during the Terror. He supported the Revolution’s early ideals but opposed its violence.' },
    ],
    works: [
      { title: 'Common Sense (1776)', note: 'The pamphlet that argued for American independence.' },
      { title: 'The American Crisis (1776–83)', note: 'A series of essays supporting the war effort.' },
      { title: 'Rights of Man (1791–92)', note: 'His reply to Burke and a defence of republican government and social reform.' },
      { title: 'The Age of Reason (1794, 1795, 1807)', note: 'His critique of organised religion and defence of deism, published in three parts.' },
      { title: 'Agrarian Justice (1797)', note: 'A short pamphlet proposing a grant at adulthood and a pension in old age.' },
    ],
    legacy: [
      'Paine’s pamphlets were among the first political writings to reach a mass audience, and they helped to make independence and republican government seem reasonable to ordinary readers on both sides of the Atlantic. Rights of Man fed the growth of radical reform movements in Britain, and his ideas about pensions, education and taxation are often cited in later arguments about welfare and social insurance, though historians disagree about how direct the line is.',
      'After his death his reputation suffered, above all in America, because of The Age of Reason, and for much of the nineteenth century he was a figure to be attacked or defended in religious controversies. Since then, historians have given him credit as a main voice of the Atlantic revolutions. His critics, among them Burke and many conservatives, said that his rejection of tradition was reckless, and their debate with him is still alive today.',
    ],
  },
]
