import type { Profile } from './types'

export const ENLIGHTENMENT_A: Profile[] = [
  {
    slug: 'montesquieu',
    order: 1689,
    dates: '1689 – 1755',
    place: 'La Brède near Bordeaux, and Paris, France',
    era: 'Enlightenment',
    tradition: 'French Enlightenment',
    tagline: 'A magistrate and satirist who asked why laws differ from country to country, and argued that power must be made to check power.',
    who: [
      'Charles-Louis de Secondat was born on 18 January 1689 at the château of La Brède, near Bordeaux, into a family of nobles who held judicial office. He trained in law, and in 1714 became a councillor in the parlement of Bordeaux, the regional high court. In 1716 he inherited from an uncle both the title Baron de Montesquieu, the name by which he is known, and the office of président à mortier, a senior judgeship in the same court. He held it for about a decade and sold it in 1726, by which time he cared more for study and writing than for the bench.',
      'He became famous in 1721 with the Persian Letters, published anonymously. It is a novel told through letters sent by two imaginary Persian visitors to Paris, who look at French society, the Church, the king and fashion with puzzled outsiders’ eyes. The book was witty and a little scandalous, and it was a bestseller. In 1728 he was elected to the Académie Française, and then set out on several years of travel through central Europe, Italy and, from late 1729 until spring 1731, England, where he studied the country’s government and is said to have joined a Masonic lodge.',
      'Back at La Brède he spent roughly twenty years, by his own account, on his masterpiece, The Spirit of the Laws, which appeared in 1748 and was an immediate success across Europe. Church authorities were less pleased: in 1751 the book was placed on the Catholic Index of Prohibited Books. Montesquieu died in Paris on 10 February 1755. He is often remembered as the thinker who gave modern politics the idea of dividing governmental power, but he also saw himself as a student of how societies actually work.',
    ],
    context: [
      'France in Montesquieu’s lifetime was an absolute monarchy at the end of the long reign of Louis XIV, who died in 1715. The king’s wars had left heavy debts, and many educated people were uneasy about royal power, religious intolerance and the pomp of Versailles. Britain, by contrast, had limited the monarch after the revolution of 1688, and its Parliament, press and commerce fascinated French observers.',
      'The scientific revolution had also changed how people thought. If nature follows laws that can be discovered, perhaps societies do too. Montesquieu applied that hope to politics: instead of asking only what laws ought to be, he asked what laws are, and what causes them. His method of comparing customs from many times and places helped found modern social science.',
    ],
    ideas: [
      { title: 'Laws have causes', text: 'In The Spirit of the Laws, Montesquieu argued that laws are not arbitrary. They relate to a country’s size, religion, trade, customs and government, and the “spirit” of laws lies in those relations. A law that works in one society may fail in another, so a wise legislator studies the people before writing the rules.' },
      { title: 'Three kinds of government', text: 'He sorted governments into republics, monarchies and despotisms, and gave each a driving principle: virtue, honour and fear. In a republic citizens must love the common good, in a monarchy people strive for rank and reputation, and in a despotism, where one person rules by whim, subjects obey out of fear. He thought despotism the most dangerous of the three, since it needs no consent and no restraint.' },
      { title: 'Power must check power', text: 'In his famous chapter on the English constitution, he wrote that liberty is endangered when the power to make laws, to carry them out and to judge cases are united in the same hands. His remedy was to separate these powers and let each restrain the others. Liberty, for him, meant the security that comes from knowing the law will protect you from arbitrary treatment.' },
      { title: 'Moderate government and intermediate bodies', text: 'He admired moderate governments in which nobles, courts and other institutions stand between the ruler and the people, and he saw the ruin of such bodies as a step towards tyranny. He also thought gentle, clear and predictable criminal laws were essential to freedom, and that harsh penalties often fail.' },
      { title: 'Commerce, climate and slavery', text: 'He argued that trade softens manners and encourages peace, because nations that trade depend on one another. He also proposed that climate shapes temperament and so, indirectly, laws, with hot climates producing indolence and cold ones vigour. This climate theory is now rejected as unsound and as reflecting European prejudice. On slavery he wrote that it is contrary to nature and, in a famous passage of mock-argument, he mocked the reasons given for it. Yet he also suggested that hot climates might make it less unjust, a claim that has been criticised ever since.' },
    ],
    principles: [
      'Study how things actually work before deciding how they should work.',
      'Concentrated power tempts abuse, so divide it.',
      'Clear, moderate laws protect liberty better than harsh ones.',
      'Respect the customs and circumstances of a people when you judge their laws.',
      'Be wary of explanations that flatter your own country.',
    ],
    practice: [
      'When you judge an unfamiliar custom or rule, first ask what problem it solves in its setting.',
      'In any organisation you lead, ask who checks your decisions, and welcome that check.',
      'Read about another country’s institutions as Montesquieu did, and compare them with your own to see your habits more clearly.',
    ],
    facts: [
      'The Persian Letters were published anonymously in Amsterdam in 1721, though the author’s identity was an open secret in Paris.',
      'He published Considerations on the Causes of the Greatness of the Romans and their Decline in 1734, a study of why Rome rose and fell.',
      'The Spirit of the Laws was published in Geneva in 1748 without the author’s name on the title page.',
      'James Madison called him “the celebrated Montesquieu” in the Federalist Papers, and one political scientist has found that colonial Americans quoted him more than any authority except the Bible.',
      'He took a close interest in the wine estate at La Brède, which he inherited and ran, and the countryside around it shaped some of his observations about farming and trade.',
      'He spent time in England between 1729 and 1731, where he met leading politicians and observed Parliament at work.',
    ],
    myths: [
      { myth: 'Montesquieu invented the separation of powers.', reality: 'Earlier writers, including Aristotle, Polybius and John Locke, had discussed mixed government and divided authority. Montesquieu’s contribution was to present a clear and influential account that tied the division of powers to liberty.' },
      { myth: 'He described the English constitution as it really worked.', reality: 'His portrait of Britain was idealised. In practice the king’s ministers sat in Parliament and worked closely with it, and the neat separation Montesquieu described was not how the system operated. His real influence lay in the principle, not in the accuracy of the picture.' },
    ],
    works: [
      { title: 'Persian Letters (1721)', note: 'A satirical epistolary novel that examines French society through the eyes of two Persian visitors.' },
      { title: 'Considerations on the Causes of the Greatness of the Romans and their Decline (1734)', note: 'A study of Roman history that looks for causes in institutions and habits instead of fate or accident.' },
      { title: 'The Spirit of the Laws (1748)', note: 'His masterpiece, a long comparison of laws, governments and societies. It contains his accounts of the types of government and of the division of powers.' },
      { title: 'Defence of The Spirit of the Laws (1750)', note: 'A reply to critics who accused the book of irreligion.' },
    ],
    legacy: [
      'The Spirit of the Laws shaped constitutions for generations. The framers of the United States Constitution drew on it when they divided power among Congress, the president and the courts, and later liberal constitutions in Europe and Latin America borrowed the same logic. French revolutionaries also cited him, though they often went beyond his careful preference for moderation.',
      'He also helped shape how we study society. By treating laws and customs as products of circumstances that can be compared, he is counted among the founders of sociology and political science. His climate theory and his views on slavery show the limits of his age, which is a good reason to read him with attention to both his insights and his blind spots.',
    ],
  },
  {
    slug: 'voltaire',
    order: 1694,
    dates: '1694 – 1778',
    place: 'Paris, then England, Prussia, Switzerland and Ferney on the French border',
    era: 'Enlightenment',
    tradition: 'French Enlightenment',
    tagline: 'The sharpest pen of the age, who used wit, history and drama to fight intolerance and fanaticism.',
    who: [
      'François-Marie Arouet was born in Paris on 21 November 1694, the son of a notary, and was educated by the Jesuits at the Collège Louis-le-Grand. He took the name Voltaire as a young writer, around 1718, and made his name with poetry and plays. His quick tongue got him into trouble: he spent eleven months in the Bastille in 1717–18 over verses mocking the regent, and in 1726, after a quarrel with a nobleman, he was imprisoned again and then sent into exile in England.',
      'He stayed in England for roughly two and a half years, learning the language, reading Locke and Newton and meeting writers and politicians. His book on the English, the Letters Concerning the English Nation, appeared in London in 1733 and in French the next year as the Philosophical Letters. It praised English religious tolerance, trade and science and implicitly criticised France, and French authorities ordered the book burned. He then lived for years at Cirey with his companion Émilie du Châtelet, a gifted mathematician and translator of Newton, before spending a stormy period at the court of Frederick the Great of Prussia in 1750–52.',
      'In 1758 he settled at Ferney, a short distance from Geneva and just across the French border, which put him out of reach of the French authorities. There he ran an estate, built a church, entertained visitors and wrote ceaselessly. His campaign on behalf of the Calas family, from 1762, made him a champion of justice. He returned to Paris in February 1778 to a hero’s welcome after more than twenty-five years away, and died there on 30 May 1778. Because he had been denied a Christian burial, his body was taken secretly out of the city, and in 1791 the French revolutionaries moved his remains to the Panthéon.',
    ],
    context: [
      'In eighteenth-century France the Catholic Church and the crown controlled printing, and writers who offended either could be jailed, censored or exiled. Religious dissenters, notably the Protestants, still suffered legal penalties long after the revocation of the Edict of Nantes in 1685 had made their worship illegal.',
      'Voltaire thrived by working around these limits. He published abroad, used pseudonyms and anonymity, wrote satire in the guise of fiction and kept homes near borders. He also took advantage of a changing reading public: salons, coffeehouses and lending circles in which educated people eagerly discussed new ideas.',
    ],
    ideas: [
      { title: 'Tolerance over fanaticism', text: 'Voltaire detested religious persecution and wrote against it throughout his life. In his Treatise on Tolerance, prompted by the Calas affair, he argued that people with different beliefs can live in peace, and that persecution produces cruelty and violence instead of truth. He used the phrase “écrasez l’infâme”, usually translated “crush the infamous thing”, in letters to friends. It was aimed mainly at fanaticism and the abuse of religious power.' },
      { title: 'Deism and reason', text: 'He believed in a creator God revealed by the order of nature, but rejected the idea that God intervenes in history or that any church has a monopoly on truth. This position is called deism. He attacked superstition, miracles and clerical privilege, while holding that a belief in God was useful for morality.' },
      { title: 'Against easy optimism', text: 'The Lisbon earthquake of 1755 shook his faith in the claim that everything is for the best. His poem on the disaster and his novella Candide (1759) mock the philosopher Pangloss, a caricature of Leibnizian optimism. Candide ends not with a grand doctrine but with a modest instruction to “cultivate our garden”, to do the useful work close at hand.' },
      { title: 'History for the general reader', text: 'In works such as the Essay on the Customs and the Spirit of Nations, he wrote history that looked beyond kings and battles to manners, arts, trade and belief, and that included China, India and the Islamic world. He used history as a weapon against prejudice and a guide to progress.' },
      { title: 'Freedom of expression', text: 'He insisted that people should be free to think and write, and he fought censorship in practice by publishing widely and under many names. He was not, however, a democrat: he preferred enlightened monarchs to popular government.' },
    ],
    principles: [
      'Do not let any authority, however sacred, put an end to questions.',
      'Defend people from persecution whatever they believe.',
      'Doubt is uncomfortable, but certainty is absurd when it is not earned.',
      'Use humour to puncture pomposity.',
      'Prefer useful work to grand theories.',
    ],
    practice: [
      'When you hear a cruelty justified in the name of certainty, ask what evidence would convince you that you were wrong.',
      'Use humour carefully: a joke can show an absurdity that a long argument cannot, but it must be aimed at ideas and power, not at the powerless.',
      'When overwhelmed by big questions, choose one small, useful task nearby and do it well.',
    ],
    facts: [
      'Candide was published anonymously in January 1759 and was banned soon afterwards, yet sold in large numbers.',
      'Jean Calas, a Protestant merchant of Toulouse, was executed in 1762 after being accused of murdering his son, who was supposedly going to convert to Catholicism. Voltaire campaigned for the family, and in 1765 the verdict was overturned.',
      'He had a long relationship with Émilie du Châtelet, with whom he lived at Cirey, and the two worked on science together; she died in 1749.',
      'He wrote dozens of plays, long poems, histories, philosophical tales and a vast correspondence, with many thousands of letters surviving.',
      'He became wealthy through lottery schemes, speculation and loans, which gave him the financial independence to write freely.',
      'At Ferney he built a church carrying the inscription “Deo erexit Voltaire”, “Voltaire built this for God”.',
    ],
    myths: [
      { myth: 'Voltaire said, “I disapprove of what you say, but I will defend to the death your right to say it.”', reality: 'He never wrote this. The line comes from Evelyn Beatrice Hall, who published a biography in 1906 under the pen name S. G. Tallentyre, and it was meant to sum up his attitude, not to quote him. It captures his spirit but is not his own wording.' },
      { myth: 'Voltaire was an atheist and an enemy of all religion.', reality: 'He was a deist who believed in a creator and thought belief in God socially useful. His targets were fanaticism, clerical power and superstition, and he also wrote sharply about some Jewish and Muslim practices, as well as Christian ones.' },
      { myth: 'Voltaire was a consistent champion of equality.', reality: 'He fought persecution, but he also wrote prejudiced remarks about Jews and about Africans. Scholars have shown that he held shares in the French East India Company and invested in ventures connected to the slave trade. Admirers and critics still argue about how these facts bear on his legacy.' },
    ],
    works: [
      { title: 'Letters Concerning the English Nation (1733)', note: 'Essays on English government, religion, science and literature, published in London.' },
      { title: 'Candide (1759)', note: 'A short satirical novel about optimism, suffering and the search for a livable philosophy.' },
      { title: 'Treatise on Tolerance (1763)', note: 'Written after the Calas affair, a plea against religious persecution.' },
      { title: 'Philosophical Dictionary (1764)', note: 'A collection of short, sharp entries on religion, politics and morals.' },
      { title: 'Essay on the Customs and the Spirit of Nations', note: 'A wide-ranging world history, revised over many years.' },
    ],
    legacy: [
      'Voltaire became the symbol of the Enlightenment. His campaigns for individual cases, such as Calas, helped turn public opinion against torture and religious persecution, and his clear, witty prose showed that philosophy could reach a wide audience. French revolutionaries honoured him by moving his body to the Panthéon, though he himself had favoured reform from above.',
      'Today he is admired as a defender of free speech and tolerance, and criticised for his prejudices and his financial interests. Most historians treat the two as belonging together: he was a brave critic of the abuses of his own society who shared some of the assumptions of his era.',
    ],
  },
  {
    slug: 'jean-jacques-rousseau',
    order: 1712,
    dates: '1712 – 1778',
    place: 'Geneva, then France and Switzerland',
    era: 'Enlightenment',
    tradition: 'Enlightenment political thought',
    tagline: 'A self-taught outsider who argued that people are born free and good, and that society chains and corrupts them.',
    who: [
      'Jean-Jacques Rousseau was born in Geneva on 28 June 1712, the son of a watchmaker. His mother died of fever nine days after his birth, and when he was about ten his father left Geneva after a quarrel, so Rousseau was brought up by relatives and sent into apprenticeships. At about fifteen he left the city and eventually found a patron and, in time, a lover in Madame de Warens in Savoy, in whose house he read, studied music and educated himself. In 1742 he moved to Paris with a plan for a new system of musical notation.',
      'In Paris he befriended Diderot and wrote articles on music for the Encyclopédie. In 1749, so he later said, an idea came to him on the road to visit Diderot in prison, and it became his first Discourse, which won a prize from the Academy of Dijon in 1750. It argued that the arts and sciences had not improved morals. He followed it with the Discourse on Inequality (1755), and then, in 1761–62, with three major works: the novel Julie, or the New Heloise, The Social Contract and the educational treatise Émile. His opera Le Devin du village (1752) was also a success.',
      'Rousseau’s life did not match his teaching. With Thérèse Levasseur, his companion for decades, he had five children, and he placed each in a foundling hospital, a decision for which he gave various explanations and about which he later expressed remorse, yet he also wrote Émile, a book about raising a child. In 1762 the Parisian authorities condemned Émile and the Social Contract, and Geneva did too, so he fled. He moved among Switzerland, England, where he quarrelled with David Hume in 1766, and France, increasingly suspicious that others were plotting against him. He wrote the Confessions, a pioneering autobiography, and the Reveries of the Solitary Walker, and died at Ermenonville on 2 July 1778. In 1794 his remains were moved to the Panthéon.',
    ],
    context: [
      'Rousseau wrote at a time when many Enlightenment writers were confident that reason, science and commerce would improve humanity. He questioned this faith, and many of his contemporaries found him provocative. His upbringing in Geneva, a republic with citizen assemblies, shaped his political imagination, and he proudly signed some of his works as a “citizen of Geneva”.',
      'France under Louis XV was a society of rank, privilege and royal absolutism, where the rich lived comfortably and the poor often did not. Rousseau, who had known insecurity, felt keenly how social inequality distorted human relations, and his writing speaks to that experience.',
    ],
    ideas: [
      { title: 'Natural goodness, social corruption', text: 'Rousseau held that human beings are naturally good, with a basic self-love (amour de soi) and a natural pity for others. Society, in his view, awakens a different passion, amour propre, a need to be seen and ranked above others, which breeds vanity, envy and domination. He did not think we could simply return to a primitive state; the question was how to live well in society.' },
      { title: 'The origins of inequality', text: 'In the Discourse on Inequality he imagined how private property and comparison gradually divided people into rich and poor, masters and servants. He treated his picture of early humanity as a thought experiment, not as history. The aim was to show that inequality was made by human arrangements, not by nature.' },
      { title: 'The social contract and the general will', text: 'The Social Contract opens with the line “Man is born free, but is everywhere in chains.” Rousseau asked how legitimate authority can exist, and answered that only laws made by the people themselves can bind them without making them slaves. He called the common interest of the citizens the “general will”, and held that sovereignty belongs to the people and cannot be handed away. Critics have argued that the idea could be used to silence minorities, a debate that continues.' },
      { title: 'A new kind of education', text: 'In Émile he argued that children should be educated according to their stage of development, learning from experience and nature instead of memorising adult rules. He was suspicious of books and lectures for the young, and valued physical activity, practical skill and the growth of judgement. His picture of the education of girls in the same book, however, was narrower, and drew sharp criticism from Mary Wollstonecraft.' },
      { title: 'Feeling and the inner life', text: 'Rousseau gave the individual’s emotions and conscience a central place. In the Confessions he tried to describe himself with unprecedented honesty, flaws included, and in the Reveries he explored solitude and the simple joy of being. This helped open the way to Romanticism.' },
    ],
    principles: [
      'Freedom means living under laws one has a share in making.',
      'Inequality is a human creation, so it can be addressed by human action.',
      'Educate by experience and judgement, not just by instruction.',
      'Be wary of vanity and the urge to compare yourself with others.',
      'Listen to your conscience, but test it against others.',
    ],
    practice: [
      'Notice when you want something because you need it and when you want it because others will see you have it.',
      'When you teach or parent, let the learner try and fail, and step in when it matters.',
      'In group decisions, ask what serves the common good, not only what the most vocal members prefer.',
    ],
    facts: [
      'His Discourse on the Arts and Sciences won a prize from the Academy of Dijon in 1750 and made him famous almost overnight.',
      'Besides writing, he composed music and proposed a numerical system of musical notation; his opera Le Devin du village was performed at court in 1752.',
      'He wrote the articles on music for Diderot’s Encyclopédie, but later quarrelled with Diderot and others in his circle.',
      'Émile and The Social Contract were both condemned in Paris and Geneva in 1762, and Rousseau had to flee France.',
      'He was an enthusiastic amateur botanist, and wrote letters on plants.',
      'The Confessions were completed around 1770 and published after his death, in 1782.',
    ],
    myths: [
      { myth: 'Rousseau urged people to return to nature and the “noble savage”.', reality: 'The phrase “noble savage” is not his, and he explicitly said that a return to a primitive state was impossible. His early humans were a thought experiment, and his aim was to understand how society could be organised justly.' },
      { myth: 'Rousseau’s general will is just majority rule, or a blueprint for dictatorship.', reality: 'The general will, for Rousseau, is the common good the citizens aim at when they vote, not the sum of private wishes. Whether this idea protects or threatens liberty is much debated, and later movements, from democratic to authoritarian ones, have claimed it.' },
      { myth: 'He was a hypocrite who wrote about children while abandoning his own.', reality: 'It is a fact that he placed his five children in a foundling hospital, and it is hard to defend. But the charge simplifies a more complicated story: he admitted the act in the Confessions and offered explanations that most readers find unconvincing.' },
    ],
    works: [
      { title: 'Discourse on the Arts and Sciences (1750)', note: 'His first major essay, which questioned whether progress in knowledge improves morals.' },
      { title: 'Discourse on Inequality (1755)', note: 'A speculative account of how inequality arose and why it is unnatural.' },
      { title: 'The Social Contract (1762)', note: 'His main work of political philosophy, on legitimate authority and the general will.' },
      { title: 'Émile, or On Education (1762)', note: 'A long treatise, partly a novel, on raising a child.' },
      { title: 'Confessions (published 1782) and Reveries of the Solitary Walker', note: 'Autobiographical works that shaped modern ideas of self-examination.' },
    ],
    legacy: [
      'Rousseau’s ideas of popular sovereignty and equality inspired many leaders of the French Revolution, who honoured him after his death, and they remain at the heart of modern democratic thought. His writing on education influenced reformers from Pestalozzi to Montessori, and his emphasis on feeling shaped Romanticism, from Wordsworth to Goethe.',
      'He is also a controversial figure. Critics point to the tension between his love of freedom and the demands he sometimes placed on the individual, to his limited view of women, and to his treatment of his children. Few thinkers have been so fiercely praised and attacked, and this tells us how much his questions still matter.',
    ],
  },
  {
    slug: 'denis-diderot',
    order: 1713,
    dates: '1713 – 1784',
    place: 'Langres in Champagne, and Paris, France',
    era: 'Enlightenment',
    tradition: 'French Enlightenment',
    tagline: 'The editor of the Encyclopédie, who gathered the knowledge of his age into one great work and dared to follow his materialism where it led.',
    who: [
      'Denis Diderot was born on 5 October 1713 in Langres, in Champagne, the son of a master cutler. He was educated by the Jesuits and studied in Paris, receiving a Master of Arts degree in 1732. He did not settle into a regular profession, and lived for years by his wits, as a tutor, translator and hack writer, while reading widely in mathematics, science, literature and philosophy. In 1743 he married Antoinette Champion, and he later had a long and passionate relationship with Sophie Volland, to whom he wrote many letters.',
      'His early books, the Philosophical Thoughts (1746) and the Letter on the Blind (1749), brought trouble. The first was condemned by the Parlement of Paris, and after the second, which questioned traditional proofs of God’s existence, he was arrested and held at the fortress of Vincennes for a period in 1749. The experience taught him caution, and from then on much of his boldest writing was left unpublished.',
      'In the same years he took on the project that would define his life: the Encyclopédie, which began as a plan to translate an English reference work and grew into a vast original project. Working with the mathematician Jean le Rond d’Alembert, Diderot edited and wrote for the work from 1751 to 1772. D’Alembert withdrew in 1759, and Diderot carried on largely alone. He lived modestly and, when he needed a dowry for his daughter, he sold his library to Catherine the Great of Russia, who let him keep it for life. He visited her court in 1773–74 and died in Paris on 31 July 1784.',
    ],
    context: [
      'In mid-century France, publishing was controlled by royal censors and a powerful Church. A work that praised reason over revelation, or that discussed trades, tools and science as seriously as theology, was provocative. The Encyclopédie was suspended by royal decree in 1752, and in 1759 its official publishing privilege was withdrawn, yet influential friends in government protected it and it continued in semi-secrecy.',
      'The age was also one of dramatic scientific progress. Newton’s physics, new work in chemistry and natural history, and growing knowledge of the world beyond Europe all challenged old categories. Diderot wanted to put all of this in front of ordinary readers, convinced that spreading knowledge would change how people think.',
    ],
    ideas: [
      { title: 'Knowledge for everyone', text: 'The Encyclopédie aimed to collect the knowledge of the age and make it available to the public, with articles on science, history and philosophy but also on crafts and trades, with thousands of detailed engravings of workshops and tools. Diderot wrote that its purpose was to change the way people commonly think. Treating the work of artisans as worthy of study was in itself a quiet challenge to the old social order.' },
      { title: 'Matter that feels', text: 'Diderot moved from a belief in God to deism and then to a daring form of materialism. In works such as D’Alembert’s Dream he argued that nature needs no soul or spirit to explain life: matter itself, when organised in the right way, can feel and think. He kept this work unpublished in his lifetime.' },
      { title: 'Seeing through the blind', text: 'The Letter on the Blind uses the figure of the blind mathematician Nicholas Saunderson to show how our ideas depend on our senses and how arguments about God from the order of nature might look different to someone without sight. It is an early study of how perception shapes knowledge.' },
      { title: 'Art, feeling and honesty', text: 'In his Salons, reviews of the biennial Paris art exhibitions, Diderot created modern art criticism, writing vividly about what pictures made him feel and think. He called for theatre and painting to show ordinary life truthfully, and in the Paradox of the Actor he asked whether great acting needs real emotion or skilled control.' },
      { title: 'Morality, cultures and colonialism', text: 'In the Supplement to Bougainville’s Voyage, he imagined a dialogue with Tahitians to question European sexual and social customs, and he contributed passages to the Abbé Raynal’s history that condemned colonialism and slavery. He held that morality rests on human nature and social life, not on revelation.' },
    ],
    principles: [
      'Spread knowledge widely, since ideas improve when many people can examine them.',
      'Follow evidence even when it unsettles comfortable beliefs.',
      'Value practical skill and the work of ordinary hands.',
      'Judge art and people by honesty and feeling, not by fashion.',
      'Keep your mind open: Diderot loved arguing against himself.',
    ],
    practice: [
      'When you learn something, try to explain it to someone who has no background in the subject.',
      'Write down an argument against a view you hold, and give it its strongest form.',
      'Look at a painting, a tool or a machine for long enough to describe how it was made.',
    ],
    facts: [
      'The Encyclopédie ran from 1751 to 1772 and ended up with 28 folio volumes, 17 of text and 11 of plates, and tens of thousands of articles.',
      'Over a hundred and forty people contributed to it, including Voltaire, Rousseau and Montesquieu, and the chevalier de Jaucourt wrote a large share of the articles himself.',
      'Diderot wrote thousands of the articles, and edited the rest.',
      'Catherine the Great bought his library in the mid-1760s and kept him as its salaried librarian, though the library stayed in Paris.',
      'Rameau’s Nephew, a brilliant dialogue, was unpublished in his lifetime and first appeared in print in a German translation by Goethe in 1805.',
      'Jacques the Fatalist, a playful anti-novel that keeps interrupting its own story, was written over many years and published after his death, in 1796.',
    ],
    myths: [
      { myth: 'Diderot wrote the whole Encyclopédie.', reality: 'He was its chief editor and a prolific contributor, but it was the work of many authors. D’Alembert shared the early editorship, and the writer Jaucourt contributed a very large number of articles.' },
      { myth: 'The Encyclopédie was simply an attack on religion.', reality: 'It did contain passages critical of the Church, often tucked away or phrased with irony to avoid the censors, but most of it was practical: articles on science, history, crafts and trades. It was controversial because it treated human reason as the measure of knowledge.' },
      { myth: 'Diderot was always an atheist.', reality: 'He started as a Catholic student, passed through deism, and by the late 1740s and after moved towards materialism and atheism. His views developed over time and he expressed them in different ways in different works.' },
    ],
    works: [
      { title: 'Letter on the Blind (1749)', note: 'A philosophical essay on perception and knowledge that led to his imprisonment.' },
      { title: 'Encyclopédie (1751–1772)', note: 'The great reference work he edited with d’Alembert, with its plates of crafts and trades.' },
      { title: 'D’Alembert’s Dream (written 1769)', note: 'Three dialogues on matter, life and thought, not published in his lifetime.' },
      { title: 'Rameau’s Nephew and Jacques the Fatalist', note: 'Two of the most original works of fiction of the century, both published after his death.' },
      { title: 'Salons (1759–1781)', note: 'Reviews of the Paris art exhibitions that founded modern art criticism.' },
    ],
    legacy: [
      'The Encyclopédie became the emblem of the Enlightenment, and the model for later reference works. It showed that knowledge could be organised for the public and not left to universities and churches. Many of the writers who contributed to it became leading voices of the age.',
      'Diderot himself was long overshadowed by Voltaire and Rousseau, because so much of his best work appeared late. Since the nineteenth century he has been admired as a thinker who combined science, art and philosophy in an open, conversational style. Hegel drew on Rameau’s Nephew, and modern readers prize his curiosity and humour.',
    ],
  },
  {
    slug: 'mary-wollstonecraft',
    order: 1759,
    dates: '1759 – 1797',
    place: 'London, Ireland, Paris and England',
    era: 'Enlightenment',
    tradition: 'Early feminism',
    tagline: 'She argued that women are rational beings who need education and independence, and that society should treat them as such.',
    who: [
      'Mary Wollstonecraft was born on 27 April 1759 in Spitalfields, London, the second of seven children. Her father squandered the family’s money on failed ventures, and the household moved often. Mary received little formal schooling. A close friendship with Fanny Blood, whom she credited with opening her mind, and her parents’ unhappy marriage, shaped her views of women’s dependence.',
      'In her twenties she worked as a lady’s companion, then helped to found a school at Newington Green, near London, which failed while she was away in Lisbon in 1785, nursing Fanny Blood. She then became a governess in Ireland, a post she disliked, and decided to live by her pen. With the help of the publisher Joseph Johnson she settled in London and became part of a circle of radical writers and thinkers. Her works included Thoughts on the Education of Daughters (1787) and a novel, Mary: A Fiction (1788), and she wrote reviews and translations for Johnson’s journal.',
      'In 1790 she answered Edmund Burke’s attack on the French Revolution with A Vindication of the Rights of Men, and in January 1792 she published her best-known book, A Vindication of the Rights of Woman. She moved to Paris at the end of that year, where she lived through the Terror, had a daughter, Fanny, with the American Gilbert Imlay in 1794, and endured his abandonment and two suicide attempts. Back in England she married the philosopher William Godwin in March 1797. She died on 10 September 1797 of complications after giving birth to their daughter, the future Mary Shelley, author of Frankenstein.',
    ],
    context: [
      'In Britain at the time, a married woman had few legal rights: her property and earnings generally passed to her husband, and respectable work for an unmarried woman was scarce, with governess, teacher and companion among the few options. Girls’ education typically stressed accomplishments such as music, drawing and manners, aimed at attracting a husband.',
      'The Enlightenment spoke of reason and rights, and the American and French revolutions made those words urgent. But most Enlightenment writers, including Rousseau, did not apply them to women. Wollstonecraft took the claims of her age seriously and asked why they should stop at the household door.',
    ],
    ideas: [
      { title: 'Women are rational beings', text: 'The central claim of the Vindication of the Rights of Woman is that women are not naturally inferior to men in reason, and appear so because they are denied a proper education. Reason, she argued, is what allows anyone to be moral and responsible, so denying it to women harms both them and society.' },
      { title: 'Against an education in charm', text: 'She criticised conduct books and writers, including Rousseau in Émile, who said that girls should be trained to please men. Such an upbringing, she argued, makes women vain, anxious and weak, and trains them to rely on charm and cunning. She favoured a shared national education for boys and girls.' },
      { title: 'Independence and equality in marriage', text: 'Wollstonecraft wanted women to be able to earn a living, so that they would not have to marry for security. She hoped for marriages based on friendship and respect between equals, in which both partners are rational companions and good parents. Her famous line says that she did not wish women to have power over men but over themselves.' },
      { title: 'Rights, virtue and politics', text: 'In the Rights of Men she defended the principle that rights come from reason and human dignity and are not inherited privileges, against Burke’s defence of tradition. She saw the oppression of women, the poor and the enslaved as related examples of power resting on custom instead of justice.' },
      { title: 'Feeling and reason together', text: 'Though she championed reason, she valued feeling, imagination and the pleasures of nature. Her Letters Written in Sweden, Norway and Denmark (1796) mixes travel writing with reflections on society and her own emotions, and influenced the Romantic writers.' },
    ],
    principles: [
      'Reason is a shared human capacity, and every person should be able to develop it.',
      'Dependence breeds weakness, so aim for independence.',
      'Respect between equals is the basis of good relationships.',
      'Education should aim at character, not display.',
      'Question customs that are defended only by habit.',
    ],
    practice: [
      'Ask whether an expectation you have of someone, or of yourself, rests on ability or only on habit.',
      'Build a skill that lets you stand on your own, whether financial, practical or intellectual.',
      'In your close relationships, aim for friendship and honesty as well as affection.',
    ],
    facts: [
      'She wrote the Vindication of the Rights of Woman quickly, reportedly in about six weeks, and published it in January 1792.',
      'She dedicated it to Talleyrand, who had presented a plan for French education that offered girls only a limited schooling.',
      'Her Vindication of the Rights of Men (1790) was among the first replies to Burke’s Reflections on the Revolution in France.',
      'Her husband Godwin published a frank Memoirs of her in 1798, revealing her unmarried relationship and suicide attempts.',
      'Her daughter Mary Wollstonecraft Godwin, later Mary Shelley, began writing Frankenstein as a teenager.',
      'She wrote An Historical and Moral View of the French Revolution (1794), a contemporary account of the revolution.',
    ],
    myths: [
      { myth: 'Wollstonecraft was a man-hater who wanted to abolish marriage and family.', reality: 'She valued marriage, motherhood and domestic duty, and argued that women could be better wives and mothers when educated. What she opposed was a system that kept women ignorant and dependent.' },
      { myth: 'Her book was an instant scandal and then forgotten until the twentieth century.', reality: 'The Vindication was widely and often favourably reviewed in 1792, and followed by American and French editions. Her reputation collapsed mainly after Godwin’s memoir, in 1798, which made her private life public, and she was revived by later feminists.' },
    ],
    works: [
      { title: 'Thoughts on the Education of Daughters (1787)', note: 'Her first book, a short work of advice on the upbringing of girls.' },
      { title: 'A Vindication of the Rights of Men (1790)', note: 'A quick reply to Edmund Burke defending reason and natural rights.' },
      { title: 'A Vindication of the Rights of Woman (1792)', note: 'Her best-known work, on education, reason and the position of women.' },
      { title: 'Letters Written in Sweden, Norway and Denmark (1796)', note: 'A travel book that blends observation with personal reflection.' },
      { title: 'Maria, or The Wrongs of Woman (unfinished, 1798)', note: 'An unfinished novel published after her death, on the legal and social harm done to women.' },
    ],
    legacy: [
      'For almost a century after her death her reputation suffered from the scandal around her private life, but her ideas never fully vanished. In the nineteenth century, campaigners for women’s education and the vote took up her arguments, and the Vindication became one of the founding texts of feminism.',
      'Today she is read as a philosopher in her own right, whose thinking about reason, education and equality is taken seriously by scholars of political theory. Her arguments reshaped debates about how society treats women, and the questions she asked about dependence, education and respect remain open.',
    ],
  },
]
