import type { Profile } from './types'

export const LATE_ANCIENT: Profile[] = [
  {
    slug: 'plutarch',
    order: 46,
    dates: 'c. AD 46 – after AD 119',
    place: 'Chaeronea in Boeotia, and Delphi (Greece)',
    era: 'Ancient',
    tradition: 'Middle Platonism',
    tagline: 'A Greek priest and biographer who set great lives side by side to ask what makes a person good.',
    who: [
      'Plutarch was born in Chaeronea, a small town in Boeotia, central Greece, not far from Delphi. His birth is usually placed in the middle of the first century AD, and he is thought to have died some time after AD 119. Unlike most ancient philosophers, he was not a wandering teacher or the head of a school. He spent most of his life in his home town, where he served as a local magistrate, and at nearby Delphi, where he became a priest of Apollo, probably by the 90s AD.',
      'As a young man he studied mathematics and philosophy in Athens under a Platonist named Ammonius, around AD 66–67. He travelled to Rome and elsewhere in Italy, lectured there, and made friends among the Roman elite. One of them, Lucius Mestrius Florus, is said to have sponsored his Roman citizenship, which is why he is sometimes called Lucius Mestrius Plutarchus. He was married to a woman named Timoxena and had several children, some of whom died young. His surviving essays about family life, including a letter of consolation to his wife, are among the warmest personal writing from the ancient world.',
      'Plutarch is remembered above all for two huge bodies of writing. The Parallel Lives pairs the biographies of famous Greeks and Romans, such as Alexander and Julius Caesar or Demosthenes and Cicero, and then compares them. The Moralia, a name given later to a large collection of his other works, includes about seventy-eight essays and dialogues on ethics, religion, education, nature and literature. A late tradition says that the emperor Hadrian gave him an honorary official post in Greece. Scholars treat that report with caution, since it comes from much later sources.',
    ],
    context: [
      'Plutarch lived under Roman rule, in the years after Greece had become a province of the empire. The great days of Athens, Sparta and Thebes were centuries behind him, and his town of Chaeronea had once been the site of the battle where Philip of Macedon defeated the Greek cities in 338 BC. Greek writers of his age often looked back at that heritage with pride, and also asked how Greeks could live well, and keep their dignity, inside an empire run from Rome.',
      'Philosophy at that time was shared among several schools. Stoics, Epicureans, Platonists and Aristotelians all competed for followers. Plutarch belonged to the revival of Platonism that historians call Middle Platonism, which reinterpreted Plato’s dialogues as a source of positive teaching about God, the soul and the good life. He admired Plato but wrote with freedom, and he was happy to borrow from other schools when they seemed right. He rejected the Epicureans completely, and he argued with the Stoics on many points.',
    ],
    ideas: [
      { title: 'Biography as a mirror of character', text: 'In his Life of Alexander he says that he is writing lives, not histories, and that a small moment, a joke or a gesture can reveal more about a person than a great battle. His portraits are therefore moral studies. He wants readers to look at the virtues and faults of famous people and to improve themselves by comparison. This idea about character shaped how later Europeans wrote biography.' },
      { title: 'A Platonism of open questions', text: 'Plutarch tried to join the cautious, questioning side of Plato with the doctrinal side. He thought the world had two opposed sources: a good, rational God, and a force of disorder that goes with matter. He read Plato’s Timaeus, the dialogue about the making of the world, as describing a real beginning in which God brings order to unruly material. Later Platonists such as Plotinus disagreed with that literal reading, and scholars still discuss how consistent his system is.' },
      { title: 'Providence that does not hurry', text: 'In the essay On the Delays of the Divine Vengeance he asks why the gods do not punish wrongdoers straight away. His answer is that a wise judge acts through reason, not anger, and gives people time to change. He also argues that wickedness is already a kind of punishment, because a bad conscience and a disordered mind are painful in themselves. The essay ends with a vision of the afterlife in which souls are judged.' },
      { title: 'Reason guides emotion, and does not kill it', text: 'Plutarch disagreed with the Stoic ideal of freeing oneself from passion. In his view, emotions are a natural part of the soul. The aim is for reason to govern them, as a rider guides a horse, so that anger, grief and desire serve good ends. This gives his ethics a humane, practical character. He wrote guides to self-control, to managing anger, to curiosity and to talking too much, aimed at ordinary people.' },
      { title: 'Between superstition and unbelief', text: 'Plutarch believed in the gods and in the Delphic oracle, but he criticised both atheism and what he called superstition, a fearful and degrading idea of the divine. In On Isis and Osiris he treats the myths of Egypt as symbolic stories that point to a single divine order, which different peoples describe in different ways. He also argued that animals have some share in reason and should be treated with kindness, a view that connects with his essays on eating meat.' },
    ],
    principles: [
      'Study the lives of others to see your own character more clearly.',
      'Let reason lead the emotions, and do not try to remove them.',
      'Small habits and daily details show who you are.',
      'Be slow to judge, and slow to punish, since time often shows what haste cannot.',
      'Be curious and fair, even toward the people and customs you do not share.',
    ],
    practice: [
      'Choose one person you admire and one you do not, and write down which habits of theirs show up in your own day.',
      'When you feel anger rising, delay your answer. Plutarch’s advice on anger is mostly about gaining time for reason to catch up.',
      'When you listen to a speech or read an argument, think of it as kindling for your own thinking, not as something to memorise.',
    ],
    facts: [
      'The Parallel Lives that survive include twenty-three pairs of Greek and Roman biographies and four single lives. Most pairs end with a short comparison of the two men.',
      'Plutarch’s Life of Theseus describes the ship that the Athenians kept for generations, replacing its planks as they rotted. He says philosophers used it as an example in arguments about whether a thing that changes bit by bit is still the same. This is the origin of the “Ship of Theseus” puzzle.',
      'In On the Obsolescence of Oracles he repeats a story that a voice told a ship’s pilot, off the coast of Greece, that “the great Pan is dead”. It is one of the best known legends in the ancient world, and Plutarch is reporting what others told him.',
      'The famous saying that the mind is “not a vessel to be filled but a fire to be kindled” is a short modern paraphrase of an image in his essay On Listening to Lectures, where he compares the mind to wood that needs kindling.',
      'Thomas North’s English translation of the Lives, published in 1579, was made from a French version by Jacques Amyot, and Shakespeare drew on it for Julius Caesar, Antony and Cleopatra and Coriolanus.',
      'Montaigne, the French essayist, quoted Plutarch very often, with several hundred references in his Essays.',
    ],
    myths: [
      { myth: 'Plutarch’s Lives are reliable history.', reality: 'He used earlier sources, some now lost, and wrote to show character and moral lessons. He sometimes mixes anecdote with fact, and modern historians use him with care, though for many people and events he is our best source.' },
      { myth: 'Plutarch said that the mind is a fire, in exactly those words.', reality: 'The line is a later condensation of an image from On Listening to Lectures. Plutarch’s own point was about the way a listener should take part in what is said.' },
      { myth: 'Plutarch was a Roman.', reality: 'He was a Greek who wrote in Greek and lived most of his life in Greece. He did have Roman citizenship and many Roman friends, and his book is partly about how the two cultures compare.' },
    ],
    works: [
      { title: 'Parallel Lives', note: 'Biographies of Greek and Roman statesmen and generals in pairs, from Theseus and Romulus to figures of the late Roman Republic. His most famous work.' },
      { title: 'Moralia', note: 'A large collection of essays and dialogues, including On the Delays of the Divine Vengeance, On Isis and Osiris, On the Face in the Moon and On Superstition.' },
      { title: 'Table Talk (Quaestiones convivales)', note: 'Conversations at dinner parties on topics from science to literature, in which Plutarch shows philosophy as a part of social life.' },
      { title: 'Consolation to His Wife', note: 'A letter written after the death of their young daughter, urging calm and hope.' },
      { title: 'On the Malice of Herodotus', note: 'A sharp attack on Herodotus, whom Plutarch accuses of being unfair to the Greeks of Boeotia, his own region.' },
    ],
    legacy: [
      'Plutarch had a deep influence on the later history of thought. Early Christian writers admired his ideas about God, the soul and education, and later Platonists took his approach to reading Plato’s dialogues. In the Renaissance his Lives became a manual of civic virtue for educated readers across Europe, and the period is sometimes called a “Plutarchan age”.',
      'Through North, Amyot and Montaigne his portraits entered English and French literature, and through Shakespeare they reached the stage. Readers as different as Rousseau and Emerson drew on him. Today he is still read both as a storyteller and as a moral guide, who thought that the best way to learn how to live is to look closely at how others lived.',
    ],
  },
  {
    slug: 'augustine-of-hippo',
    order: 354,
    dates: 'AD 354 – 430',
    place: 'Thagaste (now Souk Ahras, Algeria), Carthage, Milan and Hippo Regius',
    era: 'Ancient',
    tradition: 'Christian philosophy',
    tagline: 'A North African teacher of rhetoric who became a bishop and wrote the first great Western autobiography.',
    who: [
      'Augustine was born in AD 354 in Thagaste, a small town in the Roman province of Numidia in North Africa. His mother, Monica, was a devout Christian, and his father, Patricius, was a local official who was not a Christian when Augustine was young. At seventeen he went to Carthage to study rhetoric, the art of public speaking. There he read Cicero’s Hortensius, a lost dialogue urging the pursuit of wisdom, which he later said turned his heart toward philosophy. He also took a partner, whose name he never gives, and they had a son, Adeodatus.',
      'Augustine spent about nine years among the Manichaeans, a religion that taught a struggle between two equal powers of good and evil. He became a successful teacher in Carthage, then in Rome, and in 384 he won the post of public teacher of rhetoric in Milan. There he heard the sermons of Bishop Ambrose and read what he called “books of the Platonists”, probably Latin versions of some writings of Plotinus and possibly Porphyry. In his Confessions he describes a moment of crisis in a garden in 386, when he heard a child’s voice saying “take up and read”, and opened the letters of Paul. He was baptised by Ambrose in 387.',
      'He returned to Africa and was ordained a priest in Hippo Regius around 391. He became bishop there around 395 or 396, and held the post for about thirty-five years. As bishop he preached, judged disputes, ran a community and wrote enormously: books, hundreds of letters and sermons, many of which survive. He died on 28 August 430, as a Vandal army besieged Hippo, in the years when Roman power in North Africa was collapsing.',
    ],
    context: [
      'Augustine lived in a Roman world that had recently become officially Christian. Christianity had been made lawful early in the fourth century, and by the end of it, emperors were restricting traditional pagan worship. North African Christians were divided: the Donatists, a large local church, claimed that sacraments from clergy who had failed under earlier persecution were not valid, and the dispute was bitter and sometimes violent.',
      'Political order was also under pressure. In 410 the Visigothic leader Alaric took and plundered the city of Rome, a shock that echoed around the Mediterranean. Some pagans said that abandoning the old gods had brought the disaster. Augustine’s City of God was written as a reply. The Pelagian controversy over free will and grace also dominated his last decades.',
    ],
    ideas: [
      { title: 'The restless heart', text: 'The Confessions begins with the prayer that God has made us for himself, “and our heart is restless until it rests in you”. Augustine treats desire as the key to human life: people look for happiness in pleasure, ambition, knowledge and love, and nothing finite fully satisfies them. The book is written as a prayer, and it is also one of the first works to study the inner life in detail, including memory, habit and self-deception.' },
      { title: 'Evil as a lack, not a thing', text: 'Augustine had once believed, as a Manichaean, that evil is a substance in the world. Later he argued, drawing on Platonism, that everything that exists is good as far as it exists, and that evil is a privation, a missing or corrupted good, as blindness is the absence of sight. Moral evil comes from the will turning away from higher goods toward lower ones. Critics ask whether this really explains suffering, but the idea shaped Western thought for centuries.' },
      { title: 'Time as an experience of the mind', text: 'In Book 11 of the Confessions he asks what time is. He famously says he knows when no one asks him, but cannot explain it when someone does. He suggests that the past exists as memory and the future as expectation, and that time is somehow stretched out in the mind. This turned a puzzle about the cosmos into a question about consciousness, and philosophers have returned to it ever since.' },
      { title: 'Doubt and certainty', text: 'Against the sceptics, who said that nothing can be known, Augustine pointed out that even to be mistaken, you must exist. His line “if I am mistaken, I am” anticipates Descartes’s famous argument, though he uses it for his own purposes. He also held that we grasp eternal truths, such as those of mathematics, because God, whom he called the inner teacher, lights up the mind.' },
      { title: 'Two cities, two loves', text: 'In The City of God he describes history as the interweaving of two communities, one shaped by love of God and the other by love of self. They are mixed together in every earthly state, including Rome and the church, and will be separated only at the end of time. No empire, he said, is the kingdom of God, and no political success proves that a society is good. His other main contributions include a long, detailed doctrine of grace and original sin, which he sharpened in debate with Pelagius.' },
    ],
    principles: [
      'Know your desires, since what you love shapes who you are.',
      'Do not look for a final answer to your longing in things that pass away.',
      'Treat doubt as a stage on the way to truth, not as the end of the search.',
      'Do not mistake worldly power or success for goodness.',
      'Examine your own motives honestly, including the mixed and shameful ones.',
    ],
    practice: [
      'Once a week, ask what you wanted most that week, and whether it left you more settled or more restless.',
      'Try to describe an everyday experience of time, such as waiting, remembering or planning, without using a clock.',
      'When you are certain about someone else’s faults, look for the same fault in yourself first.',
    ],
    facts: [
      'The Confessions was written around AD 397–400 and has thirteen books. The first nine tell his life up to his mother’s death, and the last four turn to memory, time and the opening of the Bible.',
      'In one famous episode he describes stealing pears as a teenager, not because he was hungry, but for the thrill of doing wrong. He uses it as a study of the nature of sin.',
      'He recalls praying, as a young man, “give me chastity and continence, but not yet”.',
      'The City of God has twenty-two books and took him about thirteen years, roughly from 413 to 426. Orosius, a Spanish priest he knew, wrote a history at his urging that supported its argument.',
      'Late in life he wrote the Retractations, a review of his own books in which he points out what he had changed his mind about.',
      'By tradition his body was moved from Africa to Sardinia and later to Pavia in Italy, where his relics are venerated. Details of this journey come from later sources.',
    ],
    myths: [
      { myth: 'Augustine invented the doctrine of original sin.', reality: 'Earlier Christian writers already spoke of humanity’s shared fall, and Paul’s letters were the basis. Augustine developed the doctrine in a new, strong form, in particular that guilt and a damaged will pass from Adam to all people. Eastern Christians have generally not adopted it in his version.' },
      { myth: 'Augustine thought that sex itself is evil and the body is bad.', reality: 'He defended marriage and the goodness of creation, partly against the Manichaeans. But he also held that after the Fall sexual desire is no longer fully under the control of reason, and this view strongly shaped later Western attitudes. It has been criticised by many modern readers.' },
      { myth: 'He was only a theologian and rejected pagan philosophy.', reality: 'He was shaped by Cicero and the Platonists, and his ideas about the soul, God’s nature and the inner life are full of Platonic thought. He also criticised parts of pagan philosophy and religion.' },
    ],
    works: [
      { title: 'Confessions', note: 'A prayer and autobiography written around 397–400, about his life, his search for God and the mysteries of memory and time.' },
      { title: 'The City of God', note: 'A long work begun after the sack of Rome in 410, defending Christianity and presenting history as the story of two cities.' },
      { title: 'On the Trinity', note: 'A work on the Christian idea of God as three persons, which looks for traces of that structure in the human mind.' },
      { title: 'On the Free Choice of the Will', note: 'A dialogue about the origin of evil and human freedom, begun around 388 and finished some years later.' },
      { title: 'On Christian Doctrine', note: 'A guide to reading Scripture and speaking about it, which also contains early reflections on words and signs.' },
    ],
    legacy: [
      'Augustine became the most influential Christian thinker in the Latin West. Medieval writers such as Anselm and Aquinas built on him, and Protestant reformers like Luther and Calvin leaned heavily on his teaching about grace, while Catholic thinkers also claimed him. His writings about the self, the will and memory helped to create the modern interest in inner experience, and philosophers from Descartes to Wittgenstein have discussed his ideas on knowledge, time and language.',
      'His legacy is also contested. His reading of the “compel them to come in” parable in Luke was used for centuries to defend pressure on heretics, even though Augustine himself opposed the death penalty for Donatists. His teaching on original sin, predestination and sexuality has been both treasured and criticised. His best known works, however, remain widely read, and the Confessions in particular is still admired for its honest, searching voice.',
    ],
  },
  {
    slug: 'boethius',
    order: 480,
    dates: 'c. AD 480 – c. AD 524',
    place: 'Rome and Pavia (Italy)',
    era: 'Ancient',
    tradition: 'Late Roman philosophy',
    tagline: 'A Roman statesman who passed Greek logic to the Middle Ages and wrote a prison book on happiness and fate.',
    who: [
      'Boethius was born in Rome around AD 480, into the Anicii, one of the oldest and richest senatorial families. His father died when he was young, and he was brought up by the senator Symmachus, whose daughter Rusticiana he later married. He learned Greek, which was becoming rare in the Latin-speaking West, and studied philosophy, mathematics and literature. Italy was by then ruled by the Ostrogothic king Theodoric, who respected Roman institutions and gave senators important posts.',
      'Boethius rose quickly. He was consul in 510, and in 522 his two sons were appointed consuls together, which he describes in the Consolation as a great honour. In the same year he became magister officiorum, a senior post in the royal administration. In his book he says that he tried to resist corruption and defend the weak. Around 523, however, he was accused of treason, in connection with Albinus, a senator who had been charged with corresponding with the eastern emperor in Constantinople. Boethius denied the charges.',
      'He was imprisoned, probably near Pavia, and executed. The date of his death is usually given as 524, though some scholars place it a year or two later. Our reports of the manner of his death come from later sources, which speak of torture and clubbing, and should be read with care. His father-in-law Symmachus was also put to death. In prison, he wrote the Consolation of Philosophy, the book for which he is best known.',
    ],
    context: [
      'The western Roman Empire had formally ended a few years before Boethius was born, and Italy was now governed by Gothic kings. Theodoric was an Arian Christian, while most Romans, including Boethius, held the Nicene faith. Relations with the emperor in Constantinople, who ruled the Greek-speaking East, were uneasy, and when Theodoric grew suspicious of the senate’s loyalty, a charge of dealing with the eastern court was dangerous.',
      'Learning in Latin was thinning out. Few westerners could read Greek philosophy in the original. Boethius set himself the task of translating and explaining Greek works so that Latin readers could keep them. He said he hoped to translate all of Aristotle and Plato and to show how they agree. He completed only part of this, mainly in logic, but it was enough to carry Aristotle’s logic across the early Middle Ages.',
    ],
    ideas: [
      { title: 'True happiness cannot be taken away', text: 'In the Consolation, Boethius is visited in his cell by Lady Philosophy. She argues that wealth, fame, power and pleasure are on loan from Fortune and can always be lost. Real happiness has to be something that Fortune cannot remove, and she identifies it with the highest good, which she links to God. A person who has lost everything outwardly can still keep what matters most.' },
      { title: 'The wheel of Fortune', text: 'Fortune is shown as a goddess who turns a wheel, raising some people and lowering others. Philosophy says this is her nature and that it is foolish to complain of it. The picture became one of the best known images of the Middle Ages: it reminds rulers and ordinary people that luck can change, and that wisdom lies in not building one’s life on it.' },
      { title: 'The wicked are not really powerful', text: 'Philosophy argues that the good are in the end stronger than the wicked. Everyone wants the good, and those who choose evil fail to reach it, so they are in a sense weaker and more unhappy than the people they harm. This is a very old Platonic argument, and many readers find it hard to accept, but it gave Boethius a way to understand his own suffering.' },
      { title: 'Eternity and free will', text: 'If God knows everything in advance, can people be free? Boethius answers that God does not foresee things from within time. He lives in an eternal present, and his knowledge is like seeing someone walk by, which does not force the walker to walk. He defines eternity as the whole, simultaneous and perfect possession of endless life. Philosophers still discuss this answer.' },
      { title: 'Logic as a tool for theology', text: 'In his shorter theological treatises, the Opuscula sacra, he used the tools of Greek logic to discuss the Trinity and the nature of Christ. His definition of a person as an “individual substance of a rational nature” was widely used by later theologians. He also wrote on universals, asking whether general terms like “human” name something real, and set out the question that medieval philosophers debated for centuries.' },
    ],
    principles: [
      'Do not build happiness on things that Fortune can remove.',
      'Remember that good and bad luck both pass.',
      'Choose what is good over what is merely advantageous.',
      'Use clear logic, including on the hardest questions.',
      'Keep thinking and writing even when circumstances are at their worst.',
    ],
    practice: [
      'List what you would hate to lose, then sort it into what you can control and what depends on luck.',
      'In a setback, write yourself a dialogue as Boethius did: let a calm voice answer the anxious one.',
      'When a puzzle seems to force a bad conclusion, check whether you have assumed that something happens in time when it does not.',
    ],
    facts: [
      'The Consolation of Philosophy is a prosimetrum, a work that alternates prose and poems in different metres. It has five books.',
      'The Consolation does not mention Christianity directly, and relies on classical philosophy. Because he also wrote Christian theological treatises, scholars generally take him to have been Christian, and they debate why he left it out.',
      'King Alfred of Wessex is traditionally credited with an Old English version in the late ninth century. Chaucer later translated it as Boece, and Queen Elizabeth I produced her own translation in 1593.',
      'About four hundred medieval manuscripts of the Consolation survive, which shows how widely it was read.',
      'His translations and commentaries on Aristotle’s logic were for centuries the main source for Aristotle in Latin Europe, until more of his works were translated in the twelfth century.',
      'Dante places him among the wise spirits in the sphere of the Sun in the Paradiso, and he has been honoured in Pavia, where his feast is kept on 23 October.',
    ],
    myths: [
      { myth: 'Boethius was killed for being a Christian.', reality: 'The charge against him was treason. Later tradition honoured him as a martyr, because Theodoric was an Arian, but the political causes are better documented than any religious motive.' },
      { myth: 'The Consolation of Philosophy is a Christian devotional book.', reality: 'It is a work of classical philosophy that never mentions Christ or the Bible directly, though it speaks of God and providence in a way that Christians found very compatible. Medieval readers often read it as if it were Christian.' },
    ],
    works: [
      { title: 'The Consolation of Philosophy', note: 'Written in prison, around 523–524. A dialogue with Lady Philosophy about fortune, happiness, evil, providence and free will.' },
      { title: 'Translations and commentaries on Aristotle and Porphyry', note: 'Latin versions of Aristotle’s Categories and On Interpretation, with commentaries and with an introduction by Porphyry. They formed the basis of medieval logic.' },
      { title: 'Opuscula sacra (Theological Tractates)', note: 'Five short works on the Trinity and the natures of Christ, using Aristotelian logic.' },
      { title: 'On Arithmetic and On Music', note: 'Handbooks adapted from Greek sources. His writings helped shape the later “quadrivium” of arithmetic, music, geometry and astronomy.' },
    ],
    legacy: [
      'Edward Kennard Rand called Boethius the last of the Roman philosophers and the first of the scholastics, those medieval thinkers who used logic to explain faith. For the next six centuries, much of what Latin readers knew of Aristotle’s logic came through his hands, and the questions about universals that he raised drove a long debate in medieval schools.',
      'The Consolation became one of the most read books of the Middle Ages and the Renaissance, translated into many languages and imitated by poets. Its wheel of Fortune appears in medieval art and in Chaucer. Its picture of a person keeping their dignity under injustice still speaks to readers who face loss, and it is one of the best known examples of prison writing.',
    ],
  },
]
