import type { Profile } from './types'

export const MEDIEVAL_A: Profile[] = [
  {
    slug: 'al-ghazali',
    order: 1058,
    dates: 'c. 1058 – 1111',
    place: 'Tus (now northeastern Iran); taught in Baghdad and Nishapur',
    era: 'Medieval',
    tradition: 'Islamic philosophy and theology',
    tagline: 'A celebrated professor who walked away from fame, doubted everything, and found certainty in the inner life.',
    who: [
      'Abu Hamid al-Ghazali was born around 1058 in Tus, in what is now northeastern Iran, then part of the Seljuk Turkish empire. He studied law and theology in Nishapur under the scholar al-Juwayni, and he soon became known for his sharp mind. In 1091 the powerful Seljuk minister Nizam al-Mulk appointed him to the Nizamiyya college in Baghdad, one of the most prestigious teaching posts in the Muslim world.',
      'In 1095, at the height of his career, he suffered what he later described as a crisis. He found that he could hardly lecture, and he doubted whether his motives were sincere or were driven by fame and ambition. He resigned, gave away much of his wealth and left Baghdad. Later accounts have him travelling in Syria and Arabia and living a simple life of prayer and study, and he spent roughly a decade away from public teaching. In about 1106 he returned to teach for a while in Nishapur, and he spent his last years in Tus, where he died in December 1111.',
      'He wrote in Arabic and in Persian, on law, theology, logic, philosophy and spiritual life. Muslims later honoured him with the title “Proof of Islam” (Hujjat al-Islam), and many Sunni Muslims regard him as a “renewer” of the faith for his century. The same man who sharply criticised the philosophers also wrote a clear handbook of Aristotelian logic, so he is hard to fit into a simple label.',
    ],
    context: [
      'Al-Ghazali lived in a divided age. The Seljuk sultans ruled much of the Middle East in the name of the Abbasid caliph in Baghdad, while the rival Fatimid dynasty in Cairo supported Ismaili Shiism and challenged Sunni authority. Nizam al-Mulk founded colleges, the Nizamiyyas, partly to train scholars who could defend Sunni teaching, and al-Ghazali wrote against the Ismaili claim that a hidden infallible teacher was needed to interpret religion.',
      'At the same time, the works of Greek philosophy had been translated into Arabic and developed by thinkers such as al-Farabi and Ibn Sina (Avicenna). Some of their conclusions seemed to clash with the teaching of the Qur’an: that the world is eternal, that God does not know individual events, that bodies will not be resurrected. Al-Ghazali took these claims seriously enough to study them closely, and then to answer them.',
    ],
    ideas: [
      { title: 'Doubt as a path to certainty', text: 'In his spiritual autobiography, the Deliverer from Error, al-Ghazali describes how he came to doubt even the evidence of the senses and of reason. He says he was released from this scepticism not by an argument but by a light that God placed in his heart. The account is often compared with Descartes’s later use of doubt, though the two men reached very different conclusions.' },
      { title: 'The Incoherence of the Philosophers', text: 'Around 1095 he wrote a famous attack on twenty positions of the Aristotelian philosophers, especially Ibn Sina. His main complaint was that they claimed strict proof but rested on unproven assumptions. He accused them of unbelief on only three points: the eternity of the world, the claim that God knows only universals, and the denial of bodily resurrection. On the others he called them mistaken, not disbelievers.' },
      { title: 'Causes and habits', text: 'Al-Ghazali argued that we observe events following one another, such as cotton burning when it meets fire, but we never observe a necessary link between them. God, he said, could create the effect without the usual cause, which leaves room for miracles. Scholars debate how far this was a full doctrine of occasionalism, in which God directly causes everything, or a more limited claim about what can be proved.' },
      { title: 'Knowledge must change the heart', text: 'In his great work, the Revival of the Religious Sciences, he argued that knowing the rules of religion is not enough. Pride, greed, envy and show-offishness corrupt even good deeds, so a person has to examine the inner life and train it. The book joins law, ethics and Sufi spiritual practice into one guide to living well.' },
      { title: 'Logic is a tool, not a threat', text: 'Although he criticised the philosophers’ metaphysics, he defended Aristotelian logic as a neutral instrument, useful to jurists and theologians alike. He did not reject reason. He tried to set its limits and to show where it needed support from revelation and from direct experience.' },
    ],
    principles: [
      'Check your motives as carefully as your actions.',
      'Doubt the things you assume, and look for what survives the doubt.',
      'Knowledge that does not change how you live is incomplete.',
      'Use reason with care: know what it can prove and what it cannot.',
      'Treat character as something trained by daily habit.',
    ],
    practice: [
      'Before an important task, ask honestly whether you are doing it for its own sake or for praise, and notice the answer without excusing it.',
      'Pick one habit you want to change, such as impatience or envy, and work on it a little each day instead of trying to fix it by willpower once.',
      'When you read an argument from an opponent, state it fairly first, then look for the premises it rests on.',
    ],
    facts: [
      'In Latin Europe he was known as Algazel. A twelfth-century Latin translation of his summary of Avicenna’s philosophy was read without his refutation, so for a time he was mistaken for a follower of the philosophers.',
      'His brother Ahmad al-Ghazali was also a respected Sufi writer.',
      'The Incoherence of the Philosophers was answered a century later by Ibn Rushd (Averroes), who titled his reply the Incoherence of the Incoherence.',
      'He also wrote a shorter Persian summary of his spiritual ideas, usually known as the Alchemy of Happiness.',
      'In the Deliverer from Error he describes four groups of seekers after truth: theologians, philosophers, followers of a hidden infallible teacher, and Sufis. He says he examined each in turn.',
      'His reasons for leaving Baghdad have been debated. Some scholars stress his own account of a spiritual crisis, others the political upheaval after the deaths of Nizam al-Mulk and Sultan Malikshah in 1092.',
    ],
    myths: [
      { myth: 'Al-Ghazali ended philosophy and science in the Islamic world.', reality: 'Scholars today reject this idea. Philosophy and science continued for centuries after him, for example in the astronomy of the Maragha observatory in the thirteenth century. His attack targeted specific metaphysical claims, and Avicennan philosophy itself went on to thrive in later Islamic thought.' },
      { myth: 'He rejected reason in favour of mysticism.', reality: 'He wrote a textbook of logic, used rational argument constantly, and argued that valid demonstration is never wrong. What he opposed was the claim that philosophy alone could answer every question about God and the afterlife.' },
      { myth: 'He denied that causes have any effect.', reality: 'He argued that a necessary connection between cause and effect cannot be proved from observation. He accepted that God normally acts in regular, predictable ways, which is why we can rely on experience.' },
    ],
    works: [
      { title: 'The Revival of the Religious Sciences (Ihya ulum al-din)', note: 'His largest work, a guide to worship, daily conduct and the cleansing of the heart, and the book for which he is best loved.' },
      { title: 'The Incoherence of the Philosophers (Tahafut al-falasifa)', note: 'His critique of twenty philosophical positions, with the three charges of unbelief.' },
      { title: 'The Deliverer from Error (al-Munqidh min al-dalal)', note: 'A short spiritual autobiography about doubt, the search for certainty and his turn to Sufism.' },
      { title: 'The Niche of Lights (Mishkat al-anwar)', note: 'A mystical reading of the Qur’an’s “Light Verse”, sometimes read as showing a more philosophical side of his thought.' },
      { title: 'Doctrines of the Philosophers (Maqasid al-falasifa)', note: 'A clear summary of Avicenna’s philosophy, written as a preparation for the Incoherence.' },
    ],
    legacy: [
      'Within Sunni Islam his joining of law, theology and spiritual practice became a model, and the Revival is still read widely today. His careful use of logic in theology influenced the later Ash’arite tradition. His criticisms of the philosophers forced later thinkers, including Ibn Rushd, to defend and refine their positions.',
      'Beyond the Muslim world, translated works carried his ideas to Latin and Jewish readers, and historians trace echoes of his arguments about causation in later European debates, up to Hume. He remains a rare example of a thinker who was at once a rigorous logician, a critic of rationalism and a guide to the inner life.',
    ],
  },
  {
    slug: 'peter-abelard',
    order: 1079,
    dates: '1079 – 1142',
    place: 'Le Pallet in Brittany; taught in Paris; died near Chalon-sur-Saone, France',
    era: 'Medieval',
    tradition: 'Scholasticism',
    tagline: 'A brilliant logician who taught Paris to ask questions, and whose life ended in scandal, love letters and condemnation.',
    who: [
      'Peter Abelard was born in 1079 in Le Pallet, a village near Nantes in Brittany, the eldest son of a minor knight. He gave up his inheritance to study philosophy and travelled to the schools of northern France. He studied with the logician Roscelin and then with William of Champeaux in Paris, whom he soon challenged in debate. By his twenties he was lecturing himself, and by around 1114 he was a famous teacher in Paris, where students crowded to hear him.',
      'Around 1115 he began to teach a young woman named Heloise, the niece of a canon of Notre Dame called Fulbert. She was unusually well educated, and the two fell in love. They had a son, whom they named Astrolabe, and married in secret. Fulbert, feeling dishonoured, had Abelard attacked and castrated. Abelard then became a monk at Saint-Denis, and Heloise became a nun. In later years she became the abbess of the Paraclete, a community that Abelard had founded.',
      'The rest of his life was a series of disputes. In 1121 a council at Soissons condemned his book on the Trinity and, according to his own account, made him burn it. He later served as abbot of a remote monastery in Brittany and returned to teaching in Paris. In 1141 Bernard of Clairvaux, the most influential churchman of the day, had a council at Sens condemn propositions drawn from his works. Abelard appealed to Rome. On the way he stopped at Cluny, where abbot Peter the Venerable gave him shelter, and he died in 1142 at a priory near Chalon-sur-Saone.',
    ],
    context: [
      'The twelfth century saw the rise of the cathedral schools of northern France, forerunners of the University of Paris. Teachers such as Abelard attracted students from across Europe, and a new style of study grew up, centred on logic and public debate. The recovery of more of Aristotle’s logical works helped fuel this movement.',
      'Not everyone welcomed it. Monastic leaders such as Bernard of Clairvaux believed that faith was approached through prayer and humility, and they feared that arguing about the Trinity with the tools of logic would turn mysteries into puzzles. The conflict between Abelard and Bernard is often described as one between two styles of religion: the schoolroom and the cloister.',
    ],
    ideas: [
      { title: 'Questioning leads to truth', text: 'In his Sic et Non (“Yes and No”) Abelard collected 158 questions on which respected Church writers seemed to disagree. He did not give the answers. In his preface he argued that doubt is how learning begins, since by questioning we come to enquiry, and by enquiry to truth. The book helped to create the scholastic method of setting authorities against each other and resolving the conflict by reasoning.' },
      { title: 'Universals and language', text: 'The problem of universals asks what general words, such as “human” or “red”, refer to. Abelard rejected the view that they name real universal things existing apart from individuals, and he also rejected his teacher Roscelin’s view that they are just breaths of air. For him, general words apply to many individuals because those individuals share a likeness. Historians usually call this a form of nominalism or conceptualism.' },
      { title: 'Morality lies in intention', text: 'In his Ethics, also called Know Yourself, Abelard argued that an action is not good or bad in itself. What counts is the intention behind it, and whether the person consents to what he knows to be wrong. A person who acts out of ignorance or necessity, without bad intent, has not sinned, although his action might still be harmful. The view was controversial, and critics thought it excused too much.' },
      { title: 'Love as the heart of redemption', text: 'Abelard taught that Christ’s life and death show God’s love so clearly that they awaken love in human beings, and this love is what reconciles them to God. This is often called the moral influence theory of atonement. It was set against the dominant view that Christ’s death paid a debt or satisfied divine honour.' },
      { title: 'A clearer logic of sentences', text: 'In logic Abelard studied how propositions work. He saw that the same content can be asserted, asked or wished for, and he made careful distinctions about what statements about the future and about possibility mean. Historians of logic regard him as one of the greatest logicians between antiquity and the late Middle Ages.' },
    ],
    principles: [
      'Ask the question before accepting the answer.',
      'Judge actions by what the person intended, and by what he knew.',
      'Use reason, but remain humble about what it can reach.',
      'Learn by comparing authorities, not simply by obeying one.',
      'Understanding should lead to love, not only to argument.',
    ],
    practice: [
      'When you read two experts who disagree, list the points on which they really differ and the points where they only use words differently.',
      'Before judging someone’s action, ask what they meant to do and what they knew at the time.',
      'Write down one belief you hold on authority alone, and try to find the reasons behind it.',
    ],
    facts: [
      'Abelard described his own life in the Historia calamitatum (“The Story of My Troubles”), a long letter written in the 1130s. Its self-portrait is vivid and not entirely modest.',
      'The letters between Abelard and Heloise, which were preserved in later manuscripts, have been read as moving testimony and also, by some modern scholars, argued over as to how far they were edited or shaped later. The debate is not settled.',
      'Heloise’s age at the start of the affair is not recorded, and modern writers give differing estimates, so it is best left uncertain.',
      'Their traditional tomb is now in the Pere Lachaise cemetery in Paris, though historians note that how their remains moved over the centuries is complicated.',
      'Abelard also wrote hymns and laments that survive, and he is sometimes counted among the early composers of poetry in Latin.',
      'He named his son Astrolabe, after the scientific instrument. After Abelard’s own death, little is known for certain about Astrolabe’s later life.',
    ],
    myths: [
      { myth: 'Abelard was condemned as a heretic and died in disgrace.', reality: 'He was condemned at Soissons and Sens, and the condemnation was confirmed by Pope Innocent II. But Peter the Venerable welcomed him to Cluny, and wrote to Heloise of his peaceful last months and devout end.' },
      { myth: 'The affair with Heloise was the main reason his writings were condemned.', reality: 'The scandal made him vulnerable, but the formal charges concerned his teaching, especially on the Trinity and on sin and redemption. Bernard of Clairvaux attacked his rationalism, not his private life.' },
    ],
    works: [
      { title: 'Sic et Non', note: 'A collection of conflicting quotations from Church authorities, with a preface on how to resolve them.' },
      { title: 'Historia calamitatum', note: 'An autobiographical letter that is the main source for his early life.' },
      { title: 'Ethics (Scito te ipsum)', note: 'A work on sin and intention, probably unfinished.' },
      { title: 'Logica ingredientibus and Dialectica', note: 'His major writings on logic and language.' },
      { title: 'Collationes (Dialogue between a Philosopher, a Jew and a Christian)', note: 'A late dialogue on which way of life leads to the highest good.' },
    ],
    legacy: [
      'Abelard’s method of asking questions and weighing authorities passed into the universities, where Peter Lombard’s Sentences and later the great summae of the thirteenth century used similar procedures. His students included men who became bishops, cardinals and a pope. His work on ethics and logic remained in circulation, even though some of it was condemned.',
      'In later centuries he and Heloise became symbols of love and of the clash between the individual and institutions. For historians of thought, he stands for the confidence of the early schools that careful reasoning belongs in the study of faith, and for the dangers it raised in that period.',
    ],
  },
  {
    slug: 'averroes',
    order: 1126,
    dates: '1126 – 1198',
    place: 'Cordoba, al-Andalus (now Spain); died in Marrakesh',
    era: 'Medieval',
    tradition: 'Islamic Aristotelianism',
    tagline: 'The judge and physician whose commentaries made him “the Commentator” on Aristotle for Muslims, Jews and Christians.',
    who: [
      'Abu al-Walid Muhammad ibn Rushd, known in Latin as Averroes, was born in 1126 in Cordoba, in the Muslim-ruled part of Spain called al-Andalus. His family were prominent jurists, and his grandfather had been the city’s chief judge. He studied law, medicine, theology and philosophy, and he served as a judge (qadi), first in Seville and later in Cordoba.',
      'Around 1169 he was introduced to the Almohad caliph Abu Yaqub Yusuf, ruler of North Africa and Muslim Spain, by the philosopher Ibn Tufayl. A later account says the caliph questioned him about whether the heavens were eternal and then asked him to produce clear commentaries on Aristotle. We cannot be sure of the details, but Averroes did spend much of his career writing them, and he also served as a court physician.',
      'In about 1195, under the caliph Abu Yusuf Yaqub al-Mansur, he fell out of favour and was sent to Lucena, a town near Cordoba. Later reports say that some of his books were condemned. The reasons are debated, and many historians think politics, and the caliph’s need for the support of conservative scholars, mattered more than philosophy. He was soon restored to favour and died in Marrakesh in December 1198. Tradition says his body was carried back to Cordoba.',
    ],
    context: [
      'Andalusia was a place of learning in which Muslims, Jews and Christians shared libraries and scholars, though the age was also one of conflict. The Almohads, a reforming movement from the Atlas Mountains, had taken over from the Almoravids in the mid-twelfth century. They supported scholarship, including medicine and philosophy, but demanded religious conformity, and their attitude toward philosophy changed over time.',
      'Philosophy in Arabic had already been shaped by al-Farabi and Ibn Sina, who blended Aristotle with Neoplatonic ideas. Averroes believed that these writers had drifted from the real Aristotle, and he set out to recover his teaching through careful reading. His critique of al-Ghazali’s attack on philosophy was part of the same project.',
    ],
    ideas: [
      { title: 'Philosophy and revelation do not conflict', text: 'In the Decisive Treatise he argued, as a matter of Islamic law, that the Qur’an itself urges people to reflect on the natural world, so the study of philosophy is permitted and even recommended for those able to do it. Truth, he wrote, does not oppose truth. Where scripture seems to conflict with demonstrated reason, the text should be interpreted figuratively, but only by those with the training to do so.' },
      { title: 'Different readers, different arguments', text: 'He held that people reach the truth in different ways: through rhetoric, through dialectic, and through strict demonstration. Most people should be taught in ordinary language, while demonstration belongs to trained philosophers. He worried about public debates over difficult interpretations that might confuse ordinary believers.' },
      { title: 'Defending causes', text: 'In reply to al-Ghazali he argued in the Incoherence of the Incoherence that denying real causes destroys knowledge itself, since to know a thing is to know its causes. Fire really burns, and things have natures that explain what they do.' },
      { title: 'The unity of the intellect', text: 'Following Aristotle’s difficult remarks on the intellect, Averroes held, at least in his later commentaries, that the intellect that grasps universal truths is not a separate part of each individual but is shared among humankind. Scholars still debate precisely what he meant and how his view changed between works.' },
      { title: 'Law that explains itself', text: 'As a jurist he wrote the Distinguished Jurist’s Primer, a work that sets out disagreements between schools of Islamic law and explains the reasoning behind each. The aim is to understand why legal experts differ, not only to list their conclusions.' },
    ],
    principles: [
      'Seek the truth wherever it comes from, including from earlier thinkers of other traditions.',
      'Expect true things to fit together, and look for the reading that makes them fit.',
      'Match the way you explain something to the person you are talking to.',
      'Understand a position well before refuting it.',
      'Study the causes of things instead of stopping at appearances.',
    ],
    practice: [
      'When two sources you trust seem to contradict each other, look for a reading in which both could be true before choosing one.',
      'Practise explaining one idea in three ways: a short story, a plain argument and a precise definition.',
      'When you read an influential commentator, go back to the original text and compare.',
    ],
    facts: [
      'Medieval Europeans called him simply “the Commentator”, as Aristotle was “the Philosopher”. In Dante’s Divine Comedy he appears among the virtuous pagans and non-Christians in the first circle of Hell, described as the one who made the great Commentary.',
      'His commentaries came in three kinds: short summaries, middle paraphrases and long line-by-line commentaries. They covered most of Aristotle’s surviving works.',
      'His medical encyclopedia, known in Latin as the Colliget, was widely read in Europe, and it contains observations such as one suggesting that the retina is the part of the eye that receives light.',
      'Michael Scot translated some of his commentaries into Latin around the 1220s, and Hebrew translations became standard reading for Jewish philosophers.',
      'Thomas Aquinas wrote a treatise attacking Averroes’s view of the intellect, called On the Unity of the Intellect against the Averroists.',
      'Many of his works survive only in Hebrew or Latin translation, because the Arabic originals were lost.',
    ],
    myths: [
      { myth: 'Averroes taught a “double truth”: that something can be true in philosophy and false in religion.', reality: 'He argued the opposite: truth cannot contradict truth. The idea of two truths was attributed to certain Latin Averroists, and the charge shaped how Christian authorities viewed him.' },
      { myth: 'He was a secular rationalist who wanted to separate reason from religion.', reality: 'He was a practising jurist who defended philosophy on religious grounds, and he thought the two were allies. Modern readers sometimes see him through later European debates, which do not fit his own setting well.' },
    ],
    works: [
      { title: 'Decisive Treatise (Fasl al-maqal)', note: 'A short legal and philosophical argument that philosophy is permitted, and that scripture and reason agree.' },
      { title: 'Incoherence of the Incoherence (Tahafut al-tahafut)', note: 'His reply to al-Ghazali’s Incoherence of the Philosophers.' },
      { title: 'Commentaries on Aristotle', note: 'Short, middle and long commentaries on works such as the Physics, On the Soul and the Metaphysics.' },
      { title: 'The Distinguished Jurist’s Primer (Bidayat al-mujtahid)', note: 'A comparative work on Islamic legal disagreement and its causes.' },
      { title: 'Kulliyat (the Colliget)', note: 'A general medical encyclopedia, known in Latin translation.' },
    ],
    legacy: [
      'In the Latin West, his commentaries helped introduce Aristotle to the universities. Some masters at Paris, such as Siger of Brabant, drew on him in ways that alarmed Church authorities, and Paris condemned a number of Aristotelian propositions in 1270 and 1277. Aquinas was both a student of Averroes and one of his sharpest critics. Averroes’s influence on Jewish thought was also considerable, for example on Gersonides.',
      'In the Islamic world his work was less continuously read after his death, and later philosophy there took other directions. In recent decades scholars have revisited him as a thinker in his own right, whose argument for the harmony of religion and reason, and for the careful, patient reading of texts, still speaks to modern readers.',
    ],
  },
  {
    slug: 'thomas-aquinas',
    order: 1225,
    dates: 'c. 1225 – 1274',
    place: 'Roccasecca, southern Italy; taught in Paris, Cologne and Italy',
    era: 'Medieval',
    tradition: 'Scholasticism',
    tagline: 'The Dominican friar who built a great system joining faith and reason, drawing on Aristotle.',
    who: [
      'Thomas was born around 1225 at or near Roccasecca, in the kingdom of Sicily in southern Italy, into a family of minor nobility. As a boy he was sent to the Benedictine abbey of Monte Cassino, and later he studied at the University of Naples. There he met members of the new Dominican order, a group of friars devoted to preaching and study, and decided to join, around 1244.',
      'His family opposed the decision and, according to early accounts, held him at home for about a year before he was released. He went on to study with the Dominican scholar Albert the Great, in Paris and then in Cologne. His classmates reportedly nicknamed him the “dumb ox” for his quiet and large frame, and Albert is said to have replied that the ox would one day bellow so loudly that the world would hear it.',
      'He became a master of theology at Paris in 1256, and he taught there again from 1268 to 1272, with years in Italy in between, at Orvieto, Rome and Naples. In December 1273, according to tradition reported by his companion, he had an experience while saying Mass after which he stopped writing, and said that all he had written seemed like straw compared with what he had seen. He died on 7 March 1274 at the Cistercian abbey of Fossanova, while travelling to the Council of Lyon. He was canonised in 1323.',
    ],
    context: [
      'In the thirteenth century the full works of Aristotle reached Latin Europe, together with the commentaries of Arabic writers such as Averroes. They offered a powerful account of nature, the soul and ethics that did not rest on Christian revelation, and some churchmen feared them. Several of Aristotle’s books were restricted at Paris early in the century, and later became standard texts.',
      'The new universities were also fierce places. Secular masters resented the Dominicans and Franciscans, and philosophers argued about the limits of reason. Aquinas worked in this atmosphere. He read Aristotle in careful new translations, helped by his friend William of Moerbeke, and tried to show that the best of Greek philosophy could be harmonised with Christian faith.',
    ],
    ideas: [
      { title: 'Faith and reason work together', text: 'Aquinas held that some truths about God, such as that God exists, can be reached by reason, while others, such as the Trinity, are known only by revelation. Because both come from the same source, he argued, they cannot truly contradict each other. Where they seem to, we have probably misunderstood one of them.' },
      { title: 'The Five Ways', text: 'In the Summa Theologiae he gave five short arguments that God exists, starting from features of the world: motion, causation, contingency, degrees of perfection and order. They are not meant as the whole of his case, and scholars debate how they are best read. They aim to show that the world points beyond itself to a first and necessary source.' },
      { title: 'Natural law', text: 'Human beings, Aquinas argued, can grasp basic moral principles by reason, since our nature inclines us toward goods like life, family, knowledge and living in society. Human laws are just when they follow from these principles, and an unjust law has the character of violence, not of true law. The idea has shaped Western debate about law and rights.' },
      { title: 'Analogy: how we speak of God', text: 'Words such as “good” or “wise” cannot mean exactly the same for God and for creatures, or the divine would be reduced to our scale. Nor can they mean something wholly different, or we would say nothing. Aquinas proposed that they are used by analogy, with a related but not identical meaning. He also insisted that we know better what God is not than what God is.' },
      { title: 'Soul and body as one', text: 'Following Aristotle, he taught that the soul is the form of the body, and that a human being is a unity of body and soul, not a spirit trapped in a machine. This shaped his views on knowledge, which begins in the senses and is completed by the intellect, and on happiness, which he saw as ultimately found in knowing God.' },
    ],
    principles: [
      'Truth is one: look for how what you know can fit together.',
      'State the strongest objection to your view before you answer it.',
      'Take your starting point from experience, and reason from there.',
      'Law and politics answer to a moral standard beyond them.',
      'Happiness depends on virtue, and it is more than pleasure or success.',
    ],
    practice: [
      'Before arguing for your position, write the best case against it in its strongest form, and answer that.',
      'When a word is ambiguous, ask in what sense it is used, instead of assuming it means the same in each case.',
      'List the things you want and sort them: which are good in themselves, which are only means, and which are in conflict?',
    ],
    facts: [
      'The Summa Theologiae is unfinished. It was left incomplete when he stopped writing in December 1273, and a supplement was later compiled from his earlier writings by others.',
      'Each section of the Summa follows a set pattern: a question, objections, a statement on the other side, his answer, and replies to each objection.',
      'He was a prolific writer, with commentaries on scripture and on Aristotle, many disputed questions, and shorter works such as On Being and Essence. Witnesses at his canonisation inquiry said he sometimes dictated to several secretaries at once.',
      'Tradition credits him with the Latin hymns for the feast of Corpus Christi, including Pange lingua, though scholars have discussed the details of authorship.',
      'After his death a number of positions associated with his teaching were included in or close to the condemnations issued at Paris in 1277 and by the Archbishop of Canterbury, Robert Kilwardby, at Oxford. They were later reversed in effect.',
      'He was declared a Doctor of the Church in 1567, and Pope Leo XIII’s encyclical Aeterni Patris in 1879 promoted his philosophy for Catholic schools.',
    ],
    myths: [
      { myth: 'Aquinas thought that reason could prove everything about God.', reality: 'He limited what reason can show. He believed it can establish that God exists and some divine attributes, but not the central Christian doctrines, which he held to be known only by revelation.' },
      { myth: 'He came to reject his own work as worthless before he died.', reality: 'The “straw” remark is reported by his companion, and it is better read as an expression of awe at what he had experienced than as a retraction. He did not disown his writings.' },
      { myth: 'His teaching was accepted by the Church from the start.', reality: 'It was controversial in his own lifetime. Some of his positions were criticised or condemned within a few years of his death, and only gradually did he become the central authority he is today.' },
    ],
    works: [
      { title: 'Summa Theologiae', note: 'His great, unfinished synthesis, in three parts, covering God, human action and morality, and Christ and the sacraments.' },
      { title: 'Summa contra Gentiles', note: 'A systematic work written around 1259–1265 that argues for Christian teaching in a way aimed at non-Christian readers, with much reasoning from first principles.' },
      { title: 'On Being and Essence (De ente et essentia)', note: 'A short early work on the basic structure of things, including the difference between what a thing is and that it is.' },
      { title: 'Disputed Questions', note: 'Records of university debates, such as On Truth and On Evil.' },
      { title: 'Commentaries on Aristotle', note: 'Careful commentaries on works including the Ethics, the Physics, the Metaphysics and On the Soul.' },
    ],
    legacy: [
      'Aquinas gave Christian thought one of its most complete frameworks, and his work shaped Catholic theology and philosophy for centuries. The Dominicans adopted him as their authority, and after Aeterni Patris in 1879 Thomism became a major school in Catholic education. His influence extends to natural law and just war thinking, and to modern debates in ethics, metaphysics and philosophy of religion.',
      'Many non-Catholic philosophers also study him. Twentieth-century thinkers such as Elizabeth Anscombe and Alasdair MacIntyre drew on his ethics of virtue, and other scholars read him as a major contributor to the long conversation between Greek, Arabic and Latin thought. His style of patient argument remains a model.',
    ],
  },
  {
    slug: 'meister-eckhart',
    order: 1260,
    dates: 'c. 1260 – c. 1328',
    place: 'Thuringia (Germany); taught in Paris, Strasbourg and Cologne',
    era: 'Medieval',
    tradition: 'Christian mysticism',
    tagline: 'A Dominican preacher who spoke of the soul as a place where God is born, and was tried for it.',
    who: [
      'Eckhart von Hochheim was born around 1260, probably near Tambach in Thuringia, in central Germany. He joined the Dominican order as a young man, possibly at Erfurt, and studied in Cologne and then in Paris. Like Aquinas before him, he became a master of theology at Paris, a post he held in the early 1300s and again in 1311. Few friars were given the chair twice, and he was known as “Meister”, the German form of “master”.',
      'He also held high office in his order. He was prior at Erfurt and then provincial of the Dominican province of Saxony, which covered dozens of houses, and he later worked in Strasbourg and Cologne. His duties included pastoral care of communities of women, and he preached in German, as well as writing in Latin for academic readers. Many of his vernacular sermons survive in copies made by listeners and later readers, so the exact wording is sometimes uncertain.',
      'In 1326 the Archbishop of Cologne began an inquisitorial case against him, and an investigation of his teaching followed. Eckhart defended himself, arguing that he had no wish to teach error and was ready to correct any mistake, and he appealed to the pope at Avignon. He most likely died in 1328, before a verdict. In March 1329 Pope John XXII issued the bull In agro dominico, which condemned twenty-eight propositions from his works, seventeen as heretical and eleven as dangerous or suspect. The bull says that Eckhart had retracted whatever might lead people astray, and he was not himself declared a heretic.',
    ],
    context: [
      'Late medieval Germany saw an upsurge of lay devotion. Communities of women, such as the Beguines and Dominican nuns, hungered for spiritual teaching in their own language. Eckhart’s sermons, delivered to such audiences, took the difficult ideas of the schools and put them in everyday speech, which is part of what made them both powerful and risky.',
      'The Church was also anxious about movements that seemed to claim direct union with God and so to bypass its authority. Around 1310 a Beguine writer, Marguerite Porete, was burned in Paris for her book on the soul’s union with God, and Eckhart was in Paris soon afterwards. Historians discuss how far he knew her book and whether it affected his later problems. Rivalries between Dominicans and Franciscans, and between local church leaders, also played a part in his case.',
    ],
    ideas: [
      { title: 'The birth of God in the soul', text: 'Eckhart taught that the Word, which Christians believe God eternally speaks, is born again in the soul of whoever is open to it. For him the point of religion is not to look for God far away but to let this birth happen within. The language is bold, and some of it sounded to critics as if human beings were being made equal to God.' },
      { title: 'God and the Godhead', text: 'He distinguished between God as the Trinity and as the Creator, known through names and images, and the “Godhead”, the hidden depth beyond all names. He called it a desert or abyss in which nothing can be said. This is a form of negative theology, which holds that no human words can capture the divine.' },
      { title: 'Detachment and letting go', text: 'The way to such openness, he said, is detachment: freeing oneself from the grip of possessions, images, plans and even religious desires. In a famous sermon he described true poverty as wanting nothing, knowing nothing and having nothing. Detachment is not coldness, since he insisted that it makes room for love and compassion toward others.' },
      { title: 'The ground of the soul', text: 'Eckhart spoke of a “ground” or a “spark” in the soul where God and the human being meet. Some of his statements, such as that something in the soul is uncreated, were among those that the bull of 1329 condemned. He himself presented them as consistent with orthodox teaching.' },
      { title: 'Ordinary life as the place of God', text: 'He did not teach a flight from the world. He argued that a person can find God in daily work and service, and that practical action, such as caring for the needy, can be of more value than ecstatic experience. In his Talks of Instruction he told his hearers to meet God in the everyday, not just in seclusion.' },
    ],
    principles: [
      'Let go of what you cling to, and see what remains.',
      'Look inward as well as outward for what you seek.',
      'Do your ordinary work with full attention.',
      'Do not mistake your images of God, or of yourself, for the thing itself.',
      'Be as open to what you receive as you are eager to ask for it.',
    ],
    practice: [
      'Spend ten minutes a day in silence with no goal, and notice what you try to reach for.',
      'Choose one small task and do it with your whole attention, as if nothing else mattered.',
      'Notice a possession, a plan or an opinion you hold too tightly, and imagine loosening your grip.',
    ],
    facts: [
      'One saying often quoted from his German sermons, in translation, is that the eye with which he sees God is the same eye with which God sees him.',
      'He wrote in both Latin and German. He planned a large Latin work, the Opus tripartitum, which was never finished, and many of his German sermons survive.',
      'His pupils Johannes Tauler and Henry Suso, also Dominicans, carried his teaching on and shaped German spirituality in the fourteenth century.',
      'The bull of 1329 forbade the spread of the condemned propositions, but it did not end the circulation of his writings, and some were passed on under other names.',
      'Many of his works were lost or forgotten for centuries and rediscovered by scholars in the nineteenth century, after which a modern critical edition took many decades.',
      'Nicholas of Cusa, a fifteenth-century cardinal and philosopher, owned and annotated copies of Eckhart’s works.',
    ],
    myths: [
      { myth: 'Eckhart was condemned as a heretic and the Church burned his books.', reality: 'He was never formally declared a heretic. He died while his case was pending, and the bull condemned specific propositions as heretical or suspect, while stating that he had recanted any error.' },
      { myth: 'He was a pantheist who thought God and the world are the same thing.', reality: 'Many scholars read him as a Christian Neoplatonist who insisted that God is beyond creation as well as within it. Whether some of his wording went too far is still debated, and his critics in 1329 thought it did.' },
      { myth: 'He taught a spirituality of escape from ordinary life.', reality: 'In his surviving works he often insists that inner freedom has to show itself in work, service and charity.' },
    ],
    works: [
      { title: 'Opus tripartitum (Latin)', note: 'A planned three-part work of which only parts, including Latin sermons and commentaries, were completed.' },
      { title: 'German Sermons', note: 'Dozens of sermons in Middle High German, many with uncertain wording because they were recorded by listeners.' },
      { title: 'Talks of Instruction (Reden der Unterweisung)', note: 'Early practical conversations for younger Dominicans on detachment, obedience and the spiritual life.' },
      { title: 'Book of Divine Consolation', note: 'A work of comfort written for a noblewoman in grief.' },
      { title: 'On Detachment (Von abegescheidenheit)', note: 'A short treatise on detachment, often attributed to him, though some scholars debate its authenticity.' },
    ],
    legacy: [
      'In the generation after his death, Tauler and Suso kept Eckhart’s ideas alive in German spiritual writing, and his language shaped later mystical traditions in Germany and the Low Countries. Philosophers and theologians later found his thought attractive, including Nicholas of Cusa, and, in the nineteenth century, German idealists and Romantics.',
      'Today Eckhart is read by Christians, scholars of religion and general readers, who often compare him with Buddhist, Hindu and Sufi writers on letting go of the self. Such comparisons are suggestive but need care, because his thought is rooted in medieval Christian theology. His reputation has also been used for purposes far from his own, so it is wise to read the sermons themselves.',
    ],
  },
]
