import type { Profile } from './types'

export const MEDIEVAL_B: Profile[] = [
  {
    slug: 'shota-rustaveli',
    order: 1172,
    dates: 'Late 12th – early 13th century (exact dates unknown)',
    place: 'Georgia, at the court of Queen Tamar',
    era: 'Medieval',
    tradition: 'Georgian literature and thought',
    tagline: 'The poet of Georgia’s golden age, who made friendship, generosity and just rule the heart of a national epic.',
    who: [
      'Shota Rustaveli is the author of ვეფხისტყაოსანი (Vepkhistqaosani), usually called “The Knight in the Panther’s Skin”, the national epic of Georgia. Very little about the man himself is securely known. “Rustaveli” (Rustveli in older Georgian) is probably not a family name but a territorial epithet meaning “of Rustavi”, and Georgian tradition links his family with Rustavi in Meskheti, in the south-west of the country. Georgian writers of the fifteenth to eighteenth centuries are almost unanimous in calling the poet Shota Rustaveli, but those writers lived centuries after him.',
      'What is documented is mostly the poem itself. Its opening and closing lines praise Queen Tamar, who reigned from 1184 to 1213, and her husband David Soslan, so it was written in her time and for her court. Scholars date it to no earlier than the 1180s and often suggest about 1205–1207. Almost all scholars accept that one gifted author wrote it, though they cannot say much more about his life with confidence.',
      'Everything else is tradition. Later Georgian accounts say that he served Tamar as a high treasurer, and the poem’s deep knowledge of Persian poetry has led many to think he was educated at the Georgian monastic centres and perhaps abroad. A portrait in the Georgian-founded Monastery of the Cross in Jerusalem shows a kneeling figure in secular dress labelled “Rustveli”. It was described by a Georgian pilgrim in the 1750s and rediscovered in 1960, and it is why tradition says that he spent his last years in Jerusalem. Scholars debate how far this portrait and the late sources that mention a treasurer can be trusted. A popular legend that he loved the queen himself, and withdrew to Jerusalem out of that hopeless love, is a romantic story with no support in the documents.',
    ],
    context: [
      'Rustaveli’s world was the Kingdom of Georgia at its height. Under King David IV (“the Builder”) and then Queen Tamar, the kingdom controlled much of the Caucasus, grew rich on trade, and built monasteries, schools and fortresses. Tamar was an unusual ruler, a woman who held the royal title in her own right, and the poem reflects a court where a woman’s authority was admired. Later Georgians called this age their golden age, and the poem came to stand for it.',
      'The court was open to the wider Islamic and Byzantine worlds, and educated Georgians knew Persian and Greek writings. Persian epics and romances, such as the stories of kings and lovers in Firdawsi and Nizami, provided models of long narrative poetry at a time when Georgian literature had been mostly religious. Rustaveli’s poem is a secular, courtly work, set in “India” and “Arabia” and written in Georgian verse that follows its own strict form. The golden age ended in the Mongol invasions of the 1220s, and only later copies of the poem survive, the earliest being fragments from the fourteenth century and a few folios from the sixteenth.',
    ],
    ideas: [
      { title: 'Friendship as a bond stronger than blood', text: 'The story turns on the friendship of three men from different kingdoms: Avtandil of Arabia, Tariel of India and Pridon, a ruler who joins them. Avtandil, once he has found Tariel, binds himself to help a man he has only just met, and the friends share every danger. Rustaveli presents loyalty between friends as a moral achievement that crosses borders, not just as a feeling.' },
      { title: 'Love as moral strength', text: 'In the poem love is not a game. It tests character and demands courage, restraint, patience and faithfulness. Tariel falls into wild grief when he loses his beloved Nestan-Darejan, and Avtandil sets out on a long quest in order to deserve Tinatin. The poet separates shallow desire from a love that makes a person better, and he calls for love that is sincere and loyal. Scholars link this with courtly love, a tradition known in Europe and the Islamic world, and debate which influences reached Georgia.' },
      { title: 'Generosity: what you give is yours', text: 'One of the most quoted sayings of the poem says, in brief, that what you give away is yours and what you hold back is lost (the wording varies between editions and translators). Rustaveli treats generosity as true wealth and as the proper conduct of a ruler or a hero, and the poem shows its characters, such as Tinatin, giving away wealth freely. The thought is that goods kept for oneself are lost for good, while goods given become part of who you are.' },
      { title: 'Justice and just rule', text: 'The poem imagines the ideal ruler as wise, fair and generous. At the start, King Rostevan crowns his daughter Tinatin as his heir and says that a lion’s cub is a lion, whether male or female. Many readers take this as an argument for judging a person by qualities, not sex, and as a compliment to Queen Tamar. Throughout, cruelty and tyranny are defeated and honest courage is rewarded.' },
      { title: 'Courage, loyalty and an open outlook', text: 'The heroes keep their word, defend the weak and face danger without boasting. The settings are lands beyond Georgia, and the characters are treated with respect whatever their kingdom. The poem also holds a sober view of life: fortune is fickle, grief is real, and God is addressed in faith but also in complaint. This mix of idealism and realism is a large part of its lasting appeal.' },
    ],
    principles: [
      'Keep faith with your friends, even when it costs you.',
      'Let love make you braver and more honest, not more selfish.',
      'What you give is yours; what you hoard is lost.',
      'A ruler’s task is justice and care for others.',
      'Judge people by their deeds and character, not by sex, rank or birth.',
    ],
    practice: [
      'Choose one friend this week and do something useful for them without being asked, as Avtandil does for Tariel.',
      'Give something away, such as time, money or knowledge, and notice how it feels compared with keeping it.',
      'When you admire someone, name the quality (courage, honesty, patience) you admire and ask how to practise it yourself.',
    ],
    facts: [
      'The poem has about 1,600 quatrains, though the exact count varies because later copyists added stanzas. Each quatrain has four lines of sixteen syllables, in a form known as shairi.',
      'The title means roughly “the one in the skin of a vepkhi”. In modern Georgian vepkhi means tiger, and older English translations used “panther”.',
      'In the prologue the poet calls the tale a Persian one that he put into Georgian, but no Persian original has ever been found, and most scholars treat the story as his own invention.',
      'The first printed edition appeared in 1712, edited by King Vakhtang VI of Kartli. Until the early twentieth century a copy was often part of a Georgian bride’s dowry.',
      'The first English translation, by Marjory Wardrop, was published in 1912.',
      'Rustaveli’s portrait appears on the 100 lari banknote, and Rustaveli Avenue is the main street of Tbilisi, the Georgian capital.',
    ],
    myths: [
      { myth: 'The poem is a translation of an older Persian story.', reality: 'The poet says so, but no Persian source has been found. Most scholars treat the claim as a literary convention and see the plot as an original Georgian creation set in imagined foreign lands.' },
      { myth: 'We know that Rustaveli was Queen Tamar’s treasurer and died in Jerusalem as a monk.', reality: 'These are traditions resting on late sources and on the Jerusalem portrait. They may be partly true, but they are not firmly documented, and the story of a hopeless love for the queen is a legend.' },
      { myth: 'Every quatrain in the printed poem is by Rustaveli.', reality: 'The manuscripts differ, and later copyists added stanzas. Editors have debated for generations which lines are original.' },
    ],
    works: [
      { title: 'ვეფხისტყაოსანი (Vepkhistqaosani), “The Knight in the Panther’s Skin”', note: 'His only known work: an epic poem of friendship, love and adventure, with a prologue and epilogue praising Queen Tamar.' },
      { title: 'Manuscript tradition', note: 'Fragments from the fourteenth century and folios from the sixteenth survive, while most complete copies date from the seventeenth century, so the text rests on late copies.' },
      { title: 'The 1712 edition', note: 'Prepared in Tbilisi under King Vakhtang VI, this was the first printed version.' },
      { title: 'Marjory Wardrop, The Man in the Panther’s Skin (1912)', note: 'The first English prose translation, still widely read, and a base for many later English versions.' },
      { title: 'The Jerusalem portrait and inscription', note: 'The fresco in the Monastery of the Cross is the main physical evidence tied to his name, and its interpretation is still discussed.' },
    ],
    legacy: [
      'For Georgians the poem is much more than a classic. It has been a mirror of national identity through centuries of foreign rule, taught in schools, quoted at weddings and feasts, and carried in the dowry of brides. Its ideals of loyalty, generosity and fair rule are felt to be part of what being Georgian means. The highest state prize for art and literature in Georgia carries Rustaveli’s name.',
      'Outside Georgia the poem became known through nineteenth-century partial translations and Wardrop’s English version, and it has since been translated into dozens of languages. Scholars compare it with the courtly romances of Europe and the Persian epics, and argue about its philosophical background, including Neoplatonic ideas about love. Whatever the answer, the poem remains a rare case of a medieval work whose central values, friendship across borders and giving freely, still read as a plain and serious moral message.',
    ],
  },
  {
    slug: 'rumi',
    order: 1207,
    dates: '1207 – 1273',
    place: 'Born in Balkh or Wakhsh (Central Asia); lived in Konya (now Turkey)',
    era: 'Medieval',
    tradition: 'Sufism',
    tagline: 'A scholar who became a poet of longing, and whose verses turn love for the divine into music.',
    who: [
      'Jalal al-Din Rumi was born in 1207 in the region of Balkh, in what is now Afghanistan or Tajikistan. Sources name either Balkh itself or the nearby town of Wakhsh as his birthplace. His father, Baha al-Din Walad, was a respected preacher and teacher. “Rumi” means “from Rum”, the Muslim name for Anatolia, where he spent most of his life, and his followers also call him Mevlana, “our master”.',
      'As Mongol armies spread across Central Asia, the family left, travelling for years through the Islamic world before settling in Konya around 1228. Konya was the capital of the Seljuk Sultanate of Rum. Rumi took over his father’s post as a teacher and preacher and became a trained legal scholar. Traditions say he also studied in Syria and was guided for some years by a spiritual teacher named Burhan al-Din.',
      'In November 1244 the course of his life changed when he met a wandering dervish named Shams of Tabriz. The two became inseparable, and Rumi’s students resented the attention he gave to Shams. Shams left and was brought back, and then vanished around 1247 for good. His fate is unknown: some accounts speak of murder, others of a quiet departure. Rumi’s grief and longing poured into verse. Later companions, the goldsmith Salah al-Din Zarkub and then Husam al-Din Chelebi, became his close friends, and it was Husam who urged him to compose the Masnavi, his great poem of teaching stories. Rumi died in Konya on 17 December 1273.',
    ],
    context: [
      'Rumi lived between two worlds of upheaval. The Mongol conquests destroyed great cities of Persia and Central Asia, and in 1243 the Mongols defeated the Seljuk army in Anatolia and made the sultanate a vassal state. Even so, Konya was a meeting place for Muslims, Christians and Jews, and for scholars, merchants and refugees from the east. Persian was the language of poetry and learning at the Seljuk court, which is why Rumi wrote mostly in Persian although he spoke other languages and used some Arabic, Turkish and Greek.',
      'Sufism, the mystical tradition of Islam, was well established. Sufis sought a direct experience of God through prayer, remembrance, poetry, music and the guidance of a teacher. Poets such as Sanai and Attar had already used verse for mystical teaching in Persian, and Rumi built on them. He remained a devout Muslim and a scholar of the Qur’an throughout his life, and his poetry draws constantly on its language and stories.',
    ],
    ideas: [
      { title: 'Love as the road to God', text: 'For Rumi, love (ishq) is the force that draws the soul towards its source. He does not treat it as a mere feeling but as the energy that moves all things, and he often describes the divine as the Beloved. Human love can be a first step, but its true object lies beyond any person.' },
      { title: 'Separation and return', text: 'The Masnavi opens with the song of a reed flute that was cut from its reed bed and now laments being apart. The image stands for the human soul longing for its origin. Pain of separation is not pointless, because it keeps the soul searching and leads it home.' },
      { title: 'Teaching through stories', text: 'The Masnavi is a long poem of anecdotes, fables and jokes, each followed by a lesson. In one, people in a dark room touch an elephant and each describes a different animal, depending on which part they feel. The story shows how partial human views are and how easily we take our piece for the whole.' },
      { title: 'Letting go of the ego', text: 'A story in the first book tells of a man who knocks at his beloved’s door. Asked who is there, he says “I” and is turned away, and only when he answers “you” is he let in. The lesson is that closeness to the divine needs the dissolving of the self-centred ego, not its growth.' },
      { title: 'Music, movement and remembrance', text: 'Rumi loved music, and tradition says he turned and danced when moved. His followers developed the sema, a ceremony of music and turning, in which the dancer’s whirling is a form of prayer and remembrance of God, not entertainment.' },
    ],
    principles: [
      'Let longing lead you toward what matters most.',
      'Hold your own view lightly, because you may be touching only one part of the elephant.',
      'Loosen the grip of the ego, since pride keeps the door shut.',
      'Learn from stories, humour and the everyday, not only from books.',
      'Treat sorrow as part of the journey, not as a sign that it has failed.',
    ],
    practice: [
      'When you disagree with someone, ask what part of the truth they might be seeing that you cannot.',
      'Spend ten minutes in quiet attention each day, listening to music or to silence, with no aim except to be present.',
      'Read one story of the Masnavi in a good translation and write down what it says to you before reading any commentary.',
    ],
    facts: [
      'The Masnavi has six books and roughly 25,000 couplets, according to most counts. Rumi dictated it over years and left it at the end of the sixth book when he died.',
      'His other great collection, the Divan-e Shams-e Tabrizi, is named for Shams. Rumi often ends a poem by calling himself “Shams”, as if the two had merged.',
      'A prose work, Fihi ma fihi (“In it what is in it”), records his talks to students.',
      'Husam al-Din Chelebi is said to have written down the Masnavi as Rumi spoke it.',
      'His tomb in Konya, known for its green-tiled dome, is now part of a museum and a major place of visit.',
      'The Mevlevi sema ceremony is recognised by UNESCO as part of the world’s intangible cultural heritage.',
    ],
    myths: [
      { myth: 'Rumi founded the whirling dervishes.', reality: 'The Mevlevi order took shape after his death, and his son Sultan Walad is credited with organising it. Rumi’s own place in its origins is as inspiration, not as the founder of the order as we know it.' },
      { myth: 'The popular “Rumi quotes” online are accurate translations.', reality: 'Many are loose rewordings in modern free verse based on older translations, and some are not by Rumi at all. A reliable translation, with notes, is the best guide.' },
      { myth: 'Rumi was a free-floating spiritual poet unconnected to a religion.', reality: 'He was a Muslim scholar and preacher, and his poems are full of Qur’anic imagery. His message of love and openness grew from within Islam.' },
    ],
    works: [
      { title: 'Masnavi-ye Ma’navi (Spiritual Couplets)', note: 'A six-book poem of teaching stories and reflections, begun in the late 1250s and left unfinished at his death.' },
      { title: 'Divan-e Shams-e Tabrizi', note: 'A very large collection of lyrics, mostly ghazals, many of them in praise of Shams and of divine love.' },
      { title: 'Fihi ma fihi', note: 'Recorded conversations and talks, written down by students in prose.' },
      { title: 'Majalis-e Sab‘a', note: 'Seven sermons that survive in Persian prose.' },
      { title: 'Maktubat (Letters)', note: 'Letters to rulers, officials and followers, which show a practical side to the poet.' },
    ],
    legacy: [
      'The Mevlevi order, founded after his death, spread through the Ottoman world and for centuries shaped Turkish music, poetry and calligraphy. The Masnavi was studied, copied and commented upon across the Persian-speaking world, from Anatolia to India, and some people called it the Qur’an in Persian, a phrase meant as praise for its depth.',
      'In the last century Rumi became widely known in Europe and America through translations, and he is now among the most-read poets in English. Much of this fame rests on versions that simplify him, but the attention has also led to careful new scholarship. His central picture, a human being longing to return to the source of love, still speaks to readers of many faiths and none.',
    ],
  },
  {
    slug: 'dante-alighieri',
    order: 1265,
    dates: 'c. 1265 – 1321',
    place: 'Florence, then exile in northern Italy; died in Ravenna',
    era: 'Medieval',
    tradition: 'Medieval Christian thought',
    tagline: 'The poet who walked through hell, purgatory and paradise, and gave a vernacular language the weight of Latin.',
    who: [
      'Dante Alighieri was born in Florence in 1265, probably in May or June, into a family of modest rank. In his early book, the Vita Nuova (“New Life”), he describes first meeting a girl named Beatrice when he was nine, and then seeing her again nine years later. Boccaccio later identified her as Beatrice Portinari, and most scholars accept this. She died in 1290, and her memory shaped everything he wrote afterwards. He married Gemma Donati, and they had children.',
      'Dante was not only a poet. He fought as a cavalryman for the Florentine Guelphs at the battle of Campaldino in 1289, joined a guild of physicians and apothecaries in order to take part in city politics, and served as one of Florence’s six priors for two months in 1300. When the Guelph party split into Black and White factions over the role of the pope in Florence, Dante belonged to the Whites. After the Blacks took power in 1301, he was sentenced to exile in 1302 and never saw Florence again.',
      'During his exile he lived in several northern Italian cities and was supported by patrons, and he wrote the Divine Comedy, which he probably began around 1308 and finished shortly before his death. He settled in Ravenna in his last years and died there in September 1321, reportedly of malaria after a diplomatic journey. He is buried in Ravenna, and Florence has only a cenotaph.',
    ],
    context: [
      'Dante’s Italy was a patchwork of city-states, torn by rivalry between the pope and the Holy Roman Emperor. In Florence the conflict took the form of Guelphs, who generally supported the papacy, and Ghibellines, who supported the emperor, and then of feuds inside the Guelphs themselves. Pope Boniface VIII’s attempts to extend his influence in Tuscany were central to Dante’s downfall, and the poem returns to this struggle again and again. Dante hoped that the emperor Henry VII, who came to Italy in 1310, might restore order, but Henry died in 1313.',
      'Intellectually, Dante lived in the age of the great scholastic synthesis. Thomas Aquinas, who died in 1274, had joined Christian theology with the philosophy of Aristotle, and Dante absorbed these ideas, along with Virgil, Boethius and the Latin poets. The usual language of learning was Latin, and Italian was thought fit only for songs and everyday talk. Dante’s decision to write the Comedy in the Tuscan dialect of his own people was a deliberate and bold choice.',
    ],
    ideas: [
      { title: 'A journey of the soul', text: 'The Comedy tells of a man who “midway in the journey of our life” finds himself lost in a dark wood. He is led through Hell, up the mountain of Purgatory and through the spheres of Paradise to a vision of God. The setting is Easter week of the year 1300, but the journey is also a picture of every person’s path from error towards understanding.' },
      { title: 'Justice that fits the sin', text: 'Dante’s Hell is organised by moral logic. Sinners are punished in ways that mirror their faults, a principle later called contrapasso. Lust, anger, fraud and treason are ranked, with the worst offenders at the bottom. Dante places popes, kings and even friends and enemies from Florence in Hell, which shows that he claimed the right to judge public figures by their deeds.' },
      { title: 'Love is behind both virtue and vice', text: 'In Purgatory, Virgil explains that love is the seed of every virtue and also of every sin: bent the wrong way, too weak or too strong, it leads astray. The poem’s final line speaks of the love that moves the sun and the other stars. For Dante, love is the force that orders the universe and the human heart alike.' },
      { title: 'Reason and faith, working together', text: 'Dante’s guides show his view of human knowledge. Virgil represents human reason, which can bring a person a long way, but only Beatrice, who stands for divine revelation, can lead him to the heavens. He valued philosophy highly and defended its independence, yet he saw it as incomplete without grace.' },
      { title: 'Two authorities, one world', text: 'In his Latin treatise Monarchia, Dante argued that humanity needs a universal emperor to secure peace and earthly happiness, while the pope should guide souls towards eternal life. Each authority has its own sphere, and the pope should not rule the state. The book was condemned after his death, and scholars still debate when he wrote it.' },
    ],
    principles: [
      'Look honestly at your own failings before you judge anyone else’s.',
      'Order your loves, because misdirected love is the source of most trouble.',
      'Use reason as far as it goes, and be humble about where it stops.',
      'Speak to your readers in the language they actually use.',
      'Keep your integrity even when it costs you your home.',
    ],
    practice: [
      'Take an evening to ask what you love most, and whether your daily time and energy follow that love.',
      'When you face a hard decision, write down what reason says and what your deeper values say, and compare them.',
      'Read one canto of the Inferno in a good translation with notes, and notice how each punishment reflects the sin.',
    ],
    facts: [
      'The Divine Comedy has 100 cantos in total: an opening canto and then 33 each for Inferno, Purgatorio and Paradiso. It runs to about 14,200 lines.',
      'Dante invented, or at least made famous, the verse form called terza rima, in which the middle line of each three-line stanza rhymes with the first and last lines of the next.',
      'He called the poem simply the Commedia. The word “Divine” was added later, and first appeared in the title of a Venetian edition of 1555.',
      'In the poem, Dante meets the dead from antiquity and from his own time, and imagines Boniface VIII, who was still alive in 1300, as destined for Hell.',
      'Each of the three parts ends with the word “stelle”, “stars”.',
      'In 1329 Monarchia was condemned by Church authorities, and it was later placed on the Church’s Index of prohibited books in 1554.',
    ],
    myths: [
      { myth: 'Dante wrote the Divine Comedy as a medieval vision of hellfire alone.', reality: 'Hell is only the first of three parts. Purgatory and Paradise make up two thirds of the poem, and it ends in light and love, not in punishment.' },
      { myth: 'Dante was merely a religious poet.', reality: 'He was also a politician, a philosopher and a theorist of language. Much of his work, from Monarchia to the Convivio, deals with politics, ethics and science.' },
      { myth: 'Beatrice was only a symbol.', reality: 'Most scholars think Beatrice was a real woman, probably Beatrice Portinari, though nothing certain is known about her. In the Comedy she is also a sign of divine grace, so Dante treated her as both a person and a symbol.' },
    ],
    works: [
      { title: 'La Vita Nuova (c. 1294)', note: 'A mix of poems and prose on his love for Beatrice, written in Italian.' },
      { title: 'De vulgari eloquentia', note: 'A Latin treatise, left unfinished, on the nature of language and the case for an “illustrious” literary Italian.' },
      { title: 'Convivio (c. 1304–1307)', note: 'An unfinished “banquet” of commentary on his own poems, ranging over philosophy, ethics and politics.' },
      { title: 'Monarchia', note: 'A Latin treatise on the relationship between emperor and pope, with a date that scholars debate.' },
      { title: 'La Commedia (Divine Comedy)', note: 'His masterpiece in three parts, written in exile and completed shortly before his death.' },
    ],
    legacy: [
      'The Comedy helped establish Tuscan as the basis of the Italian literary language, and Dante is often called the father of the language. His work raised the vernacular to a rank that rivalled Latin, and writers such as Petrarch and Boccaccio, although they differed from him, followed in a landscape that he had changed.',
      'Over the centuries the poem has inspired painters, composers and poets, from Botticelli and Rodin to T. S. Eliot and Borges. It is read today both as a monument of medieval Christian thought and as a human drama of exile, desire and hope. Few works give so full a picture of how a medieval person saw the world and the soul.',
    ],
  },
  {
    slug: 'petrarch',
    order: 1304,
    dates: '1304 – 1374',
    place: 'Born in Arezzo; lived in Avignon, Vaucluse, Italian cities and Arquà',
    era: 'Medieval',
    tradition: 'Renaissance humanism',
    tagline: 'The scholar-poet who went looking for the ancient world, and for himself, in old books.',
    who: [
      'Francesco Petrarca, known in English as Petrarch, was born in Arezzo in 1304. His father, Ser Petracco, was a Florentine notary who had been exiled from Florence, like Dante, and the family later settled near Avignon in southern France, where the popes then resided. Petrarch studied law at Montpellier and Bologna to please his father, but he preferred Cicero and Virgil. After his father died he returned to Avignon, took minor church orders, and found work and patrons among the clergy and powerful families.',
      'His life divides into a French period and an Italian one. He lived for years at Vaucluse, a quiet valley near Avignon, where he read and wrote. In 1341 he was crowned poet laureate on the Capitoline Hill in Rome, an honour that revived an ancient custom. He then travelled widely, serving rulers such as the Visconti of Milan, and spent his last years in Padua and in Arquà, in the Euganean Hills, where he died in July 1374. Legends say he was found at his desk among his books. The story is told often but it is a later tradition.',
      'Petrarch’s heart, he said, belonged to Laura. According to his own notes he first saw her on 6 April 1327, in a church in Avignon, and she died in the plague of 1348. Who Laura really was is unknown, and scholars debate whether she was a specific person at all. Their contact, if any, was slight, and he turned the experience of unfulfilled desire into the poems of his Italian songbook.',
    ],
    context: [
      'Petrarch lived through the Avignon papacy (1309–1377), when the popes ruled from southern France instead of Rome, which he saw as a scandal. He lived through the Black Death of 1348, which killed many of his friends, and through constant war and political fragmentation in Italy. Rome, the old centre of the Roman world, lay in decay, and Petrarch’s longing for it was both political and cultural.',
      'University learning at the time was dominated by scholasticism, the method of logical analysis of Aristotle and the Church Fathers. Petrarch had little patience for it. He thought its dry technical debates neglected what matters most, which is how to live well. He turned instead to the Latin classics, hunting for forgotten manuscripts in monasteries and cathedral libraries. In 1345 he found letters of Cicero to his friend Atticus in the cathedral library at Verona, a discovery that gave a more personal view of the great Roman.',
    ],
    ideas: [
      { title: 'Back to the sources', text: 'Petrarch believed that wisdom lay in the great writers of antiquity, and that they should be read directly, in good texts, not through layers of medieval commentary. He collected manuscripts, compared them, and even wrote letters addressed to Cicero, Virgil and Homer. This habit of recovering and critiquing original texts became the basis of Renaissance scholarship.' },
      { title: 'Philosophy for living', text: 'He preferred moral philosophy, which asks how to be good and calm, to abstract logic. In works such as On His Own Ignorance and That of Many Others he argued that knowing what virtue is matters less than loving it and practising it. Learning, for him, must change character or it is worth little.' },
      { title: 'The divided self', text: 'In the Secretum, a Latin dialogue between “Francesco” and St Augustine, Petrarch lays bare his own struggles with ambition, love of fame and desire. Augustine urges him towards a plain Christian life, and Francesco admits the truth of the charge but cannot yet change. The book is among the first deep self-examinations of the Renaissance, and it does not settle the conflict.' },
      { title: 'Solitude and leisure', text: 'In On the Solitary Life he praised the value of quiet retreat for thought and study, free from the demands of the crowd. He did not hate people, since he had many friends and wrote hundreds of letters, but he believed that time alone with books and nature was needed for a thoughtful life.' },
      { title: 'A past to be recovered', text: 'Petrarch looked on antiquity as a time of light and on the centuries since Rome’s fall as darkness. This was an exaggeration, and modern historians do not accept the label “Dark Ages”. But it gave Europeans a new way of thinking about history, as a story of decline and possible rebirth, and it shaped the idea of a Renaissance.' },
    ],
    principles: [
      'Go to the original sources and read them for yourself.',
      'Learning matters when it makes you a better person.',
      'Be honest with yourself about your own contradictions.',
      'Guard time for solitude and thought.',
      'Honour the past, but use it to improve the present.',
    ],
    practice: [
      'Pick one book that everyone quotes and read the original text, not a summary.',
      'Keep a short private journal in which you note where your actions and your values do not match.',
      'Set aside an hour each week with no phone or news, and use it to think or to read slowly.',
    ],
    facts: [
      'Petrarch’s Italian collection, the Canzoniere (“Songbook”), has 366 poems, mostly sonnets, and he revised it for decades. Its formal title is Rerum vulgarium fragmenta, “fragments of vernacular matters”.',
      'The “Petrarchan sonnet” is named after him because his sonnets shaped the form that later poets across Europe copied.',
      'He is known for a letter describing a climb of Mont Ventoux in 1336, with a moment at the summit when he opened Augustine’s Confessions. Many scholars think the letter, written years later, is partly literary invention.',
      'He was crowned poet laureate in Rome on 8 April 1341, the second poet since antiquity to receive that honour, after Albertino Mussato.',
      'In 1345 he found letters of Cicero at Verona that were previously unknown to him, which became a landmark of humanist scholarship.',
      'He wrote a “Letter to Posterity”, an autobiography addressed to future readers.',
    ],
    myths: [
      { myth: 'Petrarch invented the Renaissance single-handedly.', reality: 'Earlier Italian scholars, such as Lovato Lovati and Albertino Mussato, were already studying the classics. Petrarch gave the movement fame and direction, and scholars now treat him as one leader among several.' },
      { myth: 'Petrarch climbed Mont Ventoux simply to enjoy the view, like a modern hiker.', reality: 'The famous letter was written years after the date given, and it is deeply moral and literary in character. Some scholars doubt the climb happened as described.' },
      { myth: 'Petrarch rejected religion for human reason.', reality: 'He remained a committed Christian, and the Secretum and many letters are deeply religious. He argued that earthly achievement and a sincere faith could belong together.' },
    ],
    works: [
      { title: 'Canzoniere (Rerum vulgarium fragmenta)', note: 'His Italian songbook of 366 poems, centred on Laura and on the pain of desire.' },
      { title: 'Secretum', note: 'A Latin dialogue with Augustine about his inner conflicts, begun in the 1340s.' },
      { title: 'Africa and De viris illustribus', note: 'An unfinished Latin epic on Scipio Africanus, and a series of lives of famous Romans.' },
      { title: 'Epistolae familiares and Seniles', note: 'Collections of letters, which Petrarch prepared for publication and which show his friendships and ideas.' },
      { title: 'Trionfi, De vita solitaria, De remediis utriusque fortunae', note: 'An Italian poem of allegorical triumphs, a work in praise of solitude, and a dialogue on handling good and bad fortune.' },
    ],
    legacy: [
      'Petrarch’s example of searching for forgotten texts, editing them with care and writing in an elegant Latin shaped the humanist movement. Later scholars such as Boccaccio, Salutati and Bruni took up his interests, and the study of the humanities grew into a core part of European education.',
      'His Italian poetry became the model for European love lyric. For two centuries poets across Italy, France, Spain and England imitated his sonnets, with their conceits of fire and ice and the pain of an unreachable beloved, and Shakespeare’s sonnets answer to this tradition. Petrarch’s own restless inner life, caught between love of the world and love of God, also makes him one of the first modern-sounding voices.',
    ],
  },
  {
    slug: 'kabir',
    order: 1398,
    dates: 'Traditionally c. 1398 – 1518; modern scholars propose earlier or shorter dates',
    place: 'Varanasi (Banaras), northern India',
    era: 'Medieval',
    tradition: 'Bhakti and Sant tradition',
    tagline: 'A weaver-poet who mocked empty ritual and sang of a God beyond Hindu and Muslim labels.',
    who: [
      'Kabir was a poet and spiritual teacher who lived in or near Varanasi, a city on the Ganges that was a centre of Hindu learning and pilgrimage. His dates are uncertain. Tradition places his birth in 1398 and death in 1518, which would give him an implausible 120 years. Modern scholars have proposed shorter spans, either about 1398–1448 or about 1440–1518, and they stress that no firm records exist from his lifetime.',
      'Tradition says he was raised in a Muslim weaver family, and the weavers of Varanasi, called julaha, ranked low in the social order. A popular legend says he was found as an infant by the pool of Lahartara and adopted by a weaver couple, Niru and Nima. Another says he took the Vaishnava teacher Ramananda as his guru, receiving the name of Ram. Scholars debate such stories, since they come from later devotional accounts, and some scholars doubt that Kabir had a human guru in any formal sense.',
      'Legend also says that he died in Maghar, a town outside the sacred city, since a belief held that dying in Varanasi brought liberation, and he wished to show that God’s grace does not depend on place. It adds that at his death Hindus and Muslims quarrelled over his body, and that when they lifted the cloth they found only flowers. This is a story told by his followers, not history. What is certain is the verse that bears his name, and that it was handed on orally for generations.',
    ],
    context: [
      'Kabir’s north India was ruled by Muslim sultans in Delhi, and it was a place of daily contact between Hindus and Muslims. Hindu devotional movements known as bhakti taught that anyone, whatever their caste, could love and reach God. Sufi mystics spread a similar message of love and inward devotion, and yogic groups such as the Naths stressed bodily discipline and direct experience of the divine. Kabir’s verses draw on all these streams, and the speaker in his poems often seems to stand outside each of them.',
      'He is counted among the Sants, “saints” or “truth-finders”, a loose tradition of poets, many from artisan and low-caste backgrounds, who spoke of a God without form and without a temple. Others in this stream include Ravidas and Namdev, and Guru Nanak, founder of Sikhism, belonged to the same age and spirit. These poets composed in everyday spoken languages, not Sanskrit or Persian, so that ordinary people could hear and remember their songs.',
    ],
    ideas: [
      { title: 'One God beyond labels', text: 'Kabir calls the divine by many names, including Ram and Rahim, and says that God is not found in a temple or a mosque but in the heart. He sees the divine as without form and shared by all, so quarrels between Hindu and Muslim over names are, to him, a kind of blindness.' },
      { title: 'Ritual without love is empty', text: 'He mocked pilgrimages, rosaries, idol worship, ritual baths, fasting and the shows of priests and mullahs when they replaced inward devotion. A famous couplet, widely attributed to him, says that people read books until they die and none becomes wise, but whoever learns the “two and a half letters” of love is a true scholar. Some verses of this type may have been added later, as scholars point out.' },
      { title: 'Worth is not birth', text: 'Kabir was an artisan, and he refused to honour caste. A person’s worth lies in conduct and devotion, he says, not in birth, and he often mocks Brahmin pride. His voice is that of a working man speaking to working people, with images from the loom and the marketplace.' },
      { title: 'The guru and the inner word', text: 'He gives great weight to the teacher, or satguru, who points to the truth, and to the “name” or inner word that one repeats and hears within. Religion in his verse is experience: a direct inner awareness, not belief learned from outside.' },
      { title: 'Paradox and plain speech', text: 'Many poems are riddles, “upside-down sayings” in which the world is turned on its head: a fish is thirsty while it lives in water. The shock is meant to break the habits of thought. Other verses are blunt and humorous, taking the form of short couplets, and the mixture of paradox and plain talk has kept them alive.' },
    ],
    principles: [
      'Look for the divine within, not only in buildings and rituals.',
      'Judge people by what they do and how they love, not by birth.',
      'Do not let a name or label divide you from others.',
      'Take learning lightly if it does not make you kinder.',
      'Speak plainly, and let humour puncture pride.',
    ],
    practice: [
      'Notice one habit you perform from routine, and ask whether it still carries any living meaning for you.',
      'Next time a debate turns on labels, ask what each side actually cares about.',
      'Read a few of his couplets slowly, one a day, and write what each asks of you.',
    ],
    facts: [
      'Kabir’s verse takes several forms: the doha (couplet), the sakhi (“witness”), the pad (song) and the ramaini. Many are in a mixed spoken language rather than a single dialect.',
      'His verses were collected by others. Major collections include the Bijak, treasured by the Kabir Panth, the Kabir Granthavali, compiled in the Dadu Panth tradition of Rajasthan and published in 1928, and the verses included in the Sikh scripture, the Adi Granth, compiled in 1604.',
      'Because the different collections preserve different versions, scholars such as Charlotte Vaudeville have compared them closely to separate earlier layers from later additions.',
      'The Kabir Panth, a community that follows his teaching, formed after his death, and it has its own tradition of texts.',
      'Rabindranath Tagore’s English translation, Songs of Kabir, published in 1915, introduced him to many readers in the West.',
      'He is said to have worked as a weaver all his life, and his poems use the loom as a symbol.',
    ],
    myths: [
      { myth: 'Kabir lived for 120 years, from 1398 to 1518.', reality: 'This is the traditional span, but modern scholars regard it as doubtful and suggest shorter lives, either earlier (about 1398–1448) or later (about 1440–1518). No reliable records fix the dates.' },
      { myth: 'Every verse that carries Kabir’s name was composed by him.', reality: 'His verses were sung and passed on orally for generations before being written down by compilers in different communities. Whole songs were probably added by others, so scholars treat each collection with care.' },
      { myth: 'Kabir was simply a Hindu saint, or simply a Muslim one.', reality: 'Both communities claim him, and his verses criticise both. He drew on Hindu, Sufi and yogic ideas and refused to be placed in any single camp.' },
    ],
    works: [
      { title: 'Bijak', note: 'A collection preserved by the Kabir Panth, rich in riddle poems, and treated as a main authority by his followers.' },
      { title: 'Kabir Granthavali', note: 'A collection compiled in the Dadu Panth tradition in Rajasthan, edited and published in 1928 by Shyamsundar Das.' },
      { title: 'Verses in the Adi Granth (Guru Granth Sahib)', note: 'A substantial group of his hymns and couplets, in the Sikh scripture compiled in 1604, where they have been preserved in a fixed form.' },
      { title: 'Kabir Panchvani and other compilations', note: 'Further anthologies, showing that no single collection is complete, and that his poetry circulated widely in the oral tradition.' },
      { title: 'Rabindranath Tagore, Songs of Kabir (1915)', note: 'The best-known early English translation, with an introduction by Evelyn Underhill, based on a Bengali collection.' },
    ],
    legacy: [
      'Kabir’s influence is wide. His verses are sung in villages and concert halls across India, quoted in speeches and proverbs, and studied in schools. The Kabir Panth carries his teaching as a distinct community, and his hymns in the Guru Granth Sahib have shaped Sikh worship. He is often seen as a voice of unity between Hindus and Muslims, though this is also something that later readers have emphasised.',
      'Modern readers claim him in different ways: as a mystic, a social critic, a poet of the oppressed castes and a forerunner of religious tolerance. These readings do not always agree, and the scholarly effort to separate his own words from later additions continues. What survives in all versions is a recognisable voice: direct, ironic, and sure that real devotion lies in an honest and loving heart.',
    ],
  },
]
