import type { Profile } from './types'

export const MORE_11: Profile[] = [
  {
    slug: 'thomas-carlyle',
    order: 1795,
    dates: '1795 – 1881',
    place: 'Ecclefechan, Edinburgh, Craigenputtock and Chelsea, London',
    era: '19th Century',
    tradition: 'Victorian thought',
    tagline: 'A Scottish prophet of work, duty and heroes who shaped Victorian conscience, and whose later politics and racism darkened his name.',
    who: [
      'Thomas Carlyle was born in 1795 in Ecclefechan, a village in the south of Scotland, the son of a stonemason who became a farmer. His parents were strict Calvinists and hoped he would become a minister. He studied at the University of Edinburgh, but he lost his faith, gave up the idea of the church, and worked as a schoolteacher and tutor while he taught himself German and read widely in the new literature of Germany, above all Goethe, Schiller and Kant.',
      'In 1826 he married Jane Welsh, a gifted and witty woman from a family of some standing, and the couple lived for six years on her family’s remote farm at Craigenputtock, where he wrote essays that introduced German thought to Britain. In 1834 they moved to Cheyne Row in Chelsea, London, which remained his home for the rest of his life. The marriage was close and also often painful, and the question of how well he treated Jane has been argued over ever since her death in 1866. The early biography by James Anthony Froude is the main source, and it was itself controversial.',
      'In the 1830s and 1840s Carlyle became the most famous moral voice in Britain, through Sartor Resartus, The French Revolution and On Heroes and Hero-Worship. From the later 1840s his writing grew angrier. He turned against democracy and philanthropy, admired strong rulers, and in 1849 published an essay on race and emancipation that is now widely condemned as racist. He died in 1881, aged 85, still honoured as a great man of letters, though by then many of his old admirers had left him.',
    ],
    context: [
      'Carlyle came of age in the years after the Napoleonic Wars, when Britain was industrialising fast. Cities were growing, factories were multiplying, and the old social order, in which each person knew a place, was giving way to wage labour and markets. Carlyle called the problem “the condition of England question”, and he was among the first to say that the cash payment had become, in his phrase, the only tie between people. He was alarmed by what he saw as a spiritual emptiness in a society that measured everything by profit.',
      'He also lived in the shadow of the French Revolution, the central event of his century for him. Faith in traditional religion was weakening under the pressure of science and criticism of the Bible, and many thoughtful people felt that old beliefs had gone without anything to replace them. Carlyle’s answer drew on German Romanticism and idealism: look for the divine in nature, in work and in great persons, not in dogma. This made him a leading voice of what is now called Victorian thought, a figure whom Dickens, Ruskin, Emerson, George Eliot and Mill all read closely, whether they agreed with him or not.',
    ],
    ideas: [
      { title: 'The clothes philosophy', text: 'Sartor Resartus (“the tailor re-tailored”) pretends to present the life and opinions of a German professor, Diogenes Teufelsdröckh, who holds that all outward things, institutions, customs and even the body, are clothes that cover a deeper spiritual reality. The book is also a disguised account of Carlyle’s own spiritual crisis. It moves from the “Everlasting No”, a despairing denial, through a stage of indifference, to the “Everlasting Yea”, an acceptance of life through action and duty.' },
      { title: 'Heroes and history', text: 'In lectures given in 1840, Carlyle argued that history is shaped above all by exceptional individuals: prophets, poets, priests, men of letters and kings. He treated them as people who see further than their neighbours and give others something to believe in. Critics have objected that this view ignores ordinary people and social forces, and the idea is often called the “great man” theory of history.' },
      { title: 'The gospel of work', text: 'For Carlyle, work is the moral centre of life: a person finds meaning not by seeking happiness but by doing the nearest task honestly and well. He urged readers to stop brooding over their own feelings and to act. Much Victorian talk of duty, effort and earnestness echoes him.' },
      { title: 'Against the cash nexus', text: 'In Chartism (1839) and Past and Present (1843) he attacked a society that, in his view, had reduced human relations to payment and left workers and the poor to fend for themselves. He claimed that those who held wealth and power owed leadership and care to those below them. His criticism of laissez-faire economics appealed to reformers, though his remedies were often paternalist and authoritarian rather than democratic.' },
      { title: 'Wonder at the world', text: 'Carlyle thought that familiarity had made people blind to the strangeness of existence. Sartor Resartus describes what he calls natural supernaturalism: the idea that the ordinary world is itself miraculous, and that nothing needs to be added to nature to find the divine in it.' },
    ],
    principles: [
      'Do the work that lies nearest you, and do it with all your strength.',
      'Look for meaning in duty and action, not in the pursuit of happiness.',
      'Stay amazed by the ordinary world.',
      'Ask what a society owes to those who have the least, and do not accept that money is the only bond between people.',
      'Examine admiration with care: a leader who deserves loyalty must also be answerable for what he does.',
    ],
    practice: [
      'When you are stuck in doubt or gloom, pick one concrete task and finish it before deciding what life means.',
      'Choose a figure you admire and write down both what they achieved and what harm their admirers or they themselves did.',
      'Look at something familiar, such as a road, a loaf of bread or a face, as if seeing it for the first time.',
    ],
    facts: [
      'The first volume of The French Revolution was nearly lost: in 1835 the manuscript, lent to John Stuart Mill, was accidentally burned by a maid, and Carlyle rewrote it from memory and scattered notes.',
      'Sartor Resartus appeared in instalments in Fraser’s Magazine in 1833–34. It was first published as a book in Boston in 1836, with a preface by Emerson, before it appeared in book form in Britain in 1838.',
      'Carlyle’s house at 5 Cheyne Row in Chelsea is now a museum run by the National Trust.',
      'He coined or popularised phrases such as “the cash nexus”, “captains of industry” and “the condition of England question”.',
      'In 1865 he was elected Rector of the University of Edinburgh, and in 1874 he accepted the Prussian order Pour le Mérite from Bismarck while declining a baronetcy offered by Disraeli.',
      'In 1865–66 he led the committee defending Edward Eyre, the governor of Jamaica, after Eyre’s violent suppression of the Morant Bay rebellion, in which hundreds were killed. The opposing committee included Mill, Darwin and Huxley.',
    ],
    myths: [
      { myth: 'Carlyle invented “the dismal science” as a general sneer at economics.', reality: 'He introduced the phrase in his 1849 “Occasional Discourse on the Negro Question”, where he used it to attack political economists who, in his view, were too ready to leave labour to the market. In the essay it is tied to his argument against the results of emancipation in the West Indies, and the phrase is not a neutral joke.' },
      { myth: 'Carlyle’s “Negro Question” essay was a harmless piece of devil’s-advocate satire.', reality: 'It was published in Fraser’s Magazine in December 1849 and reprinted as a pamphlet in 1853 with a racial slur in the title. In it Carlyle spoke contemptuously of Black people and argued that formerly enslaved people in the West Indies were idle and should be made to work, if necessary by force, in conditions close to the servitude that had just been abolished. Mill answered it at once, and the essay is now widely condemned as racist. Carlyle later defended these views as his own.' },
      { myth: 'Carlyle was a straightforward conservative.', reality: 'He admired Cromwell and Frederick the Great and distrusted democracy, but he also condemned the cruelty of industrial capitalism, and Engels, Ruskin and later socialists drew on his critique. He is better described as a moralist who did not fit any party.' },
    ],
    works: [
      { title: 'Sartor Resartus (1833–34)', note: 'His strange, comic, spiritual autobiography in the guise of a book about a German professor.' },
      { title: 'The French Revolution: A History (1837)', note: 'A vivid, dramatic account that made his name and later inspired Dickens’s A Tale of Two Cities.' },
      { title: 'On Heroes, Hero-Worship, and the Heroic in History (1841)', note: 'Six lectures on the hero as divinity, prophet, poet, priest, man of letters and king.' },
      { title: 'Chartism (1839) and Past and Present (1843)', note: 'His diagnosis of industrial England, contrasting a medieval monastery with modern greed.' },
      { title: 'Occasional Discourse on the Negro Question (1849)', note: 'His essay on race and emancipation, given here because it is part of the historical record of his views.' },
    ],
    legacy: [
      'In the middle of the nineteenth century Carlyle was one of the most widely read writers in the English-speaking world. Emerson was his friend and correspondent, Dickens and Ruskin acknowledged debts to him, and his demand that society recognise duties to the poor helped shape the Victorian sense of social conscience. His prose, with its capital letters, sudden exclamations and invented words, changed what English writing could sound like.',
      'His reputation declined sharply in the twentieth century. His praise of strong leaders, his contempt for democracy and his racism made him an uncomfortable ancestor, and his work was later claimed by authoritarian movements, though historians disagree about how far he can be held responsible for that. Today he is read as a powerful critic of industrial society and a writer of great originality, and also as a warning of how moral anger can turn to contempt for the people it claims to defend.',
    ],
  },
  {
    slug: 'auguste-comte',
    order: 1798,
    dates: '1798 – 1857',
    place: 'Montpellier and Paris, France',
    era: '19th Century',
    tradition: 'Positivism',
    tagline: 'The founder of positivism, who named sociology, argued that knowledge passes through three stages, and then tried to found a religion of humanity.',
    who: [
      'Auguste Comte was born in 1798 in Montpellier, in southern France, into a Catholic and royalist family. A gifted mathematician, he entered the École Polytechnique in Paris, a school known for its republican spirit, but it was closed for reorganisation in 1816 and he never returned. In 1817 he became the secretary and collaborator of the social thinker Henri de Saint-Simon, and he worked with him until they broke apart in 1824 over questions of credit and ideas.',
      'In 1825 he married Caroline Massin, and in 1826 he began a private course of lectures on his philosophy. He suffered a serious mental collapse that year and was placed in a clinic under the care of the psychiatrist Jean-Étienne Dominique Esquirol. He left before he was cured, attempted suicide in 1827 by jumping into the Seine, and then recovered at home, returning to work in 1828. He later spoke of this episode as a crisis he had overcome. The marriage was unhappy and the couple eventually separated.',
      'Comte never secured a permanent university chair. He earned his living as a private tutor and as an examiner at the Polytechnique, and in later years depended on gifts from friends and followers. He published the six volumes of his Course of Positive Philosophy between 1830 and 1842, and in 1844 he fell in love with Clotilde de Vaux, a writer whose husband had left her. Their relationship was never consummated, and she died in 1846. Her memory, in his words, turned his thought toward a religion of love, and he spent his last years building it. He died of stomach cancer in Paris in 1857.',
    ],
    context: [
      'Comte lived in a France that had been through revolution, terror, empire and restoration within a single generation. Many thinkers believed that the old order of throne and altar could not be rebuilt, yet the revolutionary attempts to replace it had led to disorder. Comte wanted a new social order that would be both stable and progressive, grounded not in tradition or in metaphysical claims about rights but in knowledge that everyone could test.',
      'The natural sciences supplied his model. Astronomy, physics, chemistry and biology had each made rapid progress by dropping speculation and sticking to observed regularities, and Comte asked why the study of society should not do the same. This was the origin of positivism: the view that real knowledge consists of facts and the laws that connect them, established by observation and reasoning, and that questions about ultimate causes or essences lie beyond what we can know.',
    ],
    ideas: [
      { title: 'The law of three stages', text: 'Comte claimed that human thought, and each science within it, passes through three stages. In the theological stage events are explained by gods and spirits, in the metaphysical stage by abstract forces and essences, and in the positive stage by observable laws. He thought society advances along the same path, and that the positive stage would end the period of intellectual conflict.' },
      { title: 'A hierarchy of the sciences', text: 'He arranged the sciences in order from the simplest and most general to the most complex: mathematics, astronomy, physics, chemistry, biology and, last, the study of society. Each rests on the one before it, and each became positive in turn. The crown of the series was a new science of society, which he first called social physics.' },
      { title: 'Sociology', text: 'Comte introduced the word sociology in the late 1830s for the scientific study of society. He divided it into social statics, the study of what holds a society together, and social dynamics, the study of how it changes. Later sociologists, including Durkheim, treated him as a founder of the discipline, even where they rejected his system.' },
      { title: 'Living for others', text: 'Comte held that people are naturally social, and that morality means putting others before the self. He used the phrase “live for others” and is often credited with coining the word altruism. For him, moral progress was the real aim of science, not an extra.' },
      { title: 'The Religion of Humanity', text: 'In his later System of Positive Polity (1851–54) he proposed a secular religion, with Humanity as its object of devotion, a calendar of great figures in place of saints, public rituals, and a priesthood of positivists. He believed that society needs shared feeling as well as shared knowledge. Many admirers, including John Stuart Mill, found this late system strange, and Mill separated the “good Comte” of the Course from the later one.' },
    ],
    principles: [
      'Base beliefs on what can be observed and tested.',
      'Notice how much of your thinking still rests on habit or inherited stories.',
      'Treat society as something that can be studied, not only argued about.',
      'Put the good of others at the centre of moral life.',
      'Remember that knowledge alone does not hold a society together: people also need shared feeling and ritual.',
    ],
    practice: [
      'When you hold a strong opinion, ask whether it rests on something anyone could check, and what evidence would change it.',
      'Look at a social problem, such as traffic or loneliness, as a pattern with causes and ask what data exists.',
      'Mark a moment of gratitude each week for the people, living and dead, whose work you depend on.',
    ],
    facts: [
      'In 1835 Comte wrote that humans could never learn the chemical composition of the stars. Spectroscopy, developed in the 1850s and 1860s, proved him wrong.',
      'The word altruism is often credited to Comte, who built his ethics on the phrase “vivre pour autrui” (live for others).',
      'His positivist calendar had thirteen months, each named after a figure such as Moses, Aristotle, Dante or Shakespeare.',
      'The Brazilian national motto “Ordem e Progresso” (Order and Progress) derives from a Comtean slogan, and positivist officers had a part in the founding of the Brazilian republic in 1889.',
      'Harriet Martineau translated and condensed his Course into English in 1853, and Comte approved of her version so much that it was translated back into French.',
      'His former apartment at 10 rue Monsieur-le-Prince in Paris is now a museum, the Maison d’Auguste Comte.',
    ],
    myths: [
      { myth: 'Positivism means that only physical facts matter.', reality: 'Comte’s positivism was also a theory of society and of ethics, and in his later work it became a religion with its own rituals. The narrower positivism of the twentieth century, such as logical positivism, is a different movement that only shares part of the name.' },
      { myth: 'Comte was a cold rationalist with no feeling.', reality: 'His later writing puts love at the centre of his system, and his devotion to Clotilde de Vaux after her death shaped it. Critics thought he had gone too far in that direction.' },
    ],
    works: [
      { title: 'Course of Positive Philosophy (1830–1842)', note: 'His six-volume masterpiece, setting out the three stages and the sciences, and naming sociology.' },
      { title: 'Discourse on the Positive Spirit (1844)', note: 'A short, readable summary of his method.' },
      { title: 'System of Positive Polity (1851–1854)', note: 'His four-volume account of society and the Religion of Humanity.' },
      { title: 'Catechism of Positive Religion (1852)', note: 'A short dialogue-form summary of his religion.' },
      { title: 'J. S. Mill, Auguste Comte and Positivism (1865)', note: 'A sympathetic and critical contemporary assessment.' },
    ],
    legacy: [
      'Comte’s greatest lasting influence is the idea that society can be studied scientifically. Sociology as an academic subject grew from his challenge, through Émile Durkheim and Herbert Spencer, and his stress on observation and evidence helped shape the social sciences generally. In Britain and Latin America, positivist groups and churches carried his ideas into politics and education, especially in Brazil.',
      'His own system did not last. Few accepted the Religion of Humanity, his picture of a society governed by a scientific priesthood was seen by Mill and others as a threat to liberty, and his confident claim about what could never be known was disproved within a few decades. Yet the question he raised, whether a society without traditional faith can find something to hold it together, is still a live one.',
    ],
  },
  {
    slug: 'giacomo-leopardi',
    order: 1798,
    dates: '1798 – 1837',
    place: 'Recanati, then Rome, Milan, Bologna, Florence, Pisa and Naples, Italy',
    era: '19th Century',
    tradition: 'Romantic pessimism',
    tagline: 'A frail young scholar from a small Italian town who wrote some of the most beautiful poetry of his century about the sorrow of being alive.',
    who: [
      'Giacomo Leopardi was born in 1798 in Recanati, a small hill town in the Marche, then part of the Papal States. His father, Count Monaldo Leopardi, was a conservative nobleman with a large library, and his mother, Adelaide Antici, managed the family’s finances strictly. In the library the boy taught himself Greek, Latin, Hebrew and several modern languages, and he later spoke of seven years of “mad and desperate study” between about 1809 and 1816. As a teenager he produced scholarly works, and he composed Greek texts that he presented as ancient ones and that were reportedly accepted by some learned readers.',
      'The study damaged his health. He developed a deformed spine, thought today to be the result of a condition such as Pott’s disease, along with weak eyes and constant illness. His height was small, and he felt shut away from love and ordinary life. Recanati, which he called a “savage village”, seemed to him a prison. He tried to leave in 1819, but his father stopped him, and he did not manage to go until 1822, when he visited Rome and found its learned society a disappointment. He lived in several cities in northern and central Italy, earning a little by editing and writing.',
      'In Florence he knew the circle of writers around the review Antologia and became close to Antonio Ranieri, a young exile from Naples. He also fell, without return, for Fanny Targioni Tozzetti, who inspired the poems of the so-called Aspasia cycle. In 1833 he moved to Naples with Ranieri, hoping for a kinder climate. He wrote his last great poems near Vesuvius and died in Naples on 14 June 1837, a fortnight before his thirty-ninth birthday, during a cholera epidemic, probably of heart failure or pulmonary oedema.',
    ],
    context: [
      'Leopardi was born in an Italy of separate states, partly under foreign rule and partly under the Church. The Napoleonic wars had swept through, and after 1815 the old rulers returned. Many writers hoped for national unity and freedom, and his early patriotic poems, such as the ode to Italy, spoke to that hope. By temperament, though, he was drawn less to politics than to the question of human happiness.',
      'His thinking developed within the clash between the Enlightenment and Romanticism. From the Enlightenment he took a cool, rational view of the natural world, with no providence in it. From Romanticism he took the cult of feeling, imagination and the ancient past. He did not join the Catholic revival or the optimistic faith in progress of his time, and he turned his scepticism on both, which left him a solitary figure, admired by only a few contemporaries.',
    ],
    ideas: [
      { title: 'The Zibaldone', text: 'From 1817 to 1832 Leopardi filled thousands of pages, about 4,500 in the manuscript, with notes on language, poetry, psychology, history, religion and nature. He did not publish them, and they appeared only between 1898 and 1900 as the Zibaldone, a word meaning a hodgepodge. It is now regarded as one of the great intellectual journals of the nineteenth century.' },
      { title: 'The infinite and the limit', text: 'In “L’infinito”, a poem of fifteen lines written in 1819, the poet sits on a hill where a hedge blocks the far horizon, and his imagination leaps to endless space and silence, until he is happy to be lost in it. The poem shows his belief that the imagination, helped by a limit, can reach for something that reality never provides.' },
      { title: 'Pleasure is always out of reach', text: 'Leopardi argued that human beings want a boundless pleasure, and that every real pleasure is limited and therefore disappoints. Happiness exists mainly as hope and memory, as in the poem “Il sabato del villaggio”, which prefers the eve of the holiday to the holiday itself. Unhappiness, he wrote, is built into the nature of desire.' },
      { title: 'From a kind nature to a hostile one', text: 'His pessimism changed over time. At first he blamed civilisation for ruining the happiness of ancient people, who lived close to nature. Later he came to see nature itself as indifferent or cruel, a mother who makes her children suffer, as in the dialogue between Nature and an Icelander in the Operette morali, a book of twenty-four dialogues and short essays that he wrote mainly in the 1820s.' },
      { title: 'Solidarity against suffering', text: 'In his last poem, “La ginestra” (The Broom), he rejects the comfortable faith in progress and also despair. Faced with the volcano, symbol of a nature that does not care, people should drop their pride and unite, with honesty and kindness, as companions in a common misfortune.' },
    ],
    principles: [
      'Face the facts of life honestly, even when they are painful.',
      'Do not rely on comforting illusions, and also do not let sorrow make you cruel.',
      'Treat your fellow humans as companions in a shared difficulty.',
      'Value imagination, which can make life larger without denying its limits.',
      'Give beauty and knowledge their due, even in poor health and bad luck.',
    ],
    practice: [
      'When you are disappointed after getting what you wanted, notice how much of the pleasure was in the wanting, and let that teach you to enjoy anticipation and memory too.',
      'Keep a notebook where you set down thoughts without any plan to publish them, as Leopardi did with the Zibaldone.',
      'When life feels hard, look for others in the same position and do something small for them.',
    ],
    facts: [
      'The Zibaldone was published from 1898 to 1900, and the name by which it is now known was fixed in the twentieth century.',
      'Leopardi’s first edition of Canti appeared in Florence in 1831, an expanded edition in Naples in 1835, and the definitive edition was prepared after his death by Ranieri and published in 1845.',
      'The German scholar Barthold Niebuhr, who met him in Rome, thought highly of his philological work and tried to help him find a position.',
      'Schopenhauer, in the second volume of The World as Will and Representation (1844), praised Leopardi for treating the misery of existence more thoroughly than anyone before. The two men had arrived at their views independently.',
      'Nietzsche admired Leopardi as a stylist and as a rare scholar who was also a poet.',
      'He died, according to Ranieri’s account, soon after eating sweets, which Leopardi was fond of, though the cause of death was probably heart failure.',
    ],
    myths: [
      { myth: 'Leopardi’s pessimism was only the result of his illness and bad luck.', reality: 'His personal misery was real, but he insisted that his view of life was a philosophical position, and he rejected the idea that it could be explained away as a symptom. Modern readers take his reasoning seriously.' },
      { myth: 'He was a gloomy poet who offers no comfort.', reality: 'His writing is full of tenderness, irony and humour, and in his last poems he calls for human solidarity. Many readers find the honesty consoling.' },
      { myth: 'Leopardi was a follower of Schopenhauer.', reality: 'Leopardi wrote before Schopenhauer was widely known and never read him. The similarity between them comes from separate paths, and it was Schopenhauer who later noticed Leopardi.' },
    ],
    works: [
      { title: 'Canti', note: 'His collected poems, including “L’infinito”, “A Silvia”, “Canto notturno di un pastore errante dell’Asia”, “A se stesso” and “La ginestra”.' },
      { title: 'Operette morali (1827; expanded later)', note: 'Dialogues and prose pieces in elegant, ironic language, on nature, happiness, glory and death.' },
      { title: 'Zibaldone di pensieri', note: 'His private notebooks, published after his death.' },
      { title: 'Pensieri', note: 'A short collection of aphorisms and observations on society, published after his death.' },
      { title: 'Epistolario', note: 'His letters, which give much of what we know of his life, health and friendships.' },
    ],
    legacy: [
      'In Italy Leopardi is regarded as the greatest poet since Dante and Petrarch, and he is taught in every school. Outside Italy he became known more slowly. Nietzsche and Schopenhauer admired him, and writers such as Beckett, Ungaretti and Montale have written about him or been shaped by him. William Gladstone, later the British prime minister, translated some of his poems.',
      'Philosophers have been slower to see him as one of their own, but the publication of the Zibaldone has made it clear that he was an original thinker about language, imagination, nature and the self. His pessimism looks forward to existentialism, though with a more tender, humane note than many later writers: he sees suffering as universal and therefore a ground for compassion.',
    ],
  },
  {
    slug: 'ludwig-feuerbach',
    order: 1804,
    dates: '1804 – 1872',
    place: 'Landshut, Erlangen, Bruckberg and Nuremberg, Bavaria',
    era: '19th Century',
    tradition: 'Young Hegelians',
    tagline: 'The philosopher who said that God is a projection of human nature, and whose humanism shaped Marx, Engels and Freud.',
    who: [
      'Ludwig Feuerbach was born in 1804 in Landshut, Bavaria, one of several gifted sons of the jurist Paul Johann Anselm von Feuerbach. He began to study theology at Heidelberg, where the teacher Karl Daub introduced him to Hegel’s philosophy, and he then moved to Berlin to hear Hegel himself. He later described Hegel as the teacher who shaped him most. In 1828 he took his doctorate at Erlangen and began to lecture there.',
      'His career in the university ended quickly. In 1830 he published, anonymously, Thoughts on Death and Immortality, which attacked the idea of a personal afterlife. When his authorship became known, he was shut out of academic posts in the conservative Bavaria of the time. After his marriage in 1837 to Bertha Löw, a part-owner of a porcelain factory, he lived for more than two decades in the village of Bruckberg, writing in relative isolation on the strength of her income.',
      'The Essence of Christianity (1841) made him famous across Germany, and for a few years he was the leading voice of the radical young followers of Hegel. In 1848 he was invited by students to lecture in the Heidelberg town hall, because the university would not host him. After the revolution failed he withdrew. When the factory failed around 1860 the family fell into financial hardship, and he moved near Nuremberg. He joined the Social Democratic Workers’ Party in 1870 and died in 1872, a respected but largely forgotten figure.',
    ],
    context: [
      'After Hegel died in 1831, his followers split. The “Old Hegelians” held that his system supported Christianity and the Prussian state. The “Young Hegelians”, among them David Friedrich Strauss, Bruno Bauer, Feuerbach, the young Marx and Engels, and Max Stirner, used his method of criticism to question religion and politics. In an age of censorship, an attack on religion was an indirect attack on the authority of the state, which was bound up with the Church.',
      'Strauss’s Life of Jesus (1835) had treated the Gospel stories as myths created by the early community, and this opened the way for Feuerbach’s more thoroughgoing claim that religion is a human creation. The revolutions of 1848 raised hopes for a free and democratic Germany, and Feuerbach’s call to put humanity in the place of God matched the mood of those who hoped for it.',
    ],
    ideas: [
      { title: 'Religion as projection', text: 'Feuerbach argued that God is the human being’s own essence, projected outward and made into an independent being. Qualities such as love, wisdom and justice are human ideals, which people take from themselves, enlarge to infinity and then worship as if they belonged to someone else. Theology, he said, is really anthropology, the study of humanity.' },
      { title: 'Alienation', text: 'Projecting our best qualities onto God leaves us poorer: the more we give to God, the less we think we have ourselves. Feuerbach called this a form of self-estrangement. Taking back what belongs to humanity would restore dignity, and in his view it would not destroy morality but return it to its true home.' },
      { title: 'Reversing the subject and predicate', text: 'Hegel’s philosophy, in Feuerbach’s view, was theology in disguise: it made thought or spirit the real subject and the human being merely its expression. He proposed to turn this upside down and to start from real, sensuous, bodily human beings, with thought as one of their activities. Marx later used this “inverting” method in his own way.' },
      { title: 'The I and the You', text: 'In his later works Feuerbach stressed that people exist only in relation to others. Humanity is realised not in the isolated thinker but in the meeting of I and You, in love and friendship. He summed it up by saying that human beings are gods to each other, meaning that what we revere in God we should cherish in one another. This idea later influenced Martin Buber.' },
      { title: 'The body and nature', text: 'Feuerbach rejected a philosophy of pure reason in favour of one that respects the senses, the body and our dependence on nature. His well-known pun, “man is what he eats” (1850), made a serious point: ideas cannot be separated from material life. He also held that feeling of dependence is at the root of religion.' },
    ],
    principles: [
      'Look for the human need behind a belief.',
      'Take back for yourself and for others the best qualities you tend to place far away.',
      'Begin from real people, in their bodies and relationships, not from abstractions.',
      'Treat love and friendship as the heart of human life.',
      'Respect what we owe to nature and to others, since we are not self-sufficient.',
    ],
    practice: [
      'When you admire an ideal, such as justice or kindness, ask where you can practise it yourself, not only where you can praise it.',
      'When you read a big abstract claim, ask which real person it describes, and what that person needs.',
      'Strengthen one friendship this month by spending time face to face.',
    ],
    facts: [
      'The Essence of Christianity was translated into English by Marian Evans, later known as the novelist George Eliot, in 1854.',
      'Richard Wagner dedicated his essay The Artwork of the Future (1849) to Feuerbach.',
      'His nephew was the painter Anselm Feuerbach, and his father was one of the leading legal reformers of Bavaria.',
      'Marx’s eleven “Theses on Feuerbach”, written in 1845 and first published by Engels in 1888, criticised him for being too contemplative and too little historical.',
      'Engels recalled in 1886 that the book had a liberating effect on young radicals, who for a time all became “Feuerbachians”.',
      'He joined the Social Democratic Workers’ Party in 1870 and, in his last years, studied Marx’s Capital with interest.',
    ],
    myths: [
      { myth: 'Feuerbach simply wanted to destroy religion.', reality: 'He wanted to understand it. He thought that religion expressed real human hopes and needs, and he wanted to move the love and devotion that people give to God toward other human beings.' },
      { myth: 'He was a Marxist.', reality: 'Marx and Engels learned from him and then moved past him, and Marx criticised his picture of man as an abstract, unchanging being. Feuerbach had little interest in economics or in organised politics until the end of his life.' },
    ],
    works: [
      { title: 'Thoughts on Death and Immortality (1830)', note: 'His anonymous first book, which cost him his academic career.' },
      { title: 'The Essence of Christianity (1841)', note: 'His most influential book, setting out the theory of projection.' },
      { title: 'Principles of the Philosophy of the Future (1843)', note: 'A short, sharp programme for a philosophy of the human being, built on the senses and on relation to others.' },
      { title: 'Lectures on the Essence of Religion (1851)', note: 'Based on the Heidelberg lectures of 1848–49.' },
      { title: 'Theogony (1857)', note: 'A later study of the origins of the gods in ancient religions, showing his turn toward nature and need.' },
    ],
    legacy: [
      'Feuerbach’s ideas travelled quickly. Marx and Engels took from him the claim that religion is a human product and the method of turning abstractions back to human activity, then built their own materialism on a historical and economic base. Freud’s later treatment of religious belief as a projection of human wishes draws on a similar thought, though Freud’s route to it was different. Nietzsche, Wagner and many writers of the later nineteenth century also read him closely.',
      'In his own time and after, Feuerbach himself faded. He was neither a systematic builder nor a politician, and the scientific materialism of the following decades overtook his version. Yet his central idea, that our images of the divine tell us about ourselves, remains one of the most important in the study of religion, and his stress on relation to others has found echoes in the philosophy of dialogue and in humanist thought.',
    ],
  },
  {
    slug: 'max-stirner',
    order: 1806,
    dates: '1806 – 1856',
    place: 'Berlin, Prussia',
    era: '19th Century',
    tradition: 'Individualist anarchism',
    tagline: 'A shadowy Berlin schoolteacher whose single book defended the unique self against every cause, creed and state.',
    who: [
      'Max Stirner was the pen name of Johann Caspar Schmidt, born in 1806 in Bayreuth, Bavaria. His father, a maker of wind instruments, died when he was an infant, and he grew up partly in Kulm in West Prussia. “Stirner” was a nickname that referred to his high forehead (Stirn in German). He studied philosophy, philology and theology in Berlin, where he attended lectures by Hegel and Schleiermacher, and then at Erlangen and Königsberg, but he never obtained a stable post in the state school system.',
      'From about 1839 he taught at a private school for girls in Berlin. His first wife, Agnes Burtz, died in 1838 after only a short marriage. In 1843 he married Marie Dähnhardt, a woman from the radical circle he moved in, but the marriage did not last. In the early 1840s he joined the Berlin club known as “The Free” (Die Freien), a group of Young Hegelians who met at a wine bar and argued about religion and politics. Marx and Engels were among those who visited, and Engels later drew a sketch of Stirner, which is the only known likeness of him.',
      'In late 1844 Stirner published The Ego and Its Own, a book that astonished and troubled his friends and then, for decades, nearly vanished from sight. He replied to critics in 1845, translated Adam Smith and Jean-Baptiste Say into German, and in 1852 published a compilation, History of Reaction. He fell into poverty, went into debtors’ prison in the 1850s according to his biographer, and died in Berlin in 1856. Very little is known about his private life, and most of what we know comes from the biography written by John Henry Mackay in 1898, long after his death.',
    ],
    context: [
      'Stirner was a Young Hegelian, part of the generation that took Hegel’s philosophy and turned it against religion and the Prussian state. By 1843–44, the group had moved from criticising Christianity to criticising the idea of God itself, with Feuerbach arguing that God is a projection of humanity. Stirner asked what then replaced God, and he thought the answer given by his friends, such as Humanity, the Nation or the State, was just another god.',
      'Prussia under Frederick William IV was a censored, conservative monarchy, and there was great hope among liberals and radicals for constitutional change, which would come to a head in 1848. Stirner’s book, which came out during this wave of hope and debate, was a challenge to the optimism of liberals, socialists and humanists alike.',
    ],
    ideas: [
      { title: 'The unique one', text: 'The German title of his book, Der Einzige und sein Eigentum, means “the unique one and his property”. The unique individual is not a type or a member of any group, and cannot be captured by a concept such as Man or Citizen. Stirner begins and ends the book with a line adapted from Goethe: he has based his cause on nothing, meaning that he serves no higher principle outside himself.' },
      { title: 'Spooks and fixed ideas', text: 'Stirner argued that people are ruled by ideas they treat as sacred, such as God, humanity, duty, rights, the state and even freedom. These are fixed ideas, or “spooks”, that live in our heads and demand obedience. To free oneself, a person must see through them and ask what they actually want.' },
      { title: 'Egoism', text: 'He claimed that each person acts from self-interest anyway, even when serving a cause, and that it is more honest to admit it. This did not mean crude selfishness: the egoist might love and help others because it satisfies him. The point was to recognise one’s own will as the basis of what one does, not an external authority.' },
      { title: 'Critique of liberalism and humanism', text: 'Stirner distinguished political, social and humane liberalism, and said each replaced one master with another: the state, society or the abstract “Man”. Even Feuerbach, he argued, had only turned God into Humanity and kept the old habit of worship. For Stirner, real freedom means “ownness”, being master of oneself, not simply being released from particular rulers.' },
      { title: 'The union of egoists', text: 'In place of the state and fixed institutions, Stirner proposed voluntary associations, a “union of egoists”, which people join for their own benefit and may leave at will. He also treated rights as a matter of power: what you can take and keep is yours, a view that critics found chilling. How far he meant this as a political programme remains debated.' },
    ],
    principles: [
      'Ask whether an idea you serve is really yours, or has been placed in you by others.',
      'Do not let a cause, even a good one, replace your own judgment.',
      'Be honest about your motives.',
      'Join with others freely and for real reasons, and be ready to leave when those reasons end.',
      'Treat yourself as an owner, not a servant, of your thoughts.',
    ],
    practice: [
      'List a few beliefs you hold on duty or principle, and for each ask who taught it to you and what it costs you.',
      'Before joining a group, write what you want from it and under what conditions you would leave.',
      'Notice when you say “one should”, and try replacing it with “I want” or “I choose”.',
    ],
    facts: [
      'The Ego and Its Own appeared in late 1844, though the title page bears the date 1845, and it was published in Leipzig by Otto Wigand.',
      'Stirner’s pen name came from a nickname about his forehead; his real name, Johann Caspar Schmidt, was one of the commonest in Germany.',
      'The only known portrait is a sketch that Engels drew from memory many years later, along with a group drawing of The Free at Hippel’s wine bar.',
      'Marx and Engels wrote a very long reply in The German Ideology (1845–46), where the section called “Saint Max” is the largest part of the text. The work was not published in full until 1932.',
      'The Scottish-German writer John Henry Mackay rediscovered him in the 1880s and published a biography in 1898, which is the main source on his life.',
      'The first English translation, The Ego and His Own, by Steven T. Byington, was published in New York in 1907 by the anarchist Benjamin Tucker.',
    ],
    myths: [
      { myth: 'Stirner taught that you should trample on others for your own gain.', reality: 'His egoism is mainly about freeing oneself from imposed ideals, and he allows that an egoist may love and cooperate. His remarks on power and right are unsettling, though, and readers disagree about how far his theory offers any ethical limit.' },
      { myth: 'Stirner was the source of Nietzsche’s philosophy.', reality: 'Some readers noticed similarities as early as the 1890s, but Nietzsche never mentions Stirner in his published work, and there is no firm evidence that he read him. Historians continue to debate it.' },
      { myth: 'Stirner was an anarchist.', reality: 'He did not use the word of himself, and he opposed political revolution as another cause. Individualist anarchists such as Benjamin Tucker and Dora Marsden later adopted him, and his place in the anarchist tradition is a matter of interpretation.' },
    ],
    works: [
      { title: 'The Ego and Its Own (1844)', note: 'His only major book, in two parts: “Man” and “I”.' },
      { title: 'Stirner’s Critics (1845)', note: 'His reply to the reviews, clarifying some points.' },
      { title: 'The False Principle of Our Education (1842)', note: 'An earlier essay on schooling, published in the Rheinische Zeitung, that already shows his stress on the individual.' },
      { title: 'Marx and Engels, The German Ideology (written 1845–46)', note: 'A long critique of Stirner, not published during their lifetimes.' },
      { title: 'John Henry Mackay, Max Stirner: His Life and His Work (1898)', note: 'The only full biography, built from the few traces he left.' },
    ],
    legacy: [
      'For decades after his death Stirner was nearly forgotten. Mackay’s efforts and the translations that followed brought him new readers around 1900, especially among individualist anarchists in the United States, Britain and Europe, and among writers and artists who disliked collective movements. Later readers have found him in existentialism, the writings of Albert Camus (who discussed him in The Rebel), the Situationists and post-left anarchism. He has also been read by some on the political right, and anarchists and socialists have both criticised these readings.',
      'Marx and Engels thought him important enough to answer at length, and the answer shows how seriously they took his challenge to their idea of liberation. Whether one finds Stirner liberating, alarming or both, his book remains a standing test for every philosophy that asks the individual to serve a higher cause: it asks, in the bluntest way, why.',
    ],
  },
]
