import type { Profile } from './types'

export const MORE_13: Profile[] = [
  {
    slug: 'herbert-spencer',
    order: 1820,
    dates: '1820 – 1903',
    place: 'Derby, then London, England',
    era: '19th Century',
    tradition: 'Evolutionary philosophy',
    tagline: 'The self-taught Victorian who tried to explain the whole universe, from stars to societies, as one process of evolution.',
    who: [
      'Herbert Spencer was born in Derby, England, in 1820, the son of a schoolteacher with independent religious views. He had little formal schooling and was taught largely at home and later by an uncle who was a clergyman. As a young man he worked as a civil engineer on the new railways, then turned to journalism and became a sub-editor at The Economist in the late 1840s. His first book, Social Statics, appeared in 1851.',
      'In 1855 he published The Principles of Psychology, which treated the mind as something that develops over time, and after Darwin’s Origin of Species appeared in 1859 he set himself an enormous task: a “Synthetic Philosophy” that would show one law of evolution at work in nature, life, mind, society and morals. The plan was outlined around 1858–60, the first volume came out in 1862, and the last volume was finished in 1896, so the project took far longer than the twenty years he had first expected.',
      'He never married, held no university post and often struggled with poor health and sleeplessness. Friends included George Eliot, John Stuart Mill and Thomas Huxley, and he belonged to Huxley’s dining circle, the X Club. He declined honours that were offered to him, and he died in Brighton in 1903. His ashes lie in Highgate Cemetery in London.',
    ],
    context: [
      'Spencer wrote in an age of rapid change: railways, factories and fast-growing cities, together with new science in geology and biology. Many Victorians wondered whether progress was a law of nature or only a hope, and whether science and religion could be reconciled. A thinker who offered a single grand explanation for all of it found a large audience, in Britain and especially in the United States.',
      'Politically, he belonged to the English tradition of radical individualism that distrusted state power and admired free trade and voluntary association. He wrote against the growth of government regulation in the later nineteenth century, at a time when many liberals were beginning to accept a larger role for the state in education, housing and public health.',
    ],
    ideas: [
      { title: 'Evolution as a universal law', text: 'Spencer held that everything, from the solar system to languages and laws, develops by moving from the simple and uniform toward the complex and differentiated, with its parts becoming more specialised and more dependent on one another. He used the word “evolution” in this wide sense before it became tied to Darwin’s biology. Critics later objected that his formula was so general that it explained everything and predicted nothing.' },
      { title: 'Survival of the fittest', text: 'In The Principles of Biology (1864) Spencer coined the phrase “survival of the fittest” to sum up what he saw as the same idea as Darwin’s natural selection. Darwin adopted the phrase himself in later editions of the Origin. Spencer also relied on the inheritance of acquired characteristics, an idea associated with Lamarck, and defended it against critics such as August Weismann in the 1890s.' },
      { title: 'The Unknowable', text: 'In First Principles, Spencer argued that science and religion could be reconciled because both lead to a power behind appearances that human minds cannot fully grasp. Science explains the relations between things, he said, and religion points to the mystery that remains. Readers found this either a respectful peace treaty or an evasion.' },
      { title: 'The law of equal freedom', text: 'His ethics and politics rested on the principle that each person should be free to do what they wish, provided they do not infringe the equal freedom of anyone else. From it he argued for a small state, and he opposed state-run education, compulsory poor relief and many forms of regulation. He distinguished “militant” societies, organised around war and obedience, from “industrial” societies, based on voluntary exchange, and he hoped the second would replace the first.' },
      { title: 'Society as a kind of organism', text: 'Spencer compared societies to living bodies: they grow, develop specialised organs and depend on the cooperation of the parts. He used the comparison to study how institutions arise and change, and he is counted among the founders of sociology. He also warned against pushing the analogy too far, since a society, unlike an animal, exists for the sake of its individual members.' },
    ],
    principles: [
      'Look for the general pattern behind many separate facts.',
      'Respect the equal freedom of other people as the limit of your own.',
      'Be suspicious of quick remedies that are imposed from above and ignore side effects.',
      'Accept that some things are beyond the reach of the human mind, and be humble about them.',
      'Let your views change when the evidence changes, even for a favourite theory.',
    ],
    practice: [
      'When a problem seems new, ask what it resembles in another field, and what the pattern might teach you.',
      'Before backing a rule or a reform, ask who bears the cost and what side effects it may have.',
      'Separate what science can measure from what it cannot, and say plainly which one you are discussing.',
    ],
    facts: [
      'Spencer’s Man versus the State (1884) is his best-known political work. Its title is still used for arguments against state expansion.',
      'In the first edition of Social Statics he argued that private ownership of land conflicts with equal freedom. He later withdrew this position in a revised edition.',
      'He toured the United States in 1882, where his books had sold widely, and was honoured at a large dinner in New York.',
      'Justice Oliver Wendell Holmes wrote in his 1905 dissent in Lochner v. New York that the Fourteenth Amendment did not enact Mr. Herbert Spencer’s Social Statics.',
      'He remained an opponent of imperialism and militarism throughout his life.',
      'His Autobiography was published after his death, in 1904.',
    ],
    myths: [
      { myth: 'Spencer was a “social Darwinist” who taught that the poor should be left to die so the strong could thrive.', reality: 'The label “social Darwinism” was applied later, mostly in the twentieth century, to a range of views, and Spencer did not use it. He did argue against state relief and criticised interference with the effects of competition. But he also stressed that private kindness and sympathy were valuable and expected cooperation to become more important over time. Historians still debate how far his arguments justified later policies of inequality, eugenics or racism, which he himself did not clearly endorse, and how far his critics have simplified him.' },
      { myth: 'Spencer invented evolution before Darwin and Darwin took the idea from him.', reality: 'Spencer wrote about development and evolution before 1859, but he did not have Darwin’s mechanism of natural selection. He took the phrase “survival of the fittest” from his reading of Darwin, not the reverse.' },
      { myth: 'He was a conservative defender of the establishment.', reality: 'Early in life Spencer was a radical who backed women’s equality and criticised private landholding. His later writing grew more conservative on economic questions, but he kept his opposition to empire and war.' },
    ],
    works: [
      { title: 'Social Statics (1851)', note: 'His first book, setting out the law of equal freedom and a case for limited government.' },
      { title: 'The Principles of Psychology (1855)', note: 'An early attempt to treat the mind as the product of evolution.' },
      { title: 'First Principles (1862)', note: 'The foundation of the Synthetic Philosophy: the Unknowable and the law of evolution.' },
      { title: 'The Principles of Biology, Sociology and Ethics', note: 'Later volumes of the Synthetic Philosophy, completed by 1896.' },
      { title: 'The Man versus the State (1884)', note: 'Essays attacking the growth of state power.' },
    ],
    legacy: [
      'In his own lifetime Spencer was among the most widely read philosophers in the English-speaking world, and his ideas shaped early sociology, education and debates about progress. After 1900 his reputation fell quickly. Specialists found his system too sweeping and too loosely tied to evidence, and his reliance on Lamarckian inheritance was undermined by genetics.',
      'He is still studied as a window on Victorian thought and as a source for debates about liberty and the state. Historians remain divided on his connection to social Darwinism: some see him as one of its chief sources, while others say the term fits the views of later writers better than his own. Either way, his gift to the language, “survival of the fittest”, remains one of the most quoted and most misunderstood phrases in the history of science.',
    ],
  },
  {
    slug: 'ernest-renan',
    order: 1823,
    dates: '1823 – 1892',
    place: 'Paris, France (born in Tréguier, Brittany)',
    era: '19th Century',
    tradition: 'French historical criticism',
    tagline: 'A scholar who lost his faith, wrote the life of Jesus as a human story, and defined a nation as a daily act of shared will.',
    who: [
      'Ernest Renan was born in 1823 in Tréguier, a small town in Brittany. His father, a sailor, died at sea when Ernest was a child, and the family lived in poverty. His much older sister Henriette helped support him, and he was educated for the priesthood, first in Brittany and then at the Paris seminary of Saint-Sulpice.',
      'While studying Hebrew and German biblical scholarship, he concluded that he could no longer accept the Church’s teaching about scripture, and in 1845 he left the seminary. He turned to philology, the study of languages and texts, and made his reputation with works on the Semitic languages and on the medieval philosopher Averroes. In 1860–61 he led an archaeological mission to Phoenicia in what is now Lebanon, where his sister Henriette, who had joined him, died.',
      'In 1862 he was appointed professor of Hebrew at the Collège de France. His opening lecture called Jesus “an incomparable man”, and the uproar led to the suspension of his course. He was removed from the chair in 1864 and was restored only after the fall of the Second Empire in 1870. His Life of Jesus (1863) became a bestseller, he entered the Académie française in 1878, and he later became administrator of the Collège de France. He died in Paris in 1892.',
    ],
    context: [
      'Renan lived in a France divided between the Catholic Church and a secular, republican and scientific outlook. German scholarship, especially David Friedrich Strauss’s Life of Jesus (1835), had begun to apply critical methods to the Bible. Renan brought that approach to a French public and wrote in a style meant for ordinary educated readers, not only specialists.',
      'After France lost the war with Prussia in 1870–71 and the border regions of Alsace and Lorraine were annexed by Germany, French intellectuals asked what made a people a nation, and who had a right to decide its borders. Renan’s best-known lecture was part of that debate. The age also believed in a hierarchy of “races”, a belief now rejected, and Renan shared it for much of his career.',
    ],
    ideas: [
      { title: 'A historian’s Jesus', text: 'In the Life of Jesus Renan treated Jesus as a historical person, not a divine figure, and he rejected miracles as events that historians cannot accept. He portrayed him as a gentle and charismatic preacher in Galilee. The book was attacked by churchmen as an insult to faith, and by some scholars for its romantic and imaginative portrait of the evidence. It was the first of a seven-volume History of the Origins of Christianity.' },
      { title: 'Religion as a human creation to be studied', text: 'Renan believed religions could be studied like any other historical product, through languages, texts and inscriptions. He kept respect for religious feeling even after losing his own faith, and he thought the scientific study of the past could replace superstition without destroying what was valuable in it.' },
      { title: 'What Is a Nation? (1882)', text: 'In a lecture given at the Sorbonne, Renan argued that a nation is not defined by race, language, religion or geography. It rests on a shared rich heritage of memories and on the present will to live together, which he called a “daily plebiscite”. He also remarked that forgetting, and even historical error, are part of creating a nation, because every nation’s past includes violence that its members have chosen to leave behind.' },
      { title: 'Science as the guide of humanity', text: 'In his early book The Future of Science, written in 1848–49 but published only in 1890, he hoped that scientific criticism would become the main source of truth and progress. Later in life he was more doubtful and more sceptical, and his writing took on a tone of ironical detachment.' },
      { title: 'Race, and why his views are rejected', text: 'In his earlier scholarship Renan described “Semitic” peoples as having a limited, inferior mentality compared with “Aryan” peoples, and he wrote of the superiority of some races over others. These claims have no scientific basis and are now rejected. He softened his position later: in 1882 he wrote that pure races do not exist, and in an 1883 lecture he denied that Jews were a race. Historians nonetheless note that his earlier writing helped spread racial ideas of language and mind.' },
    ],
    principles: [
      'Examine inherited beliefs with the tools of honest scholarship.',
      'Respect what is meaningful in other people’s faith even when you disagree.',
      'Belonging is a matter of shared memory and present choice, not of blood.',
      'Be ready to see how much a shared past depends on what a group agrees to forget.',
      'Check your own era’s certainties, because ours are not safer than those of the past.',
    ],
    practice: [
      'When reading about a founding story, a nation, a company or a family, ask which parts are remembered and which are left out.',
      'When you study a belief you do not hold, learn it well enough that its followers would recognise it.',
      'When you notice a generalisation about a whole people, treat it as a warning sign and ask for the evidence.',
    ],
    facts: [
      'He was suspended from the Collège de France in 1862 after a single lecture, and dismissed in 1864 when he refused to resign.',
      'In 1871 he exchanged open letters with David Friedrich Strauss on the Franco-Prussian War and the future of Alsace-Lorraine.',
      'The Life of Jesus was translated into many languages and sold widely, drawing sharp responses from the Catholic Church.',
      'He wrote a memoir, Recollections of My Youth, published in 1883, about his Breton childhood and loss of faith.',
      'He became a member of the Académie française in 1878.',
      'His 1882 lecture is often cited today in debates on nationalism and national identity.',
    ],
    myths: [
      { myth: 'Renan said that a nation is a “daily plebiscite”, so anyone may leave or join as they please.', reality: 'The phrase describes the continuing consent that holds a nation together, but Renan also insisted on a shared past, heroes and sacrifices. He did not mean that nationality is a casual, individual choice.' },
      { myth: 'Renan was simply an enemy of religion.', reality: 'He rejected the Church’s authority and miracles, but he wrote with admiration for religious experience and for the moral force of Christianity, and his critics on the secular side sometimes found him too sympathetic.' },
    ],
    works: [
      { title: 'Life of Jesus (1863)', note: 'The first volume of his History of the Origins of Christianity; a bestseller and a scandal.' },
      { title: 'What Is a Nation? (1882)', note: 'A lecture at the Sorbonne, widely reprinted.' },
      { title: 'The Future of Science (written 1848–49, published 1890)', note: 'His early statement of faith in scientific progress.' },
      { title: 'Recollections of My Youth (1883)', note: 'A graceful memoir of his childhood and his break with the Church.' },
      { title: 'History of the People of Israel (1887–93)', note: 'His late, multivolume history of ancient Israel.' },
    ],
    legacy: [
      'Renan helped to make critical study of the Bible and the origins of Christianity familiar to a general readership, and his style, polished and ironic, was admired by many writers. His lecture on the nation became one of the most quoted texts in political thought, and political scientists still cite it as a classic statement of the “civic” idea of the nation, based on consent, against the “ethnic” idea, based on descent.',
      'At the same time his writings on race show how a learned and humane scholar could repeat the prejudices of his time. His claims about Semitic and other peoples were later used by others for harmful purposes, and today they are rejected. Readers value him for his historical questions and his definition of the nation, and read the rest with care.',
    ],
  },
  {
    slug: 'thomas-henry-huxley',
    order: 1825,
    dates: '1825 – 1895',
    place: 'London, England (born in Ealing)',
    era: '19th Century',
    tradition: 'Scientific agnosticism',
    tagline: 'Darwin’s fiercest public defender, who gave the world the word “agnostic” and argued that ethics must resist nature.',
    who: [
      'Thomas Henry Huxley was born in Ealing, then a village near London, in 1825. His family was not wealthy and he had barely two years of formal schooling; he educated himself, reading widely and teaching himself German. He trained in medicine, and in 1846 he sailed as assistant surgeon on HMS Rattlesnake, a naval survey voyage to Australia and New Guinea, which gave him the chance to study marine animals. On the voyage he met Henrietta Heathorn, whom he married in 1855.',
      'He was elected a Fellow of the Royal Society in 1851 and became a professor at the Government School of Mines in London, a forerunner of Imperial College. When Darwin’s Origin of Species appeared in 1859, Huxley defended it in the press and in public lectures, and he earned the nickname “Darwin’s bulldog”. He was not an uncritical follower: he doubted that natural selection had been proved, and he was unsure that evolution always proceeds in small steps.',
      'In later life he was an influential public figure: a member of the London School Board, president of the Royal Society from 1883 to 1885, and a popular lecturer. He died in Eastbourne in 1895. His descendants include the biologist Julian Huxley and the novelist Aldous Huxley.',
    ],
    context: [
      'Victorian Britain was changing quickly, and science was becoming a profession. The universities and the Church of England, which had controlled education and public opinion, were challenged by new fields of knowledge. Huxley belonged to a generation that wanted scientists to have status and funds, and that wanted science taught in schools.',
      'The debate over evolution touched on deep questions about human origins, the authority of scripture and the place of morality. Huxley’s position was that these should be argued on evidence, in public, by people who were willing to follow the facts. This made him both admired and hated, but it also made him one of the most effective communicators of science of his time.',
    ],
    ideas: [
      { title: 'Defending evolution in public', text: 'Huxley wrote a review of the Origin of Species in 1859 and then lectured widely to working people as well as scholars. His Evidence as to Man’s Place in Nature (1863) argued from anatomy that humans are closely related to the apes. He also proposed, in the late 1860s, that birds descend from small dinosaurs, an idea now broadly accepted.' },
      { title: 'Agnosticism as a method', text: 'In 1869, at a meeting of the Metaphysical Society, Huxley coined the word “agnostic”, from the Greek for “not knowing”, taking it as the opposite of the Gnostics, who claimed secret knowledge. For him it was a method, not a creed: follow reason as far as it goes, and do not claim certainty about what has not been shown. He applied this to religious claims, but also to his own scientific views.' },
      { title: 'Science and general education', text: 'Huxley campaigned for science to be a regular part of education, from primary schools to universities. He also wanted education open to girls and children of the poor. In 1880, in a speech opening a science college in Birmingham, he argued that science deserved a place alongside literature in a good education, which drew a reply from Matthew Arnold.' },
      { title: 'Evolution and Ethics', text: 'In his Romanes Lecture at Oxford in 1893, Huxley argued that the “cosmic process” of struggle and selection does not provide a pattern for human morality. Human ethics, he said, depends on restraining and resisting the competitive struggle, not copying it. This put him at odds with writers such as Herbert Spencer, who saw morality as a continuation of evolution.' },
      { title: 'Evidence over authority', text: 'Huxley held that scientific beliefs must rest on evidence that anyone can examine, and he applied that rule to claims by scientists and clergy alike. He once made a mistake of this kind himself: he named a supposed ocean-floor organism, Bathybius, later shown to be a chemical precipitate, and he publicly admitted the error in 1875.' },
    ],
    principles: [
      'Follow the evidence, even when you dislike where it leads.',
      'Do not claim to know what you have not shown.',
      'Make knowledge public, and explain it to people without special training.',
      'Admit mistakes openly.',
      'Human goodness is an achievement that takes effort, not something nature supplies for free.',
    ],
    practice: [
      'When you disagree on a factual question, state what evidence would change your mind, and ask the other person the same.',
      'Explain something you know well to a person outside the field, and notice what you had assumed.',
      'Use “I do not know” as a real answer, and separate it from “nobody can know”.',
    ],
    facts: [
      'The 1860 Oxford meeting of the British Association took place on 30 June, in the new University Museum. Bishop Samuel Wilberforce and Huxley both spoke, but no verbatim record exists.',
      'Several eyewitnesses reported that Wilberforce asked, in effect, whether Huxley was descended from an ape on his grandfather’s or his grandmother’s side, but the accounts of Huxley’s reply differ in their wording.',
      'He coined “agnostic” in 1869, though he described the occasion only later, in an 1889 essay.',
      'His son Noel died of scarlet fever in 1860, at the age of four, which affected him deeply.',
      'He was elected to the first London School Board in 1870 and helped shape its approach to teaching.',
      'In 1868 he gave a lecture, On a Piece of Chalk, to working people in Norwich, showing how a lump of chalk tells the history of the Earth.',
    ],
    myths: [
      { myth: 'Huxley crushed Bishop Wilberforce in the 1860 Oxford debate, and the audience cheered the triumph of science.', reality: 'We know the main speakers, the date and the place, and that the ape remark was made and answered in some form. The rest of the legend, including the dramatic retort and the lady who fainted, comes from later recollections that disagree with each other. At the time many people believed the bishop held his own, and the “victory” grew in the telling.' },
      { myth: 'Huxley was an atheist.', reality: 'He rejected that label and invented “agnostic” partly to describe a different position, namely that the existence of God cannot be known. He also supported Bible reading in schools, without doctrinal teaching.' },
      { myth: 'Huxley and Darwin agreed on everything.', reality: 'Huxley supported evolution but hesitated over natural selection as the sole mechanism and over strict gradualism, and he said so in print.' },
    ],
    works: [
      { title: 'Evidence as to Man’s Place in Nature (1863)', note: 'A comparison of humans and apes, among the first books to apply evolution to human origins.' },
      { title: 'Lay Sermons, Addresses and Reviews (1870)', note: 'Collected essays and talks for general readers, including On a Piece of Chalk.' },
      { title: 'Science and Culture (1881)', note: 'A volume of addresses on education, including his Birmingham speech.' },
      { title: 'Agnosticism and related essays (1889)', note: 'His explanation of the word and his controversies with churchmen.' },
      { title: 'Evolution and Ethics (1893, expanded 1894)', note: 'The Romanes Lecture, with a Prolegomena added a year later.' },
    ],
    legacy: [
      'Huxley’s campaign gave science a place in British schools and universities and made scientists respected public voices. “Agnostic” entered everyday language. His arguments about human evolution and his sceptical, evidence-first style influenced generations of teachers and writers.',
      'His record is not flawless. Like many Victorian scientists he accepted a ranking of human races, including in an 1865 essay in which he opposed slavery but still held that people differ in natural capacity. This view has no scientific support and is rejected today. His reputation rests on his defence of open inquiry, and on the question he raised in Evolution and Ethics, which is still debated: whether morality can be grounded in nature, or must be built against it.',
    ],
  },
  {
    slug: 'ramakrishna',
    order: 1836,
    dates: '1836 – 1886',
    place: 'Dakshineswar, near Calcutta, Bengal (born in Kamarpukur)',
    era: '19th Century',
    tradition: 'Bengal mysticism',
    tagline: 'A temple priest in Bengal whose devotion to the Divine Mother and respect for many faiths drew visitors from across Calcutta.',
    who: [
      'Ramakrishna was born Gadadhar Chattopadhyay in 1836 in Kamarpukur, a village in rural Bengal, into a poor Brahmin family. He had little schooling and was drawn to songs, stories and religious play. After the death of his father he went to Calcutta, where his elder brother Ramkumar became a priest at the new Kali temple at Dakshineswar, founded by the wealthy widow Rani Rashmoni and consecrated in 1855. When Ramkumar died, Ramakrishna took over his duties.',
      'At Dakshineswar he became absorbed in the worship of Kali, the Divine Mother, and according to the accounts of his followers he went through years of intense longing and visions, with episodes of trance that onlookers took for illness or madness. In 1859 he married Sarada Devi, then a young girl, as was the custom of the time. She joined him at Dakshineswar some years later; the marriage, by all accounts, remained celibate, and he is said to have worshipped her as an embodiment of the Divine Mother.',
      'In the following years he studied under several teachers: a woman ascetic known as the Bhairavi Brahmani, who guided him in Tantric practice, and the monk Totapuri, who taught him the non-dual Vedanta path and initiated him as a renunciant in 1865. He also practised Vaishnava devotion, and, according to his biographers, followed Islamic and Christian practice for a time. In 1885 he became ill with throat cancer and died in 1886 in a garden house at Cossipore, near Calcutta.',
    ],
    context: [
      'Calcutta in the nineteenth century was the centre of British rule in India and of the “Bengal Renaissance”, in which an English-educated class debated social reform, religion and nationalism. Reform movements such as the Brahmo Samaj challenged image worship and caste. Missionaries and Western education led many young men to doubt the traditions of their families.',
      'Ramakrishna, who spoke Bengali, used village parables and songs, and showed no interest in reform platforms, was an unlikely figure for this setting. Yet many educated visitors, including members of the Brahmo Samaj such as Keshab Chandra Sen, came to hear him, perhaps because he spoke of direct religious experience instead of argument.',
    ],
    ideas: [
      { title: 'Direct experience of the divine', text: 'Ramakrishna taught that God can be experienced, not just believed in, and that sincere longing is what opens the way. He compared a person’s longing for God to that of a drowning person for air. Followers record that he spoke of God as both with form and without form, and he kept both paths open.' },
      { title: 'Devotion to the Mother', text: 'His central practice was devotion to Kali, whom he addressed as a mother and not as a distant or frightening deity. For him, the Mother’s power was present in the world, in the temple image and in every person. This tradition of loving, even playful, devotion is typical of Bengali Shakta worship.' },
      { title: 'Many paths, one goal', text: 'He is known for the saying, often rendered as “as many faiths, so many paths”, and for using the image of different ponds from which people draw the same water under different names. He is reported to have practised Hindu, Muslim and Christian forms of worship, and to have concluded that each leads to the same reality. Scholars note that this harmony was seen from within a Hindu framework, and that his own devotional life remained centred on the Hindu goddess.' },
      { title: 'God in the human being', text: 'He taught that the divine is present in people, and he treated the worship of persons, including his wife, as worship of the divine. Later followers drew from this the idea of serving humanity as serving God, a theme that Vivekananda developed more than Ramakrishna himself did.' },
      { title: 'Warnings about worldly attachment', text: 'Ramakrishna often warned his visitors against being caught by “woman and gold”, a phrase in which he meant lust and the pursuit of money. Modern readers sometimes find this language harsh, and scholars debate how it should be read. For married householders he advised living in the world while keeping the mind on God.' },
    ],
    principles: [
      'Seek what you believe in through direct experience, not only through argument.',
      'Approach other people’s faith with respect and curiosity.',
      'Sincerity matters more than learning.',
      'Live in the world without letting it own you.',
      'See something sacred in each person you meet.',
    ],
    practice: [
      'Read a religious or philosophical text from a tradition not your own, as a guest and not as a critic.',
      'Spend a few minutes each day in silence, attending to a single thought or phrase.',
      'Ask yourself, in an ordinary dispute, what the other person is trying to reach and whether it is close to your own aim.',
    ],
    facts: [
      'Ramakrishna wrote nothing. Our knowledge of his words comes mainly from the diary of his disciple Mahendranath Gupta, known as “M”, published in Bengali as the Kathamrita, and its English version by Swami Nikhilananda, The Gospel of Sri Ramakrishna (1942).',
      'The Dakshineswar temple was built by Rani Rashmoni, who came from a lower caste, and some local Brahmins objected to serving there.',
      'He met the young Narendranath Datta, later Swami Vivekananda, in 1881, and Vivekananda became his best-known disciple.',
      'Sarada Devi, born in 1853, lived until 1920 and is revered by his followers as the Holy Mother.',
      'The Ramakrishna Mission was founded by Vivekananda in 1897, and the Ramakrishna Math’s headquarters are at Belur, near Calcutta.',
      'The Oxford scholar Max Müller wrote a short biography, Ramakrishna: His Life and Sayings, in 1898.',
    ],
    myths: [
      { myth: 'Ramakrishna was an unlettered rustic who knew nothing of the modern world.', reality: 'He had little schooling, but at Dakshineswar he talked with Calcutta college graduates, reformers and critics, and followed new ideas. The picture of an innocent village saint is partly a creation of his followers.' },
      { myth: 'Ramakrishna taught the same message that Vivekananda later preached.', reality: 'Vivekananda was a gifted organiser who combined Ramakrishna’s teachings with Advaita Vedanta, nationalism and social service, and he presented them to Western audiences in new language. Historians distinguish the devotional Ramakrishna of the Gospel from the activist Vivekananda of the Mission, and recognise that the movement’s image of its founder was shaped by his disciples.' },
      { myth: 'Everything recorded about his visions and miracles is established fact.', reality: 'Most accounts come from devoted followers, many written decades later, and they follow the pattern of saints’ lives. Some scholars read his trances in psychological terms, and works such as Jeffrey Kripal’s Kali’s Child (1995), a controversial reading, set off a heated debate with the Ramakrishna Mission. A fair reading keeps both the sources’ evidence and their devotion in view.' },
    ],
    works: [
      { title: 'No writings by Ramakrishna', note: 'He taught orally in Bengali, using parables and songs.' },
      { title: 'Sri Sri Ramakrishna Kathamrita', note: 'Mahendranath Gupta’s Bengali record of conversations from 1882–86, published from 1902.' },
      { title: 'The Gospel of Sri Ramakrishna (1942)', note: 'Swami Nikhilananda’s English translation of the Kathamrita.' },
      { title: 'Ramakrishna: His Life and Sayings (1898)', note: 'Max Müller’s account for Western readers.' },
      { title: 'Kali’s Child (1995)', note: 'Jeffrey Kripal’s critical study, and the controversy that followed it.' },
    ],
    legacy: [
      'After his death his disciples, led by Vivekananda, created the Ramakrishna Math and Mission, which runs schools, hospitals and relief work in India and abroad. Vivekananda’s appearance at the Parliament of the World’s Religions in Chicago in 1893 made his teacher’s name known outside India. Through them, Ramakrishna became one of the most widely known figures of modern Hinduism.',
      'His idea that the world’s religions are different roads to the same goal has been influential in modern interfaith thinking, and it has also been criticised for presuming that all faiths agree on what the goal is. Scholars today separate the Ramakrishna of the sources from the image his movement created, and treat both as part of his legacy.',
    ],
  },
  {
    slug: 'charles-sanders-peirce',
    order: 1839,
    dates: '1839 – 1914',
    place: 'Cambridge, Massachusetts, and Milford, Pennsylvania, USA',
    era: '19th Century',
    tradition: 'Pragmatism',
    tagline: 'The brilliant, difficult American logician who founded pragmatism and the study of signs, and died in near poverty.',
    who: [
      'Charles Sanders Peirce (pronounced “purse”) was born in Cambridge, Massachusetts, in 1839, the son of Benjamin Peirce, a leading Harvard mathematician. His father trained him early in mathematics, logic and scientific habits of mind. He studied at Harvard and took a degree in chemistry, and in 1859 began work for the United States Coast Survey, where he stayed, on and off, until 1891. His work included precise measurements of gravity with pendulums and research in astronomy and geodesy. His book Photometric Researches (1878) was the only full-length book he published in his lifetime.',
      'He was a gifted but difficult man who suffered from severe nerve pain, and he had few allies in the academic world. He lectured on logic at Johns Hopkins University from 1879, but was dismissed in January 1884. The reasons are debated: his irregular personal life, after his first wife left him and before his divorce, seems to have played a part, as did the hostility of influential figures. He never held another university post. In 1891 he left the Coast Survey, at the request of its superintendent.',
      'Peirce and his second wife, Juliette, moved to a house at Milford, Pennsylvania, which he called Arisbe. There he lived in deep poverty, writing book reviews and dictionary entries for money, while producing thousands of pages on logic, mathematics, philosophy and the study of signs. William James helped by arranging lectures and gathering funds. Peirce died there of cancer in 1914, leaving about 1,650 unpublished manuscripts.',
    ],
    context: [
      'Nineteenth-century America was building its own scientific institutions, and Peirce belonged to the first professional generation of American scientists. In Cambridge, in the early 1870s, he took part in an informal discussion group, the Metaphysical Club, which included William James, Oliver Wendell Holmes Jr. and Chauncey Wright. The members were reading Darwin and asking what ideas of truth and knowledge could survive in a world of change and uncertainty.',
      'Peirce thought as a laboratory scientist and as a logician. He wanted philosophy to follow the methods of the sciences, with clear definitions, testable claims and a community of investigators who correct one another. Unlike many philosophers of his time, he was at home in the new mathematical logic and in the practical problem of measurement.',
    ],
    ideas: [
      { title: 'The pragmatic maxim', text: 'In the 1878 essay How to Make Our Ideas Clear, Peirce proposed that to understand what a concept means, we should consider the practical effects we would expect if it applied. Our idea of a thing, he said, is just our idea of those effects. Calling a diamond “hard” means that it would resist scratching, and nothing more is needed. William James later popularised pragmatism, and Peirce, who felt James had bent it toward personal belief, renamed his version “pragmaticism” in 1905.' },
      { title: 'Signs: icon, index, symbol', text: 'Peirce built a general theory of signs, called semiotics. A sign stands for something (its object) to someone, who forms a further idea (its interpretant). He sorted signs into three kinds: an icon resembles what it stands for, like a portrait or a diagram; an index is connected to it, like smoke to fire or a weathervane to the wind; and a symbol works by habit or convention, like words. His system is still used in linguistics, media studies and computing.' },
      { title: 'Abduction', text: 'Besides deduction and induction, Peirce described a third kind of reasoning, abduction, the creative step of proposing an explanation for a surprising fact. It is a guess, but not a random one: it gives us a hypothesis that can then be tested by deduction and induction. He thought it was how new ideas enter science.' },
      { title: 'Fallibilism and the community of inquiry', text: 'Peirce held that no belief is beyond possible revision, and that we should never “block the way of inquiry”. In his view truth is what a community of honest investigators would eventually agree on if inquiry continued without end. He also described four ways of fixing belief, by stubbornness, authority, convenient reasoning or science, and argued that only science corrects itself.' },
      { title: 'Logic and the mathematics of thought', text: 'Peirce made important contributions to the logic of relations and to the use of quantifiers, and he invented a diagrammatic system called existential graphs. In 1886 he observed that logical operations could be carried out by electrical switching circuits, an idea that anticipated the design of computers.' },
    ],
    principles: [
      'Do not block the way of inquiry.',
      'Treat your own beliefs as open to correction.',
      'To clarify an idea, ask what difference it would make in practice.',
      'Use hunches, but test them.',
      'Truth is a shared enterprise, which no single person completes.',
    ],
    practice: [
      'When a debate seems endless, ask what observable difference the two positions would make, and if none, drop the question.',
      'When you form a theory about something surprising, write down what else would have to be true, and go and check.',
      'Read signs carefully: ask whether a thing resembles, points to, or merely stands for its object by convention.',
    ],
    facts: [
      'His 1877–78 papers The Fixation of Belief and How to Make Our Ideas Clear are the starting point of pragmatism.',
      'He was among the first to suggest using the wavelength of light as a natural standard of length.',
      'He earned money by writing hundreds of definitions for the Century Dictionary, and by reviews, many of them for The Nation.',
      'His collected writings were first published in eight volumes, as the Collected Papers, between 1931 and 1958, and a fuller chronological edition is still being prepared.',
      'He settled in Milford in 1887, buying land and remodelling an older farmhouse, but he could rarely afford to keep it heated or repaired.',
      'He proposed that signs, thoughts and nature itself are connected by habit and continuity, a view he called synechism.',
    ],
    myths: [
      { myth: 'Peirce and William James held the same pragmatism.', reality: 'James credited Peirce but gave pragmatism a broader, more personal meaning, and Peirce disliked the change. His own version stresses the logic of meaning and scientific inquiry, which is why he adopted the new name “pragmaticism”.' },
      { myth: 'Peirce was ignored because his ideas were minor.', reality: 'He was neglected in his lifetime, partly because of his temperament, his scandal and his dense, unfinished writing, and partly because many of his ideas were far ahead of his time. Much of what we know of him has been recovered only from his manuscripts since his death.' },
    ],
    works: [
      { title: 'The Fixation of Belief (1877) and How to Make Our Ideas Clear (1878)', note: 'The founding essays of pragmatism, published in Popular Science Monthly.' },
      { title: 'Photometric Researches (1878)', note: 'His only book published in his lifetime, a scientific study of starlight.' },
      { title: 'Collected Papers of Charles Sanders Peirce (1931–58)', note: 'Eight volumes, edited by Hartshorne, Weiss and Burks.' },
      { title: 'Writings of Charles S. Peirce: A Chronological Edition', note: 'A fuller scholarly edition, published from 1982 by the Peirce Edition Project.' },
      { title: 'The Essential Peirce (1992, 1998)', note: 'A two-volume selection that is a good starting point for readers.' },
    ],
    legacy: [
      'During his life Peirce was nearly unknown outside a small circle. James, Josiah Royce and John Dewey carried pragmatism forward, and in the twentieth century logicians, philosophers and scientists rediscovered his work. Today he is regarded by many as the most original and versatile American philosopher, and as a major figure in logic, scientific method and the theory of signs.',
      'His ideas have shaped fields far from philosophy: the study of how language and images carry meaning, the logic of scientific discovery, statistics, and aspects of artificial intelligence, where abduction is used to describe reasoning to the best explanation. His life is also a cautionary tale about how talent, ill health, poverty and prejudice can leave a great thinker without institutional support.',
    ],
  },
]
