import type { Profile } from './types'

export const MORE_20: Profile[] = [
  {
    slug: 'paulo-freire',
    order: 1921,
    dates: '1921 – 1997',
    place: 'Recife, Brazil; exile in Chile, the United States and Switzerland; São Paulo',
    era: '20th Century',
    tradition: 'Critical pedagogy',
    tagline: 'The Brazilian educator who taught that learning to read the word means learning to read the world, and that teaching is never neutral.',
    who: [
      'Paulo Freire was born on 19 September 1921 in Recife, in the poor north-east of Brazil. His family was middle class, but the Great Depression pushed it into hardship, and Freire later wrote that he knew hunger as a child and that it disturbed his schooling. The experience gave him a lasting sense of how poverty can shut a child out of learning. He studied law at the University of Recife, but he turned to education, teaching Portuguese and working with adult learners.',
      'In 1946 he became director of the Department of Education and Culture in the state of Pernambuco, and in the early 1960s he was running adult-literacy projects among the rural poor. At that time many Brazilian adults could not read, and illiterate citizens were not allowed to vote. In 1963, in the town of Angicos in Rio Grande do Norte, a team under his guidance taught about 300 adults to read and write. Accounts of how long it took vary, but the “forty hours of Angicos” became famous, and the government of President João Goulart planned a national literacy programme based on his approach.',
      'That plan ended with the military coup of 1964. Freire was arrested as a subversive and held for about 70 days, then went into exile, first briefly in Bolivia and then for about five years in Chile, where he wrote Pedagogy of the Oppressed. He later taught at Harvard, worked for the World Council of Churches in Geneva, and advised newly independent former Portuguese colonies such as Guinea-Bissau. He returned to Brazil in 1979 for a visit and settled there in 1980. He joined the Workers’ Party, taught at universities in São Paulo, and from 1989 served as the city’s secretary of education. He died in São Paulo on 2 May 1997.',
    ],
    context: [
      'Brazil in the early 1960s was a country of great inequality. In the north-east, many rural families lived on estates owned by a few landlords, and a large share of adults could not read. Social movements, Catholic activists and student groups were organising “popular education” among the poor, and many saw literacy as a path to political voice. Freire belonged to this world, and the Catholic social teaching of his youth, together with Marxist and existentialist thought, shaped how he understood it.',
      'The military coup of March 1964 overthrew Goulart and began about two decades of military rule. Ideas that had seemed like education were treated as a danger to the order, which is why a literacy teacher was jailed. In exile, Freire’s thinking reached a worldwide audience in the era of decolonisation, student movements and liberation theology, and Pedagogy of the Oppressed, first published in Portuguese in 1968 and in Spanish and English in 1970, became one of the most widely read books on education ever written.',
    ],
    ideas: [
      { title: 'The “banking” model of education', text: 'Freire described a common style of teaching in which the teacher “deposits” facts into students, who are expected to receive, memorise and repeat them. In this picture the teacher knows everything and the students know nothing. He argued that such teaching trains people to adapt to the world as it is, rather than to question it, and that it treats learners as containers and not as thinkers.' },
      { title: 'Problem-posing education and dialogue', text: 'As an alternative he proposed problem-posing education, in which teachers and students investigate real problems together. Dialogue is the heart of it: the teacher also learns, and the students are co-investigators. Freire insisted that dialogue is not just a technique but an act of respect, grounded in love for the world and for people, humility and trust.' },
      { title: 'Conscientization', text: 'The word, from the Portuguese conscientização, means developing a critical awareness of the social forces that shape one’s life, and the readiness to act on them. People who have been taught to see their poverty as fate learn to see it as a situation made by history, and therefore open to change. Freire stressed that this awareness must lead to action and reflection together, which he called praxis.' },
      { title: 'Reading the word and the world', text: 'In his literacy work, adults learned to read using words drawn from their own lives, such as words for the land, work and housing, which were discussed before they were spelled out. Reading was not only decoding letters. It was a way to name one’s experience and see it afresh. This is the idea behind his phrase “reading the word and the world”.' },
      { title: 'Education is never neutral', text: 'Freire held that every school either helps people adapt to existing arrangements or helps them examine and transform them, and that claims of neutrality hide a choice. He called for teachers to be honest about their own commitments. Yet he also insisted that a teacher must not manipulate: the aim is to help students think for themselves, not to impose conclusions.' },
    ],
    principles: [
      'Start from the learner’s real life and words.',
      'Teach by dialogue, not by deposit.',
      'Respect what people already know; everyone knows something and no one knows everything.',
      'Join reflection to action, and neither alone is enough.',
      'Be honest that teaching is never neutral, and never use it to manipulate.',
    ],
    practice: [
      'When you explain something, ask one question first to find out what the other person already knows, and build on that.',
      'In a group, turn a lecture into a discussion about a concrete problem the participants actually face.',
      'Ask of any lesson or institution you belong to who benefits from the way things are done, and whether the people affected have a voice.',
    ],
    facts: [
      'Pedagogy of the Oppressed is one of the most cited books in the humanities and social sciences. A 2016 analysis of Google Scholar citations ranked it third, after works by Thomas Kuhn and Everett Rogers.',
      'Freire wrote Pedagogy of the Oppressed while living in Chile, and it was first published in Portuguese in 1968. The English edition appeared in 1970, in a translation by Myra Bergman Ramos.',
      'He was held for about 70 days after the 1964 coup and then left Brazil. He did not live there again until 1980, after an amnesty allowed exiles to return.',
      'His method used “cultural circles”, discussion groups in which adults talked about images and words from their daily lives, in place of a traditional classroom.',
      'In 1989 the São Paulo city government, led by the Workers’ Party, made him its secretary of education, giving him charge of a large school system.',
      'Brazil has formally honoured him as the patron of Brazilian education, a status that is also contested by some political critics.',
    ],
    myths: [
      { myth: 'Freire thought teachers should have no authority and that lectures are always wrong.', reality: 'In later books he wrote that dialogue does not mean the teacher disappears. Teachers have knowledge, direct the process and carry responsibility. What he criticised was authoritarian teaching that silences students, not structure or expertise.' },
      { myth: 'His method was just a quick trick for teaching reading.', reality: 'The literacy work used themes from learners’ lives and was meant to build critical awareness as well as skill. Freire himself said that methods cannot simply be copied from one place to another, and that they must be reinvented in each context.' },
    ],
    works: [
      { title: 'Education as the Practice of Freedom (1967)', note: 'His first major book, drawing on the literacy work in Brazil and written around the time of his exile.' },
      { title: 'Pedagogy of the Oppressed (1968; English 1970)', note: 'His best-known work, setting out the banking model, dialogue and conscientization.' },
      { title: 'Pedagogy in Process: The Letters to Guinea-Bissau (1978)', note: 'Reflections on his advisory work on literacy and education in a newly independent African country.' },
      { title: 'Pedagogy of Hope (1992)', note: 'A look back at Pedagogy of the Oppressed, its critics and the experiences behind it.' },
      { title: 'Pedagogy of Freedom (1996)', note: 'One of his last books, on the ethics and practice of teaching.' },
    ],
    legacy: [
      'Freire’s ideas spread into adult education, community development, nursing and health education, theology and teacher training in many countries, and they gave rise to the field called critical pedagogy. Educators in the United States, such as Henry Giroux and bell hooks, took up and extended his work, and the Paulo Freire Institute in São Paulo was founded in 1991 to keep his work alive. His call to listen first and to treat learners as partners is now widely repeated in education.',
      'His ideas also remain debated. Some critics argue that his language is abstract, that his debt to Marxism makes classroom work political, or that his thinking underplays teachers’ expertise and the need for solid basic skills. In Brazil, Freire has been both honoured and attacked in recent political arguments about schools. Whatever one’s view, his central question, whom education serves and who gets to speak in it, is still at the centre of discussions about teaching.',
    ],
  },
  {
    slug: 'nodar-dumbadze',
    order: 1928,
    dates: '1928 – 1984',
    place: 'Tbilisi and western Georgia (Guria), Soviet Georgia',
    era: '20th Century',
    tradition: 'Georgian literature',
    tagline: 'A Soviet-era Georgian storyteller whose warm, funny and heartbreaking novels made him one of the best-loved writers in the country.',
    who: [
      'Nodar Dumbadze (ნოდარ დუმბაძე) was born in Tbilisi on 14 July 1928. His childhood was darkened by the Stalinist terror: according to Georgian and Russian biographies, his father, Vladimir, a local Communist Party official, was arrested in 1937 and shot, and his mother, Anna, was arrested and sent away, returning only in 1946. The boy grew up with relatives in western Georgia, in the countryside of Guria. He finished school in the village of Khidistavi in 1945, and these village years, with their wartime hardships and their gallery of unforgettable elders, later became the material of his best-known books.',
      'He graduated from the economics faculty of Tbilisi State University in 1950 and worked for a time as a laboratory assistant. At the same time he began publishing humorous stories in the Georgian press, and in 1957 he left his job to write full time. His early comic sketches were followed by the novels that made him famous: “Me, Grandma, Iliko and Illarion” (1960), which brought him a wide readership, and “I See the Sun” (1962). He also edited the satirical magazine “Niangi” from 1967 to 1972 and wrote for the cinema.',
      'From the 1970s he held public offices as well: he was a secretary of the Union of Georgian Writers from 1972, a deputy in the Supreme Soviet of the Georgian SSR and later of the USSR, and from 1981 chairman of the Georgian Writers’ Union. He received the Lenin Komsomol Prize (1966), the Shota Rustaveli State Prize of the Georgian SSR (1975) and the Lenin Prize (1980). He died in Tbilisi in September 1984, aged 56. Georgian and Russian sources give 14 September, while some other sources say 4 September, and Russian-language sources report that he died of a heart attack.',
    ],
    context: [
      'Dumbadze wrote under Soviet rule, when literature in Georgia, as elsewhere in the USSR, was published through state-controlled houses and journals and expected to fit Party guidelines. The death of Stalin in 1953 and the cultural “Thaw” that followed opened more room for personal and lyrical writing. Dumbadze’s family had suffered in the purges, and yet he became an official figure of the system, holding posts in the Writers’ Union and the legislature, a mix that is part of what makes his career hard to sum up in a single word.',
      'Georgian writers also had a special duty in this setting. The Georgian language and its literature, among the oldest in the Caucasus, were a central part of national identity, and in April 1978 mass demonstrations in Tbilisi defended the status of Georgian as the state language of the republic. In such a climate, a prose writer who could reach readers of every age and background with simple, humane stories had a place in public life that was close to that of a national storyteller.',
    ],
    ideas: [
      { title: 'Humanity above ideology', text: 'Dumbadze’s fiction is built around kindness, loyalty, conscience and the dignity of ordinary people, and it rarely preaches Party doctrine. Critics and encyclopedias describe his central faith as a faith in the human being. His characters, from peasants to prisoners, are shown with sympathy even when they fail.' },
      { title: 'Laughter and sorrow together', text: 'His prose is known for combining humour with melancholy and for turning from laughter to tears within a page. In his village novels comic scenes sit beside the grief of war and loss, and the comedy makes the sorrow easier to bear and more truthful. This mixture is a big reason his books are loved.' },
      { title: 'The child’s and the village’s eye', text: 'Many of his best-known books are drawn from his own youth and tell of village life through the eyes of a young narrator. The elders, the neighbours and the grandmother become moral teachers, and ordinary village life carries a quiet wisdom. This turn to memory and home gave Georgian readers a mirror of their own world.' },
      { title: 'Good, evil and conscience', text: 'In his later novels, such as “White Flags” (თეთრი დროშები, 1973) and “The Law of Eternity” (მარადისობის კანონი, 1978), he took up moral questions more directly: guilt and forgiveness, the pain of a person who has done wrong and the struggle between good and evil in the face of death. “The Law of Eternity” was his last major novel and won the Lenin Prize in 1980.' },
      { title: 'Compassion and its cost', text: 'His short novel “Kukaracha” (1981) tells of a decent man whose kindness toward a wrongdoer ends in tragedy, a story that asks whether compassion is naive. Dumbadze leaves the reader with the question and still comes down on the side of mercy, which is typical of how he treats his characters.' },
    ],
    principles: [
      'Look at people with sympathy, including those who have failed.',
      'Keep humour alive even in hard times; it makes sorrow bearable.',
      'Honour the old and the ordinary: wisdom often lives in small villages and plain speech.',
      'Let conscience, not fear, decide what you do.',
      'Choose mercy, even when it carries a risk.',
    ],
    practice: [
      'Write down a story about an older person who shaped you, and notice the small details that made them memorable.',
      'When you have to deliver bad news or tell a hard story, look for the honest bit of humour in it, without making light of the pain.',
      'In a conflict, ask what the other person might be suffering, before deciding what they deserve.',
    ],
    facts: [
      'He was born in Tbilisi in 1928, and his father was shot in the repressions of 1937. His mother was released from exile in 1946.',
      'Sources disagree on the date of his death: Georgian and Russian Wikipedia give 14 September 1984, while English Wikipedia and the National Library of Georgia’s catalogue give 4 September.',
      '“Me, Grandma, Iliko and Illarion” was adapted for the screen in 1963 by the director Tengiz Abuladze, and “Kukaracha” was filmed in 1982 by Siko and Keti Dolidze.',
      'In 1982 he took the initiative in creating Mziuri Park, a park and children’s city in Tbilisi. He was first buried there in 1984, and his remains were moved to the Mtatsminda Pantheon in 2009.',
      'His books have been translated into Russian and many other languages, and several were adapted for the stage and for film.',
      'From 1981 until his death he led the Union of Georgian Writers.',
    ],
    myths: [
      { myth: 'Dumbadze was a dissident who was persecuted by the Soviet state.', reality: 'His family suffered in the terror of 1937, but as a writer he was honoured by the system: he was a deputy in the Supreme Soviet, a leader of the Writers’ Union and a winner of the Lenin Prize. His books were popular because of their humanity, not because they were openly anti-Soviet.' },
      { myth: 'He was only a humorist.', reality: 'He began with comic stories, but his best-known novels mix comedy with grief, and his later works, such as “The Law of Eternity” and “Kukaracha”, are serious, even tragic, meditations on conscience and mercy.' },
    ],
    works: [
      { title: 'მე, ბებია, ილიკო და ილარიონი (Me, Grandma, Iliko and Illarion, 1960)', note: 'The novel that made his name, drawn from village life in wartime Georgia and filmed in 1963.' },
      { title: 'მე ვხედავ მზეს (I See the Sun, 1962)', note: 'A second novel of youth and village life, among his most widely read works.' },
      { title: 'მზიანი ღამე (The Sunny Night, 1967) and ნუ გეშინია, დედა! (Don’t Be Afraid, Mother!, 1971)', note: 'Two later novels. The second draws on the life of Soviet border guards, and its themes are friendship, loss and unreturned love.' },
      { title: 'თეთრი დროშები (White Flags, 1973)', note: 'A novel about guilt, punishment and the possibility of forgiveness.' },
      { title: 'მარადისობის კანონი (The Law of Eternity, 1978) and კუკარაჩა (Kukaracha, 1981)', note: 'His late work: the Lenin Prize novel on good and evil, and a short novel about compassion and its cost.' },
    ],
    legacy: [
      'Dumbadze remains one of the most popular Georgian prose writers of the twentieth century. Most of his major works were adapted for the stage and the screen, and he is described in Georgian and English reference works as one of the best-known and most popular Georgian prose writers of his time. His blend of simplicity, lyricism, humour and melancholy still defines what many readers expect from a Georgian novel of village life.',
      'His early death at the age of 56 ended his career at the height of his fame. The 2009 reburial in the Mtatsminda Pantheon, the resting place of many national cultural figures, marked his place in Georgian memory. He was at once an official laureate of the Soviet system and a deeply popular, unpolemical humanist, and readers will judge for themselves how those two roles fit together.',
    ],
  },
  {
    slug: 'jacques-derrida',
    order: 1930,
    dates: '1930 – 2004',
    place: 'Algiers; Paris, France',
    era: '20th Century',
    tradition: 'Deconstruction',
    tagline: 'The French philosopher who showed that texts, and the concepts we think with, rarely mean what they claim to mean.',
    who: [
      'Jacques Derrida was born on 15 July 1930 in El Biar, a suburb of Algiers, then part of French Algeria, into a Sephardic Jewish family. In 1940 the Vichy regime stripped Algerian Jews of French citizenship, and in 1942 he was expelled from his lycée under antisemitic quotas. He later wrote about the uneasiness of belonging to a language and a country that had treated him as an outsider, in works such as “Monolingualism of the Other”. At 19 he moved to France to prepare for the competitive entrance exams to the École Normale Supérieure in Paris.',
      'He studied there, wrote on the phenomenology of Edmund Husserl, and taught at the École Normale Supérieure from 1964 to 1984 and then at the École des Hautes Études en Sciences Sociales. In 1967 he published three books in one year, Writing and Difference, Speech and Phenomena and Of Grammatology, which established him as a leading voice in French thought. He co-founded the Collège International de Philosophie in Paris in 1983, and he held regular visiting posts at American universities such as Yale and the University of California, Irvine.',
      'In later decades he turned more openly to ethics and politics, writing on forgiveness, hospitality, friendship, justice and the death penalty. He also became a public figure: in 1981 he was arrested in Prague on drug charges, which his supporters said were fabricated, after helping Czech dissidents, and he was freed after French intervention. He died in Paris on 9 October 2004, of pancreatic cancer, aged 74.',
    ],
    context: [
      'Derrida emerged in the France of the 1960s, when philosophers were questioning the confident systems of the earlier generation. Phenomenology, existentialism, structuralism and the linguistics of Ferdinand de Saussure were all in play. Structuralists looked for fixed systems of signs that could explain language, myth and society, and Derrida asked whether any such system could ever close itself off from what it excludes.',
      'He also drew on Nietzsche, Heidegger and Freud, who had already challenged the idea that reason or the conscious self is a solid foundation. The result was “deconstruction”, a way of reading the great texts of philosophy and literature that looked closely at their hidden tensions. It spread quickly to literary studies, architecture, law and theology in the English-speaking world, where it was often simplified or misunderstood.',
    ],
    ideas: [
      { title: 'Deconstruction', text: 'Deconstruction is a way of reading. It looks at the oppositions that structure our thinking, such as speech and writing, nature and culture, presence and absence, and shows that the first term is usually treated as primary and the second as secondary or a lesser copy. Close reading shows that the privileged term depends on the one it excludes. Derrida did not call this a method or destruction, but an attention to how texts undo their own claims.' },
      { title: 'Logocentrism', text: 'Derrida used this word for the long tradition in Western philosophy that treats living speech, the logos, as the pure carrier of meaning and sees writing as a derived and second-rate copy. In Of Grammatology (1967) he argued that this prejudice shaped thinkers from Plato to Rousseau and Saussure, and that writing, understood broadly as a system of marks that can be repeated in the absence of the speaker, is a condition of language as such.' },
      { title: 'Différance', text: 'This coined word, spelled with an a, plays on the French verbs for “to differ” and “to defer”. Meaning, Derrida said, does not sit in a sign by itself. It arises from differences between signs, and it is always postponed, because each sign leads to others. The spelling change cannot be heard in French speech, only seen in writing, which was part of the point.' },
      { title: 'There is no outside-text', text: 'Of Grammatology contains the often-quoted line “il n’y a pas de hors-texte”. Derrida later explained that it means there is nothing outside context, and that we never meet reality except through frameworks of interpretation. It does not mean that nothing exists beyond books.' },
      { title: 'Ethics, hospitality and justice', text: 'In his later work he argued that justice, forgiveness and hospitality are ideals that can never be fully captured by laws or rules, yet they call on us to act. He described them as “impossible” in the sense that they exceed any existing arrangement, and that is exactly why they keep pushing us to improve it.' },
    ],
    principles: [
      'Read slowly, and notice what a text leaves out as well as what it says.',
      'Be suspicious of neat oppositions, since the second term is often doing hidden work.',
      'Attend to the words you use and the history they carry.',
      'Meaning depends on context, so ask in which context a claim is being made.',
      'Keep your ideals of justice and hospitality higher than any law or rule that tries to contain them.',
    ],
    practice: [
      'Take a text you know well and ask which two terms it sets against each other and which one it treats as the norm.',
      'When you argue about a word such as “natural”, “normal” or “freedom”, ask what the word excludes and who benefits from the exclusion.',
      'When you read a rule or policy, ask what situation it fails to anticipate, and how you would handle the person it does not fit.',
    ],
    facts: [
      'In 1992 Cambridge University proposed an honorary degree for him. A group of philosophers, led by Barry Smith and including W. V. Quine, signed a letter in The Times objecting, and the university’s senior members voted 336 to 204 to award it.',
      'After the death of his friend and Yale colleague Paul de Man in 1983, wartime newspaper articles that de Man had written in Belgium came to light in 1987. They included antisemitic writing. Derrida responded in 1988 with the essay “Like the Sound of the Sea Deep Within a Shell: Paul de Man’s War”, which critics accused of excusing de Man.',
      'He published Of Grammatology, Writing and Difference and Speech and Phenomena in the same year, 1967.',
      'His name for his own approach, “deconstruction”, came from his reworking of Heidegger’s term for dismantling the history of philosophy.',
      'Specters of Marx (French 1993, English 1994) was his response to the apparent victory of capitalism after 1989. It argues for a spirit of Marx’s critique without a Marxist system.',
      'In 1983 he helped found the Collège International de Philosophie and was its first president.',
    ],
    myths: [
      { myth: 'Deconstruction means destroying texts, or saying that anything can mean anything.', reality: 'Derrida insisted that deconstruction is careful reading, not demolition, and that it requires respect for the text. He argued that meaning is never fixed absolutely, but that does not make interpretation arbitrary, and he held that readers can be right or wrong about a text.' },
      { myth: '“There is nothing outside the text” means that the real world does not exist.', reality: 'Derrida rejected this reading. He said that he meant that there is no experience outside a context of interpretation, and that the “text” includes the wider web of relations, history and institutions. He never denied the existence of the world, suffering or death.' },
      { myth: 'Derrida was a relativist who did not believe in truth or ethics.', reality: 'His late writings on justice, forgiveness and hospitality are strongly ethical. He argued that ideals such as justice cannot be reduced to existing laws, and that this is why we must keep working for them. Critics still disagree about whether his philosophy supports or weakens that commitment.' },
    ],
    works: [
      { title: 'Of Grammatology (1967)', note: 'His most famous book, criticising the privileging of speech over writing and reading Rousseau, Saussure and others.' },
      { title: 'Writing and Difference (1967) and Speech and Phenomena (1967)', note: 'Two books from the same year, including essays on Husserl, Freud, Foucault and Levinas.' },
      { title: 'Margins of Philosophy (1972)', note: 'A collection including the essay “Différance”, first presented in 1968.' },
      { title: 'Specters of Marx (1993)', note: 'On Marx, ghosts, and the responsibility toward the past and the future after the Cold War.' },
      { title: 'Monolingualism of the Other (1996)', note: 'A short, personal book on language, identity and his Algerian-Jewish background.' },
    ],
    legacy: [
      'Deconstruction influenced literary theory in the United States and Britain, notably at Yale, and spread into architecture, legal theory, theology, feminism, postcolonial studies and gender studies. Derrida’s emphasis on the exclusions built into concepts proved useful for scholars studying power, language and identity, and his late writings on justice, hospitality and forgiveness influenced debates in politics and ethics.',
      'He remains a controversial figure. Analytic philosophers, such as John Searle in a well-known exchange, accused him of obscurity, while others, including Jürgen Habermas, criticised what they saw as the weakening of reason. Admirers see in him a rigorous reader who showed how much hides in familiar concepts. Both groups agree that few philosophers of the twentieth century changed the way so many fields read their own texts.',
    ],
  },
  {
    slug: 'chinua-achebe',
    order: 1930,
    dates: '1930 – 2013',
    place: 'Ogidi and Nsukka, Nigeria; later the United States',
    era: '20th Century',
    tradition: 'African literature',
    tagline: 'The Nigerian novelist who told the story of colonialism from the African side and changed how the world reads Africa.',
    who: [
      'Chinua Achebe was born Albert Chinụalụmọgụ Achebe on 16 November 1930 in Ogidi, an Igbo town in south-eastern Nigeria, then a British colony. His father taught and served as a catechist for a Christian mission, so he grew up between the church and the older Igbo traditions of his village, the stories, proverbs and masquerades that he later put into his fiction. He studied at University College, Ibadan, and from 1954 worked for the Nigerian Broadcasting Service.',
      'His first novel, Things Fall Apart, was published in London in 1958 and made him famous. He followed it with No Longer at Ease (1960), Arrow of God (1964) and A Man of the People (1966). He also became the founding editor of Heinemann’s African Writers Series, which brought many African authors into print. When the Biafran secession of May 1967 led to a civil war with Nigeria, Achebe, an Igbo, supported Biafra and acted as an envoy for it abroad. The war, which ended in 1970 with Biafra’s defeat and enormous civilian suffering, marked him deeply.',
      'After the war he taught at the University of Nigeria in Nsukka, and in 1972 he began a long academic career in the United States. In March 1990 a car accident in Nigeria left him paralysed from the waist down, and he lived afterwards in the United States, teaching at Bard College and later at Brown University. He wrote essays, poetry, stories and a late history-memoir, There Was a Country (2012). He died in Boston on 21 March 2013.',
    ],
    context: [
      'Achebe grew up during the high point of British rule in Nigeria, which became independent in 1960. Colonial schooling taught him to see Africa through European eyes, and the books he read at school often portrayed Africans as savages or as background figures. He later said that his fiction was a response to those stories, an attempt to show Igbo society from the inside, with its own law, religion, humour and flaws.',
      'The independence era brought hope, then disappointment. Corruption and ethnic rivalry shaped Nigerian politics, and a military coup in January 1966 was followed by a second coup and then by violence against Igbo people. In 1967 the south-east declared the independent state of Biafra, and a war followed. Achebe’s work moves with this history, from the encounter with colonialism in Things Fall Apart to the disillusionment of the new nation in A Man of the People.',
    ],
    ideas: [
      { title: 'Telling the story from the inside', text: 'Things Fall Apart shows a pre-colonial Igbo community through the life of Okonkwo, a proud wrestler and farmer, before and after the arrival of missionaries and colonial administrators. The book does not idealise either side. It presents Igbo society as complex, with its own justice, and also shows its cruelties, and it ends with a colonial official who plans to reduce the story to a paragraph in a book. Achebe said a people’s story must be told by themselves.' },
      { title: 'Oral tradition and proverbs', text: 'Achebe wrote in English, but he shaped it to carry Igbo speech. In Things Fall Apart he remarks that proverbs are the palm-oil with which words are eaten, and his characters use them constantly to argue, teach and joke. Folktales, songs and the voices of elders appear throughout his novels, and he made oral tradition a living part of the written African novel.' },
      { title: 'The responsibility of the writer', text: 'In essays such as “The Novelist as Teacher” he argued that African writers have a duty to help their people recover their dignity after colonialism, by showing that their past was not a long night of savagery. He also held that writers must criticise their own societies honestly, and A Man of the People is a sharp satire of corrupt post-independence politicians.' },
      { title: 'A critique of “Heart of Darkness”', text: 'In a 1975 lecture, “An Image of Africa”, Achebe argued that Joseph Conrad’s Heart of Darkness presents Africa as a place of backwardness against which Europe measures itself, and that the book deprives Africans of language and humanity. He called Conrad a thoroughgoing racist. The essay started a long debate about whether a work can be great and still be damaged by its racial attitudes, and it changed how the book is taught.' },
      { title: 'Leadership and failure', text: 'In The Trouble with Nigeria (1983) he argued that Nigeria’s problems were at root a failure of leadership. He turned down national honours twice, in 2004 and 2011, in protest at the state of public life in his country. Achebe’s ideas about the novel and about politics fit together: he wanted storytelling to hold people accountable.' },
    ],
    principles: [
      'Whoever tells your story shapes how you are seen, so tell it yourself.',
      'Be honest about your own community’s faults and strengths.',
      'Language can carry more than one tradition; make it carry yours.',
      'A writer, or any citizen, has a duty to speak about public life.',
      'Understand that stories can justify harm or heal it, and choose carefully which you tell.',
    ],
    practice: [
      'When you read a story about a place or a people, ask who wrote it and whose view is missing.',
      'Collect proverbs or sayings from your own family or community and write down what each one teaches.',
      'Take a work you love that has troubling attitudes in it, and practise discussing both its power and its flaws.',
    ],
    facts: [
      'The title Things Fall Apart is taken from a line in W. B. Yeats’s poem “The Second Coming”.',
      'Things Fall Apart has been translated into dozens of languages and has been widely read and taught around the world as the best-known African novel.',
      'A Man of the People ends with a military coup. It appeared in January 1966, just as a real coup took place in Nigeria, and the poet John Pepper Clark remarked that everything in the book had happened except a coup.',
      'He served as general editor of the African Writers Series from 1962, which published many African authors.',
      'He gave the lecture “An Image of Africa” at the University of Massachusetts Amherst on 18 February 1975.',
      'In 2007 he won the Man Booker International Prize for his body of work.',
    ],
    myths: [
      { myth: 'Things Fall Apart is a simple celebration of pre-colonial African life.', reality: 'Achebe shows the strengths of Igbo society, but also its harshness, including the killing of the boy Ikemefuna and the social exclusion of outcasts. Okonkwo’s own rigid ideas of manhood play a part in his downfall, so the book is a tragedy and not a postcard.' },
      { myth: 'A Man of the People was a deliberate prophecy of the January 1966 coup.', reality: 'The novel is a satire of the politics of the First Republic and appeared about the time the coup took place. Readers took it as prophecy, but it grew from the corruption that Achebe saw around him.' },
      { myth: 'His argument about Conrad was that the book should be ignored.', reality: 'His essay argued that the book’s picture of Africa should be discussed honestly, and not set aside because it is famous. The argument is about how the work treats Africans and how it is taught.' },
    ],
    works: [
      { title: 'Things Fall Apart (1958)', note: 'His first and best-known novel, about Okonkwo and the coming of colonial rule to an Igbo community.' },
      { title: 'No Longer at Ease (1960) and Arrow of God (1964)', note: 'The first follows Okonkwo’s grandson, a young civil servant in modern Lagos. The second tells of a village priest in the 1920s, caught between his people and the colonial government.' },
      { title: 'A Man of the People (1966)', note: 'A satire of corruption in a newly independent African state.' },
      { title: 'Morning Yet on Creation Day (1975) and Hopes and Impediments (1988)', note: 'Essay collections, including the Conrad lecture and “The Novelist as Teacher”.' },
      { title: 'There Was a Country (2012)', note: 'A personal history of Nigeria and the Biafran war, published late in his life.' },
    ],
    legacy: [
      'Achebe is often called the father of modern African literature in English. Writers across Africa and the diaspora, from Ngũgĩ wa Thiong’o and Wole Soyinka to Chimamanda Ngozi Adichie, have acknowledged his influence. As an editor, he opened the door to many authors, and his readiness to write about the lives of ordinary Africans changed what publishers and readers thought African fiction could be.',
      'His work also changed the debate on how stories about Africa are told and taught. The discussion about Conrad and about the “single story” of Africa continues in schools and universities, and Things Fall Apart remains a standard text in many countries. He is remembered for his fiction and for the moral clarity with which he asked who tells a people’s story and what it costs when someone else tells it.',
    ],
  },
  {
    slug: 'vaclav-havel',
    order: 1936,
    dates: '1936 – 2011',
    place: 'Prague, Czechoslovakia',
    era: '20th Century',
    tradition: 'Dissident thought',
    tagline: 'The playwright who became a dissident and then president, and who argued that ordinary people can undermine a lie by refusing to live in it.',
    who: [
      'Václav Havel was born in Prague on 5 October 1936 into a prosperous, cultured family. After the Communist takeover of 1948 the family lost much of its property, and because of his “bourgeois” background he was barred from the higher education he wanted. He worked as a laboratory assistant and then in the theatre, and from 1960 at the Theatre on the Balustrade in Prague, where he became a playwright. His absurdist comedies, among them The Garden Party (1963) and The Memorandum (1965), mocked the empty language and bureaucracy of the regime.',
      'During the Prague Spring of 1968 he spoke out for reform. After the Soviet-led invasion that August his plays were banned, and he had to take work in a brewery, an experience that fed later plays such as Audience. In 1977 he was one of the first spokespeople of Charter 77, a human-rights declaration signed by hundreds of citizens, and he was jailed briefly that year. In 1978 he wrote “The Power of the Powerless”. In 1979 he was arrested again as a leader of the Committee for the Defense of the Unjustly Prosecuted and sentenced to four and a half years. He served nearly four of them, was released in early 1983 because of serious illness, and wrote Letters to Olga to his wife from prison.',
      'In November 1989, as protests spread after a student demonstration on 17 November, Havel helped found Civic Forum and became the face of what was called the Velvet Revolution. On 29 December 1989 the federal parliament elected him president of Czechoslovakia. He resigned in July 1992, when the Slovak push toward independence made it impossible to continue, and was elected the first president of the Czech Republic in 1993, serving until February 2003. He died on 18 December 2011 at his country house in Hrádeček, aged 75.',
    ],
    context: [
      'After 1968, Czechoslovakia entered a period known as “normalisation”, in which the regime, backed by Soviet power, restored strict control and removed reformers from public life. Most people kept quiet, kept their jobs and went along. The state demanded public displays of loyalty, such as slogans and ritual votes, but did not require anyone to believe them.',
      'In this setting Havel and other dissidents, including the philosopher Jan Patočka, asked what resistance could mean when open political opposition was impossible. The trial of the rock band The Plastic People of the Universe in 1976 was one spark for Charter 77, which appealed to the human-rights promises that the government itself had signed. Havel’s answer was that politics begins in how individuals choose to live, whether or not the regime is ever challenged directly.',
    ],
    ideas: [
      { title: 'Living in truth', text: 'Havel argued that a regime built on lies is held up by ordinary people who go along with them. To “live in truth” means to refuse to take part in the ritual, to say what you think and to act accordingly, however small the act. He saw this as a moral and existential choice that can have political power.' },
      { title: 'The greengrocer', text: 'In “The Power of the Powerless” he imagines a greengrocer who puts a sign in his shop window among the onions and carrots reading “Workers of the world, unite!”. He does not believe it, but the sign shows that he is obedient and keeps him out of trouble. Havel’s point is that millions of such small gestures sustain the system. If the greengrocer one day stops, he changes the situation, and the regime has to punish him, and so shows what it is.' },
      { title: 'The post-totalitarian system', text: 'Havel used this term for a regime in which fear and ideology had become mostly ritual, and in which everyone was both victim and supporter. He thought that modern industrial societies in the West shared some troubling features, such as consumerism and a loss of personal responsibility, so his critique was not limited to communism.' },
      { title: 'Anti-political politics', text: 'He called for a politics based on moral responsibility, trust and the care of the human community, and not on power games and party machinery. This is why he thought that independent culture, free speech and civil society mattered more than seizing the state. Many have found the idea idealistic, but it guided the dissident movement.' },
      { title: 'Hope as a stance, not a forecast', text: 'In interviews he said that hope is not the belief that things will turn out well, but the conviction that something makes sense whatever the outcome. This view helped him through imprisonment and long years when change looked impossible, and it became one of his most quoted thoughts.' },
    ],
    principles: [
      'Do not say what you do not believe.',
      'Small acts of honesty matter, because systems rest on small acts of compliance.',
      'Take responsibility for the world you share, not only for your own interests.',
      'Choose what makes sense, not what is sure to win.',
      'Use power, if you ever have it, with humility.',
    ],
    practice: [
      'Notice one ritual phrase, in your workplace or community, that everyone says and no one believes, and consider quietly not repeating it.',
      'When you feel powerless, name one thing within your reach that you can do honestly, and do it.',
      'Keep in touch with people whose honesty you trust, and support them when it costs them something.',
    ],
    facts: [
      'He wrote more than a dozen plays, including The Garden Party, The Memorandum, The Increased Difficulty of Concentration and Largo Desolato, and the late play Leaving, which premiered in 2008.',
      'Letters to Olga collects 144 letters that he wrote to his wife Olga from prison, which were censored and limited in length.',
      'The Velvet Revolution is the name for the peaceful end of communist rule in Czechoslovakia in November and December 1989. Crowds in Prague chanted “Havel to the Castle”, meaning Prague Castle, the seat of the president.',
      'In January 1977 Havel was among the first three spokespeople of Charter 77, together with Jan Patočka and Jiří Hájek.',
      'After he left office, Prague’s international airport was renamed Václav Havel Airport Prague in 2012.',
      'In 1999 he supported the NATO air campaign over Kosovo, a position that many at home and abroad criticised.',
    ],
    myths: [
      { myth: 'Havel believed that the regime should be overthrown by confrontation and force.', reality: '“The Power of the Powerless” is about moral and civic resistance. He thought that the first step is to change how people live and speak, and not to plan an uprising, and the 1989 changes were largely peaceful.' },
      { myth: 'Havel wanted Czechoslovakia to split.', reality: 'He opposed the division of the country and worked to keep it together. After the 1992 elections Czech and Slovak leaders agreed to separate, and Czechoslovakia ended on 31 December 1992. Havel resigned as federal president beforehand.' },
      { myth: 'He was only an idealist with no political skill.', reality: 'Critics did call him impractical, and his idealism is part of his writing. But he led a mass movement through the transition, guided the new country into NATO and the process of joining the European Union, and was elected twice as president of the Czech Republic.' },
    ],
    works: [
      { title: 'The Garden Party (1963) and The Memorandum (1965)', note: 'Absurdist plays satirising bureaucracy and empty official language.' },
      { title: 'The Power of the Powerless (1978)', note: 'His best-known essay, with the greengrocer and the idea of living in truth.' },
      { title: 'Letters to Olga (written 1979–1983)', note: 'Prison letters to his wife, mixing daily life with reflections on responsibility, identity and being.' },
      { title: 'Disturbing the Peace (1986)', note: 'Book-length interviews with Karel Hvížďala on his life and views.' },
      { title: 'Summer Meditations (1991)', note: 'Essays written during his first period as president, on politics and morality after communism.' },
    ],
    legacy: [
      'Havel became a symbol of the peaceful end of the Cold War in Europe. His idea of living in truth inspired dissidents and civic movements in other countries, and “The Power of the Powerless” is still read by people who work for human rights under repressive governments. As president he spoke often about conscience, responsibility and the moral dimension of public life.',
      'His record in office is also debated. Some Czechs felt that he was too idealistic or too occupied with symbols, and his early amnesty for many prisoners and his stance on Kosovo drew criticism. Yet many regard him as the rare figure who kept the roles of writer, dissident and head of state, and who showed that a writer’s insistence on truthful language can have political effect.',
    ],
  },
]
