import type { Profile } from './types'

export const MORE_09: Profile[] = [
  {
    slug: 'georg-christoph-lichtenberg',
    order: 1742,
    dates: '1742 – 1799',
    place: 'Göttingen, Electorate of Hanover (now Germany)',
    era: 'Enlightenment',
    tradition: 'Aphorism',
    tagline: 'A hunchbacked Göttingen physicist whose private notebooks of one-line thoughts made him one of Europe’s sharpest wits.',
    who: [
      'Georg Christoph Lichtenberg was born on 1 July 1742 in Ober-Ramstadt, near Darmstadt, the son of a Lutheran pastor who later became a senior church official and died while Georg was still a boy. He studied mathematics and natural science at the University of Göttingen from 1763, became a professor there in 1770, and held a full chair in physics from 1775. Apart from two visits to England, he stayed in Göttingen for the rest of his life.',
      'In childhood a curvature of the spine left him with a hunched back and a small, frail body, and he suffered all his life from breathing trouble, poor health and fits of low spirits. He made jokes about his condition instead of hiding it. His lectures were famously popular because he combined experiments with electricity and air pumps with a gift for making his audience laugh, and students came to Göttingen from well beyond Hanover to hear him.',
      'He visited England in 1770 and again in 1774–75 and was received by King George III, whose family also ruled Hanover. He edited a popular almanac, wrote essays against fashionable crazes, and produced a long commentary on the engravings of the English artist William Hogarth. Most of his best thoughts, though, went into private notebooks that he never prepared for the public. He died in Göttingen on 24 February 1799, after a short illness.',
    ],
    context: [
      'The University of Göttingen was founded in the 1730s by George II, who was both King of Great Britain and Elector of Hanover. It was one of the most modern universities in Germany, with strong science, a fine library and close ties to England. Lichtenberg was at home in both cultures, and he admired English wit, English science and English common sense.',
      'His lifetime saw the German Enlightenment give way to the emotional “Storm and Stress” movement, to the hugely popular novel The Sorrows of Young Werther, to Kant’s Critique of Pure Reason (1781) and to the French Revolution. Lichtenberg watched these enthusiasms with interest and a good deal of scepticism. He preferred careful observation, clear language and a sense of humour to grand systems and fashionable feeling.',
    ],
    ideas: [
      { title: 'The notebook as a laboratory for thought', text: 'From the 1760s until the year of his death Lichtenberg kept notebooks that he called Sudelbücher, usually translated “waste books”. The name comes from the rough account books that English merchants kept for jotting down transactions as they happened. Into his own he put observations, jokes, experiments, quotations and half-formed arguments, in no fixed order. The method let him catch a thought before it was polished, and it created the modern aphorism: a short remark that sets a whole idea in motion.' },
      { title: 'Wit as a way of thinking', text: 'For Lichtenberg a good joke or comparison was not decoration but a tool for seeing. His line that a book is a mirror, and that if an ape looks in, no apostle will look out, makes a point about reading in a single image: what we get from a text depends on what we bring to it. He believed that wit could expose muddled thinking faster than a long argument.' },
      { title: 'Thinking is something that happens', text: 'Lichtenberg questioned Descartes’s “I think, therefore I am”. We should say “it thinks”, he suggested, just as we say “it flashes” when lightning appears. All we really observe is that thoughts occur, and to add an “I” that does the thinking is already a step beyond the evidence. He also remarked that much of philosophy is a correction of everyday language. These notes anticipated twentieth-century worries about how words mislead us, and Wittgenstein read him with admiration.' },
      { title: 'Observe first, theorise second', text: 'As an experimentalist he trusted careful observation over grand schemes, and he warned against narrow specialisation: whoever understands nothing but chemistry, he wrote, does not understand chemistry properly either. His best-known scientific discovery came from patient looking. In 1777, studying electrical discharges on an insulating plate dusted with fine powder, he saw branching, tree-like patterns, now called Lichtenberg figures.' },
      { title: 'Scepticism about fashionable certainty', text: 'He mocked the physiognomy of Johann Kaspar Lavater, who claimed that character could be read from the shape of the face, and argued that such claims could not be tested and encouraged cruel prejudice. The same instinct made him wary of the Werther craze and of sweeping political enthusiasm. His scepticism was playful and humane, not bitter.' },
    ],
    principles: [
      'Write down a thought the moment it appears, before it is polished away.',
      'Use humour to test an idea: if the joke does not work, the idea may be confused.',
      'Be careful with words, since they can claim more than we know.',
      'Stay curious beyond your specialty, because a narrow expert misses even his own subject.',
      'Look hard at the evidence before you trust a clever theory.',
    ],
    practice: [
      'Keep a notebook of your own, and put in observations, questions and jokes without sorting them. Re-read it after a month.',
      'When you read, notice what you brought to the page, and what a different reader might see.',
      'Before accepting a confident claim about people, ask how it could be tested.',
    ],
    facts: [
      'Lichtenberg figures are named after him, and the same branching patterns appear in lightning, in high-voltage engineering and on the skin of some lightning-strike survivors. The idea of using electric charge to attract powder to a surface is often seen as an ancestor of photocopying.',
      'He was one of the first professors in Germany to base his teaching on regular experimental demonstrations for large audiences.',
      'He championed the lightning rod, and he had one fitted to his own garden house.',
      'Together with Georg Forster he edited a scholarly magazine, and from 1778 he edited the Göttinger Taschen-Calender, a yearbook that mixed science, essays and satire.',
      'His notebooks were published only after his death, in selections made by his brother Ludwig Christian and the scholar Friedrich Kries, and later in full editions.',
      'A crater on the Moon bears his name.',
    ],
    myths: [
      { myth: 'Lichtenberg was a bitter, withdrawn cripple.', reality: 'He did suffer from ill health and melancholy, and he wrote about it candidly. But contemporaries describe a witty, sociable teacher whose lectures were crowded, and his humour was usually kind.' },
      { myth: 'His aphorisms were a finished book.', reality: 'They are selections from private working notebooks. Lichtenberg never arranged them for publication, and the order and choice in printed editions are the work of later editors.' },
      { myth: 'He was mainly a philosopher.', reality: 'By profession he was a physicist and a professor of experimental science. His reputation as a thinker grew mostly after his death, through his notebooks.' },
    ],
    works: [
      { title: 'Sudelbücher (the “waste books”)', note: 'The private notebooks, kept from the 1760s until 1799, are the source of his fame as an aphorist.' },
      { title: 'Über Physiognomik (“On Physiognomy”, 1778)', note: 'His attack on Lavater’s claim that character can be read from the face.' },
      { title: 'Ausführliche Erklärung der Hogarthischen Kupferstiche', note: 'A long, witty commentary on Hogarth’s engravings, published in instalments from 1794.' },
      { title: 'Letters and the Göttinger Taschen-Calender', note: 'His essays and almanac pieces show his skill as a popular writer on science and society.' },
      { title: 'Vermischte Schriften (1800–1806)', note: 'The first posthumous collection, edited by his brother Ludwig Christian Lichtenberg and Friedrich Kries.' },
    ],
    legacy: [
      'Lichtenberg’s notebooks were discovered by later readers as much as by his own time. Schopenhauer and Nietzsche both admired him, and Freud quoted him in his study of jokes. Karl Kraus and Elias Canetti drew on his example, and Wittgenstein, who valued his remarks on language, is among the thinkers who kept reading him.',
      'In science his name survives in the Lichtenberg figures, which still matter to electrical engineering and to the study of fractal and branching patterns. As a writer he left the model of a thinker who gives the reader one sharp sentence, then trusts the reader to continue.',
    ],
  },
  {
    slug: 'thomas-jefferson',
    order: 1743,
    dates: '1743 – 1826',
    place: 'Monticello, Virginia, United States',
    era: 'Enlightenment',
    tradition: 'American Enlightenment',
    tagline: 'Author of the Declaration of Independence, who wrote that all men are created equal and who held hundreds of people in slavery.',
    who: [
      'Thomas Jefferson was born on 13 April 1743 (by the modern calendar) at Shadwell, in Albemarle County, Virginia, the son of a planter and surveyor. He studied at the College of William and Mary, where the teacher William Small introduced him to science and Enlightenment thought, and then read law under George Wythe. He practised law, sat in Virginia’s House of Burgesses, and around 1768 began building Monticello, the hilltop house near Charlottesville that he redesigned for the rest of his life.',
      'In 1776 the Continental Congress chose him to be principal drafter of the Declaration of Independence. He later served as governor of Virginia, as American minister in Paris from 1785 to 1789, as the first Secretary of State, as vice-president under John Adams, and as the third president from 1801 to 1809. His presidency included the Louisiana Purchase of 1803, which roughly doubled the country’s size, and the Lewis and Clark expedition. In retirement he founded the University of Virginia. He died at Monticello on 4 July 1826, the fiftieth anniversary of the Declaration, within hours of John Adams.',
      'Jefferson also enslaved more than 600 people during his life, and Monticello was built and run by enslaved labour. He formally freed only seven people, two during his life and five in his will, and after his death in debt about 130 enslaved people were sold at auction at Monticello in January 1827. This fact is not a footnote to his biography: it is central to how historians now read him, because his writings about liberty and his daily practice pointed in opposite directions.',
    ],
    context: [
      'Jefferson’s Virginia was a British colony whose wealth rested on tobacco and on slavery. Its gentry were educated in the ideas of the Enlightenment, in John Locke’s theory of natural rights, in Scottish writers on society and in the English tradition of liberty, and they came to feel that Britain’s rule after 1763 violated those rights. The crisis ended in the war of independence, and in the founding of a new republic.',
      'The new nation had to decide what a free society would look like. Jefferson’s answer favoured a republic of small independent farmers, limited government, religious liberty and widely spread education. It left out enslaved Black Americans and, in practice, Native Americans, who faced pressure to give up land or move west. His generation of founders knew about the contradiction, and argued about it, but did not end slavery.',
    ],
    ideas: [
      { title: 'Rights belong to people by nature', text: 'The Declaration of Independence states that all men are created equal and have rights, among them life, liberty and the pursuit of happiness, and that governments exist to secure those rights and derive their power from the consent of the governed. Jefferson later said he had not aimed at originality but at expressing the common mind of his time. The sentence became one of the most widely quoted in political history, and later reformers, from abolitionists to suffragists to civil-rights leaders, used it to hold the country to its own words.' },
      { title: 'Religion is a matter of conscience', text: 'Jefferson drafted the Virginia Statute for Establishing Religious Freedom in 1777. It was passed by the legislature in 1786, with James Madison guiding it through. It declares that no one may be forced to support or attend a church and that a person’s civil rights do not depend on religious opinion. Jefferson himself admired the moral teaching of Jesus but doubted miracles, and in his private “Jefferson Bible” he cut out the supernatural passages. In 1802 he used the phrase “a wall of separation between church and state” in a letter to Baptists in Danbury, Connecticut.' },
      { title: 'A free people must be educated', text: 'He believed that self-government fails if citizens are ignorant. In 1779 he proposed a plan for public schooling in Virginia, and in his last years he planned and designed the University of Virginia, which opened in 1825. He arranged its buildings as an “academical village” and left out a professorship of divinity. He wanted students to follow their interests and to pursue truth freely.' },
      { title: 'Limited government and a republic of farmers', text: 'Jefferson distrusted concentrated power, and he feared that cities, banks and a strong central government would corrupt republican virtue. He trusted independent farmers to be good citizens. He also wrote that laws and constitutions should be revised as generations change, and in a letter of 1787 he suggested that a country benefits from an occasional rebellion. In practice, as president, he used federal power more boldly than his theory suggested, most plainly in the Louisiana Purchase.' },
      { title: 'A republic built on a contradiction', text: 'In Notes on the State of Virginia he condemned slavery as corrupting to masters and unjust to the enslaved, saying he trembled for his country when he reflected that God is just. He proposed gradual emancipation followed by removal of freed people from the country. In the same book he put forward, as a suspicion, that Black people were naturally inferior, a view later writers used to justify racism. His own draft of the Declaration included a passage attacking the slave trade that Congress removed. Historians, including most scholars today, also conclude on documentary and DNA evidence that Jefferson fathered the six children of Sally Hemings, an enslaved woman who was the half-sister of his late wife. The relationship is thought to have begun when she was a teenager, around the time of their stay in Paris in 1787–89. Because she was enslaved by him, she could not freely refuse, and scholars stress that power imbalance. Jefferson never discussed it publicly.' },
    ],
    principles: [
      'Rights come first and governments exist to protect them.',
      'Keep conscience free: no one should be forced in matters of belief.',
      'Educate citizens, because free government depends on informed people.',
      'Be wary of concentrated power, public or private.',
      'Judge people, and yourself, by what they do as well as by what they say.',
    ],
    practice: [
      'Read the Declaration of Independence and the Virginia Statute for Religious Freedom in full, and ask which of their claims you could defend today.',
      'Notice where your own stated values and your daily habits do not match, as Jefferson’s did, and decide what you will change.',
      'Support, or take part in, local education and libraries, because Jefferson saw them as the foundation of self-government.',
    ],
    facts: [
      'Jefferson and John Adams both died on 4 July 1826. Adams’s reported last words were that Jefferson survived him, though Jefferson had died a few hours earlier.',
      'His own epitaph, which he designed, names three achievements: author of the Declaration, author of the Virginia Statute for Religious Freedom, and father of the University of Virginia. It does not mention the presidency.',
      'In 1815 he sold his large library to Congress, to replace the collection burned when British forces destroyed the Capitol in 1814. It consisted of more than 6,000 volumes and became the core of the new Library of Congress.',
      'Monticello and the University of Virginia were named a UNESCO World Heritage Site together in 1987.',
      'He was an enthusiastic inventor and gardener, who kept detailed records of weather, crops and experiments and used a copying device called a polygraph for his letters.',
      'In 1820, thinking of slavery, he wrote that the country had the wolf by the ear: it could neither hold him nor safely let him go.',
    ],
    myths: [
      { myth: 'Jefferson wrote the Declaration of Independence alone.', reality: 'He was the principal drafter of a committee of five that included John Adams and Benjamin Franklin. Congress also made substantial edits and cut about a quarter of his text.' },
      { myth: 'The story of Sally Hemings was disproven, or only a rumour.', reality: 'The claim was first published by a hostile journalist in 1802, and it was long dismissed. A 1998 DNA study and a review of the documents led the Thomas Jefferson Foundation in 2000, and most historians since, to conclude that Jefferson was the father of her children.' },
      { myth: 'Jefferson opposed slavery and freed his slaves.', reality: 'He criticised the institution in writing and tried to limit the slave trade, but he never made emancipation a priority and depended on slavery all his life. He formally freed only seven men, most of them members of the Hemings family or related to it, two in his lifetime and five in his will, and he let two more of Sally Hemings’s children leave Monticello without formal manumission.' },
    ],
    works: [
      { title: 'Declaration of Independence (1776)', note: 'The statement of rights and the list of grievances against George III, drafted by Jefferson and revised by Congress.' },
      { title: 'Notes on the State of Virginia (written 1780–81, published 1785–87)', note: 'His only full book: answers to a French diplomat’s questions about Virginia’s land, people and laws, including his views on slavery and race.' },
      { title: 'Virginia Statute for Establishing Religious Freedom', note: 'Drafted in 1777 and enacted in 1786.' },
      { title: 'The Life and Morals of Jesus of Nazareth (the “Jefferson Bible”)', note: 'A private compilation of Jesus’s teachings that he made around 1820 and did not publish.' },
      { title: 'Letters, especially with John Adams, Madison and Martha Jefferson Randolph', note: 'Thousands of surviving letters, available in the Papers of Thomas Jefferson edition.' },
    ],
    legacy: [
      'Jefferson’s words became a standard for people far beyond his own world. Abraham Lincoln, Frederick Douglass, the signers of the Seneca Falls declaration and Martin Luther King Jr. all appealed to the Declaration. Its language echoed in later declarations of independence and in international debates about human rights, and his statute on religious liberty influenced the debates that led to the First Amendment.',
      'Today historians no longer present him as a simple hero or villain. They study how a man who wrote so eloquently about liberty profited from slavery, and what that says about the nation he helped found. Monticello now interprets the lives of the enslaved people who lived there, including the Hemings family, alongside the life of its builder.',
    ],
  },
  {
    slug: 'johann-gottfried-herder',
    order: 1744,
    dates: '1744 – 1803',
    place: 'Riga, Bückeburg and Weimar',
    era: 'Enlightenment',
    tradition: 'German Enlightenment and Romanticism',
    tagline: 'He argued that people think through language and that every culture should be understood on its own terms.',
    who: [
      'Johann Gottfried Herder was born on 25 August 1744 in Mohrungen, East Prussia (now Morąg, Poland), the son of a schoolmaster. He studied in Königsberg, where he attended the lectures of Immanuel Kant, who was then a young teacher, and became a friend of the thinker Johann Georg Hamann. He then worked as a teacher and preacher in Riga, on the Baltic coast.',
      'In 1769 he left Riga and travelled by sea to France, an experience that made him rethink what he wanted to write. In Strasbourg in 1770 he met the young Goethe and opened his eyes to Shakespeare, Ossian and folk songs. After years as a court preacher in Bückeburg, he moved to Weimar in 1776 as the church’s senior official, with Goethe’s help, and stayed there until his death on 18 December 1803.',
      'Herder was a Lutheran pastor as well as a writer, and his books on language, poetry, history and religion came out of a lifetime of reading in many languages. He married Caroline Flachsland in 1773. In his later years he quarrelled with Kant and became somewhat isolated, but his ideas had already spread across Europe.',
    ],
    context: [
      'Herder worked in the age of French cultural prestige. In much of Europe educated people admired French literature and reason, and German-speaking lands were politically divided into many small states, with no national centre. Many Enlightenment writers presented history as a single line of progress, with modern European society as its peak.',
      'Herder reacted against this. Younger German writers in the Sturm und Drang (“Storm and Stress”) movement wanted feeling, originality and native tradition. Herder gave them a theory: each people has its own way of speaking, singing and living, and these should be understood from within, not ranked against a French or classical model.',
    ],
    ideas: [
      { title: 'Language comes first', text: 'In his Treatise on the Origin of Language (1772), which won a prize from the Berlin Academy, Herder argued that language is not a gift from God, nor an invention made on purpose. It arises naturally from being human. Humans lack the sure instincts of animals, so they must use their reason, and reason works by marking things with words. For Herder we think in language, which means that to learn how a people speaks is to learn how it sees the world.' },
      { title: 'Every culture has its own centre', text: 'Against the idea that history is a single march toward European civilisation, Herder held that each age and each people has its own character and its own sources of happiness. A medieval village, an ancient Greek city and an eighteenth-century Paris salon cannot be measured on one scale. He opposed colonial conquest and condemned the arrogance of treating other peoples as inferior.' },
      { title: 'Poetry belongs to the people', text: 'Herder collected folk songs from many countries and used the word Volkslied (“folk song”) for them. He saw this poetry as living evidence of a people’s inner life, and he urged writers to learn from it. His collection helped to create the modern study of folklore, and encouraged writers across Europe to record their own songs and tales.' },
      { title: 'History as the education of humanity', text: 'In Ideas on the Philosophy of the History of Mankind (1784–91) he placed human history inside the history of nature, from climate and geography to language and religion. He thought that humans are meant to develop their humanity, a word he used for sympathy, reason and a sense of shared dignity. He rejected ranking humankind into biological hierarchies and wrote that there are no sharply separate races.' },
      { title: 'Pluralism, not uniformity', text: 'Herder valued a world of many cultures, each worth preserving, and he distrusted large empires that forced one way of life on many peoples. He thought that humanity flourishes through variety and that a state is more stable when it respects its different communities. This pluralism is among the most lasting of his ideas, and the philosopher Isaiah Berlin made a famous case for its importance in the twentieth century.' },
    ],
    principles: [
      'Understand people and cultures from the inside before you judge them.',
      'Remember that you think in a language, and that language shapes what you notice.',
      'Treat difference as richness, not as a problem to remove.',
      'Learn from the songs, stories and crafts of ordinary people.',
      'Aim at humanity: sympathy and shared dignity across every boundary.',
    ],
    practice: [
      'Learn a few phrases of another language, and notice which ideas or feelings it expresses in a way yours cannot.',
      'When you read about another time or place, ask first what its people were trying to do, before asking whether they matched your standards.',
      'Record the stories, songs or sayings of your own family or community, which are often at risk of being lost.',
    ],
    facts: [
      'Herder heard Kant lecture in Königsberg. Years later Kant wrote sharp reviews of Herder’s Ideas, and Herder replied with attacks on Kant’s philosophy in two late books.',
      'He is credited with popularising the word Volkslied, and his collection was reissued after his death as Stimmen der Völker in Liedern (“Voices of the Peoples in Songs”).',
      'He described the human being as a creature lacking instincts and compensated by language and reason, a view that influenced later philosophical anthropology.',
      'He defended Spinoza against the charge of atheism, in the dispute over pantheism of the 1780s, in his dialogues on God (1787).',
      'In Weimar he lived near Goethe, Schiller and Wieland, and the city’s literary circle was shaped by their friendship and their rivalries.',
      'His Ideas contains a passage that praises the peaceful Slavic peoples and imagines them awakening to a cultural future, which later Slavic national movements read with enthusiasm.',
    ],
    myths: [
      { myth: 'Herder was a nationalist who believed in racial or ethnic superiority.', reality: 'His Volk meant a community of shared language and culture, not a biological race, and he criticised racial classification and conquest. Nationalist movements in the nineteenth and twentieth centuries later borrowed his vocabulary and dropped his humanism, and they sometimes turned his cultural pluralism into political claims he did not make.' },
      { myth: 'Herder thought cultures cannot understand one another.', reality: 'He believed in a common humanity and worked to translate and share other peoples’ songs. His point was that understanding takes imagination and effort, not that it is impossible.' },
      { myth: 'He was simply Kant’s enemy.', reality: 'Herder was Kant’s grateful student and admired him in his youth. The break came later, over history and over Kant’s critical philosophy, and it was sharp on both sides.' },
    ],
    works: [
      { title: 'Treatise on the Origin of Language (1772)', note: 'His prize essay arguing that language arises from human nature itself.' },
      { title: 'Also a Philosophy of History for the Education of Humanity (1774)', note: 'An early statement of his view that each age has its own value.' },
      { title: 'Ideas on the Philosophy of the History of Mankind (1784–91)', note: 'His largest work, placing human history within the history of nature.' },
      { title: 'Volkslieder (1778–79), later Stimmen der Völker in Liedern', note: 'His anthology of folk songs from many languages.' },
      { title: 'Letters for the Advancement of Humanity (1793–97)', note: 'Essays on humanity, literature and public life.' },
    ],
    legacy: [
      'Herder’s thought shaped German Romanticism and the study of folklore, literature and language across Europe. His idea that language and culture form a people’s identity helped inspire national revivals among Czechs, Slovaks, Serbs, Finns and others, as scholars collected songs and wrote grammars. Through the Humboldt tradition and thinkers like Franz Boas, his respect for cultures on their own terms also fed into modern anthropology and its rejection of crude hierarchies.',
      'His legacy is double-edged and needs careful reading. Later nationalists often took the language of Volk without the humane framework around it, and some twentieth-century movements claimed him for ideas he would have rejected. Today scholars tend to see him mainly as a founder of cultural pluralism and of the philosophy of language, and many value him for raising the question of how to respect difference without claiming that everyone is closed off from everyone else.',
    ],
  },
  {
    slug: 'jeremy-bentham',
    order: 1748,
    dates: '1748 – 1832',
    place: 'London, England',
    era: 'Enlightenment',
    tradition: 'Utilitarianism',
    tagline: 'He asked of every law and custom a single question: does it increase happiness or reduce suffering?',
    who: [
      'Jeremy Bentham was born in London on 15 February 1748 (by the modern calendar), the son of a prosperous attorney. He was a child prodigy who entered Queen’s College, Oxford, at the age of twelve and took his degree at fifteen. He trained in law and was called to the bar in 1769, but he disliked the practice and the confusing English legal system, and he decided to spend his life reforming it.',
      'His first major work, A Fragment on Government (1776), attacked the leading legal authority of the day, William Blackstone. His Introduction to the Principles of Morals and Legislation was printed in 1780 and published in 1789. From 1785 to 1788 he visited his brother Samuel in Russia, where he conceived the Panopticon, a design for a prison. A French translation of his work by Étienne Dumont made him famous across Europe, and in 1792 he was made an honorary citizen of France.',
      'Bentham never married and led a quiet, studious life, working at his desk and producing many thousands of manuscript pages that he never finished. Younger reformers gathered around him, including James Mill and, through him, John Stuart Mill. He died in London on 6 June 1832, at the age of 84, a day before the Great Reform Act became law. According to his will his body was dissected publicly by his friend Thomas Southwood Smith, and then preserved.',
    ],
    context: [
      'Bentham lived through the American and French revolutions, the early Industrial Revolution and the rise of London as the world’s greatest city. English law was a tangle of old customs, harsh punishments, expensive courts and privileges for the powerful. More than two hundred crimes carried the death penalty, and the voting system left whole new cities without representation.',
      'The Enlightenment supplied reformers with their tools: the belief that reason can improve institutions, and that traditions must justify themselves. Bentham took this faith further than most. He did not want to appeal to ancient rights or to tradition, and he looked instead for a measurable standard by which every law could be judged.',
    ],
    ideas: [
      { title: 'The principle of utility', text: 'Bentham began his Introduction by saying that nature has placed humankind under two sovereign masters, pain and pleasure. From this he built utilitarianism: an action or law is right to the extent that it promotes happiness and wrong to the extent that it produces suffering. He often expressed the standard as “the greatest happiness of the greatest number”, a phrase he took from earlier writers, and he counted every person’s happiness equally.' },
      { title: 'Measuring pleasure and pain', text: 'He proposed a “felicific calculus”, a list of things to consider when weighing pleasures and pains: their intensity, duration, certainty, nearness, and how far they spread among people. It was never a precise mathematics, but it showed what he wanted: policy judged by its real effects on real people, not by status or prejudice.' },
      { title: 'Can they suffer?', text: 'In a famous footnote Bentham compared the way animals were treated with slavery, and argued that the key question about animals is not whether they can reason or talk, but whether they can suffer. This made suffering, not species, the reason to count a being’s interests. Philosophers such as Peter Singer later built on this line to argue for animal welfare.' },
      { title: 'Law reform and “nonsense upon stilts”', text: 'He wanted clear, written, systematically organised law, a project he called codification, a word he coined. He argued for open courts, for prisons that reformed people, for wider voting rights, for freedom of expression and for an end to slavery and colonial rule. He rejected the idea of natural rights as “nonsense upon stilts”, because he thought rights are made by laws, and he judged laws by their consequences. He also wrote, though he did not publish, that sexual acts between men that harm no one should not be punished.' },
      { title: 'The Panopticon', text: 'The Panopticon was a circular building with cells around the edge and a watchtower in the centre. Inmates could not tell whether they were being watched, so they would behave as if they always were. Bentham thought the design could be used in prisons, workhouses, schools and hospitals, and he spent years trying to have a prison built. It was never constructed as he planned. In the 1970s the philosopher Michel Foucault used the Panopticon as a symbol of modern surveillance and discipline.' },
    ],
    principles: [
      'Ask what a law or habit actually does to people’s happiness and suffering.',
      'Count everyone equally: each person’s wellbeing counts for one.',
      'Give reasons for rules, and do not defend them only by tradition.',
      'Take suffering seriously wherever it occurs, including in animals.',
      'Make rules clear and public so that everyone can know and challenge them.',
    ],
    practice: [
      'Before a significant decision, list who will be affected, and how much, in each possible outcome, then compare.',
      'When you inherit a rule or routine, ask what purpose it serves and whether something else would serve it better.',
      'Test your concern: do you extend it to people, or beings, who cannot speak for themselves?',
    ],
    facts: [
      'His preserved body, dressed in his own clothes and seated in a cabinet, is displayed in the South Cloisters of University College London. It is called his “auto-icon”, a word he coined for a person serving as his own memorial.',
      'The preservation of his real head failed, and it was replaced on the figure by a wax head. The original head was displayed for a time, but after repeated student pranks it was put into storage and is no longer on show.',
      'He coined words that are still in use, including “international” and “codification”.',
      'He drafted proposals for a new constitution and legal code for many countries, and he corresponded with leaders in Europe and the Americas.',
      'Parliament passed a Penitentiary Act in 1794 that backed his Panopticon scheme, but the government dropped the plan in 1803, and Parliament later paid Bentham £23,000 in compensation for his losses.',
      'He is often summed up as saying that the simple game of push-pin is as good as poetry if it gives as much pleasure. That wording is John Stuart Mill’s paraphrase, but Bentham wrote something close to it in The Rationale of Reward (1825): that, prejudice apart, push-pin is of equal value with music and poetry.',
    ],
    myths: [
      { myth: 'Bentham’s body attends meetings of the UCL Council, recorded as “present but not voting”.', reality: 'UCL says the auto-icon is not a regular attender. It has been brought into a Council meeting only on rare occasions, reportedly in 1926 and 1976 for the college’s anniversaries and in 2013, when the minutes noted him as “present but not voting”.' },
      { myth: 'Bentham founded University College London.', reality: 'He had little direct involvement. The college, founded in 1826, was built on ideas he championed, notably education open to all regardless of religion, and his followers helped to create it, but he is better described as its inspiration.' },
      { myth: 'Utilitarianism means the majority can ignore the minority.', reality: 'Bentham insisted that each person counts as one, and he used the principle to oppose cruelty, slavery and the persecution of unpopular groups. Critics argue that a consequences-only theory can still be used to sacrifice individuals, and that remains a central debate about utilitarianism.' },
    ],
    works: [
      { title: 'A Fragment on Government (1776)', note: 'His first major work, an attack on Blackstone’s defence of English law.' },
      { title: 'An Introduction to the Principles of Morals and Legislation (printed 1780, published 1789)', note: 'The classic statement of the principle of utility.' },
      { title: 'Panopticon; or, The Inspection-House (1791)', note: 'Letters written in Russia setting out the design.' },
      { title: 'Anarchical Fallacies', note: 'His critique of the French Declaration of the Rights of Man, written in the 1790s and first published in a French adaptation by Dumont in 1816.' },
      { title: 'The Collected Works of Jeremy Bentham', note: 'The scholarly edition produced by the Bentham Project at UCL, which is still making his manuscripts available.' },
    ],
    legacy: [
      'Bentham’s ideas shaped the nineteenth-century reform movement in Britain. His secretary Edwin Chadwick brought his thinking to the Poor Law and to public health. John Stuart Mill built on utilitarianism, softening it by separating higher and lower pleasures. Many reforms of the century, from criminal law to the vote, drew on the same readiness to test institutions by their effects.',
      'Modern debates still use his tools. Cost-benefit analysis in government, welfare economics and the movement known as effective altruism owe him a debt, and so does the animal-welfare movement. His Panopticon lives on in discussions of surveillance, and his body remains a well-known and slightly strange monument.',
    ],
  },
  {
    slug: 'johann-wolfgang-von-goethe',
    order: 1749,
    dates: '1749 – 1832',
    place: 'Weimar, Saxe-Weimar-Eisenach (now Germany)',
    era: 'Enlightenment',
    tradition: 'Weimar classicism',
    tagline: 'Poet, dramatist, scientist and statesman, whose Faust became the great German drama of striving and doubt.',
    who: [
      'Johann Wolfgang Goethe was born on 28 August 1749 in the free imperial city of Frankfurt, into a well-off family. His father, a lawyer, supervised his education, and he studied law in Leipzig and Strasbourg. In Strasbourg in 1770–71 he met Johann Gottfried Herder, who turned his attention to Shakespeare and folk poetry. His first play Götz von Berlichingen (1773) and above all the novel The Sorrows of Young Werther (1774) made him famous across Europe while he was still in his twenties. Napoleon is said to have read Werther several times.',
      'In 1775 the young Duke Karl August invited him to Weimar, a small court town, where he stayed for the rest of his life. He became an adviser and minister, taking on mines, roads, finance and the court theatre, and was ennobled in 1782. In 1786 he left suddenly for Italy, where he spent nearly two years, mostly in Rome, studying art, antiquity and nature. He returned changed, and began a long relationship with Christiane Vulpius, whom he married in 1806. From 1794 he was close friends with Friedrich Schiller, and the two shaped what is called Weimar classicism until Schiller’s death in 1805.',
      'He published Faust, Part One, in 1808, brought out his science of colour in 1810 and wrote novels, poems, autobiography and a collection inspired by the Persian poet Hafez. He finished Faust, Part Two, in 1831, and sealed the manuscript. He died in Weimar on 22 March 1832, aged 82.',
    ],
    context: [
      'Goethe’s Germany was a patchwork of small states within the Holy Roman Empire, without a capital like Paris or London. A literary culture grew up around universities and courts, and Weimar, under a duke and his mother, the dowager Duchess Anna Amalia, who valued writers, became its centre. His youth was shaped by the Sturm und Drang (“Storm and Stress”), a rebellion in favour of feeling and genius over rules.',
      'He lived through the French Revolution and the Napoleonic wars, which he watched with unease, and he was a witness to the beginnings of modern science and industry. He took the Enlightenment’s trust in inquiry but not its narrow rationalism. In his work he tried to join feeling, reason, nature and art.',
    ],
    ideas: [
      { title: 'Striving and the Faust wager', text: 'In Faust, Goethe retells the old legend of a scholar who sells his soul. Faust, bored with books, makes a wager with the devil Mephistopheles: he will forfeit his soul only if he ever says to a passing moment, “Stay, you are so beautiful.” The play, begun in the 1770s and finished in 1831, follows Faust through love, guilt, politics and ambition. Its central thought is that to be human is to keep striving and making mistakes, and that this striving, not perfection, is what finally matters.' },
      { title: 'Nature as a living whole', text: 'Goethe studied plants, bones, rocks and clouds. He coined the word “morphology” for the study of form, and in The Metamorphosis of Plants (1790) he argued that leaves, petals and sepals are variations of one basic organ. He also argued, in 1784, that humans have an intermaxillary bone like other mammals, a point that showed a kinship between humans and animals. His belief in an underlying unity in nature influenced later biology.' },
      { title: 'Colour as experience', text: 'In his Theory of Colours (1810) Goethe attacked Newton’s explanation that white light is a mixture of coloured rays. He argued that colours arise where light and darkness meet, and he described in detail how colours look to the human eye. Physicists reject his physics, but his careful account of colour perception influenced painters and psychologists, and later philosophers such as Schopenhauer and Wittgenstein engaged with it.' },
      { title: 'God in nature, with Spinoza', text: 'Goethe admired Spinoza, who identified God with nature, and he was drawn to a view in which the divine is present in the world and not outside it. He described himself in a letter as a polytheist as a poet and artist and a pantheist as a student of nature, and he disliked narrow church doctrine. His religion was a feeling of reverence for the order and life of the world.' },
      { title: 'World literature', text: 'In conversation in January 1827 Goethe said that national literature meant little now and that the age of world literature was coming. He read widely in Persian, Chinese, Serbian and other foreign poetry, translated freely, and believed that nations learn about themselves by reading each other. The term Weltliteratur, which he helped to popularise, is still used for the shared literary heritage of humankind.' },
    ],
    principles: [
      'Keep learning and striving, because a life is made by effort, including mistakes.',
      'Look closely at nature before theorising about it.',
      'Join feeling and reason instead of choosing one.',
      'Read beyond your own country and tongue.',
      'Do the task in front of you, and let mastery grow from steady work.',
    ],
    practice: [
      'Choose one natural thing, such as a leaf or a cloud, and observe it carefully for ten minutes before you read about it.',
      'Read a work in translation from a culture you know little about, and note what it makes you see in your own.',
      'At the end of the week, ask what you strove for and what you learned from your failures, as Faust’s story invites.',
    ],
    facts: [
      'Goethe worked on Faust, on and off, for about sixty years, from early drafts in the 1770s to the completion of Part Two in 1831. Part Two was published after his death.',
      'The mineral goethite is named after him. He gathered a collection of many thousands of rocks and minerals.',
      'Napoleon met him at Erfurt in 1808 and is reported to have exclaimed, “Here is a man!”',
      'He admired the English meteorologist Luke Howard, who classified clouds, and wrote a poem in his honour.',
      'Johann Peter Eckermann, who became his secretary and companion in 1823, published Conversations with Goethe in 1836 and 1848. It is a vivid but partly reconstructed record, and some of its scenes may be shaped by Eckermann. Nietzsche considered it among the best German books.',
      'His Italian Journey, written up decades afterwards from letters and diaries, helped shape how educated Europeans thought about travel in Italy.',
    ],
    myths: [
      { myth: 'Werther set off an epidemic of suicides across Europe.', reality: 'Some copycat cases were reported, and the book was banned in places such as Leipzig and Copenhagen. Historians say the scale is hard to prove, and the “Werther effect”, a term from modern media research, takes the name from the novel without settling how widespread the event was.' },
      { myth: 'Goethe’s last words were “More light!”', reality: 'The line was reported by some who were present, but accounts differ, and it may be a legend that grew afterwards. Most reliable accounts agree only that he died quietly in his armchair.' },
      { myth: 'His colour theory was simply a mistake.', reality: 'As physics of light it was wrong, and Newton’s analysis stands. But Goethe’s observations of how colours appear to us were detailed and valuable, and they remain a source for the study of perception.' },
    ],
    works: [
      { title: 'The Sorrows of Young Werther (1774)', note: 'The letter-novel of an unhappy young man in love, which brought him European fame.' },
      { title: 'Faust, Part One (1808) and Part Two (1832)', note: 'His great verse drama, completed just before his death.' },
      { title: 'Wilhelm Meister’s Apprenticeship (1795–96)', note: 'A novel of education that shaped the German tradition of the Bildungsroman.' },
      { title: 'Italian Journey (1816–17)', note: 'His account of his stay in Italy in 1786–88.' },
      { title: 'Eckermann, Conversations with Goethe (1836, 1848)', note: 'The main record of his talk in old age, to be read with its limits in mind.' },
    ],
    legacy: [
      'Goethe became the central figure of German literature, and his influence reached writers across the world, from Thomas Mann to Emerson and Carlyle. Faust inspired operas by Gounod and Berlioz, symphonic works by Liszt and Mahler, and countless adaptations. The Goethe-Institut now carries his name as a symbol of German culture abroad.',
      'In science, his morphology anticipated ideas that later biology developed, and his work on colour perception was taken up by physiologists and philosophers. He is a rare example of a writer who treated art and science as parts of one inquiry, and later thinkers have returned again and again to his picture of a mind that is patient, many-sided and always learning.',
    ],
  },
]
