import type { Profile } from './types'

export const MORE_19: Profile[] = [
  {
    slug: 'dietrich-bonhoeffer',
    order: 1906,
    dates: '1906 – 1945',
    place: 'Berlin, Germany (born in Breslau); executed at Flossenbürg',
    era: '20th Century',
    tradition: 'Christian resistance ethics',
    tagline: 'A Lutheran pastor and theologian who argued that faith must cost something, and who paid for that conviction with his life under the Nazis.',
    who: [
      'Dietrich Bonhoeffer was born on 4 February 1906 in Breslau (now Wrocław), one of eight children in a distinguished German family. His father Karl was a leading psychiatrist, and the household was cultured, liberal and only loosely churchgoing, so his decision to study theology surprised his relatives. He earned his doctorate at the University of Berlin at 21, spent a year as an assistant pastor in Barcelona, and in 1930–31 studied at Union Theological Seminary in New York, where he worshipped at the Abyssinian Baptist Church in Harlem and was deeply affected by the faith and the suffering he saw there.',
      'Adolf Hitler became chancellor in January 1933, and Bonhoeffer was among the first church figures to oppose the regime openly. He criticised the Nazi “Führer principle” in a radio talk, argued against the exclusion of Christians of Jewish descent from the church, and helped build the Confessing Church, the movement of Protestants who rejected the pro-Nazi “German Christians”. After a spell as a pastor in London, he led an illegal seminary for Confessing Church ministers, first at Zingst and then at Finkenwalde, from 1935 until the Gestapo closed it in 1937. His book Life Together grew out of that communal experience, and The Cost of Discipleship appeared in 1937.',
      'In 1939 he travelled to the United States, but he returned to Germany within weeks, writing that he could not help rebuild German church life after the war unless he shared its trials. Forbidden to teach, speak or publish, he joined the military intelligence office (the Abwehr), which sheltered several members of the resistance. He took part in a scheme that helped a group of Jews escape to Switzerland and carried messages for the conspirators abroad. He was arrested on 5 April 1943 on charges linked to that rescue operation and to the Abwehr’s activities, held at Tegel prison in Berlin, and later moved to other prisons and camps. On 9 April 1945, just weeks before the war in Europe ended, he was hanged at Flossenbürg concentration camp.',
    ],
    context: [
      'Bonhoeffer belonged to a Germany shaken by defeat in the First World War, by inflation and by the fragile Weimar Republic. Most German Protestant churches were closely tied to the nation and its rulers, and many welcomed the Nazi seizure of power or stayed silent. A minority of pastors, including Martin Niemöller, organised the Pastors’ Emergency League in 1933, and in 1934 the Confessing Church issued the Barmen Declaration, which said that Christ, not any political leader, claims absolute loyalty. Bonhoeffer was a leading voice among the younger members of this movement, though even within it the response to the persecution of the Jews was often cautious.',
      'Once the war began, the choices narrowed. Bonhoeffer’s brother-in-law Hans von Dohnányi worked with the Abwehr, and a circle of officers and officials there planned to overthrow Hitler. Bonhoeffer used his church contacts abroad, including a meeting with Bishop George Bell of Chichester in Sweden in 1942, to look for foreign support for a post-Hitler Germany. The conspirators’ failed attempt of 20 July 1944 led to a wave of arrests, and documents discovered that autumn tied the Abwehr group more firmly to the resistance.',
    ],
    ideas: [
      { title: 'Costly grace', text: 'In The Cost of Discipleship Bonhoeffer separated “cheap grace” from “costly grace”. Cheap grace means forgiveness offered without repentance, comfort without change. Costly grace is the call to follow Jesus, which demands one’s whole life but is also a gift. He wrote this partly as a criticism of a church that had grown comfortable.' },
      { title: 'Life in community', text: 'Life Together describes how Christians should live side by side, with shared prayer, silence, meals and honest confession. Bonhoeffer insisted that community is not something we build from our own ideals. We receive it as a gift, and it begins when we stop loving a dream of community and start loving the real, flawed people around us.' },
      { title: 'Responsibility and willingness to bear guilt', text: 'In his unfinished Ethics he argued that moral life is not following a set of rules but responding to the concrete situation in the light of Christ. Responsible action, he said, can mean taking on guilt for the sake of others, as when a person acts against a tyrant. He did not claim this made such acts innocent, only that refusing to act was no escape from guilt either.' },
      { title: 'Being there for others', text: 'In letters from prison, Bonhoeffer wondered what Christianity could mean in a world that no longer needed religion to explain things, which he called a world “come of age”. He wrote of the need for a “religionless Christianity”, one stripped of cultural habit and focused on the figure of Jesus as “the man for others”. He left the idea unfinished, and scholars still argue about what he meant.' },
      { title: 'A suffering God', text: 'Bonhoeffer rejected the picture of God as a power we call on to fix our problems. In prison he wrote that only a God who suffers can help, because God shares in human weakness rather than rescuing us from it. For him faith meant standing with God in the world’s suffering.' },
    ],
    principles: [
      'Do not accept comfort that costs you nothing and changes nothing.',
      'Speak up for those who cannot speak for themselves, and do not wait until it is safe.',
      'Love the actual people near you, not an ideal of community.',
      'Act responsibly in the situation you are in, and be honest about the cost.',
      'Stay alert to the way fear and convenience reshape your conscience.',
    ],
    practice: [
      'Choose one habit that your convenience has quietly replaced with a commitment, and take it up again, accepting its cost.',
      'Set aside a short period of silence and shared reflection each day, with family, friends or a group, and keep to it.',
      'When you face a hard decision, ask not only what the rules allow but who will bear the consequences of what you do and what you fail to do.',
    ],
    facts: [
      'Bonhoeffer had a twin sister, Sabine, who married Gerhard Leibholz, a jurist of Jewish descent. The family escaped to England in 1938.',
      'He wrote the poem “Who Am I?” in prison, and a hymn-like poem sent to his fiancée and family at the end of 1944, which begins “By gracious powers” and is still widely sung in German-speaking churches.',
      'He was engaged to Maria von Wedemeyer in 1943, but they never married. They were allowed only a few supervised visits while he was in prison.',
      'Two of his brothers-in-law and his brother Klaus were also killed by the regime in the closing weeks of the war.',
      'He was executed alongside other resistance figures, including Admiral Wilhelm Canaris, the former head of the Abwehr, on the orders of the Nazi leadership.',
      'The Ethics was edited from his manuscripts by his friend Eberhard Bethge, who also preserved the prison letters and published them in 1951.',
    ],
    myths: [
      { myth: 'Bonhoeffer was part of the plan to assassinate Hitler.', reality: 'He was close to the circle of conspirators through his family and the Abwehr, and he knew of their aims. He was arrested in April 1943 on charges tied to the rescue of Jews and the Abwehr’s activities, well before the 20 July 1944 attempt. Scholars still debate how directly he took part in planning and how he reconciled such plans with his faith.' },
      { myth: 'In prison he gave up Christianity for a secular outlook.', reality: 'His phrase “religionless Christianity” was a search for a faith not tied to old habits and cultural privilege. In the same letters he went on praying, reading the Bible and writing about worship, and he described his thinking as incomplete.' },
      { myth: 'Quotations about the evil of silence, widely shared online, are plainly his.', reality: 'Several popular sayings about silence and evil are paraphrases or have no firm source. Check any quotation against his published works before relying on it.' },
    ],
    works: [
      { title: 'The Cost of Discipleship (1937)', note: 'A reading of the Sermon on the Mount, and the source of the distinction between cheap and costly grace.' },
      { title: 'Life Together (1939)', note: 'A short account of Christian community, drawn from the seminary at Finkenwalde.' },
      { title: 'Ethics (published 1949)', note: 'Unfinished manuscripts edited by Eberhard Bethge, on responsibility and the Christian life in a tyranny.' },
      { title: 'Letters and Papers from Prison (1951)', note: 'Letters mostly to Eberhard Bethge, with poems and fragments, including the discussion of a “religionless” faith.' },
      { title: 'Sanctorum Communio and Act and Being', note: 'His early academic work on the church as a social reality and on knowledge of God.' },
    ],
    legacy: [
      'Bonhoeffer’s death made him one of the best-known Christian witnesses against Nazism. His prison letters, published in 1951, set off a wide debate in the second half of the twentieth century, and his thinking has been used by theologians in many traditions. His life and writings inspired Christians resisting injustice in places such as apartheid South Africa and communist Eastern Europe. He is honoured in several churches as a martyr.',
      'He is also claimed by many causes, sometimes by people whose views he would not have shared, and scholars argue over how to read the gaps and tensions in his work. His early statements on Jews and the church, for example, were not as radical as his later conduct, and historians trace his development over time. Readers value him for the way his convictions were tested by events.',
    ],
  },
  {
    slug: 'maurice-merleau-ponty',
    order: 1908,
    dates: '1908 – 1961',
    place: 'Paris, France',
    era: '20th Century',
    tradition: 'Phenomenology',
    tagline: 'The philosopher who put the living body at the centre of experience, and showed that we know the world through it, not apart from it.',
    who: [
      'Maurice Merleau-Ponty was born on 14 March 1908 in Rochefort-sur-Mer on the French Atlantic coast. His father died when he was a small child, and he was raised in Paris by his mother. He studied at the École Normale Supérieure, where he met Jean-Paul Sartre and Simone de Beauvoir, and passed the competitive teaching examination (the agrégation) in 1930. He taught in secondary schools for several years and began to study psychology and the work of the German philosopher Edmund Husserl, the founder of phenomenology.',
      'In 1939 he visited the Husserl Archives in Leuven, Belgium, where Husserl’s unpublished manuscripts had been rescued from Nazi Germany. He served in the French army in 1939–40, and after the defeat he took part in a small resistance group in Paris. His first two books, The Structure of Behavior (1942) and Phenomenology of Perception (1945), established him as a leading French philosopher. After the war he cofounded the journal Les Temps modernes with Sartre and Beauvoir and was its political editor.',
      'Merleau-Ponty held university posts at Lyon and the Sorbonne, and in 1952 he was elected to a chair of philosophy at the Collège de France, one of the most prestigious positions in French intellectual life, and one he held until his death. He died suddenly on 3 May 1961 in Paris, aged 53, apparently of a heart attack, while working on unfinished manuscripts. Sartre wrote a moving tribute to him in Les Temps modernes. His last work was published in 1964 as The Visible and the Invisible.',
    ],
    context: [
      'French philosophy before the Second World War was dominated by a tradition of thought that treated the mind as a pure observer, separate from the body and the world. Husserl’s phenomenology offered an alternative: describe experience as it is lived, before theories explain it away. Merleau-Ponty read Husserl closely, together with Heidegger, and combined their ideas with work in psychology, especially Gestalt psychology and studies of patients with brain injuries.',
      'The war and the Cold War also shaped his career. After 1945 French intellectuals argued fiercely over communism, the Soviet Union and violence in the name of progress. In Humanism and Terror (1947) Merleau-Ponty wrote about the Moscow trials and the idea that revolutionary violence might be justified by history, and he was read by many as sympathetic to the Soviet side. By the early 1950s, after the Korean War and growing evidence of Soviet labour camps, he lost faith in that position. Disagreements with Sartre, who moved closer to the Communist Party, led Merleau-Ponty to leave Les Temps modernes in 1952–53. His critique of Sartre’s politics in Adventures of the Dialectic (1955) ended their friendship, though Sartre later wrote warmly of him.',
    ],
    ideas: [
      { title: 'The lived body', text: 'We do not experience the world as a mind looking out from inside a body. We are our bodies, and our body is how we have a world at all. Merleau-Ponty described how we reach for a cup or walk through a doorway without calculating, using a practical, bodily understanding that comes before any thinking. He called this “motor intentionality”.' },
      { title: 'Perception comes first', text: 'Perception is not a collection of sensations that the mind assembles into objects, nor a rational interpretation laid over raw data. We perceive things already meaningful, in a situation, from a point of view. He argued that science itself depends on this lived perceptual world, which it cannot fully explain away.' },
      { title: 'Ambiguity', text: 'Human life, he said, is ambiguous: we are both subject and object, free and conditioned, in the world and aware of it. Instead of resolving these tensions into a simple theory, he wanted philosophy to stay with them. The same attitude shaped his political thought, which doubted both rigid dogmas and abstract appeals to pure reason.' },
      { title: 'Other people and the shared world', text: 'We do not first meet others as puzzling minds hidden behind bodies. We see anger in a face and warmth in a gesture directly. Our experience is always open to others and rests on a shared world that we find already there.' },
      { title: 'Flesh', text: 'In his late work Merleau-Ponty used the word “flesh” for a basic way of being in which the one who perceives and the thing perceived belong to the same fabric. His example is one hand touching the other: each is both touching and touched. The idea is difficult and was left unfinished, but it shows him trying to move beyond the old split between subject and world.' },
    ],
    principles: [
      'Begin from what you actually experience, not from theory about it.',
      'Take the body seriously as the way you know the world.',
      'Stay with ambiguity before forcing a neat answer.',
      'Treat other people as present in your world, not as mysteries behind masks.',
      'Be willing to revise your political and philosophical commitments in the light of events.',
    ],
    practice: [
      'Practise an everyday skill, such as playing an instrument or cooking, and notice how the knowing sits in your hands rather than in explicit thought.',
      'Pay attention to a single object, such as a tree or a painting, for a few minutes, and describe what you perceive before you name or explain it.',
      'When a question seems to demand a flat yes or no, ask what is being left out, and whether the truth is more mixed.',
    ],
    facts: [
      'He is reported to have been the youngest person elected to a chair at the Collège de France.',
      'With Sartre and others he helped form a small resistance group in occupied Paris, Socialisme et Liberté, whose bulletin was called “Sous la botte”. Its activity was mostly writing and discussion.',
      'In 1945 he published the essay “Cézanne’s Doubt”, which uses the painter’s struggle to show how art reveals the structure of perception.',
      'One of his last essays, “Eye and Mind” (1961), is a reflection on painting and vision.',
      'The Visible and the Invisible was published after his death in 1964, edited by the philosopher Claude Lefort from unfinished manuscripts and working notes.',
      'He gave a series of radio talks in 1948, later published as The World of Perception, aimed at general listeners.',
    ],
    myths: [
      { myth: 'Merleau-Ponty was simply a follower of Sartre.', reality: 'They were friends and allies for years, but their philosophies differed. Sartre stressed absolute freedom of consciousness, while Merleau-Ponty emphasised the body, situation and ambiguity. Their break over politics in the early 1950s made the gap public.' },
      { myth: 'He claimed that the mind is nothing but the body, or that perception is just physical reaction.', reality: 'He criticised both views. Against “empiricism” he argued that perception is not a mechanical response, and against “intellectualism” that it is not a pure act of thought. The lived body is his way between them.' },
      { myth: 'Humanism and Terror was his permanent defence of Soviet communism.', reality: 'The book was widely read as sympathetic to Marxist politics, and critics have said so. Merleau-Ponty later turned against that position and criticised communism in his later writings.' },
    ],
    works: [
      { title: 'The Structure of Behavior (1942)', note: 'A study of behaviour that argues against reducing mind to mechanism or to pure consciousness.' },
      { title: 'Phenomenology of Perception (1945)', note: 'His main work, on the body, space, other people and freedom, with long discussions of cases of brain injury.' },
      { title: 'Humanism and Terror (1947)', note: 'Essays on revolutionary violence and the Moscow trials, which caused lasting controversy.' },
      { title: 'Adventures of the Dialectic (1955)', note: 'A critique of Marxist and Sartrean political thought, including his argument with Sartre.' },
      { title: 'The Visible and the Invisible (1964)', note: 'Unfinished late work, published posthumously, where the idea of “flesh” appears.' },
    ],
    legacy: [
      'Merleau-Ponty’s account of the lived body opened a path that later thinkers have followed in many fields. Philosophers of mind and cognitive scientists who study “embodied cognition” often cite him, as do researchers in psychology, nursing, architecture, dance and art theory. His work on perception influenced feminist and disability scholarship, which draws on his attention to how bodies shape experience.',
      'Because he died while his late ideas were still forming, readers have long argued about where he was heading and how The Visible and the Invisible relates to his earlier work. Many see him as the most careful and open-minded of the French phenomenologists, and his writing is still widely read for its mix of close description and philosophical daring.',
    ],
  },
  {
    slug: 'octavio-paz',
    order: 1914,
    dates: '1914 – 1998',
    place: 'Mexico City, with years in Paris, Tokyo and New Delhi',
    era: '20th Century',
    tradition: 'Latin American literature',
    tagline: 'A Mexican poet and essayist who tried to understand his country’s solitude, and found in poetry a way of crossing it.',
    who: [
      'Octavio Paz was born on 31 March 1914 in Mexico City, in the middle of the Mexican Revolution. His grandfather Ireneo Paz was a liberal writer and publisher, and his father was a lawyer who had supported the revolutionary leader Emiliano Zapata. Paz grew up in a house full of books and published his first poems as a teenager. As a young man he was drawn to the political left, and in 1937 he travelled to Spain to attend a writers’ congress in support of the Republic during the Civil War, an experience that marked him for life.',
      'He joined the Mexican diplomatic service in the 1940s and spent long periods abroad, in Paris, Japan and India. In Paris he met the Surrealist poet André Breton and absorbed the movement’s interest in dreams, desire and the marvellous. He wrote The Labyrinth of Solitude, an essay on Mexican identity, while living in Paris and published it in 1950. From the 1950s he published major poems, among them Sun Stone (Piedra de sol, 1957), a circular poem of 584 lines, the length of the synodic cycle of the planet Venus in days, which ends with the lines it begins with.',
      'From 1962 to 1968 Paz served as Mexico’s ambassador to India, a period that deepened his interest in Hinduism and Buddhism and in the dialogue between East and West. After soldiers and police killed protesting students in the Plaza de Tlatelolco in Mexico City on 2 October 1968, shortly before the Olympic Games, he resigned his post in protest. He taught at universities in Britain and the United States, founded and edited the magazines Plural and then Vuelta, and in 1990 was awarded the Nobel Prize in Literature. He died in Mexico City on 19 April 1998.',
    ],
    context: [
      'Paz’s Mexico was shaped by revolution, a one-party state that long dominated politics, and a continuing search for a national identity that was neither a copy of Europe nor a return to the pre-Hispanic past. Mexican writers of his generation asked what it meant to be Mexican, a question given urgency by the revolution and by the country’s mixed Indigenous and Spanish heritage.',
      'On the world stage, Paz lived through the Spanish Civil War, the Second World War and the Cold War. He began as a sympathiser of the left, but in 1951 he spoke out against Soviet labour camps, which angered many of his friends, including the poet Pablo Neruda. In the following decades he criticised both authoritarian communism and the Mexican government’s repression, and he described his own position as that of an independent liberal democrat. This path made him a controversial figure for readers on both the left and the right.',
    ],
    ideas: [
      { title: 'The labyrinth of solitude', text: 'In his famous essay, Paz described a Mexican tendency to hide behind masks of politeness, irony and formality, and he related it to the country’s history of conquest. He argued that solitude is a universal human condition, but that Mexicans feel it in a particular way, and that understanding it is the first step toward overcoming it. The book is an interpretation, not a scientific study, and it has been criticised for generalising.' },
      { title: 'Poetry as a way beyond solitude', text: 'For Paz, poetry is not decoration but a way of knowing and a way of reaching other people. In The Bow and the Lyre he treats the poem as an act that can bring about a moment of communion, in which time seems to open. He saw poets as heirs of an old human effort to speak what ordinary language cannot.' },
      { title: 'Love and the erotic', text: 'Throughout his work, desire and love are a means of breaking out of isolation. In The Double Flame (1993) he describes eroticism as a basic flame and love as a higher flame that grows from it, choosing one particular person, and he follows both through the literature of many cultures.' },
      { title: 'Modernity and the break with tradition', text: 'In Children of the Mire (1974) Paz traces how modern poetry since the Romantics has been a tradition of rebellion against tradition. He suggests that this succession of breaks, from Romanticism to the avant-garde, had run its course by the late twentieth century, leaving poets to look for something beyond it.' },
      { title: 'The dialogue of cultures', text: 'His years in India and Japan taught him to see Western ideas of time and self from outside. He wrote about Indian art, Buddhism and Tantra, and about Japanese poetry, and he argued that no culture develops in isolation. Translation, in his view, is a form of creation and the great means by which cultures talk to each other.' },
    ],
    principles: [
      'Face your solitude honestly, and then look for ways to reach others.',
      'Let poetry, and other art, speak for what argument cannot.',
      'Learn from cultures that are not your own, and from your own past.',
      'Hold power to account whatever its political colour.',
      'Treat love as a discipline of attention, not only a feeling.',
    ],
    practice: [
      'Read one poem slowly each day, aloud if possible, and notice what changes in how you attend to the world.',
      'Translate a short text, even badly, into another language, and see what you learn about both languages.',
      'When you hold a strong political opinion, test it by asking what you would criticise if your own side were in power.',
    ],
    facts: [
      'Paz received the Nobel Prize in Literature in 1990. The Swedish Academy cited “impassioned writing with wide horizons, characterized by sensuous intelligence and humanistic integrity”.',
      'He was twice married. His first wife was the writer Elena Garro, whom he married in 1937, and his second was the artist Marie-José Tramini, whom he married in the 1960s.',
      'He resigned as ambassador to India in October 1968, a public protest that became part of his reputation. He wrote a poem about the massacre, and in the essay Posdata (1970), published in English as The Other Mexico, he tied the event to older patterns in Mexican history.',
      'Sun Stone takes its name from the Aztec calendar stone, and its 584 lines are often linked to the Venus cycle in Mesoamerican astronomy.',
      'He wrote a major study of the seventeenth-century Mexican nun and poet Sor Juana Inés de la Cruz, published in English as Sor Juana, or, The Traps of Faith.',
      'He founded the cultural magazines Plural and Vuelta, which gave a home to writers from across Latin America and Europe.',
    ],
    myths: [
      { myth: 'The Labyrinth of Solitude describes the character of every Mexican.', reality: 'Paz presented a personal, literary interpretation, mostly based on the urban mestizo and on historical symbols such as the figure of La Malinche. Critics have said it is essentialist and overlooks the diversity of the country. He revisited some of its claims in the later essay Posdata.' },
      { myth: 'Paz was a lifelong conservative, or a lifelong radical.', reality: 'His politics shifted over time. He began on the left, supported the Spanish Republic, broke with Soviet communism, and described himself as a democratic critic of the left and the right. Admirers see consistency in his defence of freedom, and critics see a drift to the right. The debate is still open.' },
    ],
    works: [
      { title: 'The Labyrinth of Solitude (1950)', note: 'His essay on Mexican history and identity, and the book that made him widely known.' },
      { title: 'Sun Stone (1957)', note: 'A long circular poem on time, love and memory, often seen as his masterpiece.' },
      { title: 'The Bow and the Lyre (1956)', note: 'His major study of the poem and poetic experience.' },
      { title: 'Children of the Mire (1974)', note: 'Lectures on modern poetry from Romanticism to the avant-garde.' },
      { title: 'Sor Juana, or, The Traps of Faith (1982)', note: 'A biography and cultural study of the colonial poet.' },
    ],
    legacy: [
      'Paz is widely regarded as one of the major Spanish-language poets of the twentieth century and as a central figure in modern Mexican letters. His essays shaped how generations of readers think about Mexican identity, and his poetry has been translated into dozens of languages. He also helped to connect Latin American literature to world literature through his criticism, translation and editing.',
      'Debates over his life continue. Some critics argue that his later political positions, his dealings with powerful institutions and his sometimes harsh attacks on opponents deserve criticism. Others defend his insistence on independent thought. Readers today often value him less for his politics than for the range of his writing and the clarity of his best poems.',
    ],
  },
  {
    slug: 'iris-murdoch',
    order: 1919,
    dates: '1919 – 1999',
    place: 'Oxford, England (born in Dublin)',
    era: '20th Century',
    tradition: 'Moral philosophy and literature',
    tagline: 'A philosopher and novelist who argued that goodness depends on learning to see other people truly.',
    who: [
      'Iris Murdoch was born in Dublin on 15 July 1919 to an Anglo-Irish family and grew up in London, an only child. She studied classics, ancient history and philosophy at Somerville College, Oxford, graduating with first-class honours in 1942. During the war she worked in the British civil service, and afterwards she helped refugees for the United Nations relief agency in Europe. In 1947–48 she held a studentship at Newnham College, Cambridge, where she attended lectures by Ludwig Wittgenstein.',
      'In 1948 she became a fellow in philosophy at St Anne’s College, Oxford, where she taught for about fifteen years. Her first book was a study of Jean-Paul Sartre (1953), and her first novel, Under the Net, appeared in 1954. In 1956 she married the literary critic John Bayley. She went on to write about twenty-six novels, including The Bell (1958), The Black Prince (1973) and The Sea, the Sea (1978), which won the Booker Prize. She also continued to publish philosophy, most importantly The Sovereignty of Good (1970).',
      'She was made a Dame in 1987. In the mid-1990s, while she was finishing her last novel, Jackson’s Dilemma (1995), she began to show signs of illness, and in 1997 she was diagnosed with Alzheimer’s disease. Her decline was described with great candour by her husband in his memoir Iris (1998), and later in a film adaptation. She died in Oxford on 8 February 1999.',
    ],
    context: [
      'When Murdoch began to write philosophy in the 1950s and 1960s, Anglo-American moral philosophy was dominated by views that she thought too thin. Behaviourism treated the mind in terms of outward conduct, and a popular picture of moral life, shared with some forms of existentialism, stressed free choice at the moment of decision. Moral philosophers such as R. M. Hare argued that to call something good is mainly to express an attitude or issue a prescription, and many held that facts and values were sharply separate.',
      'She believed these views left out the inner life. Her own sources were different: the Greek philosopher Plato, the French thinker Simone Weil, and the great novelists. She also took religion seriously as a source of moral insight, even though she did not hold conventional belief in God. The Sovereignty of Good, which grew from lectures in the 1960s, collected her main arguments for a moral philosophy that attends to love, imagination and effort.',
    ],
    ideas: [
      { title: 'Attention', text: 'Murdoch borrowed the word from Simone Weil. Moral life, she said, is largely a matter of how we look at the world and the people in it, long before we choose how to act. Learning to see accurately and generously, without the distortions of our own fear and wishful thinking, is the main moral task.' },
      { title: 'The mother-in-law example', text: 'She described a woman, M, who dislikes her daughter-in-law D, finding her vulgar and immature. M is a conscientious woman, and she looks again, with patience, until she sees D as spontaneous and young. Nothing in M’s outward behaviour need change, yet something morally important has happened. Murdoch used the case to show that inner moral change is real.' },
      { title: 'Unselfing', text: 'We are surrounded by egoistic daydreams that blur reality. Murdoch gives the example of a person who, upset about a slight, notices a hovering kestrel, and for a moment the anxious self disappears. Beauty in nature or art, and the effort of study or craft, can break the grip of the self and turn attention outward.' },
      { title: 'The sovereignty of Good', text: 'The Good, in her view, is real and cannot be reduced to our wishes or choices. Following Plato, she compared it to the sun, which lets us see all else, and she held that it is always out of reach, so that we can only move toward it. This view makes moral progress a matter of growing clearer vision.' },
      { title: 'Against the existentialist-behaviourist picture', text: 'Murdoch rejected the idea, common to existentialists and to many analytic philosophers, that morality is a matter of the will choosing between options in a void. She argued that this picture makes our private, imaginative life irrelevant and our moral freedom thinner than it is.' },
    ],
    principles: [
      'Look again, and look more patiently, before you judge another person.',
      'Be wary of the comfortable stories you tell about yourself.',
      'Turn your attention outward to nature, art and other people.',
      'Treat moral effort as a long, quiet discipline, not a series of heroic decisions.',
      'Accept that the good is real even though you will never reach it.',
    ],
    practice: [
      'When you catch yourself judging someone harshly, try to describe them as a fair-minded friend would, and see whether your view shifts.',
      'Spend a few minutes each day on something outside yourself, such as a bird, a plant or a piece of music, and notice how your mood changes.',
      'Take up a discipline that needs patience, such as learning a language or an instrument, as a way of training attention.',
    ],
    facts: [
      'She was briefly a member of the Communist Party as a student at Oxford, and left it after a few years.',
      'She wrote about twenty-six novels, and Under the Net was later included in a list of the best English-language novels of the twentieth century.',
      'The title Under the Net echoes an image used in Wittgenstein’s early philosophy.',
      'She won the Booker Prize in 1978 for The Sea, the Sea, and the James Tait Black Memorial Prize in 1973 for The Black Prince.',
      'John Bayley’s memoir of her illness inspired the 2001 film Iris, in which she was played by Judi Dench and Kate Winslet at different ages.',
      'Her last major philosophical book, Metaphysics as a Guide to Morals, appeared in 1992.',
    ],
    myths: [
      { myth: 'Murdoch was a novelist who dabbled in philosophy.', reality: 'She was a professional philosopher who taught at Oxford for years and kept writing philosophy alongside her fiction. She also insisted that her novels were not illustrations of her theories.' },
      { myth: 'She was an existentialist like Sartre.', reality: 'She wrote one of the first English books on Sartre and admired his gifts, but she criticised existentialism for making morality a matter of the lone will and for neglecting vision and love.' },
      { myth: 'Her moral philosophy is a form of religion.', reality: 'She took religion’s moral language seriously and wrote about the Good in terms close to it. She did not, however, hold conventional belief in a personal God, and she wanted a moral philosophy that could stand without one.' },
    ],
    works: [
      { title: 'The Sovereignty of Good (1970)', note: 'Three essays that set out her moral philosophy of attention, with the mother-in-law and kestrel examples.' },
      { title: 'Under the Net (1954)', note: 'Her first novel, a comic story of a young writer in London and Paris.' },
      { title: 'The Bell (1958)', note: 'A novel about a lay religious community in an English country house.' },
      { title: 'The Sea, the Sea (1978)', note: 'The Booker Prize winner, narrated by a retired theatre director who retreats to a house by the sea.' },
      { title: 'Metaphysics as a Guide to Morals (1992)', note: 'A late, wide-ranging philosophical work on morality, art and religion.' },
    ],
    legacy: [
      'Murdoch’s moral philosophy was neglected for some years but has become influential. Philosophers of virtue ethics and moral psychology, such as Martha Nussbaum, Cora Diamond and Charles Taylor, have drawn on her ideas about attention and moral vision. Her work helped to bring literature and the study of character back into moral philosophy.',
      'Her novels remain widely read for their intelligent comedy, their large casts and their sense of moral peril in ordinary life. Readers today also discuss her difficult personal life and the effects of her illness, which her husband described in detail. Her legacy is that of a writer who believed that paying real attention to another person is a moral act.',
    ],
  },
  {
    slug: 'primo-levi',
    order: 1919,
    dates: '1919 – 1987',
    place: 'Turin, Italy',
    era: '20th Century',
    tradition: 'Holocaust testimony',
    tagline: 'A chemist who survived Auschwitz and became one of its most precise and humane witnesses.',
    who: [
      'Primo Levi was born on 31 July 1919 in Turin, in northern Italy, to an assimilated Jewish family, and he lived most of his life in the same apartment building. He studied chemistry at the University of Turin and graduated in 1941, even though Italy’s racial laws of 1938 had made life harder for Jews. He worked as a chemist in a mine and later in a pharmaceutical company in Milan. After the German occupation of northern Italy in 1943 he joined a small partisan group in the mountains, and he was arrested by Fascist militia on 13 December 1943.',
      'Identified as a Jew, he was sent to the transit camp at Fossoli and from there deported to Auschwitz in late February 1944. He was tattooed with the number 174517 and assigned to Monowitz, a labour camp attached to the IG Farben chemical works. He survived about eleven months there, helped by luck, by his training as a chemist, which got him work in a laboratory late in 1944, and by the kindness of Lorenzo Perrone, an Italian civilian worker who brought him food. When the Germans abandoned the camp in January 1945 he was left behind, ill with scarlet fever, and was liberated by the Red Army on 27 January.',
      'After a long journey home through Eastern Europe, he reached Turin in October 1945. He wrote If This Is a Man in the following months and published it in 1947. After a first small edition it was little noticed, and it reached a wide readership only after Einaudi republished it in 1958. For nearly thirty years he worked in a paint factory, becoming its manager, and he wrote in his spare time. After retiring in 1977 he devoted himself to writing. He died on 11 April 1987, after a fall into the stairwell of his apartment building in Turin.',
    ],
    context: [
      'Levi grew up in Fascist Italy, where Mussolini’s regime was long indifferent to the fate of Jews until the racial laws of 1938 banned them from schools and public life. After Italy’s armistice in 1943 and the German occupation, Jews in the north were rounded up and deported. Levi was one of about 650 people sent from Fossoli on his convoy, and only a small number came back.',
      'After the war many survivors found that people did not want to listen. Levi described how he felt a strong need to tell his story, and how the demand to bear witness shaped his writing. Over the decades the subject of the Holocaust moved to the centre of public memory, and during the 1970s and 1980s Levi grew concerned about deniers who played down or erased what had happened. His last book was written partly in response to such pressures.',
    ],
    ideas: [
      { title: 'Witness without hatred', text: 'In If This Is a Man, Levi describes the camp in a calm, exact style, as if giving a report. He wrote that he wanted to give evidence, not to take revenge, and the restraint makes the account all the more powerful. He asked readers to consider whether a person who works in mud, who has no name and who fights for a crust of bread is still a man.' },
      { title: 'Here there is no why', text: 'Levi recounts a guard who answered his question about why a thing was done with the German words for “here there is no why”. The phrase captures the camp as a place built to remove reason and explanation, in which language and ordinary justice had no force.' },
      { title: 'The grey zone', text: 'In The Drowned and the Saved (1986) Levi wrote that the world of the camps was not simply divided into victims and perpetrators. There was a “grey zone” of prisoners who held privileges and collaborated under pressure, including members of the Sonderkommando who worked in the gas chambers. He urged readers not to rush to judge them, and he put the blame on the system that forced such choices.' },
      { title: 'The drowned and the saved', text: 'Levi insisted that survivors were not the true witnesses. The complete witnesses, he wrote, were those who did not return, and survivors speak in their place. He also wrote about the shame survivors may feel for having lived, and about the way memory can become distorted over time.' },
      { title: 'Work, matter and the dignity of craft', text: 'As a chemist, Levi saw knowledge of matter as a way to understand the world and a source of dignity. The Periodic Table (1975) organises memoirs and stories around chemical elements. He believed in the value of skilled work done well, as in his novel The Wrench (1978), whose hero is a rigger who takes pride in his craft.' },
    ],
    principles: [
      'Tell the truth plainly, without exaggeration or revenge.',
      'Do not judge too quickly people who were placed in impossible situations.',
      'Remember that it happened, and that it can happen again.',
      'Value careful work and the pleasure of understanding how things are made.',
      'Listen to those who can no longer speak.',
    ],
    practice: [
      'Read a first-hand account of an historical atrocity slowly, and notice how plain language can carry more weight than rhetoric.',
      'When you hear a story of wrongdoing, ask what pressures and choices the people involved faced before you decide how to judge them, without excusing what was done.',
      'Take pride in doing one piece of work precisely, and describe it to someone else in clear words.',
    ],
    facts: [
      'Levi’s first book was initially turned down by Einaudi, the publisher that later made it a classic, and was first published by a small firm, De Silva, in 1947.',
      'The Truce (1963) tells the story of his strange, roundabout journey home from Auschwitz through Poland, Belarus, Ukraine and Romania, and it is often read as a counterpart to the first book.',
      'The Periodic Table has twenty-one chapters, each named after a chemical element. In 2006 the Royal Institution of Great Britain named it the best science book ever written.',
      'He also wrote science-fiction stories, the first collection of which, Storie naturali, appeared in 1966 under a pseudonym.',
      'He often described himself as a “centaur”, half chemist and half writer, and refused to see the two sides of his life as opposed.',
      'He won Italy’s Strega Prize in 1979 for The Wrench and the Campiello Prize for The Truce.',
    ],
    myths: [
      { myth: 'Levi was consumed by hatred of Germans.', reality: 'He wrote that he sought justice and understanding, and he corresponded with German readers. In The Drowned and the Saved he reproduces such letters, including some from Germans, and discusses them frankly. He also did not consider guilt a matter of nationality.' },
      { myth: 'His death must have been a late result of Auschwitz, as many assume.', reality: 'It was ruled a suicide, and no note was found. Levi had had periods of depression, but some friends and later scholars have argued that the evidence is not conclusive and that an accident cannot be excluded. The question is unsettled, and it does not alter the meaning of his work.' },
      { myth: 'Survivors like Levi were the best of humanity.', reality: 'Levi explicitly rejected this idea. He wrote that survival depended heavily on chance and on privilege, and that many of the best people perished.' },
    ],
    works: [
      { title: 'If This Is a Man (1947)', note: 'His account of eleven months at Monowitz. Published in the United States as Survival in Auschwitz.' },
      { title: 'The Truce (1963)', note: 'The story of his long journey home through Eastern Europe after liberation.' },
      { title: 'The Periodic Table (1975)', note: 'Autobiographical stories, each linked to a chemical element, including his years as a chemist.' },
      { title: 'The Wrench (1978)', note: 'A novel of work and skill, told through the stories of a rigger.' },
      { title: 'The Drowned and the Saved (1986)', note: 'His last book, a set of essays on memory, shame, the grey zone and the uses of violence.' },
    ],
    legacy: [
      'Levi’s books are among the most widely read works about the Holocaust and are taught in schools and universities across the world. His mix of scientific clarity and moral seriousness set a standard for testimony, and his reflections on memory, shame and responsibility continue to be debated by historians and philosophers. His insistence that ordinary people can be pushed into cruelty by systems remains a central theme in discussions of how atrocities happen.',
      'The circumstances of his death have often coloured how he is read. Some commentators treat it as a final consequence of the camp, while others warn against turning an uncertain event into a symbol. What is firmly known is that he left behind a body of work that combines witness, science and literature, and that readers continue to find in it a measured voice that does not offer easy consolation.',
    ],
  },
]
