import type { Profile } from './types'

export const MORE_06: Profile[] = [
  {
    slug: 'giovanni-pico-della-mirandola',
    order: 1463,
    dates: '1463 – 1494',
    place: 'Mirandola, Bologna, Ferrara, Padua, Paris and Florence',
    era: 'Early Modern',
    tradition: 'Renaissance humanism',
    tagline: 'A brilliant young nobleman who tried to reconcile every philosophy and religion he could read, and who gave Renaissance thought its most quoted speech about human freedom.',
    who: [
      'Giovanni Pico was born in 1463 into the family of the counts of Mirandola, a small territory in northern Italy. His mother, according to the usual account, hoped he would enter the Church, and at fourteen he was sent to Bologna to study canon law. He soon turned to philosophy, and over the next years he studied in Ferrara, Padua and Paris. At Padua he met Aristotelian teachers, among them the Jewish philosopher Elia del Medigo, and he worked at Hebrew, Arabic and Aramaic with the help of Jewish and converted Jewish tutors.',
      'In the mid-1480s he spent time in Florence, where he met Marsilio Ficino, Angelo Poliziano and the circle around Lorenzo de’ Medici. His life was not purely scholarly. In 1486, in Arezzo, he took part in an attempt to carry off a married woman, which ended in bloodshed and a short imprisonment. Later that year he went to Rome with a plan that would make him famous across Europe: to gather scholars from everywhere and defend nine hundred theses in open debate, and to pay the travel costs of those who came.',
      'The plan collapsed. Pope Innocent VIII stopped the debate, a commission examined the theses, and some of them were condemned. Pico left for France, was arrested there in early 1488 and freed through the intercession of Italian rulers. He settled near Florence under Lorenzo’s protection, wrote and studied intensely, and grew closer to the preaching of Girolamo Savonarola. He died in Florence on 17 November 1494, at the age of thirty-one, the same day the French king Charles VIII entered the city.',
    ],
    context: [
      'Fifteenth-century Italy was a patchwork of city-states and courts that competed for scholars as they competed for armies. Humanists were recovering Greek texts that had long been unknown in the Latin West, and Ficino in Florence was translating Plato and the late-antique writings then attributed to Hermes Trismegistus. Medieval university philosophy, based on Aristotle, was still strong, especially at Padua and Paris, and Pico knew both worlds well.',
      'The Church, meanwhile, was alert to anything that looked like novelty. Rome could tolerate a great deal of speculation, but a young layman proposing to dispute everything from Averroes to the Kabbalah, in public and in the pope’s city, attracted suspicion. His case shows both how open and how fragile the intellectual life of the Renaissance was.',
    ],
    ideas: [
      { title: 'The speech on human freedom', text: 'Pico wrote an opening speech for his planned debate, which was never delivered and was printed only after his death. It was later called the “Oration on the Dignity of Man”, but that title is not his. Its best-known passage imagines God telling Adam that he has been given no fixed place or nature, so that he may shape himself, rising towards the divine or sinking towards the beasts. It is a vivid statement that human beings are defined by choice, though the speech as a whole is about the pursuit of wisdom, not simply about self-expression.' },
      { title: 'The nine hundred theses', text: 'The theses were short propositions drawn from a very wide range of sources: Latin scholastics, Arabic and Greek philosophers, Platonists, Hermetic texts, Jewish Kabbalah and others. Roughly five hundred were presented as the views of named authorities, and about four hundred put forward his own positions. Their sheer range was the point. Pico wanted to show that serious traditions of thought, understood well, tell a related story.' },
      { title: 'Concord of the philosophers', text: 'This hope is often called syncretism, the attempt to combine different systems. Pico argued that Plato and Aristotle, whom many of his contemporaries treated as opponents, largely agree beneath their different vocabularies. He took the same attitude to religious traditions: he read Hebrew and Kabbalistic sources as if they offered support for Christian doctrine, a use of them that was new among Christian thinkers, and one that Jewish scholars would not have recognised as their own.' },
      { title: 'Against astrology', text: 'In his last years he wrote a long attack on astrology, published after his death. If human beings are free to shape themselves, he reasoned, the stars cannot rule them. He also objected to the weak evidence for astrologers’ claims and to the quarrels among astrologers. The book was widely read and is a rare case of a Renaissance scholar of the occult arguing against divination.' },
      { title: 'Philosophy as peace-making', text: 'Pico wanted philosophy to reconcile people, not defeat them. He argued that the many schools might each hold a share of the truth, and that the philosopher’s task is to see how the pieces fit. The idea has a weakness, since some views cannot be combined, but it expresses a generous view of learning.' },
    ],
    principles: [
      'Read the strongest thinkers of every school before deciding what you believe.',
      'Look for agreement beneath different vocabularies before assuming a quarrel is real.',
      'Treat your nature as something to shape, not something that is simply given.',
      'Do not let fate, whether the stars or habit, excuse you from choosing.',
      'Pursue learning with humility: the same ambition that made Pico famous also put him in trouble.',
    ],
    practice: [
      'Before arguing against a view, write the best version of it in terms its supporters would accept.',
      'Pick one habit you assume is “just how you are” and treat it for a month as a choice.',
      'When two experts seem to disagree, ask whether they are using the same words for the same things.',
    ],
    facts: [
      'He died at thirty-one. Contemporaries spoke of a fever, and the poet Poliziano died the same autumn. When the remains of both men were examined in 2007, researchers reported arsenic in Pico’s remains at levels they called potentially lethal, while Poliziano’s arsenic was judged more likely to come from long exposure or from the burial. How to interpret the result is still debated, and the poison story remains unproven.',
      'The speech now called the “Oration on the Dignity of Man” was never given. It was printed after his death, and the title was added by later editors.',
      'In 1487 a papal bull condemned the whole set of theses as partly heretical and partly suspect. Pope Alexander VI cleared Pico in 1493.',
      'Pico’s nephew, Gianfrancesco Pico, wrote a biography of him, which Thomas More translated into English around 1510.',
      'He was buried in the church of San Marco in Florence, associated with Savonarola’s Dominican order.',
      'He assembled a large library, including many Hebrew manuscripts, at a time when few Christians could read them.',
    ],
    myths: [
      { myth: 'Pico wrote the “Oration on the Dignity of Man”, a manifesto of Renaissance individualism.', reality: 'The title is not his, and the text was a speech meant to open a debate. Its famous passage on free self-making is part of a larger argument that human beings should rise towards wisdom and God. Modern scholars warn against reading it as a modern celebration of the self.' },
      { myth: 'He was poisoned by his secretary or by the Medici.', reality: 'Poisoning was suspected even in his own day, and the 2007 tests added fuel, but arsenic in a body does not show murder, and the evidence does not settle the matter. Historians remain cautious.' },
      { myth: 'He was condemned and silenced as a heretic.', reality: 'Thirteen theses were singled out by a papal commission in 1487, then all nine hundred were censured, and he was briefly jailed in France in 1488. He was later absolved, wrote major works afterwards, and died in good standing with the Church.' },
    ],
    works: [
      { title: 'Conclusiones (the 900 Theses, 1486)', note: 'Printed in Rome; the proposed debate never took place.' },
      { title: 'Oration (printed after his death in 1496)', note: 'The speech later known as “On the Dignity of Man”.' },
      { title: 'Apologia (1487)', note: 'His defence of the theses against the charge of heresy.' },
      { title: 'Heptaplus (1489)', note: 'A sevenfold interpretation of the creation story in Genesis.' },
      { title: 'On Being and the One (written 1491) and Disputations against Divinatory Astrology', note: 'The first argues that Plato and Aristotle agree; the second, published after his death, rejects astrology.' },
    ],
    legacy: [
      'Pico’s attempt to find truth across all traditions inspired later scholars, among them the German humanist Johannes Reuchlin, who developed what is sometimes called Christian Kabbalah. His book against astrology influenced later critics of divination, and his speech became one of the most cited texts of the Renaissance.',
      'Since the nineteenth century readers have often treated him as a spokesman for “Renaissance man”. Historians now stress that he was also a religious thinker, deeply interested in mysticism and in the unity of truth, and that his career shows how quickly Church authorities could turn on a novelty. His reputation rests on a short life of dazzling ambition.',
    ],
  },
  {
    slug: 'nicolaus-copernicus',
    order: 1473,
    dates: '1473 – 1543',
    place: 'Toruń, Kraków, Bologna, Padua and Frombork, Royal Prussia (now Poland)',
    era: 'Early Modern',
    tradition: 'Astronomy',
    tagline: 'A cathedral canon who worked out, in mathematical detail, a universe in which the Earth moves round the Sun.',
    who: [
      'Nicolaus Copernicus was born in 1473 in Toruń, a Hanseatic trading city in Royal Prussia, which was then under the Polish crown. His father, a merchant, died in the 1480s, when Nicolaus was about ten to twelve, and his uncle Lucas Watzenrode, later prince-bishop of Warmia, raised him. He studied at Kraków, then in Italy, at Bologna, Padua and Ferrara, where he trained in canon law and medicine and took a doctorate in canon law in 1503. In Bologna he also worked with the astronomer Domenico Maria Novara.',
      'From 1497 he held a place as a canon of the cathedral chapter of Warmia, based at Frombork, and he spent most of his adult life there, never marrying. The job was demanding. He administered the chapter’s estates, handled legal and financial business, practised medicine, and in the war of 1520–21 helped organise the defence of Olsztyn against the Teutonic Knights. He also wrote a memorandum on the coinage, arguing for a single reliable currency and noticing that debased money drives out good.',
      'Astronomy was his private passion. Around 1514 he circulated a short manuscript, now called the Commentariolus, which set out the basic idea that the Sun, not the Earth, lies near the centre of the planets’ orbits. He worked on the full proof for decades and published it only at the end of his life, as De revolutionibus orbium coelestium, printed in Nuremberg in 1543. Tradition says he received a copy on his deathbed.',
    ],
    context: [
      'Medieval astronomy followed Ptolemy’s second-century system, in which the Earth sits still at the centre and the Sun, Moon and planets circle it on a combination of circles called epicycles and deferents. It predicted positions fairly well, but it was complicated, and astronomers disliked one device, the equant, because it let a planet move at an uneven speed round its circle, which offended the principle that heavenly motion should be uniform.',
      'The sixteenth century also brought new instruments, new printing presses and a growing market for calendar reform, a problem the Church cared about. Friends such as Bishop Tiedemann Giese encouraged him to publish, and the young Wittenberg mathematician Georg Joachim Rheticus travelled to Frombork in 1539 to study with him. Rheticus wrote the first printed summary, the Narratio prima, in 1540, and helped push the book into print.',
    ],
    ideas: [
      { title: 'The Sun near the centre', text: 'Copernicus proposed that the Earth is one planet among several that orbit the Sun, and that it also turns once a day on its own axis. The daily motion of the sky then becomes an appearance caused by the Earth’s rotation. He also placed the planets in an order based on how long they take to go round, which gave a natural ranking and relative distances that the old system had treated as arbitrary.' },
      { title: 'Retrograde motion explained', text: 'Planets sometimes seem to slow down, move backwards for a while and then resume. In the old system each loop needed its own epicycle. In Copernicus’s system the loops follow naturally because we watch the other planets from a moving Earth, as one car seems to drift backwards when another overtakes it.' },
      { title: 'Still a system of circles', text: 'It is easy to overstate how modern he was. He kept the ancient demand for uniform circular motion, kept epicycles, and took the centre of the Earth’s orbit to be near the Sun, not exactly at it. His model was no more accurate in prediction than Ptolemy’s, and it was nearly as intricate. Its power lay in its structure and in the simplicity of its main idea.' },
      { title: 'Not wholly new', text: 'In the third century BC Aristarchus of Samos had proposed a Sun-centred cosmos, and Copernicus knew that some ancient writers had considered a moving Earth. He used mathematical devices that earlier Islamic astronomers such as al-Tusi and Ibn al-Shatir had developed, though historians still debate how they reached him. His achievement was to work the idea out in the full detail of a technical astronomy.' },
      { title: 'Money and order', text: 'In his work on coinage he argued that a state should issue one standard currency, keep it from being debased, and not let the ruler profit by cheapening it. Like his astronomy, it reflects a preference for order and measure.' },
    ],
    principles: [
      'Look for the simpler explanation, and be ready to rethink what seems obvious.',
      'Do careful work, and do not rush to publish what you cannot yet support.',
      'Take ideas from every source, ancient or foreign, and credit them honestly.',
      'Keep ordinary responsibilities, because the best thinking can come from someone with a day job.',
      'Keep a sense of proportion: your own viewpoint may be the thing that is moving.',
    ],
    practice: [
      'When something seems to be moving, ask whether it is you who is moving, and what the same events look like from another position.',
      'Take a problem you handle by adding exceptions, and test whether a different starting point removes them.',
      'Keep a long-term project going alongside your daily duties, and give it regular time.',
    ],
    facts: [
      'He has been claimed by both Polish and German national traditions. Born in a Prussian city under the Polish crown, he wrote in Latin and also used German, and the question of his “nationality” is one later centuries asked more than he did.',
      'When the book finally appeared, it carried an unsigned preface, later shown to be by the Lutheran theologian Andreas Osiander, saying that the theory was only a mathematical device and need not be true. Copernicus did not write it, and his own text treats the Sun-centred arrangement as real.',
      'His grave in Frombork Cathedral was unmarked. In 2005 archaeologists found a skeleton there, and in 2008 DNA from the bones matched hairs preserved in one of his books. He was reburied with honours in 2010.',
      'The Church placed De revolutionibus on its Index of Prohibited Books in 1616, “until corrected”, and corrections were published in 1620. The Church’s restrictions on books supporting a moving Earth were eased in the eighteenth century and ended in the nineteenth.',
      'If the Earth circles the Sun, the stars should seem to shift slightly over the year. Nobody could detect such a shift with the instruments of his time, so Copernicus answered that the stars must be immensely far away, and critics used the missing shift as an argument against him.',
    ],
    myths: [
      { myth: 'Copernicus single-handedly began the scientific revolution.', reality: 'His book was technical, conservative in several ways and read mostly by astronomers. It took Kepler’s elliptical orbits, Galileo’s telescope and Newton’s physics to turn the idea into a new science of the heavens. The label “revolution” also owes much to later writers.' },
      { myth: 'The Church immediately condemned him.', reality: 'The book was dedicated to Pope Paul III and circulated for decades with little official objection. Controversy came mostly after Galileo, and the 1616 decree followed more than seventy years later.' },
      { myth: 'He was the first to think of a moving Earth.', reality: 'Ancient writers such as Aristarchus had suggested it, and medieval scholars such as Nicole Oresme had discussed the Earth’s rotation. What Copernicus added was a worked-out mathematical model.' },
    ],
    works: [
      { title: 'De revolutionibus orbium coelestium (1543)', note: 'His main work, in six books, with a dedication to Pope Paul III.' },
      { title: 'Commentariolus (c. 1514)', note: 'A short early outline of the Sun-centred system, circulated in manuscript and only rediscovered in the nineteenth century.' },
      { title: 'Rheticus, Narratio prima (1540)', note: 'The first printed account, by Copernicus’s only formal pupil.' },
      { title: 'Memorandum on coinage (1520s)', note: 'His proposals for a single stable currency in Prussia.' },
    ],
    legacy: [
      'Tycho Brahe, Kepler and Galileo all argued with Copernicus’s book. Kepler replaced his circles with ellipses, Galileo’s telescope showed the moons of Jupiter and the phases of Venus, and Newton’s gravity finally explained why the planets move as they do. By the late seventeenth century a moving Earth was the working assumption of astronomy.',
      'His name has become shorthand for a change of viewpoint that displaces humanity from the centre of things. Historians now urge us to see him as a careful late-medieval astronomer who opened a door, not as a modern hero who walked through it, and the story is more interesting for that.',
    ],
  },
  {
    slug: 'martin-luther',
    order: 1483,
    dates: '1483 – 1546',
    place: 'Eisleben, Erfurt and Wittenberg, Saxony (now Germany)',
    era: 'Early Modern',
    tradition: 'Protestant Reformation',
    tagline: 'A German monk and professor whose protest against the sale of indulgences split Western Christianity, and whose legacy includes both a vernacular Bible and writings against Jews.',
    who: [
      'Martin Luther was born in 1483 in Eisleben, in Saxony, the son of Hans Luder, a copper miner who rose to become a small-scale owner. He studied at Erfurt and took his master’s degree in 1505. That summer he was caught in a violent thunderstorm and, according to later accounts, vowed to become a monk if he survived. He entered the Augustinian monastery in Erfurt, was ordained in 1507, and a few years later became a professor of the Bible at the new university of Wittenberg, where he taught for the rest of his career.',
      'Luther was a tormented, scrupulous monk who feared that he could never be righteous enough for God. His reading of Paul’s letter to the Romans, and the advice of his superior Johann von Staupitz, helped him towards a different view: that righteousness is a gift received through faith, not something earned. In 1517 he wrote to church leaders against the sale of indulgences, attaching a list of ninety-five theses for debate. They spread across Germany in print within weeks.',
      'Rome demanded that he recant. After a debate with Johann Eck in 1519 and a papal bull in 1520, Luther was excommunicated in January 1521 and summoned to the imperial Diet at Worms, where he refused to withdraw his books. Emperor Charles V declared him an outlaw. His protector, Elector Frederick of Saxony, hid him at the Wartburg castle, where he translated the New Testament. In 1525 he married Katharina von Bora, a former nun, and they raised a family in Wittenberg. He died on a trip to Eisleben in February 1546.',
    ],
    context: [
      'Late medieval Christianity was rich in devotion, and also bitterly criticised. Many complained of clergy who held several offices, of Rome’s demands for money, and of a system of indulgences, which offered remission of penalties for sin in exchange for payment. In 1517 a preacher named Johann Tetzel was selling an indulgence to help fund the rebuilding of St Peter’s in Rome and to repay a debt of Archbishop Albrecht of Mainz. Luther’s theses were first of all an academic and pastoral complaint.',
      'Other forces helped it spread. The printing press let pamphlets reach thousands of readers cheaply. German princes and cities resented Rome’s power and were ready to protect a critic. Humanists had been urging a return to the sources, including the Greek New Testament, and Erasmus’s edition of 1516 was available to Luther. Without these conditions an obscure professor’s dispute might have remained local.',
    ],
    ideas: [
      { title: 'Justification by faith', text: 'Luther taught that people are made right with God by trusting in Christ’s promise, not by their own good works, which follow as the fruit of faith. Salvation is a gift, and no pilgrimage, payment or ritual can purchase it. This is the core of the Reformation, and it explains his opposition to indulgences.' },
      { title: 'Scripture first', text: 'In debate he insisted that the Bible, not pope or council, was the final authority, and he asked every Christian to read it. At Worms, tradition has him ending with the words “Here I stand”, but the official record of the hearing does not include them, and historians doubt that he said them. What is attested is his refusal to recant unless shown his error from Scripture and plain reason.' },
      { title: 'The priesthood of all believers', text: 'He argued that all baptised Christians share in the priesthood and that ordinary work can serve God as much as monastic life can. The idea dignified farming, trading and family life, and it led him to leave the monastery and to marry.' },
      { title: 'A Bible people could read', text: 'Luther translated the New Testament into German in 1522, in a matter of weeks according to common accounts, and the whole Bible appeared in 1534 with help from colleagues such as Philipp Melanchthon. German Bibles existed before his, but his was widely read, vivid and influential on the written language. He also wrote hymns and catechisms to teach faith to families.' },
      { title: 'Two kingdoms', text: 'He distinguished God’s spiritual rule, exercised through the word, from the worldly rule of governments, exercised through the sword. Rulers should keep order, and the Church should not rule by force. In practice this teaching made him deferential to the princes who protected him.' },
    ],
    principles: [
      'Test every authority against evidence and conscience.',
      'Do not try to earn what can only be received.',
      'Treat ordinary work as a calling that matters.',
      'Put learning within everyone’s reach, in language they speak.',
      'Remember that great reformers can do great harm, and judge a person’s legacy by all of it.',
    ],
    practice: [
      'When you disagree with an institution you belong to, state the objection in writing and in terms the institution itself accepts.',
      'Read an important text in a version you can understand, and then compare translations.',
      'Check whether a belief of yours rests on evidence or on someone’s say-so.',
    ],
    facts: [
      'The tradition that he nailed the theses to the door of the Castle Church in Wittenberg on 31 October 1517 comes from later accounts. What is certain is that he sent them to Archbishop Albrecht of Mainz, and that the theses were soon printed.',
      'In the Peasants’ War of 1524–25, thousands of German peasants rose against their lords. Luther first urged both sides to make peace, then wrote a pamphlet urging the princes to put down the rebels without mercy. Estimates of the dead run to around 100,000, and his reputation among ordinary Germans suffered.',
      'In 1523 he wrote that Jesus was born a Jew and urged kindness towards Jews, in the hope they would convert. In 1543, in On the Jews and Their Lies, he called for synagogues to be burned, Jewish houses to be razed, prayer books to be seized, and rabbis to be forbidden to teach. These writings were used by antisemites in later centuries, including the Nazis. In 1994 the Evangelical Lutheran Church in America formally rejected them, and other Lutheran churches have made similar statements.',
      'Katharina von Bora escaped from a convent in 1523, and married Luther in 1525. They had six children, two of whom died young, and ran a large household in the former Wittenberg monastery.',
      'He wrote hymns, including “A Mighty Fortress Is Our God”, and he encouraged congregational singing in German.',
    ],
    myths: [
      { myth: 'Luther set out to found a new church.', reality: 'He began by calling for a debate inside the Church. A break came only after years of conflict, and his followers organised themselves into a separate church in the 1520s and 1530s, often under princely protection.' },
      { myth: 'Luther created the German Bible, and with it the German language.', reality: 'There were earlier German Bibles. His translation was influential in shaping a written standard, but he drew on existing chancery German and on the work of others.' },
      { myth: 'He said, “Even if I knew the world would end tomorrow, I would plant an apple tree today.”', reality: 'No source in his own writings or from his lifetime has been found for this saying. It appears in the twentieth century and is probably a later attribution.' },
    ],
    works: [
      { title: 'The Ninety-five Theses (1517)', note: 'Written in Latin for academic debate and soon translated and printed.' },
      { title: 'Three treatises of 1520', note: 'To the Christian Nobility, On the Babylonian Captivity of the Church and On the Freedom of a Christian set out his programme.' },
      { title: 'The German Bible (New Testament 1522, whole Bible 1534)', note: 'The translation that did the most to spread his ideas.' },
      { title: 'On the Bondage of the Will (1525)', note: 'His reply to Erasmus on free will.' },
      { title: 'Small and Large Catechisms (1529)', note: 'Teaching texts that remain central to Lutheran churches. The Table Talk, notes by his students, is a later and less reliable source.' },
    ],
    legacy: [
      'The Reformation divided Western Christianity into Catholic and Protestant churches and led to generations of conflict, including the Thirty Years’ War, which ended in 1648. It encouraged literacy, vernacular literature and the idea that individuals should read and judge for themselves, and it reshaped politics by strengthening rulers and states who broke with Rome. The Peace of Augsburg of 1555 let each German prince decide the religion of his lands.',
      'Luther’s legacy remains contested. Admirers point to his courage, his theology of grace, his hymns and his dignifying of family life. Historians also record his violent language against opponents, his support for princes against the peasants, and his writings against Jews, which became a source for later hatred. Any fair account has to hold all of these together.',
    ],
  },
  {
    slug: 'teresa-of-avila',
    order: 1515,
    dates: '1515 – 1582',
    place: 'Ávila and other cities of Castile, Spain',
    era: 'Early Modern',
    tradition: 'Carmelite mysticism',
    tagline: 'A Spanish nun who reformed her order, described the inner life of prayer with astonishing frankness, and became the first woman named a Doctor of the Church.',
    who: [
      'Teresa de Cepeda y Ahumada was born in 1515 in or near Ávila, in Castile, one of several children of a prosperous cloth merchant. Her paternal grandfather, Juan Sánchez, was a converso, a Jewish convert to Christianity, who in 1485 was brought before the Inquisition in Toledo, accused of secretly returning to Judaism, and made to do public penance. The family moved to Ávila, and in 1519–20 her father and uncles went to court to have their noble status confirmed. Teresa herself says little about this background in her writings, but it shaped her world, in which “purity of blood” was a social weapon.',
      'She grew up reading romances of chivalry and, at about twenty, entered the Carmelite convent of the Incarnation in Ávila. The convent was large and comfortable, with many visitors, and for years she struggled with illness and with her prayer. She describes a turning point in her late thirties, before an image of the wounded Christ, after which she began to experience visions and inner voices, which she reported to her confessors, who sometimes feared they came from the devil.',
      'In 1562 she founded a small convent, San José, in Ávila, run on stricter principles of poverty and prayer. She went on to found more than a dozen houses across Spain, travelling in rough carts, dealing with bishops, landowners and builders, and writing on the way. A rift opened between her reformed “Discalced” Carmelites and the older branch, and she was criticised by church officials, among them the papal nuncio. She died at Alba de Tormes in the night of 4 October 1582, the very night Spain switched to the Gregorian calendar and ten days were skipped, so that the next day was 15 October.',
    ],
    context: [
      'Sixteenth-century Spain was a Catholic monarchy that had expelled its Jews in 1492 and watched its converts, and later converted Muslims, for signs of insincerity. The Inquisition was active against alleged Protestants, false mystics and groups of spiritual enthusiasts called alumbrados. In 1559 the Inquisitor General published an index that banned many spiritual books in the vernacular, so that Teresa, a woman without Latin, had few books to learn from.',
      'The Council of Trent (1545–63) pushed monastic houses to return to discipline, and many reformers sought stricter observance. Teresa’s mix of inner prayer and practical reform belonged to this wider movement, but her life’s work was personal and unusual. She had to defend herself repeatedly against suspicion, because visions and a woman’s authority were both regarded with doubt.',
    ],
    ideas: [
      { title: 'Prayer as friendship', text: 'She described mental prayer as an intimate sharing between friends, taking time to be alone with the one who we know loves us. It is not a technique or a performance. In her book about her life, she compares the stages of prayer to four ways of watering a garden, from hauling buckets by hand to rain falling from heaven.' },
      { title: 'The Interior Castle', text: 'Written in 1577, it pictures the soul as a castle made of a single diamond or clear crystal, with seven sets of rooms, or dwelling places, and God at the centre. The task of prayer is to move inward, past distractions and fears, towards a union with God that she describes with psychological precision.' },
      { title: 'Self-knowledge and humility', text: 'For Teresa humility means truthfulness: knowing what you are and what you are not. She insists that no one can pray well without understanding themselves, and that grand spiritual experiences are worth little without charity towards others.' },
      { title: 'Mystical experience, with caution', text: 'She reports visions, voices, raptures and a famous experience of a spear piercing her heart, which later inspired Bernini’s sculpture. She also warns readers that these experiences are not the goal, can be delusions, and should be tested against Scripture and the advice of learned people. She wrote partly because her confessors told her to.' },
      { title: 'Practical reform', text: 'Her convents were small, poor and strictly enclosed, with no more than a limited number of nuns. She wanted women who prayed seriously, and she demanded good sense, cheerfulness and friendship in community life. A founder as well as a mystic, she handled contracts, lawsuits and money with remarkable skill.' },
    ],
    principles: [
      'Pray as you can, not as you think you should, since what matters is love.',
      'Know yourself honestly, and be humble without being timid.',
      'Judge a spiritual experience by what it does to your character and your care for others.',
      'Combine contemplation with practical work, because God, she said, is also among the pots and pans.',
      'Keep a sense of humour, even about holiness.',
    ],
    practice: [
      'Set aside a short, regular time to be quiet and attentive, with no agenda, and notice what rises.',
      'When you feel moved by something grand, test it by asking what it requires of you for the next person you meet.',
      'Take a large aim in small, repeated steps, as she did with each new foundation.',
    ],
    facts: [
      'In her Life she says that at the age of about seven she set off with her brother Rodrigo for “the land of the Moors” to be martyred, until an uncle met them on the road and brought them home.',
      'Her Life was examined by theologians and the Inquisition, which requested the manuscript in 1575. A leading theologian, Domingo Báñez, gave a favourable opinion, but the Inquisition kept the manuscript until after her death, and it was first printed in 1588 under the editorship of Fray Luis de León.',
      'In 1577 the papal nuncio, Felipe Sega, called her a restless, disobedient and stubborn woman, according to reports. In the same year her friend and collaborator John of the Cross was seized and imprisoned by members of the older branch of the order.',
      'She wrote The Way of Perfection for her nuns in the 1560s, and in a second version in 1569. The Interior Castle was written in 1577 in a few months.',
      'She was canonised in 1622 and, in 1970, Pope Paul VI named her a Doctor of the Church, the first woman to receive that title. Catherine of Siena was named a week later.',
      'A short poem found in her breviary, often called “Nada te turbe”, begins with the line “Let nothing disturb you”, and is attributed to her.',
    ],
    myths: [
      { myth: 'Teresa was an uneducated woman who simply recorded visions.', reality: 'She had little formal schooling and called herself ignorant, a convention for women writers of her time, but she was well read, shrewd and a gifted writer. She consulted learned confessors and rewrote her work carefully.' },
      { myth: 'She withdrew from the world.', reality: 'She spent her last twenty years travelling, founding convents, negotiating with officials and writing letters, several hundred of which survive. Her contemplation was meant to feed action.' },
      { myth: 'Her converso background was a secret she hid, or an unimportant detail.', reality: 'It was known in Ávila and probably mattered. Some modern scholars argue that it shaped her outlook on honour, social rank and the equality of souls, though how far is debated, since she rarely addresses it.' },
    ],
    works: [
      { title: 'The Book of Her Life (written c. 1562–65)', note: 'A spiritual autobiography written for confessors; first published in 1588.' },
      { title: 'The Way of Perfection (c. 1566)', note: 'Advice for her nuns on prayer and community life.' },
      { title: 'The Interior Castle (1577)', note: 'Her most mature work, on the stages of the inner life.' },
      { title: 'The Book of Foundations', note: 'An account of the founding of her convents.' },
      { title: 'Letters and poems', note: 'Hundreds of letters survive and show her practical, humorous side.' },
    ],
    legacy: [
      'Her reformed order, the Discalced Carmelites, grew across Europe and the world, and her writings became classics of Christian spirituality. John of the Cross, whom she helped to reform the men’s branch of the order, is the other great figure of Spanish mysticism. Her description of prayer influenced Catholic writers for centuries, and her works are read by many outside the Church for their psychological honesty.',
      'She is also remembered as a woman who lived and wrote under the eye of the Inquisition, and who made her way in a male-dominated institution through a mixture of obedience, charm and determination. Her canonisation and her title of Doctor of the Church recognised a legacy that her own century had often distrusted.',
    ],
  },
  {
    slug: 'etienne-de-la-boetie',
    order: 1530,
    dates: '1530 – 1563',
    place: 'Sarlat and Bordeaux, France',
    era: 'Early Modern',
    tradition: 'Political thought',
    tagline: 'A young French magistrate who asked why whole peoples obey a single tyrant, and who became immortal as Montaigne’s closest friend.',
    who: [
      'Étienne de La Boétie was born on 1 November 1530 in Sarlat, in the Périgord region of south-western France, into a family of magistrates. After his father’s early death he was brought up by an uncle, a priest, and he studied law at Orléans. In 1554, about two years under the usual minimum age, he was given a place as a councillor in the Parlement of Bordeaux, the regional high court, thanks to a special dispensation and his obvious talent.',
      'He was also a humanist and poet, who knew Greek and Latin and translated classical works. While still very young, he wrote a short treatise in French against tyranny, the Discourse on Voluntary Servitude, which is also called Contr’un, meaning “Against One”. Montaigne said it was written when La Boétie was about sixteen to eighteen, which would mean the late 1540s, but some modern scholars date it to around 1552–53, when he was a law student of about twenty-two. It was not printed in his lifetime.',
      'In about 1558 he met Michel de Montaigne, a fellow magistrate, and the two became close friends. In the early 1560s, as religious conflict grew, he was given official tasks and wrote a memorandum urging moderation and negotiation between Catholics and Protestants. In August 1563 he fell ill, probably with dysentery, with plague also around the region, and died after about ten days, at the age of thirty-two. Montaigne was with him, and described the death in a letter to his father.',
    ],
    context: [
      'France in the mid-sixteenth century was ruled by an increasingly powerful monarchy, which taxed heavily and extended its control over the provinces, with revolts, such as the salt-tax rising of 1548 in Guyenne, put down harshly. La Boétie was a royal official, but he saw such events up close, and the Bordeaux repression is often suggested as one trigger for his essay, though its date is uncertain.',
      'From 1562 the country fell into the wars of religion between Catholics and Huguenots. The Discourse later became a weapon in that struggle, which shows how a text written as a classical exercise by a young humanist could take on a political life of its own.',
    ],
    ideas: [
      { title: 'Why do people obey?', text: 'The essay opens with a puzzle: a tyrant has only the power his subjects give him, so why do millions serve one person? La Boétie answers that they are not forced all the time, they consent, though often without realising it. If they simply stopped supporting him, he would collapse, in his image like a great colossus whose base has been pulled away. The power of one over many exists because the many allow it.' },
      { title: 'Habit and custom', text: 'People born into servitude, he says, never learn what freedom is, and they take their condition for nature. Custom makes servitude seem normal. He cites the example of animals raised in captivity, which accept it, while wild ones do not.' },
      { title: 'Bread, circuses and rituals', text: 'Tyrants keep their subjects docile with spectacle, games and handouts, as Roman emperors did. They also surround themselves with symbols and religion to make their rule seem sacred. La Boétie mocks even French royal legends, such as the holy oil of Reims and the oriflamme, the king’s sacred banner.' },
      { title: 'The pyramid of dependence', text: 'A tyrant rules through a few favourites, each of whom has men below him, who in turn depend on others, so that a long chain of beneficiaries has an interest in keeping the system going. Servitude, in this view, is something many people take part in, and from which many profit.' },
      { title: 'Freedom and friendship', text: 'He holds that nature made humans equal enough to live as companions, and that friendship is impossible between a tyrant and his subjects, since friendship needs equality and trust. The cure for servitude is not violence but refusal: resolve to serve no more, and you are free.' },
    ],
    principles: [
      'Ask why a system continues, and notice your own part in keeping it going.',
      'Do not mistake habit for nature.',
      'Be wary of those who offer spectacle and comfort in exchange for obedience.',
      'Prefer withdrawal of support to destruction.',
      'Value friendship, which needs equality and trust, above power.',
    ],
    practice: [
      'Pick one rule or routine that you follow without question, and find out who set it and who benefits.',
      'Notice when you accept something because “it has always been this way”, and test it against a fresh start.',
      'Invest in a friendship where you can tell the truth, as La Boétie and Montaigne did.',
    ],
    facts: [
      'Montaigne wrote that he and La Boétie sought one another before they met, through reputation and through the Discourse, which Montaigne had read. In his essay “Of Friendship”, he explains their bond with the words “because it was he, because it was I”.',
      'Montaigne planned to put the Discourse in the middle of his first book of Essays, but it was printed by Protestant pamphleteers in the 1570s as a weapon against the French monarchy. He replaced it with La Boétie’s sonnets, and published his friend’s verse and translations in 1571.',
      'La Boétie left his books to Montaigne, who kept them in the tower library where he wrote the Essays.',
      'Montaigne and other early sources say the Discourse was written when La Boétie was sixteen to eighteen, though some modern scholars think he was older, around twenty-two, and the date remains uncertain.',
      'He wrote a short memorandum urging the French crown to try to pacify religious conflict through conciliation, which shows him as a loyal official, not a revolutionary.',
    ],
    myths: [
      { myth: 'He wrote “The great only seem great because we are on our knees.”', reality: 'The line is often attributed to him, but it is usually traced to a French revolutionary newspaper of 1790, not to the Discourse, which contains related ideas in different words.' },
      { myth: 'La Boétie was a revolutionary or an anarchist.', reality: 'He served the king as a magistrate and urged moderation during the religious wars. Anarchists, libertarians and radicals later claimed the Discourse, but it rejects tyranny without setting out a programme of government.' },
      { myth: 'The Discourse was published in his lifetime.', reality: 'It circulated in manuscript among friends and was first printed, in part, in Huguenot pamphlets in the 1570s, after his death.' },
    ],
    works: [
      { title: 'Discourse on Voluntary Servitude (Discours de la servitude volontaire)', note: 'His one famous work, written in French; first printed in 1574 and 1576 in Protestant collections.' },
      { title: 'Memorandum on the pacification of the troubles (1561–62)', note: 'A short political text urging moderation in the religious conflict.' },
      { title: 'Poems and translations', note: 'Edited by Montaigne after his death, and published in 1571.' },
      { title: 'Montaigne, Essays, I.28 “Of Friendship”', note: 'The main source on his character, and on how the Discourse survived.' },
    ],
    legacy: [
      'The Discourse was used by Huguenots against the Crown in the 1570s and later by republicans, and in the twentieth century it was read in very different ways. Libertarian writers such as Murray Rothbard saw an early case for withdrawing consent from the state. Others, such as Claude Lefort and Pierre Clastres, read it as a question about why societies produce domination, and it is often connected to ideas about nonviolent resistance and civil disobedience.',
      'Perhaps the most striking part of his legacy is the friendship. Montaigne’s account of their bond is one of the great pieces of writing on friendship, and it gave La Boétie a lasting place in French literature even though he died so young. Whether his treatise is a classroom exercise, a protest or a work of political philosophy, it keeps raising a question that most societies would rather not face: how much of our servitude do we choose?',
    ],
  },
]
