import type { Profile } from './types'

export const MORE_14: Profile[] = [
  {
    slug: 'akaki-tsereteli',
    order: 1840,
    dates: '1840 – 1915',
    place: 'Skhvitori, Imereti, and Kutaisi, Tbilisi and across Georgia',
    era: '19th Century',
    tradition: 'Georgian poetry and national thought',
    tagline: 'The poet of the Georgian people, whose verses became songs that a whole nation knows by heart.',
    who: [
      'Akaki Tsereteli was born on 21 June 1840 (9 June in the old Russian calendar) in the village of Skhvitori in Imereti, in western Georgia. His father, Rostom Tsereteli, was a prince, and his mother, Ekaterine Abashidze, descended from the royal line of Imereti. Following an old Georgian custom, he spent his early childhood in the household of a peasant family in the village of Savane, where he absorbed folk songs, tales and the speech of ordinary people. He later wrote about this upbringing with affection in his autobiography, “My Adventures” (Chemi tavgadasavali).',
      'He entered the Kutaisi classical gymnasium in 1852 and in 1859 went to St Petersburg to study oriental languages at the university. He left in 1862 without a diploma, partly because he had never taken the gymnasium certificate, and he came away with a lasting dislike of the Russifying school system. He had already begun to publish verse, and in 1860 a lyric called “The Secret Letter” (Saidumlo barati) was printed in the journal Tsiskari and soon spread as a song. In 1864 he married Natalia Bazilevskaya in Moscow, and they had a son, Alexei, who became a theatre and ballet impresario in Russia.',
      'Back in Georgia he chose to live by writing and public work instead of taking an official post. He spoke for the defendants at the trial that followed the Svaneti uprising of 1875–76, called attention to the manganese deposits of Chiatura, and in 1889 turned down the directorship of the Kutaisi land bank. He edited his own monthly, “Akaki’s Monthly Collection”, from 1897 to 1900, and in 1907 founded the satirical weekly Khumara, which was banned after its first issue. He died on 26 January 1915 by the old calendar (8 February in the modern one) at the age of seventy-four and was buried in the Mtatsminda Pantheon in Tbilisi.',
    ],
    context: [
      'Georgia was part of the Russian Empire for all of Akaki’s life, after the kingdoms of eastern and western Georgia had been annexed in the early nineteenth century. Imperial policy pressed Georgians to use Russian in schools and offices, and the old nobility was losing its land and its role. Out of this situation grew a generation of young Georgians who studied in Russian universities and came home determined to renew their own language, literature and public life. Their conservative critics nicknamed them the Tergdaleulebi, “those who drank the waters of the Terek”, because they had crossed the Terek river to study in Russia; the older generation was called the Mtkvardaleulebi, after the Mtkvari (Kura) river that flows through Georgia.',
      'The best-known leader of the Tergdaleulebi was Ilia Chavchavadze, and Akaki is usually counted among the “first group” that gathered around him, with the educator Iakob Gogebashvili and the writers Vazha-Pshavela and Aleksandre Qazbegi. Their programme combined cultural revival with the hope of a better life for peasants and townspeople. In 1879 they helped found the Society for the Spreading of Literacy among Georgians, which opened schools, printed textbooks and gathered manuscripts and folklore. Akaki was active in the Society, in the Georgian Dramatic Society and in the Georgian press, and he worked with Ilia on bringing the written language closer to the way people actually spoke.',
    ],
    ideas: [
      { title: 'Poetry in the language of the people', text: 'With Ilia Chavchavadze, Akaki helped reshape modern literary Georgian so that it sounded like living speech and folk song. His verse is flexible, musical and full of the rhythms of village life, and Georgian critics have long noted how easily his lines turn into songs. The critic Gerontii Kikodze called him the “selfless troubadour of Georgia”.' },
      { title: 'A song that carries a nation', text: 'His poem “Suliko”, published in 1895 in the journal Kvali, was set to music the same year by a relative, Varinka (Barbare) Tsereteli, and became one of the most loved songs in Georgia. The word suliko means roughly “little soul”. Readers have long argued about whom the poem addresses: critics have read the beloved as the homeland, as a woman and as God, and the poem supports all three readings.' },
      { title: 'History as a school of dignity', text: 'In historical poems and prose such as “Tornike Eristavi” (written in the 1880s), about the medieval Georgian commander who became a monk on Mount Athos, “Tamar the Cunning” and the prose tale “Bashi-Achuki” (1895–96), Akaki turned to the Georgian past to rebuild confidence in the present. Critics describe these works as patriotic and sometimes idealising the past, and they also carry a sharp criticism of his own day.' },
      { title: 'The folk tale as social satire', text: 'He retold the folk hero Natsarkekia, a clever youth who outwits stronger opponents, in the 1880s, and in 1899 wrote “Kudabziketi”, a fairy tale about an imaginary country full of Natsarkekias. Scholars point out that he gave the hero a physical weakness instead of simple laziness, so that wit and intelligence triumph over brute strength, and that the tale is a commentary on Georgian society.' },
      { title: 'Culture as public work', text: 'Akaki believed that a poet should also build institutions. He spoke and wrote for schools, the theatre, the press and the common people, and in the revolutionary year 1905 he published poems that welcomed political change and, in “Gurian Nana”, reacted to Russia’s defeat in the war with Japan. He was a patriot but also an advocate of friendship among peoples.' },
    ],
    principles: [
      'Speak and write so that ordinary people can understand and sing your words.',
      'Love your homeland without hating your neighbours.',
      'Use the past to strengthen the present, not to escape from it.',
      'Take part in the work of schools, theatres and newspapers, not only in poetry.',
      'Answer injustice with wit as well as with anger.',
    ],
    practice: [
      'Learn one poem or song in your own language by heart and notice how it ties you to other people who know it.',
      'Support a local library, school or cultural society, as the literacy societies of Akaki’s time did.',
      'When you want to criticise something, try a story or a joke first, as Akaki did with Natsarkekia.',
    ],
    facts: [
      'The poem “Suliko” appeared in 1895 in the journal Kvali, and Akaki is reported to have given the composer a portrait inscribed to his “beloved nightingale”. Varinka Tsereteli’s authorship of the melody was not always acknowledged: in 1937 an ensemble in Moscow presented the song as a folk song, and she had to work for years to be recognised as its composer.',
      'In 1912 the cinematographer Vasil Amashukeli filmed Akaki’s journey through Racha and Lechkhumi, from late July to early August, as the poet was welcomed by crowds in town after town. The film, “Journey of Akaki Tsereteli in Racha-Lechkhumi”, premiered in Kutaisi in September 1912 and is regarded as the first full-length documentary of Georgian cinema; only part of it survives.',
      'In the summer of 1889 he stayed for the first time at the home of the writer and economist Niko Nikoladze at Didi-Jikhaishi, in western Georgia, on the occasion of a christening.',
      'In 1908 Georgians celebrated the fiftieth anniversary of his literary and public work as a national event, and he was already widely called the “people’s poet”.',
      'He translated the “Internationale” into Georgian in 1906.',
      'The main avenue in Tbilisi and a metro station there carry his name.',
    ],
    myths: [
      { myth: 'Suliko is an anonymous folk song.', reality: 'It has named authors: the words are by Akaki Tsereteli (1895) and the melody is by Varinka Tsereteli. In 2025 Georgia’s National Agency for Cultural Heritage Preservation reportedly recognised the song as a monument of intangible cultural heritage.' },
      { myth: 'Suliko is just a love song to a woman, or Stalin’s favourite song for sure.', reality: 'Critics have read the poem as addressed to the homeland, to a beloved and to God. The claim that it was a favourite of Stalin is often repeated, but it is a reputation without solid documentation.' },
      { myth: 'Akaki Tsereteli was a revolutionary radical who followed Russian revolutionary writers.', reality: 'Georgian scholars stress that, unlike other Tergdaleulebi, he drew his inspiration from folklore, Georgian history and democratic and national aspirations, not from Russian revolutionary literature, though he welcomed the 1905 revolution in verse.' },
    ],
    works: [
      { title: 'Lyric poems and songs', note: 'Including “The Secret Letter” (1860), “Imeretian Nanina”, “Gurian Nana” and “Suliko” (1895). Many were set to music.' },
      { title: 'Historical poems', note: 'Including “Bagrat the Great” (1875), “Tornike Eristavi” (1880s) and “Tamar the Cunning” (1880s).' },
      { title: 'Bashi-Achuki (1895–96)', note: 'A historical prose tale and one of his best-known narratives; a Soviet film of the same name appeared in 1956.' },
      { title: 'My Adventures (Chemi tavgadasavali)', note: 'His autobiography, published in parts between the 1890s and 1909, which tells of his childhood among peasants and his education.' },
      { title: 'Gamzrdeli (“The Educator”)', note: 'A long philosophical poem of the late nineteenth century that he regarded as the best expression of his outlook.' },
    ],
    legacy: [
      'Akaki Tsereteli is, with Ilia Chavchavadze, counted among the founders of modern Georgian literature and of the modern literary language. His popularity during his own lifetime was unusual: crowds met him on his journeys, and the 1908 jubilee and the 1912 Racha-Lechkhumi journey were turned by the public into national festivals.',
      'Today his verses still circulate as songs at Georgian tables, in schools and abroad, where “Suliko” has been translated into many languages. He is buried among writers and public figures in the Mtatsminda Pantheon in Tbilisi, and his name remains a shorthand for the idea that poetry belongs to the people.',
    ],
  },
  {
    slug: 'jose-marti',
    order: 1853,
    dates: '1853 – 1895',
    place: 'Havana, Spain, Mexico, Guatemala, New York; killed at Dos Ríos, Cuba',
    era: '19th Century',
    tradition: 'Latin American independence thought',
    tagline: 'A poet and journalist who organised a war for Cuban freedom and died on its first weeks of fighting.',
    who: [
      'José Martí was born in Havana on 28 January 1853, the son of Spanish parents, and grew up in a Cuba still ruled by Spain, where slavery still existed. As a schoolboy he came under the influence of his teacher Rafael María de Mendive, a poet who supported Cuban independence. In October 1869, at sixteen, he was arrested after a letter was discovered that criticised a fellow student for joining the Spanish side. He was sentenced to six years of hard labour, and after his health suffered he was sent into exile in Spain.',
      'In Spain he studied law and philosophy and took degrees at Zaragoza, and he published an account of the Cuban political prison. He then lived in Mexico, Guatemala and, briefly, Venezuela, working as a teacher, journalist and editor. In 1880 he moved to New York, where he lived most of his remaining years, writing for newspapers across Latin America and serving as consul for Uruguay, Paraguay and Argentina. He published the poems of Ismaelillo (1882), a book for his young son, and in 1889 a magazine for children, La Edad de Oro.',
      'From 1892 he devoted himself to the cause of independence. He founded the Cuban Revolutionary Party and its newspaper Patria, and recruited support among Cuban exiles in New York and in the tobacco factories of Florida. In March 1895 he and General Máximo Gómez signed the Manifesto of Montecristi, and in April he landed on the Cuban coast with Gómez and a few others. On 19 May 1895, at Dos Ríos, he was killed in a clash with Spanish troops. He was forty-two.',
    ],
    context: [
      'Cuba and Puerto Rico were among the last remaining Spanish colonies in the Americas, after the mainland republics had won independence earlier in the century. Cuban rebels had fought the Ten Years’ War (1868–78) against Spain without winning independence, and slavery was abolished in Cuba only in 1886. Many Cubans, including a large community of exiles in Florida and New York, wanted another attempt.',
      'Martí also lived in a time when the United States was growing in economic and political power in the hemisphere. Some Cubans and Americans favoured annexation of Cuba, and Martí worried that Cuba might exchange one master for another. The war that he helped to launch in 1895 ended with Spain’s defeat after the United States entered in 1898, and Cuba became a formally independent republic in 1902, with the United States keeping considerable influence.',
    ],
    ideas: [
      { title: 'A republic “with all, and for the good of all”', text: 'Martí wanted independence to produce a republic open to every Cuban, whatever their colour or class, and not a regime run by one group. In speeches to exiles he stressed unity and justice, and he said that there was no race hatred because there were no separate races, only human beings. This stood in contrast to the racial divisions of the colonial order.' },
      { title: 'Nuestra América', text: 'In his essay “Nuestra América” (1891) he argued that the peoples of Latin America should know their own history, land and cultures instead of copying European or North American models. Good government, he wrote, had to be built from the real conditions of the country. The essay also warned against both European and American domination.' },
      { title: 'Poetry as sincerity', text: 'In Versos sencillos (1891) he wrote short, plain, musical verses about friendship, honour, death and exile. Some of those verses, beginning “Yo soy un hombre sincero”, were later adapted into the popular song “Guantanamera”. For Martí, poetry was a form of moral honesty.' },
      { title: 'A necessary, limited war', text: 'He prepared the war of 1895 with great care. He wanted it to be disciplined and to lead to a civil republic, and he feared that military rule would betray the cause.' },
      { title: 'Education for freedom', text: 'Martí held that knowledge and culture make people free. La Edad de Oro, written for the children of the Americas, introduced young readers to science, art, history and moral stories, in clear and lively prose.' },
    ],
    principles: [
      'Be sincere in your words, and let your actions match them.',
      'Work for a country in which all citizens count.',
      'Learn from your own history and land before you borrow from others.',
      'Prepare carefully before you act, and act when the cause is just.',
      'Educate children so that they can be free.',
    ],
    practice: [
      'Before you adopt an idea from abroad, ask whether it fits the place where you live.',
      'Read poetry aloud and choose a line as a guide to your day.',
      'Join, or help to build, a community organisation that brings different groups together.',
    ],
    facts: [
      'In 1869, aged sixteen, he was sent to hard labour in a quarry in Cuba before being exiled.',
      'The magazine La Edad de Oro was written almost entirely by Martí and ran for only four issues in 1889.',
      'He wrote for newspapers in Buenos Aires, Mexico and elsewhere, giving Latin American readers detailed reports on life in the United States.',
      'The day before his death he began a letter to his friend Manuel Mercado, in which he wrote that he was working to stop the United States from spreading across the Antilles. The letter was left unfinished.',
      'He is buried in Santa Ifigenia Cemetery in Santiago de Cuba.',
      'A bronze statue of Martí on horseback stands at the edge of Central Park in New York.',
    ],
    myths: [
      { myth: 'Martí was a revolutionary of the left, claimed by one side only.', reality: 'Both the Cuban government and its exile opponents claim his legacy. In 1953 Fidel Castro called Martí the intellectual author of the Moncada attack, while Cuban exiles in Miami honour him as a champion of liberty and democracy. His own writings are varied enough that each side finds support.' },
      { myth: 'Martí wrote the song “Guantanamera”.', reality: 'The tune comes from a Cuban popular song, and lines from his Versos sencillos were adapted to it only later. He did not compose the song.' },
      { myth: 'He was a soldier who died leading a charge in a large battle.', reality: 'He was the political leader of the independence movement and not a trained officer. He was killed in a skirmish at Dos Ríos barely a month after landing in Cuba, and accounts of the details differ.' },
    ],
    works: [
      { title: 'Ismaelillo (1882)', note: 'A short book of poems for his infant son, often seen as a beginning of Spanish American modernism.' },
      { title: 'Versos sencillos (1891)', note: 'Plain-spoken lyrics, the most widely read of his poetry.' },
      { title: 'Nuestra América (1891)', note: 'The essay that sets out his picture of Latin American identity and independence.' },
      { title: 'La Edad de Oro (1889)', note: 'A magazine for children, issued in four numbers.' },
      { title: 'Manifiesto de Montecristi (1895) and journalism', note: 'The manifesto, signed with Máximo Gómez, set out the aims of the war; his many newspaper chronicles are collected in his Obras completas.' },
    ],
    legacy: [
      'Cubans often call Martí the “Apostle” of independence, and his portrait and quotations appear throughout the island. Statues, schools and an international airport in Havana carry his name. He became a symbol that political movements of very different kinds have claimed for themselves, from the 1950s revolutionaries to Cuban exiles.',
      'Outside Cuba he is remembered as a major Spanish-language poet and essayist, and as a thinker who made the case for a Latin American identity that is independent of both Europe and the United States. His essays are widely read in universities, and his plain, musical poems remain among the most quoted in the Spanish language.',
    ],
  },
  {
    slug: 'emile-durkheim',
    order: 1858,
    dates: '1858 – 1917',
    place: 'Épinal, Bordeaux and Paris, France',
    era: '19th Century',
    tradition: 'Sociology',
    tagline: 'The scholar who argued that society can be studied as a science, and that it shapes us far more than we realise.',
    who: [
      'Émile Durkheim was born on 15 April 1858 in Épinal, in the Vosges region of eastern France. He came from a family of Jewish rabbis, but he chose a secular career, entering the École normale supérieure in Paris in 1879 and qualifying as a teacher of philosophy in 1882. After teaching in schools, he spent time in 1885–86 visiting German universities to learn how the human sciences were being studied there.',
      'In 1887 he was appointed to the University of Bordeaux, where he taught what was among the first social science courses in France, and in 1893 he published his doctoral thesis, The Division of Labour in Society. He followed it with The Rules of Sociological Method (1895) and Suicide (1897), and in 1898 he founded the journal L’Année sociologique, which gathered a team of younger scholars, among them his nephew Marcel Mauss. In 1902 he moved to the Sorbonne in Paris, where he later held the chair in education and sociology.',
      'He published his last major book, The Elementary Forms of Religious Life, in 1912. When the First World War began, he worked for the French cause, writing pamphlets and serving on committees, while many of his students and colleagues were killed. His son André died in December 1915 on the Balkan front, a loss from which Durkheim never recovered. He suffered a stroke and died in Paris on 15 November 1917, leaving unfinished work on morality.',
    ],
    context: [
      'Durkheim lived in the early Third Republic, a France that had lost the war with Prussia in 1870 and was divided over the place of the Church, the army and the Republic itself. The Dreyfus affair of the 1890s, in which a Jewish army officer was wrongly convicted of treason, forced intellectuals to take sides, and Durkheim, a Dreyfusard, defended individual rights as a moral principle of modern society.',
      'Industrialisation and the growth of cities were transforming how people lived and worked, and thinkers such as Auguste Comte and Herbert Spencer had already proposed a science of society. Durkheim set out to give this new discipline its own subject matter, methods and place in the university, and to show that it could help France rebuild a shared morality for a secular age.',
    ],
    ideas: [
      { title: 'Social facts', text: 'In The Rules of Sociological Method, Durkheim defined social facts as ways of acting, thinking and feeling that exist outside the individual and exert pressure on him or her: laws, customs, religious beliefs, languages and fashions. Because they are real and can be observed, he argued, they can be studied by comparison and statistics, which makes sociology a science distinct from psychology.' },
      { title: 'Solidarity and the division of labour', text: 'In small traditional societies, he suggested, people are held together by similarity, shared beliefs and shared life, which he called mechanical solidarity. In modern societies people do different jobs and depend on each other, which creates organic solidarity. For this to work, he argued, a society needs fair rules and a shared morality, not just markets.' },
      { title: 'Suicide and anomie', text: 'Using official statistics from several European countries, Durkheim showed that suicide rates vary with social conditions. He distinguished egoistic suicide (too weak a tie to the group), altruistic (too strong a tie), anomic (too little regulation of desires, as in sudden economic change) and fatalistic (too much regulation). Anomie, a state in which social norms lose their force, became one of the best-known words in sociology.' },
      { title: 'Religion as the expression of society', text: 'In The Elementary Forms of Religious Life, using ethnographic reports on Aboriginal Australian totemism, Durkheim argued that the sacred is a way in which a group represents itself, and that rituals renew the bonds among its members. He used the phrase collective effervescence for the heightened energy people feel in shared ceremonies. The book has been influential and also much criticised, especially for the quality of its evidence.' },
      { title: 'Education and secular morality', text: 'Durkheim lectured on moral education at the Sorbonne and argued that a modern, secular school should teach discipline, attachment to groups and a reasoned autonomy, so that children become both members of a society and independent thinkers. He saw teachers as key figures in handing on a society’s ideals.' },
    ],
    principles: [
      'Look for the social causes behind what seems purely personal.',
      'Treat social questions with evidence, not only with opinion.',
      'A free society still needs shared rules and a sense of belonging.',
      'Rituals and common symbols hold communities together, so take them seriously.',
      'Schools should form citizens as well as workers.',
    ],
    practice: [
      'When a trend worries you, such as loneliness or burnout, ask what changes in work, family or community could lie behind it.',
      'Take part in a shared ritual, such as a meal, a celebration or a commemoration, and notice how it affects the group.',
      'Check a claim about society against data before accepting it.',
    ],
    facts: [
      'Durkheim helped to establish sociology as an academic subject in France, beginning with his teaching at Bordeaux, where he gave one of the first university courses in social science.',
      'In Suicide he noted that, in the German states he studied, Protestants had higher suicide rates than Catholics, and he explained this by differences in social integration. Later researchers have disputed some of his data and methods.',
      'He took an active role in the Dreyfus affair as a supporter of Dreyfus, and in 1898 he published an essay defending the “cult of the individual” as the moral basis of modern society.',
      'Many of his colleagues at L’Année sociologique were killed in the First World War.',
      'The word anomie did not originate with him, but Durkheim made it a central term of social science.',
      'His lectures on moral education and on professional ethics were published only after his death.',
    ],
    myths: [
      { myth: 'Durkheim claimed that society matters and individuals do not.', reality: 'He insisted that social facts have their own reality, but he also defended individual dignity as the key value of modern societies and was a public defender of individual rights in the Dreyfus affair.' },
      { myth: 'Durkheim showed that religion is a mere illusion.', reality: 'He treated religion as a real social force that expresses the life of a community. He did not claim to settle whether any religious belief is true, and he thought that a modern society would need new forms of shared moral life.' },
      { myth: 'Suicide proved that society causes suicide in a simple, predictable way.', reality: 'The book is an early model of social research, but later scholars have criticised its use of official statistics and its reasoning from group rates to individual cases.' },
    ],
    works: [
      { title: 'The Division of Labour in Society (1893)', note: 'His doctoral thesis, on solidarity in traditional and modern societies.' },
      { title: 'The Rules of Sociological Method (1895)', note: 'A statement of what sociology should study and how.' },
      { title: 'Suicide (1897)', note: 'A pioneering empirical study of social causes and of anomie.' },
      { title: 'The Elementary Forms of Religious Life (1912)', note: 'His study of religion, ritual and the sacred.' },
      { title: 'Moral Education and Professional Ethics and Civic Morals', note: 'Lecture courses published after his death, on school and morality.' },
    ],
    legacy: [
      'Durkheim is considered, with Karl Marx and Max Weber, one of the founders of modern sociology. His ideas of social facts, solidarity and anomie are standard concepts, and his method of comparing statistics on different groups shaped the research of the twentieth century. His students and collaborators, including Marcel Mauss, carried the work into anthropology, history and religious studies.',
      'Later scholars have criticised parts of his work, including its stress on social order over conflict, and its dependence on limited evidence, but many of his questions remain alive: what holds a society together, how change affects well-being, and what role schools, rituals and shared values play in a free society.',
    ],
  },
  {
    slug: 'max-planck',
    order: 1858,
    dates: '1858 – 1947',
    place: 'Kiel, Munich, Berlin and Göttingen, Germany',
    era: '20th Century',
    tradition: 'Physics and philosophy of science',
    tagline: 'The physicist who introduced the quantum in 1900 and opened the door to modern physics, reluctantly.',
    who: [
      'Max Planck was born on 23 April 1858 in Kiel, and grew up in a scholarly family; his father was a professor of law. He studied physics in Munich and Berlin, receiving his doctorate in Munich in 1879 for a thesis on the second law of thermodynamics. After holding posts at Munich and Kiel, he became professor of theoretical physics at the University of Berlin in 1889, a position that he held until his retirement in 1926. He was also a gifted pianist and lover of music.',
      'On 14 December 1900 Planck presented to the German Physical Society a new formula for the radiation of a hot body, which he could explain only by assuming that energy is exchanged in small, separate portions, or quanta, in proportion to the frequency of the radiation. The constant of proportionality, now called Planck’s constant and written h, is about 6.626 × 10⁻³⁴ joule-seconds. He did not at first believe that this was physical reality and long regarded it as a mathematical device. He received the Nobel Prize in Physics for the year 1918, which was awarded in 1919.',
      'Planck also lived through great personal loss. His son Karl was killed at Verdun in 1916, and his daughters Grete and Emma each died in childbirth, in 1917 and 1919. He served as secretary of the Prussian Academy of Sciences and from 1930 as president of the Kaiser Wilhelm Society, the German research organisation. His Berlin home was destroyed by bombing in 1944, and in 1945 his son Erwin was executed for taking part in the resistance against Hitler. Planck died in Göttingen on 4 October 1947.',
    ],
    context: [
      'In the late nineteenth century many physicists believed that physics was almost complete. Newton’s mechanics, Maxwell’s electromagnetism and thermodynamics explained most known phenomena. One puzzle was the spectrum of light given off by a hot body, the “black-body radiation” problem, where the existing formulas matched the measurements only in part of the spectrum. Planck worked on the problem as a question of fundamental theory, tied to the laws of thermodynamics.',
      'Planck’s quantum was only the start. In 1905 Albert Einstein used the idea to explain the photoelectric effect and proposed that light itself comes in quanta, and in the 1910s and 1920s Niels Bohr, Werner Heisenberg, Erwin Schrödinger and others built quantum mechanics. Planck, who was a conservative by temperament, supported Einstein from an early date, and he brought him to Berlin in 1914, but he was uneasy about the radical turns of the new physics.',
    ],
    ideas: [
      { title: 'Energy comes in quanta', text: 'To fit the observed spectrum of a hot body, Planck proposed that the oscillators that emit and absorb radiation can only change their energy in steps of size hν, where ν is the frequency and h a new constant of nature. This is the origin of quantum theory. Planck himself later described his step as an act of desperation, taken because he could find no other way to match the data.' },
      { title: 'A constant that sets a scale', text: 'The constant h fixes the scale at which quantum effects become important. In everyday life it is so small that we do not notice it, but in atoms it is decisive. Together with other constants it also defines the “Planck units”, which he proposed in 1899 as a natural system of measurement not tied to human conventions.' },
      { title: 'Science and the search for the absolute', text: 'Planck held that physics aims at a picture of the world that is independent of the observer, and he found in the laws of nature, such as the principle of least action, evidence of an underlying order. This conviction made him sceptical of views that reduced science to convenient description.' },
      { title: 'Science and religion are not enemies', text: 'Planck was a member of the Lutheran church and described himself as deeply religious. In lectures and essays, such as his 1937 lecture on religion and natural science, he argued that science and religion do not exclude each other but supplement each other: science deals with what can be measured, and religion with values and meaning.' },
      { title: 'Duty and the integrity of the scholar', text: 'He saw research as a vocation to be pursued with honesty, patience and a sense of duty to the community, and in public life he argued for the independence and international character of science.' },
    ],
    principles: [
      'Follow the evidence, even when it contradicts what you expected.',
      'Do not mistake a successful calculation for understanding, and keep asking what it means.',
      'Keep science and faith each in their proper place, and do not set them at war.',
      'Serve institutions that outlast individuals.',
      'Carry out your duty with steadiness in difficult times.',
    ],
    practice: [
      'When a result surprises you, resist the urge to hide it and look for what it could mean.',
      'Set aside time for something outside work, such as music, as Planck did.',
      'Support colleagues and younger people, as Planck did for Einstein, even when you do not agree with every idea.',
    ],
    facts: [
      'The quantum hypothesis was first presented on 14 December 1900, which is often taken as the birthday of quantum theory.',
      'In 1914 Planck signed the “Appeal to the Civilised World”, a manifesto of German academics that defended Germany’s conduct in the early part of the First World War.',
      'In May 1933 he met Adolf Hitler to plead for Jewish scientists, and argued that forced emigration would harm German science. The meeting achieved nothing. In 1934 he organised a commemorative meeting for his Jewish colleague Fritz Haber, who had died in exile, and the Kaiser Wilhelm Society kept some Jewish researchers employed for a time.',
      'He served as president of the Kaiser Wilhelm Society from 1930 until the mid-1930s, and again as interim president from May 1945 to March 1946. In 1948 the society was renamed the Max Planck Society in his honour.',
      'His son Erwin, a former state secretary, was arrested after the failed plot of 20 July 1944 and executed at Plötzensee prison on 23 January 1945. Planck had written to Hitler asking for mercy; the request was not granted.',
      'Planck and Einstein were friends who played music together, with Planck at the piano and Einstein on the violin.',
    ],
    myths: [
      { myth: 'Planck knew that he had discovered a new kind of physics.', reality: 'He introduced the quantum as a mathematical device and spent years trying to fit it into classical physics. Einstein, Bohr and others developed its full meaning.' },
      { myth: 'Planck said that “science advances one funeral at a time”.', reality: 'The popular phrase is a paraphrase of a passage in his Scientific Autobiography, where he wrote that a new scientific truth wins not by convincing its opponents but because they eventually die and a new generation grows up familiar with it.' },
      { myth: 'Planck was either a Nazi collaborator or a brave resistance figure.', reality: 'Historians describe a more complicated picture. He tried to protect colleagues and institutions, interceded for some Jewish scientists and lost his son to Nazi justice, but he also remained in office, avoided open public protest and led a society that carried out the anti-Jewish civil-service laws. The biographer J. L. Heilbron describes him as a conservative who tried to keep science going within a regime he disliked.' },
    ],
    works: [
      { title: 'On the Law of Distribution of Energy in the Normal Spectrum (1901)', note: 'The paper in which he published his radiation law and the quantum hypothesis.' },
      { title: 'Treatise on Thermodynamics', note: 'A textbook that long served as a standard text in the subject.' },
      { title: 'Where Is Science Going? (1932)', note: 'A collection of essays on science, causality and free will, with a preface by Albert Einstein.' },
      { title: 'Religion and Natural Science (1937)', note: 'A lecture on the relation between science and religion.' },
      { title: 'Scientific Autobiography and Other Papers (1948)', note: 'His reflections on his career, published after his death.' },
    ],
    legacy: [
      'Planck’s constant stands at the base of quantum mechanics, which underlies chemistry, electronics, lasers and much of modern technology. Since 2019 the constant h has been fixed by definition at 6.62607015 × 10⁻³⁴ joule-seconds, and it is used to define the kilogram. Planck units and the Planck length are standard terms in theoretical physics.',
      'After the Second World War the Kaiser Wilhelm Society was refounded as the Max Planck Society, which today runs dozens of research institutes in Germany and abroad. The name ties his scientific example to an institution that has also had to examine its own role in the Nazi period.',
    ],
  },
  {
    slug: 'john-dewey',
    order: 1859,
    dates: '1859 – 1952',
    place: 'Chicago and New York, United States',
    era: '20th Century',
    tradition: 'Pragmatism',
    tagline: 'The philosopher who argued that we learn by doing, and that democracy is a way of living together.',
    who: [
      'John Dewey was born on 20 October 1859 in Burlington, Vermont. He studied at the University of Vermont, taught school for a time, and received his doctorate in philosophy from Johns Hopkins University in 1884. He then taught at the University of Michigan and from 1894 at the University of Chicago, where he led the philosophy, psychology and education department and, in 1896, opened the University Elementary School, soon known as the Laboratory School, with his wife Alice Chipman Dewey.',
      'After a dispute over the school with the university’s administration, he moved in 1904 to Columbia University in New York, where he taught until 1930. His major books include The School and Society (1899), How We Think (1910), Democracy and Education (1916), Human Nature and Conduct (1922), Experience and Nature (1925), The Public and Its Problems (1927), Art as Experience (1934), A Common Faith (1934) and Experience and Education (1938). He lectured in Japan and China from 1919 to 1921, and he also visited Turkey, the Soviet Union and Mexico.',
      'Dewey was also a public citizen. He took part in the founding of the American Association of University Professors, of which he was the first president, was an early supporter of the NAACP and the American Civil Liberties Union, and helped to start the New School for Social Research in 1919. In 1937, at the age of seventy-seven, he went to Mexico to chair a commission that examined the charges made against Leon Trotsky at the Moscow Trials. He died in New York on 1 June 1952, aged ninety-two.',
    ],
    context: [
      'Dewey’s America was changing rapidly, with industrial growth, mass immigration, big cities and new debates about the purpose of public schools. At the same time, Darwin’s theory of evolution was reshaping how educated people thought about nature and the mind. Dewey joined the pragmatist movement of Charles Sanders Peirce and William James, who held that ideas should be understood by their practical consequences and as tools for coping with the world.',
      'In the twentieth century, Dewey saw democracy challenged by economic inequality, world wars, and the rise of Communism and Fascism. His writing on education and public life tried to answer a question that he believed mattered more than any doctrine: how can ordinary people learn to think and act together intelligently?',
    ],
    ideas: [
      { title: 'Ideas are tools', text: 'Dewey held that thinking begins with a real problem, and that ideas are proposals to be tested by what happens when we act on them. He called this approach instrumentalism or experimentalism. Knowledge is therefore not a copy of reality made by a detached observer but the result of an active inquiry.' },
      { title: 'Learning by doing', text: 'In education, he argued that children learn best when they take part in real, meaningful activity, building, cooking, gardening and investigating, and are guided by teachers who connect these activities with the subjects of the curriculum. In the Laboratory School, the school was meant to be a small community, not a place of passive listening.' },
      { title: 'Democracy as a way of life', text: 'In Democracy and Education he described democracy as more than a form of government: it is a mode of shared living and communicated experience, in which people take part in shaping the conditions of their lives. Schools should be places where children practise this kind of life.' },
      { title: 'The public and its problems', text: 'In The Public and Its Problems he asked how citizens in a large, complex, industrial society can understand the effects of social action and govern themselves. His answer stressed free communication, local community life and the use of social science, so that the public can recognise its common interests.' },
      { title: 'Art and experience', text: 'In Art as Experience he argued that art is not confined to museums, but grows out of ordinary experience when it becomes unified and fully felt. The work of art, for him, is completed in the experience of those who engage with it.' },
    ],
    principles: [
      'Treat each problem as an occasion for inquiry, and test your ideas in action.',
      'Learn through experience, and reflect on it.',
      'Take part in the community you wish to improve.',
      'Do not separate thought from action, or school from life.',
      'Keep your beliefs open to revision.',
    ],
    practice: [
      'Choose a problem you face, state it clearly, list several possible solutions and try the most promising one as an experiment.',
      'When learning something new, apply it quickly in a project and review what happened.',
      'Join a local group or council in which people with different views discuss a shared issue.',
    ],
    facts: [
      'The Laboratory School in Chicago opened in January 1896, and was run with his wife Alice Dewey.',
      'He is not related to Melvil Dewey, the librarian who created the Dewey Decimal system.',
      'The commission he chaired held hearings at Trotsky’s home in Coyoacán, Mexico City, in April 1937, and reported in September 1937 that the Moscow Trials were frame-ups and that Trotsky was not guilty of the charges. Dewey said that the inquiry was about the evidence and not about sympathy with Trotsky.',
      'He spent about two years in China, from 1919 to 1921, giving lectures that influenced Chinese educators such as Hu Shih.',
      'In 1915 he became the first president of the American Association of University Professors.',
      'He kept writing and publishing into his nineties.',
    ],
    myths: [
      { myth: 'Dewey wanted children to do whatever they liked.', reality: 'In Experience and Education (1938), he criticised both rigid traditional schooling and the excesses of some progressive schools. He held that real freedom requires guidance, structure and a connection to subject matter.' },
      { myth: 'Pragmatism means doing whatever works for you.', reality: 'For Dewey, “what works” was to be tested publicly by inquiry and judged by its consequences for a community, not by private advantage.' },
      { myth: 'Dewey invented the Dewey Decimal System.', reality: 'That was Melvil Dewey, an unrelated American librarian.' },
    ],
    works: [
      { title: 'The School and Society (1899)', note: 'Lectures on the Laboratory School and the role of schooling in a changing society.' },
      { title: 'Democracy and Education (1916)', note: 'His major book on education and democratic life.' },
      { title: 'The Public and Its Problems (1927)', note: 'On democracy, communication and the modern state.' },
      { title: 'Art as Experience (1934)', note: 'His philosophy of art and aesthetic experience.' },
      { title: 'Experience and Education (1938)', note: 'A short, clear restatement of his educational ideas and a critique of both traditional and progressive extremes.' },
    ],
    legacy: [
      'Dewey is counted, with Peirce and James, as one of the three classical American pragmatists, and his writings influenced philosophy, psychology, political theory, aesthetics and, above all, education. Ideas such as project-based learning, learning from experience and schools as democratic communities trace back to him, though they have often been applied in ways that he might not have recognised.',
      'His reputation has gone through phases, with strong interest in the mid-twentieth century, a decline after the Second World War and a revival from the 1980s, when philosophers such as Richard Rorty and Hilary Putnam drew on his work. His questions about how education can prepare people for democratic life remain at the centre of debates about schooling.',
    ],
  },
]
