import type { Profile } from './types'

export const MORE_03: Profile[] = [
  {
    slug: 'nagarjuna',
    order: 150,
    dates: 'c. 150 – c. 250 AD (uncertain)',
    place: 'Southern India',
    era: 'Ancient',
    tradition: 'Madhyamaka Buddhism',
    tagline: 'The Buddhist philosopher who argued that nothing has a fixed nature of its own, and that this is exactly why things can exist at all.',
    who: [
      'Almost nothing about Nagarjuna’s life is certain. Most scholars place him around 150–250 AD, probably in southern India, and the Stanford Encyclopedia of Philosophy notes that very little can be said precisely about his biography. The stories we have come from Chinese and Tibetan sources written long after his time, among them a biography preserved in Chinese and traditionally linked to the translator Kumarajiva, who worked around 400 AD. These accounts are hagiography, the kind of writing that honours a saint, and they are full of legend.',
      'One famous legend says that the nagas, serpent-like beings of Indian myth, guarded the Perfection of Wisdom sutras underwater, and that Nagarjuna brought them to the human world. His name, which joins “naga” to “arjuna”, is sometimes taken to hint at that story. Tradition also says he came from a Brahmin family, studied the Buddhist teachings in depth and later lived near a king of the Satavahana dynasty, who ruled much of central and southern India. Treat all of this as tradition, not as established fact.',
      'What is solid is the body of writing. A handful of works are widely accepted as his, above all the Mulamadhyamakakarika, “Fundamental Verses on the Middle Way”, about 450 verses in 27 chapters. Care is needed because later tradition attached his name to many other texts, and later tradition also knows a tantric and alchemical Nagarjuna who is probably a different person, living centuries afterwards. Scholars try not to merge these authors into one.',
    ],
    context: [
      'Buddhism had existed for several centuries by Nagarjuna’s day, and it had split into many schools. Some of the Abhidharma traditions, which analysed experience into basic elements called dharmas, held that these elements have an “own-nature” (svabhava), a real core that makes each one what it is. Alongside them a newer movement, the Mahayana, was spreading texts such as the Perfection of Wisdom sutras, which declared that all things are empty. That movement was not his invention, and it was already underway before him.',
      'Nagarjuna also wrote in a lively debate with non-Buddhist Indian schools such as Nyaya, which defended the reality of knowledge, causes and a self. His task was to show that the Buddha’s teaching of dependent origination, the claim that everything arises in dependence on other things, is incompatible with any belief in fixed, self-standing natures. In doing so he gave the Mahayana its most rigorous philosophical form.',
    ],
    ideas: [
      { title: 'Emptiness (shunyata)', text: 'For Nagarjuna, to be empty means to be empty of svabhava, of an intrinsic nature that exists independently. It does not mean that nothing exists. A table has no essence that would let it be a table apart from its parts, its uses, its makers and the words we apply to it. Everything we meet is like this, so nothing is a self-sufficient foundation on which the rest could stand.' },
      { title: 'Dependent origination', text: 'Things arise and vanish in dependence on causes, conditions, parts and our concepts. Nagarjuna links this with emptiness in a well-known verse of the Mulamadhyamakakarika: whatever is dependently arisen is called emptiness, and that is a dependent designation, which is the middle way. Emptiness is not a deeper reality behind things. It is simply the fact that things depend on other things.' },
      { title: 'The two truths', text: 'He distinguishes a conventional truth, in which we speak of persons, tables, causes and moral laws, from an ultimate truth, in which nothing has an intrinsic nature. He insists the two are not rivals. Without the conventional level, he says, the ultimate cannot be taught, and without understanding the ultimate, liberation is not reached. Ordinary life and ethics therefore keep their place.' },
      { title: 'Arguments that dissolve our assumptions', text: 'His main method is to take a concept such as causation, motion, time, fire and fuel, or the self, and test the possible ways it could work. If a cause makes its effect, does the effect already exist in the cause, or not, or both, or neither? Each option, he argues, leads to absurdity when pushed. The aim is not to destroy ordinary talk but to show that our attempts to ground it in fixed natures fail.' },
      { title: 'Emptiness is not a view to hold', text: 'He warns that emptiness itself must not become a doctrine to cling to. Emptiness was taught, he says, to remove all views, and those who turn it into a view are beyond help. In a short work, the Vigrahavyavartani, he replies to the charge that if everything is empty then his own words are empty too: yes, he says, his words have no intrinsic nature either, and that is no problem. Seeing this ends the grasping that causes suffering, which is the point of the whole project.' },
    ],
    principles: [
      'Hold your concepts lightly, because they depend on conditions and on how we use them.',
      'Do not mistake what is useful for what is ultimate, or the reverse.',
      'Avoid the two extremes: that things have fixed natures, and that nothing matters.',
      'Treat even your best theory as a tool and not as something to cling to.',
      'Let insight into interdependence become kindness, since nothing stands alone.',
    ],
    practice: [
      'When you label someone “lazy” or “brilliant”, ask what conditions produced that behaviour, and whether it could change.',
      'Next time you are sure that a thing is simply what it is, look at its parts, causes and uses, and notice how far the name depends on them.',
      'Notice when you are defending an idea mainly because it is yours, and practise stating it as one useful view among others.',
    ],
    facts: [
      'The Mulamadhyamakakarika has about 450 verses and 27 chapters, which examine topics such as causation, motion, the self, time and nirvana.',
      'One of its most startling verses says that there is no real difference between samsara, the cycle of rebirth, and nirvana. The point is that both are empty of intrinsic nature, not that suffering does not matter.',
      'The Ratnavali, “Precious Garland”, is a work of ethical and practical advice to a king, which shows that his philosophy was meant to guide conduct.',
      'The Letter to a Friend (Suhrllekha), a poem of counsel to a king, was much loved in Tibet and in China.',
      'The site Nagarjunakonda in Andhra Pradesh, “Nagarjuna’s hill”, carries his name by later tradition, though the link between the philosopher and the place is uncertain.',
      'Later schools in India, Tibet and China all built on him: Candrakirti in India, Tsongkhapa in Tibet and the Sanlun school in China are among the best known.',
    ],
    myths: [
      { myth: 'Nagarjuna taught that nothing exists, so he was a nihilist.', reality: 'He rejected nihilism as firmly as he rejected belief in fixed natures. Things exist conventionally, depend on conditions and have effects. What he denied is that they exist with an independent, unchanging essence.' },
      { myth: 'Nagarjuna founded Mahayana Buddhism.', reality: 'The Mahayana movement and its sutras existed before him. He is better described as the founder of the Madhyamaka school, which gave the Mahayana a systematic philosophy.' },
      { myth: 'Every text with Nagarjuna’s name on it is by him.', reality: 'Many works were later attributed to him. A very large commentary on the Perfection of Wisdom, preserved in Chinese, is traditionally his, but many scholars doubt it, and the tantric and alchemical Nagarjuna of later centuries is probably a different person.' },
    ],
    works: [
      { title: 'Mulamadhyamakakarika', note: 'His central work, in about 450 verses, on causation, the self, time, nirvana and the middle way.' },
      { title: 'Vigrahavyavartani (Averting the Arguments)', note: 'A reply to critics who said that emptiness undermines all reasoning and knowledge.' },
      { title: 'Ratnavali (Precious Garland)', note: 'Advice to a king on ethics and on liberation, written in verse.' },
      { title: 'Suhrllekha (Letter to a Friend)', note: 'A short poem of Buddhist advice, preserved in Tibetan and Chinese.' },
      { title: 'Sources for his life', note: 'Chinese and Tibetan biographies written long after his death. They are our main stories about him, and they are legendary in character.' },
    ],
    legacy: [
      'Candrakirti, Buddhapalita and Bhaviveka in India developed competing readings of the Mulamadhyamakakarika, and their disputes shaped Madhyamaka philosophy. In Tibet, Madhyamaka became the standard view in most schools, and in China the Sanlun school, “Three Treatise”, carried his arguments into East Asian Buddhism.',
      'Modern philosophers have compared his work with Hume, Wittgenstein and contemporary debates about whether any ultimate foundation exists. Such comparisons are open to argument, but they show that his questions still seem live. Among Buddhists he is revered as one of the most important thinkers after the Buddha himself.',
    ],
  },
  {
    slug: 'origen',
    order: 185,
    dates: 'c. 185 – c. 253 AD',
    place: 'Alexandria, Egypt, and Caesarea in Palestine',
    era: 'Ancient',
    tradition: 'Christian Platonism',
    tagline: 'A brilliant and controversial scholar who tried to read the Bible with the full tools of ancient learning, and who was condemned after his death.',
    who: [
      'Origen was born around 185 AD in Alexandria, the great Greek-speaking city of Roman Egypt, into a Christian family. His father Leonides was a teacher, and according to Eusebius, the fourth-century church historian who is our main source, Leonides was executed in the persecution of 202. Origen was about seventeen. Eusebius adds that he wanted to die with his father and was stopped only when his mother hid his clothes. Since the whole account comes from Eusebius, who admired Origen, some details may be shaped by admiration.',
      'He supported the family by teaching and became a leading teacher at the Christian catechetical school in Alexandria, where candidates were taught the faith. He studied Greek philosophy as well, and tradition says he heard the philosopher Ammonius Saccas. A wealthy convert named Ambrose provided secretaries and copyists so that Origen could produce large numbers of writings. Around 231 he left Alexandria after a dispute with Bishop Demetrius, who objected to his ordination in Palestine, and settled in Caesarea, where he taught, preached and wrote.',
      'In the persecution under the emperor Decius, around 250, Origen was imprisoned and tortured. He survived, and he died a few years later, around 253, probably in Tyre. He lived into his late sixties, and left a body of writing that later ancient authors counted in the thousands of works, a figure we cannot check but which shows his reputation for sheer output.',
    ],
    context: [
      'In the second and third centuries, Christians were a minority in the Roman Empire, sometimes tolerated and sometimes persecuted. They also had to explain themselves to educated pagans, who often thought the faith crude. Alexandria, with its enormous library and its mix of Greek, Jewish and Egyptian learning, was one of the best places in the empire to meet that challenge, and it had already produced the Jewish philosopher Philo and the Christian teacher Clement.',
      'The culture of the day was strongly influenced by Platonism, which taught that the visible world depends on a higher spiritual order. Origen did not simply adopt Platonism. He used its language, and many of its ideas about the soul and about God, to explain Christian belief, while rejecting parts that clashed with Scripture. He also lived before the great church councils, so many doctrines, such as the exact relation of the Son to the Father, were still being discussed openly.',
    ],
    ideas: [
      { title: 'Scripture has several levels', text: 'Origen taught that the Bible has a literal meaning, a moral meaning for the soul and a deeper spiritual meaning, an analogy to body, soul and spirit. Where the literal sense seemed unworthy of God or contradictory, he read the passage allegorically. Critics have argued that this allows readers too much freedom, but he wanted to show that every verse could teach something about God.' },
      { title: 'Careful scholarship on the text', text: 'He insisted that reading the Bible well begins with knowing what it actually says. In the Hexapla he set out the Old Testament in parallel columns, apparently the Hebrew text, the Hebrew in Greek letters and several Greek versions, so that readers could compare differences. Few copies of the whole work existed, and it has mostly been lost, but it was an early landmark in textual criticism.' },
      { title: 'God, the Word and the Spirit', text: 'In On First Principles, the first systematic Christian theology we have, he describes God as invisible and incorporeal, the Son as eternally begotten from the Father and the Holy Spirit as part of the divine life. Later theologians thought some of his language placed the Son too far below the Father, but Origen helped to create the vocabulary that the later debates used.' },
      { title: 'Souls, freedom and a drama of return', text: 'He held that every rational being is free, and that moral failure is the result of free choices. He also speculated that souls existed before their earthly lives and fell away from God to different degrees, and that all will eventually return to God. Origen presents some of these views as questions for discussion and not as settled teaching, and scholars still argue about how firmly he held them.' },
      { title: 'Answering the critics', text: 'In Contra Celsum, written around 248, he answers a pagan philosopher named Celsus point by point. He defends the Christian life as morally serious, argues that Christians support the empire through prayer even though they will not fight, and uses the arguments of Greek philosophy where he can. It is one of the earliest great works of Christian apologetics.' },
    ],
    principles: [
      'Read carefully before you interpret, and know the text first.',
      'Look beyond the surface when the surface does not make sense.',
      'Treat free will as real, and take responsibility for your choices.',
      'Use the best learning of your age instead of fearing it.',
      'Answer an opponent’s actual arguments, not a weaker version of them.',
    ],
    practice: [
      'Before arguing about a text, a law or a message, compare more than one version of it, the way he did with the Hexapla.',
      'When a passage seems to contradict itself, ask what larger purpose it might serve, and then test your answer against the rest of the work.',
      'Summarise a critic’s position in terms they would accept before you reply to it.',
    ],
    facts: [
      'The Hexapla takes its name from its six main columns, and it has mostly been lost. Parts survive in later quotations and in fragments.',
      'On First Principles survives mostly in a Latin translation by Rufinus, made around 398, who admitted that he smoothed some passages, so we cannot always be sure of Origen’s exact wording.',
      'Contra Celsum, in eight books, quotes so much of Celsus’s lost work, The True Doctrine, that it is the main way we know it.',
      'According to Eusebius, Origen taught himself Hebrew, which was unusual for a Christian of his time.',
      'Eusebius says that Ambrose provided stenographers and copyists, so that Origen’s lectures could be recorded.',
      'He was condemned long after his death. Emperor Justinian issued an edict against his teachings around 543, and later church councils, probably including that of 553, condemned some views linked to his name, though historians debate how closely these views match what he actually wrote.',
    ],
    myths: [
      { myth: 'Origen castrated himself and so was a fanatic.', reality: 'Eusebius reports that, taking a saying of Jesus literally, Origen castrated himself when young. Many modern scholars doubt the story, partly because Origen himself later criticised the literal reading of that saying in his commentary on Matthew. It may have been a rumour spread by his opponents, and it is best treated as an unproven report.' },
      { myth: 'Origen was condemned as a heretic during his lifetime.', reality: 'Bishop Demetrius censured him over his ordination, and some local opposition existed. But the formal condemnations of his teachings came in the sixth century, long after his death, and many leading churchmen between those dates admired him, including Gregory of Nyssa and, for a time, Jerome.' },
      { myth: 'Origen simply mixed Christianity with Greek philosophy.', reality: 'He used philosophy as a tool, but he argued from Scripture and the church’s teaching, and he rejected views, such as the transmigration of souls into animal bodies, when he thought they conflicted with them.' },
    ],
    works: [
      { title: 'On First Principles (Peri Archon)', note: 'The first systematic Christian theology, on God, the world, freedom and the end of all things. It survives mainly in Rufinus’s Latin.' },
      { title: 'Contra Celsum (Against Celsus)', note: 'A defence of Christianity against a pagan critic, in eight books, written around 248.' },
      { title: 'Hexapla', note: 'A giant parallel edition of the Old Testament. Mostly lost.' },
      { title: 'Commentaries and homilies on Scripture', note: 'Large numbers of commentaries and sermons on books of the Bible. Many survive only partly or in translation.' },
      { title: 'Eusebius, Church History, Book VI', note: 'The principal ancient biography. It is admiring, and it is our main source for the stories about his life.' },
    ],
    legacy: [
      'Origen shaped Christian reading of the Bible for a thousand years. The idea of several levels of meaning ran through medieval interpretation, and the Cappadocian Fathers, Basil, Gregory of Nazianzus and Gregory of Nyssa, took much from him. He also stands near the beginning of Christian scholarship, in the sense that he treated textual and historical study as part of faith.',
      'His reputation, however, divided the church. Controversies in the fourth and sixth centuries left some of his speculative ideas condemned, and many of his works were neglected or copied only in translation. Modern scholars have worked to separate what Origen actually wrote from what was later attributed to him, and he is now often seen as one of the most creative minds of early Christianity.',
    ],
  },
  {
    slug: 'adi-shankara',
    order: 700,
    dates: 'traditionally 788 – 820; modern scholars c. 700 – 750',
    place: 'Kalady in Kerala, and travels across India',
    era: 'Medieval',
    tradition: 'Advaita Vedanta',
    tagline: 'The Indian philosopher and monk who taught that the self and the ultimate reality are one.',
    who: [
      'Adi Shankara, also called Shankaracharya, was born, according to tradition, in Kalady in what is now Kerala. The dates 788–820 AD were long standard, but many modern scholars favour the first half of the eighth century, roughly 700–750. Some traditional monasteries claim a far earlier date. The exact period is therefore uncertain, and so is nearly everything about his life.',
      'The biographies were written centuries later, and they are full of legend. They say that he was a prodigy who mastered the Vedas as a child, that he persuaded his mother to let him become a renunciant monk, and that he studied under Govinda Bhagavatpada, a pupil of Gaudapada, whose verses on the Mandukya Upanishad were an important earlier source of the non-dual teaching. They then describe him walking across India, debating rivals, such as the Mimamsa scholar Mandana Mishra, and writing his commentaries.',
      'The same traditions say that he died young, at about thirty-two, though the place is given differently, Kedarnath in the Himalayas in some accounts. Scholars note that Shankara was little known for several centuries after his death, and that the picture of a great founding saint was largely built later, notably in the Vijayanagara period, around the fourteenth century. What stands on firmer ground is his writing.',
    ],
    context: [
      'In early medieval India, Hindu traditions lived alongside Buddhism and Jainism, and alongside many local cults. Scholars of Mimamsa taught that liberation and good order come from correct performance of Vedic ritual. Buddhists argued that there is no permanent self. Shankara’s project was to defend the Upanishads, the late Vedic texts about knowledge, as teaching a single reality, while answering these rivals.',
      'Philosophical argument was a public art, with formal debates between schools. His opponents sometimes accused him of being a “crypto-Buddhist”, a hidden Buddhist, because his picture of a world that is not ultimately real resembled some Buddhist ideas. Advaita tradition rejects the charge, and modern scholars see both real differences and some shared ground.',
    ],
    ideas: [
      { title: 'Brahman is the one reality', text: 'Shankara reads the Upanishads as teaching that there is one reality, Brahman, which is pure being and consciousness, without parts and without change. Advaita means “not two”: the many things we see are not a second reality standing beside Brahman. This claim is the foundation of the rest of his system.' },
      { title: 'The self is Brahman', text: 'The inner self, atman, is not the body, the mind or the personality, since these change and can be observed. At its core, he argues, the self is identical with Brahman. He cites the Upanishad statement “tat tvam asi”, “you are that”, as the central teaching, and explains that the apparent gap between the individual and the ultimate is the result of ignorance.' },
      { title: 'Ignorance and superimposition', text: 'He explains why we do not see this by the idea of superimposition (adhyasa): we mistakenly project the features of the body, mind and world onto the self, and the features of the self onto them, just as a rope in dim light may be taken for a snake. This beginningless ignorance, avidya, is closely tied to the word maya, which the later tradition often translates as illusion, although in Shankara’s own works the term has a more subtle role.' },
      { title: 'Knowledge, not action, liberates', text: 'Since the problem is ignorance, he argues that liberation comes through knowledge, not through ritual or effort alone. Ritual and ethical discipline prepare the mind, but only the realisation that one is Brahman ends the cycle of rebirth. He describes a path of study, reflection and meditation, taught by a qualified teacher, and he asks seekers to cultivate detachment, calm and a longing for freedom.' },
      { title: 'Two standpoints', text: 'Shankara allows that ordinary life has its own order. From the everyday standpoint the world, God as the creator and ruler (Ishvara), moral law and worship all have a place. From the highest standpoint, only Brahman is real. Later Advaita writers developed this into a more detailed theory of levels of reality, but the basic two-level structure is already there.' },
    ],
    principles: [
      'Ask who it is that experiences, behind the changing thoughts.',
      'Study with a teacher and test teaching against your own reflection.',
      'Practise detachment from outcomes, calmness and self-control.',
      'Do not confuse an appearance with what is ultimately real.',
      'Prepare through disciplined living, because insight needs a steady mind.',
    ],
    practice: [
      'Sit quietly for a few minutes and notice thoughts, moods and sensations coming and going, then ask what it is that notices them.',
      'When you feel threatened by a label, such as your job title or reputation, remember that it describes a role and not the whole of you.',
      'Read a hard text slowly, with a trusted guide or a commentary, and write out the argument in your own words.',
    ],
    facts: [
      'His commentary on the Brahma Sutras, the Brahma Sutra Bhashya, is generally regarded as his masterwork.',
      'Scholars accept his commentaries on the major Upanishads and on the Bhagavad Gita as authentic, and the Upadesasahasri, “A Thousand Teachings”, is also accepted.',
      'Many popular works carry his name, including the Vivekachudamani, but scholars have mostly rejected his authorship of these.',
      'Tradition says he founded four monasteries, mathas, at Sringeri in the south, Dwarka in the west, Puri in the east and Jyotirmath near Badrinath in the north. Historians doubt that all four go back to him.',
      'Tradition also says he organised the Dashanami order of monks, though the history of that order is not well documented.',
      'A famous legend says he debated Mandana Mishra, and that the judge was Mandana’s wife, Ubhaya Bharati, who is a legendary figure.',
    ],
    myths: [
      { myth: 'Shankara taught that the world is an illusion, meaning it is nothing.', reality: 'He taught that the world is not ultimately real in the way Brahman is, but he did not say it does not exist at all. It is dependent and changing, and in everyday life it must be taken seriously. The word “illusion” for maya is a simplification.' },
      { myth: 'Shankara invented Advaita Vedanta.', reality: 'Earlier teachers, such as Gaudapada, had already taught non-dual views, and the Upanishads are older still. Shankara gave this teaching its classic and most influential form.' },
      { myth: 'All the hymns and treatises in his name are his.', reality: 'Many popular texts, such as the Vivekachudamani, were attributed to him later. Scholars rely on a core of commentaries and the Upadesasahasri.' },
    ],
    works: [
      { title: 'Brahma Sutra Bhashya', note: 'His long commentary on the Brahma Sutras, with a famous introduction on superimposition.' },
      { title: 'Commentaries on the principal Upanishads', note: 'Including the Brihadaranyaka, Chandogya, Taittiriya and others.' },
      { title: 'Bhagavad Gita Bhashya', note: 'A commentary reading the Gita as teaching knowledge and detachment.' },
      { title: 'Upadesasahasri (A Thousand Teachings)', note: 'A work of verse and prose on the practice of self-knowledge.' },
      { title: 'Hagiographies such as the Shankara Digvijaya', note: 'Late biographies full of legend, valuable for tradition but not as evidence of his life.' },
    ],
    legacy: [
      'Shankara’s work became the root of the Advaita tradition, and later thinkers wrote extensively on his commentaries. Other Vedanta teachers, such as Ramanuja and Madhva, argued against him from the view that the self and God remain distinct, so that the debate about non-duality shaped Hindu thought for centuries. Monastic institutions that trace themselves to him still exist.',
      'In modern times his thought was reintroduced to a wider public through teachers such as Swami Vivekananda and the philosopher S. Radhakrishnan. Many readers have drawn parallels with Western ideas about mind and reality, though such comparisons have to be made with care, because Shankara’s argument rests on the authority of the Upanishads and on a particular path of practice.',
    ],
  },
  {
    slug: 'murasaki-shikibu',
    order: 973,
    dates: 'c. 973 – c. 1014 or later',
    place: 'Heian-kyo (Kyoto), Japan',
    era: 'Medieval',
    tradition: 'Heian literature',
    tagline: 'A lady-in-waiting at the Japanese imperial court who wrote The Tale of Genji, one of the world’s great works of fiction.',
    who: [
      'We do not know her real name. “Murasaki Shikibu” is a court nickname: “Shikibu” refers to a post held by a male relative, her father, and “Murasaki”, meaning purple or violet, is probably borrowed from a heroine of her own story. She was the daughter of Fujiwara no Tametoki, a scholar and provincial official, and she was born around 973. Her exact dates of death are unknown, and scholars place it around 1014, though some suggest she lived later.',
      'In her diary she says that she learned Chinese characters, normally a male accomplishment, by listening in as her brother was taught, and that her father regretted she was not a boy. Around 998 she married Fujiwara no Nobutaka, a much older official, and had a daughter, Kenshi, in 999. Nobutaka died about two years later, probably of an epidemic. Some scholars think that writing helped her through the loss, and that the first parts of the Genji may date from these years.',
      'Around 1005 or 1006 she was invited to serve Empress Shoshi, a daughter of the powerful statesman Fujiwara no Michinaga, at the imperial court. She served about five or six years. Her diary, which covers part of 1008–1010, describes court ceremony, the birth of a prince and her gossip about other women. She also writes of her unease in court life and of a wish to withdraw. After the death of Emperor Ichijo in 1011, her trail fades.',
    ],
    context: [
      'The Heian period (794–1185) was a time when the Fujiwara family ruled Japan by marrying their daughters to emperors and acting as regents for the boy-emperors born of these marriages. The court in Kyoto prized poetry, calligraphy, music, scent and refined behaviour. Official writing was in Chinese, a language associated with men, while women wrote in the Japanese kana scripts, and so the greatest works of Heian prose, among them The Pillow Book of Sei Shonagon, came from women.',
      'An empress’s household competed for talent. Michinaga, to strengthen the standing of his daughter Shoshi, gathered gifted women around her, and this is one reason a writer such as Murasaki was brought in. The world she depicts, with its elaborate etiquette, whispered rumours and quick changes of fortune, is rooted in that setting, though the story itself is fiction and often looks back to an earlier age.',
    ],
    ideas: [
      { title: 'A long story about inner lives', text: 'The Tale of Genji follows Hikaru Genji, the emperor’s son, “the shining prince”, through love affairs and court intrigue, and then, in its last part, the next generation. Its length, around fifty-four chapters, is striking, but so is its attention to thought and feeling. Characters change, regret and misjudge each other, and we are often shown how they feel as well as what they do.' },
      { title: 'The pathos of things', text: 'The Japanese scholar Motoori Norinaga, in the eighteenth century, argued that the heart of the Genji is mono no aware, a sensitivity to the quiet sadness of passing things. Cherry blossoms, autumn leaves and human love are moving because they do not last. Whether this phrase captures Murasaki’s own intention is a modern interpretation, but it fits the mood of the book.' },
      { title: 'Impermanence and Buddhism', text: 'Buddhist ideas of impermanence, attachment and karma run through the story. Characters suffer because they hold on to love, rank and beauty, and many of them turn toward monastic life. The heroine Ukifune, at the end of the tale, becomes a nun. The book does not preach, but it shows how hard it is to let go.' },
      { title: 'Power, love and the women’s side', text: 'Women in the Genji have limited power. Marriages are arranged by families and politics, and a woman’s fate often depends on a man’s favour. Murasaki draws a wide range of women, among them proud, shy, clever and wounded ones, and she gives their feelings as much weight as Genji’s. Readers continue to argue about whether the book critiques or simply reflects its society.' },
      { title: 'What fiction is for', text: 'In one chapter, Genji speaks in defence of tales, saying that they may record what the official histories leave out. Readers often take the passage as a comment on the book’s own purpose. The idea that fiction can show human truth in a way chronicles cannot is still a living argument.' },
    ],
    principles: [
      'Pay attention to small details of feeling, because they hold much of life’s meaning.',
      'Accept impermanence, and let it deepen appreciation instead of leading only to sorrow.',
      'Notice how power and rank shape people’s choices.',
      'Observe yourself and others with honesty and some gentleness.',
      'Use stories to understand what facts alone cannot say.',
    ],
    practice: [
      'Keep a short daily journal that records what you noticed about people’s moods, not only what happened, as her diary does.',
      'When something beautiful is passing, a season or a gathering, stop and look at it for a full minute instead of reaching for your phone.',
      'Read a novel slowly and ask of each major character: what do they want, and what are they afraid of?',
    ],
    facts: [
      'The Tale of Genji has 54 chapters and contains nearly 800 poems, which characters use to speak to each other.',
      'The earliest firm reference to the Genji is in her diary entry for 1008, where a courtier jokingly asks after “Wakamurasaki”, a character’s name.',
      'According to her diary, rival ladies nicknamed her the “Lady of the Chronicles” because of her knowledge of Chinese, and she says she pretended not to know the characters and secretly taught the empress Chinese poems.',
      'A later tradition says she began the work at Ishiyama-dera, a temple by Lake Biwa. It is a tradition, not a proven fact.',
      'Arthur Waley’s English translation, published in six volumes between 1925 and 1933, made the book known in the West. Later translators include Edward Seidensticker, Royall Tyler and Dennis Washburn.',
      'The unnamed author of the Sarashina Diary, written around 1060, describes the delight of reading the Genji, which shows how widely it was loved within decades.',
    ],
    myths: [
      { myth: 'The Tale of Genji is the first novel in the world.', reality: 'The claim is often made, but it depends on how “novel” is defined. Earlier prose fiction existed in Japan, such as The Tale of the Bamboo Cutter, as well as Greek and Roman romances. It is more safely described as one of the earliest long works of prose fiction with psychological depth.' },
      { myth: 'We know exactly who she was and when she died.', reality: 'Her personal name is unknown, her birth year is approximate and the date of her death is uncertain, with estimates running from around 1014 to later. Even the authorship of the final chapters has been questioned by some scholars, though most accept them as hers.' },
      { myth: 'Murasaki and Sei Shonagon were close friends.', reality: 'They served rival empresses and probably never met. In her diary Murasaki criticises Sei Shonagon sharply, so the picture is of two rivals whose books are often compared.' },
    ],
    works: [
      { title: 'The Tale of Genji (Genji Monogatari)', note: 'Her great work, written roughly between 1000 and 1012, and the most famous work of classical Japanese literature.' },
      { title: 'The Diary of Lady Murasaki (Murasaki Shikibu Nikki)', note: 'Court life from about 1008 to 1010, including portraits of other women and reflections on herself.' },
      { title: 'Murasaki Shikibu Shu', note: 'A collection of her poems.' },
      { title: 'Poems in imperial anthologies', note: 'A number of her poems appear in official anthologies, among them the well-known Hyakunin Isshu.' },
    ],
    legacy: [
      'The Tale of Genji shaped Japanese art and literature for a thousand years. Painters illustrated it, poets alluded to its scenes, and Noh theatre drew on its characters. Its emphasis on mood and feeling influenced the Japanese sense of beauty, and it has been adapted into modern novels, films, manga and opera.',
      'In the twentieth century translations carried it around the world, and readers compared it with Proust and with Jane Austen. Scholars today study it as literature, as a document of Heian court life and as an early example of a woman writing with great authority. It remains one of the clearest windows on that vanished society.',
    ],
  },
  {
    slug: 'omar-khayyam',
    order: 1048,
    dates: '1048 – 1131',
    place: 'Nishapur, Samarkand and Isfahan (Persia)',
    era: 'Medieval',
    tradition: 'Persian poetry and science',
    tagline: 'A mathematician and astronomer of medieval Persia, remembered in the West as the poet of the Rubaiyat.',
    who: [
      'Omar Khayyam was born in 1048 in Nishapur, then a flourishing city in the Persian province of Khorasan, and he died there in 1131. His surname “Khayyam” means “tentmaker”, and it may reflect his family’s trade. He studied mathematics, astronomy, medicine and philosophy, and around 1070 he moved to Samarkand, where he wrote his famous treatise on algebra under the protection of a local judge.',
      'He was then called to the court of the Seljuk sultan Malik-Shah, where, around 1074, he was put at the head of a team to reform the calendar and run an observatory, probably at Isfahan. The work led to the Jalali calendar, introduced in 1079. After Malik-Shah died in 1092, and his powerful minister Nizam al-Mulk was assassinated, support for the court scientists weakened. Later sources say that Khayyam made the pilgrimage to Mecca and spent his last years teaching and writing.',
      'Almost all we know of his life comes from later biographies, which sometimes disagree. One twelfth-century writer, Nizami Arudi, reports a meeting with him and says that Khayyam predicted that his grave would lie where roses would fall on it in the spring wind. This is a literary story, though his tomb in Nishapur remains a place of visits. To his own contemporaries he was a leading scientist and philosopher, and poetry seems to have been a minor side of his reputation.',
    ],
    context: [
      'In the eleventh century the Seljuk Turks ruled much of the Islamic world from Persia. The sultans supported scholars, schools and observatories. Arabic served as the language of science and philosophy, and Persian was becoming a language of poetry and prose. A tradition of mathematics stretching back through al-Khwarizmi, who gave algebra its name, offered Khayyam a base to work from.',
      'It was also a period of religious and intellectual tension. Philosophy in the tradition of Ibn Sina (Avicenna) was both admired and attacked, and it was soon challenged by thinkers such as al-Ghazali. A philosopher with an interest in doubt and wine imagery, as the poems attributed to Khayyam show, could easily be suspected, and some sources suggest that he was careful about what he said in public.',
    ],
    ideas: [
      { title: 'A theory of cubic equations', text: 'In his Treatise on Demonstration of Problems of Algebra, Khayyam classified equations of the third degree and solved them geometrically, by finding where conic sections such as circles, parabolas and hyperbolas intersect. He was among the first to give a systematic treatment, and he expressed the hope that an arithmetic solution would someday be found. One came with Italian mathematicians in the sixteenth century.' },
      { title: 'Rigour about parallel lines', text: 'In a commentary on the difficulties of Euclid’s book, he examined the parallel postulate, the assumption about parallel lines that many mathematicians felt ought to be provable. He tried to replace it with a more intuitive statement and used a quadrilateral that later writers would also use. His proof did not succeed, but it formed part of a long inquiry that eventually led to non-Euclidean geometry.' },
      { title: 'Measuring time with care', text: 'The Jalali calendar, based on his group’s observations, used a system of leap years that in the long run is remarkably accurate. The solar calendar now used in Iran descends from it. His interest was in precision: to make a calendar match the sky as closely as the instruments of the day would allow.' },
      { title: 'Philosophy of existence', text: 'In several short Arabic treatises, among them one on existence and necessity, Khayyam discusses questions such as why there is variety in the world, how things can be necessary or contingent and how God relates to creation. He works largely within the tradition of Ibn Sina, and his surviving prose writings are explicitly theistic.' },
      { title: 'Short poems on a short life', text: 'The quatrains (ruba’i) attributed to him meditate on death, fate and the pleasure of the moment, and many mention wine, which some readers read as literal and others as mystical. They ask what we can know about God and the afterlife, and they often answer with doubt or a call to enjoy the day. Since many of them may not be his, these poems tell us about a Persian tradition of questioning as much as they tell us about one man.' },
    ],
    principles: [
      'Be exact in your work, and do not mistake approximate for sure.',
      'Admit what you do not know.',
      'Value the present day, because it will not return.',
      'Do not let fear of conflict stop you from asking honest questions.',
      'Combine curiosity about the sky with attention to the table in front of you.',
    ],
    practice: [
      'When you solve a problem, write down how you know the answer is right, and where it could break.',
      'Set aside a small, regular time to enjoy something simple, such as a meal with friends or a walk, without work in mind.',
      'When someone offers a certain answer to a large question, ask what evidence supports it, and be content to say “I am not sure”.',
    ],
    facts: [
      'The Jalali calendar was introduced in 1079 and uses a system of leap years in a long cycle, reportedly of 33 years, which gives a very accurate average year.',
      'A crater on the Moon is named after him.',
      'The Rubaiyat was almost unknown in the English-speaking world until Edward FitzGerald’s first edition of 1859, which was published anonymously and at first sold poorly. It was later praised by the poet Dante Gabriel Rossetti and others, and became a Victorian success.',
      'FitzGerald revised the poem three times in his lifetime, in 1868, 1872 and 1879, and the first edition had 75 quatrains.',
      'The word “ruba’i” means a four-line poem, with a rhyme pattern usually AABA.',
      'The modern mausoleum in Nishapur, designed by Hooshang Seyhoun and opened in 1963, stands near his reputed burial place.',
    ],
    myths: [
      { myth: 'Khayyam wrote the Rubaiyat as FitzGerald presents it.', reality: 'FitzGerald’s poem is a free rendering. He chose, reordered and merged quatrains, and added ideas of his own, and he admitted taking liberties with the originals. The verses are best read as an English poem “inspired by” Khayyam.' },
      { myth: 'Every quatrain attributed to Khayyam is his.', reality: 'Many hundreds of quatrains circulate under his name, and manuscripts differ greatly. Poets across the centuries added their own to the collection, and scholars accept only a small core, with disagreement about how large it is. Some early references to his poems appear in the twelfth and thirteenth centuries, long after his death.' },
      { myth: 'He was a simple drinker and sceptic who rejected all religion.', reality: 'His surviving prose philosophy is theistic, and later sources describe him as both pious and doubting. Readers have taken the poems as hedonist, sceptical or mystical, and the evidence does not settle the matter.' },
    ],
    works: [
      { title: 'Treatise on Demonstration of Problems of Algebra', note: 'His major work in mathematics, with the classification and geometric solution of cubic equations.' },
      { title: 'Commentary on the Difficulties in the Postulates of Euclid', note: 'An attempt to deal with the parallel postulate.' },
      { title: 'Philosophical treatises in Arabic', note: 'Short works on existence, necessity and related questions, in the Avicennan tradition.' },
      { title: 'Rubaiyat (attributed quatrains)', note: 'Persian four-line poems of uncertain authorship, the earliest large manuscripts of which are centuries later than his time.' },
      { title: 'FitzGerald, Rubaiyat of Omar Khayyam (1859)', note: 'The free English version that made the poems famous, and a work of English literature in its own right.' },
    ],
    legacy: [
      'As a scientist, Khayyam contributed to algebra, geometry and astronomy at the height of medieval Islamic science. His work on cubic equations stands in the line of thought that led to later European algebra, and the calendar that grew from his team’s work remains in use in a modified form. The Persian New Year, Nowruz, is tied to the same astronomical reckoning.',
      'As a poet, his fame in the modern world is largely a result of FitzGerald’s version, which was read by millions in English and translated into many other languages. It inspired artists and musicians, and it created clubs of devoted readers. In Iran and the wider Persian-speaking world he is honoured both as a poet and as a scholar, and the debate over which quatrains are really his continues.',
    ],
  },
]
