import type { Profile } from './types'

export const MORE_12: Profile[] = [
  {
    slug: 'mikhail-bakunin',
    order: 1814,
    dates: '1814 – 1876',
    place: 'Russia, Germany, Siberia, then exile in Western Europe and Switzerland',
    era: '19th Century',
    tradition: 'Anarchism',
    tagline: 'A Russian aristocrat turned professional revolutionary, who argued that every state, however it is justified, ends up ruling over the people it claims to serve.',
    who: [
      'Mikhail Bakunin was born in 1814 on his family’s estate at Pryamukhino, in the Tver region north-west of Moscow, into a landowning noble family. He trained as an artillery officer but left the army, and in Moscow in the 1830s he joined a circle of young intellectuals who studied German philosophy, above all Hegel. He travelled to Berlin in 1840, and in 1842 he published an essay on “The Reaction in Germany” that ended with the line that the passion for destruction is also a creative passion. Over the following years he turned from philosophy to revolutionary politics.',
      'In 1848, the year of revolutions across Europe, he took part in the Slavic Congress in Prague and in the uprising that followed, and in May 1849 he joined the insurrection in Dresden, where he was arrested. He was sentenced to death in Saxony and again in Austria, and both sentences were commuted, but in 1851 he was handed over to Russia. He spent years in the Peter and Paul Fortress and then in Shlisselburg, writing a famous “Confession” to Tsar Nicholas I from prison, a document whose sincerity historians still debate. In 1857 he was sent into exile in Siberia.',
      'In 1861 he escaped by travelling down the Amur river to the Pacific coast and then, via Japan, San Francisco and New York, to London. He spent the rest of his life as a revolutionary in exile, in Italy and Switzerland, organising secret societies, writing pamphlets and joining the International Workingmen’s Association in 1868. He was expelled from it at the Hague Congress of 1872. He died in Bern in July 1876, worn out by illness and short of money.',
    ],
    context: [
      'Bakunin grew up in the Russia of Nicholas I, an autocracy built on serfdom, censorship and a large state bureaucracy. For young educated Russians, German philosophy offered an escape from this world, and Hegel’s idea that history moves through conflict toward freedom became, in the hands of the “Left Hegelians”, an argument for revolution. The wave of risings across Europe in 1848–49 seemed to promise that the old order would fall, and its defeat shaped Bakunin’s lasting suspicion of leaders who betray revolutions once they hold power.',
      'The second half of his life coincided with the rise of organised socialism. Marx and his followers wanted workers to form political parties, win power and use the state to build a new society, while Bakunin and his supporters feared that any such state would create a new ruling class of officials and intellectuals. This quarrel split the International in the early 1870s and set the two main currents of the socialist movement, Marxism and anarchism, on different paths.',
    ],
    ideas: [
      { title: 'Against every kind of authority', text: 'Bakunin held that human freedom is not a private possession but grows with the freedom of others, and that power over people corrupts those who hold it, however good their intentions. He therefore rejected not only monarchy and capitalism but also the state in any form, including a workers’ state, and the authority of the Church. He expressed his rebellion against religion by turning a saying of Voltaire on its head: if God really existed, it would be necessary to abolish him.' },
      { title: 'Federation from below', text: 'In place of the state he imagined a society built up from free associations: workers’ groups, communes and regions that join together by voluntary agreement and can leave again. Authority would flow upward from the members, not downward from a centre. He called this view collectivist anarchism, and it influenced later anarcho-syndicalism, which put trade unions at the centre of social change.' },
      { title: 'The critique of the “red bureaucracy”', text: 'In his quarrel with Marx he warned that a “dictatorship of the proletariat” would in practice become the rule of a small educated elite over the workers, who would be told it was for their own good. Many readers see this as one of the most striking predictions of the twentieth century, while others point out that Bakunin himself was drawn to secret organisations with a leadership that gave orders.' },
      { title: 'Revolution as the work of the people', text: 'Bakunin trusted the instincts of peasants and workers more than the programmes of theorists, and he looked to the rural poor of Russia, Italy and Spain as a revolutionary force. His faith in spontaneous revolt influenced the Russian populists and the anarchist movements of southern Europe, but critics note that it sat uneasily with his own plans for conspiracy.' },
      { title: 'Freedom and science', text: 'He admired science but feared rule by scientists. People should listen to experts as one listens to a bricklayer or an architect, he said, by free choice and without handing over the right to decide. Authority that rests on voluntary trust, in his view, differs from authority that is imposed.' },
    ],
    principles: [
      'Treat the freedom of others as the condition of your own.',
      'Be wary of anyone who claims the right to rule for your own good.',
      'Build things from below, by agreement, and not from above, by command.',
      'Trust expertise only as long as it can be questioned.',
      'Judge a revolution by whether it ends the old domination or only changes the people holding it.',
    ],
    practice: [
      'In a group you belong to, ask who really makes decisions and whether those who are affected are consulted.',
      'When you give someone authority, whether a boss, a leader or a specialist, ask how you would remove them if they abused it.',
      'Try to solve a local problem through voluntary cooperation, such as a neighbourhood group or a mutual-help scheme, before turning to a higher authority.',
    ],
    facts: [
      'Richard Wagner, who took part in the Dresden uprising of 1849, knew Bakunin there, and the two are said to have talked at length. The musician later fled to Switzerland, while Bakunin went to prison.',
      'His escape from Siberia in 1861 took him down the Amur to the Pacific, across to Japan and then through San Francisco, Panama and New York to London, a journey of many months.',
      'He met Marx in Paris in 1844 and again in London in 1864. At first they were on friendly terms, and Bakunin even praised Marx’s learning, before their rivalry over the International turned bitter.',
      'At the Hague Congress in 1872 the majority backed by Marx voted to expel Bakunin and his ally James Guillaume, partly on a charge of running a secret organisation inside the International. Bakunin’s followers then formed their own “anti-authoritarian” International.',
      'His best-known text, God and the State, is an unfinished fragment written around 1871. It was not published until 1882, after his death, when his followers Carlo Cafiero and Élisée Reclus edited it and gave it its title.',
      'In exile he found his main followers in Italy, Spain and the watchmaking villages of the Swiss Jura. He had married Antonia Kwiatkowska in Siberia in 1858.',
    ],
    myths: [
      { myth: 'Bakunin simply preached destruction and chaos.', reality: 'His slogans were provocative, but his writings describe a society of federated, self-governing associations, and he argued that a revolution must replace authority with free organisation. Critics can fairly say that his method was often more conspiratorial than his ideal.' },
      { myth: 'Bakunin wrote the Catechism of a Revolutionary, the ruthless manual of the Nechayev affair.', reality: 'In 1869 he worked briefly with the young revolutionary Sergey Nechayev, who claimed to lead a vast secret network. The Catechism is usually credited to Nechayev, perhaps with Bakunin’s input, and historians disagree about how much he contributed. When Nechayev murdered a student named Ivanov and deceived his associates, Bakunin broke with him in 1870.' },
      { myth: 'The conflict between Bakunin and Marx was purely a matter of principle.', reality: 'It was also a struggle for control of the International, with personal rivalry and mutual accusations on both sides. Bakunin’s writings against Marx contain remarks about Jews and Germans that have been widely criticised as antisemitic, and historians still discuss how far they were personal abuse and how far a wider prejudice, while his general theory of anarchism does not depend on them.' },
    ],
    works: [
      { title: 'God and the State (written c. 1871, published 1882)', note: 'His best-known text, an unfinished argument against religion and the state, assembled and titled by followers after his death.' },
      { title: 'Statism and Anarchy (1873)', note: 'A book on Russia, Germany and revolution, which contains his critique of Marxist state socialism.' },
      { title: 'The Reaction in Germany (1842)', note: 'The early essay, written under a pseudonym, that contains the famous line about the creative passion of destruction.' },
      { title: 'Confession (1851)', note: 'A long letter to Nicholas I written in the Peter and Paul Fortress, published after the 1917 revolution and read in very different ways.' },
      { title: 'Writings collected by his followers and in later editions', note: 'Much of his output is made of letters, pamphlets and unfinished manuscripts, so most readers meet him through selections and anthologies.' },
    ],
    legacy: [
      'Bakunin became the main founding figure of the collectivist and revolutionary wing of anarchism. His ideas shaped the anarchist movements of Italy, Spain and Latin America, and the Spanish anarcho-syndicalist unions of the early twentieth century, which played a large part in the Spanish Civil War, regarded him as a forerunner.',
      'His quarrel with Marx remains alive in debates about how far socialism can be reconciled with freedom. His warning that a revolutionary state might turn into a new form of domination was cited after the Russian Revolution by anarchists and also by many who were not, while others argue that his own conspiratorial methods and the Nechayev episode show the dangers of the same temptation.',
    ],
  },
  {
    slug: 'taras-shevchenko',
    order: 1814,
    dates: '1814 – 1861',
    place: 'Ukraine, St Petersburg, and exile in the Orenburg region and Kazakhstan',
    era: '19th Century',
    tradition: 'Ukrainian national thought',
    tagline: 'A serf who became the great poet and painter of Ukraine, and whose voice gave a people a language for its freedom.',
    who: [
      'Taras Shevchenko was born in March 1814 into a serf family in the village of Moryntsi, in the Kyiv region of the Russian Empire, and he was orphaned young. His owner took him to Vilnius and then to St Petersburg as a household servant. There, in his spare time, he drew, and he was noticed by artists and writers who came to admire his talent.',
      'In 1838 his freedom was bought. The painter Karl Bryullov painted a portrait of the poet Vasily Zhukovsky, which was raffled among the imperial family, and the money raised paid his owner, Pavel Engelhardt, 2,500 rubles. Shevchenko then studied at the Academy of Arts under Bryullov. In 1840 he published Kobzar, a small collection of poems in Ukrainian, which made him famous. A kobzar was a travelling singer who accompanied himself on a stringed instrument and sang about the history of the Cossacks and the people.',
      'In the 1840s he travelled in Ukraine and became close to a group of young Kyiv intellectuals, the Brotherhood of Saints Cyril and Methodius. In April 1847 the authorities arrested the members. Shevchenko’s sharp political poems, including satires on Nicholas I and the empress, weighed heavily against him. He was sent as a private soldier to the Orenburg region, with an order (reported to have been approved by the tsar) forbidding him to write or paint. He was released in 1857, returned to St Petersburg in 1858, and died there on 10 March 1861 (26 February by the old calendar), days after the emancipation of the serfs was signed, a measure he had long hoped for.',
    ],
    context: [
      'Ukraine in Shevchenko’s time had no state of its own. Its lands were divided between the Russian and Austrian empires, and the Ukrainian language was treated by many officials and writers as a peasant dialect. At the same time, interest in folk songs, history and language was growing across Europe, and educated Ukrainians began to collect songs, to study the Cossack past and to write in the vernacular. Shevchenko’s poetry grew out of this movement and made it more powerful than any previous writer had.',
      'Serfdom was the other great fact of his world. Millions of peasants in the empire belonged to a landlord, and Shevchenko was one of them. The Brotherhood of Cyril and Methodius, formed in Kyiv in 1845–46 with figures such as the historian Mykola Kostomarov and the writer Panteleimon Kulish, called for the abolition of serfdom, for a federation of free Slavic peoples and for a place for Ukraine within it. Shevchenko was a member, though not among its leaders or the authors of its programme, and his poems, which were circulating in manuscript, brought him the harshest punishment.',
    ],
    ideas: [
      { title: 'The poet as the voice of a people', text: 'In Kobzar and later poems Shevchenko wrote in a living Ukrainian, close to the language of songs and ordinary speech, and he used it for subjects that earlier literature had left to Russian or Polish: the Cossack past, the wrongs of the peasantry, the loneliness of the exile. He helped make Ukrainian a language that could carry serious literature.' },
      { title: 'Against serfdom and tyranny', text: 'His poems condemn the cruelty of landlords and the empire’s officials, and they speak for women who were seduced and abandoned, for conscripts and for hungry peasants. Poems such as “Kateryna” and “The Dream” put the suffering of the weak next to the arrogance of power, and he wrote with a bitterness that came from personal experience.' },
      { title: 'History as memory and warning', text: 'In Haidamaky (1841), about the 1768 uprising in right-bank Ukraine, he dwelled on the bloodshed and what it cost, and critics have long debated how far the poem glorifies the rebels and how far it mourns them. In other poems he reproached Ukrainians for forgetting their own history and for serving their oppressors. Memory, for him, was a moral duty.' },
      { title: 'Freedom and faith', text: 'Many of his poems draw on biblical language and psalms, and he asked God for justice for the poor. His testament poem “Zapovit” (1845) asks to be buried on a mound above the Dnipro, and asks the living to “bury me and rise up” and break their chains, and to remember him in the family of the free. It is read at funerals and gatherings to this day.' },
      { title: 'Artist as well as poet', text: 'Shevchenko was a talented painter and printmaker, with portraits, landscapes and scenes of the lives of ordinary people, and in 1860 the Academy of Arts gave him the title of academician for engraving. He thought of word and image as parts of the same work.' },
    ],
    principles: [
      'Remember where you come from, and do not be ashamed of your own language or people.',
      'Stand beside those who are denied their dignity, and do not become their oppressor in turn.',
      'Be truthful about the past, including its violence.',
      'Keep creative work alive even when it is forbidden.',
      'Value freedom for every person, not only for yourself.',
    ],
    practice: [
      'Learn a song, a story or a poem from your own family or region, and pass it on to someone younger.',
      'When you hear a group described only by its worst moments, look for the voices of its own poets and writers.',
      'If you are in a position of comfort, find one concrete way to support someone who has been denied it, as those who bought Shevchenko’s freedom did.',
    ],
    facts: [
      'The portrait of Zhukovsky that freed Shevchenko was raffled in 1838 among the imperial family, and the lottery raised the money for his purchase.',
      'The word “kobzar” refers to a bard who played the kobza or bandura. Kobzar first appeared in 1840 as a slim volume, and a much larger edition appeared in 1860.',
      'While in exile at the Novopetrovsk fortress, now in Kazakhstan, he continued to write in secret and to draw when he could, and he also took part in a survey expedition to the Aral Sea.',
      'After his release in 1857 he kept a diary, written in Russian, which gives a rare view of his daily thoughts. He also wrote stories and plays in Russian.',
      'His body was first buried in St Petersburg. In May 1861 his friends carried it to Ukraine and he was buried above the Dnipro at Kaniv, as he had asked in “Zapovit”, and the place became a site of pilgrimage.',
      'Monuments to him stand far beyond Ukraine, in cities such as Washington and Winnipeg.',
    ],
    myths: [
      { myth: 'Shevchenko was a revolutionary leader who organised a conspiracy.', reality: 'He was a member of the circle around the Brotherhood of Cyril and Methodius, but historians generally see him as its poet, not an organiser. The tsar’s anger was directed above all at his poems.' },
      { myth: 'Shevchenko’s image has always meant the same thing.', reality: 'In the Soviet Union he was celebrated as a “revolutionary democrat” and an enemy of the tsars and landlords, while his religious language and national feeling were played down. In independent Ukraine, and in the Ukrainian diaspora, he has been presented above all as national poet and symbol of the fight for independence. His poems and his image have also been invoked by many sides in political struggles over Ukrainian identity, and historians urge readers to separate the poet from the uses made of him.' },
      { myth: 'Shevchenko wrote only in Ukrainian and had nothing to do with Russian culture.', reality: 'He wrote his poetry in Ukrainian, but he wrote his diary, stories and letters mainly in Russian, studied in Russia’s Academy, and counted Russian writers and artists among his friends and rescuers.' },
    ],
    works: [
      { title: 'Kobzar (1840; enlarged 1860)', note: 'His principal collection of poems. The title has become a name for the whole body of his verse.' },
      { title: 'Haidamaky (1841)', note: 'A long poem about the 1768 uprising, and one of his most debated works.' },
      { title: 'Kateryna (1838) and The Dream (1844)', note: 'A poem about a betrayed peasant girl, and a satire on the empire’s court and officials.' },
      { title: 'Zapovit, “Testament” (1845)', note: 'His best-known poem, a call to freedom and a request for burial on the banks of the Dnipro.' },
      { title: 'Diary (Zhurnal), 1857–58, and paintings and etchings', note: 'A first-hand record of his last years, along with a large body of art in Ukrainian and Russian museums.' },
    ],
    legacy: [
      'Shevchenko is often called the father of modern Ukrainian literature, and for many Ukrainians he is the national poet whose words every school child learns. His poetry helped create a modern Ukrainian literary language and gave the national movement a vocabulary of freedom, memory and dignity. After his death, his grave at Kaniv and his birthday on 9 March became occasions for public commemoration.',
      'Because he is so widely loved, his image has often been used for political aims by governments and movements with very different goals. Readers today can return to the poems themselves, which are bound up with serfdom, exile and the hope of a freedom that he did not live to see, and read them against the uses made of him.',
    ],
  },
  {
    slug: 'john-ruskin',
    order: 1819,
    dates: '1819 – 1900',
    place: 'London, Oxford and the Lake District, England',
    era: '19th Century',
    tradition: 'Victorian art criticism',
    tagline: 'The critic who taught Victorians to look at art and architecture, and then turned the same moral eye on the economy.',
    who: [
      'John Ruskin was born in London in 1819, the only child of a prosperous wine merchant and his devout wife. He was educated at home with great care, read the Bible and the Romantic poets, travelled widely in Europe with his parents, and went on to Oxford, where he won the Newdigate Prize for poetry. He soon abandoned poetry for prose, and in 1843 he published the first volume of Modern Painters, a long defence of the landscape painter J. M. W. Turner that grew into a five-volume work on art, nature and truth, completed in 1860.',
      'In the following years he wrote The Seven Lamps of Architecture (1849) and The Stones of Venice (1851–53), which argued that the Gothic style, with its irregular, hand-carved ornament, showed the dignity of free workers, and that the condition of a society’s workers could be read in its buildings. His private life was troubled: his marriage to Effie Gray was annulled in 1854 on the ground that it had not been consummated, and she later married the painter John Everett Millais, whom Ruskin had defended.',
      'From about 1860 he turned from art to the problems of the economy with Unto This Last, then to lectures, letters and books on work, education and nature. In 1869 he became the first Slade Professor of Fine Art at Oxford. He suffered serious mental breakdowns from 1878 onward, with periods of illness, recovery and relapse, and in later years he lived mostly in retirement at Brantwood, beside Coniston Water, where he died in January 1900.',
    ],
    context: [
      'Ruskin wrote in the age of the industrial revolution, when machines, factories and railways were transforming Britain and creating great wealth alongside crowded cities and poor working conditions. Many thoughtful Victorians, among them Thomas Carlyle, whom Ruskin admired, worried that the cash relationship between employer and worker had replaced older ties of duty and care.',
      'It was also a time of great debate in art and religion. Ruskin’s evangelical upbringing and then his gradual loss of orthodox faith shaped the moral seriousness of everything he wrote. He championed the Pre-Raphaelite painters, helped to launch the Gothic Revival’s claims for medieval craft, and influenced the architecture and design of his age. His belief that beauty and morality belong together was in sharp contrast with the dominant political economy, which treated wealth as the product of competition and demand.',
    ],
    ideas: [
      { title: 'Learn to see truly', text: 'In Modern Painters he urged artists and viewers to study nature faithfully: the shape of a cloud, the structure of a rock, the growth of a tree. For him, accurate seeing was both a skill and a moral habit, an act of humility toward the world. His own drawings and watercolours show how closely he practised what he preached.' },
      { title: 'Work should be human', text: 'In the chapter “The Nature of Gothic” in The Stones of Venice he argued that the medieval carver was free to make mistakes and to give his own character to the work, while modern factory production treated workers as machines. Dividing labour so that people repeated one tiny task, he thought, degraded them. He wanted work in which the maker’s mind and hand were both engaged.' },
      { title: 'There is no wealth but life', text: 'In Unto This Last (1860) he attacked the political economy of his day, which assumed that people are driven only by self-interest. He argued that real wealth is the capacity to live well, and that an economy should be judged by the quality of the lives it produces, not only by the quantity of goods. He also argued for fair wages, for state schools and for public support for the poor.' },
      { title: 'Architecture as a moral art', text: 'The Seven Lamps of Architecture set out principles such as sacrifice, truth, power, beauty, life, memory and obedience. Buildings, he said, should be honest in their materials, should be cared for rather than “restored” out of existence, and should be built to last, so that they carry the memory of a society. His arguments influenced the later movement to protect historic buildings.' },
      { title: 'Education, nature and community', text: 'In his later years he set up the Guild of St George (1871), a charity meant to show an alternative to industrial life through land, crafts and a museum for working people in Sheffield. It was small and often ill-organised, and he intended it as an example more than as a business, but it still exists as a charity today.' },
    ],
    principles: [
      'Look closely and honestly before you judge.',
      'Judge an economy by the lives it produces.',
      'Give work meaning and respect the person who does it.',
      'Preserve and care for beautiful things instead of replacing them.',
      'Pay a fair price, and do not pay for what is dishonestly cheap.',
    ],
    practice: [
      'Draw something you pass every day, a leaf or a doorway, and notice how much you had not seen.',
      'When you buy something, ask who made it, and under what conditions.',
      'Take up one handmade skill, such as cooking, repair, sewing or woodwork, as a way to value the work of other people’s hands.',
    ],
    facts: [
      'The essays of Unto This Last first appeared in Cornhill Magazine in 1860 and aroused such hostility among readers that the series was cut short after four essays. They appeared as a book in 1862.',
      'Mohandas Gandhi read Unto This Last in 1904, on a train journey in South Africa. Gandhi said it changed his life, and he later paraphrased it in Gujarati as Sarvodaya, “the welfare of all”.',
      'In a survey of newly elected Labour Members of Parliament in 1906, Ruskin was named as one of the writers who most influenced them.',
      'The Stones of Venice was meant partly as a warning: Ruskin feared that Venice’s decline was a lesson for Victorian Britain, and he also made a detailed record of the city’s buildings, much of which was later altered or lost.',
      'The Whistler libel case of 1878 ended with Whistler awarded a farthing in damages and no costs.',
      'He coined the phrase “pathetic fallacy” in Modern Painters to describe the habit of poets attributing human feeling to nature.',
    ],
    myths: [
      { myth: 'Ruskin lost the Whistler libel case and was ruined by it.', reality: 'Ruskin had written that Whistler was asking two hundred guineas for flinging a pot of paint in the public’s face, and Whistler sued. The jury found for Whistler but awarded him a single farthing, and with heavy legal costs he went bankrupt the next year. Ruskin was too ill to attend the trial, and ill health later led him to give up his Oxford chair.' },
      { myth: 'Ruskin was merely a snob who disliked modern life.', reality: 'He was a conservative in some matters, and often a romantic about the Middle Ages, but he also demanded schooling for all, support for the old and unemployed, and fair pay. His ideas fed into the Arts and Crafts movement of William Morris and others, and into early British socialism.' },
      { myth: 'The reasons for his marriage ending are well established.', reality: 'The marriage was annulled in 1854, and the cause has been the subject of rumour and speculation ever since. The evidence is incomplete and mostly comes from later, second-hand accounts, so scholars treat the stories with caution.' },
    ],
    works: [
      { title: 'Modern Painters (5 vols, 1843–60)', note: 'A defence of Turner that grew into a wide-ranging study of art, nature and truth.' },
      { title: 'The Seven Lamps of Architecture (1849) and The Stones of Venice (1851–53)', note: 'His great works on architecture, including the chapter “The Nature of Gothic”.' },
      { title: 'Unto This Last (1860; book 1862)', note: 'Four essays criticising the economics of his day, and the work that most influenced Gandhi and the British labour movement.' },
      { title: 'Sesame and Lilies (1865) and Fors Clavigera (1871–84)', note: 'A popular book on reading and education, and a long series of letters to working men on society, art and the Guild of St George.' },
      { title: 'Praeterita (1885–89)', note: 'His unfinished autobiography, written in his later years with long intervals of illness.' },
    ],
    legacy: [
      'Ruskin’s ideas about the dignity of craft and the moral value of beauty inspired William Morris and the Arts and Crafts movement, as well as the founding of Ruskin College in Oxford and other schools and societies. His arguments about the care of old buildings were part of the background to the Society for the Protection of Ancient Buildings and the modern conservation movement.',
      'Gandhi’s reading of Unto This Last, and the Phoenix Settlement he founded in South Africa in 1904, show how far these ideas travelled. Modern debates about ethical consumption, the environment and the meaning of wealth often recall him, though some of his views, on gender, on the Middle Ages and on empire, have not dated well, and his later writing is fragmentary and affected by illness.',
    ],
  },
  {
    slug: 'george-eliot',
    order: 1819,
    dates: '1819 – 1880',
    place: 'Warwickshire, Coventry and London, England',
    era: '19th Century',
    tradition: 'Victorian literature and ethics',
    tagline: 'The novelist who tried to make readers understand other people from the inside, and treated sympathy as the foundation of morality.',
    who: [
      'George Eliot was the pen name of Mary Ann Evans, born in November 1819 on a Warwickshire estate near Nuneaton, where her father was the land agent. She was a clever child, and she was educated at boarding schools and then, largely, on her own, reading widely. As a young woman she was strongly religious, but around 1841–42, in Coventry, where she met a freethinking circle around Charles and Cara Bray, she lost her faith and for a time refused to attend church, which caused a painful quarrel with her father.',
      'She became a translator and then a journalist. In 1846 she published an English translation of David Friedrich Strauss’s Life of Jesus, a German study that treated the gospels as myth in the making, and in 1854 she translated Ludwig Feuerbach’s The Essence of Christianity. In 1851 she moved to London, where she became assistant editor of the Westminster Review, a leading intellectual journal. There she met the writer and critic George Henry Lewes.',
      'In 1854 she began to live with Lewes, who was legally married to Agnes Jervis and, under the law of the time, could not obtain a divorce. Many people in respectable society turned away from her, and her brother Isaac cut off contact. Encouraged by Lewes, she began to write fiction, and “The Sad Fortunes of the Reverend Amos Barton” appeared in 1857 under the name George Eliot. Her novels, including Adam Bede (1859), The Mill on the Floss (1860), Silas Marner (1861), Middlemarch (1871–72) and Daniel Deronda (1876), made her one of the most admired writers of her age. Lewes died in 1878, and in May 1880 she married John Cross. She died that December and was buried at Highgate Cemetery.',
    ],
    context: [
      'Eliot lived through a crisis of faith that affected many educated Victorians. German biblical criticism, geology and the new science, including Darwin’s Origin of Species (1859), made it hard for many to accept the literal truth of scripture. Yet most people still believed that morality needed a religious foundation, and the question of whether goodness could survive the loss of belief in God was one of the great anxieties of the time.',
      'It was also a period in which the novel became the main form of serious public conversation. Eliot’s generation of women faced limited opportunities and strict codes of respectability, which is part of why she wrote under a man’s name and why her partnership with Lewes cost her so dearly. Her novels, set mostly in the English provinces of the early nineteenth century, ask how people live and what they owe each other in a changing society.' ,
    ],
    ideas: [
      { title: 'Sympathy as the root of morality', text: 'In an essay of 1856 she wrote that the greatest benefit the artist can give is the extension of our sympathies. For her, moral growth begins when we feel the reality of another person’s inner life. Her novels are built to produce this effect, by showing the same events from many points of view and by treating even unattractive characters with understanding.' },
      { title: 'Ethics without a divine commander', text: 'Having translated Strauss and Feuerbach, she did not believe in a personal God or in an afterlife, but she took morality seriously. She drew on Feuerbach’s idea that the qualities we attribute to God, such as love and compassion, belong to humanity, and she believed that duty, fellow-feeling and the memory of the dead could hold human life together. She described herself as a “meliorist”, one who believes that the world can be improved through human effort.' },
      { title: 'Consequences and responsibility', text: 'Her characters often make choices that seem small, and then find that they shape their whole lives. A lie, a hasty marriage or a refusal to face the facts has results that cannot be undone. She held that people are formed by habit and circumstance but are still responsible for what they do with them.' },
      { title: 'The importance of ordinary lives', text: 'Middlemarch ends by saying that the growing good of the world depends partly on unhistoric acts, and that many people who live faithfully a hidden life rest in unvisited tombs. Eliot gave ordinary people, such as a doctor with ideals, a young woman who wants to do good, or a clergyman, the seriousness that earlier fiction had reserved for heroes and aristocrats.' },
      { title: 'Egoism and moral blindness', text: 'In Middlemarch she remarks that each of us tends to see the world as if we were its centre, as if a candle held near a scratched mirror made all the scratches arrange themselves in circles around it. Much of her moral thinking is about the effort to see beyond one’s own self, in marriage, in work and in the way we judge others.' },
    ],
    principles: [
      'Try to understand the inner life of the person you disagree with.',
      'Remember that small choices, repeated, make a character.',
      'Do not wait for a grand stage on which to do good.',
      'Accept the consequences of your actions and do not look for others to blame.',
      'Be honest about doubt, and keep your commitments to others all the same.',
    ],
    practice: [
      'Before judging someone, write down three reasons why a sensible person might act as they did.',
      'Read fiction slowly and choose characters unlike yourself, and ask what the author wants you to feel for them.',
      'Look at your own daily habits, and ask what they will add up to in ten years.',
    ],
    facts: [
      'Eliot was about 37 when her first fiction appeared. Until then she was known as a translator, editor and essayist.',
      'Her real identity was kept secret until 1859, when a man named Joseph Liggins was falsely rumoured to be the author of Adam Bede and she revealed her name.',
      'Virginia Woolf called Middlemarch “one of the few English novels written for grown-up people”.',
      'Middlemarch was first published in eight parts between 1871 and 1872, and is set in the years around the first Reform Act of 1832.',
      'Her marriage at the age of 60 to John Cross, a banker about twenty years younger, was followed by her death within months. Her brother Isaac, who had refused to write to her for years, sent congratulations.',
      'Because of the scandal about her private life, she was not buried in Westminster Abbey. A memorial in Poets’ Corner was placed there in 1980, a century after her death.',
    ],
    myths: [
      { myth: '“It is never too late to be what you might have been” is a quotation from George Eliot.', reality: 'The line is widely attributed to her, but it has not been found in her published writings or letters, and scholars treat it as misattributed.' },
      { myth: 'She wrote under a man’s name only to hide the fact that she was a woman.', reality: 'Partly, since she wanted to be judged on her work rather than on her sex and her private life. Her biographer Cross reported that she chose “George” because it was Lewes’s name, and she and Lewes were also keen to avoid the scandal of her unmarried partnership. Women writers did publish under their own names in her day, so her motives are better described as a mixture.' },
      { myth: 'Because she rejected Christian doctrine, her novels are hostile to religion.', reality: 'Her novels portray religion with sympathy and detail, in the lives of the Methodist Dinah Morris in Adam Bede or the clergy of Middlemarch, and she took seriously its moral and communal role even though she did not accept its doctrines.' },
    ],
    works: [
      { title: 'Adam Bede (1859) and The Mill on the Floss (1860)', note: 'Her first full-length novels, which made her famous and which draw on her own memories of rural England.' },
      { title: 'Silas Marner (1861) and Romola (1862–63)', note: 'A short moral tale of a lonely weaver, and a historical novel set in Renaissance Florence.' },
      { title: 'Middlemarch (1871–72)', note: 'Her most celebrated novel, a study of a provincial town and the people whose lives interweave in it.' },
      { title: 'Daniel Deronda (1876)', note: 'Her last novel, which treats Jewish identity with unusual seriousness for its time.' },
      { title: 'Translations and essays', note: 'The translations of Strauss and Feuerbach, and essays such as “The Natural History of German Life” (1856), set out the ideas behind her fiction.' },
    ],
    legacy: [
      'Eliot’s psychological realism and her use of an intelligent, reflective narrator shaped the English novel. Henry James, Virginia Woolf and many later writers learned from her, and Middlemarch is regularly named among the great English novels.',
      'Her work also left a mark on moral philosophy, especially on ideas about the role of imagination and attention in ethics. Philosophers such as Martha Nussbaum have drawn on novels like hers in arguing that literature trains moral perception, while readers of every kind continue to turn to her for her portrayal of how people change, fail and sometimes do well.',
    ],
  },
  {
    slug: 'friedrich-engels',
    order: 1820,
    dates: '1820 – 1895',
    place: 'Barmen (Prussia), Manchester and London',
    era: '19th Century',
    tradition: 'Marxism',
    tagline: 'A mill-owner’s son who became Marx’s lifelong partner, and who did more than anyone to turn their shared ideas into a worldwide movement.',
    who: [
      'Friedrich Engels was born in November 1820 in Barmen, in the Rhineland, to a wealthy family of textile manufacturers with strong Protestant beliefs. He was withdrawn from school early to train for the family business, but he read widely, and as a young man in Berlin he joined the circle of radical followers of Hegel. In 1842 his father sent him to Manchester, England, to work at Ermen & Engels, a cotton-spinning firm in which the family had an interest.',
      'In Manchester he observed the poverty of the industrial working class, helped by a young Irish mill worker, Mary Burns, who became his companion, and he wrote The Condition of the Working Class in England (published in German in 1845). In 1844 he met Karl Marx in Paris, and the two began a collaboration that lasted until Marx’s death in 1883. Together they wrote The German Ideology and, in 1848, the Communist Manifesto. After the revolutions of 1848–49, in which Engels fought as a soldier in the Baden uprising, he returned to Manchester and worked in the family firm for about twenty years, partly to support Marx and his family with money.',
      'He left the business in 1869 and moved to London the next year. After Marx died he became the leading authority on their joint thought. He edited and published the second and third volumes of Capital from Marx’s notes, wrote Anti-Dühring (1878) and The Origin of the Family, Private Property and the State (1884), and advised socialist parties across Europe. He died of cancer of the throat in London in August 1895.',
    ],
    context: [
      'Engels’s world was the industrial revolution at its harshest. Manchester, the first great factory city, showed wealth and misery side by side, and the new working class lived in crowded and unhealthy districts with long hours and few legal protections. Many thinkers, Christian, utopian and radical, tried to understand and respond to it, and Engels’s book was part of this wave of social investigation.',
      'Politically it was an age of revolution and reaction. The risings of 1848 failed, the old regimes recovered, and many radicals went into exile. In the second half of the century trade unions and socialist parties grew, especially in Germany, where the Social Democratic Party became the largest in the country by votes. Engels’s role was to explain, defend and apply Marxist theory to these new conditions, and in his last years he was often asked for guidance on strategy.',
    ],
    ideas: [
      { title: 'The working class and industrial capitalism', text: 'In The Condition of the Working Class in England he combined his own observations in Manchester with official reports and the press to describe housing, health, factory work and the lives of workers. The book argued that industrial capitalism created a new class with a common interest. Later historians have both praised its pioneering detail and criticised it for bias and selectivity.' },
      { title: 'The materialist view of history', text: 'With Marx he held that the way a society produces its necessities, its economy, shapes its politics, laws and ideas, and that history is driven by conflicts between classes. In letters of the 1890s Engels insisted that this does not mean economics is the only factor, only that it is decisive “in the last instance”, and he admitted that he and Marx had sometimes overstated it.' },
      { title: 'Science, dialectics and socialism', text: 'In Anti-Dühring, written against Eugen Dühring, a Berlin lecturer with a following among German socialists, and in the shorter Socialism: Utopian and Scientific (1880), he set out a popular account of Marxism as a unified outlook. He argued that socialism rests on the analysis of real historical forces and not on moral appeals alone, a claim that made it attractive to the growing socialist parties.' },
      { title: 'Family, property and the state', text: 'The Origin of the Family, Private Property and the State, based partly on Marx’s notes on the anthropologist Lewis Henry Morgan, argued that monogamous marriage, private property and the state arose together, and that women’s subordination was linked to property. Its anthropology is now largely outdated, but it was a founding text for many later discussions of gender and economics.' },
      { title: 'Dialectics of nature', text: 'In manuscripts left unfinished and published after his death, Engels tried to extend the dialectical method to the natural sciences, with “laws” such as the turning of quantity into quality. This is the most criticised part of his legacy, since many later Marxists and scientists doubt that nature follows the same kind of logic as history.' },
    ],
    principles: [
      'Study conditions on the ground before theorising about them.',
      'Look for the material interests behind high-minded claims.',
      'Be ready to revise your theory when events and evidence change.',
      'Support the people whose work you rely on, and in practical ways.',
      'Treat theory as a guide to action, not as a creed.',
    ],
    practice: [
      'Before forming a view about a social problem, visit the place or speak to people who live there, as Engels did in Manchester.',
      'Ask of any policy or argument whose interests it serves, and who pays its cost.',
      'If you work with a collaborator, make clear and fair arrangements about credit and about money.',
    ],
    facts: [
      'Engels’s family firm, Ermen & Engels, had mills in Manchester. He became a partner in 1864 and sold out in 1869, and his income helped to keep Marx’s family alive for decades.',
      'The Condition of the Working Class in England appeared in German in 1845. The first English edition came out in the United States in 1887, and a British edition followed in 1892.',
      'After Marx’s death in 1883 Engels spent more than a decade deciphering Marx’s difficult manuscripts and preparing them as the second and third volumes of Capital.',
      'Engels lived with Mary Burns until her death in 1863 and then with her sister Lizzie, whom he married on her deathbed in 1878.',
      'Though a prominent communist, he enjoyed the lifestyle of a Manchester gentleman, including riding to hounds with a hunt.',
      'On his instructions, his body was cremated and his ashes were scattered in the sea off Eastbourne, near Beachy Head.',
    ],
    myths: [
      { myth: 'Engels invented “dialectical materialism” and gave Marx’s ideas their fixed form.', reality: 'The label was popularised after Engels’s death by writers such as Georgi Plekhanov and later became official Soviet doctrine. Engels spoke of the materialist conception of history, and many scholars argue that the systematic, scientific-sounding form given to Marxism owes more to his successors, and in part to him, than to Marx himself. Historians continue to debate how far Marx and Engels differed.' },
      { myth: 'Engels was merely a rich helper who followed Marx.', reality: 'He was an original writer, who reached many of the ideas about industrial capitalism before Marx, and Marx described the 1844 “Outlines of a Critique of Political Economy” as brilliant. At the same time, Marx was the more rigorous economist and theorist, and Engels often said so himself.' },
      { myth: 'In 1895 Engels rejected revolution and endorsed peaceful parliamentary politics.', reality: 'His last preface, to Marx’s Class Struggles in France, did stress the success of elections and the changes in military technology that made barricade fighting unlikely. He complained that party leaders had cut passages to make him look more peaceful, and historians still debate how far the text reflects his real views.' },
    ],
    works: [
      { title: 'The Condition of the Working Class in England (1845)', note: 'His first major book, a study of industrial Manchester and its workers.' },
      { title: 'The Communist Manifesto (1848, with Marx)', note: 'A short political programme written for the Communist League, and the best-known text of the movement.' },
      { title: 'Anti-Dühring (1878) and Socialism: Utopian and Scientific (1880)', note: 'Popular statements of Marxist theory, widely read in socialist parties.' },
      { title: 'The Origin of the Family, Private Property and the State (1884)', note: 'A study of family and class in history, based partly on Morgan’s Ancient Society.' },
      { title: 'Capital, Volumes II and III (1885, 1894) and Dialectics of Nature (1925)', note: 'Marx’s manuscripts edited by Engels; and his own unfinished essays on science, published after his death.' },
    ],
    legacy: [
      'Engels was the principal link between Marx and the socialist parties of the late nineteenth century. Through his books, which circulated widely and were translated into many languages, and through his letters, he shaped what most socialists thought Marxism meant, and without his editing and publication of the later volumes of Capital, the work would have been left far less complete.',
      'In the twentieth century, the Soviet state made his writings part of its official philosophy, and critics, including some Western Marxists, blamed Engels for turning Marx’s open-ended method into a rigid system. Others defend him, arguing that later interpreters, not he, gave Marxism its dogmatic form. The Condition of the Working Class in England is still read as an early work of social investigation, and his writings on family and gender continue to raise discussion.',
    ],
  },
]
