import type { Profile } from './types'

export const MORE_02: Profile[] = [
  {
    slug: 'patanjali',
    order: -200,
    dates: 'Uncertain; the Yoga Sutras date from c. 2nd century BC to c. 4th century AD',
    place: 'India (exact place unknown)',
    era: 'Ancient',
    tradition: 'Yoga philosophy',
    tagline: 'The name attached to the Yoga Sutras, a short and exact manual on quieting the mind and ending suffering.',
    who: [
      'Almost nothing secure is known about the person called Patanjali. No ancient source gives his dates, his birthplace or his family, and the stories that fill the gap are late. One tradition makes him an incarnation of Shesha, the divine serpent, who fell from heaven into the cupped hands of a woman at prayer; the name is sometimes explained from this tale. Such stories are devotional, not historical, and a careful profile should treat them that way.',
      'The name belongs to a text, the Yoga Sutras, a collection of about 195 or 196 aphorisms (the count varies between manuscripts) arranged in four chapters. Scholars debate when it took its present form. Estimates range from around the second century BC to the fourth or fifth century AD, and some think the work was assembled from earlier material by one editor or by several hands. “Patanjali” may therefore name an author, a compiler or a tradition.',
      'It is also worth separating him from a namesake. A grammarian called Patanjali wrote the Mahabhashya, a large commentary on the Sanskrit grammar of Panini, and can be dated firmly to the second century BC. Later Indian tradition, from roughly the eleventh century, often treated the grammarian and the yoga teacher as one man, but most modern scholars think they were two different people whose names happen to match.',
    ],
    context: [
      'The Yoga Sutras belong to a long Indian conversation about suffering and release. Before and around the time of the text, many teachers practised disciplines of the body and mind, and the Upanishads, early Buddhist and Jain teachings, and the Bhagavad Gita all use the word yoga for some kind of training. Patanjali’s contribution was to gather these methods into a compact system with a clear aim and a clear order of steps.',
      'Philosophically the Yoga Sutras stand close to Samkhya, one of the classical schools of Indian thought. Samkhya describes the world as two kinds of reality: purusha, pure awareness that simply witnesses, and prakriti, nature, which includes matter, the senses and the mind. Suffering arises, on this picture, when awareness mistakes itself for the changing contents of the mind. The Sutras add a practical method and a place for Ishvara, a special, untouched being who can serve as an object of devotion. The earliest major commentary, traditionally credited to Vyasa, helped make the text the standard statement of the Yoga school.',
    ],
    ideas: [
      { title: 'Yoga is the stilling of the mind', text: 'The second sutra of the book defines yoga as citta-vritti-nirodha: the settling of the whirling activity of the mind. The mind (citta) is full of waves (vrittis), such as correct perception, error, imagination, sleep and memory. When the waves settle, the Sutras say, the observer rests in its own nature instead of being swept along by thoughts. The aim is clarity, not blankness.' },
      { title: 'The five kleshas, the root of suffering', text: 'Patanjali names five afflictions that colour ordinary experience: ignorance of what is lasting and what is not (avidya), the sense of a separate and solid self (asmita), attachment to pleasure (raga), aversion to pain (dvesha), and clinging to life or fear of ending (abhinivesha). Ignorance is treated as the ground of the other four. The practical point is that suffering is not a random event but has causes that can be seen and weakened.' },
      { title: 'The eight limbs', text: 'The second chapter lays out eight “limbs” of practice: restraints toward others (yama), observances toward oneself (niyama), posture (asana), breath control (pranayama), withdrawal of the senses (pratyahara), concentration (dharana), meditation (dhyana) and absorption (samadhi). The first five are outer supports, the last three inner work. The order matters: conduct comes first, because a restless life makes a restless mind.' },
      { title: 'Ethics as the foundation', text: 'The restraints are non-harming (ahimsa), truthfulness, not stealing, restraint of desire and not grasping. The observances are cleanliness, contentment, disciplined effort, self-study and devotion to Ishvara. Patanjali does not offer these as rules imposed from outside. He presents them as conditions for a calm mind, since lying, harming and craving keep the mind agitated.' },
      { title: 'Practice and non-attachment', text: 'The first chapter says the mind is steadied by two things together: sustained practice (abhyasa) and letting go of craving (vairagya). Patanjali also offers a social method. Cultivate friendliness toward the happy, compassion toward the suffering, gladness toward the virtuous and calm toward the wrongdoer, and the mind grows serene. Posture itself gets only a short treatment: it should be steady and comfortable.' },
    ],
    principles: [
      'Understand the mind before trying to control the world.',
      'Pair steady practice with willingness to let go.',
      'Build conduct first: honesty and non-harm are the ground of a calm mind.',
      'Notice cravings and aversions as causes of suffering, not as facts about the world.',
      'Meet others with friendliness, compassion, gladness and equanimity.',
    ],
    practice: [
      'Sit quietly for a few minutes each day and simply notice the waves of thought arise and pass, without following each one.',
      'When you are upset, ask which of the five afflictions is at work: ignorance, ego, craving, aversion or fear of loss.',
      'Choose one restraint or observance, such as telling the truth in small matters, and keep it for a week.',
    ],
    facts: [
      'The Yoga Sutras are famously short. Each aphorism is only a few words, and without a commentary it is often hard to follow.',
      'Its four chapters are named Samadhi (absorption), Sadhana (practice), Vibhuti (powers) and Kaivalya (aloneness, or freedom).',
      'The third chapter discusses unusual powers that may arise in deep concentration, but warns that they can distract the practitioner from the goal.',
      'Patanjali the grammarian lived in the second century BC and wrote a long commentary on Panini. Whether he is the same man as the yoga teacher is doubted by most scholars.',
      'The eleventh-century scholar al-Biruni is known to have translated a text linked to Patanjali into Arabic, an early sign of how far the ideas travelled.',
      'The book became widely known in the modern world in large part through Swami Vivekananda’s lectures in the 1890s, later published as Raja Yoga.',
    ],
    myths: [
      { myth: 'Patanjali invented yoga, and the Sutras teach the postures popular in modern studios.', reality: 'Yoga was practised long before the Sutras, and the text gives posture only a brief mention, as a steady and comfortable seat. Modern postural yoga draws on many later sources and is largely a different thing.' },
      { myth: 'The author of the Yoga Sutras is the grammarian Patanjali, and his life is well documented.', reality: 'The identification appears only in later tradition, and most modern scholars doubt it. Nothing reliable is known about the author of the Sutras as a person.' },
      { myth: 'Yoga in the Sutras is simply a form of relaxation or fitness.', reality: 'The Sutras are about freeing awareness from suffering through ethics, attention and meditation. Calm is a by-product, not the final goal.' },
    ],
    works: [
      { title: 'Yoga Sutras', note: 'The only work credited to Patanjali in the yoga tradition, in four chapters of short aphorisms.' },
      { title: 'Vyasa, Yoga Bhashya', note: 'The earliest major commentary, traditionally credited to Vyasa, and the main way the text was read for centuries.' },
      { title: 'Vacaspati Mishra, Tattva-Vaisharadi', note: 'A later commentary on Vyasa’s work, from about the ninth or tenth century AD.' },
      { title: 'Bhoja, Raja-martanda', note: 'An eleventh-century commentary on the Sutras, also a source for the later identification with the grammarian.' },
      { title: 'Patanjali, Mahabhashya', note: 'The grammarian’s Great Commentary on Panini, included here to mark the separate tradition and not as a work on yoga.' },
    ],
    legacy: [
      'For many centuries the Yoga Sutras were studied mainly within Sanskrit scholarly circles and read with commentaries. Their ideas on mind, suffering and release fed into later Indian thought and meditative practice, and through translations in the medieval period they also reached readers beyond India.',
      'In the nineteenth and twentieth centuries the text became a standard reference for yoga in India and the wider world, and it is now translated into most major languages. Today people read it as a psychological manual, a religious text and a philosophical argument, and scholars continue to disagree about how much of the modern practice it really describes.',
    ],
  },
  {
    slug: 'archimedes',
    order: -287,
    dates: 'c. 287 – c. 212 BC',
    place: 'Syracuse, Sicily',
    era: 'Ancient',
    tradition: 'Greek mathematics',
    tagline: 'The mathematician of Syracuse who proved how levers and floating bodies behave, and showed that nature can be reasoned about with geometry.',
    who: [
      'Archimedes was born in Syracuse, a wealthy Greek city on the east coast of Sicily, around 287 BC. The date comes from a twelfth-century writer, John Tzetzes, who says he lived about seventy-five years, so it is only approximate. Archimedes himself mentions that his father was an astronomer named Phidias. Plutarch says he was a relative of the Syracusan king Hiero II, but Cicero speaks of him as a man of humble background, and the question is not settled.',
      'Tradition says he studied for a time in Alexandria, the great centre of Greek learning, where he would have met pupils of Euclid. He certainly kept in touch with Alexandrian scholars, since he sent his results to Conon, Dositheus and Eratosthenes, with letters that often explain how he found the proofs. Back in Syracuse he worked for Hiero, and ancient writers credit him with machines for lifting, hauling and defence.',
      'When Hiero died, Syracuse took the side of Carthage in the Second Punic War, and a Roman fleet and army under Marcellus besieged the city from about 213 BC. Ancient historians such as Polybius, Livy and Plutarch tell how Archimedes’ engines slowed the Romans for a long time. The city fell in 212 BC, and Archimedes was killed in the sack. Accounts of his death differ in detail, but they agree that a Roman soldier killed him, perhaps against orders. Marcellus is said to have mourned him.',
    ],
    context: [
      'Archimedes lived in the Hellenistic world, when Greek culture spread around the Mediterranean and many kings paid for scholars and engineers. Euclid’s Elements had set a standard for rigorous proof from stated starting points, and Archimedes worked in that style, while Syracuse, a city of ports, ships and wars, gave him real problems.',
      'The Second Punic War between Rome and Carthage pulled Sicily into the struggle. Syracuse had been a friend of Rome under Hiero, but his grandson Hieronymus broke with Rome after Hiero’s death, and the result was the siege that ended the independence of the city and, soon after, Archimedes’ life.',
    ],
    ideas: [
      { title: 'Proof as the model of knowledge', text: 'Archimedes treated difficult questions about areas, volumes and balance as problems to be settled by strict proof, in the manner of Euclid. He showed, for instance, that the area of a segment of a parabola is four thirds of the area of a certain inscribed triangle, using the “method of exhaustion”, which closes in on a result from both sides without any appeal to eye or measurement. This habit of demonstrating instead of asserting is his deepest legacy.' },
      { title: 'Mathematics applied to nature', text: 'In On the Equilibrium of Planes he derives the law of the lever from stated postulates and then uses it to find centres of gravity. In On Floating Bodies he does the same for fluids, and shows how a body in water behaves. Few earlier Greeks had treated physical questions as theorems, so he is often called a founder of mathematical physics.' },
      { title: 'The principle of buoyancy', text: 'The first book of On Floating Bodies shows that a body immersed in a fluid is pushed up by a force equal to the weight of the fluid it displaces. This is the result now called Archimedes’ principle, and it explains why ships float. It is one of the oldest laws of physics that we still use.' },
      { title: 'Handling the very large and the very small', text: 'In the Sand Reckoner he builds a system for naming huge numbers, in order to count the grains of sand that would fill the universe. In the process he mentions Aristarchus’s theory that the Earth moves around the Sun. In Measurement of the Circle he traps the value of pi between 223/71 and 22/7 using polygons inscribed and circumscribed around a circle.' },
      { title: 'Finding by mechanics, proving by geometry', text: 'In a letter to Eratosthenes, now called the Method, Archimedes explains that he often discovered results by imagining shapes balanced on a lever, cut into thin slices. He insisted that this was a way of finding answers, not of proving them, and that a proof still had to be given by geometry. It is an early statement of the difference between discovery and justification.' },
    ],
    principles: [
      'Demand a proof, not just a confident claim.',
      'Break a hard problem into simple parts you can handle.',
      'Let experiment and imagination suggest answers, then check them with rigour.',
      'Look for the law behind a working machine.',
      'Keep thinking even in difficult times, and be curious to the end.',
    ],
    practice: [
      'When you solve a problem, write down why the answer must be right, not just what it is.',
      'Try a rough estimate before you calculate, and then use the estimate to catch mistakes.',
      'Take apart something you use daily, such as a lever, a pulley or a tap, and explain in plain words why it works.',
    ],
    facts: [
      'Vitruvius, writing about two centuries after Archimedes, tells the story of the crown. King Hiero doubted that a goldsmith had used all the gold he was given, and Archimedes is said to have found the answer while bathing, noticing the water he displaced, and to have run through the streets shouting “Eureka”. The story is a late anecdote, and its details may be embellished.',
      'He asked that a sphere inside a cylinder be carved on his tomb, to mark his result that the sphere’s volume is two thirds of the cylinder’s. Cicero, serving in Sicily in 75 BC, says he found the overgrown tomb with that figure on it.',
      'Pappus, in the fourth century AD, attributes to him the boast that, given a place to stand, he could move the Earth. It is reported centuries after the fact.',
      'The Archimedean screw, a spiral inside a tube that lifts water, is traditionally linked to him, though some historians suspect it was already known in Egypt.',
      'The Archimedes Palimpsest, a prayer book written in 1229 on re-used parchment, hides the only known copies of the Method and part of On Floating Bodies in their original Greek. Johan Ludvig Heiberg identified the undertext in Constantinople in 1906.',
      'The manuscript was sold at auction in 1998 and then studied with ultraviolet light and X-ray imaging, which recovered much of the erased text.',
    ],
    myths: [
      { myth: 'Archimedes burned Roman ships with giant mirrors.', reality: 'The earliest accounts of the siege mention catapults, cranes and grappling devices and say nothing of mirrors. The burning-mirror tale appears centuries later, and modern attempts to reproduce it have had little success.' },
      { myth: 'He shouted “Eureka” in the bath and invented the principle of buoyancy on the spot.', reality: 'The tale is told by Vitruvius long after his death. His own surviving work, On Floating Bodies, derives buoyancy by logical steps from postulates, which is far more impressive than a flash of insight.' },
      { myth: 'Archimedes despised practical engineering and cared only for pure mathematics.', reality: 'Plutarch says he regarded mechanical work as ignoble, but Plutarch also reports that Archimedes designed devices for Hiero. His own treatises treat mechanics as a source of mathematical ideas.' },
    ],
    works: [
      { title: 'On the Sphere and Cylinder', note: 'Finds the surface and volume of a sphere and relates them to the cylinder around it.' },
      { title: 'Measurement of the Circle, and Quadrature of the Parabola', note: 'The bounds on pi, and the area of a parabolic segment by exhaustion.' },
      { title: 'On the Equilibrium of Planes; On Floating Bodies', note: 'The foundations of statics and hydrostatics, in a deductive style.' },
      { title: 'The Sand Reckoner', note: 'A short, readable work on naming very large numbers, addressed to Gelon, the son of Hiero.' },
      { title: 'The Method', note: 'A letter to Eratosthenes on discovery by mechanics, found only in the Palimpsest and lost for centuries.' },
    ],
    legacy: [
      'His works were copied and studied in Byzantium and the Islamic world, and Latin translations in the Middle Ages and Renaissance brought him back into Western science. Galileo admired him and wrote on the balance and on floating bodies in his manner. His method of exhaustion was a precursor of the integral calculus developed by Newton and Leibniz.',
      'Philosophically he stands for a particular claim: that nature obeys rules that can be written as mathematics and proved. That claim underlies modern science. The rediscovery of the Method in 1906 also showed that one of antiquity’s greatest mathematicians was reflective about how he found things, and not only about how he proved them.',
    ],
  },
  {
    slug: 'han-fei',
    order: -280,
    dates: 'c. 280 – 233 BC',
    place: 'State of Han, then the state of Qin (China)',
    era: 'Ancient',
    tradition: 'Legalism',
    tagline: 'The Warring States thinker who argued that a state should be run by clear laws and checks on its officials, not by the goodness of rulers.',
    who: [
      'Han Fei was born around 280 BC into the ruling family of the small state of Han, one of the seven great states fighting for supremacy in China in the Warring States period. The main source for his life is the historian Sima Qian, who wrote about a century and a half later. According to him Han Fei studied with the Confucian master Xunzi alongside Li Si, who would become a powerful minister of Qin. Han Fei is said to have stammered, which made it hard for him to speak at court, but he wrote with force.',
      'He watched his homeland weaken and wrote repeatedly to the king of Han, urging reforms that would strengthen the state, but he was not given a position of influence. Frustrated, he turned to writing essays on rulers, ministers and how states fall. Some reached the king of Qin, Ying Zheng, who is reported to have said that he could die without regret if he could meet the author.',
      'Qin attacked Han, and Han Fei went to Qin, sent, according to Sima Qian, as an envoy. There Li Si and another courtier warned the king that Han Fei would always put Han’s interests first. The king had him jailed, and in 233 BC he died there, by poison that Li Si is said to have sent him. The king is reported to have regretted it and sent a pardon too late. Qin conquered Han in 230 BC and completed the conquest of China in 221 BC, and Ying Zheng became the First Emperor.',
    ],
    context: [
      'For two and a half centuries the Zhou kings had lost real power, and the states under them fought almost without pause. Thinkers of the “hundred schools” offered competing cures. Confucius and his followers wanted rulers to govern by moral example. Mohists wanted impartial care and economy. Daoist writers urged simplicity and restraint. Han Fei was the heir of a fourth group, now called Legalists, who looked for methods that would work whatever the character of the ruler.',
      'Several earlier figures lay behind his work. Shang Yang, who reformed Qin in the fourth century BC, stressed public law with rewards and punishments. Shen Buhai taught the ruler techniques for managing his officials, and Shen Dao stressed the authority that comes from the ruler’s position. Han Fei combined these strands, and the Daoist idea of a ruler who stays quiet and unreadable, into a single system. The name “Legalism” was applied to this group later, by Han-dynasty writers.',
    ],
    ideas: [
      { title: 'Law (fa)', text: 'Laws should be public, clear and applied equally, with fixed rewards for service and fixed penalties for crime. If the rules are known and enforced even for the powerful, people can predict the results of their actions and order does not depend on anyone’s mercy or mood. Han Fei believed that stable rules do more good than hoping for virtue.' },
      { title: 'Technique (shu)', text: 'The ruler must be able to test his officials. Han Fei urged matching “forms and names”: an official states what he will do, and the ruler later compares the result with the promise. Doing more than promised is punished as well as doing less, because it shows that the officials are not being straight. This is an early theory of accountability.' },
      { title: 'Position (shi)', text: 'The power of a ruler lies in his office, not in his personal qualities. Han Fei argued that most rulers are neither sages nor tyrants but average, so a state should be designed to work with an ordinary person at the top. He warned that ministers can capture a ruler through the “two handles” of reward and punishment if he gives them up.' },
      { title: 'A realistic view of human motives', text: 'Han Fei assumed that people mostly follow their interests. He saw this as a fact to plan for, not a reason for scorn: set up incentives so that private advantage leads to public good. He also warned rulers not to reveal their likes and dislikes, since flatterers will exploit them, and he borrowed from Daoist writing the ideal of a ruler who acts through the system and keeps himself hidden.' },
      { title: 'Change with the times', text: 'In the story of the farmer of Song, a man sees a hare run into a tree stump and break its neck. He abandons his plough and waits by the stump for more hares, and becomes a laughing-stock. Han Fei uses it to mock those who think that the practices of ancient sage kings must be copied today. A good ruler suits his policies to present conditions.' },
    ],
    principles: [
      'Make rules clear, public and consistent.',
      'Judge people by what they do, not by what they say about themselves.',
      'Do not depend on virtue alone to solve problems that need design.',
      'Match your methods to the actual circumstances, not to the past.',
      'Beware of those who profit by flattering the person in charge.',
    ],
    practice: [
      'When you set a goal for a team or for yourself, write down the measurable result, then check it honestly later.',
      'Where possible, replace a decision that depends on someone’s good mood with a rule that does not.',
      'Notice when you are repeating a habit only because it worked in the past, and ask whether the conditions have changed.',
    ],
    facts: [
      'The book Han Feizi has 55 chapters. Scholars think some were added or edited by others, but most accept that many are by Han Fei.',
      'Sima Qian lists among his essays “Solitary Indignation”, “The Five Vermin”, “Difficulties of Persuasion” and the collections of stories known as Inner and Outer Congeries.',
      'The Han Feizi contains two chapters that comment on the Daoist text Laozi, among the earliest known commentaries on it, though their authorship is debated.',
      'The Chinese word for “contradiction”, maodun (“spear-shield”), comes from a story in the book about a man selling a spear that pierces any shield and a shield that no spear can pierce.',
      'In “The Five Vermin” Han Fei names five groups he considered harmful to the state: scholars, orators, swordsmen, courtiers who avoid military service, and merchants and artisans who profit while the farmers and soldiers bear the burden.',
      'The state that used his methods did not last long after its triumph: the Qin dynasty fell in 206 BC, only a few years after the First Emperor’s death in 210 BC.',
    ],
    myths: [
      { myth: 'Han Fei invented Legalism and believed that harsh punishment is the answer to everything.', reality: 'He drew on earlier thinkers such as Shang Yang, Shen Buhai and Shen Dao. His books also stress administrative technique and the limits on a ruler, not only punishment, although he certainly defended severe penalties.' },
      { myth: 'He was executed on the First Emperor’s orders.', reality: 'Sima Qian says he was jailed on the strength of Li Si’s slanders and died by poison in prison. The king then regretted his death. Even this is a late account, and historians cannot confirm the details.' },
      { myth: 'Han Fei is simply the Chinese Machiavelli.', reality: 'The two share a cool view of power, but the comparison hides differences. Han Fei wrote for a system of impersonal law and offices, and he saw the ideal ruler as removed from the machinery of government, which is not Machiavelli’s picture.' },
    ],
    works: [
      { title: 'Han Feizi', note: 'The book that bears his name, in 55 chapters of essays, arguments and illustrative stories.' },
      { title: 'The Five Vermin (Wu Du)', note: 'His critique of Confucian scholars, itinerant orators, swordsmen and others, and the story of the farmer and the hare.' },
      { title: 'Difficulties of Persuasion (Shui Nan)', note: 'A famous essay on how hard it is to advise a ruler without giving offence.' },
      { title: 'Sima Qian, Records of the Grand Historian', note: 'The main ancient biography, written about a century and a half after Han Fei’s death.' },
      { title: 'Chapters on the Laozi', note: 'Two chapters of the Han Feizi that comment on the Daoist classic.' },
    ],
    legacy: [
      'The state of Qin put into practice many of the methods Han Fei described, and it conquered the other states, but the dynasty collapsed within fifteen years, and later Chinese writers often blamed its harsh rule. The succeeding Han dynasty openly favoured Confucian teaching, yet its government continued to rely on written law, penalties and checks on officials, as historians have often observed.',
      'In the twentieth and twenty-first centuries scholars and political leaders have returned to Han Fei in debates about law, bureaucracy and authoritarianism. Some see him as a clear-eyed theorist of institutions, others as a defender of absolute power, and both views have evidence in his text. His writing is still valued for its clarity, its stories and its insistence that good government is a matter of design.',
    ],
  },
  {
    slug: 'horace',
    order: -65,
    dates: '65 – 8 BC',
    place: 'Venusia, Rome and a farm in the Sabine hills (Italy)',
    era: 'Ancient',
    tradition: 'Roman poetry',
    tagline: 'The Roman poet who turned a plain philosophy of moderation, friendship and living in the present into some of the most quoted lines in Latin.',
    who: [
      'Quintus Horatius Flaccus was born on 8 December 65 BC in Venusia, a town in southern Italy. His father was a freed slave who had become a prosperous auctioneer’s agent, and who spent money to give his son an excellent education in Rome and then in Athens. Horace later spoke with great affection of this father and of the moral lessons he taught by example.',
      'In Athens he joined the army of Brutus, the assassin of Julius Caesar, and served as a military tribune. Brutus lost at Philippi in 42 BC, and Horace, by his own joking account, ran away and left his shield behind. His father’s property was confiscated, but Horace was pardoned and found work as a clerk in the treasury, writing verse on the side. About 38 BC the poets Virgil and Varius introduced him to Maecenas, a wealthy friend and adviser of Octavian, the future Augustus.',
      'Maecenas became his patron and friend, and gave him a farm in the Sabine hills, where Horace wrote and rested. His poems grew in range and assurance, and Augustus asked him to write a hymn for the Secular Games in 17 BC. Suetonius reports that Augustus even offered him the post of private secretary, which Horace declined without losing the emperor’s favour. Horace died on 27 November 8 BC, a few weeks after Maecenas, and was buried near him in Rome.',
    ],
    context: [
      'Horace grew up in the last years of the Roman Republic, which collapsed in civil war. The murder of Caesar, the war between his killers and the heirs, and then the struggle between Octavian and Antony shaped his youth. When Octavian won at Actium in 31 BC and became Augustus, many Romans felt relief, and Horace’s later poems share this mood, though he never fully gives up his independence.',
      'The Augustan age saw a flowering of Latin literature, and patrons such as Maecenas supported poets who could celebrate Rome’s peace and renewal. Horace admired Greek models, especially the lyric poets Alcaeus and Sappho, and he took pride in claiming to be the first to bring Greek lyric metres into Latin. Philosophically he moved between schools. He jokes that he is a pig from Epicurus’s herd, yet he often sounds like a Stoic when he praises self-command, and he declares that he is not bound to swear by the words of any master.',
    ],
    ideas: [
      { title: 'Seize the day', text: 'In one of his Odes he tells a woman not to ask what the gods have planned for her and to trust the future as little as possible, and ends with the phrase carpe diem, “pluck the day”, which he is the first known writer to use. The point is not reckless pleasure. Life is short and uncertain, so do what is good and enjoyable now instead of postponing life to a future that may not come.' },
      { title: 'The golden mean', text: 'In another Ode he praises the “golden mean” (aurea mediocritas): the person who loves the middle way avoids both the squalor of a hovel and the envy attracted by a palace. Tall trees are shaken by winds and high towers fall hardest. Moderation is both a moral and a practical wisdom.' },
      { title: 'Equanimity in good times and bad', text: 'Horace tells his friends to keep a balanced mind in difficulty and not to be too joyful in prosperity, since death comes to all. This note, close to Stoic thought, runs through the Odes and gives their gaiety a serious edge.' },
      { title: 'Satire with a smile', text: 'His Satires and Epistles use conversational verse to examine greed, ambition, envy and fussiness, often with himself as the target. He says that someone may “tell the truth while laughing”. The famous fable of the town mouse and the country mouse argues for a simple life, without the anxieties that come with luxury.' },
      { title: 'Poetry as craft', text: 'In the Ars Poetica, a verse letter on writing, he recommends that poets choose a subject suited to their strength, avoid inconsistency, and revise patiently, and that poetry should both please and instruct. His remarks about starting a story in the middle of things have shaped discussions of narrative ever since.' },
    ],
    principles: [
      'Enjoy the present without staking everything on the future.',
      'Prefer the middle way to extremes of luxury or hardship.',
      'Keep a level mind in success and in trouble.',
      'Be content with enough, and notice how little a good life needs.',
      'Dare to use your own understanding, a call he makes in the Epistles with the words sapere aude.',
    ],
    practice: [
      'Pick one pleasure that is available today, such as a meal with a friend or a walk, and do it fully instead of putting it off.',
      'When you want something, ask what “enough” would look like, and write the answer down.',
      'Revise something you have written after leaving it for a few days, in the way Horace advised poets to let work rest.',
    ],
    facts: [
      'His works include the Satires (two books), the Epodes, the Odes (four books), the Epistles (two books) and the Carmen Saeculare, a hymn for the Secular Games of 17 BC. The Ars Poetica is usually printed with the Epistles.',
      'The first three books of Odes appeared about 23 BC, and a fourth followed around 13 BC.',
      'He ends the third book of Odes by claiming that he has built a monument more lasting than bronze. Two thousand years later the claim is hard to dispute.',
      'The phrase dulce et decorum est pro patria mori (“it is sweet and fitting to die for one’s country”) is from his Odes. Wilfred Owen later used it as the title of a poem about the horror of the First World War, calling it an old lie.',
      'The farm in the Sabine hills, given to him by Maecenas, is a recurring subject in his poetry as a place of simplicity and peace.',
      'He described himself, with some humour, as short and fond of the sun, with greying hair early in life.',
    ],
    myths: [
      { myth: 'Carpe diem means live for pleasure and ignore the consequences.', reality: 'In its poem the phrase follows a reminder that life is short and the future uncertain. It advises making good use of the time you have, with a calm and accepting temper, which is closer to his ideal of moderation than to indulgence.' },
      { myth: 'Horace was simply a mouthpiece for Augustus.', reality: 'He wrote for Augustus and his circle, but scholars differ about how far he was a propagandist. He kept some distance, turned down a post in the emperor’s household, and filled his work with irony and personal voice.' },
      { myth: 'He was a committed Epicurean, or a committed Stoic.', reality: 'He mixes ideas from several schools and says he is bound to none. His outlook is an eclectic practical wisdom, not a system.' },
    ],
    works: [
      { title: 'Satires (Sermones)', note: 'Two books of conversational verse on ambition, greed and friendship, from the 30s BC.' },
      { title: 'Odes (Carmina)', note: 'Four books of lyric poems on love, wine, friendship, patriotism and mortality, his most admired work.' },
      { title: 'Epodes', note: 'Shorter poems in the manner of the Greek poet Archilochus, with a sharper tone.' },
      { title: 'Epistles', note: 'Letters in verse on how to live, addressed to friends and patrons.' },
      { title: 'Ars Poetica (Art of Poetry)', note: 'A verse letter on the craft of poetry, traditionally placed with the Epistles.' },
    ],
    legacy: [
      'Horace was read in Roman schools and then through the Middle Ages and the Renaissance, and he became one of the most quoted of classical authors. Poets from Petrarch to Pope imitated him, and essayists such as Montaigne drew on him for a conversational style of reflection. The English-speaking world has long known him through his phrases: carpe diem, the golden mean and “dare to know”.',
      'His appeal rests on a rare combination of polish and ease. He treats philosophy as something one lives with at the dinner table and in the countryside, not as a system, and he is honest about his own flaws. For readers today he offers a model of a humane, self-aware moderation that does not claim to cure every trouble.',
    ],
  },
  {
    slug: 'philo-of-alexandria',
    order: -20,
    dates: 'c. 20 BC – c. AD 50',
    place: 'Alexandria, Egypt',
    era: 'Ancient',
    tradition: 'Hellenistic Judaism',
    tagline: 'A Jewish thinker in Greek-speaking Alexandria who read the Torah through Plato and made scripture speak to philosophy.',
    who: [
      'Philo was born into a wealthy and prominent Jewish family in Alexandria, the great Egyptian port that was also a centre of Greek learning. Only a few facts are secure, because the main sources are his own writings and a short mention by the historian Josephus. His brother Alexander held the important post of alabarch, a senior official, and his nephew Tiberius Julius Alexander gave up the Jewish way of life and later became governor of Egypt. Philo’s dates are estimated, c. 20 BC to c. AD 50.',
      'He received a thorough Greek education, and his writings show wide knowledge of Plato, the Stoics and the Pythagoreans. He read scripture in the Greek translation known as the Septuagint, and most scholars think he knew little or no Hebrew. He also says he once went to Jerusalem to pray, and he writes admiringly of the Temple and of Jewish customs. Alexandrian Jews were a large community, and Philo tried to show that their faith was in harmony with the best of Greek thought.',
      'In AD 38 anti-Jewish violence broke out in Alexandria, and the Roman prefect Flaccus did little to stop it. Philo described the events in Against Flaccus. In the aftermath the Jewish community sent an embassy to the emperor Caligula in Rome, and Philo, then an older man, was one of its leaders. He describes the failed audience in On the Embassy to Gaius, where Caligula’s demand to be worshipped is the main danger. Caligula was murdered in AD 41, and the trail of Philo’s life then goes cold.',
    ],
    context: [
      'Alexandria in Philo’s time was a cosmopolitan city, with Greek, Egyptian and Jewish communities that were often in tension. The Jews of Alexandria spoke Greek and had translated their scriptures into it, and so they were a bridge between two traditions. The great library and the schools of the city kept Greek philosophy alive, particularly Platonism and Stoicism, and the Jewish thinkers had to explain to themselves and to their neighbours how their faith stood beside it.',
      'Rome ruled Egypt as a province, and relations between the Roman governor, the Greek citizens and the Jews were a source of repeated conflict. The riots of AD 38 were among the worst, and they made Philo’s defence of his people urgent. His work is therefore both philosophy and a political plea: he wanted Jewish tradition respected as a rational and ancient wisdom.',
    ],
    ideas: [
      { title: 'Allegorical reading of scripture', text: 'Philo believed that the Torah has a literal meaning and a deeper one. Adam, Eve and the serpent, or Abraham’s journey from Ur, can stand for the soul moving between reason and desire or travelling toward God. Allegory allowed him to hold that scripture was true and that it agreed with philosophy, and he is the best-known early practitioner of the method in Judaism.' },
      { title: 'The Logos', text: 'Philo borrows the Greek idea of the Logos, meaning reason or word, and makes it a mediator between the transcendent God and the world. He calls it God’s image, the instrument by which the world was made and the pattern behind it. Whether he thought of it as a person or as a divine power is debated, but the idea gave later thinkers a model for how an unchanging God could act in the world.' },
      { title: 'Creation and Plato', text: 'Reading the opening of Genesis alongside Plato’s Timaeus, Philo explains that God first conceived an ideal plan of the world and then made the visible world as its copy. Unlike many Greek philosophers he holds that God brought the world into being and cares for it. The synthesis is his most characteristic achievement.' },
      { title: 'God beyond description', text: 'For Philo, God is without a body, a change or a limit, and no name or concept can fully describe him. We can know that God is, but not what God is. This stress on divine transcendence runs through his work and later shaped “negative” ways of speaking about God.' },
      { title: 'Philosophy as the soul’s ascent', text: 'He holds that the goal of life is to rise from the senses and passions toward the knowledge and love of God, guided by virtue and contemplation. In On the Contemplative Life he describes a group of Jewish ascetics, the Therapeutae, who lived by the Lake Mareotis near Alexandria, as an ideal of this life.' },
    ],
    principles: [
      'Read old texts closely, and look for what they mean, not only what they say.',
      'Let faith and reason inform each other instead of competing.',
      'Move from the senses and passions toward understanding.',
      'Remember that our language about the highest things is always limited.',
      'Defend your community with courage, and by argument and not by violence.',
    ],
    practice: [
      'When you read a hard text, write down its literal meaning first, then ask what else it might be about.',
      'When you meet two traditions that seem to disagree, look for what each is trying to protect before choosing between them.',
      'Spend a little time each week on contemplation or reflection, away from screens.',
    ],
    facts: [
      'Philo’s surviving works fill many volumes, which is far more than we have from most Jewish writers of his time.',
      'Josephus mentions him as a man of high standing who headed the Jewish embassy to Caligula.',
      'Philo’s works were preserved mainly by Christians. Church writers such as Clement of Alexandria and Origen used him heavily, and some works survive only in an Armenian translation.',
      'Early Christian historians such as Eusebius and Jerome wrote about him as a notable author, though there is no sign that he knew anything of Christianity.',
      'The rabbinic literature does not clearly mention him, and Jewish tradition largely neglected his work for many centuries.',
      'In Against Flaccus he reports that the prefect was later arrested, sent into exile and put to death, which he reads as divine justice.',
    ],
    myths: [
      { myth: 'Philo was the first Christian philosopher.', reality: 'He was a Jew who wrote about Jewish scripture and had no knowledge of Jesus or Christianity. Christians preserved and used his work, but he did not write for them.' },
      { myth: 'Philo’s Logos is the same as the Logos in the Gospel of John.', reality: 'There are similarities of vocabulary and background, and scholars debate the relation. But the Gospel’s claim that the Logos became flesh has no counterpart in Philo.' },
      { myth: 'The saying “be kind, for everyone you meet is fighting a hard battle” comes from Philo.', reality: 'The line is often credited to Philo or to Plato, but it is generally traced to a Scottish minister who wrote under the name Ian Maclaren in the 1890s. It is not found in his works.' },
    ],
    works: [
      { title: 'On the Creation of the World', note: 'His reading of the first chapters of Genesis alongside Plato’s Timaeus.' },
      { title: 'Allegorical Commentary on Genesis', note: 'A series of treatises that read Genesis as a story of the soul.' },
      { title: 'Exposition of the Law, including On the Life of Moses', note: 'A presentation of the Torah and its laws for an outside readership.' },
      { title: 'Questions and Answers on Genesis and Exodus', note: 'A verse-by-verse commentary, partly surviving only in Armenian.' },
      { title: 'Against Flaccus and On the Embassy to Gaius', note: 'His eyewitness accounts of the violence in Alexandria in AD 38 and the embassy to Caligula.' },
    ],
    legacy: [
      'Philo’s method of reading scripture allegorically was taken up by Christian thinkers, among them Clement and Origen, and it shaped how the Bible was read for more than a thousand years. His idea of the Logos and his picture of a transcendent God also influenced early Christian theology, though he was not a Christian and did not hold the doctrines that came after.',
      'Jewish thought mostly passed him by until modern scholars took him up again, and he is now studied as the main witness to Hellenistic Judaism and as an early attempt to join faith and philosophy. His effort to show that revelation and reason can agree went on to inspire medieval thinkers, Jewish, Christian and Muslim.',
    ],
  },
]
