import type { Profile } from './types'

export const MORE_17: Profile[] = [
  {
    slug: 'fernando-pessoa',
    order: 1888,
    dates: '1888 – 1935',
    place: 'Lisbon, Portugal (childhood in Durban, South Africa)',
    era: '20th Century',
    tradition: 'Modernist poetry',
    tagline: 'A Lisbon clerk who wrote as dozens of different authors and left behind a trunk full of unfinished books.',
    who: [
      'Fernando António Nogueira Pessoa was born in Lisbon on 13 June 1888. His father died when he was five, and after his mother married João Miguel Rosa, the Portuguese consul in Durban, the family moved to South Africa in 1896. He was schooled in English, at a convent school and then at Durban High School, and in 1903 he won the Queen Victoria Prize for English prose. In 1905, aged seventeen, he returned alone to Lisbon to study. He did not finish his university course.',
      'For the rest of his life he stayed in Lisbon, mostly in rented rooms, earning a modest living as a freelance commercial correspondent who wrote and translated business letters in English and French for trading firms. The job left time for his real work. He wrote poetry, essays and criticism in Portuguese, English and French. In 1915 he helped start the magazine Orpheu with Mário de Sá-Carneiro and Almada Negreiros. Only two issues appeared, but they scandalised the Lisbon press and are seen as the start of Portuguese modernism. Sá-Carneiro killed himself in Paris in 1916.',
      'Pessoa published little under his own name. His lifetime output was a few English-language booklets in 1918 and 1921, poems and essays in magazines, and one Portuguese book, Mensagem, in 1934. He died in Lisbon on 30 November 1935, aged 47. The cause is usually given as a liver ailment linked to heavy drinking, though this is not certain. After his death a trunk was found holding some 25,000 manuscript and typed pages, and his reputation has grown from that archive.',
    ],
    context: [
      'Portugal changed fast during his adult life. The monarchy fell in 1910 and the unstable First Republic followed, ended by a military coup in 1926. The authoritarian Estado Novo regime of António de Oliveira Salazar took shape in the early 1930s. Pessoa watched this with mixed feelings, and in 1935 he published a newspaper article against a bill aimed at secret societies such as Freemasonry.',
      'Intellectually he was a child of the age of isms. Symbolism, decadence, Futurism and Cubism were all arriving in Lisbon through magazines and cafés, and Orpheu mixed them together. Pessoa also read widely in philosophy, theosophy and the occult, and he drew up astrological charts for himself and his invented authors. Behind it all stood Portugal’s old sea-faring past, which he treated as a source of myth as much as of history.',
    ],
    ideas: [
      { title: 'Heteronyms, not pen names', text: 'Pessoa invented authors with their own biographies, personalities, philosophies and writing styles, and called them heteronyms. The best known are Alberto Caeiro, Ricardo Reis and Álvaro de Campos, and he is thought to have invented more than seventy names in all. He described the result as a “drama in people” rather than a drama in acts. His 1935 account that Caeiro and the others appeared in one burst of inspiration on 8 March 1914 is regarded by scholars as a partly invented story.' },
      { title: 'Three voices, three ways of seeing', text: 'Caeiro, presented as a simple shepherd-poet, rejects metaphysics and insists that things are just what they are. Reis, a doctor and classicist, writes calm, disciplined odes in the spirit of Epicureanism and Stoicism. Campos, supposedly a naval engineer from Tavira, begins as a loud Futurist and ends as a weary, restless modern man, as in his poem “Tabacaria” (“Tobacconist’s”). Each is a different answer to the same question: how should one live in a world without certainty?' },
      { title: 'The poet as pretender', text: 'In his poem “Autopsicografia”, Pessoa says the poet is a pretender who feigns so completely that he feels even the pain he really feels. Feeling is turned into art by imagination, and the reader feels something else again. For Pessoa, the self is not a fixed possession but something shaped, and sometimes shattered, by writing.' },
      { title: 'The Book of Disquiet', text: 'This is a collection of fragments, diary-like and dreamy, about the life of a Lisbon bookkeeper. Pessoa gave it to a semi-heteronym, Bernardo Soares, whose voice differs from his own mainly by being less capable of action. Pessoa called it a “factless autobiography”. It was never assembled by him, so every edition, the first of which came out only in 1982, makes its own choices about order and content.' },
      { title: 'Mensagem and the Fifth Empire', text: 'Mensagem (“Message”), his only Portuguese book published in his lifetime, is a sequence of poems about Portuguese heroes, sea voyages and national myth. It looks forward to a spiritual “Fifth Empire” of culture rather than conquest, and to the return of the lost young King Sebastian. The regime’s propaganda office gave it a prize, but readers still argue whether it endorses nationalism or quietly questions it.' },
    ],
    principles: [
      'Admit that you are many people, and give each of them a voice.',
      'Look at things as they are before explaining them away.',
      'Use imagination to understand lives unlike your own.',
      'Make something even when you doubt it will be finished.',
      'Be honest about your restlessness, since it can be a source of writing and not only of pain.',
    ],
    practice: [
      'Write a page from the point of view of someone who disagrees with you, in a style quite unlike your own, and see what you learn.',
      'Keep a notebook of fragments without worrying about order, as Pessoa did, and reread it after a few months.',
      'Take a walk in your own city, describing exactly what you see without commentary, in the manner of Caeiro.',
    ],
    facts: [
      'Pessoa means “person” in Portuguese, and the Latin word persona originally meant a mask.',
      'He is thought to have invented more than seventy named authors, some with their own horoscopes, which he cast himself.',
      'In 1930 he met the occultist Aleister Crowley in Lisbon and helped him to stage a fake suicide at the cliffs of Boca do Inferno.',
      'He lived from 1920 until his death in the apartment that is now the Casa Fernando Pessoa museum.',
      'His last written words, dated 29 November 1935, were in English: “I know not what tomorrow will bring.”',
      'In 1985, fifty years after his death, his remains were moved to the Jerónimos Monastery in Lisbon, alongside national heroes.',
    ],
    myths: [
      { myth: 'Pessoa was unknown during his lifetime.', reality: 'He was little known to the general public, but he was well known in Lisbon’s literary circles, edited and contributed to several magazines, and had admirers such as the poet José Régio and the group around the magazine Presença. What he lacked was a body of published books.' },
      { myth: 'The heteronyms are simply pseudonyms.', reality: 'A pseudonym is a different name for the same writer. Pessoa gave each heteronym a different outlook, and they disagree with each other and with him. He also kept a few lesser “semi-heteronyms”, such as Bernardo Soares, who is closer to his own personality.' },
      { myth: 'Every popular “Pessoa quote” is genuine.', reality: 'Many lines circulated online under his name are mistranslated, invented or taken from the heteronyms. Check the source, and check which author wrote the passage.' },
    ],
    works: [
      { title: 'Mensagem (1934)', note: 'The only Portuguese-language book published in his lifetime, in three parts on the founding, the sea and the hope of national renewal.' },
      { title: 'The Book of Disquiet (first published 1982)', note: 'Assembled from the fragments in the trunk. English readers may use the editions of Richard Zenith (2001) or Margaret Jull Costa (2017), which make different choices.' },
      { title: 'Poems of Caeiro, Reis and Campos', note: 'Includes Caeiro’s sequence The Keeper of Sheep and Campos’s “Tabacaria”, and shows the heteronyms at their most distinctive.' },
      { title: 'Orpheu (1915)', note: 'The two issues of the modernist magazine; a third, prepared in 1915, was not published until 1984.' },
      { title: 'The trunk archive', note: 'About 25,000 papers, now held by the National Library of Portugal, are the source for most of what has been published since his death.' },
    ],
    legacy: [
      'After his death editors spent decades sorting and transcribing the papers, and each new edition has changed the picture of what he wrote. The result is a body of work that is still being discovered. Pessoa is now seen with Camões as one of the two central figures of Portuguese literature, and he is read across the world in dozens of languages.',
      'His idea of a self made of many voices has appealed to later writers, translators and philosophers of identity. Visitors to the Casa Fernando Pessoa and to his Lisbon cafés keep him in view, as do novelists such as António Tabucchi, who translated him into Italian, and José Saramago. Saramago even gave him a ghostly role in a novel, The Year of the Death of Ricardo Reis.',
    ],
  },
  {
    slug: 'b-r-ambedkar',
    order: 1891,
    dates: '1891 – 1956',
    place: 'Bombay and New Delhi, India',
    era: '20th Century',
    tradition: 'Anti-caste and constitutional thought',
    tagline: 'Born an “untouchable”, he became a scholar, a lawyer and the chief architect of India’s Constitution, and spent his life arguing that caste must be destroyed.',
    who: [
      'Bhimrao Ramji Ambedkar was born on 14 April 1891 in Mhow, an army town in central India. His family belonged to the Mahar community, which Hindu society treated as “untouchable”. His father served in the British Indian Army and valued education. At school young Bhimrao was made to sit apart and was sometimes denied water. By the usual account, he took the surname Ambedkar from a teacher who liked him. With help from the ruler of Baroda, Sayajirao Gaekwad III, he was able to continue his studies.',
      'He earned a degree at Elphinstone College in Bombay in 1912, then studied at Columbia University in New York, where he took a master’s degree in 1915 and was formally awarded a doctorate in economics in 1927. In London he completed a science degree and then a doctorate at the London School of Economics, and he qualified as a barrister at Gray’s Inn. He taught in Bombay, and his 1923 book The Problem of the Rupee dealt with Indian currency. Despite his qualifications he met discrimination at work and in finding lodgings.',
      'From the 1920s he became a political leader. He launched the newspaper Mooknayak in 1920, led the Mahad satyagraha in 1927 to assert the right of Dalits to use a public water tank, and attended the Round Table Conferences in London. After independence he served as India’s first law minister and chaired the committee that drafted the Constitution. He resigned from the government in 1951 after the Hindu Code Bill, which sought to reform Hindu family law, stalled. On 14 October 1956 he became a Buddhist in Nagpur, and he died in Delhi on 6 December 1956.',
    ],
    context: [
      'Caste, a graded hierarchy of birth, shaped almost every part of life in India, and Dalits (people outside the four-fold varna order, once called untouchables) faced exclusion from temples, wells and schools. Reformers such as Jyotirao Phule had attacked caste in the nineteenth century, and Ambedkar built on their example. At the same time the nationalist movement led by the Indian National Congress was pressing for self-rule, and the argument about who would speak for India’s Dalits became part of it.',
      'Britain was slowly widening Indian representation through a series of reforms, and communities competed to secure a political voice. In this contest Ambedkar argued that political freedom without social equality would be empty. India became independent and was partitioned in 1947, and the Constituent Assembly then had to write a charter for a deeply unequal society.',
    ],
    ideas: [
      { title: 'The annihilation of caste', text: 'In Annihilation of Caste (1936), written as a speech for a reform society in Lahore whose organisers withdrew the invitation after seeing it, Ambedkar argued that caste is not just a division of labour but a division of labourers, ranked in a hierarchy. He held that it could not be reformed from within without challenging the religious texts that justified it. His remedy included inter-caste marriage and a break with the authority of the shastras.' },
      { title: 'Political safeguards for the excluded', text: 'Ambedkar held that Dalits could not rely on the goodwill of upper-caste reformers and needed their own political representation. At the Round Table Conferences he pressed for separate electorates. The resulting 1932 Communal Award granted them, and Gandhi began a fast unto death in prison to oppose it. Ambedkar then negotiated the Poona Pact with Gandhi’s allies. It replaced separate electorates with reserved seats chosen in joint elections, and raised the number of reserved provincial seats from 71 to 148.' },
      { title: 'Gandhi and Ambedkar: two views', text: 'Gandhi feared separate electorates would permanently divide Hindu society, and he argued that untouchability should be ended by a change of heart among caste Hindus. Ambedkar argued that moral appeals had not worked for centuries, that Gandhi’s term “Harijan” was patronising, and that real power was needed. He later said he had signed under duress and criticised the pact’s effect on Dalit political independence. Historians still weigh the two positions differently.' },
      { title: 'Constitutional democracy and social democracy', text: 'In his closing speech to the Constituent Assembly in November 1949, Ambedkar warned that India was entering a life of contradictions, with equality in politics but inequality in social and economic life. He argued that political democracy would not last without social democracy, and that fraternity was the principle that holds liberty and equality together. He also credited others, including the constitutional adviser B. N. Rau and the chief draftsman S. N. Mukherjee, for their work on the text.' },
      { title: 'A rational religion', text: 'After announcing in 1935 that he had been born a Hindu but would not die one, Ambedkar spent twenty years studying other faiths. He chose Buddhism, which he read as a religion of reason, equality and compassion rather than of ritual or caste. His book The Buddha and His Dhamma gives his own interpretation, which some traditional Buddhists dispute. In his conversion ceremony he and several hundred thousand followers took vows rejecting caste-based Hindu practices.' },
    ],
    principles: [
      'Educate, agitate, organise. This is his well-known slogan.',
      'Political rights are hollow without social equality.',
      'Dignity cannot be given as charity. It has to be claimed and secured by law.',
      'Question any custom that rests on birth, however old.',
      'Test every belief against reason and compassion.',
    ],
    practice: [
      'Look at whom your group, school or workplace quietly excludes, and what unwritten rule produces that.',
      'Read a primary text, such as Annihilation of Caste or the 1949 Constituent Assembly speech, instead of only summaries.',
      'Support institutions that protect equal access, such as schools, scholarships and legal aid.',
    ],
    facts: [
      'On 25 December 1927 at Mahad he led a public burning of the Manusmriti, an ancient legal text that he saw as upholding caste.',
      'The Constitution of India was adopted on 26 November 1949 and came into force on 26 January 1950.',
      'He served as labour member of the Viceroy’s Executive Council from 1942 to 1946, before independence.',
      'He founded the Independent Labour Party in 1936 and later the Scheduled Castes Federation.',
      'He was posthumously awarded the Bharat Ratna, India’s highest civilian honour, in 1990.',
      'His birthday, 14 April, is a public holiday in India.',
    ],
    myths: [
      { myth: 'Ambedkar single-handedly wrote the Constitution.', reality: 'He chaired the seven-member Drafting Committee and defended the draft in the Assembly, but the document was the work of many hands, including B. N. Rau’s preliminary draft and S. N. Mukherjee’s drafting. Ambedkar himself said so.' },
      { myth: 'Gandhi simply opposed Dalit rights.', reality: 'Gandhi campaigned against untouchability and founded an organisation for the cause in 1932. His dispute with Ambedkar was about separate electorates and about method, and the two disagreed sharply on how change should come.' },
      { myth: 'His conversion was a sudden political move.', reality: 'He announced in 1935 that he would leave Hinduism, and he spent two decades examining other religions before choosing Buddhism in 1956, only weeks before his death.' },
    ],
    works: [
      { title: 'Annihilation of Caste (1936)', note: 'The undelivered address that he published himself. His most widely read single work.' },
      { title: 'Castes in India (1916)', note: 'An early paper presented at Columbia University that sets out his analysis of how caste works.' },
      { title: 'The Problem of the Rupee (1923)', note: 'His work in economics, on currency and monetary policy.' },
      { title: 'Constituent Assembly speeches (1948–1949)', note: 'Including his final speech of 25 November 1949. Collected in the multi-volume Dr Babasaheb Ambedkar: Writings and Speeches, published by the Government of Maharashtra.' },
      { title: 'The Buddha and His Dhamma (1957)', note: 'Finished shortly before his death and published after it, giving his own account of the Buddha’s teaching.' },
    ],
    legacy: [
      'The Constitution he helped to shape guarantees equality, bans untouchability and provides reserved places in legislatures, education and public employment for Scheduled Castes. Millions of Indians still honour 14 April, and statues of him stand in towns across the country. Dalit movements, parties and writers have taken inspiration from his example.',
      'His legacy is also argued over. Admirers see a founder of modern India, and critics question particular policies or his reading of Buddhism. The mass conversion he began has continued, and many Indian Buddhists today follow what is called the Navayana path he proposed. Around the world his work is now studied in law, economics and the history of social movements.',
    ],
  },
  {
    slug: 'antonio-gramsci',
    order: 1891,
    dates: '1891 – 1937',
    place: 'Turin and Rome, Italy (born in Sardinia)',
    era: '20th Century',
    tradition: 'Western Marxism',
    tagline: 'A Sardinian revolutionary who wrote, from a Fascist prison, how power works through consent as well as force.',
    who: [
      'Antonio Gramsci was born on 22 January 1891 in Ales, a town in Sardinia. His father, a minor official, was imprisoned on corruption charges in 1898 and the family fell into poverty. As a child Gramsci suffered a spinal deformity, probably from Pott’s disease, which left him small and frail for life. Despite this, he won a scholarship to the University of Turin in 1911 to study literature and languages, but he left without a degree as politics took over his life.',
      'In industrial Turin he joined the Socialist Party in 1913 and became a journalist. In 1919 he co-founded the weekly L’Ordine Nuovo, which backed the factory councils of the workers’ occupations of 1919–20. In 1921 he was among the founders of the Communist Party of Italy. He spent 1922–23 in Moscow, where he met Julia Schucht, whom he married. Elected to parliament in 1924, he became the party’s leading figure. He had two sons.',
      'Mussolini’s regime arrested him on 8 November 1926, despite his parliamentary immunity. At his trial in 1928 he was sentenced to more than twenty years. The prosecutor is reported to have said that they must stop “this brain” from working for twenty years. In prison his health collapsed, but from 1929 he filled some thirty notebooks with notes on history, politics and culture. Freed in 1934 to clinics because of illness, he died in Rome on 27 April 1937, aged 46, days after the formal end of his sentence.',
    ],
    context: [
      'Italy after the First World War was shaken by strikes, unemployment and the example of the Russian Revolution. The “two red years” of 1919–20 ended in defeat for the left, and Mussolini’s Fascists took power in 1922. Gramsci’s question, unlike many Marxists’, was why revolution had succeeded in Russia but failed in the more developed West, and why so many workers and peasants supported Fascism or the Church.',
      'He also came from a deeply divided country. Southern Italy, including Sardinia, was poorer than the industrial north, and Gramsci wrote early on about the “Southern Question”, the need for an alliance between northern workers and southern peasants. Prison censorship forced him to write in careful, sometimes coded language, which is one reason the notebooks are still debated.',
    ],
    ideas: [
      { title: 'Hegemony', text: 'Gramsci argued that a ruling class holds power not by force alone but by winning consent. Schools, churches, newspapers and everyday habits spread the ruling class’s way of seeing things until it appears to be common sense. A group that wants to change society must therefore lead culturally and morally before it takes power, and must win allies beyond its own class.' },
      { title: 'Civil society and the war of position', text: 'In Russia in 1917, he thought, the state was everything and civil society was weak, so a swift assault (a “war of manoeuvre”) could win. In the West, civil society is a sturdy network of institutions standing behind the state, so change requires a slow “war of position”, building up influence in culture and organisation first.' },
      { title: 'Organic intellectuals', text: 'Every social group, Gramsci said, produces its own thinkers who give it a sense of identity and purpose, such as managers for business or union organisers for workers. These “organic intellectuals” differ from traditional ones, such as clergy, who see themselves as above class. Gramsci held that “all men are intellectuals”, though not all have the function of intellectuals in society.' },
      { title: 'Common sense and good sense', text: 'Ordinary beliefs, Gramsci observed, are a patchwork of inherited prejudice, religion and practical wisdom. He called the wise part “good sense” and thought education should build on it rather than sneer at it. Critical thinking begins by understanding the ideas people already live by.' },
      { title: 'The subaltern', text: 'Gramsci used the word “subaltern” for groups, such as peasants and the poor, who are dominated and whose history is told, if at all, by their rulers. He urged historians to study their scattered, partial attempts at self-organisation. Later scholars of colonial and postcolonial history took up the term.' },
    ],
    principles: [
      'Pessimism of the intellect, optimism of the will. Gramsci took this phrase from Romain Rolland, and it became his motto.',
      'Power rests on consent as well as force, so ideas matter.',
      'Respect what ordinary people already know.',
      'Study, organise and educate before you try to rule.',
      'Tell the truth about defeats as well as victories.',
    ],
    practice: [
      'Ask which beliefs in your workplace or community are treated as “just common sense”, and who benefits from them.',
      'Build an alliance across differences before taking a stand, as Gramsci urged for workers and peasants.',
      'Read slowly and take notes by hand. Gramsci’s notebooks were written under harsh limits, and they show what steady study can achieve.',
    ],
    facts: [
      'His sentence was twenty years, four months and five days.',
      'His sister-in-law Tatiana Schucht looked after him in prison and helped to save the notebooks, and the economist Piero Sraffa opened an account at a Milan bookshop to supply him with books.',
      'The Prison Notebooks consist of about thirty-three notebooks, covering roughly 3,000 pages.',
      'Letters from Prison appeared in 1947 and won a major Italian literary prize, the Viareggio.',
      'In a 1926 letter on behalf of the Italian party he warned the Soviet leadership about the split in its own ranks. Togliatti, who received it, did not pass it on.',
      'His ashes lie in the Non-Catholic Cemetery in Rome.',
    ],
    myths: [
      { myth: 'The prosecutor’s line about stopping Gramsci’s brain is a documented quotation.', reality: 'The line is widely repeated and attributed to the prosecutor Michele Isgrò at the 1928 trial. It is reported rather than recorded verbatim, so its wording varies between sources.' },
      { myth: 'Gramsci thought culture alone decides politics and economics does not matter.', reality: 'He remained a Marxist and thought economic structures set limits. His point was that economics alone does not explain why people accept their situation.' },
      { myth: 'The Prison Notebooks are a finished book.', reality: 'They are notes, drafts and reworkings written under censorship, with no final arrangement. The versions we read were edited after his death.' },
    ],
    works: [
      { title: 'Prison Notebooks (1929–35)', note: 'First published in thematic volumes in 1948–51, then in a critical edition by Valentino Gerratana (1975). In English, see the editions by Joseph Buttigieg and the selection by Hoare and Nowell Smith (1971).' },
      { title: 'Letters from Prison', note: 'His letters to his wife, sister-in-law, friends and sons, where he discusses ideas and the reality of imprisonment.' },
      { title: 'Some Aspects of the Southern Question (1926)', note: 'An unfinished essay on the divide between north and south, written shortly before his arrest.' },
      { title: 'Articles from L’Ordine Nuovo and other journals', note: 'His political writing of 1916–1926, much of it on the Turin councils and the working class.' },
    ],
    legacy: [
      'After the war the Italian Communist Party, led by Palmiro Togliatti, published and promoted Gramsci as a national thinker, and his works were read around the world, sometimes selectively. In Britain, scholars such as Stuart Hall used him to understand culture, class and race, and the concept of hegemony became central to cultural studies. Postcolonial thinkers, among them Edward Said and the Subaltern Studies group, also drew on him.',
      'Today the idea of hegemony is used by scholars and activists across the political spectrum, and often loosely. Historians continue to ask how far his later notes were shaped by censorship, how he related to Leninism, and how his concepts should be read in their original context. Few thinkers have gained so much influence from a body of work written without any chance of publication.',
    ],
  },
  {
    slug: 'galaktion-tabidze',
    order: 1891,
    dates: '1891 – 1959',
    place: 'Tbilisi, Georgia (born in Chkvishi, Imereti)',
    era: '20th Century',
    tradition: 'Georgian symbolism',
    tagline: 'The poet many Georgians call the greatest of the twentieth century, whose music of words survived the Soviet years that destroyed his friends.',
    who: [
      'Galaktion Tabidze was born on 17 November 1891 (5 November in the Old Style calendar) in the village of Chkvishi, near Vani in Imereti, western Georgia. His father Vasil, a teacher from a family with a priestly tradition, died two months before he was born, and his mother Makrine brought him up. The National Archives of Georgia records a baptism on 3 January 1892, and some reference books give 1892 as his birth year. He studied at the seminaries in Kutaisi and Tbilisi, where his cousin Titsian Tabidze, also from Chkvishi, was a fellow student.',
      'His first poems appeared in print around 1908, and his book Poems came out in 1914. A second book, Artistic Flowers (Artistuli kvavilebi, 1919), made him the leading Georgian poet of his time and brought titles like “Genius Galaktion” and “king of poets”. He was close to the Georgian symbolists of the Blue Horns, whose journal printed some of his poems. In 1916 he married Olga Okujava. He spent 1917–18 in Moscow and Petrograd, and in 1918–19 he worked as a clerk in the government of the independent Georgian republic.',
      'After the Red Army took Georgia in 1921, he stayed and wrote under Soviet rule. He was named People’s Poet of Georgia in 1933, became a member of the Georgian Academy of Sciences in 1944, and received the Order of Lenin. Yet the Great Purge of 1937 took his cousin and friends, and his wife was arrested. Depression and illness marked his last years. He died in Tbilisi on 17 March 1959, after falling from a window of the hospital where he was being treated. It was ruled a suicide. Tens of thousands attended his funeral, and he was buried in the Mtatsminda Pantheon.',
    ],
    context: [
      'Georgia had been part of the Russian Empire for a century when Galaktion was born. Its cultural life was shaped by Georgian national revival, and Georgian writers of the 1910s opened the language to European influence, especially French Symbolism. The Blue Horns, founded in Kutaisi around 1915–16 (sources differ), set out to reject the realism and civic tone that had dominated Georgian literature. Its core figures included Grigol Robakidze, Titsian Tabidze, Paolo Iashvili and Valerian Gaprindashvili.',
      'Georgia’s short independence, from 1918 to 1921, ended with Soviet invasion. Both Stalin and Lavrenti Beria were Georgians, and the Soviet purge of 1937 hit Georgian writers hard. On 22 July 1937 Paolo Iashvili shot himself at the Writers’ Union in Tbilisi. Titsian Tabidze was arrested in October and, as was learned much later, shot on 16 December 1937. The novelist Mikheil Javakhishvili was also shot that year. Writers were pressed to praise the regime, and a poet like Galaktion faced demands to write in an approved manner.',
    ],
    ideas: [
      { title: 'Poetry as music', text: 'Readers of Galaktion often speak first of sound. His verse is built on rhythm, rhyme and sound, in the manner of the Symbolists, who wanted poetry to approach music. Some of his best-known poems, such as “Mtatsmindis mtvare” (“The Moon of Mtatsminda”), are loved for their sound as much as for their images.' },
      { title: 'Loneliness and the night', text: 'Many of his poems turn on isolation, longing and dark premonitions, as in “Me da ghame” (“I and the Night”). Titsian Tabidze is said to have nicknamed him the “Chevalier of the Order of Loneliness”. The solitary poet facing the night, the moon and the city became a lasting image in Georgian poetry.' },
      { title: 'Europe through a Georgian voice', text: 'Galaktion took the Symbolist movement, with its French roots, and made it Georgian. He wrote about Georgian places and moods, as in the title of “Mtatsmindis mtvare”, which names the hill above Tbilisi. His poem “Lurja tsekhenebi” (“Blue Horses”) is among the works linked to the Blue Horns circle.' },
      { title: 'The poet and the state', text: 'Under Soviet rule, writers were expected to serve the Party’s goals. Accounts of his career describe pressure to adapt, and the tension between his own voice and official demands is a theme in studies of him. How far he yielded, and how much he kept private, is still discussed by Georgian critics.' },
      { title: 'A language made new', text: 'Reference works describe his influence as profound on every later generation of Georgian poets. He widened what Georgian verse could do with rhythm and form, and many later poets took him as a starting point or a measure to answer.' },
    ],
    principles: [
      'Trust the music of language as much as its meaning.',
      'Let solitude feed your work without letting it consume you.',
      'Keep a private voice that cannot be ordered about.',
      'Remember your friends, especially those silenced.',
      'Take your own language and make it new.',
    ],
    practice: [
      'Read a favourite poem aloud, in its original language if you can, and notice how rhythm and sound carry feeling.',
      'Keep a notebook for drafts and fragments. Galaktion’s archive of notebooks shows how much work happens out of view.',
      'When you feel isolated, write it down in precise images instead of general statements.',
    ],
    facts: [
      'His birth year is given as both 1891 and 1892. The Georgian National Archives gives 5 November 1891 (Old Style), with baptism in January 1892.',
      'He and Titsian Tabidze were both born in Chkvishi, where the Galaktion and Titsian Tabidze House Museum stands, founded in 1966 and open to the public since 1983.',
      'He edited his own periodical, Galaktion Tabidze’s Journal, which ran for nine issues in 1922–23.',
      'Georgian accounts say he took part in the 1935 anti-fascist writers’ congress in Paris.',
      'In June 2000 the Georgian Orthodox Church, which traditionally regards suicide as a sin, formally absolved him of it, describing his death as a consequence of Soviet-era persecution.',
      'His literary papers, reportedly some 100,000 items, are preserved in Tbilisi’s literature museum.',
    ],
    myths: [
      { myth: 'Galaktion was a founder of the Blue Horns.', reality: 'Sources differ. The group’s core was Robakidze, Titsian Tabidze, Iashvili and others. Galaktion was closely associated with it and published in its journal, but some sources say he soon left it, and he is often described as a senior poet standing alongside it.' },
      { myth: 'He was shot in the 1937 purge like his cousin.', reality: 'He survived 1937. His cousin Titsian and several friends were killed, and he lived until 1959, dying in hospital in the way described above.' },
      { myth: 'His fate is well documented in every detail.', reality: 'Biographies vary on his birth year, on the date of his wife’s death, and on claims of torture or interrogation by the secret police. Careful accounts say what the documents show and leave the rest open.' },
    ],
    works: [
      { title: 'Poems (Leksebi, 1914)', note: 'His first book, which brought him attention and showed the influence of French Symbolism.' },
      { title: 'Artistic Flowers (Artistuli kvavilebi, 1919)', note: 'The collection that made him the leading Georgian poet.' },
      { title: '“Mtatsmindis mtvare” (“The Moon of Mtatsminda”)', note: 'One of his best-loved poems, set in the hills above Tbilisi.' },
      { title: '“Me da ghame” (“I and the Night”) and “Lurja tsekhenebi” (“Blue Horses”)', note: 'Two early poems often named among his masterpieces.' },
      { title: 'Archives and collected editions', note: 'The National Archives of Georgia holds documents and notebooks, and a Tbilisi literature museum holds his papers. The Georgian-language collected editions remain the main source.' },
    ],
    legacy: [
      'Georgians often call Galaktion their greatest twentieth-century poet. The museum in Chkvishi draws visitors, and his poems are still learned and recited in Georgia. He is buried in the Mtatsminda Pantheon in Tbilisi, among other writers and public figures, in the hills of the city whose moon he wrote about.',
      'The story of Georgian symbolism is also a story of loss. Titsian Tabidze, Paolo Iashvili and others died in 1937, and the survivors lived under pressure for decades. Galaktion’s poems have been translated into Russian, French, English and German, but remain best known in Georgian, where their sound and rhythm cannot be fully matched.',
    ],
  },
  {
    slug: 'walter-benjamin',
    order: 1892,
    dates: '1892 – 1940',
    place: 'Berlin, Paris and Portbou (Spain)',
    era: '20th Century',
    tradition: 'Critical theory',
    tagline: 'A Berlin essayist who wrote about the lost aura of art, the dream-worlds of cities and the angel of history, and who died on a border while fleeing the Nazis.',
    who: [
      'Walter Benjamin was born in Berlin on 15 July 1892 into a wealthy, assimilated Jewish family. He studied philosophy in Freiburg, Berlin, Munich and Bern, and took a doctorate in Bern in 1919 on German Romantic art criticism. From about 1915 he was a close friend of the scholar of Jewish mysticism, Gershom Scholem, and their long correspondence is one of the great sources for his life.',
      'His hope of an academic career ended in 1925, when the University of Frankfurt rejected his habilitation thesis, The Origin of German Tragic Drama (the book appeared in 1928). He lived as a freelance critic, translator and radio writer, translating Baudelaire and, with Franz Hessel, Proust. In 1924 he met the Latvian theatre director Asja Lacis, who pushed him toward Marxism, and in 1926–27 he visited Moscow. His books One-Way Street (1928) and Berlin Childhood around 1900 mix memory, observation and philosophy.',
      'After the Nazis took power in 1933 he left Germany and settled in Paris, supported by a small stipend from the Institute for Social Research, the Frankfurt School, then in exile in New York. He was stripped of his German citizenship in 1939 and briefly interned in France. When Paris fell in June 1940 he fled south, and in September he crossed the Pyrenees on foot with a small group. He died in Portbou, Spain, on the night of 26 September 1940 (some sources give the 27th).',
    ],
    context: [
      'Benjamin belonged to the generation formed by the First World War and the Weimar Republic, a time of artistic experiment, economic collapse and political violence. Photography, film and mass newspapers were changing how people saw and made things, and he was among the first major thinkers to take them seriously. He combined Jewish messianic ideas, Marxism and avant-garde art in a way that fitted no school.',
      'The rise of Nazism ended that world. In exile he had little money and fragile support, and the Hitler–Stalin pact of August 1939 shocked the left. Benjamin’s late writings, including the Theses on the Philosophy of History, were written under this pressure.',
    ],
    ideas: [
      { title: 'Aura', text: 'In “The Work of Art in the Age of Mechanical Reproduction” (written in several versions from 1935 to 1939), Benjamin described the aura of a work of art as its unique presence in time and space, tied to its place in a tradition. Photography and film, which can be copied endlessly, weaken that aura. He saw this as both a loss and a liberation, since art no longer depended on ritual or on the privilege of seeing the original.' },
      { title: 'Art, mass media and politics', text: 'The essay ends by contrasting the “aestheticising of politics”, which he linked with Fascism and its staging of war and mass spectacle, with the “politicising of art”, which he hoped for from film and the left. The argument still shapes debates on media and propaganda, though readers dispute whether his hopes for film were too optimistic.' },
      { title: 'The Arcades Project', text: 'From 1927 until his flight in 1940, Benjamin collected thousands of quotations and notes on the covered shopping arcades of nineteenth-century Paris, seeing them as the birth of consumer culture. He left the huge, unfinished manuscript with Georges Bataille at the Bibliothèque nationale. It was first published in German in 1982. He hoped the “dialectical image”, a flash in which past and present meet, could wake people from the dream of progress.' },
      { title: 'History and the angel', text: 'In the Theses on the Philosophy of History (1940), Benjamin rejected the idea of smooth, inevitable progress. He described Paul Klee’s drawing Angelus Novus, which he owned, as an angel of history with face turned to the past, seeing a pile of wreckage while a storm called progress drives it backward into the future. The theses ask us to remember the defeated and to take hold of the past in moments of danger.' },
      { title: 'Storytelling and experience', text: 'In “The Storyteller” (1936), Benjamin argued that the art of telling stories, with its passing on of experience from person to person, was fading in an age of newspapers and information. Information must be explained to be understood, while a story leaves room for the listener to think. The essay is also a meditation on craft, memory and what is lost when experience is replaced by data.' },
    ],
    principles: [
      'Look at the overlooked: small objects and neglected places can reveal a whole age.',
      'Distrust the idea that history is simply progress.',
      'Remember the defeated, not only the victors.',
      'Treat new media as a fact to understand, not only a threat.',
      'Write in fragments if the truth refuses to come in a system.',
    ],
    practice: [
      'Choose one everyday object or street and write down everything it tells you about the age that produced it.',
      'Before you accept a story of steady progress, ask who is missing from it.',
      'Read an essay slowly, with a pencil. Benjamin’s own method was the collection of quotations, so keep a commonplace book.',
    ],
    facts: [
      'He bought Klee’s Angelus Novus in 1921, and after his death the drawing passed to Scholem. It is now in the Israel Museum in Jerusalem.',
      'He was friends with Bertolt Brecht from the late 1920s and visited him in exile in Svendborg, Denmark, in the 1930s, where they played chess and argued.',
      'Theodor Adorno became his main contact at the Institute for Social Research, and the two exchanged sharp criticism of each other’s work. Adorno later helped to edit and publish his writings.',
      'Hannah Arendt received a copy of the Theses and edited the English collection Illuminations (1968), which introduced him to English readers.',
      'Scholem repeatedly urged him to move to Palestine, and Benjamin planned but never undertook the move.',
      'A memorial by the Israeli artist Dani Karavan, called Passages, overlooks the sea at Portbou, where Benjamin is buried.',
    ],
    myths: [
      { myth: 'Benjamin was a member of the Frankfurt School in the full sense.', reality: 'He was supported by the Institute for Social Research and published in its journal, but he was never a regular member, and his thinking differed from that of Adorno and Horkheimer.' },
      { myth: 'He argued that mechanical reproduction destroys art.', reality: 'He described both a loss and a gain. The aura fades, but new media open art to a mass audience and new uses.' },
      { myth: 'What happened at Portbou is fully known.', reality: 'Most evidence points to suicide with morphine tablets after he learned that Spanish officials would send the group back to France, but it rests mainly on accounts from fellow refugees, especially Henny Gurland. A suggestion that he was murdered by agents of Stalin has been made, but no convincing evidence has been found for it. The briefcase he carried, said by Lisa Fittko to hold an important manuscript, was never recovered.' },
    ],
    works: [
      { title: 'The Origin of German Tragic Drama (1928)', note: 'The rejected habilitation thesis, on Baroque mourning-plays, with its famous opening on method.' },
      { title: 'One-Way Street (1928)', note: 'Short pieces on city life, books, dreams and money in the modern world.' },
      { title: '“The Work of Art in the Age of Mechanical Reproduction” (1935–39)', note: 'His most influential essay. Several versions exist, so check which one you are reading.' },
      { title: 'The Arcades Project (published 1982)', note: 'Thousands of notes and quotations for an unfinished book on nineteenth-century Paris.' },
      { title: 'Theses on the Philosophy of History (1940)', note: 'His last major text, on history, memory and the angel. Often published as “On the Concept of History”.' },
    ],
    legacy: [
      'Almost unknown in his lifetime beyond a small circle, Benjamin became famous after the war through editions by Adorno and Scholem and, in English, through Arendt’s Illuminations. His aura essay is now standard reading in art history, film studies and media theory, and his ideas about cities, memory and consumer culture underlie much cultural criticism.',
      'He has been claimed by Marxists, by readers of Jewish thought, and by literary critics, and each group reads him differently. That openness is part of his appeal. His story at Portbou, a refugee at a closed border, has made him a symbol of exile and of the cost of persecution, and the memorial there draws visitors from around the world.',
    ],
  },
]
