import type { Profile } from './types'

export const MORE_05: Profile[] = [
  {
    slug: 'bonaventure',
    order: 1217,
    dates: 'c. 1217/21 – 1274',
    place: 'Bagnoregio (Italy), Paris and Lyon',
    era: 'Medieval',
    tradition: 'Franciscan mysticism',
    tagline: 'A Franciscan master and minister general who taught that the whole created world is a ladder of signs leading the mind to God.',
    who: [
      'Bonaventure was born Giovanni di Fidanza in Bagnoregio, a hill town north of Rome. Scholars still disagree about his birth year, and the usual choices are about 1217 and about 1221. He studied the arts at the University of Paris and joined the Franciscans, probably in the early 1240s. He then studied theology under the Franciscan master Alexander of Hales and his successors, and his own lectures on Peter Lombard’s Sentences became the base of his theological work.',
      'In 1253 he took the Franciscan chair of theology at Paris, but a quarrel between the secular masters and the new mendicant orders delayed his formal acceptance as a master until 1257. In the same year he was elected Minister General of the Franciscans, which ended his career as a full-time professor. For about sixteen years he governed an order of thousands of friars across Europe. He travelled constantly, wrote the order’s constitutions, preached, and in 1259 retreated to Mount La Verna, where Francis was said to have received the stigmata, and wrote his best-known work there.',
      'In 1273 Pope Gregory X made him Cardinal Bishop of Albano, and he took a leading part in preparing the Second Council of Lyon. He died in Lyon on 15 July 1274, in the middle of the council. His sudden death produced rumours of foul play that have never been proved. He was canonised in 1482 and declared a Doctor of the Church in 1588, and tradition calls him the “Seraphic Doctor”.',
    ],
    context: [
      'Bonaventure worked in the Paris of the thirteenth century, the leading centre of theology in Europe, at a moment when Aristotle’s works had arrived in Latin translation, along with Arabic commentaries on them. Some masters were thrilled by the new learning, others alarmed. The Franciscans and Dominicans, the new orders of preaching friars, entered the university just as this argument was heating up, and many established masters resented them. The dispute led to attacks on the friars by the secular master William of Saint-Amour in the 1250s, which Bonaventure and Thomas Aquinas both answered in writing.',
      'The Franciscan order itself was divided. Francis had lived in strict poverty, but a large international order needed buildings, books and administration. Some friars wanted a stricter reading of Francis’s ideals, and some of them were drawn to prophecies of a coming new age of the Spirit. Bonaventure held a middle course, defending the order’s poverty as an evangelical ideal while keeping it organised and obedient to the Church, and in the 1260s his Life of Francis was adopted as the order’s official biography.',
    ],
    ideas: [
      { title: 'The mind’s journey to God', text: 'In The Soul’s Journey into God (Itinerarium mentis in Deum), Bonaventure describes six stages by which the mind climbs, as if on the six wings of the seraph that Francis saw in his vision. We first look at the world outside and see God’s footprints, then at the world as a sign, then inward at the soul as God’s image, then at God as being and as goodness. The seventh stage is rest, when the intellect gives way to love. The book teaches that study and prayer are meant to work together.' },
      { title: 'Creation as a book of signs', text: 'Bonaventure held that every creature carries some trace of its maker, and that human beings, as images of God, carry more. He called this reading of the world exemplarism, since all things reflect the divine ideas in God’s mind. The world is therefore a kind of book: it can be read at the level of facts, but it asks to be read as a pointer to its source.' },
      { title: 'Illumination and the limits of Aristotle', text: 'Bonaventure was no enemy of reasoning, and he used Aristotle’s logic and concepts freely. But he held that the human mind needs God’s light to reach certain truth, an idea from Augustine called illumination. He also argued that reason can show that the world had a beginning, which is the opposite of Aristotle’s eternal world. Late in life he warned that a philosophy that claims to explain everything without Christ ends in error.' },
      { title: 'Christ at the centre', text: 'For Bonaventure, Christ is the centre of all knowledge: the one master of every discipline and the way back to God. His short work On the Reduction of the Arts to Theology shows how every craft and science, from mechanics to philosophy, can be read as a reflection of divine wisdom.' },
      { title: 'Wisdom needs love', text: 'Knowledge without love is incomplete, in his view. Theology exists to make us better, and not only better informed. This is why his writings blend precise argument with warm devotion, and why he treats the heart as a way of knowing that completes the mind.' },
    ],
    principles: [
      'Read the world as a book that points beyond itself.',
      'Let learning serve love, and not pride.',
      'Move from outside to inside: from things, to the self, to what is above the self.',
      'Combine study with prayer and quiet.',
      'Hold to high ideals but keep a community together.',
    ],
    practice: [
      'Take a short walk and treat what you see as a sign: ask what the order, beauty or fragility of something is pointing to.',
      'After you study a hard subject, spend a few minutes in silence, and notice how understanding shifts when you stop pushing for it.',
      'When you lead a group, ask whether you are protecting the ideal, the people, or both, and make sure that neither is lost.',
    ],
    facts: [
      'He and Thomas Aquinas were admitted together as masters of theology in Paris in 1257, after papal pressure had overcome the secular masters’ resistance. The two are often described as friends and colleagues, and they did disagree on important questions.',
      'Bonaventure and Aquinas died within a few months of each other in 1274: Aquinas in March, on his way to the Council of Lyon, and Bonaventure in July, during it.',
      'He wrote the Itinerarium at Mount La Verna in 1259, according to its own prologue, and it takes its structure from Francis’s vision of a six-winged seraph.',
      'His Legenda Major (c. 1260–63) became the official life of Francis, and in 1266 the order ordered earlier lives to be withdrawn, though scholars debate how thoroughly that was done.',
      'Unlike Aquinas, he thought that reason could prove that the world has a beginning in time.',
      'His sudden death at the council led to rumours of poisoning, which no evidence supports.',
    ],
    myths: [
      { myth: 'Bonaventure was an enemy of reason who rejected philosophy.', reality: 'He used Aristotle’s logic and concepts and wrote rigorous academic theology. What he opposed was the claim that philosophy alone can give a complete account of reality without faith. The Stanford Encyclopedia describes him as broadly Aristotelian in method but not in all of his conclusions.' },
      { myth: 'Bonaventure and Aquinas were rivals who denounced each other.', reality: 'They were colleagues who defended the mendicant orders together and respected one another. Their schools disagreed on questions such as the eternity of the world, the matter of angels and the role of illumination, but the disagreement was between two kinds of Christian Aristotelianism, not a personal feud.' },
      { myth: 'He was only a mystic who left administration to others.', reality: 'He spent about sixteen years running a large international order, writing its legislation and handling disputes over poverty, and then served as a cardinal at a church council.' },
    ],
    works: [
      { title: 'Itinerarium mentis in Deum (The Soul’s Journey into God)', note: 'Written in 1259 at La Verna: the best-known short guide to the ascent of the mind.' },
      { title: 'Breviloquium', note: 'A compact summary of the whole of theology, written for students.' },
      { title: 'Commentary on the Sentences', note: 'His Paris lectures, the main source for his scholastic thought.' },
      { title: 'Legenda Major (Life of Saint Francis)', note: 'The official biography of Francis, completed in the early 1260s.' },
      { title: 'Collationes in Hexaemeron', note: 'Lectures from 1273 on the six days of creation, in which he criticises the excesses of Aristotelian philosophy in Paris.' },
    ],
    legacy: [
      'Bonaventure shaped the Franciscan intellectual tradition for centuries. Duns Scotus, William of Ockham and later Franciscan theologians took up and often changed his positions. His writings were widely copied, his devotional works reached many readers in the later Middle Ages, and the Itinerarium remains a standard text of Christian mysticism.',
      'In the generation after his death, the Paris condemnations of 1277 targeted a range of Aristotelian positions, some of them close to Aquinas’s, and Franciscan theologians were often wary of the new philosophy. Modern scholars no longer see Bonaventure and Aquinas as opposed champions of faith and reason. Instead they see two different ways of fitting Greek and Arabic philosophy into Christian thought, each with a lasting influence.',
    ],
  },
  {
    slug: 'geoffrey-chaucer',
    order: 1343,
    dates: 'c. 1343 – 1400',
    place: 'London, England',
    era: 'Medieval',
    tradition: 'Medieval English literature',
    tagline: 'A court official who made the English of his own day into a language fit for great poetry, and filled it with the voices of ordinary people.',
    who: [
      'Geoffrey Chaucer was born in London around 1343, the son of a prosperous wine merchant. Records show him as a young attendant in a noble household in 1357, and in 1359–60 he served in the English army in France, was captured, and was ransomed with a contribution from the king. By 1367 he was a valet in the royal household. He married Philippa de Roet around 1366, and she later served in a great household. Their son Thomas had a long public career and became Speaker of the House of Commons.',
      'Chaucer was a civil servant and diplomat before he was a famous poet. He was sent on royal business to France, and to Italy in 1372–73 and 1378, where he came into contact with the work of Dante, Petrarch and Boccaccio. From 1374 to 1386 he was Controller of the Customs in the port of London. He sat in Parliament as a knight of the shire for Kent in 1386, and in 1389–91 he held the post of Clerk of the King’s Works. He wrote in whatever time his public duties left him.',
      'He began The Canterbury Tales in the late 1380s and left it unfinished at his death in 1400. He was buried in Westminster Abbey, where he lived in the precincts, and the tomb that visitors see today was built in the sixteenth century. Over time other writers were buried near him, and the area became known as Poets’ Corner.',
    ],
    context: [
      'Chaucer lived through the Black Death of 1348–49, the Hundred Years’ War, the Peasants’ Revolt of 1381 and the deposition of Richard II in 1399. These events shook the old order. The plague changed wages and labour, and the Peasants’ Revolt showed how angry many ordinary people were with the powers above them. Chaucer’s work often shows these tensions, with its mix of knights, merchants, clergy and labourers, though he rarely comments on them directly.',
      'The languages of literature in England were also in flux. Educated people used Latin for scholarship and the Church, and French had long been the language of the court. English was growing in status, and in 1362 a statute ordered that cases in the courts be pleaded in English. Writers such as William Langland, John Gower and the poet of Sir Gawain and the Green Knight were all writing in English in these years. Chaucer chose English for his major poems, and his choice, with his skill, gave the language a prestige that it had lacked.',
    ],
    ideas: [
      { title: 'English as a language of art', text: 'Chaucer wrote in the London English of his day, with its mix of Old English and French words. He took the metres and stories of French and Italian poetry and showed that English could do the same work. His choice was not the first of its kind, but its success mattered: later writers could treat English as a language for serious poetry. Estimates suggest that he is the earliest recorded user of many English words, though some may simply be the earliest ones that survive.' },
      { title: 'Many voices, and an ironic narrator', text: 'In The Canterbury Tales a group of pilgrims tell stories on the road to Canterbury, and each tale reveals the teller. Chaucer appears as a pilgrim himself, a modest and sometimes naive figure, which lets him report what others say without endorsing it. The result is a collection of competing views on love, money, marriage, religion and class, and the reader has to decide which to trust.' },
      { title: 'Fortune and free will', text: 'Chaucer translated Boethius’s Consolation of Philosophy into English prose as Boece, and its themes run through his poetry. How far are we ruled by fortune, which raises and casts down, and how far are we free? Troilus and Criseyde, set in the siege of Troy, follows a lover whose happiness depends on forces he cannot control, and he speaks in the poem about whether foreknowledge removes freedom. In the Knight’s Tale a ruler argues that a higher order stands behind change, and the Nun’s Priest’s Tale turns the same debate into comedy about a cockerel.' },
      { title: 'Experience against authority', text: 'The Wife of Bath opens her prologue by saying that her own experience of marriage is authority enough, against the learned books that men use to lecture women. Whether we take her side or not, the passage shows a poet testing inherited rules against lived life, and giving a woman’s voice a rare and complex hearing in medieval writing.' },
      { title: 'True nobility is a matter of conduct', text: 'In several poems, including a short one called “Gentilesse” and the tale told by the Wife of Bath, Chaucer argues that real nobility comes from virtue and not from birth. This echoes a theme in Dante and Boethius, and it fits with the social mobility of his own life, as a merchant’s son at court.' },
    ],
    principles: [
      'Listen to many voices before judging.',
      'Test what the books say against what you have seen.',
      'Remember that fortune can change, and do not rest your happiness on it alone.',
      'Judge people by conduct, not by birth or rank.',
      'Laugh at human folly, including your own.',
    ],
    practice: [
      'Before you decide who is right in a quarrel, write down each person’s version in their own words, as if telling their story.',
      'When you face a setback, ask which part was fortune and which part was choice, and put your energy into the second.',
      'Read a few lines of Chaucer aloud in the original spelling. The sound helps you notice how closely it connects to modern English.',
    ],
    facts: [
      'In 1374 Edward III granted him a daily allowance of wine, which was later converted into a money payment.',
      'He wrote a Treatise on the Astrolabe, around 1391, for his young son Lewis. It is among the earliest technical manuals in English.',
      'The Canterbury Tales is unfinished. The prologue plans several tales for each of about thirty pilgrims, but only twenty-four tales survive, and some of them are incomplete.',
      'William Caxton printed The Canterbury Tales in the 1470s, among the earliest books printed in England. More than eighty manuscript copies survive, including the famous Ellesmere manuscript.',
      'Many of his stories have Italian sources. The Knight’s Tale and Troilus and Criseyde both draw on works by Boccaccio, and Chaucer changes them freely.',
      'A legal document of 1380 records that a woman named Cecily Chaumpaigne released him from a charge of “raptus”. Scholars disagree about whether the word means abduction or rape, and the circumstances are unknown.',
    ],
    myths: [
      { myth: 'Chaucer was the first English writer, and wrote in Old English.', reality: 'English literature goes back centuries before him. He wrote in Middle English, which differs much from Old English, and his contemporaries Langland, Gower and the Gawain poet were writing in English too. “Father of English literature” is a later title.' },
      { myth: 'Chaucer once beat a friar on Fleet Street and was fined for it.', reality: 'The story appears in print only in the sixteenth century, and no record supports it. Biographers set it aside and rely on surviving documents.' },
      { myth: 'The Canterbury Tales is a simple collection of bawdy jokes.', reality: 'Some tales are crude and funny, but others are saints’ legends, sermons, tragedies and romances. The collection ends with the Parson’s serious prose treatise on penance and a retraction in which Chaucer asks forgiveness for some of his works. How seriously to take that retraction is debated.' },
    ],
    works: [
      { title: 'The Canterbury Tales', note: 'His last and greatest work, begun in the late 1380s and left unfinished. The main manuscripts are Hengwrt and Ellesmere.' },
      { title: 'Troilus and Criseyde', note: 'A long poem from the 1380s about love and fortune during the siege of Troy, adapted from Boccaccio.' },
      { title: 'Boece', note: 'His English prose translation of Boethius’s Consolation of Philosophy, which influenced his thinking about fortune.' },
      { title: 'The Book of the Duchess', note: 'An early dream poem, usually dated to the late 1360s, widely read as an elegy for Blanche of Lancaster.' },
      { title: 'A Treatise on the Astrolabe', note: 'A practical guide to using an astronomical instrument, written for his son.' },
    ],
    legacy: [
      'Within a generation of his death, poets such as Thomas Hoccleve and John Lydgate were praising Chaucer as their master. In Scotland the poets known as the Scottish Chaucerians learned from him, and in the sixteenth century Spenser and later Shakespeare read him with admiration. Printing kept The Canterbury Tales in circulation, so Chaucer was never out of view.',
      'Today he is read in universities and schools, and his tales have been adapted for stage, film and television. His characters, from the Wife of Bath to the Pardoner, are still recognised as individuals, and his gift for letting people reveal themselves in their own words is a reason that readers return to him after six centuries.',
    ],
  },
  {
    slug: 'thomas-a-kempis',
    order: 1380,
    dates: 'c. 1380 – 1471',
    place: 'Kempen (Germany), Deventer and Zwolle (Netherlands)',
    era: 'Medieval',
    tradition: 'Devotio Moderna',
    tagline: 'A quiet canon and copyist whose small book on following Christ became one of the most widely read works of Christian devotion.',
    who: [
      'Thomas was born around 1380 in Kempen, near the Rhine, in what is now Germany, and the name “à Kempis” means “of Kempen”. His family name is given as Hemerken, or Hammerken. At about twelve he was sent to the school in Deventer in the Netherlands, where he stayed from 1392 to 1399. There he met the Brethren of the Common Life, a community of laypeople and priests who followed the “modern devotion”, a movement begun by Gerard Groote, who had died in 1384.',
      'In 1406 he entered the monastery of Mount St Agnes near Zwolle, where his older brother John was already a member. It belonged to the Windesheim Congregation, a union of Augustinian canons regular that grew out of Groote’s movement. He was ordained a priest in 1413 and became sub-prior in 1429. He spent the rest of his life in the Mount St Agnes community, more than sixty years in all.',
      'Thomas lived the quiet life of a community that copied books, taught novices, and prayed together. He copied the Bible several times, wrote sermons, letters and lives of leaders of his movement, and compiled a chronicle of his monastery. He died in July 1471, a very old man for the time. He was never formally canonised, and he is remembered as a devout writer more than as a public figure.',
    ],
    context: [
      'Thomas lived in a troubled church. From 1378 to 1417 the Western Church was split by the Great Schism, with rival popes in Rome and Avignon, and for part of the time a third claimant too. Many ordinary believers were confused by institutions that seemed to fight for power, and some looked for a religion of the inner life. The Devotio Moderna offered that: simple, practical, with attention to the daily habits of prayer, reading and work.',
      'The movement grew in the towns of the Low Countries, where trade had created a literate middle class. The Brethren and Sisters of the Common Life lived in shared houses, without formal vows, supporting themselves by copying books and teaching. They produced and spread simple devotional writing in Latin and in the vernacular. The canons of Windesheim, which Thomas joined, gave the movement an order of its own. The new printing press was soon to carry such works much further than the copyists could.',
    ],
    ideas: [
      { title: 'The inward life', text: 'The Imitation of Christ begins with the words of Jesus, “he who follows me does not walk in darkness”, and asks what following means in practice. Its answer is mostly about inner attitudes: humility, patience, self-knowledge and trust. It treats outer religion, such as ceremonies and learned discussion, as valuable only if it changes the heart.' },
      { title: 'Humility over learning for show', text: 'Thomas warns against knowledge pursued for status. In a well-known passage he says he would rather feel sorrow for his faults than be able to define it. The point is not that learning is bad, since he spent his life among books, but that learning which makes someone proud has missed its purpose.' },
      { title: 'Bearing with others', text: 'One chapter of the first book is about putting up with the faults of others. Thomas observes that we cannot make even ourselves what we would like to be, so we should be patient with other people. This realistic gentleness is a main reason why readers outside any one denomination have valued the book.' },
      { title: 'The world passes quickly', text: 'The Imitation repeatedly reminds readers that honours, wealth and reputation fade. Its line “how quickly the glory of the world passes away” has often been quoted. The remedy it offers is not despair but a change of attention, towards what lasts.' },
      { title: 'Silence, solitude and the sacrament', text: 'Thomas praises the quiet of a cell and the discipline of silence, and he treats solitude as a way of hearing one’s own heart. The fourth book, on the Eucharist, places Communion at the centre of the devout life. The third book is written as a conversation between Christ and the disciple, which gives it an intimate tone.' },
    ],
    principles: [
      'Seek inner change before outer display.',
      'Hold your knowledge humbly.',
      'Be patient with other people’s faults.',
      'Do not set your heart on honours that fade.',
      'Make room every day for silence.',
    ],
    practice: [
      'Set aside ten minutes a day with no screen, and use it for silence or for reading a few lines slowly.',
      'When you feel the urge to correct someone, ask first what faults you yourself have not yet overcome.',
      'Choose one small, regular task, such as copying out a passage by hand, and do it patiently as a discipline of attention.',
    ],
    facts: [
      'He is reported to have copied the whole Bible by hand, and some accounts say as many as four times.',
      'The Imitation of Christ was written in Latin, as four short books that first circulated separately, apparently between about 1418 and 1427.',
      'The oldest dated copy, from 1441, carries a note saying it was written by Thomas’s own hand. Some argue it only proves he was the copyist, but it is a key piece of evidence.',
      'By some counts the Imitation has appeared in thousands of editions and in dozens of languages. It is often described as one of the most widely read Christian books apart from the Bible.',
      'John Wesley, founder of Methodism, described reading it in 1725 as a turning point in his religious life, and Ignatius of Loyola is reported to have valued it.',
      'He wrote other works too, including a collection of sermons to novices, a chronicle of Mount St Agnes and a life of Gerard Groote.',
    ],
    myths: [
      { myth: 'Nobody knows who wrote the Imitation of Christ.', reality: 'The book was copied anonymously and, in the fifteenth to seventeenth centuries, was attributed to others, including the chancellor Jean Gerson and a supposed abbot named Giovanni Gersen. Most modern scholars now accept Thomas as the author, based on manuscripts and style, though some debate lingers about how much he adapted earlier material.' },
      { myth: 'Thomas was a gloomy hermit who despised learning.', reality: 'He was a scribe and teacher who lived among books and wrote a chronicle and biographies. The Imitation criticises pride in learning, not learning itself, and its tone is often warm and consoling.' },
      { myth: 'He is Saint Thomas à Kempis.', reality: 'He was never formally canonised. He is sometimes called a saint informally, and some traditions remember him in their calendars, but the Catholic Church has not declared him a saint.' },
    ],
    works: [
      { title: 'De imitatione Christi (The Imitation of Christ)', note: 'His best-known work, in four books: counsels for the spiritual life, counsels for the inner life, inward consolation, and the Sacrament.' },
      { title: 'Sermons to novices and other devotional writings', note: 'Practical teaching for the young canons he trained at Mount St Agnes.' },
      { title: 'Chronicle of Mount St Agnes', note: 'A history of his own community, and a window into life in a monastery of the Devotio Moderna.' },
      { title: 'Lives of Gerard Groote, Florens Radewyns and others', note: 'Biographies of the founders of his movement, which are also a main source for its history.' },
    ],
    legacy: [
      'The Imitation of Christ spread quickly in manuscript and, from the later fifteenth century, in print. It was translated into many languages, and Catholics, Protestants and Orthodox readers have all used it. Its inward emphasis fitted the needs of the late medieval and Reformation periods, and the book was widely used for private reading in both traditions.',
      'The Devotio Moderna, of which Thomas is the best-known writer, helped to prepare the ground for later reform movements, and its schools taught young people who became leading scholars of the Renaissance, including, as many accounts say, Erasmus, who was educated by the Brethren as a boy. Whatever its exact influence, Thomas’s book has lasted because it offers a plain, patient guide to inner life that does not depend on any special learning.',
    ],
  },
  {
    slug: 'nicholas-of-cusa',
    order: 1401,
    dates: '1401 – 1464',
    place: 'Kues on the Moselle (Germany), Basel, Brixen and Rome',
    era: 'Early Modern',
    tradition: 'Renaissance Neoplatonism',
    tagline: 'A cardinal who argued that the greatest knowledge is to know how much we do not know, and who imagined a universe with no centre.',
    who: [
      'Nicholas was born in 1401 in Kues, a village on the Moselle, the son of a boatman or ship-owner, and he is known as Cusanus after his birthplace. He studied at Heidelberg from 1416, then at Padua, where he took a doctorate in canon law in 1423. At Padua he began friendships with humanist scholars, among them the mathematician and physician Paolo Toscanelli. He became a priest and worked as a legal adviser to bishops and the church.',
      'At the Council of Basel, which met from 1431, he first sided with those who thought that a general council had authority over the pope, and in 1433 he wrote On Catholic Concord, an argument that authority in church and empire rests on harmony and the consent of the governed. In the same work he showed that the Donation of Constantine, a document that claimed the emperor had given the pope rule in the West, was a forgery. As the council split, he turned to the papal side, and in 1437–38 he travelled to Constantinople as part of a delegation to invite the Greek Church to a council on reunion. He said that on the voyage home the idea of “learned ignorance” came to him as a gift.',
      'He became a cardinal in 1448 and Bishop of Brixen in 1450, and he served as papal legate to Germany, travelling to reform monasteries. In Brixen he clashed with Duke Sigismund of Tyrol over church rights and lands. Sigismund held him prisoner in 1460, and he left for Rome. He died in Todi in 1464, on a journey to join Pope Pius II’s planned crusade. His body lies in Rome, and his heart is in the chapel of the hospital he founded in Kues.',
    ],
    context: [
      'Nicholas worked at a hinge in European history. The Great Schism had been ended at the Council of Constance, but the Church was still arguing about where authority lay. The Ottoman Turks were advancing, and Constantinople fell in 1453. The Renaissance was recovering Greek texts and Platonic philosophy, and Nicholas, who collected manuscripts, was a part of this. Scholars often place him between medieval and Renaissance thought, and the label “Early Modern” has to be read with that in mind.',
      'His intellectual sources were wide: the Neoplatonism of Proclus and Pseudo-Dionysius, the German mysticism of Meister Eckhart, the work of Ramon Llull, and the Christian tradition of speaking about God through negations, since God exceeds all our words. He combined these with mathematics and with practical experience of church politics, in a style that mixes dialogues and treatises and often uses images drawn from geometry.',
    ],
    ideas: [
      { title: 'Learned ignorance', text: 'In On Learned Ignorance (De docta ignorantia, 1440) Nicholas argues that we know anything only by comparing it with something else, and since God is infinite, no comparison is possible. Our best knowledge of God is therefore to know that we cannot grasp God. This is not a refusal to think. It is a trained humility that knows the limits of the human mind, and that keeps learning, since our knowledge can always come nearer without ever finishing.' },
      { title: 'The coincidence of opposites', text: 'In the infinite, he held, the distinctions we draw in the finite world, such as largest and smallest, or straight and curved, meet and become one. He used geometry to show this: a polygon inscribed in a circle comes closer to the circle with every extra side but never becomes it, and an infinite straight line would be a circle. God, he wrote, is beyond contradictions that govern our thinking about creatures.' },
      { title: 'A universe without a centre', text: 'Because the universe cannot have a fixed centre or boundary that we could find, Nicholas wrote that it has its centre everywhere and its edge nowhere. The Earth, he suggested, is a star like others, is not at rest, and may not be the only inhabited place, though he presented this as philosophical reasoning and not as astronomy. These were bold thoughts for the mid-fifteenth century.' },
      { title: 'One faith in many rites', text: 'After the fall of Constantinople he wrote On the Peace of Faith (De pace fidei, 1453), a dialogue in which representatives of many nations and religions meet in a vision of heaven and agree that there is one religion behind a variety of rites. It is an early plea for religious dialogue, though Nicholas was a committed Christian whose own proposals assume Christian truth. In 1460–61 he also wrote a critical study of the Qur’an, the Cribratio Alkorani, which aims to find points of contact but is critical of Islam.' },
      { title: 'Mathematics and the human mind', text: 'Nicholas treated mathematics as the best symbolic language for thinking about the infinite, and he thought the human mind is creative: it makes its own concepts and measures, as God makes real things. He experimented with ways of measuring, such as weighing and counting pulse beats, and he tried to square the circle, though his solutions were not accepted by mathematicians.' },
    ],
    principles: [
      'Know the limits of what you know.',
      'Look for the unity beyond apparent contradictions.',
      'Treat other people’s beliefs with an effort to understand.',
      'Base authority on consent and harmony.',
      'Use images and numbers to think about what cannot be seen.',
    ],
    practice: [
      'When you face a hard question, write down what you cannot know about it, and let that guide your next step.',
      'In a disagreement, look for the shared concern that makes both views seem reasonable to the people who hold them.',
      'Draw a polygon in a circle, add sides, and notice how an endless approach can still teach something.',
    ],
    facts: [
      'His family name was Krebs, or Cryfftz, and Cusanus comes from Kues, the Latinised form of the village.',
      'In 1433 he argued that the Donation of Constantine was a forgery, a few years before Lorenzo Valla made the better-known case.',
      'At Basel he proposed a calendar reform in 1436, and a method of voting for the Holy Roman Emperor that later writers compared to the Borda count.',
      'He suggested counting a patient’s pulse as a medical measure.',
      'The library and hospital he founded in Kues still exist, and the hospital still cares for elderly residents.',
      'A crater on the Moon is named after him.',
    ],
    myths: [
      { myth: 'Nicholas of Cusa anticipated Copernicus’s sun-centred system.', reality: 'He argued that the Earth moves and is not the centre of the universe, but he did not propose that the Sun is at the centre. His arguments were philosophical, based on the infinity of God’s creation, and not on observation or calculation.' },
      { myth: 'He solved the problem of squaring the circle.', reality: 'He believed for a time that he had, and published several attempts. Mathematicians such as Regiomontanus pointed out that the results were not correct. His geometry is valued for its philosophical use, not for these claims.' },
      { myth: 'Nicholas was a pantheist who identified God with the world.', reality: 'Critics such as Johannes Wenck made this charge in 1449, and Nicholas replied in a written defence. He held that God is infinite and beyond the world, though the world reflects God, so he sought to avoid the charge.' },
    ],
    works: [
      { title: 'De docta ignorantia (On Learned Ignorance)', note: 'His first major philosophical work, completed in 1440, and the source of most of his best-known ideas.' },
      { title: 'De concordantia catholica (On Catholic Concord)', note: 'A work on church and empire from 1433, including his argument about the Donation of Constantine.' },
      { title: 'De pace fidei (On the Peace of Faith)', note: 'A dialogue of 1453 about unity among religions, written after the fall of Constantinople.' },
      { title: 'De visione Dei (On the Vision of God)', note: 'A meditative work of 1453, written for monks, which uses the image of a portrait whose gaze seems to follow each viewer.' },
      { title: 'Idiota dialogues and De ludo globi', note: 'Dialogues on wisdom, mind and measurement, featuring an unlearned layman, and a dialogue on a game with a curving ball.' },
    ],
    legacy: [
      'Nicholas was little known in the generations after his death, but some readers took up his ideas. Giordano Bruno acknowledged him in developing his ideas about an infinite universe, and Leibniz knew his work. Nineteenth-century and twentieth-century scholars, among them Ernst Cassirer, brought him back into view, and a critical edition of his works has been published.',
      'Today he is studied as a thinker who combined mysticism, mathematics and church politics. His ideas about the limits of knowledge, about unity beyond opposites and about dialogue among religions still speak to readers, and the Cusanus societies and institutes in Germany continue to study and edit his work.',
    ],
  },
  {
    slug: 'jami',
    order: 1414,
    dates: '1414 – 1492',
    place: 'Herat, Khurasan (now western Afghanistan)',
    era: 'Medieval',
    tradition: 'Persian Sufism',
    tagline: 'A Sufi master, scholar and poet of Herat whose seven long poems made him one of the last great voices of classical Persian literature.',
    who: [
      'Nur al-Din Abd al-Rahman Jami was born in November 1414 at Kharjird, in the district of Jam in Khurasan. He took the pen name Jami, and he explained it, according to tradition, in two ways: as a reference to his birthplace and, in a play on words, to the cup (jam) of mystical knowledge, with an allusion to the Sufi saint Ahmad-i Jam. His father was a scholar, and Jami studied in Herat and, according to biographers, in Samarkand, mastering Arabic grammar, law, theology, logic and the sciences.',
      'He joined the Naqshbandi Sufi order, taking guidance from Sa’d al-Din Kashgari, and he became a Sufi teacher in his own right around 1453. The Naqshbandis stressed silent remembrance of God and a life lived among people, and their leaders were influential at Timurid courts. Jami was also deeply read in the Sufi thought of Ibn Arabi, and he wrote commentaries that explained it in Persian. He made the pilgrimage to Mecca in 1472–73, travelling via Iraq and Syria.',
      'For most of his life he lived in Herat, under the rule of Sultan Husayn Bayqara, the last great Timurid ruler. The ruler’s minister Ali-Shir Navai became his devoted friend and disciple. Jami was offered posts and invitations from distant rulers, but he declined to leave. He died in Herat on 9 November 1492, and his funeral was reportedly attended by great crowds and led by the city’s ruling prince.',
    ],
    context: [
      'Herat was in this period one of the great cultural centres of the Islamic world. Under the Timurids, descendants of Tamerlane, the city supported scholars, historians, calligraphers and painters, including the miniaturist Bihzad. Persian was the language of high culture and administration, while Turkic Chagatai was the language of the court’s military elite. Navai, who wrote in Chagatai and argued for its literary value, worked closely with Jami, who wrote in Persian.',
      'Jami also stood at the end of a long tradition: Sana’i, Attar, Rumi, Nizami, Sa’di and Hafez had already made Persian poetry one of the world’s great literatures, and Jami drew on all of them. Within about fifteen years of his death Timurid rule in Khurasan ended, with Herat falling to the Uzbeks in 1507, and from 1501 the Safavids were building a new political and religious order in Iran. This is one reason that Jami is often seen as the close of an era.',
    ],
    ideas: [
      { title: 'Earthly love as a bridge', text: 'In his poem Yusuf and Zulaykha, based on the Qur’anic story of Joseph, Jami follows Zulaykha’s overpowering love for Yusuf, which is gradually transformed into love of God. He drew on the Sufi saying that the earthly is a bridge to the real: human love, with all its pain, can train the heart to turn towards what is greater. Readers have praised the poem for its psychological detail.' },
      { title: 'Unity of being explained for readers', text: 'Jami was a leading interpreter of Ibn Arabi’s idea, often called the unity of being, that all things exist through the single reality of God. His prose work Lawa’ih (Flashes) explains this with the language of the lover, the beloved and love, treated as aspects of one reality. He made the subject accessible by using the images of Persian poetry.' },
      { title: 'A path lived in the world', text: 'The Naqshbandi path stressed inner devotion carried on in ordinary life, with work, family and public duties. Jami lived this out as a scholar, teacher and adviser in a city at the heart of court life. For him, spiritual life did not require leaving society, but it did require keeping a distance from its prizes.' },
      { title: 'Learning from the lives of others', text: 'His Nafahat al-uns (Breaths of Intimacy) is a collection of biographies of Sufi men and, in a separate section, women, drawing on earlier works. It teaches through example, and it became a standard reference. Navai later prepared a Turkic version.' },
      { title: 'Poetry as instruction and delight', text: 'Jami held that poetry could teach ethics and give pleasure at once. His Baharistan (Abode of Spring, 1487), modelled on Sa’di’s Gulistan, mixes prose, verse and anecdotes for his son, and his long poems tell stories that carry moral and mystical meaning, from the tale of Salaman and Absal to the quest of Alexander for wisdom.' },
    ],
    principles: [
      'Let love for what is near teach you about what is highest.',
      'Live in the world without being owned by it.',
      'Learn from the lives of those who went before.',
      'Teach through beauty as well as argument.',
      'Keep your independence from the powerful, even when you accept their support.',
    ],
    practice: [
      'Read one story or poem slowly each week, and ask what it says about desire and what it should be for.',
      'Write down a short biography of someone you admire, focusing on the habits that shaped them.',
      'When you receive an offer that would pull you away from your work, ask what you would be giving up, as Jami did when he stayed in Herat.',
    ],
    facts: [
      '“Haft Awrang” means “Seven Thrones”, which is also the Persian name for the constellation of the Great Bear.',
      'The seven poems of the Haft Awrang include Silsilat al-dhahab (The Chain of Gold), Salaman and Absal, Yusuf and Zulaykha, Layla and Majnun and the Khiradnama-yi Iskandari (The Wisdom Book of Alexander), composed roughly between the late 1460s and mid-1480s.',
      'He wrote three divans (collections) of lyric poetry, as well as works on grammar, music, prosody, history and theology. His commentary on a grammar of Arabic was used as a school text across the Islamic world for generations.',
      'A magnificent illustrated copy of the Haft Awrang, made in Safavid Iran in the sixteenth century, is held in the Freer Gallery in Washington.',
      'The English poet Edward FitzGerald, known for his Rubaiyat of Omar Khayyam, also translated Jami’s Salaman and Absal, in 1856.',
      'Copies of his works travelled to Ottoman lands and to Mughal India, and the Mughal court produced its own versions of his stories.',
    ],
    myths: [
      { myth: 'Jami was the last great Persian poet.', reality: 'This phrase is a common label, but it is a judgement more than a fact. Persian poetry continued after him, and later poets in Iran and India wrote in new styles. The label reflects his role at the end of the classical period, and some scholars would phrase it less sharply.' },
      { myth: 'He was only a court poet who flattered the powerful.', reality: 'Jami wrote praise poems and benefited from the support of the court. But he also held independent standing as a Sufi master, kept his distance from power, and turned down invitations that would have taken him away from Herat.' },
      { myth: 'He was only a poet.', reality: 'He was equally a grammarian, theologian, biographer and musical theorist. In the Islamic world he was valued as much for his scholarship and his Sufi writings as for his verse.' },
    ],
    works: [
      { title: 'Haft Awrang (Seven Thrones)', note: 'A set of seven long narrative and didactic poems in rhymed couplets, including Yusuf and Zulaykha, his most admired poem.' },
      { title: 'Nafahat al-uns (Breaths of Intimacy)', note: 'A biographical dictionary of Sufi saints, based on earlier sources, written in the 1470s.' },
      { title: 'Baharistan (Abode of Spring)', note: 'A mix of prose and verse, modelled on Sa’di’s Gulistan, composed in 1487.' },
      { title: 'Lawa’ih (Flashes) and commentaries on Ibn Arabi and Iraqi', note: 'His main works on Sufi thought, including a treatise on love and unity.' },
      { title: 'Three divans of lyric poetry', note: 'Collections of his shorter poems, among them ghazals and qasidas.' },
    ],
    legacy: [
      'Jami was read widely from the Ottoman Empire to Mughal India and Central Asia. Madrasa students studied his grammar commentary, poets imitated his poems, and artists illustrated them in manuscripts. His friend Navai wrote a tribute to him after his death, and Navai’s Turkic writings show how far his influence reached beyond Persian.',
      'He is still honoured in Afghanistan, Iran and Tajikistan, which all claim him as a part of their heritage. His reputation as the last of the classical masters rests on the range of his work: poetry, scholarship and Sufi teaching joined in one life. Readers outside the Persian world met him in the nineteenth century through translations, and he remains a good first guide to the mystical Persian tradition.',
    ],
  },
]
