import type { Profile } from './types'

export const MORE_04: Profile[] = [
  {
    slug: 'bernard-of-clairvaux',
    order: 1090,
    dates: '1090 – 1153',
    place: 'Clairvaux, Champagne (France)',
    era: 'Medieval',
    tradition: 'Cistercian mysticism',
    tagline: 'A monk who made love the centre of the spiritual life, and who was also one of the most powerful public voices of twelfth-century Europe.',
    who: [
      'Bernard was born in 1090 into a noble family at Fontaine-lès-Dijon in Burgundy. Around 1113 he entered the new and austere monastery of Cîteaux, bringing with him a group of relatives and friends, traditionally said to number about thirty. Two years later, in 1115, he was sent out to found a daughter house in a wooded valley in Champagne. It became Clairvaux, and he remained its abbot for the rest of his life.',
      'Cîteaux had been founded in 1098 by Robert of Molesme and others who wanted to live the Rule of Saint Benedict more strictly, in simplicity, manual labour and silence. Bernard did not found the Cistercian order, but his energy and eloquence helped it spread across Europe. By his death, well over a hundred monasteries traced their origin to Clairvaux, and he had become a counsellor to bishops, kings and popes. His health, by his own account, was poor, partly because of severe fasting in his youth.',
      'Bernard is often described as a man divided between the cloister he loved and the public life that kept calling him out of it. He supported Pope Innocent II in the disputed election of 1130, travelled widely to settle quarrels, and wrote to the pope who followed, Eugene III, who had once been a monk at Clairvaux. He died at Clairvaux on 20 August 1153, was canonised in 1174, and was named a Doctor of the Church in 1830.',
    ],
    context: [
      'The twelfth century was a time of religious renewal and intellectual change. New monastic orders such as the Cistercians and the Carthusians offered a stricter life than the wealthy older houses, which Bernard criticised in his Apology for their luxury. At the same time, cathedral schools in Paris and elsewhere were developing a new method of argument, scholastic dialectic, in which theological questions were examined with logic and objections. Many monks welcomed the new learning, but Bernard distrusted it when it seemed to turn the mysteries of faith into puzzles.',
      'The century was also an age of papal ambition, church reform and holy war. The First Crusade had taken Jerusalem in 1099, and in December 1144 the Latin county of Edessa fell to the Muslim ruler Zengi. Pope Eugene III responded by calling a new crusade, and Bernard, then the most famous preacher in Europe, was asked to promote it. The expedition that followed, the Second Crusade, is the setting for the most disputed part of his legacy.',
    ],
    ideas: [
      { title: 'The four degrees of love', text: 'In his treatise On Loving God, Bernard describes a ladder of love. We begin by loving ourselves for our own sake, then love God because we need God, then begin to love God for God’s own sake, and finally, rarely and briefly in this life, love ourselves for the sake of God. He insists that God is to be loved because God is lovable, and that the measure of love is to love without measure.' },
      { title: 'Reading the Song of Songs as a story of the soul', text: 'Bernard preached eighty-six sermons on the Song of Songs to his monks, and left the series unfinished when he died. In them the lover and beloved of the biblical poem stand for Christ and the soul. He speaks openly about desire, longing and the experience of God’s presence and absence, and treats such feelings as a path to understanding, not a distraction from it.' },
      { title: 'Experience over argument', text: 'For Bernard, the deepest knowledge of God comes through experience, not debate. He told his monks that they should turn to the “book of experience”, meaning their own lives, since no one can understand what love or compunction is without feeling it. He was wary of an approach to theology that treated the faith mainly as material for clever argument.' },
      { title: 'Humility as the way to truth', text: 'In The Steps of Humility and Pride, he describes twelve stages of the proud person’s descent from curiosity to arrogance, and the reverse climb of the humble. For Bernard, humility is not self-hatred but truthful self-knowledge: seeing oneself as one is, in the light of God’s love.' },
      { title: 'Power must listen', text: 'In On Consideration, written for Pope Eugene III, he urges the head of the Church not to be absorbed by legal business and ceremonial. A ruler needs time to reflect, to look inward and upward, and to remember that he serves others. The book has been quoted by church reformers ever since.' },
    ],
    principles: [
      'Love without measure, and ask what the love is for.',
      'Do not mistake cleverness for wisdom.',
      'Know yourself honestly, neither inflated nor despairing.',
      'Make time for reflection even when the work never stops.',
      'Those who hold power should serve, not just command.',
    ],
    practice: [
      'Set aside a short time each day for silence, without a screen or an agenda, as Bernard asked of busy people in positions of responsibility.',
      'Notice your motives for what you do. Ask whether you are acting from need, from habit or from care for another person.',
      'When you disagree with someone, pause before answering. Bernard thought that being right was less important than being truthful and humble.',
    ],
    facts: [
      'Pope Eugene III had been a monk at Clairvaux before his election in 1145, and Bernard wrote to him as both a spiritual son and a spiritual father.',
      'At the council of Sens in 1141, Bernard confronted the theologian Peter Abelard over a list of propositions drawn from Abelard’s writings. Abelard left the council and appealed to the pope, who condemned the propositions. Abelard died in 1142 at Cluny, under the protection of its abbot, Peter the Venerable.',
      'Bernard preached for the Second Crusade at Vézelay in 1146 and in Germany later that year. He also supported a campaign against the pagan Wends on the Baltic frontier in 1147, and wrote In Praise of the New Knighthood, a text about the Knights Templar.',
      'When a monk named Radulf preached massacres of Jews in the Rhineland in 1146, Bernard wrote against him and travelled to the area. He insisted that Jews should not be killed, and the monk was sent back to his monastery.',
      'The Second Crusade failed. The German and French armies were defeated in Anatolia, and the attack on Damascus in 1148 was abandoned. Bernard himself wrote about the disaster in On Consideration, blaming the sins of the crusaders.',
      'In Dante’s Divine Comedy, Bernard appears near the end of the Paradiso as the final guide who leads the poet to the vision of God.',
    ],
    myths: [
      { myth: 'Bernard founded the Cistercian order.', reality: 'The order began at Cîteaux in 1098 under Robert of Molesme and his companions, and was shaped by Stephen Harding. Bernard joined in 1113 and became its most important promoter, but he was not the founder.' },
      { myth: 'Bernard invented the Knights Templar and wrote their rule.', reality: 'The Templars were founded around 1119 by Hugh of Payns and others. Bernard supported them, including at the council of Troyes in 1129, and wrote In Praise of the New Knighthood. How large his part was in the early rule is disputed.' },
      { myth: 'Bernard wrote the hymn “Jesu dulcis memoria” and other famous devotions that bear his name.', reality: 'Several hymns and prayers long linked to Bernard were probably written by others in later centuries. Scholars rely on his sermons, letters and treatises for his own voice.' },
    ],
    works: [
      { title: 'On Loving God (De diligendo Deo)', note: 'A short treatise on the reasons for and degrees of love, written around the 1120s–1130s.' },
      { title: 'Sermons on the Song of Songs', note: 'Eighty-six sermons delivered to his monks over many years, never finished. They are his greatest work of mystical theology.' },
      { title: 'On Consideration (De consideratione)', note: 'Advice to Pope Eugene III on how a pope should govern and reflect, written in the late 1140s and early 1150s.' },
      { title: 'The Steps of Humility and Pride', note: 'An early treatise setting out his view of humility as truth.' },
      { title: 'Letters', note: 'About five hundred letters survive, giving a close view of church politics, friendship and the crusade.' },
    ],
    legacy: [
      'Bernard shaped the emotional tone of later medieval devotion. His emphasis on affection, on the humanity of Christ and on the role of Mary influenced the Cistercians, and the Franciscans. Martin Luther, centuries later, praised his piety. His view of the unfinished, felt knowledge of God remained a counterweight to the ordering of theology in the new universities.',
      'His public career is remembered with mixed feelings. His part in the Second Crusade, in the condemnation of Abelard, and in expanding the power of the Church is judged very differently depending on the historian, while his writing on love, humility and reflection is still read and loved. Most modern accounts treat him as a complex figure of his age: sincere, influential, severe in some matters and tender in others.',
    ],
  },
  {
    slug: 'hildegard-of-bingen',
    order: 1098,
    dates: '1098 – 1179',
    place: 'Disibodenberg and Bingen, Rhineland (Germany)',
    era: 'Medieval',
    tradition: 'Christian mysticism',
    tagline: 'A German abbess who recorded her visions, wrote music, studied nature and healing, and spoke to popes and emperors.',
    who: [
      'Hildegard was born around 1098 at Bermersheim, near Mainz, to a noble family. Tradition says she was the tenth child and was given to the Church as a child. She later wrote that she had seen visions since early childhood. Around 1112 she entered the enclosed cell attached to the Benedictine monastery of Disibodenberg, where an older woman, Jutta of Sponheim, was her teacher. When Jutta died in 1136, Hildegard was chosen to lead the growing community of nuns.',
      'In 1141, when she was about forty-two, she said that a voice commanded her to write down what she saw and heard. With the help of the monk Volmar, who acted as her secretary and adviser, she began her first great book, Scivias, which she finished around 1151. The archbishop of Mainz and, later, Pope Eugene III, who heard parts of her work at a synod at Trier in 1147–48, are said to have approved of it. Bernard of Clairvaux is said to have spoken in her favour.',
      'Around 1150 she moved her nuns to a new convent at Rupertsberg near Bingen, and later founded a second house at Eibingen across the river. She kept writing, composing and corresponding, and in her sixties and early seventies she undertook preaching journeys along the Rhine and beyond, which was highly unusual for a woman. She died on 17 September 1179, shortly after a dispute with the church authorities of Mainz that had placed her convent under an interdict, which was lifted just before her death.',
    ],
    context: [
      'Hildegard lived in a Germany that was part of the Holy Roman Empire, during a long struggle between popes and emperors. Frederick Barbarossa became emperor in 1155 and supported rival popes, and Hildegard wrote letters to rulers and bishops warning them about their conduct. Monasteries were the main centres of learning, and women’s houses, like hers, were among the few places where women could study, write and hold authority.',
      'Medicine and natural philosophy were then based on ideas inherited from the ancient world: that the body is governed by four humours, that the human being mirrors the larger cosmos, and that plants, stones and animals have properties that can heal or harm. The great translations from Arabic into Latin that changed European science mostly came later, so Hildegard drew on monastic herbal lore, Latin sources and her own observation.',
    ],
    ideas: [
      { title: 'Visions as theology', text: 'In Scivias, a title commonly explained as “know the ways”, she describes twenty-six visions of creation, redemption and the end of time, and then explains their meaning. She said she saw them with her waking eyes and mind, not in a trance. The visions are full of images of light, fire, jewels, mountains and living figures, which she interprets as teaching about the Church and the soul.' },
      { title: 'Viriditas: the greening power of God', text: 'She used the Latin word viriditas, “greenness” or freshness, for the life-giving power that runs through creation and through a healthy soul. In her view, nature and spirit belong together. Neglecting the spirit makes the soul dry, just as a lack of water withers a plant.' },
      { title: 'Body, soul and cosmos', text: 'Her writings on nature and medicine, Physica and Causae et Curae, treat health as a balance among body, mind and the surrounding world. They describe plants, stones, fish and animals, and many remedies, as well as the humours and the causes of disease. Modern scholars note that she was working within medieval ideas, so her remedies cannot be judged by modern standards.' },
      { title: 'Music as the voice of heaven', text: 'She composed a cycle of more than sixty liturgical songs, collected as the Symphonia, for the nuns to sing. The melodies are unusually wide-ranging and ornate for plainchant. In her morality play Ordo Virtutum, sixteen virtues, sung, contend with the devil, whose part is spoken, not sung. For Hildegard, music recalled the harmony that humanity lost in Eden and hoped to regain.' },
      { title: 'A woman’s voice with authority', text: 'Hildegard described herself as a poor and unlearned woman, but she believed God had given her a message that she was bound to share. She wrote to popes, emperors and abbots, sometimes with sharp criticism of corruption in the Church. Her claim to authority rested on prophecy, not office, and the Church of her time accepted it, at least in part.' },
    ],
    principles: [
      'Keep body, mind and spirit in balance.',
      'Stay green: tend what is alive in you.',
      'Use the gifts you are given, even if you feel unqualified.',
      'Speak honestly to those in power.',
      'Find harmony through music and beauty.',
    ],
    practice: [
      'Spend regular time among plants or trees, and note what changes in your mood and energy.',
      'Sing or listen to a piece of music with full attention for ten minutes, with no other task.',
      'When you feel you have no standing to speak on something that matters, write down what you know and say it plainly.',
    ],
    facts: [
      'The title Scivias is a contraction of the Latin words for “know the ways of the Lord”, according to the usual explanation.',
      'About 390 of her letters survive, to correspondents including popes, Emperor Frederick Barbarossa, Bernard of Clairvaux, abbots and ordinary nuns.',
      'She invented a secret language, the Lingua ignota, a list of roughly a thousand invented words with Latin or German glosses, and a special alphabet. Its purpose is not known.',
      'She undertook four preaching tours along the Rhine and into other regions between about 1158 and 1171, speaking in public to clergy and laypeople.',
      'The Church had long honoured her as a saint, but a formal process was never completed. In 2012 Pope Benedict XVI extended her veneration to the whole Church and, on 7 October 2012, named her a Doctor of the Church.',
      'In 1178–79 her convent was placed under an interdict, forbidding it to sing or celebrate Mass, after she permitted the burial of a man whom church authorities considered excommunicated. She protested, and the interdict was lifted in March 1179.',
    ],
    myths: [
      { myth: 'Hildegard’s visions were simply migraines.', reality: 'In the twentieth century the historian Charles Singer suggested that some visions resemble the shimmering light of a migraine aura. Others find this unconvincing as a full explanation, and no diagnosis can be certain from a medieval text. Her own account stressed that she regarded them as divine revelation and spent years interpreting them.' },
      { myth: 'Everything in the medical books credited to her is certainly by her.', reality: 'Physica and Causae et Curae survive only in manuscripts copied after her death, and scholars disagree about how much was written by her, how much she dictated, and how much was compiled or altered by others. They are best treated as texts from her circle.' },
      { myth: 'She was a lone rebel against the Church.', reality: 'Hildegard worked within the Church and had the backing of Bernard, of Pope Eugene III, and of many abbots and bishops. She criticised corrupt clergy, but she did so as a loyal member of the Church, and she opposed groups that she considered heretical.' },
    ],
    works: [
      { title: 'Scivias', note: 'Her first visionary work (c. 1141–1151), with twenty-six visions in three books on creation, redemption and the end of time.' },
      { title: 'Liber vitae meritorum and Liber divinorum operum', note: 'Her second and third visionary works, on moral life and on the relation of God, humanity and the cosmos.' },
      { title: 'Symphonia and Ordo Virtutum', note: 'Her liturgical songs and her musical morality play.' },
      { title: 'Physica and Causae et Curae', note: 'Books on natural history and on medicine, whose exact authorship is debated.' },
      { title: 'Letters', note: 'Hundreds of letters that show her relations with the powerful and her pastoral concern for her nuns.' },
    ],
    legacy: [
      'Hildegard’s influence in her own age was real but limited, and her works were copied for centuries in the Rhineland. In the twentieth century she was rediscovered. Her songs were recorded and performed, her visions studied by historians of religion, and her life became an example for those writing about women in the medieval Church.',
      'Her reputation today includes much that goes beyond the evidence, such as wellness products and diets sold under her name, which are not supported by clinical research. A careful reading shows a monastic leader of great intelligence and courage who joined theology, music and care for the natural world in a way few others of her time attempted.',
    ],
  },
  {
    slug: 'moshe-ben-maimon',
    order: 1138,
    dates: '1138 (or 1135) – 1204',
    place: 'Córdoba, Fez and Fustat (Cairo)',
    era: 'Medieval',
    tradition: 'Jewish philosophy',
    tagline: 'A physician and judge who codified Jewish law and argued that faith and reason belong together.',
    who: [
      'Maimonides, whose Hebrew name was Moses ben Maimon, was born in Córdoba in Muslim Spain, on the eve of Passover in 1138 according to the most widely accepted reckoning. Some scholars prefer 1135. His father, Maimon, was a scholar and a judge who taught him Torah, Talmud, mathematics and astronomy. He grew up in a city with a rich Arabic-language culture in which Jewish scholars wrote in Arabic as well as Hebrew.',
      'In 1148 the Almohads, a strict Muslim dynasty from North Africa, conquered Córdoba and pressed non-Muslims to convert. His family left, and after years of moving around Spain, they settled in Fez in Morocco around 1160, then travelled to Palestine in 1165, and finally to Egypt, where they settled in Fustat, next to modern Cairo. There he became a leading figure of the Jewish community. After the death of his brother David, a merchant who supported the family, around 1169 or 1170, he turned to medicine as a livelihood.',
      'He became a physician in the household of the court of Saladin’s government, and later served the ruling family, while teaching, judging and answering questions from Jewish communities as far away as Yemen and southern France. In a letter to a translator he described long days at court followed by long evenings of patients and writing. He died in Fustat on 12 December 1204 and, according to tradition, was buried in Tiberias in the Land of Israel.',
    ],
    context: [
      'Maimonides lived in the Arabic-speaking Mediterranean, where Greek philosophy and science had been translated and developed by Muslim thinkers such as al-Farabi, Avicenna and, in his own Córdoba, Averroes. Jewish thinkers took part in this culture and wrote in Judeo-Arabic, which is Arabic in Hebrew letters. Maimonides placed himself in this philosophical tradition, drawing especially on Aristotle as read by the Muslim philosophers.',
      'His own times were unstable for Jews. The Almohad conquest ended the relative tolerance of earlier Muslim Spain, and in the 1160s and 1170s he wrote letters encouraging endangered communities to hold firm. Egypt, newly under Saladin’s rule after 1171, offered more security. Throughout, he wanted Jewish teaching to be clear, systematic and accessible to people who had little time to master the huge Talmudic literature.',
    ],
    ideas: [
      { title: 'Law made clear', text: 'In the Mishneh Torah, written in clear Hebrew between about 1170 and 1180, Maimonides organised the whole of Jewish law into fourteen books, without citing his sources or arguments. His aim was that a reader could find the answer without studying the Talmud first. Critics, notably Abraham ben David of Posquières, objected that he left out his reasoning, but the work became a central text of Jewish law.' },
      { title: 'Principles of faith', text: 'In his commentary on the Mishnah, completed around 1168, he set out thirteen principles that he considered basic to Judaism, including the existence and unity of God, God’s lack of a body, the truth of prophecy, the Torah’s divine origin, reward and punishment, the coming of the Messiah, and the resurrection of the dead. The list was influential but also debated, and later thinkers such as Hasdai Crescas and Joseph Albo offered their own.' },
      { title: 'God can be described only by negation', text: 'In his philosophical work The Guide for the Perplexed, written in Arabic around 1190, he argued that God is utterly unlike creatures, so positive statements about God’s nature mislead. We can say what God is not, and in doing so approach silence. Biblical descriptions of God with a body or emotions are to be read as figures for the human mind.' },
      { title: 'Reason and revelation do not conflict', text: 'Maimonides held that truth cannot contradict truth. When a demonstrated philosophical result seems to conflict with a verse, the verse should be reinterpreted. When a philosophical claim is not demonstrated, as in his view Aristotle’s claim that the world is eternal, scripture may stand. This was a moderate path between those who rejected philosophy and those who put it above faith.' },
      { title: 'The middle path and care for the poor', text: 'In his writings on character he recommended the moderate path, avoiding extremes of anger, greed or excessive self-denial. In the Mishneh Torah he also set out eight levels of charity, from reluctant giving to the highest, helping a person become self-supporting so that he or she needs no help.' },
    ],
    principles: [
      'Seek the middle path and avoid extremes.',
      'Do not set faith and reason against each other.',
      'Give in a way that restores independence and dignity.',
      'Say clearly what you know and admit what you do not.',
      'Treat knowledge as a way of serving others, not of rising above them.',
    ],
    practice: [
      'When you give money or help, ask whether it also helps the other person to stand on their own, for example through a loan, a job or training.',
      'Choose a habit you tend to exaggerate, such as working, spending or criticising, and aim for the middle rather than the opposite extreme.',
      'When a claim troubles you, check what is actually demonstrated before deciding whether to doubt it or to reread it in a new light.',
    ],
    facts: [
      'His name is often abbreviated in Hebrew as Rambam, from Rabbi Moses ben Maimon. In Arabic he was known as Musa ibn Maymun.',
      'The Guide for the Perplexed was written as a letter to a favourite student, Joseph ibn Judah, and was translated into Hebrew within Maimonides’s own lifetime.',
      'He wrote about ten medical works in Arabic, including treatises on asthma, poisons and haemorrhoids, and a regimen of health for a prince of the Ayyubid family.',
      'After his death a fierce debate arose in southern France and elsewhere about whether his philosophical writings threatened Jewish tradition. In the 1230s opponents and defenders appealed to Christian and Jewish authorities.',
      'Christian scholastics, including Thomas Aquinas, read the Guide in Latin translation and cited him as “Rabbi Moses”.',
      'His tomb in Tiberias remains a place of visits for Jews and others.',
    ],
    myths: [
      { myth: 'The famous “Prayer of Maimonides” for physicians was written by Maimonides.', reality: 'The prayer is generally attributed to Markus Herz, a German Jewish physician of the late eighteenth century. It reflects a later spirit and is not found in medieval sources.' },
      { myth: 'Maimonides simply followed Aristotle and put philosophy above the Torah.', reality: 'He used Aristotle heavily, but argued against him on matters such as the eternity of the world, and held that the Torah teaches creation. He saw philosophy and Jewish law as partners, not rivals.' },
      { myth: 'His Thirteen Principles were accepted by all Jewish thinkers.', reality: 'They became well known, partly through a later poem and a prayer-book version, but medieval thinkers disagreed about how many principles there are and which ones are essential.' },
    ],
    works: [
      { title: 'Commentary on the Mishnah', note: 'Written in Arabic and completed around 1168, with introductions on prophecy and the Thirteen Principles.' },
      { title: 'Mishneh Torah', note: 'The fourteen-book code of Jewish law, in Hebrew, c. 1170–1180.' },
      { title: 'The Guide for the Perplexed', note: 'His philosophical masterpiece, written in Judeo-Arabic around 1190, on how to read scripture and speak about God.' },
      { title: 'Medical writings', note: 'Several works in Arabic on health, diet, poisons and diseases.' },
      { title: 'Letters', note: 'Including the Letter to Yemen (c. 1172) and his letter to Samuel ibn Tibbon on his daily life.' },
    ],
    legacy: [
      'Maimonides became the most influential figure in Jewish thought after the Talmud. The Mishneh Torah shaped later codes, and commentators on law still discuss it, while the Guide opened a long line of Jewish philosophy, from Gersonides to Spinoza, who both drew from it and argued against it. A saying attached to him in later centuries compared him to Moses, a sign of his reputation.',
      'Beyond Judaism, his example of joining faith and philosophy was taken up by Christian scholastics, especially Aquinas. Today Maimonides is remembered as a codifier, a doctor and a philosopher who tried to show that careful thought can strengthen faith, though thinkers still disagree on what he really meant in the hardest passages of the Guide.',
    ],
  },
  {
    slug: 'attar-of-nishapur',
    order: 1145,
    dates: 'c. 1145 – c. 1221',
    place: 'Nishapur, Khorasan (now northeastern Iran)',
    era: 'Medieval',
    tradition: 'Sufism',
    tagline: 'A Persian apothecary-poet who told the story of the soul as a flight of birds in search of their king.',
    who: [
      'Farid al-Din Muhammad, known as Attar, lived in Nishapur, then one of the great cities of Khorasan in northeastern Iran. His pen name means roughly “druggist” or “perfumer”, and ancient sources say he worked as an apothecary, treating customers while composing. The details of his life are uncertain, and his dates are traditional, so the years c. 1145 to c. 1221 are best treated as approximate.',
      'A well-known story says that he gave up his shop after a visiting dervish looked over his goods and asked how he would manage to die with all this. Whether the encounter happened or not, Attar became a Sufi, a follower of the mystical path within Islam, and most of his writing is concerned with the soul’s search for God. He wrote in Persian, in verse and in prose, and drew on stories of saints, kings, beggars and fools.',
      'Tradition says that he died when the Mongols took Nishapur in April 1221, killing much of its population. Many scholars treat this as a legend that fits a tragic end to an exemplary life, and some propose other dates for his death, so it should be called a tradition and not an established fact. A mausoleum in Nishapur is honoured as his tomb.',
    ],
    context: [
      'Attar lived at the end of a rich period in Persian culture. Poets such as Sanai had already made Persian a language of mystical poetry, and Sufism had grown from small circles of ascetics into a wide movement with orders, teachers and a large literature. The stories of earlier saints, like the woman mystic Rabia and the martyred Hallaj, were being gathered and told.',
      'The world around him was violent. Seljuk power had weakened, Khorasan’s cities were repeatedly attacked, and in the early thirteenth century the Mongol armies of Genghis Khan swept into the region. Nishapur was devastated in 1221. Attar’s tales of detachment, loss and the nearness of death were written under the shadow of such upheavals.',
    ],
    ideas: [
      { title: 'The soul as a bird in search of its king', text: 'In The Conference of the Birds, thousands of birds gather and are urged by the hoopoe to seek the Simorgh, their legendary king. Each bird makes an excuse, standing for a human weakness such as vanity, fear or love of ease. The story is an allegory of the spiritual path, and of the many ways people avoid it.' },
      { title: 'The seven valleys', text: 'The journey passes through seven valleys, usually named as Quest, Love, Understanding, Detachment, Unity, Bewilderment, and Poverty and Annihilation. Each valley strips away something the traveller relies on. The sequence has been read as a map of mystical experience, from first longing to the dissolving of the self.' },
      { title: 'We are what we seek', text: 'Only thirty birds survive the journey. When they reach the court of the Simorgh, they see only themselves reflected there. The story depends on a Persian pun, because si morgh means “thirty birds”. The point is that the goal of the quest is not outside the seeker, though it cannot be found without the journey.' },
      { title: 'Saints as teachers by example', text: 'In his prose Memorial of the Saints (Tadhkirat al-awliya), Attar collected sayings and anecdotes about early Muslim saints and mystics. He presents them not as perfect beings but as people who struggled, laughed, failed and persevered. The anecdotes teach by example.' },
      { title: 'Love beyond reason and convention', text: 'Attar often praises the lover who is willing to be called a fool, a heretic or a beggar for the sake of God. Many of his stories turn on surprising figures, such as a prostitute or a madman, whose sincerity puts the respectable to shame. This frees the spiritual life from outward status.' },
    ],
    principles: [
      'Start the journey, even if you are afraid.',
      'Look for the cause of your excuses before you offer them.',
      'Do not judge a person by their appearance or standing.',
      'What you seek may be closer than you think.',
      'Let go of what you cling to.',
    ],
    practice: [
      'Write down the excuse you most often give for not doing something that matters, and ask what it protects you from.',
      'Read a short story or fable aloud once a week and ask what each character stands for in you.',
      'Practice generosity toward a person you tend to look down on, and notice what you learn.',
    ],
    facts: [
      'The Conference of the Birds, in Persian Mantiq al-tayr, means roughly “the language of the birds”, and runs to several thousand couplets.',
      'Attar wrote several long narrative poems, among them the Ilahi-nama (“Book of God”), the Asrar-nama (“Book of Secrets”) and the Musibat-nama (“Book of Affliction”).',
      'Many works were later attributed to him that scholars now believe were written by others, so the exact list of his works is still debated.',
      'The Mongols sacked Nishapur in 1221 after the death of a Mongol commander there, in one of the worst massacres of the conquest of Khorasan.',
      'The Conference of the Birds was translated into French by Garcin de Tassy in the nineteenth century, and was adapted for the stage by Jean-Claude Carrière and Peter Brook in 1979.',
      'Rumi, the great Persian poet, is reported to have said that Attar had passed through the seven cities of love while he himself was still at the bend of one alley.',
    ],
    myths: [
      { myth: 'Attar certainly died in the Mongol massacre of Nishapur in 1221.', reality: 'This is a long-standing tradition. Some scholars doubt it, and the evidence for the dates of his life is late and uncertain.' },
      { myth: 'The young Rumi met Attar in Nishapur, and Attar gave him a book and foretold his greatness.', reality: 'The story is told in later biographical works, about a century after the supposed meeting, and many historians regard it as a legend that expresses the link between the two poets. Rumi did honour Attar as a master, which is well attested in his own verse.' },
      { myth: 'Everything attributed to Attar is by Attar.', reality: 'Many poems and treatises circulated under his name. Scholars have separated a smaller group of works, such as The Conference of the Birds and the Memorial of the Saints, that are generally accepted, from others that are doubtful.' },
    ],
    works: [
      { title: 'The Conference of the Birds (Mantiq al-tayr)', note: 'His best-known poem, an allegory of the soul’s search in thousands of couplets with many embedded stories.' },
      { title: 'Memorial of the Saints (Tadhkirat al-awliya)', note: 'His prose collection of lives and sayings of Sufi saints, a major source for early Sufism.' },
      { title: 'Ilahi-nama, Asrar-nama and Musibat-nama', note: 'Long narrative poems with frame stories and moral tales.' },
      { title: 'Divan', note: 'A collection of lyric poems (ghazals) and quatrains, partly of uncertain authorship.' },
    ],
    legacy: [
      'Attar shaped the Persian mystical tradition more than almost anyone except Rumi. Later poets reused his images of the bird, the valley and the king, and Rumi honoured him in verse as a master whose spiritual journey was far ahead of his own. Through translation his work reached Europe and a wider public in the nineteenth and twentieth centuries.',
      'The Conference of the Birds continues to be read and staged, and its allegory of a self that is found only through losing itself has been applied in many settings. Because the record of Attar’s life is thin, he remains less a historical personality than the voice of his poems, whose stories continue to speak across languages and centuries.',
    ],
  },
  {
    slug: 'roger-bacon',
    order: 1220,
    dates: 'c. 1219/20 – c. 1292',
    place: 'Oxford and Paris',
    era: 'Medieval',
    tradition: 'Scholastic natural philosophy',
    tagline: 'A Franciscan friar who argued that knowledge of nature needs experience, mathematics and languages, and who became a legend.',
    who: [
      'Roger Bacon was born around 1219 or 1220, probably in the west of England, and studied at Oxford before teaching in the arts faculty at Paris in the 1240s. There he lectured on Aristotle at a time when Aristotle’s natural philosophy, newly translated from Arabic and Greek, was a source of both excitement and suspicion. He returned to Oxford later and, by his own account, spent a large sum on books, instruments and assistants.',
      'Around 1257 he joined the Franciscan order. He says he felt restricted there, and he complained that his superiors discouraged his work. A turning point came when Guy Foulques, who became Pope Clement IV in 1265, asked him in 1266 to send his writings. Bacon responded with three long works, the Opus Majus, the Opus Minus and the Opus Tertium, written around 1267 and 1268.',
      'After Clement died in 1268, Bacon’s patronage vanished. A later tradition says that he was condemned and imprisoned by his order in the late 1270s, but the evidence is thin and late, and many scholars doubt it. He was still writing around 1292, the date of his last known work, and probably died in or soon after that year, most likely at Oxford.',
    ],
    context: [
      'Bacon lived in the age of the new universities of Paris and Oxford, where the translation of Greek and Arabic science changed what scholars read. The works of Aristotle, Ibn al-Haytham (Alhazen) on optics, and Avicenna on medicine and natural philosophy came into Latin. Oxford had a local tradition of interest in light and mathematics, associated with Robert Grosseteste, the bishop of Lincoln, whose ideas Bacon built on.',
      'The Church supervised learning closely. Parts of Aristotle’s teaching had been restricted in Paris in the early thirteenth century, and in 1277 the bishop of Paris condemned a long list of propositions. Within this setting, Bacon was a combative schoolman who criticised famous colleagues, argued for reform and wished to harness learning for the Church’s needs.',
    ],
    ideas: [
      { title: 'Experience as a source of certainty', text: 'In the Opus Majus Bacon argues that argument alone does not give certainty, and that we need experience, the testing of claims by observation and trial. He distinguishes ordinary experience from a more special “experimental science” that uses instruments and trained observers. He placed this inside a Christian vision, where better knowledge of nature would serve religion.' },
      { title: 'Mathematics and optics as keys to nature', text: 'Bacon held that mathematics underlies all the sciences, and he gave particular attention to optics, the study of light and vision, following Alhazen. He wrote on reflection, refraction, lenses, mirrors, the rainbow and the structure of the eye, and he thought that studying light revealed how natural forces act across distance.' },
      { title: 'Four obstacles to truth', text: 'He listed four chief causes of error: trust in unworthy authority, the weight of custom, the opinion of the crowd, and hiding ignorance behind a show of wisdom. The list was aimed at contemporaries, but it reads as a general guide to thinking clearly.' },
      { title: 'Languages as tools of knowledge', text: 'Bacon complained that translators of Aristotle and the Bible did not know enough Greek, Hebrew or Arabic. He wrote grammars of Greek and Hebrew, and urged scholars to learn the languages in which the sources were written, since errors in translation distort science and theology alike.' },
      { title: 'Science for the good of the Church and society', text: 'He called for a reform of education and for the use of natural knowledge, including mathematics, geography and medicine, to improve life. In a letter on the secrets of art and nature, he imagined machines such as ships and carriages that moved without being pulled, and flying devices, and he suggested that careful calendar reform was needed. These were speculations, not inventions he built.' },
    ],
    principles: [
      'Test a claim before you trust it.',
      'Be wary of authority, habit, popular opinion and pretended knowledge.',
      'Learn the original languages and sources.',
      'Use knowledge to serve others.',
      'Accept that new knowledge can improve on old.',
    ],
    practice: [
      'When you hear a claim repeated, ask which of the four obstacles might be at work: authority, custom, the crowd or concealed ignorance.',
      'Try to read at least one important text in the original language, or compare two translations.',
      'Choose a small question you can test yourself, such as a recipe, a habit or a comparison, and record what you actually see.',
    ],
    facts: [
      'The title “Doctor Mirabilis”, “wonderful teacher”, was attached to him in later centuries.',
      'Bacon’s writings include the earliest known European description of a mixture of saltpetre, charcoal and sulphur, concealed in a coded passage, which has been interpreted as the ingredients of gunpowder.',
      'He wrote the Opus Majus in answer to a papal request, and said he did so in secret, because the rules of his order forbade friars to circulate their writings without permission.',
      'He criticised the Julian calendar for having drifted from the true solar year, and pressed the pope to reform it, three centuries before the Gregorian reform.',
      'Bacon had no relation to the later philosopher Francis Bacon, who lived in the sixteenth and seventeenth centuries.',
      'Opus Majus was only fully printed in the eighteenth century, and John Henry Bridges produced a standard edition in 1897–1900.',
    ],
    myths: [
      { myth: 'Roger Bacon was imprisoned for a decade or more because of his scientific work.', reality: 'The claim comes from a fourteenth-century chronicle and is not confirmed by contemporary evidence. Scholars doubt it or are unsure about its date and cause. If he was disciplined, it may have been related to the condemnations of the 1270s or to his criticism of other friars, not to science as such.' },
      { myth: 'He built a brazen head that could speak.', reality: 'This legend grew in later centuries, and it was popularised in the Elizabethan play Friar Bacon and Friar Bungay by Robert Greene. No medieval source says Bacon made one. Stories of such heads were told about several medieval scholars.' },
      { myth: 'Roger Bacon was the founder of the scientific method.', reality: 'Nineteenth- and twentieth-century admirers often called him a lone forerunner of modern science. Historians now see him as one thinker among many in thirteenth-century Oxford and Paris, building on Grosseteste and on Arabic science. His programme was rarely carried out in practice, and he also wrote about astrology and alchemy.' },
    ],
    works: [
      { title: 'Opus Majus', note: 'His major work (1267–68), in seven parts: causes of error, philosophy and theology, languages, mathematics, optics, experimental science and moral philosophy.' },
      { title: 'Opus Minus and Opus Tertium', note: 'Companion works, partly summaries and partly additions, also sent to Clement IV.' },
      { title: 'Compendium of the Study of Philosophy', note: 'A later work, c. 1272, criticising the state of learning and the clergy.' },
      { title: 'Greek and Hebrew grammars', note: 'Surviving writings on languages, some of them fragmentary.' },
      { title: 'Letter on the secrets of art and nature', note: 'A short text on wonders and on the limits of magic, containing the concealed formula, whose authorship and date have been debated.' },
    ],
    legacy: [
      'In his own time Bacon had limited influence. His books were copied for several centuries, but he did not found a school, and his work was largely overshadowed by the great Parisian masters. In late medieval and early modern times he acquired a reputation as a magician, which is how he appears in Elizabethan plays and chapbooks.',
      'From the nineteenth century, scholars rediscovered his manuscripts and often exaggerated his importance as a modern figure before his time. The more careful picture today shows a gifted, argumentative friar who placed experiment, mathematics and languages at the centre of learning, and who illustrates how much of what we call early science was done within medieval religion and universities.',
    ],
  },
]
