import type { Profile } from './types'

export const MORE_16: Profile[] = [
  {
    slug: 'g-k-chesterton',
    order: 1874,
    dates: '1874 – 1936',
    place: 'London and Beaconsfield, England',
    era: '20th Century',
    tradition: 'Christian apologetics and paradox',
    tagline: 'A huge, laughing English journalist who defended old ideas by turning them upside down.',
    who: [
      'Gilbert Keith Chesterton was born in Kensington, London, on 29 May 1874, and was educated at St Paul’s School and then at the Slade School of Art, where he studied illustration before turning to writing. He married Frances Blogg in 1901, and the couple settled in Beaconsfield, Buckinghamshire, in 1909. A very tall, large man who wore a cape and a crumpled hat, he became one of the best-known public figures in England long before he was fifty.',
      'He made his living as a journalist, and later writers estimate that he produced around eighty books and several thousand essays. His weekly column in the Illustrated London News ran for decades, and he wrote novels, poems, biographies of Dickens, Browning, Francis of Assisi and Thomas Aquinas, and the Father Brown detective stories. Orthodoxy appeared in 1908, a lively account of how he came to believe in Christianity, and The Everlasting Man in 1925, a counter-history of humanity written in reply to H. G. Wells.',
      'Chesterton moved from a loose Anglicanism towards Rome, and was received into the Catholic Church in 1922. In the 1920s he also led a political campaign, through G.K.’s Weekly and the Distributist League, for a society of many small property owners. He was a famous public debater, above all against his friend George Bernard Shaw. He died at Beaconsfield on 14 June 1936, and his funeral was held in Westminster Cathedral.',
    ],
    context: [
      'Chesterton came of age in the Edwardian years, when science, socialism and doubt were reshaping English life. Many clever people of his generation, including Shaw and Wells, believed that progress would sweep away religion and that experts should plan society. Chesterton thought these confident predictions were themselves a kind of faith, and he enjoyed questioning them with humour instead of anger.',
      'The First World War, the rise of big business and the Depression gave his politics a sharper edge. He distrusted both large capitalist combines and state socialism, and drew on Catholic social teaching, especially Pope Leo XIII’s 1891 encyclical Rerum Novarum, to argue that ordinary families should own land and tools. He also lived through the early rise of fascism and Nazism, which he criticised, while his own writings on Jews were attacked during his lifetime and are still debated today.',
    ],
    ideas: [
      { title: 'Paradox as a way of seeing', text: 'Chesterton’s trademark was the paradox: a statement that sounds absurd at first and turns out to be true. He used it to wake readers from habit, as when he argued that the madman is not the person who has lost his reason but the one who has lost everything except his reason. For him a paradox was often just the truth standing on its head to get attention.' },
      { title: 'Wonder and gratitude', text: 'In Orthodoxy he argues that the right response to existence is surprise and thanks, and he calls the world a kind of fairy tale in which every ordinary thing could have been otherwise. Boredom, he thought, comes from losing the ability to be amazed. He believed religion begins in gratitude for being here at all.' },
      { title: 'The democracy of the dead', text: 'Chesterton defended tradition by describing it as giving a vote to the most neglected of all classes, our ancestors. He did not mean that the past is always right, but that we should not ignore what many generations have learned. His “fence” parable, from a 1929 essay, says that before you remove a fence you should first find out why somebody put it there.' },
      { title: 'Distributism', text: 'Distributism is Chesterton’s and Hilaire Belloc’s answer to both capitalism and socialism. Their slogan was that the problem with capitalism is not that it makes too many capitalists but that it makes too few. They wanted property, such as land, workshops and shops, spread across as many families as possible, so that ordinary people would have real independence. The movement had limited political success, but it influenced later talk about small-scale ownership and local economies.' },
      { title: 'The story of humanity as a surprise', text: 'In The Everlasting Man, Chesterton argues that humans are not just another animal, and that history looks different if you set aside the assumption that Christianity is only one religion among many. He insists on art, ritual and laughter as signs of something special in people. The book is a work of persuasion, not of scholarship, but it helped change the mind of the young C. S. Lewis, who later said so.' },
    ],
    principles: [
      'Stay amazed by ordinary things and give thanks for them.',
      'Do not remove a custom or institution until you understand why it exists.',
      'Argue with good humour and treat your opponent as a friend you have not yet convinced.',
      'Be suspicious of large schemes that promise to fix everyone from above.',
      'Take small things, such as home, family and neighbourhood, seriously.',
    ],
    practice: [
      'When you are bored, describe a familiar thing, such as a lamp-post or a loaf of bread, as if you had never seen it before.',
      'Before dismissing a tradition, write down the best reason someone might have had for starting it.',
      'In your next disagreement, state your opponent’s view so well that they would agree with your summary before you reply.',
    ],
    facts: [
      'Father Brown, the priest-detective, first appeared in 1910. Chesterton is said to have based him partly on a real priest, Father John O’Connor of Bradford, who received him into the Church.',
      'He wrote The Man Who Was Thursday (1908), a dreamlike thriller about anarchists and detectives, which he subtitled “a nightmare”.',
      'Pope Pius XI made him a Knight Commander of the Order of St Gregory the Great in 1933.',
      'His debates with Shaw, who was a socialist and a sceptic, were popular, friendly spectacles. A well-known 1927 public debate, “Do We Agree?”, was chaired by Belloc.',
      'Many writers have admired him, among them C. S. Lewis, Jorge Luis Borges, T. S. Eliot and Marshall McLuhan, though not always for the same reasons.',
      'In Eugenics and Other Evils (1922) he attacked the eugenics movement, which many educated people in Britain then supported.',
    ],
    myths: [
      { myth: '“When men choose not to believe in God, they do not thereafter believe in nothing, they then become capable of believing in anything” is a Chesterton quotation.', reality: 'This exact wording has not been found in his writings. It is a popular compression of a theme he did write about. A similar remark appears in a Father Brown story, but the version people quote online seems to be a later paraphrase.' },
      { myth: 'Chesterton was simply an antisemite, or, on the other side, simply a friend of the Jews.', reality: 'The evidence is mixed, and scholars disagree about how to weigh it. He wrote disparaging generalisations about Jews and, after the Marconi scandal of 1912–13 involving his brother Cecil, was hostile to particular Jewish financiers and politicians. In The New Jerusalem (1920) he supported a Jewish homeland, while arguing that Jews were a separate nation. He also condemned Nazi racial theory and persecution in the 1930s. Some scholars call him a mainstream antisemite of his time, while others argue his hostility was political and limited. G.K.’s Weekly, which he edited, also printed antisemitic pieces by others, and how far he approved them is uncertain.' },
      { myth: 'He was a narrow-minded reactionary who hated modern life.', reality: 'He was a radical on many questions, a supporter of ordinary workers and small property, an early critic of eugenics, and a lover of modern inventions such as the detective story, the cinema and radio. He broadcast on the BBC from 1931.' },
    ],
    works: [
      { title: 'Orthodoxy (1908)', note: 'His best-known book of ideas: a cheerful, paradoxical account of why he came to believe.' },
      { title: 'The Everlasting Man (1925)', note: 'A sweeping reply to H. G. Wells’s Outline of History, and a favourite of C. S. Lewis.' },
      { title: 'The Father Brown stories (from 1910)', note: 'A series of short detective stories, beginning with The Innocence of Father Brown, that are also short lessons in human nature.' },
      { title: 'The Man Who Was Thursday (1908)', note: 'A philosophical thriller and his best-known novel.' },
      { title: 'What’s Wrong with the World (1910) and The Outline of Sanity (1926)', note: 'The books where he sets out his views on family, property and distributism.' },
    ],
    legacy: [
      'Chesterton’s mixture of wit and serious argument has kept a wide readership. Catholic and Protestant writers cite him as a model for explaining faith to a doubtful public, and C. S. Lewis, T. S. Eliot and others commented on his influence. Societies devoted to him exist around the world, and the Church has examined the question of declaring him a saint, an effort that has met opposition because of his writings about Jews.',
      'Readers outside religion enjoy him too, for his style, for the Father Brown stories, and for the habit of finding the extraordinary in the ordinary. The “Chesterton’s fence” idea is quoted in policy debates, and distributist ideas are still discussed in debates about ownership and local economies. Any fair account of his legacy has to include both the lasting delight of his work and the criticism of what he wrote about Jews.',
    ],
  },
  {
    slug: 'hermann-hesse',
    order: 1877,
    dates: '1877 – 1962',
    place: 'Calw, Germany; Bern and Montagnola, Switzerland',
    era: '20th Century',
    tradition: 'Modern spiritual literature',
    tagline: 'A novelist of the inner journey who sent Western readers east and inward in search of themselves.',
    who: [
      'Hermann Hesse was born on 2 July 1877 in Calw, in the German state of Württemberg, into a family of Protestant missionaries. His father worked for the Basel Mission, and his mother and maternal grandfather, the scholar Hermann Gundert, had both lived in India. At fourteen he entered the Maulbronn seminary to train for the ministry, but in 1892 he ran away, and a period of deep unhappiness followed. He later worked as a bookshop apprentice in Tübingen and began to write, and his novel Peter Camenzind (1904) made him financially independent as an author.',
      'He married Maria Bernoulli in 1904, lived by Lake Constance, and in 1911 travelled to Ceylon and South-East Asia. In 1912 he moved to Switzerland. When the First World War began he volunteered for service but was judged unfit for the front, and worked on behalf of German prisoners of war. In November 1914 he published an article in a Swiss newspaper asking German writers to resist nationalist hatred, and he was attacked as a traitor in the German press. His father’s death, his son’s illness and the failure of his marriage brought a breakdown, and in 1916–17 he began psychoanalysis with Josef Bernhard Lang, a follower of C. G. Jung.',
      'In 1919 he settled in Montagnola in the Swiss canton of Ticino, where he lived for the rest of his life, painting, gardening and writing. Demian appeared in 1919 under a pseudonym, Siddhartha in 1922, Steppenwolf in 1927 and The Glass Bead Game in 1943. He took Swiss citizenship in the 1920s and won the Nobel Prize in Literature in 1946. He died in Montagnola on 9 August 1962.',
    ],
    context: [
      'Hesse wrote in the shadow of two world wars and of Germany’s collapse. Many Germans of his generation, brought up on pride in the nation and in Protestant duty, found that these supports had failed. Hesse’s books are full of people who have lost their old certainties and look for a new, more honest way of living.',
      'He was also part of a broad Western interest in Asia, psychology and mysticism in the early twentieth century. Translations of Indian and Chinese texts, the writings of Nietzsche and Dostoevsky, and the new psychoanalysis of Freud and Jung all shaped him. During the Nazi years his books were not banned outright, but he was treated as undesirable, and The Glass Bead Game had to be published in Zurich, not in Germany.',
    ],
    ideas: [
      { title: 'The journey to the self', text: 'Almost every Hesse novel follows a person who breaks away from conventional life to find who he truly is. Demian puts it as the task of becoming what one is meant to be, and it warns that this is difficult and lonely. Hesse treats the path as a duty to oneself, not a selfish indulgence.' },
      { title: 'Learning from experience, not doctrine', text: 'Siddhartha is a young Brahmin in ancient India who leaves home, lives as an ascetic, then as a merchant and lover, and finally finds peace beside a river as a ferryman. He meets the Buddha, but declines to become his follower, because he believes wisdom cannot be taught in words and must be lived. The book is a novel inspired by Indian thought, not a manual of Buddhism.' },
      { title: 'A divided self', text: 'In Steppenwolf, Harry Haller thinks of himself as half man and half wolf. Over the book he finds that he has not two natures but thousands, and that his torment comes from forcing himself into a single image. Here the influence of Jung and of psychoanalysis is clear: the person who tries to deny parts of himself becomes unhappy and often cruel.' },
      { title: 'Opposites and unity', text: 'Hesse repeatedly shows opposed forces, such as mind and body, order and wildness, and holiness and appetite, that need each other. In Narcissus and Goldmund, the thinker and the artist each long for the other’s way of life. His idea is that growth means bringing opposites together, not choosing one and rejecting the other.' },
      { title: 'Intellect that serves life', text: 'The Glass Bead Game is set in Castalia, a future community of scholars devoted to a game that links all arts and sciences. Its hero, Joseph Knecht, finally leaves because a life of pure thought has lost contact with ordinary people. The novel honours learning and warns against retreating into it.' },
    ],
    principles: [
      'Take responsibility for becoming yourself, even if it is lonely.',
      'Do not treat any single doctrine or teacher as the last word.',
      'Do not deny the parts of yourself you dislike, and learn to live with them.',
      'Let solitude and nature feed your attention.',
      'Do not let a life of the mind cut you off from other people.',
    ],
    practice: [
      'Keep a journal of dreams or moods for a few weeks, and look for the patterns you did not know you had.',
      'Spend time with a quiet task such as walking, gardening or painting, as Hesse did, and let your mind wander without a goal.',
      'Choose one part of yourself you usually hide, and ask what it is trying to tell you.',
    ],
    facts: [
      'Hesse began painting seriously in 1917 and produced many hundreds of watercolours of the Ticino landscape.',
      'Siddhartha is dedicated in part to Romain Rolland and to his cousin Wilhelm Gundert, a scholar of Japan.',
      'Demian was first published in 1919 under the name Emil Sinclair, and he revealed his authorship only later.',
      'The Nobel Committee cited his inspired writings which, while growing in boldness and penetration, exemplify classical humanitarian ideals and high qualities of style.',
      'The rock band Steppenwolf, formed in Los Angeles in 1967, took its name from his novel.',
      'He wrote thousands of letters, and after 1933 he quietly helped writers who were in difficulty under the Nazi regime.',
    ],
    myths: [
      { myth: 'Siddhartha is a biography of the Buddha, or a Buddhist scripture.', reality: 'The hero is a fictional contemporary of the Buddha, who appears as a separate character. Hesse drew on Hindu, Buddhist and also Chinese ideas and on his own life, and the book’s point is that each person must find their own way.' },
      { myth: 'Hesse was a 1960s hippie guru who promoted drugs.', reality: 'He died in 1962, before the counterculture took him up. In the mid-1960s his books, especially Siddhartha, Steppenwolf and Demian, became bestsellers among young American readers, but their quest for the self owes more to Jung and to Indian thought than to drugs. Hesse himself was a quiet, retiring man.' },
      { myth: 'He won the Nobel Prize for Siddhartha.', reality: 'The prize honoured his whole body of work. The Glass Bead Game, published only three years before, was his major recent novel, but the citation speaks of his writings as a whole.' },
    ],
    works: [
      { title: 'Demian (1919)', note: 'A coming-of-age novel shaped by Jung’s psychology, and a book that spoke to young Germans after the First World War.' },
      { title: 'Siddhartha (1922)', note: 'A short novel of a seeker in ancient India, now one of the most widely read books of the century.' },
      { title: 'Steppenwolf (1927)', note: 'A bleak and funny novel of a middle-aged outsider, ending in the Magic Theatre.' },
      { title: 'Narcissus and Goldmund (1930)', note: 'A story of friendship between a scholar-monk and an artist.' },
      { title: 'The Glass Bead Game (1943)', note: 'His last major novel, also published as Magister Ludi, written during the Second World War.' },
    ],
    legacy: [
      'After Hesse’s Nobel Prize his reputation in Germany was solid but not extraordinary. In the United States the mid-1960s brought a “Hesse boom”, when paperback translations sold in huge numbers and new readers took the books as guides to self-discovery. Millions of copies have been sold worldwide.',
      'Critics have sometimes called his work self-absorbed or sentimental, and some find his later novels too schematic. Others see him as a rare writer who made the inner life, Eastern thought and psychology accessible to ordinary readers. His pacifism in 1914, long before it was popular, and his refusal to join nationalist movements are widely respected.',
    ],
  },
  {
    slug: 'martin-buber',
    order: 1878,
    dates: '1878 – 1965',
    place: 'Vienna, Lemberg, Heppenheim and Jerusalem',
    era: '20th Century',
    tradition: 'Dialogical philosophy',
    tagline: 'A Jewish philosopher who taught that real life happens in meeting between persons.',
    who: [
      'Martin Buber was born in Vienna on 8 February 1878. After his parents separated when he was about three, he was raised in Lemberg (now Lviv, Ukraine) by his grandfather Solomon Buber, a respected scholar of Jewish texts. He grew up among Hebrew and German books and, as a boy, saw something of the Hasidic world, the pious, joyful Jewish communities of Eastern Europe, which later became a lifelong subject. He studied philosophy and art history in Vienna, Leipzig, Berlin and Zurich.',
      'From the 1890s he was involved in the Zionist movement, but as a cultural Zionist: he cared more about the spiritual and cultural renewal of Judaism than about political structures. He edited the monthly Der Jude from 1916, retold the stories of Hasidic masters, and in 1923 published Ich und Du, I and Thou, the book that made his name. In the 1920s he worked with Franz Rosenzweig on a new German translation of the Hebrew Bible, a project that took decades.',
      'He taught at the University of Frankfurt, but resigned after the Nazis came to power in 1933, and spent his later German years working in Jewish adult education until he was forbidden to speak in public. In 1938 he emigrated to Palestine and taught social philosophy at the Hebrew University of Jerusalem. He lived in Jerusalem for the rest of his life, was a voice for Arab–Jewish cooperation, travelled widely in later years, and died there on 13 June 1965.',
    ],
    context: [
      'Buber grew up when Jewish life in Europe was changing: assimilation, new nationalism, and then growing antisemitism. His interest in Hasidism came from the wish to find a living, joyful form of Jewish faith, in contrast to the dry rationalism he saw in modern Western life. At the same time European philosophy was moving from abstract systems to concrete human existence, and Buber’s thought, like that of Kierkegaard and Rosenzweig, belongs with that move.',
      'Politically he lived through the First World War, the Nazi regime, the founding of Israel in 1948, and the first years of the Arab–Israeli conflict. Buber thought the Jewish national home should be a place of justice and cooperation, and he worried that if it became just another nation-state, it would lose the moral purpose that gave it its meaning. These views kept him on the edge of the Zionist mainstream.',
    ],
    ideas: [
      { title: 'I and Thou', text: 'Buber says we can stand in two basic relations to the world. In I–It we treat something as an object to be used, measured or understood from outside. In I–Thou we meet another being, whether a person, an animal, a tree or a work of art, as a whole presence, with no aim beyond the meeting. He argues that a human being becomes a self only through such meetings, and that modern life is dangerously dominated by I–It.' },
      { title: 'Dialogue', text: 'Real dialogue, for Buber, is more than exchanging information. It means turning to the other person and responding to them as they are, and it is something that happens “between” people, not inside either of them. A genuine conversation can be silent, and it cannot be forced or planned: we can only prepare to be open to it.' },
      { title: 'The eternal Thou', text: 'Buber believed that every meeting with a particular Thou points to the eternal Thou, which is God. God is never an It, he said, and cannot be proved or described, but can be addressed in relation. His religious thought is therefore about presence and encounter, not about doctrines.' },
      { title: 'Hasidism as lived wisdom', text: 'In his retellings, collected for example in Tales of the Hasidim, Buber presented the Hasidic masters as teachers of finding holiness in everyday acts, such as eating, working and speaking. These tales are a literary reworking, and the scholar Gershom Scholem criticised him for playing down the mystical and legal sides of Hasidism. Nevertheless, they brought the movement to a wide audience.' },
      { title: 'A binational, cooperative Palestine', text: 'Buber argued that Jews and Arabs should share the land as partners, in a binational state or a federation, and that Jewish settlement should not be built on the exclusion of the Arab population. With Judah Magnes and others he helped found the Ihud group in 1942 to promote this view. It was a minority position then and became more so after 1948, and it is still debated whether it was realistic.' },
    ],
    principles: [
      'Treat other people as persons, not as tools or categories.',
      'Be fully present in conversation, and listen before replying.',
      'Do not try to use a relationship for a purpose it cannot serve.',
      'Look for the sacred in everyday work and speech.',
      'Seek a politics that includes the people you disagree with.',
    ],
    practice: [
      'In your next conversation, put away the phone and give the other person your whole attention for ten minutes, with no goal other than to listen.',
      'Notice the moments when you treat someone as a function, such as the cashier or the driver, and greet them as a person.',
      'When a conflict arises, ask what the other side needs and fears before you ask who is right.',
    ],
    facts: [
      'The title Ich und Du was published in 1923. The English translation by Ronald Gregor Smith appeared in 1937, and Walter Kaufmann made a later one in 1970.',
      'Buber was nominated many times for both the Nobel Prize in Literature and the Nobel Peace Prize, though he never won either.',
      'He received the Peace Prize of the German Book Trade in 1953, the Israel Prize in 1958, and the Erasmus Prize in 1963.',
      'On 18 April 1957 he took part in a public dialogue with the American psychologist Carl Rogers at the University of Michigan in Ann Arbor, an event that introduced his thinking to many therapists.',
      'In the Rogers dialogue Buber argued that a therapy relationship cannot be fully mutual, since the client comes for help. Rogers saw more mutuality than Buber allowed.',
      'He wrote in both German and Hebrew, and a large part of his later work was published in Hebrew.',
    ],
    myths: [
      { myth: 'I and Thou is a book about getting along with people.', reality: 'It is a short, poetic and demanding philosophical work. Its subject is the two basic ways of relating to the world, including to God, and it says that I–It is necessary and unavoidable. The danger is that I–It takes over everything.' },
      { myth: 'Buber and Gandhi simply disagreed about non-violence.', reality: 'In November 1938 Gandhi wrote an article, “The Jews”, which condemned the Nazi persecution but recommended that German Jews use non-violent resistance, satyagraha, and that Jews in Palestine seek to win over the Arabs and not rely on British protection. Buber published an open letter in 1939 saying that Gandhi misjudged the conditions of Jews under the Nazis and in Palestine, and that non-violence assumed an opponent who could be moved. Buber and Judah Magnes both wrote to Gandhi, and Gandhi did not reply to them at the time. Historians see an honest clash between two admirers of non-violence, and they still disagree about how to judge each side.' },
      { myth: 'Buber was an uncritical supporter of the state of Israel.', reality: 'He welcomed a Jewish homeland, but he opposed a purely nationalist, majority-rule state and argued for Arab–Jewish partnership. He criticised the treatment of Arab refugees after 1948 and accepted a chair at the Hebrew University while remaining an independent voice.' },
    ],
    works: [
      { title: 'I and Thou (Ich und Du, 1923)', note: 'His best-known work, setting out I–Thou and I–It.' },
      { title: 'Between Man and Man (1947)', note: 'Essays applying dialogue to education, community and ethics.' },
      { title: 'Tales of the Hasidim (1947)', note: 'A collection of Hasidic stories and sayings, retold in his own voice.' },
      { title: 'The Legend of the Baal-Shem (1908)', note: 'An early retelling that helped make Hasidism known outside Eastern Europe.' },
      { title: 'Paths in Utopia (1949) and Two Types of Faith (1950)', note: 'His books on community, society and the difference between trust and belief.' },
    ],
    legacy: [
      'Buber’s language of I–Thou and dialogue has shaped theology, education, psychotherapy and conflict resolution. Writers such as Emmanuel Levinas, Abraham Joshua Heschel, Paul Tillich and Carl Rogers all engaged with him, and the phrase “dialogue” in interfaith work owes much to his influence. Rogers’s person-centred approach and the later field of dialogue studies are among his descendants.',
      'His political views have drawn attention again in recent decades, as people ask whether a shared homeland for Jews and Arabs could have worked. Admirers see in him a rare voice of moral seriousness in a bitter conflict, while critics say his position underestimated the force of nationalism on both sides. In Jewish thought he remains a central modern figure, and for many general readers his short book on meeting is the starting point.',
    ],
  },
  {
    slug: 'kahlil-gibran',
    order: 1883,
    dates: '1883 – 1931',
    place: 'Bsharri, Lebanon; Boston and New York, USA',
    era: '20th Century',
    tradition: 'Pen League and mystic poetry',
    tagline: 'A Lebanese-American poet and painter whose short book The Prophet became one of the century’s most loved.',
    who: [
      'Gibran Khalil Gibran was born on 6 January 1883 in Bsharri, a mountain village in what was then Ottoman Mount Lebanon, into a Maronite Christian family. In 1895 his mother took him and his siblings to Boston, where they joined the city’s Syrian-Lebanese community in the South End. A teacher noticed his drawings, and the photographer and publisher Fred Holland Day introduced him to Boston’s artistic circles. As a young man he returned to Lebanon to study Arabic literature at a school in Beirut.',
      'In Boston he met Mary Haskell, a headmistress, in 1904. She became his patron, friend and editor, supporting his art studies in Paris from 1908 to 1910 and helping to polish his English prose. In 1912 he settled in New York, where he lived and worked until his death. His early works, such as the novella Broken Wings (1912), were written in Arabic, and his first English book, The Madman, appeared in 1918.',
      'In 1920 he helped found the Pen League (al-Rabita al-Qalamiyya) in New York, a group of Arab writers in America that included Mikhail Naimy. The Prophet, published by Knopf in 1923, made him famous. He followed it with Sand and Foam (1926) and Jesus, the Son of Man (1928). He died in New York on 10 April 1931 of cirrhosis of the liver and tuberculosis, and his body was taken to Lebanon and buried at the Mar Sarkis monastery in Bsharri, now the Gibran Museum.',
    ],
    context: [
      'Gibran belonged to the first big wave of emigrants from Ottoman Syria, which included what is now Lebanon, to the United States. Many of these emigrants were Christians who left because of poverty and political pressure. In America they started newspapers and literary circles, creating a new Arab-American literature, the mahjar or “emigrant” writing.',
      'The Pen League sought to renew Arabic writing by breaking the rigid forms of classical poetry, using simpler language, and giving free play to emotion and imagination. Its members, like the English Romantics and Walt Whitman, whom Gibran read, drew on nature and spiritual feeling. At the same time Gibran’s English prose took on the cadences of the King James Bible, which suited the American public’s taste for spiritual writing.',
    ],
    ideas: [
      { title: 'Love as freedom', text: 'In The Prophet, a wise man named Almustafa speaks to the people of the city of Orphalese before he leaves by ship, answering their questions on love, marriage, children, work, joy and sorrow, death and other subjects. On love he says that it both crowns and crucifies us, and on marriage he advises husband and wife to stand together yet apart, as the pillars of a temple stand apart. Love is a gift that does not own.' },
      { title: 'Children are not possessions', text: 'One of his best-loved passages says that our children are not really ours but come through us, and that we may give them love but not our thoughts, because they have their own. Parents are the bows from which children, as living arrows, are sent forth. The passage became a favourite at weddings and christenings.' },
      { title: 'Joy and sorrow are linked', text: 'Gibran writes that the same cup that holds our wine was once burned in the potter’s oven, and that sorrow carves out the space that joy later fills. He does not deny pain, but argues that it can deepen us. Your pain, he says, is the breaking of the shell that encloses your understanding.' },
      { title: 'Work as visible love', text: 'On work, Almustafa says that work is love made visible. Whatever we do, from weaving to building, should be done as if our beloved were to wear the cloth or live in the house. The idea is that dignity lies in the spirit in which an ordinary task is done.' },
      { title: 'A spirituality without borders', text: 'Gibran drew on Christianity, Sufi mysticism, Romanticism, and ideas from other faiths, but did not belong to any single church. He criticised corrupt clergy and rigid institutions, and he praised Jesus as a figure of human compassion. His teachings are gentle and non-dogmatic, and for many readers that is their attraction.' },
    ],
    principles: [
      'Love without trying to possess.',
      'Let your children be themselves.',
      'Do your work as an expression of care.',
      'Accept sorrow as part of what makes joy deep.',
      'Keep a faith open enough to learn from other traditions.',
    ],
    practice: [
      'Choose one routine task this week and do it as if you were doing it for someone you love.',
      'In a close relationship, ask where you may be holding on too tightly, and where you could leave more space.',
      'When you are in pain, write down what it may be teaching or opening up in you, without pretending that it is pleasant.',
    ],
    facts: [
      'His full name in Arabic is Jubran Khalil Jubran, and his family name appears in English with several spellings, such as Gibran and Khalil.',
      'The Prophet has been translated into more than a hundred languages, and has reportedly never been out of print since 1923.',
      'He wrote in Arabic as well as English, and his Arabic works such as Spirits Rebellious (1908) and Broken Wings are still read across the Arab world.',
      'He was also a painter and draughtsman, and made portraits of well-known people, among them, in 1912, the Bahá’í leader ʻAbdu’l-Bahá, who was visiting New York.',
      'Two further books, The Wanderer and The Garden of the Prophet, were published after his death, the second completed by his friend Barbara Young.',
      'He was elected as leader of the Pen League, and the writer Mikhail Naimy later wrote a biography of him.',
    ],
    myths: [
      { myth: 'Many of the quotations on the internet attributed to Gibran are his.', reality: 'A large number are not. “Your children are not your children” and “your pain is the breaking of the shell” are really from The Prophet. But the line “Out of suffering have emerged the strongest souls” is often credited to him and is generally traced to the American writer Edwin Hubbell Chapin, and many “travel and tell no one” style quotes have no source in his books. A good rule is to look for the passage in an actual edition.' },
      { myth: 'The long “Pity the nation” list is by Gibran.', reality: 'Gibran did write a short “pity the nation” passage in The Garden of the Prophet (1933). The much longer list that circulates widely is a poem by Lawrence Ferlinghetti, published in the 2000s, written “after Khalil Gibran” in homage.' },
      { myth: 'The Prophet was an immediate success with critics.', reality: 'Critical reception was mixed. Some reviewers found it sentimental or imitative of biblical style, and for a long time academics gave him little attention. Readers adopted it through word of mouth, and it became a best-seller anyway.' },
    ],
    works: [
      { title: 'The Prophet (1923)', note: 'His best-known work, in twenty-six prose poems of spiritual advice.' },
      { title: 'The Madman (1918)', note: 'His first English book, a collection of short parables and aphorisms.' },
      { title: 'Broken Wings (1912)', note: 'A short Arabic novel about a young man’s doomed love, important in modern Arabic literature.' },
      { title: 'Sand and Foam (1926)', note: 'A collection of aphorisms in English.' },
      { title: 'Jesus, the Son of Man (1928)', note: 'A portrait of Jesus through the voices of different people who knew him.' },
    ],
    legacy: [
      'The Prophet has sold on a very large scale, and its lines are read at weddings, funerals and graduations. The book was also popular in the 1960s counterculture. Gibran is a national symbol in Lebanon, and the Gibran Museum in Bsharri receives visitors from around the world.',
      'Scholars have sometimes been slow to place him, because he belongs to two literatures at once. In the Arab world he is valued as a pioneer of free-verse and Romantic style, and the Pen League influenced later modernist poets. In the English-speaking world he is read mainly as a popular spiritual writer. His readers often value what critics pass over, namely the plain consolation of his words.',
    ],
  },
  {
    slug: 'john-maynard-keynes',
    order: 1883,
    dates: '1883 – 1946',
    place: 'Cambridge and London, England',
    era: '20th Century',
    tradition: 'Economics',
    tagline: 'The economist who argued that governments should spend in a slump, and whose ideas shaped the postwar world.',
    who: [
      'John Maynard Keynes was born in Cambridge on 5 June 1883, the son of the economist and university administrator John Neville Keynes and of Florence Ada Keynes, who later became mayor of the city. He studied at Eton, where he won a scholarship, and at King’s College, Cambridge, where he read mathematics. He spent two years in the India Office, and then returned to Cambridge as a fellow of King’s in 1909, where he taught economics and wrote on probability and Indian currency.',
      'During the First World War he worked at the Treasury and was a financial representative at the 1919 Paris Peace Conference. He resigned from the British delegation in protest at the harsh terms for Germany and wrote The Economic Consequences of the Peace (1919), which made him famous. In 1925 he married the Russian ballerina Lydia Lopokova. He was a central figure in Bloomsbury, the circle of writers and artists around Virginia Woolf and Lytton Strachey, and he was an active speculator, an investor for King’s College and a patron of the arts.',
      'In the Great Depression he wrote his most important work, The General Theory of Employment, Interest and Money (1936). In the Second World War he advised the Treasury, wrote How to Pay for the War (1940), became a baron in 1942, and was the chief British negotiator at the Bretton Woods conference in 1944. He led the talks for a loan from the United States in late 1945. He died of a heart attack at Tilton, his Sussex home, on 21 April 1946.',
    ],
    context: [
      'Keynes lived through a period of economic crisis: the First World War and its debts, the hyperinflation in Germany, the return to the gold standard in Britain, and the Great Depression, when a quarter of workers in some countries were without jobs. The dominant economic view held that markets quickly correct themselves, so that lasting unemployment is mostly a sign of rigid wages. Keynes thought this was wrong for the world he saw.',
      'His thinking also took shape in the Cambridge of G. E. Moore and in the Bloomsbury circle, which stressed friendship, beauty and the value of states of mind. He saw economics as a means to an end: a technique for making a civilised life possible, not the goal of life itself. This outlook shows in his famous essay on the economic prospects of his grandchildren.',
    ],
    ideas: [
      { title: 'Demand drives employment', text: 'In The General Theory, Keynes argues that total spending in the economy, called aggregate demand, decides how many people are employed. If households and firms cut spending, workers lose jobs, incomes fall, and spending falls further, so the economy can settle into a slump without any natural way out. He therefore said that governments can and should act to raise demand, for example by public spending, when private spending is weak.' },
      { title: 'Uncertainty and “animal spirits”', text: 'Investors do not know the future, and Keynes argued that they cannot calculate it like a game of chance. Much investment, he wrote in the General Theory, depends on “animal spirits”, a spontaneous urge to act instead of doing nothing, and on confidence that can quickly vanish. He therefore treated booms and busts as partly psychological as well as mechanical.' },
      { title: '“In the long run we are all dead”', text: 'The phrase comes from A Tract on Monetary Reform (1923). Keynes was criticising economists who said that, in the long run, prices will adjust to changes in the money supply. He did not deny the long-run result, but said that this is too easy and useless a task if, in stormy times, economists can only say that the ocean will be flat once the storm is past. The point was to take the short run seriously, not to ignore the future.' },
      { title: 'A managed international order', text: 'At Bretton Woods in July 1944, delegates of forty-four nations met in New Hampshire to plan the postwar monetary system. Keynes proposed an international clearing union with its own currency unit, the “bancor”, to discourage countries from running large permanent surpluses. The American plan, led by Harry Dexter White, prevailed, and the conference created the International Monetary Fund and what became the World Bank.' },
      { title: 'Economics in service of a good life', text: 'In “Economic Possibilities for our Grandchildren” (1930), Keynes predicted that within a hundred years, living standards in advanced countries would be several times higher and people might need to work only about fifteen hours a week. He thought the real challenge would then be how to use leisure well. Output did grow roughly as he expected, but working hours fell far less than he predicted.' },
    ],
    principles: [
      'Do not treat a simple rule as a law of nature when circumstances change.',
      'Take the short run seriously, because people live in it.',
      'Remember that spending and saving are choices that affect everyone else.',
      'Accept that the future cannot be known and plan with humility.',
      'Treat money as a means, and ask what a good life is for.',
    ],
    practice: [
      'When a rule of thumb stops working, check what has changed in the situation instead of defending the rule.',
      'When you hear a confident forecast, ask what assumptions it relies on and what it leaves uncertain.',
      'Ask yourself what you would do with more free time or more money, and whether you are working towards that.',
    ],
    facts: [
      'He nearly lost his fortune in currency speculation in 1920 and later rebuilt it, and he helped to manage the investments of King’s College.',
      'In 1936 he bought a large number of Isaac Newton’s papers at auction, and later wrote an essay calling Newton “the last of the magicians”.',
      'He helped to found the Arts Council of Great Britain, and was chairman of its predecessor, the Council for the Encouragement of Music and the Arts.',
      'He built the Arts Theatre in Cambridge, which opened in 1936.',
      'He had relationships with men, including the painter Duncan Grant, before his marriage to Lydia Lopokova in 1925.',
      'The word “Keynesian” is used for ideas he never held in a single form, because later economists developed and changed his thinking.',
    ],
    myths: [
      { myth: '“In the long run we are all dead” means Keynes did not care about the future.', reality: 'The line is from a book on money in 1923, where he was criticising the habit of saying that things will be fine in the long run. He cared deeply about the long-term, and the grandchildren essay and his work on a postwar order show it. His point was that policy must deal with the short run.' },
      { myth: 'Keynes said “When the facts change, I change my mind. What do you do, sir?”', reality: 'The line is widely attributed to him, but a reliable source in his own writings or speeches has not been found. It is better treated as an unverified attribution, though it fits his reputation for adapting his views.' },
      { myth: 'Keynes always favoured big government deficits.', reality: 'He argued for counter-cyclical policy: spend more when the economy is weak and, in good times, restrain demand. He supported balancing the budget over the cycle and, during the Second World War, wanted taxes and compulsory saving to hold back inflation in How to Pay for the War.' },
    ],
    works: [
      { title: 'The Economic Consequences of the Peace (1919)', note: 'His attack on the Versailles reparations terms, which argued they would damage European recovery; later historians still debate how right he was.' },
      { title: 'A Tract on Monetary Reform (1923)', note: 'The book containing the “long run” remark and an argument for managing the currency.' },
      { title: 'The General Theory of Employment, Interest and Money (1936)', note: 'His main work, which founded modern macroeconomics.' },
      { title: 'Essays in Persuasion (1931)', note: 'A collection of articles, including “Economic Possibilities for our Grandchildren”.' },
      { title: 'How to Pay for the War (1940)', note: 'A wartime pamphlet on taxation, saving and inflation.' },
    ],
    legacy: [
      'After the Second World War, many governments used Keynesian ideas to guide their policy, and the postwar decades of growth and low unemployment in much of the West are often linked to that approach. The International Monetary Fund and the World Bank, established at Bretton Woods, remain central institutions. In the 1970s, stagflation, which means high inflation together with high unemployment, led to a reaction from monetarists and others, but Keynesian arguments returned in the financial crisis of 2008 and the pandemic of 2020.',
      'His record also includes involvement with eugenics, a movement that sought to improve populations by controlling who had children, and which was widely supported by educated opinion in Britain at the time. Keynes was a member of the Eugenics Society, held office in it from 1937 to 1944, gave its Galton Lecture in 1937 on population decline, and in 1946 spoke of eugenics approvingly as an important branch of sociology. Historians disagree about the meaning: some see a conventional view of his class and period, others a more serious and lasting commitment. Both his economic ideas and this part of his life belong in an honest account.',
    ],
  },
]
