import type { Profile } from './types'

export const MORE_01: Profile[] = [
  {
    slug: 'aesop',
    order: -620,
    dates: 'c. 620 – c. 564 BC (traditional)',
    place: 'Greece and Asia Minor (tradition names Samos and Delphi)',
    era: 'Ancient',
    tradition: 'Fable tradition',
    tagline: 'A half-legendary storyteller whose animal tales have taught practical wisdom for more than two thousand years.',
    who: [
      'Almost nothing about Aesop can be stated with confidence. Greek writers of the fifth and fourth centuries BC treat him as a real person from the sixth century BC. Herodotus calls him a slave on Samos who was owned by a man named Iadmon, and Aristotle mentions a speech he supposedly gave in a political trial on the island. The traditional dates of about 620 to 564 BC come from later chronology and should be treated as a rough guide, not as a record.',
      'The detailed biography is a much later invention. A popular prose work called the Life of Aesop, written probably in the first or second century AD, makes him a deformed but quick-witted slave who talks his way to freedom, advises kings and finally dies at Delphi. Tradition says the Delphians, angered by his sharp tongue, planted a sacred cup in his luggage and threw him off a cliff for theft. Herodotus does report that Delphi later paid compensation for his death, which suggests a real memory behind the story, but the vivid details belong to legend.',
      'What we call Aesop’s fables is really a tradition, not a single author’s book. Short animal stories with a point were told across the Near East and Greece long before and after him, and Greeks gave the genre his name. Writers later collected and versified the tales: Demetrius of Phalerum made a prose collection around 300 BC that is now lost, Phaedrus wrote Latin verse versions in the first century AD, and Babrius wrote Greek verse versions a little later. In practice, “Aesop” names a way of thinking that many people shared.',
    ],
    context: [
      'Fables were an old form of speech in the ancient world. Hesiod in the eighth century BC tells a short tale of a hawk and a nightingale, and the poet Archilochus used animal stories as well. Greeks used such stories in the law court and the assembly to make a point without making an accusation, and Aristotle’s handbook on rhetoric lists the fable among the tools of persuasion because it is easy to invent and easy to remember.',
      'The sixth century BC was a time of tyrants, aristocrats and slaves in the Greek world, and the powerful were rarely open to criticism. Phaedrus later says that the fable was invented by slaves who could not say what they thought and therefore hid it in stories about animals. Whether or not that is the true origin, it explains why the genre is full of the weak looking for ways to survive the strong. Socrates, waiting in prison, is said by Plato to have turned some of Aesop’s fables into verse, showing how familiar they already were in Athens.',
    ],
    ideas: [
      { title: 'Truth told at an angle', text: 'A fable lets a speaker say something unwelcome without naming anyone. When a listener sees the fox in the story, he may understand his own behaviour before he thinks to be offended. The form teaches that a lesson often lands better when people discover it for themselves, and that stories carry moral argument more effectively than lectures.' },
      { title: 'Power and its excuses', text: 'In “The Wolf and the Lamb” the wolf accuses the lamb of muddying the water, and when the lamb proves it cannot have done so, the wolf eats him anyway. The tale shows that the strong often look for reasons to do what they were going to do regardless, and that arguing with a bully on the bully’s terms may not help. Many fables are realistic about power, and some advise caution above heroism.' },
      { title: 'Self-deception and vanity', text: 'The fox who cannot reach the grapes decides they were sour anyway, and the crow who is flattered into singing loses her cheese. These stories show how pride, envy and wishful thinking lead people to talk themselves into foolish positions. They invite the listener to notice the same habits in themselves.' },
      { title: 'Prudence and steady effort', text: 'The ant stores food in summer while the grasshopper sings and is hungry in winter, and the tortoise beats the overconfident hare by never stopping. Such tales praise foresight, patience and ordinary diligence, and warn against talent that is wasted through complacency. The morals are practical and aimed at everyday life, not at heroic virtue.' },
      { title: 'The small may matter', text: 'In “The Lion and the Mouse” the little creature that the lion spared later frees the lion from a hunter’s net. The fable argues that kindness is a sensible investment and that no one is too small to be of help. It balances the harsher fables in which the strong simply win, and shows that the tradition does not offer a single worldview.' },
    ],
    principles: [
      'Do not let pride or envy write your account of events.',
      'Prepare in good times for hard ones.',
      'Be wary of flattery; ask what the flatterer wants.',
      'Slow and steady work often beats brilliant but careless effort.',
      'Treat even the small and weak with respect, since you may need them.',
    ],
    practice: [
      'When you catch yourself dismissing something as “sour grapes”, ask whether you really do not want it or only fear that you cannot have it.',
      'When you need to give difficult feedback, try telling a short story or giving an example instead of making a direct accusation, and see whether it is heard more easily.',
      'Choose one routine to do a little every day, such as saving, practising or tidying, instead of relying on bursts of enthusiasm.',
    ],
    facts: [
      'Herodotus says that Rhodopis, a courtesan in Egypt, had been a fellow slave of Aesop. This is one of the earliest pieces of evidence that he was thought of as a real person.',
      'The fable collection scholars use today is the Perry Index, compiled by Ben Edwin Perry in the twentieth century. It numbers roughly 700 fables that circulated under Aesop’s name.',
      'The tidy sentence of moral at the end of a fable (“the story shows that...”) was usually added by later editors, and the same tale can carry different morals in different collections.',
      'An influential early printed collection was made in Germany by Heinrich Steinhöwel around 1476, and William Caxton printed an English version, translated from a French adaptation, in 1484.',
      'The French poet Jean de La Fontaine retold many of the fables in verse from 1668, and his versions shaped the way later Europeans know them.',
      'Aristophanes mentions Aesop in his comedies, which shows that Athenian audiences in the fifth century BC knew his name and his tales.',
    ],
    myths: [
      { myth: 'Aesop was an ugly, hunchbacked slave who wrote the fables.', reality: 'The hunchbacked image comes from the Life of Aesop, a late and fanciful biography. Early writers say little about his appearance, and the fables are the work of a long tradition, not of one author.' },
      { myth: 'Every familiar fable, such as the Ant and the Grasshopper, goes back to Aesop himself.', reality: 'Many were added to the collection over the centuries, from Greek, Roman, Indian and medieval sources. Whether any particular tale was told by a sixth-century Aesop is usually impossible to say.' },
      { myth: 'Fables are only for children.', reality: 'In antiquity they were used by adults in politics, law, teaching and satire. Their simplicity is what let them carry sharp social criticism.' },
    ],
    works: [
      { title: 'No writings by Aesop', note: 'The tales were passed on by word of mouth for centuries before they were collected.' },
      { title: 'Phaedrus, Fables', note: 'Latin verse versions written in the first century AD, with comments on the purpose of the genre.' },
      { title: 'Babrius, Fables', note: 'Greek verse versions, probably from the second century AD.' },
      { title: 'The Life of Aesop', note: 'A late prose romance about his supposed career. It is entertaining but unreliable as history.' },
      { title: 'Herodotus, Histories, Book II', note: 'The earliest surviving mention of Aesop as a person, along with the report of the compensation paid for his death.' },
    ],
    legacy: [
      'Aesop’s fables were among the first texts that children learned to read in Greece and Rome, and they were used in schools for centuries as exercises in writing and speaking. Through medieval collections, Renaissance printings and translations into nearly every language, they became part of the shared moral vocabulary of Europe and well beyond it. Phrases such as “sour grapes” and “crying wolf” come directly from them.',
      'The fable form also gave later writers a way to say what they could not say openly. La Fontaine, Lessing, Krylov in Russia and many others used animals to comment on kings, courts and manners, and modern satire from George Orwell’s Animal Farm onward still uses the same device. The fables remain a reminder that a short story can be a serious tool for moral thinking.',
    ],
  },
  {
    slug: 'hippocrates',
    order: -460,
    dates: 'c. 460 – c. 370 BC',
    place: 'Cos, then Thessaly (Greece)',
    era: 'Ancient',
    tradition: 'Greek medicine',
    tagline: 'The Greek physician who became the symbol of medicine as careful observation, honest judgement and care for the patient.',
    who: [
      'Hippocrates was born on the island of Cos, in the eastern Aegean, around 460 BC. Later tradition says he belonged to a family of Asclepiads, a group that claimed descent from the healing god Asclepius, and that his father was a physician. He was famous enough in his lifetime for Plato to mention him twice. In the Protagoras Plato names him as a teacher of medicine who accepts pupils for a fee, and in the Phaedrus Plato mentions his view that understanding a part of nature requires understanding the whole.',
      'Beyond this, the evidence is thin. The first full biography, by Soranus, dates from the second century AD, and it is full of legend: it has Hippocrates travelling widely, treating a plague in Athens and refusing a royal Persian invitation, and these stories are not trusted by historians. Tradition says he died at Larissa in Thessaly, at a very advanced age, but the dates of his life are only approximate.',
      'Most importantly, historians now separate the man from the writings. About sixty medical works survive under his name as the Hippocratic Corpus. They were gathered in the Hellenistic period, probably in the library at Alexandria, and they are the work of many authors writing over perhaps a century or more. They differ in style, in method and sometimes in doctrine, and scholars cannot say with certainty that any single work is by Hippocrates himself. What the Corpus shows is the medicine that he came to represent.',
    ],
    context: [
      'In early Greece, illness was often thought to come from the gods, from curses or from impurity, and healing took place in temples of Asclepius as well as at the hands of folk healers. By the fifth century BC a new kind of practitioner appeared who looked for natural causes. This turn is closely linked to the Ionian philosophers and their habit of explaining nature without myth, and the physicians who wrote the Corpus were part of that intellectual movement.',
      'Medicine was also a trade in a competitive market. Doctors travelled from city to city, and they had to persuade people of their skill, to predict the course of disease accurately, and to avoid blame when patients died. Several treatises in the Corpus argue against rival ideas, and some argue against the philosophers themselves, warning that medicine should be built on experience of patients rather than on grand theories about the universe. Two main centres, Cos and Cnidus, are associated with different approaches, though how sharply they differed is debated.',
    ],
    ideas: [
      { title: 'Disease has natural causes', text: 'The treatise On the Sacred Disease deals with epilepsy, which many Greeks thought was caused by the gods. Its author argues that it is no more sacred than any other illness, that it has a cause in the body, and that people who blame divine anger are often covering their own ignorance. This stands as a landmark in the move from supernatural to natural explanation.' },
      { title: 'Careful observation and the case history', text: 'The Epidemics record cases day by day: the fever, the sleep, the colour of the urine, the outcome. The aim was to learn what usually happens in a disease, so that the physician could predict it, and the tradition of detailed, unembellished case notes is one of the great achievements of the Corpus. The Aphorisms open with the observation that life is short, the art is long, the occasion fleeting and judgement difficult.' },
      { title: 'The four humours', text: 'The treatise On the Nature of Man, which Aristotle’s testimony links to Polybus, said by tradition to be a pupil and son-in-law of Hippocrates, teaches that the body contains four humours: blood, phlegm, yellow bile and black bile. Health is a balance of them and disease an imbalance. This picture was not universal even in the Corpus, but it grew into the dominant model of medicine in Europe and the Islamic world for nearly two thousand years.' },
      { title: 'Environment and way of life', text: 'Airs, Waters, Places argues that a doctor arriving in a new town should study its climate, winds, water supply and the habits of the people, since these shape their health. Writings on regimen add diet, exercise, sleep and rest. The Corpus treats health as the result of a person’s whole way of living, and often prefers to adjust that way of living before turning to drugs or surgery.' },
      { title: 'The ethics of the physician', text: 'The Corpus gives much attention to how a physician should behave: with modesty, honesty and self-control, keeping the patient’s confidence and not taking on hopeless cases for show. The Epidemics put the aim as to help, or at least to do no harm. The famous phrase “first, do no harm” is a later Latin summary and not a quotation from the Greek.' },
    ],
    principles: [
      'Look for natural causes before supernatural ones.',
      'Observe closely and record what you see, including the failures.',
      'Treat the whole person and their way of life, not just the symptom.',
      'Help if you can; at the least, do no harm.',
      'Keep confidences, and do not oversell what you can do.',
    ],
    practice: [
      'When you are unwell or stressed, keep a short daily log for a week of sleep, food, activity and symptoms before drawing conclusions about the cause.',
      'Before making a decision about your health, ask a professional what the treatment is likely to do and what it might harm, and weigh both.',
      'In any job that involves caring for others, practise discretion and plain honesty about what you do not know.',
    ],
    facts: [
      'The Hippocratic Oath is a short pledge to Apollo and other healing gods. It includes promises to teach the art to the sons of one’s teacher, to avoid giving a deadly drug, and to keep patients’ secrets, as well as to avoid sexual relations with patients. Its date is debated, and many scholars think it was written after Hippocrates’s lifetime.',
      'The oath forbids cutting for the stone, which has been read as a sign that surgery was a separate trade in the community that produced it.',
      'Epidemics I includes a description of an outbreak on the island of Thasos that appears to be mumps.',
      'The Prognostic gives a classic description of the face of a dying patient, still known in medicine as the “Hippocratic face”.',
      'Galen, the great Roman physician of the second century AD, treated Hippocrates as the model physician and decided which works in the Corpus he considered genuine.',
      'Modern medical graduates often recite oaths, but these are usually modern texts, such as the Declaration of Geneva of 1948, not the ancient one.',
    ],
    myths: [
      { myth: 'Hippocrates said “Let food be thy medicine, and medicine be thy food.”', reality: 'No such sentence has been found in the Hippocratic writings. It is widely quoted but has no traceable ancient source, and the Corpus does discuss diet in a more complicated way.' },
      { myth: 'The Hippocratic Oath contains the words “first, do no harm.”', reality: 'The Oath does not use that phrase. The nearest ancient wording is in the Epidemics, and the Latin primum non nocere appears much later.' },
      { myth: 'Hippocrates wrote the Hippocratic Corpus.', reality: 'The Corpus is the work of many authors and several medical schools over a century or more, collected by later editors, and its treatises sometimes disagree with one another.' },
    ],
    works: [
      { title: 'On the Sacred Disease', note: 'A treatise arguing that epilepsy has natural causes and that it is the brain that is affected.' },
      { title: 'Epidemics', note: 'Case histories and notes on disease patterns across seasons and places.' },
      { title: 'Airs, Waters, Places', note: 'A study of how climate, water and way of life shape health.' },
      { title: 'Aphorisms and Prognostic', note: 'Short sayings and a guide to predicting the course of disease, both widely read for centuries.' },
      { title: 'The Oath', note: 'A short statement of professional ethics, probably later than Hippocrates himself.' },
    ],
    legacy: [
      'Through Galen, and later through Arabic and Latin translations, the Hippocratic tradition became the foundation of medicine in the Byzantine, Islamic and European worlds. The humoral theory shaped diagnosis and treatment, including bloodletting, until the nineteenth century, when new knowledge of cells and germs replaced it. More lasting than any single theory was the picture of the physician as a careful observer, which medical teaching in every age has sought to preserve.',
      'Today Hippocrates is mainly remembered for the ethics attached to his name. Codes of medical conduct, from the Oath to the Declaration of Geneva, echo the idea that the physician owes loyalty to the patient above all, including confidentiality. Scholars may doubt how much of this goes back to one man, but the picture of the doctor as a rational, humane and disciplined professional is a major gift of Greek medicine.',
    ],
  },
  {
    slug: 'xenophon',
    order: -430,
    dates: 'c. 430 – c. 354 BC',
    place: 'Athens, Persia, Scillus and Corinth',
    era: 'Ancient',
    tradition: 'Socratic writing',
    tagline: 'A soldier, exile and gifted prose writer who gave us a down-to-earth portrait of Socrates and the story of the Ten Thousand.',
    who: [
      'Xenophon was born in Athens around 430 BC to a well-off family and was a young follower of Socrates. In 401 BC, at about thirty, he left Athens to join the army of Cyrus the Younger, a Persian prince who was gathering Greek mercenaries for an expedition into the heart of the empire. Cyrus intended to seize the throne from his brother, Artaxerxes II. Xenophon went at the invitation of a friend, the Boeotian Proxenus, and not as a general.',
      'At the battle of Cunaxa, near Babylon, Cyrus was killed. The Greeks, deep in hostile territory, lost their leaders soon after, when the Persian satrap Tissaphernes seized and killed the generals under a truce. Xenophon was among the men chosen to replace them and helped to lead some ten thousand Greek soldiers on a long march north through mountains and snow to the Black Sea. He told the story in the Anabasis. Athens exiled him, probably because of his links to Cyrus and to Sparta, though the date and the exact cause are uncertain; a common view ties it to his fighting beside the Spartans at Coronea in 394 BC.',
      'After his army service he fought for Sparta under King Agesilaus, and the Spartans gave him an estate at Scillus near Olympia, where he lived for years, hunting, farming and writing. After the Spartans were defeated at Leuctra in 371 BC he moved to Corinth. Some sources say Athens lifted his exile and that his sons served in its cavalry, and one son, Gryllus, is said to have died at the battle of Mantinea in 362 BC. Xenophon died around 354 BC.',
    ],
    context: [
      'Xenophon grew up during the Peloponnesian War between Athens and Sparta, and the world he lived in was shaken by defeat, civil conflict and the rule of the Thirty Tyrants in Athens in 404 BC. Socrates, whom he admired, was executed by the restored democracy in 399 BC. Many of his pupils, including Plato and Xenophon, felt disillusioned with democratic Athens, and the question of what makes a good leader and a good community runs through Xenophon’s works.',
      'In this age of unrest, professional soldiers and mercenaries became common, and the Greek cities grew used to the idea of Persian money and power. Xenophon’s march showed that a small Greek force could survive deep inside the empire, a point that some later writers took as evidence of Persian weakness. His writing on leadership, estates and horsemanship also speaks to the aristocratic class to which he belonged.',
    ],
    ideas: [
      { title: 'Leadership as example and care', text: 'In the Anabasis Xenophon shows how a commander keeps an army together in a crisis: by sharing hardship, explaining decisions, listening to the soldiers and acting decisively. The Cyropaedia, a partly fictional account of the education of Cyrus the Great, extends this into a portrait of an ideal ruler who earns obedience through generosity and competence. Whether he fully believed in this ideal is debated, since the last chapter of that work is more critical.' },
      { title: 'A practical Socrates', text: 'In the Memorabilia, Xenophon defends Socrates against the charges of impiety and of corrupting the young and shows him as a useful, devout and self-controlled teacher. His Socrates is more interested in everyday virtue, friendship, work and self-mastery than in abstract theory, and he often gives down-to-earth advice. This is a different figure from the questioner of Plato, and historians still debate which of them is closer to the real man.' },
      { title: 'Self-control as the basis of virtue', text: 'Xenophon’s Socrates stresses enkrateia, the ability to rule one’s desires, as the foundation of freedom and friendship. A person who is mastered by appetite can neither lead others well nor be a reliable friend. The idea is simple but demanding, and later schools such as the Cynics and Stoics drew on it.' },
      { title: 'Managing a household', text: 'In the Oeconomicus, Socrates relates a conversation with a landowner called Ischomachus about running an estate and training a wife and workers. It is one of the earliest works on household management, and the source of the word “economics”. It contains a view of marriage as a partnership but also reflects the unequal assumptions of its time, which readers should keep in mind.' },
      { title: 'Learning from experience and from history', text: 'Xenophon wrote on horsemanship, hunting, cavalry command and public finance, always with a practical eye. He believed that skills come from training and that leaders should study how things actually work. His Hellenica carried the history of Greece forward from where Thucydides stopped, down to 362 BC.' },
    ],
    principles: [
      'Lead by sharing the hardships you ask others to bear.',
      'Master your own appetites before you try to govern others.',
      'Treat practical skill as a form of knowledge.',
      'Give clear reasons for orders; people follow what they understand.',
      'Choose friends who strengthen your self-discipline.',
    ],
    practice: [
      'Before asking someone to do something difficult, ask yourself whether you would do it, and say so out loud.',
      'Pick one appetite, such as scrolling, snacking or spending, and set a small rule about it for a month.',
      'When you manage a project or household, write down who is responsible for what and why, as Ischomachus does in his orderly estate.',
    ],
    facts: [
      'In the Anabasis the Greeks reach the sea after months of marching and shout “Thalatta! Thalatta!” (“The sea! The sea!”), one of the best-known moments in ancient literature.',
      'The title Anabasis means “going up” from the coast into the interior. The book describes the march up toward Babylon, which ends at Cunaxa, and the long retreat.',
      'Xenophon wrote the Anabasis in the third person, so the narrator refers to himself as “Xenophon”.',
      'He was not in Athens for the trial and death of Socrates, since he was on his Persian expedition. His account is based on others and on memory.',
      'The Roman writer Cicero says that the general Scipio Africanus (usually taken to be the younger Scipio) always had the Cyropaedia at hand, which shows how the work was read as a manual of leadership.',
      'Xenophon also wrote a dialogue called Hiero, in which a tyrant and the poet Simonides discuss the unhappiness of absolute power.',
    ],
    myths: [
      { myth: 'Xenophon gives a plain, neutral record of what Socrates said.', reality: 'The Memorabilia was written in part to defend Socrates, and Xenophon shaped the conversations to that purpose. Plato’s dialogues are also literary works. Comparing the two is an essential part of reconstructing Socrates, not a way of choosing between them.' },
      { myth: 'Xenophon saved Socrates’s life in battle.', reality: 'Diogenes Laertius tells a story that Socrates carried the fallen Xenophon from the field at Delium, but this clashes with the usual dating of Xenophon’s birth and is considered unreliable.' },
      { myth: 'Xenophon was only a soldier, not a thinker.', reality: 'He wrote on ethics, economics, politics, history and education, and his work was widely read in antiquity and in the Renaissance.' },
    ],
    works: [
      { title: 'Anabasis', note: 'The account of the expedition of Cyrus and the march of the Ten Thousand, written in a clear, plain style.' },
      { title: 'Memorabilia, Apology and Symposium', note: 'Xenophon’s portrait of Socrates, his defence speech, and a dinner-party dialogue.' },
      { title: 'Oeconomicus', note: 'A Socratic dialogue on managing a household and an estate.' },
      { title: 'Cyropaedia', note: 'A partly fictional account of the upbringing and rule of Cyrus the Great, a study of leadership.' },
      { title: 'Hellenica', note: 'A history of Greece from 411 to 362 BC, continuing the narrative of Thucydides.' },
    ],
    legacy: [
      'Xenophon’s plain Attic Greek made the Anabasis a classic for generations of students learning the language, and his works on leadership were widely read by Roman and Renaissance statesmen. Machiavelli discusses the Cyropaedia in The Prince, and later political thinkers returned to it and to the Hiero when they wrote about rulers and tyranny.',
      'In philosophy he stands beside Plato as an early witness to Socrates. His version of the man, practical, pious and moderate, gave readers throughout history a figure who could be admired without difficulty, and it influenced the Cynics and Stoics, who built on the Socratic emphasis on self-control. Modern scholars use Xenophon as a check on Plato and as evidence for the many different ways in which Socrates was remembered.',
    ],
  },
  {
    slug: 'zhuang-zhou',
    order: -369,
    dates: 'c. 369 – c. 286 BC (traditional)',
    place: 'State of Song, central China',
    era: 'Ancient',
    tradition: 'Taoism',
    tagline: 'A humorous, imaginative thinker who questioned fixed categories and taught people to move through life with ease.',
    who: [
      'Zhuangzi, whose personal name was Zhuang Zhou (莊子), came from the small state of Song in what is now central China. The only early biography is a short entry in the Records of the Grand Historian by Sima Qian, written around 100 BC, and it gives few details. It says he held a minor post, that he lived in poverty and that he declined an invitation to serve as chief minister to the king of Chu. The traditional dates, about 369 to 286 BC, come from later estimates and are uncertain.',
      'Stories in the book that bears his name show him as a poor man in patched clothes who is sharp-tongued and playful. He argues with his friend Hui Shi, a logician, about whether one can know the joy of fish, and in one passage he is said to have drummed on a tub and sung when his wife died, a story that shocked his friend and was meant to illustrate a calm view of life and death. These passages are in chapters that scholars do not think he wrote, so they may reflect later tradition more than reliable memory.',
      'The book is a composite. The Zhuangzi as we have it was edited by Guo Xiang around AD 300 into 33 chapters, from a longer earlier version. The seven Inner Chapters are usually thought to be closest to the thinker himself, and the Outer and Miscellaneous Chapters probably come from later followers and other writers. This profile therefore speaks of Zhuangzi both as a person and as the voice of the text.',
    ],
    context: [
      'Zhuangzi lived in the Warring States period (475–221 BC), when China was divided into rival states that fought one another with growing efficiency. The age was also the great time of the “hundred schools” of thought: Confucians, Mohists, Legalists and others competed to say how rulers should govern and how people should live. Many of these thinkers believed they had the right way, and they argued about it with confidence.',
      'Zhuangzi belongs to the tradition later called Taoism, or Daoism, which centres on the Dao, the way of the natural world, and often appears together with the book of Laozi, the Daodejing. His voice, however, is different: where others give instructions, Zhuangzi uses jokes, paradoxes, parables and tall tales. He doubts that any school’s way can claim final authority, including his own, and he sets his imagination against the busy certainty of his age.',
    ],
    ideas: [
      { title: 'Perspective and relativism', text: 'In the second chapter, “Discussion on Making All Things Equal”, Zhuangzi points out that every “this” is a “that” from another point of view, and that arguments about right and wrong rarely settle anything because each side starts from its own standpoint. He does not conclude that nothing matters. Instead he invites us to see how limited any single viewpoint is, and to hold our judgements more lightly.' },
      { title: 'The butterfly dream', text: 'Zhuang Zhou dreams that he is a butterfly, happy and unaware of being anyone else, and on waking he cannot tell whether he is Zhuang Zhou who dreamed of a butterfly or a butterfly now dreaming that it is Zhuang Zhou. The text says there must be some difference between the two, and it calls this the “transformation of things”. The story raises questions about identity, certainty and the boundary between dream and waking, without insisting on an answer.' },
      { title: 'Free and easy wandering', text: 'The first chapter opens with the great fish Kun that turns into the bird Peng, and with small creatures who laugh at its vast flight. The point is that happiness does not depend on size or status, and that freedom means moving through life without being tied to fixed goals or to the judgement of others. The ideal is to wander with the changes of things, depending on nothing.' },
      { title: 'The use of the useless', text: 'Hui Shi complains that Zhuangzi’s ideas are like a huge old tree whose gnarled wood is useless for timber, so that no carpenter looks at it. Zhuangzi replies that the tree escapes the axe, and that something without use can be a place to rest in its shade. The parable questions the habit of judging everything, including ourselves, by usefulness, and values safety and peace over recognition.' },
      { title: 'Skill that flows with the grain', text: 'Cook Ding cuts up an ox for a lord so smoothly that his movements seem like music. He explains that he no longer sees the whole animal but follows the natural gaps and joints, so that his knife stays sharp after nineteen years. This story presents expertise as attention and responsiveness, in which the doer adapts to the thing instead of forcing it. The same attitude applies to living: finding the openings in difficult situations without needless struggle.' },
    ],
    principles: [
      'Hold your own viewpoint with humour; others see from where they stand.',
      'Do not measure your worth only by usefulness or approval.',
      'Work with the grain of a situation instead of against it.',
      'Accept change, including death, as part of the natural course of things.',
      'Do not be captured by names and categories, or by the quarrels over them.',
    ],
    practice: [
      'In a disagreement, try to describe the other person’s position in terms that they would accept before you reply.',
      'Choose one task you do well, and give it full attention, noticing where it goes smoothly and where you are forcing it.',
      'Set aside time each week that has no goal and no productivity measure, and see what you notice.',
    ],
    facts: [
      'The Chinese name Zhuangzi (莊子) means “Master Zhuang”.',
      'According to Sima Qian, Zhuangzi refused an offer of high office from the king of Chu by comparing the post to a sacrificial ox that is pampered and then led to slaughter.',
      'In AD 742 the Tang emperor Xuanzong gave the book the title “True Scripture of Southern Florescence”, which raised it to the status of a Taoist canonical work.',
      'The Zhuangzi is famous for its imaginary characters, including cripples, cooks, butchers, wheelwrights and talking trees, who often have more insight than the rulers they meet.',
      'The Buddhist traditions that developed in China, especially Chan (Zen), drew heavily on Taoist language and ideas, and the Zhuangzi was a major source.',
      'The friendship between Zhuangzi and the logician Hui Shi is one of the most famous in Chinese literature, and the text records many of their playful arguments.',
    ],
    myths: [
      { myth: 'Zhuangzi wrote the whole book that bears his name.', reality: 'The Zhuangzi is a collection that took shape over generations. The Inner Chapters are considered the most likely to be his, and the rest come from later writers who developed or varied his ideas.' },
      { myth: 'Zhuangzi taught that nothing is true and nothing matters.', reality: 'He questions our confidence in fixed distinctions and in rigid rules, but he also praises skill, attentiveness, friendship and living in tune with the Dao. His relativism is meant to loosen dogmatism, not to end all seriousness.' },
      { myth: 'Taoism as an organised religion began with Zhuangzi.', reality: 'Organised Taoist religion arose several centuries later, in the Han dynasty and after. The Zhuangzi is a philosophical and literary text that later movements adopted.' },
    ],
    works: [
      { title: 'Zhuangzi, Inner Chapters (1–7)', note: 'The core of the book, including “Free and Easy Wandering”, “Discussion on Making All Things Equal” and the story of Cook Ding.' },
      { title: 'Zhuangzi, Outer and Miscellaneous Chapters (8–33)', note: 'Later material in several voices, including the debate with Hui Shi over the joy of fish and the story of the wife’s death.' },
      { title: 'Sima Qian, Records of the Grand Historian', note: 'The earliest biography, short and partly legendary.' },
      { title: 'Guo Xiang’s edition and commentary', note: 'The text that survives today comes from this editor of around AD 300, who also wrote an influential commentary.' },
    ],
    legacy: [
      'The Zhuangzi became one of the most admired books in Chinese culture. Poets such as Tao Yuanming and Li Bai drew on its images, painters took its landscapes and wandering figures as models, and scholars wrote commentaries on it for two thousand years. It offered a counterweight to Confucian duty, a language for people who wished to step back from public life while remaining thoughtful and cheerful.',
      'Translated into Western languages from the nineteenth century, it has been read as philosophy, as literature and as a spiritual text. Readers have compared its relativism and its attention to skilled action with ideas in modern philosophy and psychology, such as theories of flow, although such comparisons should be made cautiously. Its lasting appeal lies in how it questions certainty with humour.',
    ],
  },
  {
    slug: 'xunzi',
    order: -310,
    dates: 'c. 310 – c. 235 BC',
    place: 'States of Zhao, Qi and Chu (China)',
    era: 'Ancient',
    tradition: 'Confucianism',
    tagline: 'The Confucian who argued that people are born self-seeking and become good only through learning and ritual.',
    who: [
      'Xunzi (荀子), whose personal name was Xun Kuang, was born in the state of Zhao in northern China around 310 BC. Han-dynasty sources say that he went to the state of Qi, whose capital had a famous gathering of scholars at the Jixia Academy, and that he rose to be its most respected senior teacher. After a period of slander and rivalry he left Qi. He then went to the southern state of Chu, where the chief minister Lord Chunshen appointed him magistrate of Lanling.',
      'When Lord Chunshen was killed in 238 BC, Xunzi lost his post. He is said to have remained in Lanling, teaching and writing, until his death around 235 BC. Sources also say he visited the state of Qin, which was the strongest power of the day, and that he judged it orderly but lacking in Confucian learning, though the details of his travels are uncertain.',
      'The book that bears his name has 32 chapters, edited by the Han scholar Liu Xiang in the first century BC. Unlike many early Chinese texts, most of the chapters are essays that appear to be by a single author, which is why Xunzi is among the easiest early thinkers to follow. He saw himself as a defender of the way of Confucius and, in his own words, as a critic of other schools, including some Confucians.',
    ],
    context: [
      'Xunzi lived in the late Warring States period, when seven major states competed for dominance and Qin was moving toward the conquest that would create the first unified empire in 221 BC. Violence, shifting alliances and ambitious rulers made order the burning question. Rival thinkers offered different remedies: the Legalists favoured strict laws and rewards and punishments, the Mohists urged impartial care and frugality, and the Taoists distrusted the whole business of government.',
      'Within Confucianism, Mencius, who lived a generation or two earlier, had taught that human nature is good. Xunzi regarded this as a mistake. He wanted to keep Confucian values but to defend them against a more sceptical age, and he did so by developing a theory of how an unruly human nature could be shaped into a good one. It was a Confucianism fitted for a time of war and statecraft.',
    ],
    ideas: [
      { title: 'Human nature is bad', text: 'In his chapter on human nature, Xunzi claims that people are born with desires for profit, ease and comfort, and with envy and dislike for others, so that if people simply followed their natural tendencies they would end in conflict. “Bad” here means disorderly, not wicked. Goodness, he says, is wei: something made through conscious effort, learning and training. Its source is not in our inborn feelings but in the work we do on ourselves.' },
      { title: 'Ritual as a shaping force', text: 'The early sages, he says, saw that unregulated desires lead to strife and so created rituals and standards of right (li and yi) to guide them, just as a potter shapes clay or a carpenter straightens a warped board. Ritual gives people a shared form for mourning, music, family life and government, and trains emotions as well as actions. In his chapter on ritual, it is both a social order and a way of refining feeling.' },
      { title: 'Learning never ends', text: 'The first chapter, “Encouraging Learning”, says that learning must never stop and that indigo dye comes from the indigo plant yet is bluer than it. Through steady effort anyone, including “the person on the street”, can become like the sage kings. Xunzi’s account of the mind is that it can be made clear by being empty of prejudice, unified in purpose and still, so that it can judge accurately.' },
      { title: 'Heaven is impersonal', text: 'In “Discourse on Heaven”, Xunzi says that Heaven’s ways are constant: they do not exist for the sake of a good ruler such as Yao, nor do they disappear because of a bad one such as Jie. Floods, eclipses and rain do not respond to human virtue or vice. People must therefore attend to what they can control, farming, saving and good government. He treats sacrifices and rituals as cultural forms that express feeling, not as ways of bargaining with spirits.' },
      { title: 'Clear names and clear thinking', text: 'Xunzi cared about language and reasoning. In the chapters on rectifying names and on dispelling blindness he argues that confused terms lead to social confusion, and that every person is prone to being blinded by one favourite viewpoint. A good thinker, he holds, must keep the whole picture in view and resist partial perspectives.' },
    ],
    principles: [
      'Do not assume that good habits are natural; build them.',
      'Let form and ritual train your feelings as well as your behaviour.',
      'Keep learning to the end of life.',
      'Do not wait on Heaven or luck; take responsibility for what you can control.',
      'Beware of the one-sided view that hides everything else.',
    ],
    practice: [
      'Choose a virtue you want to strengthen, such as patience or generosity, and design a small daily routine that practises it, instead of waiting to feel it.',
      'Learn the customs, rituals or routines of a group you belong to, and ask what feelings they are meant to cultivate.',
      'When you are about to blame luck or fate for an outcome, list what was within your control and what you can change next time.',
    ],
    facts: [
      'Under the Han dynasty he was often called Sun Qing because the name Xun was avoided as the personal name of an emperor, according to the usual explanation.',
      'Two of his pupils became famous in the Legalist school: Han Fei, a prince of the state of Han whose writings influenced the Qin rulers, and Li Si, who became chief minister to the first emperor of Qin.',
      'Han Fei died in 233 BC after being imprisoned in Qin, and Li Si, who held power for years, was executed in 208 BC.',
      'The book was long overshadowed by Mencius. From the Song dynasty, Neo-Confucian scholars favoured Mencius’s optimistic view of human nature, and Xunzi was treated with suspicion for centuries.',
      'The chapter on music argues that music shapes character and brings people together, and a correct music is seen as a tool of moral education.',
      'He was appointed three times as the chief teacher, or “libationer”, at Jixia, according to Sima Qian.',
    ],
    myths: [
      { myth: 'Xunzi thought people were evil and beyond hope.', reality: 'His claim concerns raw desires, which cause conflict when unchecked. He also believed that anyone can become a sage through learning, so his view is demanding but hopeful.' },
      { myth: 'Xunzi was a Legalist, or the founder of Legalism.', reality: 'He was a Confucian who stressed moral cultivation, ritual and worthy rulers. Two pupils became Legalists, and some of his ideas about order and human nature were developed in that direction, but he did not hold their view that law and punishment alone are enough.' },
      { myth: 'He rejected Confucius and Mencius.', reality: 'He saw himself as upholding Confucius. He criticised Mencius’s theory of human nature but shared much of his Confucian outlook, including the importance of moral education and humane government.' },
    ],
    works: [
      { title: 'Xunzi (32 chapters)', note: 'The collected essays, edited by Liu Xiang. Most chapters are thought to be by Xunzi himself.' },
      { title: '“Encouraging Learning” and “Discourse on Ritual”', note: 'Two of the chapters that best show his views on self-cultivation and the purpose of ritual.' },
      { title: '“Discourse on Heaven” and “Human Nature Is Bad”', note: 'His treatments of the natural world and of the human condition.' },
      { title: 'Sima Qian, Records of the Grand Historian', note: 'A short biography that is the earliest source for his life.' },
    ],
    legacy: [
      'Xunzi’s ideas shaped Han-dynasty Confucianism, which took over his emphasis on ritual, education and institutions. His naturalistic view of Heaven also influenced later thinkers who wished to understand the world without invoking spirits. Through his pupils his thinking was bound up with the Qin state’s methods of rule, a legacy that later scholars debated with some tension.',
      'In later centuries Mencius’s position became orthodox, and Xunzi was less admired, but interest has returned in modern times. Scholars find in him a thoughtful account of how character is formed through practice and community, a defence of education and ritual, and an early example of a view of nature without divine intervention. His work keeps raising a question that remains important: how do people become good if goodness is not simply there from the start?',
    ],
  },
]
