import type { Profile } from './types'

export const MORE_08: Profile[] = [
  {
    slug: 'sor-juana-ines-de-la-cruz',
    order: 1648,
    dates: '1648 or 1651 – 1695',
    place: 'San Miguel Nepantla and Mexico City, New Spain (now Mexico)',
    era: 'Early Modern',
    tradition: 'Baroque literature and thought',
    tagline: 'A nun who built one of the great libraries of her age, wrote the finest poetry of the Spanish-speaking Baroque, and defended a woman’s right to study.',
    who: [
      'Juana Ramírez de Asbaje was born in the village of San Miguel Nepantla, near Mexico City, in New Spain, as the Spanish colony in Mexico was called. Her birth year is disputed: one baptismal record points to 1648 and another to 1651, and scholars still argue over which refers to her. She was the child of an unmarried couple, and she grew up on her grandfather’s farm. In her own later account she says that she learned to read at about the age of three and that, as a small girl, she begged to be sent to the university dressed as a boy.',
      'As a teenager she joined the viceregal court in Mexico City as a lady-in-waiting, where her learning drew attention. An early biographer reports that the viceroy had her questioned by a panel of scholars, and that she passed with ease. In 1667 she briefly entered a Carmelite convent and in 1669 she joined the Hieronymite (Order of St Jerome) convent, where she took the name Sor Juana Inés de la Cruz. In her own words she did it because she had a strong dislike of marriage and wanted the freedom to study.',
      'In her cell she gathered a library said to hold thousands of volumes, along with musical and scientific instruments, and she wrote plays, poems, songs and learned treatises. She entertained visitors, including the viceroys and their wives, and was warmly supported by the Countess of Paredes, the viceroy’s wife, who helped to bring her poems into print in Spain. Her fame spread across the Spanish world, which was unusual for a woman and unprecedented for a nun in the colonies.',
    ],
    context: [
      'New Spain in the later seventeenth century was a wealthy, hierarchical colony governed from Madrid, with a viceroy at its head and the Catholic Church deeply woven into daily life. Spanish, Indigenous, African and mixed communities lived together under strict legal and social ranks, and a woman’s options were largely limited to marriage or the convent. The convent was, in practice, one of the few places where a woman could read, write and own books, though it was always under the supervision of male clergy.',
      'Spain’s Baroque literature was at its height. The style prized wit, elaborate imagery, paradox and learned allusion, and Sor Juana excelled in it. She read the classics, the Church Fathers, Renaissance humanists and the new science, and she wrote in Spanish, Latin and, in some of her carols, passages in Nahuatl, the language of the Aztecs. The Church of her time valued learning, but it was suspicious of women who taught or spoke on theology.',
    ],
    ideas: [
      { title: 'A woman’s right to learn', text: 'In her Response to Sor Filotea of 1691 she argued that women have minds equal to men’s and the right to study and to teach other women. She cited a long list of learned women from the Bible, antiquity and history, and she said that a woman’s reason is as much a gift of God as a man’s. The text is often read as one of the earliest arguments for women’s education in the Americas.' },
      { title: 'Knowledge as one connected whole', text: 'In the same Response she says that every subject she studied helped her to understand the others, and that theology cannot be properly grasped without the arts and sciences. She wrote, half-joking, that one can philosophise while cooking, because the same laws of nature are at work in the kitchen. For her, learning was not a rival to faith but its tool.' },
      { title: 'The mind’s ascent in the First Dream', text: 'Her long philosophical poem Primero sueño (First Dream, probably written in the 1680s) describes a soul that rises while the body sleeps and tries to grasp the whole universe in a single act. It fails, and then tries to understand things one by one, stage by stage, until dawn returns. She said it was the only work she wrote purely for her own pleasure. The poem is about the limits and the ambition of human knowledge.' },
      { title: 'The double standard exposed', text: 'Her best-known poem, beginning “Hombres necios que acusáis” (“Foolish men who accuse women”), points out that men blame women for the very behaviour they invite. She uses wit and logic rather than anger, showing how a social habit can contradict itself. It is still read widely in Spanish-speaking schools.' },
      { title: 'Debate with a famous preacher', text: 'Her Carta atenagórica (1690) criticised a famous sermon by the Portuguese Jesuit António Vieira on what Christ’s greatest act of love was, offering a different answer. She wrote it at the request of Manuel Fernández de Santa Cruz, Bishop of Puebla, who printed it without her knowledge. It was a theological argument by a woman, and it was received with both admiration and alarm.' },
    ],
    principles: [
      'Study widely, because every field throws light on the others.',
      'Use reason and wit, not rage, to expose injustice.',
      'Treat the mind as a gift that deserves cultivation, whoever has it.',
      'Be honest about how far your knowledge reaches, and keep reaching anyway.',
      'Defend your right to think in the language your time allows, and then stretch it.',
    ],
    practice: [
      'When you study one subject, deliberately look for what it explains in a different one, and write down the link.',
      'When someone criticises you for a trait they approve of in others, restate the criticism as a question and see whether it still stands.',
      'Keep one project that you do only because you love it, as she did with Primero sueño.',
    ],
    facts: [
      'In her own account she cut off several inches of her hair as a penalty whenever she failed to learn a lesson she had set herself in time, because she thought a head should not be dressed with hair if it were empty of knowledge.',
      'She wrote comedies, a religious play called El divino Narciso, and carols (villancicos), some including words in Nahuatl and in the speech of Africans in the colony.',
      'The Response to Sor Filotea is dated 1 March 1691, but it was not printed until 1700, after her death, in a volume of her posthumous works.',
      'Her portrait appears on the Mexican 200-peso banknote.',
      'Her first collection, Inundación castálida, was published in Madrid in 1689.',
      'She died on 17 April 1695, during an epidemic in Mexico City, after caring for sick sisters in her convent.',
    ],
    myths: [
      { myth: 'She became a nun because of a failed love affair.', reality: 'This is a later romantic story. Her own statement is that she chose the convent because she disliked marriage and wanted to keep studying, and that it seemed the least unsuitable choice open to her.' },
      { myth: 'The Inquisition tried her and forced her to give up writing.', reality: 'There is no record of an Inquisition trial. She faced pressure from Church authorities, and in 1694 she signed penitential documents and her library was sold. Whether this was a forced silencing or a deep spiritual turn is debated by scholars.' },
      { myth: 'She was a secular rebel against the Church.', reality: 'She was a devout nun who argued from inside the faith. Her defence of learning depended on religious arguments.' },
    ],
    works: [
      { title: 'Primero sueño (First Dream)', note: 'Her long philosophical poem on the soul’s attempt to understand the universe.' },
      { title: 'Respuesta a Sor Filotea de la Cruz (Response to Sor Filotea, 1691)', note: 'Part autobiography, part defence of women’s learning.' },
      { title: 'Carta atenagórica (1690)', note: 'Her critique of Vieira’s sermon, printed by the Bishop of Puebla.' },
      { title: 'Inundación castálida (1689) and later volumes', note: 'Collections of her poems, plays and carols, published in Spain.' },
      { title: 'Fama y obras póstumas (1700)', note: 'A posthumous collection which includes her Response and an early biography by Diego Calleja.' },
    ],
    legacy: [
      'Her fame faded for a time after her death, but in the twentieth century she was rediscovered, above all by the Mexican poet Octavio Paz, whose 1982 study Sor Juana, or The Traps of Faith brought her to a wide public. Feminist scholars read her as an early voice for women’s education, while others stress her baroque art and her place in colonial Catholic culture. Both views rest on real evidence, and the tension between them is part of what keeps her interesting.',
      'Today she is a national figure in Mexico and a classic of Spanish-language literature. The mystery of her last years, in which she gave up public writing and sold her library, remains an open question, with some scholars seeing coercion and others seeing a choice made under severe pressure and for religious reasons. What is clear is that she left behind some of the most brilliant writing of the colonial Americas and a clear argument that the mind has no sex.',
    ],
  },
  {
    slug: 'giambattista-vico',
    order: 1668,
    dates: '1668 – 1744',
    place: 'Naples, Kingdom of Naples (now Italy)',
    era: 'Early Modern',
    tradition: 'Philosophy of history',
    tagline: 'An overlooked Neapolitan professor who argued that we can truly know only what humans have made, and that history is the greatest human work of all.',
    who: [
      'Giambattista Vico was born in Naples in 1668, the son of a bookseller. At the age of seven he fell from a ladder and fractured his skull, and in his later autobiography he said that the injury and the slow recovery shaped his serious, melancholy temperament. School disappointed him, and he became largely self-taught, studying law, philosophy and the classics on his own.',
      'For about nine years he worked as a tutor in the remote village of Vatolla, south of Naples, where he had access to a good library. In 1699 he won the chair of rhetoric at the University of Naples, a modest and badly paid post that he held until ill health forced him to retire in 1741. He tried for the more senior chair in law in 1723 and failed, which was a lasting disappointment. In the mid-1730s he was appointed royal historiographer by the new Bourbon king, a title with a small salary.',
      'He spent his life in Naples, writing in Italian and Latin, with little recognition and many money worries. His major work, the Scienza nuova (New Science), appeared in 1725, was largely rewritten in 1730, and was reworked again in a third edition just after his death in January 1744. During his life he was admired by a small circle at best, and his work was often found obscure.',
    ],
    context: [
      'Vico wrote in the shadow of René Descartes, whose method of doubt and mathematical certainty dominated educated opinion in the late seventeenth century. Descartes treated mathematics and natural science as the models for real knowledge, and tended to regard history, languages and poetry as unreliable. Vico, trained as a teacher of rhetoric and steeped in Roman law, thought this was a serious mistake.',
      'Naples was part of the Spanish and then the Austrian empire before it passed to the Bourbons in 1734. It had a lively intellectual life, a strong legal culture and a long tradition of studying Roman antiquity and Renaissance humanism. Vico remained a believing Catholic, and his work took for granted that divine Providence works through human history, while insisting that its details are the work of human beings.',
    ],
    ideas: [
      { title: 'We know what we make (verum factum)', text: 'In an early work of 1710 he stated the principle that the true and the made are interchangeable: we can have real knowledge of what we have made. Mathematics is certain because humans construct its objects. God alone knows nature through and through because God made it, but humans can know the human world, with its laws, languages and institutions, because humans made that.' },
      { title: 'A new science of history', text: 'In the New Science he proposed a systematic study of how nations arise and develop. He wanted to find the common pattern behind law, language, religion and custom across peoples, combining philosophy, which looks for reasoned truth, with philology, which examines what people actually said and did.' },
      { title: 'Three ages, and returns', text: 'He described each nation as passing through an age of gods, an age of heroes and an age of men, each with its own religion, law, language and kind of mind. After the age of men, he said, a society may fall into a “barbarism of reflection”, in which cleverness and self-interest wear down shared values, and then begin the course again (ricorso). The pattern is not an exact repetition, and Vico believed in progress within each cycle.' },
      { title: 'Imagination and myth come first', text: 'He argued that the earliest humans did not reason in abstract terms. They thought in images and stories, and made their gods out of fear of thunder and other natural forces. Myth is therefore not a mistake to be dismissed but the first form of human understanding, and it deserves to be read as a source of real information about early societies.' },
      { title: 'Against the limits of method', text: 'Vico accepted that Descartes’s method suits geometry, but he doubted that it should rule the whole of education. He valued common sense, judgement, rhetoric and imagination as things that clear analysis cannot replace, and he feared that a purely critical education leaves young people without wisdom.' },
    ],
    principles: [
      'Study the human world from the inside, as something people made and can understand.',
      'Read myths and old stories as evidence about how people once thought.',
      'Keep common sense and imagination alive alongside logic.',
      'Do not judge past societies only by the standards of your own.',
      'Remember that clever, self-interested societies can lose the shared values that hold them together.',
    ],
    practice: [
      'When you meet an institution or custom that seems irrational, ask what problem the people who made it were solving.',
      'Read one old myth or folk story and ask what it shows about the fears and hopes of its time.',
      'In an argument, ask whether you have been using logic alone where judgement and shared understanding are also needed.',
    ],
    facts: [
      'His autobiography, written in the third person, is among the earliest intellectual autobiographies in Europe.',
      'The New Science was published first in 1725, again in a heavily changed edition in 1730, and in a third edition in 1744, shortly after his death.',
      'He taught rhetoric at the University of Naples for over four decades, and his poorly paid post forced him to tutor privately to support his large family.',
      'Goethe, visiting Naples in 1787, learned about Vico through the jurist Gaetano Filangieri, and noted his impression of the work in his Italian Journey.',
      'Jules Michelet published a partial French translation of the New Science in 1827, which helped to bring Vico to wider notice.',
      'The Irish writer Samuel Beckett wrote in 1929 about the debt that James Joyce’s Finnegans Wake owes to Vico’s cycles.',
    ],
    myths: [
      { myth: 'Vico taught that history simply repeats itself.', reality: 'The ricorso is a return to similar conditions, not a copy. Each cycle comes after the one before and carries the memory of it, and Vico believed that Providence guides the whole.' },
      { myth: 'Vico was an early Marxist or secular historicist.', reality: 'Later thinkers such as Marx admired his insistence that humans make their own history, but Vico himself was a devout Catholic who believed in Providence, and modern readers have recast him in their own terms.' },
    ],
    works: [
      { title: 'The New Science (Scienza nuova, 1725, 1730, 1744)', note: 'His major work, presenting the common nature of nations.' },
      { title: 'On the Most Ancient Wisdom of the Italians (1710)', note: 'First statement of the verum factum principle.' },
      { title: 'On the Study Methods of Our Time (1709)', note: 'An inaugural lecture arguing for a rounded education against a purely Cartesian one.' },
      { title: 'Autobiography (written from 1725 to 1728)', note: 'An account of his education and the making of his thought.' },
    ],
    legacy: [
      'Vico was largely unknown outside Naples in his lifetime, and he was only slowly rediscovered. In the nineteenth century, Michelet in France, and thinkers in Germany and Italy, took him up as a forerunner of the historical approach to human affairs. Herder and Hegel are often compared with him, though how far they knew his work directly is debated. Marx praised him for pointing out that people make their own history, and Benedetto Croce and R. G. Collingwood made him a central figure in the philosophy of history.',
      'In the twentieth century he found new readers among literary and social thinkers. Joyce built Finnegans Wake partly on a Viconian cycle, Erich Auerbach drew on his ideas about language and imagination, and Isaiah Berlin presented him as a founder of the idea that different cultures should be understood in their own terms. His claim that the humanities offer a kind of knowledge distinct from natural science is still a live question.',
    ],
  },
  {
    slug: 'george-berkeley',
    order: 1685,
    dates: '1685 – 1753',
    place: 'Dublin, Rhode Island and Cloyne, Ireland',
    era: 'Early Modern',
    tradition: 'Idealism',
    tagline: 'An Irish bishop who argued that the world is made of minds and their ideas, and that this is just common sense properly understood.',
    who: [
      'George Berkeley was born in 1685 at Dysart Castle, near Thomastown in County Kilkenny, Ireland, into an English Protestant family of modest means. He studied at Kilkenny College and then at Trinity College Dublin, where he became a fellow in 1707. While still in his twenties he published An Essay towards a New Theory of Vision (1709), the Treatise concerning the Principles of Human Knowledge (1710) and the Three Dialogues between Hylas and Philonous (1713).',
      'He was ordained in the Church of Ireland and spent years travelling in Europe and working in London. He became obsessed with a plan to found a college in Bermuda to train clergy and missionaries for the colonies and for the education of Native Americans. He gained a royal charter and a parliamentary promise of money, and in 1728 he sailed for America with his new wife Anne, settling in Rhode Island in 1729. The promised funds never came, and he returned home in 1731. While there he bought several enslaved Africans to work the farm and did not oppose slavery, though he urged that enslaved people be baptised.',
      'In 1734 he became Bishop of Cloyne, in County Cork, where he lived for nearly two decades, working for the poor of his diocese and writing on economics and medicine. He promoted tar-water as a medicine, in a book called Siris (1744). In 1752 he moved to Oxford to be near his son, and he died there on 14 January 1753.',
    ],
    context: [
      'Berkeley wrote after John Locke and Isaac Newton. Locke had argued that we know the world through ideas in our minds, and that these ideas come from a material world made of invisible particles. Newton’s physics seemed to confirm that matter is real and governs everything. Berkeley saw a danger: that this view left a gap between our ideas and the real things, which might lead to scepticism, and also to atheism.',
      'He was a clergyman writing in a period of rising philosophical doubt about religion. He wanted to protect common sense and Christian belief against sceptics and freethinkers, and he did it by an unexpected route, by rejecting the assumption that matter exists apart from any mind.',
    ],
    ideas: [
      { title: 'Immaterialism', text: 'Berkeley held that everything we perceive consists of ideas, and that ideas can exist only in a mind. Nothing exists that is not a mind or an idea in a mind. He denied the existence of “matter” as an unperceived substance behind appearances. He did not deny that tables and trees exist: for him, they are collections of ideas, such as colour, shape and touch, that we really do perceive.' },
      { title: '“To be is to be perceived”', text: 'The Latin phrase esse est percipi sums up his position about the things we sense: their existence consists in being perceived. Minds themselves, which do the perceiving, are not ideas, and are active. The principle is mostly a claim about what it means to say a thing exists.' },
      { title: 'God sustains the world', text: 'If things exist only when perceived, one might worry that they vanish when nobody is looking. Berkeley answered that an infinite mind, God, perceives everything at all times, and that this is also why our sense experience is orderly and not under our control. The regularities of nature are the language through which God speaks to us.' },
      { title: 'Against abstract ideas', text: 'He criticised Locke’s view that we can form general abstract ideas, such as a triangle that is neither right-angled nor oblique nor any particular size. Berkeley argued that general words work by letting one particular idea stand for many similar ones. This attack on abstraction runs through his philosophy.' },
      { title: 'How we see distance', text: 'In his Essay on vision he argued that we do not see distance directly. We learn to connect visual cues with the experience of touch and movement. The idea shaped later psychology and the discussion of how experience shapes perception.' },
    ],
    principles: [
      'Test big theories against ordinary experience.',
      'Be suspicious of abstract words that seem to name something we cannot actually imagine.',
      'Ask what a claim means in terms of experience before arguing about whether it is true.',
      'Combine speculation with care for the practical needs of the people around you.',
      'Argue in plain language and keep dialogue and objection in view.',
    ],
    practice: [
      'When a debate rests on an abstract term, ask what concrete experience would count as an example of it.',
      'Notice how much of what you take as “seen” is learned association, and try describing a familiar scene purely in terms of what you sense.',
      'When you propose a large plan, write down in advance what resources must really arrive for it to work, since Berkeley’s Bermuda college failed for want of promised money.',
    ],
    facts: [
      'The city of Berkeley in California and the University of California, Berkeley are named after him, after a line in his poem about the arts moving westward: “Westward the course of empire takes its way.”',
      'In 1733 he gave his Rhode Island farm and a large gift of books to Yale College, and the gift helped to build up the collection there.',
      'His book The Analyst (1734) attacked the logical foundations of Newton’s calculus, mocking infinitesimals as “ghosts of departed quantities”. Mathematicians in the next century made the foundations rigorous.',
      'His economics pamphlet The Querist (1735–37) is written entirely as a series of questions.',
      'The Three Dialogues feature Hylas, whose name comes from the Greek word for matter, and Philonous, “lover of mind”.',
      'Samuel Johnson’s famous “refutation” took place in 1763, as recorded by his friend James Boswell: Johnson kicked a large stone and said “I refute it thus”.',
    ],
    myths: [
      { myth: 'Berkeley taught that the world is an illusion and that things vanish when nobody looks.', reality: 'He insisted that ordinary things are real and that he was defending common sense. For him they are real because they are perceived, ultimately by God, and because they follow the stable order that sensation shows.' },
      { myth: 'Kicking a stone refuted him.', reality: 'Johnson’s stone hurt his foot, but Berkeley never denied that we feel a hard resistance. For Berkeley that feeling is itself an idea of touch. The kick therefore does not touch his claim, which is about what lies behind such experiences.' },
      { myth: 'He wrote the saying “If a tree falls in a forest and no one hears it, does it make a sound?”', reality: 'That puzzle does not appear in Berkeley’s writings. It is a later popular riff on his ideas.' },
    ],
    works: [
      { title: 'A Treatise concerning the Principles of Human Knowledge (1710)', note: 'His main statement of immaterialism.' },
      { title: 'Three Dialogues between Hylas and Philonous (1713)', note: 'A lively, readable presentation of the same ideas in dialogue form.' },
      { title: 'An Essay towards a New Theory of Vision (1709)', note: 'His account of how sight and touch combine.' },
      { title: 'Alciphron (1732) and The Analyst (1734)', note: 'Works of religious apology and a criticism of the foundations of calculus.' },
      { title: 'Siris (1744)', note: 'A mixture of advice on tar-water and philosophical reflections, widely read in its day.' },
    ],
    legacy: [
      'Berkeley was the middle figure of the British empiricists, between Locke and Hume. Hume took many of his arguments about abstraction and perception further, in directions Berkeley would not have accepted. Kant’s critical philosophy was in part a response to idealism of this kind, and Berkeley’s analysis of what we actually perceive shaped later phenomenalism, including the work of Ernst Mach and Bertrand Russell.',
      'He is often remembered through the stone and the tree, but he is also an important figure in the history of mathematics, economics and the philosophy of perception. His claim that we can only meaningfully speak of what can be experienced echoes in modern discussions of realism and meaning. Many philosophers reject his conclusion, but his arguments remain among the hardest to answer cleanly.',
    ],
  },
  {
    slug: 'gotthold-ephraim-lessing',
    order: 1729,
    dates: '1729 – 1781',
    place: 'Leipzig, Berlin, Hamburg and Wolfenbüttel, Germany',
    era: 'Enlightenment',
    tradition: 'German Enlightenment',
    tagline: 'A playwright, critic and theologian who made tolerance a matter for the stage and treated the search for truth as worth more than its possession.',
    who: [
      'Gotthold Ephraim Lessing was born in 1729 in Kamenz, in Saxony, the son of a Lutheran pastor. He studied theology and medicine in Leipzig, but he was drawn to the theatre and to writing, and moved to Berlin to live by his pen. He worked as a critic and translator and published plays, among them Miss Sara Sampson (1755), a pioneering German tragedy about ordinary middle-class people. He became close friends with the Jewish philosopher Moses Mendelssohn.',
      'After a period in Breslau as secretary to a Prussian general, he returned to the theatre with Minna von Barnhelm (1767), a comedy set just after the Seven Years’ War that is still staged in Germany. In 1767 he went to Hamburg to help to run a new National Theatre. The theatre failed within about two years, but his reviews of its productions grew into the Hamburg Dramaturgy, a landmark of dramatic criticism.',
      'From 1770 he lived as librarian at the ducal library in Wolfenbüttel. He married Eva König, a widow, in 1776, but she died in January 1778 after the birth of their son, who did not survive. In his last years he became embroiled in a bitter theological quarrel. He died in Braunschweig on 15 February 1781, aged 52.',
    ],
    context: [
      'Germany in Lessing’s time was a patchwork of small states, with no national capital and little of a national theatre. German literature was often thought inferior to French, and German courts imitated French taste. Lessing was one of the writers who changed this, arguing that German drama should find its own course.',
      'Religious debate was also intense. The Lutheran churches defended the authority of the Bible, while Enlightenment critics asked how far reason could judge revelation. Jews faced legal restrictions and prejudice, and Lessing’s friendship with Mendelssohn, who was both a leading philosopher and a Jew, was exceptional for its time. Censorship was real, and Lessing at one point was forbidden by his duke to publish on religion without approval.',
    ],
    ideas: [
      { title: 'Nathan the Wise and the ring parable', text: 'His last play, Nathan the Wise (1779), is set in Jerusalem at the time of the Crusades. A Jewish merchant, Nathan, is asked by the Muslim ruler Saladin which religion is true. He answers with the parable of three rings, adapted from older tales including one in Boccaccio’s Decameron. A father leaves three identical rings to three sons, and a judge advises them each to prove their ring’s power by their conduct. The play makes the case for tolerance, though how far it treats the religions as equal is debated.' },
      { title: 'The limits of the arts (Laocoon)', text: 'In Laocoon (1766) he argued that painting and sculpture work in space and show bodies at one moment, while poetry works in time and tells actions that unfold. Each art does best by respecting its own medium. He used it to question the view of the critic Winckelmann, who read the calm face of the famous Laocoon statue as a sign of Greek restraint.' },
      { title: 'A new idea of drama', text: 'In the Hamburg Dramaturgy (1767–69) he criticised the rigid rules of French classical tragedy and reread Aristotle’s Poetics to argue that tragedy should move the audience to pity and fear. He praised Shakespeare as closer in spirit to the Greeks. He also defended plays about ordinary people.' },
      { title: 'The Education of the Human Race', text: 'In this short work of 100 numbered paragraphs (published in full in 1780), he proposed that revelation works on humanity much as education works on a child: God gives what people are ready to receive, step by step. Religion would eventually be understood by reason. He ends with a daring speculation about souls living more than once.' },
      { title: 'The search matters more than the possession', text: 'In a reply to a Hamburg pastor in 1778 he wrote that if God offered him the whole truth in one hand and the endless striving for truth in the other, he would choose the striving. He also insisted that accidental historical facts can never prove necessary truths of reason, a gap he called a “broad, ugly ditch”.' },
    ],
    principles: [
      'Test each religion and each idea by what it does to the way people live.',
      'Value the honest search for truth over the comfort of certainty.',
      'Let each art form do what only it can do.',
      'Defend those whom prejudice excludes.',
      'Disagree in the open, with arguments, and stay friends with those you argue with.',
    ],
    practice: [
      'When you disagree on a deep question, ask what difference each side’s view makes to how a person should act.',
      'Read a view you reject in its strongest form before replying to it.',
      'Value friendships with people whose beliefs differ from yours, as Lessing valued Mendelssohn.',
    ],
    facts: [
      'He wrote one of the first German plays to portray Jews sympathetically, Die Juden (The Jews), in 1749.',
      'He had Moses Mendelssohn in mind, according to tradition, when he created Nathan.',
      'Nathan the Wise was not performed until 1783, two years after his death.',
      'He published fragments by Hermann Samuel Reimarus, a Hamburg scholar, that questioned the historical basis of the Bible. The fragments caused a storm, and Hauptpastor Johann Melchior Goeze led the attack against Lessing.',
      'In 1778 his duke forbade him to publish on religious subjects without approval. He answered, he said, by returning to his old pulpit, the theatre.',
      'He was a Freemason and wrote dialogues on Freemasonry, Ernst and Falk, as a reflection on the ideals of humanity beyond sects.',
    ],
    myths: [
      { myth: 'Nathan the Wise teaches that all religions are equally true.', reality: 'The ring parable leaves open which ring is real, and the judge’s advice is to show the ring’s power by gentleness and good deeds. Readers have drawn different conclusions, from equality of religions to a challenge to each to prove itself by conduct.' },
      { myth: 'Lessing was a confirmed Spinozist or atheist.', reality: 'The claim rests mainly on Jacobi’s report of a private conversation in 1780, published after Lessing’s death. Mendelssohn disputed it and Lessing’s own writings leave the matter uncertain.' },
    ],
    works: [
      { title: 'Nathan the Wise (1779)', note: 'A play of ideas on tolerance and religion, in blank verse.' },
      { title: 'Laocoon (1766)', note: 'An essay on the limits of painting and poetry.' },
      { title: 'Hamburg Dramaturgy (1767–69)', note: 'Critical essays on the plays staged at the Hamburg theatre, and on the theory of drama.' },
      { title: 'The Education of the Human Race (1780)', note: 'A short, influential essay on revelation and progress.' },
      { title: 'Minna von Barnhelm (1767) and Emilia Galotti (1772)', note: 'His best-known comedy and tragedy.' },
    ],
    legacy: [
      'The Pantheismusstreit (pantheism controversy) began soon after his death. In 1785 Friedrich Heinrich Jacobi published an account of a conversation in July 1780, in which Lessing was said to have declared that he knew no philosophy but Spinoza’s, summed up as “one and all”. Moses Mendelssohn defended his late friend against the charge, and the quarrel made Spinoza a respectable subject among German thinkers. It shaped Herder, Goethe, Schelling and Hegel, and in this way Lessing helped to open the road to German idealism.',
      'In the theatre, Lessing was a founder of modern German drama and criticism. Nathan the Wise became a central play of German culture. It was banned under the Nazi regime and was among the plays that German theatres revived after 1945 as a statement of tolerance. The play remains a standard reference in debates about coexistence among religions.',
    ],
  },
  {
    slug: 'cesare-beccaria',
    order: 1738,
    dates: '1738 – 1794',
    place: 'Milan, Duchy of Milan (Austrian Lombardy, now Italy)',
    era: 'Enlightenment',
    tradition: 'Penal reform',
    tagline: 'A young Milanese nobleman whose short book argued that punishment should be certain, moderate and humane, and helped to change how Europe thought about crime.',
    who: [
      'Cesare Bonesana, Marquis of Beccaria, was born in Milan on 15 March 1738 into an aristocratic family. He was educated by Jesuits in Parma and studied law at the University of Pavia, graduating in 1758. As a young man he had little taste for the law and was restless in his family’s house, and in 1761 he married Teresa Blasco against his father’s wishes.',
      'In Milan he was drawn into a circle of young reformers led by Pietro Verri and his brother Alessandro, known as the Accademia dei Pugni (Academy of Fists). They read the French philosophes and Montesquieu, Helvétius and Hume, and they published a periodical, Il Caffè (1764–66). Pietro Verri encouraged Beccaria to write on criminal justice, and Alessandro, who worked as protector of prisoners, supplied him with knowledge of how prisons and courts actually worked.',
      'The result was On Crimes and Punishments (Dei delitti e delle pene), published anonymously in 1764 when Beccaria was 26. It was a success across Europe. Beccaria visited Paris in 1766 but left early, homesick and uncomfortable in the limelight. He later became a professor of public economy in Milan and a public official in the Austrian administration, and he died in Milan on 28 November 1794. His daughter Giulia was the mother of the novelist Alessandro Manzoni.',
    ],
    context: [
      'In most of Europe criminal law was harsh and arbitrary. Trials could be secret, judges had wide discretion, penalties were often brutal and varied by social rank, and torture was a normal way of getting confessions. Capital punishment was applied to many offences, including theft. Reformers such as Montesquieu and Voltaire had already criticised parts of the system.',
      'Milan was part of the Austrian Habsburg domains. Under Maria Theresa and her son Joseph II, Lombardy’s administration was being modernised, which gave Enlightenment-minded officials an opening. Beccaria’s book did not appear in a vacuum: it was the work of a reform circle that knew its readers and its government well, and it arrived at a moment when many rulers were open to change.',
    ],
    ideas: [
      { title: 'Punishment serves the public, not revenge', text: 'Beccaria used the idea of a social contract to say that people give up a part of their liberty to the state only to keep the rest secure. Punishment is justified only to the extent that it prevents harm, by deterring the offender and others. It should not be a form of vengeance or a display of cruelty.' },
      { title: 'Certainty beats severity', text: 'He argued that what deters crime is not the harshness of a penalty but the certainty and promptness with which it follows. A moderate punishment that is sure and swift works better than a terrible one that is often avoided. He added that it is better to prevent crimes than to punish them, and that good laws and education do this.' },
      { title: 'Against torture', text: 'He called torture both cruel and irrational. A person cannot be called guilty before a judge has found them guilty, so they cannot be treated as guilty during the inquiry. Torture, he said, favours the strong and punishes the weak, since a hardy criminal may endure it while an innocent but fragile person confesses.' },
      { title: 'Against the death penalty', text: 'Beccaria doubted that individuals ever gave the state a right to take their lives, and he doubted that executions deter better than lasting imprisonment at hard labour, which keeps the example before the public. He allowed rare exceptions, such as a person whose existence threatens the security of the nation, for example in a time of anarchy. Critics have noted that his alternative of lasting forced labour was itself severe.' },
      { title: 'Proportion, clarity and fair trial', text: 'Penalties should match the seriousness of the crime, the laws should be written clearly and published, judges should apply the law and not make it, and trials should be open and based on proof. He also objected to secret accusations and to the confiscation of an offender’s property, which punishes the family.' },
    ],
    principles: [
      'Punish to prevent harm, not to gratify anger.',
      'Make the rules clear, public and the same for everyone.',
      'A certain consequence is stronger than a cruel one.',
      'Presume innocence until guilt is proven.',
      'Prevent wrongdoing through education and good laws, not only through punishment.',
    ],
    practice: [
      'When you set rules at home, work or school, make the consequences clear in advance and apply them consistently, instead of occasionally and harshly.',
      'When you feel the urge to punish, ask whether the response will prevent a repeat of the harm or only relieve your anger.',
      'When you read about a crime or a legal dispute, wait for the full facts and notice how a rush to judgement distorts fairness.',
    ],
    facts: [
      'The book was published anonymously, because the author feared the reaction of Church and state. It was placed on the Catholic Church’s Index of Prohibited Books in 1766.',
      'Voltaire wrote a Commentary on the book in 1766, and the French translation by the abbé André Morellet was widely read, though Morellet rearranged the order of the text freely.',
      'Catherine the Great of Russia drew on Beccaria in her 1767 Instruction for a new law code, and she invited him to Russia, though he did not go.',
      'Tuscany under Grand Duke Leopold issued a penal code in 1786 that abolished the death penalty and torture, and it is often described as among the first modern states to do so.',
      'John Adams quoted the book in 1770 when defending the British soldiers tried after the Boston Massacre, and Thomas Jefferson copied passages into his notebook and cited Beccaria in a Virginia bill to reform punishments.',
      'Jeremy Bentham praised him warmly, and Beccaria’s phrase about the greatest happiness divided among the greatest number is a forerunner of Bentham’s utilitarianism.',
    ],
    myths: [
      { myth: 'Beccaria was the first person to oppose torture and the death penalty.', reality: 'Others had criticised both before him. His achievement was to bring the arguments together in a short, forceful and widely read book, at a time when rulers were ready to listen.' },
      { myth: 'He demanded the abolition of capital punishment in every case.', reality: 'He argued against it in normal circumstances, but allowed it in exceptional cases, such as a threat to the nation’s security. Later campaigners went further than he did.' },
      { myth: 'He was a lawyer or judge who wrote from experience.', reality: 'He was a young aristocrat and later an economist and official. The legal detail came largely from the Verri brothers and from his reading.' },
    ],
    works: [
      { title: 'On Crimes and Punishments (Dei delitti e delle pene, 1764)', note: 'His one famous work, expanded in later editions.' },
      { title: 'Il Caffè (1764–66)', note: 'The periodical of the Milanese reformers, to which he contributed.' },
      { title: 'Voltaire, Commentary on the Book On Crimes and Punishments (1766)', note: 'Voltaire’s response, which helped to spread Beccaria’s fame.' },
      { title: 'Elements of Public Economy (published 1804)', note: 'His lectures on economics, published after his death.' },
    ],
    legacy: [
      'Beccaria’s influence on legal reform was large. Torture was ended in many European states during the next decades, Tuscany’s code of 1786 followed his lines, and Austria’s Joseph II issued a reforming criminal code in 1787. The idea that penalties should be proportionate, written down and open to public scrutiny, and that the accused have rights, became part of the basic structure of modern criminal law.',
      'Across the Atlantic, the American founders knew the book well. It was cited in debates over the Bill of Rights and its ban on cruel and unusual punishments, though scholars differ on how directly it shaped them. Today, campaigns against the death penalty and against torture often claim him as a forerunner, and the Milan Enlightenment he belonged to is remembered as a model of reform from within.',
    ],
  },
]
