import type { Profile } from './types'

export const MORE_15: Profile[] = [
  {
    slug: 'george-santayana',
    order: 1863,
    dates: '1863 – 1952',
    place: 'Madrid, Boston and Cambridge (Massachusetts), later Rome',
    era: '20th Century',
    tradition: 'Naturalism',
    tagline: 'A Spanish-born Harvard philosopher who doubted everything he could not live without, and who wrote about the life of the mind as a poet would.',
    who: [
      'Jorge Agustín Nicolás Ruiz de Santayana y Borrás, who became George Santayana, was born in Madrid on 16 December 1863. His mother had moved to Boston in 1869 to be with the children of her first marriage, and he joined her there in 1872, at the age of eight. He grew up speaking Spanish at home and English at school, attended the Boston Latin School and then Harvard, where he graduated in 1886. After two years of study in Berlin he returned to Harvard and taught philosophy there from 1889 to 1912.',
      'At Harvard he worked beside William James and Josiah Royce, in what is often called the golden age of American philosophy, and his students included T. S. Eliot, Robert Frost, Gertrude Stein, W. E. B. Du Bois and Walter Lippmann. He published poetry and criticism as well as philosophy, and the five volumes of The Life of Reason (1905–06) made his name. Yet he never felt at home in New England. He kept his Spanish citizenship all his life, and he later described himself as a spectator of American life, not a member of it.',
      'In 1912, after his mother’s death left him a modest inheritance, he resigned his chair and left America for good. He lived in Paris, Oxford and elsewhere, then settled in Rome, where he wintered from about 1920 and where he remained, even through the Second World War. His last years were spent in a nursing home run by Catholic nuns, and he died in Rome on 26 September 1952. His memoir Persons and Places and his novel The Last Puritan (1935), which became an unexpected bestseller, show how well he wrote when he stopped writing like a professor.',
    ],
    context: [
      'Santayana taught in the America of the Gilded Age, where philosophy was split between a fading religious idealism inherited from New England and the new, practical philosophy of pragmatism. In a 1911 lecture he described the older cultural inheritance as the “genteel tradition”: a set of polite moral and religious ideas that had become detached from the energetic, commercial life actually lived by most Americans. He saw both sides clearly and belonged fully to neither.',
      'His later career unfolded in a Europe shaken by the First World War and then by fascism. He lived in Italy under Mussolini, and he disliked political enthusiasm of every kind, which he thought of as one more illusion. His response was not to take sides but to withdraw into a philosophy of calm, contemplation and a clear-eyed acceptance of what nature will and will not allow.',
    ],
    ideas: [
      { title: 'Naturalism: mind grows out of matter', text: 'Santayana held that everything real is part of nature and that the mind is a product of living bodies, not a separate substance. He called himself a materialist in that sense, though he was never a crude one. Consciousness, he thought, is a fragile and beautiful by-product of matter, and philosophy should say so without either lamenting it or pretending otherwise.' },
      { title: 'Animal faith', text: 'In Scepticism and Animal Faith (1923) he pushed doubt as far as it will go. Strictly, he argued, we can be certain only of what is directly present to the mind, and reason alone cannot prove that an outside world, other people or even a past exists. Yet we all act as if they do, because of a natural, bodily trust he called animal faith. His point was that this trust needs no proof and is no weakness: it is how a living creature faces its surroundings.' },
      { title: 'Essences', text: 'An essence, for Santayana, is any quality or form that can appear to the mind, such as a particular shade of red, a triangle or the character of Hamlet, taken just as it appears. Essences do not exist as things and do not change, though we meet them in changing things. Poets, mathematicians and mystics deal with them directly, and this gave him a way of defending art and imagination without claiming that they describe the world.' },
      { title: 'The realms of being', text: 'In his later system, the four volumes of Realms of Being (1927–40), he sorted what there is into four kinds: essence, matter, truth and spirit. Matter is the active stuff of the world, and spirit is the light of awareness that matter occasionally produces. Truth is simply the complete description of what has happened, whether or not anyone knows it.' },
      { title: 'Reason, religion and the ideal life', text: 'In The Life of Reason he described how human beings gradually bring order to their instincts through common sense, society, religion, art and science. He treated religion as poetry that carries moral truth and not as a report on supernatural facts, a view that made him an outsider to believers and unbelievers alike. The best life, he thought, is one in which impulses are harmonised and then enjoyed with a certain detachment.' },
    ],
    principles: [
      'Doubt honestly, and then live: you cannot prove everything, and you do not have to.',
      'Progress depends on remembering what we have learned.',
      'Treat religion and art as ways of understanding human life, even when you do not take them literally.',
      'Value contemplation: some of the best things in life are simply seen and enjoyed.',
      'Keep a spectator’s distance from fashions and crowds.',
    ],
    practice: [
      'When a belief feels certain, ask whether it is a proven fact or an everyday trust you simply cannot do without, and treat the two differently.',
      'Keep a record of lessons learned the hard way, and read it before repeating a familiar mistake.',
      'Spend some time each day just looking at something, a face, a landscape or a piece of music, without trying to use it.',
    ],
    facts: [
      'Santayana never became an American citizen and kept a Spanish passport throughout his life. He is buried in the Spanish pantheon in the Campo Verano cemetery in Rome.',
      'He left Harvard at the age of 48 and never returned to teach, though he lived another forty years.',
      'The five volumes of The Life of Reason were published within two years, in 1905–06, as one large, planned work.',
      'He never married, and he was a lifelong writer of poems and sonnets as well as philosophy.',
      'Among his Harvard students were the poets T. S. Eliot and Robert Frost, as well as W. E. B. Du Bois and Gertrude Stein.',
      'His novel The Last Puritan, begun long before, appeared in 1935 and became a bestseller, to the surprise of its seventy-one-year-old author.',
    ],
    myths: [
      { myth: '“Those who cannot remember the past are condemned to repeat it” is a warning that history repeats itself, or a general rule that studying history prevents disaster.', reality: 'The line comes from Reason in Common Sense (1905), the first volume of The Life of Reason. It appears in a passage arguing that progress depends on retentiveness: a person or a culture that does not keep its experience stays like a child, and cannot improve. It is about learning and memory in general, not about wars or politics, and it is usually misquoted with “doomed” in place of “condemned”.' },
      { myth: '“Only the dead have seen the end of war” was said by Plato.', reality: 'The sentence is Santayana’s own, from the essay “Tipperary” in Soliloquies in England (1922), and it has been wrongly credited to Plato for decades. No such line is known in Plato.' },
      { myth: 'Santayana was an American philosopher who simply happened to be born in Spain.', reality: 'He spent forty years in America, but he remained a Spanish citizen and thought of himself as an outsider there. His English prose is among the finest of any philosopher, yet he kept his distance from American philosophy and eventually from America itself.' },
    ],
    works: [
      { title: 'The Life of Reason (1905–06)', note: 'Five volumes: Reason in Common Sense, in Society, in Religion, in Art and in Science. The source of his best-known line.' },
      { title: 'Scepticism and Animal Faith (1923)', note: 'His most important work of philosophy, and the introduction to his later system.' },
      { title: 'Realms of Being (1927–40)', note: 'Four volumes presenting the system: essence, matter, truth and spirit.' },
      { title: 'The Last Puritan (1935)', note: 'A novel, subtitled “A Memoir in the Form of a Novel”, about the decline of New England culture.' },
      { title: 'Persons and Places (1944–53)', note: 'His memoir, in three volumes, and the best guide to his own account of his life.' },
    ],
    legacy: [
      'Santayana’s influence is oddly divided. Philosophers in the pragmatist and analytic traditions have often passed him by, while poets, critics and readers who care about style have kept him in print. His account of animal faith anticipated later discussions about what we can know without proof, and his naturalism was an important early statement of a view that many scientists and philosophers now share.',
      'He is also remembered as a writer of aphorisms, and one of them, the line about remembering the past, has become one of the most quoted sentences in the English language. That fame is a little ironic, since it has been repeated so often without its context that it has come to be used for almost any argument about history.',
    ],
  },
  {
    slug: 'miguel-de-unamuno',
    order: 1864,
    dates: '1864 – 1936',
    place: 'Bilbao and Salamanca, Spain',
    era: '20th Century',
    tradition: 'Existentialist forerunner',
    tagline: 'A Basque professor, novelist and poet who made doubt, death and the hunger for immortality the centre of philosophy.',
    who: [
      'Miguel de Unamuno was born in Bilbao, in the Basque Country, on 29 September 1864. He studied in Madrid, where he took a doctorate in philosophy and letters, and in 1891 he won the chair of Greek at the University of Salamanca. He married Concepción Lizárraga, and they had a large family. In 1897 he went through a deep religious crisis, which he later said shaped everything he wrote: he could not believe like a simple believer, and he could not stop wanting to.',
      'In 1900 he became rector (the head) of the University of Salamanca, and he held the post until 1914, when the government removed him. His writing in those years included essays, poems and novels, among them Niebla (“Mist”, 1914), and the long essay The Tragic Sense of Life, published in 1912–13. An outspoken critic of the monarchy, he was banished in 1924 to the island of Fuerteventura by the dictator Primo de Rivera, and escaped to France, where he lived in Paris and then in Hendaye on the border until 1930.',
      'He returned to Spain in 1930, and was greeted by cheering crowds, and he again served as rector of Salamanca in the Second Republic. When the Civil War began in July 1936, he at first welcomed the military uprising as a way to restore order, but he became troubled by the killing around him. The Republican government removed him as rector on 22 August 1936, and the Nationalist authorities removed him again in October, after the confrontation in the university described below. He died in Salamanca on 31 December 1936.',
    ],
    context: [
      'Unamuno belongs to a group of Spanish writers loosely called the Generation of ’98, named after 1898, when Spain lost Cuba, Puerto Rico and the Philippines in a war with the United States. The defeat set off a long debate about what Spain was and what had gone wrong with it. Writers such as Azorín, Pío Baroja, Antonio Machado and Ramón del Valle-Inclán are usually counted in the group, though scholars debate whether it was ever a real movement, and whether Unamuno, who disliked such labels, belongs to it.',
      'The Spain of his lifetime was a country torn between tradition and modernisation, between the Church and its critics, and between centralism and regional identity. Unamuno took the side of none of them for long. He was a liberal who distrusted the Left’s materialism, a believer who distrusted the Church’s certainty and a Basque who was impatient with Basque nationalism, and the contradictions were his material, not a problem he tried to solve.',
    ],
    ideas: [
      { title: 'The tragic sense of life', text: 'In his best-known essay Unamuno argued that human beings are caught between two things: the demand of reason, which says that we die and that is the end, and the hunger of the heart, which cannot accept it. Neither can defeat the other. He did not offer a solution but asked us to live honestly in the conflict, and called that struggle “agony”, in the original sense of a contest.' },
      { title: 'The man of flesh and bone', text: 'Philosophy, Unamuno complained, is usually written as if about an abstract “Man”. He insisted on the real person who is born, suffers, loves and dies, and held that every philosopher’s system is really an expression of his own longing and fear. A philosophy, in his view, should be judged by how it deals with death.' },
      { title: 'Faith as struggle', text: 'For Unamuno, faith is not a settled possession but a restless striving, joined with doubt. He admired Don Quixote, the knight who lives by an ideal that the world does not confirm, and wrote a long commentary on the book. He thought a person who has never doubted has probably never believed anything seriously.' },
      { title: 'Intrahistory', text: 'In his early essays on Spain he distinguished the visible events of history from what he called intrahistoria: the quiet, unrecorded daily life of ordinary people, which he thought carries a nation on through changes of government and battles. The idea shifted attention from kings and generals to the anonymous many.' },
      { title: 'Fiction that questions its author', text: 'In Niebla the hero, Augusto Pérez, learns that he is a character and visits his author, Unamuno himself, who tells him that he will have to die. Unamuno called such books nivolas, to avoid the word novel. They raise a question his philosophy also asks: who is real, and who gives anyone the right to say so?' },
    ],
    principles: [
      'Do not escape the great questions through busy routine or comfortable answers.',
      'Respect real people before systems and abstractions.',
      'Hold doubt and hope together without forcing a quick resolution.',
      'Speak out even when it is costly, and when you are not sure of the outcome.',
      'Be wary of every cause that demands the surrender of thought.',
    ],
    practice: [
      'When you disagree with a view you hold dear, write down the best case against it, and see whether you can live with both.',
      'Ask of any grand theory: what does it say to a person who is grieving, or who is afraid of dying?',
      'Make room for the ordinary, unrecorded life around you, the work and care that never make the news, and treat it as seriously as the headlines.',
    ],
    facts: [
      'He was professor of Greek at Salamanca from 1891, and rector there twice, with dismissals in 1914, in August 1936 by the Republican government and in October 1936 by the Nationalist authorities.',
      'After the Spanish dictator Primo de Rivera banished him to Fuerteventura in 1924, he escaped by boat to France, where he lived until the dictator fell.',
      'On 12 October 1936, the “Day of the Race”, he took part in a ceremony at the University of Salamanca with, among others, the Nationalist General José Millán-Astray, the bishop and Franco’s wife. The event is remembered for a clash between Unamuno and Millán-Astray, but accounts of what was said differ, as explained below.',
      'He was dismissed as rector in the same month and kept under house arrest, and died at home on 31 December 1936.',
      'He wrote a long commentary, The Life of Don Quixote and Sancho (1905), which treated the novel as a kind of sacred book.',
    ],
    myths: [
      { myth: 'Unamuno stood up in October 1936 and made a famous speech ending “You will win, but you will not convince”, and Millán-Astray shouted “Death to intelligence!”', reality: 'This version comes mainly from accounts published after the war, notably by Luis Portillo in 1941 and later by the historian Hugh Thomas. No full record of the exchange survives. Researchers such as Severiano Delgado have argued that the dramatic speech was embellished or even invented, and that the quarrel was a sharper, shorter exchange sparked by a speaker’s insults against Catalans and Basques. What seems certain is that Unamuno and Millán-Astray clashed, that Unamuno was soon dismissed, and that he lived under house arrest until his death.' },
      { myth: 'Unamuno was a consistent opponent of Franco’s side.', reality: 'He had at first welcomed the military uprising, hoping it would end disorder, and only turned against it as the violence grew. His disillusionment was real but gradual, and he distrusted the Republic too.' },
      { myth: 'He is simply the “existentialist” of Spanish thought.', reality: 'Unamuno lived before the movement had a name, and he did not belong to any school. He is better called a forerunner: his stress on individual existence, anguish and faith anticipated themes later developed by existentialists, but he wrote as an essayist and poet, not a systematic philosopher.' },
    ],
    works: [
      { title: 'The Tragic Sense of Life (1912–13)', note: 'His major philosophical essay on death, faith and the hunger for immortality.' },
      { title: 'Niebla (Mist, 1914)', note: 'The best-known of his nivolas, and a landmark of experimental fiction in Spanish.' },
      { title: 'Abel Sánchez (1917)', note: 'A novel retelling the story of Cain and Abel as a study of envy.' },
      { title: 'San Manuel Bueno, mártir', note: 'Written around 1930, a short novel about a village priest who has lost his faith and hides it to protect his flock.' },
      { title: 'The Life of Don Quixote and Sancho (1905)', note: 'A personal commentary on Cervantes.' },
    ],
    legacy: [
      'Unamuno influenced Spanish and Latin American writers, and his thinking about death and individual existence was read alongside Kierkegaard’s and later alongside the existentialists. Many later writers took up his example, and playful experiments in fiction, where characters argue with their authors, owe much to Niebla.',
      'In Spain his name stands for a stubborn independence of mind. People on the Left and the Right have both claimed him, which suits a man who belonged to neither. The disputed scene in Salamanca in 1936 has become part of the story that Spaniards tell about the role of intellectuals in a time of war, which is a reason to read the sources on it carefully.',
    ],
  },
  {
    slug: 'max-weber',
    order: 1864,
    dates: '1864 – 1920',
    place: 'Erfurt, Berlin, Freiburg, Heidelberg and Munich, Germany',
    era: '20th Century',
    tradition: 'Sociology',
    tagline: 'The German scholar who asked how religion, bureaucracy and power shaped the modern world, and who warned about what it costs.',
    who: [
      'Max Weber was born in Erfurt, Prussia, on 21 April 1864, and grew up in Berlin in a wealthy, politically connected family. He studied law, history and economics, and in 1894 became a professor of economics at Freiburg, moving two years later to Heidelberg. In 1893 he had married his distant cousin Marianne, who later edited much of his work and wrote his biography.',
      'In 1897 he quarrelled bitterly with his father over the way the older man treated Weber’s mother, and his father died soon afterwards, with the quarrel unresolved. Weber then suffered a severe breakdown, with exhaustion, sleeplessness and depression, and for several years he could hardly teach. He spent time in sanatoriums and travelled in Italy, and he gave up his professorship in 1903. He gradually returned to scholarship, and in 1904–05 published the essay that made him famous, The Protestant Ethic and the Spirit of Capitalism.',
      'After the First World War he taught again, at Vienna and then Munich, and took part in public life, helping to found the liberal German Democratic Party and advising on the constitution of the Weimar Republic. He also criticised the Treaty of Versailles as unfair in blaming Germany alone. In 1919 he delivered two famous lectures, Science as a Vocation and Politics as a Vocation. He died in Munich on 14 June 1920, of pneumonia, possibly connected to the influenza pandemic, leaving his largest work, Economy and Society, unfinished.',
    ],
    context: [
      'Weber lived in the new German Empire, which was industrialising at great speed. Cities grew, factories and state offices multiplied, and traditional ways of life were giving way to rules, contracts and expert administration. He wanted to understand how this world had arisen, and why it arose in the West and not elsewhere. Thinkers such as Marx, Nietzsche and the historical economists of Germany were his constant partners in argument.',
      'The war and the revolution of 1918 changed the setting. Germany became a republic, and Weber, long a nationalist who had worried about German power, now worried about how a democracy could be led. His political writings from these years are among the most debated of his work: he favoured strong parliaments and strong leaders who win public support, and some later historians have asked whether this left democracy too exposed, while others reject any simple line from his views to what followed.',
    ],
    ideas: [
      { title: 'The Protestant ethic', text: 'Weber argued that some forms of Protestantism, especially Calvinism, encouraged a disciplined, work-centred way of life, in which success was valued as a sign of a person’s calling. Over time, he suggested, this attitude lost its religious roots and helped produce the rational, profit-seeking “spirit” of modern capitalism. He did not claim that religion alone caused capitalism, and historians have argued about the evidence ever since.' },
      { title: 'Three types of legitimate authority', text: 'Why do people obey? Weber distinguished three grounds. Traditional authority rests on custom, as with a hereditary king. Charismatic authority rests on the extraordinary personal qualities attributed to a leader. Legal-rational authority rests on rules and offices, as in a modern state. Real systems usually mix them, but the scheme remains one of the most used tools in political science.' },
      { title: 'Bureaucracy and the “iron cage”', text: 'Weber saw bureaucracy, rule by trained officials following written rules, as the most efficient form of organisation yet devised, and also as a threat. He feared that modern life would become a routine of rules and specialisation, which the 1930 English translation of The Protestant Ethic called an “iron cage”. A more literal rendering of his German is “a shell as hard as steel”, and scholars still debate how gloomy he meant it to be.' },
      { title: 'The state and legitimate violence', text: 'In Politics as a Vocation he defined the state as the human community that successfully claims the monopoly of the legitimate use of physical force within a given territory. The point was not that the state is the only one who uses force, but that only it is recognised as entitled to. He then asked what it takes, morally, to practise politics, which he described as slowly boring through hard boards with passion and judgment.' },
      { title: 'Disenchantment and value freedom', text: 'Weber said that modern life is marked by disenchantment, the loss of belief in magical and religious explanations, as science and calculation replace them. He also argued that scientists should keep their value judgments out of their research and not hide them: a professor can show what means will reach an end, but cannot prove which ends are right. This idea is known as value freedom.' },
    ],
    principles: [
      'Understand how people see their own actions before judging them.',
      'Separate facts from the values you bring to them, and be open about both.',
      'Ask what makes authority legitimate: custom, a leader’s appeal, or rules.',
      'Combine passion, a sense of responsibility and a sense of proportion in public life.',
      'Be wary of efficiency that forgets the people it serves.',
    ],
    practice: [
      'When you follow an instruction at work, ask on what basis the person giving it has authority, and whether you accept it.',
      'When you read a study or a news story, ask what values or interests the author brings, and what has been assumed.',
      'Notice where rules and procedures serve a purpose in your life, and where they have become a habit that no one questions.',
    ],
    facts: [
      'He and his wife Marianne were both scholars, and she edited and published Economy and Society and his other unfinished works after his death.',
      'Weber travelled to the United States in 1904 and visited the St. Louis world’s fair, and his impressions of American life fed into his later writing on religion and capitalism.',
      'He helped found the German Sociological Society in 1909, though he later resigned from it.',
      'His Politics as a Vocation lecture was given in Munich on 28 January 1919, in the revolutionary winter after the war.',
      'The first English translation of The Protestant Ethic, by the American sociologist Talcott Parsons in 1930, introduced the phrase “iron cage” to English readers.',
      'After 1903 he worked mostly as a private scholar in Heidelberg, with no university post until 1918, supported partly by a family inheritance.',
    ],
    myths: [
      { myth: 'Weber argued that Protestantism caused capitalism.', reality: 'His claim was narrower: that certain Protestant beliefs about vocation and discipline fitted with, and encouraged, a particular economic attitude. He studied other world religions to compare, and he never said religion was the only cause. His thesis has also been challenged on historical grounds, which is part of why it remains a live debate.' },
      { myth: 'Weber’s “iron cage” is his own phrase and a settled statement of despair.', reality: 'The English phrase comes from Parsons’s translation. The German is closer to “shell as hard as steel”, and the metaphor’s exact meaning is argued over. Weber was certainly worried about the loss of freedom in a rationalised society, but he also admired the efficiency and fairness that rules can bring.' },
      { myth: 'The state’s monopoly on violence means that the state alone may use force.', reality: 'Weber’s point is about legitimacy. Force may be used by others, but only so far as the state allows or permits. The definition is meant to explain what is distinctive about the modern state, and not to justify any particular use of force.' },
    ],
    works: [
      { title: 'The Protestant Ethic and the Spirit of Capitalism (1904–05)', note: 'His most famous essay, first published in a journal in two parts.' },
      { title: 'Science as a Vocation and Politics as a Vocation (1917–19)', note: 'Two lectures given in Munich on the duties of the scholar and of the politician.' },
      { title: 'Economy and Society (1921–22)', note: 'His great unfinished work, assembled by his widow, containing the types of authority and the theory of bureaucracy.' },
      { title: 'The Methodology of the Social Sciences', note: 'Essays on objectivity and value freedom, including the ideal type.' },
      { title: 'Collected Essays on the Sociology of Religion (1920–21)', note: 'Comparative studies of the economic ethics of the world religions.' },
    ],
    legacy: [
      'Along with Émile Durkheim and Karl Marx, Weber is counted among the founders of modern sociology. His concepts, such as legitimate authority, charisma, bureaucracy, the ideal type and the Protestant ethic, are used in many fields, from politics and management to religion and economic history. Thinkers of the later twentieth century, including Talcott Parsons, the Frankfurt School and Michel Foucault, all engaged with him, sometimes critically.',
      'His thesis on Protestantism is still debated and has been criticised on both historical and economic grounds, and his views on leadership and the nation have been judged differently by different scholars. Much of his lasting appeal lies not in settled conclusions but in his questions about how rationality and meaning relate in modern life.',
    ],
  },
  {
    slug: 'emma-goldman',
    order: 1869,
    dates: '1869 – 1940',
    place: 'Kaunas (Lithuania), New York, Moscow, Barcelona and Toronto',
    era: '20th Century',
    tradition: 'Anarchist feminism',
    tagline: 'An immigrant agitator who fought for free speech, free love and the freedom of the individual against every kind of state.',
    who: [
      'Emma Goldman was born in Kaunas (then Kovno), in the Russian Empire, on 27 June 1869, into a Jewish family. She grew up in Königsberg and St Petersburg, and at 16 went to the United States, where she worked in a clothing factory in Rochester, New York. The hanging of the Haymarket anarchists in Chicago in 1887 pushed her toward anarchism, and in 1889 she moved to New York City, where she met Alexander Berkman, who became her closest friend and companion in the movement.',
      'She became a famous public speaker, lecturing across the United States on anarchism, workers’ rights, women’s freedom, birth control and the arts. In 1892 Berkman shot and stabbed the industrialist Henry Clay Frick during the Homestead steel strike; Goldman was arrested but not convicted. In 1893 she was sentenced to a year in prison for “inciting to riot” after a speech to unemployed workers in New York. In 1906 she founded the magazine Mother Earth, which she edited until 1917, and she later spent time in jail for distributing birth-control information.',
      'In 1917 she and Berkman were convicted of conspiring to obstruct the military draft and each served two years in prison. In December 1919, in the post-war Red Scare, they were deported to Russia on a ship that newspapers called the “Soviet Ark”. She was at first hopeful about the Bolshevik Revolution but, after the crushing of the Kronstadt rebellion in 1921, left Russia and wrote My Disillusionment in Russia. She lived in Europe and Canada for the rest of her life, supported the anarchists in the Spanish Civil War, and died in Toronto on 14 May 1940.',
    ],
    context: [
      'Goldman’s America was an industrial country of enormous wealth and brutal labour conflicts, from the Haymarket affair of 1886 to the Homestead strike of 1892. Hundreds of thousands of immigrants from Europe poured into its cities, and anarchist and socialist movements grew among them. The state and many newspapers regarded anarchists as dangerous, and after the assassination of President McKinley in 1901 by Leon Czolgosz, who said he had been moved by hearing her speak, anarchists were hunted and new laws were passed to exclude them.',
      'The First World War and the Russian Revolution of 1917 sharpened the conflict. The American government prosecuted opponents of the war and the draft, and in 1919 launched raids against radicals and deported hundreds of foreign-born activists. Goldman’s deportation belongs to this period, and her later hostility to Soviet communism came out of her first-hand experience of the system she had hoped would free people.',
    ],
    ideas: [
      { title: 'Anarchism as freedom from authority', text: 'Goldman held that the state, the church and capital each limit the free development of the individual. She did not think freedom would arrive by seizing the state, but by people building voluntary, cooperative ways of living. Her book Anarchism and Other Essays (1910) set out these views for general readers.' },
      { title: 'Women’s freedom, beyond the vote', text: 'She supported women’s equality, but doubted that winning the vote alone would liberate women, and she criticised the narrowness of the suffrage movement. She argued for women’s economic independence, for the right to control one’s own body and for freedom in love, and she was among the first to speak publicly in favour of birth control. She also spoke in defence of homosexual people at a time when almost no one did.' },
      { title: 'Means shape ends', text: 'Her views on violence changed over time. As a young woman she accepted “propaganda by the deed”, the idea that attacks on leading figures could rouse the public, and she was loyal to Berkman after his attempt on Frick. In essays such as “The Psychology of Political Violence” she treated violence as a symptom of injustice, and in Russia she became convinced that a revolution which uses terror and dictatorship will end up reproducing what it overthrew.' },
      { title: 'Free speech and the individual', text: 'She was repeatedly arrested for speaking, and she turned the cases into arguments for free expression. Mother Earth published art, drama and politics together, and she lectured on Ibsen, Strindberg and Shaw as much as on economics, because she saw the freedom of art and the freedom of people as the same cause.' },
      { title: 'Education and the child', text: 'Following the Spanish educator Francisco Ferrer, who was executed in 1909, she criticised schools that taught obedience and urged an education that respected the child’s own curiosity. It was part of her wider belief that people are shaped by the institutions they grow up in.' },
    ],
    principles: [
      'Freedom for oneself is hollow without freedom for others.',
      'Judge a movement by what it does with power, not by what it promises.',
      'Hold to your convictions even when the cost is public hostility.',
      'Do not separate personal liberty from political liberty.',
      'Do not postpone joy: a good cause should not demand the denial of life.',
    ],
    practice: [
      'When a cause asks you to give up a freedom now for a better future, ask who will hold the power in between.',
      'Test your own commitments by asking what you would defend for people you disagree with.',
      'Support the creative and personal parts of your life as seriously as the political ones.',
    ],
    facts: [
      'The line “If I can’t dance, I don’t want to be part of your revolution” is not in her writings. It is a paraphrase that appeared on a 1970s anarchist T-shirt, based on a passage in her 1931 autobiography Living My Life, in which she rejected a movement colleague’s view that an agitator should not dance, saying that a cause should not demand the denial of life and joy.',
      'She was jailed on several occasions: in 1893, for the Union Square speech; in 1916, for spreading birth-control information; and in 1917–19 for conspiracy to obstruct the draft.',
      'In December 1919 she and Berkman were deported with more than 240 others on the USAT Buford, and they reached Finland in January 1920 before travelling to Russia.',
      'To gain British citizenship, and with it the right to live in Britain, she married an anarchist friend, James Colton, in 1925.',
      'Her autobiography Living My Life (1931) is one of the best-known memoirs of the radical movement in America.',
      'She was allowed back into the United States for a short lecture tour in 1934, under strict conditions, and she is buried at Forest Home Cemetery in Illinois, near the Haymarket memorial.',
    ],
    myths: [
      { myth: 'Goldman said “If I can’t dance, I don’t want to be part of your revolution.”', reality: 'The words appear nowhere in her writings. They are a later paraphrase of a story in Living My Life, popularised on a 1973 T-shirt. The sentiment is faithful to her outlook, but the quotation is not hers.' },
      { myth: 'Goldman organised or took part in violent attacks.', reality: 'She was arrested in connection with the Frick shooting and with the McKinley assassination, but was not convicted in either case, and the evidence did not link her to them. She did, however, defend the motives of Berkman and, in the McKinley case, treated the assassin as a human being, which exposed her to bitter public hostility.' },
      { myth: 'She turned against the left after Russia and joined its opponents.', reality: 'She remained an anarchist and a critic of capitalism to the end. In Spain in 1936–37 she worked for and defended the anarchist movement, though she was uneasy about some of its compromises. How to read her statements from this period, and whether her criticism of the Soviet Union helped enemies of the left, has been debated by historians and activists since.' },
    ],
    works: [
      { title: 'Anarchism and Other Essays (1910)', note: 'A collection of her main essays, including “The Traffic in Women” and “The Psychology of Political Violence”.' },
      { title: 'Mother Earth (1906–17)', note: 'The monthly magazine she founded and edited, mixing politics, art and literature.' },
      { title: 'My Disillusionment in Russia (1923)', note: 'Her account of her time under the Bolsheviks, followed by My Further Disillusionment in Russia (1924).' },
      { title: 'Living My Life (1931)', note: 'Her two-volume autobiography, vivid and personal but written from memory.' },
      { title: 'The Emma Goldman Papers', note: 'A large archive of letters and speeches at the University of California, Berkeley, which has been used to correct many stories about her.' },
    ],
    legacy: [
      'Goldman was a major figure in the history of American radicalism and one of the first people to link the cause of labour, women’s liberation and individual liberty. Her campaigns for free speech and birth control helped shape later struggles over civil liberties, and the feminism of the 1960s and 1970s rediscovered her as a forerunner.',
      'Views of her differ. Admirers see a courageous defender of freedom who saw early what the Soviet state would become; critics point to her early tolerance of political violence and to a utopian streak in her anarchism. Her life remains a reminder of how far a person might go in defence of conscience, and of the cost.',
    ],
  },
  {
    slug: 'rosa-luxemburg',
    order: 1871,
    dates: '1871 – 1919',
    place: 'Zamość (Poland), Zurich and Berlin',
    era: '20th Century',
    tradition: 'Revolutionary socialism',
    tagline: 'A Polish-German Marxist who believed socialism must be won by the masses, with democracy, and who was murdered for it.',
    who: [
      'Rosa Luxemburg was born in Zamość, in Russian-ruled Poland, to a Jewish family, and is usually said to have been born on 5 March 1871, though some documents give 1870. As a child, an illness left her with a permanent limp. She became active in underground socialist circles as a schoolgirl and, to escape arrest, left for Switzerland, where she studied at the University of Zurich and earned a doctorate in 1897 with a thesis on the industrial development of Poland. With Leo Jogiches she helped found a Polish socialist party.',
      'In 1898 she moved to Germany, gaining German citizenship through a marriage of convenience, and joined the Social Democratic Party (SPD), then the largest socialist party in the world. She became known as a brilliant polemicist, first against Eduard Bernstein’s “revisionism” in Reform or Revolution. She took part in the revolution of 1905 in Warsaw, where she was briefly imprisoned, and from 1907 she taught economics at the party school in Berlin.',
      'When the SPD voted for war credits in August 1914, she was among those who broke with it, and with Karl Liebknecht, Jogiches and others she founded the Spartacus League. She spent much of the war in prison, where she wrote the Junius Pamphlet, and she was released in November 1918 when the German Revolution began. She helped to found the Communist Party of Germany (KPD) at the end of December. On 15 January 1919 she was arrested in Berlin by soldiers of a Freikorps unit, the Guard Cavalry Rifle Division. She was struck with a rifle butt, shot and murdered, and her body was thrown into the Landwehr Canal.',
    ],
    context: [
      'Luxemburg lived in the age of the great socialist parties, when many believed that capitalism was heading for collapse and that workers’ movements would inherit the world. The argument was about how: by gradual reform through elections and trade unions, or by revolution. She saw the SPD becoming comfortable, more concerned with preserving its organisation than with the transformation of society, and the vote for war showed her fears had been justified.',
      'The war ended in German defeat and revolution. In November 1918 the Kaiser fell, and a new government under the Social Democrats Friedrich Ebert and Gustav Noske tried to keep order and to prevent a Soviet-style takeover. Workers’ councils, soldiers’ councils and radicals challenged it, and the government turned to the army and to the volunteer Freikorps units to put down armed resistance. Luxemburg’s last days belong to this struggle between two parts of the labour movement that had once been one.',
    ],
    ideas: [
      { title: 'Reform or revolution', text: 'In 1899 she argued that Bernstein was wrong to think capitalism could be reformed into socialism step by step. Reforms matter, she said, as a daily struggle that builds the workers’ strength, but they cannot replace the fundamental change of who owns and controls the economy. The two are not opposed: socialism needs both the daily struggle and a final transformation.' },
      { title: 'The mass strike', text: 'Learning from the Russian Revolution of 1905, she argued in The Mass Strike, the Political Party and the Trade Unions (1906) that great waves of strikes rise from the spontaneous action of workers, and cannot be ordered by a party or a union leadership. The task of the party, she thought, is to give such movements direction and awareness, not to command them.' },
      { title: 'Capitalism and imperialism', text: 'In The Accumulation of Capital (1913) she argued that capitalism needs to keep expanding into regions that are not yet capitalist, in order to find buyers for the surplus it produces. She saw this as a driver of imperialism, colonial conquest and militarism. Other Marxists, including those who admired her, disputed her economic argument, and it remains controversial among economists.' },
      { title: 'Socialism and democracy', text: 'She supported the Russian Revolution of October 1917 but criticised Lenin’s methods, from his early centralised party model to the dissolution of the Constituent Assembly and the restriction of the press and of assembly. In a manuscript written in prison in 1918, she argued that freedom only for supporters of the government is no freedom, and that freedom is always the freedom of the one who thinks differently. For her, socialism could only be built with the broad, active participation of the people, and without democracy it would decay into the rule of a narrow group.' },
      { title: 'Socialism or barbarism', text: 'In the Junius Pamphlet (1916) she wrote that humanity faces a choice between socialism and barbarism, a phrase she took from Engels. The slaughter of the First World War, she argued, showed what the alternative looked like.' },
    ],
    principles: [
      'Reform and radical change need each other.',
      'Trust the political awareness of ordinary people, and do not rule in their name.',
      'Hold that freedom for opponents is the test of freedom.',
      'Think critically about your own side, even when it is under attack.',
      'Act from conviction, and accept the cost.',
    ],
    practice: [
      'In any group you belong to, ask whether the members are actually shaping decisions, or only being informed of them.',
      'Defend the rights of people you disagree with to speak, and ask whether your own cause could survive their criticism.',
      'Pair practical, small improvements with a view of the larger change you want, and do not give up either.',
    ],
    facts: [
      'Her birth year is given as 1871 in most sources, but some documents of the time say 1870, and she herself used 1871.',
      'She earned a doctorate in Zurich in 1897, at a time when very few women in Europe did.',
      'She spent more than three years of the First World War in prison or in protective custody, and wrote some of her major texts there.',
      'Her pamphlet The Russian Revolution was written in prison in 1918 and was unfinished. It was published in 1922 by her former comrade Paul Levi, and there has been a long argument about whether she would have revised it, as Clara Zetkin claimed.',
      'Her last article, written on 14 January 1919, was titled “Order Prevails in Berlin”, and ended with the words “I was, I am, I shall be”.',
      'Her body was found in the Landwehr Canal at the end of May 1919, months after the killing, and she was buried in Berlin on 13 June.',
    ],
    myths: [
      { myth: '“Freedom is always the freedom of the one who thinks differently” is a general liberal statement about free speech.', reality: 'It comes from her critical manuscript on the Russian Revolution, written by a committed socialist who supported the revolution while warning that suppressing political freedom would destroy it. The text was unfinished and not published in her lifetime, and the line has been used by people of very different politics.' },
      { myth: 'She led the Spartacist uprising of January 1919.', reality: 'She was a leading figure in the Spartacus League and the new KPD, and she wrote for its newspaper, but accounts indicate that she thought a bid to take power by force was premature and mistaken. The uprising was largely spontaneous, and was crushed by government troops and Freikorps.' },
      { myth: 'Luxemburg was simply a Leninist.', reality: 'She disagreed with Lenin on party organisation, on democracy and on several policies of the new Soviet government. She admired the Bolsheviks’ courage in taking power, but wrote that they should not make a virtue of necessity.' },
    ],
    works: [
      { title: 'Reform or Revolution (1899)', note: 'Her reply to Eduard Bernstein, and her best-known early work.' },
      { title: 'The Mass Strike, the Political Party and the Trade Unions (1906)', note: 'Her theory of mass action, drawing on the 1905 revolution.' },
      { title: 'The Accumulation of Capital (1913)', note: 'Her main work of economic theory, followed by the Anti-Critique, written in prison.' },
      { title: 'The Junius Pamphlet (1916)', note: 'A denunciation of the war, written in prison and smuggled out under a pseudonym.' },
      { title: 'The Russian Revolution (written 1918, published 1922)', note: 'Her critical assessment of the Bolsheviks, left unfinished.' },
    ],
    legacy: [
      'After her death, the Communist movement honoured her as a martyr but the Soviet-aligned parties distrusted her ideas, and the term “Luxemburgism” was used as an accusation. Later socialists, from the New Left of the 1960s to modern democratic socialists, rediscovered her as a revolutionary who insisted on democracy. Her thinking about imperialism also influenced writers on the economics of colonialism.',
      'Her murder, and that of Liebknecht, was a turning point for the German left. Few of those responsible were punished, and the Social Democrats and the Communists, who had once belonged to the same movement, became bitter enemies. Many historians see this split as one of the weaknesses of German democracy in the years that followed. Each January, thousands of people still march in Berlin to her memorial.',
    ],
  },
]
