import type { Profile } from './types'

export const MORE_10: Profile[] = [
  {
    slug: 'william-blake',
    order: 1757,
    dates: '1757 – 1827',
    place: 'London, with three years at Felpham, Sussex',
    era: 'Enlightenment',
    tradition: 'English Romanticism',
    tagline: 'A poor engraver who saw eternity in a grain of sand and answered the age of reason with imagination.',
    who: [
      'William Blake was born in London in 1757, the son of a hosier, and lived most of his life in the city. He left school early and at fourteen was apprenticed to the engraver James Basire, whose trade of cutting images into copper plates he practised all his life. He studied briefly at the Royal Academy, married Catherine Boucher in 1782, and published his first poems, Poetical Sketches, the following year. Catherine learned to help with printing and colouring, and the two worked as a team.',
      'Blake invented his own method of “illuminated printing”, in which words and pictures are etched together on one plate and then printed and painted by hand. With it he produced Songs of Innocence (1789), the combined Songs of Innocence and of Experience (1794), The Marriage of Heaven and Hell (made in the early 1790s), the prophetic books such as America and The Book of Urizen, and the long poems Milton and Jerusalem. He also claimed from childhood to see visions, and he treated them as part of his working life, though scholars debate how literally he meant them.',
      'Blake earned a modest living from commercial engraving and a few patrons. In 1800 he moved to Felpham on the Sussex coast to work for the poet William Hayley, and in 1803 he was arrested after an argument with a soldier in his garden. He was tried for sedition at Chichester in January 1804 and acquitted. He returned to London, lived on little, and was almost unknown when he died in 1827 in rooms off the Strand, working to the end on his illustrations to Dante. He was buried in Bunhill Fields in an unmarked grave.',
    ],
    context: [
      'Blake grew up in the age of Newton, Locke and the Enlightenment, when reason, experiment and commerce were changing Britain. He also lived through the American Revolution, the French Revolution and the long war with France, and through the first years of the factory system. He is said to have been caught up in the crowd that burned Newgate Prison in the Gordon Riots of 1780. In the early 1790s he belonged to a circle of radical writers and publishers around the bookseller Joseph Johnson, and the sympathy he showed for the revolutions is clear in his poem America.',
      'He was also shaped by the religious dissent of London. He knew the writings of the Swedish visionary Emanuel Swedenborg and attended an early meeting of the Swedenborgian New Church in 1789, but he soon turned against what he saw as its tame orthodoxy, and The Marriage of Heaven and Hell mocks Swedenborg for offering nothing new. His relation to the Enlightenment was therefore mixed. He shared its hatred of tyranny, superstition and priestcraft, but he thought the rationalism of Bacon, Newton and Locke had shrunk the human mind to what it could measure.',
    ],
    ideas: [
      { title: 'Imagination is the heart of human life', text: 'For Blake, imagination was not decoration or fantasy. It was the faculty by which people perceive what is truly there, and he identified it with the divine in each person. His lines about seeing a world in a grain of sand, from the poem Auguries of Innocence, express the claim that close attention to the small can open the infinite.' },
      { title: 'Innocence and experience', text: 'The Songs present “two contrary states of the human soul”. Innocence is trusting, playful and open; experience has learned about poverty, power and cruelty. Blake does not treat either as simply right. Innocence left alone is naive and open to being exploited, and experience alone hardens into cynicism, so he looks for a way to pass through both to a higher vision.' },
      { title: 'Contraries and progression', text: 'In The Marriage of Heaven and Hell he wrote that without contraries there is no progression, such as attraction and repulsion, reason and energy, love and hate. He mocked a religion that called one side “good” and suppressed the other, and he argued that energy, desire and the body, often condemned by the church, are sources of life that need to be freed, not killed.' },
      { title: 'The mind-forged manacles', text: 'In his poem London he describes the “mind-forg’d manacles” heard in the voices of the city: oppression is held in place not only by law and force but by the habits of thought of the oppressed. His targets include the church that blessed the poverty of chimney sweeps, the monarchy, the wealthy, and the factories, which in the preface to Milton he calls the “dark Satanic Mills”, though readers still disagree about whether he meant literal factories, a religion, or a way of thinking.' },
      { title: 'Against single vision', text: 'Blake feared a way of seeing that counts only what can be measured and sold. He portrayed Newton in a famous colour print as a figure bent over a compass, absorbed in a narrow diagram. This was not a rejection of science as such, but a protest against treating one kind of knowledge as the only kind, and a warning that the machine and the market can make people into parts of a mechanism.' },
    ],
    principles: [
      'Look closely: the small thing, truly seen, can hold the whole.',
      'Do not accept a creed, or a ruler, merely because it is old and powerful.',
      'Desire and reason need each other; a life without one of them goes wrong.',
      'Question the voices in your own head that tell you what is possible.',
      'Make something with your hands and imagination, and do not wait for permission.',
    ],
    practice: [
      'Spend ten minutes looking at one ordinary object, a leaf or a stone, and write down what you notice that you had never seen before.',
      'When you feel stuck, ask whose rule you are following, and whether you chose it.',
      'Read a poem in two states: first for what it says, then for what it hides, and notice how the two readings differ.',
    ],
    facts: [
      'Blake wrote, illustrated, printed and coloured his own books, so no two copies of an illuminated book are identical.',
      'The Marriage of Heaven and Hell includes the “Proverbs of Hell”, such as “The road of excess leads to the palace of wisdom”.',
      'He was tried for sedition in 1804 after a soldier named John Scolfield, in some spellings Schofield, accused him of shouting that the soldiers were slaves and cursing the king. The jury acquitted him.',
      'The words known as the hymn “Jerusalem”, “And did those feet in ancient time”, come from the preface to his poem Milton, not from the book called Jerusalem. Hubert Parry set them to music in 1916.',
      'His last major project was a series of watercolours and engravings for Dante’s Divine Comedy, commissioned by the painter John Linnell and left unfinished at his death.',
      'Blake’s grave in Bunhill Fields was lost, and a new memorial was placed near its approximate site in 2018.',
    ],
    myths: [
      { myth: 'Blake was simply mad.', reality: 'Some contemporaries called him mad because of his visions and his unconventional art. But he ran a business, worked with a respected patron, wrote with great precision and held firm political and religious views. Many modern scholars see the visions as part of a deliberate poetic and religious practice, though how Blake himself understood them is still debated.' },
      { myth: 'Blake rejected the Enlightenment altogether.', reality: 'He attacked its narrow rationalism, but he shared its opposition to tyranny, slavery, and the unquestioned authority of church and state, and he moved among radical thinkers who supported the Enlightenment’s political ideals.' },
      { myth: 'The hymn “Jerusalem” is a patriotic song about the glory of England.', reality: 'The poem’s own question is whether a new Jerusalem was ever built in England, and its answer is a call to struggle for one. Readers disagree about how far it is a call for reform and how far a religious vision, but it was not a celebration of empire.' },
    ],
    works: [
      { title: 'Songs of Innocence and of Experience (1789, 1794)', note: 'His best-known poems, including “The Lamb”, “The Tyger”, “The Chimney Sweeper” and “London”.' },
      { title: 'The Marriage of Heaven and Hell (c. 1790–93)', note: 'A satirical prose and verse work that overturns conventional ideas of good and evil.' },
      { title: 'The prophetic books (1790s)', note: 'America, Europe, The Book of Urizen and others set out Blake’s personal mythology of tyranny and liberation.' },
      { title: 'Milton and Jerusalem (c. 1804–20)', note: 'Long illuminated poems; Jerusalem is his largest work, dealing with a fallen England and the hope of renewal.' },
      { title: 'Alexander Gilchrist, Life of William Blake (1863)', note: 'The first full biography, which helped revive Blake’s reputation; some of its anecdotes rest on friends’ memories and should be read cautiously.' },
    ],
    legacy: [
      'Blake’s reputation in his lifetime was small, and for decades after his death he was seen as an eccentric. Gilchrist’s biography in 1863, which had help from Dante Gabriel Rossetti, and an essay by Swinburne in 1868 brought him to a wider audience, and in the twentieth century critics such as Northrop Frye placed him among the greatest English poets. W. B. Yeats edited an early edition of his works with Edwin Ellis in 1893.',
      'His influence stretches across poetry, painting, music, and protest. The Pre-Raphaelites revered him, poets and musicians of the twentieth century drew on his work, and his lines are still quoted in political and religious debate. His questions, about whether reason alone can make a humane society, and about what imagination is for, remain open.',
    ],
  },
  {
    slug: 'friedrich-schiller',
    order: 1759,
    dates: '1759 – 1805',
    place: 'Stuttgart, Jena and Weimar, Germany',
    era: 'Enlightenment',
    tradition: 'Weimar classicism',
    tagline: 'The poet-dramatist who argued that beauty and play are how human beings become free.',
    who: [
      'Friedrich Schiller was born in 1759 in Marbach, in the duchy of Württemberg. At the order of the duke, Karl Eugen, he entered a strict military academy near Stuttgart as a boy, studied law and then medicine, and became a poorly paid regimental doctor. In secret he wrote a wild, rebellious play, The Robbers, which was a sensation at its Mannheim premiere in 1782. When the duke punished him for leaving his post to see it, Schiller fled the duchy.',
      'Years of money trouble followed, helped by friends, above all Christian Gottfried Körner in Dresden, for whom he wrote the poem “Ode to Joy” in 1785. After the play Don Carlos (1787), he turned to history and in 1789 became a professor at Jena. He married Charlotte von Lengefeld in 1790. A serious illness in 1791 left his health permanently weak, and a gift from Danish patrons gave him time to study Kant and to write his philosophical essays.',
      'From 1794 he formed a close friendship with Goethe, and the two became the centre of Weimar classicism. Schiller moved to Weimar in 1799 and wrote his greatest plays there: the Wallenstein trilogy, Maria Stuart, The Maid of Orleans and William Tell. He was ennobled in 1802 and died of tuberculosis in Weimar in 1805, aged 45, while working on a new play, Demetrius.',
    ],
    context: [
      'Schiller grew up in a Germany divided into hundreds of small states, ruled by princes who often claimed absolute power. Duke Karl Eugen’s treatment of him was one personal example of that power, and The Robbers and Intrigue and Love reflect the anger of a generation of German writers, known as the Sturm und Drang, who demanded freedom and feeling against the old order.',
      'The French Revolution gave the question urgency. Schiller was at first sympathetic, and in 1792 he was named an honorary citizen of the French republic. But the Terror of 1793 horrified him, and he concluded that political change could not succeed unless people were first fit for freedom. His answer, in the Letters on the Aesthetic Education of Man, was that art and culture must educate the sense and the will together. He wrote under the influence of Kant, whose moral philosophy he admired, though he thought it too stern about human feeling.',
    ],
    ideas: [
      { title: 'Play and freedom', text: 'In the fifteenth of his Letters on the Aesthetic Education of Man, Schiller wrote that a person plays only when fully human, and is fully human only when playing. By “play” he meant the free exercise of our powers for their own sake, as in art, when we are neither forced by need nor commanded by duty. In that state, he argued, we get a taste of freedom.' },
      { title: 'Reconciling sense and reason', text: 'Schiller described a human being as divided between a “sense drive”, tied to feeling and the present moment, and a “form drive”, tied to reason and law. Neglect one and you get either a creature of impulse or a cold, abstract thinker. The “play drive”, awakened by beauty, brings the two together, and so beauty plays a moral role, not just a decorative one.' },
      { title: 'Aesthetic education', text: 'He held that a society cannot be made free by decree or by violence if its people are not yet capable of freedom. Art and culture, by training taste and feeling, prepare character for it. The idea shaped later theories of education and of the arts as a public good, though critics have asked whether it risks making politics wait on culture.' },
      { title: 'Grace and dignity', text: 'Against Kant’s picture of duty as a struggle against inclination, Schiller argued in his essay On Grace and Dignity for an ideal in which a person does the right thing gracefully, because inclination and duty have been brought into harmony. Dignity is shown when reason masters strong feeling, and grace when the two agree.' },
      { title: 'Drama as moral theatre', text: 'Schiller believed the stage could educate a public. His plays set individual conscience against power: in Don Carlos, the marquis of Posa asks the king for freedom of thought; in Wallenstein, an ambitious general is destroyed by his own calculations; in William Tell, ordinary people rise against a tyrant. The dramas are as much arguments as stories.' },
    ],
    principles: [
      'Freedom needs preparation: build the character before you demand the change.',
      'Let duty and affection work together, not against each other.',
      'Make room for play, because it is where people are most themselves.',
      'Use art to widen what you can feel, as well as what you can think.',
      'Speak up for freedom of thought, even to those in power.',
    ],
    practice: [
      'Schedule time for an activity that has no purpose except enjoyment, and notice what it does to your energy.',
      'When a duty feels heavy, ask whether you can do it in a way that also expresses what you care about.',
      'Go to a play, concert or exhibition and say afterwards what it made you feel as well as what it meant.',
    ],
    facts: [
      'Beethoven’s Ninth Symphony (1824) sets parts of the “Ode to Joy” in its finale, rearranged and with some lines Beethoven added himself. His melody, without words, is the anthem of the European Union.',
      'Schiller later judged the Ode a weak poem. In a letter of 1800 to Körner he said it was far from reality and of little value for the world or for poetry.',
      'The line “Beggars become princes’ brothers” in the Ode was changed to “All men become brothers” in an edition published after his death.',
      'Schiller wrote William Tell without ever visiting Switzerland, relying on chronicles and on Goethe’s descriptions of his own travels there.',
      'According to Goethe, Schiller kept rotting apples in his desk drawer because the smell helped him to write.',
      'His Letters on the Aesthetic Education of Man began as letters to the Danish Prince Friedrich Christian of Augustenburg, and the originals were lost in a fire at Copenhagen’s royal palace in 1794; Schiller then reworked them for publication in 1795.',
    ],
    myths: [
      { myth: 'Schiller wrote the words of Beethoven’s Ninth Symphony.', reality: 'He wrote the poem, in 1785, but Beethoven selected only some stanzas, changed their order and added a few lines of his own, including the opening call to abandon “these tones”.' },
      { myth: 'Schiller was a straightforward follower of Kant.', reality: 'He took over Kant’s central ideas about freedom but criticised Kant’s moral stiffness, and he gave beauty and play a much larger role in human development than Kant did.' },
      { myth: 'The Ode to Joy was the work of a calm, cheerful man.', reality: 'It was written by a young writer in debt and dependent on friends, and he later distanced himself from it. Its theme of universal brotherhood is a hope as much as a description.' },
    ],
    works: [
      { title: 'The Robbers (1781), Intrigue and Love (1784), Don Carlos (1787)', note: 'The early plays of rebellion against tyranny and hypocrisy.' },
      { title: 'On the Aesthetic Education of Man (1795)', note: 'A series of letters, and his main work of philosophy, on beauty, play, and freedom.' },
      { title: 'On Naive and Sentimental Poetry (1795–96)', note: 'An essay contrasting poets who are at one with nature with those who long for it, with Goethe as the first type.' },
      { title: 'Wallenstein, Maria Stuart, William Tell (1799–1804)', note: 'The mature historical dramas, central to German theatre.' },
      { title: 'The Schiller–Goethe correspondence', note: 'Letters from 1794 to 1805, a main source for how both men understood art and for their friendship.' },
    ],
    legacy: [
      'Schiller became a national poet in Germany, and his plays remain a staple of its stages and of opera: Verdi wrote Don Carlos and I masnadieri (The Robbers), Rossini wrote William Tell and Donizetti wrote Maria Stuarda. His vision of aesthetic education influenced Hegel and later thinkers such as Herbert Marcuse. Political movements across the nineteenth century, liberal, nationalist and socialist alike, claimed him, and the hundredth anniversary of his birth in 1859 was marked by festivals across Germany.',
      'Through Beethoven’s Ninth, the “Ode to Joy” became a global symbol of human solidarity, used at ceremonies of reconciliation and, more problematically, by many regimes. The reading of Schiller’s idea of play in modern writing on education, games and creativity shows how far his thought has travelled from its first setting.',
    ],
  },
  {
    slug: 'johann-gottlieb-fichte',
    order: 1762,
    dates: '1762 – 1814',
    place: 'Jena and Berlin, Germany',
    era: 'Enlightenment',
    tradition: 'German idealism',
    tagline: 'The philosopher who made the free, active self the starting point of all knowledge.',
    who: [
      'Johann Gottlieb Fichte was born in 1762 in Rammenau, in Saxony, the eldest child of a poor family of ribbon weavers. A local nobleman who heard him recite a sermon paid for his education, and he went on to study theology and philosophy at Jena and Leipzig. For some years he worked as a private tutor, including a period in Zurich, where he met and later married Johanna Rahn.',
      'In 1790 he read Kant and later said it changed his life. He visited Kant in Königsberg in 1791 and wrote an essay on revelation which, published anonymously in 1792, was at first taken for Kant’s own work. The fame it brought him led to a professorship at Jena in 1794, where he presented his Wissenschaftslehre, or “Doctrine of Science”, a system that tried to ground all knowledge in the activity of the self.',
      'In 1798 an essay in a journal he co-edited led to a charge of atheism. The Saxon authorities confiscated the journal, and after a heated dispute about how the case was being handled, Fichte was dismissed from Jena in 1799. He moved to Berlin, lectured privately, and held posts elsewhere, then in 1810 became a professor at the new University of Berlin and was elected its rector for 1811–12. He died of typhus in January 1814, probably caught from his wife, who had nursed wounded soldiers.',
    ],
    context: [
      'Fichte was one of the first to take up Kant’s philosophy and push it further. Kant had argued that human knowledge is shaped by the mind, but kept a puzzling “thing in itself” beyond it. Fichte, like other young philosophers of his generation, thought that this left the system incomplete, and he looked for a single principle from which everything else could follow. This was the beginning of German idealism, which Schelling and Hegel developed after him.',
      'Politically, he was a supporter of the French Revolution in its early years and wrote defences of free thought. The later years of his life were shaped by the Napoleonic wars. After Prussia’s defeat by France in 1806 and the occupation of Berlin, he wrote and spoke about the future of Germany as a cultural and educational task, and in the Wars of Liberation of 1813 he gave lectures in support of the struggle against French rule.',
    ],
    ideas: [
      { title: 'The self posits itself', text: 'Fichte began from the thought that the “I” is not a thing found in the world but an act: it makes itself what it is by being aware of itself. This pure activity, he argued, is the foundation on which knowledge rests. He then argued that in order to be active the I must meet something that resists it, a “Not-I”, which is how the world appears to us.' },
      { title: 'Philosophy depends on who you are', text: 'In an introduction to his system he wrote that the sort of philosophy a person chooses depends on the sort of person they are. By this he meant that the choice between a view that puts freedom first (idealism) and one that explains everything by things and causes (dogmatism) cannot be settled by argument alone, and reflects a person’s own character.' },
      { title: 'Freedom and duty', text: 'For Fichte, to be a self is to be free, and freedom is realised by acting on duty. The world is, in his phrase, the material of our duty made sensible. This gives his ethics a restless, demanding tone: our task is not to rest but to keep acting, to shape ourselves and the world.' },
      { title: 'Recognition by others', text: 'In his Foundations of Natural Right (1796), he argued that a person becomes a free self only through being “summoned” to freedom by another person. We become selves by being recognised. This idea of recognition influenced Hegel and has been taken up in modern social theory.' },
      { title: 'Education for the nation', text: 'In his Addresses to the German Nation he argued that Germany’s recovery after defeat depended on a new national education that would teach people to think for themselves and to act from duty. He believed that language and culture shape a people, and that education could bring about a moral renewal.' },
    ],
    principles: [
      'You become who you are by acting, not by waiting.',
      'Freedom is not just permission; it is the task of making yourself.',
      'Be honest about what your philosophy says about your own character.',
      'Respect others as free beings, since you owe your own freedom partly to them.',
      'Do your duty with energy, and make your work count.',
    ],
    practice: [
      'Choose one habit you have always called “just how I am” and treat it as a decision you can remake.',
      'Before arguing with someone, ask what experiences and values make their view feel natural to them.',
      'Define one task that is yours alone and carry it out today without waiting to be asked.',
    ],
    facts: [
      'His first book, the Attempt at a Critique of All Revelation (1792), was published without his name, and many readers thought it was by Kant until Kant publicly named Fichte as the author.',
      'The dispute that cost him his post began when Fichte published an essay on belief in a divine governance of the world. In it he identified God with the moral order, which critics read as a denial of a personal God.',
      'The triad “thesis, antithesis, synthesis” is often credited to Hegel, but it was Fichte who used these terms, and Hegel rarely did.',
      'The Addresses to the German Nation were delivered as a series of lectures in Berlin between December 1807 and March 1808, while the city was occupied by French troops.',
      'He was elected rector of the University of Berlin in 1811 and resigned the following year after disputes with colleagues, in part over the harassment of Jewish students, whom he defended.',
      'In 1793 he expressed opposition to civil rights for Jews in his writing, which is a serious stain on his record, although he also added a plea for their religious freedom.',
    ],
    myths: [
      { myth: 'Fichte was an atheist.', reality: 'He denied it. He believed in a moral world order that he sometimes called divine, but he rejected the idea of God as a being who exists like a person. Whether his position is atheism has been debated from his own time to ours.' },
      { myth: 'The Addresses to the German Nation are a call for German racial superiority.', reality: 'The Addresses stress language, education and culture, not biological race, and they were a response to the occupation of Berlin. Yet they also contain claims about the special qualities of the German language and people, and later nationalists used them, and in the twentieth century the Nazis did, to support racist politics. Historians still argue about how much responsibility for that use belongs to the text itself.' },
      { myth: 'Fichte invented the dialectic of thesis, antithesis and synthesis, and Hegel borrowed it.', reality: 'Fichte did use those terms in 1794, but his dialectic is built on the opposition of the I and the Not-I, and Hegel’s method differs from it.' },
    ],
    works: [
      { title: 'Attempt at a Critique of All Revelation (1792)', note: 'The essay that brought him fame and the favour of Kant.' },
      { title: 'Foundations of the Entire Doctrine of Science (1794–95)', note: 'The core statement of the Wissenschaftslehre, the system of the self-positing I.' },
      { title: 'Foundations of Natural Right (1796) and System of Ethics (1798)', note: 'His political and moral philosophy, including the theory of recognition.' },
      { title: 'The Vocation of Man (1800)', note: 'A popular, personal presentation of his philosophy and its answer to doubt.' },
      { title: 'Addresses to the German Nation (1808)', note: 'His public lectures on education and national renewal, the most read and most controversial of his works.' },
    ],
    legacy: [
      'Fichte was the link between Kant and the idealists who followed. Schelling and Hegel developed their systems in answer to his, and Hegel’s theory of recognition was influenced by Fichte’s. His stress on action and the free self also prefigured themes in existentialism and in later philosophies of the person.',
      'His political legacy is mixed. The Addresses were quoted by German nationalists across the nineteenth century as a founding text of the nation, and in the 1930s and 1940s they were used by the Nazi regime. Many scholars argue that this reading takes them out of context, while others point to troubling passages within them. His Berlin lectures and his role at the new university also made him one of the founders of the modern German university.',
    ],
  },
  {
    slug: 'germaine-de-stael',
    order: 1766,
    dates: '1766 – 1817',
    place: 'Paris, Coppet (Switzerland), and exile across Europe',
    era: 'Enlightenment',
    tradition: 'Liberal Romanticism',
    tagline: 'The salon hostess and author who opposed Napoleon and introduced French readers to German Romanticism.',
    who: [
      'Anne-Louise Germaine Necker was born in Paris in 1766, the daughter of the Swiss banker Jacques Necker, who served as finance minister to Louis XVI, and of Suzanne Curchod, who ran an important salon. Raised among philosophers and statesmen, she was precocious and outspoken. In 1786 she married Baron Erik Magnus Staël von Holstein, the Swedish ambassador, and became Madame de Staël. She wrote Letters on the Works and Character of J.-J. Rousseau in 1788 and hosted a salon in Paris.',
      'The Revolution first excited and then endangered her. In 1792, during the September massacres, she helped friends escape and then left France herself. She returned in the mid-1790s and became a leading voice of the moderate republicans, with a long relationship with the writer and politician Benjamin Constant. When Napoleon took power she refused to flatter him, and in 1803 he ordered her to stay at least forty leagues from Paris. This began years of exile, much of it at her father’s estate at Coppet, near Geneva, where she gathered a circle of writers and thinkers.',
      'From Coppet she travelled to Germany, Italy, and in 1812 across Russia and Sweden to England. She published the novels Delphine (1802) and Corinne (1807), the study De l’Allemagne, and many essays. Napoleon’s police seized and destroyed the French printing of De l’Allemagne in 1810, and it appeared in London in 1813. She returned to Paris after Napoleon’s fall in 1814, and died there in July 1817 after a stroke. Her Considerations on the French Revolution was published the following year.',
    ],
    context: [
      'Staël lived through the end of the old regime, the Revolution, the Terror, the Directory, the Napoleonic empire and the Restoration, and her writing is a running commentary on them. She believed in the ideals of 1789, including constitutional government, civil liberties and a free press, but feared both the mob and the despot, and she thought Britain’s mix of monarchy and parliament offered a model.',
      'Intellectually she stood between the Enlightenment and Romanticism. She had been raised on the writings of Montesquieu, Rousseau and Voltaire, and she kept their faith in progress and reason. But she was also among the first in France to take German literature, philosophy and feeling seriously, and she brought it to readers who had thought of literature as a matter of fixed classical rules.',
    ],
    ideas: [
      { title: 'Liberty is an old French tradition', text: 'In her Considerations on the French Revolution she argued that the Revolution’s principles were a fulfilment of centuries of French and European history, not an alien invention. She defended liberty, and the rule of law, while condemning the Terror and Napoleon’s despotism, and she used the English example to argue for a balanced constitution. This put her among the founders of French liberalism.' },
      { title: 'Literature shaped by society', text: 'In On Literature Considered in Its Relations to Social Institutions (1800), she argued that literature changes with a society’s laws, religion and customs, and can help it improve. She contrasted the literature of the North, thoughtful and melancholy, with that of the South, and her view that writing has a history helped to launch the modern idea of comparative literature.' },
      { title: 'Introducing German Romanticism', text: 'De l’Allemagne presented the Germans as a nation of thinkers and poets, and described Goethe, Schiller, Kant and the Schlegels for French readers. She praised enthusiasm and inner feeling and argued that France could renew itself by learning from them. The book helped establish Romanticism in France.' },
      { title: 'The woman of genius in a hostile society', text: 'Her novel Corinne tells the story of an Anglo-Italian poet whose talent and independence are thwarted by a man who prefers a conventional wife. The book is also a travel guide to Italy and a meditation on the cost of female genius. Many readers took Corinne as a portrait of Staël herself, which she did not deny.' },
      { title: 'Passions and happiness', text: 'In her early work On the Influence of the Passions (1796) she considered how ambition, love and the desire for fame shape personal happiness and political life, and concluded that these passions bring more pain than peace unless they are balanced by reason and moral feeling. This theme runs through her novels.' },
    ],
    principles: [
      'Defend liberty even when it is unpopular and costly.',
      'Learn from other nations rather than guard your own habits.',
      'Treat conversation as a serious art.',
      'Let feeling and reason correct each other.',
      'Do not flatter power.',
    ],
    practice: [
      'Read one book from a country whose culture you know little about, and note what its authors take for granted.',
      'Invite a few people with different views to a meal and aim for real conversation, not a debate.',
      'When you disagree with someone in authority, write down your reasons clearly and share them with someone you trust.',
    ],
    facts: [
      'Napoleon’s police ordered the entire first printing of De l’Allemagne to be destroyed; the manuscript was saved, and a French edition was printed in London in 1813.',
      'Her Coppet circle included Constant, the German critic August Wilhelm Schlegel (tutor to her children), the historian Sismondi and Madame Récamier.',
      'A son was born in 1812 to her and Albert de Rocca, a Swiss-born officer about twenty years younger than she was. Most accounts say they married secretly in 1816, though some give an earlier date.',
      'She spent the winter of 1803–04 in Weimar, where she met Goethe and Schiller, and the visit shaped her plan to write about Germany.',
      'In 1792 she helped hide Louis de Narbonne, a former minister of war and her lover at the time, and other friends from the revolutionary authorities before leaving France herself.',
      'In her memoir Ten Years of Exile she gave her own account of how Napoleon’s police watched and harassed her.',
    ],
    myths: [
      { myth: 'She was exiled because she was a political rival of Napoleon.', reality: 'Her opposition was real, but it was expressed mainly through her salon, her conversation and her writing. Napoleon disliked her independence and her circle, and the exile was a punishment for that, not a response to any proven plot.' },
      { myth: 'Corinne is just her autobiography.', reality: 'It draws on her life and her travels, and she shared many of Corinne’s hopes, but it is a novel with its own plot and invented characters.' },
      { myth: 'She was only a salon figure and a socialite.', reality: 'She wrote some of the most read books of her time, and her political and literary analysis shaped French liberalism and Romanticism well beyond her salon.' },
    ],
    works: [
      { title: 'On Literature (De la littérature, 1800)', note: 'Argues that literature is shaped by social institutions and is capable of progress.' },
      { title: 'Delphine (1802) and Corinne, or Italy (1807)', note: 'Novels that explore women’s place in society, with Corinne the best known.' },
      { title: 'On Germany (De l’Allemagne, 1810; published 1813)', note: 'A portrait of German culture, philosophy and literature, and her main contribution to Romanticism.' },
      { title: 'Considerations on the Principal Events of the French Revolution (1818)', note: 'Her last major work, published after her death; a liberal history of the Revolution and the empire.' },
      { title: 'Ten Years of Exile (published 1821)', note: 'Her memoir of her exile under Napoleon, published after her death.' },
    ],
    legacy: [
      'Staël influenced French and European liberalism, and her Considerations on the French Revolution was widely read by liberals and by later historians. She is also often seen as a foundational figure for French Romanticism: French Romantics drew on her ideas, and her work encouraged translation and comparative study across Europe.',
      'In recent decades she has been rediscovered by scholars of women’s writing, of the Enlightenment and of exile. Her Coppet salon is studied as a model of transnational intellectual exchange, and the questions she asked about how to defend liberty against both the crowd and the autocrat still feel familiar.',
    ],
  },
  {
    slug: 'wilhelm-von-humboldt',
    order: 1767,
    dates: '1767 – 1835',
    place: 'Berlin, Rome, Vienna and Tegel, Prussia',
    era: 'Enlightenment',
    tradition: 'Philosophy of language and education',
    tagline: 'The statesman and linguist who argued that people flourish through self-cultivation, and that language shapes how we see the world.',
    who: [
      'Wilhelm von Humboldt was born in 1767 in Potsdam into a Prussian noble family. His younger brother was the naturalist Alexander von Humboldt. Educated at home by private tutors, he studied law and classics at Frankfurt an der Oder and Göttingen. He married Caroline von Dacheröden in 1791, and their partnership, with its many letters, became a model of intellectual companionship.',
      'In the 1790s he wrote about politics and aesthetics, lived in Jena, where he became a close friend of Schiller and Goethe, and then in Paris, where he studied the French and began his interest in the Basque language. From 1802 to 1808 he served as Prussian envoy to the Holy See in Rome, a post that left him time for study, and he translated Greek poetry.',
      'In 1809 he was called to Berlin to lead the section for education and culture in the Prussian interior ministry, which he did for about sixteen months. He started a major reform of schooling and planned the University of Berlin, which opened in 1810, after he had left the post. He then served as a diplomat in Vienna and at the peace conferences that followed Napoleon’s defeat, and briefly returned to government. After resigning in 1819, in protest at the repressive turn in Prussian policy, he retired to his estate at Tegel and devoted himself to the study of languages until his death in 1835.',
    ],
    context: [
      'Humboldt grew up under Frederick the Great and matured in the years of the French Revolution and the Napoleonic wars. Prussia’s crushing defeat by Napoleon in 1806 convinced reformers that the state needed new strength, and many believed it could come only from educated, self-reliant citizens. Humboldt’s reforms belonged to this effort, together with the ones of Stein and Hardenberg.',
      'Intellectually he belonged to the circle of Weimar and Jena. He had read Kant, Herder and Schiller, and he shared the German classical ideal of Bildung, the harmonious cultivation of all of a person’s powers. He also sought a general science of humanity, with languages as the key to understanding how different peoples think.',
    ],
    ideas: [
      { title: 'Bildung: the self-cultivation of the person', text: 'For Humboldt the highest aim of a human being is the development of all their powers into a harmonious whole. Education is therefore not mainly job training but a way of forming character through contact with the world and with culture. This ideal, called Bildung, became central to German educational thought.' },
      { title: 'The limits of state action', text: 'In The Limits of State Action, written in 1791–92, he argued that the state should secure the safety of its citizens and leave them free to shape their own lives, since a state that tries to make people happy ends by making them uniform. John Stuart Mill used a line from the book as the motto of On Liberty, about the importance of human development in its richest diversity.' },
      { title: 'Language shapes thought', text: 'He held that language is not a stock of labels but an activity, an energy through which people form thoughts. Each language, he argued, carries a particular way of looking at the world, a “worldview” formed by its structure. He called language the formative organ of thought. His ideas are often seen as forerunners of later claims about the link between language and cognition, though scholars dispute how strong a claim he made.' },
      { title: 'Infinite use of finite means', text: 'Humboldt noted that language makes “infinite use of finite means”: a limited set of sounds and rules lets speakers create and understand an unlimited number of new sentences. Noam Chomsky later cited this remark as an early statement of the creative aspect of language.' },
      { title: 'The university as a place of research and freedom', text: 'Humboldt’s plans for higher education called for the unity of teaching and research, for professors and students alike to take part in the pursuit of knowledge, and for the state to fund the university but not to dictate what it teaches. Free inquiry, he said, needs both freedom and a measure of solitude.' },
    ],
    principles: [
      'Develop all your powers, not only the ones that pay.',
      'Let people shape their own lives, and be wary of those who would do it for them.',
      'Learn another language to see your own with new eyes.',
      'Value inquiry for its own sake as well as for its uses.',
      'Combine public duty with private study.',
    ],
    practice: [
      'Take up a language, even a little, and notice what ideas are easy to say in it and hard to say in your own.',
      'Plan your learning around questions you care about, and leave space for research that will not obviously pay off.',
      'When you want to help someone, ask first whether you are supporting their choices or replacing them.',
    ],
    facts: [
      'The University of Berlin, founded in 1810, was renamed Humboldt University in 1949, in honour of both Wilhelm and his brother Alexander.',
      'He studied Basque on journeys through the Basque country in 1799 and 1801, and later published a study of it.',
      'His great work on language grew from a study of the Kawi language of Java, and its long introduction, On the Diversity of Human Language Construction, appeared after his death in 1836.',
      'Humboldt wrote an opinion in 1809 in support of civil rights for Jews in Prussia, and the Prussian edict of 1812 granted citizenship to Jews.',
      'He knew many languages, including Greek, Latin, French, English, Basque, Sanskrit and Chinese, and wrote about many more, including languages of the Pacific and the Americas.',
      'His Limits of State Action was only partly printed in his lifetime; the full text appeared in the mid-nineteenth century.',
    ],
    myths: [
      { myth: 'Humboldt founded the University of Berlin as we now picture the “Humboldtian university”.', reality: 'He led the planning for only about sixteen months and left before the university opened. The picture of a unified Humboldtian model of research, teaching and freedom was largely shaped later in the nineteenth century, and historians debate how much of it reflects his own plans.' },
      { myth: 'Humboldt believed language determines thought entirely.', reality: 'He argued that language shapes how speakers see the world, but also that people can step beyond their own language through learning and thought. Strong claims about linguistic determinism came from later writers.' },
      { myth: 'He was the explorer Humboldt.', reality: 'That was his brother Alexander, who travelled through Latin America and wrote Cosmos. The two were close, and Wilhelm’s own travels were mainly in Europe.' },
    ],
    works: [
      { title: 'The Limits of State Action (written 1791–92; published 1851)', note: 'An early, influential statement of liberal limits on the state.' },
      { title: 'Theory of Bildung (c. 1793–94)', note: 'A short fragment on the relation between the self and the world in education.' },
      { title: 'Memoranda on education (1809–10)', note: 'His proposals for Prussian schools and the Berlin university; some texts were not printed until the 1890s.' },
      { title: 'On the Diversity of Human Language Construction (1836)', note: 'The introduction to his study of the Kawi language, and his main work on the philosophy of language.' },
      { title: 'Letters to a Female Friend and the correspondence with Schiller', note: 'Rich sources for his thought and his friendships.' },
    ],
    legacy: [
      'Humboldt’s ideas on education shaped the German university and, through it, universities around the world, especially the research university that links teaching to inquiry. Wherever people argue that higher education should serve free inquiry as well as employment, they draw, knowingly or not, on this tradition.',
      'In political thought he stands as an early liberal, a source for Mill and for debates about the limits of the state. In linguistics his writings on language as activity, on its inner form and its link to thought were an inspiration to later linguists and philosophers such as Steinthal and Cassirer, and to Chomsky, who cited him in his work on creativity in language.',
    ],
  },
]
