import type { Profile } from './types'

export const MORE_18: Profile[] = [
  {
    slug: 'aldous-huxley',
    order: 1894,
    dates: '1894 – 1963',
    place: 'England, then Los Angeles, California',
    era: '20th Century',
    tradition: 'Dystopian fiction and mysticism',
    tagline: 'A satirist who imagined a world enslaved by pleasure, then spent his later years searching for the experience that lies beyond ordinary perception.',
    who: [
      'Aldous Huxley was born in 1894 in Godalming, Surrey, into one of England’s great intellectual families. His grandfather was the biologist T. H. Huxley, “Darwin’s bulldog”, and his brother Julian became a prominent biologist. At about sixteen he caught an eye disease, keratitis punctata, that left him almost blind for a year and a half and ended his plan to become a doctor. He recovered enough sight to read at Balliol College, Oxford, where he studied English literature and graduated in 1916, and he kept poor eyesight for the rest of his life.',
      'He made his name in the 1920s with witty, sceptical novels such as Crome Yellow (1921), then with Brave New World (1932), the book that remains his best known. In 1937 he moved to California with his wife Maria and his friend Gerald Heard, and he stayed in the United States for the rest of his life. Alongside his writing he worked in Hollywood as a screenwriter, studied Eastern and Western mysticism, and became attached to the Vedanta Society of Southern California, led by Swami Prabhavananda, where he met Christopher Isherwood.',
      'In May 1953 he took mescaline under the supervision of the psychiatrist Humphry Osmond and wrote The Doors of Perception (1954) about the experience. After Maria died in 1955 he married Laura Archera in 1956. Huxley died of cancer of the larynx on 22 November 1963 in Los Angeles. At his own written request, Laura gave him LSD in his last hours. His death was overshadowed by the assassination of John F. Kennedy, which took place the same day.',
    ],
    context: [
      'Huxley grew up in the shadow of Darwin and the Victorian debate between science and religion, and he came of age during the First World War, which shattered the confidence of the generation before him. The 1920s and 1930s brought new technologies, mass production, the assembly lines of Henry Ford, advertising, psychology and propaganda, and also the rise of Soviet and fascist states. Huxley watched with unease as science and industry promised a better life while also offering new tools for control.',
      'Many of his contemporaries looked for a replacement for lost faith in politics, science or art. Huxley turned toward a mix of reason and mysticism. In the 1930s he became active in the pacifist movement, supporting the Peace Pledge Union and writing Ends and Means (1937) on how peaceful ends require peaceful means. His move to the United States just before the Second World War, and his decision to remain there, drew criticism from some in Britain, but his pacifist convictions did not change.',
    ],
    ideas: [
      { title: 'A dystopia built on pleasure', text: 'Brave New World pictures a future “World State” in which people are manufactured in hatcheries, sorted into castes, conditioned by repeated suggestions during sleep, and kept content with the drug soma, easy sex and shallow entertainment. Nobody is tortured, and nobody much wants anything else. The book asks whether a society that removes suffering by removing freedom, art, family and deep feeling is a paradise or a trap.' },
      { title: 'Huxley and Orwell compared', text: 'George Orwell’s 1984 (1949) imagines control by fear, surveillance and punishment. Huxley’s book imagines control by pleasure, distraction and engineered desire. In a letter to Orwell in 1949, Huxley argued that the future might look more like his own vision, and in Brave New World Revisited (1958) he said that some of his fears were arriving faster than he had expected. The two books are often read together as two different warnings about the same danger: the loss of independent thought.' },
      { title: 'The doors of perception', text: 'Huxley took the title of his 1954 essay from William Blake’s line about cleansing “the doors of perception”. He described how, under mescaline, ordinary things such as a chair or the folds of a trouser leg appeared overwhelmingly vivid and meaningful. He suggested that the brain acts as a filter, or “reducing valve”, that narrows what we notice so that we can survive, and that certain substances may widen it. Critics, including the Oxford scholar R. C. Zaehner, argued that a drug experience is not the same as the mystical experience described by saints.' },
      { title: 'The perennial philosophy', text: 'In The Perennial Philosophy (1945) Huxley gathered passages from Christian, Hindu, Buddhist, Taoist, Sufi and other mystics, arranging them by theme to argue that they point to a common core: a divine reality that can be known directly, and a human need to loosen the ego in order to know it. The idea is old, and scholars today often question whether the traditions are really as similar as Huxley claimed. The book was nonetheless influential in bringing Eastern thought to Western readers.' },
      { title: 'A utopia of attention', text: 'His last novel, Island (1962), is the other side of Brave New World. On the imaginary island of Pala, people combine Eastern contemplative practice with modern science, small-scale economies, gentle education and a mind-expanding “moksha-medicine”. Birds trained to call out “Attention” and “Here and now, boys” remind the islanders to be present. Huxley did not treat the island as an easy answer, and it is destroyed by outside powers in the story.' },
    ],
    principles: [
      'Means shape ends: you cannot reach peace through violence or freedom through manipulation.',
      'Pay attention to the present moment, which is where life actually happens.',
      'Be wary of comfort and entertainment that make you stop thinking.',
      'Learn from many traditions rather than only your own.',
      'Keep science, the arts and contemplation in conversation with one another.',
    ],
    practice: [
      'Notice which of your habits, devices or pleasures are chosen and which are simply easy, and set aside time each week without them.',
      'Practise a few minutes of undistracted attention each day, on breathing, a view or a single task, and notice how much you normally miss.',
      'Read one text from a tradition far from your own, and look for where it agrees with you and where it truly differs.',
    ],
    facts: [
      'George Orwell is reported to have been briefly taught French by Huxley at Eton during the First World War.',
      'The title Brave New World comes from Shakespeare’s The Tempest, in which Miranda exclaims “O brave new world”.',
      'In 1961 a fire destroyed Huxley’s home in the Hollywood Hills, along with many of his books and papers.',
      'In the early 1940s he learned the Bates method of eye training and described it in The Art of Seeing (1942). Modern ophthalmology rejects the method as ineffective, though Huxley felt it helped him.',
      'He was nominated for the Nobel Prize in Literature but never won it.',
      'He died on the same day as John F. Kennedy and the writer C. S. Lewis, 22 November 1963.',
    ],
    myths: [
      { myth: 'Brave New World was written as a blueprint or an endorsement of a drug-based society.', reality: 'It is a satire. Soma is a tool of control in the book, and the story sides with the Savage who demands the right to be unhappy. Huxley’s later interest in psychedelics was a separate matter, and he never presented drugs as a way to run society.' },
      { myth: 'The Doors of Perception gave the rock band The Doors their name, so Huxley was part of the 1960s counterculture.', reality: 'The band did take its name from Huxley’s title, and Huxley’s essay was widely read in the 1960s. But he was an older man with a measured, intellectual approach, and he advocated careful, supervised use, which differed from the later mass drug culture.' },
      { myth: 'Huxley was blind.', reality: 'He had severely impaired vision after his illness as a teenager, and wrote of using a magnifying glass, but he never lost sight entirely, and he continued reading and writing throughout his life.' },
    ],
    works: [
      { title: 'Brave New World (1932)', note: 'His best-known novel, a satire of technology, consumerism and conditioning.' },
      { title: 'Ends and Means (1937)', note: 'An essay on pacifism, ethics and the link between how we act and what we achieve.' },
      { title: 'The Perennial Philosophy (1945)', note: 'An anthology of mystical writings with Huxley’s commentary.' },
      { title: 'The Doors of Perception (1954)', note: 'His account of the mescaline experience; Heaven and Hell followed in 1956.' },
      { title: 'Island (1962)', note: 'His final novel, a counterpart to Brave New World.' },
    ],
    legacy: [
      'Brave New World, together with 1984 and Yevgeny Zamyatin’s We, forms the core of the modern dystopian tradition. Its themes of engineered happiness, genetic selection, drugs and mass entertainment return in debates about biotechnology, social media and attention, and the book is regularly cited, with varying accuracy, in discussions of present-day life.',
      'His writing on mysticism and consciousness influenced researchers and writers interested in psychedelics, comparative religion and meditation, and many later scholars of religion have either built on or argued against his perennial philosophy. Huxley remains an unusual figure: a satirist who looked for truth beyond satire, and a rationalist who took seriously the possibility that ordinary perception is only part of the picture.',
    ],
  },
  {
    slug: 'friedrich-hayek',
    order: 1899,
    dates: '1899 – 1992',
    place: 'Vienna, London, Chicago and Freiburg',
    era: '20th Century',
    tradition: 'Austrian school economics',
    tagline: 'An economist who argued that no planner can gather the knowledge scattered among millions of people, and who became a leading voice of classical liberalism.',
    who: [
      'Friedrich August von Hayek was born in Vienna on 8 May 1899, into an academic family of scientists and doctors. He served as a young artillery officer in the Austro-Hungarian army in the First World War, and then studied law and political science at the University of Vienna, earning doctorates in 1921 and 1923. Through the Austrian school of economics, associated with Carl Menger and Ludwig von Mises, he turned to the study of money, capital and the business cycle.',
      'In 1931 he moved to the London School of Economics, where his work on the trade cycle made him a leading opponent of John Maynard Keynes. He became a British citizen in 1938. In 1944 he published The Road to Serfdom, written during the Second World War, which brought him a wide public audience. He later taught at the University of Chicago (1950–1962), the University of Freiburg in Germany, and the University of Salzburg in Austria.',
      'Hayek shared the 1974 Nobel Memorial Prize in Economic Sciences with Gunnar Myrdal, a Swedish economist whose political views differed sharply from his own. In his later decades he wrote on law, liberty and the evolution of institutions. He received the Presidential Medal of Freedom in the United States in 1991 and died in Freiburg on 23 March 1992, aged 92.',
    ],
    context: [
      'Hayek’s thinking was formed by the collapse of the Habsburg empire, the inflation in Austria and Germany after the First World War, the Great Depression, and the rise of communism and fascism. He saw economies in which governments claimed to direct production and prices for the common good, and he feared the political cost of that power. Many intellectuals of the 1930s and 1940s believed that central planning was the efficient, modern alternative to a chaotic market, and Hayek took the other side.',
      'After the war the mainstream view in Britain and the United States favoured the welfare state and Keynesian management of the economy, and Hayek was at times isolated. In 1947 he helped found the Mont Pelerin Society, a network of economists and thinkers who defended free markets. His ideas gained a wider political audience from the 1970s, as inflation and slow growth led governments to look again at market-based policies.',
    ],
    ideas: [
      { title: 'The knowledge problem', text: 'In his 1945 essay The Use of Knowledge in Society, Hayek argued that the central problem of economics is not how to allocate known resources but how to use knowledge that is scattered among millions of people and often cannot be written down: the local, practical, changing facts known to a farmer, a shopkeeper or a shipper. No central authority can collect all of it. Prices, he said, work as a signal that coordinates people’s plans without anyone needing to know the whole picture.' },
      { title: 'Spontaneous order', text: 'Some of the most useful human institutions, such as language, law, customs and markets, grew by the interaction of many people, without anyone designing them. Hayek called this a spontaneous order, and contrasted it with an organisation built for a purpose. He warned that reformers who try to redesign society from above may destroy the unseen order that makes cooperation possible.' },
      { title: 'The road to serfdom', text: 'In The Road to Serfdom he argued that economic planning on a large scale, however well meant, tends to concentrate power and to require coercion, since planners must override the differing choices of individuals. He feared that a society that began by planning for security could slide into authoritarianism. The book is often misread: Hayek did not argue that every government intervention leads to tyranny, and he accepted a role for the state in areas such as a basic safety net and public health.' },
      { title: 'The rule of law and liberty', text: 'In The Constitution of Liberty (1960) and Law, Legislation and Liberty (1973–1979), Hayek defended liberty under general rules that apply equally to everyone. He argued that a free society relies on law that is known in advance and not on the commands of officials. He also separated this liberal outlook from conservatism, in an essay titled “Why I Am Not a Conservative”.' },
      { title: 'The debate with Keynes', text: 'In the early 1930s Hayek and Keynes argued about the causes of depressions and what to do about them. Hayek stressed the damage done by credit expansion and the distortion of production, and he was wary of government spending as a remedy. Keynes argued for active public spending to support demand. Keynes criticised Hayek’s Prices and Production sharply, yet in a letter after The Road to Serfdom he wrote that he agreed morally and philosophically with much of it. The two remained on cordial terms.' },
    ],
    principles: [
      'Respect how much you do not know: no single mind sees the whole.',
      'Value the local, practical knowledge of the people closest to a problem.',
      'Be careful with grand plans that require everyone to follow one design.',
      'Defend general rules that apply to all, rather than favours for some.',
      'Hold your own convictions with humility, and with an understanding of why others differ.',
    ],
    practice: [
      'Before deciding a question for others, ask who has the relevant local knowledge, and how you could hear from them.',
      'Treat prices, feedback and experience as information, and notice what they are telling you.',
      'When you want to reform something old, find out first why it grew up that way, and what it quietly does.',
    ],
    facts: [
      'Hayek was a distant relative of the philosopher Ludwig Wittgenstein.',
      'The Road to Serfdom became a surprise bestseller in Britain and the United States, helped by a condensed version published in Reader’s Digest in 1945.',
      'He shared the 1974 Nobel Prize with Gunnar Myrdal, a social-democratic economist whose politics opposed his, and the two were not close.',
      'He also wrote on psychology, publishing The Sensory Order (1952), a theory of how the mind organises experience.',
      'In the 1950s he took a post at the University of Chicago in the Committee on Social Thought, not in the economics department.',
      'He suffered long periods of depression, particularly in the 1960s, before returning to productive work.',
    ],
    myths: [
      { myth: 'Hayek opposed all government action and wanted no welfare state.', reality: 'In The Road to Serfdom and later works he accepted that the state may provide a minimum income, social insurance and public health measures, provided they are consistent with a competitive market. He objected to central direction of the economy, not to every public programme.' },
      { myth: 'Hayek and Keynes were bitter personal enemies.', reality: 'They disagreed fiercely in print, but they were on good terms. Keynes wrote warmly about The Road to Serfdom, and during the war the two shared fire-watching duty at King’s College, Cambridge.' },
      { myth: 'Hayek is simply the thinker behind the market policies of Margaret Thatcher and Ronald Reagan.', reality: 'Both leaders admired him, and he was honoured in both countries. But Hayek distanced himself from the label conservative, and how far his writings drove their policies is debated. His influence was one among several.' },
    ],
    works: [
      { title: 'Prices and Production (1931)', note: 'His business cycle theory, which prompted the exchange with Keynes.' },
      { title: 'The Road to Serfdom (1944)', note: 'His most widely read book, a warning about central planning.' },
      { title: 'The Use of Knowledge in Society (1945)', note: 'A short essay, widely cited, on knowledge and prices.' },
      { title: 'The Constitution of Liberty (1960)', note: 'His main statement of liberal political philosophy.' },
      { title: 'Law, Legislation and Liberty (1973–1979)', note: 'A three-volume work on law, order and democracy; The Fatal Conceit (1988) was his last major book.' },
    ],
    legacy: [
      'Hayek’s ideas about knowledge and prices became part of mainstream economics, and the knowledge problem is discussed in debates about planning, markets, organisations and, more recently, data and technology. His defence of spontaneous order influenced thinkers in law, economics, politics and the study of complex systems. Many economists who do not share his politics acknowledge the force of his argument about dispersed information.',
      'He has also been criticised. Some argue that his picture of markets understates inequality, unequal power and the need for strong public provision, and that he underplayed how much states have contributed to economic development. His views on democracy and dictatorship drew particular controversy. He visited Chile in 1977 and 1981, when it was ruled by General Augusto Pinochet, and in letters to The Times he wrote that personal freedom in Chile was greater under Pinochet than it had been under the previous government of Salvador Allende, and in a 1981 interview with the newspaper El Mercurio he said that he opposed dictatorship as a lasting system but that it might be necessary for a transitional period. Defenders say his comments were limited and that he favoured liberty above all, while critics say he was too ready to excuse a regime responsible for serious human rights abuses. Historians continue to debate what he knew and how much weight his remarks deserve.',
    ],
  },
  {
    slug: 'antoine-de-saint-exupery',
    order: 1900,
    dates: '1900 – 1944',
    place: 'Lyon, the Sahara, Argentina, New York and southern France',
    era: '20th Century',
    tradition: 'Humanist literature',
    tagline: 'A pilot who wrote about flight, the desert and the bonds between people, and whose small book about a prince became one of the most translated works in the world.',
    who: [
      'Antoine de Saint-Exupéry was born in Lyon on 29 June 1900 into an aristocratic family that was not wealthy. His father died when he was a small child, and he grew up in the care of his mother and in family châteaux, which he recalled as a lost kingdom of childhood. As a young man he failed the entrance exam for the naval academy, did military service, and in 1926 joined the airmail company that later became Aéropostale, flying mail between Toulouse and Dakar over Spain, Morocco and the Sahara.',
      'Flying mail in the 1920s and 1930s was dangerous work, with open cockpits, poor maps and few instruments. He served as head of a remote airfield at Cape Juby in the Sahara, where he lived among the local people, and later worked in Argentina, helping to open air routes across South America. His first novel, Courrier sud (1929), was followed by Vol de nuit (Night Flight, 1931), which won the Prix Femina. In 1931 he married Consuelo Suncín. In December 1935 he crashed in the Libyan desert with his mechanic-navigator André Prévot, and the two walked for days before a Bedouin found them.',
      'When the Second World War began, he flew reconnaissance missions with the French air force and described one of them, over Arras in 1940, in Pilote de guerre. After the fall of France he spent about two years in the United States, and in 1943 he published The Little Prince there. He then rejoined the Free French forces in North Africa, though he was well above the usual age for a pilot, and he disappeared on a reconnaissance flight from Corsica on 31 July 1944.',
    ],
    context: [
      'Saint-Exupéry belonged to the pioneering age of aviation, when flying was still an adventure and a new way of seeing the Earth. Airmail linked Europe to Africa and South America, and the pilots were seen as modern heroes. He wrote about the work with a mixture of poetry and moral seriousness, treating the aeroplane as a tool that brought people closer to the essential things, and not simply as a machine.',
      'He also lived through the First World War’s aftermath and the Second World War, and the fall of France in 1940 divided French people. Saint-Exupéry was in exile in New York, where he felt homesick and was criticised by rival groups of French exiles who disagreed about whether to support Vichy or de Gaulle. He kept out of the quarrels and wrote with hope for a France that would be reunited. Some of his writings were banned under the occupation, and they were widely read after liberation.',
    ],
    ideas: [
      { title: 'To be human is to be responsible', text: 'In Terre des hommes (Wind, Sand and Stars, 1939), he wrote that to be a man is to be responsible, to feel shame at what seems unjust, and to feel that one adds a stone to the building of the world. For Saint-Exupéry responsibility was not a burden imposed from outside but the thing that gives life weight. Pilots who carried the mail for others, he said, discovered it in the plainest form.' },
      { title: 'Brotherhood and looking in the same direction', text: 'He wrote that love does not consist of gazing at each other but of looking together in the same direction. He saw deep ties among people who share a task, such as crews, pilots and comrades, more than among those who simply gaze at one another. The aim is not isolation but a shared effort toward something larger than oneself.' },
      { title: 'The little prince and what is essential', text: 'The Little Prince (1943) tells of a pilot stranded in the Sahara who meets a small boy from a tiny asteroid. The fox’s secret, that one sees well only with the heart because what is essential is invisible to the eye, and the rule that you become responsible for what you have tamed, are the best-known lines. Readers have taken the book as a fable about childhood and the narrowness of adult values, about friendship and loss, and about love: the vain and delicate rose is often linked to Saint-Exupéry’s complicated marriage to Consuelo.' },
      { title: 'The desert and the meaning of life', text: 'His crash in the Libyan desert and the near-death experience that followed became a lasting image of how stripped-down conditions reveal what matters. In Wind, Sand and Stars he describes the thirst, the mirages and the thought of those waiting for him. The desert, in his writing, is empty and yet it makes a person more aware of water, of friends and of the value of every hour.' },
      { title: 'Citadelle and the building of a civilisation', text: 'Citadelle (published after his death in 1948 as The Wisdom of the Sands) is an unfinished work in which a desert ruler reflects on how to build a lasting community. Saint-Exupéry did not live to complete it, and its aphoristic, sometimes authoritarian-sounding passages have divided readers. Its central view is that a person is defined by the bonds and tasks he takes on, and that meaning is built by effort and sacrifice, not handed over by comfort.' },
    ],
    principles: [
      'Take responsibility for those who depend on you and for the people you have drawn close.',
      'Look beneath surfaces: what matters most is often not obvious.',
      'Find meaning in shared work and shared purposes.',
      'Do not let numbers and routine crowd out wonder and friendship.',
      'Keep something of the child’s curiosity as you grow older.',
    ],
    practice: [
      'Think of one person or task you have taken on, and ask whether you are giving it real attention, not just time.',
      'Before judging a person or a situation, ask what you may be missing that is not visible at first glance.',
      'Choose a shared project, even a small one, and see how it changes your relationship with the people involved.',
    ],
    facts: [
      'He held a pilot’s licence from the early 1920s and also patented several inventions related to flying.',
      'Wind, Sand and Stars won the Grand Prix du roman of the Académie française in 1939 and, in its American edition, a U.S. National Book Award.',
      'He wrote and illustrated The Little Prince himself, with watercolours, while living in New York and on Long Island. It first appeared in 1943, in English and in French, in New York, and French readers in France did not get it until after the war.',
      'A silver identity bracelet engraved with his name and the details of his American publisher was found by a fisherman off Marseille in 1998.',
      'In 2000 a diver located the remains of a Lockheed P-38 Lightning on the sea floor near Riou Island, and the wreck was identified in 2003 by its serial number and recovered that year.',
      'The Little Prince has been translated into hundreds of languages and dialects and is among the most translated books ever published.',
    ],
    myths: [
      { myth: 'We know exactly how Saint-Exupéry died.', reality: 'We know when and roughly where his plane fell, but not why. The wreck found near Marseille shows he crashed into the sea, yet it has not established whether his plane was shot down, suffered a mechanical failure, or he lost consciousness. In 2008 a former German pilot, Horst Rippert, said he might have shot down his plane, but historians have questioned his account and it remains unproven.' },
      { myth: 'The Little Prince is just a children’s book.', reality: 'It is written in the form of a children’s tale, but it is a reflection on loneliness, friendship, love and the loss of wonder that is directed to adults, and its dedication is to a friend, Léon Werth, a Jewish writer, who was in hiding in France at the time.' },
      { myth: 'He wrote the book as a deliberate allegory with one fixed meaning.', reality: 'Saint-Exupéry did not explain it. Readings that map every character to a real person, a political position or a religious doctrine are interpretations, and many have been proposed. The text supports several at once.' },
    ],
    works: [
      { title: 'Vol de nuit (Night Flight, 1931)', note: 'A short novel about the duty and cost of night airmail, with a preface by André Gide.' },
      { title: 'Terre des hommes (Wind, Sand and Stars, 1939)', note: 'A memoir in essays about flying, the Libyan desert crash and human solidarity.' },
      { title: 'Pilote de guerre (Flight to Arras, 1942)', note: 'An account of a reconnaissance mission in 1940 during the defeat of France.' },
      { title: 'Le Petit Prince (The Little Prince, 1943)', note: 'His best-known work, written and illustrated by himself.' },
      { title: 'Citadelle (1948)', note: 'An unfinished, posthumous collection of reflections, assembled from his manuscripts.' },
    ],
    legacy: [
      'The Little Prince has sold many millions of copies and has been adapted for stage, screen, opera and many other forms. Its lines on seeing with the heart are quoted around the world, and the book is a fixture of language classes and school curricula. It has also kept Saint-Exupéry’s name alive far beyond his other writings.',
      'His disappearance and the discoveries made decades later added to his fame. Airlines, airports and institutions in France bear his name, and the sense that he vanished while flying has become part of how readers see him. Critics note that Citadelle remains less admired and less read than his earlier works, and that some readers find his emphasis on duty and hierarchy hard to accept. Still, his belief that people find meaning in responsibility and shared effort continues to speak to readers.',
    ],
  },
  {
    slug: 'theodor-w-adorno',
    order: 1903,
    dates: '1903 – 1969',
    place: 'Frankfurt, Oxford, New York, Los Angeles and Frankfurt again',
    era: '20th Century',
    tradition: 'Critical theory',
    tagline: 'A philosopher, sociologist and musician who asked how a civilisation built on reason could end in catastrophe, and whether mass culture helps keep people docile.',
    who: [
      'Theodor Ludwig Wiesengrund, who later took the name Adorno from his mother’s family, was born in Frankfurt on 11 September 1903. His father was a Jewish wine merchant and his mother, Maria Calvelli-Adorno, a singer of Catholic Italian-Corsican descent. The household was full of music, and he trained as a pianist and composer. He studied philosophy at Frankfurt, wrote on Husserl, and in 1925 went to Vienna to study composition with Alban Berg, a pupil of Arnold Schoenberg.',
      'After the Nazis came to power in 1933 he lost his right to teach because of his Jewish background. He left Germany, spent time at Oxford, and in 1938 moved to New York to work with the Institute for Social Research, which had been relocated there. In 1941 he joined Max Horkheimer in Los Angeles, where the two wrote Dialectic of Enlightenment, first circulated in 1944 and published as a book in 1947. Among his neighbours in exile was the novelist Thomas Mann, whom he advised on the musical passages in Doctor Faustus.',
      'He returned to Frankfurt in 1949 and became a professor and, with Horkheimer, a director of the reopened Institute. Through the 1950s and 1960s he published widely on philosophy, sociology, music and literature, among them Minima Moralia (1951) and Negative Dialectics (1966). He died of a heart attack on 6 August 1969 in Visp, Switzerland, during a holiday, a few months after a bitter conflict with student radicals.',
    ],
    context: [
      'Adorno belonged to the first generations of the Frankfurt School, a group of Marxist-influenced thinkers, mostly of Jewish background, who tried to understand why the revolution Marx expected had not happened in the industrial West, and why a cultured country such as Germany had turned to Nazism. They drew on Marx, Hegel, Freud and Weber, and gave their approach the name critical theory: a theory that aims not only to describe society but to criticise it and to help change it.',
      'The Holocaust and the experience of exile shaped everything Adorno wrote afterward. In America he saw a different kind of mass society: Hollywood, radio and advertising, which he regarded as more subtle than a dictatorship but still capable of shaping how people think. After the war he took part in the public life of the Federal Republic of Germany, giving radio talks such as “Education after Auschwitz” (1966) and arguing that German society had not properly confronted its past.',
    ],
    ideas: [
      { title: 'The dialectic of enlightenment', text: 'In Dialectic of Enlightenment, Adorno and Horkheimer argued that the Enlightenment aim of freeing humanity from fear by mastering nature through reason has a dark side. Reason that is used only to dominate and calculate can turn into a new kind of myth and become a tool of control, including of people over other people. They saw Nazism and the modern administered world as consequences of that tendency and not as a simple relapse into barbarism.' },
      { title: 'The culture industry', text: 'A chapter of the same book describes the “culture industry”: film, radio, popular music and advertising, produced like goods on an assembly line. Adorno argued that these products offer standardised entertainment that distracts and adapts people to the existing order, while giving the impression of choice. He deliberately avoided the term “mass culture” so as not to suggest that it springs up from the people themselves. Critics reply that he underrated the intelligence of audiences and was dismissive of jazz and popular music, which he knew poorly.' },
      { title: 'Negative dialectics', text: 'In Negative Dialectics (1966) Adorno argued that concepts never fully capture the things they describe, and that thinking must stay alert to what escapes it, which he called the non-identical. Philosophy that claims to reach a final system, as he thought Hegel’s did, covers over suffering and difference. His thought is a discipline of criticism that does not offer a neat resolution. Among his most quoted lines is that “the whole is the false”, and that “wrong life cannot be lived rightly”.' },
      { title: 'Poetry after Auschwitz', text: 'In a 1949 essay he wrote that to write poetry after Auschwitz is barbaric. He was criticising a culture that could treat the catastrophe as material for refined enjoyment, and not forbidding poets to write. Later, in Negative Dialectics, he accepted that suffering has as much right to expression as a tortured man has to scream, and that his earlier statement may have been wrong. He kept the deeper question: whether, after Auschwitz, one can go on living, especially someone who survived by chance.' },
      { title: 'Music as philosophy', text: 'Adorno held that serious music contains in its form a kind of truth about society. In Philosophy of New Music (1949) he contrasted Schoenberg, whom he admired for refusing easy consolation, with Stravinsky, whom he accused of surrendering to collective power. His Aesthetic Theory, left unfinished and published in 1970, argues that autonomous art criticises society by its very difficulty. His enthusiasm for the Second Viennese School shaped how many people think of twentieth-century music.' },
    ],
    principles: [
      'Do not let the concept replace the thing: stay alert to what an idea leaves out.',
      'Resist comfort and slogans, and think again when something comes too easily.',
      'Pay attention to suffering, and let it set the standard for thought.',
      'Treat culture seriously: what people watch and hear shapes how they think.',
      'Try to educate so that atrocity cannot happen again.',
    ],
    practice: [
      'Notice which of your entertainment choices are chosen, and which are simply fed to you, and try one thing that asks for effort.',
      'When you describe a person or situation in a label, ask what the label leaves out.',
      'Listen to a piece of music slowly and completely, with no other task, and note how it unfolds.',
    ],
    facts: [
      'Adorno was a trained composer and wrote songs, string quartets and other pieces.',
      'He wrote part of Dialectic of Enlightenment in Pacific Palisades, California, in the 1940s.',
      'His sentence about poetry after Auschwitz is one of the most quoted lines of twentieth-century philosophy, though it is often cut off from the essay it appeared in.',
      'In April 1969 students disrupted his lecture, and three women bared their breasts and scattered flower petals at him. He left the hall.',
      'In January 1969 he called the police to clear students who had occupied the Institute for Social Research building, a move that deepened the quarrel with the student movement.',
      'He died of a heart attack in the Swiss Alps, after, according to accounts, taking a mountain walk against medical advice.',
    ],
    myths: [
      { myth: 'Adorno said that poetry is impossible after Auschwitz.', reality: 'His remark was about the barbarity of a culture that could carry on as before and aestheticise suffering. Later he conceded that suffering needs expression and that the line may have been wrong. He also admired the poetry of Paul Celan.' },
      { myth: 'Adorno simply hated popular culture and loved only the elite.', reality: 'He argued that popular culture produced by industry reinforces conformity, and his remarks on jazz are widely seen as uninformed. But he also criticised high culture that became a consumer commodity, and he was as severe about the concert hall as about the cinema.' },
      { myth: 'He supported the 1960s student movement or opposed it entirely.', reality: 'He shared many of the students’ criticisms of society, but he rejected what he saw as hasty action and violence, and he feared that it would play into the hands of reaction. The relationship was strained and ended sadly in 1969.' },
    ],
    works: [
      { title: 'Dialectic of Enlightenment (with Max Horkheimer, 1944/1947)', note: 'A founding text of critical theory, including the chapter on the culture industry.' },
      { title: 'Minima Moralia (1951)', note: 'Short reflections written in exile on damaged life.' },
      { title: 'Philosophy of New Music (1949)', note: 'An essay on Schoenberg and Stravinsky.' },
      { title: 'Negative Dialectics (1966)', note: 'His main philosophical work, a critique of systematic thought.' },
      { title: 'Aesthetic Theory (1970)', note: 'An unfinished work on art, published after his death.' },
    ],
    legacy: [
      'Adorno shaped critical theory, sociology, aesthetics, musicology and cultural studies. His ideas about the culture industry are still a reference point in debates about advertising, streaming, social media and entertainment, whether people agree with him or not. The Frankfurt School continued through Jürgen Habermas, who departed from Adorno’s pessimism but built on his questions.',
      'His reception has been mixed. Admirers value the uncompromising rigour of his thought and his insistence that philosophy face suffering. Critics find him elitist, obscure and gloomy, point out that his account of mass culture neglects how audiences interpret what they consume, and question whether a theory that seems to leave no room for effective resistance can guide action. His books continue to be read, argued with, and used in discussions of how to think about modern society.',
    ],
  },
  {
    slug: 'emmanuel-levinas',
    order: 1906,
    dates: '1906 – 1995',
    place: 'Kaunas, Lithuania; Strasbourg, Freiburg and Paris',
    era: '20th Century',
    tradition: 'Ethics and phenomenology',
    tagline: 'A philosopher who argued that ethics comes before everything else, and that it begins in the face of another person.',
    who: [
      'Emmanuel Levinas was born on 12 January 1906 in Kaunas (Kovno), Lithuania, then part of the Russian Empire, into a Lithuanian-Jewish family. He grew up reading the Hebrew Bible and also Russian literature, particularly Pushkin, Dostoevsky and Tolstoy. During the First World War the family moved to Ukraine and returned to Lithuania in 1920. In 1923 he went to study in Strasbourg in France, where he became a friend of the writer Maurice Blanchot.',
      'In 1928–1929 he studied at the University of Freiburg with Edmund Husserl, the founder of phenomenology, and heard Martin Heidegger, whose Being and Time deeply impressed him. His study of Husserl’s theory of intuition, published in 1930, helped introduce phenomenology to France. He became a French citizen and in 1939 was drafted into the French army as an interpreter of Russian and German. He was captured in 1940 and spent the rest of the war as a prisoner, held at Stalag XI-B near Hanover, where he did forced labour.',
      'His wife Raïssa and their daughter were hidden in a convent, with help from Blanchot. Most of his family in Lithuania, including his father and brothers, were killed during the Nazi occupation in 1941. After the war he became director of a school for Jewish teachers in Paris, studied Talmud with a mysterious teacher known as Monsieur Chouchani, and slowly built an academic career, teaching at Poitiers, Nanterre and the Sorbonne. He died in Paris on 25 December 1995.',
    ],
    context: [
      'Levinas’s thought comes from two worlds. One is the phenomenology of Husserl and Heidegger, which aimed to describe experience as it appears. The other is the Jewish tradition of Talmudic study that he knew from his Lithuanian background, in which texts are read through argument and commentary. He worked in the French language and in the intellectual life of postwar Paris, where he stood somewhat apart from the fashionable existentialists.',
      'The Second World War and the Holocaust shaped his work deeply, though he rarely wrote about them directly. Otherwise than Being is dedicated to the victims of the Nazi persecutions, and names members of his family. His philosophy is often read as a response to the question of how a civilisation that prized knowledge and reason could allow such violence: his answer was that ethics must come before knowledge and being.',
    ],
    ideas: [
      { title: 'Ethics as first philosophy', text: 'Western philosophy, Levinas argued, has usually begun with knowledge or with being, and has tried to bring everything under one system. He held that the meeting with another person is more basic. Before we know or understand anything, we are already addressed by someone and responsible to them. Ethics is therefore not a branch of philosophy that comes after metaphysics, but its starting point.' },
      { title: 'The face of the Other', text: 'The “face” in Levinas is not just a visible face. It is the way another person appears as a presence that cannot be reduced to an object I can grasp, possess or control. The face both exposes the other’s vulnerability and issues a demand, and it says, in effect, that I must not kill. Levinas thought this demand comes before any choice of mine, so that responsibility for the other is something I find myself already in.' },
      { title: 'Totality and Infinity', text: 'In his first major work, Totality and Infinity (1961), he criticised philosophies of “totality”, which make every individual a part of a larger whole, whether history, the state or a system of thought. He opposed to them the idea of the infinite: the other person always exceeds any category I place them in. War, for Levinas, is what happens when people are reduced to roles in a totality, and ethical peace comes from respecting what cannot be reduced.' },
      { title: 'Otherwise than Being', text: 'His second major work, Otherwise than Being or Beyond Essence (1974), is more difficult and more radical in style. Here he distinguishes the “saying”, the openness of one person to another in speaking, from the “said”, the content that can be stated and systematised. He describes the self as a “hostage” to the other and as being responsible even for the other’s responsibility. The book also deals with the “third party”, the other people who make justice and institutions necessary, because I cannot respond to all others in the same direct way.' },
      { title: 'Talmudic readings and philosophy', text: 'Alongside his philosophical works Levinas published a series of Talmudic readings, such as Nine Talmudic Readings, and essays on Judaism, collected in Difficult Freedom (1963). He kept the two kinds of writing distinct, saying that his philosophy should be argued on its own terms and not on the basis of scripture. Yet readers see in both the same concerns: the primacy of responsibility, the dignity of the stranger, and the idea that Torah study is a way of attending to others.' },
    ],
    principles: [
      'Responsibility for others comes before your own plans and preferences.',
      'Do not reduce another person to a category, a role or a use.',
      'Listen first: let the other person be heard before you decide who they are.',
      'Remember that justice is needed because there are many others, and not just one.',
      'Treat reading and argument as a form of moral attention.',
    ],
    practice: [
      'In your next conversation, put aside your own agenda for a few minutes and give the other person your full attention.',
      'When you are about to label someone, pause and ask what you do not know about them.',
      'Choose a text you find difficult and read it slowly, with a partner if you can, and treat the disagreements as part of the learning.',
    ],
    facts: [
      'Levinas translated Husserl’s Cartesian Meditations into French with Gabrielle Peiffer, published in 1931.',
      'In a brief essay about his captivity, “The Name of a Dog, or Natural Rights”, he recalled a stray dog that greeted the prisoners as they marched to and from work, and called it the last Kantian in Nazi Germany.',
      'His wife Raïssa and daughter Simone were sheltered in a convent in France while he was a prisoner.',
      'The mysterious teacher known as Monsieur Chouchani, with whom he studied the Talmud after the war, also taught the writer Elie Wiesel.',
      'He wrote that Heidegger’s Being and Time was among the finest books in the history of philosophy, and also that Heidegger’s Nazi involvement was something he could not forgive.',
      'He was a late-blooming public figure: his main works came out in his fifties and later, and he became widely known in France and abroad only in his later decades.',
    ],
    myths: [
      { myth: 'Levinas’s ethics is just a religious teaching in philosophical clothing.', reality: 'He insisted on a distinction between his philosophy, which is argued without appeal to revelation, and his Jewish writings. Many readers still find echoes of the Bible and Talmud in his thought, and critics, such as Jacques Derrida in his 1964 essay “Violence and Metaphysics”, asked whether the language of philosophy could support what he wanted to say.' },
      { myth: 'He thought we must love everyone equally, with no place for law or politics.', reality: 'Levinas saw that the presence of more than one other requires justice, comparison and institutions. The “third party” appears for exactly this reason, so ethical asymmetry and political equality have to be held together.' },
    ],
    works: [
      { title: 'Existence and Existents (1947) and Time and the Other (1948)', note: 'Early works developed partly in captivity, with the idea of the anonymous “there is”.' },
      { title: 'Totality and Infinity (1961)', note: 'His first great work, on ethics and the face of the other.' },
      { title: 'Difficult Freedom (1963)', note: 'Essays on Judaism, with his reflections on Jewish thought and modern life.' },
      { title: 'Otherwise than Being or Beyond Essence (1974)', note: 'His second major work, on responsibility, saying and substitution.' },
      { title: 'Nine Talmudic Readings (1968–1975)', note: 'Commentaries delivered at Jewish intellectual colloquia, with an English edition of 1990.' },
    ],
    legacy: [
      'Levinas became one of the most influential philosophers of the later twentieth century. His idea that ethics precedes ontology influenced Jacques Derrida, who admired and questioned him, and shaped debates in continental philosophy, theology, literary theory and political thought. His language of the face, responsibility and the vulnerability of the other is widely used in medicine, nursing, education and the study of conflict.',
      'He has also drawn criticism. Feminist thinkers, among them Simone de Beauvoir and Luce Irigaray, questioned his use of the feminine, and others find his style hard to turn into practice. His relation to Heidegger is complex: he owed him a great debt as a philosopher and condemned him as a man, and he thought philosophy had to resist what Heidegger’s choices represented. In a 1982 radio interview after the massacres at Sabra and Shatila in Lebanon, he was asked whether Israelis had an obligation to the Palestinians as “the other”, and his answer, which distinguished between the neighbour and the other, has been debated ever since. Readers disagree about how to interpret those remarks and how they fit his philosophy.',
    ],
  },
]
