import type { Profile } from './types'

export const MORE_07: Profile[] = [
  {
    slug: 'galileo-galilei',
    order: 1564,
    dates: '1564 – 1642',
    place: 'Pisa, Padua and Florence, Italy',
    era: 'Early Modern',
    tradition: 'Scientific revolution',
    tagline: 'He pointed a telescope at the sky, argued that nature is written in mathematics, and ended his life under house arrest for defending a moving Earth.',
    who: [
      'Galileo Galilei was born in Pisa in 1564, the eldest son of Vincenzo Galilei, a musician and music theorist who tested old theories against experiment. Galileo began to study medicine at the University of Pisa but turned to mathematics, and after teaching in Pisa he became professor of mathematics at the University of Padua in 1592. There he taught for about eighteen years, studied motion and mechanics, and built instruments for sale. He never married, but had three children with Marina Gamba, and his elder daughter Virginia became a nun and took the name Sister Maria Celeste.',
      'In 1609 he heard of a Dutch device that made distant objects look near. He built his own telescopes, improved them quickly, and turned them on the heavens. The results, published in March 1610 as Sidereus Nuncius (“The Starry Messenger”), made him famous across Europe: mountains on the Moon, countless faint stars in the Milky Way, and four moons circling Jupiter. He named the moons after the Medici family and soon left Padua to become court mathematician and philosopher to the Grand Duke of Tuscany in Florence.',
      'His later years were dominated by the question of whether the Earth moves. In 1616 the Church’s authorities warned him not to hold or defend the Copernican view as true. In 1632 he published the Dialogue Concerning the Two Chief World Systems, and in 1633 the Roman Inquisition found him “vehemently suspected of heresy”. He recanted and spent the rest of his life under house arrest near Florence, where he went blind but still completed his last great book, the Two New Sciences, published in 1638. He died in January 1642.',
    ],
    context: [
      'When Galileo was young, most university teachers still followed Aristotle: the heavens were perfect and unchanging, heavy things fell faster than light ones, and the Earth sat at the centre of the universe. Copernicus had proposed in 1543 that the Earth circles the Sun, but few astronomers took this as a literal description rather than a calculating device. The Reformation and the Catholic response to it had made Church authorities anxious about anyone reinterpreting Scripture, and the old science was bound up with theology and university teaching.',
      'Galileo wrote in a Europe of new instruments, wealthy patrons and printed books. Courts such as the Medici in Florence wanted clever mathematicians and spectacular discoveries, and a telescope could provide both. Seeing new things in the sky gave Galileo evidence, not just argument, and he used it with a skill for showmanship that also made him powerful enemies.',
    ],
    ideas: [
      { title: 'The telescope as evidence', text: 'The moons of Jupiter showed that not everything orbits the Earth. The mountains and craters on the Moon suggested that heavenly bodies are rough, earthlike places and not perfect spheres. Late in 1610 he saw that Venus goes through phases like the Moon, which fits a Venus orbiting the Sun and does not fit the old Earth-centred model of Ptolemy. These were observations that others could check with their own telescopes.' },
      { title: 'The book of nature is written in mathematics', text: 'In The Assayer (1623) he wrote that the universe is like a great book, written in the language of mathematics, with triangles, circles and other figures as its letters. The idea was that nature follows precise, measurable patterns, and that the way to learn them is to measure, not to quote authorities. This view shaped the whole of modern physics.' },
      { title: 'Experiment and idealisation', text: 'Galileo studied falling and rolling bodies by timing balls on inclined planes, and he concluded that falling bodies speed up in a regular way, covering distances that grow with the square of the time. He imagined situations that cannot be built exactly, such as motion with no friction, and used them to reach simple laws. The famous story of dropping weights from the Leaning Tower of Pisa comes from his later pupil and biographer Vincenzo Viviani, and historians doubt it happened.' },
      { title: 'Relativity of motion', text: 'If the Earth moves, why do we not feel it? In the Dialogue he answered with the image of a ship: a person below deck, with a closed cabin, cannot tell by any experiment whether the ship is moving smoothly or standing still. Uniform motion is shared by everything on board, so it is not detectable from within. This was an important step toward the later principle of relativity.' },
      { title: 'Science and Scripture', text: 'In a long letter to the Grand Duchess Christina, written in 1615 and circulated in manuscript, he argued that the Bible and nature both come from God and cannot truly contradict one another. He held that Scripture is meant to teach salvation, not astronomy, and quoted a saying often attributed to Cardinal Baronio that the Bible tells how to go to heaven, not how the heavens go. Where demonstrated science and the plain words of Scripture seem to clash, he argued, the text should be read in a way that fits what has been proved.' },
    ],
    principles: [
      'Look for yourself, and trust measurement over authority.',
      'Look for the simple mathematical pattern behind complicated behaviour.',
      'Simplify the problem: ask what would happen in the ideal case.',
      'Let evidence change your mind, and be honest about what it does and does not show.',
      'Do not mix questions of faith with questions of fact, but do not assume they must be enemies.',
    ],
    practice: [
      'When a claim is repeated with confidence, find out whether anyone has measured it, and try a small test of your own.',
      'Break a messy problem into a simpler version: remove one complication at a time and see what stays true.',
      'Present your ideas with the evidence that others can check, and consider how they will land with people who disagree.',
    ],
    facts: [
      'The Dutch spectacle-maker Hans Lipperhey applied for a patent on a telescope in 1608. Galileo did not invent the telescope, but he greatly improved it and was among the first to use it systematically on the sky.',
      'He named Jupiter’s four large moons the “Medicean Stars” after Cosimo II de’ Medici and his brothers. Today they are called the Galilean moons: Io, Europa, Ganymede and Callisto.',
      'In the Dialogue, the follower of the old view is named Simplicio. Pope Urban VIII, once a friend and admirer of Galileo, is said to have felt that the character mocked him, though historians still debate how far that explains the trial.',
      'The Inquisition sentenced him on 22 June 1633, banned the Dialogue and ordered him to recant. He lived under house arrest for the last years of his life, at Arcetri near Florence.',
      'The Two New Sciences, his last major book, was smuggled out of Italy and printed in Leiden in 1638.',
      'In 1992 Pope John Paul II acknowledged that errors had been made in the handling of the Galileo case.',
    ],
    myths: [
      { myth: 'After recanting, Galileo muttered “Eppur si muove” (“And yet it moves”).', reality: 'The phrase is almost certainly a legend. It appears in print more than a century after his death, and no contemporary account of the trial mentions it.' },
      { myth: 'Galileo was tortured and imprisoned in a dungeon.', reality: 'He was threatened and questioned under the formal procedure of the Inquisition, but there is no evidence that he was tortured. His sentence was a form of house arrest in comfortable surroundings, though it ended his freedom to publish and travel.' },
      { myth: 'The Church simply opposed science, and Galileo was alone against it.', reality: 'The affair was tangled with theology, patronage, personal quarrels and politics. Jesuit astronomers confirmed many of his observations, and some churchmen supported him. Many of his opponents were professors who disagreed on scientific grounds as well.' },
    ],
    works: [
      { title: 'Sidereus Nuncius (1610)', note: 'A short report of his first telescopic discoveries: the Moon, the stars and Jupiter’s moons.' },
      { title: 'Letter to the Grand Duchess Christina (1615)', note: 'His argument about how to read Scripture in light of science. It was circulated in manuscript and printed later.' },
      { title: 'The Assayer (1623)', note: 'A polemic on comets that contains his famous passage on the book of nature and mathematics.' },
      { title: 'Dialogue Concerning the Two Chief World Systems (1632)', note: 'A lively conversation among three speakers comparing the Ptolemaic and Copernican views, and the book that led to his trial.' },
      { title: 'Discourses and Mathematical Demonstrations Concerning Two New Sciences (1638)', note: 'His founding work on the strength of materials and on motion.' },
    ],
    legacy: [
      'Galileo’s work on motion, along with the telescope’s discoveries, helped open the way to Newton, who built a single mathematical physics for earth and sky. His example of combining careful measurement, mathematical description and bold simplification became a model of how physical science is done.',
      'His trial became a lasting symbol in debates about science, religion and freedom of inquiry, and it is often told as a simple story of conflict. Historians stress the complexity of the case, but few doubt that his condemnation harmed the Church’s standing and made scientists in Italy more cautious. The moons of Jupiter, the Galileo spacecraft and the Galilean transformation of physics all carry his name.',
    ],
  },
  {
    slug: 'johannes-kepler',
    order: 1571,
    dates: '1571 – 1630',
    place: 'Graz, Prague and Linz (Habsburg lands)',
    era: 'Early Modern',
    tradition: 'Scientific revolution',
    tagline: 'A devout Lutheran astronomer who found that the planets move in ellipses, and who believed that the heavens reflect a divine harmony.',
    who: [
      'Johannes Kepler was born on 27 December 1571 in Weil der Stadt, in southwestern Germany, into a family that had once been prosperous but had fallen on hard times. He was a sickly child. A scholarship took him to the Protestant university at Tübingen, where he trained for the Lutheran ministry and learned from the astronomer Michael Maestlin that Copernicus’s Sun-centred system could be defended. In 1594 he accepted a post teaching mathematics in Graz, in Austria, instead of becoming a pastor.',
      'In 1596 he published the Mysterium Cosmographicum, his first attempt to explain why the six known planets are spaced as they are. It brought him notice from Tycho Brahe, the greatest observer of the age, and when Protestants were forced out of Graz he joined Tycho near Prague in 1600. Tycho died in 1601, and Kepler became imperial mathematician at the court of Emperor Rudolf II. Using Tycho’s precise records of Mars, he worked for years on the planet’s orbit and published his first two laws in Astronomia Nova in 1609.',
      'His life was hard. His first wife and one of his children died in 1611, and the family moved to Linz, where he remained until 1626. In 1615 his mother Katharina was accused of witchcraft, and she was arrested in 1620 and held for more than a year, until Kepler’s legal defence helped win her release in 1621. In the middle of this he published the Harmonices Mundi (1619), which contains the third law, and later the Rudolphine Tables (1627). He died in Regensburg in November 1630 while travelling to collect money owed to him.',
    ],
    context: [
      'Kepler lived in a Central Europe divided by religion. Lutherans, Calvinists and Catholics competed for power in the Habsburg lands, and the conflict grew into the Thirty Years’ War, which began in 1618. Kepler’s own faith was a Lutheran one, but he did not accept every point of the Lutheran formula of agreement. In Linz the local pastor refused him communion, and Catholic rulers in turn pushed Protestants out of Graz and later Linz, so he spent his life as a believer on the move.',
      'In astronomy, the old Ptolemaic system and the newer ideas of Copernicus and Tycho Brahe competed, and all of them assumed that planets move in perfect circles. Mathematics, astrology and natural philosophy were not yet separate trades, and astronomers were expected to cast horoscopes for patrons. Kepler held to the old hope that the cosmos is mathematically beautiful and made by a rational Creator, but he allowed observation to overrule his preferences.',
    ],
    ideas: [
      { title: 'Planets move in ellipses', text: 'After years of calculation on Mars, he found that the planet’s orbit is not a circle but an ellipse, with the Sun at one focus. This is the first law. Giving up the circle was a break with two thousand years of assumption, and he made it only because the data, which differed from a circle by a small angle, forced it.' },
      { title: 'Faster near the Sun', text: 'His second law says that a line from the Sun to a planet sweeps out equal areas in equal times, so a planet moves faster when it is closer to the Sun. He also tried to explain this by a physical force from the Sun, an early attempt at celestial physics: the heavens as a machine to be understood, not a set of perfect crystal spheres.' },
      { title: 'The harmonic law', text: 'The third law, published in the Harmonices Mundi in 1619, links a planet’s orbital period to its distance: the square of the period is proportional to the cube of the average distance. It ties all the planets into one scheme. Newton later showed that it follows from gravity.' },
      { title: 'Geometry and the harmony of the spheres', text: 'In the Mysterium Cosmographicum, Kepler proposed that the five regular solids, such as the cube and the tetrahedron, fit between the orbits of the six planets. The model was wrong. But the Harmonices Mundi continues the search for harmony, comparing planetary speeds with musical intervals. This was a Pythagorean hope, and it led him to the discoveries that last.' },
      { title: 'Optics and a measured universe', text: 'Kepler also made lasting contributions to optics. He explained how the eye forms an image on the retina, worked out the principles of a telescope with two convex lenses, and described the supernova that appeared in 1604. His work shows a mind that combined mystical aims with precise measurement.' },
    ],
    principles: [
      'Let the data overrule your favourite theory.',
      'Look for the harmony in many facts, but check it against the numbers.',
      'Treat failure as information: a model that is wrong by a small amount is still telling you something.',
      'Hold deep convictions while you stay honest about evidence.',
      'Be patient: the patterns of nature may take years of work to reveal.',
    ],
    practice: [
      'When your results disagree with a model you like by a small amount, take the gap seriously instead of explaining it away.',
      'Keep careful records of your own work, so that later you or others can find patterns in them.',
      'Make room for imagination, and then test it. Many of Kepler’s wildest guesses led to real discoveries when he checked them.',
    ],
    facts: [
      'Kepler spent years on the orbit of Mars and described the effort as a war with the planet. The key came from the very accurate observations of Tycho Brahe, which Kepler obtained after Tycho’s death in 1601.',
      'He wrote a story called Somnium (“The Dream”) about a journey to the Moon, which was published after his death in 1634. It is sometimes called one of the earliest works of science fiction.',
      'In 1611 he wrote a short essay on the six-cornered shape of snowflakes, and in it posed a question about the best way to pack spheres. The Kepler conjecture, that the usual stacking of oranges is the densest, was proved only in the twenty-first century.',
      'His mother Katharina was held in chains for more than a year. Kepler studied the legal record, wrote detailed responses to the charges and worked to get her freed. She was released in October 1621 and died the following year.',
      'He cast horoscopes throughout his career, including a famous one for the general Albrecht von Wallenstein, though he was critical of much conventional astrology and referred to it as the foolish daughter of astronomy who helped support her mother.',
      'He lived on irregular pay. The imperial treasury often failed to pay his salary, and he was owed large sums when he died.',
    ],
    myths: [
      { myth: 'Kepler was a purely modern scientist who rejected mysticism.', reality: 'His discoveries came from a mind that believed in cosmic harmony, divine geometry and, in a qualified way, astrology. The mixture is what makes him interesting, and his three laws came from work done within that view.' },
      { myth: 'Kepler’s mother was burned as a witch.', reality: 'Katharina Kepler was accused, arrested and tried, but she was released in 1621 after a long process, and she died in 1622. Her trial took place in an age of many witchcraft cases, and Kepler’s defence is part of why she survived.' },
      { myth: 'Kepler discovered the laws by simple observation.', reality: 'He relied on Tycho Brahe’s records and spent years on heavy mathematical work, trying and discarding many models, before reaching the ellipse.' },
    ],
    works: [
      { title: 'Mysterium Cosmographicum (1596)', note: 'His first book, which proposes that the planetary orbits are nested between the five regular solids.' },
      { title: 'Astronomia Nova (1609)', note: 'The “New Astronomy”, containing the first two laws and the long story of how he found them from the orbit of Mars.' },
      { title: 'Harmonices Mundi (1619)', note: 'A work on geometry, music and astronomy, in which the third law appears.' },
      { title: 'Epitome of Copernican Astronomy (1618–1621)', note: 'A textbook that applied his laws to all the planets and to the moons of Jupiter.' },
      { title: 'Rudolphine Tables (1627)', note: 'Tables of planetary positions based on Tycho’s observations and Kepler’s laws, which remained in use for a long time.' },
    ],
    legacy: [
      'Newton showed that Kepler’s three laws follow from a single law of gravity, and the laws became a model for how an exact pattern can lead to deeper theory. Astronomers still use them to describe orbits of planets, moons, satellites and distant stars. A space telescope and several lunar craters carry his name.',
      'He is also remembered as a bridge between old and new. He was a Lutheran who saw the study of nature as a form of worship, and a mathematician who gave up beautiful circles for ugly ellipses because nature required it. Many later scientists have repeated his belief that the universe is open to human reason.',
    ],
  },
  {
    slug: 'miyamoto-musashi',
    order: 1584,
    dates: 'c. 1584 – 1645',
    place: 'Harima or Mimasaka province, then Kumamoto, Japan',
    era: 'Early Modern',
    tradition: 'Japanese martial philosophy',
    tagline: 'A swordsman who claimed never to have lost a duel and who tried to turn the study of the sword into a study of the whole of life.',
    who: [
      'Miyamoto Musashi was born around 1584, in a period when Japan was emerging from a century of civil war. His birthplace is disputed: traditions point to Harima or Mimasaka province in western Japan. He is said to have been the son of a martial arts teacher, to have been raised partly by relatives, and to have fought his first duel as a boy. The details of his early life come mostly from later accounts, including a biography written more than a century after his death, so they should be treated with caution.',
      'In his own writing Musashi claims that he fought more than sixty duels and never lost, beginning at the age of thirteen. Later stories give dramatic details of the best-known fights: against members of the Yoshioka school of Kyoto and, most famously, against Sasaki Kojiro on a small island in 1612. According to the legend, Musashi arrived late and carved an oar into a wooden sword on the way. Historians regard this and many similar details as embellishment, though a duel with Kojiro probably did take place.',
      'In his later years Musashi settled in Kumamoto in the service of the Hosokawa family. He spent his last years as a teacher, painter and calligrapher, and, according to tradition, retired to a cave known as Reigando, where he wrote The Book of Five Rings. He died in June 1645. A short work of twenty-one precepts, the Dokkodo, is said to have been written a week before his death.',
    ],
    context: [
      'Musashi was born at the end of the age of warring states. Oda Nobunaga, Toyotomi Hideyoshi and then Tokugawa Ieyasu had reunified the country, and the Battle of Sekigahara in 1600 gave the Tokugawa family control. The peace that followed left many warriors without lords. Some became masterless samurai, or ronin, and wandering swordsmen sought reputation by challenging schools and fighters in other regions.',
      'Under Tokugawa rule the samurai became more of a bureaucratic class, and the sword was increasingly a symbol of status and a path of self-cultivation than a tool of daily war. Schools of swordsmanship wrote down their teachings, and martial arts drew on Zen Buddhism, Confucian ethics and ideas of discipline. Musashi’s writings belong to this age, when fighting was becoming a subject for reflection.',
    ],
    ideas: [
      { title: 'The Way of two swords', text: 'Musashi founded a school called Niten Ichi-ryu, “the school of two heavens as one”, in which the fighter uses a long sword and a short sword together. In the Book of Five Rings he argues that ordinary samurai were trained to carry two swords but did not make use of them. His point is practical: do not become attached to a single weapon or a single technique.' },
      { title: 'Strategy is the Way for everything', text: 'The Book of Five Rings is divided into five sections, called Earth, Water, Fire, Wind and Void. Though it is about sword fighting, Musashi says that strategy applies in large battles, in single combat and in every trade. A carpenter, he points out, must also know timing, measure and the use of his tools, and strategy means knowing your own craft thoroughly.' },
      { title: 'Rhythm and timing', text: 'He teaches that everything has a rhythm, and that victory depends on understanding the rhythm of your opponent and of the moment. He urges readers to learn to see the whole situation and to watch with a wide, calm gaze instead of fixing on the opponent’s sword, and to distinguish “perception” and “sight”, which means seeing the essence of things.' },
      { title: 'Discipline through practice', text: 'He stresses training through constant practice, often summed up as a thousand days of practice to forge and ten thousand to polish. He rejects showy technique and tells readers to study many arts and to learn from what is real, not from what looks impressive. For Musashi the Way is something you do every day, not a theory.' },
      { title: 'The Void', text: 'The final book describes the Void, a state of clear mind that is free from confusion and from fixed ideas. In this state, Musashi says, one can act without hesitation. The idea draws on Buddhist thought, though he does not present it as a doctrine and presents it instead as the result of long practice.' },
    ],
    principles: [
      'Do not rely on a single technique or tool. Be ready to use whatever suits the situation.',
      'Know your craft thoroughly, whatever it is.',
      'Practise daily, and judge yourself by results.',
      'Watch the whole situation, not only one detail.',
      'Free the mind of attachment to show, reputation and fixed ideas.',
    ],
    practice: [
      'Pick one skill and practise it a little every day, instead of waiting for big bursts of effort.',
      'In a tense situation, widen your attention. Look at the whole room, the whole project or the whole conversation instead of the one thing that bothers you.',
      'Read the precepts of the Dokkodo slowly, as a list of habits to examine, such as not depending on partial feelings, not being driven by desire for comfort and not regretting what you have done.',
    ],
    facts: [
      'The Book of Five Rings (Go Rin no Sho) is generally dated to the last years of his life, around 1643–1645, and it is said to have been given to his pupil Terao Magonojo shortly before his death.',
      'No manuscript in Musashi’s own hand survives. The text is known from copies made later, and their wording and details differ, which is one reason scholars debate how much has been altered.',
      'The Dokkodo, “The Path of Aloneness” or “Going One’s Own Way”, consists of twenty-one short rules. Its early history is less well documented than that of the Book of Five Rings, and some scholars question how securely it can be traced to Musashi himself.',
      'His surviving ink paintings include a bird on a dead branch known as “Shrike on a Withered Tree” and a painting of Hotei watching a cockfight. Calligraphy and carved sword guards are also credited to him.',
      'His only well-documented participation in a war was the Shimabara Rebellion of 1637–1638, in which Christian peasants and masterless samurai rose against the Tokugawa government.',
      'The Book of Five Rings became widely known in English after a translation in the 1970s and is now read in business and strategy circles. Musashi himself never wrote for managers.',
    ],
    myths: [
      { myth: 'Musashi killed Sasaki Kojiro with a wooden oar after arriving hours late to annoy him.', reality: 'The story comes from later accounts and from fiction, and the details differ between versions. Scholars accept that a duel took place around 1612 but treat the oar and the lateness as legend.' },
      { myth: 'Musashi won every one of his sixty-odd duels, all of them to the death.', reality: 'The claim of an unbeaten record comes from his own book and from admiring later biographers. Few of the duels can be checked, and many fights in this period were with wooden swords and did not end in death.' },
      { myth: 'The popular figure of “Takezo”, the wild youth, is the real Musashi.', reality: 'Much of that image comes from a twentieth-century novel by Yoshikawa Eiji, which made Musashi into a character on a quest of self-improvement. The historical Musashi is known mainly from a few documents and his own writings.' },
    ],
    works: [
      { title: 'The Book of Five Rings (Go Rin no Sho)', note: 'His main work, written near the end of his life. It is divided into the books of Earth, Water, Fire, Wind and Void, and survives in later copies.' },
      { title: 'Dokkodo', note: 'Twenty-one precepts on self-discipline, said to have been composed shortly before his death.' },
      { title: 'Heiho Sanju-go (Thirty-five Articles on Strategy)', note: 'A shorter treatise on swordsmanship, said to have been written in 1641 for his lord Hosokawa Tadatoshi.' },
      { title: 'Ink paintings and calligraphy', note: 'Surviving works show a restrained and confident style and are among the best evidence for his character as an artist.' },
      { title: 'Later biographical writings', note: 'Accounts from the Hosokawa domain and the later Niten-ki are the main sources for his life, and both mix record with legend.' },
    ],
    legacy: [
      'Musashi became the best-known swordsman in Japanese history. Niten Ichi-ryu is still practised, and his story has been retold in novels, films, theatre, manga and games. The mixture of real achievement, legend and fiction can make it hard to see the actual man, but his own writings remain the best source.',
      'Since the twentieth century the Book of Five Rings has found readers worldwide. People have read it as a handbook on strategy, concentration and craft, and as a work of martial philosophy. Its lasting appeal comes from a plain claim: that whatever you practise with total seriousness can teach you about everything else.',
    ],
  },
  {
    slug: 'baltasar-gracian',
    order: 1601,
    dates: '1601 – 1658',
    place: 'Aragon, Spain',
    era: 'Early Modern',
    tradition: 'Spanish Baroque',
    tagline: 'A Jesuit priest who wrote the sharpest handbook of worldly prudence in Europe, and was punished by his own order for it.',
    who: [
      'Baltasar Gracián was born on 8 January 1601 in Belmonte, near Calatayud, in the kingdom of Aragon. He studied with the Jesuits, entered the Society of Jesus as a young man and was ordained a priest in 1627. For many years he taught at Jesuit colleges in Aragon and Catalonia, giving lessons in grammar, philosophy and theology, and he later served as rector of the college at Tarragona.',
      'He began to publish in the 1630s, with books on the ideal leader, the ideal courtier and the art of wit. In Huesca he enjoyed the support of a wealthy patron and scholar, Vincencio Juan de Lastanosa, who had a large library and a circle of friends. In 1646 he served as a chaplain with Spanish troops during the siege of Lleida (Lérida), at a time when Spain was fighting a rebellion in Catalonia. In 1647 he published his best-known work, the Oraculo manual y arte de prudencia, a collection of three hundred short maxims.',
      'Gracián published most of his works under a pseudonym, often the name Lorenzo Gracián, and without the permission of his superiors, who disapproved of a priest writing worldly books. The third part of his long allegorical novel El Criticón appeared in 1657, and the order responded sharply. He was reprimanded, reportedly given a punishment diet, and removed from his teaching post and sent to a small town. He died in Tarazona on 6 December 1658.',
    ],
    context: [
      'Gracián wrote in Spain’s Golden Age, which was also an age of decline. The Spanish Habsburg monarchy had the largest empire in the world but was exhausted by constant wars, taxes and corruption. The Thirty Years’ War, revolts in Catalonia and Portugal in 1640 and bankruptcies of the crown made many writers sceptical about power and honest dealing. The mood of the period, called desengaño, was one of disillusionment: things are not what they seem.',
      'In literature, the Spanish Baroque prized ingenuity. Two styles competed: culteranismo, associated with Luis de Góngora and full of elaborate vocabulary, and conceptismo, associated with Francisco de Quevedo, which valued compressed thought, wordplay and surprising comparisons. Gracián was the great theorist of conceptismo. In Agudeza y arte de ingenio he argued that wit is the art of finding hidden connections between things and expressing them in the fewest words.' ,
    ],
    ideas: [
      { title: 'Prudence in a dangerous world', text: 'The Oraculo manual offers advice for getting through a world of ambition, flattery and rivalry. Gracián treats life as a contest in which one needs self-command, good judgment and discretion. He does not recommend cruelty, but he does not pretend that goodness alone will protect a person, and he teaches how to avoid being exploited.' },
      { title: 'Reserve and self-control', text: 'Many maxims recommend keeping your plans to yourself, not showing your feelings or weaknesses, and not letting others see how much you depend on them. A person who is not readable is hard to manipulate. Gracián links this to inner freedom: master your passions or they will master you.' },
      { title: 'Know yourself and your moment', text: 'He advises readers to understand their own talents, to find the occupation that suits them and to judge the right time to act. Timing, in his view, is as important as ability, and a sensible person knows when to wait and when to press an advantage.' },
      { title: 'Wit and the compressed phrase', text: 'In his writing on conceptismo, Gracián held that a good idea should be short and sharp. He himself wrote in condensed, riddling sentences, so that readers must work to unpack them. The famous Spanish saying that what is good, if brief, is twice as good is often connected to his Oraculo.' },
      { title: 'Life as a journey of disillusion', text: 'In El Criticon, two travellers, the experienced Critilo and the natural man Andrenio, journey together through the stages of life and the world of courts and cities. The book is an allegory in which Andrenio learns that appearances deceive and that real value is rare. The goal is a lasting good beyond worldly success, and the final scenes turn toward eternity.' },
    ],
    principles: [
      'Do not reveal everything: keep some part of yourself in reserve.',
      'Know your strengths and weaknesses, and choose your path accordingly.',
      'Judge by substance, not by appearance, and be wary of flattery.',
      'Choose your friends and models with care.',
      'Aim at the good with both prudence and honour.',
    ],
    practice: [
      'Before a meeting or a decision, write down what you want and what you need to find out, and share only what is useful.',
      'Notice when you are reacting emotionally and pause, as Gracián advised, before you speak or write.',
      'Practise being concise. State your point in one clear sentence before you explain it.',
    ],
    facts: [
      'Gracián’s name for his long work was “El Criticon”, from the Greek for a person who judges. It appeared in three parts in 1651, 1653 and 1657.',
      'The Oraculo manual was written in a tiny format, meant to be carried in the pocket, and contains three hundred maxims, each with a short commentary.',
      'Arthur Schopenhauer admired Gracián deeply, called El Criticon a masterpiece and translated the Oraculo into German. The translation was published after Schopenhauer’s death.',
      'A French version of the Oraculo by Amelot de la Houssaye in 1684 helped spread the book in Europe, and the first English translations appeared in the late seventeenth century.',
      'His superiors punished him in 1658, according to the traditional account, by removing him from his teaching post and sending him to Graus, and he was then placed in a minor role at Tarazona.',
      'Modern English readers often know the Oraculo as The Art of Worldly Wisdom, the title used in several translations.',
    ],
    myths: [
      { myth: 'Gracián was a cynic who taught people to be manipulative.', reality: 'The Oraculo is amoral in tone at times, but it sits alongside religious works by the same author, including a book of meditations for Holy Communion, and El Criticon ends with a spiritual aim. Readers still disagree about how to balance the two sides.' },
      { myth: 'He left the Jesuit order or was expelled.', reality: 'He was reprimanded and sent away from prominent positions in 1658, but he remained a Jesuit until his death.' },
      { myth: 'The Oraculo is a plain collection of rules for success at court.', reality: 'Its author was a teacher of rhetoric and wit, and each maxim is a literary construction with layers of meaning. It is written to challenge readers, not just to give advice.' },
    ],
    works: [
      { title: 'El Heroe (1637) and El Politico (1640)', note: 'Early works on the qualities of a leader, the second a portrait of King Ferdinand the Catholic.' },
      { title: 'Agudeza y arte de ingenio (1648)', note: 'His treatise on wit and the conceit, which expanded an earlier work from 1642.' },
      { title: 'El Discreto (1646)', note: 'A guide to the cultivated and discreet person.' },
      { title: 'Oraculo manual y arte de prudencia (1647)', note: 'Three hundred maxims on prudence, his best-known work.' },
      { title: 'El Criticon (1651, 1653, 1657)', note: 'A three-part allegorical novel that follows two travellers through the stages of life.' },
    ],
    legacy: [
      'Gracián was widely read in seventeenth-century Europe. French and German translations influenced writers on manners and moral philosophy. He was admired by Schopenhauer and by Nietzsche, and the Oraculo has stayed in print as a handbook of discretion and self-command.',
      'Today he is read in several ways: as a major Baroque stylist, as a moralist of disillusion, and as a source for modern books on strategy and influence. Readers who come to him for tips find a stranger and more serious writer, one who thought that reason and restraint are needed to live in a world that rewards pretence.',
    ],
  },
  {
    slug: 'isaac-newton',
    order: 1643,
    dates: '1643 – 1727',
    place: 'Cambridge and London, England',
    era: 'Early Modern',
    tradition: 'Natural philosophy',
    tagline: 'The man who showed that one set of laws governs the fall of an apple and the orbit of the Moon, and who spent as much time on alchemy and theology as on physics.',
    who: [
      'Isaac Newton was born on Christmas Day 1642 by the calendar then used in England, which is 4 January 1643 by the modern one, at Woolsthorpe in Lincolnshire. His father died before he was born, and his mother left him with his grandmother when she remarried. He went to the King’s School in Grantham and in 1661 entered Trinity College, Cambridge. When the plague closed the university in 1665–1666, he returned home and began, by his own later account, his early work on calculus, light and gravitation.',
      'He became Lucasian Professor of Mathematics at Cambridge in 1669, aged twenty-six. He built a reflecting telescope, worked on the nature of colour and light, and quarrelled with rivals such as Robert Hooke. Urged by the astronomer Edmond Halley, who also paid for the printing, he wrote the Philosophiae Naturalis Principia Mathematica, published in 1687. It made him the most famous natural philosopher in Europe.',
      'In the 1690s he moved to London. He became Warden of the Royal Mint in 1696 and Master in 1699, led a major recoinage and pursued counterfeiters, and in 1703 became President of the Royal Society. Queen Anne knighted him in 1705. He published the Opticks in 1704, never married, and died in March 1727, receiving a state funeral and burial in Westminster Abbey. Dates in England were then eleven days behind the continental calendar, so his death is recorded as 20 March 1727 by the modern calendar and 1726 in the old style.',
    ],
    context: [
      'Newton came of age in a period of upheaval. England endured civil war, the execution of Charles I, the Restoration of the monarchy in 1660 and the Glorious Revolution of 1688. The Royal Society, founded in 1660, promoted experiment and shared observation. Natural philosophy, the name for what we call science, was changing quickly through the work of Galileo, Kepler and Descartes, and the question of how to explain motion in the heavens and on earth was open.',
      'Most scholars of the time still saw knowledge of nature as bound up with religion. Newton took the Bible and ancient texts seriously and studied alchemy, chronology and prophecy. What now looks like a sharp line between science and other kinds of inquiry did not yet exist, and he moved across it freely.' ,
    ],
    ideas: [
      { title: 'Universal gravitation and the laws of motion', text: 'The Principia sets out three laws of motion and the law of universal gravitation: every body attracts every other with a force that grows with their masses and weakens with the square of the distance. From these he derived Kepler’s laws, explained the tides and the paths of comets, and treated falling bodies and the planets as parts of one system. It was the first great demonstration that one mathematical theory could cover heaven and earth.' },
      { title: 'Calculus', text: 'Newton developed a method he called fluxions, which is a form of calculus, in the 1660s and 1670s. It lets mathematicians handle changing quantities, such as speed and slope, and areas under curves. Leibniz developed his own version independently and published first. A bitter priority dispute followed, in which the Royal Society, under Newton’s presidency, ruled in his favour in 1712 in a report that he himself had largely written. Historians now generally credit both men.' },
      { title: 'Light and colour', text: 'In the Opticks he showed through experiments with prisms that white light is a mixture of rays of different colours, each bent by a characteristic amount. This overturned the view that colours are produced by darkening or modifying white light. He also speculated that light consists of tiny particles, and his book influenced experimental science for generations.' },
      { title: 'Method: no mere hypotheses', text: 'In the General Scholium, added to the second edition of the Principia in 1713, he wrote “hypotheses non fingo”, usually translated “I do not feign hypotheses”. He meant that he would describe what gravity does and how it acts, as the evidence showed, without inventing an unproved explanation of what it is. He put the emphasis on inference from phenomena and on mathematical results that can be checked.' },
      { title: 'Alchemy and theology', text: 'Newton wrote a great deal on alchemy, biblical prophecy and church history, probably more than he wrote on physics. His private theological views were unorthodox: he seems to have rejected the doctrine of the Trinity, which was dangerous to admit in his day. Scholars still debate how these studies related to his physics, but they show that he looked for one divine order behind nature and history.' },
    ],
    principles: [
      'Reason from observations to general laws, and test the laws against more observations.',
      'Do not claim more than you can show.',
      'Concentrate your attention on a hard problem for as long as it takes.',
      'Be generous in acknowledging debts: knowledge builds on earlier work.',
      'Be careful that pride in your results does not turn into quarrels with colleagues.',
    ],
    practice: [
      'When tackling a hard problem, keep it in mind for days and return to it repeatedly. Newton credited his discoveries to constant thought.',
      'Separate what you can show from what you only suppose, and label each clearly in your own notes.',
      'Write up your results clearly and early, and give credit to those whose work you rely on, to avoid disputes later.',
    ],
    facts: [
      'The falling apple is a real story, but it is not clear that an apple hit his head. William Stukeley recorded Newton’s own recollection of watching an apple fall in a garden, which made him think about gravity. Voltaire later helped popularise it.',
      'The phrase “standing on the shoulders of giants” long predates Newton. It is attributed to Bernard of Chartres in the twelfth century, and Newton used a version in a letter to Robert Hooke in February 1676 (dated 1675 in the old-style calendar), perhaps with a note of irony.',
      'John Maynard Keynes, who bought many of Newton’s papers in 1936, called him “the last of the magicians”, because so many of the manuscripts dealt with alchemy and prophecy.',
      'As Warden and Master of the Mint he took a hands-on role in pursuing counterfeiters. One of them, William Chaloner, was convicted and hanged in 1699.',
      'He suffered a mental breakdown around 1693, with sleeplessness and paranoid letters to friends. The cause is still discussed, and theories include exhaustion, stress and exposure to mercury from his alchemical work.',
      'A well-known account describes his experiment with a bodkin, a blunt needle, which he slid between his eye and the bone to study how pressure changes what one sees. The report comes from his own notebooks.',
    ],
    myths: [
      { myth: 'An apple fell on Newton’s head and gave him the idea of gravity.', reality: 'The surviving accounts speak of seeing an apple fall, not being hit. The story is a simplified version of a later recollection, and the theory came from years of mathematical work.' },
      { myth: 'Newton invented the phrase “standing on the shoulders of giants”.', reality: 'It is a much older saying, usually credited to Bernard of Chartres in the twelfth century and passed on by John of Salisbury. Newton’s version appears in that letter to Hooke, and some historians read it as a barbed remark to Hooke.' },
      { myth: 'Newton was a cold rationalist who left religion out of his science.', reality: 'He wrote far more about theology and alchemy than about physics. He saw the order of nature as the work of a creator, and in later editions of the Principia he wrote of God’s dominion over the universe.' },
    ],
    works: [
      { title: 'Philosophiae Naturalis Principia Mathematica (1687)', note: 'The “Mathematical Principles of Natural Philosophy”, containing the laws of motion and universal gravitation. Later editions came out in 1713 and 1726.' },
      { title: 'Opticks (1704)', note: 'An experimental study of light and colour, written in English and ending with a set of speculative “Queries”.' },
      { title: 'De Methodis Serierum et Fluxionum', note: 'A treatise on his method of fluxions, written in the early 1670s and published only after his death.' },
      { title: 'Arithmetica Universalis (1707)', note: 'A work on algebra, based on his Cambridge lectures.' },
      { title: 'Theological and alchemical manuscripts', note: 'A vast body of papers, mostly unpublished in his lifetime, now held in collections such as Cambridge University Library and being edited and put online.' },
    ],
    legacy: [
      'For more than two centuries Newton’s mechanics was the model for physics. It guided engineers, astronomers and navigators, and it led to predictions such as the return of Halley’s comet and the discovery of Neptune. Poets and philosophers of the Enlightenment treated him as the symbol of what human reason could achieve. Alexander Pope’s epitaph imagined that “God said, Let Newton be!” and light appeared.',
      'In the twentieth century, Einstein’s relativity and quantum mechanics showed that Newton’s laws are an approximation that fails at very high speeds, very strong gravity and very small scales. They remain accurate and widely used for everyday purposes. The unit of force, the newton, is named after him.',
    ],
  },
]
