import type { Profile } from './types'

export const NINETEENTH_D: Profile[] = [
  {
    slug: 'ilia-chavchavadze',
    order: 1837,
    dates: '1837 – 1907',
    place: 'Kvareli, Kakheti, then Tbilisi (Georgia)',
    era: '19th Century',
    tradition: 'Georgian national thought',
    tagline: 'Poet, editor and banker who tried to rebuild a nation under imperial rule from three things: the fatherland, the language and the faith.',
    who: [
      'Ilia Chavchavadze was born on 8 November 1837 in Kvareli, in the wine region of Kakheti in eastern Georgia, into a noble family. He studied in Tbilisi and then, in 1857, entered the law faculty of St Petersburg University. He left in his fourth year, around 1861, without a degree, and went home. He is remembered as the leader of the Tergdaleulebi, the “those who drank the water of the Terek”, a nickname for the young Georgians who crossed the Terek river to study in Russia and came back with European ideas of progress, liberty and national renewal.',
      'Back in Georgia he turned writing into public work. He founded the journal Sakartvelos Moambe (“The Georgian Herald”) in 1863, which lasted only a year, and in 1877 he started the newspaper Iveria, which he edited as a daily from 1886 to 1902. He was also an organiser and a financier. He helped to create and long led the Land Bank of the Georgian nobility, he took a leading part in the Society for the Spreading of Literacy among Georgians from its founding in 1879, and he chaired that society from 1885 until his death. He married Olga Guramishvili in 1863.',
      'He died violently. On 30 August 1907 by the old Russian calendar (12 September by the modern one), he and Olga were driving from Tbilisi toward their estate at Saguramo when a group of gunmen stopped the carriage near Tsitsamuri, close to Mtskheta, and shot him. He was 69. He is buried in the Mtatsminda Pantheon in Tbilisi, and the Georgian Orthodox Church declared him a saint in 1987.',
    ],
    context: [
      'Georgia had been absorbed into the Russian Empire in the early nineteenth century, and its old kingdoms no longer existed as political units. Russian officials favoured the Russian language in schools and church life, and Georgian writing in print was limited. At the same time the emancipation of the serfs in the 1860s, the growth of Tbilisi as a commercial city and the arrival of new ideas from Europe were reshaping society. A nation that had no state of its own had to decide what it was and how it would survive.',
      'Chavchavadze’s answer was cultural and civic rather than revolutionary. He believed that a people could keep itself alive through schools, a modern literary language, a free press, economic institutions that kept land and capital in local hands, and loyalty to the Georgian church. In his later years this view clashed with the rising Marxist movement in Georgia, which put class before nation, and with the Russian authorities, who were wary of Georgian national feeling. His career ended in the turbulent years after the 1905 Revolution.',
    ],
    ideas: [
      { title: 'Fatherland, language, faith', text: 'Chavchavadze’s name is tied to the triad mamuli, ena, sarcmunoeba: fatherland, language and faith. For him these were the three pillars that a nation without its own state could stand on. The fatherland meant the land and shared history, the language was the carrier of a people’s thought, and the faith was the Georgian Orthodox Church as part of national identity. The formula became so widely used that it is still quoted in Georgia today.' },
      { title: 'Education as national self-help', text: 'He argued that a nation is built by its own efforts and not by waiting for rulers. The Society for the Spreading of Literacy among Georgians, founded in 1879 with Dimitri Kipiani, Iakob Gogebashvili and Mariam Jambakur-Orbeliani among its founders, ran schools, bookshops and libraries, trained teachers and supported Georgian-language publishing. He also supported simplifying the Georgian alphabet by dropping letters that were no longer needed.' },
      { title: 'Economic strength protects culture', text: 'He saw that landless nobles and poor peasants could not keep a culture alive. The Land Bank of the nobility, which he helped to found and long led, gave loans so that estates would not pass out of Georgian hands. Supporters saw practical patriotism in this. Critics, then and later, noted that the policy was framed around the nobility and sometimes carried suspicion of the Armenian merchant class that dominated Tbilisi trade.' },
      { title: 'Literature that questions society', text: 'His fiction and poetry turned a critical eye on his own class. In the satirical story “Is a Man a Human?!”, written in 1859–1863, a lazy landowner called Luarsab Tatkaridze lives in comfortable idleness, and the title asks whether such a life is human at all. His prose also described the injustice of serfdom, and his long poem “The Hermit” (1883) turns a folk legend into a meditation on the loneliness of the person who seeks truth.' },
      { title: 'A moderate road between empire and revolution', text: 'Chavchavadze wanted reform, not revolt. He pressed for peasant emancipation and wider education, and he resisted the pressure to assimilate into Russian culture. He also argued with Georgian socialists who saw the nation as a distraction from class struggle. Historians still debate whether his emphasis on the Georgian Orthodox faith and the nobility left too little room for other groups and classes.' },
    ],
    principles: [
      'A people without its own state keeps itself alive through language, memory and institutions.',
      'Education is the foundation on which every other reform rests.',
      'Cultural renewal needs money, so build banks and schools together.',
      'Write in the language ordinary people speak.',
      'Love of country should be put to work through practical civic labour, not left as a sentiment.',
    ],
    practice: [
      'Support the places where a shared culture is kept alive: local libraries, schools, small presses and language classes.',
      'When you are tempted to complain about a problem, ask what institution could be built to solve it, however small.',
      'Read a text from your own tradition critically: be loyal to your community and still willing to name its failings, as Chavchavadze did in his satire.',
    ],
    facts: [
      'He translated poetry by writers such as Schiller, Heine, Byron and Pushkin into Georgian, a sign of how seriously he took bringing European literature home.',
      'The newspaper Iveria was published for years and became the main platform of Georgian public debate; its name, Iveria, comes from Iberia, the classical name for the Georgian lands.',
      'He spent several years in the 1860s and 1870s as a mediator and judge in Dusheti, where he supported the settlement of peasant affairs after emancipation.',
      'After the 1905 Revolution he was chosen to represent the Georgian nobility in the Russian Empire’s State Council, which he served on from 1906.',
      'His wife Olga asked the authorities to pardon her husband’s killers, saying that he would have forgiven them himself, according to later accounts.',
      'Georgian Orthodox tradition celebrates his feast on 2 August, which is 20 July by the old calendar.',
    ],
    myths: [
      { myth: 'The identity of his killers and their masters is settled history.', reality: 'Six men attacked him, and a military court sentenced the group in 1909. Beyond that, interpretations differ. Soviet historians blamed the tsarist secret police, while other Georgian scholars point to revolutionary groups opposed to his politics. The question of who ordered the attack is still debated.' },
      { myth: 'He was simply a poet who wrote patriotic verse.', reality: 'Poetry was only one strand. He was also a journalist, a banker, a fundraiser, a politician, a school organiser and the head of a national society, and much of his influence comes from this practical work.' },
      { myth: 'The slogan “Fatherland, Language, Faith” was a rigid national creed to him.', reality: 'It worked more as a shorthand for the things a stateless people needed. In his own writing he also pressed for reform, education and critical self-examination, and not only for loyalty.' },
    ],
    works: [
      { title: 'Is a Man a Human?! (written 1859–1863)', note: 'A satirical story on the idle landowner Luarsab Tatkaridze, regarded as a landmark of nineteenth-century Georgian prose.' },
      { title: 'The Hermit (1883)', note: 'A long poem based on a folk legend from Khevi, first published in Iveria; it reflects on conscience, suffering and the search for truth.' },
      { title: 'Glakhis naambobi, “A Beggar’s Story”', note: 'A prose work about the hardship of a poor man under serfdom, one of his early social stories. It is sometimes translated under other titles.' },
      { title: 'Kako the Robber (1860) and other early poems', note: 'An early work from around the time of his student years, dated by Georgian sources to 1860.' },
      { title: 'Articles and editorials in Iveria and Sakartvelos Moambe', note: 'The place where his views on language, nation and reform were set out for a wide readership.' },
    ],
    legacy: [
      'Chavchavadze is often called the “father of the nation” in Georgia, and his image runs through the country’s modern public life. Streets, a university in Tbilisi and many schools carry his name. His slogan and his example of building institutions shaped the Georgian national movement that led to the short-lived independent republic of 1918–1921.',
      'His canonisation in 1987, during the late Soviet period, linked his memory to the revival of the Georgian Church, and his murder became a symbol of the cost of national leadership. His record is also open to debate. Scholars discuss how his views on class, the nobility and religion fit later ideas of a pluralist nation, and who stood behind his death. Most agree that few individuals did more to give Georgians a modern sense of themselves.',
    ],
  },
  {
    slug: 'vazha-pshavela',
    order: 1861,
    dates: '1861 – 1915',
    place: 'Chargali, Pshavi (Georgian highlands), and Tbilisi',
    era: '19th Century',
    tradition: 'Georgian literature and thought',
    tagline: 'A mountain schoolteacher and farmer who wrote epics in which conscience, nature and the stranger outweigh the demands of the tribe.',
    who: [
      'Vazha-Pshavela was the pen name of Luka Razikashvili, born in 1861 in the village of Chargali in Pshavi, a mountain region of north-eastern Georgia. The name means “the Pshavian man”, vazha being a Georgian word for a man. His father, Pavle, was a priest, and two of his brothers, Bachana and Tedo, also became writers. Biographies give 14 July 1861, and a few older references give a different year, so the exact day and year are best treated with some care.',
      'He studied at a teachers’ school in Tbilisi and then at the Teachers’ Seminary in Gori, where he finished in 1882. He went to St Petersburg to study law and attended lectures in 1883–1884, but he had to leave for lack of money. He worked as a teacher in village schools and, from 1888, settled again in Chargali, where he farmed, kept livestock and wrote. His first publication was a letter from Khevsureti printed in 1879 in the newspaper Droeba.',
      'He married Tamar Didebashvili and had four children. He wrote about 36 epic poems and many shorter poems, plus stories, plays and essays, mostly drawing on the life and beliefs of the Pshavs and neighbouring highlanders. He died in Tbilisi in July 1915, aged 53, and was first buried in the Didube Pantheon. In 1935 his remains were moved to the Mtatsminda Pantheon, the resting place of Georgia’s national figures.',
    ],
    context: [
      'The world he wrote about was the high-mountain frontier of Georgia. Pshavi and neighbouring Khevsureti kept customs of honour, hospitality and blood feud, and strong traditions of local sanctuaries and law, long after the lowlands had changed. Many highlanders were Christian, while neighbours across the ridge such as the Kists were Muslim, and old rules of vengeance and truce governed their dealings.',
      'Vazha began writing in the 1880s, a time when Georgian literature was dominated by the national-reform debates led by Ilia Chavchavadze’s generation. He was part of the same cultural movement, yet his voice was different. He did not describe the nobility or the cities. He took a very small society, observed it closely and found in it the great questions: what do we owe our community, our own conscience, strangers and the natural world?',
    ],
    ideas: [
      { title: 'Conscience against custom', text: 'In poems such as “Aluda Ketelauri” (1888) a hero meets an enemy and sees a human being. Aluda is moved by respect for a fallen Kist warrior and will not treat him as custom demands, and his own community turns on him. Vazha does not condemn the old code outright, but he shows the cost when an individual sees further than the group.' },
      { title: 'Hospitality as the highest law', text: 'In “Host and Guest” (1893) the Muslim Joqola hosts the Christian Zviadauri, who has been an enemy of his people. When the village demands that the guest be handed over, Joqola refuses, because a guest is under his protection. The poem ends in tragedy, and its power comes from the idea that a person’s duty to a stranger can outweigh religion, clan and even life.' },
      { title: 'Nature as a living world', text: 'Vazha’s landscapes are full of speaking trees, animals and rocks. In “Snake-Eater” (1901) the hero Mindia eats a snake and can suddenly understand the voices of nature. He can no longer kill, yet his father and his community demand blood revenge, and the conflict leads to his death. The poem is often read as a picture of a poet or visionary who cannot live inside the laws of his society.' },
      { title: 'Patriotism and cosmopolitanism belong together', text: 'In his 1905 essay “Cosmopolitanism and Patriotism” Vazha argued that a person who does not love their own land and people cannot truly love humanity. Universal love, in his view, grows from the local kind and does not replace it. A true patriot, he says, must be open to the world, and a real cosmopolitan must be rooted somewhere.' },
      { title: 'An unusual moral world', text: 'His heroes are often warriors who also show tenderness for enemies, animals and plants. He admired the highlanders’ courage and honour, but his best poems test those values against kindness. This mix of respect for tradition and willingness to question it is what makes his moral world feel both ancient and surprisingly modern.' },
    ],
    principles: [
      'Treat the guest and the stranger as under your protection.',
      'Listen to your conscience even when the group demands something else.',
      'Respect an enemy’s humanity; it does not make you weaker.',
      'Live close to nature and learn from it.',
      'Love of your own place is the root from which love of humanity grows.',
    ],
    practice: [
      'When your group asks you to dislike someone, ask a simple question: what would hospitality require of me here?',
      'Spend regular time outside, away from screens, and notice details such as a tree, a stream or a bird as Vazha did.',
      'Read one of his poems slowly, then write down which loyalty the hero chooses and what it costs him.',
    ],
    facts: [
      'The film The Plea (Vedreba, 1967), directed by Tengiz Abuladze, is based on “Aluda Ketelauri” and “Host and Guest”.',
      'His poems have been translated into more than twenty languages, including Russian versions by Boris Pasternak, Marina Tsvetaeva and Osip Mandelstam, and English ones by Donald Rayfield.',
      '“Bakhtrioni” (1892) tells of the highlanders’ part in the Kakhetian uprising against Iranian rule in 1659.',
      'He lived a working farmer’s life in Chargali, herding and farming while writing, rather than in a literary city.',
      'He was first buried in Tbilisi’s Didube Pantheon, and in 1935 his remains were moved to the Mtatsminda Pantheon.',
      'Georgian schoolchildren still read “Host and Guest”, which is among the best-loved works in the language.',
    ],
    myths: [
      { myth: 'Vazha was an untrained mountain bard who simply repeated folk songs.', reality: 'He was a trained teacher who studied at seminary and attended lectures in St Petersburg. He drew deeply on highland tradition and folklore, but he shaped it into his own epic poems and psychological drama.' },
      { myth: 'He celebrated every old highland custom.', reality: 'He admired the highlanders’ courage and honour, but his best-known heroes, such as Aluda and Mindia, break with harsh rules like blood revenge. Many readers see his work as a critique as well as a tribute.' },
    ],
    works: [
      { title: 'Aluda Ketelauri (1888)', note: 'An epic poem about a man whose respect for an enemy sets him against his own community.' },
      { title: 'Bakhtrioni (1892)', note: 'An epic of highlanders joining the 1659 uprising in Kakheti against Iranian rule.' },
      { title: 'Host and Guest (1893)', note: 'His best-known poem, about hospitality across religious lines and its fatal cost.' },
      { title: 'Snake-Eater (1901)', note: 'A visionary poem, often seen as his greatest, about a man who understands the language of nature.' },
      { title: 'Cosmopolitanism and Patriotism (1905)', note: 'An essay arguing that love of one’s own country and love of humanity support each other.' },
    ],
    legacy: [
      'Vazha-Pshavela is regarded in Georgia as one of the greatest poets in the language, often named alongside Shota Rustaveli and Ilia Chavchavadze. His Pshavian world, with its sanctuaries, feuds and hospitality, became part of how Georgians imagine their own highlands. In the twentieth century his work was staged, filmed and set to music, including Abuladze’s film and an opera on Mindia.',
      'Outside Georgia he is less known, but the translations by major poets and the film’s success abroad opened a path for readers. His stress on conscience, the protection of the stranger and a bond with nature has made him a touchstone in modern debates about nationalism, religious difference and the environment. Soviet critics sometimes tried to read him as a social realist, while others have emphasised his pantheism and individualism, which shows how rich and contested his reading remains.',
    ],
  },
  {
    slug: 'rabindranath-tagore',
    order: 1861,
    dates: '1861 – 1941',
    place: 'Calcutta (Kolkata) and Santiniketan, Bengal, India',
    era: '19th Century',
    tradition: 'Bengali Renaissance',
    tagline: 'A poet, songwriter and educator who won the Nobel Prize and spent his life pleading for a humanity larger than any nation.',
    who: [
      'Rabindranath Tagore was born on 7 May 1861 in the Jorasanko house of the Tagore family in Calcutta, the youngest child of a large household that was a centre of Bengali art, music and reform. His father, Debendranath Tagore, was a leader of the Brahmo Samaj, a reforming movement that rejected image worship and caste rigidity. His mother died when he was a boy. He disliked formal schooling, was educated largely at home, and spent a short period in England in 1878. He began publishing poetry as a teenager.',
      'In 1890 he took over the management of the family estates in rural Bengal, living at Shilaidaha on the river, and the villagers and the landscape deeply shaped his writing. In 1901 he founded a school at Santiniketan, north of Calcutta, where classes were often held in the open air. He lost his wife Mrinalini in 1902, and later two of his five children died young. In 1921 the school grew into Visva-Bharati, an international university.',
      'In 1913 he became the first non-European to receive the Nobel Prize in Literature, honoured for the English version of his religious poems Gitanjali, published in 1912 with an introduction by W. B. Yeats. In later decades he lectured across Asia, Europe and the Americas, took up painting in old age and wrote to the end. He died in Calcutta on 7 August 1941.',
    ],
    context: [
      'Nineteenth-century Bengal, then the heart of British India, saw an extraordinary flowering of literature, religious reform and social debate, now called the Bengal Renaissance. Writers and reformers argued over how to combine European learning with Indian traditions, and over women’s education, caste and religion. The Tagore family was at the heart of those arguments.',
      'Politically, the period was one of growing resistance to British rule. The 1905 partition of Bengal led to the Swadeshi movement, and Tagore briefly took part in it, writing songs and speaking publicly. He soon grew uneasy at its coercion and communal tension, and he drew back. His disagreement with both imperial rule and aggressive nationalism marked much of his later thought.',
    ],
    ideas: [
      { title: 'A humanism beyond nations', text: 'In lectures given in Japan and the United States in 1916–1917 and published as “Nationalism” (1917), Tagore criticised the modern nation-state as a machine of organised self-interest, and warned that it could make people cold and aggressive. He was not against love of one’s country. He feared that worship of the nation would override ethics, as he saw in the militarism of the period.' },
      { title: 'The religion of man', text: 'In his religious writings, later gathered in works such as The Religion of Man (based on lectures given in 1930), he described the divine as present in human creativity, love and freedom. For him God was not a distant ruler but a presence found in beauty, in relationships and in the effort to grow beyond narrow self-interest.' },
      { title: 'Education through joy and nature', text: 'He disliked the rote learning of colonial schools. At Santiniketan he wanted children to learn through music, art, nature and conversation, and he wished to bring together Eastern and Western learning. Visva-Bharati reflected his hope that the world could meet in one place for study.' },
      { title: 'Freedom needs reason', text: 'Tagore admired Mahatma Gandhi and was critical of British rule, but he disagreed with Gandhi’s methods. He worried that the non-cooperation campaign of 1920–1921 encouraged an exclusive spirit, and in 1925 he wrote an essay doubting that spinning cloth by hand could solve India’s problems. After the Bihar earthquake of 1934, he criticised Gandhi for describing it as a punishment for the sin of untouchability, since he held that natural disasters have natural causes.' },
      { title: 'Art as a way of seeing', text: 'He wrote about two thousand songs, plus poems, plays, essays, short stories and novels. His fiction, such as Gora (published in book form in 1910), asked whether an Indian identity could be based on religion, caste or race, and in the end looked to a wider humanity. His songs are still sung in Bengal and shape its culture.' },
    ],
    principles: [
      'Love your country without making it an idol.',
      'Learning should awaken curiosity and delight, and not only transmit facts.',
      'The divine is to be found in human creativity and compassion.',
      'Freedom depends on reason as well as courage.',
      'Cultures grow by meeting each other, not by closing their doors.',
    ],
    practice: [
      'Take a lesson outdoors: read, think or discuss something under a tree and notice how it changes the quality of attention.',
      'When you meet strong group feeling, ask what is being left out, and who is being treated as outside the circle.',
      'Learn one creative skill, such as songwriting, drawing or poetry, purely for the pleasure of making something.',
    ],
    facts: [
      'He renounced the knighthood given to him in 1915, in a letter to the Viceroy written in May 1919 after the Jallianwala Bagh massacre in Amritsar. He did not refuse the Nobel Prize, which is a frequent mistake.',
      'He wrote the words and music for the national anthem of India, “Jana Gana Mana”, and the words of the Bangladeshi anthem, “Amar Shonar Bangla”.',
      'He met Albert Einstein in 1930, and the two discussed the nature of reality in a well-known conversation.',
      'He visited Argentina in 1924, where he was helped by the writer Victoria Ocampo, and he travelled to Persia in 1932 and the Soviet Union in 1930.',
      'Between about 1916 and 1917 he lectured in Japan and the United States, and the talks became his book Nationalism.',
      'He began serious painting late in life and his works were shown in Paris and London in 1930.',
    ],
    myths: [
      { myth: 'Tagore opposed Indian independence or was indifferent to it.', reality: 'He criticised British rule sharply, and his 1919 protest is the best-known example. What he opposed was the aggressive, exclusive form of nationalism that he saw in the West and feared at home.' },
      { myth: 'Tagore and Gandhi were enemies.', reality: 'They respected each other and exchanged letters for years, but they argued openly on non-cooperation, the spinning wheel and the 1934 earthquake. Their disagreement was a sincere debate between friends.' },
      { myth: 'Tagore turned down the Nobel Prize.', reality: 'He accepted the Nobel Prize in 1913. What he gave up, in 1919, was the knighthood.' },
    ],
    works: [
      { title: 'Gitanjali (Bengali 1910; English “Song Offerings” 1912)', note: 'Devotional poems whose English version brought him the Nobel Prize.' },
      { title: 'Gora (1910)', note: 'A novel about religion, caste and identity in colonial India.' },
      { title: 'Ghare-Baire, “The Home and the World” (1916)', note: 'A novel about nationalism, love and moral ambiguity during the Swadeshi period.' },
      { title: 'Nationalism (1917)', note: 'Lectures that criticised the modern nation-state and the worship of national power.' },
      { title: 'The Religion of Man (1931)', note: 'A late statement of his view of the divine in human life, based on lectures delivered in 1930.' },
    ],
    legacy: [
      'Tagore changed Bengali literature, giving it a modern lyric voice and a form of the short story and the song that is still central to its culture. Two nations use his words for their anthems, and his school and university at Santiniketan still operate as Visva-Bharati, now a central university in India. His ideas on learning have influenced progressive education worldwide.',
      'His reputation has been debated. Admirers value his humane internationalism and his warnings about the danger of nationalism, which seem prophetic after the world wars. Critics point to his sometimes distant, aesthetic way of seeing rural poverty, or note that his political views changed over time. Few doubt that he made a lasting case for a humanity larger than any single nation.',
    ],
  },
  {
    slug: 'swami-vivekananda',
    order: 1863,
    dates: '1863 – 1902',
    place: 'Calcutta (Kolkata), India; Chicago and the West; Belur Math',
    era: '19th Century',
    tradition: 'Vedanta and Hindu reform',
    tagline: 'A monk who carried Vedanta to the West and taught that serving people is a way of serving God.',
    who: [
      'Vivekananda was born Narendranath Datta on 12 January 1863 in Calcutta, into a well-off Bengali family. His father, Vishwanath, was a lawyer, and his mother, Bhuvaneshwari Devi, was deeply religious. He studied at the Scottish Church College, where he read Western philosophy, and took part in the lively religious debates of the city. In 1881 he met Sri Ramakrishna, a mystic priest at the Dakshineswar temple, whose teaching that all religions lead to the same goal became the centre of his life.',
      'After his father’s death in 1884 and Ramakrishna’s death in 1886, Narendranath and a small group of fellow disciples became monks. From about 1888 to 1893 he travelled across India as a wandering monk, seeing poverty and caste divisions at first hand. He took the monastic name Vivekananda, and accounts differ as to when and by whom it was suggested.',
      'On 11 September 1893 he spoke at the Parliament of the World’s Religions in Chicago, and his opening address to “sisters and brothers of America” brought applause. He lectured in the United States and Britain, wrote Raja Yoga (1896) and founded Vedanta societies. Back in India he founded the Ramakrishna Mission on 1 May 1897, with its headquarters at Belur Math near Calcutta. He made a second trip to the West in 1899–1900, and he died at Belur Math on 4 July 1902 at the age of 39, after years of ill health, including asthma and diabetes.',
    ],
    context: [
      'India under British rule saw widespread debate about how to answer colonial claims of Western superiority. Missionaries criticised Hinduism, and educated Indians asked whether their traditions could be defended and reformed. Movements such as the Brahmo Samaj and the Arya Samaj offered new answers. Vivekananda’s version drew on Ramakrishna’s devotion and on the Advaita Vedanta tradition, which holds that the self and the ultimate reality are one.',
      'In the West, interest in Indian thought was already growing through translations of the Upanishads and the Bhagavad Gita, the Transcendentalists and the Theosophical Society. The 1893 Parliament, held alongside the World’s Columbian Exposition, was a stage where Asian religious voices were heard by a large Western public for the first time on this scale.',
    ],
    ideas: [
      { title: 'Each soul is potentially divine', text: 'Vivekananda taught that the divine is already within every person, and that the goal of life is to manifest it. He called this Vedanta applied to life. He stressed strength and fearlessness and criticised teachings that make people feel weak or sinful.' },
      { title: 'Harmony of religions', text: 'Following Ramakrishna, he held that the various religions are different paths to the same truth. At Chicago he spoke for tolerance and against fanaticism. Critics note that he also placed Advaita Vedanta at the top of his own ranking of religions, so his universalism had a Hindu centre.' },
      { title: 'Service as worship', text: 'He insisted that religion without service to the poor is empty. Seeing the suffering of ordinary Indians, he urged his followers to see God in the hungry and the sick, and he set up the Ramakrishna Mission for education, relief and healthcare. This idea of “practical Vedanta” gave the monastic tradition a new, social direction.' },
      { title: 'Four yogas for four temperaments', text: 'He presented Jnana, Bhakti, Karma and Raja yoga as four ways of reaching the same goal: knowledge, devotion, action and meditation. His Raja Yoga (1896) was important in shaping the modern Western idea of yoga as a practice of mind and self-control, which differs from physical postures.' },
      { title: 'Strength, education and national renewal', text: 'He told young Indians to build character, strength and self-confidence, and to educate the masses, including women. His message gave courage to many nationalists. He also made remarks on caste, women and other religions that are debated by scholars, and his legacy has been used in different ways in Indian politics.' },
    ],
    principles: [
      'Every person has an inner divinity that is waiting to be expressed.',
      'Serve people as a form of worship.',
      'Be strong in body, mind and character, and do not be afraid.',
      'Respect other paths and be honest about your own.',
      'Combine thought, feeling, action and discipline in one life.',
    ],
    practice: [
      'Choose one concrete act of service each week for someone who cannot repay you.',
      'Notice which temperament suits you, thoughtful, devotional, active or contemplative, and add practices from the others.',
      'When you read his speeches, ask where he agrees with and where he departs from the older tradition he draws on.',
    ],
    facts: [
      'He met the industrialist Jamsetji Tata in 1893 on a ship from Yokohama to Chicago, and Tata later asked him to lead a research institute, an offer he declined.',
      'In November 1895 he met Margaret Noble, an Irish teacher who became Sister Nivedita and devoted herself to work in India.',
      'The Ramakrishna Mission published the journals Prabuddha Bharata in English and Udbodhan in Bengali, which he launched in the late 1890s.',
      'His birthday, 12 January, is observed in India as National Youth Day.',
      'In 1900 he took part in the Congress of the History of Religions in Paris during his second trip to the West.',
      'His chronic ill health, which included asthma, diabetes and insomnia, limited his activity in his last years.',
    ],
    myths: [
      { myth: 'Vivekananda alone introduced Hinduism and yoga to the West.', reality: 'Western readers already knew Indian texts through translations, the Transcendentalists and the Theosophists, and other Indian speakers such as the Brahmo leader Protap Chunder Mozoomdar were at the Parliament. He was, however, among the most influential and widely heard Indian voices of his day.' },
      { myth: 'He is simply a Hindu nationalist, or alternatively a purely universal saint.', reality: 'Scholars disagree. Some, such as Jyotirmaya Sharma, see him as a forerunner of Hindu nationalism, while others argue that he was a patriot who criticised caste and championed religious pluralism and that later political movements misuse him. His own writings contain both strands.' },
    ],
    works: [
      { title: 'Raja Yoga (1896)', note: 'Lectures on the practice of meditation and the mind, drawing on Patanjali; very influential in the West.' },
      { title: 'Karma Yoga, Bhakti Yoga and Jnana Yoga', note: 'Collected lectures on the other paths of yoga, published in the late 1890s.' },
      { title: 'The Parliament of Religions addresses (1893)', note: 'The Chicago speeches that made him famous, including his opening address on 11 September.' },
      { title: 'Letters and the Complete Works', note: 'His letters and talks, collected by the Ramakrishna Order, are the main sources for his views on society and education.' },
      { title: 'Prabuddha Bharata and Udbodhan', note: 'Journals launched in the late 1890s to spread the Mission’s message.' },
    ],
    legacy: [
      'The Ramakrishna Mission and Math continue to run schools, hospitals and relief programmes in India and elsewhere, and Vedanta centres exist in many countries. His speeches shaped both modern Hinduism’s sense of itself and the way the West learned about yoga and Vedanta. Generations of Indian reformers and nationalists, including figures in the independence movement, drew inspiration from his call for strength and service.',
      'His legacy is also contested. Scholars have examined his attitudes to caste, gender and other religions, and debated whether his “neo-Vedanta” presents Advaita accurately. Political movements of different kinds, from the Hindu right to socialists, have claimed him. A fair reading takes his writings in their historical setting and separates them from later uses.',
    ],
  },
]
