import type { Profile } from './types'

export const NINETEENTH_B: Profile[] = [
  {
    slug: 'ralph-waldo-emerson',
    order: 1803,
    dates: '1803 – 1882',
    place: 'Boston and Concord, Massachusetts, USA',
    era: '19th Century',
    tradition: 'Transcendentalism',
    tagline: 'The Concord essayist who told Americans to trust their own minds and to read nature, and not tradition, as a source of truth.',
    who: [
      'Ralph Waldo Emerson was born in Boston on 25 May 1803 into a long line of ministers. He entered Harvard at fourteen, graduated in 1821, and trained for the ministry. In January 1829 he was ordained as junior pastor of Boston’s Second Church, and the same year he married Ellen Tucker, who died of tuberculosis in February 1831, when she was only twenty. In 1832 he resigned his post, after disagreeing with his congregation over how the Lord’s Supper should be observed. He felt he could no longer perform a ritual he did not believe in.',
      'After a trip to Europe he settled in Concord, Massachusetts, and made his living as a writer and a travelling lecturer. His first book, Nature, appeared in 1836, and in 1837 and 1838 he gave two speeches that made him famous and controversial: “The American Scholar” and the Divinity School Address. He married Lidian Jackson in 1835, and in January 1842 their five-year-old son Waldo died of scarlet fever. The grief shaped his later essay “Experience”, which is darker and more cautious than his early writing. He went on to lecture on a huge scale; his lifetime total is estimated at about 1,500 talks.',
      'Emerson was never the leader of an organised movement, though he became the best-known voice of what people called transcendentalism. He supported younger writers generously, among them Henry David Thoreau, who lived for a time in his household, and Walt Whitman, to whom he sent a warm letter in 1855 after reading Leaves of Grass. In his last decade his memory failed, and he died of pneumonia in Concord on 27 April 1882, at the age of seventy-eight.',
    ],
    context: [
      'Emerson grew up in Unitarian New England, where the old Calvinist idea of a stern God was giving way to a more rational and humane faith. Many younger thinkers found even Unitarianism too dry and too tied to the evidence of miracles. They were drawn to European Romanticism, to the German philosopher Immanuel Kant, whom they met mainly through writers such as Coleridge and Carlyle, and to Plato, and later to Indian texts such as the Bhagavad Gita, which Emerson read with interest.',
      'Transcendentalism was the American result. The word refers to the belief that people have a kind of knowledge that goes beyond (“transcends”) the senses and inherited doctrine, an intuition of spiritual truth available to every person. A small circle began meeting informally in 1836 as the Transcendental Club, and they published a journal, The Dial, from 1840, with Margaret Fuller as its first editor. All this happened in a young, quickly industrialising democracy, where slavery and the question of what it meant to be an American thinker were pressing public issues.',
    ],
    ideas: [
      { title: 'Self-reliance', text: 'The centre of Emerson’s ethics is the claim that each person should trust their own deepest convictions, not imitate others or follow custom for its own sake. “Whoso would be a man must be a nonconformist,” he wrote in “Self-Reliance” (1841), and in the same essay he said that “a foolish consistency is the hobgoblin of little minds”. He did not mean selfishness. He meant that a society is only as good as the independent minds that make it up.' },
      { title: 'Nature as teacher and symbol', text: 'In Nature he argued that the natural world is not just raw material but a language, in which physical things point to spiritual truths. Famously he described standing in an open field and becoming a “transparent eye-ball”, feeling himself part of everything he saw. Whatever one makes of the image, it expresses his belief that wonder before nature is a form of knowledge.' },
      { title: 'The Over-Soul', text: 'Emerson held that behind individual minds there is a shared spiritual source, which he called the Over-Soul in an essay of 1841. Every person is in contact with it, which is why intuition can reveal truths and why human beings, deep down, are not strangers. The idea drew on Plato, on Romantic thought and on Indian ideas of an underlying unity.' },
      { title: 'Living religion, not inherited doctrine', text: 'In the Divinity School Address of July 1838, delivered to graduating ministers at Harvard, he argued that Christianity had become a matter of repeating the past, and that miracles and ritual were no substitute for a person’s own experience of the divine. Church leaders were outraged, and he was not invited back to speak at Harvard for decades. For Emerson, revelation was not finished long ago but available now.' },
      { title: 'Independent thinking in a new country', text: 'In “The American Scholar” (1837) he called on Americans to stop relying on European learning and to think from their own experience, a speech that Oliver Wendell Holmes later called America’s intellectual declaration of independence. Later in life he balanced this optimism with a sense of limits: in “Fate” and “Experience” he admitted that circumstance, grief and temperament restrict our freedom.' },
    ],
    principles: [
      'Trust your own thought, and test it honestly before you act on it.',
      'Do not conform simply because others do.',
      'Learn from books, but do not let them replace your own thinking.',
      'Look to nature for perspective, and to inner experience for meaning.',
      'Combine independence with care for other people and for justice.',
    ],
    practice: [
      'Before accepting an opinion, ask whether you hold it because you have examined it or because everyone around you does.',
      'Spend regular time outdoors without a screen, and write down what you notice.',
      'Keep a journal, as Emerson did throughout his life, and return to it to see what you really thought.',
    ],
    facts: [
      'Emerson agreed to be the godfather of William James, who was born in January 1842.',
      'He was an early reader of Indian philosophy, including the Bhagavad Gita, and these texts influenced his idea of underlying unity.',
      'When his house burned down in July 1872, friends raised money to rebuild it and sent him on a trip to Europe.',
      'In 1855 he sent Walt Whitman a letter of praise for Leaves of Grass, five pages long, when almost no one else had noticed the book.',
      'He spoke out against the Fugitive Slave Act in Concord on 3 May 1851 and supported the abolition of slavery.',
      'He gave the funeral address for Thoreau in 1862.',
    ],
    myths: [
      { myth: 'Emerson taught pure individualism: do whatever you like and ignore society.', reality: 'His essays praise independence of mind, but he also wrote about friendship, duty and the common spiritual source of all people. In the 1850s he spoke publicly against slavery and the Fugitive Slave Act.' },
      { myth: 'Emerson founded the transcendentalist movement as a school with a programme.', reality: 'The Transcendental Club was an informal gathering, and its members disagreed widely. Emerson was its best-known voice, not its commander, and he was uneasy about being tied to a label.' },
      { myth: 'He was an optimist who never doubted.', reality: 'After the death of his son in 1842 his writing, especially “Experience” and “Fate”, shows grief and a sober recognition of life’s limits alongside his faith in the human spirit.' },
    ],
    works: [
      { title: 'Nature (1836)', note: 'His first book, which sets out his view of nature as a source of spiritual insight and contains the “transparent eye-ball” passage.' },
      { title: 'The American Scholar (1837) and the Divinity School Address (1838)', note: 'Two famous speeches, the first on intellectual independence and the second on living religion.' },
      { title: 'Essays: First Series (1841) and Second Series (1844)', note: 'Include “Self-Reliance”, “The Over-Soul”, “Circles” and, in the second series, “Experience”.' },
      { title: 'Representative Men (1850)', note: 'Lectures on figures such as Plato, Montaigne, Shakespeare and Napoleon as examples of human greatness.' },
      { title: 'The Conduct of Life (1860)', note: 'Essays of his maturity, including “Fate”, on power, wealth, culture and the limits of freedom.' },
    ],
    legacy: [
      'Emerson shaped American writing and thought for generations. Thoreau and Whitman were directly inspired by him, and his emphasis on experience and individual development influenced William James and John Dewey. In Europe his work was admired by Friedrich Nietzsche, who read his essays closely.',
      'His essays are still widely read, quoted and argued over. Admirers see in them the roots of American democratic individualism and of modern environmental thinking, while critics point out that his stress on the individual can underestimate how much we depend on others. That both views can be drawn from the same pages is part of why he is still worth reading.',
    ],
  },
  {
    slug: 'henry-david-thoreau',
    order: 1817,
    dates: '1817 – 1862',
    place: 'Concord, Massachusetts, USA',
    era: '19th Century',
    tradition: 'Transcendentalism',
    tagline: 'The writer who went to a pond near Concord to live deliberately and left behind the classic argument for conscience over obedience.',
    who: [
      'Henry David Thoreau was born in Concord, Massachusetts, on 12 July 1817. His father made pencils, and the family business, which Thoreau later helped improve, supported him on and off throughout his life. He attended Harvard from 1833, graduated in 1837, and briefly taught school before resigning, reportedly because he did not want to punish pupils physically. He and his brother John then ran a small school of their own. After John died in 1842 from tetanus, following a shaving cut, Thoreau was deeply shaken.',
      'Thoreau became a friend and protégé of Ralph Waldo Emerson, and for a time he lived in the Emerson household. In July 1845 he built a small cabin near Walden Pond, on land owned by Emerson, and lived there until September 1847. While there he wrote much of A Week on the Concord and Merrimack Rivers, a memorial to John, and drafts of what became Walden. In July 1846 he spent a night in the Concord jail for refusing to pay a poll tax, in protest against slavery and the Mexican–American War. The next morning someone else paid the tax, and he was released.',
      'He earned his living with odd jobs, pencil-making and especially land surveying, and he kept a journal for most of his adult life. He supported the abolitionists, helped fugitive slaves on their way north, and defended John Brown after the raid on Harpers Ferry. He contracted tuberculosis and died in Concord on 6 May 1862, aged forty-four. In his lifetime he was known mostly to a small circle, and his fame grew after his death.',
    ],
    context: [
      'Thoreau lived in a village at the edge of a changing America. Railways, factories and markets were transforming the economy, and many people were giving up farm and craft work to chase wages and goods. The Mexican–American War and the expansion of slavery troubled many New Englanders, who had to decide how far to cooperate with a government that did things they thought wrong.',
      'Intellectually, he belonged to the transcendentalist circle around Emerson, which held that individuals could grasp spiritual truths by direct intuition and that nature was a source of such insight. Thoreau shared this belief but gave it a practical and observational turn. Where Emerson often wrote about nature in general terms, Thoreau walked the same woods every year and recorded what he saw.',
    ],
    ideas: [
      { title: 'Simplicity as freedom', text: 'In Walden he argues that most people work long hours to pay for things they do not need, and so lose the very life they are working to protect. His answer is not poverty for its own sake but a conscious reduction of wants: “simplify, simplify”. By lowering the cost of living you gain time, and time is what life is made of.' },
      { title: 'Living deliberately', text: 'He said he went to the woods because he wished “to live deliberately”, to face the essential facts of life and see whether he could learn what it had to teach. The point is attention. A life lived on habit, he thought, is a life half missed.' },
      { title: 'Conscience before law', text: 'In “Resistance to Civil Government”, published in 1849 and later reprinted as “Civil Disobedience”, he argued that a person should not hand their conscience over to the state, and that it is more important to cultivate respect for what is right than for the law. If a government forces you to take part in injustice, he said, your duty is not to cooperate. He accepted the consequences of such refusal, as his night in jail shows.' },
      { title: 'Nature as a source of wildness and renewal', text: 'Thoreau saw wild nature as a source of spiritual and moral health, and his late essay “Walking” praises the wild as the “preservation of the world”. He also studied it closely, recording the dates when plants flowered and birds arrived, and treating his journal as his main work.' },
      { title: 'Independence of mind', text: 'Like Emerson, he distrusted conformity. “If a man does not keep pace with his companions,” he wrote, “perhaps it is because he hears a different drummer.” He wanted a life shaped by one’s own reasons, even if this made one look odd.' },
    ],
    principles: [
      'Reduce what you need, so that you are less dependent on what you must earn.',
      'Pay attention to the world around you, in all seasons.',
      'Put conscience above convenience.',
      'Do not take part in what you believe is wrong.',
      'Be willing to accept the cost of your convictions.',
    ],
    practice: [
      'Add up what an item really costs, counting the hours of work it took to pay for it.',
      'Take a regular walk in the same place, and write down one thing that has changed since the last time.',
      'Ask which of your habits or duties you perform only because everyone does, and try giving one up for a month.',
    ],
    facts: [
      'The Walden cabin was about ten feet by fifteen, and Thoreau recorded that it cost him a little over twenty-eight dollars in materials.',
      'The cabin stood about a mile and a half from the centre of Concord. He walked into town often, ate with friends and family, and his family helped him with food and washing.',
      'Walden was published on 9 August 1854. It sold slowly, and a first printing of 2,000 copies took years to sell.',
      'A Week on the Concord and Merrimack Rivers (1849) was a commercial failure: fewer than 300 of the 1,000 printed copies sold, and the unsold ones were returned to him.',
      'In Walden he compressed his two years and two months at the pond into a single year, arranged by the seasons.',
      'Modern climate scientists have used Thoreau’s records of flowering dates in Concord as a baseline for studying how plants respond to a warming climate.',
    ],
    myths: [
      { myth: 'Thoreau lived alone in the wilderness, cut off from society.', reality: 'Walden Pond was a short walk from Concord. He visited the town regularly, received visitors at the cabin, and friends and family helped him. The experiment was about deliberate simplicity, not total isolation, and he left after two years.' },
      { myth: 'He hated people and society.', reality: 'He kept three chairs in his cabin, he said: one for solitude, two for friendship, three for company. His criticism was aimed at habits and institutions that, in his view, cost people their freedom, and he took an active part in the abolitionist cause.' },
      { myth: 'Walden was a how-to manual for living in the woods.', reality: 'It is a work of philosophy and literature, partly humorous and partly provocative, meant to make readers question how they live rather than to be copied exactly.' },
    ],
    works: [
      { title: 'A Week on the Concord and Merrimack Rivers (1849)', note: 'His first book, a river journey with his brother John, mixed with essays and reflections.' },
      { title: 'Resistance to Civil Government (“Civil Disobedience”, 1849)', note: 'The essay on conscience and the state, which grew out of his night in jail.' },
      { title: 'Walden; or, Life in the Woods (1854)', note: 'His masterpiece, on economy, simplicity, nature and attention.' },
      { title: 'Essays and speeches on slavery', note: 'Include “Slavery in Massachusetts” and “A Plea for Captain John Brown”.' },
      { title: 'Journal, and posthumous works such as Walking, The Maine Woods and Cape Cod', note: 'His journal, kept for years, is the source of most of his writing, and several books were published after his death.' },
    ],
    legacy: [
      'Thoreau’s essay on civil disobedience inspired later movements for nonviolent resistance. Mahatma Gandhi credited it with influence, and Martin Luther King Jr. cited it in connection with the civil rights movement. Leo Tolstoy also admired his writing. Walden became a foundation of American nature writing and, later, of the environmental movement.',
      'Today people read him for different reasons: as a guide to simple living, as a naturalist, as a political thinker, and as a stylist. It is worth remembering that he was also a man with contradictions, who lived near a village and often depended on it. That honest mixture of ideal and ordinary life makes his writing more interesting, not less.',
    ],
  },
  {
    slug: 'william-james',
    order: 1842,
    dates: '1842 – 1910',
    place: 'New York City and Cambridge, Massachusetts, USA',
    era: '19th Century',
    tradition: 'Pragmatism',
    tagline: 'The psychologist and philosopher who judged ideas by what they do in lived experience, and who defended our right to believe.',
    who: [
      'William James was born in New York City on 11 January 1842, the eldest child of the theologian Henry James Sr. His younger brother became the novelist Henry James, and his sister Alice became a diarist. His family travelled widely, and he was educated in several countries. He first thought of becoming a painter, then turned to science and medicine, joined Louis Agassiz’s expedition to the Amazon in 1865, and received his medical degree from Harvard in 1869, although he never practised as a doctor.',
      'In about 1870 he fell into a deep depression with thoughts of suicide. He later wrote of overcoming it partly through reading the French philosopher Charles Renouvier on free will, and he recorded that his first act of free will would be to believe in free will. From 1873 he taught at Harvard, in physiology, psychology and then philosophy, and he set up one of the first psychology teaching laboratories in the United States. He married Alice Gibbens in 1878.',
      'His Principles of Psychology (1890), which took him about twelve years to write, made him famous. He then turned increasingly to philosophy and religion, producing The Will to Believe (1897), The Varieties of Religious Experience (1902) and Pragmatism (1907). He was also a public figure: he joined the Anti-Imperialist League in 1898 in opposition to the annexation of the Philippines. He died at his summer home in Chocorua, New Hampshire, on 26 August 1910.',
    ],
    context: [
      'James worked at a time when psychology was becoming a laboratory science, when Darwin’s theory of evolution had shaken older ideas about mind and nature, and when many educated people felt torn between science and religious faith. Much of his thought is an attempt to take science seriously without giving up the things that matter to human beings: freedom, meaning and the possibility of belief.',
      'Pragmatism had roots in conversations among a group of friends in Cambridge, Massachusetts, in the 1870s, among them Charles Sanders Peirce, who first formulated the idea that the meaning of a concept lies in its practical effects. James took that idea and made it famous, using the word in a public lecture in 1898 and then in his book Pragmatism, based on lectures given in 1906 and 1907. The term comes from the Greek for “action”: a pragmatist asks what difference a belief makes in practice.',
    ],
    ideas: [
      { title: 'The stream of thought', text: 'In the Principles of Psychology, James described consciousness not as a chain of separate ideas but as a continuous, ever-changing flow, like a stream. The image became so influential that “stream of consciousness” entered literary criticism and came to be used of modern novels. He also argued that attention, habit and selective interest shape what we experience.' },
      { title: 'Habit and will', text: 'James thought that habit is the great stabiliser of life, saving effort by making actions automatic, and he urged readers to form good habits early, since they are hard to change later. He also defended the reality of free will: our efforts of attention, he argued, are real choices that make a difference.' },
      { title: 'Pragmatism: truth and its consequences', text: 'For James, an idea is to be judged by how it works when tested in experience. A true idea is one that can be verified, that fits with other things we know, and that leads us successfully through experience. In a famous example he imagines a squirrel on a tree trunk, with a person walking round the tree, and shows how a dispute about whether the person goes “around” the squirrel dissolves once we ask what the word means in practice.' },
      { title: 'The will to believe', text: 'In an 1896 lecture James argued that in some cases we are entitled to believe something before the evidence is complete. His conditions are strict: the choice must be live (a real possibility for you), forced (you cannot avoid choosing) and momentous (it matters), and it must be a question that evidence cannot settle. Religious faith and trust in other people are his chief examples.' },
      { title: 'Religion as lived experience', text: 'In The Varieties of Religious Experience, based on his Gifford Lectures at Edinburgh in 1901 and 1902, he studied religion by looking at the experiences of individuals, such as mystics, converts and saints, and not at doctrine. He contrasted the “healthy-minded” who see mostly the good in life with the “sick soul” who feels evil keenly, and he treated the value of a religious experience as something to be judged by its fruits in a person’s life.' },
    ],
    principles: [
      'Judge ideas by their consequences in experience.',
      'Respect the full range of human experience, including feeling and faith.',
      'Be open to many points of view; truth has more than one side.',
      'Build good habits while you are young, and act on your resolutions.',
      'Do not demand more certainty than the question allows, and do not pretend to less doubt than you have.',
    ],
    practice: [
      'When you get stuck in an argument, ask: what difference would it make in practice if one side were right?',
      'Pick one small habit you want to build, and do not allow an exception until it is fixed.',
      'When facing a big decision that evidence cannot settle, write down the live options, what is at stake, and what each choice would do for your life.',
    ],
    facts: [
      'Ralph Waldo Emerson agreed to be William James’s godfather.',
      'His students at Harvard included Gertrude Stein, W. E. B. Du Bois, Theodore Roosevelt and George Santayana.',
      'He took part in the early work of the American Society for Psychical Research, studying claims of mediums and other unusual experiences, while remaining critical.',
      'The James–Lange theory of emotion holds that bodily reactions come first and the feeling follows: we feel sorry because we cry, as James put it, and not the reverse. It is named for James and the Danish physician Carl Lange.',
      'In his essay “The Moral Equivalent of War” (1910) he proposed that societies should find peaceful ways, such as national service, to channel the courage and discipline that war demands.',
      'Pragmatism: A New Name for Some Old Ways of Thinking was the full title of his 1907 book, which he presented as a name for an approach as old as Socrates.',
    ],
    myths: [
      { myth: 'Pragmatism says that whatever is useful to believe is true.', reality: 'James argued that truth is something that is verified by experience and that must fit the facts. A belief that merely pleases us but fails when tested is not true. His critics found his wording loose, but he did not say that wishing makes it so.' },
      { myth: 'The Will to Believe says you may believe anything you like.', reality: 'He restricted the argument to a narrow range of genuine options that cannot be settled by evidence, and he insisted that where evidence is available, we should follow it.' },
      { myth: 'James was a philosopher who rejected science.', reality: 'He was trained in medicine, helped found experimental psychology in America, and wrote about the importance of testing. His concern was that science should not be used to rule out matters of meaning and value without argument.' },
    ],
    works: [
      { title: 'The Principles of Psychology (1890)', note: 'A two-volume work, with chapters on the stream of thought, habit, emotion and will.' },
      { title: 'The Will to Believe, and Other Essays in Popular Philosophy (1897)', note: 'Includes the title lecture on faith and evidence.' },
      { title: 'The Varieties of Religious Experience (1902)', note: 'A study of religious experience, still in print more than a century later.' },
      { title: 'Pragmatism (1907)', note: 'The book that made pragmatism widely known, with chapters on truth, the one and the many, and meaning.' },
      { title: 'A Pluralistic Universe (1909) and Essays in Radical Empiricism (1912)', note: 'His later philosophy of experience and of a world that is many-sided, the second published after his death.' },
    ],
    legacy: [
      'James helped establish psychology as a discipline in the United States and left it with ideas, such as the stream of thought and the study of habit, that are still discussed. In philosophy, pragmatism was developed further by John Dewey, and it became one of the most important American philosophical traditions.',
      'His writing remains popular because it is clear, humane and honest about doubt. The Varieties of Religious Experience is read by philosophers, psychologists and general readers alike, and his questions about how belief, evidence and action fit together remain open.',
    ],
  },
  {
    slug: 'friedrich-nietzsche',
    order: 1844,
    dates: '1844 – 1900',
    place: 'Röcken, Prussia; Basel, Switzerland; Weimar, Germany',
    era: '19th Century',
    tradition: 'Existentialism and critique of morality',
    tagline: 'The philosopher who asked what is left of morality and meaning after belief in God fades, and who challenged people to create their own values.',
    who: [
      'Friedrich Nietzsche was born on 15 October 1844 in Röcken, a village in Prussia, the son of a Lutheran pastor who died when Friedrich was four. He studied classical languages at the famous school of Schulpforta and then at Bonn and Leipzig. In 1869, aged twenty-four and before he had finished a doctorate, he was appointed professor of classical philology at the University of Basel in Switzerland, and he gave up his Prussian citizenship. In 1870 he served briefly as a medical orderly in the Franco-Prussian War and fell seriously ill.',
      'His first book, The Birth of Tragedy (1872), was written in the circle of the composer Richard Wagner, whom he admired and later rejected. Poor health, including headaches and failing eyesight, forced him to resign from Basel in 1879. For the next decade he lived on a small pension, moving between Swiss mountain villages, Italian cities and the French coast, and wrote his best-known books, among them The Gay Science, Thus Spoke Zarathustra, Beyond Good and Evil and On the Genealogy of Morality. He was little read, and he suffered from loneliness and illness.',
      'In early January 1889, in Turin, Nietzsche suffered a mental collapse. A popular story says it began when he saw a horse being beaten and threw his arms around it, but the story comes from later accounts and is uncertain. His friend Franz Overbeck brought him back to Switzerland. For the rest of his life he was unable to work and was cared for first by his mother and, after her death in 1897, by his sister Elisabeth. He died in Weimar on 25 August 1900. The cause of his illness is still debated: syphilis was the early diagnosis, but other explanations have been proposed.',
    ],
    context: [
      'Nietzsche wrote in a Europe that was rapidly changing. Science, and especially Darwin’s theory of evolution, challenged traditional religious accounts of the world, industry was transforming society, and the new German Empire, founded in 1871, was filling with nationalist pride. Many educated people kept the moral habits of Christianity while no longer believing the doctrines behind them, and Nietzsche asked whether that could last.',
      'He was also a trained scholar of the ancient Greeks, and he admired their tragic art and their frank view of suffering. From the German philosopher Arthur Schopenhauer he took the idea that life involves deep strife and pain, though he rejected Schopenhauer’s pessimistic conclusion. Nietzsche’s method was unusual: he wrote in aphorisms, short essays and poetic prose, and he treated philosophy as something close to experiment and self-examination.',
    ],
    ideas: [
      { title: '“God is dead”', text: 'The phrase appears in The Gay Science (1882), most famously in the parable of the madman, who announces that “we have killed him”. Nietzsche is not cheering for atheism. He is observing that belief in the Christian God has become unbelievable for many Europeans, and that the moral and meaning structures built on that belief are now shaky. The question he poses is what we will do next, and whether we will face the danger of nihilism, the loss of any sense of value.' },
      { title: 'Revaluing values', text: 'In On the Genealogy of Morality (1887) he traces the history of moral ideas and asks where they came from and whom they serve. He argues that some of our values grew out of resentment, which he called ressentiment, and that we should question what we take as self-evident. The aim was not to throw morality out but to examine it honestly and to ask what kind of life it makes possible.' },
      { title: 'The Übermensch', text: 'In Thus Spoke Zarathustra (1883–85), the prophet Zarathustra teaches the Übermensch, usually translated as “overman” or “superhuman”. It is an ideal of a person who creates new values and affirms life, rising above the herd and above resentment. The idea is about self-overcoming. It is not a biological race and not a political class.' },
      { title: 'Eternal recurrence', text: 'In The Gay Science (section 341) Nietzsche asks the reader to imagine a demon who tells you that you will have to live your life again, exactly as it is, countless times. Would you be crushed, or would you welcome it? The thought is a test of whether you can affirm your life, and it connects with his phrase “amor fati”, love of fate.' },
      { title: 'Will to power and perspectivism', text: 'Nietzsche suggested that living things are driven by a will to power, which in his better-considered texts means a drive to grow, to overcome resistance and to give shape to oneself, and not simply to dominate others. He also held that there is no view from nowhere: all knowing is done from a perspective, though more perspectives bring us closer to the truth. He did not say that all views are equally good.' },
    ],
    principles: [
      'Question what you take for granted, especially your own moral habits.',
      'Create your own values instead of simply inheriting them, and take responsibility for them.',
      'Turn suffering into material for growth, not an excuse.',
      'Affirm your life, including its difficulties.',
      'Look at things from many perspectives.',
    ],
    practice: [
      'Take one belief you hold strongly and trace where it came from: who taught it to you, and who benefits from it?',
      'Try the thought experiment of eternal recurrence at the end of a day or a year: would you live it again, and what would you change?',
      'When facing hardship, ask what it could teach you or make possible, without pretending it is pleasant.',
    ],
    facts: [
      'He became a professor at twenty-four, before finishing a doctorate, and he never took another academic post after resigning in 1879.',
      'His books sold poorly during his sane lifetime. Interest began to grow only in 1888, partly thanks to lectures on his work by the Danish critic Georg Brandes in Copenhagen.',
      'The idea for Thus Spoke Zarathustra came to him in the Swiss Alps in the summer of 1881, according to his own account.',
      'Lou Salomé, a young Russian intellectual whom he met in 1882, declined his marriage proposal, and his friendship with her and Paul Rée ended painfully.',
      'He wrote that he learned psychology from the novelist Dostoevsky and admired Emerson, whose essays he read for years.',
      'His sister Elisabeth married the antisemitic nationalist Bernhard Förster in 1885, and Nietzsche objected strongly to both the marriage and the politics.',
    ],
    myths: [
      { myth: '“God is dead” means Nietzsche triumphantly announced that atheism had won.', reality: 'It is a diagnosis, not a celebration. He describes a culture that has stopped believing in God but has not yet understood what follows, namely a crisis of meaning, and he treats it as both a danger and an opportunity.' },
      { myth: 'The Übermensch is a master race, and Nietzsche was a forerunner of Nazism.', reality: 'The Übermensch is an ideal of individual self-overcoming, not a racial concept. Nietzsche attacked antisemitism and German nationalism in his writings and in letters. The Nazi image of him came from the later editing and promotion of his work, especially by his sister Elisabeth Förster-Nietzsche, who after his collapse ran the Nietzsche Archive in Weimar. With Peter Gast she assembled his notebooks into a book called The Will to Power, first published in 1901 and expanded in 1906, which scholars Colli and Montinari later showed to be a misleading arrangement. The Nazi regime, which supported the archive from 1933 and whose leader was photographed there in the 1930s, used selected quotations out of context, and postwar scholars such as Walter Kaufmann worked to correct this.' },
      { myth: 'Nietzsche’s philosophy is just a defence of cruelty and the strong ruling the weak.', reality: 'His main concern is how individuals can create meaning and excellence in their own lives. The “will to power” in his published work is often about self-mastery and creative growth. Readers still argue about how to interpret his sharper remarks, and it is fair to say that his writing can be read in more than one way.' },
    ],
    works: [
      { title: 'The Birth of Tragedy (1872)', note: 'His first book, on Greek tragedy and the opposition between the Apollonian (order and form) and the Dionysian (ecstasy and chaos).' },
      { title: 'The Gay Science (1882; expanded 1887)', note: 'Contains the madman’s parable and the first statement of eternal recurrence.' },
      { title: 'Thus Spoke Zarathustra (1883–85)', note: 'A poetic and philosophical work, where Zarathustra teaches the Übermensch.' },
      { title: 'Beyond Good and Evil (1886)', note: 'A critique of earlier philosophers and of moral prejudice.' },
      { title: 'On the Genealogy of Morality (1887)', note: 'Three essays on the origins of moral concepts, including “master” and “slave” morality, a contrast between an ethic of noble self-assertion and one born of resentment.' },
    ],
    legacy: [
      'Nietzsche’s influence on twentieth-century thought is enormous. Existentialist writers such as Jean-Paul Sartre and Albert Camus took up his questions about meaning in a world without a given purpose. Psychologists, sociologists, poets and novelists drew on him, and philosophers such as Heidegger, Foucault and Deleuze engaged with his work in detail.',
      'His reputation was damaged by the political use made of his name, and it took scholars decades to separate his actual writings from the version presented by his sister’s archive. Today he is read as a critic of complacency who asks uncomfortable questions: what do you really value, and why? Whether one agrees with his answers or not, those questions are hard to avoid.',
    ],
  },
]
