import type { Profile } from './types'

export const NINETEENTH_C: Profile[] = [
  {
    slug: 'alexis-de-tocqueville',
    order: 1805,
    dates: '1805 – 1859',
    place: 'Paris, and travels in the United States and Algeria',
    era: '19th Century',
    tradition: 'Political philosophy',
    tagline: 'A French aristocrat who crossed the Atlantic to study democracy and saw both its promise and its hidden dangers.',
    who: [
      'Alexis de Tocqueville was born in Paris on 29 July 1805 into an old Norman noble family. His parents had narrowly escaped the guillotine during the Terror, and his great-grandfather, the statesman Malesherbes, was executed during the Revolution. Growing up in a family that had lost so much to the upheaval of 1789, Tocqueville was drawn all his life to one question: why had France swung between revolution and despotism while other societies seemed to manage freedom better?',
      'He trained as a lawyer and worked as a junior magistrate. In 1831, with his close friend Gustave de Beaumont, he obtained an official mission to study prisons in the United States. The two men travelled for about nine months, from the east coast to the frontier of Michigan and down the Ohio and Mississippi rivers to New Orleans. They did write the prison report, but Tocqueville’s real project was much bigger: to understand what a society built on equality looks like. The result was Democracy in America, whose first volume appeared in 1835 and the second in 1840.',
      'He then entered politics. He sat in the French Chamber of Deputies from 1839 to 1848 and in the National Assembly after the revolution of 1848, and he served as foreign minister for a few months in 1849. In 1836 he had married Mary Mottley, an Englishwoman; they had no children. When Louis-Napoléon Bonaparte seized power in December 1851, Tocqueville protested, was briefly detained, and withdrew from public life. He wrote The Old Regime and the Revolution (1856) and died of tuberculosis in Cannes on 16 April 1859.',
    ],
    context: [
      'Tocqueville lived through a long French argument about the legacy of the Revolution. The monarchy was restored in 1815, overthrown in 1830, and overthrown again in 1848, and a second Napoleonic empire followed. Many aristocrats hoped to turn back the clock, and many radicals hoped to finish the Revolution. Tocqueville believed that the rise of equality was a historical force that could not be reversed, and that the only useful question was how to make it compatible with freedom.',
      'The United States seemed to him a laboratory. It had no feudal past, a very wide spread of voting rights for white men, strong local government and a vigorous religious life. It also had slavery and the dispossession of Native Americans, which he described with open criticism. He wrote about America with France in mind, and he said so: the book was a way of looking at Europe’s likely future.',
    ],
    ideas: [
      { title: 'The march of equality', text: 'Tocqueville saw the gradual levelling of social ranks as the central fact of modern history, so powerful that he called it providential. He did not simply praise it. Equality of conditions, he argued, shapes habits, manners, family life, religion and politics, and a society must learn to live with the new temperament it produces.' },
      { title: 'The tyranny of the majority', text: 'In a democracy the majority holds power, and it can also dominate opinion. He worried that an American majority could leave dissenters with no one to appeal to, not through laws but through social pressure. A free society, he said, needs courts, independent thinkers, and habits of tolerance that protect the minority.' },
      { title: 'Soft despotism', text: 'The second volume describes a danger that he found hard to name: a gentle, paternal state that looks after the comforts of citizens who have lost interest in public life. It does not whip or imprison. It simply takes care of everything, and treats adults like children. People may keep the forms of freedom while losing the habit of using it.' },
      { title: 'Individualism and associations', text: 'He used the word individualism for a quiet withdrawal into family and friends, away from the wider community, and he thought equality encouraged it. His cure was practical liberty: local government, juries, newspapers and above all voluntary associations, in which ordinary people learn to cooperate. Americans formed a club or society for almost any purpose, and he saw this as the schooling of democracy.' },
      { title: 'Liberty needs more than laws', text: 'Tocqueville stressed what he called the habits of the heart: customs, beliefs and religion. He noted that in America religion was separate from the state yet shaped public morals, which in his view restrained the temptation to put private gain above everything. For him, free institutions survive only if citizens care about them.' },
    ],
    principles: [
      'Freedom is a habit, and it weakens when it goes unused.',
      'Equality is not enough. A society also needs protections for liberty.',
      'Take part in local, concrete affairs. The small republic teaches the large one.',
      'Beware of a majority that mistakes its numbers for wisdom.',
      'Look at history as a long movement, and ask what a trend will become, not only what it is.',
    ],
    practice: [
      'Join one local association, whether a club, a school board or a neighbourhood group, and treat it as practice in self-government.',
      'Seek out a view you disagree with and ask how it would feel to hold it with no one standing by you.',
      'Notice what you let institutions decide for you, and ask whether it is convenience or a loss of responsibility.',
    ],
    facts: [
      'The prison report he wrote with Beaumont, published in 1833, was his first success, and it was Democracy in America that made him famous across Europe.',
      'John Stuart Mill reviewed both volumes of Democracy in America and helped to make it known to English readers.',
      'He was elected to the Académie française in 1841.',
      'At the end of the first volume he remarked that the United States and Russia seemed likely to become great powers, each on a very different basis, a passage often quoted in the twentieth century.',
      'In January 1848, weeks before the revolution broke out, he warned the Chamber of Deputies that France was sleeping on a volcano.',
      'His memoir of the 1848 revolution, Recollections, was written privately and published only after his death, in 1893.',
    ],
    myths: [
      { myth: 'Tocqueville simply admired America and wanted Europe to copy it.', reality: 'He admired much of it, including its local liberty and civic spirit, but he spent as much time on its weaknesses: conformity, materialism, racial injustice, and the risk of a mild despotism. He called himself a friend of liberty, not an advocate of any country.' },
      { myth: 'He wrote that America is great because America is good.', reality: 'This line is widely attributed to him, but it has not been found in Democracy in America or his other writings. Use it with caution.' },
      { myth: 'Democracy in America is only a book about the United States.', reality: 'He wrote that his real concern was the democratic future of France and Europe. America served as a mirror, and a warning as well as a model.' },
    ],
    works: [
      { title: 'Democracy in America (1835 and 1840)', note: 'His masterpiece, in two volumes. The first deals with American institutions and politics, and the second with manners, ideas and the dangers of equality.' },
      { title: 'The Old Regime and the Revolution (1856)', note: 'Argues that the Revolution continued a centralisation that the old French monarchy had already begun. He left a planned second part unfinished.' },
      { title: 'Recollections (written 1850–51, published 1893)', note: 'A sharp, personal account of the 1848 revolution and its politicians.' },
      { title: 'Writings on Algeria (1837 to 1847)', note: 'Letters, reports and speeches in which he supported French conquest and settlement. They show the limits of his liberalism.' },
      { title: 'On the Penitentiary System in the United States (1833)', note: 'The prison report written with Gustave de Beaumont.' },
    ],
    legacy: [
      'Tocqueville was widely respected in his lifetime and then partly forgotten, until the twentieth century returned him to attention. Historians of the French Revolution now treat his claim about continuity as a starting point, and political scientists draw on his ideas about civic associations, the role of the local community, and the way equality can encourage conformity. Later writers on civil society and social trust often return to him.',
      'His record is not simple, and honest readers keep both sides in view. The defender of liberty in Democracy in America also argued in the 1840s for French conquest in Algeria, travelled there in 1841 and 1846, and accepted harsh war methods as an unfortunate necessity, though he also criticised some of the army’s conduct. Today scholars debate how that fits his liberalism, and many read it as a warning that a belief in freedom for one’s own people does not guarantee justice toward others.',
    ],
  },
  {
    slug: 'charles-darwin',
    order: 1809,
    dates: '1809 – 1882',
    place: 'Shrewsbury and Downe, England, and the voyage of HMS Beagle',
    era: '19th Century',
    tradition: 'Natural history and evolution',
    tagline: 'He showed how living things could arise by natural selection, and changed how humans see their place in nature.',
    who: [
      'Charles Darwin was born in Shrewsbury, England, on 12 February 1809, into a prosperous family. His father was a doctor and his mother a daughter of the potter Josiah Wedgwood. He began medical studies at Edinburgh, which he disliked, and then prepared for the church at Christ’s College, Cambridge, where he spent more time collecting beetles than reading. Through his Cambridge teachers he was recommended as a naturalist for a surveying voyage.',
      'The voyage of HMS Beagle lasted from December 1831 to October 1836 and took him around South America and across the Pacific. He gathered fossils, plants and animals, and noted the geography and the people he met. He also saw how species differ between places that are close together, such as the creatures of the Galápagos Islands. Back in England he filled notebooks with speculation about how species change. In 1838 he read Thomas Malthus’s essay on population, which argued that more offspring are born than can survive, and he saw how this pressure could act as a natural filter.',
      'In 1839 Darwin married his cousin Emma Wedgwood, and in 1842 the family moved to Down House in Kent, where he lived for the rest of his life. They had ten children. His health was poor for most of his adult years, and the death of his daughter Annie in 1851 at the age of ten was a heavy blow. For about twenty years he worked on his theory in private, while also publishing on barnacles, until a letter from Alfred Russel Wallace in 1858 outlined the same idea and led to a joint presentation to the Linnean Society. He died at Downe on 19 April 1882 and was buried in Westminster Abbey.',
    ],
    context: [
      'Many educated Victorians believed that species were fixed and designed. Natural theology, the study of nature as evidence of a Creator, was a respected tradition, and Darwin himself had admired it at Cambridge. At the same time, geology had revealed a very old Earth with a deep fossil record, and some thinkers, among them his own grandfather Erasmus Darwin and the French naturalist Lamarck, had suggested that species change. What was missing was a convincing mechanism.',
      'Darwin delayed publishing for years. He knew the idea would be controversial, and he wanted overwhelming evidence. When On the Origin of Species appeared on 24 November 1859, its first printing sold out at once. It was debated in scientific societies, newspapers and pulpits, and in 1860 a famous exchange at Oxford, involving Bishop Samuel Wilberforce and Thomas Huxley, became a symbol of the clash between religion and science, though the real debates were far more varied.',
    ],
    ideas: [
      { title: 'Natural selection', text: 'Individuals in a species vary, and some of that variation is inherited. In every generation more are born than can survive, so those whose traits suit their surroundings tend to leave more offspring. Over many generations this slow, undirected filtering can change a population. Darwin modelled the idea on the way breeders improve domestic animals, but with nature as the selector.' },
      { title: 'Common descent', text: 'All living things, he argued, descend from earlier forms and are related, like branches of a tree. The similarities among very different animals, such as the bones in a human hand, a bat’s wing and a whale’s flipper, make sense if they inherit a common plan from shared ancestors. This replaced the picture of separate, unrelated creations.' },
      { title: 'Design without a designer', text: 'The adaptation of eyes, wings and roots had long been taken as proof of a purposeful maker. Darwin offered another explanation: a gradual, cumulative process with no foresight. This is the heart of the philosophical shock, because purpose in nature could now be explained without a plan.' },
      { title: 'Humans as part of nature', text: 'The Origin said little about humans, but The Descent of Man (1871) applied the argument directly. Darwin held that humans share ancestry with other animals and that our mental and moral abilities differ from theirs in degree, not in kind. He also proposed sexual selection, in which mate choice shapes traits such as bright colours and songs.' },
      { title: 'A long, slow history of life', text: 'He asked readers to see nature as a tangled bank, where many different creatures depend on each other in complex ways. His closing passage calls this view of life grand. Time, which Darwin took from geology, became a creative factor: small changes, summed over millions of years, can produce great differences.' },
    ],
    principles: [
      'Observe closely, and take small things seriously.',
      'Test your favourite idea against every fact that seems to go against it.',
      'Be patient: large effects can arise from slow, steady processes.',
      'Do not mistake what is natural for what is right. Describing nature is not the same as setting moral rules.',
      'Be honest about difficulties in your own theory.',
    ],
    practice: [
      'Keep a notebook for a month and record what you see in a garden, park or street. Look for patterns rather than isolated facts.',
      'When you form an opinion, write down the single strongest objection to it, and try to answer it fairly.',
      'When a problem seems too complex to have arisen without a plan, ask whether small, repeated changes could account for it.',
    ],
    facts: [
      'He was away from England for almost five years on the Beagle, and he was seasick for much of the journey.',
      'He spent about eight years studying barnacles before publishing the Origin.',
      'On 1 July 1858, the papers by Darwin and Wallace were read at the Linnean Society of London. Neither author was present, and Darwin was at home mourning the death of his young son.',
      'The Origin went through six editions in his lifetime. The phrase “survival of the fittest” was coined by the philosopher Herbert Spencer, and Darwin adopted it only in the fifth edition (1869).',
      'The word “evolution” does not appear in the first edition. The last word of the book is “evolved”, and Darwin used the word “evolution” itself only in the sixth edition of 1872.',
      'He was buried in Westminster Abbey, near Isaac Newton.',
    ],
    myths: [
      { myth: 'Darwin said humans descended from monkeys.', reality: 'He argued that humans and the living apes share a common ancestor, which is different from saying we come from any species alive today.' },
      { myth: 'Darwin taught “social Darwinism”, the idea that the strong should rule and the weak be left to fail.', reality: 'That label belongs to later writers, including Herbert Spencer, and to the eugenics movement, which grew from the work of his cousin Francis Galton. Darwin’s scientific theory describes how populations change and says nothing about how society ought to be run. He was himself a lifelong opponent of slavery, though some passages in his writings reflect Victorian assumptions about race and sex that readers today rightly question.' },
      { myth: 'He renounced his theory on his deathbed.', reality: 'A story of a deathbed conversion appeared decades after his death, and his family denied it. There is no good evidence for it. Darwin described himself as an agnostic in later life.' },
    ],
    works: [
      { title: 'On the Origin of Species (1859)', note: 'The founding book of evolutionary biology. Its full title is On the Origin of Species by Means of Natural Selection, or the Preservation of Favoured Races in the Struggle for Life.' },
      { title: 'The Voyage of the Beagle (1839)', note: 'His lively account of the expedition, a classic of travel writing and natural history.' },
      { title: 'The Descent of Man, and Selection in Relation to Sex (1871)', note: 'Applies his theory to human origins, morality and sexual selection.' },
      { title: 'The Expression of the Emotions in Man and Animals (1872)', note: 'Studies how feeling is shown in the face and body across species.' },
      { title: 'The Formation of Vegetable Mould, through the Actions of Worms (1881)', note: 'His last book, on earthworms and the slow power of small causes.' },
    ],
    legacy: [
      'Darwin’s theory became the unifying framework of the life sciences. After the discovery of genes in the twentieth century, it was combined with genetics into what is called the modern synthesis, and it still guides research in medicine, agriculture, ecology and conservation. His insistence that living things share a single family tree also shaped how scientists compare species, from fossils to DNA.',
      'Philosophically the effect has been profound and still contested. Some thinkers have seen in Darwin the end of the old picture of a world made for human beings, and others have found room for faith alongside evolution, treating it as the way creation unfolds. Writers on ethics, mind, language and religion now ask how our moral feelings and reasoning evolved. The challenge Darwin posed, to understand ourselves as part of nature without making that a reason to lose our responsibility, remains open.',
    ],
  },
  {
    slug: 'fyodor-dostoyevsky',
    order: 1821,
    dates: '1821 – 1881',
    place: 'Moscow, Siberia, and Saint Petersburg, Russia',
    era: '19th Century',
    tradition: 'Russian religious and psychological thought',
    tagline: 'A novelist who staged the great arguments about freedom, suffering and faith inside the minds of his characters.',
    who: [
      'Fyodor Dostoevsky was born in Moscow on 11 November 1821 (New Style; 30 October in the Russian calendar of the time). His father was a doctor at a hospital for the poor, and the family grew up in a modest apartment in the hospital grounds. His mother died in 1837 and his father in 1839; some accounts say that his father was killed by his own serfs, though this is not certain. Dostoevsky trained as a military engineer in Saint Petersburg, but his heart was in literature. His first novel, Poor Folk, appeared in January 1846 to great praise.',
      'In April 1849 he was arrested as a member of the Petrashevsky Circle, a group that discussed banned books and social reform, including a letter by the critic Belinsky criticising the Russian church and state. He and others were sentenced to death. On 22 December 1849 in the Russian calendar of the time (3 January 1850 in the Gregorian calendar), they were taken to a square in Saint Petersburg and prepared for a firing squad, and at the last moment the order came that Tsar Nicholas I had commuted the sentence. Dostoevsky spent four years at hard labour in a prison camp at Omsk in Siberia, then served as a soldier in Semipalatinsk. He came back to Saint Petersburg in 1859.',
      'The man who returned was different. He had been through the camp among ordinary convicts, with the New Testament as almost his only book, and came to value Christian faith and the Russian people more than the radical ideas of his youth. He lived in debt, suffered from epilepsy, and fell into a gambling habit. His first wife Maria died in 1864 and his brother Mikhail the same year. In 1867 he married Anna Snitkina, a young stenographer who helped him to put his finances in order. Between 1864 and 1880 he wrote the great novels on which his reputation rests. He died in Saint Petersburg on 9 February 1881 (New Style; 28 January in the Russian calendar), and thousands followed his coffin.',
    ],
    context: [
      'Dostoevsky’s Russia was an autocracy with serfdom, a huge peasant population, and a small educated class that argued over its future. The big debate was whether Russia should follow Western Europe, with its science, socialism and rationalism, or find its own path in Orthodox faith and national tradition. Serfdom ended in 1861, and the following decades brought rapid change, radical movements, and terrorism.',
      'His own ideas moved across this ground. In his youth he was drawn to utopian socialism, and afterwards he became suspicious of ideologies that claim to reorganise humanity by reason alone. He wrote as a journalist and editor too, and his later essays in A Writer’s Diary mix insight with the nationalism and prejudice of his time. A fair reading of him has to hold both the profound novelist and the opinions that trouble readers today.',
    ],
    ideas: [
      { title: 'The irrational freedom of the human being', text: 'In Notes from Underground (1864), an embittered narrator attacks the confident belief that people always act in their rational self-interest. People, he says, will sometimes choose something foolish simply to prove they are free. The book answers the idea that human beings can be fully explained and arranged by science and planning.' },
      { title: 'Crime, conscience and ideas that kill', text: 'In Crime and Punishment (1866), the student Raskolnikov persuades himself that an extraordinary person may break moral law for a greater good, and he murders a pawnbroker. The novel traces what follows in his conscience, and shows how an abstract theory can take hold of a mind and lead it into a crime. His path back is slow and goes through suffering and human contact.' },
      { title: 'Freedom, faith and the Grand Inquisitor', text: 'In The Brothers Karamazov (1879–80), Ivan tells the tale of a Grand Inquisitor who tells Christ that people are too weak for freedom and want bread, miracles and authority. Dostoevsky gave this argument great force, and then answered it elsewhere in the novel through the elder Zosima and through Alyosha, whose faith rests on active love.' },
      { title: 'Suffering and responsibility', text: 'A recurring thought in the novels is that everyone is responsible for everyone else. Dostoevsky saw suffering as something that can purify as well as destroy, and he did not offer easy consolation. His characters often come to life only when they accept guilt and reach out to others.' },
      { title: 'Many voices', text: 'The critic Mikhail Bakhtin described Dostoevsky’s novels as polyphonic: several fully developed viewpoints argue with one another and the author does not simply decide for one of them. This is one reason that readers of very different convictions, from believers to atheists, have found themselves in his books.' },
    ],
    principles: [
      'Do not reduce a person to a formula, because people exceed any theory about them.',
      'Ideas have consequences, so judge them by what they do to real human beings.',
      'Freedom is a burden as well as a gift, and love is the way to carry it.',
      'Accept responsibility for your own part in what happens around you.',
      'Look into the darkest corners of yourself rather than pretending they are not there.',
    ],
    practice: [
      'When you notice a strong theory about someone, ask what in their life it leaves out.',
      'After an argument, try to state the other side so well that its holder would agree with you.',
      'Choose one small, concrete act of care for someone nearby, and do it without announcing it.',
    ],
    facts: [
      'His first major book, Poor Folk, was championed by the critic Vissarion Belinsky, who called Dostoevsky a new talent.',
      'During the mock execution the condemned men were tied to posts in groups of three, and Dostoevsky was in the second group when the reprieve was read out.',
      'Notes from the House of the Dead (1860–62), his account of the prison camp, mixes autobiography with fiction.',
      'He wrote The Gambler in 1866 under a tight contract, dictating it to the stenographer Anna Snitkina, whom he married the following year.',
      'The novel Demons (1871–72) drew on the real murder of a student by the revolutionary Sergey Nechaev’s group in 1869.',
      'His Pushkin speech in Moscow in June 1880 was received with extraordinary emotion, and listeners reportedly wept and embraced.',
    ],
    myths: [
      { myth: 'Dostoevsky was a few seconds from death and the mock execution alone changed him.', reality: 'The authorities staged the scene, and the tsar is generally said to have decided on the lesser sentence before the day. The experience marked Dostoevsky deeply and he returned to it in his writing, but the four years in the prison camp and his reading of the Gospels mattered just as much to his change of outlook.' },
      { myth: 'Dostoevsky’s religious characters are simply his mouthpieces.', reality: 'His books allow powerful objections to faith, such as Ivan Karamazov’s protest about the suffering of children, and the answers are shown in lives rather than stated as a final argument. That balance is why readers on every side take him seriously.' },
      { myth: 'He was a straightforward conservative.', reality: 'He began with socialist circles, and his later views are complicated: he defended monarchy and Orthodoxy and was strongly nationalist, while criticising social injustice and the cruelty of the powerful. His antisemitic remarks in A Writer’s Diary, such as in the issue of March 1877, are a documented and troubling part of his record, even though he also denied hating Jews and corresponded politely with Jewish readers.' },
    ],
    works: [
      { title: 'Notes from Underground (1864)', note: 'A short, bitter monologue against the rational utopia, often read as the key to his later work.' },
      { title: 'Crime and Punishment (1866)', note: 'A psychological novel about a murder and its aftermath.' },
      { title: 'The Idiot (1868–69)', note: 'An attempt to portray a truly good man, Prince Myshkin, in a harsh society.' },
      { title: 'Demons (1871–72)', note: 'A novel about revolutionary conspiracy and the moral emptiness of fanatical ideas.' },
      { title: 'The Brothers Karamazov (1879–80)', note: 'His last novel, which takes on faith, doubt, freedom and the murder of a father. It includes the Grand Inquisitor.' },
    ],
    legacy: [
      'Dostoevsky influenced writers, philosophers and psychologists across the twentieth century. Existentialists such as Sartre and Camus read him, and Nietzsche called him the only psychologist from whom he had something to learn. Freud wrote an essay on The Brothers Karamazov. His books are still among the most widely translated in the world.',
      'Readers continue to come to him for his picture of the human mind under pressure: guilt, pride, self-deception, and the sudden need for forgiveness. He also reminds us that a great writer can be both penetrating and flawed. His moral insight and his prejudices came from the same man, and a good reader keeps both facts in sight.',
    ],
  },
  {
    slug: 'leo-tolstoy',
    order: 1828,
    dates: '1828 – 1910',
    place: 'Yasnaya Polyana, Russia',
    era: '19th Century',
    tradition: 'Christian anarchism and moral thought',
    tagline: 'A great novelist who turned away from fame and wealth to preach non-violence and the plain teaching of Jesus.',
    who: [
      'Leo Tolstoy was born on 9 September 1828 (New Style; 28 August in the Russian calendar of the time) at Yasnaya Polyana, the family estate south of Moscow. He was orphaned young and raised by relatives. After an unfinished stretch at Kazan University and some years of a restless, indulgent young life, he joined the army and served in the Caucasus and then in the Crimean War, where he took part in the siege of Sevastopol in 1854–55. His Sevastopol Sketches brought him early fame.',
      'In 1862 he married Sophia Behrs, and for years they lived at Yasnaya Polyana with a growing family. They had thirteen children, of whom eight survived childhood. In this period he wrote War and Peace (published 1865–69) and Anna Karenina (1873–77), two of the greatest novels ever written. He also ran a school for peasant children on his estate and wrote on education.',
      'In the late 1870s he went through a deep crisis of meaning, which he described in A Confession. He came to believe that the teaching of Jesus, above all the Sermon on the Mount, called for non-resistance to evil by violence, and that church and state, which rely on force, had betrayed it. From then on he wrote mostly on faith, morals and society, lived more simply, and gave up some of his privileges, which caused serious tension with Sophia over property and the rights to his works. In October 1910, at 82, he left home secretly, fell ill on the road, and died on 20 November (New Style; 7 November in the Russian calendar) at the small railway station of Astapovo.',
    ],
    context: [
      'Tolstoy came from the Russian landed nobility, at a time when serfdom ended in 1861 and the empire faced questions of poverty, reform and revolution. He saw the wealth of his class and the poverty of the peasants close at hand, and he grew uneasy about the moral basis of that gap. In 1891–92 he took part in famine relief in the Russian countryside.',
      'The Russian Orthodox Church was closely tied to the state, and Tolstoy’s writings on religion were widely banned or circulated abroad and in secret copies. He denied the divinity of Christ as the church taught it and rejected miracles and church ritual, while claiming to be a more faithful follower of Jesus’s moral teaching. In February 1901 the Holy Synod published a declaration that he had fallen away from the church, which is commonly called his excommunication. He replied that he had rejected a church that calls itself Orthodox, because he wanted to serve God.',
    ],
    ideas: [
      { title: 'Non-resistance to evil', text: 'Taking the words “do not resist an evil person” and the command to love one’s enemies at face value, Tolstoy concluded that Christians must not meet violence with violence, whether in war, punishment or self-defence. He argued that evil is overcome by refusing to take part in it and by answering with love. This is the core of his later thought.' },
      { title: 'The kingdom within', text: 'In The Kingdom of God Is Within You (1894), he argued that the true Christian life is a change of inner life and conduct, not membership of an institution. A person who truly lives by the Gospel cannot serve in an army, swear oaths to a state, or approve of the death penalty. Governments, he said, survive because people cooperate with them.' },
      { title: 'Rejecting church and state authority', text: 'Because he thought states and churches depend on force and on claims no one can test, Tolstoy is often called a Christian anarchist. He disliked violent revolutionaries, and his hope was for a peaceful, voluntary change in how people live and think, beginning with each person’s own conscience.' },
      { title: 'Simple, honest living', text: 'He tried to live by his own labour, wore plain clothes, grew his own food on occasion, and became vegetarian. He saw luxury and idleness as a moral problem and held that everyone should do real work. He did not always manage to live as he preached, as his critics, and he himself, noted.' },
      { title: 'Facing death and finding meaning', text: 'In The Death of Ivan Ilyich (1886), a comfortable official comes to see on his deathbed that he has wasted his life on appearances. The story reflects Tolstoy’s conviction that the fear of death is answered not by distraction but by honest love and service to others.' },
    ],
    principles: [
      'Do not answer violence with violence.',
      'Do not take part in what you know to be wrong, even when everyone does.',
      'Live by your own work and avoid luxury.',
      'Love is the measure of a good life, so judge a life by what it gave to others.',
      'Change begins in the conscience of the individual.',
    ],
    practice: [
      'Next time someone wrongs you, pause and decide on a reply that does not repay harm with harm.',
      'Choose one habit of comfort or display that you could give up, and see what it frees you to do.',
      'Do some useful physical work each week, and notice how it changes your sense of your day.',
    ],
    facts: [
      'Tolstoy published War and Peace in instalments, then as a book in 1869; his wife Sophia copied out large parts of his manuscripts by hand.',
      'His 1899 novel Resurrection was written in part to raise money for the Doukhobors, a pacifist sect that was persecuted in Russia and emigrated to Canada.',
      'He started learning to ride a bicycle in 1895, at the age of 66.',
      'He corresponded with the young Mohandas Gandhi in 1909–10, and his A Letter to a Hindu (1908) influenced Gandhi’s thinking on non-violence. Gandhi later gave the name Tolstoy Farm to a community he co-founded in South Africa.',
      'He was nominated for the Nobel Prize in Literature and for the Peace Prize, but never received either.',
      'His final flight from Yasnaya Polyana was a break with the household and a long conflict over his will and copyrights, with Sophia at one pole and some of his followers at the other.',
    ],
    myths: [
      { myth: 'Tolstoy was cursed by the church in a dramatic ceremony.', reality: 'The 1901 act of the Holy Synod was a published declaration that he had fallen away from the church and could not be counted a member unless he repented. It is still called his excommunication, and Tolstoy replied that he had already rejected the church himself.' },
      { myth: 'He lived as a saintly peasant and found peace.', reality: 'Tolstoy lived with a deep gap between ideals and reality. He remained a landowner’s family man, his marriage was strained by conflict over money, children and his teachings, and his last years were painful. Both he and Sophia left detailed diaries that give different accounts.' },
      { myth: 'He rejected all religion.', reality: 'He rejected church doctrine, ritual and authority, but he considered himself a Christian and wrote extensively on the Gospels. His faith was a moral and ethical reading of Jesus’s teaching.' },
    ],
    works: [
      { title: 'War and Peace (1865–69)', note: 'A vast novel of Russian society during the Napoleonic wars, mixing family life, battle and a reflection on history.' },
      { title: 'Anna Karenina (1873–77)', note: 'A novel of love, marriage and moral choice in Russian high society.' },
      { title: 'A Confession (1879–80, published 1882)', note: 'His account of the crisis of meaning that changed his life.' },
      { title: 'The Death of Ivan Ilyich (1886)', note: 'A short novella on death and a life lived on the surface.' },
      { title: 'The Kingdom of God Is Within You (1894)', note: 'His statement of Christian non-resistance, banned in Russia and published abroad.' },
    ],
    legacy: [
      'As a novelist, Tolstoy is often counted among the greatest, and War and Peace and Anna Karenina are read all over the world. His late essays and stories also had a political effect. His idea of non-violent resistance reached Gandhi, and through Gandhi shaped the later campaigns of Martin Luther King Jr. and others. Pacifists and conscientious objectors in many countries cite him.',
      'His legacy is also a lesson in the difficulty of living by one’s ideals. His critics point to the gap between his preaching and his life, and to the suffering in his family. His admirers answer that a person who keeps asking whether he lives honestly is worth reading. Both readings are fair, and together they are the reason Tolstoy still seems close to us.',
    ],
  },
  {
    slug: 'peter-kropotkin',
    order: 1842,
    dates: '1842 – 1921',
    place: 'Moscow, Siberia, Switzerland, France, England and Dmitrov, Russia',
    era: '19th Century',
    tradition: 'Anarchism',
    tagline: 'A prince and geographer turned anarchist, who argued that cooperation is as natural as competition.',
    who: [
      'Peter Kropotkin was born in Moscow on 9 December 1842 (New Style; 27 November in the Russian calendar of the time) into an old princely family. He was educated at the Page Corps, an elite school in Saint Petersburg, where he became a page to the tsar. Instead of a court career, he chose to serve with a Cossack regiment in Siberia, where he spent about five years from 1862.',
      'In Siberia and Manchuria he led expeditions and worked as a geographer, studying the high plateaus and mountains of northern Asia and winning recognition from the Russian Geographical Society. He also observed how peasants and animals survive in harsh conditions. Those years left him doubtful about the usefulness of the state administration he was serving and convinced that ordinary people organise themselves better than officials believe.',
      'After a visit to Switzerland in 1872, where he met workers in the watchmaking communities of the Jura, he became an anarchist. Back in Russia, he joined the Chaikovsky Circle, a network that spread ideas among workers. He was arrested in 1874 and held in the Peter and Paul Fortress, then escaped from a prison hospital in 1876. In exile he lived in Switzerland and France, where he was imprisoned from 1883 to 1886, and then settled in England in 1886. He returned to Russia in June 1917, after the revolution, and died in Dmitrov, near Moscow, on 8 February 1921.',
    ],
    context: [
      'Kropotkin’s lifetime saw rapid industrialisation, the growth of socialist and workers’ movements, and the rise of centralised nation states. Anarchism had grown out of this, as a movement that held that society can function without government and that real freedom needs equality. Kropotkin came to be its best-known writer, with a patient, scientific and humane voice.',
      'He also lived through the debate over Darwin. Some writers took “the struggle for existence” as proof that ruthless competition is the law of life, and Thomas Huxley’s 1888 essay on the struggle for existence in human society was a well-known example. Kropotkin wrote a series of essays in reply, published in the journal The Nineteenth Century between 1890 and 1896, and then in 1902 as the book Mutual Aid.',
    ],
    ideas: [
      { title: 'Mutual aid as a factor of evolution', text: 'In Mutual Aid he argued that cooperation within species is a major force in survival, from insects and birds to mammals and humans. Drawing on his Siberian observations, he claimed that harsh conditions often limit animal populations more than competition for food does, and that species that cooperate tend to thrive. Cooperation, he said, is as much a law of nature as the struggle.' },
      { title: 'A fair reading of Darwin', text: 'Kropotkin did not reject Darwin. He accepted natural selection, and held that Darwin himself had stressed social instincts in The Descent of Man, while some of his followers narrowed the idea to a fight between individuals. His point was one of emphasis: competition exists, but it does not tell the whole story.' },
      { title: 'Anarchist communism', text: 'He believed society should be organised through free, voluntary groups, without a state or private ownership of the means of production, and that goods should be shared according to need. In The Conquest of Bread (1892), he argued that modern industry already produces enough for everyone, and that a revolution should secure well-being for all instead of leaving it to the market.' },
      { title: 'Decentralised work and local life', text: 'In Fields, Factories and Workshops (1899) he proposed that industry and farming should be combined in smaller communities, with workers doing both manual and intellectual work. He hoped technology could ease labour and allow a more balanced life.' },
      { title: 'Ethics from nature', text: 'Kropotkin held that moral feeling arises from social instincts and from the experience of living together. He worked on a book called Ethics, which he left unfinished at his death, to show that ethical life has natural roots and needs neither religious command nor state authority.' },
    ],
    principles: [
      'Cooperation is as natural as competition, and often more productive.',
      'Freedom needs equality, and equality needs freedom.',
      'People can organise themselves without being commanded.',
      'Science should serve human welfare and be open to all.',
      'Combine thinking and doing, head and hands.',
    ],
    practice: [
      'Think about the last time a group of people solved a problem without a boss. What made it work?',
      'Join or help to build something that depends on mutual help, such as a community garden, tool library or neighbourhood group.',
      'When you hear that people are naturally selfish, ask what evidence supports it, and what evidence points the other way.',
    ],
    facts: [
      'He was born a prince, but he gave up the title and wrote as Peter Kropotkin.',
      'As a young geographer he proposed a new view of the structure of Asian mountain ranges, and a mountain range in Siberia was later named for him.',
      'He wrote the entry on anarchism for the eleventh edition of the Encyclopaedia Britannica (1910–11).',
      'His Memoirs of a Revolutionist (1899) were first written in English for an American audience.',
      'During the First World War he supported the Allies against Germany, a stand that split him from many fellow anarchists.',
      'On returning to Russia in 1917 he declined an offer to join the provisional government, and in 1920 he wrote to Lenin criticising the Bolsheviks’ practice of taking hostages.',
    ],
    myths: [
      { myth: 'Kropotkin denied that there is any competition in nature.', reality: 'He wrote that there is a great deal of struggle in nature, and he accepted Darwin’s theory. His claim was that mutual support is equally important, and that cooperating species often do better.' },
      { myth: 'Mutual Aid was a rejection of evolution.', reality: 'It was an argument within evolutionary thought, which asked about the role of cooperation in natural selection. Biologists such as Stephen Jay Gould have noted that cooperation is consistent with natural selection when it helps individuals survive, and the book is seen as an early spur to the scientific study of cooperation.' },
      { myth: 'Anarchism means chaos and violence, and Kropotkin supported it.', reality: 'Kropotkin wanted a stateless society based on voluntary cooperation and local self-government. He did justify revolution, and some anarchists of his time used violence, which he sometimes defended and sometimes criticised. His own writings are mostly calm, scientific and constructive.' },
    ],
    works: [
      { title: 'Mutual Aid: A Factor of Evolution (1902)', note: 'His best-known book, arguing for the importance of cooperation in nature and in human history.' },
      { title: 'The Conquest of Bread (1892)', note: 'First published in French. It sets out his vision of an anarchist-communist economy.' },
      { title: 'Fields, Factories and Workshops (1899)', note: 'A proposal for decentralised, mixed industry and agriculture.' },
      { title: 'Memoirs of a Revolutionist (1899)', note: 'An autobiography covering his life from childhood to his years in England.' },
      { title: 'Modern Science and Anarchism and Ethics', note: 'Later writings on the scientific basis of anarchism and the natural origins of morality. Ethics was left unfinished.' },
    ],
    legacy: [
      'Kropotkin remained the leading theorist of anarchism for decades, and his thought influenced movements in Europe, Latin America and Asia. His funeral in Moscow in February 1921 drew thousands, though by then the Bolshevik state he had criticised was firmly in control. His book on mutual aid became a classic for those who believe that cooperation shapes societies.',
      'Today, his ideas are discussed by ecologists, economists and social scientists who study cooperation, commons and community. Many biologists would say that his emphasis was important and that the study of altruism and cooperation has since become central. Critics note that his picture of human nature is optimistic and that his proposals for stateless societies have not been tested at scale. His work stands as a serious and humane counterweight to the view that life is only competition.',
    ],
  },
]
