import type { Profile } from './types'

export const NINETEENTH_A: Profile[] = [
  {
    slug: 'georg-wilhelm-friedrich-hegel',
    order: 1770,
    dates: '1770 – 1831',
    place: 'Stuttgart, Jena, Nuremberg, Heidelberg and Berlin (Germany)',
    era: '19th Century',
    tradition: 'German idealism',
    tagline: 'He tried to show that history, thought and freedom move forward through conflict, and that every contradiction can lead to something richer.',
    who: [
      'Georg Wilhelm Friedrich Hegel was born on 27 August 1770 in Stuttgart, in the German duchy of Württemberg, to a family of civil servants. He studied theology at the Protestant seminary in Tübingen, where two of his fellow students were the poet Friedrich Hölderlin and the philosopher Friedrich Schelling. The three young men followed the French Revolution with enthusiasm, and the Revolution’s promise of a society based on freedom stayed with Hegel for the rest of his life.',
      'After years as a private tutor, he began teaching at the University of Jena in 1801. His first great book, the Phenomenology of Spirit, was finished in 1806 as Napoleon’s army defeated the Prussians near Jena. Hegel wrote in a letter that he had seen the emperor, “this world-soul”, riding out of the city on horseback. The book appeared in 1807. Hegel then worked as a newspaper editor in Bamberg and as headmaster of a school in Nuremberg, where he wrote the three-volume Science of Logic (1812–1816). In 1811 he married Marie von Tucher.',
      'Professorships followed at Heidelberg in 1816 and at Berlin in 1818, where he held the chair of philosophy that Fichte had once held. In Berlin he became the most famous philosopher in Germany, lecturing on logic, history, art, religion and the history of philosophy to packed halls. He died in Berlin on 14 November 1831, aged 61, during a cholera epidemic. The physicians named cholera as the cause, though some historians think another stomach illness is likelier. Many of his best-known books, such as the lectures on aesthetics and on the philosophy of history, were put together after his death from his own notes and his students’ notes.',
    ],
    context: [
      'Hegel came after Immanuel Kant, who had argued that we know the world only as it appears to a mind that shapes it, and never as it is in itself. Fichte and Schelling tried to repair what they saw as the gaps in Kant’s system, and Hegel set out to go further than both. He wanted a philosophy that could bring together thought and reality, mind and nature, the individual and society, without leaving a dividing line between them.',
      'He also lived through enormous political change: the French Revolution, the Napoleonic wars, the collapse of the old Holy Roman Empire in 1806 and the conservative restoration that followed after 1815. Prussia, where he taught from 1818, was a reforming but still authoritarian state. Much of his thought is an attempt to understand how a modern society can combine individual freedom with a stable community and a lawful state.',
    ],
    ideas: [
      { title: 'Dialectic: progress through contradiction', text: 'Hegel believed that ideas and societies develop by running into their own limits. A view of the world is pushed to its conclusion, shows a tension or contradiction inside itself, and is replaced by a fuller view that keeps what was true in it. He called this movement “dialectic”, a word for reasoning that advances through opposition. His own word for the keep-and-surpass step was Aufhebung, often translated as “sublation”, a term that means to cancel, to preserve and to lift up at once.' },
      { title: 'Spirit and history as the growth of freedom', text: 'Hegel used the word Geist, “spirit” or “mind”, for the shared life of thought and culture that humans create together. He argued that history is not a heap of accidents but the story of spirit coming to understand itself, and he summed it up as progress in the consciousness of freedom. In the ancient East, he said, one person was free, in the classical world some were free, and in the modern world the idea is that all are free. Critics have pointed out that this scheme makes large claims on slim evidence.' },
      { title: 'Recognition and the master and slave', text: 'In the Phenomenology, Hegel describes two self-conscious beings who meet and each demand to be recognised by the other. In the famous scene of lordship and bondage, the one who wins becomes a master and the one who gives in becomes a servant. But the master depends on the servant for everything, while the servant gains skill and self-respect from work. The scene shows that we become selves only through being recognised by other people, a thought that later philosophers, sociologists and political thinkers took up in many ways.' },
      { title: 'Freedom lives in institutions', text: 'In the Elements of the Philosophy of Right (1821), Hegel argued that freedom is not just doing what you like. It takes shape in the family, in civil society, the world of markets and professions, and in the state, which together give people roles, rights and mutual obligations. Real freedom, he thought, means being at home in a world one can recognise as reasonable. Readers still disagree about how much he approved of the Prussian state of his day.' },
      { title: 'The whole is the truth', text: 'Hegel thought that nothing can be understood properly in isolation, because each concept or event gets its meaning from its place within a larger whole. He wrote that “the true is the whole”. This is why his books are so demanding: each step in the argument only makes full sense in light of the entire system. He also held that philosophy always comes late, as in his image that the owl of Minerva, the bird of wisdom, flies at dusk, once a way of life has already taken shape.' },
    ],
    principles: [
      'Treat a contradiction as a sign that your understanding is ready to grow, not as a reason to give up.',
      'Understand things by their history and their place in a larger whole.',
      'You become a self through being recognised by others, so respect their recognition and their independence.',
      'Freedom is more than being left alone: it also means taking part in a shared life that makes sense.',
      'Philosophy understands its own time in thought, and cannot jump ahead of it.',
    ],
    practice: [
      'When you meet an argument you reject, write down what is true in it before writing what is wrong, and see whether a better view contains both.',
      'Before judging an institution or a habit, ask how it came to be and what need it once served.',
      'In a hard relationship, ask whether each side feels recognised, and what each needs from the other in order to be free.',
    ],
    facts: [
      'The popular formula “thesis, antithesis, synthesis” is not Hegel’s. He hardly used those terms. A similar triad appears in Fichte, and the label was attached to Hegel by later commentators such as Heinrich Moritz Chalybäus.',
      'His fellow students at Tübingen, Hölderlin and Schelling, became a major poet and a major philosopher, and the three worked on shared ideas during and after their time at the seminary.',
      'The Phenomenology of Spirit was completed while the battle of Jena was being fought nearby, in October 1806.',
      'Between 1821 and 1831 his lectures at Berlin drew students from across Europe, and by the end of his life he was probably the most influential philosopher in Germany.',
      'His Science of Logic is a study of the basic concepts of thought, such as being, nothing and becoming, rather than of logic in the sense of valid argument forms.',
      'He died on 14 November 1831 and, at his request, was buried in Berlin next to Fichte.',
    ],
    myths: [
      { myth: 'Hegel taught that every idea has a thesis, an antithesis and a synthesis.', reality: 'The triad is a later simplification, and Hegel himself warned against forcing thought into a lifeless schema. His own steps are better described as an idea showing its limits and being taken up into a fuller one.' },
      { myth: 'Hegel was simply the apologist of the Prussian state who thought whatever exists is right.', reality: 'His line that the rational is actual and the actual is rational is easily misread, since by “actual” he meant what truly realises its potential, not whatever happens to exist. Scholars disagree about his politics: he argued for a constitution, the rule of law and public debate, and some read him as a reformer and others as a conservative.' },
    ],
    works: [
      { title: 'Phenomenology of Spirit (1807)', note: 'A journey through forms of consciousness, from simple sense-experience to absolute knowing, including the scene of lordship and bondage.' },
      { title: 'Science of Logic (1812–1816)', note: 'His long and difficult account of the basic categories of thought, in three volumes.' },
      { title: 'Encyclopaedia of the Philosophical Sciences (1817; revised 1827 and 1830)', note: 'A compact outline of his whole system: logic, nature and spirit.' },
      { title: 'Elements of the Philosophy of Right (1821)', note: 'His political and moral philosophy, covering family, civil society and the state.' },
      { title: 'Lectures on aesthetics, the philosophy of history, religion and the history of philosophy', note: 'Published after his death from lecture notes. The history lectures include views on non-European peoples, and especially on Africa, that are widely criticised today as Eurocentric and dismissive.' },
    ],
    legacy: [
      'Hegel’s followers split soon after his death. The Right Hegelians stressed his defence of religion and the state, and the Left or Young Hegelians, including Ludwig Feuerbach and Karl Marx, turned his method of dialectic against existing society and religion. Marx said he had “inverted” Hegel, keeping the dynamic of conflict but placing it in material and economic life rather than in spirit. Kierkegaard, by contrast, defined much of his own philosophy as a protest against Hegel’s system.',
      'In the twentieth century Hegel was rediscovered in many forms: in the Marxism of the Frankfurt School, in existentialism, in French philosophy through Alexandre Kojève’s lectures, and in the pragmatists and recent philosophers who study his ideas on recognition, freedom and social life. Whether or not one accepts his system, his claim that ideas and institutions are historical and develop through their own tensions became a basic assumption of modern thought.',
    ],
  },
  {
    slug: 'arthur-schopenhauer',
    order: 1788,
    dates: '1788 – 1860',
    place: 'Danzig (now Gdańsk), Hamburg, Dresden, Berlin and Frankfurt',
    era: '19th Century',
    tradition: 'Pessimism',
    tagline: 'A fierce and elegant writer who saw the world as driven by a blind striving, and who looked to art and compassion for relief.',
    who: [
      'Arthur Schopenhauer was born on 22 February 1788 in Danzig, now Gdańsk in Poland, into a rich merchant family. When Prussia took over the city in 1793, his family moved to Hamburg. His father, Heinrich Floris, wanted him to follow a business career, and gave him a long tour of Europe as a boy. After his father died in 1805, probably by suicide, Schopenhauer eventually left commerce, studied at Göttingen and Berlin, and took his doctorate at Jena in 1813 with a dissertation on the principle of sufficient reason.',
      'His mother, Johanna, became a successful novelist and hosted a literary circle in Weimar. The two quarrelled and parted in 1814, and he never saw her again. In Weimar he met Goethe, with whom he discussed the theory of colour, and in Dresden he wrote his masterpiece, The World as Will and Representation, which came out at the end of 1818. In 1820 he became a lecturer at the University of Berlin and, with great self-confidence, scheduled his classes at the same hours as those of Hegel. Very few students came to his, and he gave up on an academic career.',
      'In 1833 he settled in Frankfurt, where he lived quietly for 27 years, played the flute, kept a series of poodles and published little that anyone noticed. A prize essay on the freedom of the will won recognition from a Norwegian society in 1839, but wide fame came only with the essays of Parerga and Paralipomena in 1851, when he was 63. He spent his last years as a celebrity among admirers, and died in Frankfurt on 21 September 1860.',
    ],
    context: [
      'Schopenhauer saw himself as the true heir of Kant. Kant had argued that the world we know is shaped by our own minds, in space, time and cause and effect, while the thing in itself stays hidden. Schopenhauer accepted this and then claimed to have found a way to open it up: we know our own body from the inside as well as from the outside, and what we find from the inside is will. He had little patience for Fichte, Schelling and Hegel, whose complex language he thought was a cover for confusion.',
      'He was also one of the first major European philosophers to take Indian thought seriously. He read the Upanishads in a Latin translation and admired Buddhism, and he thought that Indian and Western traditions had arrived at similar insights about illusion and suffering. The age of Romanticism, with its interest in feeling, music and the dark side of life, was the background for his gloomy but beautifully written work.',
    ],
    ideas: [
      { title: 'The world is my representation', text: 'The opening words of his major book say that the world is “my representation”. Everything we perceive is an appearance for a mind that organises it through space, time and causes. This is a refinement of Kant, but expressed in a more vivid, more direct way. What we see is always a view for someone, and it points beyond itself to something we do not yet know.' },
      { title: 'The will behind appearances', text: 'Schopenhauer believed that the inner nature of the world is will: a blind, aimless striving, with no purpose and no goal. We feel it in ourselves as hunger, desire, fear and longing, and he saw the same force in gravity, in growth and in the instincts of animals. Unlike the rational God of earlier philosophers, this will has no wisdom and no plan.' },
      { title: 'Life as striving, suffering and boredom', text: 'Because the will never has a final aim, he thought, we are always wanting something. Desire hurts while it lasts, satisfaction is brief, and then boredom or a new craving comes. This is the basis of his philosophical pessimism: not a mood but an argument that suffering is built into a life of endless wanting. He rejected suicide as an answer, since in his view it only expresses the will’s urge to live.' },
      { title: 'Art and music as relief', text: 'In deep aesthetic contemplation, he said, we forget ourselves and our wants and see the lasting patterns behind things, and for a moment the pressure of the will lifts. He gave music a unique place, as an art that does not copy the world but directly expresses the will itself. This idea moved many composers, above all Richard Wagner.' },
      { title: 'Compassion and the denial of the will', text: 'For Schopenhauer, morality starts with compassion, the felt recognition that another’s suffering is like my own, because we are all expressions of the same will. The deepest relief, in his view, is a turning away from the will’s demands, which he saw in saints and ascetics, and which he compared with Christian and Indian traditions of renunciation.' },
    ],
    principles: [
      'Look at the world for what it is, and do not expect it to reward every effort.',
      'Wanting is a source of suffering, so keep your desires modest.',
      'Take time for quiet attention to beauty, since it can free you from your own worries.',
      'Treat others’ pain as akin to your own: compassion is the basis of ethics.',
      'Think for yourself and write clearly.',
    ],
    practice: [
      'When you are restless, notice what you want and how long the satisfaction lasts, and see whether the wanting itself is the problem.',
      'Set aside time each week to look at a landscape, a painting or listen to a piece of music with full attention and no other aim.',
      'When someone is difficult, remind yourself that they, too, are struggling with wants and fears like yours.',
    ],
    facts: [
      'His 1813 dissertation, On the Fourfold Root of the Principle of Sufficient Reason, argues that the principle that everything has a ground takes four different forms: grounds of becoming, of knowing, of being and of acting.',
      'He kept several pet poodles, including one he named Atman, the Indian word for the self.',
      'He deliberately put his Berlin lectures at the same hour as Hegel’s, and attracted only a handful of students.',
      'He won the 1839 prize of the Royal Norwegian Society of Sciences for his essay on the freedom of the will. The Danish society to which he sent his essay on the basis of morality did not give him the prize, though his was the only entry.',
      'Friedrich Nietzsche read his main book as a student and wrote a famous essay, Schopenhauer as Educator, though he later broke with Schopenhauer’s pessimism.',
      'He is known for a parable about porcupines in winter, who move close together for warmth and then move apart when they prick each other, an image of the need for polite distance between people.',
    ],
    myths: [
      { myth: 'Schopenhauer’s pessimism means he recommended suicide.', reality: 'He argued the opposite. In his view suicide does not escape the will but expresses its strongest drive, and the real relief lies in compassion, art and in the calming of desire.' },
      { myth: 'He was only a gloomy hermit who hated everyone.', reality: 'He was quarrelsome and vain, and his writing about women is a notable weakness: his essay “On Women” makes sweeping and demeaning claims that few readers today defend, and it contrasts with his own ideal of compassion. But he also had friends and admirers, loved music and animals, and argued strongly for kindness to animals.' },
    ],
    works: [
      { title: 'On the Fourfold Root of the Principle of Sufficient Reason (1813)', note: 'His doctoral thesis, and the groundwork for the later system.' },
      { title: 'The World as Will and Representation (1818; expanded 1844 and 1859)', note: 'His main book, in four parts: knowledge, nature, art and ethics. The second edition added a volume of essays.' },
      { title: 'On the Freedom of the Will (1839) and On the Basis of Morality (1840)', note: 'Two prize essays, later published together as The Two Fundamental Problems of Ethics.' },
      { title: 'Parerga and Paralipomena (1851)', note: 'Two volumes of essays, including the practical “Aphorisms on the Wisdom of Life”, which brought him a wide readership.' },
    ],
    legacy: [
      'Schopenhauer’s influence on culture was far greater than on university philosophy during his lifetime. Wagner read him in the 1850s and drew on his ideas for Tristan and Isolde, and Nietzsche, Thomas Mann, Tolstoy and many others were shaped or provoked by him. Philosophers such as Wittgenstein admired his thought, and Freud noticed the resemblance between the will and his own idea of the unconscious drives.',
      'He remains a vivid voice for the view that human life is shaped by deep, non-rational forces, and for the claim that attention, art and sympathy can relieve suffering. Critics argue that his pessimism is too sweeping and his metaphysics unproven, but his account of desire and his lucid prose still find readers.',
    ],
  },
  {
    slug: 'john-stuart-mill',
    order: 1806,
    dates: '1806 – 1873',
    place: 'London, England, and Avignon, France',
    era: '19th Century',
    tradition: 'Utilitarianism and liberalism',
    tagline: 'A prodigy who rebuilt utilitarianism around human development, and who argued that people should be free to live as they choose so long as they do not harm others.',
    who: [
      'John Stuart Mill was born in London on 20 May 1806, the eldest son of the Scottish philosopher and historian James Mill. His father, a close friend of the reformer Jeremy Bentham, gave him an extraordinarily strict education at home. According to Mill’s own account, he began Greek at the age of three and Latin at eight, and worked through history, logic and economics while still a boy. He later wrote that his early training left his emotional life undeveloped.',
      'At 17 he took a job at the East India Company, where he worked until 1858 and rose to be head of its department dealing with Indian correspondence. In 1826, at the age of 20, he fell into a deep depression, asking himself whether he would be happy even if all his goals for reform were achieved. He recovered gradually, helped by the poetry of Wordsworth, and concluded that happiness has to be pursued indirectly, along with cultivation of feeling and character. In the 1830s he became close to Harriet Taylor, whom he married in 1851, two years after her first husband’s death; he credited her with a deep influence on his work.',
      'After Harriet died in 1858 in Avignon, he bought a house near her grave and spent much of his remaining life there. He served as an independent Member of Parliament for Westminster from 1865 to 1868, where he supported votes for women and spoke up for other reforms. He died in Avignon on 7 May 1873, and his Autobiography appeared later that year.',
    ],
    context: [
      'Mill grew up in Britain’s age of reform: the Industrial Revolution created new wealth and new misery, the vote was still limited to a small part of the population, and the educated debated whether society should be remade by reason. His father and Bentham belonged to the Philosophical Radicals, who argued that laws and institutions should be judged by whether they increase the happiness of the greatest number. Mill grew up as the movement’s hope, then came to feel it was too narrow.',
      'Britain was also the centre of a vast empire, and Mill worked inside its machinery. Like many liberals of his day, he accepted the idea that societies could be ranked by their degree of civilisation, and this shaped some of his opinions on colonial government, which are discussed below.',
    ],
    ideas: [
      { title: 'Utilitarianism with quality of pleasure', text: 'Utilitarianism holds that actions are right when they promote happiness and wrong when they produce the opposite. Mill’s Utilitarianism (1861) defended the view against the charge that it was a doctrine for pigs. He argued that pleasures differ in quality: those who have experienced both generally prefer the pleasures of thought, feeling and imagination. In his words, it is better to be a human being dissatisfied than a pig satisfied, and better to be Socrates dissatisfied than a fool satisfied.' },
      { title: 'The harm principle', text: 'On Liberty (1859) states that the only good reason for society to use power over a person against their will is to prevent harm to others. A person’s own good, physical or moral, is not enough. Within this limit, adults should be free to think, speak and live as they wish. The principle was not meant to apply to children or to people he thought were not yet capable of improving themselves through free discussion, a qualification that carries heavy consequences in his view of empire.' },
      { title: 'Free speech and the value of being wrong', text: 'Mill argued that silencing an opinion is a loss even when it is false. If the opinion is true, we lose the truth. If it is partly true, we lose a part of it, and if it is false, we lose the chance to see the truth more clearly by testing it against error. Beliefs that are never challenged, he thought, harden into dead dogma.' },
      { title: 'Individuality and experiments in living', text: 'He thought human beings are like trees rather than machines: they grow in different directions, and a society needs a variety of characters and “experiments in living”. The pressure of custom and public opinion, which he saw as a danger as serious as the power of the state, tends to crush originality.' },
      { title: 'Equality for women and a fairer society', text: 'The Subjection of Women (1869) argued that the legal subordination of women to men was wrong and held back all of society. He also supported proportional representation, workers’ cooperatives and trade unions. In 1867 he proposed, unsuccessfully, an amendment to the Reform Bill that would have extended the vote to women on the same terms as men.' },
    ],
    principles: [
      'Judge actions by their effects on the happiness of everyone affected, counting each person equally.',
      'Not all pleasures are equal: seek those that use your best faculties.',
      'Your freedom stops where it harms others, and not where others merely disapprove.',
      'Let ideas, including ones you dislike, be tested in open argument.',
      'Develop your own character, and let others do the same.',
    ],
    practice: [
      'Before a decision, list who is affected and how, including people you rarely think about.',
      'Seek out the strongest version of a view you disagree with, and try to state it so fairly that its supporters would accept it.',
      'When you feel inclined to stop someone doing something, ask whether it truly harms others or only offends you.',
    ],
    facts: [
      'By his own account he learned Greek at three and Latin and algebra at eight, and he later helped teach his younger siblings.',
      'The 1826 crisis, described in his Autobiography, made him think about the role of emotion and art, and shifted his utilitarianism towards the culture of the whole person.',
      'He worked for the East India Company for 35 years, from 1823 to 1858, and argued in its defence when the British government took over its powers after the 1857 rebellion.',
      'He chaired the Jamaica Committee, formed to press for the prosecution of Governor Edward Eyre over the severe repression of an uprising in Jamaica in 1865.',
      'On Liberty is dedicated to Harriet, who had died the year before, and he said it owed much to her.',
      'He was the secular godfather of the future philosopher Bertrand Russell.',
    ],
    myths: [
      { myth: 'Mill believed in freedom for everyone in all circumstances.', reality: 'On Liberty applies only to adults in societies he considered mature enough to improve through discussion. He wrote that despotism is a legitimate form of government for “barbarians”, if the aim is their improvement, and he defended the East India Company’s rule in India. These views reflect the paternalistic and hierarchical assumptions of his time and are widely criticised today.' },
      { myth: 'Utilitarianism, in Mill’s version, is about adding up crude pleasure.', reality: 'Mill explicitly rejected this, and he distinguished higher and lower pleasures, and he gave a large role to character, dignity and liberty. Philosophers still argue about whether his quality distinction fits with the utilitarian principle, but the crude version was not his.' },
    ],
    works: [
      { title: 'A System of Logic (1843)', note: 'A major treatise on reasoning and scientific method, long used as a textbook.' },
      { title: 'Principles of Political Economy (1848)', note: 'A leading economics text for decades, in later editions more sympathetic to cooperative and socialist ideas.' },
      { title: 'On Liberty (1859)', note: 'His best-known short book, on freedom of thought, speech and individuality.' },
      { title: 'Utilitarianism (1861) and Considerations on Representative Government (1861)', note: 'The first states his moral theory, and the second his views on democracy, including the protection of minorities.' },
      { title: 'The Subjection of Women (1869) and Autobiography (1873)', note: 'A case for equality between the sexes, and the story of his education and mental crisis.' },
    ],
    legacy: [
      'On Liberty is among the most quoted defences of free speech and personal freedom, and the harm principle appears regularly in debates about law, from censorship to drug policy. Mill’s arguments for women’s equality were ahead of the opinion of his time, and many of the reforms he supported, including votes for women, became law long after his death.',
      'His reputation also now includes a more critical view of his role in empire, where his liberal principles sat beside real authority over the lives of millions. Scholars continue to debate how far this was a flaw in his philosophy and how far it was an inconsistency. Either way, his work remains a reference point for anyone who asks how much freedom a society should allow.',
    ],
  },
  {
    slug: 's-ren-kierkegaard',
    order: 1813,
    dates: '1813 – 1855',
    place: 'Copenhagen, Denmark',
    era: '19th Century',
    tradition: 'Existentialism',
    tagline: 'He asked what it means to become a real individual before God, and wrote under invented names to make readers think for themselves.',
    who: [
      'Søren Kierkegaard was born on 5 May 1813 in Copenhagen, the youngest child of Michael Pedersen Kierkegaard, a wealthy retired merchant with a serious and often gloomy religious outlook. Several of his siblings died young, and the shadow of guilt and death hung over the household. He studied theology at the University of Copenhagen and in 1841 defended his master’s thesis, On the Concept of Irony, which dealt with Socrates.',
      'In 1840 he became engaged to Regine Olsen, and in 1841 he broke off the engagement. He gave his own melancholy and sense of calling as reasons, and the episode troubled him for years and appears in disguised form in several of his books. After the break he went to Berlin, where he heard the philosopher Schelling lecture and wrote much of Either/Or, which came out in February 1843. For the next few years he published at a remarkable rate, living mostly on his inheritance and walking the streets of Copenhagen, where he talked with all kinds of people.',
      'In late 1845 he quarrelled with the satirical paper The Corsair, which then mocked him in print and in cartoons for months, and he felt it had made him a public laughing-stock. In his last years he turned fiercely against the Danish state church, which he thought had turned Christianity into a comfortable social habit, and published a series of pamphlets called The Moment in 1855. He collapsed in the street in October of that year and died on 11 November 1855 in Frederiks Hospital, aged 42. He refused to take communion from a pastor, whom he saw as an official of the state. He was buried in Assistens Cemetery in Copenhagen.',
    ],
    context: [
      'Denmark in the early nineteenth century was a small, mostly peaceful Lutheran country, living through a cultural flowering known as the Danish Golden Age. Everyone was baptised into the state church, and Hegel’s philosophy was fashionable among Danish intellectuals. Kierkegaard felt that it was easy to be a Christian by birth and a spectator of ideas, and he wanted to confront readers with the need to decide how to live.',
      'He was writing against Hegel’s idea that philosophy could explain everything within one system. To Kierkegaard, a system might explain the world, but it could not tell a particular person how to live, love and die. His thinking is therefore about the person living a life, with fears, choices and a short time, and this concern is why he is seen as a forerunner of existentialism, a movement that took form well after his death.',
    ],
    ideas: [
      { title: 'Writing under pseudonyms', text: 'Kierkegaard published many of his major books under invented names, such as Victor Eremita, Johannes de Silentio, Johannes Climacus and Anti-Climacus. Each name stands for a point of view, so the reader has to judge it rather than simply accept the author’s authority. It also let him explore ways of living, from playful aesthete to anxious believer, without claiming that each was his own.' },
      { title: 'Three stages of existence', text: 'He described different ways of life, often called the aesthetic, the ethical and the religious. The aesthetic life seeks enjoyment and interest, and risks emptiness and boredom. The ethical life commits to duties and promises, such as marriage and work. The religious life stands before God as an individual, and is the hardest, because it may be at odds with what the world expects. These are not rigid steps and the pseudonyms do not agree on every detail.' },
      { title: 'Faith as a leap', text: 'In Fear and Trembling (1843), Johannes de Silentio retells the biblical story of Abraham, who is told to sacrifice his son Isaac, as a case in which faith goes beyond ordinary moral reasoning. Kierkegaard’s works speak of faith as a “leap”, a commitment that cannot be proved by argument, and which still must be made with passion. The common phrase “leap of faith” sums this up, though he used the word “leap” more often than the exact phrase. Readers still argue about what the story shows.' },
      { title: 'Anxiety and despair', text: 'In The Concept of Anxiety (1844), he describes anxiety as the “dizziness of freedom”, the feeling that arises when we see that we are free to choose, and that nothing can choose for us. In The Sickness unto Death (1849), published under the name Anti-Climacus, he describes despair as a sickness of the self, found even in people who seem content, and he defines it as the failure to become oneself before God.' },
      { title: 'Truth as lived inwardly', text: 'In the Concluding Unscientific Postscript (1846), Johannes Climacus says that for the most important questions, such as how to live, objective information is not enough. What counts is how a person relates to the truth, with inward passion and commitment. He wrote that subjectivity matters most in this domain. This is not a claim that anything goes, but a claim that some truths can only be held by living them.' },
    ],
    principles: [
      'Do not hide in the crowd: become a single individual who takes responsibility for your own life.',
      'Be wary of knowing about things without acting on what you know.',
      'Take anxiety as a sign that you are free, not only as a problem.',
      'Do not mistake an easy, inherited habit for real commitment.',
      'Ask what it would mean to live out your beliefs.',
    ],
    practice: [
      'Choose one belief you hold and ask what you would do differently each day if you truly lived by it.',
      'When you feel anxious about a choice, write down what you are free to do, and take one real step.',
      'In a journal, try writing a view you do not hold from the inside, as one of his pseudonyms might.',
    ],
    facts: [
      'He remarked in a journal in 1843 that life can only be understood backwards, but that it has to be lived forwards.',
      'He broke his engagement to Regine Olsen on 11 August 1841, about a year after he proposed, and she later married another man.',
      'He wrote at great speed, and his books appeared in rapid succession. Fear and Trembling and Repetition came out on the same day in October 1843.',
      'He wrote many works under pseudonyms, and published religious “upbuilding discourses” under his own name.',
      'When he collapsed in 1855, he was working on the tenth issue of The Moment.',
      'At his funeral his nephew Henrik Lund protested that the church was burying a man who had attacked it.',
    ],
    myths: [
      { myth: 'Kierkegaard was an atheist, or an enemy of reason.', reality: 'He was a committed Christian who wanted to make faith serious again. He criticised the church of his day for turning Christianity into habit, and his emphasis on faith’s paradox is not a rejection of thinking but a claim about its limits.' },
      { myth: 'The “leap of faith” means believing without any reason.', reality: 'For Kierkegaard the leap is a decision of the whole person under uncertainty, not a blind guess, and it often follows long reflection. His pseudonyms differ on how reason and faith relate, and scholars still debate the point.' },
    ],
    works: [
      { title: 'Either/Or (1843)', note: 'A two-volume work that sets the aesthetic and ethical ways of life against each other, edited by the pseudonym Victor Eremita.' },
      { title: 'Fear and Trembling (1843)', note: 'A reflection on Abraham and Isaac, and on what faith asks.' },
      { title: 'Philosophical Fragments (1844) and Concluding Unscientific Postscript (1846)', note: 'Two works by Johannes Climacus on faith, truth and what it is to become a Christian.' },
      { title: 'The Concept of Anxiety (1844) and The Sickness unto Death (1849)', note: 'Psychological studies of freedom, anxiety and despair.' },
      { title: 'Works of Love (1847)', note: 'A work published under his own name on the Christian command to love one’s neighbour.' },
    ],
    legacy: [
      'Kierkegaard was little read outside Scandinavia during his life, but in the early twentieth century his books were translated into German and French and had a powerful effect. Martin Heidegger, Karl Jaspers and Jean-Paul Sartre drew on his ideas about anxiety, choice and the individual, and the Protestant theologians Karl Barth and Paul Tillich took up his sense of the distance between God and humanity.',
      'Today his writing is read by philosophers, theologians, psychologists and literary scholars. Some see him mainly as a religious writer, and others as a founder of the existential approach to life. Whatever view one takes, his main question stays fresh: how can I live my own life, honestly, when no argument can do the living for me?',
    ],
  },
  {
    slug: 'karl-marx',
    order: 1818,
    dates: '1818 – 1883',
    place: 'Trier, Paris, Brussels and London',
    era: '19th Century',
    tradition: 'Marxism',
    tagline: 'He argued that economic life shapes society and history, and that capitalism contains conflicts that would end in its transformation.',
    who: [
      'Karl Marx was born on 5 May 1818 in Trier, in the Prussian Rhineland. His father, Heinrich, was a lawyer from a Jewish family who had converted to Protestantism. Marx studied law at Bonn and then Berlin, where he turned to philosophy and joined the circle of Young Hegelians. He received his doctorate from the University of Jena in 1841 with a thesis on the natural philosophies of Democritus and Epicurus.',
      'After editing a liberal newspaper in Cologne, the Rheinische Zeitung, which the Prussian government shut down in 1843, he married Jenny von Westphalen and moved to Paris. There he met Friedrich Engels in 1844, and began a lifelong friendship and collaboration. Expelled from France, he lived in Brussels, and together with Engels he wrote the Communist Manifesto, published in February 1848. After the revolutions of that year failed, he was driven out of Prussia and, in 1849, settled in London for good, a stateless exile.',
      'In London he lived for years in poverty and illness, supported largely by Engels and by his journalism, including articles for the New-York Daily Tribune from 1852 to 1862. Several of his children died young. He spent much of his time reading and writing in the British Museum library, and the first volume of Capital appeared in 1867. He helped lead the International Workingmen’s Association from 1864. He died at home in London on 14 March 1883 and was buried in Highgate Cemetery, where Engels spoke at the graveside.',
    ],
    context: [
      'Marx wrote during the Industrial Revolution, when factories, railways and cities were transforming Europe. The new wealth came with long hours, child labour and crowded slums, and many workers had little say in political life. Socialist and workers’ movements were growing, and the revolutions of 1848 spread across the continent. He sought to give these movements a scientific base by studying how the economy actually worked.',
      'His intellectual sources were German philosophy, especially Hegel, French socialism and British political economy, which he drew from Adam Smith and David Ricardo. He famously said that he took Hegel’s dialectical way of thinking, but placed it on a material footing: change in history, he argued, begins in how people produce what they need, and not in the movement of ideas.',
    ],
    ideas: [
      { title: 'Historical materialism', text: 'Marx argued that the way a society produces goods, its economic base, shapes its laws, politics and ideas. The tools, skills and relations between owners and workers change over time, and when the old social arrangement holds back production, conflict and change follow. In his summary, the history of all hitherto existing society is the history of class struggles. Historians and philosophers still debate how strictly he meant this and how far economics determines everything else.' },
      { title: 'Alienation', text: 'In his early writings, the Economic and Philosophic Manuscripts of 1844, Marx described how wage labour under capitalism can separate workers from the products they make, from the activity of work, from other people and from their own human capacities. Work, which should be a creative expression of a person, becomes a means of survival under someone else’s control.' },
      { title: 'Capital, exploitation and surplus value', text: 'In Capital, Marx analysed capitalism as a system in which workers sell their labour power for a wage and produce more value than they are paid. The difference, which he called surplus value, goes to the owners of capital as profit. He also described how competition drives firms to accumulate and expand, producing crises and growing inequality. Economists today disagree strongly about his theory of value.' },
      { title: 'Ideology and commodity fetishism', text: 'Marx argued that the ruling ideas of a society often serve the interests of its dominant class and make an unequal order seem natural. He used the term commodity fetishism for the way that, in a market economy, relations between people appear as relations between things with prices, which hides how goods are produced.' },
      { title: 'Philosophy as a tool to change the world', text: 'The eleventh of his Theses on Feuerbach (1845) says that philosophers have only interpreted the world in various ways, and the point is to change it. He saw the working class as the force that could do this, and he expected capitalism to give way to a classless society. He wrote little about what that society would look like, though in his Critique of the Gotha Programme he mentions the principle “from each according to his ability, to each according to his needs”.' },
    ],
    principles: [
      'Look at who owns and who works, and who benefits, before accepting a story about how society works.',
      'Understand ideas in their historical and material setting.',
      'Work should be a meaningful, creative activity and not only a means of survival.',
      'Be sceptical of ideas that conveniently justify the position of the powerful.',
      'Knowledge should be tested by whether it helps change conditions for the better.',
    ],
    practice: [
      'When you read about an economic or political change, ask who gains and who loses, and what the effect is on ordinary working lives.',
      'Look at your own work and ask which parts feel like your own contribution and which feel imposed or empty.',
      'Study how a familiar custom or belief began, and whether its history changes how natural it seems.',
    ],
    facts: [
      'He was stateless from 1845, after giving up his Prussian citizenship, until his death in 1883.',
      'Engels, whose family owned a textile business, supported Marx financially for decades, and edited the second and third volumes of Capital after Marx’s death, published in 1885 and 1894.',
      'The Communist Manifesto was commissioned by the Communist League and first published in London in February 1848.',
      'The German Ideology, written in 1845–46 with Engels, was not published in full until 1932.',
      'Engels reported that Marx once said, of some French followers, that if anything was certain it was that he himself was not a Marxist.',
      'His doctoral thesis, completed in 1841, compared the natural philosophies of the ancient atomists Democritus and Epicurus.',
    ],
    myths: [
      { myth: 'Marx designed the communist states of the twentieth century.', reality: 'He wrote very little about how a communist society would be organised, and he expected revolution first in industrial countries. The governments of the Soviet Union, China and other states that claimed his name were one-party systems with widespread repression. Scholars disagree about how far they followed from his ideas, and many Marxists and non-Marxists reject the link.' },
      { myth: 'Marx said that religion should be banned, or that everything is determined by money.', reality: 'His famous line that religion is the “opium of the people” describes it as comfort for suffering, and not a call for prohibition. He also gave a large role to ideas and politics, though he held that material conditions limit and shape them.' },
    ],
    works: [
      { title: 'Economic and Philosophic Manuscripts of 1844', note: 'Early notebooks on alienation, published only in the twentieth century.' },
      { title: 'The Communist Manifesto (1848, with Engels)', note: 'A short, forceful statement of the view of history as class struggle, and a call to action.' },
      { title: 'The Eighteenth Brumaire of Louis Bonaparte (1852)', note: 'A sharp analysis of the French coup of 1851, containing the line that history repeats itself, first as tragedy, then as farce.' },
      { title: 'Capital, Volume I (1867)', note: 'His major study of capitalism; Volumes II and III were edited by Engels and published after his death.' },
      { title: 'The Civil War in France (1871) and Critique of the Gotha Programme (1875)', note: 'Writings on the Paris Commune and on the aims of the socialist movement.' },
    ],
    legacy: [
      'Marx’s ideas shaped labour and socialist movements around the world, and in the twentieth century governments in the Soviet Union, China, Cuba and elsewhere ruled in his name. Their record, which includes industrialisation and literacy campaigns as well as dictatorship, forced collectivisation, famine and political terror, is a subject of continuing historical debate, and it left Marx’s reputation deeply contested.',
      'Outside party politics, his influence runs through economics, sociology, history, literary study and philosophy. Concepts such as class, ideology, alienation and the importance of economic structure are used even by people who reject his conclusions. His writing about colonialism is also debated: in his 1853 articles on India he condemned British brutality, but also described British rule as a force that was breaking up old village society, relying on stereotypes of an unchanging Asia. In later years, his writing on Ireland and Russia shows him paying more attention to non-European societies, and scholars differ on how far his views changed.',
    ],
  },
]
