import type { Profile } from './types'

export const PRESOCRATIC: Profile[] = [
  {
    slug: 'thales',
    order: -624,
    dates: 'c. 624 – c. 546 BC',
    place: 'Miletus, Ionia (now western Turkey)',
    era: 'Ancient',
    tradition: 'Presocratic',
    tagline: 'The first thinker on record to ask what the world is made of, and to answer without turning to the gods.',
    who: [
      'Thales lived in Miletus, a prosperous Greek port on the coast of Ionia, in what is now western Turkey. Later writers dated his life to roughly 624–546 BC, and they counted him among the Seven Sages, a group of early Greeks famous for practical wisdom. Aristotle, writing about two centuries after Thales’s death, called him the founder of the kind of philosophy that looks for the material principle behind all things.',
      'Nothing that Thales wrote survives, and he may have written nothing at all. Everything we know comes from later authors: Herodotus in the fifth century BC, Plato and Aristotle in the fourth, and Diogenes Laertius in the third century AD. The stories about him therefore mix real tradition with legend, and historians treat the details cautiously.',
      'What is beyond doubt is the kind of question he asked. Where earlier Greeks explained the world through stories of gods, such as Poseidon shaking the earth, Thales and his successors in Miletus asked what the world is made of and how it changes, and they gave answers that others could test, criticise and improve. That habit of giving reasons instead of myths is why he is often called the first philosopher, and the first scientist, of the Western tradition.',
    ],
    context: [
      'Miletus was a rich trading city with links to Egypt, Lydia, the Black Sea and Phoenicia. Merchants and travellers brought ideas as well as goods: Egyptian land surveying, Babylonian records of the stars and eclipses, and many different religious accounts of how the world began. Meeting competing stories may have pushed thoughtful people to ask which of them, if any, was true.',
      'In Thales’s old age the region came under Persian rule, after the Persian king Cyrus conquered the Lydian kingdom around 546 BC. Greek philosophy began in this meeting of cultures on the eastern edge of the Greek world, not in Athens, which became important only a century later.',
    ],
    ideas: [
      { title: 'Water is the source of everything', text: 'Aristotle reports that Thales held water to be the basic stuff of all things. Aristotle guesses at his reasons: that nourishment is moist, that heat itself comes from moisture, and that the seeds of all things are moist. We cannot be sure of Thales’s own reasoning, but the claim matters for its form. It names a single natural substance as the source of everything and treats the variety of the world as changes in that one thing.' },
      { title: 'Nature explains nature', text: 'Thales is said to have explained earthquakes by supposing that the flat Earth floats on water and is rocked by waves, as a ship is. The explanation is wrong, but the method is new. It appeals to a cause anyone can imagine and discuss, with no god required. This is the seed of scientific explanation: a claim about nature that can be examined and replaced by a better one.' },
      { title: 'The beginnings of geometry', text: 'Later Greek writers credit him with introducing geometry to Greece from Egypt and with proving a handful of basic results: that a circle is cut in half by its diameter, that the angles at the base of an isosceles triangle are equal, that the opposite angles formed by two crossing lines are equal, and that a triangle is fixed by one side and the two angles beside it. Whether he gave proofs in the later sense is debated, but tradition places the start of Greek mathematics with him.' },
      { title: 'Measuring what you cannot reach', text: 'Diogenes Laertius reports, citing an earlier source, that Thales measured the height of an Egyptian pyramid by waiting for the hour when a person’s shadow equals their height, and then measuring the pyramid’s shadow. The idea of using proportion to measure what cannot be reached directly is an early example of applied reasoning.' },
      { title: 'A world alive with power', text: 'Aristotle says Thales thought the magnet has a kind of soul because it moves iron, and later writers add that he said the same about amber. Whatever he meant, he seems to have felt that life and motion are widespread in nature, and not something added from outside.' },
    ],
    principles: [
      'Ask what something is made of, and how it works, before asking which god is angry.',
      'Prefer explanations that others can examine and test.',
      'Look for the single pattern behind many different things.',
      'Use what you learn to solve real problems.',
      'Begin with honest self-knowledge. Ancient writers credit the maxim “know thyself” to several of the Seven Sages, Thales among them.',
    ],
    practice: [
      'When something puzzling happens, write down at least two natural explanations before choosing one.',
      'When you hear a confident claim, ask how anyone could know it: what could be measured or observed?',
      'Pair curiosity with practical skill. Knowledge persuades most when it solves a real problem.',
    ],
    facts: [
      'Herodotus says Thales predicted a solar eclipse that interrupted a battle between the Lydians and the Medes. Modern astronomers date an eclipse to 28 May 585 BC, though how he could have predicted it is still debated.',
      'Plato tells a story that Thales fell into a well while watching the stars, and a Thracian servant girl laughed that he was so eager to know the heavens that he missed what was at his feet.',
      'Aristotle tells the opposite story: using his knowledge of the weather, Thales predicted a large olive harvest, rented all the olive presses cheaply in advance, and made a fortune, to show that philosophers could be rich if they wished.',
      'Herodotus also says he helped the army of King Croesus cross the river Halys by digging a channel that split the stream in two.',
      'He is said to have travelled to Egypt, where Egyptian priests and surveyors taught him geometry.',
      'One tradition makes him the first of the Seven Sages, the group of early Greeks remembered for short, practical sayings.',
    ],
    myths: [
      { myth: 'Thales scientifically predicted the eclipse of 585 BC.', reality: 'No method of predicting a particular eclipse at a particular place existed then. Many scholars think the story is a later embellishment, or that he used a rough Babylonian cycle that could suggest a year but not a location.' },
      { myth: 'He taught that the world is literally made of ordinary water.', reality: 'We only have second-hand reports. The claim is probably about water as the source or underlying nature of things, and Aristotle himself offers it as a reconstruction of Thales’s reasons.' },
    ],
    works: [
      { title: 'No surviving writings', note: 'Later lists credit him with a “Nautical Astronomy” and works on the solstice and equinox, but ancient writers already doubted that he wrote them.' },
      { title: 'Aristotle, Metaphysics, Book I', note: 'The earliest summary of Thales’s view that water is the first principle.' },
      { title: 'Herodotus, Histories', note: 'The eclipse story and the account of the river Halys.' },
      { title: 'Plato, Theaetetus', note: 'The story of the philosopher who fell into a well.' },
      { title: 'Diogenes Laertius, Lives of the Eminent Philosophers, Book I', note: 'A collection of anecdotes and sayings, written in the third century AD.' },
    ],
    legacy: [
      'His successors Anaximander and Anaximenes, also from Miletus, kept asking about the first principle of nature. By the end of the sixth century BC the Milesian school had shown that a rational account of the whole world was possible, and other Greeks began to follow them.',
      'Aristotle’s history of philosophy begins with Thales, and so do most modern ones. When people say science began with an attempt to explain nature on its own terms, they are describing, in a sense, what Thales started.',
    ],
  },
  {
    slug: 'pythagoras',
    order: -570,
    dates: 'c. 570 – c. 495 BC',
    place: 'Samos, then Croton in southern Italy',
    era: 'Ancient',
    tradition: 'Presocratic',
    tagline: 'A teacher who heard music in numbers and taught that the soul travels from life to life.',
    who: [
      'Pythagoras was born on the Aegean island of Samos around 570 BC. Ancient biographies, written centuries later, say he travelled in Egypt and the East, studied with priests and wise men, and left Samos around 530 BC, when the island was ruled by the tyrant Polycrates. He settled in Croton, a Greek colony in southern Italy, where he soon won followers among the city’s leading families.',
      'In Croton he founded a community that was part school, part religious order and part political club. Members shared a disciplined way of life: a simple diet, daily self-examination, music, mathematics and a period of silence for new students. The group grew influential in southern Italian politics until it met violent opposition, and Pythagoras himself is said to have left Croton for Metapontum, where he died around 495 BC.',
      'Pythagoras wrote nothing, and the early Pythagoreans credited the group’s discoveries to the Master himself. Historians therefore separate the historical Pythagoras, about whom we know little, from the Pythagorean tradition, which shaped Greek mathematics, music theory and philosophy, and which Plato admired.',
    ],
    context: [
      'In the sixth century BC the Greek cities of southern Italy and Sicily, known as Magna Graecia, were wealthy and politically restless. Religious movements promising purification and a better afterlife were popular. Pythagoras’s teaching about the soul fits this atmosphere, while his interest in number connects it to the growing study of mathematics and astronomy.',
      'Greek mathematics was only beginning. Egyptians and Babylonians already had practical arithmetic and geometry, including lists of number triples that fit what we call the Pythagorean theorem. The distinctive Greek step was to ask why a result must be true and to look for proofs, and the Pythagorean circles were among the early places where that happened.',
    ],
    ideas: [
      { title: 'Number is the order behind nature', text: 'The Pythagoreans held that the world is ordered by number and proportion. They noticed that the main musical harmonies match simple ratios of string lengths: 2:1 for the octave, 3:2 for the fifth and 4:3 for the fourth. If beauty in sound can be explained by number, they reasoned, perhaps the whole cosmos is ordered the same way.' },
      { title: 'The soul is immortal and reborn', text: 'Pythagoras taught that the soul is immortal and passes from one body into another, including into animals (metempsychosis). A story tells how he stopped a man beating a dog because he recognised the voice of a dead friend in its cry. The belief gave the Pythagoreans a reason to treat other living beings with care.' },
      { title: 'Philosophy as a way of life', text: 'Later writers distinguish two kinds of followers: listeners, who memorised short rules for living, and learners, who studied number and proof. Both lived under discipline, and new members were reportedly silent for years. Philosophy was something you practised every day, not just a subject you discussed.' },
      { title: 'An ordered, beautiful universe', text: 'The word kosmos, meaning both order and ornament, is traditionally credited to Pythagoras or his school. A later Pythagorean, Philolaus, imagined a universe with a central fire around which the Earth and planets moved, one of the first ideas that put the Earth in motion.' },
      { title: 'Mathematics as a path to the divine', text: 'For the Pythagoreans, studying number and harmony was a way of purifying the mind. Plato later took up this idea and made mathematics the training that prepares the soul for philosophy.' },
    ],
    principles: [
      'Look for the pattern behind things.',
      'Harmony, in music, in the soul and in the city, comes from the right proportion.',
      'Examine your day each evening, a practice later writers attribute to the Pythagoreans.',
      'Treat learning as a discipline of character, not just of the mind.',
      'Be careful with living creatures, since all life may be related.',
    ],
    practice: [
      'End each day by asking: what did I do wrong, what did I do well, and what did I leave undone?',
      'Notice proportion in everyday life: in music, in a schedule, in how you divide time between work and rest.',
      'Learn a little mathematics or music for its own sake, and see how it trains attention.',
    ],
    facts: [
      'The theorem that bears his name was known to Babylonian mathematicians more than a thousand years earlier. The Pythagoreans may have been among the first Greeks to prove it, but we cannot be sure.',
      'According to tradition he was the first to call himself a “philosopher”, a lover of wisdom, rather than a wise man. The story is told by later writers and may be a later invention.',
      'Followers were reportedly forbidden to eat beans. Ancient writers disagree about why.',
      'Women were admitted to the community. Theano, traditionally his wife or pupil, is the best known.',
      'A famous legend says he discovered musical ratios by listening to blacksmiths’ hammers. The story cannot be right physically, since hammers of different weights do not produce those ratios; the ratios are more likely to have been found by experimenting with strings.',
      'Later Greeks sometimes treated him almost as a divine figure, telling stories of miracles, such as being in two places at once.',
    ],
    myths: [
      { myth: 'Pythagoras discovered the Pythagorean theorem.', reality: 'The relationship was known in Babylonia and in India before him. Whether Pythagoras or his followers gave the first Greek proof is uncertain.' },
      { myth: 'A Pythagorean named Hippasus was drowned for revealing that some numbers are irrational.', reality: 'The story appears in late sources, with several versions and no reliable evidence. The discovery of irrational numbers did trouble Greek mathematics, but the tale is a legend.' },
      { myth: 'All Pythagoreans were strict vegetarians.', reality: 'The evidence is mixed. Some reports say they avoided meat, others that they ate sacrificial meat except for certain parts.' },
    ],
    works: [
      { title: 'No writings by Pythagoras', note: 'The earliest evidence comes from fragments of Pythagoreans such as Philolaus and Archytas, and from comments by Aristotle.' },
      { title: 'Diogenes Laertius, Lives, Book VIII', note: 'A collection of anecdotes and rules attributed to the Pythagoreans.' },
      { title: 'Porphyry and Iamblichus, Lives of Pythagoras', note: 'Long, admiring biographies written in the third and fourth centuries AD, with much legend.' },
      { title: 'Plato, Phaedo and Timaeus', note: 'Plato’s dialogues show how deeply Pythagorean ideas about the soul and number shaped him.' },
    ],
    legacy: [
      'Plato drew deeply on Pythagorean ideas about the soul and number, and through Plato they spread into Neoplatonism and into early Christian and Islamic thought. In the Renaissance, scientists such as Kepler were still inspired by the Pythagorean hope that the heavens follow mathematical harmony.',
      'The belief that mathematics describes reality, which scientists today take for granted, runs through Western science back to the Pythagoreans. Whatever Pythagoras himself said, the school he founded made number central to the way people think about the world.',
    ],
  },
  {
    slug: 'heraclitus',
    order: -535,
    dates: 'c. 535 – c. 475 BC',
    place: 'Ephesus, Ionia (now western Turkey)',
    era: 'Ancient',
    tradition: 'Presocratic',
    tagline: 'The philosopher of change: the river is never the same, and yet it is still the river.',
    who: [
      'Heraclitus lived in Ephesus, a wealthy Greek city on the coast of Ionia and home to the great temple of Artemis. He came from a leading family and, according to later writers, he gave up a hereditary public role in favour of his brother. Ancient writers nicknamed him “the Obscure” because his short, riddling sayings are hard to read.',
      'He wrote a single book, now lost except for about 130 fragments quoted by other authors. In them he is proud, blunt and often scornful of the people around him, whom he accuses of sleepwalking through life, deaf to the common order that surrounds them. He claims to have “searched himself”, and he says that he learned from no teacher.',
      'The fragments are written as paradoxes and puns, and readers have argued about them for twenty-five centuries. Behind the riddles lies a steady picture of the world: it is always changing, it is held together by the tension between opposites, and a single rational pattern runs through everything.',
    ],
    context: [
      'Ionia was the home of the earliest Greek philosophers, and Heraclitus was reacting to them. Thales, Anaximander and Anaximenes had each named a first principle: water, the boundless and air. Heraclitus chose fire and, more importantly, changed the question: what matters is the pattern of change itself.',
      'Ephesus was under Persian rule in his lifetime, and the Ionian cities rose in revolt in 499 BC, a conflict that led to the Persian Wars. Heraclitus’s sayings about strife, and about how war is shared among all, were written against that background of conflict.',
    ],
    ideas: [
      { title: 'Everything changes', text: 'The world is in constant flux. The famous river saying, in its closest surviving form, says that different waters flow on those who step into the same river. The river remains “the same” only because it keeps changing. Heraclitus saw the same truth in everything: life, the city and the self are patterns that last only through change.' },
      { title: 'The unity of opposites', text: 'Day and night, war and peace, hot and cold, sickness and health depend on each other: we understand one only through the other. He compared the world to a bow or a lyre, held together by tension between opposed pulls. Opposition is not a flaw in the world but the thing that makes it work.' },
      { title: 'The Logos', text: 'Beneath all change lies a rational order he called the Logos, a word meaning speech, reason and account. It is common to everyone, yet most people live as if they each had a private understanding. Heraclitus believed that good thinking means listening to the Logos and following what is shared, not one’s own opinions.' },
      { title: 'Fire as the pattern of change', text: 'He chose fire as the basic stuff, not because everything is flames, but because fire is always active, consuming one thing and giving off another. It stands for the world’s constant exchange: things turn into fire and fire into things, in fixed measures.' },
      { title: 'Character is destiny', text: 'One of his sayings is often translated as “a person’s character is their fate”. It points to a theme in his thought: how we see the world and what we choose are bound up with the kind of person we become.' },
    ],
    principles: [
      'Expect change and do not cling.',
      'Wake up: pay attention to what is shared and real, not only to your own opinions.',
      'Look for the harmony that holds opposites together.',
      'Search yourself: understanding the world begins with understanding who is looking.',
      'Do not put too much trust in the crowd. Thinking takes effort.',
    ],
    practice: [
      'When something in your life changes, ask what is being kept and what is being exchanged, instead of only what is lost.',
      'When you disagree with someone, look for what each of you depends on, and where the opposition holds something together.',
      'Check whether you are following a shared reason or just your habits.',
    ],
    facts: [
      'The phrase “panta rhei” (“everything flows”) is a later summary, not a quotation from his surviving fragments.',
      'Later writers called him “the weeping philosopher”, as a pair to Democritus the laughing one. This is a late literary invention.',
      'Tradition says he placed his book in the temple of Artemis at Ephesus, one of the Seven Wonders of the ancient world.',
      'He said that the way up and the way down are one and the same, a saying that has been read as a statement about the unity of opposites.',
      'Hegel said that there was no sentence of Heraclitus he had not taken into his own Logic.',
      'A story says that late in life he left Ephesus for the mountains and lived on plants, though this is probably legend.',
    ],
    myths: [
      { myth: 'Heraclitus taught that nothing is stable.', reality: 'He taught that stability comes from change: the river or the flame lasts because of constant exchange. A single Logos governs the change, so the world is ordered, not chaotic.' },
      { myth: 'He was a miserable recluse who wept at human folly.', reality: 'The “weeping philosopher” label is a later invention. The fragments show a proud, sharp and sometimes playful writer.' },
    ],
    works: [
      { title: 'On Nature (lost)', note: 'His only book, known from about 130 fragments quoted by later writers.' },
      { title: 'Diogenes Laertius, Lives, Book IX', note: 'Gathers the biographical tradition, including the temple of Artemis story.' },
      { title: 'Plato, Cratylus and Theaetetus', note: 'Plato discusses a Heraclitean view of flux, though he may simplify it.' },
      { title: 'Clement of Alexandria, Plutarch, Hippolytus', note: 'Later authors who preserved many of the fragments by quoting them.' },
    ],
    legacy: [
      'Plato took from Heraclitus the idea that the physical world is always changing, and then looked for something permanent behind it. The Stoics built on the Logos: their universe is guided by divine reason and fire, a clear descendant of his thought.',
      'In modern times Hegel treated Heraclitus as a forerunner of his own ideas about contradiction and change, and Nietzsche admired him as a thinker of becoming. His image of the river has become a lasting symbol of how things persist through change.',
    ],
  },
  {
    slug: 'parmenides',
    order: -515,
    dates: 'c. 515 – c. 450 BC',
    place: 'Elea, southern Italy',
    era: 'Ancient',
    tradition: 'Presocratic',
    tagline: 'He argued that reality is one and unchanging, and that change is an illusion.',
    who: [
      'Parmenides lived in Elea, a Greek colony on the coast of southern Italy, in what is now Campania. Ancient tradition says he was born into a wealthy family, that he was influenced by a Pythagorean teacher, and that he wrote laws for his city. He is said to have visited Athens when he was about 65.',
      'He wrote one work, a poem in verse, in which an unnamed goddess greets a young man who has been carried in a chariot to her house. She promises to teach him everything: both the unshakeable truth and the opinions of mortals, in which there is no true reliability.',
      'The poem has two parts. In “The Way of Truth”, the goddess lays out an argument about what must be true if we are to think or speak at all. In “The Way of Opinion”, she describes the world as it seems to ordinary people, with light and night, and a cosmology of its own. Plato admired him enough to name a dialogue after him and to call him “venerable and awesome”.',
    ],
    context: [
      'Parmenides lived at a time when Greek philosophers were comparing explanations of the world. Heraclitus stressed that all is change, and the Pythagoreans taught that number is the order of things. Parmenides’s poem is a challenge to everyone: it argues, step by step, that the very idea of coming-to-be and change is not coherent.',
      'The poem is in epic verse, like Homer and Hesiod, and in the form of a revelation from a goddess. It uses the traditional language of divine knowledge to deliver something new: an argument that appeals to reason, not to authority.',
    ],
    ideas: [
      { title: '“What is, is; what is not, is not”', text: 'From this plain-sounding starting point Parmenides argued that you cannot think about, or speak about, what does not exist, because there would be nothing to think or speak of. Anything we can think about must therefore be. From this he drew far-reaching conclusions about what can and cannot be.' },
      { title: 'Nothing comes from nothing', text: 'If what is not cannot be, then nothing can come into being from non-being, and nothing can pass away into it. There can be no empty space and no beginning or end. What is, he said, is ungenerated, imperishable, whole, and complete.' },
      { title: 'Change and plurality are illusions', text: 'If real being cannot begin, end, move or divide, then the world of many shifting things that our senses show us is mere appearance. This conclusion is hard to accept, and that was the point: he wanted to show that if you follow the logic, common sense has to be given up.' },
      { title: 'Trust reason over the senses', text: 'The senses deceive us, he said, and only reasoning can reach the truth about what really is. This is the first great defence of rationalism, the view that reason, not observation, is the main path to knowledge.' },
      { title: 'A challenge to everyone after him', text: 'Atomists, Plato and Aristotle each built their systems partly to answer him. They had to explain how change is possible when his argument seems so hard to refute. The atomists, for instance, argued that empty space does exist, so that being is many and can move.' },
    ],
    principles: [
      'Follow an argument where it leads, even when it clashes with common sense.',
      'Do not trust appearances alone.',
      'Be careful with words: ask whether the things you talk about can really be.',
      'Look for what must be true in any case.',
      'Be willing to be surprised by your own conclusions.',
    ],
    practice: [
      'When an argument leads somewhere surprising, check each step slowly before accepting or rejecting the conclusion.',
      'Ask whether a statement you are making means anything: what exactly would it be about?',
      'Remember that how things look is not always how they are, and test your impressions.',
    ],
    facts: [
      'His student Zeno of Elea devised famous paradoxes, such as Achilles and the tortoise, to defend the claim that motion is impossible.',
      'Plato’s dialogue Parmenides imagines a young Socrates meeting the old Parmenides and his student Zeno. Whether the meeting really happened is doubtful.',
      'Only about 150 lines of his poem survive. Most of them were preserved in the sixth century AD by the commentator Simplicius.',
      'Ancient sources say he wrote laws for his home city of Elea, which are said to have remained in force for generations.',
      'Some ancient writers claim he was also the first to describe the Earth as a sphere, though this is uncertain.',
    ],
    myths: [
      { myth: 'Parmenides believed that we should ignore the world around us.', reality: 'The second part of his poem gives a detailed account of the world of appearances, “the way of opinion”. Scholars still debate how it relates to the first part.' },
      { myth: 'Parmenides simply denied that anything moves.', reality: 'He argued that, strictly speaking, being does not change. How that fits with the experience of motion is a puzzle he left to others.' },
    ],
    works: [
      { title: 'On Nature (poem, fragmentary)', note: 'His only work, in two parts: the Way of Truth and the Way of Opinion.' },
      { title: 'Plato, Parmenides', note: 'A dialogue in which Parmenides and Zeno question the theory of Forms.' },
      { title: 'Aristotle, Physics and Metaphysics', note: 'Aristotle repeatedly argues against Parmenides’s conclusions.' },
      { title: 'Simplicius, Commentary on Aristotle’s Physics', note: 'Preserved most of the surviving lines of the poem.' },
    ],
    legacy: [
      'Much of Western metaphysics begins as a series of replies to Parmenides. Plato’s Forms, which do not change, owe something to his idea of what truly is, while Aristotle and the atomists constructed accounts of change to avoid his conclusion.',
      'His insistence that logic can overrule appearances shaped the later rationalists, and modern philosophers still discuss his questions about being, nothing and what we can think about.',
    ],
  },
  {
    slug: 'democritus',
    order: -460,
    dates: 'c. 460 – c. 370 BC',
    place: 'Abdera, Thrace (northern Greece)',
    era: 'Ancient',
    tradition: 'Presocratic',
    tagline: 'The “laughing philosopher” who said the world is made of atoms and empty space.',
    who: [
      'Democritus was born in Abdera, a Greek city on the coast of Thrace, and developed the atomic theory begun by his teacher Leucippus. Ancient writers list dozens of his works on physics, ethics, mathematics, music and literature, but almost all are lost. He was a contemporary of Socrates, though the two do not seem to have met.',
      'According to later writers he travelled widely, to Egypt and perhaps further east, spending his inheritance on his studies and living modestly afterwards. One story says that when he came home he was almost without money, but that his learning won his fellow citizens’ respect.',
      'Later tradition called him the “laughing philosopher” because he found human folly funny. The label appears long after his death, but it fits an ethical theme in his surviving fragments: that cheerfulness and calm, not excitement or wealth, are the aim of life.',
    ],
    context: [
      'Abdera was a prosperous trading city, a colony from Ionia. Democritus’s teacher Leucippus, whom we know little about, is credited with the first atomic theory. Their aim was to answer Parmenides’s argument that change is impossible. If there are many tiny unchanging things moving in empty space, then change can be explained as their rearrangement.',
      'Democritus lived through the Peloponnesian War, which devastated much of the Greek world, yet his work shows a steady interest in how to live calmly in uncertain times.',
    ],
    ideas: [
      { title: 'Atoms and void', text: 'Everything is made of tiny, indivisible, eternal particles moving in empty space. Atoms differ only in shape, arrangement and position, and the variety of the world comes from how they combine, much as the same letters make different words. Without empty space nothing could move, so the void, though nothing, must exist.' },
      { title: 'Qualities are conventions', text: 'He summed it up: by convention there is sweet and bitter, hot and cold, colour; in truth there are only atoms and void. How things taste or feel is how atoms affect us, not a property of the atoms themselves. The senses give us only an appearance, and reason must reach beyond them.' },
      { title: 'A world without a designer', text: 'The cosmos arises from the motion and collision of atoms, with no plan and no divine craftsman. Countless worlds may exist, forming and dissolving. Chance and necessity, not purpose, explain how things come to be.' },
      { title: 'Cheerfulness as the goal', text: 'The aim of life is euthymia, a calm and cheerful state of mind that comes from moderation, not from excess pleasure or wealth. Too much or too little of anything disturbs the soul.' },
      { title: 'Ethics from within', text: 'Many surviving sayings stress that a person should avoid wrong because of self-respect, not fear of others. He valued fairness, moderation and friendship, and warned that anger and envy are damaging.' },
    ],
    principles: [
      'Seek contentment through moderation.',
      'Do not only refrain from wrongdoing, but do not even desire it.',
      'Respect yourself more than the opinion of others.',
      'Do not think that sweetness and bitterness are all there is to the world, and look beneath appearances.',
      'Do not let envy or anger rule you.',
    ],
    practice: [
      'When you are chasing a pleasure, ask whether it will leave you calmer or more restless afterwards.',
      'Behave as if someone you respect were watching, and then notice that it is yourself you are answering to.',
      'Remember that how something feels and what it is can differ, in food, in people, and in news.',
    ],
    facts: [
      'The word “atom” comes from the Greek atomos, “uncuttable”.',
      'Later tradition made him the “laughing philosopher” who found human folly funny, a pair to weeping Heraclitus.',
      'One ancient story says Plato wished to burn all of Democritus’s books. It is an anecdote, not a proven fact.',
      'Ancient lists credit him with roughly seventy titles, including works on geometry, astronomy, music and agriculture.',
      'Most of his surviving fragments are ethical sayings, preserved in later anthologies.',
      'Modern atomic theory is very different from his, but his idea that matter is made of tiny particles is why he is called a forerunner.',
    ],
    myths: [
      { myth: 'Democritus’s atoms were the same as atoms in modern science.', reality: 'His atoms were indivisible solid bits distinguished by shape. Modern atoms are made of smaller parts, and Democritus had no experiments. The similarity is in a bold idea, not in the details.' },
      { myth: 'Democritus was always laughing at people.', reality: 'The “laughing philosopher” is a later tradition. His fragments value moderation and calm and show a serious moralist.' },
    ],
    works: [
      { title: 'Many works, mostly lost', note: 'Diogenes Laertius lists about seventy titles, including “Great World-Order” and “On Cheerfulness”.' },
      { title: 'Fragments of ethical sayings', note: 'Preserved mostly by the later anthologist Stobaeus.' },
      { title: 'Aristotle, On Generation and Corruption; Metaphysics', note: 'Aristotle gives a clear account of atomism, and criticises it.' },
      { title: 'Lucretius, On the Nature of Things', note: 'A Latin poem that explains atomism in Epicurean form.' },
    ],
    legacy: [
      'Epicurus adopted his atomism and adapted it, and through Epicurus and Lucretius the theory survived the ancient world. When the atomic idea was revived in the seventeenth century by thinkers such as Gassendi and Boyle, it brought Democritus back into the story of science.',
      'His claim that sweetness, colour and warmth exist “by convention” anticipated a modern distinction between the properties of things and how we experience them.',
    ],
  },
]
