// GENERATED by scripts/build-profile-index.mjs. Do not edit by hand.
import type { Profile } from './types'

export type ProfileCard = Pick<Profile, 'slug' | 'order' | 'dates' | 'place' | 'era' | 'tradition' | 'tagline'>

/** Everything the gallery needs; small enough to ship with the page. */
export const PROFILE_CARDS: ProfileCard[] = [
 {
  "slug": "thales",
  "order": -624,
  "dates": "c. 624 – c. 546 BC",
  "place": "Miletus, Ionia (now western Turkey)",
  "era": "Ancient",
  "tradition": "Presocratic",
  "tagline": "The first thinker on record to ask what the world is made of, and to answer without turning to the gods."
 },
 {
  "slug": "aesop",
  "order": -620,
  "dates": "c. 620 – c. 564 BC (traditional)",
  "place": "Greece and Asia Minor (tradition names Samos and Delphi)",
  "era": "Ancient",
  "tradition": "Fable tradition",
  "tagline": "A half-legendary storyteller whose animal tales have taught practical wisdom for more than two thousand years."
 },
 {
  "slug": "laozi",
  "order": -600,
  "dates": "traditionally 6th century BC",
  "place": "Chu and the Zhou court, China (traditional)",
  "era": "Ancient",
  "tradition": "Taoism",
  "tagline": "The “Old Master” credited with the Tao Te Ching, a short book on the strength of softness and the wisdom of not forcing things."
 },
 {
  "slug": "pythagoras",
  "order": -570,
  "dates": "c. 570 – c. 495 BC",
  "place": "Samos, then Croton in southern Italy",
  "era": "Ancient",
  "tradition": "Presocratic",
  "tagline": "A teacher who heard music in numbers and taught that the soul travels from life to life."
 },
 {
  "slug": "the-buddha",
  "order": -563,
  "dates": "traditionally c. 563 – 483 BC; many scholars place his death c. 400 BC",
  "place": "Lumbini (now Nepal) and the Ganges plain of northern India",
  "era": "Ancient",
  "tradition": "Buddhism",
  "tagline": "A teacher who left a life of comfort to understand suffering, and who taught a path between indulgence and self-denial."
 },
 {
  "slug": "confucius",
  "order": -551,
  "dates": "551 – 479 BC",
  "place": "Lu (now Shandong, China)",
  "era": "Ancient",
  "tradition": "Confucianism",
  "tagline": "A teacher who made learning, humane character and good example the foundation of a decent society."
 },
 {
  "slug": "sun-tzu",
  "order": -544,
  "dates": "traditionally c. 544 – c. 496 BC; the book is probably later",
  "place": "Qi and Wu (traditional); the historical details are uncertain",
  "era": "Ancient",
  "tradition": "Chinese military thought",
  "tagline": "The name on the most famous book of strategy ever written, though we know very little about the man."
 },
 {
  "slug": "heraclitus",
  "order": -535,
  "dates": "c. 535 – c. 475 BC",
  "place": "Ephesus, Ionia (now western Turkey)",
  "era": "Ancient",
  "tradition": "Presocratic",
  "tagline": "The philosopher of change: the river is never the same, and yet it is still the river."
 },
 {
  "slug": "parmenides",
  "order": -515,
  "dates": "c. 515 – c. 450 BC",
  "place": "Elea, southern Italy",
  "era": "Ancient",
  "tradition": "Presocratic",
  "tagline": "He argued that reality is one and unchanging, and that change is an illusion."
 },
 {
  "slug": "socrates",
  "order": -470,
  "dates": "c. 470 – 399 BC",
  "place": "Athens",
  "era": "Ancient",
  "tradition": "Classical Greek",
  "tagline": "He wrote nothing, questioned everyone, and died rather than give up a life of inquiry."
 },
 {
  "slug": "mozi",
  "order": -470,
  "dates": "c. 470 – c. 391 BC (approximate)",
  "place": "Probably Lu (now Shandong), active in Song, Chu and other states, China",
  "era": "Ancient",
  "tradition": "Mohism",
  "tagline": "A craftsman-philosopher who argued that we should care for everyone alike and that war is organised crime."
 },
 {
  "slug": "hippocrates",
  "order": -460,
  "dates": "c. 460 – c. 370 BC",
  "place": "Cos, then Thessaly (Greece)",
  "era": "Ancient",
  "tradition": "Greek medicine",
  "tagline": "The Greek physician who became the symbol of medicine as careful observation, honest judgement and care for the patient."
 },
 {
  "slug": "democritus",
  "order": -460,
  "dates": "c. 460 – c. 370 BC",
  "place": "Abdera, Thrace (northern Greece)",
  "era": "Ancient",
  "tradition": "Presocratic",
  "tagline": "The “laughing philosopher” who said the world is made of atoms and empty space."
 },
 {
  "slug": "xenophon",
  "order": -430,
  "dates": "c. 430 – c. 354 BC",
  "place": "Athens, Persia, Scillus and Corinth",
  "era": "Ancient",
  "tradition": "Socratic writing",
  "tagline": "A soldier, exile and gifted prose writer who gave us a down-to-earth portrait of Socrates and the story of the Ten Thousand."
 },
 {
  "slug": "plato",
  "order": -428,
  "dates": "c. 428 – c. 348 BC",
  "place": "Athens",
  "era": "Ancient",
  "tradition": "Classical Greek",
  "tagline": "Student of Socrates, founder of the Academy, and author of the dialogues that shaped Western thought."
 },
 {
  "slug": "diogenes-of-sinope",
  "order": -412,
  "dates": "c. 412 – c. 323 BC",
  "place": "Sinope on the Black Sea, then Athens and Corinth",
  "era": "Ancient",
  "tradition": "Cynicism",
  "tagline": "The philosopher who lived in a jar and told a king to stand out of his sunlight."
 },
 {
  "slug": "aristotle",
  "order": -384,
  "dates": "384 – 322 BC",
  "place": "Stagira, then Athens",
  "era": "Ancient",
  "tradition": "Classical Greek",
  "tagline": "The great organiser of knowledge: logic, ethics, biology, politics and more."
 },
 {
  "slug": "mencius",
  "order": -372,
  "dates": "traditionally c. 372 – c. 289 BC (other dates are given)",
  "place": "Zou (now Shandong, China); travelled to Liang, Qi and other states",
  "era": "Ancient",
  "tradition": "Confucianism",
  "tagline": "The Confucian who argued that human nature is good and that a ruler who betrays the people loses the right to rule."
 },
 {
  "slug": "zhuang-zhou",
  "order": -369,
  "dates": "c. 369 – c. 286 BC (traditional)",
  "place": "State of Song, central China",
  "era": "Ancient",
  "tradition": "Taoism",
  "tagline": "A humorous, imaginative thinker who questioned fixed categories and taught people to move through life with ease."
 },
 {
  "slug": "chanakya",
  "order": -350,
  "dates": "traditionally 4th – 3rd century BC (dates uncertain)",
  "place": "Taxila and Pataliputra (Magadha), India, according to later tradition",
  "era": "Ancient",
  "tradition": "Indian political thought",
  "tagline": "The legendary minister to the first Maurya emperor, whose name is attached to the Arthashastra, India’s great treatise on statecraft."
 },
 {
  "slug": "epicurus",
  "order": -341,
  "dates": "341 – 270 BC",
  "place": "Samos, then Athens",
  "era": "Ancient",
  "tradition": "Epicureanism",
  "tagline": "He taught that a good life means simple pleasures, good friends and freedom from fear."
 },
 {
  "slug": "zeno-of-citium",
  "order": -334,
  "dates": "c. 334 – c. 262 BC",
  "place": "Citium, Cyprus, then Athens",
  "era": "Ancient",
  "tradition": "Stoicism",
  "tagline": "The founder of Stoicism, who taught in a painted colonnade and made virtue the only true good."
 },
 {
  "slug": "xunzi",
  "order": -310,
  "dates": "c. 310 – c. 235 BC",
  "place": "States of Zhao, Qi and Chu (China)",
  "era": "Ancient",
  "tradition": "Confucianism",
  "tagline": "The Confucian who argued that people are born self-seeking and become good only through learning and ritual."
 },
 {
  "slug": "archimedes",
  "order": -287,
  "dates": "c. 287 – c. 212 BC",
  "place": "Syracuse, Sicily",
  "era": "Ancient",
  "tradition": "Greek mathematics",
  "tagline": "The mathematician of Syracuse who proved how levers and floating bodies behave, and showed that nature can be reasoned about with geometry."
 },
 {
  "slug": "han-fei",
  "order": -280,
  "dates": "c. 280 – 233 BC",
  "place": "State of Han, then the state of Qin (China)",
  "era": "Ancient",
  "tradition": "Legalism",
  "tagline": "The Warring States thinker who argued that a state should be run by clear laws and checks on its officials, not by the goodness of rulers."
 },
 {
  "slug": "patanjali",
  "order": -200,
  "dates": "Uncertain; the Yoga Sutras date from c. 2nd century BC to c. 4th century AD",
  "place": "India (exact place unknown)",
  "era": "Ancient",
  "tradition": "Yoga philosophy",
  "tagline": "The name attached to the Yoga Sutras, a short and exact manual on quieting the mind and ending suffering."
 },
 {
  "slug": "cicero",
  "order": -106,
  "dates": "106 – 43 BC",
  "place": "Arpinum, then Rome",
  "era": "Ancient",
  "tradition": "Roman Republic",
  "tagline": "Rome’s greatest orator, who in his last years turned Greek philosophy into Latin and defended the Republic with his pen."
 },
 {
  "slug": "lucretius",
  "order": -99,
  "dates": "c. 99 – c. 55 BC",
  "place": "Probably Rome",
  "era": "Ancient",
  "tradition": "Epicureanism",
  "tagline": "A Roman poet who used verse to explain a universe of atoms and to argue that death is nothing to fear."
 },
 {
  "slug": "horace",
  "order": -65,
  "dates": "65 – 8 BC",
  "place": "Venusia, Rome and a farm in the Sabine hills (Italy)",
  "era": "Ancient",
  "tradition": "Roman poetry",
  "tagline": "The Roman poet who turned a plain philosophy of moderation, friendship and living in the present into some of the most quoted lines in Latin."
 },
 {
  "slug": "philo-of-alexandria",
  "order": -20,
  "dates": "c. 20 BC – c. AD 50",
  "place": "Alexandria, Egypt",
  "era": "Ancient",
  "tradition": "Hellenistic Judaism",
  "tagline": "A Jewish thinker in Greek-speaking Alexandria who read the Torah through Plato and made scripture speak to philosophy."
 },
 {
  "slug": "seneca",
  "order": -4,
  "dates": "c. 4 BC – 65 AD",
  "place": "Corduba (Córdoba, Spain), then Rome",
  "era": "Ancient",
  "tradition": "Stoicism",
  "tagline": "Playwright, statesman and adviser to an emperor, who wrote some of the most readable advice ever given on time, anger and facing misfortune."
 },
 {
  "slug": "plutarch",
  "order": 46,
  "dates": "c. AD 46 – after AD 119",
  "place": "Chaeronea in Boeotia, and Delphi (Greece)",
  "era": "Ancient",
  "tradition": "Middle Platonism",
  "tagline": "A Greek priest and biographer who set great lives side by side to ask what makes a person good."
 },
 {
  "slug": "epictetus",
  "order": 50,
  "dates": "c. 50 – c. 135 AD",
  "place": "Hierapolis in Phrygia, Rome, then Nicopolis in Greece",
  "era": "Ancient",
  "tradition": "Stoicism",
  "tagline": "A former slave who taught that we are free as soon as we learn to govern our own judgments."
 },
 {
  "slug": "marcus-aurelius",
  "order": 121,
  "dates": "121 – 180 AD",
  "place": "Rome",
  "era": "Ancient",
  "tradition": "Stoicism",
  "tagline": "The Roman emperor who spent his campaigns writing private notes on how to be a good person."
 },
 {
  "slug": "nagarjuna",
  "order": 150,
  "dates": "c. 150 – c. 250 AD (uncertain)",
  "place": "Southern India",
  "era": "Ancient",
  "tradition": "Madhyamaka Buddhism",
  "tagline": "The Buddhist philosopher who argued that nothing has a fixed nature of its own, and that this is exactly why things can exist at all."
 },
 {
  "slug": "origen",
  "order": 185,
  "dates": "c. 185 – c. 253 AD",
  "place": "Alexandria, Egypt, and Caesarea in Palestine",
  "era": "Ancient",
  "tradition": "Christian Platonism",
  "tagline": "A brilliant and controversial scholar who tried to read the Bible with the full tools of ancient learning, and who was condemned after his death."
 },
 {
  "slug": "plotinus",
  "order": 204,
  "dates": "c. 204/5 – 270 AD",
  "place": "Roman Egypt (probably), Alexandria, then Rome",
  "era": "Ancient",
  "tradition": "Neoplatonism",
  "tagline": "The philosopher-mystic who described all of reality as flowing from a single source, the One, and the soul’s way back to it."
 },
 {
  "slug": "augustine-of-hippo",
  "order": 354,
  "dates": "AD 354 – 430",
  "place": "Thagaste (now Souk Ahras, Algeria), Carthage, Milan and Hippo Regius",
  "era": "Ancient",
  "tradition": "Christian philosophy",
  "tagline": "A North African teacher of rhetoric who became a bishop and wrote the first great Western autobiography."
 },
 {
  "slug": "boethius",
  "order": 480,
  "dates": "c. AD 480 – c. AD 524",
  "place": "Rome and Pavia (Italy)",
  "era": "Ancient",
  "tradition": "Late Roman philosophy",
  "tagline": "A Roman statesman who passed Greek logic to the Middle Ages and wrote a prison book on happiness and fate."
 },
 {
  "slug": "adi-shankara",
  "order": 700,
  "dates": "traditionally 788 – 820; modern scholars c. 700 – 750",
  "place": "Kalady in Kerala, and travels across India",
  "era": "Medieval",
  "tradition": "Advaita Vedanta",
  "tagline": "The Indian philosopher and monk who taught that the self and the ultimate reality are one."
 },
 {
  "slug": "murasaki-shikibu",
  "order": 973,
  "dates": "c. 973 – c. 1014 or later",
  "place": "Heian-kyo (Kyoto), Japan",
  "era": "Medieval",
  "tradition": "Heian literature",
  "tagline": "A lady-in-waiting at the Japanese imperial court who wrote The Tale of Genji, one of the world’s great works of fiction."
 },
 {
  "slug": "omar-khayyam",
  "order": 1048,
  "dates": "1048 – 1131",
  "place": "Nishapur, Samarkand and Isfahan (Persia)",
  "era": "Medieval",
  "tradition": "Persian poetry and science",
  "tagline": "A mathematician and astronomer of medieval Persia, remembered in the West as the poet of the Rubaiyat."
 },
 {
  "slug": "al-ghazali",
  "order": 1058,
  "dates": "c. 1058 – 1111",
  "place": "Tus (now northeastern Iran); taught in Baghdad and Nishapur",
  "era": "Medieval",
  "tradition": "Islamic philosophy and theology",
  "tagline": "A celebrated professor who walked away from fame, doubted everything, and found certainty in the inner life."
 },
 {
  "slug": "peter-abelard",
  "order": 1079,
  "dates": "1079 – 1142",
  "place": "Le Pallet in Brittany; taught in Paris; died near Chalon-sur-Saone, France",
  "era": "Medieval",
  "tradition": "Scholasticism",
  "tagline": "A brilliant logician who taught Paris to ask questions, and whose life ended in scandal, love letters and condemnation."
 },
 {
  "slug": "bernard-of-clairvaux",
  "order": 1090,
  "dates": "1090 – 1153",
  "place": "Clairvaux, Champagne (France)",
  "era": "Medieval",
  "tradition": "Cistercian mysticism",
  "tagline": "A monk who made love the centre of the spiritual life, and who was also one of the most powerful public voices of twelfth-century Europe."
 },
 {
  "slug": "hildegard-of-bingen",
  "order": 1098,
  "dates": "1098 – 1179",
  "place": "Disibodenberg and Bingen, Rhineland (Germany)",
  "era": "Medieval",
  "tradition": "Christian mysticism",
  "tagline": "A German abbess who recorded her visions, wrote music, studied nature and healing, and spoke to popes and emperors."
 },
 {
  "slug": "averroes",
  "order": 1126,
  "dates": "1126 – 1198",
  "place": "Cordoba, al-Andalus (now Spain); died in Marrakesh",
  "era": "Medieval",
  "tradition": "Islamic Aristotelianism",
  "tagline": "The judge and physician whose commentaries made him “the Commentator” on Aristotle for Muslims, Jews and Christians."
 },
 {
  "slug": "moshe-ben-maimon",
  "order": 1138,
  "dates": "1138 (or 1135) – 1204",
  "place": "Córdoba, Fez and Fustat (Cairo)",
  "era": "Medieval",
  "tradition": "Jewish philosophy",
  "tagline": "A physician and judge who codified Jewish law and argued that faith and reason belong together."
 },
 {
  "slug": "attar-of-nishapur",
  "order": 1145,
  "dates": "c. 1145 – c. 1221",
  "place": "Nishapur, Khorasan (now northeastern Iran)",
  "era": "Medieval",
  "tradition": "Sufism",
  "tagline": "A Persian apothecary-poet who told the story of the soul as a flight of birds in search of their king."
 },
 {
  "slug": "shota-rustaveli",
  "order": 1172,
  "dates": "Late 12th – early 13th century (exact dates unknown)",
  "place": "Georgia, at the court of Queen Tamar",
  "era": "Medieval",
  "tradition": "Georgian literature and thought",
  "tagline": "The poet of Georgia’s golden age, who made friendship, generosity and just rule the heart of a national epic."
 },
 {
  "slug": "rumi",
  "order": 1207,
  "dates": "1207 – 1273",
  "place": "Born in Balkh or Wakhsh (Central Asia); lived in Konya (now Turkey)",
  "era": "Medieval",
  "tradition": "Sufism",
  "tagline": "A scholar who became a poet of longing, and whose verses turn love for the divine into music."
 },
 {
  "slug": "bonaventure",
  "order": 1217,
  "dates": "c. 1217/21 – 1274",
  "place": "Bagnoregio (Italy), Paris and Lyon",
  "era": "Medieval",
  "tradition": "Franciscan mysticism",
  "tagline": "A Franciscan master and minister general who taught that the whole created world is a ladder of signs leading the mind to God."
 },
 {
  "slug": "roger-bacon",
  "order": 1220,
  "dates": "c. 1219/20 – c. 1292",
  "place": "Oxford and Paris",
  "era": "Medieval",
  "tradition": "Scholastic natural philosophy",
  "tagline": "A Franciscan friar who argued that knowledge of nature needs experience, mathematics and languages, and who became a legend."
 },
 {
  "slug": "thomas-aquinas",
  "order": 1225,
  "dates": "c. 1225 – 1274",
  "place": "Roccasecca, southern Italy; taught in Paris, Cologne and Italy",
  "era": "Medieval",
  "tradition": "Scholasticism",
  "tagline": "The Dominican friar who built a great system joining faith and reason, drawing on Aristotle."
 },
 {
  "slug": "meister-eckhart",
  "order": 1260,
  "dates": "c. 1260 – c. 1328",
  "place": "Thuringia (Germany); taught in Paris, Strasbourg and Cologne",
  "era": "Medieval",
  "tradition": "Christian mysticism",
  "tagline": "A Dominican preacher who spoke of the soul as a place where God is born, and was tried for it."
 },
 {
  "slug": "dante-alighieri",
  "order": 1265,
  "dates": "c. 1265 – 1321",
  "place": "Florence, then exile in northern Italy; died in Ravenna",
  "era": "Medieval",
  "tradition": "Medieval Christian thought",
  "tagline": "The poet who walked through hell, purgatory and paradise, and gave a vernacular language the weight of Latin."
 },
 {
  "slug": "petrarch",
  "order": 1304,
  "dates": "1304 – 1374",
  "place": "Born in Arezzo; lived in Avignon, Vaucluse, Italian cities and Arquà",
  "era": "Medieval",
  "tradition": "Renaissance humanism",
  "tagline": "The scholar-poet who went looking for the ancient world, and for himself, in old books."
 },
 {
  "slug": "geoffrey-chaucer",
  "order": 1343,
  "dates": "c. 1343 – 1400",
  "place": "London, England",
  "era": "Medieval",
  "tradition": "Medieval English literature",
  "tagline": "A court official who made the English of his own day into a language fit for great poetry, and filled it with the voices of ordinary people."
 },
 {
  "slug": "thomas-a-kempis",
  "order": 1380,
  "dates": "c. 1380 – 1471",
  "place": "Kempen (Germany), Deventer and Zwolle (Netherlands)",
  "era": "Medieval",
  "tradition": "Devotio Moderna",
  "tagline": "A quiet canon and copyist whose small book on following Christ became one of the most widely read works of Christian devotion."
 },
 {
  "slug": "kabir",
  "order": 1398,
  "dates": "Traditionally c. 1398 – 1518; modern scholars propose earlier or shorter dates",
  "place": "Varanasi (Banaras), northern India",
  "era": "Medieval",
  "tradition": "Bhakti and Sant tradition",
  "tagline": "A weaver-poet who mocked empty ritual and sang of a God beyond Hindu and Muslim labels."
 },
 {
  "slug": "nicholas-of-cusa",
  "order": 1401,
  "dates": "1401 – 1464",
  "place": "Kues on the Moselle (Germany), Basel, Brixen and Rome",
  "era": "Early Modern",
  "tradition": "Renaissance Neoplatonism",
  "tagline": "A cardinal who argued that the greatest knowledge is to know how much we do not know, and who imagined a universe with no centre."
 },
 {
  "slug": "jami",
  "order": 1414,
  "dates": "1414 – 1492",
  "place": "Herat, Khurasan (now western Afghanistan)",
  "era": "Medieval",
  "tradition": "Persian Sufism",
  "tagline": "A Sufi master, scholar and poet of Herat whose seven long poems made him one of the last great voices of classical Persian literature."
 },
 {
  "slug": "giovanni-pico-della-mirandola",
  "order": 1463,
  "dates": "1463 – 1494",
  "place": "Mirandola, Bologna, Ferrara, Padua, Paris and Florence",
  "era": "Early Modern",
  "tradition": "Renaissance humanism",
  "tagline": "A brilliant young nobleman who tried to reconcile every philosophy and religion he could read, and who gave Renaissance thought its most quoted speech about human freedom."
 },
 {
  "slug": "erasmus",
  "order": 1466,
  "dates": "c. 1466 – 1536",
  "place": "Rotterdam or Gouda, then Paris, England, Basel and Freiburg",
  "era": "Early Modern",
  "tradition": "Christian humanism",
  "tagline": "The most famous scholar in Europe, who tried to reform the Church with learning, good humour and sharp satire, and refused to join either side of the Reformation."
 },
 {
  "slug": "niccolo-machiavelli",
  "order": 1469,
  "dates": "1469 – 1527",
  "place": "Florence, Italy",
  "era": "Early Modern",
  "tradition": "Renaissance political thought",
  "tagline": "A Florentine diplomat whose cold-eyed book on power made his name a byword for cunning, though his deeper loyalty was to free republics."
 },
 {
  "slug": "nicolaus-copernicus",
  "order": 1473,
  "dates": "1473 – 1543",
  "place": "Toruń, Kraków, Bologna, Padua and Frombork, Royal Prussia (now Poland)",
  "era": "Early Modern",
  "tradition": "Astronomy",
  "tagline": "A cathedral canon who worked out, in mathematical detail, a universe in which the Earth moves round the Sun."
 },
 {
  "slug": "thomas-more",
  "order": 1478,
  "dates": "1478 – 1535",
  "place": "London, England",
  "era": "Early Modern",
  "tradition": "Humanism",
  "tagline": "A lawyer, scholar and statesman who imagined an island called Nowhere, and who died on the scaffold for refusing to accept the king as head of the Church."
 },
 {
  "slug": "martin-luther",
  "order": 1483,
  "dates": "1483 – 1546",
  "place": "Eisleben, Erfurt and Wittenberg, Saxony (now Germany)",
  "era": "Early Modern",
  "tradition": "Protestant Reformation",
  "tagline": "A German monk and professor whose protest against the sale of indulgences split Western Christianity, and whose legacy includes both a vernacular Bible and writings against Jews."
 },
 {
  "slug": "teresa-of-avila",
  "order": 1515,
  "dates": "1515 – 1582",
  "place": "Ávila and other cities of Castile, Spain",
  "era": "Early Modern",
  "tradition": "Carmelite mysticism",
  "tagline": "A Spanish nun who reformed her order, described the inner life of prayer with astonishing frankness, and became the first woman named a Doctor of the Church."
 },
 {
  "slug": "etienne-de-la-boetie",
  "order": 1530,
  "dates": "1530 – 1563",
  "place": "Sarlat and Bordeaux, France",
  "era": "Early Modern",
  "tradition": "Political thought",
  "tagline": "A young French magistrate who asked why whole peoples obey a single tyrant, and who became immortal as Montaigne’s closest friend."
 },
 {
  "slug": "michel-de-montaigne",
  "order": 1533,
  "dates": "1533 – 1592",
  "place": "Château de Montaigne, near Bordeaux, France",
  "era": "Early Modern",
  "tradition": "Renaissance skepticism",
  "tagline": "The inventor of the personal essay, who turned the study of one ordinary mind, his own, into a way of understanding everyone."
 },
 {
  "slug": "giordano-bruno",
  "order": 1548,
  "dates": "1548 – 1600",
  "place": "Nola near Naples, then across Europe, and Rome",
  "era": "Early Modern",
  "tradition": "Renaissance philosophy",
  "tagline": "A restless Dominican friar who imagined an infinite universe of countless worlds, and was burned in Rome after an eight-year trial."
 },
 {
  "slug": "francis-bacon",
  "order": 1561,
  "dates": "1561 – 1626",
  "place": "London, England",
  "era": "Early Modern",
  "tradition": "Empiricism",
  "tagline": "A lawyer-statesman who argued that nature should be studied by patient experiment, and who fell from the highest legal office in England in a corruption scandal."
 },
 {
  "slug": "galileo-galilei",
  "order": 1564,
  "dates": "1564 – 1642",
  "place": "Pisa, Padua and Florence, Italy",
  "era": "Early Modern",
  "tradition": "Scientific revolution",
  "tagline": "He pointed a telescope at the sky, argued that nature is written in mathematics, and ended his life under house arrest for defending a moving Earth."
 },
 {
  "slug": "johannes-kepler",
  "order": 1571,
  "dates": "1571 – 1630",
  "place": "Graz, Prague and Linz (Habsburg lands)",
  "era": "Early Modern",
  "tradition": "Scientific revolution",
  "tagline": "A devout Lutheran astronomer who found that the planets move in ellipses, and who believed that the heavens reflect a divine harmony."
 },
 {
  "slug": "miyamoto-musashi",
  "order": 1584,
  "dates": "c. 1584 – 1645",
  "place": "Harima or Mimasaka province, then Kumamoto, Japan",
  "era": "Early Modern",
  "tradition": "Japanese martial philosophy",
  "tagline": "A swordsman who claimed never to have lost a duel and who tried to turn the study of the sword into a study of the whole of life."
 },
 {
  "slug": "thomas-hobbes",
  "order": 1588,
  "dates": "1588 – 1679",
  "place": "Malmesbury, Wiltshire, England; later Paris and Chatsworth",
  "era": "Early Modern",
  "tradition": "Social contract theory",
  "tagline": "He argued that without a power to keep order, life would be a war of everyone against everyone, and built a political theory on that fear."
 },
 {
  "slug": "rene-descartes",
  "order": 1596,
  "dates": "1596 – 1650",
  "place": "La Haye en Touraine, France; the Dutch Republic; Stockholm",
  "era": "Early Modern",
  "tradition": "Rationalism",
  "tagline": "He doubted everything he could, found one thing he could not doubt, and tried to rebuild knowledge on it."
 },
 {
  "slug": "baltasar-gracian",
  "order": 1601,
  "dates": "1601 – 1658",
  "place": "Aragon, Spain",
  "era": "Early Modern",
  "tradition": "Spanish Baroque",
  "tagline": "A Jesuit priest who wrote the sharpest handbook of worldly prudence in Europe, and was punished by his own order for it."
 },
 {
  "slug": "blaise-pascal",
  "order": 1623,
  "dates": "1623 – 1662",
  "place": "Clermont (now Clermont-Ferrand), then Rouen and Paris, France",
  "era": "Early Modern",
  "tradition": "Christian thought and mathematics",
  "tagline": "A mathematical prodigy who turned to faith and wrote about human greatness and misery."
 },
 {
  "slug": "benedictus-de-spinoza",
  "order": 1632,
  "dates": "1632 – 1677",
  "place": "Amsterdam, then Rijnsburg, Voorburg and The Hague (Dutch Republic)",
  "era": "Early Modern",
  "tradition": "Rationalism",
  "tagline": "A lens grinder expelled by his own community who argued that God and Nature are one."
 },
 {
  "slug": "john-locke",
  "order": 1632,
  "dates": "1632 – 1704",
  "place": "Wrington, Somerset, England; Oxford, London, the Netherlands, and Oates, Essex",
  "era": "Early Modern",
  "tradition": "Empiricism and liberalism",
  "tagline": "He said that the mind starts as a blank page and that governments exist to protect our natural rights."
 },
 {
  "slug": "isaac-newton",
  "order": 1643,
  "dates": "1643 – 1727",
  "place": "Cambridge and London, England",
  "era": "Early Modern",
  "tradition": "Natural philosophy",
  "tagline": "The man who showed that one set of laws governs the fall of an apple and the orbit of the Moon, and who spent as much time on alchemy and theology as on physics."
 },
 {
  "slug": "gottfried-wilhelm-leibniz",
  "order": 1646,
  "dates": "1646 – 1716",
  "place": "Leipzig, then Mainz, Paris and Hanover (Germany)",
  "era": "Early Modern",
  "tradition": "Rationalism",
  "tagline": "A universal genius who co-invented calculus and argued that this is the best of all possible worlds."
 },
 {
  "slug": "sor-juana-ines-de-la-cruz",
  "order": 1648,
  "dates": "1648 or 1651 – 1695",
  "place": "San Miguel Nepantla and Mexico City, New Spain (now Mexico)",
  "era": "Early Modern",
  "tradition": "Baroque literature and thought",
  "tagline": "A nun who built one of the great libraries of her age, wrote the finest poetry of the Spanish-speaking Baroque, and defended a woman’s right to study."
 },
 {
  "slug": "giambattista-vico",
  "order": 1668,
  "dates": "1668 – 1744",
  "place": "Naples, Kingdom of Naples (now Italy)",
  "era": "Early Modern",
  "tradition": "Philosophy of history",
  "tagline": "An overlooked Neapolitan professor who argued that we can truly know only what humans have made, and that history is the greatest human work of all."
 },
 {
  "slug": "george-berkeley",
  "order": 1685,
  "dates": "1685 – 1753",
  "place": "Dublin, Rhode Island and Cloyne, Ireland",
  "era": "Early Modern",
  "tradition": "Idealism",
  "tagline": "An Irish bishop who argued that the world is made of minds and their ideas, and that this is just common sense properly understood."
 },
 {
  "slug": "montesquieu",
  "order": 1689,
  "dates": "1689 – 1755",
  "place": "La Brède near Bordeaux, and Paris, France",
  "era": "Enlightenment",
  "tradition": "French Enlightenment",
  "tagline": "A magistrate and satirist who asked why laws differ from country to country, and argued that power must be made to check power."
 },
 {
  "slug": "voltaire",
  "order": 1694,
  "dates": "1694 – 1778",
  "place": "Paris, then England, Prussia, Switzerland and Ferney on the French border",
  "era": "Enlightenment",
  "tradition": "French Enlightenment",
  "tagline": "The sharpest pen of the age, who used wit, history and drama to fight intolerance and fanaticism."
 },
 {
  "slug": "david-hume",
  "order": 1711,
  "dates": "1711 – 1776",
  "place": "Edinburgh, Scotland",
  "era": "Enlightenment",
  "tradition": "Scottish Enlightenment",
  "tagline": "The Scottish sceptic who asked how much we can really know from experience, and whose questions Kant said woke him from his slumber."
 },
 {
  "slug": "jean-jacques-rousseau",
  "order": 1712,
  "dates": "1712 – 1778",
  "place": "Geneva, then France and Switzerland",
  "era": "Enlightenment",
  "tradition": "Enlightenment political thought",
  "tagline": "A self-taught outsider who argued that people are born free and good, and that society chains and corrupts them."
 },
 {
  "slug": "denis-diderot",
  "order": 1713,
  "dates": "1713 – 1784",
  "place": "Langres in Champagne, and Paris, France",
  "era": "Enlightenment",
  "tradition": "French Enlightenment",
  "tagline": "The editor of the Encyclopédie, who gathered the knowledge of his age into one great work and dared to follow his materialism where it led."
 },
 {
  "slug": "adam-smith",
  "order": 1723,
  "dates": "1723 – 1790",
  "place": "Kirkcaldy, Glasgow and Edinburgh, Scotland",
  "era": "Enlightenment",
  "tradition": "Scottish Enlightenment",
  "tagline": "A moral philosopher who explained how trade, specialisation and self-interest can build a nation’s wealth, and who never thought that was the whole story."
 },
 {
  "slug": "immanuel-kant",
  "order": 1724,
  "dates": "1724 – 1804",
  "place": "Königsberg, Prussia (now Kaliningrad, Russia)",
  "era": "Enlightenment",
  "tradition": "German idealism",
  "tagline": "The philosopher who argued that the mind shapes experience, and that morality rests on duty and respect for persons."
 },
 {
  "slug": "edmund-burke",
  "order": 1729,
  "dates": "1729 – 1797",
  "place": "Dublin, Ireland, and England",
  "era": "Enlightenment",
  "tradition": "Conservatism",
  "tagline": "A statesman who defended inherited institutions as the stored wisdom of generations, and warned that revolution can destroy what it cannot rebuild."
 },
 {
  "slug": "gotthold-ephraim-lessing",
  "order": 1729,
  "dates": "1729 – 1781",
  "place": "Leipzig, Berlin, Hamburg and Wolfenbüttel, Germany",
  "era": "Enlightenment",
  "tradition": "German Enlightenment",
  "tagline": "A playwright, critic and theologian who made tolerance a matter for the stage and treated the search for truth as worth more than its possession."
 },
 {
  "slug": "thomas-paine",
  "order": 1737,
  "dates": "1737 – 1809",
  "place": "Thetford, England; Philadelphia, Paris and New York",
  "era": "Enlightenment",
  "tradition": "Radical Enlightenment",
  "tagline": "An English corset-maker turned pamphleteer whose plain words helped drive the American and French revolutions and gave democracy a popular voice."
 },
 {
  "slug": "cesare-beccaria",
  "order": 1738,
  "dates": "1738 – 1794",
  "place": "Milan, Duchy of Milan (Austrian Lombardy, now Italy)",
  "era": "Enlightenment",
  "tradition": "Penal reform",
  "tagline": "A young Milanese nobleman whose short book argued that punishment should be certain, moderate and humane, and helped to change how Europe thought about crime."
 },
 {
  "slug": "georg-christoph-lichtenberg",
  "order": 1742,
  "dates": "1742 – 1799",
  "place": "Göttingen, Electorate of Hanover (now Germany)",
  "era": "Enlightenment",
  "tradition": "Aphorism",
  "tagline": "A hunchbacked Göttingen physicist whose private notebooks of one-line thoughts made him one of Europe’s sharpest wits."
 },
 {
  "slug": "thomas-jefferson",
  "order": 1743,
  "dates": "1743 – 1826",
  "place": "Monticello, Virginia, United States",
  "era": "Enlightenment",
  "tradition": "American Enlightenment",
  "tagline": "Author of the Declaration of Independence, who wrote that all men are created equal and who held hundreds of people in slavery."
 },
 {
  "slug": "johann-gottfried-herder",
  "order": 1744,
  "dates": "1744 – 1803",
  "place": "Riga, Bückeburg and Weimar",
  "era": "Enlightenment",
  "tradition": "German Enlightenment and Romanticism",
  "tagline": "He argued that people think through language and that every culture should be understood on its own terms."
 },
 {
  "slug": "jeremy-bentham",
  "order": 1748,
  "dates": "1748 – 1832",
  "place": "London, England",
  "era": "Enlightenment",
  "tradition": "Utilitarianism",
  "tagline": "He asked of every law and custom a single question: does it increase happiness or reduce suffering?"
 },
 {
  "slug": "johann-wolfgang-von-goethe",
  "order": 1749,
  "dates": "1749 – 1832",
  "place": "Weimar, Saxe-Weimar-Eisenach (now Germany)",
  "era": "Enlightenment",
  "tradition": "Weimar classicism",
  "tagline": "Poet, dramatist, scientist and statesman, whose Faust became the great German drama of striving and doubt."
 },
 {
  "slug": "william-blake",
  "order": 1757,
  "dates": "1757 – 1827",
  "place": "London, with three years at Felpham, Sussex",
  "era": "Enlightenment",
  "tradition": "English Romanticism",
  "tagline": "A poor engraver who saw eternity in a grain of sand and answered the age of reason with imagination."
 },
 {
  "slug": "mary-wollstonecraft",
  "order": 1759,
  "dates": "1759 – 1797",
  "place": "London, Ireland, Paris and England",
  "era": "Enlightenment",
  "tradition": "Early feminism",
  "tagline": "She argued that women are rational beings who need education and independence, and that society should treat them as such."
 },
 {
  "slug": "friedrich-schiller",
  "order": 1759,
  "dates": "1759 – 1805",
  "place": "Stuttgart, Jena and Weimar, Germany",
  "era": "Enlightenment",
  "tradition": "Weimar classicism",
  "tagline": "The poet-dramatist who argued that beauty and play are how human beings become free."
 },
 {
  "slug": "johann-gottlieb-fichte",
  "order": 1762,
  "dates": "1762 – 1814",
  "place": "Jena and Berlin, Germany",
  "era": "Enlightenment",
  "tradition": "German idealism",
  "tagline": "The philosopher who made the free, active self the starting point of all knowledge."
 },
 {
  "slug": "germaine-de-stael",
  "order": 1766,
  "dates": "1766 – 1817",
  "place": "Paris, Coppet (Switzerland), and exile across Europe",
  "era": "Enlightenment",
  "tradition": "Liberal Romanticism",
  "tagline": "The salon hostess and author who opposed Napoleon and introduced French readers to German Romanticism."
 },
 {
  "slug": "wilhelm-von-humboldt",
  "order": 1767,
  "dates": "1767 – 1835",
  "place": "Berlin, Rome, Vienna and Tegel, Prussia",
  "era": "Enlightenment",
  "tradition": "Philosophy of language and education",
  "tagline": "The statesman and linguist who argued that people flourish through self-cultivation, and that language shapes how we see the world."
 },
 {
  "slug": "georg-wilhelm-friedrich-hegel",
  "order": 1770,
  "dates": "1770 – 1831",
  "place": "Stuttgart, Jena, Nuremberg, Heidelberg and Berlin (Germany)",
  "era": "19th Century",
  "tradition": "German idealism",
  "tagline": "He tried to show that history, thought and freedom move forward through conflict, and that every contradiction can lead to something richer."
 },
 {
  "slug": "arthur-schopenhauer",
  "order": 1788,
  "dates": "1788 – 1860",
  "place": "Danzig (now Gdańsk), Hamburg, Dresden, Berlin and Frankfurt",
  "era": "19th Century",
  "tradition": "Pessimism",
  "tagline": "A fierce and elegant writer who saw the world as driven by a blind striving, and who looked to art and compassion for relief."
 },
 {
  "slug": "thomas-carlyle",
  "order": 1795,
  "dates": "1795 – 1881",
  "place": "Ecclefechan, Edinburgh, Craigenputtock and Chelsea, London",
  "era": "19th Century",
  "tradition": "Victorian thought",
  "tagline": "A Scottish prophet of work, duty and heroes who shaped Victorian conscience, and whose later politics and racism darkened his name."
 },
 {
  "slug": "auguste-comte",
  "order": 1798,
  "dates": "1798 – 1857",
  "place": "Montpellier and Paris, France",
  "era": "19th Century",
  "tradition": "Positivism",
  "tagline": "The founder of positivism, who named sociology, argued that knowledge passes through three stages, and then tried to found a religion of humanity."
 },
 {
  "slug": "giacomo-leopardi",
  "order": 1798,
  "dates": "1798 – 1837",
  "place": "Recanati, then Rome, Milan, Bologna, Florence, Pisa and Naples, Italy",
  "era": "19th Century",
  "tradition": "Romantic pessimism",
  "tagline": "A frail young scholar from a small Italian town who wrote some of the most beautiful poetry of his century about the sorrow of being alive."
 },
 {
  "slug": "ralph-waldo-emerson",
  "order": 1803,
  "dates": "1803 – 1882",
  "place": "Boston and Concord, Massachusetts, USA",
  "era": "19th Century",
  "tradition": "Transcendentalism",
  "tagline": "The Concord essayist who told Americans to trust their own minds and to read nature, and not tradition, as a source of truth."
 },
 {
  "slug": "ludwig-feuerbach",
  "order": 1804,
  "dates": "1804 – 1872",
  "place": "Landshut, Erlangen, Bruckberg and Nuremberg, Bavaria",
  "era": "19th Century",
  "tradition": "Young Hegelians",
  "tagline": "The philosopher who said that God is a projection of human nature, and whose humanism shaped Marx, Engels and Freud."
 },
 {
  "slug": "alexis-de-tocqueville",
  "order": 1805,
  "dates": "1805 – 1859",
  "place": "Paris, and travels in the United States and Algeria",
  "era": "19th Century",
  "tradition": "Political philosophy",
  "tagline": "A French aristocrat who crossed the Atlantic to study democracy and saw both its promise and its hidden dangers."
 },
 {
  "slug": "max-stirner",
  "order": 1806,
  "dates": "1806 – 1856",
  "place": "Berlin, Prussia",
  "era": "19th Century",
  "tradition": "Individualist anarchism",
  "tagline": "A shadowy Berlin schoolteacher whose single book defended the unique self against every cause, creed and state."
 },
 {
  "slug": "john-stuart-mill",
  "order": 1806,
  "dates": "1806 – 1873",
  "place": "London, England, and Avignon, France",
  "era": "19th Century",
  "tradition": "Utilitarianism and liberalism",
  "tagline": "A prodigy who rebuilt utilitarianism around human development, and who argued that people should be free to live as they choose so long as they do not harm others."
 },
 {
  "slug": "charles-darwin",
  "order": 1809,
  "dates": "1809 – 1882",
  "place": "Shrewsbury and Downe, England, and the voyage of HMS Beagle",
  "era": "19th Century",
  "tradition": "Natural history and evolution",
  "tagline": "He showed how living things could arise by natural selection, and changed how humans see their place in nature."
 },
 {
  "slug": "s-ren-kierkegaard",
  "order": 1813,
  "dates": "1813 – 1855",
  "place": "Copenhagen, Denmark",
  "era": "19th Century",
  "tradition": "Existentialism",
  "tagline": "He asked what it means to become a real individual before God, and wrote under invented names to make readers think for themselves."
 },
 {
  "slug": "mikhail-bakunin",
  "order": 1814,
  "dates": "1814 – 1876",
  "place": "Russia, Germany, Siberia, then exile in Western Europe and Switzerland",
  "era": "19th Century",
  "tradition": "Anarchism",
  "tagline": "A Russian aristocrat turned professional revolutionary, who argued that every state, however it is justified, ends up ruling over the people it claims to serve."
 },
 {
  "slug": "taras-shevchenko",
  "order": 1814,
  "dates": "1814 – 1861",
  "place": "Ukraine, St Petersburg, and exile in the Orenburg region and Kazakhstan",
  "era": "19th Century",
  "tradition": "Ukrainian national thought",
  "tagline": "A serf who became the great poet and painter of Ukraine, and whose voice gave a people a language for its freedom."
 },
 {
  "slug": "henry-david-thoreau",
  "order": 1817,
  "dates": "1817 – 1862",
  "place": "Concord, Massachusetts, USA",
  "era": "19th Century",
  "tradition": "Transcendentalism",
  "tagline": "The writer who went to a pond near Concord to live deliberately and left behind the classic argument for conscience over obedience."
 },
 {
  "slug": "karl-marx",
  "order": 1818,
  "dates": "1818 – 1883",
  "place": "Trier, Paris, Brussels and London",
  "era": "19th Century",
  "tradition": "Marxism",
  "tagline": "He argued that economic life shapes society and history, and that capitalism contains conflicts that would end in its transformation."
 },
 {
  "slug": "john-ruskin",
  "order": 1819,
  "dates": "1819 – 1900",
  "place": "London, Oxford and the Lake District, England",
  "era": "19th Century",
  "tradition": "Victorian art criticism",
  "tagline": "The critic who taught Victorians to look at art and architecture, and then turned the same moral eye on the economy."
 },
 {
  "slug": "george-eliot",
  "order": 1819,
  "dates": "1819 – 1880",
  "place": "Warwickshire, Coventry and London, England",
  "era": "19th Century",
  "tradition": "Victorian literature and ethics",
  "tagline": "The novelist who tried to make readers understand other people from the inside, and treated sympathy as the foundation of morality."
 },
 {
  "slug": "friedrich-engels",
  "order": 1820,
  "dates": "1820 – 1895",
  "place": "Barmen (Prussia), Manchester and London",
  "era": "19th Century",
  "tradition": "Marxism",
  "tagline": "A mill-owner’s son who became Marx’s lifelong partner, and who did more than anyone to turn their shared ideas into a worldwide movement."
 },
 {
  "slug": "herbert-spencer",
  "order": 1820,
  "dates": "1820 – 1903",
  "place": "Derby, then London, England",
  "era": "19th Century",
  "tradition": "Evolutionary philosophy",
  "tagline": "The self-taught Victorian who tried to explain the whole universe, from stars to societies, as one process of evolution."
 },
 {
  "slug": "fyodor-dostoyevsky",
  "order": 1821,
  "dates": "1821 – 1881",
  "place": "Moscow, Siberia, and Saint Petersburg, Russia",
  "era": "19th Century",
  "tradition": "Russian religious and psychological thought",
  "tagline": "A novelist who staged the great arguments about freedom, suffering and faith inside the minds of his characters."
 },
 {
  "slug": "ernest-renan",
  "order": 1823,
  "dates": "1823 – 1892",
  "place": "Paris, France (born in Tréguier, Brittany)",
  "era": "19th Century",
  "tradition": "French historical criticism",
  "tagline": "A scholar who lost his faith, wrote the life of Jesus as a human story, and defined a nation as a daily act of shared will."
 },
 {
  "slug": "thomas-henry-huxley",
  "order": 1825,
  "dates": "1825 – 1895",
  "place": "London, England (born in Ealing)",
  "era": "19th Century",
  "tradition": "Scientific agnosticism",
  "tagline": "Darwin’s fiercest public defender, who gave the world the word “agnostic” and argued that ethics must resist nature."
 },
 {
  "slug": "leo-tolstoy",
  "order": 1828,
  "dates": "1828 – 1910",
  "place": "Yasnaya Polyana, Russia",
  "era": "19th Century",
  "tradition": "Christian anarchism and moral thought",
  "tagline": "A great novelist who turned away from fame and wealth to preach non-violence and the plain teaching of Jesus."
 },
 {
  "slug": "ramakrishna",
  "order": 1836,
  "dates": "1836 – 1886",
  "place": "Dakshineswar, near Calcutta, Bengal (born in Kamarpukur)",
  "era": "19th Century",
  "tradition": "Bengal mysticism",
  "tagline": "A temple priest in Bengal whose devotion to the Divine Mother and respect for many faiths drew visitors from across Calcutta."
 },
 {
  "slug": "ilia-chavchavadze",
  "order": 1837,
  "dates": "1837 – 1907",
  "place": "Kvareli, Kakheti, then Tbilisi (Georgia)",
  "era": "19th Century",
  "tradition": "Georgian national thought",
  "tagline": "Poet, editor and banker who tried to rebuild a nation under imperial rule from three things: the fatherland, the language and the faith."
 },
 {
  "slug": "charles-sanders-peirce",
  "order": 1839,
  "dates": "1839 – 1914",
  "place": "Cambridge, Massachusetts, and Milford, Pennsylvania, USA",
  "era": "19th Century",
  "tradition": "Pragmatism",
  "tagline": "The brilliant, difficult American logician who founded pragmatism and the study of signs, and died in near poverty."
 },
 {
  "slug": "akaki-tsereteli",
  "order": 1840,
  "dates": "1840 – 1915",
  "place": "Skhvitori, Imereti, and Kutaisi, Tbilisi and across Georgia",
  "era": "19th Century",
  "tradition": "Georgian poetry and national thought",
  "tagline": "The poet of the Georgian people, whose verses became songs that a whole nation knows by heart."
 },
 {
  "slug": "william-james",
  "order": 1842,
  "dates": "1842 – 1910",
  "place": "New York City and Cambridge, Massachusetts, USA",
  "era": "19th Century",
  "tradition": "Pragmatism",
  "tagline": "The psychologist and philosopher who judged ideas by what they do in lived experience, and who defended our right to believe."
 },
 {
  "slug": "peter-kropotkin",
  "order": 1842,
  "dates": "1842 – 1921",
  "place": "Moscow, Siberia, Switzerland, France, England and Dmitrov, Russia",
  "era": "19th Century",
  "tradition": "Anarchism",
  "tagline": "A prince and geographer turned anarchist, who argued that cooperation is as natural as competition."
 },
 {
  "slug": "friedrich-nietzsche",
  "order": 1844,
  "dates": "1844 – 1900",
  "place": "Röcken, Prussia; Basel, Switzerland; Weimar, Germany",
  "era": "19th Century",
  "tradition": "Existentialism and critique of morality",
  "tagline": "The philosopher who asked what is left of morality and meaning after belief in God fades, and who challenged people to create their own values."
 },
 {
  "slug": "jose-marti",
  "order": 1853,
  "dates": "1853 – 1895",
  "place": "Havana, Spain, Mexico, Guatemala, New York; killed at Dos Ríos, Cuba",
  "era": "19th Century",
  "tradition": "Latin American independence thought",
  "tagline": "A poet and journalist who organised a war for Cuban freedom and died on its first weeks of fighting."
 },
 {
  "slug": "emile-durkheim",
  "order": 1858,
  "dates": "1858 – 1917",
  "place": "Épinal, Bordeaux and Paris, France",
  "era": "19th Century",
  "tradition": "Sociology",
  "tagline": "The scholar who argued that society can be studied as a science, and that it shapes us far more than we realise."
 },
 {
  "slug": "max-planck",
  "order": 1858,
  "dates": "1858 – 1947",
  "place": "Kiel, Munich, Berlin and Göttingen, Germany",
  "era": "20th Century",
  "tradition": "Physics and philosophy of science",
  "tagline": "The physicist who introduced the quantum in 1900 and opened the door to modern physics, reluctantly."
 },
 {
  "slug": "john-dewey",
  "order": 1859,
  "dates": "1859 – 1952",
  "place": "Chicago and New York, United States",
  "era": "20th Century",
  "tradition": "Pragmatism",
  "tagline": "The philosopher who argued that we learn by doing, and that democracy is a way of living together."
 },
 {
  "slug": "henri-bergson",
  "order": 1859,
  "dates": "1859 – 1941",
  "place": "Paris, France",
  "era": "20th Century",
  "tradition": "Process philosophy and vitalism",
  "tagline": "The philosopher of lived time, who argued that the clock measures something other than the flow we actually experience."
 },
 {
  "slug": "vazha-pshavela",
  "order": 1861,
  "dates": "1861 – 1915",
  "place": "Chargali, Pshavi (Georgian highlands), and Tbilisi",
  "era": "19th Century",
  "tradition": "Georgian literature and thought",
  "tagline": "A mountain schoolteacher and farmer who wrote epics in which conscience, nature and the stranger outweigh the demands of the tribe."
 },
 {
  "slug": "rabindranath-tagore",
  "order": 1861,
  "dates": "1861 – 1941",
  "place": "Calcutta (Kolkata) and Santiniketan, Bengal, India",
  "era": "19th Century",
  "tradition": "Bengali Renaissance",
  "tagline": "A poet, songwriter and educator who won the Nobel Prize and spent his life pleading for a humanity larger than any nation."
 },
 {
  "slug": "alfred-north-whitehead",
  "order": 1861,
  "dates": "1861 – 1947",
  "place": "Ramsgate, England, then London and Cambridge, Massachusetts",
  "era": "20th Century",
  "tradition": "Process philosophy",
  "tagline": "A mathematician who co-wrote Principia Mathematica, then spent his last decades arguing that reality is made of events, not things."
 },
 {
  "slug": "george-santayana",
  "order": 1863,
  "dates": "1863 – 1952",
  "place": "Madrid, Boston and Cambridge (Massachusetts), later Rome",
  "era": "20th Century",
  "tradition": "Naturalism",
  "tagline": "A Spanish-born Harvard philosopher who doubted everything he could not live without, and who wrote about the life of the mind as a poet would."
 },
 {
  "slug": "swami-vivekananda",
  "order": 1863,
  "dates": "1863 – 1902",
  "place": "Calcutta (Kolkata), India; Chicago and the West; Belur Math",
  "era": "19th Century",
  "tradition": "Vedanta and Hindu reform",
  "tagline": "A monk who carried Vedanta to the West and taught that serving people is a way of serving God."
 },
 {
  "slug": "miguel-de-unamuno",
  "order": 1864,
  "dates": "1864 – 1936",
  "place": "Bilbao and Salamanca, Spain",
  "era": "20th Century",
  "tradition": "Existentialist forerunner",
  "tagline": "A Basque professor, novelist and poet who made doubt, death and the hunger for immortality the centre of philosophy."
 },
 {
  "slug": "max-weber",
  "order": 1864,
  "dates": "1864 – 1920",
  "place": "Erfurt, Berlin, Freiburg, Heidelberg and Munich, Germany",
  "era": "20th Century",
  "tradition": "Sociology",
  "tagline": "The German scholar who asked how religion, bureaucracy and power shaped the modern world, and who warned about what it costs."
 },
 {
  "slug": "emma-goldman",
  "order": 1869,
  "dates": "1869 – 1940",
  "place": "Kaunas (Lithuania), New York, Moscow, Barcelona and Toronto",
  "era": "20th Century",
  "tradition": "Anarchist feminism",
  "tagline": "An immigrant agitator who fought for free speech, free love and the freedom of the individual against every kind of state."
 },
 {
  "slug": "mahatma-gandhi",
  "order": 1869,
  "dates": "2 October 1869 – 30 January 1948",
  "place": "Porbandar (Gujarat), South Africa and India",
  "era": "20th Century",
  "tradition": "Nonviolence and Indian independence",
  "tagline": "A lawyer who turned refusal to hit back into a method of political struggle, and led India’s movement against British rule."
 },
 {
  "slug": "rosa-luxemburg",
  "order": 1871,
  "dates": "1871 – 1919",
  "place": "Zamość (Poland), Zurich and Berlin",
  "era": "20th Century",
  "tradition": "Revolutionary socialism",
  "tagline": "A Polish-German Marxist who believed socialism must be won by the masses, with democracy, and who was murdered for it."
 },
 {
  "slug": "bertrand-russell",
  "order": 1872,
  "dates": "18 May 1872 – 2 February 1970",
  "place": "Trellech, Wales; worked mainly in Cambridge and London",
  "era": "20th Century",
  "tradition": "Analytic philosophy",
  "tagline": "A logician who tried to rebuild mathematics from pure logic, and a public campaigner who went to prison for his convictions."
 },
 {
  "slug": "aurobindo-ghosh",
  "order": 1872,
  "dates": "15 August 1872 – 5 December 1950",
  "place": "Calcutta, England and Pondicherry (India)",
  "era": "20th Century",
  "tradition": "Integral philosophy",
  "tagline": "A revolutionary turned yogi who taught that human consciousness is still evolving and that life itself can be transformed."
 },
 {
  "slug": "g-k-chesterton",
  "order": 1874,
  "dates": "1874 – 1936",
  "place": "London and Beaconsfield, England",
  "era": "20th Century",
  "tradition": "Christian apologetics and paradox",
  "tagline": "A huge, laughing English journalist who defended old ideas by turning them upside down."
 },
 {
  "slug": "albert-schweitzer",
  "order": 1875,
  "dates": "14 January 1875 – 4 September 1965",
  "place": "Kaysersberg (Alsace), Strasbourg and Lambaréné (Gabon)",
  "era": "20th Century",
  "tradition": "Ethics of reverence for life",
  "tagline": "A theologian, organist and philosopher who left a brilliant career in Europe to become a jungle doctor and taught “reverence for life”."
 },
 {
  "slug": "hermann-hesse",
  "order": 1877,
  "dates": "1877 – 1962",
  "place": "Calw, Germany; Bern and Montagnola, Switzerland",
  "era": "20th Century",
  "tradition": "Modern spiritual literature",
  "tagline": "A novelist of the inner journey who sent Western readers east and inward in search of themselves."
 },
 {
  "slug": "martin-buber",
  "order": 1878,
  "dates": "1878 – 1965",
  "place": "Vienna, Lemberg, Heppenheim and Jerusalem",
  "era": "20th Century",
  "tradition": "Dialogical philosophy",
  "tagline": "A Jewish philosopher who taught that real life happens in meeting between persons."
 },
 {
  "slug": "albert-einstein",
  "order": 1879,
  "dates": "14 March 1879 – 18 April 1955",
  "place": "Ulm, Zurich, Berlin and Princeton",
  "era": "20th Century",
  "tradition": "Physics and philosophy of science",
  "tagline": "The physicist who remade our picture of space, time and gravity, and who also wrote thoughtfully about religion, war and freedom."
 },
 {
  "slug": "kahlil-gibran",
  "order": 1883,
  "dates": "1883 – 1931",
  "place": "Bsharri, Lebanon; Boston and New York, USA",
  "era": "20th Century",
  "tradition": "Pen League and mystic poetry",
  "tagline": "A Lebanese-American poet and painter whose short book The Prophet became one of the century’s most loved."
 },
 {
  "slug": "john-maynard-keynes",
  "order": 1883,
  "dates": "1883 – 1946",
  "place": "Cambridge and London, England",
  "era": "20th Century",
  "tradition": "Economics",
  "tagline": "The economist who argued that governments should spend in a slump, and whose ideas shaped the postwar world."
 },
 {
  "slug": "jose-ortega-y-gasset",
  "order": 1883,
  "dates": "1883 – 1955",
  "place": "Madrid, Spain",
  "era": "20th Century",
  "tradition": "Spanish philosophy",
  "tagline": "The Spanish thinker who said that each of us is “myself and my circumstance”, and who warned that a society can be ruled by people who refuse to be guided by anything beyond themselves."
 },
 {
  "slug": "fernando-pessoa",
  "order": 1888,
  "dates": "1888 – 1935",
  "place": "Lisbon, Portugal (childhood in Durban, South Africa)",
  "era": "20th Century",
  "tradition": "Modernist poetry",
  "tagline": "A Lisbon clerk who wrote as dozens of different authors and left behind a trunk full of unfinished books."
 },
 {
  "slug": "martin-heidegger",
  "order": 1889,
  "dates": "26 September 1889 – 26 May 1976",
  "place": "Messkirch, Germany; taught in Marburg and Freiburg",
  "era": "20th Century",
  "tradition": "Phenomenology",
  "tagline": "A thinker who asked what it means to be at all, and whose brilliant work is shadowed by his support for the Nazi regime."
 },
 {
  "slug": "ludwig-wittgenstein",
  "order": 1889,
  "dates": "26 April 1889 – 29 April 1951",
  "place": "Vienna, Austria; lived mainly in Cambridge, England",
  "era": "20th Century",
  "tradition": "Analytic philosophy",
  "tagline": "A philosopher who changed his mind about language so completely that he wrote two masterpieces that seem to argue with each other."
 },
 {
  "slug": "b-r-ambedkar",
  "order": 1891,
  "dates": "1891 – 1956",
  "place": "Bombay and New Delhi, India",
  "era": "20th Century",
  "tradition": "Anti-caste and constitutional thought",
  "tagline": "Born an “untouchable”, he became a scholar, a lawyer and the chief architect of India’s Constitution, and spent his life arguing that caste must be destroyed."
 },
 {
  "slug": "antonio-gramsci",
  "order": 1891,
  "dates": "1891 – 1937",
  "place": "Turin and Rome, Italy (born in Sardinia)",
  "era": "20th Century",
  "tradition": "Western Marxism",
  "tagline": "A Sardinian revolutionary who wrote, from a Fascist prison, how power works through consent as well as force."
 },
 {
  "slug": "galaktion-tabidze",
  "order": 1891,
  "dates": "1891 – 1959",
  "place": "Tbilisi, Georgia (born in Chkvishi, Imereti)",
  "era": "20th Century",
  "tradition": "Georgian symbolism",
  "tagline": "The poet many Georgians call the greatest of the twentieth century, whose music of words survived the Soviet years that destroyed his friends."
 },
 {
  "slug": "walter-benjamin",
  "order": 1892,
  "dates": "1892 – 1940",
  "place": "Berlin, Paris and Portbou (Spain)",
  "era": "20th Century",
  "tradition": "Critical theory",
  "tagline": "A Berlin essayist who wrote about the lost aura of art, the dream-worlds of cities and the angel of history, and who died on a border while fleeing the Nazis."
 },
 {
  "slug": "aldous-huxley",
  "order": 1894,
  "dates": "1894 – 1963",
  "place": "England, then Los Angeles, California",
  "era": "20th Century",
  "tradition": "Dystopian fiction and mysticism",
  "tagline": "A satirist who imagined a world enslaved by pleasure, then spent his later years searching for the experience that lies beyond ordinary perception."
 },
 {
  "slug": "jiddu-krishnamurti",
  "order": 1895,
  "dates": "11 May 1895 – 17 February 1986",
  "place": "Madanapalle (India), Adyar, England and Ojai (California)",
  "era": "20th Century",
  "tradition": "Independent spiritual teaching",
  "tagline": "Raised to be a world saviour, he rejected the role and spent fifty years telling people that truth cannot be reached through any teacher, system or organisation."
 },
 {
  "slug": "friedrich-hayek",
  "order": 1899,
  "dates": "1899 – 1992",
  "place": "Vienna, London, Chicago and Freiburg",
  "era": "20th Century",
  "tradition": "Austrian school economics",
  "tagline": "An economist who argued that no planner can gather the knowledge scattered among millions of people, and who became a leading voice of classical liberalism."
 },
 {
  "slug": "antoine-de-saint-exupery",
  "order": 1900,
  "dates": "1900 – 1944",
  "place": "Lyon, the Sahara, Argentina, New York and southern France",
  "era": "20th Century",
  "tradition": "Humanist literature",
  "tagline": "A pilot who wrote about flight, the desert and the bonds between people, and whose small book about a prince became one of the most translated works in the world."
 },
 {
  "slug": "erich-fromm",
  "order": 1900,
  "dates": "23 March 1900 – 18 March 1980",
  "place": "Frankfurt, Germany; later New York, Mexico and Switzerland",
  "era": "20th Century",
  "tradition": "Humanistic psychoanalysis",
  "tagline": "A psychoanalyst who asked why free people give up their freedom, and why love has to be learned."
 },
 {
  "slug": "karl-popper",
  "order": 1902,
  "dates": "28 July 1902 – 17 September 1994",
  "place": "Vienna, Austria; later Christchurch, New Zealand, and London",
  "era": "20th Century",
  "tradition": "Philosophy of science",
  "tagline": "He said that science advances by trying to prove itself wrong, and that open societies do the same."
 },
 {
  "slug": "theodor-w-adorno",
  "order": 1903,
  "dates": "1903 – 1969",
  "place": "Frankfurt, Oxford, New York, Los Angeles and Frankfurt again",
  "era": "20th Century",
  "tradition": "Critical theory",
  "tagline": "A philosopher, sociologist and musician who asked how a civilisation built on reason could end in catastrophe, and whether mass culture helps keep people docile."
 },
 {
  "slug": "jean-paul-sartre",
  "order": 1905,
  "dates": "21 June 1905 – 15 April 1980",
  "place": "Paris, France",
  "era": "20th Century",
  "tradition": "Existentialism",
  "tagline": "The philosopher and writer who told people they are condemned to be free, and who tried to live by it in public."
 },
 {
  "slug": "emmanuel-levinas",
  "order": 1906,
  "dates": "1906 – 1995",
  "place": "Kaunas, Lithuania; Strasbourg, Freiburg and Paris",
  "era": "20th Century",
  "tradition": "Ethics and phenomenology",
  "tagline": "A philosopher who argued that ethics comes before everything else, and that it begins in the face of another person."
 },
 {
  "slug": "dietrich-bonhoeffer",
  "order": 1906,
  "dates": "1906 – 1945",
  "place": "Berlin, Germany (born in Breslau); executed at Flossenbürg",
  "era": "20th Century",
  "tradition": "Christian resistance ethics",
  "tagline": "A Lutheran pastor and theologian who argued that faith must cost something, and who paid for that conviction with his life under the Nazis."
 },
 {
  "slug": "hannah-arendt",
  "order": 1906,
  "dates": "14 October 1906 – 4 December 1975",
  "place": "Linden, near Hanover, and Königsberg, Germany; later Paris and New York",
  "era": "20th Century",
  "tradition": "Political philosophy",
  "tagline": "She tried to understand totalitarianism and what it means to act freely with others, and she gave us the phrase “the banality of evil”."
 },
 {
  "slug": "maurice-merleau-ponty",
  "order": 1908,
  "dates": "1908 – 1961",
  "place": "Paris, France",
  "era": "20th Century",
  "tradition": "Phenomenology",
  "tagline": "The philosopher who put the living body at the centre of experience, and showed that we know the world through it, not apart from it."
 },
 {
  "slug": "simone-de-beauvoir",
  "order": 1908,
  "dates": "9 January 1908 – 14 April 1986",
  "place": "Paris, France",
  "era": "20th Century",
  "tradition": "Existentialism and feminism",
  "tagline": "She argued that womanhood is shaped by society, and that freedom is real only when others are free too."
 },
 {
  "slug": "simone-weil",
  "order": 1909,
  "dates": "3 February 1909 – 24 August 1943",
  "place": "Paris, France; died in Ashford, England",
  "era": "20th Century",
  "tradition": "Christian mysticism and political thought",
  "tagline": "A philosopher who tried to share the suffering of workers and who taught that attention is a form of love."
 },
 {
  "slug": "emil-cioran",
  "order": 1911,
  "dates": "1911 – 1995",
  "place": "Rășinari, Transylvania, then Paris",
  "era": "20th Century",
  "tradition": "Pessimism",
  "tagline": "A sleepless Romanian exile in Paris who turned despair into some of the sharpest, and strangely funniest, prose of the century."
 },
 {
  "slug": "albert-camus",
  "order": 1913,
  "dates": "7 November 1913 – 4 January 1960",
  "place": "Mondovi (now Dréan), French Algeria; Algiers; France",
  "era": "20th Century",
  "tradition": "Absurdism",
  "tagline": "A writer who asked how to live honestly in a world that gives no answers, and concluded that we must imagine Sisyphus happy."
 },
 {
  "slug": "octavio-paz",
  "order": 1914,
  "dates": "1914 – 1998",
  "place": "Mexico City, with years in Paris, Tokyo and New Delhi",
  "era": "20th Century",
  "tradition": "Latin American literature",
  "tagline": "A Mexican poet and essayist who tried to understand his country’s solitude, and found in poetry a way of crossing it."
 },
 {
  "slug": "iris-murdoch",
  "order": 1919,
  "dates": "1919 – 1999",
  "place": "Oxford, England (born in Dublin)",
  "era": "20th Century",
  "tradition": "Moral philosophy and literature",
  "tagline": "A philosopher and novelist who argued that goodness depends on learning to see other people truly."
 },
 {
  "slug": "primo-levi",
  "order": 1919,
  "dates": "1919 – 1987",
  "place": "Turin, Italy",
  "era": "20th Century",
  "tradition": "Holocaust testimony",
  "tagline": "A chemist who survived Auschwitz and became one of its most precise and humane witnesses."
 },
 {
  "slug": "paulo-freire",
  "order": 1921,
  "dates": "1921 – 1997",
  "place": "Recife, Brazil; exile in Chile, the United States and Switzerland; São Paulo",
  "era": "20th Century",
  "tradition": "Critical pedagogy",
  "tagline": "The Brazilian educator who taught that learning to read the word means learning to read the world, and that teaching is never neutral."
 },
 {
  "slug": "john-rawls",
  "order": 1921,
  "dates": "1921 – 2002",
  "place": "Baltimore, Maryland, and Cambridge, Massachusetts, USA",
  "era": "20th Century",
  "tradition": "Political philosophy",
  "tagline": "He asked what rules of society we would choose if we did not know who we would be, and the question reshaped modern political philosophy."
 },
 {
  "slug": "frantz-fanon",
  "order": 1925,
  "dates": "1925 – 1961",
  "place": "Martinique, France, Algeria and Tunisia",
  "era": "20th Century",
  "tradition": "Anti-colonial thought",
  "tagline": "A psychiatrist from Martinique who joined the Algerian struggle and wrote about what colonialism does to the mind."
 },
 {
  "slug": "michel-foucault",
  "order": 1926,
  "dates": "1926 – 1984",
  "place": "Poitiers and Paris, France",
  "era": "20th Century",
  "tradition": "Post-structuralism",
  "tagline": "A historian of ideas who showed how prisons, clinics and schools shape the way we think, and who asked how we came to be the kind of people we are."
 },
 {
  "slug": "nodar-dumbadze",
  "order": 1928,
  "dates": "1928 – 1984",
  "place": "Tbilisi and western Georgia (Guria), Soviet Georgia",
  "era": "20th Century",
  "tradition": "Georgian literature",
  "tagline": "A Soviet-era Georgian storyteller whose warm, funny and heartbreaking novels made him one of the best-loved writers in the country."
 },
 {
  "slug": "jacques-derrida",
  "order": 1930,
  "dates": "1930 – 2004",
  "place": "Algiers; Paris, France",
  "era": "20th Century",
  "tradition": "Deconstruction",
  "tagline": "The French philosopher who showed that texts, and the concepts we think with, rarely mean what they claim to mean."
 },
 {
  "slug": "chinua-achebe",
  "order": 1930,
  "dates": "1930 – 2013",
  "place": "Ogidi and Nsukka, Nigeria; later the United States",
  "era": "20th Century",
  "tradition": "African literature",
  "tagline": "The Nigerian novelist who told the story of colonialism from the African side and changed how the world reads Africa."
 },
 {
  "slug": "merab-mamardashvili",
  "order": 1930,
  "dates": "1930 – 1990",
  "place": "Gori, Georgia; Moscow and Tbilisi",
  "era": "20th Century",
  "tradition": "Georgian and Soviet philosophy",
  "tagline": "A Georgian philosopher who taught in Moscow and Tbilisi that being human is an effort, and that truth stands above the fatherland."
 },
 {
  "slug": "vaclav-havel",
  "order": 1936,
  "dates": "1936 – 2011",
  "place": "Prague, Czechoslovakia",
  "era": "20th Century",
  "tradition": "Dissident thought",
  "tagline": "The playwright who became a dissident and then president, and who argued that ordinary people can undermine a lie by refusing to live in it."
 }
]

const GROUP_OF: Record<string, string> = {
 "socrates": "classical",
 "plato": "classical",
 "aristotle": "classical",
 "diogenes-of-sinope": "classical",
 "epicurus": "classical",
 "zeno-of-citium": "classical",
 "laozi": "eastern-ancient",
 "the-buddha": "eastern-ancient",
 "confucius": "eastern-ancient",
 "sun-tzu": "eastern-ancient",
 "mozi": "eastern-ancient",
 "mencius": "eastern-ancient",
 "chanakya": "eastern-ancient",
 "montesquieu": "enlightenment-a",
 "voltaire": "enlightenment-a",
 "jean-jacques-rousseau": "enlightenment-a",
 "denis-diderot": "enlightenment-a",
 "mary-wollstonecraft": "enlightenment-a",
 "david-hume": "enlightenment-b",
 "adam-smith": "enlightenment-b",
 "immanuel-kant": "enlightenment-b",
 "edmund-burke": "enlightenment-b",
 "thomas-paine": "enlightenment-b",
 "plutarch": "late-ancient",
 "augustine-of-hippo": "late-ancient",
 "boethius": "late-ancient",
 "al-ghazali": "medieval-a",
 "peter-abelard": "medieval-a",
 "averroes": "medieval-a",
 "thomas-aquinas": "medieval-a",
 "meister-eckhart": "medieval-a",
 "shota-rustaveli": "medieval-b",
 "rumi": "medieval-b",
 "dante-alighieri": "medieval-b",
 "petrarch": "medieval-b",
 "kabir": "medieval-b",
 "aesop": "more-01",
 "hippocrates": "more-01",
 "xenophon": "more-01",
 "zhuang-zhou": "more-01",
 "xunzi": "more-01",
 "patanjali": "more-02",
 "archimedes": "more-02",
 "han-fei": "more-02",
 "horace": "more-02",
 "philo-of-alexandria": "more-02",
 "nagarjuna": "more-03",
 "origen": "more-03",
 "adi-shankara": "more-03",
 "murasaki-shikibu": "more-03",
 "omar-khayyam": "more-03",
 "bernard-of-clairvaux": "more-04",
 "hildegard-of-bingen": "more-04",
 "moshe-ben-maimon": "more-04",
 "attar-of-nishapur": "more-04",
 "roger-bacon": "more-04",
 "bonaventure": "more-05",
 "geoffrey-chaucer": "more-05",
 "thomas-a-kempis": "more-05",
 "nicholas-of-cusa": "more-05",
 "jami": "more-05",
 "giovanni-pico-della-mirandola": "more-06",
 "nicolaus-copernicus": "more-06",
 "martin-luther": "more-06",
 "teresa-of-avila": "more-06",
 "etienne-de-la-boetie": "more-06",
 "galileo-galilei": "more-07",
 "johannes-kepler": "more-07",
 "miyamoto-musashi": "more-07",
 "baltasar-gracian": "more-07",
 "isaac-newton": "more-07",
 "sor-juana-ines-de-la-cruz": "more-08",
 "giambattista-vico": "more-08",
 "george-berkeley": "more-08",
 "gotthold-ephraim-lessing": "more-08",
 "cesare-beccaria": "more-08",
 "georg-christoph-lichtenberg": "more-09",
 "thomas-jefferson": "more-09",
 "johann-gottfried-herder": "more-09",
 "jeremy-bentham": "more-09",
 "johann-wolfgang-von-goethe": "more-09",
 "william-blake": "more-10",
 "friedrich-schiller": "more-10",
 "johann-gottlieb-fichte": "more-10",
 "germaine-de-stael": "more-10",
 "wilhelm-von-humboldt": "more-10",
 "thomas-carlyle": "more-11",
 "auguste-comte": "more-11",
 "giacomo-leopardi": "more-11",
 "ludwig-feuerbach": "more-11",
 "max-stirner": "more-11",
 "mikhail-bakunin": "more-12",
 "taras-shevchenko": "more-12",
 "john-ruskin": "more-12",
 "george-eliot": "more-12",
 "friedrich-engels": "more-12",
 "herbert-spencer": "more-13",
 "ernest-renan": "more-13",
 "thomas-henry-huxley": "more-13",
 "ramakrishna": "more-13",
 "charles-sanders-peirce": "more-13",
 "akaki-tsereteli": "more-14",
 "jose-marti": "more-14",
 "emile-durkheim": "more-14",
 "max-planck": "more-14",
 "john-dewey": "more-14",
 "george-santayana": "more-15",
 "miguel-de-unamuno": "more-15",
 "max-weber": "more-15",
 "emma-goldman": "more-15",
 "rosa-luxemburg": "more-15",
 "g-k-chesterton": "more-16",
 "hermann-hesse": "more-16",
 "martin-buber": "more-16",
 "kahlil-gibran": "more-16",
 "john-maynard-keynes": "more-16",
 "fernando-pessoa": "more-17",
 "b-r-ambedkar": "more-17",
 "antonio-gramsci": "more-17",
 "galaktion-tabidze": "more-17",
 "walter-benjamin": "more-17",
 "aldous-huxley": "more-18",
 "friedrich-hayek": "more-18",
 "antoine-de-saint-exupery": "more-18",
 "theodor-w-adorno": "more-18",
 "emmanuel-levinas": "more-18",
 "dietrich-bonhoeffer": "more-19",
 "maurice-merleau-ponty": "more-19",
 "octavio-paz": "more-19",
 "iris-murdoch": "more-19",
 "primo-levi": "more-19",
 "paulo-freire": "more-20",
 "nodar-dumbadze": "more-20",
 "jacques-derrida": "more-20",
 "chinua-achebe": "more-20",
 "vaclav-havel": "more-20",
 "georg-wilhelm-friedrich-hegel": "nineteenth-a",
 "arthur-schopenhauer": "nineteenth-a",
 "john-stuart-mill": "nineteenth-a",
 "s-ren-kierkegaard": "nineteenth-a",
 "karl-marx": "nineteenth-a",
 "ralph-waldo-emerson": "nineteenth-b",
 "henry-david-thoreau": "nineteenth-b",
 "william-james": "nineteenth-b",
 "friedrich-nietzsche": "nineteenth-b",
 "alexis-de-tocqueville": "nineteenth-c",
 "charles-darwin": "nineteenth-c",
 "fyodor-dostoyevsky": "nineteenth-c",
 "leo-tolstoy": "nineteenth-c",
 "peter-kropotkin": "nineteenth-c",
 "ilia-chavchavadze": "nineteenth-d",
 "vazha-pshavela": "nineteenth-d",
 "rabindranath-tagore": "nineteenth-d",
 "swami-vivekananda": "nineteenth-d",
 "thales": "presocratic",
 "pythagoras": "presocratic",
 "heraclitus": "presocratic",
 "parmenides": "presocratic",
 "democritus": "presocratic",
 "erasmus": "renaissance",
 "niccolo-machiavelli": "renaissance",
 "thomas-more": "renaissance",
 "michel-de-montaigne": "renaissance",
 "giordano-bruno": "renaissance",
 "francis-bacon": "renaissance",
 "cicero": "roman",
 "lucretius": "roman",
 "seneca": "roman",
 "epictetus": "roman",
 "marcus-aurelius": "roman",
 "plotinus": "roman",
 "thomas-hobbes": "seventeenth",
 "rene-descartes": "seventeenth",
 "blaise-pascal": "seventeenth",
 "benedictus-de-spinoza": "seventeenth",
 "john-locke": "seventeenth",
 "gottfried-wilhelm-leibniz": "seventeenth",
 "bertrand-russell": "twentieth-a",
 "martin-heidegger": "twentieth-a",
 "ludwig-wittgenstein": "twentieth-a",
 "jean-paul-sartre": "twentieth-a",
 "albert-camus": "twentieth-a",
 "erich-fromm": "twentieth-b",
 "karl-popper": "twentieth-b",
 "hannah-arendt": "twentieth-b",
 "simone-de-beauvoir": "twentieth-b",
 "simone-weil": "twentieth-b",
 "mahatma-gandhi": "twentieth-c",
 "aurobindo-ghosh": "twentieth-c",
 "albert-schweitzer": "twentieth-c",
 "albert-einstein": "twentieth-c",
 "jiddu-krishnamurti": "twentieth-c",
 "henri-bergson": "twentieth-d",
 "alfred-north-whitehead": "twentieth-d",
 "jose-ortega-y-gasset": "twentieth-d",
 "john-rawls": "twentieth-d",
 "michel-foucault": "twentieth-d",
 "emil-cioran": "twentieth-e",
 "frantz-fanon": "twentieth-e",
 "merab-mamardashvili": "twentieth-e"
}

const LOADERS: Record<string, () => Promise<Profile[]>> = {
  'classical': () => import('./classical').then((m) => m.CLASSICAL),
  'eastern-ancient': () => import('./eastern-ancient').then((m) => m.EASTERN_ANCIENT),
  'enlightenment-a': () => import('./enlightenment-a').then((m) => m.ENLIGHTENMENT_A),
  'enlightenment-b': () => import('./enlightenment-b').then((m) => m.ENLIGHTENMENT_B),
  'late-ancient': () => import('./late-ancient').then((m) => m.LATE_ANCIENT),
  'medieval-a': () => import('./medieval-a').then((m) => m.MEDIEVAL_A),
  'medieval-b': () => import('./medieval-b').then((m) => m.MEDIEVAL_B),
  'more-01': () => import('./more-01').then((m) => m.MORE_01),
  'more-02': () => import('./more-02').then((m) => m.MORE_02),
  'more-03': () => import('./more-03').then((m) => m.MORE_03),
  'more-04': () => import('./more-04').then((m) => m.MORE_04),
  'more-05': () => import('./more-05').then((m) => m.MORE_05),
  'more-06': () => import('./more-06').then((m) => m.MORE_06),
  'more-07': () => import('./more-07').then((m) => m.MORE_07),
  'more-08': () => import('./more-08').then((m) => m.MORE_08),
  'more-09': () => import('./more-09').then((m) => m.MORE_09),
  'more-10': () => import('./more-10').then((m) => m.MORE_10),
  'more-11': () => import('./more-11').then((m) => m.MORE_11),
  'more-12': () => import('./more-12').then((m) => m.MORE_12),
  'more-13': () => import('./more-13').then((m) => m.MORE_13),
  'more-14': () => import('./more-14').then((m) => m.MORE_14),
  'more-15': () => import('./more-15').then((m) => m.MORE_15),
  'more-16': () => import('./more-16').then((m) => m.MORE_16),
  'more-17': () => import('./more-17').then((m) => m.MORE_17),
  'more-18': () => import('./more-18').then((m) => m.MORE_18),
  'more-19': () => import('./more-19').then((m) => m.MORE_19),
  'more-20': () => import('./more-20').then((m) => m.MORE_20),
  'nineteenth-a': () => import('./nineteenth-a').then((m) => m.NINETEENTH_A),
  'nineteenth-b': () => import('./nineteenth-b').then((m) => m.NINETEENTH_B),
  'nineteenth-c': () => import('./nineteenth-c').then((m) => m.NINETEENTH_C),
  'nineteenth-d': () => import('./nineteenth-d').then((m) => m.NINETEENTH_D),
  'presocratic': () => import('./presocratic').then((m) => m.PRESOCRATIC),
  'renaissance': () => import('./renaissance').then((m) => m.RENAISSANCE),
  'roman': () => import('./roman').then((m) => m.ROMAN),
  'seventeenth': () => import('./seventeenth').then((m) => m.SEVENTEENTH),
  'twentieth-a': () => import('./twentieth-a').then((m) => m.TWENTIETH_A),
  'twentieth-b': () => import('./twentieth-b').then((m) => m.TWENTIETH_B),
  'twentieth-c': () => import('./twentieth-c').then((m) => m.TWENTIETH_C),
  'twentieth-d': () => import('./twentieth-d').then((m) => m.TWENTIETH_D),
  'twentieth-e': () => import('./twentieth-e').then((m) => m.TWENTIETH_E),
}

/** Downloads the group of profiles that holds `slug` (about five profiles) and returns the one asked for. */
export async function loadProfile(slug: string): Promise<Profile | undefined> {
  const group = GROUP_OF[slug]
  if (!group) return undefined
  return (await LOADERS[group]()).find((p) => p.slug === slug)
}
