import type { Profile } from './types'

export const RENAISSANCE: Profile[] = [
  {
    slug: 'erasmus',
    order: 1466,
    dates: 'c. 1466 – 1536',
    place: 'Rotterdam or Gouda, then Paris, England, Basel and Freiburg',
    era: 'Early Modern',
    tradition: 'Christian humanism',
    tagline: 'The most famous scholar in Europe, who tried to reform the Church with learning, good humour and sharp satire, and refused to join either side of the Reformation.',
    who: [
      'Desiderius Erasmus was born in the Netherlands, in Rotterdam or nearby Gouda, probably on 27 or 28 October. The year is uncertain, with 1466 the usual choice and 1467 or 1469 sometimes proposed. He was the illegitimate son of a priest, and both his parents died in his youth, probably of plague. He entered an Augustinian monastery at Steyn around 1487, and he was ordained a priest in the early 1490s. He disliked monastic life, and a bishop soon took him into service, which gave him the chance to leave and study in Paris.',
      'From then on he lived as a wandering scholar, supported by patrons, teaching and the income from his books. He made three stays in England, where he became close to John Colet and Thomas More, and he spent years in Italy and later in Basel, the centre of Swiss printing. He never held a permanent professorship for long. His real base was the printing press: he worked with the Basel printer Johann Froben, and his books and letters made him a celebrity across Europe.',
      'Erasmus remained a Catholic priest all his life, but he was impatient with the habits of the Church of his day, such as empty ritual, quarrelsome theology and worldly bishops. He wanted to return to the Bible and the early Christian writers, and to reform behaviour by education and persuasion. That position made him a hero to many reformers at first, and later a target for both Protestants and conservative Catholics. When Basel adopted the Reformation in 1529 he moved to Freiburg, returned to Basel in 1535 and died there on 12 July 1536.',
    ],
    context: [
      'The printing press, invented a few decades before his birth, transformed the world he worked in. For the first time a scholar’s edition of an ancient text could reach thousands of readers at once. Humanists, the scholars who studied the languages and literature of Greece and Rome, saw in this a chance to recover the original sources of Western culture, the Bible included, and to clean away what they saw as centuries of error and clutter.',
      'The Church of the time was wealthy, politically powerful and widely criticised. Erasmus lived through the years when Luther’s protest of 1517 turned a debate among scholars into a split of western Christendom, followed by wars of religion. His stance as a critic who wanted reform without breaking the Church made him enormously influential before the split and uncomfortable after it.',
    ],
    ideas: [
      { title: 'Return to the sources', text: 'The humanists’ motto was “to the sources”. Erasmus believed that reading the Bible in its original Greek, and the early Church writers in their own words, would show what Christianity had meant before centuries of commentary. In 1516 he published the first printed Greek New Testament, with his own Latin translation beside it and notes explaining his choices. Because his Latin differed from the traditional Vulgate in places, some theologians attacked him for tampering with sacred text.' },
      { title: 'The philosophy of Christ', text: 'Erasmus argued that the heart of Christianity is a way of life, humble, peaceful and charitable, and not a set of fine points of doctrine or ceremony. He called this the “philosophy of Christ”. His 1503 Handbook of the Christian Soldier urges ordinary lay people to pray, study scripture and fight their own vices, and it does not depend on monks or pilgrimages.' },
      { title: 'Satire as a tool for reform', text: 'In The Praise of Folly, written in 1509 at Thomas More’s house and published in 1511, the goddess Folly speaks in her own praise and gradually exposes the vanity of scholars, princes, merchants and churchmen. The Latin title, Moriae encomium, is also a pun on More’s name. The book is funny, but it carries a serious claim: pride and self-deception are the real source of much of the world’s trouble.' },
      { title: 'Peace and the critique of war', text: 'Erasmus was one of the strongest voices against war in his age. His essay on the proverb “war is sweet to those who have not tried it” and his Complaint of Peace (1517) argue that war is a crime against reason and Christian teaching, which tends to ruin the people it claims to protect. In The Education of a Christian Prince (1516) he urged the future emperor Charles V to rule for the good of his subjects.' },
      { title: 'Human effort and divine grace', text: 'When Luther claimed that the human will is bound and that we are saved only by grace, Erasmus answered in On Free Will (1524), arguing for a role for human choice cooperating with grace, and he disliked dogmatic certainty on such difficult questions. Luther replied sharply in On the Bondage of the Will (1525). The exchange shows two incompatible views of the human being, and Erasmus’s view stayed closer to the traditional teaching.' },
    ],
    principles: [
      'Go back to the original sources and read them carefully before you judge.',
      'Good conduct matters more than ceremony and clever argument.',
      'Persuade; do not coerce. Education and example change people more lastingly than force.',
      'Humour can tell the truth to people who will not listen to a lecture.',
      'Peace, even an imperfect one, is better than most victories.',
    ],
    practice: [
      'Before arguing about a quotation or a claim, track it back to its original context and read what was actually said.',
      'When a dispute turns heated, ask what both sides would still agree on and whether the disagreement needs to be a break.',
      'Use a little self-mockery: if you can laugh at your own certainties, you will listen better.',
    ],
    facts: [
      'The name Desiderius Erasmus is a scholar’s adopted name: both parts, Latin and Greek, are commonly explained as meaning “beloved” or “desired”. He is also known as Erasmus of Rotterdam, after the town he treated as his home.',
      'He recorded and popularised hundreds of classical proverbs in his Adagia, first published in 1500 and enlarged many times. Phrases such as “in the land of the blind the one-eyed man is king” appear in his collection, though he did not invent them.',
      'His Greek New Testament was a key source for later translators. Luther’s German Bible and Tyndale’s English New Testament both drew on it.',
      'He refused to choose sides in the Reformation, and a saying of the time, which he rejected, held that he “laid the egg that Luther hatched”.',
      'Erasmus wrote extensive letters. Thousands survive, and they are one of the best sources for the intellectual life of his time.',
      'The European Union’s Erasmus student exchange programme is named after him, partly for his travels across the continent.',
    ],
    myths: [
      { myth: 'Erasmus caused the Reformation and then abandoned it.', reality: 'He criticised abuses and prepared an audience that welcomed reform, but he never left the Catholic Church. He opposed Luther on free will and on the idea of splitting the Church, and he spent his last years fending off attacks from both camps.' },
      { myth: 'He was a timid fence-sitter without convictions.', reality: 'He took strong positions, against war, against superstition and for scripture in the vernacular, and he risked his reputation for them. He was reluctant to make a binary choice, but that was itself a conviction about unity and tolerance.' },
    ],
    works: [
      { title: 'Adagia (1500 and later editions)', note: 'A collection of classical proverbs with essays on them, which grew from a few hundred to several thousand entries.' },
      { title: 'Enchiridion militis christiani (1503)', note: 'A handbook of practical Christian life for lay people.' },
      { title: 'Moriae encomium, The Praise of Folly (1511)', note: 'His best-known satire, still widely read.' },
      { title: 'Novum Instrumentum (1516)', note: 'The first published Greek New Testament, with Latin translation and annotations.' },
      { title: 'Colloquies and Letters', note: 'Dialogues for teaching Latin that also criticise society and Church, and a huge body of correspondence.' },
    ],
    legacy: [
      'Erasmus’s editions and translations changed how Christians read their Bible, and the critical study of texts that he practised grew into modern scholarship. The Catholic Church put his works on its list of prohibited books in the sixteenth century and later allowed expurgated editions, while Protestants relied on his New Testament even as they rejected his stance on free will.',
      'He remains a symbol of moderation, tolerance and the power of education. Later writers, from the philosophes of the Enlightenment to modern defenders of free inquiry, have looked to him as an example of someone who tried to keep reason and conscience alive in a time of fanatical quarrels, and whose failure to prevent the split is itself a lesson about how hard that is.',
    ],
  },
  {
    slug: 'niccolo-machiavelli',
    order: 1469,
    dates: '1469 – 1527',
    place: 'Florence, Italy',
    era: 'Early Modern',
    tradition: 'Renaissance political thought',
    tagline: 'A Florentine diplomat whose cold-eyed book on power made his name a byword for cunning, though his deeper loyalty was to free republics.',
    who: [
      'Niccolò Machiavelli was born in Florence on 3 May 1469 into an old but not rich family. He seems to have had a good humanist education, but little is known about his early life. In 1498, after the fall of the preacher Savonarola, he was appointed Second Chancellor of the Florentine republic, an administrative and diplomatic post he held until 1512. He also served as a secretary to a committee responsible for war.',
      'In those years he travelled on missions to the French king, to the papal court and to the ruthless Cesare Borgia, and he organised a citizen militia for Florence as a replacement for hired soldiers. His career ended abruptly in 1512, when Spanish and papal forces helped restore the Medici family to power and the republic fell. In early 1513 he was arrested on suspicion of involvement in a plot against the Medici and tortured by the rope, but he was released, and he retired to a small farm outside the city.',
      'In forced retirement he wrote the works that made him famous. In a letter to his friend Francesco Vettori, dated December 1513, he describes spending his days with country neighbours and his evenings in his study, dressed in formal clothes, speaking with the ancient authors. He also hoped that the Medici would hire him again, which they only partly did. He died in Florence on 21 June 1527, shortly after the Medici had been driven out once more.',
    ],
    context: [
      'Italy in his lifetime was a patchwork of rival states, Florence, Venice, Milan, Naples and the Papal States among them, and from 1494 it became a battlefield for the armies of France, Spain and the Holy Roman Empire. City-states that had seemed strong collapsed within months. Machiavelli saw how quickly governments fell and he wanted to understand why.',
      'Earlier political writing in Europe often took the form of advice on how rulers should be virtuous, or described an ideal state. Machiavelli turned to what he called the “effectual truth” of things, meaning what actually happens in politics, drawn from his own experience and from the history of Rome and other states. This looks cynical to many readers, but it was a deliberate method.',
    ],
    ideas: [
      { title: 'Politics follows its own logic', text: 'In The Prince, written in 1513 and published only after his death, in 1532, Machiavelli argues that a ruler who always acts by the rules of conventional morality may be destroyed by those who do not. He advises that a prince must learn “how not to be good” when necessity demands it, and he must be judged by the results. He does not say cruelty is good; he says that rulers face choices where every option has a cost.' },
      { title: 'Virtù and fortuna', text: 'Two words run through his work. Virtù, from the Latin for “manliness” or ability, means the energy, skill and nerve needed to get things done; it is not the same as moral virtue. Fortuna, luck or chance, is the power of events. Machiavelli compares fortune to a river that floods: it cannot be stopped, but prepared people can build dikes beforehand, and he claims that bold action often succeeds against her.' },
      { title: 'A defence of republics', text: 'The Discourses on Livy, written around the same years and published in 1531, uses the early history of Rome to praise republican government. He argues that conflict between the people and the nobles, though noisy, kept Rome free, and that a well-ordered republic is more stable and more capable of lasting greatness than a monarchy. The book is the clearest sign that the author of The Prince was no simple champion of tyranny.' },
      { title: 'Citizens should bear arms', text: 'Machiavelli distrusted hired mercenary armies, which he thought were unreliable and dangerous to the state that paid them. He wanted armies made up of citizens who had something to fight for. His Art of War, published in 1521, presents this view in dialogue form, and it was the only major political work of his that appeared in print during his lifetime.' },
      { title: 'Appearance matters', text: 'A prince, he says, needs to seem merciful, faithful and religious, since people judge by what they see. This advice has been read as an endorsement of hypocrisy, but it also reflects a realistic view of how public trust works and why leaders who lose it do not survive.' },
    ],
    principles: [
      'Study what actually happens, and not only what ought to happen.',
      'Prepare for bad luck in good times, as one builds dikes before the flood.',
      'Free states need conflict among their groups to be channelled by good laws and institutions.',
      'Do not rely on others to fight your battles for you.',
      'Judge leaders by the results and by how they treat the people they rule.',
    ],
    practice: [
      'When making a plan, write down how it might fail and what you would do if luck turns against you.',
      'Notice the difference between how institutions are supposed to work and how they work, and plan with the second in mind.',
      'Read history for patterns: ask what a similar situation looked like in the past and how it ended.',
    ],
    facts: [
      'The Prince has 26 short chapters and was dedicated to a Medici ruler. It was first intended for Giuliano de’ Medici and then, after his death in 1516, for Lorenzo de’ Medici.',
      'Machiavelli was also a playwright. His comedy La Mandragola, written around 1518, is regarded as one of the best Italian plays of its time.',
      'In 1520 the Medici commissioned him to write a history of Florence, which he finished in 1525.',
      'He was tortured with the strappado, in which the victim is hoisted by the arms tied behind the back, and he later wrote sonnets from prison.',
      'His works were placed on the Catholic Church’s list of prohibited books in 1559, yet they continued to circulate widely.',
    ],
    myths: [
      { myth: '“The end justifies the means” is Machiavelli’s motto.', reality: 'The phrase does not appear in The Prince. He wrote that people judge a ruler by the outcome, which is a claim about how political judgement works, not a moral recommendation that anything is allowed.' },
      { myth: 'He was simply an advocate of tyranny.', reality: 'His longest political work praises republics, and he spent his career serving one. Scholars disagree whether The Prince is a sincere manual for rulers, a job application to the Medici, or a veiled lesson to the public, and the debate is still open. Rousseau, in the eighteenth century, suggested that it was meant to teach peoples about the ways of tyrants.' },
    ],
    works: [
      { title: 'The Prince (1513, published 1532)', note: 'A short guide to winning and keeping power in a state.' },
      { title: 'Discourses on Livy (c. 1514–19, published 1531)', note: 'Reflections on republican government through the history of early Rome.' },
      { title: 'The Art of War (1521)', note: 'A dialogue on military organisation and citizen armies.' },
      { title: 'Florentine Histories (finished 1525)', note: 'A history of Florence, commissioned by the Medici.' },
      { title: 'La Mandragola', note: 'A satirical comedy, written around 1518.' },
    ],
    legacy: [
      'Machiavelli is often called the founder of modern political thought. By describing power as it is, and not as moralists wished it to be, he opened a path that leads to Hobbes, Spinoza and later political science. His republicanism influenced writers in England and in the American founding generation, who read the Discourses closely.',
      'His name has also become an adjective, “Machiavellian”, which now means cunning and unscrupulous. That popular image has long outrun the actual books, and it hides the real argument of the Discourses. His work remains useful because it asks hard questions that moral advice often avoids: what do leaders owe to the truth, how can freedom survive, and what do we do when doing right is costly.',
    ],
  },
  {
    slug: 'thomas-more',
    order: 1478,
    dates: '1478 – 1535',
    place: 'London, England',
    era: 'Early Modern',
    tradition: 'Humanism',
    tagline: 'A lawyer, scholar and statesman who imagined an island called Nowhere, and who died on the scaffold for refusing to accept the king as head of the Church.',
    who: [
      'Thomas More was born in London on 7 February 1478, the son of a lawyer who later became a judge. As a boy he served in the household of John Morton, Archbishop of Canterbury, and then studied at Oxford for about two years before his father sent him to train in the law, at New Inn and Lincoln’s Inn. For a time he lived near a Carthusian monastery and considered becoming a monk, but he chose the law and family life instead. He married Jane Colt in 1505, and after her death in 1511 he married a widow, Alice Middleton.',
      'He became a successful lawyer, a member of Parliament and, in 1523, Speaker of the House of Commons. Through the humanist circle of John Colet and Erasmus he became one of the leading scholars of England, and Erasmus wrote The Praise of Folly in his house. Utopia, published in 1516, made him famous across Europe. He entered the service of Henry VIII around 1518, was knighted in 1521, and in October 1529 succeeded Cardinal Wolsey as Lord Chancellor.',
      'The crisis came over Henry’s wish to end his marriage to Catherine of Aragon and break with Rome. More resigned as Chancellor in May 1532. In 1534 he was asked to swear an oath to the new Act of Succession, whose preamble denied the Pope’s authority, and he refused. He was imprisoned in the Tower of London, tried in July 1535 for treason, and beheaded on 6 July. He was canonised by the Catholic Church in 1935.',
    ],
    context: [
      'Tudor England was changing quickly. The wool trade and enclosure of common land were pushing people off farms, the printing press was spreading new ideas, and the Church’s authority was contested at home and abroad. Humanist scholars hoped to use education and Christian ethics to improve society, and More shared those hopes in his early career.',
      'Luther’s protest in 1517 made More a determined opponent of the new Protestant movement, which he saw as a threat both to the unity of the Church and to social order. In England Henry VIII’s divorce campaign then drew the crown into open conflict with Rome. More was thus a humanist and reformer who became, in the 1520s and 1530s, a defender of the old order, and that tension is why he remains a debated figure.',
    ],
    ideas: [
      { title: 'A critique of European society', text: 'In the first book of Utopia a traveller, Raphael Hythloday, criticises the greed of the rich, the idleness of the nobility, and the harsh punishment of petty thieves in England, who steal, he says, because poverty leaves them no choice. More puts the argument in the mouth of a fictional character, so we cannot simply read it as his own view, but the problems it names were real.' },
      { title: 'An imaginary island', text: 'The second book describes Utopia, an island where property is held in common, the working day is six hours, hospitals are free and gold is treated with contempt, used for chains and chamber pots. The name is a Greek pun, often explained as combining “no place” and “good place”. Some features seem attractive, and others, such as slavery for criminals and strict control of daily life, look troubling. Readers have long argued whether More meant it as a blueprint, a joke or a mirror.' },
      { title: 'Religious toleration, within limits', text: 'Utopians are allowed many religions, and no one may be punished for belief, though people who deny that there is a god or a life after death are distrusted and kept from public office. This contrasts with More’s later hard line against Protestant “heretics”, and historians have long debated how the two fit together.' },
      { title: 'Conscience and the law', text: 'During his imprisonment More refused to say why he would not take the oath, relying on the principle that the law could not convict a person for silence. At his trial he argued that Parliament could not make the king head of the Church against the practice of all Christendom. For him, conscience was a matter between the individual and God, and the state could not override it.' },
      { title: 'Hope and humour in suffering', text: 'In the Tower he wrote A Dialogue of Comfort against Tribulation, an imagined conversation between a Hungarian uncle and his nephew awaiting a Turkish invasion, about how to face fear and loss. It is a Christian reflection, and it is also notably humane and funny.' },
    ],
    principles: [
      'Look honestly at the suffering that social arrangements cause.',
      'Hold to your conscience, even when the cost is high.',
      'Serve the public but keep an inner life the state cannot reach.',
      'Use imagination, such as fiction or thought experiments, to test the way things are.',
      'Keep your sense of humour, even in a crisis.',
    ],
    practice: [
      'When you criticise an institution, try describing a concrete alternative, and then look for its flaws as hard as you looked for the original’s.',
      'Decide in advance which of your commitments you would not give up under pressure, and why.',
      'Keep a small space for reflection or prayer apart from your work, especially when your job is demanding.',
    ],
    facts: [
      'The phrase “a man for all seasons” was applied to More by the writer Robert Whittington in 1520. It later became the title of Robert Bolt’s 1960 play about him.',
      'Utopia was written in Latin and first printed in Louvain in 1516. The first English translation, by Ralph Robinson, did not appear until 1551.',
      'The painter Hans Holbein the Younger drew and painted More and his family in the 1520s, and his 1527 portrait of More is one of the best-known images of the period.',
      'More’s daughter Margaret Roper was one of the best-educated women in England, and she reportedly visited him in the Tower and, by tradition, later recovered his head.',
      'The usual account of his last words, that he was “the king’s good servant, but God’s first”, comes from reports written after his death, so its exact wording is uncertain.',
      'He was declared the patron saint of statesmen and politicians by Pope John Paul II in 2000.',
    ],
    myths: [
      { myth: 'More was a simple hero of conscience and tolerance.', reality: 'He was a man of integrity who died for his beliefs, but he also wrote fiercely against Protestant writers such as William Tyndale and supported the burning of heretics. Several people, usually counted as six, were burned for heresy during his time as Lord Chancellor. He denied the claims of his enemies that he tortured prisoners, and historians have not found independent proof for them. A fair picture includes both his courage and his part in persecution.' },
      { myth: 'Utopia is More’s own political programme.', reality: 'The book is a dialogue with ironic touches, and More appears in it as a character who doubts Hythloday’s ideas. Scholars disagree about how far it reflects his real opinions.' },
    ],
    works: [
      { title: 'Utopia (1516)', note: 'His best-known book, a Latin satire in two parts about an ideal island.' },
      { title: 'History of King Richard III', note: 'An unfinished work, written in the 1510s, that shaped the image of Richard as a tyrant, including Shakespeare’s.' },
      { title: 'Dialogue Concerning Heresies (1529) and Confutation of Tyndale’s Answer (1532)', note: 'Polemics against Protestant writings.' },
      { title: 'A Dialogue of Comfort against Tribulation (written 1534)', note: 'A reflection on facing suffering, written in the Tower.' },
      { title: 'William Roper, Life of Sir Thomas More', note: 'An early biography by his son-in-law, valuable but admiring.' },
    ],
    legacy: [
      'Utopia gave the world a word and a genre. Later “utopias” and “dystopias” in literature, from Bacon’s New Atlantis to the twentieth century’s dark satires, all respond in some way to More’s book, and the question it raises, whether a perfect society is possible or even desirable, is still discussed.',
      'More’s death made him a symbol of conscience against state power. The Catholic Church canonised him in 1935, and the Church of England remembers him as a reformation martyr, while his reputation among historians remains mixed because of his role in the heresy trials. Few people have been both celebrated and criticised so persistently, and that is part of what makes him worth reading.',
    ],
  },
  {
    slug: 'michel-de-montaigne',
    order: 1533,
    dates: '1533 – 1592',
    place: 'Château de Montaigne, near Bordeaux, France',
    era: 'Early Modern',
    tradition: 'Renaissance skepticism',
    tagline: 'The inventor of the personal essay, who turned the study of one ordinary mind, his own, into a way of understanding everyone.',
    who: [
      'Michel Eyquem de Montaigne was born on 28 February 1533 at the family estate near Bordeaux, in south-west France. His father, Pierre Eyquem, had unusual ideas about teaching: the boy was reportedly raised with a German tutor who spoke only Latin to him, so that Latin was in effect his first language. He then studied at the Collège de Guyenne in Bordeaux, and he later became a magistrate, serving in the Parlement of Bordeaux from 1557.',
      'His closest friend was the writer Étienne de La Boétie, whom he met in the late 1550s. La Boétie died in 1563, and Montaigne mourned him for the rest of his life. After the death of his own father in 1568 he inherited the estate, and in 1571 he withdrew from public duties to a tower of the château, where he kept his library and began to write. The result was the Essais, a word that means “attempts” or “trials”.',
      'The first edition appeared in 1580, and he travelled through Germany, Switzerland and Italy soon after, partly to seek relief from kidney stones. While he was away he was elected mayor of Bordeaux, and he served from 1581 to 1585, a hard period in the middle of France’s religious wars. He kept revising the Essays until the end, adding a third book in 1588. He died at the château on 13 September 1592.',
    ],
    context: [
      'France in Montaigne’s lifetime was torn by civil wars between Catholics and Protestants, which began in 1562 and, with pauses, continued for decades. Neighbours turned on each other, and atrocities such as the St Bartholomew’s Day massacre of 1572 were fresh memories. Montaigne, a Catholic who remained loyal to the crown, was a moderate trying to keep the peace and he distrusted fanaticism of all kinds.',
      'The sixteenth century also brought a flood of new information: voyages to the Americas, rediscovered ancient writings and religious controversies that disputed every certainty. Montaigne read the ancient skeptics, whose works had recently been printed again, and he used them to reflect on the limits of human knowledge.',
    ],
    ideas: [
      { title: 'The self as the subject', text: 'Montaigne wrote about himself: his tastes, his illnesses, his habits, his moods. In the preface he says he is himself the matter of his book. He did not do this out of vanity, but because he thought that a careful look at one human being shows what all humans are like. The result is the first major work of self-portrait in modern European literature.' },
      { title: 'What do I know?', text: 'His motto, “Que sçay-je?” (“What do I know?”), reflects the skeptical tradition that doubts our claims to certain knowledge. In the long essay “Apology for Raymond Sebond” he questions human reason, the superiority of humans over animals, and the confidence of theologians. Doubt was not a way to give up thinking, but a reason for modesty and open-mindedness.' },
      { title: 'Custom shapes belief', text: 'In essays such as “Of Cannibals” he reflects on the people of Brazil, as reported by travellers, and argues that we tend to call “barbarous” whatever is unfamiliar. He points out that Europeans do cruel things themselves, such as torture and burning people alive for belief. The essay is an early example of looking at one’s own culture from outside.' },
      { title: 'Learning to live and to die', text: 'In an early essay he says that “to philosophize is to learn to die”, taking the idea from the ancient Stoics. Over time his view changed, and in the last book he argues that the point is to live well and naturally, and to accept the body, pleasure and ordinary life as parts of wisdom, without trying to be an angel.' },
      { title: 'Friendship and tolerance', text: 'His essay on friendship, inspired by La Boétie, is one of the most moving things he wrote, with the famous explanation of their bond, “because it was he, because it was I”. He also condemns cruelty as the worst of vices and speaks against torture and against witch trials, arguing that it puts a high price on one’s guesses to burn someone alive for them.' },
    ],
    principles: [
      'Be honest about your own limits, and do not claim certainty you lack.',
      'Do not assume your own customs are the only natural ones.',
      'Judge cruelty harshly, whoever commits it.',
      'Accept ordinary life, body and pleasure included, as part of wisdom.',
      'Think of your thoughts as attempts, to be tested and revised.',
    ],
    practice: [
      'Write regularly about a single experience or opinion of yours and see what it looks like once it is on the page, then revise it later.',
      'When you meet a strange custom, ask what makes it seem strange and how it would look to someone who grew up with it.',
      'When you are certain, look for one strong argument against your view before you speak.',
    ],
    facts: [
      'His Essays were first printed in Bordeaux in 1580, and Montaigne added thousands of passages in later editions. Scholars label the layers of text A, B and C, for the 1580, 1588 and later additions.',
      'He had a medal struck with his motto and a balance in 1576, and he had sayings from ancient authors inscribed on the ceiling beams of his library.',
      'His posthumous 1595 edition was prepared by Marie de Gournay, a young admirer whom he called his “adopted daughter”.',
      'John Florio’s English translation of 1603 was read by Shakespeare, and the speech of Gonzalo in The Tempest echoes “Of Cannibals”.',
      'He wrote a journal of his trip to Italy in 1580–81, which was not published until 1774.',
      'In 1676 the Catholic Church’s Index of Prohibited Books included the Essays, although he had died a loyal Catholic.',
    ],
    myths: [
      { myth: 'Montaigne was a lazy gentleman who just wrote down his thoughts.', reality: 'He rewrote and expanded the Essays over twenty years, and his writing is full of ancient quotations and careful argument. He was also a magistrate and mayor and he acted as a go-between in the religious wars.' },
      { myth: 'His skepticism means he believed in nothing.', reality: 'He doubted human certainty, but he remained a Catholic, valued tradition and friendship and held firm moral views, especially against cruelty. His doubt was a form of humility, not nihilism.' },
    ],
    works: [
      { title: 'Essays (Essais), 1580–1595', note: 'Three books of reflections on subjects from friendship and death to cannibals, coaches, thumbs and experience.' },
      { title: '“Apology for Raymond Sebond”', note: 'The longest essay, a classic statement of Renaissance skepticism.' },
      { title: '“Of Cannibals” and “Of Cruelty”', note: 'Two essays on cultural difference and the evil of cruelty.' },
      { title: '“Of Experience”', note: 'The final essay, a defence of ordinary, embodied, natural life.' },
      { title: 'Journal de voyage', note: 'His travel diary of 1580–81, published long after his death.' },
    ],
    legacy: [
      'Montaigne created a new literary form, the essay, and nearly every essayist since has worked in his shadow. Francis Bacon borrowed the title for his own short pieces, and writers from Pascal and Emerson to Virginia Woolf and modern memoirists have drawn on his example.',
      'His skepticism and respect for human diversity helped shape later thinkers such as Descartes and Pascal, and later the philosophers of the Enlightenment. Readers still find him disarmingly modern because he treats his subject, an ordinary person confronting life, death and doubt, as worthy of serious attention.',
    ],
  },
  {
    slug: 'giordano-bruno',
    order: 1548,
    dates: '1548 – 1600',
    place: 'Nola near Naples, then across Europe, and Rome',
    era: 'Early Modern',
    tradition: 'Renaissance philosophy',
    tagline: 'A restless Dominican friar who imagined an infinite universe of countless worlds, and was burned in Rome after an eight-year trial.',
    who: [
      'Giordano Bruno was born in 1548 in Nola, near Naples, and baptised Filippo. He joined the Dominican order at the convent of San Domenico Maggiore in Naples in the 1560s, taking the name Giordano, and he was ordained a priest in 1572. He trained in scholastic theology but read widely beyond it, and he was soon suspected of heterodox views. Around 1576 he left Naples, and he left the order, ahead of an investigation.',
      'For the next sixteen years he wandered: Geneva, Toulouse, Paris, London, Oxford, Wittenberg, Prague, Helmstedt and Frankfurt. He lectured, published books and sought patrons, but his sharp tongue and unorthodox opinions got him into trouble with Calvinists and Lutherans as well as Catholics. In France he enjoyed the support of King Henry III. In England, from 1583 to 1585, he lived at the French embassy and wrote his most famous Italian dialogues.',
      'In 1591 he accepted an invitation from a Venetian nobleman, Giovanni Mocenigo, to teach him, and the following year Mocenigo denounced him to the Venetian Inquisition. He was arrested in May 1592 and sent to Rome in 1593, where he was held and questioned for years, so that the proceedings against him lasted about eight years in all. Under the cardinals of the Roman Inquisition, including Robert Bellarmine, he was asked to recant a list of propositions. He refused, was sentenced in February 1600 and was burned at the stake in the Campo de’ Fiori on 17 February 1600.',
    ],
    context: [
      'Bruno’s world had been shaken by Copernicus, who published in 1543 a theory that the Earth moves around the Sun. Few astronomers accepted it as physically true, and the telescope was not yet invented, so every argument was philosophical. The Reformation had also divided Christians, and the Catholic Church, responding with the Counter-Reformation, was strict about doctrine and suspicious of independent thinkers.',
      'Renaissance culture also revived older traditions: Platonism, the Hermetic writings believed to hold ancient Egyptian wisdom, and the memory arts, which used mental images to store knowledge. Bruno mixed all these with the new astronomy and the ancient atomists whom he found in Lucretius. His thought can look to us like a blend of science, magic and philosophy, and it is best understood in that setting.',
    ],
    ideas: [
      { title: 'An infinite universe', text: 'In On the Infinite Universe and Worlds (1584) Bruno argued that the universe has no edge and no centre, and that the stars are distant suns, probably with their own planets and possibly inhabited. His reasoning was philosophical, not observational: an infinite God, he thought, would produce an infinite creation, not a limited one. The idea was bold, and it anticipated later cosmology, though he reached it without evidence.' },
      { title: 'God in all things', text: 'Bruno taught that the divine is present in the world, and that nature is alive and full of purpose. This sits uneasily with the traditional view of a God separate from creation, and critics saw it as pantheism. Scholars still debate exactly how to describe his view, which draws on Neoplatonism, Hermetic writings and the philosopher Nicholas of Cusa.' },
      { title: 'Copernicus, and beyond', text: 'Bruno was one of the earliest thinkers to defend the Earth’s motion in public, as in The Ash Wednesday Supper (1584). He also went further than Copernicus, who still pictured a finite universe closed by a sphere of fixed stars. Bruno removed that sphere altogether.' },
      { title: 'The art of memory', text: 'Much of his early reputation rested on memory techniques, taught in books such as On the Shadows of Ideas (1582). He believed that organising images in the mind reflected the order of the universe, so that the art of memory was also a way of thinking. Historians such as Frances Yates helped revive interest in this side of him.' },
      { title: 'Heroic love of truth', text: 'In On the Heroic Frenzies (1585) Bruno describes the philosopher as a lover pursuing a truth that can never be fully possessed. The pursuit itself, not reaching the goal, makes the mind greater. The book expresses his own restless temperament, as well as a view of the intellectual life.' },
    ],
    principles: [
      'Do not assume that the world is as small as it looks from here.',
      'Follow an idea to its logical end, even when it unsettles tradition.',
      'Treat knowledge as a lifelong pursuit, not a possession.',
      'Look for the unity behind the variety of things.',
      'Be ready to pay the price of independent thought, and be careful about what you provoke.',
    ],
    practice: [
      'Try thinking about a problem at a much larger scale of space or time, and see which of your worries look smaller.',
      'Build a simple memory palace: link ideas you want to remember to places you know well.',
      'When a new idea unsettles you, spend a little time imagining it is true, and ask what follows.',
    ],
    facts: [
      'Bruno took the name Giordano from his tutor in the Dominican order, Giordano Crispo, according to some accounts.',
      'He wrote a comedy, Il Candelaio (1582), and a number of Italian dialogues in lively, sometimes abrasive prose, as well as Latin poems.',
      'The telescope was first used for astronomy around 1609, nine years after his death, so he did not base any of his claims on observation.',
      'Most records of his Roman trial are lost, so historians work from a summary and from documents of the earlier Venetian proceedings.',
      'A statue of Bruno, put up in 1889, stands at the Campo de’ Fiori in Rome, on the site where he was burned.',
      'In 2000 a senior Vatican official expressed regret for the methods used against him, though the Church has not reversed the verdict on his teaching.',
    ],
    myths: [
      { myth: 'Bruno was a martyr of science, burned for defending Copernicus.', reality: 'The surviving evidence suggests that the charges were mainly theological, including doubts about the Trinity, Christ and the soul, plus his views on many worlds. His cosmology was part of the case but not the whole. He was a philosopher with mystical and magical interests, not a scientist in the modern sense. The trial was still an act of severe persecution.' },
      { myth: 'He proved that the stars are suns with planets.', reality: 'He proposed it as a philosophical conclusion with no observations to back it up. It turned out to be right in outline, but the way he reached it was not scientific.' },
    ],
    works: [
      { title: 'De umbris idearum (On the Shadows of Ideas, 1582)', note: 'A book on the art of memory and the structure of reality.' },
      { title: 'La cena de le ceneri (The Ash Wednesday Supper, 1584)', note: 'A dialogue defending the motion of the Earth, set at a supper in London.' },
      { title: 'De la causa, principio et uno (1584) and De l’infinito, universo et mondi (1584)', note: 'His main philosophical dialogues on matter, the One and the infinite universe.' },
      { title: 'Spaccio de la bestia trionfante (1584) and De gli eroici furori (1585)', note: 'Dialogues on morality and on the philosopher’s quest.' },
      { title: 'Latin poems: De triplici minimo, De monade, De immenso (1591)', note: 'Published in Frankfurt, developing his atomism and cosmology.' },
    ],
    legacy: [
      'In the nineteenth century, with the rise of national unity in Italy and a struggle against clerical power, Bruno became a symbol of free thought, and the monument in Rome was erected in that spirit. Later scholars, notably Frances Yates, stressed his Hermetic and magical side, and more recent work stresses his serious philosophy.',
      'His idea of an infinite, centreless universe was later taken for granted in modern cosmology, and later philosophers of divine nature, such as Spinoza, have often been compared with him, though how far he influenced them is debated. Whatever one decides about the details, he has remained a figure that both science and religion keep returning to, as a warning about the cost of enforcing orthodoxy.',
    ],
  },
  {
    slug: 'francis-bacon',
    order: 1561,
    dates: '1561 – 1626',
    place: 'London, England',
    era: 'Early Modern',
    tradition: 'Empiricism',
    tagline: 'A lawyer-statesman who argued that nature should be studied by patient experiment, and who fell from the highest legal office in England in a corruption scandal.',
    who: [
      'Francis Bacon was born on 22 January 1561 at York House in London, the son of Sir Nicholas Bacon, Lord Keeper of the Great Seal under Elizabeth I. He entered Trinity College, Cambridge, at twelve and then Gray’s Inn to study law, and he spent part of his youth in France. His father died in 1579 leaving him little money, so he had to make his own way. He entered Parliament in 1581 and served in it for most of the next forty years.',
      'His rise was slow under Elizabeth and faster under James I, who knighted him in 1603. He became Solicitor General in 1607, Attorney General in 1613, Lord Keeper in 1617 and Lord Chancellor in 1618, with the title of Baron Verulam, and in 1621 he became Viscount St Alban. He earlier prosecuted the Earl of Essex, a former patron, in 1601, an act for which he has often been criticised.',
      'In 1621 Parliament investigated complaints that he had accepted gifts from people with cases before his court. Bacon admitted taking gifts, though he said they had not affected his judgments. He was convicted, fined £40,000 and sent briefly to the Tower of London, and he was barred from office and Parliament. The king soon released him and reduced the penalties. He spent his last years writing, and died on 9 April 1626 at Highgate, near London.',
    ],
    context: [
      'In Bacon’s youth, university teaching still rested mainly on Aristotle and the medieval commentators. At the same time, new discoveries were unsettling the old picture: voyages to the Americas, the printing press, the Copernican astronomy and the instruments of craftsmen and navigators. Bacon was convinced that the old learning was producing arguments and not results.',
      'He was also writing at the dawn of the Stuart period, in a court that valued rhetoric and favour, which shaped both his ambitions and his failures. He wanted to reorganise human knowledge and persuaded himself, and tried to persuade the king, that this was a public service. Whether he spent too much time on politics or too little on science is a question his biographers still debate.',
    ],
    ideas: [
      { title: 'Knowledge for the benefit of humankind', text: 'Bacon argued that the true purpose of knowledge is to improve human life, and not to win debates or to display learning. “Knowledge itself is power”, he wrote in an early work, and in Novum Organum he states that nature, to be commanded, must first be obeyed. By that he meant that we gain power over nature only by learning its laws.' },
      { title: 'A new method: induction', text: 'Instead of starting from general principles and deducing results, as scholastic philosophy often did, Bacon wanted researchers to collect careful observations and experiments, arrange them in tables of cases where a quality is present, absent or varies, and work gradually toward general laws. He compared the best scientist to a bee, which gathers material and turns it into something new, unlike the ant, who merely collects, and the spider, who spins everything from itself.' },
      { title: 'The idols of the mind', text: 'Bacon described four kinds of habitual error that distort our thinking, which he called idols. Idols of the Tribe are weaknesses of human nature in general, such as seeing more order than exists. Idols of the Cave are the quirks of each person’s upbringing. Idols of the Marketplace arise from careless or misleading words. Idols of the Theatre come from false systems of thought that we absorb from tradition. The list is an early catalogue of what we now call cognitive biases.' },
      { title: 'Science as a shared, organised effort', text: 'In the unfinished fable New Atlantis (published in 1626) he imagined an island with an institution called Salomon’s House, where teams of researchers collect data, run experiments and apply results for the public good. This picture of science as a collective, state-supported enterprise influenced the founders of the Royal Society in the 1660s.' },
      { title: 'Reform of learning and law', text: 'Bacon surveyed all fields of knowledge in The Advancement of Learning (1605) and found many of them undeveloped. He called for new fields and for the systematic revision of English law. His great plan, the Great Instauration (Instauratio Magna), was meant to have six parts but was left incomplete.' },
    ],
    principles: [
      'Test ideas against experience instead of relying only on authority.',
      'Know your own biases, because they are the first obstacles to knowing anything.',
      'Be patient: collect many facts before drawing a general conclusion.',
      'Aim at knowledge that helps people.',
      'Look for the cases that contradict you, not only the ones that confirm you.',
    ],
    practice: [
      'When you form an opinion, deliberately look for evidence against it and weigh it fairly.',
      'Notice when a word is doing the work of an argument, and ask what exactly it refers to.',
      'Treat a belief as a hypothesis for a while, and ask what experience would count against it.',
    ],
    facts: [
      'His Essays began in 1597 with ten short pieces and grew to 58 in the final edition of 1625. In the essay “Of Studies” he says that some books should be tasted, others swallowed, and a few chewed and digested.',
      'He wrote in both English and Latin. He chose Latin for his major philosophical works, such as Novum Organum (1620), so that they would reach readers across Europe.',
      'The story that he died after stuffing a chicken with snow to test refrigeration comes from John Aubrey’s later account, which is second-hand. He did die of a chest illness in the early spring of 1626.',
      'A theory dating from the nineteenth century claims that Bacon wrote Shakespeare’s plays. Historians of literature do not take it seriously.',
      'In 1606 he married Alice Barnham, the daughter of a London alderman. They had no children.',
    ],
    myths: [
      { myth: 'Bacon invented the scientific method.', reality: 'Experiment and observation had earlier champions, among them medieval scholars and Muslim scientists such as Ibn al-Haytham. Bacon’s achievement was to argue forcefully and publicly for a reformed programme of inquiry. He also underrated the role of mathematics and bold hypotheses, and he was unpersuaded by Copernicus.' },
      { myth: 'He was simply a corrupt official.', reality: 'He admitted to accepting gifts, and the practice of gift-taking by judges was common in his time. Some historians think he was also a convenient target in a political struggle. He admitted his fault, and his conviction ended his public career, but historians differ on how much blame he deserves.' },
    ],
    works: [
      { title: 'Essays (1597, enlarged 1612 and 1625)', note: 'Short, pointed pieces on topics such as truth, studies, friendship and ambition.' },
      { title: 'The Advancement of Learning (1605)', note: 'A survey of human knowledge in English, with proposals to extend it.' },
      { title: 'Novum Organum (1620)', note: 'The “new instrument”, his statement of a new method of inquiry, containing the doctrine of the idols.' },
      { title: 'History of the Reign of King Henry VII (1622)', note: 'A prose history that Bacon wrote after his fall.' },
      { title: 'New Atlantis (published 1626)', note: 'An unfinished fable of an ideal scientific society.' },
    ],
    legacy: [
      'Bacon’s vision of organised, practical, collaborative science was taken up by the early Royal Society, founded in 1660, whose members regarded him as an inspiration. In the Enlightenment, the French Encyclopédie named him among its chief intellectual forebears, and his influence on the modern idea of research is wide.',
      'His record also shows the gap between a thinker’s ideas and his conduct. The man who warned against the distortions of the mind failed to avoid those of ambition. Modern historians see him less as the single founder of the scientific method than as one of its most effective advocates, who helped persuade educated Europe that careful study of nature could improve human life.',
    ],
  },
]
