import type { Profile } from './types'

export const ROMAN: Profile[] = [
  {
    slug: 'cicero',
    order: -106,
    dates: '106 – 43 BC',
    place: 'Arpinum, then Rome',
    era: 'Ancient',
    tradition: 'Roman Republic',
    tagline: 'Rome’s greatest orator, who in his last years turned Greek philosophy into Latin and defended the Republic with his pen.',
    who: [
      'Marcus Tullius Cicero was born on 3 January 106 BC in Arpinum, a hill town south-east of Rome. His family was wealthy and respectable but had no record of high office, so he was what the Romans called a “new man”, the first of his line to reach the consulship. He studied law and rhetoric in Rome, then travelled to Athens and Rhodes, where he heard the Academic philosopher Philo of Larissa, Antiochus of Ascalon and the rhetorician Apollonius Molon. These years gave him both his training as a speaker and his lifelong interest in Greek thought.',
      'His career was built in the courts. In 70 BC he won fame by prosecuting Gaius Verres, a former governor of Sicily accused of plundering the province, and he rose steadily through the offices of quaestor, aedile and praetor to the consulship in 63 BC. As consul he uncovered and put down the conspiracy of Catiline, a ruined aristocrat accused of plotting to seize power. Several conspirators were executed on the Senate’s decision without a formal trial, and a political enemy, Clodius, later used this against Cicero to drive him into exile in 58 BC. He was recalled in 57 BC, but never regained the influence he had enjoyed as consul. He governed Cilicia, in southern Anatolia, in 51–50 BC.',
      'In the civil war between Pompey and Julius Caesar he reluctantly chose Pompey, and after Pompey’s defeat he was pardoned by Caesar. Shut out of real politics, and grieving the death of his daughter Tullia in 45 BC, he wrote at great speed through 45–44 BC, producing most of his philosophical works. After Caesar’s assassination in March 44 BC he returned to public life and attacked Mark Antony in a series of speeches called the Philippics. When Antony, Octavian and Lepidus joined forces and published lists of enemies to be killed, Cicero was on them. He was caught and killed near Formiae on 7 December 43 BC, and his head and hands were displayed on the speakers’ platform in the Forum.',
    ],
    context: [
      'Cicero lived through the long collapse of the Roman Republic. Rome had grown from a city into a Mediterranean empire, and the old system of annual magistrates and a ruling Senate was strained by ambitious generals with private armies, by quarrels over land and debt, and by street violence. He believed that the Republic’s mixed constitution, with its blend of magistrates, Senate and people, was the best government ever devised, and he spent his life trying to keep it alive.',
      'By Cicero’s time educated Romans admired Greek culture but wrote their own books mostly about law, history and speech. Philosophy was usually read in Greek. Cicero set out to change that, and he explained Greek schools to Roman readers in Latin, often as conversations between well-known Romans. In doing so he had to invent or adapt Latin words for abstract ideas, and he is credited with giving Latin much of its philosophical vocabulary, including the word qualitas, “quality”.',
    ],
    ideas: [
      { title: 'Natural law', text: 'In his work On the Republic, Cicero writes that true law is right reason in agreement with nature, the same for all people and in all times. Human rules that contradict it have no real claim on us, whatever the Senate or the people decree. He drew on Stoic thought here, and the idea that there is a standard of justice above any particular state became very influential in later legal and political thinking.' },
      { title: 'Duty and the honourable', text: 'On Duties, written in 44 BC for his son Marcus, is a guide to practical conduct. Following the Stoic Panaetius in the first two books, Cicero argues that what is morally right and what is truly useful can never genuinely conflict, and that apparent clashes come from misjudging one of them. He sets out obligations to family, friends, country and humanity at large.' },
      { title: 'Probability instead of certainty', text: 'In philosophy Cicero followed the Academic sceptics, who held that certain knowledge is very hard or impossible to obtain. This did not mean giving up. We should accept what seems most probable, act on it, and stay ready to revise it. He was fair to rival schools, and presented the Stoics, Epicureans and others in dialogue form so that readers could weigh them against one another.' },
      { title: 'Friendship as a good of its own', text: 'In On Friendship, Cicero has an older Roman, Laelius, speak about his lost friend Scipio. True friendship, he argues, rests on shared respect for virtue and cannot be built on mere usefulness. Friends should ask only what is honourable and refuse to do wrong for each other.' },
      { title: 'Facing age and death', text: 'In On Old Age, the elder Cato defends later life: it frees us from some passions, rewards a well-spent life, and need not mean the loss of the mind. Death, the speaker says, is either the end of feeling or a change of home for the soul, and neither is a thing to dread. Cicero’s Tusculan Disputations take up the same questions about pain, grief and death more fully.' },
    ],
    principles: [
      'Public service is a duty, and talent should be used for the common good.',
      'What is truly useful is never in conflict with what is honourable.',
      'Hold opinions in proportion to the evidence, and be willing to change them.',
      'Choose friends for their character, and keep faith with them.',
      'Use words with care. Clear speech and clear thought belong together.',
    ],
    practice: [
      'Before an important decision, ask whether the action is honourable as well as advantageous, and look hard at any case where the two seem to part.',
      'Read the best argument against your own view, stated fairly, before you defend your position.',
      'Write to people you care about regularly. Cicero’s letters show how friendship is kept alive by attention.',
    ],
    facts: [
      'More than 900 letters to and from Cicero survive, among them his exchanges with his friend Atticus, which give an unusually close view of Roman political and private life.',
      'Petrarch found a manuscript of Cicero’s letters to Atticus and others in the cathedral library at Verona in 1345, a find often counted among the sparks of Renaissance humanism.',
      '“O tempora, o mores!” (“What times, what customs!”) comes from his first speech against Catiline in 63 BC.',
      'He wrote that there is nothing so absurd that some philosopher has not said it, a line from his work On Divination.',
      'His lost dialogue Hortensius, an encouragement to study philosophy, made a deep impression on the young Augustine, who describes it in his Confessions.',
      'Dio and other later writers report that after his death Antony’s wife Fulvia pierced his tongue with a hairpin. The story is not reliable, but it shows how bitter the quarrel had become.',
    ],
    myths: [
      { myth: 'Cicero was a Stoic.', reality: 'He admired Stoic ethics and borrowed from them, but he considered himself an Academic sceptic. He criticised Stoic and Epicurean certainty alike, and his own view was that we can only claim what is probable.' },
      { myth: 'Cicero was a flawless defender of Roman liberty.', reality: 'He was a sincere republican, but a vain one, and he often boasted of his consulship. The execution of Catiline’s associates without trial is still debated, and many historians see it as a breach of the very laws he claimed to defend. His admirers and critics have argued about it since antiquity.' },
    ],
    works: [
      { title: 'On the Republic and On the Laws', note: 'Written in the 50s BC. They set out his picture of the ideal Roman state and his ideas about natural law, and survive only in part.' },
      { title: 'On Ends, Tusculan Disputations, On the Nature of the Gods, On Divination, On Fate', note: 'His main philosophical dialogues from 45–44 BC, presenting and weighing the views of Epicureans, Stoics and Academics.' },
      { title: 'On Duties, On Friendship, On Old Age', note: 'His best-loved practical works, the first addressed to his son and the other two spoken by older Romans.' },
      { title: 'Speeches, including the Verrines, the Catilinarians and the Philippics', note: 'The orations that made his name, and the main sources for his politics.' },
      { title: 'Letters', note: 'To Atticus, to his brother Quintus, to Brutus and to many friends. They show the unguarded Cicero, anxious, funny, vain and warm.' },
    ],
    legacy: [
      'For centuries Cicero’s Latin was the model of good prose. Medieval and Renaissance schools taught from his writings, Augustine and many other Christian thinkers learned from him, and the humanists of the Renaissance treated his style as the standard. David Hume modelled his Dialogues Concerning Natural Religion on Cicero’s dialogue On the Nature of the Gods.',
      'His thinking about natural law, about duties that bind rulers as well as citizens, and about a government balanced between different powers, shaped later political thought. Writers of the modern republics, such as John Adams, read him closely. Cicero was a man of his time, with the vanity and compromises that implies, but he gave the Western tradition a language for talking about law, duty and the common good.',
    ],
  },
  {
    slug: 'lucretius',
    order: -99,
    dates: 'c. 99 – c. 55 BC',
    place: 'Probably Rome',
    era: 'Ancient',
    tradition: 'Epicureanism',
    tagline: 'A Roman poet who used verse to explain a universe of atoms and to argue that death is nothing to fear.',
    who: [
      'Titus Lucretius Carus is known almost entirely through a single poem, De rerum natura, “On the Nature of Things”. Almost nothing certain is known about his life. He seems to have lived in the last decades of the Roman Republic, probably dying in the mid-50s BC, and he was clearly well educated. His poem is dedicated to a Roman aristocrat, Gaius Memmius, who was probably his patron or friend. Beyond that, scholars rely on the poem itself and on a few later remarks.',
      'The best-known biographical claim comes from Saint Jerome, who wrote four centuries later that Lucretius was driven mad by a love potion, wrote his poem in the intervals of madness, and killed himself at the age of 43 or 44. Jerome adds that Cicero edited the work. Modern scholars treat this with great suspicion: Jerome was a Christian writer with little sympathy for an Epicurean, and the story may reflect hostility rather than record. A letter from Cicero to his brother Quintus in 54 BC does mention the poem, saying it shows flashes of genius as well as great skill, so Cicero at least knew of it. The poem also appears to be unfinished, which fits with an author who died before final revision.',
      'De rerum natura is about 7,400 lines of Latin verse in six books. It aims to teach the philosophy of Epicurus, the Greek thinker who died in 270 BC, to a Roman audience. Lucretius speaks of Epicurus with extraordinary reverence, calling him a god in the sense that he found a way of living and freed human beings from fear. The poem’s aim is therapeutic as much as scientific: Lucretius explains the world in order to free his reader from superstition and from the fear of death.',
    ],
    context: [
      'Lucretius wrote during the violent last years of the Republic, when civil strife and ambition were destroying the old order. Epicureanism taught that a calm life, with limited desires, good friends and no fear of gods or death, was the best way to live, and it often advised staying out of public life. This message had a particular appeal for Romans who felt overwhelmed by the politics of the age, even though many of the elite scorned it as unmanly or irreligious.',
      'Epicurus had written in Greek, and Lucretius complains in his poem that the poverty of the Latin language makes it hard to express Greek ideas. He chose verse because, as he says, poetry can make a hard subject attractive, in the same way that a physician smears honey on the rim of a cup to help a child swallow bitter medicine. This choice helped turn a technical philosophy into one of the great poems of the Latin language.',
    ],
    ideas: [
      { title: 'Atoms and void', text: 'Everything is made of tiny, indestructible particles moving in empty space. Compound things, such as stones, animals and stars, are temporary arrangements of atoms, and they come apart again. Lucretius argues that nothing comes from nothing and nothing is destroyed into nothing, and he offers everyday evidence, such as the way wind, though unseen, bends trees, and how a ring on a finger wears away without anyone seeing the loss.' },
      { title: 'The swerve', text: 'In Book II Lucretius says that atoms do not just fall in straight lines but sometimes swerve by a tiny, unpredictable amount. Without this swerve, he argues, atoms would never collide, and no world would form. He also uses it to defend free will, arguing that the mind is not simply a link in a chain of fixed causes.' },
      { title: 'Religion and fear', text: 'Lucretius tells the story of Iphigenia, sacrificed by her father at the start of the Trojan expedition, and concludes that religion has been able to persuade people to do great wrong. Epicureans did not deny that gods exist. They held that the gods live in perfect peace, far from our world, and take no interest in our affairs, so there is nothing to fear from them and nothing to bargain for.' },
      { title: 'Death is nothing to us', text: 'Book III argues that the soul is made of atoms and dies with the body, so we cannot experience our own death. Lucretius then offers a famous symmetry argument: the endless time before we were born did not trouble us, so the endless time after we die should not either. Fear of death, he says, drives much of human greed and ambition, and understanding the truth about it brings peace.' },
      { title: 'A natural history of the world', text: 'In Book V Lucretius describes a world that forms by chance from atoms, with no designer. Life arises from the earth, and creatures that cannot feed or reproduce die out. He describes the slow growth of human society, from early humans without laws or fire to language, farming, the arts and kingship. The details are guesswork, but the picture of a world explained without purposes anticipates later natural science.' },
    ],
    principles: [
      'Understand how things work so that you do not have to fear them.',
      'Limit your desires to what is natural and necessary, and be content.',
      'Do not let fear of death shape the way you live.',
      'Do not let superstition or panic be used to make you do harm.',
      'Seek the company of friends and the quiet of a mind that is not at war with itself.',
    ],
    practice: [
      'When a fear takes hold, ask what exactly you are afraid of and whether there is anything there to experience, and try the symmetry argument: did the time before your birth hurt?',
      'Distinguish desires that are natural and necessary, such as food, shelter and friends, from those that are endless, such as fame and wealth, and notice how much of your striving belongs to the second kind.',
      'Look for a natural explanation before settling for a frightening one, and get comfortable saying that you do not yet know.',
    ],
    facts: [
      'The six books move from the basic principles of atoms and void, through atomic motion and the formation of worlds, the nature of the soul and death, perception and desire, the history of the world and civilisation, to weather, earthquakes and disease. The last passage of the poem is a vivid description of the plague at Athens.',
      'Lucretius compares atoms to the letters of the alphabet: the same few elements, arranged differently, make an endless variety of words and things.',
      'He illustrates the constant motion of invisible atoms by the specks of dust that dance in a sunbeam. This is an analogy for atomic motion, not a description of what modern science calls Brownian motion.',
      'The poem was almost lost. In 1417 the Italian humanist Poggio Bracciolini found a manuscript in a German monastery and had it copied, and it began to circulate in the Renaissance. The story is told in Stephen Greenblatt’s popular book The Swerve (2011), though specialists have disputed some of its larger claims about the poem’s importance.',
      'Thomas Jefferson owned several copies and translations of Lucretius, and he once wrote that he considered himself an Epicurean.',
      'The poem’s famous image of a person on shore watching a storm at sea opens Book II. It has been much quoted, but Lucretius’s point is not about taking pleasure in others’ pain, but about the calm that comes from understanding.',
    ],
    myths: [
      { myth: 'Lucretius went mad and killed himself.', reality: 'The story comes from Jerome, writing about four hundred years after Lucretius’s death. No earlier source mentions it, and most scholars regard it as unreliable, possibly designed to discredit an Epicurean.' },
      { myth: 'Lucretius was an atheist who denied the gods.', reality: 'He followed Epicurus, who held that gods exist but are blessed and remote. What Lucretius attacked was superstition and the belief that gods interfere in human life, not the idea of divinity itself.' },
      { myth: 'Lucretius anticipated modern atomic physics and evolution.', reality: 'His atoms were philosophical hypotheses without experiments, and his ideas about the origin of life were speculation. The resemblance to modern science is striking in places, but he is better read as a thoughtful ancient philosopher than as a forerunner of Darwin or Dalton.' },
    ],
    works: [
      { title: 'De rerum natura (On the Nature of Things)', note: 'His only known work: a Latin poem in six books, probably unfinished at his death, setting out Epicurean physics and ethics.' },
      { title: 'Cicero, Letter to Quintus (54 BC)', note: 'A short remark about the poem, our best contemporary evidence that it existed and was read.' },
      { title: 'Jerome, Chronicle', note: 'The source of the story of madness and the claim that Cicero edited the poem. Late and doubtful.' },
      { title: 'Epicurus, Letter to Herodotus and Principal Doctrines', note: 'The Greek texts that Lucretius set out to explain, useful for comparison.' },
    ],
    legacy: [
      'Virgil, Horace and other Roman poets admired and echoed Lucretius, and the poem was read throughout the Roman Empire. Early Christian writers mostly rejected it, and for much of the Middle Ages it was almost forgotten. After its rediscovery in 1417 it influenced writers such as Montaigne, who quoted it extensively, and it became one of the main channels through which atomism returned to European thought. The philosopher Pierre Gassendi, in the seventeenth century, drew on Epicurus and Lucretius to defend a modern atomic view of nature.',
      'Whatever its scientific faults, the poem offers an argument that still speaks to ordinary readers: that much of human misery comes from fear, and that understanding the world can calm the mind. It remains one of the clearest and most beautiful expressions of the Epicurean attempt to live well without belief in divine punishment.',
    ],
  },
  {
    slug: 'seneca',
    order: -4,
    dates: 'c. 4 BC – 65 AD',
    place: 'Corduba (Córdoba, Spain), then Rome',
    era: 'Ancient',
    tradition: 'Stoicism',
    tagline: 'Playwright, statesman and adviser to an emperor, who wrote some of the most readable advice ever given on time, anger and facing misfortune.',
    who: [
      'Lucius Annaeus Seneca was born in Corduba, in the Roman province of Spain, around 4 BC, though the exact year is uncertain. His father, Seneca the Elder, was a well-known teacher of rhetoric. Seneca was brought to Rome as a child, and he studied rhetoric and philosophy there. He heard the Stoic Attalus and the teacher Sotion, and followed the lectures of Papirius Fabianus. He had poor health for much of his life, and writes of an illness he describes as asthma. His brother Gallio appears in the Acts of the Apostles as a Roman governor in Greece, and his nephew was the poet Lucan.',
      'Seneca made his name as an orator and entered the Senate. In 41 AD the emperor Claudius exiled him to Corsica, officially for an affair with Julia Livilla, the emperor’s niece. Many historians think the charge was a political one. He spent eight years there, writing consolations and essays, until Claudius’s wife Agrippina arranged for his recall in 49 AD and made him tutor to her young son Nero. When Nero became emperor in 54, at the age of sixteen, Seneca and the praetorian prefect Burrus were his chief advisers. Seneca wrote speeches for him, held the consulship in 56, and grew extremely rich.',
      'The partnership soured as Nero grew more wilful. Tacitus reports that Seneca and Burrus were implicated in the murder of Nero’s mother Agrippina in 59, and after Burrus died in 62, Seneca offered to give back his wealth and retire. Nero refused, but Seneca’s influence faded, and he spent his last years writing his best-known works. In 65 he was named, perhaps unfairly, in the Pisonian conspiracy against Nero, and the emperor ordered him to kill himself. Tacitus gives a long description of his death, in which Seneca, calm and still talking with his friends, opened his veins. When the blood flowed slowly he also took poison and, finally, a hot bath that suffocated him.',
    ],
    context: [
      'Seneca lived under the first Roman emperors: Tiberius, Caligula, Claudius and Nero. The Republic’s freedoms were gone, and the safety of the senatorial class depended on the mood of one man. Caligula, according to later reports, once considered having Seneca killed. Philosophers learned that careful words were necessary, and for a writer who held that virtue was the only real good, the court was a place of moral danger.',
      'Stoicism was a Greek school, founded in Athens around 300 BC by Zeno of Citium, which taught that virtue is the only true good and that emotions come from mistaken judgments. In Rome it had become a practical philosophy of duty and self-command, and many public men found it useful. Seneca was not a strict follower of any one master. He tells Lucilius that he treats the Stoics as guides rather than lords and happily borrows a good saying from Epicurus.',
    ],
    ideas: [
      { title: 'Time is the one thing we really own', text: 'In On the Shortness of Life, Seneca argues that life is long enough if we use it well. The problem is that we waste it on busyness, vanity and distraction, and then complain that it is short. He urges his reader to treat time like money, to guard it carefully and to give it to what matters, which for him means wisdom.' },
      { title: 'Imagine the worst in advance', text: 'Seneca recommends rehearsing misfortune: exile, illness, poverty and the loss of loved ones. Facing these possibilities in thought makes them less alarming if they arrive. The later name for this exercise is premeditatio malorum, “the rehearsal of evils”. He is careful to say that it is not pessimism, but a way to keep fortune from taking us by surprise.' },
      { title: 'Anger is a short madness', text: 'In On Anger, he cites those who call it a brief madness and argues that it is never useful. The first flash of feeling is involuntary, but the decision to act on it is ours. His advice is to delay, to look for the facts and to remember that most offences are small.' },
      { title: 'Wealth is an instrument, not a master', text: 'Seneca does not say the wise person must be poor. He argues that riches are acceptable if you are ready to lose them without distress. To train himself, he suggests setting aside a few days now and then to eat simply and wear rough clothes, to learn that poverty is not as frightening as it seems.' },
      { title: 'Philosophy is for daily life', text: 'His 124 surviving Letters to Lucilius are informal talks to a friend in his progress toward wisdom, covering friendship, crowds, grief, old age, slavery and death. Seneca stresses that learning has to be practised, not just admired, and he describes a habit he takes from another Stoic, Sextius: reviewing his day each evening, asking what faults he cured and what he still needs to work on.' },
    ],
    principles: [
      'Treat time as your most valuable possession, and spend it on purpose.',
      'Practise a little discomfort so that fortune holds fewer terrors.',
      'Before you act in anger, wait, and examine the facts.',
      'Look at each day’s events at night and ask honestly how you did.',
      'Treat others, including those with less power, as human beings with the same nature.',
    ],
    practice: [
      'Keep a short evening review: what went well, where did I go wrong, what will I change tomorrow?',
      'Once in a while, spend a day with plain food and little comfort, and notice how little you really needed.',
      'When something upsets you, wait a day, or at least an hour, before replying.',
    ],
    facts: [
      'Tacitus, who describes Seneca’s final hours, writes that his wife Pompeia Paulina also cut her wrists, but that Nero ordered her saved. She lived a few more years.',
      'The senator Suillius, a political enemy, asked in public how Seneca had gained three hundred million sesterces in four years of imperial favour. The figure is not confirmed, but the charge of hypocrisy about wealth has followed him ever since.',
      'He wrote the Apocolocyntosis (“The Pumpkinification”), a satire on the death and supposed divinisation of Claudius. Most scholars accept that he wrote it.',
      'Eight or nine tragedies survive under his name, including Medea, Phaedra and Thyestes. Scholars doubt that he wrote one or two of them, and no one knows whether they were staged or read aloud. They were widely imitated in the Renaissance, and Elizabethan translations of 1581 influenced English drama.',
      'In Letter 47 he writes that slaves are human beings who should be treated with kindness, a striking opinion in a society built on slavery, although he did not call for abolition.',
      'In his Natural Questions, a work on comets, earthquakes, thunder and other phenomena, he argues that nature, like moral life, is worth studying closely.',
    ],
    myths: [
      { myth: 'Seneca was a hypocrite who preached poverty and lived in luxury.', reality: 'The charge goes back to his own lifetime, and he was rich and a close servant of Nero. But he never claimed to be a perfect sage, he said he was still making progress, and he did not hold that wealth is evil in itself. Some historians think the accusations were exaggerated by his enemies. Fairness requires both facts: the criticisms have substance, and he was also thoughtful about them.' },
      { myth: 'He was a pure Stoic who followed the school’s doctrines to the letter.', reality: 'Seneca was an independent thinker, ready to quote Epicurus and to adapt Stoic ideas to Roman life. His work is often more about moral guidance than technical theory.' },
    ],
    works: [
      { title: 'Letters to Lucilius (Epistulae morales)', note: 'Written in his last years, 124 letters survive. They are the most personal and widely read of his works.' },
      { title: 'Dialogues (including On Anger, On the Shortness of Life, On Tranquillity of Mind, On the Happy Life)', note: 'Twelve essays and consolations. Their exact dates are uncertain, and several were written to named friends or relatives.' },
      { title: 'On Mercy (De clementia)', note: 'Addressed to the young Nero, urging a ruler to use power gently.' },
      { title: 'Natural Questions', note: 'A study of natural phenomena, linking science and ethics.' },
      { title: 'Tragedies', note: 'Verse dramas on Greek myths, full of rhetorical force and moral extremes, which became models for later European tragedy.' },
    ],
    legacy: [
      'In antiquity, Seneca was admired as a writer, and Christian writers such as Tertullian and Jerome respected his moral outlook, so much that a forged correspondence between Seneca and Saint Paul circulated in the Middle Ages. In the Renaissance, his essays and letters were popular models for writers such as Montaigne, and his tragedies helped shape the drama of Shakespeare’s generation.',
      'Today his letters are among the most accessible introductions to Stoic practice, read for what they say on time, anger, grief and fortune. Readers still argue about whether the man lived up to his words, and that debate is part of why his work remains interesting: it was written by someone who knew the distance between teaching and practice.',
    ],
  },
  {
    slug: 'epictetus',
    order: 50,
    dates: 'c. 50 – c. 135 AD',
    place: 'Hierapolis in Phrygia, Rome, then Nicopolis in Greece',
    era: 'Ancient',
    tradition: 'Stoicism',
    tagline: 'A former slave who taught that we are free as soon as we learn to govern our own judgments.',
    who: [
      'Epictetus was born around 50 AD in Hierapolis, in Phrygia, in what is now Turkey. “Epictetus” means “acquired” in Greek, a name that suggests a slave rather than a birth name. As a young man he was taken to Rome, where he belonged to Epaphroditus, a freedman who served as a secretary to the emperor Nero. With his master’s permission he attended lectures by the Stoic teacher Musonius Rufus, one of the leading philosophers of Rome.',
      'Epictetus was lame. Origen, writing in the third century, says that Epaphroditus twisted his leg and broke it, and that Epictetus calmly warned him it would happen. Another report says he was disabled from childhood. The sources disagree, and the story of the broken leg may be a legend that suits his later teaching. In his own lectures, he calls himself a lame old man. He was freed at some point, probably after Nero’s death in 68, and he began to teach philosophy in Rome.',
      'Around 93 AD the emperor Domitian banished philosophers from Rome, and Epictetus moved to Nicopolis, a city on the west coast of Greece. There he ran a school for young men, some of them intending public careers, and he lived there for the rest of his life, dying around 135. He wrote nothing. His pupil Arrian, who later became a Roman official and historian, wrote down his lectures, producing the Discourses, of which four of eight books survive, and a short handbook, the Enchiridion. Arrian says that he recorded the words as closely as he could.',
    ],
    context: [
      'Epictetus lived under Nero, Domitian and the emperors who followed. Slavery shaped the society he knew, and so did the fear of those in power. Several of the leading Stoics before him, among them Musonius Rufus, were banished or put to death for their independence, so he had seen what the powerful could do to a philosopher. His own master Epaphroditus is said to have been executed by Domitian around 95.',
      'His teaching belongs to the late Stoic tradition, which stressed ethics over logic and physics. He took from earlier Stoics the belief that virtue is the only good and that the universe is governed by a rational providence, and then focused on how to apply it in daily life. His school at Nicopolis was a place for training character, and he often said the student should leave the classroom changed, not just informed.',
    ],
    ideas: [
      { title: 'What is up to us', text: 'The Enchiridion opens with the central distinction. Some things are up to us: our opinions, choices, desires and aversions. Others are not: our bodies, property, reputation and the actions of other people. Peace comes from caring about the first group and treating the second as outside our power, to be accepted rather than demanded.' },
      { title: 'We are troubled by judgments', text: 'People, he says, are disturbed not by events but by the views they take of them. Death is not terrible in itself, or Socrates would have found it so. The terror lies in the judgment that it is terrible. Changing the judgment, which is within our power, changes the distress.' },
      { title: 'The faculty of choice', text: 'Epictetus calls our power of choice and moral purpose prohairesis. It is the one thing that cannot be forced by anyone. A tyrant can chain the leg, he says, but not the choice. This is where he locates freedom, and why he thinks a slave in chains may be freer than a master ruled by fear and greed.' },
      { title: 'Playing a role well', text: 'He compares life to a play in which we are given a part by someone else. We do not choose whether we are a lame slave, a king or a beggar, but we can choose to play the part well. Each of us also has several roles, as a child, parent, citizen and friend, and each brings duties.' },
      { title: 'Three disciplines', text: 'Later readers see in the Discourses three fields of training: desire and aversion, which means wanting only what is up to us; impulse to act, which means acting for the right reasons and toward others; and assent, which means testing each impression before we accept it. A famous practice is to meet a troubling impression with the words, “You are just an appearance, and not at all what you seem.”' },
    ],
    principles: [
      'Ask first: is this up to me or not?',
      'Remember that distress comes from my judgment of the event.',
      'Do not wish for things to go as you want, but want them to go as they do.',
      'Treat every role you hold, as friend, citizen, parent or colleague, as a duty to be done well.',
      'Philosophy is training: practise it daily, in small things.',
    ],
    practice: [
      'When something upsets you, write two lists: what is up to me here, and what is not. Act on the first list and let go of the second.',
      'Before you react to an impression, pause and say what it is, then ask whether it is really as bad as it seems.',
      'Imagine, as the Enchiridion suggests, that what you have is only lent: when something is taken, say “I gave it back” and not “I lost it”.',
    ],
    facts: [
      'A story told by the satirist Lucian says that a collector bought Epictetus’s clay lamp after his death for 3,000 drachmas, hoping to gain his wisdom by reading by its light. Lucian tells it to mock the buyer.',
      'The Roman writer Aulus Gellius attributes to Epictetus a short saying often rendered as “bear and forbear”, meaning to endure what comes and to abstain from what is wrong.',
      'Marcus Aurelius, in his Meditations, thanks his teacher Rusticus for lending him his own copy of Epictetus’s lectures.',
      'The word enchiridion in Greek means something that can be held in the hand. A dagger and a handbook could both carry that name.',
      'Admiral James Stockdale, a US Navy pilot shot down over North Vietnam in 1965 and held prisoner for more than seven years, said he had read Epictetus before the war and that his teaching helped him cope.',
    ],
    myths: [
      { myth: 'Epictetus taught that we should feel nothing and accept everything.', reality: 'He asked people to separate what they can influence from what they cannot, and to act energetically within the first. He expected people to do their duties to family, friends and country, and he described feeling affection as natural, as long as it is accompanied by understanding.' },
      { myth: 'His teaching is just a set of rules for coping with stress.', reality: 'He thought of it as a whole philosophy. For him the point of the exercises was not comfort but living in accord with nature and reason, and the sense of calm was a result, not the goal.' },
    ],
    works: [
      { title: 'Discourses (recorded by Arrian)', note: 'Four of the original eight books survive. Informal lectures and classroom conversations, with a sharp, direct voice.' },
      { title: 'Enchiridion (Handbook)', note: 'A short digest of the Discourses, compiled by Arrian, easy to carry and read.' },
      { title: 'Arrian, Letter to Lucius Gellius', note: 'The preface in which Arrian explains how he wrote down the lectures.' },
      { title: 'Simplicius, Commentary on the Enchiridion', note: 'A sixth-century Neoplatonist’s commentary that helped keep the handbook alive in late antiquity.' },
    ],
    legacy: [
      'The Enchiridion was widely used in the later Roman world. Christian monastic writers adapted it in late antiquity, and from the Renaissance onward, it was translated into many languages. Philosophers such as Descartes and Pascal responded to Epictetus, and Pascal criticised what he thought was Epictetus’s overconfidence in human strength.',
      'In the twentieth century his distinction between what we can and cannot control helped inspire cognitive behavioural therapy, as its founders Albert Ellis and Aaron Beck have acknowledged. Epictetus remains one of the most direct and practical teachers of philosophy as a way of life.',
    ],
  },
  {
    slug: 'marcus-aurelius',
    order: 121,
    dates: '121 – 180 AD',
    place: 'Rome',
    era: 'Ancient',
    tradition: 'Stoicism',
    tagline: 'The Roman emperor who spent his campaigns writing private notes on how to be a good person.',
    who: [
      'Marcus Aurelius was born in Rome on 26 April 121 AD, into a wealthy and well-connected family. His father died when he was young, and he was raised by his mother Domitia Lucilla and his grandfather. The emperor Hadrian took notice of him, and in 138 arranged that his successor, Antoninus Pius, should adopt both Marcus and another young man, Lucius Verus. Marcus studied rhetoric with Fronto, whose letters to him survive, and he turned to philosophy under teachers such as the Stoic Junius Rusticus. Later tradition says that as a boy he dressed plainly and slept on the ground in the manner of a philosopher, but the source for this is a late and unreliable biography.',
      'He married Faustina, the daughter of Antoninus Pius, in 145, and the couple had many children, though few outlived them. When Antoninus died in 161, Marcus became emperor and, in an unusual step, shared the throne with Lucius Verus, who died in 169. His reign was full of crises. A plague, possibly smallpox, spread through the empire from 165 and killed many people. A war with Parthia in the east was followed by wars along the Danube against the Marcomanni, Quadi and other tribes, which occupied him for much of his last years. In 175 the general Avidius Cassius, believing a rumour that Marcus was dead, declared himself emperor in the East, and Marcus had to prepare to march against him before Cassius was killed by his own men.',
      'Marcus made his son Commodus joint ruler in 177, and he died on 17 March 180, probably at Vindobona (Vienna) or Sirmium, while campaigning on the Danube. During these campaigns he wrote the notes now called the Meditations, in Greek, for himself alone. The title was added later, and the oldest Greek tradition calls the work something like “To Himself”. Notes at the end of Book 1 and Book 2 place their writing near the river Granua in the land of the Quadi, and at Carnuntum, on the Danube.',
    ],
    context: [
      'Marcus is the last of the “Five Good Emperors”, a label used by later writers for Nerva, Trajan, Hadrian, Antoninus Pius and Marcus, whose reigns formed a period of relative stability. Rome was at its largest and richest, but under his rule the borders came under strain, the treasury was drained by wars, and the plague hit hard. Historians still debate how deeply the plague affected the empire.',
      'Stoicism had by then become a widely respected philosophy among educated Romans, and Marcus adopted it seriously. He had read Epictetus through Rusticus, and he admired the Stoic ideal of the person who does their duty, accepts what cannot be changed and treats other people as fellow members of one community. His notes show a man trying to practise this while occupied by war, illness, family losses and the burdens of power.',
    ],
    ideas: [
      { title: 'The mind is the citadel', text: 'Again and again Marcus tells himself that events cannot touch the soul unless he lets them. What harms him is not what happens but his judgment of it. A mind free from passion is like a fortress: nothing outside can break in. Scholars sometimes use the phrase “inner citadel” for this idea, drawing on a passage in the Meditations.' },
      { title: 'The obstacle becomes the way', text: 'He writes that the obstacle to action can advance action, and what stands in the way becomes the way. Difficulties are not interruptions of virtue, but occasions for it. If someone is rude, he can practise patience. If a task is hard, he can practise perseverance.' },
      { title: 'Life is short, so act now', text: 'Marcus often reminds himself that life is brief, that great names such as Alexander and Caesar are dead, and that fame fades quickly. This is not gloom. It is a way of recalling what matters, and of not delaying what he knows is right. He tells himself to do each thing as if it were the last.' },
      { title: 'The view from above', text: 'He imagines himself looking down on the world: on armies, farms, weddings, storms and quarrels, all small from far above. The exercise, which he borrows from earlier thinkers, is meant to give perspective and to reduce the weight of his own worries and ambitions. He also tries stripping things to their parts, describing a rich robe as sheep’s wool dyed with shellfish blood.' },
      { title: 'We are made for one another', text: 'People, he writes, are born for cooperation, like feet, hands and eyes. To act against another is to act against nature. Duty to the common good comes first, and he reminds himself that even those who wrong him share the same reason and the same origin. He also often considers whether the world is governed by providence or by atoms, and concludes that in either case he should live well and be at peace.' },
    ],
    principles: [
      'Start the day by expecting difficult people, and decide to meet them with patience.',
      'Do the task in front of you now, with full attention.',
      'Be strict with yourself and generous toward others.',
      'Accept what the world brings and treat it as part of a larger whole.',
      'Act for the common good, not for reputation.',
    ],
    practice: [
      'Each morning, name the difficulties you will probably meet today and how you want to respond to them.',
      'When something upsets you, describe it in plain factual terms, stripped of the story you tell about it.',
      'Choose one small task and do it with your whole attention, instead of dividing yourself between several.',
    ],
    facts: [
      'Marcus’s “Meditations” was not meant for publication, and there is little evidence that anyone read it widely in his lifetime. The orator Themistius mentions it in the fourth century, and the first printed edition appeared in Zurich in 1558–59.',
      'Book 1 is a list of people to whom he is grateful, including his grandfather, his mother, Rusticus, who introduced him to Epictetus, and Antoninus Pius, whom he admired for his calm and fairness.',
      'The surviving letters between Marcus and his tutor Fronto were discovered in the nineteenth century in a palimpsest, a manuscript where old text had been scraped away and written over.',
      'His bronze equestrian statue in Rome survived the Middle Ages, according to a long-standing tradition because it was mistaken for a statue of the Christian emperor Constantine. It now stands in the Capitoline Museums.',
      'His son Commodus is widely seen as a poor emperor, and Edward Gibbon argued that Marcus’s choice of his own son as heir was a serious mistake.',
      'Under his reign, Christians were executed in Lugdunum (Lyon) in 177. Historians debate how far Marcus directed or approved this, and it remains a difficult fact for those who admire him.',
    ],
    myths: [
      { myth: 'Marcus Aurelius was a gentle philosopher who rejected war.', reality: 'He spent much of his reign leading military campaigns, above all against Germanic tribes on the Danube, and the Meditations were written in the field. He saw war as a duty, not a pleasure, but he did not shy from fighting.' },
      { myth: 'He wrote the Meditations as a book of wisdom for the public.', reality: 'It was a private notebook, repetitive and often unpolished. That is partly why it feels honest: a man talking to himself, not instructing a crowd.' },
      { myth: 'Marcus was untroubled by his duties.', reality: 'The notes show a man who is often tired, irritated or doubtful, and who writes the same reminders over and over because he has not mastered them. That is the point: he is practising, not preaching.' },
    ],
    works: [
      { title: 'Meditations (Ta eis heauton)', note: 'Twelve books of notes in Greek, probably written in the 170s, with no fixed order and many repeated themes.' },
      { title: 'Correspondence with Fronto', note: 'Letters, some in Latin and some in Greek, that show Marcus as a young man and his relationship with his teacher.' },
      { title: 'Cassius Dio, Roman History', note: 'A third-century historian whose account covers Marcus’s reign, though parts survive only in summary.' },
      { title: 'Historia Augusta, Life of Marcus Antoninus', note: 'A late and often unreliable collection of imperial biographies, useful but to be used with caution.' },
    ],
    legacy: [
      'The Meditations survived through Byzantine scholars and became one of the most widely read works of ancient philosophy in modern times. Frederick the Great of Prussia and many other rulers admired it, and ordinary readers, from soldiers to executives, have turned to it for guidance.',
      'Marcus is often held up as an example of the philosopher on the throne, a man with enormous power who tried to restrain himself and to serve others. He should be seen as a real person, with failures and blind spots, including his choice of successor. Yet his notebook remains a unique record of an ancient ruler talking honestly to himself about how to live.',
    ],
  },
  {
    slug: 'plotinus',
    order: 204,
    dates: 'c. 204/5 – 270 AD',
    place: 'Roman Egypt (probably), Alexandria, then Rome',
    era: 'Ancient',
    tradition: 'Neoplatonism',
    tagline: 'The philosopher-mystic who described all of reality as flowing from a single source, the One, and the soul’s way back to it.',
    who: [
      'Plotinus was born in 204 or 205 AD in Roman Egypt. A late source names the town as Lycopolis, but we cannot be sure. Nearly all we know about his life comes from a biography written by his pupil Porphyry. Plotinus himself was reluctant to speak of his origins. Porphyry says that he would not tell anyone his birthday or his family and refused to sit for a portrait, asking whether it was not enough to carry around the image in which nature had enclosed him.',
      'At around the age of 28 he went to Alexandria to study philosophy. Disappointed in several teachers, he met Ammonius Saccas, and, according to Porphyry, said that this was the man he had been looking for. He studied with Ammonius for eleven years. Around 243 he joined the army of the emperor Gordian III on its expedition against Persia, hoping to learn the wisdom of the Persians and Indians. The campaign failed, Gordian died, and Plotinus escaped to Antioch. In about 244 he settled in Rome, where he taught for roughly twenty-five years.',
      'He began to write only in his late forties or fifties, and his treatises record the discussions of his school. His pupils included Amelius, Porphyry, who joined him in 263, and a number of Roman senators. Porphyry reports that Plotinus was a trusted guardian of the orphaned children of friends. When Porphyry fell into a deep depression and thought of suicide, Plotinus is said to have noticed and advised him to travel. Plotinus’s health failed in his last years, and he died in 270 in Campania, on an estate left to him by a pupil, Zethos. His reported last words were an instruction to try to bring back the divine in us to the divine in the All.',
    ],
    context: [
      'Plotinus lived in the third century, one of the most unstable periods of the Roman Empire. Emperors rose and fell quickly, armies fought each other and the frontiers, and plague and inflation added to the disorder. In such an age, a philosophy that turned away from outward events toward the inner life of the soul found an audience.',
      'He regarded himself as a faithful interpreter of Plato, not as a founder of a new school. The label “Neoplatonism” was invented much later by modern scholars. Plotinus read Plato through centuries of commentary, and used ideas from Aristotle and the Stoics, but his own vision was original. He also argued against rival views of his day, and one treatise, later titled “Against the Gnostics”, attacks those who held that the visible world was the creation of an evil or ignorant maker.',
    ],
    ideas: [
      { title: 'The One', text: 'At the summit of reality stands the One, also called the Good. It is absolutely simple, beyond being and beyond thought, and so nothing we say about it is strictly true. We can only say what it is not. Plotinus takes the idea partly from Plato, who said the Good is beyond being. The One is the source of everything because its perfection overflows.' },
      { title: 'Three levels: One, Intellect, Soul', text: 'From the One comes Intellect (Nous), a divine mind that contains the Forms, the patterns of all things. From Intellect comes Soul, which links the intelligible world to the physical world and gives it life and order. This outflow is often called emanation. Plotinus uses images such as light from the sun or water from a spring, and insists that the source is not diminished or changed by what comes from it.' },
      { title: 'The soul’s return', text: 'Our true self belongs to the higher realm. The aim of life is to turn back toward the source, through virtue, philosophy and contemplation, and to become like the divine. At the highest point, he writes, the soul may be united with the One in what he calls the flight of the alone to the alone, a state beyond ordinary thought.' },
      { title: 'Beauty as a guide', text: 'In a treatise on beauty, Plotinus says that we love beautiful things because they share, imperfectly, in a higher beauty. The attraction of a lovely body or a fine action can lead us upward to the source of all beauty. He offers a famous image: if you want to become beautiful, never stop sculpting your own statue, chipping away what is excessive until the beauty of your character shines out.' },
      { title: 'Matter and evil', text: 'At the bottom of the scale is matter, the formless background that receives shape. Plotinus holds that evil is not a power with its own existence but a lack, a falling away from form and good. For this reason he rejected the Gnostic view that the world is a mistake or a prison, insisting that the cosmos is good and beautiful, even if imperfect.' },
    ],
    principles: [
      'Turn your attention inward, toward what is most real in you.',
      'Work on yourself like a sculptor: remove what does not belong.',
      'Let beauty draw you upward, toward what is good.',
      'Practise stillness and contemplation.',
      'Do not mistake the world’s appearances for its source.',
    ],
    practice: [
      'Set aside a short time each day for quiet attention, with no phone and no task, and notice what remains when the noise falls away.',
      'Ask of anything you admire what it is about it that draws you, and whether that quality goes beyond the particular thing.',
      'Pick one habit or fault that is “excess stone” in your character and work to remove it, patiently, like a sculptor.',
    ],
    facts: [
      'Porphyry organised Plotinus’s 54 treatises into six groups of nine, the Enneads, from the Greek word for nine. The arrangement is by subject, not by date, and modern scholars often prefer a chronological order.',
      'Porphyry says Plotinus never reread or revised his writing and had poor eyesight and spelling, so Porphyry had to edit the texts for him.',
      'He reportedly asked the emperor Gallienus for a ruined town in Campania, to be rebuilt as “Platonopolis”, a city ruled by Plato’s laws. Porphyry says that jealous courtiers prevented it.',
      'Porphyry states that Plotinus seemed ashamed of being in a body, and that he reached union with the One four times during their years together. Porphyry himself reports one such experience.',
      'Medieval Arabic readers knew parts of the Enneads in a paraphrase called the Theology of Aristotle, which wrongly attributed Plotinus’s ideas to Aristotle.',
      'Marsilio Ficino’s Latin translation of the Enneads appeared in 1492 and gave Renaissance readers direct access to Plotinus.',
    ],
    myths: [
      { myth: 'Plotinus founded a new religion.', reality: 'He saw himself as an interpreter of Plato. His thought has a strongly religious tone, but he was a teacher of philosophy, and many pupils were pagan philosophers and Roman officials, not members of a cult.' },
      { myth: 'For Plotinus the physical world is bad and should be despised.', reality: 'He argued against Gnostics who said so. For Plotinus the visible cosmos is the beautiful image of a higher order, even though the soul’s true home lies elsewhere.' },
      { myth: 'Emanation means the One shrinks or divides.', reality: 'Plotinus is careful to say that the source remains whole and unchanged, as the sun does not lose anything by giving light. Modern scholars debate how best to understand this process.' },
    ],
    works: [
      { title: 'Enneads', note: 'Fifty-four treatises, edited by Porphyry in six groups of nine. Dense, difficult and often moving.' },
      { title: 'Porphyry, Life of Plotinus', note: 'The main source for his life, written by his pupil, admiring and sometimes legendary.' },
      { title: 'Ennead I.6, “On Beauty”', note: 'The short and much-read treatise on beauty and the soul’s ascent, which contains the image of the statue.' },
      { title: 'Ennead II.9, “Against the Gnostics”', note: 'His defence of the goodness of the cosmos against pessimistic Gnostic teachings.' },
      { title: 'Ennead VI.9, “On the Good, or the One”', note: 'His account of the highest principle and the union of the soul with it.' },
    ],
    legacy: [
      'Plotinus’s pupil Porphyry and later Neoplatonists such as Iamblichus and Proclus shaped the last centuries of pagan philosophy. Christian thinkers also drew on his ideas, though they changed them: Augustine says that he read “books of the Platonists”, widely understood to include Plotinus, and that they helped him to think of God as spiritual. Pseudo-Dionysius and others carried similar ideas further into medieval Christian mysticism.',
      'In the Islamic world, the Theology of Aristotle, translated in the circle of al-Kindi in the ninth century, brought Plotinian ideas into later thinkers such as Avicenna, and Jewish philosophers also used them. In the Renaissance, Ficino and the Florentine Platonists revived them, and the image of a world flowing from one source and returning to it has continued to inspire. Plotinus is generally regarded as the most important philosopher of late antiquity.',
    ],
  },
]
