import type { Profile } from './types'

export const SEVENTEENTH: Profile[] = [
  {
    slug: 'thomas-hobbes',
    order: 1588,
    dates: '1588 – 1679',
    place: 'Malmesbury, Wiltshire, England; later Paris and Chatsworth',
    era: 'Early Modern',
    tradition: 'Social contract theory',
    tagline: 'He argued that without a power to keep order, life would be a war of everyone against everyone, and built a political theory on that fear.',
    who: [
      'Thomas Hobbes was born on 5 April 1588 in Malmesbury, in the English county of Wiltshire. He later claimed that his birth was brought on early by news of the approaching Spanish Armada, and that his mother gave birth to “twins”, himself and fear. The remark is a joke he made about himself in later life, but it fits a thinker who made fear central to politics. His father, a clergyman, left the family after a quarrel, and a well-off uncle paid for Thomas’s schooling and sent him to Oxford, where he finished his degree in 1608.',
      'After Oxford he became tutor to the son of the Cavendish family, who became the Earls of Devonshire, and he stayed connected to that household for most of his life. The post gave him a library, travel on the Continent and introductions to scholars. In 1629 he published an English translation of Thucydides’s history of the Peloponnesian War, a book about a society tearing itself apart. In 1640, with the quarrel between King Charles I and Parliament growing, he feared for his safety and fled to Paris, where he stayed for about eleven years. In the late 1640s he taught mathematics to the young Prince of Wales, the future Charles II.',
      'His best-known book, Leviathan, was published in 1651, while he was still in exile. Its theory of the state, and its unorthodox treatment of religion, offended royalists and clergy alike, and Hobbes returned to England and made his peace with the new government. After the monarchy returned in 1660, Charles II granted him a pension, though his books remained controversial: in 1666 Parliament ordered a committee to look into writings thought to promote atheism, with Leviathan named among them. Hobbes kept writing into old age, producing a verse autobiography in Latin and translations of Homer. He died on 4 December 1679 at Hardwick Hall, aged 91.',
    ],
    context: [
      'Hobbes lived through the most violent period in English political history. The English Civil War of the 1640s pitted king against Parliament, ended in the execution of Charles I in 1649, and was followed by more than a decade without a king. Religious disputes between Anglicans, Puritans and Catholics made every political question also a question about God and conscience. Hobbes concluded that the root of the disaster was that people disagreed over who had the right to command.',
      'He was also a man of the new science. He admired Galileo, met leading thinkers in Paris, and took from them the idea that the world is matter in motion. He wanted to treat politics with the same rigour as geometry, starting from simple definitions and reasoning step by step. This ambition, to make a science of human society, is a large part of what makes him modern.',
    ],
    ideas: [
      { title: 'The state of nature', text: 'To understand why government is needed, Hobbes asks us to imagine life with no common authority at all. He argues that people are roughly equal in strength and cunning, want the same scarce things, and fear each other, so they would drift into a “war of all against all”. In that condition, he says in a famous line, life would be “solitary, poor, nasty, brutish, and short”. He presents this as a thought experiment about what happens when authority collapses, and the civil war gave it a painful reality.' },
      { title: 'The social contract', text: 'Since the state of nature is so dreadful, Hobbes holds that people have good reason to make an agreement: each gives up the right to rule themselves and hands authority to a sovereign who can keep the peace. Subjects obey, and in return they are protected. The state is therefore an artificial body, a “mortal god”, created by human consent for human safety. The image on the title page of Leviathan, a giant king made of many tiny people, shows this idea.' },
      { title: 'An undivided sovereign', text: 'Hobbes insisted that the sovereign’s power must be undivided and effectively absolute, because if authority is split between king, Parliament and church, the arguments over who decides lead back towards war. The sovereign could be a monarch or an assembly, though he preferred monarchy. Critics then and since have pointed out how little protection this offers against a ruler who abuses power, and many readers regard this as the weakest part of his system.' },
      { title: 'The limits of obedience', text: 'Even in Hobbes’s system there is a limit. Because the whole purpose of the contract is self-preservation, he held that no one can be obliged to kill themselves, and a person need not obey a sovereign who can no longer protect them. His argument was grounded in safety, not in the king’s divine right, which was a radical departure from older royalist theory. He also grounds laws of nature, such as seeking peace and keeping promises, in reason and self-interest.' },
      { title: 'A materialist view of people', text: 'Hobbes believed that everything real is bodily, and that thought, emotion and will are motions inside the body. He regarded the mind as the working of the brain and not as a separate spirit, and he argued that we do not have free will in the sense of an uncaused choice, though we can act freely when nothing external stops us. This put him at odds with Descartes, to whom he sent objections to the Meditations, and with many churchmen of his day.' },
    ],
    principles: [
      'Peace and security come before every other political good.',
      'Order depends on someone having the final say.',
      'People are moved chiefly by fear, desire and the wish to survive, and a good system takes this into account.',
      'Keep your agreements, since trust makes all cooperation possible.',
      'Define your terms carefully before you argue, as many quarrels are about words.',
    ],
    practice: [
      'When a conflict escalates, ask what each side fears, since fear often drives behaviour more than principle.',
      'Before judging an institution, imagine its absence and consider what would fill the gap.',
      'Before a debate, agree on what the key words mean, and you may find that half the quarrel disappears.',
    ],
    facts: [
      'The phrase “solitary, poor, nasty, brutish, and short” comes from chapter 13 of Leviathan and describes life in a state of nature, not life in general.',
      'Hobbes’s first publication was a translation of Thucydides, published in 1629.',
      'He argued for years with the bishop John Bramhall about free will, and with the mathematician John Wallis over geometry, in disputes that Hobbes mostly lost on the mathematics.',
      'In 1666, after the Great Fire of London, Parliament ordered a committee to investigate books that promoted atheism, and Leviathan was among those named. Hobbes feared for his safety, though he escaped punishment.',
      'His Latin verse autobiography, written in his old age and published in 1672, is the main source for his claim that fear was his “twin”.',
      'Oxford University ordered Leviathan and other books burned in 1683, a few years after Hobbes’s death.',
    ],
    myths: [
      { myth: 'Hobbes thought people are simply wicked.', reality: 'His argument is that ordinary people, concerned with their own safety, will clash when no authority exists. He does not claim that people are monsters, and he describes reason leading them towards peace.' },
      { myth: 'Hobbes defended the divine right of kings.', reality: 'Royalists of his time based the king’s power on God’s appointment. Hobbes based it on an agreement among people who want protection, which angered many royalists and helped later contract theorists.' },
    ],
    works: [
      { title: 'Leviathan (1651)', note: 'His masterpiece: a theory of human nature, the state, and the relation of religion to politics.' },
      { title: 'De Cive (1642)', note: 'A shorter, earlier statement of his political theory, written in Latin.' },
      { title: 'The Elements of Law (1640)', note: 'An early political treatise that circulated in manuscript before it was printed.' },
      { title: 'Behemoth', note: 'A history of the English civil wars written in the late 1660s and published after his death.' },
      { title: 'Translation of Thucydides (1629)', note: 'Hobbes’s English version of the Peloponnesian War, which shaped his view of civil strife.' },
    ],
    legacy: [
      'Hobbes set the terms of modern political philosophy. Later writers such as Locke and Rousseau also use a state of nature and a social contract, though they draw very different conclusions from them. Anyone who justifies political authority by asking what free and equal people would agree to is, whether they know it or not, working in the style Hobbes started.',
      'His thinking also shaped later theories of international relations, in which states, lacking a world government, sit in a state of nature towards one another. Whether or not one accepts his absolutism, his questions about order, fear and legitimate power remain urgent.',
    ],
  },
  {
    slug: 'rene-descartes',
    order: 1596,
    dates: '1596 – 1650',
    place: 'La Haye en Touraine, France; the Dutch Republic; Stockholm',
    era: 'Early Modern',
    tradition: 'Rationalism',
    tagline: 'He doubted everything he could, found one thing he could not doubt, and tried to rebuild knowledge on it.',
    who: [
      'René Descartes was born on 31 March 1596 in La Haye en Touraine, a small town in France that is now named after him. His mother died the following year. He was educated at the Jesuit college of La Flèche, which gave him a strong grounding in mathematics, logic and scholastic philosophy, and then took a law degree at Poitiers in 1616. In 1618 he joined the army of Maurice of Nassau in the Dutch Republic as a gentleman volunteer, and there he met the mathematician Isaac Beeckman.',
      'By his own later account, on the night of 10 November 1619 he had a series of dreams that convinced him he should seek a single method for all knowledge. After years of travel and a stay in Paris, he settled in the Dutch Republic in 1628, where he lived for most of the next two decades, often moving house, and often keeping his address quiet so that he could work in peace. In 1633 he held back a book on the physical world, Le Monde, after hearing that the Church had condemned Galileo for teaching that the Earth moves. His first book, the Discourse on the Method, appeared anonymously in 1637, and the Meditations on First Philosophy followed in 1641.',
      'In the 1640s he corresponded with Princess Elisabeth of Bohemia, whose sharp questions about how mind and body interact pushed him to write about the emotions, and in 1649 he published Passions of the Soul. That same year Queen Christina of Sweden invited him to Stockholm. He accepted, and he died there on 11 February 1650, most likely of pneumonia, after a winter of early-morning meetings with the queen. His remains were later returned to France.',
    ],
    context: [
      'Descartes was born into a Europe where the old order of knowledge was cracking. The Protestant Reformation had split Christendom, and the wars of religion made certainty about God and truth feel urgent. At the same time, the rediscovery of ancient scepticism and the new discoveries of Copernicus and Galileo made many traditional claims about nature look doubtful.',
      'The established university philosophy, taught at schools such as La Flèche, was largely Aristotelian. Descartes decided that this system rested on unsound foundations and set out to replace it with something built from first principles, in the way that geometry rises from a few clear axioms. He was also a gifted mathematician, and his La Géométrie, published with the Discourse, joined algebra to geometry in a way that led to what we call Cartesian coordinates.',
    ],
    ideas: [
      { title: 'The method of doubt', text: 'In the Meditations Descartes decides to set aside everything that could possibly be doubted, to see whether anything is left. The senses sometimes deceive us, dreams can feel real, and even simple sums could be wrong if some powerful deceiver were fooling us. This doubt is a tool, not a conclusion. He is not a sceptic but is using scepticism to find solid ground.' },
      { title: 'The cogito', text: 'The one thing he cannot doubt is that he is doubting and thinking, since even a deceiver could not make him deceived if he did not exist. The line is best known as “I think, therefore I am” (in Latin, cogito, ergo sum), which appears in the Discourse and the Principles; in the Meditations he puts it as “I am, I exist” whenever he thinks it. From this single certain point he tries to build outwards.' },
      { title: 'Mind and body are distinct', text: 'Descartes argued that the mind is a thinking, non-physical thing, while the body is a physical thing with extension in space, and that the two are really different substances. This is called dualism. It raised a problem that haunts philosophy to this day: if they are so different, how do they affect each other? He suggested that they meet in the pineal gland of the brain, an answer that few found convincing, even in his own time.' },
      { title: 'God as a guarantee', text: 'After the cogito, Descartes argues that he has an idea of a perfect, infinite being, and that this idea could only come from such a being, so God exists. Because God is good, he reasons, God would not let us be deceived about what we perceive clearly and distinctly. Critics from his own age onwards have noticed that the argument seems circular, and this was a central objection raised by Arnauld.' },
      { title: 'Nature as mechanism', text: 'In his physics, Descartes pictured the material world as matter in motion obeying mathematical laws, like a vast machine, with no hidden purposes or occult powers. He extended the idea to animals, which he regarded as complex automata. This mechanical outlook shaped early modern science, though many of his specific physical theories were soon replaced by Newton’s.' },
    ],
    principles: [
      'Accept nothing as true that you do not clearly recognise to be so.',
      'Divide hard problems into as many parts as are needed to solve them.',
      'Proceed in order, from the simplest matters to the more complex.',
      'Review your reasoning so thoroughly that nothing is overlooked.',
      'Doubt carefully and with a purpose, since doubt is a tool, not a way of life.',
    ],
    practice: [
      'Pick one belief you hold strongly and ask what evidence it really rests on, then check whether that evidence would survive a hard look.',
      'Break a daunting problem into smaller steps and solve the easiest first.',
      'Write down your reasoning in order, so that gaps and leaps become visible.',
    ],
    facts: [
      'The four rules of method that Descartes set out in the Discourse are about clarity, analysis, order and completeness, and were meant to apply to every subject.',
      'He never married, but in 1635 he had a daughter, Francine, with a servant, Helena Jans. Francine died of scarlet fever at the age of five, and Descartes was reportedly devastated.',
      'He dedicated his Principles of Philosophy to Princess Elisabeth of Bohemia.',
      'In 1633 he decided not to publish Le Monde after hearing of Galileo’s condemnation, and the work appeared only after his death.',
      'Some of his works were placed on the Church’s Index of forbidden books in 1663.',
      'Cartesian coordinates, the x and y grid used in school mathematics, are named after him and grew out of La Géométrie.',
    ],
    myths: [
      { myth: 'Descartes said “I think, therefore I am” in the Meditations.', reality: 'The French version of the phrase appears in the Discourse (1637) and the Latin in the Principles (1644). The Meditations make the same point in different words, as “I am, I exist”.' },
      { myth: 'Descartes was an atheist or a disguised sceptic.', reality: 'He was a practising Catholic who offered proofs of God’s existence and wanted his philosophy to support religion. Some contemporaries nonetheless suspected him, and his thought was condemned by the Church after his death.' },
    ],
    works: [
      { title: 'Discourse on the Method (1637)', note: 'An autobiographical introduction to his method, published with essays on optics, meteorology and geometry.' },
      { title: 'Meditations on First Philosophy (1641)', note: 'His core argument in six meditations, printed with objections from other thinkers and his replies.' },
      { title: 'Principles of Philosophy (1644)', note: 'A systematic account of his metaphysics and physics, intended as a textbook.' },
      { title: 'Passions of the Soul (1649)', note: 'A study of the emotions, prompted by his exchange with Princess Elisabeth.' },
      { title: 'Rules for the Direction of the Mind', note: 'An early, unfinished work on method, published after his death.' },
    ],
    legacy: [
      'Descartes is often called the father of modern philosophy. His idea of starting from the thinking self, and asking how we can know anything beyond it, set the agenda for Locke, Spinoza, Leibniz, Hume and Kant, whether they followed him or opposed him. The question of how mind and body relate, which he made so sharp, is still a major topic in philosophy and neuroscience.',
      'In mathematics, the coordinate system that bears his name joined algebra and geometry and made the later development of calculus possible. His confidence that nature can be understood through mathematics helped to launch the scientific revolution, though modern thinkers have also criticised his sharp split between mind and body.',
    ],
  },
  {
    slug: 'blaise-pascal',
    order: 1623,
    dates: '1623 – 1662',
    place: 'Clermont (now Clermont-Ferrand), then Rouen and Paris, France',
    era: 'Early Modern',
    tradition: 'Christian thought and mathematics',
    tagline: 'A mathematical prodigy who turned to faith and wrote about human greatness and misery.',
    who: [
      'Blaise Pascal was born on 19 June 1623 in Clermont, in central France. His father, Étienne, was a civil servant with a keen interest in mathematics, and educated his children at home because Blaise was often ill. The family moved to Paris and later to Rouen, where Étienne was a tax official. At sixteen, Blaise wrote a short essay on conic sections that included a result now known as Pascal’s theorem. A few years later, to help his father with the endless sums of tax work, he built a mechanical calculator, now known as the Pascaline.',
      'In the later 1640s he turned to physics, working on air pressure and the vacuum. In 1648 an experiment on the Puy de Dôme mountain, carried out by his brother-in-law Florin Périer at Pascal’s request, showed that a column of mercury falls as one climbs, supporting the idea that air has weight. In 1654, prompted by a gambling friend, he corresponded with the mathematician Pierre de Fermat, and their exchange laid the foundations of probability theory. His father had died in 1651, and his sister Jacqueline had joined the convent of Port-Royal, which was linked to the strict Jansenist movement in French Catholicism.',
      'On the night of 23 November 1654 Pascal had an intense religious experience, which he recorded on a scrap of paper known as the Memorial. After he died, it was found sewn into his coat. He grew closer to Port-Royal and wrote the Provincial Letters (1656–57), published under a pseudonym, which defended a Jansenist ally against Jesuit critics with sharp wit. He then began collecting notes for a defence of the Christian faith. Never in good health, he died in Paris on 19 August 1662, aged 39, with the work unfinished.',
    ],
    context: [
      'Pascal lived at a time when two forces were pulling at educated Europeans. On one side, the new science of Galileo and Descartes suggested that nature could be understood through measurement and mathematics. On the other, deep religious conflicts over grace, free will and the authority of the church shaped daily life.',
      'In France, the Jansenists, followers of the theologian Cornelius Jansen, taught that human beings depend entirely on God’s grace, and they clashed with the Jesuits, who took a more flexible view of moral rules. The Church and the crown eventually condemned Jansenism. Pascal was both a scientist who respected reason and a believer who thought reason alone could not satisfy the human heart.',
    ],
    ideas: [
      { title: 'The wager', text: 'Pascal suggested that a person unsure whether God exists must still live one way or another, so in effect everyone is betting. If God exists and you believe, you gain everything. If God does not exist, you lose very little. He used the language of the new probability theory to argue that believing is the sensible bet. Critics point out that it does not say which god to believe in, and that belief cannot simply be chosen. Pascal meant it for sceptics who care about the question but cannot be moved by proofs.' },
      { title: 'The reasons of the heart', text: 'He wrote that the heart has its reasons which reason does not know. By “heart” he meant an immediate, intuitive sense of truth, such as our sense that space is three-dimensional or that numbers go on forever, which comes before and underlies logical argument. He believed that we know first principles through the heart and that faith too reaches beyond proofs.' },
      { title: 'Greatness and wretchedness', text: 'Pascal found human beings a puzzle: tiny and frail, a “thinking reed” that a drop of water can kill, yet greater than the universe because we know that we die and it does not. For Pascal this contradiction was a clue that we are fallen creatures with a lost greatness. Whether or not one accepts his religious answer, the portrait of people as both noble and pitiful has been admired by many readers.' },
      { title: 'Diversion', text: 'Pascal observed that people fill their lives with entertainment, work, gossip and games to avoid sitting quietly with themselves and their mortality. He suggested that much of our restlessness comes from this, and that even kings need amusement to avoid thinking about their condition.' },
      { title: 'Two kinds of mind', text: 'He distinguished the “geometrical” spirit, which reasons carefully from definitions, from the “spirit of finesse”, which takes in many subtle things at a glance, as a good judge of character does. He thought each was necessary and that people tend to be strong in one and weak in the other.' },
    ],
    principles: [
      'Reason has limits, but within them it should be used carefully.',
      'Take seriously the questions that cannot be settled by calculation.',
      'Be honest about the human condition, with both its dignity and its weakness.',
      'Do not hide from yourself by constant distraction.',
      'Be wary of those who simplify the world into slogans.',
    ],
    practice: [
      'Spend a few minutes a day in silence with no screen, and notice what you reach for when you are bored.',
      'When facing a decision under uncertainty, compare what you stand to gain and lose in each case, as Pascal did, but also ask what you would regret.',
      'Cultivate both analysis and intuition, and notice which one you tend to ignore.',
    ],
    facts: [
      'Pascal’s name is used for the SI unit of pressure, the pascal, and for a programming language.',
      'His correspondence with Fermat in 1654 is usually named as the birth of probability theory.',
      'The Pascaline could add and subtract, and Pascal built several versions.',
      'In 1662, shortly before his death, a bus service with fixed routes and a fixed fare, the carrosses à cinq sols, began in Paris, and Pascal is often said to have been involved in the scheme.',
      'In one of the Provincial Letters he apologised that his letter was long because he had not had time to make it shorter.',
      'The Pensées, published in 1670 after his death, are a collection of fragments, not a finished book.',
    ],
    myths: [
      { myth: 'A carriage accident on a bridge in 1654 caused Pascal’s conversion.', reality: 'Some accounts connect an accident to his conversion, but scholars dispute the story. What is well documented is the Memorial, the record of his experience on the night of 23 November 1654.' },
      { myth: 'Pascal’s wager is a proof that God exists.', reality: 'It is an argument about what it is prudent to do when proof is not available, not a proof. Pascal placed it in the context of a larger defence of Christianity.' },
    ],
    works: [
      { title: 'Pensées (published 1670)', note: 'Fragments for a defence of Christianity, assembled after his death, including the wager and his reflections on human nature.' },
      { title: 'Provincial Letters (1656–57)', note: 'Eighteen letters, published under a pseudonym, attacking the moral reasoning of some Jesuits.' },
      { title: 'Essay on Conics (1640)', note: 'A short work on geometry written at sixteen, containing what is now called Pascal’s theorem.' },
      { title: 'Treatise on the Arithmetical Triangle', note: 'A work on the number triangle now named after him, written in the 1650s.' },
    ],
    legacy: [
      'Pascal’s scientific work helped lay the groundwork for hydraulics, probability and computing, and his mathematical treatment of chance became a key tool in modern statistics, economics and decision theory. The early calculating machine he built is regarded as a forerunner of later calculators.',
      'The Pensées have been read by believers and non-believers for more than three centuries. Later writers such as Kierkegaard and the existentialists drew on his sense that human life is lived in tension between greatness and fragility, and that the most important questions cannot be answered by calculation alone.',
    ],
  },
  {
    slug: 'benedictus-de-spinoza',
    order: 1632,
    dates: '1632 – 1677',
    place: 'Amsterdam, then Rijnsburg, Voorburg and The Hague (Dutch Republic)',
    era: 'Early Modern',
    tradition: 'Rationalism',
    tagline: 'A lens grinder expelled by his own community who argued that God and Nature are one.',
    who: [
      'Baruch Spinoza (in Portuguese Bento, in Latin Benedictus) was born in Amsterdam in 1632 into a family of Portuguese Jewish origin. His family’s ancestors had fled Iberia, where Jews had been forced to convert or leave, and had found refuge in the tolerant Dutch Republic. He studied at the community school, but left formal studies in his teens to help with the family import business. He also read widely outside the Jewish tradition, studying Latin and the philosophy of Descartes and mixing with Christian free-thinkers.',
      'On 27 July 1656 the leaders of Amsterdam’s Sephardic Jewish community issued a harsh writ of excommunication (herem) against him, citing “abominable heresies” and “monstrous deeds”, though the exact reasons are not spelled out. The ban was never lifted. Spinoza never married, left Amsterdam, and made his living grinding optical lenses, which brought him into contact with scientists such as Christiaan Huygens. He moved to Rijnsburg around 1661, later to Voorburg, and finally to The Hague, where he lived modestly in rented rooms.',
      'Only two of his books appeared in his lifetime: an exposition of Descartes’s philosophy (1663), under his own name, and the Theological-Political Treatise (1670), which was published anonymously and soon denounced by many authorities as dangerous. He declined a professorship at Heidelberg, perhaps because it might limit his freedom to think. He met Leibniz in 1676. He died on 21 February 1677 in The Hague, aged 44, of a lung illness, probably tuberculosis and possibly worsened by glass dust from his work. His friends published his Ethics and other writings later that year.',
    ],
    context: [
      'The Dutch Republic in the seventeenth century was among the freest and wealthiest societies in Europe. Its printing houses were busy, and its tolerance, though limited, made room for dissenters, refugees and unusual ideas. Even so, there were limits: the Reformed Church and civil authorities worried about atheism, and Spinoza’s work provoked a storm.',
      'Spinoza was deeply shaped by Descartes, whose rationalism he admired and then reworked, and by the debate about the Bible, the state and religious authority. The Dutch Republic had just endured wars, and its political class, including the statesman Johan de Witt, sought ways to keep churches from controlling the state. His Treatise is a defence of that kind of secular order and of freedom to think.',
    ],
    ideas: [
      { title: 'One substance: God or Nature', text: 'In the Ethics, Spinoza argues that there is only one substance, which he calls God or Nature. Everything else, including every person and every stone, is a mode, a way that this one reality exists. His God is not a person who makes decisions and judges, but the whole of nature, governed by necessity. Critics called this atheism, while later admirers described it as a form of pantheism, though that label is debated.' },
      { title: 'Everything follows from necessity', text: 'Because the whole of nature follows from its own essence, nothing could have been otherwise, and there are no miracles in the usual sense. Spinoza therefore rejects free will in the sense of uncaused choice, yet he holds that people can still become more free by understanding the causes that move them. Freedom, for him, is acting from your own understanding rather than being pushed about by outside forces and emotions.' },
      { title: 'The drive to persist', text: 'Every thing, he says, strives to persevere in its being. He called this striving conatus, and he used it to explain the emotions: joy is an increase in our power to act, sadness a decrease, and desire, love and hate are shaped by these changes. The Ethics treats feelings as natural facts to be understood, and it is written in the style of geometry, with definitions, axioms and proofs.' },
      { title: 'Knowledge and blessedness', text: 'Spinoza describes three kinds of knowledge: opinion from scattered experience, reasoning from general principles, and a direct intuition of how things follow from God or Nature. The more we understand, the less we are tossed about by passion, and the more we experience a lasting joy, which he called the intellectual love of God. For him this, and not reward after death, is the highest happiness.' },
      { title: 'Freedom to think in a free state', text: 'In the Theological-Political Treatise he argues that the Bible should be read as a historical text, with attention to its language and circumstances, and that religion should be about right living, not about doctrinal conformity. He also defends the freedom to philosophise, arguing that a state is stronger and more peaceful when people may speak their minds. These ideas were controversial in his time and have since become central to liberal thought.' },
    ],
    principles: [
      'Do not mock, lament or hate human actions, but understand them.',
      'Freedom grows with understanding of the causes that shape us.',
      'Joy comes from active understanding, not from passive pleasure.',
      'A free state protects freedom of thought and speech.',
      'Religion should be judged by justice and charity, not by doctrine.',
    ],
    practice: [
      'When you feel a strong emotion, ask what caused it, and notice that understanding the cause often weakens its grip.',
      'Try to explain a person’s bad behaviour by their circumstances before reacting with anger.',
      'Spend time on something that you do for the joy of understanding, with no reward attached.',
    ],
    facts: [
      'His Ethics was published only after his death, in a collection of his works compiled by friends, with his name reduced to initials.',
      'He turned down a professorship at Heidelberg, which came with the freedom to philosophise provided he did not disturb the established religion.',
      'The Dutch authorities banned the Theological-Political Treatise in 1674.',
      'Leibniz visited him in The Hague in 1676, and the two discussed philosophy.',
      'Albert Einstein, in a 1929 telegram, said that he believed in Spinoza’s God, who reveals himself in the lawful harmony of the world.',
      'The writ of excommunication against him was never revoked, though many later Jewish thinkers have taken a keen interest in his work.',
    ],
    myths: [
      { myth: 'Spinoza was an atheist.', reality: 'He was accused of atheism in his own day, but he spoke constantly of God. What he denied was a personal God who intervenes in nature and rewards or punishes. Whether his view is atheism, pantheism or something else is a matter of ongoing debate.' },
      { myth: 'Spinoza lived in poverty because he was an outcast.', reality: 'He lived simply by choice, earned a modest income as a lens maker, and had a circle of supportive friends. He turned down offers of status that would have limited his freedom.' },
    ],
    works: [
      { title: 'Ethics (published 1677)', note: 'His masterpiece, in five parts on God, the mind, the emotions, human bondage and human freedom.' },
      { title: 'Theological-Political Treatise (1670)', note: 'On the Bible, religion and the state, and a defence of freedom of thought.' },
      { title: 'Principles of Cartesian Philosophy (1663)', note: 'An exposition of Descartes, the only book he published under his own name.' },
      { title: 'Treatise on the Emendation of the Intellect', note: 'An unfinished work on method, in which he reflects on his search for the highest good.' },
      { title: 'Political Treatise', note: 'His last, unfinished work, on how states can be organised for peace and liberty.' },
    ],
    legacy: [
      'For a century after his death, Spinoza was a name used to attack people. In the late eighteenth century German writers such as Lessing, Goethe and Herder began to praise him, and a debate over his ideas, known as the pantheism controversy, drew in Jacobi and Mendelssohn. The Romantic poet Novalis later called him a man intoxicated with God.',
      'Today he is read as a pioneer of biblical criticism, of the separation of church and state and of a scientific study of the emotions. Modern neuroscientists and philosophers return to his view that mind and body are two sides of one reality, and his ethics of understanding remains a favourite of those who find peace in clear thinking.',
    ],
  },
  {
    slug: 'john-locke',
    order: 1632,
    dates: '1632 – 1704',
    place: 'Wrington, Somerset, England; Oxford, London, the Netherlands, and Oates, Essex',
    era: 'Early Modern',
    tradition: 'Empiricism and liberalism',
    tagline: 'He said that the mind starts as a blank page and that governments exist to protect our natural rights.',
    who: [
      'John Locke was born on 29 August 1632 in Wrington, Somerset, to a Puritan family. His father was a lawyer who fought on the Parliamentary side in the English Civil War, and a patron helped John get a place at Westminster School and then at Christ Church, Oxford. He stayed on at Oxford as a lecturer and tutor, but disliked the old-fashioned university curriculum and found more interest in the new science. He studied medicine, took part in the experimental circle around Robert Boyle, and later became a physician.',
      'In 1666 he met Lord Ashley, later the Earl of Shaftesbury, who became his patron. Locke served as his doctor, secretary and adviser, and helped to manage his affairs and publications. Through Shaftesbury, Locke worked on colonial matters, including as secretary to the Lords Proprietors of Carolina. When Shaftesbury fell from favour and was suspected of plotting against the crown, Locke left for the Netherlands in 1683 and lived there until the Glorious Revolution of 1688–89. He used false names while in exile and was watched by English agents.',
      'Locke returned to England in 1689 and published his two major works within months, the Essay Concerning Human Understanding and the Two Treatises of Government, the latter anonymously. He served on the Board of Trade and also wrote on religion, education and money. He never married and lived in later years at the country house of Sir Francis and Lady Masham at Oates, in Essex, where he died on 28 October 1704.',
    ],
    context: [
      'Locke’s England was a society convulsed by struggles over who should rule and who should worship how. The Civil War, the execution of a king, the restoration of the monarchy, and the fear of a Catholic king, James II, shaped his political thought. In 1688 James was driven out in the Glorious Revolution, and Parliament invited William and Mary to rule, with limits on royal power.',
      'In science and philosophy, Locke was a friend of the new experimental approach of Boyle and Newton. He believed that thinkers should proceed with humility and use observation to learn about the world, and he attacked the idea that people are born with built-in knowledge. His work was a conscious reaction to the rationalism of Descartes.',
    ],
    ideas: [
      { title: 'The mind begins empty', text: 'In the Essay, Locke argues against innate ideas, the view that we are born with certain truths stamped on our minds. He compares the mind at birth to a blank sheet, or “white paper”, which experience fills. All our ideas come from sensation, what our senses show us, or reflection, what we notice about our own mental workings. This is the classic statement of empiricism, the view that knowledge begins in experience.' },
      { title: 'The limits of what we can know', text: 'Locke distinguished the primary qualities of things, such as shape and motion, which really belong to objects, from secondary qualities, such as colour and taste, which are powers in objects to produce sensations in us. He was modest about what the human mind can reach, and his aim was to map the scope of our understanding so that people would not waste time on questions beyond it. In a famous chapter, added in a later edition, he made memory and consciousness the basis of personal identity.' },
      { title: 'Natural rights and limited government', text: 'In the Second Treatise, Locke starts from a state of nature in which people have natural rights to life, liberty and property, governed by a law of nature that reason can discover. People form governments by consent to protect those rights. If a government systematically violates them, the people have the right to resist. This idea, that legitimate authority comes from consent and is limited, deeply influenced later liberal thought.' },
      { title: 'Property and labour', text: 'Locke argued that people acquire property by mixing their labour with what nature provides, within limits meant to leave “enough and as good” for others, until money allows more accumulation. This account of property has been enormously influential, and has also been criticised. Some scholars argue that it was used to justify taking land from Indigenous peoples in the Americas, who were seen as not cultivating it.' },
      { title: 'Toleration, with limits', text: 'In A Letter Concerning Toleration (1689), Locke argues that the state’s business is the protection of civil interests, not saving souls, and that force cannot produce real belief. He argued for tolerating a wide range of Christian sects. But he would not extend toleration to Catholics, because of allegiance to a foreign ruler, or to atheists, because he thought that oaths and promises would not bind them.' },
    ],
    principles: [
      'Proportion your belief to the evidence.',
      'Know the limits of your understanding before attempting grand claims.',
      'Government is a trust, held for the good of the governed.',
      'Faith cannot be forced.',
      'Education should build habits of reason and character, not only fill the memory.',
    ],
    practice: [
      'When you are certain of something, ask how you came to believe it, and what experience or evidence it rests on.',
      'Disagree with people by arguing, not by coercing, and see whether you can make your case in terms they could accept.',
      'Notice where your own principles have exceptions or blind spots, as Locke’s did.',
    ],
    facts: [
      'Locke acted as a doctor, and Shaftesbury’s liver infection reached a point where Locke is thought to have helped persuade him to undergo surgery.',
      'He published the Two Treatises anonymously, and he acknowledged authorship only in a codicil to his will.',
      'He wrote Some Thoughts Concerning Education (1693), which advised parents on how to raise children, including a recommendation of exercise, fresh air, and learning through play.',
      'In 1683 he went into exile in the Netherlands, where he completed the Essay and wrote the Letter Concerning Toleration.',
      'Locke’s writings helped to shape the American Declaration of Independence, with its talk of life, liberty and the pursuit of happiness, though the document’s wording was not simply his.',
      'The Fundamental Constitutions of Carolina (1669), drafted under Shaftesbury’s direction with Locke as secretary, gave every free man absolute power over his enslaved people.',
    ],
    myths: [
      { myth: 'Locke was a simple champion of liberty for all.', reality: 'He was a secretary to the proprietors of Carolina when its constitution endorsed slavery, and records list him as a shareholder in the Royal African Company, which traded in enslaved people. How far this contradicts his political writings, and whether his role was only secretarial, is debated by scholars.' },
      { myth: 'Locke invented the idea that people have rights.', reality: 'Ideas of natural law and natural rights were centuries old, with roots in medieval and Renaissance thought. Locke gave them an influential statement and tied them to consent and limited government.' },
    ],
    works: [
      { title: 'An Essay Concerning Human Understanding (1689)', note: 'His major work on the origin and limits of human knowledge.' },
      { title: 'Two Treatises of Government (1689)', note: 'The first attacks the divine right of kings, and the second sets out his theory of consent, rights and limited government.' },
      { title: 'A Letter Concerning Toleration (1689)', note: 'A short, powerful case for religious toleration.' },
      { title: 'Some Thoughts Concerning Education (1693)', note: 'A practical and influential guide to bringing up children.' },
      { title: 'The Reasonableness of Christianity (1695)', note: 'His argument that the core of Christian belief is simple and can be reasonably understood.' },
    ],
    legacy: [
      'Locke’s ideas strongly shaped the Enlightenment. Voltaire and other French thinkers admired his empiricism, and his political philosophy was drawn on by the American founders and by later constitutional movements. Later empiricists, notably Berkeley and Hume, started from his account of ideas, and his view of personal identity still drives debates in philosophy.',
      'His legacy is now read with greater honesty about its blind spots. Historians and philosophers have examined his connections to slavery and colonial expansion and ask how a thinker who wrote so powerfully about natural freedom could take part in these enterprises. This does not erase what he contributed, but it shows how the language of rights can coexist with injustice.',
    ],
  },
  {
    slug: 'gottfried-wilhelm-leibniz',
    order: 1646,
    dates: '1646 – 1716',
    place: 'Leipzig, then Mainz, Paris and Hanover (Germany)',
    era: 'Early Modern',
    tradition: 'Rationalism',
    tagline: 'A universal genius who co-invented calculus and argued that this is the best of all possible worlds.',
    who: [
      'Gottfried Wilhelm Leibniz was born on 1 July 1646 in Leipzig, in Germany. His father, a professor of moral philosophy, died when Leibniz was six, and the boy taught himself from the books in his father’s library. He studied at Leipzig and then at Altdorf, where he received a doctorate in law in 1666, at about the age of twenty. Even then he was sketching a plan for a general method of reasoning, in his Dissertation on the Art of Combinations.',
      'He entered the service of the Elector of Mainz, who sent him to Paris on a diplomatic mission, and he stayed there from 1672 to 1676. In Paris he studied mathematics with Christiaan Huygens, met leading philosophers, designed a calculating machine that could multiply and divide, and developed his version of calculus. He also visited London in 1673 and showed his machine to the Royal Society. In 1676 he took a post at the court of Hanover, where he served three successive dukes and electors as librarian, adviser and historian for the rest of his life.',
      'His duties at Hanover included a long, unfinished history of the House of Brunswick, and technical projects such as an attempt to improve mining in the Harz mountains with windmills, which the duke shut down in 1685. He corresponded with over a thousand people, helped to found the Berlin Academy in 1700, and promoted scientific societies across Europe. He never married. In his last years he was embroiled in a bitter dispute with Newton’s supporters over calculus. He died in Hanover on 14 November 1716, and the funeral was attended by very few of the court he had served.',
    ],
    context: [
      'Leibniz grew up after the Thirty Years’ War, which had devastated the German lands and left a fragmented patchwork of states. He dreamed of a Europe reconciled in religion and united in learning, and he spent much of his career trying to heal divisions between Catholics and Protestants and to set up academies. These hopes shaped his idea that knowledge should be shared and organised for the common good.',
      'Intellectually, he grew up between the old scholastic philosophy and the new mechanical science of Descartes, Galileo and Hobbes. He admired the new science but felt that a purely mechanical picture left out purposes, minds and the reason why anything exists at all. He sought to reconcile the old and the new in a system that could account for both.',
    ],
    ideas: [
      { title: 'Calculus', text: 'Leibniz developed differential and integral calculus in the mid-1670s, working independently of Newton, who had developed his own version earlier but not published it. Leibniz published first, in 1684. His notation, including the integral sign and the dx and dy symbols, proved so useful that it remains standard. The question of who deserved credit, and whether Leibniz had seen Newton’s unpublished work, produced the priority dispute.' },
      { title: 'Monads', text: 'In his philosophy Leibniz argued that the world is ultimately made of countless simple, mind-like units that he called monads. Each monad has its own perceptions and its own inner drive to change, and has no windows through which anything enters or leaves. Matter and space, he held, are well-founded appearances grounded in these units. It is a strange picture, but it grew from his attempt to explain what makes something a single thing.' },
      { title: 'Pre-established harmony', text: 'If monads do not act on each other, how do mind and body seem to coordinate? Leibniz said that God arranged, from the start, that each one unfolds according to its own nature in perfect agreement with the others, like two clocks set to keep the same time. This was his answer to the puzzle of mind and body inherited from Descartes.' },
      { title: 'Sufficient reason and the best possible world', text: 'Leibniz held that nothing happens without a reason why it is so and not otherwise. Applied to the world as a whole, this led him to argue that there must be a reason for the universe’s existence, God, and that a good and wise God would choose the best of all possible worlds. His book Theodicy (1710) used this to address the problem of evil: the world, though containing suffering, is the best overall combination of goodness and order. Voltaire later mocked the idea in Candide.' },
      { title: 'A language of reasoning', text: 'Leibniz dreamed of a universal symbolic language, which he called the characteristica universalis, in which every idea would be written in symbols and arguments could be settled by calculation. He imagined disputing parties saying to each other, “let us calculate.” He also worked out binary arithmetic, writing numbers with only 0 and 1, and he published on it in 1703. These ideas anticipated later work in logic and computing.' },
    ],
    principles: [
      'Nothing is without a reason, so look for the explanation.',
      'Seek the point where rival views can be reconciled.',
      'Use symbols and notation to make thinking clearer.',
      'Learn from many fields, since ideas from one often help another.',
      'Work for the common good through shared institutions.',
    ],
    practice: [
      'When you disagree with someone, search for what is true in their view before arguing against it.',
      'When something puzzles you, ask what would have to be the case for it to make sense.',
      'Keep a notebook for ideas from different subjects and look for connections between them.',
    ],
    facts: [
      'In 1673 he showed the Royal Society in London a calculating machine that could carry out multiplication and division as well as addition and subtraction.',
      'Leibniz’s 1703 paper on binary arithmetic noted a resemblance to the hexagrams of the Chinese Book of Changes, which he learned about from a Jesuit missionary.',
      'He corresponded with Samuel Clarke, Newton’s defender, in 1715–16 on space, time and God.',
      'He tried to write his own response to Locke, the New Essays on Human Understanding, but held it back after Locke died, and it was published only in 1765.',
      'The Monadology, written in 1714 as a short summary of his philosophy, was published only after his death.',
      'He founded the Berlin Academy in 1700, and he was interested in China, publishing a collection of writings on it in 1697.',
    ],
    myths: [
      { myth: 'Leibniz stole calculus from Newton.', reality: 'Historians now think both men reached calculus independently. Newton developed his method earlier, but Leibniz published first and used a better notation. A Royal Society committee in 1712 sided with Newton, but its report was in large part directed by Newton himself.' },
      { myth: 'Leibniz believed that everything is perfect and nothing is really bad.', reality: 'Leibniz claimed that this world is the best possible among all those God could have created, not that it has no evils. Voltaire’s Candide caricatures him through the character Pangloss.' },
    ],
    works: [
      { title: 'Theodicy (1710)', note: 'His book on God, evil and freedom, published during his lifetime.' },
      { title: 'Monadology (1714)', note: 'A short summary of his metaphysics, published after his death.' },
      { title: 'Discourse on Metaphysics (1686)', note: 'An early statement of his philosophy, first published in the nineteenth century.' },
      { title: 'New Essays on Human Understanding (1765)', note: 'A chapter-by-chapter reply to Locke, written around 1704 and published after his death.' },
      { title: 'Correspondence with Clarke (1715–16)', note: 'An exchange on space, time and God, with Newton’s supporter.' },
    ],
    legacy: [
      'Leibniz’s calculus notation is used by every student of mathematics today, and his ideas about formal languages and binary numbers are echoed in modern logic and computer science. Philosophers such as Kant responded to his rationalism, and his principle of sufficient reason and his views on space and time are still debated.',
      'He is often described as the last universal genius, having contributed to law, mathematics, physics, philosophy, history and diplomacy. His hope that learning could serve peace, and that careful notation could settle quarrels, remains inspiring even though the goal he set is still far away.',
    ],
  },
]
