import type { Profile } from './types'

export const TWENTIETH_A: Profile[] = [
  {
    slug: 'bertrand-russell',
    order: 1872,
    dates: '18 May 1872 – 2 February 1970',
    place: 'Trellech, Wales; worked mainly in Cambridge and London',
    era: '20th Century',
    tradition: 'Analytic philosophy',
    tagline: 'A logician who tried to rebuild mathematics from pure logic, and a public campaigner who went to prison for his convictions.',
    who: [
      'Bertrand Russell was born in Wales into one of the great aristocratic families of Britain; his grandfather, Lord John Russell, had twice been Prime Minister. Both his parents died while he was small, and he was raised mostly by his grandparents at Pembroke Lodge, in Richmond Park. He studied mathematics at Trinity College, Cambridge, graduating in 1893, and became a Fellow of the college in 1895.',
      'His early work was in logic and the foundations of mathematics. He published The Principles of Mathematics in 1903 and, with his former teacher Alfred North Whitehead, the three-volume Principia Mathematica between 1910 and 1913. In 1911 a young Austrian engineer named Ludwig Wittgenstein turned up unannounced at his rooms, and the two men’s long, difficult exchange shaped both of them. Russell’s opposition to the First World War cost him his lectureship at Trinity in 1916, and in 1918 he served six months in Brixton Prison for a pacifist article. He used the time to write his Introduction to Mathematical Philosophy.',
      'From the 1920s he earned his living largely as a writer for general readers, on philosophy, education, marriage, religion and politics. He married four times, ran a progressive school with his second wife, Dora, and won the Nobel Prize in Literature in 1950. In his last decades he was above all a campaigner against nuclear weapons. He died in Wales in 1970, aged 97. In the prologue to his autobiography he named three passions that had governed his life: the longing for love, the search for knowledge, and an unbearable pity for human suffering.',
    ],
    context: [
      'When Russell began to think seriously about philosophy, in the 1890s, British universities were dominated by a form of idealism that held that the world as we perceive it is somehow unreal. At the same time mathematics was in turmoil. New geometries had shown that Euclid was not the only possibility, and mathematicians such as Cantor, Peano and Frege were trying to put numbers and sets on a secure logical footing. Around 1898–1900 Russell and his friend G. E. Moore broke away from idealism and set out to treat philosophical questions with the clarity and care of the new logic.',
      'His public life was shaped by the wars and the Cold War. He opposed the First World War and was punished for it. In the 1930s he moved away from absolute pacifism and by 1940 he supported the fight against Nazi Germany. After Hiroshima, the prospect of nuclear war became the main concern of his later years, and he spent them organising scientists and ordinary citizens against it.',
    ],
    ideas: [
      { title: 'Mathematics rests on logic', text: 'Russell and Whitehead set out to show that the truths of arithmetic can be derived from a small stock of logical principles, a programme known as logicism. Around 1901 Russell found a paradox in the naive idea of a set: consider the set of all sets that do not contain themselves, and ask whether it contains itself. Either answer contradicts itself. He wrote to the logician Gottlob Frege about it in 1902, and the paradox forced a rethinking of set theory. His own remedy was the theory of types, which sorts statements into levels so that such loops cannot be stated.' },
      { title: 'The theory of descriptions', text: 'In his 1905 paper “On Denoting”, Russell asked how a sentence like “the present King of France is bald” can be meaningful when there is no such king. His answer was to unpack the phrase into a longer statement: there is exactly one king of France, and he is bald. Read this way the sentence is simply false, and it needs no mysterious non-existent king to talk about. The paper is often held up as a model of philosophical analysis, in which a puzzle is dissolved by getting the logical form of a sentence right.' },
      { title: 'Knowledge by acquaintance and by description', text: 'In The Problems of Philosophy (1912) Russell separated what we know directly, such as a colour we are seeing now, from what we know only through descriptions, such as another person’s mind or a distant historical event. Much of what we claim to know, he argued, rests on a chain of inference that begins in direct experience. The book remains one of the most widely read short introductions to philosophy.' },
      { title: 'Logical atomism', text: 'In lectures given in 1918, Russell proposed that the world can be analysed into simple facts, and that a perfect language would mirror their structure. The idea was developed in parallel with Wittgenstein’s early work and influenced the analytic movement. Russell later moved towards neutral monism, the view that mind and matter are both built from the same kind of neutral stuff, arranged in different ways.' },
      { title: 'Doubt, evidence and humane freedom', text: 'In his popular writing Russell defended free inquiry, scepticism about dogma, and tolerance. He criticised religion in a 1927 lecture, “Why I Am Not a Christian”, and argued in his 1932 essay “In Praise of Idleness” that modern societies should work fewer hours. He held that beliefs should be proportioned to evidence, and that cruelty and fanaticism usually come from certainty without reasons.' },
    ],
    principles: [
      'Be clear about what a sentence means before arguing about whether it is true.',
      'Hold beliefs with only as much confidence as the evidence supports.',
      'Follow an argument even when it leads to uncomfortable places, and revise it when a paradox appears.',
      'Treat free thought and the right to dissent as essential, even when the opinions in question are unpopular.',
      'Combine rigorous thinking with compassion for human suffering.',
    ],
    practice: [
      'When an argument seems to prove something absurd, look for the hidden assumption in the wording instead of accepting the absurdity.',
      'Before taking a side, ask what evidence would change your mind and write it down.',
      'Spend time on a subject for its own sake, as Russell did with logic, and notice how it steadies you when public life is noisy.',
    ],
    facts: [
      'Russell said that the discovery of his paradox came while he was working on The Principles of Mathematics. Frege, who received the letter just as his own major work was going to press, acknowledged that it had undermined the foundations of his system.',
      'He wrote his Introduction to Mathematical Philosophy while serving his 1918 sentence in Brixton Prison.',
      'He was awarded the Order of Merit in 1949 and the Nobel Prize in Literature in 1950.',
      'In July 1955 he issued, together with Albert Einstein and other leading scientists, a manifesto warning of the dangers of nuclear war. It led to the first Pugwash Conference on Science and World Affairs in 1957.',
      'In 1961, aged 89, he took part in a Committee of 100 sit-down protest against nuclear weapons and was sentenced to two months in prison, a term reduced on medical grounds to one week.',
      'In 1966–67 he organised a private international tribunal on American conduct in the Vietnam War, which was held in Stockholm and Roskilde and chaired by Jean-Paul Sartre and Vladimir Dedijer.',
    ],
    myths: [
      { myth: 'Principia Mathematica took hundreds of pages simply to prove that 1 + 1 = 2.', reality: 'The book is far more ambitious: it tries to derive large parts of mathematics from logic. The famous equation comes late because the authors had to construct the idea of number from scratch first, and the proof was only one small step in a very long argument.' },
      { myth: 'Russell was a pacifist all his life.', reality: 'He opposed the First World War and went to prison for it, but by 1940 he judged that Nazi Germany had to be resisted by force. After 1945 he campaigned against nuclear weapons, which is a different position from absolute pacifism.' },
      { myth: 'He lost his place at City College of New York because he was an atheist.', reality: 'In 1940 a New York judge annulled his appointment after a citizen sued, ruling that his writings on sex, marriage and religion made him unfit to teach. Russell described his own position on religion, strictly, as agnostic. The case became a famous dispute about academic freedom, with Einstein and many others protesting on his behalf.' },
    ],
    works: [
      { title: 'The Principles of Mathematics (1903)', note: 'His first major statement of the idea that mathematics can be founded on logic.' },
      { title: 'Principia Mathematica (1910–1913), with A. N. Whitehead', note: 'A three-volume formal system for deriving mathematics from logic; difficult to read but very influential.' },
      { title: 'The Problems of Philosophy (1912)', note: 'A short introduction to knowledge, reality and the limits of certainty, written for general readers.' },
      { title: 'Introduction to Mathematical Philosophy (1919)', note: 'A non-technical version of the logicist programme, written in Brixton Prison.' },
      { title: 'A History of Western Philosophy (1945)', note: 'A lively and opinionated survey that became a bestseller; useful as an introduction, though historians dispute many of its judgments.' },
    ],
    legacy: [
      'Russell, with Moore, Frege and later Wittgenstein, is counted among the founders of analytic philosophy, which treats philosophy as a matter of careful argument and logical analysis. His theory of descriptions was challenged, notably by P. F. Strawson in 1950, but it is still a starting point for the study of language and reference. The logical tools developed in Principia Mathematica shaped Kurt Gödel’s work on the limits of formal systems and, more broadly, the early history of mathematical logic and computer science.',
      'Outside the seminar room he became one of the best-known public intellectuals of the century. The 1955 manifesto and the Pugwash movement, which later shared the 1995 Nobel Peace Prize with its co-founder Joseph Rotblat, grew from his insistence that scientists share responsibility for how their discoveries are used. Critics have pointed to inconsistencies in his political positions and to his sometimes careless popular generalisations, but his example of mixing rigorous thought with public courage still shapes the image of the engaged intellectual.',
    ],
  },
  {
    slug: 'martin-heidegger',
    order: 1889,
    dates: '26 September 1889 – 26 May 1976',
    place: 'Messkirch, Germany; taught in Marburg and Freiburg',
    era: '20th Century',
    tradition: 'Phenomenology',
    tagline: 'A thinker who asked what it means to be at all, and whose brilliant work is shadowed by his support for the Nazi regime.',
    who: [
      'Martin Heidegger was born in Messkirch, a small Catholic town in southwest Germany, the son of a church sexton. He was meant for the priesthood and entered a Jesuit seminary in 1909, but was released within weeks because of heart trouble. He then studied theology and philosophy at the University of Freiburg, completed a doctorate in 1914 and a second thesis, on the medieval thinker Duns Scotus, in 1916. After the First World War he became an assistant to Edmund Husserl, the founder of phenomenology.',
      'He taught at Marburg from 1923, where he became a famous lecturer and began a love affair with his student Hannah Arendt, which lasted until about 1928 and which both kept private. In 1927 he published Being and Time, a dense and original book that made him one of the leading philosophers in Germany. In 1928 he returned to Freiburg to take over Husserl’s chair, and he stayed there, apart from invitations he turned down, for the rest of his career. He spent long periods in a small hut at Todtnauberg in the Black Forest, where he liked to write.',
      'In April 1933, just after Hitler took power, Heidegger was elected rector of the University of Freiburg. On 1 May 1933 he joined the Nazi Party and kept his membership until 1945. He gave speeches in support of the new regime, and he resigned the rectorship in April 1934 after disputes with officials over the running of the university. After the war a denazification process led to a ban on his teaching, which was lifted around 1950. Heidegger later described his rectorship as a mistake but never offered a full public account or an explicit repudiation of National Socialism. He died in Freiburg in 1976.',
    ],
    context: [
      'Heidegger’s philosophy grew out of the crisis of Germany after the First World War: a country in political turmoil, and a European culture that seemed to have lost faith in its own certainties. In philosophy, he reacted against the idea that the human being is first of all a detached mind observing a world of objects. He took from Husserl the phenomenological method, which means describing experience as it actually shows itself, and he turned it towards ordinary, practical life rather than pure consciousness. Aristotle, Kierkegaard, Nietzsche and the Christian tradition also left deep marks on him.',
      'His political involvement belongs to the same period. In the early 1930s he shared a widespread conservative hope for a national renewal, and he came to see National Socialism as its vehicle. Historians disagree about how far his philosophy led him there. Since the 1980s, and especially since the publication in 2014 of the first volumes of his private Black Notebooks, written between the early 1930s and the 1970s, which contain anti-Semitic passages, the question of how his thought and his politics relate has been at the centre of debate about his legacy.',
    ],
    ideas: [
      { title: 'The question of Being', text: 'Heidegger believed Western philosophy had long forgotten its most basic question: what does it mean to be? We use the word “is” all the time without knowing what we mean by it. Being and Time begins by trying to ask the question again properly, and it starts with the one kind of being that can ask it: us.' },
      { title: 'Dasein and being-in-the-world', text: 'Heidegger used the German word Dasein, which means “being there”, for the human way of existing. We are not first of all minds that look out at objects. We are always already involved in a world of tasks, tools, people and meanings. A hammer is first encountered as something to hammer with, “ready-to-hand”, and only when it breaks do we step back and look at it as a mere thing, “present-at-hand”.' },
      { title: 'The “they” and authenticity', text: 'In daily life, he said, we mostly do what “one” does, think what “one” thinks, and follow the opinions of anonymous others, which he called das Man, “the they”. This makes life easier but also hides our own responsibility for it. Authenticity means owning one’s existence and choosing from one’s own possibilities. It is not a matter of being unusual, but of not hiding from the fact that one’s life is one’s own.' },
      { title: 'Anxiety, death and time', text: 'Heidegger held that anxiety, unlike fear of a particular threat, reveals that our existence is not secured by anything. Facing our own death, which no one else can die for us, throws us back on ourselves and makes a whole life visible. This is why he linked the meaning of Dasein with time: we live by projecting ourselves into the future, carrying our past, and acting in the present.' },
      { title: 'Technology and dwelling', text: 'In his later work, often described as a “turn” after the 1930s, Heidegger paid less attention to the individual and more to how Being shows itself in different historical ages. In essays such as “The Question Concerning Technology” (1954) he argued that modern technology is not merely a set of tools but a way of seeing everything as resource to be stored and used, which he called Gestell, or “enframing”. He looked to poetry, art and what he called dwelling as other ways of letting things appear.' },
    ],
    principles: [
      'Ask the most basic questions again, even ones that seem too obvious to ask.',
      'Describe how things actually show up in lived experience before building theories.',
      'Do not assume you are a detached observer: you are always already involved in a world.',
      'Watch for the pull of “what one does” and ask what you would choose if the choice were truly yours.',
      'Treat your own mortality as a clue about how to live, not only as something to fear.',
    ],
    practice: [
      'Next time a familiar tool fails, such as a phone or a pen, notice how suddenly it shows up as an object and how it had disappeared into your activity before.',
      'Pick one habit you follow because it is expected. Ask whether you would choose it on your own, and decide knowingly either to keep or to change it.',
      'Spend a few minutes in a technology-free setting, such as a walk or a meal, and notice how things appear when you are not trying to optimise them.',
    ],
    facts: [
      'Being and Time was published in 1927 in the journal edited by Husserl. It was planned as a much larger work, and its second half was never written as planned.',
      'Dasein is an ordinary German word for existence. Heidegger took it literally as “being there” and made it his technical term for the human way of being, and in later writings he sometimes spelled it with a hyphen, “Da-sein”, to stress that sense.',
      'The Spiegel interview in which he discussed his political past was given in 1966 but published only after his death, on 31 May 1976, under the title “Only a God Can Save Us”.',
      'The poet Paul Celan visited him at Todtnauberg in July 1967, and later wrote a poem named after the place.',
      'The complete edition of his writings, the Gesamtausgabe, began to appear in 1975 and runs to more than a hundred volumes.',
      'After the war he wrote a letter to the French philosopher Jean Beaufret, published in 1947 as the “Letter on Humanism”, in which he separated his thought from Sartre’s existentialism.',
    ],
    myths: [
      { myth: 'Heidegger was an existentialist like Sartre.', reality: 'Sartre borrowed heavily from Being and Time, but Heidegger rejected the label in the Letter on Humanism. He said his concern was the meaning of Being, not human choice and freedom as such.' },
      { myth: 'Being and Time is a book about death.', reality: 'Death is one theme, but the book’s main aim is to uncover the meaning of Being by studying the way human beings exist. Being-toward-death serves that argument.' },
      { myth: 'His Nazi involvement was a brief administrative episode that has nothing to do with his philosophy.', reality: 'The rectorship lasted about a year, but Heidegger remained a party member until 1945 and wrote supportive texts in these years. The Black Notebooks show that some of his private reflections contained anti-Semitic claims. Scholars disagree about how far his philosophy is tainted by this, and the question remains open.' },
    ],
    works: [
      { title: 'Being and Time (1927)', note: 'His major early work on Dasein, time, anxiety and authenticity. Famously hard to read, and unfinished.' },
      { title: 'Introduction to Metaphysics (lectures of 1935, published 1953)', note: 'A course on the question “why is there something rather than nothing?”, which also contains remarks that are controversial in light of his politics.' },
      { title: 'Contributions to Philosophy (written in the late 1930s, published 1989)', note: 'A private work that is central to his later thought.' },
      { title: 'Letter on Humanism (1947)', note: 'A response to Sartre and to French readers, containing the claim that “language is the house of Being”.' },
      { title: 'The Question Concerning Technology (1954)', note: 'His best-known essay on how technology shapes the way things appear to us.' },
    ],
    legacy: [
      'Heidegger’s influence on twentieth-century thought is hard to overstate. Sartre, Arendt, Gadamer, Levinas, Merleau-Ponty, Foucault and Derrida all drew on him, often critically. His analysis of practical, embodied involvement in the world shaped existentialism, hermeneutics, and later debates in the philosophy of technology, psychology, architecture and artificial intelligence. Hubert Dreyfus, for example, used him to argue that human skill cannot be reduced to rules.',
      'The man himself remains a problem. Arendt, who was Jewish and had been his student and lover, defended his philosophical stature after the war while criticising his judgment, and many Jewish and other readers have found it hard to separate the thinker from the Nazi. The publication of the Black Notebooks sharpened the debate. Some scholars argue that his thought must now be read with its political side in view, while others hold that its insights remain valuable and that it can be criticised without being dismissed. Few doubt that it must be studied honestly, with both sides on the table.',
    ],
  },
  {
    slug: 'ludwig-wittgenstein',
    order: 1889,
    dates: '26 April 1889 – 29 April 1951',
    place: 'Vienna, Austria; lived mainly in Cambridge, England',
    era: '20th Century',
    tradition: 'Analytic philosophy',
    tagline: 'A philosopher who changed his mind about language so completely that he wrote two masterpieces that seem to argue with each other.',
    who: [
      'Ludwig Wittgenstein was born in Vienna into one of the richest families in the Austro-Hungarian Empire. His father, Karl, was a steel magnate, and the family home was a centre of music and culture. Three of his brothers died by suicide, and the family’s tragedies and high expectations marked him throughout his life. He studied engineering in Berlin and then in Manchester, where he worked on aeronautics. His interest turned from engineering to the foundations of mathematics, and in 1911 he went to Cambridge to study with Bertrand Russell.',
      'He left Cambridge to work alone in Norway, then served in the Austro-Hungarian army throughout the First World War, and was taken prisoner in Italy near the end. During the war he finished the Tractatus Logico-Philosophicus, published in German in 1921 and in English in 1922. He believed that it had solved the main problems of philosophy, and he gave away his inheritance, which went to members of his family. From 1920 to 1926 he worked as a primary school teacher in small Austrian villages, among them Trattenbach, Puchberg and Otterthal. His teaching ended after an incident in 1926 in which a boy collapsed after being struck by him in class. There was a court inquiry, and he left the profession. He also worked briefly as a gardener and helped design a modernist house in Vienna for his sister Margarethe.',
      'In 1929 he returned to Cambridge, where the Tractatus was accepted as his doctoral thesis. His own thinking had begun to shift, and over the following years he came to reject much of his early book. He became a professor in 1939, in the same year that he took British citizenship, and during the Second World War he worked as a hospital porter in London and Newcastle. He resigned his chair in 1947 and died of cancer in Cambridge in 1951. His second major book, Philosophical Investigations, appeared two years after his death.',
    ],
    context: [
      'Wittgenstein’s early work belongs to the revolution in logic led by Frege and Russell, which promised a precise language for science and mathematics. It also grew out of the cultural world of Vienna, where writers and thinkers such as Karl Kraus were concerned with the misuse of language. The Tractatus was an attempt to say exactly what can be said, and so to show the limits of thought.',
      'His later work was written in the 1930s and 1940s, after he had gone back to Cambridge, and it reflects his dissatisfaction with the idea that language has a single hidden logical structure. He now looked at how words are actually used in ordinary life. His style also changed: instead of numbered propositions he wrote short remarks, examples and questions, which he kept revising and which were gathered after his death by his literary executors.',
    ],
    ideas: [
      { title: 'The picture theory', text: 'In the Tractatus, Wittgenstein proposed that a meaningful statement is a kind of picture of a possible state of affairs. It can be true or false because it shares a logical form with the facts it describes. The world, in this early view, is the totality of facts, and the limits of my language, he wrote, mean the limits of my world.' },
      { title: 'Saying and showing', text: 'The Tractatus argues that some things cannot be said but can only be shown, such as the logical form of language, and, in his view, matters of ethics and the meaning of life. The book ends with the line that whereof one cannot speak, thereof one must be silent. Near the end Wittgenstein compares the book’s own propositions to a ladder to be thrown away once one has climbed it.' },
      { title: 'Meaning is use, and language games', text: 'In Philosophical Investigations, Wittgenstein rejected the idea that words get their meaning by standing for objects. Instead, he suggested that the meaning of a word is, in many cases, its use in the language. He compared the many activities in which we use words, such as giving orders, telling stories, joking and praying, to games, which he called language games, each with its own rules and purposes.' },
      { title: 'Family resemblance and rule-following', text: 'Many concepts, such as “game”, have no single feature shared by everything we call by that name. Instead, there are overlapping similarities, like the resemblances among the members of a family. Wittgenstein also asked what it is to follow a rule, and concluded that rule-following is a shared practice, rooted in what he called forms of life, and not a private act of the mind.' },
      { title: 'No private language, and philosophy as therapy', text: 'Wittgenstein argued that a language whose words referred only to a person’s own private sensations could not have the public standards needed to tell correct use from incorrect. His famous image of the beetle in a box makes the point: if everyone has a box that only they can see inside, the thing in it plays no role in the language. He also thought philosophy should not build theories but dissolve confusions, in his words showing the fly the way out of the fly-bottle.' },
    ],
    principles: [
      'Look at how a word is actually used before asking what it “really” means.',
      'Do not expect every concept to have a neat definition; look for overlapping similarities.',
      'Be wary of puzzles that arise when language is taken out of its everyday setting.',
      'Some things are better shown than said.',
      'Be prepared to revise your own earlier thought.',
    ],
    practice: [
      'When a word such as “knowledge” or “fair” causes a dispute, collect several ordinary examples of how it is used rather than hunting for a definition.',
      'When a philosophical problem seems unsolvable, ask whether the question itself uses words in an unusual way, and try restating it in plain terms.',
      'Treat your own past opinions as drafts, and revise them without embarrassment when you see further.',
    ],
    facts: [
      'He arrived at Russell’s rooms in Cambridge unannounced in October 1911. Russell soon decided that he was a genius.',
      'His brother Paul, a concert pianist, lost his right arm in the First World War. Ravel wrote the Piano Concerto for the Left Hand for him.',
      'The Tractatus was published in German in 1921 and in English in 1922, with an introduction by Russell that Wittgenstein felt misunderstood the book.',
      'He worked as a hospital porter and laboratory assistant during the Second World War.',
      'The Philosophical Investigations appeared in 1953, edited by G. E. M. Anscombe and Rush Rhees, with Anscombe’s English translation.',
      'The duck-rabbit drawing, which can be seen as either animal, appears in the second part of the Philosophical Investigations, and he used it to discuss how we see things as something.',
    ],
    myths: [
      { myth: 'Wittgenstein had two completely unrelated philosophies.', reality: 'He rejected many of the Tractatus’s central claims, but both periods deal with the limits of language, the dangers of philosophical confusion, and the aim of clarity. Scholars still debate how far the two periods are continuous.' },
      { myth: 'He was an early positivist who thought metaphysics was nonsense.', reality: 'The Vienna Circle admired the Tractatus and used it, but Wittgenstein thought the most important things, including ethics, lay outside what can be said. For him the silence was not a dismissal but a form of respect.' },
    ],
    works: [
      { title: 'Tractatus Logico-Philosophicus (1921, English 1922)', note: 'His only book published in his lifetime: a compact sequence of numbered propositions on language, logic and the limits of what can be said.' },
      { title: 'Philosophical Investigations (1953)', note: 'His later masterpiece, published after his death, on meaning, rules, private language and the nature of philosophy.' },
      { title: 'The Blue and Brown Books', note: 'Dictations from the early 1930s that show his thinking in transition.' },
      { title: 'On Certainty (published 1969)', note: 'Notes written in the last months of his life about doubt, knowledge and the “hinge” beliefs that we do not question.' },
      { title: 'Culture and Value', note: 'A posthumous selection of his remarks on music, religion, art and his own life.' },
    ],
    legacy: [
      'The Tractatus inspired the logical positivists of the Vienna Circle, and the Investigations shaped ordinary language philosophy and later work in the philosophy of mind and language. His ideas about meaning as use, rule-following and family resemblance have been used in linguistics, psychology, the philosophy of science and the study of religion. Philosophers still argue over how to read his work, and there are many schools of Wittgenstein interpretation.',
      'He also became a cultural figure, famous for his intensity, his austere way of living, and the fact that he turned his back on wealth and, for a time, on philosophy. His posthumous papers, the Nachlass, are now available in a large digital edition, and are still being studied. Even those who disagree with him often accept that he changed the questions philosophers ask about language.',
    ],
  },
  {
    slug: 'jean-paul-sartre',
    order: 1905,
    dates: '21 June 1905 – 15 April 1980',
    place: 'Paris, France',
    era: '20th Century',
    tradition: 'Existentialism',
    tagline: 'The philosopher and writer who told people they are condemned to be free, and who tried to live by it in public.',
    who: [
      'Jean-Paul Sartre was born in Paris in 1905. He lost his father in infancy and was raised largely in the household of his maternal grandfather. He studied at the École Normale Supérieure, the elite training school for French teachers. He failed the national teaching examination in philosophy, the agrégation, in 1928, and passed it first in 1929, with Simone de Beauvoir placed second. They became partners and remained so for the rest of his life, without marrying or, as a rule, sharing a home. They made a pact that their bond was “essential” while allowing other, “contingent” relationships, on condition that they would be honest with each other.',
      'In the 1930s he taught in lycées, spent a year in Berlin reading Husserl and the phenomenological tradition, and published the philosophical novel Nausea in 1938. Called up in 1939, he was captured in 1940 and held as a prisoner of war for about nine months. After his release he returned to Paris, wrote Being and Nothingness (1943) and the play No Exit (1944), and after the liberation of Paris became famous almost overnight. In 1945 he co-founded the journal Les Temps modernes, and in October of that year he gave a lecture, published in 1946 as Existentialism Is a Humanism, which brought the word “existentialism” to the public.',
      'Sartre became more and more politically active. He was never a member of the Communist Party, but for years he was a close ally of it, and he broke with the party after the Soviet invasion of Hungary in 1956. He opposed French colonialism in Algeria, supported the Algerian independence movement, and in 1960 published the Critique of Dialectical Reason, an attempt to reconcile existentialism with Marxism. In the late 1960s he backed Maoist groups and helped run their newspaper. He refused the Nobel Prize in Literature in 1964, saying that a writer should not be turned into an institution. He died in Paris in 1980, and about 50,000 people joined his funeral procession.',
    ],
    context: [
      'Sartre’s ideas took shape between the wars and under the German Occupation of France, a period when ordinary people had to make choices about collaboration, resistance or silence. His philosophy absorbed the phenomenology of Husserl and Heidegger, but its sense of urgency came from these experiences: if there is no fixed script for how to act, each person is responsible for what they do with their freedom.',
      'After 1945, Paris became the centre of a cultural moment in which philosophy, literature and politics mixed. The Cold War forced intellectuals to choose between East and West. Sartre’s choices, particularly his long sympathy for communism, were controversial at the time and have remained so, and they led to the end of his friendship with Albert Camus and to a long quarrel with his former schoolmate Raymond Aron.',
    ],
    ideas: [
      { title: 'Existence precedes essence', text: 'A knife is made with a purpose in mind, so its essence, what it is for, comes before its existence. Sartre argued that human beings are different: we first exist and then make ourselves what we are by our choices. There is no fixed human nature or divine plan that tells us who we are supposed to be.' },
      { title: 'Radical freedom and responsibility', text: 'For Sartre, we are “condemned to be free”: even refusing to choose is a choice. This freedom brings anguish, because no rule or authority can remove the responsibility. When I choose, he said, I choose for everyone in the sense that I show what I think a human being should be.' },
      { title: 'Bad faith', text: 'Bad faith, in French mauvaise foi, is self-deception about one’s own freedom. His best-known illustration is a café waiter who plays his role a little too perfectly, as if he were nothing but a waiter. We act in bad faith when we treat ourselves as fixed things, defined by role, past or character, in order to escape the burden of choice. The opposite mistake is to pretend we have no circumstances at all, and Sartre called these circumstances our facticity.' },
      { title: 'Being-for-itself and being-in-itself', text: 'In Being and Nothingness Sartre contrasted things, which simply are what they are, with human consciousness, which is always aware of itself, can imagine things otherwise, and so is never identical with itself. Consciousness introduces “nothingness” into the world, the ability to say no and to picture what is not there.' },
      { title: 'The look of the other', text: 'In one famous passage he describes being caught looking through a keyhole and suddenly feeling the gaze of someone else. Shame, he says, shows that other people see me as an object, and that I am dependent on them for part of my identity. This idea lies behind the line “Hell is other people” in No Exit, which Sartre later said was often misunderstood: he meant that when our relations with others are distorted, others become hell, not that they always are.' },
    ],
    principles: [
      'You are what you do, not what you intended or what you have been called.',
      'Do not hide behind roles, habits or circumstances: own your choices.',
      'Freedom comes with responsibility, and responsibility extends to others.',
      'Notice how others’ judgments shape you without letting them define you.',
      'Commit to action in the world, not only to thought about it.',
    ],
    practice: [
      'The next time you say “I have no choice”, list the alternatives you are not considering and what each would cost.',
      'Pick one role you play, such as employee, parent or friend, and ask which parts of it you are choosing and which you are hiding behind.',
      'Make one small decision this week deliberately, knowing that you could have decided otherwise.',
    ],
    facts: [
      'While a prisoner of war in 1940, he wrote and staged a Christmas play, Bariona, for his fellow prisoners.',
      'Nausea is set in an imaginary provincial port town and follows a historian, Roquentin, who begins to feel the sheer strangeness of existing things.',
      'The 1945 lecture Existentialism Is a Humanism was given in Paris in October 1945 to a packed hall. Sartre wrote it as a short, accessible defence against critics, and it is more simplified than his big treatise.',
      'He declined the Nobel Prize in Literature in 1964, as he had refused other official honours.',
      'With the Russell Tribunal of 1966–67, he joined Bertrand Russell’s inquiry into American conduct in the Vietnam War and served as one of its presidents.',
      'In his last years he was almost blind, and he worked by dictation and with the help of assistants.',
    ],
    myths: [
      { myth: 'Existentialism is a gloomy philosophy that says life is meaningless.', reality: 'Sartre insisted it was a philosophy of action and responsibility. We are not given meaning, but we can create it through commitment. His claim was that this is demanding, not hopeless.' },
      { myth: 'Sartre and Beauvoir were a conventional couple, or he was her teacher.', reality: 'They never married and usually kept separate homes. Beauvoir was an original philosopher, whose The Second Sex (1949) became a foundation of modern feminism. Their arrangement was admired by some and criticised by others, and later published letters showed that it caused real pain as well as freedom.' },
      { myth: 'Hell is other people means that Sartre disliked everyone.', reality: 'The line is spoken by a character in a play about three people trapped together. Sartre explained that it describes what happens when we depend on others’ judgment of us, not a general verdict on humanity.' },
    ],
    works: [
      { title: 'Nausea (1938)', note: 'A philosophical novel about the sudden sense of the pointless existence of things.' },
      { title: 'Being and Nothingness (1943)', note: 'His main philosophical work on consciousness, freedom, bad faith and relations with others. Long and demanding.' },
      { title: 'No Exit (1944)', note: 'A one-act play in which three characters discover they are in hell together.' },
      { title: 'Existentialism Is a Humanism (1946)', note: 'The best short introduction to his ideas, based on a public lecture.' },
      { title: 'Critique of Dialectical Reason (1960)', note: 'A late attempt to combine existentialism with Marxism. The Words (1964), a memoir of his childhood, is an easier read.' },
    ],
    legacy: [
      'Sartre was the most famous philosopher in the world for a generation, and his image of the committed intellectual, who speaks out on public matters as part of his or her work, shaped debates about the role of writers. His ideas about freedom and responsibility influenced psychology, literature, theology, anti-colonial thinkers such as Frantz Fanon, whose Wretched of the Earth he introduced, and many movements that saw identity as something chosen and made, not given. Beauvoir developed related ideas in her own direction, and the two cannot be understood separately.',
      'His reputation has gone up and down. Structuralists in the 1960s, such as Lévi-Strauss and Foucault, challenged his stress on the free individual. His political record, especially his years of sympathy for the Soviet Union and Maoist groups, has been criticised by Camus, Aron and many later readers, while others admire his support for anti-colonial causes and his refusal of honours. Whatever one thinks of his politics, his insistence that people cannot escape responsibility for what they make of their lives is still one of the most quoted ideas of the century.',
    ],
  },
  {
    slug: 'albert-camus',
    order: 1913,
    dates: '7 November 1913 – 4 January 1960',
    place: 'Mondovi (now Dréan), French Algeria; Algiers; France',
    era: '20th Century',
    tradition: 'Absurdism',
    tagline: 'A writer who asked how to live honestly in a world that gives no answers, and concluded that we must imagine Sisyphus happy.',
    who: [
      'Albert Camus was born in 1913 in Mondovi, in French Algeria. His father, a farm worker, was killed in the First World War in 1914, when Camus was an infant, and he grew up with his deaf and nearly illiterate mother in a poor district of Algiers called Belcourt. A teacher, Louis Germain, noticed his talent and helped him win a scholarship, and Camus later dedicated his Nobel Prize lecture to him. He was a keen footballer and played in goal, until tuberculosis, which he caught at 17, ended that and kept him out of military service.',
      'He studied philosophy at the University of Algiers, worked as a journalist, and wrote and directed for the theatre. After moving to France he took part in the Resistance, editing the underground newspaper Combat. In 1942, while France was occupied, he published two works that made his name: the novel The Stranger and the essay The Myth of Sisyphus. After the Liberation he wrote the novel The Plague (1947) and the essay The Rebel (1951), and a new circle formed around him in Paris, which included Jean-Paul Sartre.',
      'His friendship with Sartre ended in 1952 after a hostile review of The Rebel in Sartre’s journal Les Temps modernes. Camus replied in an open letter and Sartre answered in kind. Camus received the Nobel Prize in Literature in 1957, at 44, one of the youngest winners. He died on 4 January 1960 in a car crash at Villeblevin, in France, aged 46. An unfinished manuscript was found in the wreckage and published in 1994 as The First Man, an autobiographical novel about his Algerian childhood.',
    ],
    context: [
      'Camus belonged to the generation shaped by the Second World War, and his work grew from two experiences: the sunlit poverty of Algiers, and the moral emergency of the Occupation. The first gave him a deep sense of the physical world and a feeling for ordinary people. The second made him ask what, if anything, could justify resistance and what limits should hold even in a fight against evil.',
      'He was also a person of his time and place. As a French Algerian with a working-class background, he felt tied to both communities, and the war of Algerian independence, which began in 1954, put him in a very painful position. In January 1956 he went to Algiers to call for a truce that would protect civilians on both sides. He condemned both the torture used by French forces and the terrorism of the independence movement, and he hoped for a shared future. This brought criticism from many sides. His position, and his remark in 1957 about the risk of bombs on trams in Algiers where his mother might be riding, are still debated.',
    ],
    ideas: [
      { title: 'The absurd', text: 'For Camus, the absurd is the clash between our hunger for meaning and the silence of the world. It is not in the world alone or in us alone, but in the confrontation. The Myth of Sisyphus opens with the claim that the only truly serious philosophical question is whether life is worth living, which means whether to commit suicide.' },
      { title: 'Neither suicide nor false hope', text: 'Camus says there are three ways to respond. One is to end one’s life, which he rejects because it destroys one side of the confrontation. Another is what he called philosophical suicide: escaping the absurd through a leap into faith or a system that promises meaning. The third is to live on while keeping the tension in view, with revolt, freedom and passion.' },
      { title: 'Imagining Sisyphus happy', text: 'In Greek myth Sisyphus is condemned to push a rock up a hill forever. Camus pictures the moment when he walks back down, fully aware of his fate, and says that his scorn for it makes him stronger than his punishment. His famous conclusion is that one must imagine Sisyphus happy: the struggle itself can fill a human heart.' },
      { title: 'Revolt and limits', text: 'In The Rebel, Camus argues that rebellion begins with a refusal: a person says no to an injustice because some value is at stake that belongs to everyone. From this he draws the thought “I rebel, therefore we exist”. Revolt must keep a sense of limits: when it turns into a revolution that kills for an ideal future, it betrays the dignity it began with. This is the core of his argument against political murder, including in the name of communism.' },
      { title: 'Solidarity and common decency', text: 'In The Plague, a doctor and a handful of others fight an epidemic in the Algerian city of Oran, without hope of ultimate victory. Many readers have taken the book as a parable of resistance to Nazism, and Camus himself said as much. The doctor’s ethic is simple: do your job, help the person in front of you, and refuse to accept needless suffering.' },
    ],
    principles: [
      'Face the world as it is, without pretending to a meaning you cannot find.',
      'Revolt against suffering and injustice, but not at any price.',
      'Live fully in the present, with attention to the physical world.',
      'Do not kill for an idea: no cause justifies treating a person merely as a means.',
      'Stand with others in their trouble, even when victory is uncertain.',
    ],
    practice: [
      'When a task feels repetitive or pointless, try Camus’s attitude: notice it fully, and decide to do it with attention and a measure of defiance rather than resentment.',
      'When you feel tempted by an all-explaining ideology or a promise of ultimate meaning, ask what it asks you to ignore.',
      'Choose one concrete, small act of help for someone near you, in the spirit of the doctor in The Plague.',
    ],
    facts: [
      'The Stranger begins with the line “Mother died today”, in the French “Aujourd’hui, maman est morte”, and tells the story of Meursault, a detached man in Algiers who is tried for murder and condemned in part for failing to show conventional grief.',
      'He was awarded the Nobel Prize in Literature in 1957 at the age of 44, the second-youngest recipient at that time and the first born in Africa.',
      'He was a goalkeeper for a university football club in Algiers, and he is reported to have said later that football taught him most of what he knew about morality and obligation.',
      'Camus wrote against the death penalty and published “Reflections on the Guillotine” in 1957.',
      'He and Sartre met in 1943 in occupied Paris, became close friends, and broke with each other in 1952 over The Rebel.',
      'He died in a car driven by his publisher’s relative, Michel Gallimard, and a train ticket was found in his pocket.',
    ],
    myths: [
      { myth: 'Camus was an existentialist.', reality: 'Others placed him with Sartre, but Camus rejected the label as early as 1945 and kept doing so. He thought existentialists were too ready to build systems that claimed to resolve the absurd, whereas he wanted to live inside it.' },
      { myth: 'The absurd means that life is meaningless, so nothing matters.', reality: 'Camus claimed the opposite. The absurd is a starting point, and he used it to argue for honesty, revolt, freedom and solidarity.' },
      { myth: 'Camus ignored colonialism or simply supported French rule.', reality: 'As a young journalist in the 1930s he reported on poverty and injustice among Algeria’s Muslim population, and later he called for reform and equal rights. Critics have nevertheless argued that his fiction treats Arab characters, such as the unnamed man killed in The Stranger, as background figures, and that his hope for a shared Algeria did not reckon with the strength of the independence movement.' },
    ],
    works: [
      { title: 'The Stranger (1942)', note: 'A short novel about Meursault; his best-known work and a central text of absurdist fiction.' },
      { title: 'The Myth of Sisyphus (1942)', note: 'His essay on the absurd and on whether life is worth living.' },
      { title: 'The Plague (1947)', note: 'A novel set during an epidemic in Oran, reflecting on solidarity and resistance.' },
      { title: 'The Rebel (1951)', note: 'A long essay on revolt and political violence, which led to his break with Sartre.' },
      { title: 'The Fall (1956)', note: 'A short monologue by a lawyer in Amsterdam, on guilt and judgment. The First Man, left unfinished, was published in 1994.' },
    ],
    legacy: [
      'Camus is one of the most widely read authors of the twentieth century. His books are taught around the world and have been translated into dozens of languages. The Plague drew a new wave of readers during the COVID-19 pandemic. His idea of the absurd, and his picture of a lucid, defiant and decent person, have influenced writers, philosophers, filmmakers and countless readers who found in him a thinker for ordinary life.',
      'In his own time he was seen by some as a moral compass, and by others as a naive moralist. His break with Sartre has often been read as a contest over means and ends: whether a just cause can justify violence. In recent decades scholars have also examined his Algerian background and his portrayal of Arab characters, as in the work of Edward Said, who criticised the colonial blind spots in his fiction. Both his admirers and his critics return to him because his main question, how to live well without guarantees, has not gone away.',
    ],
  },
]
