import type { Profile } from './types'

export const TWENTIETH_E: Profile[] = [
  {
    slug: 'emil-cioran',
    order: 1911,
    dates: '1911 – 1995',
    place: 'Rășinari, Transylvania, then Paris',
    era: '20th Century',
    tradition: 'Pessimism',
    tagline: 'A sleepless Romanian exile in Paris who turned despair into some of the sharpest, and strangely funniest, prose of the century.',
    who: [
      'Emil Cioran was born on 8 April 1911 in Rășinari, a village near Sibiu in Transylvania, which then belonged to Austria-Hungary and later became part of Romania. His father was an Orthodox priest. He studied philosophy at the University of Bucharest, where he became friends with the future historian of religion Mircea Eliade and the future playwright Eugène Ionesco. From about the age of twenty he suffered from severe insomnia, and he later said that the long, empty nights shaped his whole way of thinking.',
      'His first book, “On the Heights of Despair”, appeared in Romanian in 1934, when he was in his early twenties, and won a prize for young writers. A scholarship took him to Berlin in 1933–35, and after a year teaching philosophy in a school in Brașov he left Romania in 1937 on a French Institute grant. He settled in Paris and never lived in Romania again. He spent the rest of his life in the Latin Quarter with his companion Simone Boué, whom he met in the early 1940s, living on little money and avoiding official positions.',
      'In 1947 he decided, according to his own account, to stop writing in Romanian and to write only in French. His first French book, “A Short History of Decay” (1949), won the Rivarol Prize in 1950, the only major literary prize he accepted; later reports say he refused several others. He published a series of short, polished books of essays and aphorisms, and he died in Paris on 20 June 1995, after a long illness with Alzheimer’s disease. He is buried in the Montparnasse cemetery.',
    ],
    context: [
      'Cioran belonged to a gifted generation of Romanian intellectuals who grew up in the 1920s and 1930s, when Romania was unstable and many young people were drawn to radical politics. Some, including Eliade, flirted with the far-right Iron Guard, a violent nationalist and antisemitic movement. The fact that Cioran came from this milieu is essential to understanding both his early writing and his later silence about it.',
      'In Paris he found the opposite atmosphere: a postwar culture of existentialism, doubt and literary refinement. Writing in French, a language he learned as an adult and handled with great precision, he adopted the tradition of the French moralists, who wrote in short, pointed fragments. He wrote about decline and disillusion at a time when Europe had good reasons to feel both.',
    ],
    ideas: [
      { title: 'Despair as a starting point', text: 'Cioran treated suffering and doubt as the honest starting point of thought, not as a problem to be cured. He distrusted systems that promise to make life make sense. He wrote about his sleepless nights, the weight of time and the sense that human existence is an accident, but he did it with irony and wit that readers often find consoling.' },
      { title: 'Lucidity has a cost', text: 'He was fascinated by the idea that the more clearly we see, the less we can believe. Awareness, in his view, wears away the illusions that make action easy. Much of his writing is a long argument with his own clear-sightedness: he cannot stop seeing through things, yet he cannot quite live without them.' },
      { title: 'Suicide as a thought that helps one live', text: 'Cioran wrote often about suicide, but mostly as a thought rather than a plan. He suggested that simply knowing one could end one’s life made the burden of living easier to bear. He himself lived to the age of eighty-four, and readers should take these pages as a form of self-therapy and provocation, not as advice.' },
      { title: 'Suspicion of fanaticism and utopia', text: 'In “A Short History of Decay” and “History and Utopia” (1960) he turned against enthusiasm of every kind. He argued that the believer, the ideologue and the utopian share a hunger for certainty that often turns cruel. Many readers see in this a lesson he drew from his own early errors, though he never presented it as a confession.' },
      { title: 'Writing as a way to survive', text: 'For Cioran, putting words on a feeling was a way to master it. His books, which grew shorter and more aphoristic over the years, read like the notes of a man talking himself through the night. The style, elegant and compressed, is part of the argument: even despair can be made beautiful.' },
    ],
    principles: [
      'Be suspicious of anyone who offers a final answer.',
      'Say what you actually feel, and say it exactly.',
      'Beware of enthusiasm that demands that others agree.',
      'Doubt is not a failure of nerve. It can be a form of honesty.',
      'Laugh at the human condition, including your own part in it.',
    ],
    practice: [
      'When you cannot sleep or are low, write down what is in your mind in one precise sentence. Naming a mood exactly often loosens its hold.',
      'Notice when you feel absolute certainty. Ask what you would have to ignore in order to feel it.',
      'Read him in small doses. His books are meant to be picked up and put down, and they work best when you let the lines stay with you for a while. If despair feels more than literary, talk to someone.',
    ],
    facts: [
      'He wrote six books in Romanian and, from 1949, around ten in French.',
      'In Berlin in 1933–35 he read German philosophy closely, including Kant, Hegel, Husserl, Schopenhauer and Nietzsche. Nietzsche remained a lasting influence on his style.',
      'Cioran accepted the Rivarol Prize in 1950 and, reports say, turned down other major French literary prizes.',
      'His friends in Paris included Ionesco and the poet Paul Celan, and he knew Samuel Beckett and Henri Michaux.',
      'His notebooks, kept from 1957 to 1972, were published in French after his death, in 1997.',
      'In the 1990s a heavily revised edition of his youthful Romanian book “The Transfiguration of Romania” appeared with passages he called extreme or foolish removed.',
    ],
    myths: [
      { myth: 'Cioran was a nihilist who urged readers to kill themselves.', reality: 'He wrote about suicide as a thought that made life more bearable and lived to a great age. His books are a literary exercise in lucidity and bleak humour, not a recommendation of any course of action.' },
      { myth: 'His political past was a youthful phase that he simply forgot.', reality: 'In the 1930s he wrote admiringly of Hitler and of the Iron Guard, and his book “The Transfiguration of Romania” (1936) argued for a radical, authoritarian remaking of Romania. Later in life he called this the folly of his youth and rarely spoke of it. Scholars still argue about how complete the break was, and the writings returned to public view in Romania after 1989.' },
      { myth: 'He was a gloomy, withdrawn recluse.', reality: 'He avoided public life and literary prizes, but accounts by friends describe a lively, witty talker, and his books are often very funny.' },
    ],
    works: [
      { title: '“On the Heights of Despair” (1934)', note: 'His first book, written in Romanian, a set of passionate, fragmentary meditations on suffering and insomnia.' },
      { title: '“The Transfiguration of Romania” (1936)', note: 'His most politically damning early work, which he later disowned and revised.' },
      { title: '“A Short History of Decay” (1949)', note: 'His first book in French, a sequence of essays and aphorisms on doubt, fanaticism and exhaustion.' },
      { title: '“The Temptation to Exist” (1956) and “History and Utopia” (1960)', note: 'Essays on fatigue, exile, ideology and the disillusionment of the modern age.' },
      { title: '“The Trouble with Being Born” (1973)', note: 'His best-known book of aphorisms, on birth, time and the strange fact of being alive.' },
    ],
    legacy: [
      'Cioran never founded a school, and he did not want to. His influence has been felt by writers and readers who prize concentrated, honest prose over system-building: he is read by novelists, poets and philosophers, and in the French and Romanian literary worlds he is regarded as a master stylist.',
      'His legacy is also an uneasy one. His writing on despair and fanaticism remains widely admired, while his youthful embrace of the Iron Guard is discussed openly by scholars. Reading him well means holding both facts at once: a brilliant critic of ideological zeal who had once been drawn to it.',
    ],
  },
  {
    slug: 'frantz-fanon',
    order: 1925,
    dates: '1925 – 1961',
    place: 'Martinique, France, Algeria and Tunisia',
    era: '20th Century',
    tradition: 'Anti-colonial thought',
    tagline: 'A psychiatrist from Martinique who joined the Algerian struggle and wrote about what colonialism does to the mind.',
    who: [
      'Frantz Fanon was born on 20 July 1925 in Fort-de-France, Martinique, then a French colony in the Caribbean. His father worked as a customs officer and his mother ran a shop. As a schoolboy he read the poetry of Aimé Césaire, who became an early influence. In 1943 he left Martinique to join the Free French forces, fought in the liberation of France and was wounded and decorated. The racism he met in the army, from soldiers and officers who were supposedly fighting for the same cause, disillusioned him.',
      'After the war he studied medicine and psychiatry in Lyon, finishing in 1951, and trained with the Catalan psychiatrist François Tosquelles, who practised a more humane, community-based kind of care. In 1952 he published “Black Skin, White Masks”, a study of how racism shapes the inner life of Black people in a white-dominated society. He was twenty-seven. At the end of 1953 he took up a senior post at the psychiatric hospital of Blida-Joinville in French Algeria.',
      'There he tried to reform patient care by adapting treatment to local culture, and when the Algerian war of independence began in 1954 he treated both Algerians who had been tortured and Frenchmen who had done the torturing. He made contact with the National Liberation Front (FLN) and, in November 1956, resigned in a letter that said silence had become dishonest. He was expelled from Algeria in early 1957 and went to Tunis, where he wrote for the FLN newspaper “El Moudjahid” and later served the provisional Algerian government as an ambassador in Ghana. Diagnosed with leukaemia in late 1960, he dictated “The Wretched of the Earth” while ill and died on 6 December 1961 at the age of thirty-six in Bethesda, Maryland, where he had gone for treatment. He was buried in Algeria.',
    ],
    context: [
      'Fanon’s life crossed the main fault lines of the French empire: a Caribbean colony proud of being French and yet treated as inferior, a metropole that celebrated liberty and tolerated racism, and Algeria, which France treated as part of its own territory while the Algerian majority was denied equal rights. The war of 1954–62 was brutal, and the use of torture by French forces caused scandal in France itself.',
      'These years were also the height of decolonisation, when country after country in Asia and Africa broke away from European rule. Fanon wrote with the Cold War in the background and with a deep interest in what would come after independence: who would rule, and whether the new states would serve their people or a new elite.',
    ],
    ideas: [
      { title: 'Colonialism is a psychological as well as a political wound', text: 'In “Black Skin, White Masks” Fanon described how a Black person in a white-ruled world is forced to see himself through the eyes of others. One famous scene tells of a child on a French train who points and cries out “Look, a Negro!”, and he describes the shock of being turned into an object. His psychiatric training led him to treat this as a real injury, not just an attitude.' },
      { title: 'The colonial world is divided in two', text: 'In “The Wretched of the Earth” he described the colony as a world cut in two by force, with separate zones, different rules and different treatment for settlers and natives. Such a world, he argued, cannot be reformed by polite requests alone, because it rests on a denial of the colonised person’s humanity.' },
      { title: 'Violence and its limits', text: 'Fanon wrote that decolonisation is always a violent process, and he defended the colonised people’s right to resist by force. He saw armed struggle as a way for the colonised to recover self-respect and agency. Critics, including the political thinker Hannah Arendt, have argued that he or his admirers romanticised violence, while others point out that his book also records the mental illness that war caused in both Algerians and Frenchmen. The debate over what he really meant has never ended.' },
      { title: 'The pitfalls of national consciousness', text: 'Fanon warned that independence could fail. A native middle class might simply take the place of the colonisers, copy their habits and leave the poor as badly off as before. He called for political education of ordinary people, in the countryside as well as the cities, so that independence would change how society was run.' },
      { title: 'A new humanism', text: 'Near the end of his last book he urged the newly independent peoples not to imitate Europe but to invent something new, a human relationship that does not rank people by race. His final pages express the hope that freedom would be shared, and not simply seized.' },
    ],
    principles: [
      'Take seriously what a system does to the way people see themselves.',
      'Look at the actual conditions of life, not only at the slogans.',
      'Beware of liberation that only replaces one elite with another.',
      'Support thought with action: Fanon moved from the clinic to the revolution.',
      'Measure a society by how it treats its poorest and most excluded.',
    ],
    practice: [
      'When you meet an unfair expectation, ask whose standard is being treated as the norm, and whose experience is being left out.',
      'Listen first to people who actually live with a problem, as Fanon did with his patients, before proposing solutions.',
      'When you read his chapter on violence, do not stop at the quotation that suits you. Read the whole argument, and read his critics too.',
    ],
    facts: [
      'The book he planned as his doctoral thesis in Lyon was reportedly turned down by the university. It was published instead as “Black Skin, White Masks” in 1952, with the title chosen by his editor Francis Jeanson.',
      'He was awarded the Croix de Guerre for his service in the Free French forces in 1944.',
      'Jean-Paul Sartre wrote the famous preface to “The Wretched of the Earth” after meeting Fanon in Rome in 1960.',
      'The French government censored the book soon after its publication.',
      'In Tunis he lectured to officers of the Algerian liberation army and wrote for “El Moudjahid”. His articles were collected after his death in “Toward the African Revolution” (1964).',
      'He was admitted to hospital in the United States under an assumed name, and accounts of the circumstances of his treatment there remain disputed.',
    ],
    myths: [
      { myth: 'Fanon was an Algerian.', reality: 'He was born in Martinique and trained in France. He took up the Algerian cause by choice, and Algeria honoured him as one of its own.' },
      { myth: 'Fanon was just a theorist of violence.', reality: 'Violence is one chapter of one book. He was a practising psychiatrist, a writer on racism and culture, and a diplomat. His case studies in “The Wretched of the Earth” show war’s damage to minds, and his last pages call for a new humanism.' },
      { myth: 'Fanon wrote that every act of violence is justified.', reality: 'His argument is about colonial rule and the situation of the colonised, in a specific historical moment. Readers disagree about how far it can be generalised, and many scholars read him as more ambivalent than his famous Sartre preface.' },
    ],
    works: [
      { title: '“Black Skin, White Masks” (1952)', note: 'His first book, a mix of psychiatry, philosophy and personal testimony about racism.' },
      { title: '“A Dying Colonialism” (1959)', note: 'An account of how Algerian society changed during the war, including the changing meaning of the veil and the role of radio and medicine.' },
      { title: '“The Wretched of the Earth” (1961)', note: 'His last and most influential work, with a preface by Sartre, on violence, national consciousness, culture and the mental toll of war.' },
      { title: '“Toward the African Revolution” (1964)', note: 'Posthumous collection of essays and articles from his years in Tunis.' },
    ],
    legacy: [
      'Fanon’s books travelled quickly through the movements of the 1960s and later: African anti-colonial leaders, the Black Panthers in the United States and Steve Biko’s Black Consciousness movement in South Africa all read him. In universities he became a founder of postcolonial studies, and writers such as Edward Said drew on his work.',
      'His reputation remains contested. Admirers see in him a rare mix of clinician, witness and thinker who named how racism and empire work on the mind. Critics question his views on violence, and some have pointed to blind spots in his writing about women. Read as a whole, his writing is more uneven, and more searching, than the slogans that have been taken from it.',
    ],
  },
  {
    slug: 'merab-mamardashvili',
    order: 1930,
    dates: '1930 – 1990',
    place: 'Gori, Georgia; Moscow and Tbilisi',
    era: '20th Century',
    tradition: 'Georgian and Soviet philosophy',
    tagline: 'A Georgian philosopher who taught in Moscow and Tbilisi that being human is an effort, and that truth stands above the fatherland.',
    who: [
      'Merab Mamardashvili was born on 15 September 1930 in Gori, Georgia. His father was a military officer, and the family moved between several Soviet cities in his childhood before returning to Tbilisi during the Second World War. In 1949 he went to Moscow to study philosophy at Moscow State University. He belonged to a lively circle of young Moscow philosophers in the 1950s, which included the Moscow Logical Circle, and he worked on the journal “Voprosy filosofii” (“Problems of Philosophy”) in the late 1950s.',
      'From 1961 to 1966 he lived in Prague, working as an editor at the communist journal “Problems of Peace and Socialism”. He then returned to Moscow, taught and wrote, and from 1968 was again at “Voprosy filosofii”, where he was a deputy editor. His career was repeatedly interrupted. He was reportedly barred from travelling abroad for about twenty years after an unsanctioned trip to France in the 1960s, his teaching at Moscow University stopped in the early 1970s, and in 1974 he was forced out of the journal. For the next six years he worked at the Institute of the History of Science and Technology. He later said that he lived from one banned lecture course to the next. He rejected the label of dissident.',
      'In 1980 he moved to Tbilisi, where he worked at the Institute of Philosophy and lectured at Tbilisi State University. His public lecture courses there, on Descartes, Kant and Proust and later on the nature of thought itself, drew large audiences. Away from the official institutions he spoke largely without a written text, thinking aloud before his audience, and the recordings that circulated made the lectures known well beyond the lecture hall. In his last years he entered politics through argument: he opposed the rising Georgian nationalism of Zviad Gamsakhurdia and was attacked for it. He died of a heart attack on 25 November 1990, at the age of sixty, at Vnukovo airport near Moscow, on his way home to Tbilisi. He was buried in Tbilisi.',
    ],
    context: [
      'Mamardashvili belonged to the generation formed by Stalin’s death and the cultural thaw that followed. Soviet philosophy was officially Marxism-Leninism, a doctrine with fixed answers. Anyone who wanted to think freely had to read in secret, with whatever books came to hand, and to find small groups of friends. Mamardashvili read Descartes, Kant, Proust and the Western philosophers that the official curriculum could not ignore but preferred to control.',
      'The last years of his life were a time of upheaval in Georgia. Soviet troops killed about twenty demonstrators in Tbilisi on 9 April 1989, the independence movement grew, and in October 1990 Gamsakhurdia’s bloc won the elections to the republic’s Supreme Council. Gamsakhurdia became its chairman on 14 November 1990, eleven days before Mamardashvili’s death. The Georgian philosopher spoke out at a decisive moment, and the question he raised, what a free country owes to the truth, was not easy to ask.',
    ],
    ideas: [
      { title: 'Consciousness is an effort', text: 'Mamardashvili held that consciousness is not a thing a person simply has, like a hand. It is an event that must be brought about again and again, and a person becomes human only through this effort. In this reading, being human is a task, and also a risk, since the effort can be dropped. It is one of the most repeated themes of his lectures.' },
      { title: 'Thought under prohibition', text: 'The title of his conversations with the French scholar Antoine Épelboin, recorded for French radio in 1989 and published in French in 1991, can be rendered “Thought under Prohibition” (the French title is “La pensée empêchée”). In them he described how the Soviet system tried to control language itself and to prevent real thinking. He also called philosophy “consciousness aloud”, a spoken, public form of thinking that cannot remain silent.' },
      { title: 'Philosophy as an act, in Descartes, Kant and Proust', text: 'He did not teach the history of philosophy as a set of doctrines. In the “Cartesian Meditations” he read Descartes’s “I think” as something a person has to do, not a proposition to be memorised. In the lectures on Proust, published as “Psychological Topology of the Path”, he read the novel as the story of a person learning to be present to his own life. Both were ways to show his audience what thinking looks like in practice.' },
      { title: 'Civil society and law', text: 'In the late 1980s he argued that a free society is not just a matter of removing the old regime. It needs citizens who take personal responsibility and who keep to rules and law even when no one is watching. In his view, a state built only on belonging to a nation or party cannot create this.' },
      { title: 'Truth stands above the fatherland', text: 'At a congress of the Georgian Popular Front in 1989, he said that truth is higher than the homeland, because what we take for the homeland’s interests may not be its interests at all. He was reportedly heckled and left the platform, then returned and repeated it. He later said that if his people followed Gamsakhurdia he would have to oppose them, according to Russian-language accounts. He was not rejecting Georgia, but insisting that love of country must answer to conscience.' },
    ],
    principles: [
      'Being human is an effort that must be renewed again and again.',
      'Think for yourself, and take responsibility for what you think.',
      'Truth and conscience come before loyalty to any group, including your own.',
      'A free society rests on law and on persons who keep it inwardly.',
      'Philosophy is not the repeating of doctrines but a way of being awake.',
    ],
    practice: [
      'Take a thought you hold and try to say it aloud as if to a stranger. Where you cannot, you may find that you have not yet thought it.',
      'Read a book slowly, like his students reading Proust, and ask what it is asking of you, not only what it says.',
      'When a group you belong to is certain, ask the question his Popular Front speech asked: is this really in our interest, and is it true?',
    ],
    facts: [
      'Most of his work was spoken and not written. Students recorded his lecture courses, and the books that carry his best-known ideas, such as “Cartesian Meditations” (published 1993) and “Psychological Topology of the Path” (published 1997), are edited transcripts that he never prepared for print himself.',
      'During his lifetime he published only a few books, among them “Forms and Contents of Thinking” (1968) and “Symbol and Consciousness”, written with Alexander Piatigorsky and published in Jerusalem in 1982.',
      'The French historian of antiquity Jean-Pierre Vernant is reported to have called him the “Georgian Socrates”. The comparison, which stuck, rests on his habit of teaching by talk, his refusal to write a system, and his stand for conscience.',
      'He had a first heart attack in 1989. Russian sources say he died near the passport control at Vnukovo airport.',
      'His last course at Tbilisi State University, “Conversations about Philosophy”, ended with a lecture on 10 November 1990, fifteen days before his death.',
      'A monument to him by the sculptor Ernst Neizvestny was unveiled in Tbilisi in 2001.',
    ],
    myths: [
      { myth: 'Mamardashvili was an anti-Georgian cosmopolitan.', reality: 'He insisted on being a Georgian and a European at once. His quarrel with Gamsakhurdia’s movement was about whether a nation’s claims outrank the truth. He joined the National Congress, a rival independence movement, in 1990, so he was not against independence.' },
      { myth: 'He was a Soviet dissident.', reality: 'He refused the label. He worked in Soviet institutions, was removed from several of them, and described his own work as thinking in a system that tried to prevent it.' },
      { myth: 'His death was caused by the nationalists.', reality: 'The official cause is a heart attack, and he had had a previous one. His friends linked his health to the stress of the attacks on him. The published accounts we found agree on a heart attack and do not reliably suggest anything else, so it is wise to separate grief and blame from established fact.' },
    ],
    works: [
      { title: '“Forms and Contents of Thinking” (1968)', note: 'His first monograph, a study of how thought is shaped.' },
      { title: '“Symbol and Consciousness” (published 1982, with Alexander Piatigorsky)', note: 'A dense joint work on consciousness, symbol and language, finished in the 1970s and printed in Jerusalem.' },
      { title: '“Cartesian Meditations” (lectures of the 1980s, published 1993)', note: 'A transcript of lectures on Descartes and the nature of thinking.' },
      { title: '“Psychological Topology of the Path” / Lectures on Proust (lectures 1984–85, published 1990s)', note: 'The Proust course, widely seen as the best entry point to his spoken style.' },
      { title: '“A Spy for an Unknown Country” (English, 2020)', note: 'A selection of his essays and lectures in English. Much of his work is still not translated.' },
    ],
    legacy: [
      'In Georgia and Russia, Mamardashvili became a moral figure after his death. His lectures were published and discussed, and his phrase about truth and the fatherland is still quoted in arguments about nationalism and civic life. In Tbilisi his reputation was long complicated by the politics of the 1990s, and writers have noted that he was not always welcomed by those in power.',
      'Outside the post-Soviet world he remains little known, partly because so few of his lectures exist in translation, and partly because they were never meant to be read as finished books. His main legacy is an example: a thinker who made philosophy a spoken, public act, held to it under pressure, and asked his listeners to think for themselves.',
    ],
  },
]
