import type { Profile } from './types'

export const TWENTIETH_B: Profile[] = [
  {
    slug: 'erich-fromm',
    order: 1900,
    dates: '23 March 1900 – 18 March 1980',
    place: 'Frankfurt, Germany; later New York, Mexico and Switzerland',
    era: '20th Century',
    tradition: 'Humanistic psychoanalysis',
    tagline: 'A psychoanalyst who asked why free people give up their freedom, and why love has to be learned.',
    who: [
      'Erich Fromm was born in Frankfurt in 1900, the only child of an Orthodox Jewish family. He studied law, then sociology, and took his doctorate at Heidelberg in 1922. In the 1920s he trained as a psychoanalyst, and he began to practise in 1927. His first wife, Frieda Reichmann, was a psychoanalyst who had been his teacher; they separated soon after they married in 1926 and divorced in 1942. He gradually moved away from the Orthodox faith of his youth, although he kept a lifelong interest in the Hebrew prophets and in mystical traditions.',
      'In 1930 he joined the Institute for Social Research in Frankfurt, the group later known as the Frankfurt School, as its expert on psychology. After the Nazis took power he left Germany and in 1934 reached the United States, where he worked at Columbia University and later taught at Bennington College and the New School. In 1939 his formal link with the Institute ended, after disagreements with its director Max Horkheimer and others, partly over how far to follow Freud’s theory of the sexual drive, and partly over money and institutional matters. He co-founded the William Alanson White Institute in New York in 1946.',
      'From around 1950 he lived in Mexico, teaching at the National Autonomous University in Mexico City and training psychoanalysts. In the 1950s and 1960s he also became a public figure. He wrote widely read books for general readers and took part in the peace movement in the United States. He moved to Switzerland in 1974 and died in Muralto, near Locarno, a few days before his eightieth birthday.',
    ],
    context: [
      'Fromm grew up in a Germany shaken by the First World War, inflation and political violence. Before leaving, he was part of the effort in Frankfurt to combine Marx and Freud: to ask how a society’s economy shapes the way people feel and think, and why so many workers who might have been expected to resist the Nazis did not. Around 1930 he took part in a survey of the attitudes of German workers and employees, which tried to measure the gap between their stated politics and their deeper character.',
      'Escape from Freedom was written during the Second World War, when democracy in Europe seemed on the point of collapse. After the war Fromm turned his attention to a different worry: that wealthy, peaceful democracies were producing their own kind of conformity, with people learning to treat themselves as products and to measure their lives by consumption. His books of the 1950s and 1960s were written for a reading public that was ready for such questions.',
    ],
    ideas: [
      { title: 'The fear of freedom', text: 'In Escape from Freedom (1941) Fromm argued that modern people have won freedom from old authorities such as the church, the guild and the lord, but that this “freedom from” can feel like isolation and anxiety. Unless they can use their freedom to build something of their own, many people try to escape it. He described three main ways: submitting to a strong authority, destroying what they fear, or quietly copying everyone else. He used this idea to help explain the appeal of Nazism, and warned that conformity could work the same way in democracies.' },
      { title: 'Social character', text: 'Fromm held that each society shapes the typical character of its members, so that people come to want to do what the society needs them to do. In Man for Himself (1947) he described several character orientations, including the “marketing orientation”, in which people experience themselves as goods to be sold and judge their worth by how well they sell. In contrast, the “productive orientation” means using one’s powers of reason, love and creativity.' },
      { title: 'Love is an art', text: 'The Art of Loving (1956) argues that most people treat love as a matter of being loved, of finding the right object, instead of a capacity that must be developed. Real love, Fromm said, shows itself in care, responsibility, respect and knowledge of the other person, and it takes discipline, concentration and patience, as any art does. He also discussed love between parents and children, love of neighbours, erotic love, self-love and love of God.' },
      { title: 'To have or to be', text: 'In To Have or to Be? (1976) Fromm distinguished two ways of living. In the “having” mode we relate to the world, to others and even to ourselves as things to possess and control. In the “being” mode we are alive, active and open to what is in front of us. He saw the first as dominant in industrial society and thought that it left people anxious and empty.' },
      { title: 'A society can be unhealthy', text: 'In The Sane Society (1955) Fromm argued that whole societies can be unhealthy even when most of their members fit in well, because well-adjusted people may simply have adapted to something harmful. In his later work he contrasted “biophilia”, love of life and growth, with “necrophilia”, an attraction to what is dead, mechanical or controlling. The Heart of Man (1964) and The Anatomy of Human Destructiveness (1973) explore these themes.' },
    ],
    principles: [
      'Freedom is not only being free from control, but being free to do something worthwhile with your life.',
      'Do not judge your worth by how well you sell yourself.',
      'Love is a practice, not only a feeling, and it takes effort.',
      'Ask whether you are living by having or by being.',
      'Being well-adjusted to a society does not prove that you or the society are healthy.',
    ],
    practice: [
      'Notice when you are agreeing with others out of habit or fear. Ask what you would think if nobody were watching.',
      'Treat love like a skill: set aside regular time to listen to someone fully, without planning your reply.',
      'Next time you buy something, ask what you hope it will give you, and whether it is a thing you can have or an experience you could have by being.',
    ],
    facts: [
      'The British edition of Escape from Freedom was called The Fear of Freedom.',
      'The Art of Loving became one of his best known books and sold in the millions in many languages.',
      'In 1955–56 he and the philosopher Herbert Marcuse argued in the journal Dissent, after Marcuse attacked Fromm’s revision of Freud.',
      'He co-wrote Zen Buddhism and Psychoanalysis (1960) with D. T. Suzuki and Richard De Martino, after a meeting in Mexico.',
      'His 1961 book Marx’s Concept of Man included a translation of Marx’s early manuscripts, which he wanted to bring to a wider public.',
      'He took part in the American peace movement of the late 1950s and was a founder of the group SANE, which campaigned against nuclear weapons testing.',
    ],
    myths: [
      { myth: 'The Art of Loving is a how-to guide for romance.', reality: 'It is closer to social criticism. Fromm argues that modern society, which values buying and selling, makes love hard, and he offers no tricks for finding a partner.' },
      { myth: 'Fromm was a pure follower of Freud.', reality: 'He trained as a Freudian but rejected much of Freud’s theory of drives and stressed the effect of society on character. Marcuse accused him of draining psychoanalysis of its radical force, while Fromm replied that Marcuse’s view was a bleak and harmful one. The disagreement was bitter and has never been fully settled.' },
      { myth: 'Fromm’s ideas are only popular psychology, with no serious grounding.', reality: 'His early work was part of the Frankfurt School’s research, and his writing draws on Marx, Freud and the Jewish and Christian mystics. Critics do argue that some of his later claims, such as those on human nature and on necrophilia, are broad and hard to test.' },
    ],
    works: [
      { title: 'Escape from Freedom (1941)', note: 'His study of why people give up freedom, with the rise of Nazism as a central example.' },
      { title: 'Man for Himself (1947)', note: 'Character types and an ethics based on human growth.' },
      { title: 'The Sane Society (1955)', note: 'A critique of modern capitalist society and a proposal for a more humane one.' },
      { title: 'The Art of Loving (1956)', note: 'His most widely read book, on love as a skill.' },
      { title: 'To Have or to Be? (1976)', note: 'A late statement on two modes of existence.' },
    ],
    legacy: [
      'Fromm helped make psychoanalysis part of public conversation, and he showed that questions about politics, work and love can be asked together. His writing influenced humanistic psychology and later thinking about consumer culture, authoritarianism and loneliness. His books have stayed in print for decades, and societies in several countries still study his work.',
      'He remains a disputed figure. Some scholars see him as a neglected pioneer of critical theory who was pushed out of the Frankfurt School for reasons that were partly personal, while others find his arguments too general. Whatever the verdict, his central question, why people so often choose to give up freedom, is still asked.',
    ],
  },
  {
    slug: 'karl-popper',
    order: 1902,
    dates: '28 July 1902 – 17 September 1994',
    place: 'Vienna, Austria; later Christchurch, New Zealand, and London',
    era: '20th Century',
    tradition: 'Philosophy of science',
    tagline: 'He said that science advances by trying to prove itself wrong, and that open societies do the same.',
    who: [
      'Karl Popper was born in Vienna in 1902. His father, Simon, was a lawyer with a large library, and the family, of Jewish origin, had converted to Lutheranism. Popper left school early. He trained as a cabinetmaker, and as a young man he worked as a volunteer in clinics for children run by the psychoanalyst Alfred Adler. In 1919 he briefly became a Marxist, but turned away from it after a clash in June 1919 in which police shot unarmed members of his own group.',
      'He studied at the University of Vienna and took a doctorate in psychology in 1928. He taught mathematics and physics in secondary schools, married Josefine Henninger in 1930 and published his first major book, Logik der Forschung (The Logic of Scientific Discovery), in 1934. In 1937, with Nazi power growing in Central Europe, he took a post at Canterbury University College in Christchurch, New Zealand, where he wrote The Open Society and Its Enemies.',
      'In 1946 he moved to the London School of Economics and became a professor of logic and scientific method in 1949, a post he held until 1969. He was knighted in 1965 and continued to write and lecture into his eighties. He died in 1994 near London.',
    ],
    context: [
      'Popper’s Vienna was the home of the Vienna Circle, a group of philosophers and scientists who believed that a statement is meaningful only if it can be verified by experience. Popper thought this view was mistaken, and he was sometimes described as the Circle’s “official opposition”. A decisive influence on him was the contrast between Einstein’s theory of relativity, which made a bold prediction that could have failed (and which a 1919 eclipse expedition supported), and the theories of Freud, Adler and Marx, which in his opinion could explain any event whatsoever.',
      'His political thinking came from living through the collapse of democracy in Europe. He had seen Marxist and fascist movements in Vienna, and he wrote The Open Society during the Second World War, in his words as a contribution to the war effort. Both his philosophy of science and his politics ask the same question: how can we protect ourselves from being certain and wrong?',
    ],
    ideas: [
      { title: 'Falsifiability', text: 'Popper proposed that what makes a theory scientific is that it can, in principle, be shown false by observation. No number of white swans can prove that all swans are white, but a single black swan refutes it. A theory that rules out nothing, because it can explain any outcome, is therefore not scientific, however impressive it may sound. He called this the problem of demarcation: telling science from non-science.' },
      { title: 'Conjectures and refutations', text: 'We never start from certainty. Knowledge grows when people make bold guesses and then try hard to refute them, so that error is gradually eliminated. Popper argued that no amount of observation can logically prove a general law, an old problem raised by the philosopher David Hume. His answer was that science does not need such proof: it keeps the theories that survive severe tests, while treating them as provisional. His position is called critical rationalism.' },
      { title: 'The open society', text: 'In The Open Society and Its Enemies (1945) Popper argued that a good society is one in which people can criticise their rulers and change policies without violence. He defined democracy mainly as a way of removing bad governments without bloodshed. He preferred “piecemeal” reforms, which can be tested and corrected, to grand utopian blueprints that must be imposed and cannot be questioned.' },
      { title: 'The attack on historicism', text: 'Historicism is the belief that history follows laws that allow us to predict its course. Popper argued that this is impossible, since the future of human history depends on future knowledge, which we cannot know in advance. In The Open Society he traced such thinking in Plato, who described an ideal and unchanging state, in Hegel, who gave history a grand meaning, and in Marx, whose theory of history he accused of claiming to know where society must end up. He thought the idea of a historical destiny encouraged authoritarian politics.' },
      { title: 'The paradox of tolerance and the three worlds', text: 'Popper noted that unlimited tolerance can destroy itself, because tolerating those who will not tolerate anyone can let intolerance win. He suggested that a tolerant society may sometimes need to defend itself, while preferring argument wherever argument is still possible. Later in life he also proposed that reality includes three “worlds”: the physical world, the world of mental experience, and the world of objective human knowledge, such as theories and works of art, which exist as public things.' },
    ],
    principles: [
      'Hold your views as guesses that you are ready to correct.',
      'Look for the evidence that could prove you wrong, not only evidence that supports you.',
      'Be wary of any theory that explains everything.',
      'Prefer small, testable reforms to sweeping plans that cannot be questioned.',
      'A good society keeps ways open to criticise power and remove it peacefully.',
    ],
    practice: [
      'Before arguing for a belief, write down what observation would make you drop it. If nothing could, ask why.',
      'When you plan a change at work or at home, try it on a small scale first and review what happened.',
      'Ask a critic to attack your idea, then thank them for it.',
    ],
    facts: [
      'On 25 October 1946 Popper gave a paper at the Moral Sciences Club in Cambridge, and a heated exchange with Ludwig Wittgenstein is said to have ended with Wittgenstein waving a fireplace poker. Witnesses gave conflicting accounts of what happened.',
      'He never joined the Vienna Circle, though he knew some of its members, and he thought of himself as its critic.',
      'He was married to Josefine Henninger from 1930 until her death in 1985.',
      'The financier George Soros studied under him at the London School of Economics and later named his Open Society Foundations after Popper’s book.',
      'He first called Darwin’s theory of natural selection a “metaphysical research programme” rather than a testable theory, and later said publicly that he had changed his mind.',
      'In 1974 the logicians David Miller and Pavel Tichý showed that Popper’s formal definition of “verisimilitude”, or closeness to the truth, did not work as he had intended.',
    ],
    myths: [
      { myth: 'Popper said a theory is scientific only after it has been proved false.', reality: 'Falsifiability is about whether a theory could be tested and refuted, not about whether it already has been. Theories that survive hard tests are called corroborated, which is not the same as proved.' },
      { myth: 'He showed that psychoanalysis and Marxism are false.', reality: 'He argued they were not properly testable as their followers practised them. He thought Marx’s early predictions were testable and were refuted by events, and that later Marxists then protected the theory with ad hoc explanations.' },
      { myth: 'Popper’s reading of Plato, Hegel and Marx is the accepted view.', reality: 'The Open Society was widely influential, but many scholars of Plato and Hegel argue that Popper read them harshly and sometimes unfairly. Critics also say he sometimes treated Marx’s theory of history as cruder than it was.' },
    ],
    works: [
      { title: 'The Logic of Scientific Discovery (Logik der Forschung, 1934)', note: 'His main work on science: falsifiability, testing and corroboration. The English edition came out in 1959.' },
      { title: 'The Open Society and Its Enemies (1945)', note: 'Two volumes, one on Plato and the other on Hegel and Marx, defending liberal democracy.' },
      { title: 'The Poverty of Historicism (1957)', note: 'A short book against the idea of laws of history, based on essays from the 1940s.' },
      { title: 'Conjectures and Refutations (1963)', note: 'Essays on scientific method, knowledge and politics.' },
      { title: 'Unended Quest (1976)', note: 'An intellectual autobiography.' },
    ],
    legacy: [
      'Falsifiability has become part of how many scientists and the public think about science. It has been used in debates about pseudoscience, and it was cited in a 1982 United States court ruling against teaching creationism as science. The open society, in turn, has become a standard way to describe liberal democracy, and the phrase appears in political debates around the world.',
      'His philosophy of science was challenged from many sides. Thomas Kuhn argued that science works within shared frameworks, called paradigms, and does not constantly try to refute them. Imre Lakatos said that real theories are protected by auxiliary assumptions and proposed that we should judge whole research programmes. Paul Feyerabend went further and doubted that any single method exists. Most philosophers now accept that falsifiability alone is not enough to define science, but few deny that his stress on criticism changed the discussion.',
    ],
  },
  {
    slug: 'hannah-arendt',
    order: 1906,
    dates: '14 October 1906 – 4 December 1975',
    place: 'Linden, near Hanover, and Königsberg, Germany; later Paris and New York',
    era: '20th Century',
    tradition: 'Political philosophy',
    tagline: 'She tried to understand totalitarianism and what it means to act freely with others, and she gave us the phrase “the banality of evil”.',
    who: [
      'Hannah Arendt was born in 1906 in Linden, near Hanover, and grew up in Königsberg in a secular Jewish family. Her father died in 1913, when she was seven. She studied philosophy and theology at Marburg, where she had a love affair with her teacher Martin Heidegger, then attended Husserl’s lectures in Freiburg and wrote her doctorate at Heidelberg under Karl Jaspers on the idea of love in Saint Augustine (1929). Jaspers remained a close friend for life.',
      'After the Nazis came to power she was arrested in Berlin in 1933 while researching antisemitic propaganda, and was held for eight days. She fled to Paris, where she worked with an organisation that helped young Jews emigrate to Palestine. In 1937 she lost her German citizenship, and she was stateless for many years. After marrying Heinrich Blücher in 1940 she was interned briefly in the Gurs camp in France, and in 1941 the couple escaped to the United States.',
      'In New York she worked as an editor and writer, and her first major book, The Origins of Totalitarianism, appeared in 1951. She went on to teach at several American universities, including Chicago, Princeton and the New School in New York, and wrote for journals and magazines. She died at home in New York in 1975, while writing the last part of her final book, The Life of the Mind.',
    ],
    context: [
      'Arendt’s thought was shaped by the experience of statelessness and by the breakdown of Europe. She saw people lose their rights when they lost their country, and she saw that the Nazis and, in another form, the Stalinist regime treated human beings as expendable. She did not believe these events could be explained by the old categories of tyranny or dictatorship, so she tried to understand something new.',
      'She wrote in the early Cold War, when many American and European intellectuals were deciding whether to lean towards one side or the other. She refused to fit into a party or a school. In 1961 the New Yorker sent her to Jerusalem to report on the trial of Adolf Eichmann, a Nazi official who had helped organise the deportation of Jews to the death camps and who was executed in 1962.',
    ],
    ideas: [
      { title: 'Totalitarianism as something new', text: 'In The Origins of Totalitarianism (1951), Arendt argued that Nazi and Stalinist rule differed in kind from older tyranny. Totalitarian regimes combine an ideology that claims to explain all of history with terror directed at whole populations, and they depend on masses of people who are isolated and lonely. She thought the camps showed the logic of the system: they tried to make human beings “superfluous”. She also argued that the stateless, who lost the protection of any state, showed that people need a “right to have rights”, meaning membership in a political community.' },
      { title: 'Labor, work and action', text: 'In The Human Condition (1958), Arendt divided the active life into three kinds of activity. Labor keeps us alive, as in growing food. Work builds lasting things, such as houses and books. Action is what people do and say in front of others, beginning something new and showing who they are. She thought politics belongs to action, and that modern society had made labor and consumption seem more important than action.' },
      { title: 'Natality and plurality', text: 'Arendt’s word “natality” means that every human birth brings a new beginning into the world, and so every person can start something no one expected. “Plurality” means that people are equal as human beings yet each is distinct, and politics exists because many different people share one world. She also described two powers that help action in an unpredictable world: forgiving, which releases us from the past, and promising, which binds us to a shared future.' },
      { title: 'The banality of evil', text: 'In Eichmann in Jerusalem (1963) Arendt described Eichmann not as a monster or a fanatic but as a man who was strikingly shallow, who spoke in clichés and seemed unable to think about what he was doing. She called this “the banality of evil”. She did not mean that evil is common or trivial, or that Eichmann was innocent; she supported his death sentence. She meant that terrible deeds can be done by people who simply stop thinking.' },
      { title: 'Thinking and judging', text: 'In her late work she asked whether thinking, the silent conversation we have with ourselves, can protect people from doing wrong. She suggested that habit and slogans leave us defenceless, while the effort to think and to imagine the viewpoints of others makes us harder to recruit to cruelty. She also wrote about how truth and politics clash, and about how lying in public life attacks the common world that citizens need.' },
    ],
    principles: [
      'Think for yourself, and do not rely on clichés or slogans.',
      'Remember that every person can begin something new.',
      'Politics is acting together in public, not only being governed.',
      'A person without any political community is in danger. Protect the right to belong.',
      'Try to imagine how a situation looks from someone else’s position.',
    ],
    practice: [
      'When you notice yourself repeating a slogan, stop and put the idea in your own words.',
      'Before judging a dispute, say aloud how each side would describe it.',
      'Find one local group, such as a council, a school board or a neighbourhood association, and take part in it.',
    ],
    facts: [
      'Her love affair with Heidegger in 1924–26 was not widely known until after her death. They met again and renewed contact after the war, though she knew of his links with the Nazi party.',
      'A story she told later was that her Gestapo interrogator in 1933 was sympathetic, and she was released.',
      'The Eichmann book began as a series of articles in The New Yorker in February and March 1963.',
      'In a letter to the scholar Gershom Scholem in 1963 she wrote that she did not love peoples or collectives, only her friends.',
      'She wrote her major later works in English, her second language, after arriving in the United States in 1941.',
      'Her unfinished last book, The Life of the Mind, was edited by her friend Mary McCarthy and published in 1978.',
    ],
    myths: [
      { myth: 'Arendt claimed that Eichmann was just following orders and was innocent.', reality: 'She rejected the excuse of obedience, supported the death sentence and insisted that he was responsible. Her point concerned the kind of person he was, rather than whether he deserved punishment.' },
      { myth: 'Arendt blamed the Jews for their own destruction.', reality: 'She criticised the role played by some Jewish councils, which were set up under Nazi pressure and gave lists of people to the authorities, and she did so in a sharp tone that many readers found offensive. Critics said her claims about the councils were unfair or overstated, and the dispute with figures such as Scholem was bitter. She did not hold the victims as a whole responsible for what was done to them.' },
      { myth: 'The banality of evil was a complete account of Eichmann, and later research has confirmed it.', reality: 'Later scholars, such as Bettina Stangneth in 2011, drew on interviews Eichmann gave in Argentina and argued that he was a committed antisemite who played down his role at the trial. Others reply that Arendt’s idea about thoughtlessness and bureaucratic evil still stands, even if her portrait of Eichmann was incomplete. The question remains open.' },
    ],
    works: [
      { title: 'The Origins of Totalitarianism (1951)', note: 'A study of antisemitism, imperialism and the new form of government that grew from them. Later editions added more chapters on ideology and terror.' },
      { title: 'The Human Condition (1958)', note: 'Her philosophical account of labor, work, action and the public world.' },
      { title: 'Eichmann in Jerusalem: A Report on the Banality of Evil (1963)', note: 'Her reporting on the trial, and the most disputed of her books.' },
      { title: 'On Revolution (1963)', note: 'A comparison of the American and French revolutions and what each did to political freedom.' },
      { title: 'The Life of the Mind (1978)', note: 'The unfinished last work, on thinking and willing, with a plan for a third part on judging.' },
    ],
    legacy: [
      'Arendt is read in philosophy, history, law and political science, and also by people who simply want to understand how democracies can fail. Her ideas about statelessness, the public sphere, civil disobedience and the dangers of lying in politics are still widely quoted. Interest in The Origins of Totalitarianism rose again in the 2010s, as many readers turned to it to understand political developments around them.',
      'Her work is also criticised. Some historians say her account of imperialism is Eurocentric and partial, and some political theorists argue that her sharp divide between politics and the economy leaves out questions of poverty and social justice. The Eichmann controversy has never fully faded. Even so, she is widely regarded as one of the most original political thinkers of the twentieth century.',
    ],
  },
  {
    slug: 'simone-de-beauvoir',
    order: 1908,
    dates: '9 January 1908 – 14 April 1986',
    place: 'Paris, France',
    era: '20th Century',
    tradition: 'Existentialism and feminism',
    tagline: 'She argued that womanhood is shaped by society, and that freedom is real only when others are free too.',
    who: [
      'Simone de Beauvoir was born in Paris in 1908 to a middle-class family. Her father, Georges, was a lawyer who loved the theatre, and her mother, Françoise, was a devout Catholic. After the First World War the family lost much of its money, and Simone and her sister Hélène were raised to expect to work. She gave up her religious faith in her teens, studied philosophy at the Sorbonne and in 1929, aged 21, came second in the competitive agrégation exam, behind Jean-Paul Sartre. She was the youngest person to pass it up to then.',
      'She and Sartre became partners that year. They never married and rarely shared a home, and they agreed that their bond would be an “essential” one that allowed other, “contingent”, love affairs, while each promised to be honest with the other. The arrangement lasted until Sartre’s death in 1980. Beauvoir had other significant relationships, including a long affair with the American writer Nelson Algren. In 1980 she legally adopted Sylvie Le Bon, a younger woman who had been her close companion.',
      'She taught in lycées in Marseille, Rouen and Paris, and her teaching career ended in 1943, when she was suspended after the mother of a former pupil, Nathalie Sorokine, complained and she was accused of corrupting a minor. By then her first novel, She Came to Stay, was published (1943). After the war she wrote for and helped to edit the review Les Temps Modernes, and she became a leading public intellectual. She died in Paris of pneumonia in 1986 and is buried beside Sartre in the Montparnasse Cemetery.',
    ],
    context: [
      'France in Beauvoir’s youth was a country where women had very limited legal and political rights. French women could not vote until 1944–45, and married women needed their husbands’ permission for many things until a reform in 1965. The war and the German occupation shaped her adult life, and the years just after it were the high point of French existentialism, the philosophy that stresses freedom, choice and responsibility.',
      'Existentialism held that human beings are not born with a fixed nature but make themselves through their choices. Beauvoir took this seriously, and asked what happens to such a philosophy when applied to women, who for centuries had been told what they were. The Second Sex was her answer, written after a period of research in the libraries of Paris.',
    ],
    ideas: [
      { title: '“One is not born, but rather becomes, a woman”', text: 'This famous sentence from The Second Sex (1949) says that what society calls “femininity” is not a natural destiny but a result of upbringing, law, custom and expectation. Beauvoir looked at biology, history, psychology and literature to show how a girl is taught to see herself. She did not deny bodily differences. Her claim was that their meaning is given by the situation in which people live.' },
      { title: 'Woman as the Other', text: 'Beauvoir argued that men have treated themselves as the standard human beings and described women in relation to themselves, as the “Other”. Men have been allowed to be active and creative, which she called transcendence, while women have been pushed into repetition and care for the home, which she called immanence. She also described the “myth of the eternal feminine”, an ideal picture that hides real women.' },
      { title: 'The ethics of ambiguity', text: 'In The Ethics of Ambiguity (1947) she described human beings as both free subjects and finite bodies in a world not of their choosing, and she thought this tension should be accepted, not escaped. She argued that freedom has meaning only when we also want others to be free, so that oppressing people is a moral failure and not a private matter. She called the flight from freedom, by hiding behind roles or excuses, “bad faith”.' },
      { title: 'Freedom in a situation', text: 'For Beauvoir, freedom is always exercised within a situation, shaped by money, law, education and other people. Some people have far more room to act than others, so liberation involves changing conditions as well as attitudes. She also warned that people who have been denied freedom may be tempted to give it up, for example by accepting dependence in return for security.' },
      { title: 'How societies treat the old and the dying', text: 'In The Coming of Age (1970) Beauvoir applied the same approach to old age, arguing that society treats the old as outsiders and then calls their decline natural. In A Very Easy Death (1964), she described her mother’s last illness and her own mixed feelings. In both she asked how a society treats those who can no longer be productive.' },
    ],
    principles: [
      'Take responsibility for your choices instead of blaming your role.',
      'Your own freedom is tied to the freedom of others.',
      'Notice where an “inevitable” role is actually a social habit.',
      'Accept that life is ambiguous and do not hide in simple answers.',
      'Judge a society by how it treats those who are weak or dependent.',
    ],
    practice: [
      'List the expectations you feel because of your gender, age or background, and ask for each whether it is a choice, a rule or a habit.',
      'When you say “I had no choice”, look for what choices actually existed, and what each would have cost.',
      'Support, in a small concrete way, the freedom of someone with fewer options than you: an elderly neighbour, a new colleague, a younger person asking for advice.',
    ],
    facts: [
      'She won the Prix Goncourt, France’s main literary prize, in 1954 for the novel The Mandarins.',
      'The Second Sex was published in two volumes, “Facts and Myths” and “Lived Experience”, and sold quickly. The Vatican placed it on the Index of Forbidden Books.',
      'The first English translation (1953) cut parts of the book, and a complete new translation appeared in 2009.',
      'In 1971 she signed the “Manifesto of the 343”, a public declaration by women who said they had had illegal abortions. France legalised abortion in 1975.',
      'In the 1950s she wrote in support of Algerian independence, and later helped to defend the Algerian activist Djamila Boupacha.',
      'In her memoirs, beginning with Memoirs of a Dutiful Daughter (1958), she wrote at length about her family and her years with Sartre.',
    ],
    myths: [
      { myth: 'Beauvoir was only Sartre’s follower.', reality: 'She published her first novel, She Came to Stay, in 1943, the same year as Sartre’s Being and Nothingness. Her ethics differed from his in important ways, and scholars have long debated who influenced whom. She herself often said she was not a philosopher, which many modern scholars think undersold her work.' },
      { myth: 'The Second Sex says that biology does not matter or that women should be like men.', reality: 'Beauvoir devoted the first part to biology and agreed that bodies are real. Her claim was that biology does not fix a woman’s destiny, and that its meaning depends on society. She also argued that both men and women should be free to pursue projects in the world.' },
      { myth: 'Her partnership with Sartre was a flawless model of free and equal love.', reality: 'It was unusual and lasting, and meant a great deal to both. But it also drew serious criticism. Some younger women who had been her pupils, among them Bianca Lamblin, later said they were hurt or used, and the question of how the pair treated them has been argued over ever since their letters were published.' },
    ],
    works: [
      { title: 'She Came to Stay (1943)', note: 'Her first novel, on jealousy and the problem of other people’s freedom.' },
      { title: 'The Ethics of Ambiguity (1947)', note: 'Her main work on existentialist ethics.' },
      { title: 'The Second Sex (1949)', note: 'Her study of women’s situation, and her most influential book.' },
      { title: 'The Mandarins (1954)', note: 'A novel about French intellectuals after the war; Goncourt Prize.' },
      { title: 'Memoirs of a Dutiful Daughter (1958)', note: 'The first of her several volumes of autobiography.' },
    ],
    legacy: [
      'The Second Sex became a founding text of modern feminism and influenced writers around the world, from Betty Friedan to later theorists of gender. The idea that gender is shaped by society, and not simply given by nature, owes a great deal to it. Her essays on ethics, old age and death also remain in print.',
      'Her reputation as a philosopher was long underrated, but since the late twentieth century scholars have studied her work closely, as a thinker in her own right. They have also pointed out its limits: the book says little about race, and some of her views on motherhood and her treatment of non-Western countries are now disputed. Her private life, as it has come out through letters and memoirs, has also been judged more critically.',
    ],
  },
  {
    slug: 'simone-weil',
    order: 1909,
    dates: '3 February 1909 – 24 August 1943',
    place: 'Paris, France; died in Ashford, England',
    era: '20th Century',
    tradition: 'Christian mysticism and political thought',
    tagline: 'A philosopher who tried to share the suffering of workers and who taught that attention is a form of love.',
    who: [
      'Simone Weil was born in Paris in 1909 to a secular, well-off family of Jewish origin. Her father was a doctor and her elder brother André became a famous mathematician. She was brilliant and often unwell. She studied under the philosopher Alain at the Lycée Henri-IV, entered the École Normale Supérieure and passed the agrégation in 1931. Stories from her childhood, such as that she refused sugar to share the lot of soldiers at the front, show an early tendency to identify with those who suffered.',
      'She taught in girls’ schools, starting at Le Puy, where she supported striking workers and became known as the “Red Virgin”. In 1934–35 she took leave to work in factories, including Alstom and Renault, because she wanted to know what manual labour was like from the inside. In 1936 she went to Spain to join the Republican side in the civil war, but was badly burned in a cooking accident and left. Between 1935 and 1938 she had a series of religious experiences, in Portugal, in Assisi and at the abbey of Solesmes, and she later described an encounter with Christ while reciting a poem by George Herbert. She never accepted baptism, preferring to stay outside the Church.',
      'After France fell in 1940 she moved to Marseille, where she wrote, studied and, in 1941, worked on a farm with Gustave Thibon. In 1942 she left for the United States with her parents, and then went to London to work for the Free French, where she wrote The Need for Roots. In April 1943 she collapsed, and she was found to have tuberculosis. She died in a sanatorium in Ashford, Kent, on 24 August 1943, aged 34. The inquest recorded that she had killed herself by refusing to eat while the balance of her mind was disturbed, and the death certificate cited starvation and tuberculosis. Weil had said she would not eat more than people in occupied France were allowed, but her biographer Simone Pétrement argued that she was seriously ill and did not seek death. The question is still debated.',
    ],
    context: [
      'Weil lived through the Depression, the rise of fascism, the Spanish Civil War and the Second World War. Many French intellectuals of her time joined the Communist Party or the pacifist movement. She moved among such circles but kept her distance from them, criticising Marxism, trade union bureaucracy and the Soviet Union, and in the end she gave up her earlier pacifism in the face of Nazism.',
      'Under the Vichy government, which was set up after France’s defeat, Jews were subject to anti-Jewish laws from 1940. Weil did not practise Judaism and was drawn to Christian ideas, but she was officially counted as Jewish. Her writing about the Hebrew Bible and the Jewish tradition, which was harsh, has been criticised ever since, and is one of the most disputed aspects of her work.',
    ],
    ideas: [
      { title: 'Attention', text: 'Weil thought that the most important ability we can develop is attention: the willingness to set aside our own thoughts and wait, open and patient, for the reality of another person or a problem to show itself. She wrote in 1942 that attention is “the rarest and purest form of generosity”. She argued that school exercises, including mathematics, train this ability, and that it is the root of both learning and compassion.' },
      { title: 'Affliction', text: 'Weil used the French word malheur, usually translated “affliction”, for suffering that is more than pain. It combines physical hardship with humiliation and the sense of being worthless in the eyes of others. She saw this in factory work, which she said taught her that she was treated as a thing. She believed that really noticing someone in affliction, without pity or condescension, is a rare and difficult act.' },
      { title: 'Force', text: 'In her essay “The Iliad, or the Poem of Force”, written in 1939–40 and published in 1940–41 under the pseudonym Émile Novis, Weil argued that Homer’s poem is about force, the power that turns a human being into a thing, whether by killing or by overwhelming someone. She noted that force corrupts both the victim and the one who uses it, and that Homer shows both sides with an even eye. She wrote it just as France was falling.' },
      { title: 'Gravity, grace and decreation', text: 'Weil said that human nature tends to fall, like a body under gravity, toward self-interest and the use of power. She thought that goodness is possible only through something that comes from outside, which she called grace. Her term “decreation” means loosening the ego’s claim to be the centre of the world, so that we see reality as it is. She related this to the Christian idea that God emptied himself, and she believed that God withdraws to give creation room to exist.' },
      { title: 'Roots and obligations', text: 'In The Need for Roots she argued that human beings have “needs of the soul”, such as order, liberty, responsibility, equality, honour and truth, just as they have needs of the body. She put obligations before rights, since a right means something only if others recognise a duty to respect it. She thought modern society produces “uprootedness”, in which people are cut off from work, place and tradition, and she proposed a kind of patriotism based on compassion for one’s country. She also argued, in a late essay, that political parties should be abolished because they put loyalty to the group before truth.' },
    ],
    principles: [
      'Give people your full attention. It is a kind of generosity.',
      'Share the conditions of the people you want to understand, as far as you can.',
      'Be honest about how power affects those who use it as well as those who suffer it.',
      'Put what you owe to others before what you claim for yourself.',
      'Look at truth even when it is uncomfortable or does not fit your side.',
    ],
    practice: [
      'In a conversation, put your phone away and spend one minute simply listening before you answer.',
      'Take a task you find tedious, such as a problem or a language drill, and treat it as practice in attention.',
      'Ask whether a group you belong to is asking you to repeat its views instead of looking for the truth.',
    ],
    facts: [
      'Her brother André Weil became one of the best known mathematicians of the twentieth century.',
      'She published the essay on the Iliad under a pseudonym because of the Vichy censorship and its anti-Jewish laws.',
      'Almost all of her major books appeared after her death and were assembled by others. Gravity and Grace (1947) was compiled by Gustave Thibon from her notebooks.',
      'T. S. Eliot wrote the preface to the English edition of The Need for Roots (1952), and the French edition was published in a series edited by Albert Camus.',
      'She wrote The Need for Roots while working for the Free French in London, as a study of how France might be rebuilt, but its leadership did not take up her proposals.',
      'Her letters to Father Joseph-Marie Perrin and others, collected in Waiting for God, explain why she refused baptism.',
    ],
    myths: [
      { myth: 'Weil starved herself to death for religious reasons.', reality: 'The inquest verdict said she took her own life by refusing to eat, while her death certificate listed starvation and tuberculosis. Pétrement and others argue that she was gravely ill and did not intend to die. She did say she would not eat more than those in occupied France, so the causes are mixed and still disputed.' },
      { myth: 'Weil was a Catholic convert and a saint.', reality: 'She was drawn to Catholic worship and mysticism but never joined the Church, and she criticised its claims to exclusive truth and its use of authority. Admirers have called her a saint, and she herself rejected any such label.' },
      { myth: 'Weil’s books reflect her own plan for them.', reality: 'Few were published in her lifetime. The posthumous books, such as Gravity and Grace, were assembled by editors from notebooks and letters, so the picture that readers get depends partly on their choices.' },
    ],
    works: [
      { title: '“The Iliad, or the Poem of Force” (1940–41)', note: 'An essay on how force turns people into things; it appeared in English in 1945.' },
      { title: 'Gravity and Grace (1947)', note: 'A selection from her notebooks, edited by Gustave Thibon.' },
      { title: 'The Need for Roots (1949)', note: 'Her last major work on duties, rootedness and the renewal of France, written in London.' },
      { title: 'Waiting for God (French 1950, English 1951)', note: 'Letters and essays on her religious journey.' },
      { title: 'Oppression and Liberty (1955)', note: 'Essays on work, freedom and the limits of political action.' },
    ],
    legacy: [
      'Weil’s writings reached many readers only after the war, helped by Camus and Eliot, among others. Her thought has influenced political philosophy, theology and literature, and philosophers such as Iris Murdoch drew on her idea of attention in writing about ethics. She is read today in discussions of labour, ecology, trauma, the nature of compassion and the place of religion in public life.',
      'She remains controversial. Some readers are put off by her severity and by her harsh comments on Judaism. Others dispute her view of rights and obligations. Many admire her honesty and her refusal to accept either comfort or party loyalty. Few thinkers of her time combined as much political commitment with such unusual spiritual seriousness.',
    ],
  },
]
