import type { Profile } from './types'

export const TWENTIETH_C: Profile[] = [
  {
    slug: 'mahatma-gandhi',
    order: 1869,
    dates: '2 October 1869 – 30 January 1948',
    place: 'Porbandar (Gujarat), South Africa and India',
    era: '20th Century',
    tradition: 'Nonviolence and Indian independence',
    tagline: 'A lawyer who turned refusal to hit back into a method of political struggle, and led India’s movement against British rule.',
    who: [
      'Mohandas Karamchand Gandhi was born in Porbandar, a small coastal state in Kathiawar, western India, into a Hindu merchant family. His mother’s devout Vaishnava faith, with its fasting and its respect for all life, shaped him deeply. He was married at thirteen in an arranged match to Kasturba, travelled to London to study law, and was called to the bar in 1891. Back in India he failed to build a career, and in 1893 he accepted a one-year contract with an Indian firm in South Africa.',
      'He stayed twenty-one years. In South Africa he met the racial discrimination that Indians faced, and a well-known episode in 1893, when he was ejected from a first-class train compartment at Pietermaritzburg, is often told as the turning point. He founded the Natal Indian Congress in 1894, ran the newspaper Indian Opinion, set up communal settlements (the Phoenix Settlement near Durban and, in 1910, Tolstoy Farm near Johannesburg), and in 1906 pledged himself and others to a campaign of nonviolent resistance that he named satyagraha, “truth-force” or “holding firmly to truth”. In the same year he took a vow of brahmacharya, a life without sexual relations.',
      'He returned to India in 1915 and within a few years became the leading figure of the Indian National Congress. He led campaigns of non-cooperation (1920–22), civil disobedience such as the Salt March of 1930, and the Quit India movement of 1942, and he spent many years in prison. India became independent in August 1947 but was partitioned, and Gandhi, who had opposed partition, spent that summer trying to calm communal violence. He was shot dead in New Delhi on 30 January 1948 by Nathuram Godse, a Hindu nationalist who blamed him for being too conciliatory towards Muslims.',
    ],
    context: [
      'Britain had ruled India for generations, and by 1900 Indian nationalists argued over how to answer it: petitions and gradual reform, or armed resistance and revolutionary violence. The country was also deeply divided by religion, caste and region, and most Indians lived in villages and were poor. Gandhi’s great contribution was to find a form of mass politics that ordinary peasants and workers could join without weapons.',
      'The First World War, the repressive Rowlatt Act of 1919 and the massacre at Amritsar the same year turned many Indians against British rule. Gandhi arrived in this moment with ideas he had tested in South Africa, a gift for symbols such as homespun cloth and salt, and a style that mixed religious language with practical organisation.',
    ],
    ideas: [
      { title: 'Satyagraha: holding to truth', text: 'Satyagraha is the practice of resisting injustice by nonviolent means while refusing to hate the opponent. Its supporters accept punishment without fighting back, and they aim to change the opponent’s mind and not to crush him. Gandhi saw it as a force that depends on moral courage, and he insisted that it was a weapon of the strong, not of the weak.' },
      { title: 'Ahimsa: nonviolence', text: 'Ahimsa, a word from Indian religions meaning “non-harm”, was for Gandhi more than not hitting people. It meant refusing to harm anyone in deed, word or thought, and it meant active goodwill. He treated it as inseparable from truth, which he considered the highest value, and described his life as a series of “experiments with truth”.' },
      { title: 'Swaraj: self-rule', text: 'In Hind Swaraj (1909), Gandhi argued that real freedom meant self-rule in a deeper sense than replacing British rulers with Indian ones. He criticised modern industrial civilisation, and urged that individuals and villages govern themselves. Many of his contemporaries, including some of his closest allies, thought this vision impractical.' },
      { title: 'Constructive work', text: 'Gandhi believed that freedom was built by daily work as much as by protest. He promoted spinning and wearing hand-woven khadi cloth, village industries, cleanliness, and the end of untouchability, the treatment of some castes as impure. He wanted political independence and social reform to advance together.' },
      { title: 'Means and ends', text: 'He taught that the means and the end of an action are inseparable, like a seed and a tree. A good goal pursued by violent or deceitful methods would be spoiled, in his view. This is why he called off the non-cooperation campaign in 1922 after a mob killed policemen at Chauri Chaura, a decision that surprised and angered many supporters.' },
    ],
    principles: [
      'Seek truth, and test your beliefs in how you live.',
      'Do not harm others, and refuse to cooperate with injustice.',
      'Accept suffering in a just cause instead of inflicting it.',
      'Make the means as pure as the end.',
      'Link personal habits to public life: simplicity, honest work and care for the poorest.',
    ],
    practice: [
      'Before reacting to someone who has wronged you, name the injustice itself and separate it from the person.',
      'Match your private choices to your public values, even in small ways such as what you buy or waste.',
      'Choose one regular practical task that serves others, and keep to it as a discipline.',
    ],
    facts: [
      'The Salt March ran from Sabarmati Ashram near Ahmedabad to the coastal village of Dandi from 12 March to 6 April 1930, about 240 miles in 24 days. Gandhi set out with 78 followers and broke the salt law by picking up natural salt at the shore.',
      'His autobiography, The Story of My Experiments with Truth, was written in Gujarati and published in weekly instalments from 1925 to 1929. It covers his life only to the early 1920s.',
      'The honorific “Mahatma”, “great soul”, was in use by 1914, and Gandhi himself said he disliked it.',
      'He was nominated for the Nobel Peace Prize several times but never received it. The prize was not awarded in 1948, the year he died.',
      'The United Nations General Assembly declared 2 October, his birthday, the International Day of Non-Violence.',
      'He wrote Hind Swaraj in 1909 during a sea voyage from London to South Africa.',
    ],
    myths: [
      { myth: '“Be the change you wish to see in the world” is a Gandhi quotation.', reality: 'Researchers have found no record of him saying it in this form. It seems to be a modern paraphrase of a thought he did express, for example in 1913: “If we could change ourselves, the tendencies in the world would also change.” Likewise, “An eye for an eye makes the whole world blind” is commonly credited to him without a verified source.' },
      { myth: 'Gandhi opposed all war and never took part in it.', reality: 'He organised an Indian ambulance corps in the Boer War and a stretcher-bearer unit in 1906, and in 1918 he campaigned to recruit Indians for the British army, arguing that it would earn India a claim to equal citizenship. His principle of nonviolence developed over time, and he did not always apply it consistently.' },
      { myth: 'Independence was achieved by Gandhi’s nonviolence alone.', reality: 'Historians point to many factors: other leaders and movements, including revolutionaries and constitutional politicians, the exhaustion of Britain after the Second World War, and changes within British politics. Gandhi’s campaigns mattered because they brought mass participation, but they were one cause among several.' },
    ],
    works: [
      { title: 'Hind Swaraj (Indian Home Rule), 1909', note: 'A short dialogue on freedom, civilisation and nonviolent resistance, written in Gujarati.' },
      { title: 'The Story of My Experiments with Truth, 1925–29', note: 'His autobiography, frank about his failings and his religious and dietary experiments, up to the early 1920s.' },
      { title: 'Satyagraha in South Africa', note: 'His account of the campaigns in South Africa, written in Gujarati in the 1920s.' },
      { title: 'Young India and Harijan', note: 'The weekly journals through which he published articles and answers to readers for decades.' },
      { title: 'The Collected Works of Mahatma Gandhi', note: 'A very large edition published by the Government of India, running to nearly a hundred volumes.' },
    ],
    legacy: [
      'Gandhi’s methods influenced later movements, among them Martin Luther King Jr. and the American civil rights movement, Nelson Mandela’s generation in South Africa, and many campaigns in other countries. In India he is honoured as the Father of the Nation, and 2 October is a national holiday. Yet he remains disputed. Critics point to his early writings in South Africa, where in the 1890s he used offensive language about Black Africans and tended to press for Indians’ rights without making common cause with them, views that scholars say shifted over time.',
      'His record on caste is also debated. He campaigned against untouchability and called its victims “Harijan”, but he defended a reformed idea of the traditional caste order for many years. B. R. Ambedkar, the leader of the Dalits, found this inadequate, and the two clashed in 1932 over separate electorates, when Gandhi’s fast in prison led to the Poona Pact, a compromise that raised the number of reserved seats but disappointed Ambedkar. His late experiments in brahmacharya, which included sleeping near young women, were questioned by some of his own associates. A fair account accepts both the moral force of his example and these real limits.',
    ],
  },
  {
    slug: 'aurobindo-ghosh',
    order: 1872,
    dates: '15 August 1872 – 5 December 1950',
    place: 'Calcutta, England and Pondicherry (India)',
    era: '20th Century',
    tradition: 'Integral philosophy',
    tagline: 'A revolutionary turned yogi who taught that human consciousness is still evolving and that life itself can be transformed.',
    who: [
      'Aurobindo Ghose was born in Calcutta to a Bengali family that favoured British education. At the age of seven he was taken to England, where he grew up and studied at St Paul’s School in London and then at King’s College, Cambridge. He passed the Indian Civil Service examination well but, by his own later account, did not take the riding test seriously and so did not join the service. In 1893 he returned to India and worked for the princely state of Baroda, later teaching English and French literature at the college there.',
      'From about 1902 he became involved in the movement against British rule, writing in the newspaper Bande Mataram and arguing that India should seek complete independence at a time when many leaders asked only for reform. In 1908 he was arrested in connection with the Alipore bomb case. After about a year in prison, awaiting trial, he was acquitted in May 1909. He later said that spiritual experiences during this imprisonment changed the direction of his life.',
      'In 1910 he left Bengal for the French territory of Pondicherry on the southeast coast and devoted himself to yoga and writing. From 1914 to 1921 he edited a monthly review, Arya, in which most of his major prose works first appeared. In 1926 he withdrew to his rooms and put the practical running of the growing community, the Sri Aurobindo Ashram, in the hands of Mirra Alfassa, a French-born spiritual teacher he called “the Mother”. He died in Pondicherry in 1950.',
    ],
    context: [
      'Aurobindo’s life ran across two worlds. His upbringing was almost entirely European, with Greek, Latin and English poetry, yet he turned to Indian scriptures, the Upanishads and the Bhagavad Gita, and to the Indian struggle for freedom. His thought tries to join what he had learned from both.',
      'The early twentieth century was a period of religious revival and political ferment in India, with debates between reformers, nationalists and traditional teachers. The idea of evolution, popular in Europe after Darwin, was also in the air, and Aurobindo’s philosophy is in part an attempt to place evolution inside a spiritual picture of the world.',
    ],
    ideas: [
      { title: 'Integral yoga', text: 'Most yoga traditions aim at liberating the individual from the world. Aurobindo’s integral yoga, as he and the Mother developed it, aims to bring the divine into ordinary life. It combines the paths of knowledge, devotion and selfless action, and uses surrender, inner aspiration and the rejection of lower impulses, with no required postures. It is called “integral” because it tries to include the whole of a person.' },
      { title: 'Evolution of consciousness', text: 'In The Life Divine, Aurobindo argues that nature has already evolved matter, then life, then mind, and that the process will not stop with mind. Human beings, on this view, are a transitional species. He thought the next stage would be a higher consciousness that he called the Supermind. This is a spiritual claim, not an empirical one, and scientists do not test it.' },
      { title: 'Involution and evolution', text: 'He proposed that the universe began with the divine “involving” itself in apparently unconscious matter, and that evolution is the gradual unfolding of what was hidden there. In this picture, evolution has a direction and a meaning, and does not merely happen.' },
      { title: 'The world is real', text: 'Aurobindo rejected the reading of Indian philosophy that treats the world as an illusion to be escaped. He held that matter and the world are real expressions of the divine, so spiritual life should aim to transform life and not merely to leave it. This is the sharpest difference between him and some other Hindu teachers.' },
      { title: 'Spiritual nationalism and human unity', text: 'His political writings tied Indian freedom to a wider purpose. In The Ideal of Human Unity he considered how nations might one day federate while keeping their diversity, and in The Human Cycle he considered how societies pass through stages. He did not see freedom as an end in itself but as a step towards spiritual growth.' },
    ],
    principles: [
      'Let spiritual practice include daily life, work and relationships.',
      'Aspire, reject what holds you back, and surrender to a higher guidance.',
      'Treat human nature as unfinished, not fixed.',
      'Do work as an offering, without attachment to its fruits.',
      'Unite inner discipline with service to the wider world.',
    ],
    practice: [
      'Pick one ordinary task each day and do it with full attention, as if it mattered beyond yourself.',
      'When you notice a habitual reaction such as anger, observe it first without acting, and ask what it is protecting.',
      'Keep a daily time for silence or reading that turns your attention inward before the day’s demands begin.',
    ],
    facts: [
      'He was born on 15 August, the same date, 75 years later, on which India became independent. He gave a radio message for Independence Day in 1947, in which he spoke of his hopes for a united India and a new era of world unity.',
      'He was nominated for the Nobel Prize in Literature in 1943 and for the Nobel Peace Prize in 1950.',
      'The epic poem Savitri, in blank verse, runs to about 24,000 lines. He worked on it and revised it over many years until near the end of his life.',
      'The Sri Aurobindo Ashram in Pondicherry dates its beginning to 1926. Auroville, an experimental township near Pondicherry that the Mother inspired, was inaugurated on 28 February 1968.',
      'He was acquitted in the Alipore bomb case in 1909, with the lawyer Chittaranjan Das defending him.',
      'After 1926 he saw few visitors, appearing before disciples only on a few days of the year (called darshan days), and he continued to write on yoga and to answer disciples’ questions in letters.',
    ],
    myths: [
      { myth: 'He gave up India’s cause when he went into spiritual retirement.', reality: 'He left active politics in 1910, but he kept commenting on public events. He supported the Allies in the Second World War and in 1942 backed the Cripps proposals on independence, and he wrote about India’s future until his death.' },
      { myth: 'He taught that the world is an illusion and that the goal is to escape it.', reality: 'He argued the opposite. He criticised the traditional interpretation that treats the world as illusion, and his goal was the transformation of life, not escape from it.' },
    ],
    works: [
      { title: 'The Life Divine', note: 'His main philosophical work, first serialised in Arya from 1914 and revised as a book around 1939–40.' },
      { title: 'The Synthesis of Yoga', note: 'A long study of the paths of works, knowledge and devotion, and how they might be combined.' },
      { title: 'Essays on the Gita', note: 'An interpretation of the Bhagavad Gita, first serialised in Arya.' },
      { title: 'Savitri: A Legend and a Symbol', note: 'An epic poem based on an episode of the Mahabharata, which he considered a spiritual vision in verse.' },
      { title: 'The Human Cycle and The Ideal of Human Unity', note: 'Two works of social and political thought written for Arya.' },
    ],
    legacy: [
      'The Sri Aurobindo Ashram and the international township of Auroville continue his work, and his books are studied in India and abroad. His writing influenced later thinkers who wished to join spirituality with evolution, including supporters of transpersonal psychology and what is sometimes called integral theory. His emphasis on seeing the world as spiritually meaningful, and not as a place to flee, is still seen as distinctive in modern Hindu thought.',
      'His claims about the Supermind and the “descent” of higher consciousness rest on his own experience and on the faith of his followers, and they cannot be tested in a laboratory. Some scholars admire the breadth of his synthesis while others find it hard to assess or too tied to a particular spiritual system. Auroville has also had disputes over its governance and development. It is fair to read him as a major, highly original thinker, while keeping in mind the difference between what he argued and what he asserted from experience.',
    ],
  },
  {
    slug: 'albert-schweitzer',
    order: 1875,
    dates: '14 January 1875 – 4 September 1965',
    place: 'Kaysersberg (Alsace), Strasbourg and Lambaréné (Gabon)',
    era: '20th Century',
    tradition: 'Ethics of reverence for life',
    tagline: 'A theologian, organist and philosopher who left a brilliant career in Europe to become a jungle doctor and taught “reverence for life”.',
    who: [
      'Albert Schweitzer was born in Kaysersberg in Alsace, then part of the German Empire, and grew up in the village of Günsbach, the son of a Lutheran pastor. He studied theology and philosophy at the University of Strasbourg, earned doctorates, and became a pastor and a lecturer. He was also a gifted organist, and in 1905 he published a book on Johann Sebastian Bach that influenced how the composer’s music was understood.',
      'In 1906 he published The Quest of the Historical Jesus, which argued that scholars had tended to find in Jesus a reflection of their own values, and that Jesus is better understood as a man who expected the imminent end of the world. At the age of thirty he decided to study medicine in order to serve in Africa, and he qualified in 1913. That year he and his wife, Helene Bresslau, travelled to Lambaréné on the Ogooué River in French Equatorial Africa, now Gabon, where he founded a hospital.',
      'During the First World War he and Helene, as German citizens in a French colony, were interned in France, and he returned to Lambaréné only in 1924. He rebuilt the hospital on a new site in 1927 and spent most of the rest of his life there, raising money by giving organ concerts and writing in Europe. He received the Nobel Peace Prize for 1952, and used the prize money to build a leprosy village. In his last years he spoke publicly against nuclear weapons. He died in Lambaréné in 1965, aged ninety.',
    ],
    context: [
      'Schweitzer grew up in a Europe that was confident in progress, science and its own civilisation. Yet he came to feel that European culture had weak ethical foundations, and that its material progress was not matched by moral progress. The First World War seemed to him to confirm this fear.',
      'The medical mission he chose was part of a wider European presence in Africa, under colonial rule. This shaped both what he was able to do and how his work was seen: his hospital offered medical care that was otherwise scarce, but it operated within an unequal colonial setting.',
    ],
    ideas: [
      { title: 'Reverence for life', text: 'In 1915, while travelling by river steamer, Schweitzer says the phrase “reverence for life” came to him as the foundation he had been seeking for an ethic. He argued that every living being wants to live, as he himself does, and that the good consists of preserving and helping life, while evil consists of harming or destroying it.' },
      { title: 'Ethics begin with the will to live', text: 'He began from a simple fact of experience: “I am life that wills to live, in the midst of life that wills to live.” From this, he tried to derive a duty to respect other life with the same seriousness as one’s own. He considered this more basic than any particular religious doctrine.' },
      { title: 'Necessity, not thoughtlessness', text: 'Schweitzer knew that people cannot live without harming other life. His answer was that harm must be accepted only when truly unavoidable, and never through carelessness. Each person must decide, as a matter of conscience, when harm is necessary, and Schweitzer admitted that this leaves a lasting sense of guilt.' },
      { title: 'A critique of civilisation', text: 'In his philosophy of culture, published in the early 1920s as Civilization and Ethics, he argued that Western civilisation had declined because it lost its ethical ideal. He believed that a civilisation can revive only when people again ground their lives in a world view that affirms life and acts on it.' },
      { title: 'Deeds, not only words', text: 'Schweitzer took the view that ethics must be lived. His decision to become a doctor in Africa was, in his own view, a personal response to what he saw as the debt of Europeans to the people their countries had exploited.' },
    ],
    principles: [
      'Treat all life as having value, and harm it only from real necessity.',
      'Let ethics lead to action, not only to opinions.',
      'Question whether progress in technology comes with progress in character.',
      'Accept personal responsibility for suffering that you can reduce.',
      'Keep a source of beauty, such as music, to sustain a demanding life of service.',
    ],
    practice: [
      'Notice one small act of unnecessary harm in your day, such as wasting food or crushing an insect, and avoid it.',
      'Choose one concrete service to others, however modest, and keep to it regularly.',
      'Pair demanding work with something restorative, as Schweitzer did with music.',
    ],
    facts: [
      'Schweitzer was a leading organist and an expert on organ building, and he campaigned for restoring older, warmer-toned organs. He took a piano with metal-lined casing and pedals to Lambaréné so that he could practise Bach.',
      'His first consultations at Lambaréné took place in a converted chicken house, before the first hospital buildings were completed.',
      'He received the Nobel Peace Prize for 1952, and in 1957 broadcast a “Declaration of Conscience” from Radio Oslo calling for an end to nuclear weapon tests.',
      'His autobiography, Out of My Life and Thought, appeared in 1931.',
      'The hospital he founded still exists, and as of the 2010s it was led by an African physician for the first time.',
    ],
    myths: [
      { myth: 'Schweitzer was a saintly figure whose hospital was beyond criticism.', reality: 'Admirers and critics both exist. He described Africans as brothers, but as younger brothers, a phrase that later writers, such as the Nigerian novelist Chinua Achebe, saw as condescending. Visitors in the 1950s criticised the hospital’s conditions and its strong personal control by Schweitzer, though others pointed to the limited resources and the good outcomes for many patients.' },
      { myth: 'Reverence for life means never killing anything.', reality: 'Schweitzer did not claim it was possible to avoid all harm. His ethic asks people to harm life only when necessary, and to feel the weight of each such choice, which is different from an absolute ban.' },
      { myth: 'He used the Nobel Prize money for the hospital itself.', reality: 'He used it to build a village for patients with leprosy, which he regarded as a separate project.' },
    ],
    works: [
      { title: 'The Quest of the Historical Jesus, 1906', note: 'A critical history of nineteenth-century lives of Jesus, which argued that Jesus held apocalyptic expectations.' },
      { title: 'J. S. Bach, 1905', note: 'A study of Bach as a musician and poet, first written in French and later expanded in German.' },
      { title: 'Civilization and Ethics', note: 'Part of his philosophy of culture, in which reverence for life is argued as the basis of an ethic.' },
      { title: 'On the Edge of the Primeval Forest', note: 'An early account of his first years of medical work at Lambaréné.' },
      { title: 'Out of My Life and Thought, 1931', note: 'His autobiography, covering his theology, music and philosophy.' },
    ],
    legacy: [
      'In his lifetime Schweitzer was among the most admired people in the world, and he became a model of the “humanitarian”. His ethic of reverence for life influenced later thinking about animal welfare and the environment, and the idea that ethics should extend beyond humans owes something to him. His public appeal against nuclear testing helped to bring the question before ordinary citizens.',
      'Since his death, historians and writers have given a more balanced picture. His paternalistic language about Africans, and his firm control of the hospital, are now often noted alongside his dedication. His philosophy has also been criticised as too general to settle hard cases. Many readers still find that his central claim, that moral seriousness begins with taking other lives as seriously as one’s own, is both simple and demanding.',
    ],
  },
  {
    slug: 'albert-einstein',
    order: 1879,
    dates: '14 March 1879 – 18 April 1955',
    place: 'Ulm, Zurich, Berlin and Princeton',
    era: '20th Century',
    tradition: 'Physics and philosophy of science',
    tagline: 'The physicist who remade our picture of space, time and gravity, and who also wrote thoughtfully about religion, war and freedom.',
    who: [
      'Albert Einstein was born in Ulm, in the German Empire, and raised in Munich in a Jewish family that ran an electrical business. He left Germany as a teenager, studied physics and mathematics at the Swiss Federal Polytechnic in Zurich, and graduated in 1900. He could not find an academic post, and from 1902 he worked as a patent examiner in Bern, where he thought about physics in his spare time. In 1903 he married Mileva Marić, a fellow student; they had two sons and divorced in 1919. A daughter, Lieserl, was born in 1902 before their marriage, and her fate is unknown.',
      'In 1905, his “miracle year”, he published four papers that changed physics. They explained the photoelectric effect using the idea that light comes in packets of energy, accounted for Brownian motion, which supported the reality of atoms, introduced the special theory of relativity, and derived the equivalence of mass and energy. A decade later, in 1915, he completed the general theory of relativity, a new theory of gravity. Observations of a solar eclipse in 1919 appeared to confirm one of its predictions, and brought him worldwide fame.',
      'He received the Nobel Prize in Physics for 1921, specifically for his law of the photoelectric effect. He worked in Berlin from 1914, but after the Nazis took power in 1933 he did not return to Germany from a visit to the United States. He took a position at the Institute for Advanced Study in Princeton, became a US citizen in 1940, and died there in 1955. In his later decades he sought a unified theory of physical forces and remained a critic of the standard interpretation of quantum mechanics.',
    ],
    context: [
      'At the end of the nineteenth century many physicists believed their subject was nearly complete, resting on Newton’s mechanics and Maxwell’s theory of electricity and light. A few puzzles, such as how light travels and how heated objects radiate, did not fit. Einstein’s early papers came from taking such puzzles seriously and following them to radical conclusions.',
      'His public life was marked by the political upheavals of the century: the First World War, the rise of Nazism, the Second World War and the nuclear arms race. As a Jewish scientist and a famous voice, he was drawn into causes he had not sought.',
    ],
    ideas: [
      { title: 'Special relativity', text: 'In 1905 Einstein started from two principles: the laws of physics are the same for observers moving at constant speed, and the speed of light is the same for all of them. From these he concluded that time and distance depend on motion, so that moving clocks run slow, and that mass and energy are linked in the famous equation E = mc².' },
      { title: 'General relativity', text: 'In general relativity, gravity is not a force that pulls at a distance but the curving of space and time by matter and energy. Objects follow the straightest possible paths through curved space-time, which we experience as falling or orbiting. The theory predicted that light bends near the sun, and later that ripples in space-time called gravitational waves exist, which were first detected in 2015.' },
      { title: 'Light as particles as well as waves', text: 'Einstein’s 1905 explanation of the photoelectric effect treated light as arriving in discrete quanta. This helped open the way to quantum theory, even though he later became one of its sharpest critics.' },
      { title: 'Doubts about quantum mechanics', text: 'Einstein accepted that quantum mechanics gives correct predictions, but he did not believe it was a complete description of reality. In a letter to Max Born in 1926 he wrote that he was convinced that the Old One “does not throw dice”. In 1935, with Boris Podolsky and Nathan Rosen, he published a paper pointing to what later became known as entanglement. Later experiments have mostly gone against his hopes.' },
      { title: 'Cosmic religious feeling', text: 'Einstein rejected a personal God who rewards and punishes. He spoke instead of a feeling of awe at the rational order of the universe, and said in 1929 that he believed in Spinoza’s God, who reveals himself in the harmony of what exists. He denied being an atheist, and when writing late in life he described himself as a religious unbeliever of a kind.' },
    ],
    principles: [
      'Trust simple, deep principles, and follow them even when the conclusions are strange.',
      'Keep a sense of wonder, and ask the questions that others think are childish.',
      'Test ideas against evidence, and be willing to see them fail.',
      'Be curious and imaginative, and not only well informed.',
      'Combine scientific work with a sense of responsibility for how it is used.',
    ],
    practice: [
      'Try explaining a difficult idea in simple words. If you cannot, you may not yet understand it.',
      'Run a thought experiment on a problem: imagine the extreme case and ask what would have to be true.',
      'Set aside regular time for unhurried thinking, away from screens, as Einstein did in the patent office.',
    ],
    facts: [
      'He renounced his German citizenship as a teenager in 1896, became Swiss in 1901, and later held German, Swiss and US citizenship at various times.',
      'The 1919 eclipse expeditions, led by the British astronomer Arthur Eddington, measured starlight bending near the sun in a way that matched Einstein’s prediction better than Newton’s theory.',
      'In 1939 he signed a letter, drafted with the physicist Leo Szilard and dated 2 August, warning President Roosevelt that Germany might build atomic bombs. It reached the president in October. Einstein did not work on the Manhattan Project, and was denied security clearance in 1940.',
      'In 1952 he was offered the presidency of Israel, which he declined.',
      'The Russell–Einstein Manifesto, calling on governments to avoid nuclear war, was signed by him a few days before his death and published in July 1955.',
      'He played the violin and loved sailing.',
    ],
    myths: [
      { myth: 'Einstein failed mathematics at school.', reality: 'He was very good at mathematics from an early age and had mastered calculus by his mid-teens. The myth may come from his failing the non-science sections of an entrance exam to the Zurich Polytechnic at sixteen, a year before the usual age; he passed the following year.' },
      { myth: '“Insanity is doing the same thing over and over again and expecting different results” is Einstein’s.', reality: 'There is no evidence that he said or wrote it. It is listed among misattributions in the reference work The Ultimate Quotable Einstein, and similar sayings appear in print in the 1980s, from sources unrelated to him.' },
      { myth: 'Einstein invented the atomic bomb.', reality: 'His equation described the energy locked in matter, but he did not design or work on the bomb. His 1939 letter helped to start American research into the possibility, and he later said he regretted signing it, because the Germans never developed a bomb.' },
    ],
    works: [
      { title: 'On the Electrodynamics of Moving Bodies, 1905', note: 'The paper that introduced the special theory of relativity.' },
      { title: 'The Foundation of the General Theory of Relativity, 1916', note: 'The first full presentation of general relativity.' },
      { title: 'Relativity: The Special and the General Theory, 1916', note: 'His own popular explanation, written for general readers.' },
      { title: 'Ideas and Opinions', note: 'A collection of his essays and speeches on science, religion, politics and education.' },
      { title: 'The Evolution of Physics, 1938', note: 'A popular history of physics written with Leopold Infeld.' },
    ],
    legacy: [
      'Relativity is now the basis of modern physics and cosmology, and it underlies everyday technology such as satellite navigation, which must correct for relativistic effects on time. His work on light helped found quantum theory, and his predictions about gravitational waves and black holes have been confirmed in recent decades. For many people his name has become a symbol of intelligence itself.',
      'His public positions were more complicated than the legend. In the 1920s and early 1930s he was a committed pacifist, supporting those who refused military service. After the Nazis took power, he decided that a pacifist stance was no longer enough in the face of Hitler, and he later supported efforts to arm the democracies, before turning in his last years to campaigning against nuclear weapons. His personal life, including the strains of his first marriage and the fate of his sons, shows that a great scientist could also fall short in his family relationships.',
    ],
  },
  {
    slug: 'jiddu-krishnamurti',
    order: 1895,
    dates: '11 May 1895 – 17 February 1986',
    place: 'Madanapalle (India), Adyar, England and Ojai (California)',
    era: '20th Century',
    tradition: 'Independent spiritual teaching',
    tagline: 'Raised to be a world saviour, he rejected the role and spent fifty years telling people that truth cannot be reached through any teacher, system or organisation.',
    who: [
      'Jiddu Krishnamurti was born in Madanapalle in south India into a Telugu-speaking Brahmin family. His father was a member of the Theosophical Society, a movement that blended Eastern and Western religious ideas and believed that a “World Teacher” would soon appear. In 1909 the Theosophist Charles Webster Leadbeater noticed the boy at the society’s headquarters in Adyar, near Madras, and declared that he might be the vehicle for that teacher. Annie Besant, the society’s president, became his guardian after a legal dispute with his father.',
      'He was educated in England and became the head of the Order of the Star in the East, founded in 1911 to prepare for the coming of the World Teacher. In 1922 he went through a series of intense physical and mental experiences in California that he and his followers called “the process”, and in 1925 the death of his younger brother Nitya, to whom he was devoted, shook his belief in the Theosophical framework he had been given.',
      'On 3 August 1929, at a gathering in Ommen in the Netherlands, he dissolved the Order, declaring that “truth is a pathless land” that no organisation or creed can lead people to. He later left the Theosophical Society as well. For the next five decades he gave talks and held discussions across Europe, India and the United States, refusing to be called a guru. He died in Ojai, California, in 1986.',
    ],
    context: [
      'Theosophy, founded in New York in 1875, was a popular movement in the early twentieth century. It took ideas from Hinduism and Buddhism, such as reincarnation and karma, and added a belief in hidden masters who guide humanity. Many educated people in India and the West took part, and the expectation of a coming teacher gave Krishnamurti an extraordinary public role while he was still a teenager.',
      'His break with that role was therefore a personal and a public event. Those who had invested faith, money and years in the Order were disappointed, and Besant remained convinced until her death in 1933 that he was the World Teacher. His later teaching was shaped by this experience of how belief systems and authority can capture people.',
    ],
    ideas: [
      { title: 'Truth is a pathless land', text: 'Krishnamurti held that truth cannot be reached through any religion, philosophy, ritual or teacher. Each person must discover it directly, he said, and any organisation that claims to lead people there becomes an obstacle. This is why he dissolved the Order and refused to found a movement.' },
      { title: 'Choiceless awareness', text: 'Instead of techniques, he proposed simply watching one’s thoughts and feelings as they arise, without judging, choosing or trying to change them. He called this “choiceless awareness”. In his view, the act of observing without a goal can itself bring understanding and change.' },
      { title: 'The observer is the observed', text: 'He argued that the sense of a separate self who watches and controls thoughts is itself made of thought. Trying to master your anger, for instance, is a conflict within one mind and does not resolve it. When this is seen directly, he said, the conflict ends. Critics find the argument hard to pin down, and philosophers have not treated it as a worked-out theory.' },
      { title: 'Freedom from the known', text: 'Krishnamurti considered fear, conditioning and the pursuit of psychological security to be the sources of conflict, personal and social. He urged people to question inherited beliefs, nationalism and religious labels, since these divide people and keep them in the past.' },
      { title: 'Education and relationship', text: 'He wrote and spoke often about education, hoping that schools would help children to think clearly and without fear, instead of preparing them to compete. He also gave great weight to the way we relate to other people, nature and ideas, as the true test of any insight.' },
    ],
    principles: [
      'Do not follow anyone, including the teacher, and look for yourself.',
      'Watch your own mind carefully, without judging it.',
      'Question beliefs, labels and authority, including your own.',
      'Let learning be direct and not merely a collection of knowledge.',
      'Treat relationship with others as the place where self-understanding is tested.',
    ],
    practice: [
      'Spend a few minutes each day watching your thoughts without trying to fix them, and notice when they repeat.',
      'When you feel afraid or angry, pause and ask what you are defending, before you act.',
      'In a disagreement, listen to the other person fully before forming your reply.',
    ],
    facts: [
      'The Order of the Star in the East had roughly 15,000 members by 1913 and over 40,000 by the mid-1920s, according to historians of the movement.',
      'He declined to accept payment for his talks, and refused to be treated as an authority or guru.',
      'He held a long series of conversations with the physicist David Bohm, some of which appeared in books such as The Ending of Time (1985).',
      'He knew writers such as Aldous Huxley, who wrote the introduction to The First and Last Freedom (1954).',
      'The Krishnamurti Foundations, set up in the 1960s and 1970s, maintain his archives and several schools, among them Rishi Valley in India and Brockwood Park in England.',
      'Shortly before his death, he is reported to have said that although something extraordinary had worked through his body, nobody had really lived the teachings.',
    ],
    myths: [
      { myth: 'Krishnamurti started a spiritual movement or religion.', reality: 'He did the opposite. In 1929 he dissolved the organisation that had been created around him and spent the rest of his life saying that he wanted no followers. The foundations that bear his name exist mainly to preserve his talks and to run schools.' },
      { myth: 'He never contradicted his own teaching in his life.', reality: 'His personal life raised questions. For many years he had a relationship with Rosalind Rajagopal, the wife of his close associate D. Rajagopal, which became public through a memoir by her daughter in 1991. There were also long legal disputes over property and archives. Supporters note that he did not present himself as a perfect example.' },
    ],
    works: [
      { title: 'At the Feet of the Master, 1910', note: 'A short Theosophical booklet published under his name when he was a teenager; it is not his mature teaching and he later moved away from it.' },
      { title: 'The First and Last Freedom, 1954', note: 'A collection of talks and answers on thought, fear and freedom, introduced by Aldous Huxley.' },
      { title: 'Commentaries on Living, 1956–60', note: 'Three series of short pieces describing conversations he had with people who came to him.' },
      { title: 'Freedom from the Known, 1969', note: 'A short introduction to his central themes of conditioning and awareness.' },
      { title: 'Krishnamurti’s Notebook', note: 'A personal journal from 1961–62, written in his own voice, describing his inner states.' },
    ],
    legacy: [
      'Krishnamurti influenced readers and thinkers who were wary of organised religion yet looked for spiritual depth, including writers, psychologists and teachers. His dialogues with Bohm drew attention from some scientists. The schools and foundations continue, and the recorded talks have been widely translated and shared.',
      'Because he refused to build a system, his legacy is hard to measure. Supporters see this as his point, while critics say that his teaching, which asked people to follow no authority, was still delivered by a charismatic figure to devoted audiences. His appeal lies in the directness of the question he kept asking: what can you see for yourself, without relying on anyone else?',
    ],
  },
]
