import type { Profile } from './types'

export const TWENTIETH_D: Profile[] = [
  {
    slug: 'henri-bergson',
    order: 1859,
    dates: '1859 – 1941',
    place: 'Paris, France',
    era: '20th Century',
    tradition: 'Process philosophy and vitalism',
    tagline: 'The philosopher of lived time, who argued that the clock measures something other than the flow we actually experience.',
    who: [
      'Henri Bergson was born in Paris on 18 October 1859. His father, Michał Bergson, was a Polish-Jewish musician, and his mother, Katherine Levison, came from an English-Jewish family. He was a gifted student who did well in mathematics, but he chose philosophy and entered the École Normale Supérieure at nineteen, passing the philosophy examination known as the agrégation in 1881. He then taught in provincial schools and in Paris, and wrote his first book, Time and Free Will, in 1889.',
      'In 1900 he took a chair at the Collège de France, the Paris institution where leading scholars give free public lectures, and in 1904 he moved to its chair of modern philosophy. His lectures became a social event, drawing crowds that included philosophers, poets and fashionable Parisians. Creative Evolution (1907) made him famous well beyond France. During the First World War he took part in French diplomatic efforts in the United States, and he was elected to the Académie française in 1914. He received the Nobel Prize in Literature for 1927, with a citation praising his rich and vitalizing ideas. He was too ill with rheumatism to travel to Stockholm.',
      'In his last years he grew closer to religion. His will of 1937 says his thinking had always led him toward Catholicism, which he saw as the completion of Judaism, but he did not convert, because he did not want to leave persecuted Jews at a time of rising antisemitism. He died in occupied Paris on 3 January 1941. According to accounts of his final months, when the authorities required Jews to register, he complied and described himself as an academic, a philosopher, a Nobel laureate and a Jew.',
    ],
    context: [
      'Bergson wrote at a time when the prestige of science was very high. Evolution by natural selection, physics and the new experimental psychology seemed to promise that everything, including the human mind, could be explained as matter in motion, and that a free act was an illusion. Many philosophers of the period, in France and elsewhere, accepted that picture or tried to work around it. Bergson thought it rested on a mistake about time.',
      'His answer arrived at a moment of cultural restlessness before and after the First World War. Artists, novelists and poets, from Marcel Proust, who was best man at his wedding in 1891, to the poet Charles Péguy, found in his writing a way to speak about inner life that scientific psychology seemed to leave out. His influence faded after 1945, when phenomenology and existentialism dominated French thought, and revived after Gilles Deleuze published a study of his work in 1966.',
    ],
    ideas: [
      { title: 'Duration: time as we live it', text: 'Bergson distinguished the time of clocks from what he called duration (la durée). Clock time is a line of equal, separate moments, like beads on a string. Lived time is not like that: each moment carries the past into the present, as the notes of a melody run into one another and only make sense together. For Bergson, measuring time in this spatial way captures useful facts but leaves out what time really feels like and does.' },
      { title: 'Free will as creative action', text: 'In Time and Free Will, he argued that the usual debate between determinism and free will wrongly treats our decisions as paths laid out in space, with several options to pick from. A deep choice, he said, comes from the whole of a person’s history and expresses it, so it cannot be predicted by listing causes. Freedom lies in acts that really are ours, not in a random jump between fixed alternatives.' },
      { title: 'Memory is more than the brain', text: 'In Matter and Memory (1896), Bergson separated habit, which is the body learning to repeat a task, from pure memory, in which the past is preserved as a whole. He argued that the brain selects which memories are useful for action now, and does not store them. This was a bold claim, and it remains controversial.' },
      { title: 'Intuition as a method', text: 'Bergson held that the intellect is good at dividing, measuring and manipulating, which is what practical life and science need. To grasp the living, flowing side of reality, he proposed intuition, a disciplined effort of sympathy to enter into a thing from the inside instead of looking at it from outside. He was clear that this was a method requiring hard work, not a mood or a mystical feeling.' },
      { title: 'Creative evolution and the vital impulse', text: 'In Creative Evolution, he accepted that species evolve but rejected both strict mechanism and the idea of a fixed plan. He proposed an élan vital, a vital impulse, a creative current of life that branches into different forms and produces genuine novelty. Many scientists have been unconvinced by the idea, which they see as a name for a mystery, but it expressed a deep conviction that the future of life is open.' },
    ],
    principles: [
      'Do not confuse a measurement of something with the thing itself.',
      'Pay attention to your own experience before you theorise about it.',
      'Real freedom is acting from the whole of who you are.',
      'The future is open and cannot be fully deduced from the past.',
      'Reality is better understood as flowing and creative than as a set of fixed things.',
    ],
    practice: [
      'Notice the difference between clock time and felt time: an hour of boredom and an hour of absorption are not the same, even though a clock records them equally.',
      'Before a big decision, ask whether you are choosing from your own deepest commitments or from a list of external options.',
      'Next time you listen to music, try to hear the melody as one flowing whole instead of separate notes, and then ask what that says about how you experience your day.',
    ],
    facts: [
      'Bergson’s book Laughter (1900) proposed that we laugh when a living person acts like a stiff machine, so that comedy gently corrects rigidity.',
      'Marcel Proust was his best man at his wedding to Louise Neuberger in 1891.',
      'During a visit to Columbia University in 1913, his lecture was said to have caused one of the first traffic jams on Broadway.',
      'In 1922 he became the first president of the League of Nations’ International Commission for Intellectual Cooperation, a body that later became associated with UNESCO’s work.',
      'His 1922 meeting with Albert Einstein at the Société française de philosophie in Paris is among the best-known encounters between a philosopher and a physicist.',
      'He won the Nobel Prize in Literature, not a prize for philosophy, because no Nobel Prize in philosophy exists.',
    ],
    myths: [
      { myth: 'Bergson “defeated” or was “defeated by” Einstein in their 1922 debate.', reality: 'They did not agree, and the matter is still debated. Einstein said that physical time and psychological time exist but that there is no separate “time of the philosophers”. Bergson accepted that relativity worked within physics but argued that it could not replace lived duration. In Duration and Simultaneity (1922), he also made errors about the physics, including about the so-called twin paradox. Many physicists and philosophers of science judged Einstein to have had the better of it, while others have argued that Bergson was raising a real question about the meaning of time that physics does not answer.' },
      { myth: 'Bergson was an irrationalist who rejected science.', reality: 'He studied mathematics and biology closely and said that the intellect and science are valuable for action and for measuring matter. His objection was to treating scientific abstractions as the whole of reality, not to science itself.' },
      { myth: 'He converted to Catholicism.', reality: 'His will says he was drawn toward it, but he stayed formally within the Jewish community out of solidarity with persecuted Jews.' },
    ],
    works: [
      { title: 'Time and Free Will (1889)', note: 'Originally titled Essai sur les données immédiates de la conscience. It introduces duration and his account of freedom.' },
      { title: 'Matter and Memory (1896)', note: 'His study of the relation between body, brain, perception and memory.' },
      { title: 'Laughter (1900)', note: 'A short essay on the meaning of the comic.' },
      { title: 'Creative Evolution (1907)', note: 'His most famous book, on life, evolution and the vital impulse.' },
      { title: 'The Two Sources of Morality and Religion (1932)', note: 'His late work distinguishing closed, group-bound morality from an open morality of universal love.' },
    ],
    legacy: [
      'Bergson’s emphasis on lived time shaped literature, with Proust as the best-known example, and it influenced phenomenology, existentialism and the arts. William James welcomed his work in the United States, and Alfred North Whitehead shared his view that process and change are basic to reality. Gilles Deleuze’s book Bergsonism (1966) did much to revive interest in him in France and beyond.',
      'In the twenty-first century his ideas have been taken up again in discussions of consciousness, memory and the nature of time, and the debate with Einstein has been re-examined by historians of science, who often treat it as a missed chance for dialogue. Whatever one makes of his claims about the élan vital, his central question still stands: what is left out when we turn lived experience into measurements?',
    ],
  },
  {
    slug: 'alfred-north-whitehead',
    order: 1861,
    dates: '1861 – 1947',
    place: 'Ramsgate, England, then London and Cambridge, Massachusetts',
    era: '20th Century',
    tradition: 'Process philosophy',
    tagline: 'A mathematician who co-wrote Principia Mathematica, then spent his last decades arguing that reality is made of events, not things.',
    who: [
      'Alfred North Whitehead was born on 15 February 1861 in Ramsgate, on the coast of Kent, England. His father was a schoolmaster who became an Anglican clergyman. He attended Sherborne School, where he did well in mathematics, and in 1880 he went to Trinity College, Cambridge, graduating in 1884. He stayed at Trinity for about thirty years, teaching mathematics and physics, and in 1890 he married Evelyn Wade. They had three children.',
      'At Cambridge he wrote A Treatise on Universal Algebra (1898) and began working with his former student Bertrand Russell on the foundations of mathematics. The result was Principia Mathematica, published in three volumes between 1910 and 1913, which tried to derive mathematics from a small number of logical principles. He then taught at University College London and Imperial College, and turned to the philosophy of science and of nature. His younger son Eric, a pilot, was killed in the First World War.',
      'In 1924, at the age of 63, when most people would retire, he accepted an invitation to become professor of philosophy at Harvard University. There he developed the work for which he is best known, including Science and the Modern World (1925) and Process and Reality (1929), which grew from his Gifford Lectures at Edinburgh in 1927–28. He retired in 1937, received the Order of Merit in 1945, and died in Cambridge, Massachusetts, on 30 December 1947.',
    ],
    context: [
      'Whitehead lived through the greatest upheaval in physics since Newton. Relativity and quantum theory undermined the picture of the world as solid matter moving in absolute space and time, which had dominated since the seventeenth century. Whitehead, who had been trained in the old physics and had worked on the new, concluded that philosophy needed a new picture of nature, not a patched version of the old one.',
      'He also lived through the catastrophe of the First World War, and he was concerned about the split between science, with its focus on measurable facts, and the human world of value, beauty and meaning. His Harvard years were a period of unusual freedom, in which he developed a system that was both highly technical and ambitious in range. Many readers found it hard to follow, and the logical positivists of the time were unimpressed, but a loyal group of followers kept it alive.',
    ],
    ideas: [
      { title: 'Process: the world as events', text: 'Whitehead argued that the basic things in the world are not lumps of unchanging matter but events, or acts of becoming, which he called actual occasions. Each occasion gathers up the influence of the past, adds something of its own, and then passes into the past to influence what follows. A tree, a person or an atom is a pattern that persists through a stream of such events, and is not a thing that sits still.' },
      { title: 'Everything is related', text: 'On his view, relationships are not added on after things exist. Each event takes in its surroundings, which he called prehending them, and is partly made of what it has taken in. Nature is therefore a web of interdependence, and not a collection of separate bits that happen to bump into one another.' },
      { title: 'The fallacy of misplaced concreteness', text: 'Whitehead warned against mistaking an abstraction for the full reality. A point, a billiard-ball atom or a statistic is a useful simplification, but if we treat it as the whole truth about the world we leave out feeling, value and experience. He argued that much of modern thought made this error by treating the mathematical picture of nature as complete.' },
      { title: 'Experience goes all the way down', text: 'He rejected the split, which he called the bifurcation of nature, between a real world of measurable matter and a merely subjective world of colours, feelings and meanings. In his view, something like experience, though not usually conscious thought, belongs to every event in nature. Critics have found this hard to accept, and others find it a bold way to bring minds and the rest of nature into one picture.' },
      { title: 'A God who persuades', text: 'Whitehead’s God is not an all-powerful ruler. In Process and Reality, God offers each event possibilities and an ideal for how it might become, but does not force the outcome, and God takes in and preserves what the world achieves. This idea, that God works by persuasion and not by coercion, became the starting point of process theology.' },
    ],
    principles: [
      'Do not mistake a useful abstraction for the whole of reality.',
      'Treat the world as a web of relations, not a heap of separate things.',
      'Take change and novelty seriously: nature is creative, not just a machine.',
      'Let science and the sense of value inform each other instead of competing.',
      'Education should keep ideas alive, not store them as “inert” facts.',
    ],
    practice: [
      'When you hear a statistic or a model, ask what has been left out in simplifying, and whether it matters for your decision.',
      'Think of a person or an institution as a process with a history and relationships, not as a fixed object with fixed traits.',
      'When you study something, apply it at once: try to use what you learn in a real problem, so that it does not sit as unused information.',
    ],
    facts: [
      'He wrote that the safest general description of the European philosophical tradition is that it consists of a series of footnotes to Plato. The remark is in Process and Reality.',
      'Principia Mathematica is so thorough that its proof that 1 + 1 = 2 appears long after the start of the first volume, a fact often retold as a joke about the book.',
      'He was 63 when he began teaching philosophy at Harvard, after a career in mathematics and physics.',
      'He gave the Gifford Lectures at Edinburgh in 1927–28, a prestigious series on natural theology.',
      'Whitehead and Russell remained friends but drifted apart in their views, especially over the First World War, when Russell was a vocal pacifist.',
      'He was elected a Fellow of the Royal Society in 1903, for his work in algebra and mathematical logic.',
    ],
    myths: [
      { myth: 'Whitehead was a mathematician who simply gave up science for mysticism in old age.', reality: 'His later philosophy grew directly out of his work on the philosophy of nature and of physics in the 1910s and 1920s. He was always concerned with how science relates to experience, and his system aimed to take modern physics seriously.' },
      { myth: 'Principia Mathematica was really Russell’s book, with Whitehead as a helper.', reality: 'It was a genuine collaboration. The two men worked on it for roughly a decade, and Whitehead was the older and more established mathematician. The exact division of labour is hard to reconstruct, because they revised each other’s drafts.' },
      { myth: 'Process philosophy is just a theory that “everything changes”.', reality: 'Whitehead also stressed that patterns endure and that possibilities are real. His claim is that stability itself is something achieved in the flow of events, not a primary fact.' },
    ],
    works: [
      { title: 'Principia Mathematica (1910–1913, with Bertrand Russell)', note: 'A three-volume attempt to build mathematics on logic, and a landmark in the history of logic.' },
      { title: 'Science and the Modern World (1925)', note: 'A history of how modern science shaped ideas, including the “fallacy of misplaced concreteness”.' },
      { title: 'Process and Reality (1929)', note: 'His main metaphysical work, subtitled An Essay in Cosmology. It is famously demanding.' },
      { title: 'The Aims of Education and Other Essays (1929)', note: 'Accessible essays that criticise “inert ideas” and defend learning that is alive.' },
      { title: 'Adventures of Ideas (1933)', note: 'A broad history of ideas that is more readable than Process and Reality.' },
    ],
    legacy: [
      'Whitehead’s thought has had a long afterlife outside the mainstream of analytic philosophy. Process theology, developed by thinkers such as Charles Hartshorne and John Cobb, builds on his idea of a persuading God. His work has also been used in ecological thought, in debates about consciousness, and in discussions of quantum physics, where its stress on relations and events attracts interest.',
      'Within academic philosophy his reputation has been uneven. Some admire his scope and his willingness to ask big questions about science and value, while others find his vocabulary obscure and his claims hard to test. Still, his warning against taking abstractions for the whole of reality continues to be quoted by scientists, educators and philosophers.',
    ],
  },
  {
    slug: 'jose-ortega-y-gasset',
    order: 1883,
    dates: '1883 – 1955',
    place: 'Madrid, Spain',
    era: '20th Century',
    tradition: 'Spanish philosophy',
    tagline: 'The Spanish thinker who said that each of us is “myself and my circumstance”, and who warned that a society can be ruled by people who refuse to be guided by anything beyond themselves.',
    who: [
      'José Ortega y Gasset was born in Madrid on 9 May 1883 into a family connected with journalism and the press. He studied at the Jesuit college of Deusto and then at the University of Madrid, where he took his doctorate in philosophy in 1904. He spent time in Germany, including a stay at Marburg, the centre of neo-Kantian philosophy, between 1905 and 1907. In 1910 he became professor of metaphysics at the University of Madrid, a post he held for many years.',
      'Ortega was never just a professor. He wrote for newspapers, founded the journal Revista de Occidente in 1923, which brought leading European thought to Spanish readers, and became the most influential Spanish intellectual of his generation. In 1931, after the fall of the monarchy, he helped found a group of intellectuals supporting the Second Republic and was elected to the Cortes as a deputy for León. He soon grew disillusioned with the Republic’s direction and withdrew from active politics.',
      'When the Spanish Civil War began in 1936, he left Spain, and he lived in exile in France, Argentina and finally Portugal. Under pressure to take sides, he supported neither the Republic nor the military rebels. He returned to Madrid in 1945 and in 1948, with his disciple Julián Marías, founded the Institute of Humanities. He remained critical of the Franco regime in private but was no longer politically active. He died in Madrid on 18 October 1955.',
    ],
    context: [
      'Ortega belonged to a generation of Spanish thinkers who felt that Spain had fallen behind Europe after losing the last of its empire in 1898, and who were determined to renew it by education, science and open debate. He admired German philosophy, especially phenomenology, but he wanted a philosophy that spoke to the problems of ordinary life and of his own country.',
      'Politically, the period was explosive: a weak monarchy, a dictatorship under Primo de Rivera in the 1920s, a Republic in 1931, and a polarised society that slid toward civil war. Across Europe, communism and fascism were gaining ground. The Revolt of the Masses was Ortega’s diagnosis of this crisis, written before the worst of it had happened.',
    ],
    ideas: [
      { title: '“I am myself and my circumstance”', text: 'In his first book, Meditations on Quixote (1914), Ortega wrote that he is himself and his circumstance, and that if he does not save the latter he does not save himself. By “circumstance” he meant the concrete world in which we find ourselves: our time, country, body, language and surroundings. We cannot understand a person separately from this setting, and a person is not merely shaped by it but must also act on it. The second half of the sentence, with its call to improve one’s own world, is often left out when it is quoted.' },
      { title: 'Life as a task', text: 'Ortega held that human life is not a ready-made thing but something each of us must do, in particular circumstances and under constraint. We are not given a fixed nature and have to decide who to be. This made him an early voice in what is sometimes called existential thought, although he developed it independently.' },
      { title: 'Perspectivism', text: 'Every person sees reality from a particular place, and no one sees the whole. Truth is not made false by this, but it is reached only by combining many perspectives. A viewpoint is not a mistake to be corrected but a necessary angle on something real.' },
      { title: 'Vital and historical reason', text: 'Against both dry rationalism and mere feeling, Ortega proposed reason that grows out of life and serves it, which he called vital reason, and later historical reason, which understands people by telling the story of how they came to be what they are, since humans have a history instead of a fixed nature.' },
      { title: 'The mass man', text: 'In The Revolt of the Masses (serialised in 1929, published as a book in 1930), he described a type of person who is content with himself, sees no need for standards beyond his own wishes and resents anyone who is different or excellent. Ortega insisted this was a psychological type and not a social class: he found it among educated specialists as much as among workers. He warned that when such people hold the real power in society, public life loses its direction. He also argued that Europe should move toward a closer union.' },
    ],
    principles: [
      'You are your circumstances, and you are responsible for improving them.',
      'Life is something you have to do, not something that is handed to you finished.',
      'Every viewpoint is partial. Look for what others can see that you cannot.',
      'Demand more of yourself than others demand of you.',
      'Expertise in one field does not give you authority in every other.',
    ],
    practice: [
      'List the circumstances you did not choose, such as your place, family and time. Then write down one that you could improve, and take a first step.',
      'When you disagree with someone, ask what they can see from where they stand that you cannot.',
      'Pick one area where you hold yourself to a standard that nobody else would check, and keep to it.',
    ],
    facts: [
      'His first book, Meditations on Quixote (1914), was a set of essays that used Cervantes’s novel to think about Spain and about how to look at the world.',
      'Revista de Occidente, which he founded in 1923, published Spanish translations of major European thinkers and was an important channel for modern philosophy into the Spanish-speaking world.',
      'He was elected to the Cortes for León in 1931 and later said he had been disappointed by the Republic’s course.',
      'He left Spain on the night of 31 August 1936 and returned only after the Second World War, in 1945.',
      'Many of his later works were published after his death, including Man and People and What Is Philosophy?, both of which grew out of lectures.',
    ],
    myths: [
      { myth: '“I am myself and my circumstance” is a statement that people are products of their environment.', reality: 'Ortega’s sentence goes on to say that the person must save the circumstance in order to be saved. He meant that we are inseparable from our world and responsible for acting on it, not that we are determined by it.' },
      { myth: 'The Revolt of the Masses is simply an attack on ordinary people, or a defence of fascism.', reality: 'Ortega defined the “mass” by attitude, not class, and he was critical of the violent mass movements of his time, including fascism and Bolshevism. His readers have still argued about the work: critics find it elitist and ambiguous, while defenders read it as a warning about conformity and about democratic life that needs standards of its own.' },
      { myth: 'Ortega supported the Franco regime.', reality: 'He supported neither side in the Civil War and went into exile. After his return, he kept his distance from the regime, which had its own uses for a famous intellectual. His position has been read in different ways, and the question is still discussed by historians.' },
    ],
    works: [
      { title: 'Meditations on Quixote (1914)', note: 'His first book, the home of the “I am myself and my circumstance” passage.' },
      { title: 'Invertebrate Spain (1921)', note: 'A diagnosis of Spain’s political and social weaknesses.' },
      { title: 'The Revolt of the Masses (1929–1930)', note: 'His best-known work, translated into English in 1932.' },
      { title: 'Man and People and What Is Philosophy? (published posthumously)', note: 'Late works on life, society and the purpose of philosophy.' },
    ],
    legacy: [
      'Ortega shaped modern Spanish and Latin American thought. His students and associates included the philosophers Julián Marías, María Zambrano and Xavier Zubiri, and his journal helped to open Spanish culture to Europe. Later in the twentieth century his thoughts on life, history and perspective found readers in Latin America, where he had spent part of his exile.',
      'The Revolt of the Masses has had an unusual afterlife. It has been read as a warning about conformity, mass media and populism, and also criticised for its elitism and for the way it handled the rise of fascism. Read carefully, it asks a question that is still alive: what does a democratic society owe to excellence, and what do citizens owe to one another?',
    ],
  },
  {
    slug: 'john-rawls',
    order: 1921,
    dates: '1921 – 2002',
    place: 'Baltimore, Maryland, and Cambridge, Massachusetts, USA',
    era: '20th Century',
    tradition: 'Political philosophy',
    tagline: 'He asked what rules of society we would choose if we did not know who we would be, and the question reshaped modern political philosophy.',
    who: [
      'John Rawls was born in Baltimore, Maryland, on 21 February 1921, into a well-off family. His father was a lawyer and his mother was active in the League of Women Voters. Two of his younger brothers died of infectious diseases that they caught from him, and his biographers regard this as a deeply formative event of his childhood. He studied at Princeton, where he completed his doctorate in 1950.',
      'Rawls served as an infantryman in the United States Army in the Pacific in the Second World War, in New Guinea and the Philippines, and was awarded the Bronze Star. He saw the devastation at Hiroshima and left the army with doubts about the use of force. During the war he also lost the Christian faith he had held earlier. Accounts say he refused an order to punish a fellow soldier, believing no punishment was justified, and was reduced in rank for it. He left the army in 1946.',
      'After studying at Oxford and teaching at Cornell and MIT, Rawls joined Harvard in 1962 and taught there until 1991. He published slowly, working over his ideas for years. His 1958 article “Justice as Fairness” was an early sketch, and in 1971 he published A Theory of Justice, which brought his ideas to the world. He received the National Humanities Medal in 1999 and died on 24 November 2002.',
    ],
    context: [
      'When Rawls started, many English-language philosophers thought that political philosophy was dead. They considered moral and political questions to be matters of taste, or only worth discussing as analysis of language. At the same time, the best-known theory of how to organise society was utilitarianism, which says the right policy is the one that produces the greatest total happiness. Rawls thought this could sacrifice the rights of individuals for the sake of the majority.',
      'A Theory of Justice appeared in 1971, during the civil rights movement and the Vietnam War, when Americans were arguing about equality, liberty and the limits of obedience. It offered a rigorous and systematic alternative, rooted in the older tradition of social contract thinkers such as Locke, Rousseau and Kant, and it revived the field.',
    ],
    ideas: [
      { title: 'The original position and the veil of ignorance', text: 'Rawls asks us to imagine people choosing the basic rules of their society behind a “veil of ignorance”. They do not know their class, race, gender, talents or even their own views of the good life. Since they could end up in any position, he argued, they would choose rules that are fair to everyone. The device is a thought experiment to make us reason impartially, and not a description of a real event.' },
      { title: 'Two principles of justice', text: 'He argued that people in this position would choose two principles. The first guarantees an equal set of basic liberties for everyone, such as freedom of speech and of conscience. The second says that social and economic inequalities are allowed only if jobs and positions are open to all under fair equality of opportunity, and if the inequalities work to the greatest benefit of the least advantaged. Liberty has priority over the second principle.' },
      { title: 'The difference principle', text: 'This is the part of the second principle about inequalities. A system in which some people are richer is acceptable only if it makes the worst-off group better off than they would otherwise be. It does not demand equality, but it asks the fortunate to justify their advantages to those who have less. Rawls reasoned that natural talents and social starting points are not deserved, so they should be seen as shared assets for the common good.' },
      { title: 'Reflective equilibrium', text: 'Rawls suggested that we test moral principles by going back and forth between general principles and our firm judgements about particular cases, such as the wrongness of slavery. We adjust each against the other until they fit together. This method treats moral reasoning as a process of mutual adjustment and not as deduction from fixed first principles.' },
      { title: 'Political liberalism', text: 'In Political Liberalism (1993), Rawls revised his approach. In a modern democracy, people hold many reasonable but conflicting religious and philosophical views, and this will not go away. Justice as fairness should therefore be presented as a political conception that people with different outlooks can each support for their own reasons, an “overlapping consensus”, instead of as a complete moral doctrine.' },
    ],
    principles: [
      'Judge the fairness of a rule by asking whether you would accept it without knowing your place in society.',
      'Basic liberties come first and should not be traded away for gains in wealth.',
      'Inequalities need a justification that the least advantaged can accept.',
      'Much of what we have comes from luck, in talents and in the families we were born into.',
      'In a society with different beliefs, seek principles that people can accept for their own reasons.',
    ],
    practice: [
      'When you design a policy, a rule at work or a household arrangement, imagine you do not know which role you will have and ask whether you would still call it fair.',
      'Before dismissing a view you disagree with, ask whether a reasonable person could hold it, and what common ground you share.',
      'Notice which of your advantages came from luck, and think about what that implies for what you owe others.',
    ],
    facts: [
      'A Theory of Justice has sold in very large numbers for a work of academic philosophy and has been translated into dozens of languages. Rawls revised it in 1999.',
      'He served in New Guinea and the Philippines in the war and later spoke of how seeing Hiroshima shaped his views on morality in war.',
      'He taught at Harvard from 1962 to 1991, and many leading philosophers were among his students.',
      'He received the National Humanities Medal in 1999 and the Schock Prize in Logic and Philosophy the same year.',
      'His later book The Law of Peoples (1999) extended his thinking to relations among societies.',
    ],
    myths: [
      { myth: 'The veil of ignorance is a claim that people really are equal or identical.', reality: 'It is a device for reasoning fairly. It removes knowledge of personal advantage so that the principles chosen are not biased, but it does not say that people have no differences.' },
      { myth: 'Rawls simply wanted to redistribute wealth equally.', reality: 'The difference principle allows inequalities that raise the position of the worst-off. His two principles also protect liberties that cannot be traded for economic gains.' },
      { myth: 'Rawls’s critics showed that his theory failed.', reality: 'Critics raised serious objections, and the debates shaped later political philosophy. Robert Nozick argued, in Anarchy, State, and Utopia (1974), that redistribution violates individual rights. Michael Sandel argued, in Liberalism and the Limits of Justice (1982), that Rawls pictured people as separate from their communities and attachments. Marxist critics said the theory neglects the structure of capitalism and class power, and feminist critics such as Susan Moller Okin argued, in Justice, Gender, and the Family (1989), that he did not apply his principles to the family. Rawls partly replied in his later writings, and the arguments continue.' },
    ],
    works: [
      { title: 'A Theory of Justice (1971, revised 1999)', note: 'His major book, setting out justice as fairness.' },
      { title: 'Political Liberalism (1993)', note: 'Reworks the theory for societies with many conflicting beliefs.' },
      { title: 'The Law of Peoples (1999)', note: 'Principles for international relations, with the essay “The Idea of Public Reason Revisited”.' },
      { title: 'Justice as Fairness: A Restatement (2001)', note: 'A compact late summary of his thought.' },
      { title: 'Lectures on the History of Moral Philosophy (2000) and on the History of Political Philosophy (2007)', note: 'Based on his Harvard courses. The second volume appeared after his death.' },
    ],
    legacy: [
      'Rawls revived political philosophy in the English-speaking world and set its agenda for decades. Even those who reject his conclusions, such as libertarians, communitarians, Marxists and feminists, often define their positions in relation to his. Terms such as “veil of ignorance” and “the least advantaged” have entered public debate about taxes, health care, education and global justice.',
      'His work also influenced law and economics, where it prompted work on fairness, risk and inequality, and later debates about justice across generations and among nations. The ongoing disagreements are part of his legacy: he showed that careful argument about how a free society should treat its members is possible and worthwhile.',
    ],
  },
  {
    slug: 'michel-foucault',
    order: 1926,
    dates: '1926 – 1984',
    place: 'Poitiers and Paris, France',
    era: '20th Century',
    tradition: 'Post-structuralism',
    tagline: 'A historian of ideas who showed how prisons, clinics and schools shape the way we think, and who asked how we came to be the kind of people we are.',
    who: [
      'Michel Foucault was born Paul-Michel Foucault on 15 October 1926 in Poitiers, France, into a comfortable family; his father was a surgeon. He studied at the École Normale Supérieure in Paris, where Jean Hyppolite and Louis Althusser were among his teachers, and took degrees in philosophy and psychology. He briefly belonged to the Communist Party in the early 1950s. He then spent years abroad as a teacher and cultural attaché in Sweden, Poland and West Germany, and taught at Clermont-Ferrand and in Tunisia.',
      'His first major book, History of Madness (1961), was followed by The Birth of the Clinic (1963) and The Order of Things (1966), which was a surprise bestseller. In 1969, he was elected to the Collège de France, to a chair he named the history of systems of thought, and held it until his death. His annual lecture courses there were major intellectual events. He also became active politically: in 1971 he helped found the Prisons Information Group, which gave prisoners a voice in public debate.',
      'Discipline and Punish appeared in 1975 and the first volume of The History of Sexuality in 1976. After a long pause, the second and third volumes, on the ancient Greeks and Romans, were published in 1984, the year he died. He died in Paris on 25 June 1984 of complications from AIDS, one of the first prominent French public figures to do so. A fourth volume, on early Christianity, was published only in 2018, from a manuscript he had left.',
    ],
    context: [
      'Foucault studied in post-war France, when existentialism, Marxism and phenomenology dominated, and he was trained to reason in terms of the human subject and of history as progress. He grew sceptical of both. He was often grouped with the structuralists, who studied the hidden structures behind language and culture, but he rejected the label. He was later called a post-structuralist, which he also did not much like.',
      'His own era shaped his questions. In the late 1960s and 1970s, French students and workers challenged universities, prisons, asylums and the family. Foucault’s histories of how modern institutions arose spoke to this moment. He asked not whether these institutions were good, but how they came to define what counts as normal, sane or criminal.',
    ],
    ideas: [
      { title: 'Archaeology and genealogy', text: 'In his early work, Foucault called his method archaeology: examining the rules that, in a given period, decide what can count as true or meaningful in fields such as medicine or the study of language. Later, he called his approach genealogy, taken from Nietzsche, which traces how present-day practices and ideas arose from contingent struggles, not from a single inevitable progress. The aim is to show that things we take for granted have a history and might have been different.' },
      { title: 'Power/knowledge', text: 'Foucault argued that power and knowledge are bound up with one another. Fields like psychiatry, criminology and medicine do not just discover facts about people, but also create categories and ways of observing that make people governable. In turn, power depends on knowledge to operate. He did not claim that all knowledge is merely power or that nothing is true. His claim is that what counts as knowledge in a field is bound up with practices of control and examination, which can be studied.' },
      { title: 'Disciplinary power', text: 'In Discipline and Punish, Foucault traced a shift from public torture, which opens the book with the execution of Damiens in 1757, to prison, schools, barracks and factories that train people through timetables, observation and examination. This disciplinary power works by making individuals visible and by encouraging them to monitor and correct themselves. As an image he used the Panopticon, a prison design by Jeremy Bentham in which a central watchtower can see every cell, so that prisoners never know when they are watched.' },
      { title: 'Biopower and the history of sexuality', text: 'In the first volume of The History of Sexuality, he challenged the story that modern society simply repressed sex. He argued that, from the seventeenth century onward, there was a flood of talk about sexuality, and that medicine, psychiatry and the state used it to manage the health and behaviour of whole populations, a form of power over life that he called biopower. He also argued that “the homosexual” as a type of person is a modern category.' },
      { title: 'Care of the self', text: 'In his last works, Foucault studied how ancient Greeks and Romans shaped themselves through exercises and habits of living, and he turned to ethics. He was interested in how people can give a form to their own lives, and in what freedom within a given set of constraints could mean. He insisted that where there is power there are possibilities of resistance.' },
    ],
    principles: [
      'Ask how things we treat as natural came to be, and who gained from them.',
      'Pay attention to the small, everyday practices through which people are sorted and managed.',
      'Do not assume that knowledge is neutral: look at the categories it uses.',
      'Where there is power, there is the possibility of resistance.',
      'Treat your own life as something you can work on and shape.',
    ],
    practice: [
      'Choose a category you use without thinking, such as “normal”, “productive” or “qualified”, and find out when and why it came into use.',
      'Notice where you are being measured or observed, for example by grades, ratings or metrics, and how it changes your behaviour.',
      'Choose a small daily habit that shapes who you are and deliberately practise it, as the ancient writers recommended.',
    ],
    facts: [
      'Discipline and Punish begins with a graphic account of the execution of Robert-François Damiens in 1757, then compares it with a prison timetable from the 1830s.',
      'Foucault rejected the labels of structuralist and, often, of philosopher, calling himself a historian of systems of thought.',
      'In 1971 he debated Noam Chomsky on Dutch television about human nature and power.',
      'He travelled to Iran in 1978 and wrote reports for the Italian newspaper Corriere della Sera on the revolution.',
      'His partner for many years, Daniel Defert, later founded the AIDS charity AIDES in his memory.',
      'The fourth volume of The History of Sexuality, Confessions of the Flesh, was published posthumously in 2018.',
    ],
    myths: [
      { myth: 'Foucault said that everything is power and nothing is true.', reality: 'He studied how claims to truth are produced and used, which is different from denying that anything is true. Thinkers such as Jürgen Habermas have argued that his approach leaves him without a clear basis for his own criticisms, and that is a different charge from the caricature.' },
      { myth: 'His writings on Iran were an endorsement of the Khomeini regime.', reality: 'In articles from 1978, he wrote with sympathy about the uprising against the Shah and about what he called a “political spirituality”. After the revolution turned authoritarian, he was widely criticised, including by Iranian and French writers, for naivety about what was coming. He answered some of his critics in 1979, and scholars still debate how far he approved of the Islamic government and how far he was describing a movement he found significant.' },
      { myth: 'The accusations that surfaced after his death have been proven, or else have been disproven.', reality: 'Neither is the case. In 1977 he signed an open letter, published in Le Monde, defending three men in a case involving minors and calling for a revision of French law on sexual relations between adults and minors, and this is documented and often cited in criticism of him. In 2021 the writer Guy Sorman said publicly that he had seen Foucault pay boys for sex in Tunisia in the late 1960s. Sorman’s account rests on his own recollection and was challenged over details such as dates, and he later qualified it. There has been no investigation or legal finding, and Foucault is no longer here to respond. Scholars and commentators disagree about what follows for the reading of his work.' },
    ],
    works: [
      { title: 'History of Madness (1961)', note: 'A history of how Europe came to treat madness as a medical matter to be confined.' },
      { title: 'The Order of Things (1966)', note: 'A study of how the human sciences arose and of how thought is organised in each period.' },
      { title: 'Discipline and Punish (1975)', note: 'His study of prisons and disciplinary power.' },
      { title: 'The History of Sexuality, vol. 1 (1976)', note: 'Challenges the “repressive hypothesis” and introduces biopower.' },
      { title: 'The Use of Pleasure and The Care of the Self (1984)', note: 'The second and third volumes, on ancient Greek and Roman ethics.' },
    ],
    legacy: [
      'Few thinkers of the twentieth century have been cited as often. His ideas have been taken up in sociology, history, criminology, education, medicine, literary studies and gender and queer studies, where his account of sexuality as a historical construct was especially influential. The Panopticon has become a common metaphor in discussions of surveillance in the digital age.',
      'He has also been criticised from several sides. Some historians say his accounts are too sweeping and that he simplified the evidence. Others, such as Habermas and the feminist philosopher Nancy Fraser, argued that his view of power leaves no clear basis for saying what is wrong with domination. These debates, along with the discussion of his personal conduct and of his political judgements, keep his work contested, and they make a careful, balanced reading all the more important.',
    ],
  },
]
